### ISSUE TITLE
Unspecified NullReferenceException

### ISSUE THREAD

**Issue by Dimonasdf** [anegostudios/VintageStory-Issues#1003]
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.15.0-pre.3 (Unstable)14.06.2021 1:59:36: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.CollectibleObject.<>c__DisplayClass70_0.<RefillSlotIfEmpty>b__0(ItemSlot invslot)
   at Vintagestory.API.Common.EntityPlayer.WalkInventory(OnInventorySlot handler)
   at Vintagestory.API.Common.CollectibleObject.DamageItem(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, Int32 amount)
   at Vintagestory.GameContent.ItemSpear.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _kG3l18Uo58XQnaOroOTVL156lmd._xkDAOmiQFj0Igekk6xBOkfLlbV2(Single )
   at _myXzIvBGuHgNhKsWypGDvkNbw4X._PeuIqQzFn7JdsiaCMO1A0nOHYOF(Single )
   at _myXzIvBGuHgNhKsWypGDvkNbw4X._12elMOUbssfuqzUtVoRc599RYNW(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _UwTpwIUKuzIrz4lc7aDEDr1w32f._ouD1c39oCQ2Eda0lkC3EXYeZtC7(_OdfjAwaG2wGU12XuYVt4myQv5bF , String[] )
   at _j9Ke4RlHC2L45ChATqqx7RI91CC._ouD1c39oCQ2Eda0lkC3EXYeZtC7(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 14.06.2021 0:46:18, Site = , Source = Windows Error Reporting, Message = Fault bucket 1259147309639579605, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\dimon\AppData\Local\Temp\RDR6ACE.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6ADF.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6AE0.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6AED.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6B0D.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: d969d94b-9227-4564-8f41-408434cc90cc
Report Status: 268435456
Hashed bucket: c9b9d3809ce1ec04417963ce8ef4b7d5
Cab Guid: 0 }
--------------
{ TimeGenerated = 02.01.2021 23:58:30, Site = , Source = Windows Error Reporting, Message = Fault bucket 1980881414847429928, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.2.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\dimon\AppData\Local\Temp\RDR80FC.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER810C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER810D.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER812A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER814B.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 45556499-ddbe-4207-93b2-52be952eca61
Report Status: 268435456
Hashed bucket: 596fb7afe407e19bbb7d8126d2277d28
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment]
Duplicate of #944

**Comment by Dimonasdf** [comment]
Affirmative. I was throwing a spear.
First time I had random stuff in inventory, second time, when this happened again, - nothing but 5 spears. The first was almost broken, other 4 new.
