### ISSUE TITLE
Anvil Smithing Index Out of Bounds CTD

### ISSUE THREAD

**Issue by Lemon-B-Citrom** [anegostudios/VintageStory-Issues#1018]
**Game Version:** 1.14.10
**Platform:** Windows
**Modded:** Yes

### Description
Shifting voxels when smithing an anvil leads to an index out of bounds error.

### How to reproduce
1. Start smithing an iron anvil
2. Form it into the following shape
![2021-06-17_16-47-16](https://user-images.githubusercontent.com/53537994/122470290-dd970d80-cf8b-11eb-8c9c-d2934e2852de.png)
3. Try to move the voxel highlighted by the cursor to the left
4. CTD

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.10 (Stable)6/17/2021 4:36:58 PM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockEntityAnvil.OnUpset(Vec3i voxelPos, BlockFacing towardsFace)
   at Vintagestory.GameContent.BlockEntityAnvil.OnUseOver(IPlayer byPlayer, Vec3i voxelPos, BlockSelection blockSel)
   at Vintagestory.GameContent.ItemHammer.OnHeldAttackStop(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _vKnDSS3ZW5fZhqcIJSzL9xbAUttA._mhcyOBzdAWALla9FVcjc15WACGi(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._3HP2xkrryy8Ktr1q1yqHHv9s1kb(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._JbXJA0SA6LQOS6diuqtXAjMb8Fo(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._ofvn0Tr1zNGCbNV3SxvKs2MXNP(_C7CLMRbe3BejVtaARYCgl7Bg1vl , String[] )
   at _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(ThreadStart )
-------------------------------
 
Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/9/2021 1:25:20 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1999085723610005733, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0
 
Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 
 
Attached files:
\\?\C:\Users\Joshua\AppData\Local\Temp\RDRAF6D.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAF8D.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAF9E.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAFD7.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB007.tmp.txt
 
These files may be available here:
 
 
Analysis symbol: 
Rechecking for solution: 0
Report Id: edefa9b5-a569-4435-a684-8038b607ac08
Report Status: 268435456
Hashed bucket: ee3def5252484136fbbe2ddfbf5440e5
Cab Guid: 0 }
```

**Comment by Lemon-B-Citrom** [comment]
It is worth noting that it is possible to *split* the problem voxel, but not move it.

**Comment by Craluminum2413** [comment]
I hope someday voxel coordinates will be added

**Comment by Craluminum2413** [comment]
Crash is the same as in #740

**Comment by Lemon-B-Citrom** [comment]
That seems correct, sorry for the duplicate.

**Comment by Craluminum2413** [comment]
It would be better if you recorded a video
