### ISSUE TITLE
Crash on Breaking Mature Wild Crop

### ISSUE THREAD

**Issue by nskjellum** [anegostudios/VintageStory-Issues#1034]
**Game Version:**  1.15.0-pre.5
**Platform:** Windows
**Modded:** ???

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.5 (Unstable)6/20/2021 2:50:01 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockCrop.OnBlockBroken(IWorldAccessor world, BlockPos pos, IPlayer byPlayer, Single dropQuantityMultiplier)
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryDestroyBlock(BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _MOdxi5vG0bna4SXTrSTDPTj4rVg._4Yd80CSETSLq3ryQSQyu0CgTVkD(Single )
   at _ZTfxbGnrfFIByyznrlGTkx2vj9o._fa9CGlG0qMmF2Mdhb11gCvro90x(Single )
   at _ZTfxbGnrfFIByyznrlGTkx2vj9o._xGQguz838073AFF0xjLFxOuNFvd(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _d9njO8fhbi6B7GfzQuHDVcoAyY6._3LaTwazRKZVPcHgOIFRHUTG6ZpD(_4lAn4F3kZqtcY1FLfNdzOm0cnKI , String[] )
   at _QyjwcZJgpstl1btBhzlpbS2YOg0._3LaTwazRKZVPcHgOIFRHUTG6ZpD(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/15/2021 7:03:46 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1617108784218071861, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\nskje\AppData\Local\Temp\RDR2915.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2916.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2927.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2948.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2987.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: cd0713e3-4fb7-467a-ab9c-83ed21329823
Report Status: 268435456
Hashed bucket: 53ec02d71894ee5b26711fdf167b6335
Cab Guid: 0 }
--------------
{ TimeGenerated = 3/18/2021 1:10:24 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1564561481470198046, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\nskje\AppData\Local\Temp\RDR3EEC.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3EFD.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3F0E.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3F07.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3F57.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: ca204dab-6092-41c8-80dc-a675879e27b6
Report Status: 268435456
Hashed bucket: 2422f0d2706eedebe5b67060c44a411e
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment]
Fixed in 1.15.0-pre.6
> Fixed: Game crashing when trying to harvest a wild crop
