### ISSUE TITLE
v1.15.0-pre.5 Crash upon breaking acadia tree with flint axe

### ISSUE THREAD

**Issue by Saphkey** [anegostudios/VintageStory-Issues#1038]
**Game Version:** v1.15.0-pre.5
**Platform:** Windows
**Modded:** No

### Description
Game crashed to desktop after breaking Acadia tree with flint axe.

### How to reproduce
Break acadia tree with flint axe

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.5 (Unstable)20/06/2021 21:16:19: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Datastructures.JsonObject.ToString()
   at Vintagestory.API.Common.CollectibleObject.DamageItem(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, Int32 amount)
   at Vintagestory.GameContent.ItemAxe.OnBlockBrokenWith(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, BlockSelection blockSel, Single dropQuantityMultiplier)
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryDestroyBlock(BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _MOdxi5vG0bna4SXTrSTDPTj4rVg._4Yd80CSETSLq3ryQSQyu0CgTVkD(Single )
   at _ZTfxbGnrfFIByyznrlGTkx2vj9o._fa9CGlG0qMmF2Mdhb11gCvro90x(Single )
   at _ZTfxbGnrfFIByyznrlGTkx2vj9o._xGQguz838073AFF0xjLFxOuNFvd(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _d9njO8fhbi6B7GfzQuHDVcoAyY6._3LaTwazRKZVPcHgOIFRHUTG6ZpD(_4lAn4F3kZqtcY1FLfNdzOm0cnKI , String[] )
   at _QyjwcZJgpstl1btBhzlpbS2YOg0._3LaTwazRKZVPcHgOIFRHUTG6ZpD(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 20/06/2021 20:48:03, Site = , Source = Windows Error Reporting, Message = Fault bucket 1252239485250825062, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 10.0.19042.2.0.0

Analysis symbol: 
Rechecking for solution: 0
Report Id: 40de6405-a160-4b67-b226-61e0204109d0
Report Status: 268435456
Hashed bucket: 9a6d16c7ad62a31db160d92d5c17eb66
Cab Guid: 0 }
--------------
{ TimeGenerated = 21/05/2021 07:45:23, Site = , Source = Windows Error Reporting, Message = Fault bucket 1999085723610005733, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19042.2.0.0

Analysis symbol: 
Rechecking for solution: 0
Report Id: 04c8865b-d022-4d97-b5c5-7d121c47eb24
Report Status: 268435456
Hashed bucket: ee3def5252484136fbbe2ddfbf5440e5
Cab Guid: 0 }

```

**Comment by Craluminum2413** [comment]
Could you send a seed with coordinates of that acacia tree?

**Comment by Saphkey** [comment]
> 
> 
> Could you send a seed with coordinates of that acacia tree?

tree at -1640 112 -2042

seed: 342234021
created with version 1.15.0-pre.3

playstyle(copy-paste):
{
  "worldClimate": "realistic",
  "gameMode": "survival",
  "temporalStability": true,
  "temporalStorms": "off",
  "graceTimer": "0",
  "microblockChiseling": "all",
  "polarEquatorDistance": "25000",
  "harshWinters": "true",
  "daysPerMonth": "9",
  "saplingGrowthRate": "3",
  "allowUndergroundFarming": false,
  "worldWidth": "1024000",
  "worldLength": "1024000",
  "worldEdge": "traversable",
  "startingClimate": "hot",
  "seasons": "enabled",
  "snowAccum": "true",
  "bodyTemperatureResistance": "10",
  "globalTemperature": "1.5",
  "globalPrecipitation": "1",
  "globalForestation": "0",
  "deathPunishment": "drop",
  "spawnRadius": "5000",
  "creatureHostility": "aggressive",
  "creatureStrength": "1.5",
  "playerHealthPoints": "10",
  "playerHungerSpeed": "1.25",
  "playerMoveSpeed": "1.5",
  "blockGravity": "sandgravelsoil",
  "foodSpoilSpeed": "1.25",
  "toolDurability": "1",
  "toolMiningSpeed": "1",
  "propickNodeSearchRadius": "8",
  "surfaceCopperDeposits": "0.05",
  "surfaceTinDeposits": "0",
  "globalDepositSpawnRate": "1",
  "tempstormDurationMul": "1",
  "allowCoordinateHud": false,
  "allowMap": false,
  "allowLandClaiming": false,
  "playstyle": "surviveandbuild"
}

**Comment by copygirl** [comment]
Closing this as duplicate, but please keep sharing leads on how to reproduce in #1037.
