### ISSUE TITLE
IndexOutOfRangeException in BlockMeal.SetContents

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1055]
**Game Version:** 1.15 pre 6
**Platform:** Windows
**Modded:** No

### Description
https://discord.com/channels/302152934249070593/334233095374897152/857695005748756520

### Logs
```
`Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.6 (Unstable)24/06/2021 19:53:15: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockMeal.SetContents(String recipeCode, ItemStack containerStack, ItemStack[] stacks, Single quantityServings)
   at Vintagestory.GameContent.BlockMeal.OnPickBlock(IWorldAccessor world, BlockPos pos)
   at Vintagestory.API.Common.Block.GetPlacedBlockName(IWorldAccessor world, BlockPos pos)
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.ComposeBlockInfoHud()
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.BlockInView()
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _rAz9asRtsMLxfsCCB2XddnUXyVD._lAuq80fCjazcKzbZHEKoGYIQZnl(Single )
   at _cH8DEtB83Wb5hFfMgWQO9WIYZC9._KsHdcIdO5DGEA40eebPVxTFjf0X(Single )
   at _cH8DEtB83Wb5hFfMgWQO9WIYZC9._9YOWJUIA8puJX6CgeGDq2kbUmjCb(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _Bm4NBvFGhkYYb6kZRXCyCXFHRob._0ZviBJOkkLsgH2nWPiNX4k45MmO(_WXS5zDsN00P20IS9kaePFXF9aGe , String[] )
   at _oFmKxmdL6yMMXIdkAAa9Rh1eAhj._0ZviBJOkkLsgH2nWPiNX4k45MmO(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 20/06/2021 12:55:00, Site = , Source = Windows Error Reporting, Message = Fault bucket 1259147309639579605, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Lee\AppData\Local\Temp\RDRC228.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC239.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC269.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC27B.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC2AA.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: f17f54d4-a407-49a2-ab89-678325f486ee
Report Status: 268435456
Hashed bucket: c9b9d3809ce1ec04417963ce8ef4b7d5
Cab Guid: 0 }
--------------
{ TimeGenerated = 25/03/2021 13:15:53, Site = , Source = Windows Error Reporting, Message = Fault bucket 1564561481470198046, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Lee\AppData\Local\Temp\RDREE4C.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREE4D.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREE6E.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREE85.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREEB5.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: b8b09ed8-8d3f-4fcd-8b84-4a32d7557380
Report Status: 268435456
Hashed bucket: 2422f0d2706eedebe5b67060c44a411e
Cab Guid: 0 }
--------------
{ TimeGenerated = 14/11/2020 16:38:44, Site = , Source = Windows Error Reporting, Message = Fault bucket 1384382890082581158, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.0.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Lee\AppData\Local\Temp\RDR142E.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER143F.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1450.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER147C.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER149D.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 15d827c9-cca6-4fd8-8141-556d19ec655f
Report Status: 268435456
Hashed bucket: 2ac03a417f2ed74c733650e75c803aa6
Cab Guid: 0 }`
```

**Comment by tyronx** [comment]
This report is incomplete, I need to know when/how this happened

**Comment by sirStroam** [comment]
Closed for being incomplete
