### ISSUE TITLE
Crash on ladder placement

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1058]
**Game Version:** 1.15 pre 6
**Platform:** Windows 
**Modded:** No

### Description
Placed ladder while floating in creative mode

### How to reproduce
1. go into creative
2. fly
3. place ladder with stack of 35

### Logs
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.15.0-pre.4 (Unstable)6/25/2021 12:55:15 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockBehaviorLadder.HasSupport(Block forBlock, IBlockAccessor blockAccess, BlockPos pos)
   at Vintagestory.GameContent.BlockBehaviorLadder.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, EnumHandling& handled, String& failureCode)
   at Vintagestory.API.Common.Block.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, String& failureCode)
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryPlace(BlockSelection blockSelection, String& failureCode)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnBlockBuild(BlockSelection blockSelection, Block onBlock, String& failureCode)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _nw5iq7Nu0RWJnxlBZen6mJGmcSN._MXRpcKwvmgsUnS5BPzRQ25DH3lh(Single )
   at _knXhXKQCYhvGbZXkDCncKaLldTL._BdeV9hzEfqFcm87gcxwrAtDeTgk(Single )
   at _knXhXKQCYhvGbZXkDCncKaLldTL._3JdxcXDlKfmdnBvyHIxr4AJFIze(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _SaXpqv5O911lCsSIrDnAnx1C2Wl._lESBMi7dCimysuVIyentZFkbZ2C(_3DvyrNaGS3KUgpwJWmWNJ0OhmVh , String[] )
   at _xYPi1FuSC15HmCPKeAQ55E3UGnQ._lESBMi7dCimysuVIyentZFkbZ2C(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/8/2021 11:55:42 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Sirst\AppData\Local\Temp\RDRBC88.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBC89.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBC9A.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBCBE.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBCED.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 4a231838-554c-4ecc-bb60-5459c7587166
Report Status: 536871008
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 4/14/2021 8:49:06 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1278983403590121620, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.7.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Sirst\AppData\Local\Temp\RDR9A9A.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9AAA.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9AAB.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9AD2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9B02.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 2862aaca-21f9-4717-851d-c8e51ae197b3
Report Status: 268435456
Hashed bucket: 9eea1948638d0712e1bfdca1149bf894
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment]
Duplicate of #1025

**Comment by sirStroam** [comment]
Thanks
Closing
