### ISSUE TITLE
Game crashes on clicking some ingredients in recipes

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1060]
**Game Version:** 1.15.0-pre.7
**Platform:** Windows
**Modded:** StepUp

### How to reproduce
1. Click on any ingredient (for example, `metal plate`),  which has more than two variations in a recipe of other item
2. It crashes

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.7 (Unstable)06/25/2021 14:06:07: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Client.GuiHandbookItemStackPage.PageCodeForStack(ItemStack stack)
   at Vintagestory.API.Common.CollectibleObject.<>c__DisplayClass103_0.<GetHandbookInfo>b__38(ItemStack cs)
   at Vintagestory.API.Client.SlideshowGridRecipeTextComponent.OnMouseDown(MouseEvent args)
   at Vintagestory.API.Client.GuiElementRichtext.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse)
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs)
   at Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _NfEIYGetj5nHaIEe1bMOq5qPVVe._uAPnYXwEzdCJ8CQ2oCBe9aHMUxo(_DqmInuVm7RykCDabuWwjzEo51Se , String[] )
   at _aLUPv552XTtNubHVap8iu7zzoZB._uAPnYXwEzdCJ8CQ2oCBe9aHMUxo(ThreadStart )
```

**Comment by tyronx** [comment]
thanks a bunch for the report, this is now fixed for pre.8
