### ISSUE TITLE
Game crashes on igniting BlockEntityPitKiln

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1062]
**Game Version:** 1.15.0-pre.7
**Platform:** Windows
**Modded:** No

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.7 (Unstable)06/25/2021 16:12:33: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityPitKiln.IsAreaLoaded()
   at Vintagestory.GameContent.BlockEntityPitKiln.<>c__DisplayClass14_0.<Initialize>b__2(BlockPos pos)
   at Vintagestory.GameContent.BEBehaviorBurning.canBurn(BlockPos pos)
   at Vintagestory.GameContent.BEBehaviorBurning.OnFirePlaced(BlockPos firePos, BlockPos fuelPos, String startedByPlayerUid)
   at Vintagestory.GameContent.BlockEntityPitKiln.TryIgnite(IPlayer byPlayer)
   at Vintagestory.GameContent.BlockBehaviorCanIgnite.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, EnumHandling& handling)
   at Vintagestory.API.Common.CollectibleObject.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _tWLW0byDLIhtS1wxxVHI5lzRZDE._pYOg3eHClIOT1FF5vsNdyXdGM03(Single )
   at _6pW3IzjvlkXCwvQdAjU2jMcqPPaA._7YovFWQpW8u7nZERbVYDJRoxy6p(Single )
   at _6pW3IzjvlkXCwvQdAjU2jMcqPPaA._LsdcISpmOPNjHJfC7tNPJt4urmy(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _NfEIYGetj5nHaIEe1bMOq5qPVVe._uAPnYXwEzdCJ8CQ2oCBe9aHMUxo(_DqmInuVm7RykCDabuWwjzEo51Se , String[] )
   at _aLUPv552XTtNubHVap8iu7zzoZB._uAPnYXwEzdCJ8CQ2oCBe9aHMUxo(ThreadStart )
```

**Comment by Saricane** [comment]
I can confirm. Same crash.

**Comment by tyronx** [comment]
thanks for the report, should be fixed in pre.8
