### ISSUE TITLE
Crash after sealing rot barrels and turning

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#1072]
**Game Version:** 1.15 pre8, TOPTS
**Platform:** Windows 10
**Modded:** No

### Description
Sealed multiple barrels of rot, shift-clicking rot stacks from hotbar to barrels, turned to open a chest and crashed.
Not sure what crashed exactly.

### How to reproduce
1. Put 4 stacks of rot to your hotbar
2. Seal 4 barrels of rot, shift-clicking rot there and sealing them
3. Turn to a chest to open it
4. Crash.

### Expected behavior
--

### Screenshots
--

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.8 (Unstable)26.06.2021 16:51:34: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.BlockAccessorBase.SetDecorsBulk(Int64 chunkIndex, Dictionary`2 newDecors)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _VQ30Ln02gyvoATEl8PlfeLVSgEr._B7JNvwI3nx9QEdgkJkgLg21lvde(Single )
   at _IJG2v0zGeUDfPbxVmwnXgzVbdHp._pSnRqX9ORNtB1LvHF1vzxnB3jpe(Single )
   at _IJG2v0zGeUDfPbxVmwnXgzVbdHp._g3nxKDmkyYJ7Dq7TaDsdBSLVw0A(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _yLUmmGhRYnnQv7zul2v0crZd2Tp._PwL995m4VTOZDErzGUzsRHij9rh(_rhrdlgKC766AwXQivHTdHkcGzAjb , String[] )
   at _EDKdxfQFQqcYQ64nBo1IPHJ5Kw9._PwL995m4VTOZDErzGUzsRHij9rh(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 05.06.2021 14:13:01, Site = , Source = Windows Error Reporting, Message = Fault bucket 1837167348359640725, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 6079b344
P4: mscorlib
P5: 4.8.4341.0
P6: 60230124
P7: 1694
P8: 1d8
P9: System.IO.IOException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER172B.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER19EC.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER19FC.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1A00.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1A20.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_1764dc927acd2b13639dda21195759d282faf2c_5674d60d_0fcf2832-d818-4b44-a64f-c26f9c92ab2a

Analysis symbol: 
Rechecking for solution: 0
Report Id: c7ac46fd-186b-4ebe-aaab-631ffac22dab
Report Status: 268435456
Hashed bucket: bad632bcf34946f3c97eedf837ec3695
Cab Guid: 0 }
--------------
{ TimeGenerated = 05.06.2021 14:12:59, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.14.10.0, time stamp: 0x6079b344
Faulting module name: KERNELBASE.dll, version: 10.0.18362.1474, time stamp: 0x5ae7af90
Exception code: 0xe0434352
Fault offset: 0x0000000000043b19
Faulting process id: 0x4758
Faulting application start time: 0x01d759fba6f30476
Faulting application path: D:\Games\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: c7ac46fd-186b-4ebe-aaab-631ffac22dab
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 05.06.2021 14:12:58, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode)
   at Hjg.Pngcs.FileHelper.OpenFileForWriting(System.String, Boolean)
   at Hjg.Pngcs.FileHelper.CreatePngWriter(System.String, Hjg.Pngcs.ImageInfo, Boolean)
   at Automap.Snapshotter+<Take>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
```

**Comment by Craluminum2413** [comment]
Seems like this is a multiplayer-only bug

**Comment by tyronx** [comment]
thanks, should be fixed in pre.9
