### ISSUE TITLE
crash on startup on save

### ISSUE THREAD

**Issue by Pureblood117** [anegostudios/VintageStory-Issues#1073]
**Game Version:** X.Y.Z  1.14.10 stable
**Platform:** Windows / Mac / Linux (which?) windows 10 
**Modded:** No / Yes (which?) yes

### Description
Explain the issue you're running into.
crashing on startup after unplugging harddrive from pc while in middle of game befor it was working just fine no problems
### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash here.

Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.10 (Stable)6/26/2021 4:17:05 PM: Critical error occurred
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.MemoryStream.InternalReadInt32()
   at Vintagestory.GameContent.EntityBlockFalling.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntitySpawnPacket(_qiwXoSSrnCKEl5NMyGSjHlpQcE serverpacket)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _pnnd59ZE4jC5iGjIOcyNcWxgKsR._ZHf5IMlYChPlSKBWZX1ph2DB6EP(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._3HP2xkrryy8Ktr1q1yqHHv9s1kb(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._JbXJA0SA6LQOS6diuqtXAjMb8Fo(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._ofvn0Tr1zNGCbNV3SxvKs2MXNP(_C7CLMRbe3BejVtaARYCgl7Bg1vl , String[] )
   at _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/26/2021 2:57:29 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1388753336893352706, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 0.0.0.0
P3: 6079b344
P4: clr.dll
P5: 4.8.4360.0
P6: 606e6fc7
P7: c0000005
P8: 00000000000eb75c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBDBF.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCDED.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCDFD.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCE1A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCE2B.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_a0ec34b54c3c593d5a8c6366c6ad3639856afe67_a413291d_c2cabbc2-08cc-4cbe-b993-0c67079bc0df

Analysis symbol: 
Rechecking for solution: 0
Report Id: 0d75722e-cc10-4a11-b2bc-17f7fc780246
Report Status: 268435456
Hashed bucket: 577cd9a2baeb1df98345d7cd4e2aab02
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/26/2021 2:57:23 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 0.0.0.0, time stamp: 0x6079b344
Faulting module name: clr.dll, version: 4.8.4360.0, time stamp: 0x606e6fc7
Exception code: 0xc0000005
Fault offset: 0x00000000000eb75c
Faulting process id: 0x3f80
Faulting application start time: 0x01d76a9f7042ec54
Faulting application path: E:\Games\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: 0d75722e-cc10-4a11-b2bc-17f7fc780246
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 6/26/2021 2:57:21 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFB2EBAB75C (00007FFB2EAC0000) with exit code 80131506.
 }

**Comment by copygirl** [comment]
Have you tried loading the world in repair mode? Click the pencil icon next to the world entry, then you can find a "Run in Repair Mode" button.

**Comment by Craluminum2413** [comment]
The same crash as in #511

**Comment by Pureblood117** [comment]
i tried using repair mode and nothing happens as in it goes to loading screen and says it begins it senses it remebers and stays on that screen

**Comment by Pureblood117** [comment]
nvm, it worked liked you said it just took a long time to load in and after i used repair mode i got it to work so thank you very much

**Comment by copygirl** [comment]
Alright, I'm glad!
