### ISSUE TITLE
Sneak+right click on a bucket of cottage cheese with a bowl causes crash

### ISSUE THREAD

**Issue by tuesdaey** [anegostudios/VintageStory-Issues#1076]
**Game Version:** 1.15.0-pre.8
**Platform:** Windows
**Modded:** No

### Description
Trying to get a bowl of cottage cheese from a bucket crashes to desktop.

### How to reproduce
1. Fill bucket with cottage cheese from a barrel
2. Sneak+right click on the bucket of cottage cheese with a bowl, similar to how you would honey or milk.
3. Instant crash-ola

### Expected behavior
I expected to receive a bowl of cottage cheese to snack on.

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.15.0-pre.8 (Unstable)6/26/2021 10:39:43 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.MealMeshCache.GenMealMesh(CookingRecipe forRecipe, ItemStack[] contentStacks, Vec3f foodTranslate)
   at Vintagestory.GameContent.MealMeshCache.GenMealInContainerMesh(Block containerBlock, CookingRecipe forRecipe, ItemStack[] contentStacks, Vec3f foodTranslate)
   at Vintagestory.GameContent.MealMeshCache.GetOrCreateMealInContainerMeshRef(Block containerBlock, CookingRecipe forRecipe, ItemStack[] contentStacks, Vec3f foodTranslate)
   at Vintagestory.GameContent.BlockMeal.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target)
   at Vintagestory.GameContent.EntityShapeRenderer.RenderHeldItem(Single dt, Boolean isShadowPass, Boolean right)
   at Vintagestory.GameContent.EntityShapeRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass)
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderFrameShadows(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _VQ30Ln02gyvoATEl8PlfeLVSgEr._B7JNvwI3nx9QEdgkJkgLg21lvde(Single )
   at _IJG2v0zGeUDfPbxVmwnXgzVbdHp._pSnRqX9ORNtB1LvHF1vzxnB3jpe(Single )
   at _IJG2v0zGeUDfPbxVmwnXgzVbdHp._g3nxKDmkyYJ7Dq7TaDsdBSLVw0A(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _yLUmmGhRYnnQv7zul2v0crZd2Tp._PwL995m4VTOZDErzGUzsRHij9rh(_rhrdlgKC766AwXQivHTdHkcGzAjb , String[] )
   at _EDKdxfQFQqcYQ64nBo1IPHJ5Kw9._PwL995m4VTOZDErzGUzsRHij9rh(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/26/2021 10:39:48 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.15.0.0, time stamp: 0x60d703e5
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1023, time stamp: 0x924f9cdb
Exception code: 0xc000041d
Fault offset: 0x0000000000034b89
Faulting process id: 0x68c
Faulting application start time: 0x01d76b042a679d64
Faulting application path: C:\Users\Tuesday\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 9bbf5591-a97f-47c1-be79-7e3a85a30a3e
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 6/26/2021 10:39:47 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2179765533503538416, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 60d703e5
P4: KERNELBASE.dll
P5: 10.0.19041.1023
P6: 924f9cdb
P7: c0020001
P8: 0000000000034b89
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6613.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6A99.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6AA9.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6AB7.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6AE7.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_2d5bbc4aa895cb56d94d5f822c89b09c41ad_29e9bed6_d8dac1bc-1e8b-4948-aa2d-0f21c43cecb8

Analysis symbol: 
Rechecking for solution: 0
Report Id: 53799aa3-980e-4b6d-87a0-8b12a614b8da
Report Status: 268435456
Hashed bucket: b87c077b52629abe5e4015342e1e44f0
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/26/2021 10:39:45 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.15.0.0, time stamp: 0x60d703e5
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1023, time stamp: 0x924f9cdb
Exception code: 0xc0020001
Fault offset: 0x0000000000034b89
Faulting process id: 0x68c
Faulting application start time: 0x01d76b042a679d64
Faulting application path: C:\Users\Tuesday\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 53799aa3-980e-4b6d-87a0-8b12a614b8da
Faulting package full name: 
Faulting package-relative application ID:  }
```

**Comment by tyronx** [comment]
thanks for the report, this will be fixed in pre.10
