### ISSUE TITLE
Often unable to login to TOPTS

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#1089]
**Game Version:** 1.15 pre 11
**Platform:** Windows 10
**Modded:** No

### Description
Since TOPTS was updated to 1.15 I keep getting these errors and failing to login to it from time to time.
Sometimes it takes 3 attempts to login succesfully, sometimes 2.
It does not seem to depend of the number of players, maybe just slightly.
Just now there was only one person playing, and I got this error 2 times of 3 attempts.
Attached both screenshot and client-main.txt section.

### How to reproduce
1. Click on TOPTS in server list to join it
2. Often fail to connect with this error
3. It crashes / doesn't do the thing.

### Expected behavior
--

### Screenshots
![Vintagestory Screenshot 2021 07 01 - 15 12 53 45](https://user-images.githubusercontent.com/25122345/124122567-e6eda300-da7e-11eb-848e-419245ea0327.png)

### Logs
```
1.7.2021 15:10:03 [Notification] Exiting current game to main menu
1.7.2021 15:10:20 [Error] Found closing tag char > but no tag was opened at 83. Use &gt;/&lt; if you want to display them as plain characters. See debug log for full text.
1.7.2021 15:10:20 [Warning] Could not initiate connection: DnsClient.DnsResponseException: Query 5834 => _vintagestory._tcp.gameserver.vintagestory.at IN SRV on 192.168.0.11:53 timed out or is a transient error. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at DnsClient.DnsUdpMessageHandler.Query(IPEndPoint server, DnsRequestMessage request, TimeSpan timeout)
   at DnsClient.LookupClient.ResolveQuery(IReadOnlyList`1 servers, DnsQuerySettings settings, DnsMessageHandler handler, DnsRequestMessage request, LookupClientAudit audit)
   --- End of inner exception stack trace ---
   at DnsClient.LookupClient.ResolveQuery(IReadOnlyList`1 servers, DnsQuerySettings settings, DnsMessageHandler handler, DnsRequestMessage request, LookupClientAudit audit)
   at DnsClient.LookupClient.QueryInternal(DnsQuestion question, DnsQuerySettings queryOptions, IReadOnlyCollection`1 servers)
   at _KoKrtbkwFwLHju8zwSvmbOThoTf._1VN4xuLqLNTg66rqdyoE9B4uh5K(String )
   at _xBjTSmqiAKdn4RNARVdjDiSqgBg._KjnRbkrUWFp0rAaYlgqP1svrwJF(String , String )
1.7.2021 15:10:29 [Notification] Exiting game now. Server running=False. Exit reason: Main screen quit button was pressed```

**Comment by tyronx** [comment]
hm. Odd. Your nameserver seems to be slow in looking up SRV records. I can add exception handling to just ignore the SRV record and try connecting to the default port.

**Comment by Heptagon-ru** [comment]
I don't understand much :D My DNS server is slow? Iirc my DNS server is a local provider server, maybe it is malfunctioning a bit?

**Comment by Heptagon-ru** [comment]
Since rc1 I don't seem to have this issue, no single issue after 6 logins. Either my DNS server was fixed, or something else. I guess ticket can be closed for now.

**Comment by tyronx** [comment]
You can check the client-main.txt log file if you are curious. It will log an error if the SRV record lookup timed out.

**Comment by Heptagon-ru** [comment]
Haha, yeah, still has it it seem.
```
13.7.2021 11:26:14 [Notification] Will search the following paths for mods:
13.7.2021 11:26:14 [Notification]     D:\Games\Vintagestory\Mods
13.7.2021 11:26:14 [Notification]     C:\Users\Валерий\AppData\Roaming\VintagestoryData\Mods
13.7.2021 11:26:31 [Error] Exception thrown during SRV record lookup on gameserver.vintagestory.at. Will ignore SRV record. Exception: DnsClient.DnsResponseException: Query 32355 => _vintagestory._tcp.gameserver.vintagestory.at IN SRV on 192.168.0.11:53 timed out or is a transient error. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at DnsClient.DnsUdpMessageHandler.Query(IPEndPoint server, DnsRequestMessage request, TimeSpan timeout)
   at DnsClient.LookupClient.ResolveQuery(IReadOnlyList`1 servers, DnsQuerySettings settings, DnsMessageHandler handler, DnsRequestMessage request, LookupClientAudit audit)
   --- End of inner exception stack trace ---
   at DnsClient.LookupClient.ResolveQuery(IReadOnlyList`1 servers, DnsQuerySettings settings, DnsMessageHandler handler, DnsRequestMessage request, LookupClientAudit audit)
   at DnsClient.LookupClient.QueryInternal(DnsQuestion question, DnsQuerySettings queryOptions, IReadOnlyCollection`1 servers)
   at _ol5IahZRi6ECifuvI7cSeInDD0I._oSZJsbhBWKPPxyz4zqoGoUMDSoT(String )
13.7.2021 11:26:32 [Notification] Initialized GUI Manager
```
