### ISSUE TITLE
Obsidian Knapping Crash

### ISSUE THREAD

**Issue by Stooc20** [anegostudios/VintageStory-Issues#1138]
Obsidian placed on ground but tried opening the knapping menu with basalt stone. When this did not work tried using obsidian to open knapping menu; this worked. After selecting shovel head the game crashed. No mods loaded.

"The following exception was thrown, please copy and paste this into the bug report:"

```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.14.10 (Stable)11/07/2021 14:55:48: Critical error occurred
System.InvalidOperationException: Tried to remove mesh that does not exist. This shouldn't happen
   at Vintagestory.API.Client.MeshDataPool.RemoveLocation(ModelDataPoolLocation location)
   at Vintagestory.Client.NoObf.SystemRenderDecals.OnBlockChanged(BlockPos pos, Block oldBlock)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockChanged(ClientMain game, BlockPos pos, Block oldBlock)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(_qiwXoSSrnCKEl5NMyGSjHlpQcE packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _vKnDSS3ZW5fZhqcIJSzL9xbAUttA._mhcyOBzdAWALla9FVcjc15WACGi(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._3HP2xkrryy8Ktr1q1yqHHv9s1kb(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._JbXJA0SA6LQOS6diuqtXAjMb8Fo(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._ofvn0Tr1zNGCbNV3SxvKs2MXNP(_C7CLMRbe3BejVtaARYCgl7Bg1vl , String[] )
   at _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(ThreadStart )
-------------------------------
```

**Comment by Craluminum2413** [comment]
Can't reproduce in 1.15.0-rc.2

https://user-images.githubusercontent.com/69315569/125198530-e4ebc700-e26a-11eb-9e42-56d9fda6b4a2.mp4

**Comment by copygirl** [comment]
Is this even reproducible in 1.14.10? I would be curious if there was any additional exception thrown and logged into `client-main.txt` or so.

**Comment by sirStroam** [comment]
Can't reproduce this in 1.15 rc 2. Wait for stable release.
