### ISSUE TITLE
Crash when trying to create or load a world in 1.15.0-rc.2

### ISSUE THREAD

**Issue by Fi1thyCasual** [anegostudios/VintageStory-Issues#1141]
**Game Version:** 1.15.0-rc.2 (Unstable)  
**Platform:** Windows
**Modded:** No 

### Description
This crash appears whenever I attempt to create a new world or open an existing one.

### How to reproduce
1. Open the game
2. Make or open a new world
3. Go through world loading screen
4. Crash

### Expected behavior
I expected a world to generate

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-rc.2 (Unstable)7/11/2021 8:24:03 PM: Critical error occurred
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.CollectibleObject.Attributes'.
   at medievalexpansion.src.block.mechanical.WaterWheel.<>c.<OnLoaded>b__4_1(CollectibleObject x)
   at System.Collections.Generic.List`1.FindAll(Predicate`1 match)
   at medievalexpansion.src.block.mechanical.WaterWheel.<>c__DisplayClass4_1.<OnLoaded>b__0()
   at Vintagestory.API.Util.ObjectCacheUtil.GetOrCreate[T](ICoreAPI api, String key, CreateCachableObjectDelegate`1 onRequireCreate)
   at medievalexpansion.src.block.mechanical.WaterWheel.OnLoaded(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientMain.OnServerBlocksItemsReceivedStep5(Action onCompleted)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _G8mwODDA1AsxwX2i4FhqI89RG8q._uhfxS2TdR49jQLYiobD3W6vbSqA(Single )
   at _TCvfZRHOSTvvIGLFUBoTr70UaIB._aN1SqkxDPvAUoiRD2Zzh6ho2GXb(Single )
   at _TCvfZRHOSTvvIGLFUBoTr70UaIB._fHCxxoIlSqbT6h4EgNktyNt2m9d(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _lQfc4qK0H0CxXxZeh5z4bde6UoS._RKyCnMSkLS8JAfO4ZbshWWWSELg(_amCdeQmOWwCsyohZxvSdF6gCT2W , String[] )
   at _GxxfHWxIWwVb1Y9wUYSrP1oCoUX._RKyCnMSkLS8JAfO4ZbshWWWSELg(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/14/2021 10:21:21 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1999085723610005733, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Yuuko\AppData\Local\Temp\RDR75E8.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7608.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7629.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER76D2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7712.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 6329d8bb-6b28-4fd5-bc40-7e7bc3d98ed9
Report Status: 268435456
Hashed bucket: ee3def5252484136fbbe2ddfbf5440e5
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment]
Why did you write that you don't use any mods if you used mods?? The mod that cause this is `Temporal Engineering` or `Medieval Expansion`

**Comment by sirStroam** [comment]
Cause by mod. Closing

**Comment by copygirl** [comment]
Please report this to Rhonen, the author of the [Medieval Expansion](https://www.vintagestory.at/forums/topic/2014-medieval-expansion/) mod.

**Comment by Gaara23** [comment]
I ca actually confirm the same issue as well. Though mine IS without mods enabled.

> Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-rc.2 (Unstable)7/13/2021 4:20:22 AM: Critical error occurred
System.TypeLoadException: Could not load type 'Vintagestory.API.JsonObject' from assembly 'VintagestoryAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at XLib.XEffects.CollectibleObjectPatch.Postfix(CollectibleObject __instance, StringBuilder dsc, IWorldAccessor world)
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo_Patch1(CollectibleObject this, ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.API.Common.Block.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.Common.CreativeTab.CreateSearchCache(IWorldAccessor world)
   at Vintagestory.Common.CreativeTabs.CreateSearchCache(IWorldAccessor world)
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.GuiManager.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.ClientMain.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(_3snKkbAajSfPpzHjSXHuMtXvfrE packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _G8mwODDA1AsxwX2i4FhqI89RG8q._uhfxS2TdR49jQLYiobD3W6vbSqA(Single )
   at _TCvfZRHOSTvvIGLFUBoTr70UaIB._aN1SqkxDPvAUoiRD2Zzh6ho2GXb(Single )
   at _TCvfZRHOSTvvIGLFUBoTr70UaIB._fHCxxoIlSqbT6h4EgNktyNt2m9d(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _lQfc4qK0H0CxXxZeh5z4bde6UoS._RKyCnMSkLS8JAfO4ZbshWWWSELg(_amCdeQmOWwCsyohZxvSdF6gCT2W , String[] )
   at _GxxfHWxIWwVb1Y9wUYSrP1oCoUX._RKyCnMSkLS8JAfO4ZbshWWWSELg(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/6/2021 4:37:34 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1259147309639579605, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\heath\AppData\Local\Temp\RDR46E5.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4763.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4783.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4791.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER47B1.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: e918fdbb-d2bb-4924-8aba-d90b95ac1712
Report Status: 268435456
Hashed bucket: c9b9d3809ce1ec04417963ce8ef4b7d5
Cab Guid: 0 }
--------------
{ TimeGenerated = 4/14/2021 5:25:06 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1564561481470198046, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\heath\AppData\Local\Temp\RDR6397.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6406.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6416.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6421.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6441.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 662acc54-4ae4-4c79-966c-00348c415f6d
Report Status: 268435456
Hashed bucket: 2422f0d2706eedebe5b67060c44a411e
Cab Guid: 0 }
--------------
{ TimeGenerated = 2/27/2021 6:33:46 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1529028199541149696, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 6033ac5b
P4: KERNELBASE.dll
P5: 10.0.19041.804
P6: 0e9c5eae
P7: c0020001
P8: 000000000002d759
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8CE3.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8E9A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8EBA.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8EC7.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8EE8.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_bf55e48fe32baedf65e5ded46bf42dcc9fbaae_4fd6768e_c298afbe-561a-44d1-8895-b8b09373607f

Analysis symbol: 
Rechecking for solution: 0
Report Id: 1b85ddec-afe1-4ddc-a911-83d0d29547d3
Report Status: 268435456
Hashed bucket: b005feb57a2c8f7a3538330bdd349000
Cab Guid: 0 }

**Comment by copygirl** [comment]
@Gaara23 You must have missed a mod, XLib in this case?

> `at XLib.XEffects.CollectibleObjectPatch.Postfix(CollectibleObject __instance, StringBuilder dsc, IWorldAccessor world)`

**Comment by Gaara23** [comment]
> @Gaara23 You must have missed a mod, XLib in this case?
> 
> > `at XLib.XEffects.CollectibleObjectPatch.Postfix(CollectibleObject __instance, StringBuilder dsc, IWorldAccessor world)`

Hmm...shows disabled in the Mod Manager. 🤔

**Comment by Gaara23** [comment]
I fixed it actually. Silly me forgot to reload mods before starting up my save. 😂
