### ISSUE TITLE
Seems the server doesn't respect --dataPath

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1160]
**Game Version:** 1.14.10
**Platform:** Windows
**Modded:** No 

### Description
Despite starting with --dataPath pointing to another location, attempting to run the server from a fresh extracted folder (D:\Games\Vintage Story\_ModDev\TestLayout\bin\server\) of the "Server Only" download doesn't work, until I create a file in the extracted directory Saves\temp.txt ...

### Logs
```
Version: v1.14.10 (Stable)2021-07-04 13:45:50: Critical error occurred
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Games\Vintage Story\_ModDev\TestLayout\bin\server\Saves\temp.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Vintagestory.API.Common.SQLiteDBConnection.HaveWriteAccessFolder(String folderPath)
   at Vintagestory.API.Common.SQLiteDBConnection.OpenOrCreate(String filename, String& errorMessage, Boolean requireWriteAccess, Boolean corruptionProtection, Boolean doIntegrityCheck)
   at Vintagestory.Common.GameDatabase.ProbeOpenConnection(String databaseFilename, Boolean corruptionProtection, Int32& foundVersion, String& errorMessage, Boolean& isReadonly)
   at Vintagestory.Server.ServerSystemLoadAndSaveGame.OnBeginConfiguration()
   at Vintagestory.Server.ServerMain.EnterRunPhase(EnumServerRunPhase runPhase)
   at Vintagestory.Server.ServerMain.Launch()
   at ‫⁯‎⁬⁯‭​‌​‭‍‎‏‌‫⁮​⁯‭‍‏⁮⁫‌⁭⁮​‬⁪‫‭‬⁭⁫⁬⁪‎‭.‬‎​‬‭‌‭⁯⁫​‌‏‭⁭‫⁪‎⁮​⁫⁫⁪⁮‍⁪⁪‌‏⁪‪⁬‎‪‎‌⁪⁬()
   at _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(ThreadStart )
```

**Comment by sirStroam** [comment]
https://discord.com/channels/302152934249070593/334233095374897152/861092076316786708
