### ISSUE TITLE
Improve robustness against corrupting database files and/or resulting crashes

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#1163]
### Description
This is a collection issue for crashes related to various database files being corrupted, causing "The database disk image is malformed" and "Unable to read beyond the end of the stream" errors. While the latter can be resolved, it might be possible to reduce or even eliminate these issues altogether.

It's possible for the world map data to be corrupted, causing a crash when trying to join a particular server. (#690, #773, #868, #1158)

### Note to Players
Typically, "Unable to read beyond the end of the stream" errors can be resolved by starting the world in repair mode.
If that doesn't resolve the issue, check the [Repairing a corrupt savegame](https://wiki.vintagestory.at/index.php?title=Repairing_a_corrupt_savegame) wiki page.

### Logs
```
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.MemoryStream.InternalReadInt32()
   at Vintagestory.GameContent.EntityBlockFalling.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntitySpawnPacket(_qiwXoSSrnCKEl5NMyGSjHlpQcE serverpacket)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
```
```
System.Data.SQLite.SQLiteException (0x80004005): The database disk image is malformed
database disk image is malformed
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at Vintagestory.GameContent.MapDB.SetMapPieces(Dictionary`2 pieces)
   at Vintagestory.GameContent.ChunkMapLayer.OnOffThreadTick(Single dt)
   at Vintagestory.GameContent.WorldMapManager.<OnLoaded>b__23_0()
```

**Comment by tyronx** [comment]
The savegame already uses WAL journal mode, by the way.

**Comment by copygirl** [comment]
Yeah, I've rarely if at all seen the savegame itself get corrupted. But what causes specifically entities to fail being saved correctly sometimes?

**Comment by tyronx** [comment]
Oh also disclaimer, savegame wal mode was adedd in v1.14. So rather recent. 

> But what causes specifically entities to fail being saved correctly sometimes?

Likely also power out / OS Crash. I believe it is due to the fact that in those cases, some new chunks (with newly spawned entities) are saved, but the savegame data is not, which holds the `LastEntityId` value. It determines the next entity id, which must be globally unique. 

On next startup, the game spawns new entities with the same entity id which results in undefined behavior.

**Comment by copygirl** [comment]
Would the correct solution be always saving the `LastEntityId` if it was increased, before chunks are saved? (Potentially separately from the rest of the game data to reduce amount of data that needs to be saved every time a chunk also saves?)

**Comment by tyronx** [comment]
yea, indeed, that would be a good solution

**Comment by tyronx** [comment]
in fact, it should get written before the entity gets added to the chunk, that would be exactly the right spot
