### ISSUE TITLE
Crash on startup- 

### ISSUE THREAD

**Issue by Soupincans** [anegostudios/VintageStory-Issues#1186]
**Game Version:** 1.15.0-1.15.1
**Platform:** Windows 7 64 bit
**Modded:** No 

### Description
On boot, no client startup. Other versions working fine.

### Logs
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.15.1 (Stable)7/17/2021 8:30:27 PM: Critical error occurred
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at _dWMiVfUAappivvjgQTrHbayLaP6._JCfAsRVSY5s6xyZG4pMiBR26lu(_mzzuiHzecediUg7OL4KPB2bLyPO , String[] )
   at _75U2lTywrsd0KIurOPIOvOxQoiH._JCfAsRVSY5s6xyZG4pMiBR26lu(ThreadStart )
-------------------------------
```

**Comment by Craluminum2413** [comment]
Where is the crash?

**Comment by Soupincans** [comment]
Doesn't give me a line #, but my log is 
Running on 64 bit Windows with 8 GB RAM 
Version: v1.15.1 (Stable)7/17/2021 8:30:27 PM: Critical error occurred
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at _dWMiVfUAappivvjgQTrHbayLaP6._JCfAsRVSY5s6xyZG4pMiBR26lu(_mzzuiHzecediUg7OL4KPB2bLyPO , String[] )
   at _75U2lTywrsd0KIurOPIOvOxQoiH._JCfAsRVSY5s6xyZG4pMiBR26lu(ThreadStart )
-------------------------------

**Comment by Craluminum2413** [comment]
What mods do you have in your Mods folder?

**Comment by Soupincans** [comment]
None, deleted everything for troubleshooting, cleared the AppData folders.

**Comment by MeghanBomberger** [comment]
I'm having the same issue, and have also tried clearing out the mods and I tried reinstalling from scratch so at the moment I don't have any saves either (backed them up on a flash drive)

**Comment by Soupincans** [comment]
Same OS and it doesn't crash for other versions?

**Comment by copygirl** [comment]
You need to install the [.NET Framework 4.6 Runtime](https://dotnet.microsoft.com/download/dotnet-framework/net46).

We should probably add a check for this when you start the game.

**Comment by Soupincans** [comment]
We updated to 5.0, figured that would cover earlier versions of .net

**Comment by copygirl** [comment]
Yes, that might do it too.

**Comment by Soupincans** [comment]
No, you were correct! Installing that distro worked. 
Now I have a new crash, but this time the client does startup. 
Should I make a new issue?
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.15.1 (Stable)7/18/2021 3:47:26 AM: Critical error occurred
System.Exception: Referenced library not found: Mods\VSCreativeMod.dll
   at Vintagestory.Common.ModCompilationContext..ctor()
   at Vintagestory.Common.ModLoader..ctor(ICoreAPI api, EnumAppSide side, ILogger logger, IEnumerable`1 modSearchPaths, Boolean traceLog)
   at _RWDpUP9pNIFCL1enbZzYqmh8eRe._ItG0Ykbxm7ylToLlDDIBL0c8B1o()
   at _RWDpUP9pNIFCL1enbZzYqmh8eRe._ku9AsArNrTXpS4f5WBBgq6US6PX()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by copygirl** [comment]
@Soupincans Have you deleted the default game mods by accident? There should be VSEssentials, VSSurvivalMod and VSCreativeMod in your installation directory's `Mods` subfolder? Perhaps try reinstalling the game. Either way this sounds like it's not an issue with the game itself so perhaps you should ask for support in the Forums or Discord.
