### ISSUE TITLE
Crash on disconnecting from public server

### ISSUE THREAD

**Issue by PyralIron** [anegostudios/VintageStory-Issues#120]
I get the following crash when disconnecting from the public server, but not from disconnecting from a singleplayer game, in the VintagestoryCrash log:
```
5/26/2018 6:18:25 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _ourdUfqzAA1LC9050HTFp5jFL7y._z6mf0dUbeWNEZv95hFGiZf81aJ(_AJwc24Yt9IfcyhwL2yZFE5D7qNz , _1VOv5hKRIqBqp0TMAX0zjzD4FJe )
   at _ourdUfqzAA1LC9050HTFp5jFL7y._R8OMH6ZXYQAHbTiinLipvxZ24wM(_AJwc24Yt9IfcyhwL2yZFE5D7qNz , _1VOv5hKRIqBqp0TMAX0zjzD4FJe , Boolean )
   at _axflQenH9mbc79TycZC88P79KiB._V9sjerVmuJmO2TCUwJmOvCOJr1F(_AJwc24Yt9IfcyhwL2yZFE5D7qNz[] , Int32 , _1VOv5hKRIqBqp0TMAX0zjzD4FJe )
   at _toia2RCT4Ut8QglPSp8krAxYnyp._uhcruwJB63aUSfBYqtYewObkoM0._0UKvflsU3WdjHkBAQMW9ib1U8yp()
   at _JgUFhoUoAk13oIXv5A3yfu7Irbd._HGWJdDOq5fYmBbNffexIPvG96jB(_1VOv5hKRIqBqp0TMAX0zjzD4FJe , Single )
   at _1VOv5hKRIqBqp0TMAX0zjzD4FJe._0C01fdoaO7qLsFUDLwPNy7TxMeI(Single )
   at _Z0F8JEJiMJpcz4fy5Jt9BfXZlJn._RbGapH4idAiPweMTGvzqPVJv1HBA(Single )
   at _Cz1WgWEzS48UcO7zOyiClNFLOch._cPjnRrwmNcMstiXkVBs61ZJdcHG(Single )
   at _Cz1WgWEzS48UcO7zOyiClNFLOch._fHt1tnTb7SkZ6pjefseqws17wNk(Single )
   at _2rXCtUYpc4ETjxZdlyT2qmW9P8S._pcLjESifuDB0AOLzVX9wh6zXrug(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _9WUTp2l5fCwPyPvKrfzvDWqdAnM._LIIcf4EaRmaynxVoVS2h6rkCEKw(_4iiG6Tm4yI5SdyiYZKKFLS3BHrr , String[] )
   at _P35YS4isSPXwbGPhk8XTJnS2FPF._LIIcf4EaRmaynxVoVS2h6rkCEKw(ThreadStart )
```

**Comment by sirStroam** [comment]
same
```-------------------------------
5/31/2018 4:35:07 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _4ln2nGy1IvHoH0FZ5qxbQmkU8AI._byQQLDIvrsZUoujzCaS75RGB1JD(Single )
   at _LOCdge8fPO0OoGdFisvCWDCfxkFb._7SCBtNOLweRcxVKvLicl3PEXJ6AA(Int64 , IWorldAccessor )
   at _OcDw1EJDtyxSg2zIZUkz5GvfhLf._YvjVAV2DvRhhcGH5E47iqBGXLE1(Single )
   at _OcDw1EJDtyxSg2zIZUkz5GvfhLf._ESP6jvrKgTsShcp5CABSxRTgdjh(Single )
   at _NOGdaXHjcqYbZp309TBwE1lwaJoA._ExRcvCgtpj75hrxXNi0Fq2zHtPE(Single )
   at _EP7D7TCjbI38qUrbc8v9F8rIJvBA._f1gdadbeaLzUZvf0eYqEv8hB6HHA(Single )
   at _EP7D7TCjbI38qUrbc8v9F8rIJvBA._cCrJraU5W0BU0xQ8vqgu2GncwHh(Single )
   at _0i52t9CegOtDCetucrJbvQ8mTjy._0hTztHagGp0JVZ40l1FngGASBwh(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _KbPBTtpp9dCK8HCfZavQddEV3tP._5RUcArPeN1Ng7pkVPQqGdZQ033O(_6bvH7Blhp6ycqoRLHWCCCwkK7wD , String[] )
   at _I5JXPXhpKipFp36rslLC7Rct7JC._5RUcArPeN1Ng7pkVPQqGdZQ033O(ThreadStart )
-------------------------------
```

**Comment by tyronx** [comment]
Hm, odd, could one of you guys get me the client-main.txt log where this crash happened?

**Comment by tyronx** [comment]
Eitherway, I made a tiny change, so might be fixed already for 1.5.5

**Comment by copygirl** [comment]
1.5.5 is out now - anyone who encountered the error able to confirm this does still occur or does not anymore?

**Comment by copygirl** [comment]
Closing for now. Please reopen, comment, or create a new issue if this is still occuring.
