### ISSUE TITLE
Game crashes upon me choosing to create a new world on Windows 10 

### ISSUE THREAD

**Issue by KibaAlaric** [anegostudios/VintageStory-Issues#1203]
Game Version: 1.15.1
Platform: Windows
Modded: No

### Description
So I had just recently DL'd the latest release of the game from the website and booted it up, Upon doing so I had mods installed previous from an older version of the game but thought to myself, "I'm sure they have all updated to latest patch by now", started a single player and created a new world then let it all load up but eventually crashed. So I went into the mods and diselected all of them and tried again with a new world but upon doing so it crashed as I clicked the create a new world button. So what I did was delete all the mods I had and tried again and still did the same thing, also uninstalled and re-installed as well and I'm still getting the same crash on clicking the new world button.

### How to reproduce
1. explained above in my description
2. Use it on windows computer
3. It crashes upon clicking the new world button

### Expected behavior
I expect it to allow me to create a new world and play the game

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.1 (Stable)7/20/2021 6:09:26 AM: Critical error occurred
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.WorldConfig.ToRichText(Boolean withCustomConfigs)
   at _ET44vvbVa6AuHTu0fsY1yylLd2E._XH0lCUIFXJLmWfycDhBbfDCGSTkb()
   at _ET44vvbVa6AuHTu0fsY1yylLd2E..ctor(_RWDpUP9pNIFCL1enbZzYqmh8eRe , _AMpx56AT6p0DpPViHiElnwbidoY )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at _RWDpUP9pNIFCL1enbZzYqmh8eRe._8QDbIqqnkv2G4Nr1pzCrqSsuhPR(Type )
   at _zYtcbdgceo07V7cZPr7cPmzL3zY._BZHzkjss38xepJr5LueNI2s83zd()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _AMpx56AT6p0DpPViHiElnwbidoY._gmzxD1lQbcUzg7uj53D3a0vjnJl(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _dWMiVfUAappivvjgQTrHbayLaP6._JCfAsRVSY5s6xyZG4pMiBR26lu(_mzzuiHzecediUg7OL4KPB2bLyPO , String[] )
   at _75U2lTywrsd0KIurOPIOvOxQoiH._JCfAsRVSY5s6xyZG4pMiBR26lu(ThreadStart )
-------------------------------
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.WorldConfig.ToRichText(Boolean withCustomConfigs)
   at _ET44vvbVa6AuHTu0fsY1yylLd2E._XH0lCUIFXJLmWfycDhBbfDCGSTkb()
   at _ET44vvbVa6AuHTu0fsY1yylLd2E..ctor(_RWDpUP9pNIFCL1enbZzYqmh8eRe , _AMpx56AT6p0DpPViHiElnwbidoY )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/20/2021 5:58:16 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1834284369152566606, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.1.0
P3: 60f1d839
P4: 86d0
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER52C3.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER52E3.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER52E2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5302.tmp.txt
\\?\C:\Users\themu\AppData\Local\Temp\WER595C.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_b69f64f38cbc1ee27421f6d845f1b518d030b7_0fc5e02c_e2183ccf-9b43-4f56-9a75-14171e2c94ac

Analysis symbol: 
Rechecking for solution: 0
Report Id: ae6561d1-cfbf-4d24-af27-7469ec865519
Report Status: 268435457
Hashed bucket: 397d3a98f8be73eaa974afea5063e54e
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/20/2021 5:58:16 AM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.15.1.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 247c

Start Time: 01d77d4d7ec7e230

Termination Time: 3

Application Path: C:\Games\Vintagestory\Vintagestory.exe

Report Id: ae6561d1-cfbf-4d24-af27-7469ec865519

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
```

**Comment by tyronx** [comment]
Thanks for the report. I was able to reproduce this crash by disabling the mods that the game ships with. Please make sure to enable the essentials and survival mods. 

The crash will be fixed next version.
