### ISSUE TITLE
Game crashes on cheese falling

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1204]
**Game Version:** 1.15.1
**Platform:** Windows
**Modded:** No

### How to reproduce
1. Place cheese (whole, 3/4, 2/4, 1/4 - doesn't matter)
2. Break block underneath the cheese, it should fall
3. It crashes, if not, then repeat again (99% should crash on next try)

### Logs
```
Version: v1.15.1 (Stable)07/20/2021 13:37:43: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BECheese.get_SlicesLeft()
   at Vintagestory.GameContent.BlockCheese.<>c__DisplayClass1_0.<OnLoaded>b__1(WorldInteraction wi, BlockSelection bs, EntitySelection es)
   at Vintagestory.Client.NoObf.DrawWorldInteractionUtil.ComposeBlockWorldInteractionHelp(WorldInteraction[] wis)
   at Vintagestory.Client.NoObf.HudElementBlockInteractionHelp.BlockInView()
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _LpTdfLOAWwrFBtCzFbbeuEgj89qb._BdAGMFwyOn5tRjrJ2AiJBfbgDkH(Single )
   at _RWDpUP9pNIFCL1enbZzYqmh8eRe._rmjRcUg6ZZy8gFclAtdmfo8RemC(Single )
   at _RWDpUP9pNIFCL1enbZzYqmh8eRe._uf2x7pSJniCpFh7nbMvuI5iHIsh(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _dWMiVfUAappivvjgQTrHbayLaP6._JCfAsRVSY5s6xyZG4pMiBR26lu(_mzzuiHzecediUg7OL4KPB2bLyPO , String[] )
   at _75U2lTywrsd0KIurOPIOvOxQoiH._JCfAsRVSY5s6xyZG4pMiBR26lu(ThreadStart )
```

**Comment by tyronx** [comment]
thanks for the report this should be fixed next release
