### ISSUE TITLE
Placing fishing net in water causes crash

### ISSUE THREAD

**Issue by bobmek** [anegostudios/VintageStory-Issues#1210]
**Game Version:** 1.15.1 (stable)  
**Platform:** Windows 
**Modded:** No 

### Description
I tried placing a fishing net in the water and the programmed hard crashed.

### How to reproduce
1. Make a 'fishing net'
2. Use it on 'water'
3. It crashes

### Expected behavior
I haven't tried the fishing nets yet, but i assume i should be able to interact?

### Logs
```
#### client-main.txt 
21.7.2021 15:07:24 [Notification] Client logger started.
21.7.2021 15:07:24 [Notification] Game Version: v1.15.1 (Stable)
21.7.2021 15:07:24 [Notification] Screens:
21.7.2021 15:07:24 [Notification] 0: {X=0,Y=0,Width=1920,Height=1200}, \\.\DISPLAY1 (primary)
21.7.2021 15:07:24 [Notification] 1: {X=-1920,Y=0,Width=1920,Height=1200}, \\.\DISPLAY2 
21.7.2021 15:07:25 [Notification] Graphics Card Vendor: Intel
21.7.2021 15:07:25 [Notification] Graphics Card Version: 3.3.0 - Build 27.20.100.9126
21.7.2021 15:07:25 [Notification] Graphics Card Renderer: Intel(R) UHD Graphics 620
21.7.2021 15:07:25 [Notification] Graphics Card ShadingLanguageVersion: 3.30 - Build 27.20.100.9126
21.7.2021 15:07:25 [Notification] Cairo Graphics Version: 1.17.3
21.7.2021 15:07:25 [Notification] OpenAL Version: 1.1 ALSOFT 1.16.0
21.7.2021 15:07:25 [Notification] C# Framework: .net Framework 4.0.30319.42000
21.7.2021 15:07:25 [Notification] OpenTK Version: 3.3.1 (A set of fast, low-level C# bindings for OpenGL, OpenGL ES and OpenAL. Forked by Anego Studios.)
21.7.2021 15:07:25 [Notification] Start discovering assets
21.7.2021 15:07:25 [Notification] Found 16 base assets in category lang
21.7.2021 15:07:25 [Notification] Found 0 base assets in category patches
21.7.2021 15:07:25 [Notification] Found 22 base assets in category config
21.7.2021 15:07:25 [Notification] Found 0 base assets in category worldproperties
21.7.2021 15:07:25 [Notification] Found 44 base assets in category sounds
21.7.2021 15:07:25 [Notification] Found 96 base assets in category shapes
21.7.2021 15:07:25 [Notification] Found 76 base assets in category shaders
21.7.2021 15:07:25 [Notification] Found 15 base assets in category shaderincludes
21.7.2021 15:07:25 [Notification] Found 125 base assets in category textures
21.7.2021 15:07:25 [Notification] Found 4 base assets in category music
21.7.2021 15:07:25 [Notification] Found 0 base assets in category dialog
21.7.2021 15:07:25 [Notification] Found 398 base assets in total
21.7.2021 15:07:25 [Notification] Loading sounds
21.7.2021 15:07:25 [Notification] (Re-)loaded frame buffers
21.7.2021 15:07:25 [Notification] Loaded Shaderprogramm for render pass . 
21.7.2021 15:07:25 [Notification] CPU Cores: 8
21.7.2021 15:07:25 [Notification] Window was resized to 1282 809, rebuilding framebuffers...
21.7.2021 15:07:25 [Notification] (Re-)loaded frame buffers
21.7.2021 15:07:25 [Notification] Sounds loaded
21.7.2021 15:07:25 [Notification] Begin loading shaders
21.7.2021 15:07:25 [Notification] Load shaders now
21.7.2021 15:07:25 [Notification] Loading shaders...
21.7.2021 15:07:26 [Notification] Loaded Shaderprogramm for render pass standard. 
21.7.2021 15:07:26 [Notification] Loaded Shaderprogramm for render pass particlescube. 
21.7.2021 15:07:26 [Notification] Loaded Shaderprogramm for render pass particlesquad. 
21.7.2021 15:07:26 [Notification] Loaded Shaderprogramm for render pass sky. 
21.7.2021 15:07:26 [Notification] Loaded Shaderprogramm for render pass nightsky. 
21.7.2021 15:07:26 [Notification] Loaded Shaderprogramm for render pass woittest. 
21.7.2021 15:07:26 [Notification] Loaded Shaderprogramm for render pass transparentcompose. 
21.7.2021 15:07:26 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer. 
21.7.2021 15:07:26 [Notification] Loaded Shaderprogramm for render pass helditem. 
21.7.2021 15:07:26 [Notification] Loaded Shaderprogramm for render pass chunkopaque. 
21.7.2021 15:07:26 [Notification] Loaded Shaderprogramm for render pass multitexturetest. 
21.7.2021 15:07:26 [Notification] Loaded Shaderprogramm for render pass chunkliquid. 
21.7.2021 15:07:26 [Notification] Loaded Shaderprogramm for render pass decals. 
21.7.2021 15:07:26 [Notification] Loaded Shaderprogramm for render pass final. 
21.7.2021 15:07:26 [Notification] Loaded Shaderprogramm for render pass gui. 
21.7.2021 15:07:26 [Notification] Loaded Shaderprogramm for render pass blur. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass chunktransparent. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass findbright. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass chunktopsoil. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass godrays. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass autocamera. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass blockhighlights. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass wireframe. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass entityanimated. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass luma. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass blit. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass particlesquad2d. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass texture2texture. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass celestialobject. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass guitopsoil. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass entityanimatedtransparent. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass colorgrade. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass guigear. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass ssao. 
21.7.2021 15:07:27 [Notification] Loaded Shaderprogramm for render pass bilateralblur. 
21.7.2021 15:07:27 [Notification] Cached session key is valid, validating with server
21.7.2021 15:07:28 [Notification] Server validation response: Good
21.7.2021 15:07:28 [Notification] Will search the following paths for mods:
21.7.2021 15:07:28 [Notification]     C:\Users\rmeklemburg\AppData\Roaming\Vintagestory\Mods
21.7.2021 15:07:28 [Notification]     C:\Users\rmeklemburg\AppData\Roaming\VintagestoryData\Mods



###### client-crash.txt
Version: v1.15.1 (Stable)7/21/2021 3:03:01 PM: Critical error occurred
System.MissingMethodException: Method not found: 'Void Vintagestory.API.Common.IBlockAccessor.MarkBlockDirty(Vintagestory.API.MathTools.BlockPos)'.
   at BEFishBasket.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolve)
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(_judMEzrGk2BBXJydxkBBqGcDfbeA p, ClientMain game)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(_VDN4c9aNSGhuso1YJUSgt1aBDX packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _LpTdfLOAWwrFBtCzFbbeuEgj89qb._BdAGMFwyOn5tRjrJ2AiJBfbgDkH(Single )
   at _RWDpUP9pNIFCL1enbZzYqmh8eRe._rmjRcUg6ZZy8gFclAtdmfo8RemC(Single )
   at _RWDpUP9pNIFCL1enbZzYqmh8eRe._uf2x7pSJniCpFh7nbMvuI5iHIsh(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _dWMiVfUAappivvjgQTrHbayLaP6._JCfAsRVSY5s6xyZG4pMiBR26lu(_mzzuiHzecediUg7OL4KPB2bLyPO , String[] )
   at _75U2lTywrsd0KIurOPIOvOxQoiH._JCfAsRVSY5s6xyZG4pMiBR26lu(ThreadStart )
-------------------------------

```

**Comment by Ragolution** [comment]
Aren't fishing nets are mod content?

**Comment by Craluminum2413** [comment]
https://mods.vintagestory.at/show/mod/15

**Comment by bobmek** [comment]
omg...i'm such an idiot...I totally forgot i put that mod on the past version when i upgraded to 1.15.1! Sorry for being a dumb dumb.
