### ISSUE TITLE
Handbook: Game crashes on trying to open page of charred bread baked on firepit

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1217]
**Game Version:** 1.15.2  
**Platform:** Windows
**Modded:** No

### How to reproduce
1. Try to open the handbook page of bread baked on firepit
2. It crashes

### Videos

https://user-images.githubusercontent.com/69315569/126865582-affb83aa-ef06-4da5-a1b8-816c000b1afe.mp4

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.2 (Stable)07/24/2021 13:22:41: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AssetLocation.ResolveToDomainAndPath(String domainAndPath, String& domain, String& path)
   at Vintagestory.API.Common.CollectibleObject.GetHandbookInfo(ItemSlot inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.API.Client.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.GameContent.GuiDialogHandbook.initDetailGui()
   at Vintagestory.API.Client.GuiElementHandbookList.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _DlY2IRaBbEwZdipnKtrb40WUzTZ._kVFD8SxIojOmGrxNtThdBHagQeh(_7hnpozI2lFsAA8Wa5CIiUgRAbXjA , String[] )
   at _gCIDaxCwdS0mkZub2rV5ATdV3hOA._kVFD8SxIojOmGrxNtThdBHagQeh(ThreadStart )
```

**Comment by copygirl** [comment]
Will close in favor of #1218 - this appears to occur with many different handbook pages.

**Comment by Craluminum2413** [comment]
Since Tyron said in that issue that these are two different bugs, could you please correct this by removing the duplicate label and adding resolved label etc.?
