### ISSUE TITLE
Client Crash on Hosted Server Options

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1232]
**Game Version:** 1.15.2
**Platform:** Windows 
**Modded:** No

### Description
Clicked server settings after stopping the server and it crashed.

### How to reproduce
1. Keep stopping the server and clicking on server settings until it crashes.

### Logs
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.15.2 (Stable)7/30/2021 5:03:57 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _gUENHyVWee0vGwuboDon31nF1nR._jPhTUAaFKHAXvVXUcAxllL63pRG(EnumAuthServerResponse , GameServerConfigResponse )
   at _sxB098bXeOomDA2jWDRq9GOl0le._eH5v0cNhkoIWbghhxiBC5iwVdnz`1._GLaEewNVTPNRkxrNHZQLcQJqeob()
   at _eJCiYuww7mZPzQbnKfiEtnI4MDD._B2re7Q8SHFC6kaTk8kmsYrPVaKB(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _DlY2IRaBbEwZdipnKtrb40WUzTZ._kVFD8SxIojOmGrxNtThdBHagQeh(_7hnpozI2lFsAA8Wa5CIiUgRAbXjA , String[] )
   at _gCIDaxCwdS0mkZub2rV5ATdV3hOA._kVFD8SxIojOmGrxNtThdBHagQeh(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/8/2021 11:56:49 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1252239485250825062, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Sirst\AppData\Local\Temp\RDRD9A7.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD9C8.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD9E8.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDA44.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDAB2.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 5df97390-803b-4e67-8bb2-7800e9344103
Report Status: 268435456
Hashed bucket: 9a6d16c7ad62a31db160d92d5c17eb66
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/25/2021 1:00:03 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1155247148303425079, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 60ce51ed
P4: KERNELBASE.dll
P5: 10.0.19041.1023
P6: 924f9cdb
P7: c0020001
P8: 0000000000034b89
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4AC6.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5093.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER50A4.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER50B1.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER50D2.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_ae741ec54f428bb4149b6c904a406339e8e8ae0_b5f6ba0e_952bd34f-2df5-4e35-84a5-8a62c11e9a78

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9f61455d-ea30-4410-9d6d-0d763dfbb948
Report Status: 268566528
Hashed bucket: 6d6ccb91ba3b4c41900843291e689e37
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/25/2021 12:59:50 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.15.0.0, time stamp: 0x60ce51ed
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1023, time stamp: 0x924f9cdb
Exception code: 0xc0020001
Fault offset: 0x0000000000034b89
Faulting process id: 0x4590
Faulting application start time: 0x01d76997df0a94e1
Faulting application path: C:\Users\Sirst\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 9f61455d-ea30-4410-9d6d-0d763dfbb948
Faulting package full name: 
Faulting package-relative application ID:  }
```

**Comment by sirStroam** [comment]
Needs looking into but isn't reliably reproducible.

**Comment by copygirl** [comment]
From the looks of it, this is the same as #1302, which Tyron has looked into. Will close for now.
