### ISSUE TITLE
Game crashes every time I try to place the Clay Oven

### ISSUE THREAD

**Issue by LunacyPunk** [anegostudios/VintageStory-Issues#1244]
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.3 (Stable)8/2/2021 5:34:39 PM: Critical error occurred
System.TypeLoadException: Could not load type 'Vintagestory.GameContent.BakingProperties' from assembly 'VSSurvivalMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at XSkills.BlockEntityOvenPatch.GetBlockInfoPostfix(BlockEntity __instance, InventoryOven ___ovenInv, OvenItemData[] ___bakingData, Single ___fuelBurnTime, IPlayer forPlayer, StringBuilder sb)
   at Vintagestory.GameContent.BlockEntityOven.GetBlockInfo_Patch1(BlockEntityOven this, IPlayer forPlayer, StringBuilder sb)
   at Vintagestory.API.Common.Block.GetPlacedBlockInfo(IWorldAccessor world, BlockPos pos, IPlayer forPlayer)
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.ComposeBlockInfoHud()
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.BlockInView()
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _eAYXniWl7YYoizkDdY8EDX2NUGf._naTl4w2UkJuDlsP9uyhAhjkhAvy(Single )
   at _0h7dYtC5OxgFq3Dhnj2p0gxEXO3._7siDwGtIPuCnT2TllZ2WXtr1bsM(Single )
   at _0h7dYtC5OxgFq3Dhnj2p0gxEXO3._YznPHQWtIAwbLwxdlknpXY2Mrsm(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _Km7YT9SY1sKIj5UBhEpQfHc3XzB._u0WbDJ5hzkzp3qHp31dGQ3NRIqJ(_EyrNhzlOC9XfxRuKJ1Vc8VeXIpA , String[] )
   at _pFLYUi2IEGEC895yDwFlhWqtVoD._u0WbDJ5hzkzp3qHp31dGQ3NRIqJ(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/22/2021 9:40:11 AM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.15.1.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 1528

Start Time: 01d77f071f6856e6

Termination Time: 4

Application Path: C:\Users\12077\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: fe74e344-53cd-4902-8430-ba80768c769c

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 7/22/2021 9:40:09 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1834284369152566606, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.1.0
P3: 60f1d839
P4: 86d0
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6401.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6411.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6420.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6431.tmp.txt
\\?\C:\Users\12077\AppData\Local\Temp\WER68F4.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_b69f64f38cbc1ee27421f6d845f1b518d030b7_0fc5e02c_fe7bf4de-4904-49e2-88ed-6f90fdfaf36e

Analysis symbol: 
Rechecking for solution: 0
Report Id: fe74e344-53cd-4902-8430-ba80768c769c
Report Status: 268435456
Hashed bucket: 397d3a98f8be73eaa974afea5063e54e
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/16/2021 10:35:38 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1844930624240464797, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.1.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\12077\AppData\Local\Temp\RDR3D4B.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3D6C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3D7C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3D7C.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3D9C.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: f2171337-9b25-474a-86c6-7eaec1fdfec3
Report Status: 268435456
Hashed bucket: b4a6b879c54e219cb99a82a0bd17b39d
Cab Guid: 0 }

**Comment by Ragolution** [comment]
It'd be helpful if you could go back and fill in the normal bug reporting format so we can know if you're using any mods.

**Comment by LunacyPunk** [comment]
![Mod List 00](https://user-images.githubusercontent.com/88352084/127940286-e77c35cb-539e-4374-91ab-3807328275fb.png)
![Mod List3](https://user-images.githubusercontent.com/88352084/127940288-c84f4b0e-ab8d-4dd5-b283-5080e05859a3.png)
![ModList 50](https://user-images.githubusercontent.com/88352084/127940289-9126b137-3cdd-42dd-911d-8dbe7e02ca31.png)
![Modlist1](https://user-images.githubusercontent.com/88352084/127940290-c660178c-375d-40ce-a50c-2cc57060c18b.png)
![ModList2](https://user-images.githubusercontent.com/88352084/127940291-d748e8f3-fc78-4423-be03-53b026e6a8bb.png)

**Comment by LunacyPunk** [comment]
Sorry, I'm new to this, and Just now grabbed the screenshots of my mods

**Comment by copygirl** [comment]
> `at XSkills.BlockEntityOvenPatch.GetBlockInfoPostfix(BlockEntity __instance, InventoryOven ___ovenInv, OvenItemData[] ___bakingData, Single ___fuelBurnTime, IPlayer forPlayer, StringBuilder sb)`

This is likely XSkills' fault. Report to mod author and wait until mod is updated.

**Comment by LunacyPunk** [comment]
Thank you!
