### ISSUE TITLE
Mixed cheese pie causes crash

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#1264]
**Game Version:** 1.15.3
**Platform:** Win10
**Modded:** N

### Description
Making a cheese pie with two types of cheese causes a CTD.

### How to reproduce
1. Make a pie shell. (I used sunflower flour.)
2. Fill it with 1 type of cheese ( ex. Blue Cheese )
3. Attempt to add a 2nd type of cheese (ex. Cheddar)
4. Game will crash.

### Logs
```
Running on 64 bit Windows with 24 GB RAM 
Version: v1.15.3 (Stable)8/9/2021 1:09:28 AM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.MealMeshCache.GetPieMesh(ItemStack pieStack, ModelTransform transform)
   at Vintagestory.GameContent.BlockEntityPie.loadMesh()
   at Vintagestory.GameContent.BlockEntityPie.OnInteract(IPlayer byPlayer)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _eAYXniWl7YYoizkDdY8EDX2NUGf._VmVAOpmA6roNiWQoNAQLt9tWkzR(Single )
   at _0h7dYtC5OxgFq3Dhnj2p0gxEXO3._7siDwGtIPuCnT2TllZ2WXtr1bsM(Single )
   at _0h7dYtC5OxgFq3Dhnj2p0gxEXO3._YznPHQWtIAwbLwxdlknpXY2Mrsm(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _Km7YT9SY1sKIj5UBhEpQfHc3XzB._u0WbDJ5hzkzp3qHp31dGQ3NRIqJ(_EyrNhzlOC9XfxRuKJ1Vc8VeXIpA , String[] )
   at _pFLYUi2IEGEC895yDwFlhWqtVoD._u0WbDJ5hzkzp3qHp31dGQ3NRIqJ(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/29/2021 5:43:22 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1441907903510307422, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.1.0
P3: 60f1d839
P4: KERNELBASE.dll
P5: 10.0.19041.1110
P6: 4809adf2
P7: c0020001
P8: 0000000000034ed9
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2212.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2966.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER29A5.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER29A3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER29F2.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_4196bbbe9dd9c3bd6fb911631f4eb28e61b73e_0fc5e02c_42b53ca6-62ea-41d0-bb91-4f4b74a426d4

Analysis symbol: 
Rechecking for solution: 0
Report Id: 110873f1-11b6-49f7-b376-4590003c52b1
Report Status: 268566528
Hashed bucket: 48f2ebef2d2f21df9402af99438f625e
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/29/2021 5:43:17 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.15.1.0, time stamp: 0x60f1d839
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1110, time stamp: 0x4809adf2
Exception code: 0xc0020001
Fault offset: 0x0000000000034ed9
Faulting process id: 0x30c0
Faulting application start time: 0x01d7849993d45b01
Faulting application path: F:\Games\Kosher\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 110873f1-11b6-49f7-b376-4590003c52b1
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 7/29/2021 5:43:16 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFF0AA74ED9
Stack:
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at System.Environment._Exit(Int32)
   at System.Environment._Exit(Int32)
   at System.Environment.Exit(Int32)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   at OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double, Double)
   at _dWMiVfUAappivvjgQTrHbayLaP6._JCfAsRVSY5s6xyZG4pMiBR26lu(_mzzuiHzecediUg7OL4KPB2bLyPO, System.String[])
   at _75U2lTywrsd0KIurOPIOvOxQoiH._JCfAsRVSY5s6xyZG4pMiBR26lu(System.Threading.ThreadStart)
   at _dWMiVfUAappivvjgQTrHbayLaP6._8GZdW3ZlOrTh5fxZzkjHqqed9yn(System.String[])
 }
```

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
