### ISSUE TITLE
Multi-material chisel blocks cause crash

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#1268]
**Game Version:** 1.15.4
**Platform:** Win10
**Modded:** No 

### Description
Chiseled blocks with multiple materials will crash the client upon left-click.

### How to reproduce
1. Chisel a block, make it as complex as you like.
2. Attempt to break it
3. Crash!

### Logs
```
Running on 64 bit Windows with 24 GB RAM 
Version: v1.15.4 (Stable)8/9/2021 9:21:22 PM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.Client.NoObf.SystemRenderDecals.UpdateDecal(BlockDecal decal)
   at Vintagestory.Client.NoObf.SystemRenderDecals.AddBlockBreakDecal(BlockPos pos, Int32 stage)
   at Vintagestory.Client.NoObf.SystemRenderDecals.OnPlayerBreakingBlock(_CSoix20cBYDFfjACzUucHpcWWJf blockDamage)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockBreaking(_CSoix20cBYDFfjACzUucHpcWWJf blockDamage)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _HudNshtcJTiSb0AO3ureZsghEqV._s7tOcpBSZm7boTmJPcYeXtmstYE(Single )
   at _MtvIXhgbjdJhuIbc1FegEMpLKud._0A7s5MRwo6bB8g8kaenT2SalePH(Single )
   at _MtvIXhgbjdJhuIbc1FegEMpLKud._nHJY5yhLTAITDfKmB1lJVftevLe(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _mzv7HUwbhZoZmtxEpQ4NQOm3IbH._FGqcMJeY4eQZ8jt9dxvP4gQRARG(_cgPZroMph1owK0EWmdACbOhN9fy , String[] )
   at _ZSjH1aUc8UgAKJxucBR0z2q8eQz._FGqcMJeY4eQZ8jt9dxvP4gQRARG(ThreadStart )
-------------------------------

```

**Comment by Xaffiri** [comment]
I was able to reproduce this multiple times.

**Comment by DeviantMuse** [comment]
I too was able to reproduce this multiple times

**Comment by tyronx** [comment]
thanks for the report, i'll make a quick 1.15.5 release to fix this
