### ISSUE TITLE
Screen went purple and then crashed

### ISSUE THREAD

**Issue by jdwilward** [anegostudios/VintageStory-Issues#1276]
**Game Version:** 1.15.5
**Platform:** Windows
**Modded:** Yes 

### Description
The screen went purple and I could still move around and then the game a few seconds later crashed

### How to reproduce
I was simply running around and the screen went purple to try and reset this error i tried turning the purple grass fix on and off but when i turned it on the game crashed

### Logs
```Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.5 (Stable)16/08/2021 16:36:44: Critical error occurred
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Vintagestory.Client.NoObf.ShaderProgramBase.Uniform(String uniformName, Single value)
   at VolumetricShading.Effects.DeferredLighting.OnEndRender()
   at VolumetricShading.Effects.DeferredLightingRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _EMxDKvc7iN7J6hlNFQiKeoxg0Mm._CEmopzLEk14BSqH9plcDEDfmuwE(Single )
   at _Wwq7msw90Af4XU7mxkxAUKyrS5B._iIGaTXNE8VYTpgEu9zjpAQyJSxd(Single )
   at _Wwq7msw90Af4XU7mxkxAUKyrS5B._vCB99EztL7cSfmplK8tyTwrQQxC(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _q065sSmA3CNgGuKTGnlAjR4ljPw._WkSl7yfiyr5DwPiSMvTudNAhp6(_t3ILnyYBq5OoYhhBY3JeTWgFmJDA , String[] )
   at _DBu5wiQWRAHGS5G2jiCKymvQ9yE._WkSl7yfiyr5DwPiSMvTudNAhp6(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 02/08/2021 13:11:10, Site = , Source = Windows Error Reporting, Message = Fault bucket 1803473370194165024, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.3.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Jordan\AppData\Local\Temp\RDR2A92.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2AA2.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2AB3.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2ACA.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2AFA.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 173e3cf4-a855-4e8e-9a54-ebb813226603
Report Status: 268435456
Hashed bucket: 02bffaf4f10c253a69073979984cbd20
Cab Guid: 0 }``
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by copygirl** [comment]
According to the stack trace you have the Volumetric Shading mod installed:

```
   at VolumetricShading.Effects.DeferredLighting.OnEndRender()
   at VolumetricShading.Effects.DeferredLightingRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage)
```

Make sure you have the latest version of this mod. If this doesn't help, disable or delete the mod.
For now I can only guess this error is related to the mod somehow. Please report the issue to its author.
