### ISSUE TITLE
Server Crash on Mass Dirt Mountain Collapse

### ISSUE THREAD

**Issue by Risskitty** [anegostudios/VintageStory-Issues#1277]
**Game Version:** 1.15.3 
**Platform:** Windows  
**Modded:** Yes 
 Acorns v0.5.0
anthroFoxPlayerModel1
BackpackPackPlus1.0.0
BetterThanHeresy_1.1.2
buildingplus_v.1.15.2-1.0.5
CaptureAnimals_v1.15.2-v2.0.1
CarryCapacityVS1.15.0-v0.6.2
ExtraChestsCC_v1.4.0
FixRoads_v1.15.0_v1.3.1
Flint Chisel v1.0.0
Lichen-v1.5.0
merchant_v0.9.7
MoreClasses1.1.1
MorePiles_v1.15.1v1.0.0
MoreRoads 1.3.9
PlayerCorpse_v1.15.1_v1.0.0
PrimitiveSurvivial2.6.2
spyglass_v0.2.1
Stackables2.0.4
Stacksv1.0.3
TeleportationNetwork_v1.15.1_v1.2.0
VSMovementMod v1.0.3
vsprospectorinfo_v4.1.0
wildfarming_v1.0.1
xlib_v0.6.0-pre.6
xskills_v0.6.0-pre.8
zeekea_1.15.0-1.4.10

### Description
I was playing on a personally owned server and was running around exploring. Dirt gravity was enabled. The world height is 511 blocks. I entered a new chunk and while the chunk started to render in, the game crashed. There was another individual on the same server at the time, but they were much further away from this chunk. The server did not crash for them. I had another friend come to the chunk I had crashed in. Once they arrived at the chunk and started to render it in, the game crashed for them also. By reducing their render distance, they were able to see dirt collapsing and sliding off a mountain. When they opened their map, the entire mountain was grayed out because it was not rendering. As they approached the mountain, attempting to reach my exact coordinates, they continually crashed. Similar to my problem. I have had the server owner reset the server in attempts to eliminate some of the item blocks. The server owner also turned off dirt gravity to stop the collapse. I have successfully been able to start my own solo world with and without mods, finding the problem is with the server in that specific area and not with my game or computer. I have tried logging on and rendering the area on a much stronger computer than my own only to still have it crash. Due to me being deeper in the chunk when the collapse started, even at the smallest render distance the game will still crash. 

### How to reproduce
1. Create a server/solo world with dirt gravity enabled and world height of 511+.
2. Find a chunk with a collapsing dirt mountain (which admittedly is difficult to find the exact correct circumstances).
3. It crashes almost immediately. All subsequent log ins will crash within 1 second of attempting to render. 

### Expected behavior
It may be an error with the world height being so high and the game simply attempting to load too many actions at once. The server owner and I have just done everything we can think of to try and load in the chunk at the very lowest graphical settings to no avail. 

### Screenshots
![Dirt Slide 2](https://user-images.githubusercontent.com/89051892/129647487-f11f5771-0485-4c5d-8657-9d0c2a28357d.png)
![Dirt Slide](https://user-images.githubusercontent.com/89051892/129647497-c68b430b-89a8-43d4-929d-4893f144420f.png)
![Grayed Out Mountain Zoomed](https://user-images.githubusercontent.com/89051892/129647506-7b0f4ce6-940e-437e-8973-7c0561b54f8a.png)
![Grayed Out Mountain](https://user-images.githubusercontent.com/89051892/129647510-a59ac291-745f-4497-8fe6-d4ebbdda7ca9.png)
![Item Blocks](https://user-images.githubusercontent.com/89051892/129647518-071d1968-800f-426a-ab31-0a3c68ed5cf1.png)
![Mountain Size](https://user-images.githubusercontent.com/89051892/129647528-da359713-a1f9-41d6-8a3f-8b212c71b18e.png)
![Mountain Height and Item Blocks](https://user-images.githubusercontent.com/89051892/129647534-94f46727-b71f-4ac6-bdcb-de9ba7d353a7.png)

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.3 (Stable)8/16/2021 7:04:36 PM: Critical error occurred
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at Vintagestory.Client.NoObf.ClientChunk.InitBlockEntitiesFromPacket(ClientMain game)
   at Vintagestory.Client.NoObf.ClientWorldMap.loadChunkMT(_qqiy456PdOoZqOfHyP0CRSpGMad p, ClientChunk chunk)
   at Vintagestory.Client.NoObf.ClientWorldMap.<>c__DisplayClass102_0.<LoadChunkFromPacket>b__0()
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _eAYXniWl7YYoizkDdY8EDX2NUGf._naTl4w2UkJuDlsP9uyhAhjkhAvy(Single )
   at _0h7dYtC5OxgFq3Dhnj2p0gxEXO3._7siDwGtIPuCnT2TllZ2WXtr1bsM(Single )
   at _0h7dYtC5OxgFq3Dhnj2p0gxEXO3._YznPHQWtIAwbLwxdlknpXY2Mrsm(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _Km7YT9SY1sKIj5UBhEpQfHc3XzB._u0WbDJ5hzkzp3qHp31dGQ3NRIqJ(_EyrNhzlOC9XfxRuKJ1Vc8VeXIpA , String[] )
   at _pFLYUi2IEGEC895yDwFlhWqtVoD._u0WbDJ5hzkzp3qHp31dGQ3NRIqJ(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 8/15/2021 8:46:14 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1226045517297123530, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.3.0
P3: 61051c0c
P4: KERNELBASE.dll
P5: 10.0.19041.1110
P6: 4809adf2
P7: c0020001
P8: 0000000000034ed9
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD285.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_d6ff39d03409815b9427af91353ea6c2c7c6_c6d645e5_6ba28d5b-c8b6-4b69-9e5b-d66271dcbe64

Analysis symbol: 
Rechecking for solution: 0
Report Id: b124e743-d64b-4efa-984c-200676d44b5a
Report Status: 268566528
Hashed bucket: b29374f67b395f34d103c9e6f0f480ca
Cab Guid: 0 }
--------------
{ TimeGenerated = 8/15/2021 8:46:13 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.3.0
P3: 61051c0c
P4: KERNELBASE.dll
P5: 10.0.19041.1110
P6: 4809adf2
P7: c0020001
P8: 0000000000034ed9
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_d6ff39d03409815b9427af91353ea6c2c7c6_c6d645e5_6ba28d5b-c8b6-4b69-9e5b-d66271dcbe64

Analysis symbol: 
Rechecking for solution: 0
Report Id: b124e743-d64b-4efa-984c-200676d44b5a
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 8/15/2021 8:46:13 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.15.3.0, time stamp: 0x61051c0c
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1110, time stamp: 0x4809adf2
Exception code: 0xc0020001
Fault offset: 0x0000000000034ed9
Faulting process id: 0x28e8
Faulting application start time: 0x01d79248649e57f6
Faulting application path: E:\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: b124e743-d64b-4efa-984c-200676d44b5a
Faulting package full name: 
Faulting package-relative application ID:  }
```
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/6996255/client-main.txt)

**Comment by tyronx** [comment]
Hm. Due to the amount of mods you have installed it is difficult to say if this is a vanilla bug or caused by any of those mods. 
I had a short look at the relevant code and on first glance would not know the cause of this crash.

**Comment by Craluminum2413** [comment]
Closing due to inactivity
