### ISSUE TITLE
Clickling on pickled peppers in the handbook caused a crash

### ISSUE THREAD

**Issue by jdwilward** [anegostudios/VintageStory-Issues#1283]
**Game Version:** 1.15.5  
**Platform:** Windows
**Modded:** Yes

### Description
Clicking on pickled peppers in the handbook seemly caused my game to crash

### How to reproduce
As above

### Logs
```Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.5 (Stable)21/08/2021 15:17:10: Critical error occurred
System.Exception: Can't create itemstack without item!
   at Vintagestory.API.Common.ItemStack..ctor(Item item, Int32 stacksize)
   at Vintagestory.API.Common.CollectibleObject.GetHandbookInfo_Patch0(CollectibleObject this, ItemSlot inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.API.Client.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.GameContent.GuiDialogHandbook.initDetailGui_Patch1(GuiDialogHandbook this)
   at Vintagestory.API.Client.GuiElementHandbookList.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _q065sSmA3CNgGuKTGnlAjR4ljPw._WkSl7yfiyr5DwPiSMvTudNAhp6(_t3ILnyYBq5OoYhhBY3JeTWgFmJDA , String[] )
   at _DBu5wiQWRAHGS5G2jiCKymvQ9yE._WkSl7yfiyr5DwPiSMvTudNAhp6(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 02/08/2021 13:11:10, Site = , Source = Windows Error Reporting, Message = Fault bucket 1803473370194165024, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.3.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Jordan\AppData\Local\Temp\RDR2A92.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2AA2.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2AB3.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2ACA.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2AFA.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 173e3cf4-a855-4e8e-9a54-ebb813226603
Report Status: 268435456
Hashed bucket: 02bffaf4f10c253a69073979984cbd20
Cab Guid: 0 }```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by tyronx** [comment]
hm, i cannot reproduce this. It opens the page just fine for me.

**Comment by jdwilward** [comment]
I have a mod that sorts the handbook maybe it’s related to it? I’ll try to reproduce it with and without the mod tomorrow morning and see what happens if I can, thanks!

**Comment by Craluminum2413** [comment]
I think that mod is Expanded Foods

**Comment by jdwilward** [comment]
Craluminum was right, removing expanded foods has stopped the crash from happening so it is just mod related, thanks!

**Comment by copygirl** [comment]
Thank you for looking into it!
