### ISSUE TITLE
Game Crashed 

### ISSUE THREAD

**Issue by raenbou** [anegostudios/VintageStory-Issues#1288]
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.5 (Stable)8/24/2021 11:54:29 PM: Critical error occurred
System.Exception: Don't know how to instantiate item of class 'ExpandedFood' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass)
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(_mxXW9E9OhteIZNlYAKbUeRziXXE packet, IWorldAccessor world, ClassRegistry registry)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssetsStep1()
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _TKxd5zsRGjdjjLt43mszZSMKrNM._ra0MgpFbqkfgNETNlZ5CppyVnhE(Single )
   at _Wwq7msw90Af4XU7mxkxAUKyrS5B._iIGaTXNE8VYTpgEu9zjpAQyJSxd(Single )
   at _Wwq7msw90Af4XU7mxkxAUKyrS5B._vCB99EztL7cSfmplK8tyTwrQQxC(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _q065sSmA3CNgGuKTGnlAjR4ljPw._WkSl7yfiyr5DwPiSMvTudNAhp6(_t3ILnyYBq5OoYhhBY3JeTWgFmJDA , String[] )
   at _DBu5wiQWRAHGS5G2jiCKymvQ9yE._WkSl7yfiyr5DwPiSMvTudNAhp6(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 8/24/2021 10:58:46 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1658733256924091269, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.5.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\rae\AppData\Local\Temp\RDR1254.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1274.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1285.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER12B2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER12D2.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 00b296a4-c4db-4d0d-8230-f19cba4b9b80
Report Status: 268435456
Hashed bucket: eb8d9853264150393705011bdc165385
Cab Guid: 0 }

**Comment by copygirl** [comment]
Please provide more information regarding when this error occurs.
Do or did you use mods? Did you connect to a multiplayer server?

**Comment by Craluminum2413** [comment]
I see Expanded Foods in the crash log

**Comment by tyronx** [comment]
most likely caused by a 3rd party mod, please reopen ticket otherwise.
