### ISSUE TITLE
Request World Download from Server

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1293]
**Game Version:** 1.15.5
**Platform:** Windows
**Modded:** Unknown 

### Description
Im having trouble with downloading the world from my server.
My game says "World Download Requested, copying in progress.

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.15.5 (Stable)8/29/2021 12:12:38 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _7Gljh9TrtMZNo1VaLv2WsBRLGqD._IzerFHKy7VGQuDWNxLUYvJgrKKb()
   at _Jm1GekeVHONpXWfUYAiJ0gvyjE._lxtmYa4SzyWlslBnrHadOIfFZpi`1._cwNjMeV6CKknPcGV2ZAAMQ2rLzf()
   at _Wwq7msw90Af4XU7mxkxAUKyrS5B._vCB99EztL7cSfmplK8tyTwrQQxC(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _q065sSmA3CNgGuKTGnlAjR4ljPw._WkSl7yfiyr5DwPiSMvTudNAhp6(_t3ILnyYBq5OoYhhBY3JeTWgFmJDA , String[] )
   at _DBu5wiQWRAHGS5G2jiCKymvQ9yE._WkSl7yfiyr5DwPiSMvTudNAhp6(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 8/26/2021 7:26:47 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1658733256924091269, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.5.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\JOSHUA~1\AppData\Local\Temp\RDR74F3.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER74F4.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7505.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER750F.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER752F.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 382c07ef-0e6c-4ec0-8712-009f110df371
Report Status: 268435456
Hashed bucket: eb8d9853264150393705011bdc165385
Cab Guid: 0 }
```

**Comment by tyronx** [comment]
I'll handle this internally
