### ISSUE TITLE
Crash on world loading

### ISSUE THREAD

**Issue by amzy320** [anegostudios/VintageStory-Issues#1297]
**Game Version:** 1.15.5  
**Platform:** Windows
**Modded:** No 

### Description
Crashing on world load up

### How to reproduce
3. It crashes / Thought it was because I changed some world settings in the customize window so tried a world without changing anything and still crashes

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.15.5 (Stable)7/09/2021 5:03:48 PM: Critical error occurred
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.CollectibleObject.Attributes'.
   at CaptureAnimals.ItemCage.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.Common.CreativeTab.CreateSearchCache(IWorldAccessor world)
   at Vintagestory.Common.CreativeTabs.CreateSearchCache(IWorldAccessor world)
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.GuiManager.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.ClientMain.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(_K0gsRhlFmzAJ65AP27fyOAZKCbA packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _TKxd5zsRGjdjjLt43mszZSMKrNM._ra0MgpFbqkfgNETNlZ5CppyVnhE(Single )
   at _Wwq7msw90Af4XU7mxkxAUKyrS5B._iIGaTXNE8VYTpgEu9zjpAQyJSxd(Single )
   at _Wwq7msw90Af4XU7mxkxAUKyrS5B._vCB99EztL7cSfmplK8tyTwrQQxC(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _q065sSmA3CNgGuKTGnlAjR4ljPw._WkSl7yfiyr5DwPiSMvTudNAhp6(_t3ILnyYBq5OoYhhBY3JeTWgFmJDA , String[] )
   at _DBu5wiQWRAHGS5G2jiCKymvQ9yE._WkSl7yfiyr5DwPiSMvTudNAhp6(ThreadStart )
-------------------------------

```

**Comment by Craluminum2413** [comment]
It is because you are using Capture Animals mod

**Comment by amzy320** [comment]
I'm not using any mods and that crash is from a clean install of the game..

**Comment by Craluminum2413** [comment]
Can you check "\AppData\Roaming\VintagestoryData\Mods" and "C:\Vintagestory\Mods" folder?

**Comment by amzy320** [comment]
Oh my goodness there are mods there, thank you so much, I don't remember adding them lol. Thank you :)
