### ISSUE TITLE
Single player server crash

### ISSUE THREAD

**Issue by amygamedestroyer** [anegostudios/VintageStory-Issues#1298]
**Game Version:** 1.15.5  
**Platform:** Windows 
**Modded:** No 

### Description
Every time I launch a single player server it crashes within an hour.

### How to reproduce
Start new single player game server
begin collecting rocks
crash

### Expected behavior
The game to play as normal

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.5 (Stable)9/8/2021 8:52:51 PM: Critical error occurred
System.MissingMethodException: Method not found: 'Void Vintagestory.API.Common.BlockEntity.MarkDirty(Boolean)'.
   at EntityEarthworm.OnGameTick(Single dt)
   at Vintagestory.Client.NoObf.ClientSystemEntities.OnGameTick(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _EMxDKvc7iN7J6hlNFQiKeoxg0Mm._CEmopzLEk14BSqH9plcDEDfmuwE(Single )
   at _Wwq7msw90Af4XU7mxkxAUKyrS5B._iIGaTXNE8VYTpgEu9zjpAQyJSxd(Single )
   at _Wwq7msw90Af4XU7mxkxAUKyrS5B._vCB99EztL7cSfmplK8tyTwrQQxC(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _q065sSmA3CNgGuKTGnlAjR4ljPw._WkSl7yfiyr5DwPiSMvTudNAhp6(_t3ILnyYBq5OoYhhBY3JeTWgFmJDA , String[] )
   at _DBu5wiQWRAHGS5G2jiCKymvQ9yE._WkSl7yfiyr5DwPiSMvTudNAhp6(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 9/6/2021 8:58:58 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2100537241230790266, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Amy\AppData\Local\Temp\RDRAAB3.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAAC4.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAB13.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAB88.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERABF6.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 5a1b1b94-1da3-47b8-a998-f79949f73b82
Report Status: 268435456
Hashed bucket: 6c065c08a80a8fe80d269b7de50a4e7a
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/9/2021 8:05:38 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1259147309639579605, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Amy\AppData\Local\Temp\RDR5E58.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5E69.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5E89.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5EB6.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F05.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 517b45e4-6b09-4b44-842c-53a95ec9cf79
Report Status: 268435456
Hashed bucket: c9b9d3809ce1ec04417963ce8ef4b7d5
Cab Guid: 0 }
--------------
{ TimeGenerated = 5/22/2021 4:35:45 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1564561481470198046, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Amy\AppData\Local\Temp\RDR4B0D.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4B1E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4B5D.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4BB6.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4C15.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: eddc02bf-caeb-4f87-969f-a304d1019295
Report Status: 268435456
Hashed bucket: 2422f0d2706eedebe5b67060c44a411e
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment]
You are using primitive survival - ```at EntityEarthworm.OnGameTick(Single dt)```. Check `\AppData\Roaming\VintagestoryData\Mods` and `C:\Vintagestory\Mods` folders

**Comment by copygirl** [comment]
Indeed. See if you can update the mod to resolve the issue.
The error suggests that it is using a function of the game from an old version that has been changed.

**Comment by amygamedestroyer** [comment]
That's weird, I haven't downloaded any mods at all. I wonder how one got in there.
