### ISSUE TITLE
Crash every time I open new server world settings

### ISSUE THREAD

**Issue by DanaS333** [anegostudios/VintageStory-Issues#1302]
**Game Version:** 1.15.5
**Platform:** Windows 
**Modded:** No

### Description
I started my own server but crash every time I click World Settings.

### How to reproduce
1. Open Game
2. Click World Settings on New and Unused and Unmodded World
3. It crashes / doesn't do the thing.

### Expected behavior
To see world settings and adjust them.

### Screenshots
N/A

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.5 (Stable)9/17/2021 8:58:58 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _7Gljh9TrtMZNo1VaLv2WsBRLGqD._k3HNuFNIxfLTSbJR73yAJdfKAGc(EnumAuthServerResponse , GameServerConfigResponse )
   at _Jm1GekeVHONpXWfUYAiJ0gvyjE._lxtmYa4SzyWlslBnrHadOIfFZpi`1._cwNjMeV6CKknPcGV2ZAAMQ2rLzf()
   at _Wwq7msw90Af4XU7mxkxAUKyrS5B._vCB99EztL7cSfmplK8tyTwrQQxC(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _q065sSmA3CNgGuKTGnlAjR4ljPw._WkSl7yfiyr5DwPiSMvTudNAhp6(_t3ILnyYBq5OoYhhBY3JeTWgFmJDA , String[] )
   at _DBu5wiQWRAHGS5G2jiCKymvQ9yE._WkSl7yfiyr5DwPiSMvTudNAhp6(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 9/15/2021 3:59:47 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1775098558742058606, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.5.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\danas\AppData\Local\Temp\RDRE780.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE790.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE791.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE7B2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE7E2.tmp.txt

These files may be available here:



```

**Comment by copygirl** [comment]
Just out of curiosity: You can still play on this server?

**Comment by DanaS333** [comment]
I've yet to try and play on the server but I can give it a try. I just bought it about 30min ago.

**Comment by DanaS333** [comment]
![vin](https://user-images.githubusercontent.com/90912096/133788200-fab2f2a1-a118-48de-bbb7-fc8869441d59.PNG)
What happens when I tried to join the game.

**Comment by DanaS333** [comment]
Alright, I managed to get into the server this time!

**Comment by DanaS333** [comment]
After being able to get in and restarting to attempt to get into World Settings, it still crashed when I clicked the option.

**Comment by copygirl** [comment]
Thanks. I've poked the team so they can look into this.

**Comment by DanaS333** [comment]
Cool!

**Comment by tyronx** [comment]
Hey, can you please write me a support ticket here: https://www.vintagestory.at/support/

**Comment by DanaS333** [comment]
I have a support ticket open there already. Would you like another?

**Comment by DanaS333** [comment]
Bump.

**Comment by tyronx** [comment]
nope, thats good, thanks, i was not able to reproduce it, can you still?

**Comment by copygirl** [comment]
Going to assume fixed for now. Please comment and/or reopen, if not.
