### ISSUE TITLE
Game crashes on trying to open recipes for some items

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1310]
**Game Version:** 1.15.6-rc.2 
**Platform:** Windows
**Modded:** No

### Description
- Board
- Log

### How to reproduce
1. Click on the ingredient (from description) in any recipe in the handbook
2. It crashes

### Logs
```
Version: v1.15.6-rc.2 (Unstable)09/19/2021 15:11:52: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.CollectibleObject.OnCreatedByCrafting(ItemSlot[] allInputslots, ItemSlot outputSlot, GridRecipe byRecipe)
   at Vintagestory.API.Common.CollectibleObject.GetHandbookInfo(ItemSlot inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.API.Client.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.GameContent.GuiDialogHandbook.initDetailGui()
   at Vintagestory.GameContent.GuiDialogHandbook.OpenDetailPageFor(String pageCode)
   at Vintagestory.API.Client.SlideshowGridRecipeTextComponent.OnMouseDown(MouseEvent args)
   at Vintagestory.API.Client.GuiElementRichtext.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse)
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs)
   at Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _tWK3XnqdKwEz32DZgEFtVG3UU4k._ZGFqinpvIwFTz7F68DuIhzHOWm(_0yeWQ9WAjs9sBw2gtkuglYTlTmO , String[] )
   at _O6YHJJOUkiLLqUHLpLxBur1CoDP._ZGFqinpvIwFTz7F68DuIhzHOWm(ThreadStart )
```

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in rc.3
