### ISSUE TITLE
Game crashes on trying to copy pulverizer top in creative gamemode

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1315]
**Game Version:** 1.15.6-rc.2
**Platform:** Windows
**Modded:** No

### How to reproduce
1. Get creative gamemode
2. Place a pulverizer
3. Look at pulverizer-top then press middle-click to copy it 
4. It crashes

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.6-rc.2 (Unstable)09/20/2021 18:08:04: Critical error occurred
System.ArgumentException: Trying to render an empty VAO
   at Vintagestory.Client.NoObf.ClientPlatformWindows.RenderMesh(MeshRef modelRef)
   at Vintagestory.Client.NoObf.SystemRenderHeldItem.RenderFpHandItem(ItemSlot inSlot, Boolean left, Single dt)
   at Vintagestory.Client.NoObf.SystemRenderHeldItem.OnRender3dOpaque(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _5PLCV9nT6lKYshnvhcLKYmPbSv2._SDEctPLMGfsOebRp3QVxVEQCiUh(Single )
   at _DXJNEmwVJN2e1mVFBQ5fTNR95yc._aLrho8PYHXGJeKPDayUCeRClMEf(Single )
   at _DXJNEmwVJN2e1mVFBQ5fTNR95yc._fFzUEjicM6tZAbcIuKZDCkHSfMJ(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _tWK3XnqdKwEz32DZgEFtVG3UU4k._ZGFqinpvIwFTz7F68DuIhzHOWm(_0yeWQ9WAjs9sBw2gtkuglYTlTmO , String[] )
   at _O6YHJJOUkiLLqUHLpLxBur1CoDP._ZGFqinpvIwFTz7F68DuIhzHOWm(ThreadStart )
```

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next release
