### ISSUE TITLE
Floating point Not-a-Number Seemingly Random Crash

### ISSUE THREAD

**Issue by Trexdude** [anegostudios/VintageStory-Issues#1317]
**Game Version:** v1.15.6-rc.2
**Platform:** Windows 7
**Modded:** No

### Description
Occasional floating point Not-a-number crash that seemingly has no direct cause that occurs, different from the OnCollideWithLiquid crash that's been happening in this unstable version.

### How to reproduce
Not sure, this seemingly happens with particle physics so maybe when mining? But I think I've had this before when accessing object inventories and jumping at the same time.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.6-rc.2 (Unstable)9/20/2021 10:08:59 PM: Critical error occurred
System.ArithmeticException: Function does not accept floating point Not-a-Number values.
   at System.Math.Sign(Double value)
   at Vintagestory.API.Client.ParticlePhysics.UpdateMotion(Vec3d pos, Vec3d motion, Single size)
   at Vintagestory.Client.NoObf.ParticleGeneric.TickNow(Single lifedt, Single pdt, ICoreClientAPI api, ParticlePhysics physicsSim)
   at Vintagestory.API.Common.ParticleBase.TickFixedStep(Single dt, ICoreClientAPI api, ParticlePhysics physicsSim)
   at Vintagestory.Client.NoObf.ParticlePoolQuads.OnNewFrame(Single dt, Vec3d cameraPos)
   at Vintagestory.Client.NoObf.SystemRenderParticles.Render(Int32 poolindex, Single dt)
   at Vintagestory.Client.NoObf.SystemRenderParticles.OnRenderFrame3D(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _5PLCV9nT6lKYshnvhcLKYmPbSv2._SDEctPLMGfsOebRp3QVxVEQCiUh(Single )
   at _DXJNEmwVJN2e1mVFBQ5fTNR95yc._aLrho8PYHXGJeKPDayUCeRClMEf(Single )
   at _DXJNEmwVJN2e1mVFBQ5fTNR95yc._fFzUEjicM6tZAbcIuKZDCkHSfMJ(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _tWK3XnqdKwEz32DZgEFtVG3UU4k._ZGFqinpvIwFTz7F68DuIhzHOWm(_0yeWQ9WAjs9sBw2gtkuglYTlTmO , String[] )
   at _O6YHJJOUkiLLqUHLpLxBur1CoDP._ZGFqinpvIwFTz7F68DuIhzHOWm(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 9/20/2021 7:58:21 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 000007FEFD62B87D
Stack:
 }
--------------
{ TimeGenerated = 9/19/2021 8:49:32 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 000007FEFD18B87D
Stack:
 }
--------------
{ TimeGenerated = 9/11/2021 2:37:46 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 262699778, type 303842243
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 6.1.7601.2.1.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
C:\Users\Trexdude\AppData\Local\Temp\RDR1846.tmp\empty.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 5ac88f9e-132f-11ec-a0c4-7427ead944f7
Report Status: 0 }
```

**Comment by Trexdude** [comment]
This issue may've been reported before but I'm posting it here in case it ain't been yet.

**Comment by Trexdude** [comment]
Specifically I think I've had this crash before when accessing a jar's inventory and jumping at the same time, I ain't sure if it was the same crash but maybe then it has something to do with movement and/or animation of the player character.

**Comment by tyronx** [comment]
please let me know if this still happens in rc.3

**Comment by Trexdude** [comment]
> please let me know if this still happens in rc.3

Will do.

**Comment by copygirl** [comment]
Assuming issue fixed.
