### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Melidebby** [anegostudios/VintageStory-Issues#1330]
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.6 (Stable)2021-09-25 3:18:57 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Datastructures.SyncedTreeAttribute.GetAttributeByPath(String path)
   at Vintagestory.API.Datastructures.SyncedTreeAttribute.PartialUpdate(String path, Byte[] data)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityAttributeUpdatePacket(_xJn1VSUDRUrokUBITa8ABz2qiNe p)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityBulkAttributesPacket(_f1U4e3yQ0nLDe8M5mN80luHf3ix packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _nUTCCwkT1CsTiy64OnOpdL40c6I._y0LduyPz6SS7hpGWh17f3f2ZnCW(Single )
   at _8ECD8nssQiL9uSD9vAFETn80rqE._YxuqUIHpNderNcZTb6YFhogmWOS(Single )
   at _8ECD8nssQiL9uSD9vAFETn80rqE._7qo1BKsjBXLbbifnICE8jHmvIH9(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _AP7WmUsyUYdtMlYkY1BnRzdg2ff._hdLzsTvaMxWzkcSVpoYJjLUlwAJ(_JsdNdoNt0XlKjq0tdupAM4oO6wn , String[] )
   at _0VK7uR5tb5rsnOGVuF83gJuGw9D._hdLzsTvaMxWzkcSVpoYJjLUlwAJ(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2021-09-14 5:01:15 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1775098558742058606, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.5.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\RubyG\AppData\Local\Temp\RDR8F1F.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8F20.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8F40.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8F89.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8FB9.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: eeb75309-4355-44ca-96e4-7fc49949aaa9
Report Status: 268435456
Hashed bucket: d490f7f3f456e29178a26abbfb20d66e
Cab Guid: 0 }
--------------
{ TimeGenerated = 2021-07-02 8:10:28 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1999085723610005733, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\RubyG\AppData\Local\Temp\RDRF60B.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF61B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF62C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF649.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF679.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 759271ee-b944-4ccb-bc86-2658797b1343
Report Status: 268435456
Hashed bucket: ee3def5252484136fbbe2ddfbf5440e5
Cab Guid: 0 }
--------------
{ TimeGenerated = 2021-05-28 6:01:27 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1999085723610005733, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\RubyG\AppData\Local\Temp\RDRD98E.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD9AE.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD9BF.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD9DC.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD9FD.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 636b4158-ad0b-424d-aed5-363018802c71
Report Status: 268435456
Hashed bucket: ee3def5252484136fbbe2ddfbf5440e5
Cab Guid: 0 }

**Comment by copygirl** [comment]
I don't suppose you know what you did when this crash occurred?

**Comment by Melidebby** [comment]
I set up a marker on the map for a adventure and was running towards it and
it was an extremely long distance away. I got so far then the game just
crashed.

**Comment by copygirl** [comment]
Thank you.

**Comment by Craluminum2413** [comment]
Closing due to inactivity
