### ISSUE TITLE
Game crashes when using the map. 

### ISSUE THREAD

**Issue by loveandbarley** [anegostudios/VintageStory-Issues#1356]
When playing, can consistently recreate error by opening map (pressing m) then scrolling out and moving the map around. 
--
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.6 (Stable)10/11/2021 3:31:53 PM: Critical error occurred
ProtoBuf.ProtoException: Unconsumed data left in the buffer; this suggests corrupt input
   at ProtoBuf.ProtoReader.CheckFullyConsumed()
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context)
   at ProtoBuf.Serializer.Deserialize[T](Stream source)
   at Vintagestory.API.Util.SerializerUtil.Deserialize[T](Byte[] data)
   at Vintagestory.GameContent.MapDB.GetMapPiece(Vec2i chunkCoord)
   at Vintagestory.GameContent.ChunkMapLayer.OnOffThreadTick(Single dt)
   at Vintagestory.GameContent.WorldMapManager.<OnLoaded>b__23_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
------------------------------
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/7324912/client-crash.txt)
-

**Comment by Ragolution** [comment]
Could you please fill out the format so we can know what, if any, mods you've used?
Also, I wasn't able to reproduce this with the ascribed steps, so there might be something you're leaving out.
Are there any other conditions which you think could've caused this? Did you remove mods recently, maybe?

**Comment by tyronx** [comment]
You can work around the issue by deleting the local map cache in %AppData%/VintagestoryData/Maps/

If you have multiple maps that you want to keep, you can find the affected map by the joining the world and typing `/info ident`

**Comment by tyronx** [comment]
yes, it would start you with a blank map. You can try and recover it if you have a bit of knowledge with the command line: https://wiki.vintagestory.at/index.php?title=Repairing_a_corrupt_savegame_or_worldmap

**Comment by tyronx** [comment]
Crash avoidance is now added, thanks for the report.
