### ISSUE TITLE
game crshes when loading world

### ISSUE THREAD

**Issue by sniper172te** [anegostudios/VintageStory-Issues#1357]
**Game Version:** X.Y.Z  
**Platform:** Windows / Mac / Linux (which?)  
**Modded:** No / Yes (which?)  

### Description
Explain the issue you're running into.

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash between the triple backticks.
Running on 64 bit Windows with 8 GB RAM 
Version: v1.15.7 (Stable)2021-10-13 4:39:20 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.Common.CreativeTab.CreateSearchCache(IWorldAccessor world)
   at Vintagestory.Common.CreativeTabs.CreateSearchCache(IWorldAccessor world)
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.GuiManager.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.ClientMain.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(_xWBcRtKtMHsPx2vlMTVIBEZO8Dj packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _iZ5rVmV6HXdQR8IP3qeaCA7PDqb._T9YfRFmW6X4ZcWzG7vSwet0Rgrs(Single )
   at _2hFm1B1DwOk1Z7yF6DtBdLeBFKaA._5soGXezAcR5oyhhq2pmELCuEn2M(Single )
   at _2hFm1B1DwOk1Z7yF6DtBdLeBFKaA._ZzmaNk5IGbtvQ61ssCzCszyBw2n(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _LiN8p156auXcqjjOW5aVAZ0QkUc._fwMbTl3XHB2eqbxoLfc3FpMIE00(_CFodeVozKjT5VhVV66Wv4Bd7r3c , String[] )
   at _qBF2AKwdIhCkNZsjxBA24g20vlH._fwMbTl3XHB2eqbxoLfc3FpMIE00(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2021-10-13 4:27:25 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1397969068706127840, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.7.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Taiger\AppData\Local\Temp\RDR7321.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER743B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7546.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7767.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER78C0.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: a65d14fa-b088-43a7-a68f-6ce269fb8a78
Report Status: 268435456
Hashed bucket: a9e621fc64de545c1366957613365fe0
Cab Guid: 0 }
--------------
{ TimeGenerated = 2021-04-16 8:44:13 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFB09A8D759
Stack:
   at System.Environment._Exit(Int32)
   at System.Environment._Exit(Int32)
   at System.Environment.Exit(Int32)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   at OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double, Double)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h, System.String[])
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(System.Threading.ThreadStart)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._M1VY8jQRHnZmSa0tV4cFASebLsH(System.String[])
 }
--------------
{ TimeGenerated = 2021-04-16 5:43:54 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1564561481470198046, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Taiger\AppData\Local\Temp\RDREEBF.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREFAB.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF077.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF21B.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF316.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 41f9f181-245b-43ff-bbb7-677a87652d9e
Report Status: 268435456
Hashed bucket: 2422f0d2706eedebe5b67060c44a411e
Cab Guid: 0 }

**Comment by sniper172te** [comment]
new

**Comment by tyronx** [comment]
This is a pretty incomplete bug report, I'd need more info. 

Also recommend using the 1.15.7 full installer once, so that the current installation gets removed. There's a chance some old files linger that cause this crash.

**Comment by copygirl** [comment]
No response in 14 days. Closing.
