### ISSUE TITLE
Crashes when loading new and old world.

### ISSUE THREAD

**Issue by LehroJLS** [anegostudios/VintageStory-Issues#1358]
Do not understand whatever format people are talking about I am just pasting what is asked from the launcher, clean install no mods and on different drives same error. Just tried many things is what I mean, any help is appreciated.

Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.6 (Stable)10/14/2021 11:28:14 PM: Critical error occurred
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.BlockBehavior.properties'.
   at XSkills.XSkillsBerryBushBehavior.OnLoaded(ICoreAPI api)
   at Vintagestory.API.Common.CollectibleObject.OnLoaded(ICoreAPI api)
   at Vintagestory.API.Common.Block.OnLoaded(ICoreAPI api)
   at Vintagestory.GameContent.BlockPlant.OnLoaded(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientMain.OnServerBlocksItemsReceivedStep5(Action onCompleted)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _wSTTfpl4m6PEg5bi1ZBK0lA6R0h._ClADUnYQHrAMqPUj22yJuSx9iUh(Single )
   at _8ECD8nssQiL9uSD9vAFETn80rqE._YxuqUIHpNderNcZTb6YFhogmWOS(Single )
   at _8ECD8nssQiL9uSD9vAFETn80rqE._7qo1BKsjBXLbbifnICE8jHmvIH9(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _AP7WmUsyUYdtMlYkY1BnRzdg2ff._hdLzsTvaMxWzkcSVpoYJjLUlwAJ(_JsdNdoNt0XlKjq0tdupAM4oO6wn , String[] )
   at _0VK7uR5tb5rsnOGVuF83gJuGw9D._hdLzsTvaMxWzkcSVpoYJjLUlwAJ(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10/14/2021 11:25:16 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.15.6.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 3f58

Start Time: 01d7c17c91fd13b5

Termination Time: 2

Application Path: C:\Vintagestory\Vintagestory.exe

Report Id: 613aae65-d041-40d3-ab41-274de815fad2

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 10/14/2021 11:25:16 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.6.0
P3: 614dc2b6
P4: 86d0
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8CF2.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8D02.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8D01.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8D22.tmp.txt
\\?\C:\Users\silve\AppData\Local\Temp\WER9168.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_bb42f4c3db35fb7efba6e29c8d0b0b21595a379_6503a0db_80eac930-132f-4964-bdfe-29960dedf90d

Analysis symbol: 
Rechecking for solution: 0
Report Id: 613aae65-d041-40d3-ab41-274de815fad2
Report Status: 97
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/14/2021 11:05:03 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1881389103829658245, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.6.0
P3: 614dc2b6
P4: KERNELBASE.dll
P5: 10.0.19041.1202
P6: c9db1934
P7: c000041d
P8: 0000000000034f99
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD59.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_d06a7999906368ee31a1f1eca4af97f011198a0_6503a0db_e679060b-ee15-458c-9ab1-423e21dad2f6

Analysis symbol: 
Rechecking for solution: 0
Report Id: 3822af7e-a551-42b6-b26d-5e895a564d38
Report Status: 268435456
Hashed bucket: 88d67e295b8930355a1c096c020eaa85
Cab Guid: 0 }

**Comment by LehroJLS** [comment]
Have tried a couple most recent game versions in 1.15.x

**Comment by copygirl** [comment]
Game is running with XSkills mod. Be sure to check both your user-mods folder and the install directory for additional mods.

> `at XSkills.XSkillsBerryBushBehavior.OnLoaded(ICoreAPI api)`
