### ISSUE TITLE
game breaking

### ISSUE THREAD

**Issue by s2d1w3** [anegostudios/VintageStory-Issues#1384]
```Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.7 (Stable)2021-10-28 14:20:02: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.Common.CreativeTab.CreateSearchCache(IWorldAccessor world)
   at Vintagestory.Common.CreativeTabs.CreateSearchCache(IWorldAccessor world)
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.GuiManager.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.ClientMain.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(_xWBcRtKtMHsPx2vlMTVIBEZO8Dj packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _iZ5rVmV6HXdQR8IP3qeaCA7PDqb._T9YfRFmW6X4ZcWzG7vSwet0Rgrs(Single )
   at _2hFm1B1DwOk1Z7yF6DtBdLeBFKaA._5soGXezAcR5oyhhq2pmELCuEn2M(Single )
   at _2hFm1B1DwOk1Z7yF6DtBdLeBFKaA._ZzmaNk5IGbtvQ61ssCzCszyBw2n(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _LiN8p156auXcqjjOW5aVAZ0QkUc._fwMbTl3XHB2eqbxoLfc3FpMIE00(_CFodeVozKjT5VhVV66Wv4Bd7r3c , String[] )
   at _qBF2AKwdIhCkNZsjxBA24g20vlH._fwMbTl3XHB2eqbxoLfc3FpMIE00(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2021-10-28 14:05:06, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.15.7.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 4768

Start Time: 01d7cbf382b38481

Termination Time: 8

Application Path: D:\Games\Vintagestory\Vintagestory.exe

Report Id: 0cd6e4e3-4fcb-476d-9952-c0e5bbfc812c

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 2021-10-28 13:59:47, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.15.7.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 3e40

Start Time: 01d7cbf33ce7cd29

Termination Time: 6

Application Path: D:\Games\Vintagestory\Vintagestory.exe

Report Id: ab1e8dca-f876-4377-9aaa-b481365d41b4

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 2021-10-24 23:34:10, Site = , Source = Windows Error Reporting, Message = Fault bucket 1397969068706127840, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.7.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 
```
no mods enabled

**Comment by copygirl** [comment]
Issue report is incomplete. When does the crash occur? Is this a new or old world?

**Comment by s2d1w3** [comment]
That one is old, it crashes on new worlds as well however.

Den lör 30 okt. 2021 kl 20:41 skrev copygirl ***@***.***>:

**Comment by copygirl** [comment]
Could you try reinstalling the game? Use the full installer, not the updater.

**Comment by Craluminum2413** [comment]
No response for two months

**Comment by copygirl** [comment]
Indeed, will close for now as there's not much we can do.
