### ISSUE TITLE
Crash on right-clicking on a sign in 1.6.0pre1

### ISSUE THREAD

**Issue by PyralIron** [anegostudios/VintageStory-Issues#140]
First I tried to open a sign that was placed in a previous version, then I replaced it and crashed when trying to open it again

```
7/1/2018 5:56:40 PM: Critical error occurred
System.ObjectDisposedException: Cannot access a disposed object.
Object name: '_dCIaIRSdAzJjsBm6005SaVhaXj4'.
   at OpenTK.NativeWindow.EnsureUndisposed()
   at OpenTK.GameWindow.Exit()
   at _b7HHyLP9x8y1DehWXorCxZKeuOW._a4FcmxjduLTZb4rYuqvnRFT3IlX(Exception )
   at _b7HHyLP9x8y1DehWXorCxZKeuOW._urZz2FedFIYIBhtxDCRYGPmGABd(ThreadStart )
   at _66MVpsQ4oZFrzt3x6hAQp6cRc1b._78XaCAhmkyYGkSsFIAY35xV1rCo(String[] )
```

**Comment by tyronx** [comment]
Thank you, fixed for the next release
