### ISSUE TITLE
[Crash] in creative mode when placing grain in a fast-grinding quern

### ISSUE THREAD

**Issue by Rares95** [anegostudios/VintageStory-Issues#1403]
**Game Version:** 1.15.8-rc1
**Platform:** Windows
**Modded:** Yes - but 99.9% sure it't not related as they don't affect these things
**SP/MP:** Singleplayer

### Description
So in creative mode I was trying to add a seed to a quern. I was clicking fast and multiple times in the slot after i added the seed, and it crashed. Probably because the grinding was fast and also my multi-clicking the flax grain in.

### How to reproduce
See description

### Expected behavior
No crash

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.15.8-rc.1 (Unstable)06/11/2021 15:06:59: Critical error occurred
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _vRm47jVIvDyua0N567IgCZq6kNE._PXjaJY1SvS3WsvEyYv7vvhSAtvR(_4wDa0aqDz0mL4VbEs2rMb5z8jIC , String[] )
   at _1lavE4vCw6ubZEZ4vQiL1gwMVtF._PXjaJY1SvS3WsvEyYv7vvhSAtvR(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 16/10/2021 22:38:48, Site = , Source = Windows Error Reporting, Message = Fault bucket 1905483466808130716, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.7.0
P3: 10.0.22000.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\userfolder\AppData\Local\Temp\RDR8EDF.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.20212974-1cc0-4e57-b2cf-5ed3818ecd08.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.714a83cc-a243-46f1-850c-e6a31ee17322.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8a5b9dd3-a3e3-456e-988a-8da20df888f3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.75bd7790-986d-4cf6-ba25-919c820ce69b.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 4e615c93-6ca3-405e-b968-f9f781599de0
Report Status: 268435456
Hashed bucket: c090ac3bdfdc75cffa71a31e0c7a7c9c
Cab Guid: 0 }
--------------
{ TimeGenerated = 13/10/2021 19:40:29, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangTransient
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.6.0
P3: 614dc2b6
P4: unknown
P5: unknown
P6: unknown
P7: unknown
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.87c9ee52-2d7a-4ec6-8a91-79b184957237.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.986ce1c1-5371-4305-9578-51c561b0abbe.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4dc0436f-f614-43f0-a932-e44037fbe781.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.99fabf67-e17c-40b0-b0b1-7f5960312cbf.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: d81e92c8-6861-4a33-991c-7db885224050
Report Status: 2049
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 16/09/2021 21:02:12, Site = , Source = Windows Error Reporting, Message = Fault bucket 1350128271266373572, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.5.0
P3: 10.0.22000.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\userfolder\AppData\Local\Temp\RDRBE6F.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f7688e04-b02f-463f-bb77-ad7f36f117a8.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e4fe215d-f951-4c37-8872-90b803af2354.tmp.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20210915_1 EC_0_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.24089f46-d6b1-4760-ba63-644f022e1424.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f08dd2dd-d19e-4cca-b09c-64cf38164208.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.3d5713a6-40a6-47f6-973c-e16af26a9bb3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.5bff4436-45cc-4260-8549-efcee63b7332.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 6741e86a-e214-494b-9e9f-db9bcad8e5f9
Report Status: 268435456
Hashed bucket: a2940450ac09f90112bc9e826a0b5fc4
Cab Guid: 0 }
```

**Comment by copygirl** [comment]
As seen in #1404, does not require creative mode. Might be a rare occurrence.

**Comment by Craluminum2413** [comment]
Closing due to inactivity
