### ISSUE TITLE
[Crash] when adding more sulfur to mechanized quern

### ISSUE THREAD

**Issue by martinkozle** [anegostudios/VintageStory-Issues#1404]
**Game Version:** 1.15.8-rc.1  
**Platform:** Windows
**Modded:** No
**SP/MP:** Multiplayer

### Description
Quern was automated and was crushing sulfur, and I added another half stack to the input, and the client crashed. Server was still up. Connected again, and the sulfur had actually been placed in and finished crushing.

### How to reproduce
Not sure if it is reproduceable, haven't tested it, only happened to me once.
1. Make an automated quern crushing sulfur
2. Make the "Inventory and Crafting" window movable and move it? (Not sure if this is has to do with it)
3. While it is crushing add more sulfur to the input
4. It crashes the exact same frame you left click on the sulfur

### Expected behavior
I expected it to add the sulfur to the slot and not crash.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.8-rc.1 (Unstable)06-Nov-21 16:39:58: Critical error occurred
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _vRm47jVIvDyua0N567IgCZq6kNE._PXjaJY1SvS3WsvEyYv7vvhSAtvR(_4wDa0aqDz0mL4VbEs2rMb5z8jIC , String[] )
   at _1lavE4vCw6ubZEZ4vQiL1gwMVtF._PXjaJY1SvS3WsvEyYv7vvhSAtvR(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 30-Oct-21 14:42:28, Site = , Source = Windows Error Reporting, Message = Fault bucket 1397969068706127840, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.7.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\MARTIN~1\AppData\Local\Temp\RDRF9F2.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFA03.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFA13.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFA21.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFA51.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 1bb70cf5-d3f5-4521-9af1-c092ecd8a827
Report Status: 268435456
Hashed bucket: a9e621fc64de545c1366957613365fe0
Cab Guid: 0 }
```

**Comment by martinkozle** [comment]
Seems related to #1403

**Comment by Craluminum2413** [comment]
For the quern itself, it's literally the same item as in other issue

**Comment by copygirl** [comment]
Same crash as #1403, reported just and hour earlier. Thank you for reporting though!
