### ISSUE TITLE
Crash on Customize World press

### ISSUE THREAD

**Issue by bjatta** [anegostudios/VintageStory-Issues#1408]
Running on 64 bit Windows with 32 GB RAM 
Version: v1.15.9 (Stable)11/11/2021 11:26:45 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.WorldConfig.Clone()
   at _2eEeOywAkIaZ7yw7jOVsByAKZPvA._zhpucJteidWabFwyvU23VFdcdTG()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _j4MEcbYtN5VOdfII1yL8Ce7wETF._L13DLEzxm9yEC6meaySeGvMRlqv(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _M48MnHH5BAvHUzcYoEuchRW0acb._e0atQ8VmmvgBK7zb3Yh4iDqOiHY(_UGHNIsOGTJBe1BTRXYmLwHTbmS , String[] )
   at _xNqQDGqRsRSMIeuzt2MHKQHDzSd._e0atQ8VmmvgBK7zb3Yh4iDqOiHY(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/10/2021 10:09:08 AM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.15.9.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 4aa4

Start Time: 01d7d6118aeddd2a

Termination Time: 2

Application Path: D:\games\Vintagestory\Vintagestory.exe

Report Id: 91c777b8-464a-49dd-91e0-350fa5dca6fe

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 11/10/2021 10:09:08 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.9.0
P3: 6187ffbc
P4: 86d0
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDB1D.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDB2E.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDB2D.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDB4D.tmp.txt
\\?\C:\Users\bjatt\AppData\Local\Temp\WERE2B1.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_3c65cf41918f8c66958b4d1cb411a22e3f455d_e052d6cd_1e50652d-e181-421b-9950-32197eda7f3b

Analysis symbol: 
Rechecking for solution: 0
Report Id: 91c777b8-464a-49dd-91e0-350fa5dca6fe
Report Status: 97
Hashed bucket: 
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
Closing due to inactivity
