### ISSUE TITLE
Game crash on reconnecting to server after making porridge

### ISSUE THREAD

**Issue by MarkBrad** [anegostudios/VintageStory-Issues#1414]
**Game Version:** 15.9 stable 
**Platform:** Windows 
**Modded:** No
**SP/MP:**  / Multiplayer

### Description
Joined MP server, all ok. Made my first pot of rye porridge. Went to feth bowels. Couldn't place any bloacks (eg tried soil and the bowels and pot) All would appear then disappear. Discoonected from server to try a relog. On trying to reconnect, game crashed with following  log message. Tried several time to reconnet all with failure

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
Game Crashed

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.15.9 (Stable)15/11/2021 17:24:38: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.GeneralPacketHandler.<>c.<HandleServerAssets>b__21_0()
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _pGnDS8PRrVztoyRAoNqXbYkko9B._TshCCJvNc6laaisiRTK6RNaXWQ1A(Single )
   at _o0lbNJXQO06me4d8j661Kh7y0zO._HmSBpw6fP4XFLEcv29tc0ifOKYvb(Single )
   at _o0lbNJXQO06me4d8j661Kh7y0zO._3U99eoPu0PaDLPVrL8tfzH5UDEJ(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _M48MnHH5BAvHUzcYoEuchRW0acb._e0atQ8VmmvgBK7zb3Yh4iDqOiHY(_UGHNIsOGTJBe1BTRXYmLwHTbmS , String[] )
   at _xNqQDGqRsRSMIeuzt2MHKQHDzSd._e0atQ8VmmvgBK7zb3Yh4iDqOiHY(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 21/10/2021 15:16:10, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.7.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Mark\AppData\Local\Temp\RDRE89D.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE8AD.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE8BE.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE8CC.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE8EC.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 1e44dab0-7c2d-40ba-8146-ab53a5c52cea
Report Status: 536871008
Hashed bucket: 
Cab Guid: 0 }
```

**Comment by RogueRaiden** [comment]
Ive had an issue on my server that ends up causing exactly this for almost all clients involved for my server. Usually happens when a new player is connecting for the first time. If it doesnt go through correctly, they end up getting stuck when downloading the server data and some clients become unable to place blocks or objects causing an error in the console and log any time they attempt:
[Notification] Client Vik tried to place a block but rejected because it would intersect with another player

it seems it can be fixed with a restart or sometimes fixes itself after a bit

[Logs.zip](https://github.com/anegostudios/VintageStory-Issues/files/7644210/Logs.zip)
t

**Comment by Craluminum2413** [comment]
Closing due to inactivity
