### ISSUE TITLE
Picking up crucible after updating game to newest version results in crash

### ISSUE THREAD

**Issue by GilanRanger** [anegostudios/VintageStory-Issues#1419]
**Game Version:**v1.15.9 (Stable)  
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
When I try to use right-click on crucible filled with cooled solid copper it results in the game crashing with a NullPointerException. Might have to do with the fact I just updated to the newest version from a version that is a few months old.

### How to reproduce
1. Set a crucible on the ground as a block, filled with cooled copper
2. Right-click on it to pick it back up
3. It crashes

### Expected behavior
Probably shouldn't crash

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.15.9 (Stable)11/18/2021 3:31:02 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockSmeltedContainer.GetHeldItemName(ItemStack itemStack)
   at Vintagestory.API.Common.Block.GetPlacedBlockName(IWorldAccessor world, BlockPos pos)
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.ComposeBlockInfoHud()
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.OnBlockChanged(BlockPos pos, Block oldBlock)
   at Vintagestory.API.Client.BlockChangedDelegate.Invoke(BlockPos pos, Block oldBlock)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockChanged(ClientMain game, BlockPos pos, Block oldBlock)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleSetBlock(_oIqeYhLbfggCGH4NJ27Vq8B0RmGA packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _rnlVSzJ2AGPu2719D3re8Z7kN2c._iCctvUrJRYdSyJrBVxt5h8N0k5h(Single )
   at _o0lbNJXQO06me4d8j661Kh7y0zO._HmSBpw6fP4XFLEcv29tc0ifOKYvb(Single )
   at _o0lbNJXQO06me4d8j661Kh7y0zO._3U99eoPu0PaDLPVrL8tfzH5UDEJ(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _M48MnHH5BAvHUzcYoEuchRW0acb._e0atQ8VmmvgBK7zb3Yh4iDqOiHY(_UGHNIsOGTJBe1BTRXYmLwHTbmS , String[] )
   at _xNqQDGqRsRSMIeuzt2MHKQHDzSd._e0atQ8VmmvgBK7zb3Yh4iDqOiHY(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/18/2021 3:23:38 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1824643577228952718, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.9.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Gilan\AppData\Local\Temp\RDR6A4A.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6A4B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6A6C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6A80.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6AB0.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: ad0a8ac9-c7ef-4639-b0cc-8d3bf6b7c67e
Report Status: 268435456
Hashed bucket: 329f53295c09fe7999526faa866e048e
Cab Guid: 0 }
--------------
{ TimeGenerated = 5/27/2021 8:43:51 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1822032227626530173, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Gilan\AppData\Local\Temp\RDRD090.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD091.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD092.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD0A0.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD0C1.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 5139d146-1fbe-40d1-9dd6-db4a54546c39
Report Status: 268435456
Hashed bucket: a995c73cc234971ef94928a850fe357d
Cab Guid: 0 }
--------------
{ TimeGenerated = 4/2/2021 8:19:31 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1822032227626530173, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Gilan\AppData\Local\Temp\RDR2B9B.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2BAC.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2BAD.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2BC7.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2BD8.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 77a6d0bf-4d77-4fe4-9954-04ef6b7db3ca
Report Status: 268435456
Hashed bucket: a995c73cc234971ef94928a850fe357d
Cab Guid: 0 }
```

**Comment by GilanRanger** [comment]
Will also crash if broken instead of picked up.

**Comment by lordnik22** [comment]
Have similar StackTrace:
```
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.GameContent.BlockSmeltedContainer.GetHeldItemName(ItemStack itemStack) in VSSurvivalMod\Block\BlockSmeltedContainer.cs:Zeile 428.
   bei Vintagestory.API.Common.Block.GetPlacedBlockName(IWorldAccessor world, BlockPos pos) in VintagestoryApi\Common\Collectible\Block\Block.cs:Zeile 2085.
   bei Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.ComposeBlockInfoHud() in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:Zeile 56.
   bei Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.OnBlockChanged(BlockPos pos, Block oldBlock) in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:Zeile 218.
   bei Vintagestory.API.Client.BlockChangedDelegate.Invoke(BlockPos pos, Block oldBlock)
   bei Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockChanged(ClientMain game, BlockPos pos, Block oldBlock) in VintagestoryLib\Client\Util\ClientEventManager.cs:Zeile 518.
   bei Vintagestory.Client.NoObf.GeneralPacketHandler.HandleSetBlock(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:Zeile 239.
   bei Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:Zeile 1138.
   bei Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:Zeile 123.
   bei Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:Zeile 678.
   bei Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:Zeile 622.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:Zeile 124.
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 476.
   bei OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 452.
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 375.
   bei Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   bei Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:Zeile 93.
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
