### ISSUE TITLE
`Ground Storage` layouts conflict after a firing in a pit kiln cause crash

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1422]
**Game Version:** 1.15.9
**Platform:** Windows
**Modded:** Yes
**SP/MP:** Singleplayer

### Description
There is no check of different layouts in a pit kiln

### How to reproduce
1. Add `GroundStorable` `Stacking` layout e.g. for cooking pot (`burnt`)
2. Fire e.g. cooking pot (`raw`) with other items in a pit kiln (or something else with `Quadrants`/`Halves`/`SingleCenter` layout)
3. It crashes if you look at a pit kiln when it is done

### Expected behavior
Creates temporary layout?

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.7 (Stable)11/20/2021 9:57:04 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockGroundStorage.GetPlacedBlockInteractionHelp(IWorldAccessor world, BlockSelection selection, IPlayer forPlayer)
   at Vintagestory.Client.NoObf.HudElementBlockInteractionHelp.OnBlockChanged(BlockPos pos, Block oldBlock)
   at Vintagestory.API.Client.BlockChangedDelegate.Invoke(BlockPos pos, Block oldBlock)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockChanged(ClientMain game, BlockPos pos, Block oldBlock)
   at Vintagestory.Client.NoObf.ClientWorldMap.MarkBlockDirty(BlockPos pos, IPlayer skipPlayer)
   at Vintagestory.GameContent.BlockEntityGroundStorage.OnPlayerInteract(IPlayer player, BlockSelection bs)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _gt983m53spH3zIRFvTrVgBj5MUb._T9YfRFmW6X4ZcWzG7vSwet0Rgrs(Single )
   at _2hFm1B1DwOk1Z7yF6DtBdLeBFKaA._5soGXezAcR5oyhhq2pmELCuEn2M(Single )
   at _2hFm1B1DwOk1Z7yF6DtBdLeBFKaA._ZzmaNk5IGbtvQ61ssCzCszyBw2n(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _LiN8p156auXcqjjOW5aVAZ0QkUc._fwMbTl3XHB2eqbxoLfc3FpMIE00(_CFodeVozKjT5VhVV66Wv4Bd7r3c , String[] )
   at _qBF2AKwdIhCkNZsjxBA24g20vlH._fwMbTl3XHB2eqbxoLfc3FpMIE00(ThreadStart )
```

**Comment by Craluminum2413** [comment]
First server
>Getting a crash when interacting with pitkilns with cooking pots in them.
Stopped when I took out More Piles.
Everyone on my server experienced it

Second server
>The game crashed and every time I log back in it crashes immediately again

I know this bug is caused by my mod, this is why "Modded: Yes", but it is legit since it is using "vanilla" game instruments only
