### ISSUE TITLE
Update to 1.15.10 - Crashed on restart

### ISSUE THREAD

**Issue by adambomb73** [anegostudios/VintageStory-Issues#1427]
User: AdamBomb

**Game Version:** X.Y.Z  
**Platform:** Windows / Mac / Linux (which?)   
**Modded:** No / Yes (which?)  
**SP/MP:** Singleplayer / Multiplayer (which?)  

### Description
Game crashed on restart after updating to 1.15.10.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.10 (Stable)11/30/2021 8:03:12 AM: Critical error occurred
System.InvalidOperationException: Could not execute non-optional patch: Regex (^|[\.,+\-*/;{}[\]()=:|^&?#\s])texColor\s*?\.\s*?a\s*?\+\s*?=\s*?max\s*?\(\s*?0\s*?,\s*?diff\s*?/\s*?16\s*?\+\s*?noise\s*?/\s*?4\s*?\)\s*?;($|[\.,+\-*/;{}[\]()=:|^&?#\s]) not matched
   at VolumetricShading.Patch.RegexPatch.Patch(String filename, String code)
   at VolumetricShading.Patch.ShaderPatcher.Patch(String filename, String code, Boolean cache)
   at VolumetricShading.ShaderRegistryPatches.LoadShaderCallsite(ShaderProgram shader, String code, List`1 includes, EnumShaderType type)
   at Vintagestory.Client.NoObf.ShaderRegistry.LoadShader_Patch1(ShaderProgram program, EnumShaderType shaderType, List`1 assetsinclude)
   at Vintagestory.Client.NoObf.ShaderRegistry.loadRegisteredShaderPrograms_Patch0()
   at Vintagestory.Client.NoObf.ShaderAPI.ReloadShaders()
   at Vintagestory.Client.NoObf.SystemModHandler.OnServerIdentificationReceived()
   at Vintagestory.Client.NoObf.ClientMain.ProcessServerIdentification(_TTMS23AwbUUYwtAobecOMgNfDqJ packet)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerIdent(_TTMS23AwbUUYwtAobecOMgNfDqJ packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _M3NcP5TH7TMb4K2x8uUbkjXP7iO._oYniXsjcVAWxLpTiLUivE84wTkA(Single )
   at _R2SaBRGSTE9aIRQAjhFb2LrMpJb._gq2ZjDtIZ3sLq4OCUiRUzkjv3XA(Single )
   at _R2SaBRGSTE9aIRQAjhFb2LrMpJb._tjdmYyEuuoCShcgREvOOHIl2K1G(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _rwEcecUjMyzMSfVPsyS8Wx2kGqk._XiZO0qHpODOJko3v6YCZBF7Z5Se(_2kddpZuU7wcyt2belKg18dkvHxo , String[] )
   at _E5WqgB878qvAOVUQ9yfqu340l7G._XiZO0qHpODOJko3v6YCZBF7Z5Se(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/30/2021 8:03:10 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1425832529100330876, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.10.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\adamb\AppData\Local\Temp\RDRD9B.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDAC.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDBC.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDE9.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE19.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 01036cfa-3878-46e9-8469-e96090059eec
Report Status: 268435456
Hashed bucket: 5d54ad1cf22fc6ba33c993217e38d77c
Cab Guid: 0 }
--------------
{ TimeGenerated = 9/7/2021 9:15:08 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2046779953476928566, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.5.0
P3: 61123ac1
P4: nvoglv64.dll
P5: 30.0.14.7196
P6: 6128d92d
P7: 00000000012370a9
P8: c0000409
P9: 0000000000000007
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA321.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAA55.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAA76.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAA83.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAA94.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_4f20a9298e73b14c738193f83d173dee765e76_23fa4891_acd3e4ab-ac09-4172-9e20-df9f9f14c688

Analysis symbol: 
Rechecking for solution: 0
Report Id: 1ce9da89-d24a-459a-ac4b-c13be845c5f0
Report Status: 268435456
Hashed bucket: fcaa78772d9708c43c679f85fc620436
Cab Guid: 0 }
--------------
{ TimeGenerated = 9/7/2021 9:15:04 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.15.5.0, time stamp: 0x61123ac1
Faulting module name: nvoglv64.dll, version: 30.0.14.7196, time stamp: 0x6128d92d
Exception code: 0xc0000409
Fault offset: 0x00000000012370a9
Faulting process id: 0xed0
Faulting application start time: 0x01d7a456978ad420
Faulting application path: C:\Users\adamb\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\nvmii.inf_amd64_193f04621e226017\nvoglv64.dll
Report Id: 1ce9da89-d24a-459a-ac4b-c13be845c5f0
Faulting package full name: 
Faulting package-relative application ID:  }
```

**Comment by copygirl** [comment]
Indeed. Please report the issue to its mod author.
