### ISSUE TITLE
Crash on trying to spin empty fruit press

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1428]
**Game Version:** 1.16.0-pre.1 
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Place a fruitpress
2. Spin the handle
3. It crashes

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0-pre.1 (Unstable)12/01/2021 13:16:55: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityFruitPress.onTick50ms(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _BUMabDMvB5g1D4cwmJFdUV7RB7B._W4L7Y66LZLXviCHwlVMPC4OkSvq(Single )
   at _SGHyUxV5Rv3GnxQS6X37QfGaYYI._wtaWT1dJOq4AyHDjHsCHfaFTnkQ(Single )
   at _SGHyUxV5Rv3GnxQS6X37QfGaYYI._t0woIE9wg5YcVEaBBPQohFJK0os(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 375
   at _qGIeLvQF356cX6MlSgQecVUPPnB._1UOaKCATq4VGq5WIs6BsnCl9AiN(_hepllT23IKsNQYqswdyIdzYZoCd , String[] )
   at _Va34feq3eOguuxZWZKrRDDWG2xq._1UOaKCATq4VGq5WIs6BsnCl9AiN(ThreadStart )
```

**Comment by Craluminum2413** [comment]
Still persists in pre.3

**Comment by Craluminum2413** [comment]
Just tested in 1.16.0-pre.8 and it doesn't crash anymore, maybe it was fixed in pre.5
