### ISSUE TITLE
Crash on trying to open handbook page for fruit tree cutting

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1429]
**Game Version:** 1.16.0-pre.1
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Open creative inventory
2. Search cutting
3. Press `H` to open its handbook page
4. It crashes

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/144229349-b7990f4f-ec0d-437f-9472-ff786d08e7d3.png)

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0-pre.1 (Unstable)12/01/2021 13:49:09: Critical error occurred
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Vintagestory.GameContent.BlockFruitTreeBranch.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Boolean shading, Boolean origRotate, Boolean showStackSize)
   at Vintagestory.API.Client.SlideshowItemstackTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY)
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime)
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime)
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _BUMabDMvB5g1D4cwmJFdUV7RB7B._nA3yaaylsiYnA09wfmcvIIKlcbN(Single )
   at _SGHyUxV5Rv3GnxQS6X37QfGaYYI._wtaWT1dJOq4AyHDjHsCHfaFTnkQ(Single )
   at _SGHyUxV5Rv3GnxQS6X37QfGaYYI._t0woIE9wg5YcVEaBBPQohFJK0os(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 375
   at _qGIeLvQF356cX6MlSgQecVUPPnB._1UOaKCATq4VGq5WIs6BsnCl9AiN(_hepllT23IKsNQYqswdyIdzYZoCd , String[] )
   at _Va34feq3eOguuxZWZKrRDDWG2xq._1UOaKCATq4VGq5WIs6BsnCl9AiN(ThreadStart )
```

**Comment by Craluminum2413** [comment]
Fixed in 1.16.0-pre.4
