### ISSUE TITLE
(Ground Storage) Crash on trying to place an item without shape

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1438]
**Game Version:** 1.16.0-pre.2  
**Platform:** Windows
**Modded:** Yes ([IWPEI](https://mods.vintagestory.at/iwpei))
**SP/MP:** Singleplayer

### Description
In 1.15.x, items without shape could be placed with `GroundStorable` behavior, but now it crashes instead

### How to reproduce
1. Add `GroundStorable` behavior with e.g. `Quadrants` layout to any item **without shape** or use IWPEI mod
2. Get the item e.g. hide or leather
3. Try to place it on the ground
4. It crashes
### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0-pre.2 (Unstable)12/02/2021 13:37:48: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityDisplay.genMesh(ItemStack stack)
   at Vintagestory.GameContent.BlockEntityGroundStorage.getOrCreateMesh(ItemSlot itemSlot, Vec3f offset)
   at Vintagestory.GameContent.BlockEntityGroundStorage.updateMeshes()
   at Vintagestory.GameContent.BlockEntityGroundStorage.OnPlayerInteractStart(IPlayer player, BlockSelection bs)
   at Vintagestory.GameContent.BlockGroundStorage.CreateStorage(IWorldAccessor world, BlockSelection blockSel, IPlayer player)
   at Vintagestory.GameContent.CollectibleBehaviorGroundStorable.Interact(ItemSlot itemslot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handHandling, EnumHandling& handling)
   at Vintagestory.API.Common.CollectibleObject.<>c__DisplayClass92_0.<OnHeldInteractStart>b__0(CollectibleBehavior bh, EnumHandling& hd)
   at Vintagestory.API.Common.CollectibleObject.WalkBehaviors(CollectibleBehaviorDelegate onBehavior, Action defaultAction)
   at Vintagestory.API.Common.CollectibleObject.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _9Q8fpX846Gx1pPUNQUDGlwGZBUB._cWnaco3up3FiXKqGQT8glrRJojK(Single )
   at _HRfDngnpBWTmEXiuwbRWkFKyJZs._yD9dPRZ9ZRfOdiu0s7HyEILMuoJ(Single )
   at _HRfDngnpBWTmEXiuwbRWkFKyJZs._vMYtOR2pAjMmy8Ygu8WqEmFNp0r(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 375
   at _aeznW7dUzRtbc6gGqfLLAAGPvUF._HH2M6AmcpFUMki4uDKOPMndAYft(_hFZgobIYoX0BrM3J1kokPKB9IqB , String[] )
   at _D1bjqjMU3djkJ14p5zl8JiWp0sG._HH2M6AmcpFUMki4uDKOPMndAYft(ThreadStart )
```

**Comment by Craluminum2413** [comment]
Have no idea in which version it get fixed, but I'm not able to reproduce it in 1,16.0-rc.5
