### ISSUE TITLE
Game crashes after world was loaded

### ISSUE THREAD

**Issue by Vasiliyhop** [anegostudios/VintageStory-Issues#1442]
**Game Version:** 1.15.10
**Platform:** Windows 10  
**Modded:**  Yes 
**SP/MP:** Singleplayer 

### Description
Game crashes after world was loaded

### How to reproduce
1. I don't know. It crashes on my world.

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.15.10 (Stable)12/2/2021 9:20:29 PM: Critical error occurred
System.ArgumentException: Fatal: Trying to render an uninitialized or disposed mesh
   at Vintagestory.Client.NoObf.ClientPlatformWindows.RenderMesh(MeshRef modelRef)
   at Vintagestory.GameContent.BEAnimatableRenderer.OnRenderFrame(Single dt, EnumRenderStage stage)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _37NyQC3j7xjnAt2h09BqVJtTM8J._Gd91jD2RZpLWue9im8O82g8B3Mn(Single )
   at _R2SaBRGSTE9aIRQAjhFb2LrMpJb._gq2ZjDtIZ3sLq4OCUiRUzkjv3XA(Single )
   at _R2SaBRGSTE9aIRQAjhFb2LrMpJb._tjdmYyEuuoCShcgREvOOHIl2K1G(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _rwEcecUjMyzMSfVPsyS8Wx2kGqk._XiZO0qHpODOJko3v6YCZBF7Z5Se(_2kddpZuU7wcyt2belKg18dkvHxo , String[] )
   at _E5WqgB878qvAOVUQ9yfqu340l7G._XiZO0qHpODOJko3v6YCZBF7Z5Se(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/27/2021 10:03:55 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1425832529100330876, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.10.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\vasil\AppData\Local\Temp\RDR6C7B.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6C8B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6C9C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6CC9.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6CDA.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 22c82f37-fd19-418c-a0d7-bb95043c339d
Report Status: 268435456
Hashed bucket: 5d54ad1cf22fc6ba33c993217e38d77c
Cab Guid: 0 }
--------------
{ TimeGenerated = 9/24/2021 8:00:31 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1298668709714251717, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.6.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\vasil\AppData\Local\Temp\RDRDA2F.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDA40.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDA50.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDA7D.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDA9D.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: fff77f41-77b0-4edb-901d-b15958ca560b
Report Status: 268435456
Hashed bucket: 8f39dc2e068300f29205cc4f936ecfc5
Cab Guid: 0 }
--------------
{ TimeGenerated = 8/18/2021 9:58:04 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.Server.ServerMain.Stop(System.String)
   at _q065sSmA3CNgGuKTGnlAjR4ljPw._jv5ACTxQ2zYdp9fsBzvU76QFoiQ()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

 }
```

**Comment by Craluminum2413** [comment]
What mods you used?

**Comment by Vasiliyhop** [comment]
Bunch of mods.
But I turned them off, then on, And now everything is ok.
I don't know what was cause of crash.
Now, I am going to close issue.
