### ISSUE TITLE
Crash on trying to put any item into the barrel liquid slot

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1457]
**Game Version:** 1,16.0-pre.4  
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Place a barrel
2. Put a salt into it
3. It crashes

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0-pre.4 (Unstable)12/05/2021 23:59:22: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.GuiDialogBarrel.fullnessMeterDraw(Context ctx, ImageSurface surface, ElementBounds currentBounds)
   at Vintagestory.API.Client.GuiElementCustomDraw.Redraw()
   at Vintagestory.GameContent.GuiDialogBarrel.UpdateContents()
   at Vintagestory.GameContent.BlockEntityBarrel.Inventory_SlotModified(Int32 slotId)
   at Vintagestory.API.Common.InventoryBase.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack)
   at Vintagestory.API.Common.ItemSlot.MarkDirty()
   at Vintagestory.API.Common.ItemSlotBarrelInput.OnItemSlotModified(ItemStack stack)
   at Vintagestory.API.Common.ItemSlot.TryPutInto(ItemSlot sinkSlot, ItemStackMoveOperation& op)
   at Vintagestory.Common.PlayerInventoryManager.TryTransferAway(ItemSlot sourceSlot, ItemStackMoveOperation& op, Boolean onlyPlayerInventory, StringBuilder shiftClickDebugText, Boolean slotNotifyEffect)
   at Vintagestory.API.Common.InventoryBase.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse)
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs)
   at Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 792
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 368
   at _0nHMj3ZyzuUD5RQAfs2MzHe55tl._RPVo3GRPmOwZIPP2T9xyc693xVf(_bB0LepbgyiNByBczs3ZgA7xZ3yp , String[] )
   at _7EQaQlsWtbAF9t3X3tTsUlfNlG1._RPVo3GRPmOwZIPP2T9xyc693xVf(ThreadStart )
```

**Comment by Craluminum2413** [comment]
Fixed in 1.16.0-pre.7
