### ISSUE TITLE
No errors when recipes are wrong that cause crash on opening handbook page for every item and block

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1459]
**Game Version:** 1.16.0-pre.5
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Download [ExpandedLiquidContainers-test.zip](https://github.com/anegostudios/VintageStory-Issues/files/7677889/ExpandedLiquidContainers-test.zip)
2. Load any world
3. Try to open handbook page for any item or block
4. It crashes

### Logs
```
Version: v1.16.0-pre.5 (Unstable)12/06/2021 18:02:48: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.CollectibleBehaviorHandbooked.GetHandbookInfo(ItemSlot inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.GameContent.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.GameContent.GuiDialogHandbook.initDetailGui()
   at Vintagestory.GameContent.GuiDialogHandbook.OpenDetailPageFor(String pageCode)
   at Vintagestory.GameContent.ModSystemHandbook.OnHelpHotkey(KeyCombination key)
   at _fPSOgCzvpopKZNAvT6kblkrjyqq._VD1iD9ZPtwx7t8B6dqVxnj4VWJc(KeyEvent , IWorldAccessor , IPlayer , Boolean , Boolean , Boolean )
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(Object sender, KeyboardKeyEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnKeyDown(Key key, Boolean repeat) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\Platform\NativeWindowBase.cs:line 129
   at OpenTK.Platform.Windows.WinGLNative.HandleKeyboard(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 639
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 828
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 368
   at _vHAaSwOEpE8hP7rHXHAVfarBMzJ._3JGMejUhgcQ4gIgTXeJSa5WiSBI(_6ZjejMlO4MtGoD7BKumilh2bR4N , String[] )
   at _B9TtsAmaR1ybtkoF2Fu00RmPoF7._3JGMejUhgcQ4gIgTXeJSa5WiSBI(ThreadStart )
```

**Comment by tyronx** [comment]
thanks this should be fixed (both the missing error log and the crash)
