### ISSUE TITLE
Crash when applying remap when updating from 1.16.0 pre-4 to 1.16.0 pre-5

### ISSUE THREAD

**Issue by Stainlessfool** [anegostudios/VintageStory-Issues#1460]
**Game Version:** 1.16.0 pre-5 
**Platform:** Windows 
**Modded:** No
**SP/MP:** Singleplayer 

### Description
Explain the issue you're running into.

### How to reproduce
1. Make a new world in game version 1.16.0 pre-4
2. Download and apply update 1.16.0 pre-5
3. Load saved game and apply remap when prompt
### Expected behavior
remap should work as intended 
### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
Running on 64 bit Windows with 32 GB RAM 
Version: v1.16.0-pre.5 (Unstable)12/6/2021 2:43:01 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at VSHUD.WaypointUtils.Dispose()
   at Vintagestory.Common.ModLoader.Dispose()
   at Vintagestory.Client.NoObf.ClientMain.Dispose()
   at Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected)
   at _J6QlHFLa8J4u3XLxJmC6W5aVGfk._jci38lCdLKohHuocm5lIMtqVcSY(Boolean , String )
   at _J6QlHFLa8J4u3XLxJmC6W5aVGfk._JhPwABZGkwvf17rk71MrB5KaFu4(String )
   at _FJTtALWOt4DRGfis9GGpLin5cok._0wZAtMyFihawFrCllkSdOLgvVI0(KeyCombination )
   at Vintagestory.Client.NoObf.GuiDialogConfirmRemapping.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.GuiManager.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _J6QlHFLa8J4u3XLxJmC6W5aVGfk._lc7tkPy0b03LIc2a96tWaZyhq5Q(Single )
   at _FJTtALWOt4DRGfis9GGpLin5cok._81iBWkqGDe2dMPc6UlQU4ajuEDH(Single )
   at _FJTtALWOt4DRGfis9GGpLin5cok._tE8xoRO21xXzWKEyIdXRiTxgr5C(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 375
   at _vHAaSwOEpE8hP7rHXHAVfarBMzJ._3JGMejUhgcQ4gIgTXeJSa5WiSBI(_6ZjejMlO4MtGoD7BKumilh2bR4N , String[] )
   at _B9TtsAmaR1ybtkoF2Fu00RmPoF7._3JGMejUhgcQ4gIgTXeJSa5WiSBI(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/2/2021 9:52:18 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2137399946764805085, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\stain\AppData\Local\Temp\RDRF79A.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF79B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF7AB.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF7B6.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF7D6.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 65361c68-1b8a-490e-bb3b-9467545090e9
Report Status: 268435456
Hashed bucket: 90206cb8882a62a92da991ed59dae3dd
Cab Guid: 0 }
--------------
{ TimeGenerated = 9/26/2021 7:31:12 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1298668709714251717, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.6.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\stain\AppData\Local\Temp\RDRCCF4.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCD05.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCD06.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCD13.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCD43.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 33766069-dbb6-4a68-b48d-b8a8eb35ef7c
Report Status: 268435456
Hashed bucket: 8f39dc2e068300f29205cc4f936ecfc5
Cab Guid: 0 }
--------------
{ TimeGenerated = 8/26/2021 8:37:22 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.5.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\stain\AppData\Local\Temp\RDR5B7.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5B8.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5C9.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5E6.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER607.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: dcd2b07a-a9b3-43a8-82df-ac8c4e56c15e
Report Status: 536870914
Hashed bucket: 
Cab Guid: 0 }
```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
``
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/7663169/client-main.txt)
`

**Comment by Craluminum2413** [comment]
The problem is in VSHUD mod

**Comment by copygirl** [comment]
Yes. There are some additional errors that occur when the game is loading, also related to VSHUD.
Please report this to the mod author.
```
6.12.2021 14:42:36 [Error] [vshud] An exception was thrown when trying to start the mod:
System.TypeLoadException: Could not load type 'Vintagestory.API.Common.Action`1' from assembly 'VintagestoryAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at VSHUD.ModSystemNotification.StartClientSide(ICoreClientAPI api)
   at Vintagestory.Common.ModLoader.TryStartSystem(Mod mod, ModSystem system, ICoreAPI api, ModEventPhase phase)
6.12.2021 14:42:36 [Error] Failed to start system VSHUD.ModSystemNotification
6.12.2021 14:42:36 [Error] [vshud] An exception was thrown when trying to start the mod:
System.TypeLoadException: Could not load type 'Vintagestory.API.Common.Action' from assembly 'VintagestoryAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at VSHUD.ClaimUI.StartClientSide(ICoreClientAPI api)
   at Vintagestory.Common.ModLoader.TryStartSystem(Mod mod, ModSystem system, ICoreAPI api, ModEventPhase phase)
6.12.2021 14:42:36 [Error] Failed to start system VSHUD.ClaimUI
6.12.2021 14:42:36 [Error] [vshud] An exception was thrown when trying to start the mod:
System.TypeLoadException: Could not load type 'Vintagestory.API.Common.Action' from assembly 'VintagestoryAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at VSHUD.PlacementPreview.StartClientSide(ICoreClientAPI api)
   at Vintagestory.Common.ModLoader.TryStartSystem(Mod mod, ModSystem system, ICoreAPI api, ModEventPhase phase)
6.12.2021 14:42:36 [Error] Failed to start system VSHUD.PlacementPreview
6.12.2021 14:42:36 [Error] [vshud] An exception was thrown when trying to start the mod:
System.TypeLoadException: Could not load type 'Vintagestory.API.Common.Action`1' from assembly 'VintagestoryAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at VSHUD.ClockDialogSystem.StartClientSide(ICoreClientAPI api)
   at Vintagestory.Common.ModLoader.TryStartSystem(Mod mod, ModSystem system, ICoreAPI api, ModEventPhase phase)
6.12.2021 14:42:36 [Error] Failed to start system VSHUD.ClockDialogSystem
6.12.2021 14:42:36 [Error] [vshud] An exception was thrown when trying to start the mod:
System.MissingMethodException: Method not found: '!!0 Vintagestory.API.Common.IModLoader.GetModSystem()'.
   at VSHUD.LightUtilModSystem.StartClientSide(ICoreClientAPI api)
   at Vintagestory.Common.ModLoader.TryStartSystem(Mod mod, ModSystem system, ICoreAPI api, ModEventPhase phase)
6.12.2021 14:42:36 [Error] Failed to start system VSHUD.LightUtilModSystem
6.12.2021 14:42:36 [Error] [vshud] An exception was thrown when trying to start the mod:
System.TypeLoadException: Could not load type 'Vintagestory.API.Common.Action' from assembly 'VintagestoryAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at VSHUD.WaypointUtils.StartClientSide(ICoreClientAPI api)
   at Vintagestory.Common.ModLoader.TryStartSystem(Mod mod, ModSystem system, ICoreAPI api, ModEventPhase phase)
6.12.2021 14:42:36 [Error] Failed to start system VSHUD.WaypointUtils
6.12.2021 14:42:36 [Notification] Harmony Patched Methods: onSave, TriggerNewServerChatLine, NowProcessChunks, OnHeldIdle, OnHeldIdle, SpawnBlockEntity, ExchangeBlock, SetBlock, Initialize, OnDataFromServer, 
6.12.2021 14:42:36 [Error] [vshud] An exception was thrown when trying to start the mod:
System.TypeLoadException: Could not load type 'Vintagestory.API.Common.Action' from assembly 'VintagestoryAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at VSHUD.VSHUDMain.StartClientSide(ICoreClientAPI api)
   at Vintagestory.Common.ModLoader.TryStartSystem(Mod mod, ModSystem system, ICoreAPI api, ModEventPhase phase)
6.12.2021 14:42:36 [Error] Failed to start system VSHUD.VSHUDMain
6.12.2021 14:42:36 [Notification] Loaded Shaderprogramm for render pass rift. 
6.12.2021 14:42:36 [Notification] Loaded Shaderprogramm for render pass sleepoverlay. 
6.12.2021 14:42:36 [Error] [vshud] An exception was thrown when trying to start the mod:
System.MissingMethodException: Method not found: '!!0 Vintagestory.API.Common.IModLoader.GetModSystem()'.
   at VSHUD.CommandRegistry.StartClientSide(ICoreClientAPI api)
   at Vintagestory.Common.ModLoader.TryStartSystem(Mod mod, ModSystem system, ICoreAPI api, ModEventPhase phase)
6.12.2021 14:42:36 [Error] Failed to start system VSHUD.CommandRegistry
```
