### ISSUE TITLE
Crash when right-clicking a bucket when holding a barrel

### ISSUE THREAD

**Issue by Shionsan** [anegostudios/VintageStory-Issues#1461]
**Game Version:** 1.16.0.pre5
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
Right-click a bucket while holding a barrel.

### Logs
```
Running on 64 bit Windows with 64 GB RAM 
Version: v1.16.0-pre.5 (Unstable)07.12.2021 6:48:04: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockLiquidContainerBase.GetContent(ItemStack containerStack)
   at Vintagestory.GameContent.BlockLiquidContainerBase.GetNutritionProperties(IWorldAccessor world, ItemStack itemstack, Entity forEntity)
   at Vintagestory.API.Common.CollectibleObject.GetHeldTpUseAnimation(ItemSlot activeHotbarSlot, Entity forEntity)
   at Vintagestory.API.Common.EntityAgent.HandleHandAnimations()
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt)
   at Vintagestory.Client.NoObf.ClientSystemEntities.OnGameTick(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _J6QlHFLa8J4u3XLxJmC6W5aVGfk._PRI5DfWZIQ12FiiK5ZqyonWKWx(Single )
   at _FJTtALWOt4DRGfis9GGpLin5cok._81iBWkqGDe2dMPc6UlQU4ajuEDH(Single )
   at _FJTtALWOt4DRGfis9GGpLin5cok._tE8xoRO21xXzWKEyIdXRiTxgr5C(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 375
   at _vHAaSwOEpE8hP7rHXHAVfarBMzJ._3JGMejUhgcQ4gIgTXeJSa5WiSBI(_6ZjejMlO4MtGoD7BKumilh2bR4N , String[] )
   at _B9TtsAmaR1ybtkoF2Fu00RmPoF7._3JGMejUhgcQ4gIgTXeJSa5WiSBI(ThreadStart )
-------------------------------
```

**Comment by copygirl** [comment]
Looks like the same issue as #1437, so closing as duplicate. Thank you for reporting!
