### ISSUE TITLE
Server thread crash when importing a particular selection

### ISSUE THREAD

**Issue by syntaxaire** [anegostudios/VintageStory-Issues#1462]
Steps to reproduce:
Start a creative world in the latest version (currently 1.16.0-pre5)
Import the selection attached to this issue
Server thread will crash with:
```
[Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityMicroBlock.get_LightHsv()
   at Vintagestory.GameContent.BlockMicroBlock.GetLightHsv(IBlockAccessor blockAccessor, BlockPos pos, ItemStack stack)
   at Vintagestory.Server.ServerSystemRelight.UpdateBlockLight(Int32 oldblockid, Int32 newblockid, BlockPos pos)
   at Vintagestory.Server.ServerSystemRelight.ProcessLightingQueue()
   at Vintagestory.Server.ServerThread.Update()
   at Vintagestory.Server.ServerThread.Process()
```
This selection is from a world that was upgraded from 1.15 using 1.16.0-pre4, exported on 1.16.0-pre4 and crashes both 1.16.0-pre4 and pre5.

The selection is included below:

```
{"GameVersion":"1.16.0-pre.4","SizeX":4,"SizeY":6,"SizeZ":5,"BlockCodes":{"2429":"cobblestone-peridotite","5054":"rock-redmarble","5045":"rock-slate","2705":"rockpolished-slate","6134":"planks-aged","6135":"planks-birch","2220":"soil-low-none","2426":"cobblestone-sandstone","1913":"slantedroofing-thatch-east-free","6138":"planks-pine","2431":"cobblestone-slate","7032":"firepit-cold","2425":"cobblestone-granite","7172":"table-normal","3614":"drystonefence-slate-w-free","148":"chiseledblock","331":"oillamp-east","1421":"torchholder-aged-filled-west","7113":"painting-elk-west","6934":"chair-plain","493":"caveart-chalk-1-3-2"},"ItemCodes":{},"Indices":[0,1024,2048,3072,4096,1048576,1049600,1050624,1051648,1052672,2097152,2098176,2099200,2100224,2101248,3145728,3146752,3147776,3148800,3149824,4194304,4195328,4196352,4197376,4198400,1,1025,2049,3073,4097,1048577,1049601,1050625,1051649,1052673,2097153,2098177,2099201,2100225,2101249,3145729,3146753,3147777,3148801,3149825,4194305,4195329,4196353,4197377,4198401,5242881,5243905,5244929,5245953,5246977,2,1026,3074,4098,1048578,2098178,2099202,2100226,2101250,3147778,5242882,5243906,5244930,5245954,5246978,3075,4099,1052675],"BlockIds":[2220,2220,2429,2220,2220,2220,2220,2429,2220,2220,2220,2220,2220,2220,2220,2426,2426,2426,2426,2426,1913,1913,1913,1913,1913,6138,2429,2431,2429,6138,6138,2429,7032,2429,6138,6138,2429,2429,2429,6138,2426,2426,2426,2426,2426,2425,2425,2425,2425,2425,1913,1913,1913,1913,1913,7172,3614,3614,7172,148,331,1421,331,7113,148,6138,6138,6138,6138,6138,6934,7172,148],"DecorIndices":[2048,1050624,1025,1025,3073,3073,1049601,1049601,1051649,1051649,2098177,2099201,2099201,2100225],"DecorIds":[16777709,16777709,16777709,33554925,493,16777709,16777709,33554925,493,16777709,16777709,16777709,83886573,16777709],"BlockEntities":{"1050625":"!<d@[F*PTs#64c-E,TfCD?'Y:!<d@[F*bAG#64o6@VfsmCI<#NAIN0bEb03(F=h!@Ch*_VBl8**DKKf;Gl\\+hF)5c:EsD[F!!WUJCi=E:!!!-7Ap&-3@:NkJASlBtEaa'4Eb,4NTKrSgD..ZgASlBtEaa'4Eb2lb!!!-3DfTDVDf9E*DJ)p_D.N\\I!!!-1Ap%[$6?R<d<,$2\\z\":o?XGXcgeCdN8bDH(=eAH2]1!!=!JG][Y;B6@p0BOt^RDffE(88iWkEuEG_kl2pA5R@m0@;\\YLDJ=3(7Wi9Y!!EX=@:Nt^A4C]QC]FG8!!!","1048578":"!<d@[F*PWt#64c-E,TfCD?'Y:!<d@[F*b;E#64o6@VfsmCI<#NAIW-_Bldj%ARo7dDe!Pj$#O*mATDKnCi][Y!!%ER!!'_H!!'D?!!!B3@s)7!Bk29d!!!!#=Khc\\30aMR=I&q#32$=n=I0#o2-^.r8<Erf>+kpA=ec$T\\:Xi>]<_Q,8<a-S8;.%C\\Wm5L=I9)a[Yb*]8ZDct[;>oN[sJ+^\\;^NrBq#.A[sS5+[s\\8;[&sHF=HNS0Vf`%uVI]ftW.b:AWPej<WjMn.>f?c0VRZ`(V-3kqWN#uqX1A;MUeLj.=e,QSX3Le>UoshHQ=9nRPuIfC\\W[(qCrHEeQGruLAnM0gQZiFQBW(uUCUXA\"B6XKdPY2\"rR@O@;\\t]=.N5YjBL1^L1LmS0dR\\p42Mmi\\ALNifSMPpNaMQ6`dMnB)\"N8\"BRMQHn^SAbMSQ=g8ER$[r#S$rHUQZrRgR]$:u\\XNU,fWY>o\\<-h2b+Seb\\Y9./XMk6UaHlma\\<m9=WLX#N[rVUDfTZD@\\:jp`\\Z,WLaH6HbfTQ>@fTcKM`EWF\\fTlLF$Zg3(G@Pc)DeWa'$NL/,__k[!F#]Kd'0;fejKu&ijfH`-k,Z2r[uK,B41hg!bf*feI)qWS*6OrT$P@#lDfor.;f6Mt6ZljVBk2:_zz!>#52![%IC\"#']T\"@)qe\"],1!#%.E2#B0YC#_2mT$'5,e$D7A!$a9U2%);iC%F>(T%c@<e&+BQ\"&-)\\2&J+pC&g./T'/0Ce'L2X!'i4l2(17+C(N9?T.\"D9u.?FN1.\\HbB>He).*5DOT*RFce*oI#!+7K73+92BC+V4VT+s6je,;9*!,X;>2,u=RC-=?fT-ZB%e/AM5e/^OJ!0&Q^20CSrD0E;(T0b=<e1*?Q!1GAe21dD$C2IHLe2fJa!4MUq!4jX0252ZDC5O\\XU5QCce5nF#!66H726SJKC9Y^W2:!`kC:>c*T:[e>f:]LJ!;%N^2;BPrC;_S1T?-iQT?Jkee?gn%\"?iU02@1WDC@NYXT@k[leD9r7eDVtL!Dt!`3Du]kCE=`*TEZb>eF\"dS!Ic(22J+*FDJ,fQTJIheeJfk%!K.m92No0mCO73,UO8o7eOUqL!Ors`2P:utCS^7?CT&9STTC;gfTE\"s!Tb%22U*'FCUG)ZTXj@%TY2B9eYODN\"YQ+Y2Yn-mCZ60,TZS2@e]YFLT^!H`e^>Ju!^[M43^]4?C_%6ST_B8ge__;'!`'=;2`aAcTa)D\"egTUYdbeO2ec-QG!cJS[2cgUoDci=%Td1?9edNAN!dkCb2e3F!CePH5TemJIef:W*QgqWn!h9Z-2hV\\AChs^UUhuE`ei=Gu!iZJ42j\"LHCj?N\\Tj\\Ppek$S0!kAUD2k^WXCl&YlTlC\\+el`^@!m(`T2mEbhCmbe'Tn*g;fn,NG!nIP[2nfRoCo.U.ToKWBeohYW!p0[k2pM^*Cpj`>Tq2bReqOdg!qlg&2r4i:CrQkNTrnmbes6p!o$>\"'gFAlmaAO158!!!92F(o/r;f?JdA,uZ1#S1ujA7\\&CD/XK;;f?JdA,uZ1\"USXSDe!QX@;TQl8T\\BWBjkm%:i(8k@V'Qe/KeM>DfTOl","3147778":"!<d@[F*PWt#64c-E,TfCDu]k<!<d@[F*bAG#64o6@VfsmCI<#NAIW-_Bldj%ARo7dDe!Pj$#O*mATDKnCi]UW!!'D?!!!B3@s)7!Bk29/!WW3#&-2b2!Up(#0Cf)c!\"T&P1i`R=(t&C<\"B,:S[rVO'.?a`c/$f40%G_\"<&,uVp2IleQ.\"hRc)Pd@0\"]YP!-ZoDc.?sm0)moZR#%mpD.#%_0.]*2b#C$5f$((^3$b$+d\"]tbT#`&JR\"^M,$#`8VT$EX<$/BRss$dA[e#+Yb@\"&/db&MF.R\"-3HO$GQT1%dsAu'2\\`1*8pku+7K7B5p64?2K8^/(pO&a0&cjc-\"?p0.\"_LS.\\ctu/AqNS7s\"_s.?jfu/$o:R.\"qXu.]!,R-[#Ju/%,G?)Q<_1)nH$S.]WQc/)1-P4Pg(s+:\\D1&WQkM3kbUa'Q4!A(ln[e0E2\"R5nF\"t,uFXD-=?fTHa3VQ:!iqB0&ZdC+:/#\\,XDDCRA'Zogq`t75p?:Q/CFMR+X@%C,=;Gd/b8s/1fOHA0(]-A+W18X,;oO\",\\6sR/B%Te0E(r\\+t!A\"-\"d3e/`m%R,Y.oU-[5W3.)u=>,<5aU-!:5\".]<?!/_L,U0'E:u+t3MT-><IC.#n:j/'.dc0'WGB+<(<d1J7_R-#N^g.@gIE/)('@,<c+E2h(hE9!&*10(/eg+>!TA6r!a141tXR+tire5S!kc3j/PS/&))T4l65A0E;(T1*?Q!8tZ.d9Y^W15Oe^e1GJkSaFXDu5oTg11+N@B7W/:E8<3bg8Xoe00g,Nc2.$@43M$6\":At7R1Htm20cpDe1f\",C4O4!178j0h\\:FV_8WWoT:?2Bh?i^6AUd4tp:\\Fc65QUp26qIA([rMHo]Ya^p:\"0/\"5q)djR'Zi]9ZI-45R@Ei7]?AeX0hq<:?DP0:AOsT9Z[:A5RRS!6qdTf7V`\"28?2`t9[*RU7sk<T:Ab+A5RmeD67i2u9!/-t:]LJ!@k[ldAmbTB=)e3D?gn%1[8?oM`aSpJSAkP/XjmD_S$i=9@nZma?sWj+@4qWR;a19T<F5b!B7Bmc@1iPEA3^,!BqPG1D<([4@Q=E([W)9_DuTea?ig<TA6AmjQ=^+d?l8r6QZ`?uXMb*>Lo(/QT'$)cS_!jbB#t%-D<LtsDX%51?l]6UJnk@pGhW5<A_d@;JkZ6rDXRSfL5l8rBqGCfHJSYq?k382A5<4!Ao@\\CG`MjuCsN(dEZb>ePu%GcGAmNeMP'qSI)#^eIc(2BF#!_3Xjd=uJJ%r1Pu7T0Y2fRQJQ2\\oJk,lsQ\"U/QR@+&AE>\\bCR#(g0R`PPrNTgGPNp?\\sE?5,3Q!OIBLV3]NJkc=/Id[:2F$B[!F^G.CHER;SM3%]SbH_*bTCMt1J-#^!JjTMtJJ/#C[8R&bO88iIYQOr>O9P\\uJJS<\"JlVkrJ-Q(![:]JaQ\\YWdRE#;`Rcja=O9koSQ>$>dLNrluMp)12J.DXiLl;>DMQ?ffNSOTUJp[R>M4=ReNpQhfO8K\"1VJQ=cXN^b/RB?PbKMMUCLOT=!N6_M!TDnltP;3+EPX#3TbHLsQSA5+2T&BYUTC;h0PX5@AZSVYRPZ7]TYOhftO9GVeP;N>CW.b4SR?dhUR\\^!uR\"bTTTCr81PXtk3O9biCP;rW2Q!\"+/YRCNbOW=GTP>2,2Q[JkeRCrURXmQ2BYPeIcQ>ZcfW/^lBX3L_0TDeidQ!XOeR'-JsYn@$DU*9RE[U9(BWhTP4TE5*3__M3A^[_@c[UT:uW.Y.3]<_K0Yp9<AV/u]0X0_k1XMk0C^?#?P[Whe0W/(G2bNJq`^\\@fOYoEbtV-O)TW/Uf2\\ul%eX1\\MuTFV%fTe6?1UeUpdZ7c4SXks*dZS2@e[86i2[r;<T^!cs#_BJt!g7eQdcJ\\aRciO1t[8HuT^>f2T__V9S\\t]6ecgq-0[r_US^\\%SB^]sjT_);:/[<;Oc\\X<G5]B90@YrMf2[s%h!ch@EtYR(;f[93L!`b>FB[s7tCbLllb^A.c@YU]^c[;5iT\\a'7=Z9/-1[sS21^`<F0\\Xife`bkeB[snDDcMdh@_`n.ug91MRci3tRiZJ40e3O'CacZW4g7SESgqWmucg^uTk$\\60fRX#Bc-ZMB_%Qf\"`'XMUm(r`bdN\\`ScK\"t!fRs5uacuj\"lD+DRbJaHTc-u_ech%3B_*n?/`ao-TaFsV1hW=fSch7?dadE-VbNAka`b5@2fSBNt^e\"NraGBnuc0>;A_)hY@`bYY!fSfgSanu.odOkOT_bL3ebK^+Cc2@Y/^`NRCfT-%!ae&S\"g9(GRe5$)Bgs5uuhX:FRf73i1hV\\AcdNSZCmc\"40oKrUAp1\"(sdNefee3j:2m)/luhW+ZRcisJedO\"s2e4'FTf7j9Bgr9>Rcj0W2dO5*Te49S!f6@:TgrKJThWOsAcjBcTdOG7!e4K_Cf89R1gr]W!hWb*ccjTp!dOYCCe4p\"gf7!_Eg8tA\"gs,oEhX1C\"fSon0dOtS1i=Q&\"j\"UNDj\\u3ik$S0!l&l#fiZS:CpMg0SrQtTtj?`i!k&LGSlEUCBmEttukCWb0l')0CmF2+XnIYaCo.^4eohb]2q2kY!qlp,Cs7$(RnIkmeq3(eCqm-8erR1a2s764tn-&f!o/-MToi2!!pN6ICq3:qeqm?E2rRCmTs7HAAnJ;1To/?Z!oiD-CpNHUeq3M)2qmQQTrRV%!s7ZMcnJM>!o/QfCoiV9epNZb2q3_5Tqmc^!rRh1Cs7lZ0nJ_JCo/creokOQBpmV8uqmujCrS%=es8)fRnJqVeo0!*2oj%RTpO*&!q4.NCqn3!erS7J2s8;rtnK.c2o036TomZuAq4@ZeqnE.2rSIVTs8N',$Zg3(G@Pc)DeWa'>lXj)n,SLLcjAM.n.,Hui?/U1nI[DSiA6Jo;(7b1iB#fq+Wg1SdP2aBnff^enh0qBo0<fddm>Vdj#N\\2j%fRRZp>W2jJ5NN1dt=CoL<a!`(,1ToLP#C`(?I!j@ZQT<(jV!e4e*e6qu/2j^9\\@oi5?!-!\"ITok/aS79H>cAR!.S<F+,Tk*%t/k*9fap3;Vup1^-!k'HFqp2Bs2kA`*SkD+Kdf6Nnepj`kTG_$Y2k^kDeka8LQfSf+spn.Qdae0%Bfo[9Tfp@*el)X4PlCfg19!^>Sg8/WdMPl71lIrB@g9:GTgTV[uqm%jTbI)]t/'*;BlcG^u]=[A/qp59Br4jBSm*[Kdr52;1m)EoCm*!ZSgs+XTr8-lBc-Qk!rR=UC4n`@crRd/2rS5^!*q9gB*o\\mS54h2B:?>FT53IOu:?ePS0'hKs?gn4!s78GTs7K_!s7_!C^\\F8us80P2s8CgTs8W*!$P@#lDfor.;f6Mt6ZljVBk29#!!!!%;_S1T?LRq\"Du]kCJ+*FEOrs`3WK7)fZp4U\"`D?OCf5L^!d1?9edkCb2ePH5TfoQ1CgTUYeh9Z-2hs^UUhuE`en*g;fnfRoCqOdg!r4i:Crnmb^$>\"'gFAlmaAO158!!!92F(o/r;f?JdA,uZ1#S1ujA7\\&CD/XK;;f?JdA,uZ1\"USXSDe!QX@;TQ_;f#laAKZ#3@qu&","1052675":"!<d@[F*PZu#64c-E,TfCD?'Y:!<d@[F*bGI#64o6@VfsmCI<#NAIW-_Bldj%ARo7dDe!Pj$#O*mATDKnCi]^Z!!&,g!!'_H!!)^/!!)a0!!!B3@s)7!Bk29nznF6K$&/#!d&i'G0'N+rS(30Bt(m4nB)R9>c*7=j1*qB:b!>GVi\"#C$6*Rb'E+7oUY0G4@01,8kS1f=;t2KAgB30F7c3jJc14OO3R54S_0+VY#6,;TEX4jsHg5P,\"&:_EdS;DJ4t<)N`B<cS0c=HW\\1>-\\,R>g`Wu?Le(Q5njDX6Seg%?./j4?h=CHE\"W-tE\\[YBFA`)cG&dU1G`i%RHEmPuI*r!AIe!Lt@2&f%@l\"3GIFA6VJ+NdjO:hRBOtm\"cPYqN1Q>usRR$%IuR^)oASC.EdT(2k@JJ82GK/3TiS^RX#TC`17YS$pcZ8)G1Zr-lR[W2Bu\\<6hA]!;>d][?d0^@D:cTbISiUGE!6^!d$E^[qRYck6@1dP:eRe5?;ueoCaAfTH7dg9L]0gsQ3ShXUY/_%Zu6__VBXh9uEght-t&n.G^RnhL4uoMPZAp2U0dplYV0qQ^,Sr6bQtrpg(Ri=lAXj\"gd%rR1g4s7?@#$Zg3(G@Pc)DeWa'6N@)d+RfF45QMQ!+S$]V0EX*2+S<MN+:[lA+V>=e+VQU20ce^C+o^I$5p,_!66R$C1*\\RT+t_4C+trKe,;Bf2,;V(T1Hj1e6U12C6pVLe1da&!,Yc\\e,Z!t2,uG9T,uZQ!2-nZ27:5Ze7UZu22IeNC->h02-?&GT-ZKb!-Z_$C2gs-T7t:.28:_HT3.j!e.#lXT.$*p!.?P5C.?cLe3M\"V!8Y>VT8tcq!3hnJ2.]q,!.^/CC/$T]e/$gu242')C9>C*!9YhDC4MrrT/BuTC/C3ke/^Y12/^lHT4l+Qe:#GRC:>lle53\"F!0(%'e0(8?20C]YT0Cpq!5Q0%2:]L%e#RY-[Blm9fA7\\&F!<<**$$0fkAQ*M`Bk.5E+:&L!Bk1d@Ci+*3FAm*oBk.5E+9`'\\Ci<g!:18!N&4:,BF)rI&ATS7d/PTqsF8u"},"Entities":[],"ReplaceMode":2}
```

**Comment by syntaxaire** [comment]
No longer reproducible on 1.16.0-pre7.
