### ISSUE TITLE
Error on "worldconfig classExclusiveRecipes" change

### ISSUE THREAD

**Issue by Shionsan** [anegostudios/VintageStory-Issues#1466]
**Game Version:** 1.16.0-pre5
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Change of classExclusiveRecipes value triggers an error.

### How to reproduce
Just enter this command into the chat /worldconfig classExclusiveRecipes false

### Logs
```
8.12.2021 10:00:35 [Notification] Handling Command /worldconfig classExclusiveRecipes false
8.12.2021 10:00:35 [Error] Player Shion/BQcnbh5wAN1R8C2nw/sMt0/y caused an exception through a command.
8.12.2021 10:00:35 [Error] Command: /worldconfig
8.12.2021 10:00:35 [Error] Arguments: classExclusiveRecipes false
8.12.2021 10:00:35 [Error] Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Vintagestory.Server.CmdWorldConfig.Handle(IServerPlayer player, Int32 groupId, CmdArgs args)
   at Vintagestory.Common.EventManager.TriggerChatCommand(IPlayer player, Int32 channelId, String command, CmdArgs args)
   at Vintagestory.Server.CoreServerEventManager.TriggerChatCommand(IPlayer player, Int32 channelId, String command, CmdArgs args)
   at Vintagestory.Server.ServerMain.HandleCommand(IServerPlayer player, Int32 groupid, String command, String argument)
8.12.2021 10:00:35 [Error]    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Vintagestory.Server.CmdWorldConfig.Handle(IServerPlayer player, Int32 groupId, CmdArgs args)
   at Vintagestory.Common.EventManager.TriggerChatCommand(IPlayer player, Int32 channelId, String command, CmdArgs args)
   at Vintagestory.Server.CoreServerEventManager.TriggerChatCommand(IPlayer player, Int32 channelId, String command, CmdArgs args)
   at Vintagestory.Server.ServerMain.HandleCommand(IServerPlayer player, Int32 groupid, String command, String argument)
```

**Comment by tyronx** [comment]
thanks for the report! should be fixed next release
