### ISSUE TITLE
Export selection, then reimport in creative crashes to desktop

### ISSUE THREAD

**Issue by syntaxaire** [anegostudios/VintageStory-Issues#1472]
**Game Version:** 1.16.0-pre7
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Exporting a particular selection, then importing it in creative mode, crashes the game client to desktop.

### How to reproduce
Import the block data attached: [thousand_suns.txt](https://github.com/anegostudios/VintageStory-Issues/files/7689245/thousand_suns.txt) (github won't allow .json uploads so rename)

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.16.0-pre.7 (Unstable)2021-12-09 6:27:59 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntitySign.set_MeshAngleRad(Single value)
   at Vintagestory.GameContent.BlockEntitySign.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving)
   at Vintagestory.Client.NoObf.ClientSystemEntities.createBlockEntityFromPacket(_NO63MlyDmFJMjGS9ovcPCFVkmmR packet, ClientMain game)
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(_NO63MlyDmFJMjGS9ovcPCFVkmmR p, ClientMain game)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(_tO9ZgC7cx9MCgCHLBJu7A0lSISg packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _xBQAg1Ed6CcXytaXXvOmWUEdxL7._k6NRS5nPX1QSgyNNRQGaWeLhKqD(Single )
   at _rbXziUUUKbZppQKhKM3hsf3ruBd._CtnLbpc7J2uRazUnof31R0UP56e(Single )
   at _rbXziUUUKbZppQKhKM3hsf3ruBd._Pmevnh9xHIGVAbdE0I1e7BOOUwq(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 375
   at _ZtH2ArOfMIrN7aW2XZGTRtDcnRv._pfKV6yBov4GCenLFkBHL50hygNB(_AHthcC6i7Fwv4849Hy6Llb7MiCr , String[] )
   at _mZVhRHqMFCvG5YWxn9mvtH9aP8J._pfKV6yBov4GCenLFkBHL50hygNB(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2021-12-04 2:11:10 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.16.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 706c

Start Time: 01d7e92cc153f8be

Termination Time: 14

Application Path: C:\Users\User\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: 3585f597-2ca8-462c-8780-fbbdeb917592

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 2021-12-04 2:11:09 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1896450252955402512, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 61a8cb39
P4: e41a
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB7AE.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB7BE.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB7BD.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB7DE.tmp.txt
\\?\C:\Users\User\AppData\Local\Temp\WER8F82.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_f7f57d5f53fa3e1c96b985c58bedf4e9cbc725_4474b2c0_c6a4e56c-ec46-4fa6-8093-58babcd26b97

Analysis symbol: 
Rechecking for solution: 0
Report Id: 3585f597-2ca8-462c-8780-fbbdeb917592
Report Status: 268435456
Hashed bucket: 1599d35eacb1b7a5da518b750d9b4110
Cab Guid: 0 }
--------------
{ TimeGenerated = 2021-12-01 7:40:39 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2137399946764805085, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\User\AppData\Local\Temp\RDR339C.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER33AD.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER33BE.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER33DB.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER340B.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: a2ee1567-a76e-480a-a65c-120309dda2ec
Report Status: 268435456
Hashed bucket: 90206cb8882a62a92da991ed59dae3dd
Cab Guid: 0 }
```

**Comment by syntaxaire** [comment]
[thousand_suns.txt](https://github.com/anegostudios/VintageStory-Issues/files/7689244/thousand_suns.txt)

**Comment by tyronx** [comment]
Thanks for the report, this should be fixed next release.

Unfortuantely the cave art export/import is still not properly supported, so it'll derp after import.
