### ISSUE TITLE
Crash to desktop when importing a partially complete clay form

### ISSUE THREAD

**Issue by syntaxaire** [anegostudios/VintageStory-Issues#1480]
**Game Version:** 1.16.0-pre9
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Similar to an earlier report, this is a crash to desktop when using the WorldEdit import tool.

### How to reproduce
1. Make a creative world
2. Import this json file of one block, a half-finished clay form:

```json
{"GameVersion":"1.16.0-pre.9","SizeX":1,"SizeY":1,"SizeZ":1,"BlockCodes":{"295":"clayform"},"ItemCodes":{"285":"clayworkitem-fire","283":"clay-fire"},"Indices":[0],"BlockIds":[295],"DecorIndices":[],"DecorIds":[],"BlockEntities":{"0":"!<d@[F*QoC#64c-E,TfCD?'Y:!<d@[F*`uu#64o6@VfsmCI<#NAI)d^@<lI'Ebu'dG&MV:Ci]RXs8W-!s8W-!s8W*!zzzzzs8W-!s8W-!s8N'!zzzzzs8N2:\"2G#S\"2Fm:zzzzzs8N2:\"2G#S\"2Fm:zzzzzs8N2:\"2G#S\"2Fm:zzzzzs8N2:\"2G#S\"2Fm:zzzzzs8N2:\"2G#S\"2Fm:zzzzzs8N2:\"2G#S\"2Fm:zzzzzs8N2:\"2G#S\"2Fm:zzzzzs8N2:\"2G#S\"2Fm:zzzzzs8N2:\"2G#S\"2Fm:zzzzzs8N2:\"2G#S\"2Fm:zzzzzs8N2:\"2G#S\"2Fm:zzzzzs8N2:\"2G#S\"2Fm:zzzzzs8N2:\"2G#S\"2Fm:zzzzzs8N2:\"2G#S\"2Fm:zzzzz#7YlqEbe6gASk@f@:O'Q!<<*\"*<?-?!<<*\"!!`pA@<6!S@<?($BjkfX!<<*\")Z]p=!<<*\"!!*U=G%#*$@:F%a<c<4oCi^Bm!!!$2F(K0!@ru9m;Is?PE+MUO#64`(!!"},"Entities":[],"ReplaceMode":2}
```

### Logs
```
Version: v1.16.0-pre.9 (Unstable)2021-12-15 12:46:03 PM: Critical error occurred
System.Exception: Can't create itemstack without item!
   at Vintagestory.API.Common.ItemStack..ctor(Item item, Int32 stacksize)
   at Vintagestory.GameContent.BlockEntityClayForm.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving)
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(_8fH0Rok4o3k4zejJl0rvrCyBLsh p, ClientMain game)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(_O8kiClHK0zzAFCsHeRD8gfwAtPeb packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _ZLqEEOJcEfR4W5IcfFYxYeo1W7A._CwankQjFsCeBMBz0y9Ry7krPGao(Single )
   at _EOxJ1NLdImnIf66nSLWiRqzOJBV._pZXonigaPlZyCEhfWa3dd4uy2o2(Single )
   at _EOxJ1NLdImnIf66nSLWiRqzOJBV._gDDZXwLzjLjEmUMAMKEg45j78tm(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 375
   at _uAaSAz7V1575SVexfTBsGh6P6PC._MM8bqxLY6thWJUh084URtX1dZas(_mKXLIIwPHdHpl1G8PcbI8qiO8SC , String[] )
   at _AXpGXSwGdYF9Cfh1RNvXDAvkggq._MM8bqxLY6thWJUh084URtX1dZas(ThreadStart )
```

**Comment by syntaxaire** [comment]
Updated with single block repro.

**Comment by Craluminum2413** [comment]
Closed due to inactivity
