### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by striker1254** [anegostudios/VintageStory-Issues#1486]
**Game Version:** 1.15.10
**Platform:** Windows    
**Modded:** No  
**SP/MP:** Singleplayer  

### Description
game crashes when trying to load into a game world

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Logs
```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.


```Running on 64 bit Windows with 39 GB RAM 
Version: v1.15.10 (Stable)12/19/2021 3:45:16 PM: Critical error occurred
System.InvalidOperationException: Could not execute non-optional patch: Regex (^|[\.,+\-*/;{}[\]()=:|^&?#\s])texColor\s*?\.\s*?a\s*?\+\s*?=\s*?max\s*?\(\s*?0\s*?,\s*?diff\s*?/\s*?16\s*?\+\s*?noise\s*?/\s*?4\s*?\)\s*?;($|[\.,+\-*/;{}[\]()=:|^&?#\s]) not matched
   at VolumetricShading.Patch.RegexPatch.Patch(String filename, String code)
   at VolumetricShading.Patch.ShaderPatcher.Patch(String filename, String code, Boolean cache)
   at VolumetricShading.ShaderRegistryPatches.LoadShaderCallsite(ShaderProgram shader, String code, List`1 includes, EnumShaderType type)
   at Vintagestory.Client.NoObf.ShaderRegistry.LoadShader_Patch1(ShaderProgram program, EnumShaderType shaderType, List`1 assetsinclude)
   at Vintagestory.Client.NoObf.ShaderRegistry.loadRegisteredShaderPrograms_Patch0()
   at Vintagestory.Client.NoObf.ShaderAPI.ReloadShaders()
   at Vintagestory.Client.NoObf.SystemModHandler.OnServerIdentificationReceived()
   at Vintagestory.Client.NoObf.ClientMain.ProcessServerIdentification(_TTMS23AwbUUYwtAobecOMgNfDqJ packet)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerIdent(_TTMS23AwbUUYwtAobecOMgNfDqJ packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _M3NcP5TH7TMb4K2x8uUbkjXP7iO._oYniXsjcVAWxLpTiLUivE84wTkA(Single )
   at _R2SaBRGSTE9aIRQAjhFb2LrMpJb._gq2ZjDtIZ3sLq4OCUiRUzkjv3XA(Single )
   at _R2SaBRGSTE9aIRQAjhFb2LrMpJb._tjdmYyEuuoCShcgREvOOHIl2K1G(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _rwEcecUjMyzMSfVPsyS8Wx2kGqk._XiZO0qHpODOJko3v6YCZBF7Z5Se(_2kddpZuU7wcyt2belKg18dkvHxo , String[] )
   at _E5WqgB878qvAOVUQ9yfqu340l7G._XiZO0qHpODOJko3v6YCZBF7Z5Se(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/28/2021 10:39:19 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2224173527880806636, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.8.0
P3: 61879254
P4: KERNELBASE.dll
P5: 10.0.22000.318
P6: 095a2f2a
P7: c000041d
P8: 000000000004466c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d993cede-a455-41b4-867a-c8f2e2dc6584.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.08f2d9cd-d2fe-4b23-a004-3c5cb5ff2a8b.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.936285a1-15ab-417b-9462-82a4caabda25.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.5e1acebb-aeee-4e36-9b01-5bd155b881ec.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d2949445-66b4-4d36-a935-145bc96e50d2.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_1254316763b0cedf3d2e2f88f66ca5efdc3fd5d_09f6b299_c9fd58de-6b0b-4a68-8a20-1a87988ea9d3

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5469da80-d68e-4957-8a9f-746eacc397c7
Report Status: 268435456
Hashed bucket: a7ece9c9a348c770eeddda0a1829b0ec
Cab Guid: 0 }
--------------
{ TimeGenerated = 11/28/2021 10:39:11 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.15.8.0, time stamp: 0x61879254
Faulting module name: KERNELBASE.dll, version: 10.0.22000.318, time stamp: 0x095a2f2a
Exception code: 0xc000041d
Fault offset: 0x000000000004466c
Faulting process id: 0x5988
Faulting application start time: 0x01d7e48e9aeff0b9
Faulting application path: C:\Users\iben1\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 5469da80-d68e-4957-8a9f-746eacc397c7
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/28/2021 10:39:10 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1568133846514069791, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.8.0
P3: 61879254
P4: KERNELBASE.dll
P5: 10.0.22000.318
P6: 095a2f2a
P7: c0020001
P8: 000000000004466c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b22af79d-0611-4d2b-bafc-1e520a1e7423.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8c0b87d3-e987-4d5b-9734-2b1447bf3ef3.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.764a2cb3-1a84-4b03-9349-0a9a63fea35e.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.bde8964a-67b5-49b3-a25d-20907275e09c.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9a2e0325-a3d5-41cf-8a09-7de27657d405.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_e79739c071fae7b9151636d59b427aa954b26b82_09f6b299_74204293-2d7f-4077-a332-83a6cc96529c

Analysis symbol: 
Rechecking for solution: 0
Report Id: f5cf9974-2911-45a4-b9b4-9ef275ede5ef
Report Status: 268435456
Hashed bucket: 022788c1c462adc055c3216cd1bcf11f
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
The problem is in Volumetric Shading mod

**Comment by striker1254** [comment]
ah, thank you very much
