### ISSUE TITLE
1.16.0-pre.11 worlds won't load

### ISSUE THREAD

**Issue by Jamie-Louise** [anegostudios/VintageStory-Issues#1488]
**Game Version:** 1.16.0-pre.11
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
After updating from pre.10 to pre.11, worlds won't load. New worlds and save files hang on the loading screen.

### Logs
server-event.txt
```
19.12.2021 18:22:39 [Event] Launching server...
19.12.2021 18:22:39 [Event] Server v1.16.0-pre.11, network v1.16.0, api v1.7.0
19.12.2021 18:22:39 [Event] Loading configuration...
19.12.2021 18:22:40 [Event] Loading assets...
19.12.2021 18:22:40 [Event] Loading save game...
19.12.2021 18:22:55 [Event] 6 cooking recipes loaded
19.12.2021 18:22:55 [Event] 452 crafting recipes loaded from 199 files
19.12.2021 18:22:55 [Event] 7 metal alloys loaded
19.12.2021 18:22:55 [Event] 197 smithing recipes loaded
19.12.2021 18:22:55 [Event] 54 clay forming recipes loaded
19.12.2021 18:22:55 [Event] 36 knapping recipes loaded
19.12.2021 18:22:55 [Event] 149 barrel recipes loaded
19.12.2021 18:22:58 [Event] Loading 7x7x8 spawn chunks...
19.12.2021 18:22:58 [Event] 0% (49 in queue)
19.12.2021 18:22:59 [Event] Begin save game ticking...
19.12.2021 18:22:59 [Event] Singleplayer Server now running!
19.12.2021 18:23:02 [Fatal] System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Vintagestory.GameContent.ModSystemRifts.OnServerTick3s(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Server.ServerMain.Process()
```

**Comment by copygirl** [comment]
May I ask why was this issue closed?
