### ISSUE TITLE
crash with modded hoe

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#149]
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/2193611/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/2193612/server-main.txt)
[VintagestoryCrash.txt](https://github.com/anegostudios/VintageStory-Issues/files/2193613/VintagestoryCrash.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/2193614/client-crash.txt)
```
Running on 64 bit Windows with 16GB RAM 
7/13/2018 10:22:58 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
 at Vintagestory.GameContent.ItemHoe.OnHeldInteractStart(IItemSlot itemslot, IEntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
 at Vintagestory.API.Common.CollectibleObject.OnHeldUseStart(IItemSlot slot, IEntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType)
 at _FIpgiXtN9RuuhHAYxBkpX7TJjr._7aRfQEjeE47qGhFUdlDUcLhKnGG(BlockSelection , EntitySelection , EnumHandInteract )
 at _FIpgiXtN9RuuhHAYxBkpX7TJjr._jKuYR2VDlbkwrsiMsY6tmVerbuE(Single )
 at _FIpgiXtN9RuuhHAYxBkpX7TJjr._REzMN1nU9SUI1pj0QGJVo7pFaHJ(Single )
 at _eIlbp5cU5L0xKgg3cRtmdoivNtr._0S5g8g1BgR7KvLSdlYbnsH7Qy8m(EnumRenderStage , Single )
 at _cKvmuP9Z3pnyteI6N3ItAbdaApk._RolaPMuY1NXbIITIwUscYtJrke3A(Single )
 at _dz4dcYHPqpZHusiJeJW0Qemw2iJ._RolaPMuY1NXbIITIwUscYtJrke3A(Single )
 at _xZhDEYLhjXAJANKDYobOVMh4FQdb._Jm5dcnzWsYuz08G5MJQLfRnjcqy(Single )
 at _xZhDEYLhjXAJANKDYobOVMh4FQdb._Gv1BPtOAUmCwba05S8Cgh2jukmU(Single )
 at _OQspLMDwKKkx6pDA6xajlkb5wOF._WTubJ34kd4umi71YQTkeTy7E9ZD(Object , FrameEventArgs )
 at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
 at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
 at OpenTK.GameWindow.DispatchRenderFrame()
 at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
 at _qTvBRfrZHmQZLV0omvHFpK3LT9y._w8zrVg3BYSI3s61BfPPbtf3kXdAA(_XNX59FyeaAkNf4lxYrqXRKnMA3d , String[] )
 at _ss8XnL443c6iKET9r8uH2mngrdC._w8zrVg3BYSI3s61BfPPbtf3kXdAA(ThreadStart )
-------------------------------
Crash written to file at C:\Users\Stroam\AppData\Roaming\VintagestoryData\Logs\VintagestoryCrash.txt
```
Tried to hoe the ground using a modded hoe.
[test.zip](https://github.com/anegostudios/VintageStory-Issues/files/2193620/test.zip)

**Comment by sirStroam** [comment]
Maybe. I know replacing the vanilla classes works.
````
at _eIlbp5cU5L0xKgg3cRtmdoivNtr._0S5g8g1BgR7KvLSdlYbnsH7Qy8m(EnumRenderStage , Single )
at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
 at OpenTK.GameWindow.DispatchRenderFrame()
```
Makes me think the issue is with the character animation with a modded hoe and not the `ItemHoe.cs`. Perhaps it's looking for the vanilla hoe but since there is no vanilla hoe it gets a null object, or it's looking for a vanilla asset using the mod domain. I'll do some testing and look as deep as I can.

**Comment by sirStroam** [comment]
[test.zip](https://github.com/anegostudios/VintageStory-Issues/files/2199822/test.zip)
I made an `assets/game/itemtypes/tool` folder and copied over `assets/build/itemtypes/tool/stonehoe.json` and renamed the code from `stonehoe` to `hoestonehoe`. The results were the new game domain modded hoe did not crash the game but did break in one use upon right-clicking. (side note: I wonder how much damage a use does with the hoes). The old modded hoe crashed the game as expected. The conclusion is the crash is a result of the domain being wrong. I continue to suspect the code for the animation is looking for `game:stonehoe` and not `build:stonehoe`.

**Comment by sirStroam** [comment]
`_FIpgiXtN9RuuhHAYxBkpX7TJjr._7aRfQEjeE47qGhFUdlDUcLhKnGG(BlockSelection , EntitySelection , EnumHandInteract )` I am unable to follow it that deep but I'm over 90% sure that's where the problem is.
