### ISSUE TITLE
Game Crashed While Running (v1.16 rc-1)

### ISSUE THREAD

**Issue by raeu16** [anegostudios/VintageStory-Issues#1491]
**Game Version:** v1.16 rc-1  
**Platform:** Windows    
**Modded:** No 
**SP/MP:** Singleplayer

### Description
Game suddenly crashed while character was running/exploring new area

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0-rc.1 (Unstable)12/22/2021 10:32:52 PM: Critical error occurred
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at Vintagestory.GameContent.BlockFruitTreePart.ShouldReceiveClientParticleTicks(IWorldAccessor world, IPlayer player, BlockPos pos, Boolean& isWindAffected)
   at Vintagestory.Client.NoObf.SystemClientTickingBlocks.OnBlockChanged(BlockPos pos, Block oldBlock)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockChanged(ClientMain game, BlockPos pos, Block oldBlock)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleSetBlock(_Dn7qN8daX4S7cI1oTND06G6h80k packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _PhBXNVfYe5d3lEfMtj0l7fTONzE._YKMdtNOFlXNFjI1iWLxJZTGyW70(Single )
   at _BSBPUQgngn7cAsWvyMzmCA525zp._0Jpc8lDzZ6srMMKbJvzdSTG2N7e(Single )
   at _BSBPUQgngn7cAsWvyMzmCA525zp._ebzXAhafOWCz0Zylw5noiq7E8HY(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 375
   at _c6WJfv6097n0bBAe7PdA4UCpIvx._LSOwrsgC0mWacLIhEolJaz8jGBy(_jCo1kN5fmYhKkEzb9bB2BD15DvK , String[] )
   at _WgDRf1Ijf36jY6MnFFFCmh3xcSD._LSOwrsgC0mWacLIhEolJaz8jGBy(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/4/2021 5:50:36 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1478716220082461302, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\raeu1\AppData\Local\Temp\RDRCC82.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCC83.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCCA3.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCCD0.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCD1F.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: b6cf2a4b-988d-426d-a3b4-4a1321d97d93
Report Status: 268435456
Hashed bucket: 1f92a0c50d25295c648574914d9f9a76
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/3/2021 11:55:23 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1298668709714251717, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.6.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\raeu1\AppData\Local\Temp\RDR2C4B.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2C5C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2C5D.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2C84.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2CD3.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: fb7d07e9-c759-4e35-96d3-b847c8fc12dd
Report Status: 268435456
Hashed bucket: 8f39dc2e068300f29205cc4f936ecfc5
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/18/2021 5:10:17 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1844930624240464797, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.1.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\raeu1\AppData\Local\Temp\RDRE455.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE466.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE477.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE4B3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE4F3.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: b4bb9a5c-8b42-4cf6-86c2-b9de4d66b4c8
Report Status: 268435456
Hashed bucket: b4a6b879c54e219cb99a82a0bd17b39d
Cab Guid: 0 }
```

**Comment by tyronx** [comment]
hi, thanks for the report, this should be fixed in rc.2
