### ISSUE TITLE
Crash on trying to place block with HorizontalOrientable behavior that has only two directions

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1507]
**Game Version:** 1.16.0-rc.3
**Platform:** Windows
**Modded:** Yes
**SP/MP:** Singleplayer

### How to reproduce
1. Add HorizontalOrientable behavior to any block
2. Add `north` and `west` states to variantgroups, but don't add `south` and `east`
3. Load any world
4. Try to place that block in removed directions
5. It crashes

### Logs
```
Version: v1.16.0-rc.3 (Unstable)12/28/2021 14:10:38: Critical error occurred
System.NullReferenceException: Unable to to find a rotated block with code moreshapes:slope_0002-79-south, you're maybe missing the side variant group of have a dash in your block code
   at Vintagestory.GameContent.BlockBehaviorHorizontalOrientable.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, EnumHandling& handling, String& failureCode)
   at Vintagestory.API.Common.Block.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, String& failureCode)
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryPlace(BlockSelection blockSelection, String& failureCode)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnBlockBuild(BlockSelection blockSelection, Block onBlock, String& failureCode)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _x2sphGvaQHYRL58iBmwDrxU4JDn._YW8xM33zLilYIiYmPz3LwkRyZnf(Single )
   at _8d8bxAkSchxDthWdXGk9L7JzIAp._COZH04DCHcYdj7FJVekhdO7h2zW(Single )
   at _8d8bxAkSchxDthWdXGk9L7JzIAp._NGLt2tlj0Kdb71xAZX2ab8OUsaY(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 375
   at _Gqy4bfkYgCRmVM3rr5ctXVLZlMh._aoi1Mc6iTidbcOBRjahZfdoHVdN(_BNIaG9Y7PSPYLFpjzhV1OMF5mHh , String[] )
   at _0ynubLUTRXRju8HMEIDSQn5ni6F._aoi1Mc6iTidbcOBRjahZfdoHVdN(ThreadStart )
```

**Comment by copygirl** [comment]
What do you expect to happen? That behavior is for blocks that can be placed in all horizontal directions, not just the ones you decide to provide. If you want to have something more specific (though not sure why?) then you'll have to make your own behavior.

**Comment by Craluminum2413** [comment]
I expected that it would ignore them, but instead I should use 140 the same blocks because of that

**Comment by copygirl** [comment]
If needed for your specific use-case, you can always make your own behavior.

I will close for now because this should probably be solved with a code mod.
