### ISSUE TITLE
No errors when entries in allowedVariants have game prefix in their name

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1514]
**Game Version:** 1.16.0-rc.4 
**Platform:** Windows
**Modded:** Yes
**SP/MP:** Singleplayer

### How to reproduce
1. Make any recipe with `game:` in allowedVariants array
2. Load any world
3. Open handbook page with that recipe
4. It crashes

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0-rc.4 (Unstable)12/30/2021 14:23:36: Critical error occurred
System.DivideByZeroException: Attempted to divide by zero.
   at Vintagestory.API.Client.SlideshowGridRecipeTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY)
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime)
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime)
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _7iCQoAsdfZVe97yqgBvFIlfMcLX._oSST6IDy06pC4oQluSEmtdjEFbF(Single )
   at _I0WD3I4WctxZ3hTRXyebKG0jmBf._tg8nBjK5ToT6PHOIE5xQt7pVLgG(Single )
   at _I0WD3I4WctxZ3hTRXyebKG0jmBf._gnkMjmr2bSsrfIdOhrvQRzhb10q(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Tyron\Documents\vintagestory\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Tyron\Documents\vintagestory\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Tyron\Documents\vintagestory\opentk\src\OpenTK\GameWindow.cs:line 375
   at _quY1LtnDKMMw6SVgU24CS70qLUE._JBR6QkruXskegIJwBDxKd0GbwmH(_lRqUvPQ9bMUaG7sdu7BSpZx9dCl , String[] )
   at _7NITwHRdYBX2itWgXsEcfwp9Z0J._JBR6QkruXskegIJwBDxKd0GbwmH(ThreadStart )
```

**Comment by maltiez2** [comment]
Seems to no longer cause a crash, just not matching any codes, which is expected.
