### ISSUE TITLE
No errors about missing stack in whenSpilled

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1520]
**Game Version:** 1.16.0-rc.4
**Platform:** Windows 
**Modded:** Yes
**SP/MP:** Singleplayer

### How to reproduce
1. Remove `stack` property from `itemtypes/liquid/waterportion.json`
2. Load any world
3. Get a bucket of water
4. Press `Ctrl` + `RMB` to spill it
5. It crashes

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0-rc.4 (Unstable)12/31/2021 17:55:30: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockLiquidContainerBase.SpillContents(ItemSlot containerSlot, EntityAgent byEntity, BlockSelection blockSel)
   at Vintagestory.GameContent.BlockLiquidContainerBase.OnHeldInteractStart(ItemSlot itemslot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handHandling)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _7iCQoAsdfZVe97yqgBvFIlfMcLX._oSST6IDy06pC4oQluSEmtdjEFbF(Single )
   at _I0WD3I4WctxZ3hTRXyebKG0jmBf._tg8nBjK5ToT6PHOIE5xQt7pVLgG(Single )
   at _I0WD3I4WctxZ3hTRXyebKG0jmBf._gnkMjmr2bSsrfIdOhrvQRzhb10q(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Tyron\Documents\vintagestory\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Tyron\Documents\vintagestory\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Tyron\Documents\vintagestory\opentk\src\OpenTK\GameWindow.cs:line 375
   at _quY1LtnDKMMw6SVgU24CS70qLUE._JBR6QkruXskegIJwBDxKd0GbwmH(_lRqUvPQ9bMUaG7sdu7BSpZx9dCl , String[] )
   at _7NITwHRdYBX2itWgXsEcfwp9Z0J._JBR6QkruXskegIJwBDxKd0GbwmH(ThreadStart )
```

**Comment by maltiez2** [comment]
Addressed in MR1330
