### ISSUE TITLE
Crash when trying to select tool mode on propick

### ISSUE THREAD

**Issue by Dextobust33** [anegostudios/VintageStory-Issues#1523]
**Game Version:** 1.16.0-rc.5 
**Platform:** Windows
**Modded:** Yes, same error without mod
**SP/MP:** Singleplayer / Multiplayer BOTH

### Description
Game crashes when trying to select a mode for the prospecting pick

### Logs
Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0-rc.5 (Unstable)1/1/2022 5:21:09 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.GuiDialogToolMode.OnSlotClick(Int32 num)
   at Vintagestory.API.Client.GuiElementSkillItemGrid.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse)
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs)
   at Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 792
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at _nFNsDM20as86sGo44HbF6xxAkUD._UjMaM1bzP5Ozg5ilu06DMFIxPyO(_uhgd4BSf8z6N7PAibzFcq8c5IRD , String[] )
   at _Y4Bk3tLdFsgoJryQq19g4IoitkE._UjMaM1bzP5Ozg5ilu06DMFIxPyO(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/26/2021 1:58:12 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2137399946764805085, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9b55c4c1-a404-4c29-a277-1374fec1ae97
Report Status: 268435456
Hashed bucket: 90206cb8882a62a92da991ed59dae3dd
Cab Guid: 0 }
```

**Comment by tyronx** [comment]
thanks for the report, this will be fixed in rc6.

As a workaround, look at any block while selecting the mode
