### ISSUE TITLE
Crash on trying to drink from a barrel in hands in creative

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1531]
**Game Version:** 1.16.0-rc.6
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Place a barrel
2. Fill it with honey
3. Copy the barrel with creative gamemode
4. Try to drink with that
5. It crashes (if you save the world, it will corrupt your save)

### Logs
```
4.1.2022 15:47:00 [Fatal] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockLiquidContainerBase.GetContent(ItemStack containerStack)
   at Vintagestory.GameContent.BlockLiquidContainerBase.GetNutritionProperties(IWorldAccessor world, ItemStack itemstack, Entity forEntity)
   at Vintagestory.API.Common.CollectibleObject.GetHeldTpUseAnimation(ItemSlot activeHotbarSlot, Entity forEntity)
   at Vintagestory.API.Common.EntityAgent.HandleHandAnimations()
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt)
   at Vintagestory.Server.ServerMain.Process()
```

**Comment by Craluminum2413** [comment]
Can no longer drink from a barrel starting from [1.16.0-rc.7](https://www.vintagestory.at/forums/topic/6186-homesteading-part-2-7th-release-candidate-1160-rc7/#:~:text=Fixed%3A%20Should%20fix%20a%20crash%20related%20to%20barrels)
