### ISSUE TITLE
Crash on trying to put barrel filled with liquid into inventory

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1532]
**Game Version:** 1.16.0-rc.6
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Place a barrel
2. Fill the barrel with liquid
3. Get an empty barrel
4. Right-click with `empty barrel` on GUI slot of `the placed barrel`
5. Try to put it into inventory
6. It crashes

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0-rc.6 (Unstable)01/04/2022 17:24:56: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockLiquidContainerBase.GetContent(ItemStack containerStack)
   at Vintagestory.GameContent.BlockLiquidContainerBase.GetNutritionProperties(IWorldAccessor world, ItemStack itemstack, Entity forEntity)
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.API.Common.Block.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.GameContent.BlockBarrel.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug)
   at Vintagestory.API.Client.GuiElementItemstackInfo.AsyncRecompose()
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot)
   at Vintagestory.Client.NoObf.HudMouseTools.OnMouseClickSlot(ItemSlot itemSlot)
   at Vintagestory.Client.NoObf.InputAPI.TriggerOnMouseClickSlot(ItemSlot itemSlot)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse)
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs)
   at Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 792
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at _pac23aTn0XsYq3swjP0pQIJNr6A._H28AIBPAN7K3Llru23eo2kbE1Dk(_xTlkkhSjnlZf4G6vVW717CNZxM , String[] )
   at _1OzxJijwDv4UbCmbYyW3H8Jf8QN._H28AIBPAN7K3Llru23eo2kbE1Dk(ThreadStart )
```

**Comment by copygirl** [comment]
Likely related to your previous issue, #1531. A fix will probably resolve both these issues. Keeping them both open for now though.

**Comment by Craluminum2413** [comment]
This issue is with initially empty barrel, that can be reproduced in survival, the previous issue is about already copied with help of creative

**Comment by Craluminum2413** [comment]
No longer crashes in [1.16.0-rc.7](https://www.vintagestory.at/forums/topic/6186-homesteading-part-2-7th-release-candidate-1160-rc7/#:~:text=Fixed%3A%20Should%20fix%20a%20crash%20related%20to%20barrels)
