### ISSUE TITLE
No errors about missing attributes when using name in the grid recipe

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1551]
**Game Version:** 1.16.0-rc.8
**Platform:** Windows
**Modded:** Yes
**SP/MP:** Singleplayer

### How to reproduce
1. Add a recipe like this:
```json
  {
    "ingredientPattern": "WW",
    "ingredients": {
      "W": { "type": "block", "code": "wchest-east", "name": "wood" }
    },
    "recipeGroup": 1,
    "width": 2,
    "height": 1,
    "shapeless": true,
    "output": { "type": "block", "code": "wtrunk-east", "attributes": { "type": "{wood}" } }
  }
```
2. Load any world
3. Open the handbook page with its recipe
4. It is invisible and crash the game when hovering over it

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/148666196-f729866c-f12b-4021-8640-4d998af75887.png)

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0-rc.8 (Unstable)01/09/2022 03:51:51: Critical error occurred
System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Vintagestory.API.Config.TranslationService.GetMatching(String key, Object[] args)
   at Vintagestory.API.Common.ItemSlot.GetStackName()
   at Vintagestory.API.Client.GuiElementItemstackInfo.AsyncRecompose()
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot)
   at Vintagestory.API.Client.ItemstackComponentBase.RenderItemstackTooltip(ItemSlot slot, Double renderX, Double renderY, Single dt)
   at Vintagestory.API.Client.SlideshowItemstackTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY)
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime)
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime)
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _tEDbLQTs0VDFNWvKfGRaxTN6Bnu._HYF1BohwDce3bxOfDTvaM3RD0QQ(Single )
   at _jcH3FSJ7ohiDyiUVjeI57gTMlzF._9wzjmUmSdoSvs71TINZbez3uGKf(Single )
   at _jcH3FSJ7ohiDyiUVjeI57gTMlzF._MPtQhjNuhWgAbVd6NjS5dCFTc5M(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _ZqUQ7pOQY5Qg73UAepClsoZVWgk._aC3ylqMdqishY21wVe5qXxrZ5ob(_EE6B13xM9ADbX1bGtFaOKrVoXro , String[] )
   at _mWFXvJdRjYXBzuYdW6hiXK5Fb5p._aC3ylqMdqishY21wVe5qXxrZ5ob(ThreadStart )
```

**Comment by Craluminum2413** [comment]
Another example
```json
  {
    "ingredientPattern": "S,C",
    "ingredients": {
      "S": { "type": "block", "code": "vanvar:sign-*-ground-north", "name": "swood" },
      "C": { "type": "block", "code": "wchest-east", "attributes": { "type": "*", "name": "wood" } }
    },
    "recipeGroup": 2,
    "shapeless": true,
    "width": 1,
    "height": 2,
    "output": { "type": "block", "code": "wlabeledchest-east", "attributes": { "type": "{wood}-{swood}" } }
  }
```
![image](https://user-images.githubusercontent.com/69315569/148690512-b3a5c686-47de-479e-970d-d2a4ee7b2ec8.png)

**Comment by maltiez2** [comment]
Cant reproduce, seems to be fixed
