### ISSUE TITLE
Crash on trying to break typed container that has wrong domain for shapes

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1553]
**Game Version:** 1.16.0-rc.8
**Platform:** Windows 
**Modded:** Yes
**SP/MP:** Singleplayer

### Description
[Blocks](https://github.com/anegostudios/VintageStory-Issues/files/7835327/blocktypes.zip) that I added and due those I get this crash

[Here](https://github.com/anegostudios/VintageStory-Issues/files/7835691/chest.zip) are their shapes

### How to reproduce
1. Add wood variants for trunk / [use this file](https://github.com/anegostudios/VintageStory-Issues/files/7834389/trunks.zip)
2. Load any world
3. Place any variant of this trunk
4. Try to break it in survival
5. It crashes

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0-rc.8 (Unstable)01/09/2022 04:49:36: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockGenericTypedContainer.GetDecal(IWorldAccessor world, BlockPos pos, ITexPositionSource decalTexSource, MeshData& decalModelData, MeshData& blockModelData)
   at Vintagestory.Client.NoObf.SystemRenderDecals.UpdateDecal(BlockDecal decal)
   at Vintagestory.Client.NoObf.SystemRenderDecals.AddBlockBreakDecal(BlockPos pos, Int32 stage)
   at Vintagestory.Client.NoObf.SystemRenderDecals.OnPlayerBreakingBlock(_l7J43N3XdTsgOBtmj0UUW17C3IE blockDamage)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockBreaking(_l7J43N3XdTsgOBtmj0UUW17C3IE blockDamage)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _tEDbLQTs0VDFNWvKfGRaxTN6Bnu._HYF1BohwDce3bxOfDTvaM3RD0QQ(Single )
   at _jcH3FSJ7ohiDyiUVjeI57gTMlzF._9wzjmUmSdoSvs71TINZbez3uGKf(Single )
   at _jcH3FSJ7ohiDyiUVjeI57gTMlzF._MPtQhjNuhWgAbVd6NjS5dCFTc5M(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _ZqUQ7pOQY5Qg73UAepClsoZVWgk._aC3ylqMdqishY21wVe5qXxrZ5ob(_EE6B13xM9ADbX1bGtFaOKrVoXro , String[] )
   at _mWFXvJdRjYXBzuYdW6hiXK5Fb5p._aC3ylqMdqishY21wVe5qXxrZ5ob(ThreadStart )
```

**Comment by Craluminum2413** [comment]
I tested it with Extra Chests that made literally in the same way, and it doesn't crash, thus, it is super strange unintended behavior
https://mods.vintagestory.at/show/mod/137

**Comment by Craluminum2413** [comment]
Here are shapes [chest.zip](https://github.com/anegostudios/VintageStory-Issues/files/7835691/chest.zip)

**Comment by Craluminum2413** [comment]
I fixed that by adding domain where the shape locates, for example, `woodchests:block/chest/normal-labeled-0`
