### ISSUE TITLE
Crash in .tfedit window

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1558]
**Game Version:** 1.16.0-rc.8 
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Open `.tfedit` for any item
2. Throw this item from hand without closing the window
3. Change to another tab there
4. It crashed

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0-rc.8 (Unstable)01/10/2022 01:02:58: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.GuiDialogTransformEditor.OnGuiOpened()
   at Vintagestory.API.Client.GuiElementVerticalTabs.SetValue(Int32 index)
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse)
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs)
   at Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 792
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at _ZqUQ7pOQY5Qg73UAepClsoZVWgk._aC3ylqMdqishY21wVe5qXxrZ5ob(_EE6B13xM9ADbX1bGtFaOKrVoXro , String[] )
   at _mWFXvJdRjYXBzuYdW6hiXK5Fb5p._aC3ylqMdqishY21wVe5qXxrZ5ob(ThreadStart )
```

**Comment by Craluminum2413** [comment]
Still can reproduce in 1.20

**Comment by Monkeybrain73** [comment]
Can confirm, in 1.20
