### ISSUE TITLE
Crash when I was about to finish a storage vessel

### ISSUE THREAD

**Issue by Krorzen** [anegostudios/VintageStory-Issues#1566]
**Game Version:** 1.16.0
**Platform:** Linux
**Modded:** No
**SP/MP:** Multiplayer

### Description
Was trying to finish a blue clay storage vessel and it crashed at the last voxel. I was about to place the last voxel.
Also note that before it crashed I changed to another stack I had on my inventory. On the previous vessel I made there wasn't any crashes.

Might be irrelavent but there was 1 more player close by going in and out of an unloaded chunk(unloaded from my prespective)

### How to reproduce
Unfortunately so far it happened once!

### Expected behavior
Finish building a unfired storage vessel (out of blue clay)

### Screenshots
Couldn't get one.

### Logs
```
Running on 64 bit Linux with 11 GB. 
Version: v1.16.0 (Stable)1/11/2022 8:28:25 PM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at (wrapper managed-to-managed) System.Object.ElementAddr_1(object,int,int,int)
  at Vintagestory.GameContent.BlockEntityClayForm.OnCopyLayer () [0x0002c] in <864f6d52e13c4950b1aa2dda37105fc4>:0 
  at Vintagestory.GameContent.BlockEntityClayForm.OnUseOver (Vintagestory.API.Common.IPlayer byPlayer, Vintagestory.API.MathTools.Vec3i voxelPos, Vintagestory.API.MathTools.BlockFacing facing, System.Boolean mouseBreakMode) [0x00077] in <864f6d52e13c4950b1aa2dda37105fc4>:0 
  at Vintagestory.GameContent.BlockEntityClayForm.OnUseOver (Vintagestory.API.Common.IPlayer byPlayer, System.Int32 selectionBoxIndex, Vintagestory.API.MathTools.BlockFacing facing, System.Boolean mouseBreakMode) [0x00046] in <864f6d52e13c4950b1aa2dda37105fc4>:0 
  at Vintagestory.GameContent.ItemClay.OnHeldInteractStop (System.Single secondsUsed, Vintagestory.API.Common.ItemSlot slot, Vintagestory.API.Common.EntityAgent byEntity, Vintagestory.API.Common.BlockSelection blockSel, Vintagestory.API.Common.EntitySelection entitySel) [0x000b9] in <864f6d52e13c4950b1aa2dda37105fc4>:0 
  at Vintagestory.API.Common.CollectibleObject.OnHeldUseStop (System.Single secondsPassed, Vintagestory.API.Common.ItemSlot slot, Vintagestory.API.Common.EntityAgent byEntity, Vintagestory.API.Common.BlockSelection blockSel, Vintagestory.API.Common.EntitySelection entitySel, Vintagestory.API.Common.EnumHandInteract useType) [0x00013] in <36cbe087d5194ceb880973ce6f2dfbfa>:0 
  at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction (System.Single dt) [0x00386] in <d16f4e016eef4b52a1d7221d4e54ddfc>:0 
  at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnGameTick (System.Single dt) [0x00204] in <d16f4e016eef4b52a1d7221d4e54ddfc>:0 
  at Vintagestory.Common.EventManager.TriggerGameTick (System.Int64 ellapsedMilliseconds, Vintagestory.API.Common.IWorldAccessor world) [0x000d3] in <d16f4e016eef4b52a1d7221d4e54ddfc>:0 
  at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop (System.Single dt) [0x00076] in <d16f4e016eef4b52a1d7221d4e54ddfc>:0 
  at Vintagestory.Client.NoObf.ClientMain.MainGameLoop (System.Single deltaTime) [0x00047] in <d16f4e016eef4b52a1d7221d4e54ddfc>:0 
  at _lb8GGBWOchQLOU3RFFw58Ijkh1D._uA6fxRiik2om8WbTxul2Dtkekip (System.Single ) [0x0004d] in <d16f4e016eef4b52a1d7221d4e54ddfc>:0 
  at _vFhcDU5n6Z0hUte90jdaxlrDjR5._HuDdfzha8ZKZvU2y0RbH58r7VzR (System.Single ) [0x00079] in <d16f4e016eef4b52a1d7221d4e54ddfc>:0 
  at _vFhcDU5n6Z0hUte90jdaxlrDjR5._XZOFA2JA54yZjH15yys9W7vL9hj (System.Single ) [0x000cc] in <d16f4e016eef4b52a1d7221d4e54ddfc>:0 
  at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame (System.Object sender, OpenTK.FrameEventArgs e) [0x00141] in <d16f4e016eef4b52a1d7221d4e54ddfc>:0 
  at (wrapper delegate-invoke) System.EventHandler`1[OpenTK.FrameEventArgs].invoke_void_object_TEventArgs(object,OpenTK.FrameEventArgs)
  at OpenTK.GameWindow.OnRenderFrame (OpenTK.FrameEventArgs e) [0x00000] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.GameWindow.OnRenderFrameInternal (OpenTK.FrameEventArgs e) [0x00010] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.GameWindow.RaiseRenderFrame (System.Double elapsed, System.Double& timestamp) [0x0000c] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.GameWindow.DispatchRenderFrame () [0x00038] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.GameWindow.Run (System.Double updates_per_second, System.Double frames_per_second) [0x00104] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.GameWindow.Run () [0x00000] in <a4886e33f9fc416195d24950e7205b94>:0 
  at _FKpOpQGqqf3cJWdQyWh1ysxsDBb._pYad7oBcQ5qtzQkYGDu4NFHQxhK (_5x3PJgrln4IBXPDNSNN0fecxKFb , System.String[] ) [0x003dc] in <bed49109127b412da64956a1d050210c>:0 
  at _FKpOpQGqqf3cJWdQyWh1ysxsDBb+_EbS2AEEJP4M13PeMC88IfKBzIZF._RNcFgtqGZOgUpj21Qsn4t2YRX9f () [0x00000] in <bed49109127b412da64956a1d050210c>:0 
  at _sejP0Tcz8wTg70ptIdRr3CwQmrE._pYad7oBcQ5qtzQkYGDu4NFHQxhK (System.Threading.ThreadStart ) [0x00007] in <d16f4e016eef4b52a1d7221d4e54ddfc>:0 
-------------------------------
```

**Comment by Craluminum2413** [comment]
It looks like you clicked 9th layer of "voxels that don't exist"

**Comment by Krorzen** [comment]
hmm I might actually did that because I was right clicking fast and I had a bit of lag. Also I was looking down at the last block so if I clicked I clicked the top face for sure.

**Comment by Jsowens** [comment]
Just had the same crash on the same part. I was holding down the RMB with the copy/paste layer mode. My mouse was somewhere in the middle of the part, and the last two voxels were in a corner, so that lends credence to the 9th layer theory. Haven't reproduced it yet.

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.16.5 (Stable)
Loaded Mods: game@1.16.5, creative@1.16.5, survival@1.16.5
4/23/2022 9:13:04 PM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockEntityClayForm.OnCopyLayer(Int32 layer)
   at Vintagestory.GameContent.BlockEntityClayForm.OnUseOver(IPlayer byPlayer, Vec3i voxelPos, BlockFacing facing, Boolean mouseBreakMode)
   at Vintagestory.GameContent.ItemClay.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnGameTick(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _esGsESICkihAc8ShXuIoQwZFwP4._lPY9uZeagiMGC6tvSE11dF7naaz(Single )
   at _8UC8FAMhwKY89IbtSRDjsNSApPJ._KbwUAfxjCHyIG0aK445AAA9FHl5(Single )
   at _8UC8FAMhwKY89IbtSRDjsNSApPJ._R0wAt2N0TpONMxGD0HJG3bDrRcI(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._vvUTh6X5xLRNnjtX2xSE7z8yMeh(_SUsdg1ytavxaRcNNkhfDrODGhGP , String[] )
   at _yA4PJazdKq1OMm8H6js6v5AhQB._vvUTh6X5xLRNnjtX2xSE7z8yMeh(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 4/22/2022 10:42:53 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1381417961401207149, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10:

**Comment by Chibily** [comment]
Hello :) I am not sure this is the place I am supposed to post this but I'm encountering a very similar crash, excepts that it occurs when I put the (blue) clay on the ground and choose the storage vessel ^^' I am not able to reload the save ever since, it crashes right after loading  :'(

Here is the issue log : 
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.16.5 (Stable)
Loaded Mods: game@1.16.5, creative@1.16.5, survival@1.16.5
21/05/2022 20:09:17: Critical error occurred
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnGameTick(Single dt)
   à Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   à Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   à Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   à _esGsESICkihAc8ShXuIoQwZFwP4._lPY9uZeagiMGC6tvSE11dF7naaz(Single )
   à _8UC8FAMhwKY89IbtSRDjsNSApPJ._KbwUAfxjCHyIG0aK445AAA9FHl5(Single )
   à _8UC8FAMhwKY89IbtSRDjsNSApPJ._R0wAt2N0TpONMxGD0HJG3bDrRcI(Single )
   à Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   à System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   à OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) dans C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:ligne 476
   à OpenTK.GameWindow.DispatchRenderFrame() dans C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:ligne 452
   à OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) dans C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:ligne 375
   à _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._vvUTh6X5xLRNnjtX2xSE7z8yMeh(_SUsdg1ytavxaRcNNkhfDrODGhGP , String[] )
   à _yA4PJazdKq1OMm8H6js6v5AhQB._vvUTh6X5xLRNnjtX2xSE7z8yMeh(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 13/02/2022 00:14:47, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.16.3.0, horodatage : 0x61fa6977
Nom du module défaillant : KERNELBASE.dll, version : 10.0.19041.1466, horodatage : 0xe01c7650
Code d’exception : 0xc0020001
Décalage d’erreur : 0x0000000000034f69
ID du processus défaillant : 0x699c
Heure de début de l’application défaillante : 0x01d8205ce9264eb0
Chemin d’accès de l’application défaillante : K:\Jeux\Vintage Story\Vintagestory\Vintagestory.exe
Chemin d’accès du module défaillant: C:\WINDOWS\System32\KERNELBASE.dll
ID de rapport : f8fd2b1a-acd9-43be-8150-71b4e3045554
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }
--------------
{ TimeGenerated = 13/02/2022 00:14:42, Site = , Source = .NET Runtime, Message = Application : Vintagestory.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : code d'exception c0020001, adresse d'exception 00007FFAD1D84F69
Pile :
 }

**Comment by copygirl** [comment]
@Chibily You can put text into a code block by surrounding it in triple backticks like so:
> \`\`\`
> Running on 64 bit Windows with 32 GB RAM 
> Game Version: v1.16.5 (Stable)
> [...]
> \`\`\`
The error you're getting is quite different from the one in this issue, so I'd like to ask you to create your own issue. And see if you could re-create the issue in a fresh world? Knowing how to reproduce it would help the team massively in fixing the issue.

**Comment by Chibily** [comment]
Thanks a lot @copygirl 
It is done

Have a nice evening

**Comment by Craluminum2413** [comment]
Closing due to inactivity
