### ISSUE TITLE
Crash when copying server info

### ISSUE THREAD

**Issue by pastelmangoo** [anegostudios/VintageStory-Issues#1567]
Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0 (Stable)1/11/2022 12:43:01 PM: Critical error occurred
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at Vintagestory.API.Client.GuiElementToggleButton.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse)
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs)
   at _kRNQrTEidJmQaGU3FH7i4dBfjO._dyPlabIVD002QL1qxGaejGv6HGN(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 792
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at _FKpOpQGqqf3cJWdQyWh1ysxsDBb._pYad7oBcQ5qtzQkYGDu4NFHQxhK(_5x3PJgrln4IBXPDNSNN0fecxKFb , String[] )
   at _sejP0Tcz8wTg70ptIdRr3CwQmrE._pYad7oBcQ5qtzQkYGDu4NFHQxhK(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 1/10/2022 6:36:12 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.16.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 3a94

Start Time: 01d806830464e339

Termination Time: 4

Application Path: C:\Users\Rose\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: 7a3465f6-ba99-4099-8f2a-80f1999d4ced

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 1/10/2022 6:36:09 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1612748390510221386, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 61dc5145
P4: 86d0
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD277.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD297.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD296.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD2B6.tmp.txt
\\?\C:\Users\Rose\AppData\Local\Temp\WERD826.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_8f2a69c17467ec4cf4d4c0b39ac79f6a2cbf5d5_d5c93aa4_11af1235-dbbd-4de9-a0a0-967d43d2894b

Analysis symbol: 
Rechecking for solution: 0
Report Id: 7a3465f6-ba99-4099-8f2a-80f1999d4ced
Report Status: 268435456
Hashed bucket: c6fadd331fda755d7661a21dd071d84a
Cab Guid: 0 }
--------------
{ TimeGenerated = 1/10/2022 6:30:29 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1626999641440620011, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 61dc5145
P4: KERNELBASE.dll
P5: 10.0.19041.1387
P6: 0b9a844a
P7: c000041d
P8: 0000000000034f69
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA479.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA71A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA72B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA73B.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA75B.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_1bf1956df8fd555bc61dcaccc5b8c1baf6252643_d5c93aa4_498cae05-a77f-418a-bcc1-c4381ba12d85

Analysis symbol: 
Rechecking for solution: 0
Report Id: 99684bc6-81a3-49a2-be35-a0598baeb35a
Report Status: 268435456
Hashed bucket: 643e109a2a36980c3694438dbdc18deb
Cab Guid: 0 }

**Comment by maltiez2** [comment]
if bug is still present, please provide full logs and steps to reproduce
