### ISSUE TITLE
Block reinforcements not inheriting from 1.15 world

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#1570]
**Game Version:** 1.16.0
**Platform:** Win10
**Modded:** n/a
**SP/MP:** Singleplayer / Multiplayer (which?)  

### Description
Block reinforcements from the previous game iteration (1.15) are failing to update to the new systems added in 1.16. They, and many locks, will error, and produce the same string in the console.

I understand this may be outside the scope of a 'bug report', but thought it would be wise to bring to the team's attention.

### How to reproduce
1. Make a server. Run it in any version previous to 1.16.
2. Reinforce a block.
3. Error occurs

### Logs
```
13:50:05 [Server Warning] Failed reading block reinforcments at block position, maybe old format. Will attempt to convert.
13:50:05 [Server Error] Failed reading block reinforcments at block position 500603, 111, 499706, will discard, sorry. Exception: ProtoBuf.ProtoException: Invalid wire-type; this usually means you have over-written a file without truncating or setting the length; see http://stackoverflow.com/q/2152978/23354
   at ProtoBuf.ProtoReader.ReadString()
   at proto_134(Object , ProtoReader )
   at ProtoBuf.ProtoReader.ReadTypedObject(Object value, Int32 key, ProtoReader reader, Type type)
   at proto_132(Object , ProtoReader )
   at ProtoBuf.Meta.TypeModel.TryDeserializeAuxiliaryType(ProtoReader reader, DataFormat format, Int32 tag, Type type, Object& value, Boolean skipOtherFields, Boolean asListItem, Boolean autoCreate, Boolean insideList)
   at ProtoBuf.Meta.TypeModel.TryDeserializeList(TypeModel model, ProtoReader reader, DataFormat format, Int32 tag, Type listType, Type itemType, Object& value)
   at ProtoBuf.Meta.TypeModel.TryDeserializeAuxiliaryType(ProtoReader reader, DataFormat format, Int32 tag, Type type, Object& value, Boolean skipOtherFields, Boolean asListItem, Boolean autoCreate, Boolean insideList)
   at ProtoBuf.Meta.TypeModel.DeserializeCore(ProtoReader reader, Type type, Object value, Boolean noAutoCreate)
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context)
   at ProtoBuf.Serializer.Deserialize[T](Stream source)
   at Vintagestory.API.Util.SerializerUtil.Deserialize[T](Byte[] data)
   at Vintagestory.GameContent.ModSystemBlockReinforcement.getOrCreateReinforcmentsAt(BlockPos pos)
```

**Comment by fipil** [comment]
Same on our server.

**Comment by Aledark789** [comment]
Just adding bit of information on this.


**_Also a follow-up issue resulted from this:_**
If a player reinforce the same bloc they did previously (example a lantern outside of their claim) which had a strength 0 when we went to 1.16 without breaking and replacing the bloc first...he wont be able to un-reinforce it anymore even tho he's the one who did it _**also admins with full privileges cannot break the block anymore to fix this issue**_. Super fun when there's 1200 steel ingot reinforced block you gotta break...

Could at least admin with full privileges be able to break those in creative...


First is a 1.15.10 world with blocks i reinforced.
[test reinforced blocks 1-15-10.zip](https://github.com/anegostudios/VintageStory-Issues/files/7955071/test.reinforced.blocks.1-15-10.zip)
Second is same world i loaded in vanilla in 1.16.1 (Stable)
[test reinforced blocks to 1.16.vcdbs.zip](https://github.com/anegostudios/VintageStory-Issues/files/7955073/test.reinforced.blocks.to.1.16.vcdbs.zip)


Video link(2 mins 30 seconds) showing the issue.
https://youtu.be/7e94jtz78hg (watch the video)


I'm out of option as an admin unless there's a patch that could be pushed for this.
The error (180+) errors still occur for us.

I spent over 12 hours fixing them alone + some other admins helped too and I'm not even done and error still occur i teleport to the location that list the problem with absolute values and i don't see any block currently there but the error still happens...

**Comment by bgoetschke** [comment]
This is also the case for reinforced blocks on the official test server.
