### ISSUE TITLE
Crash to desktop while preparing kiln

### ISSUE THREAD

**Issue by maddieknz** [anegostudios/VintageStory-Issues#1575]
**Game Version:** 1.16.0
**Platform:** Windows 10 
**Modded:** wolf taming 1.2.1, carry capacity 0.64
**SP/MP:** Multiplayer

### Description
Game crashes to desktop when trying to make a kiln with 33 shingles.  Crash occurred after place the first piece of grass.

### How to reproduce
I was not able reproduce.  It worked fine the second time.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 64 GB RAM 
Version: v1.16.0 (Stable)1/12/2022 9:41:59 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityPitKiln.DetermineBuildStages()
   at Vintagestory.GameContent.BlockEntityPitKiln.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving)
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(_XyJ0AvcR2vjLZ2mfN5MTsLhbkwg p, ClientMain game)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(_hpqb4cNQuSfxZLdFacKLPiYYWAN packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _lb8GGBWOchQLOU3RFFw58Ijkh1D._uA6fxRiik2om8WbTxul2Dtkekip(Single )
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._HuDdfzha8ZKZvU2y0RbH58r7VzR(Single )
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._XZOFA2JA54yZjH15yys9W7vL9hj(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _FKpOpQGqqf3cJWdQyWh1ysxsDBb._pYad7oBcQ5qtzQkYGDu4NFHQxhK(_5x3PJgrln4IBXPDNSNN0fecxKFb , String[] )
   at _sejP0Tcz8wTg70ptIdRr3CwQmrE._pYad7oBcQ5qtzQkYGDu4NFHQxhK(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/21/2021 9:48:36 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2137399946764805085, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\madde\AppData\Local\Temp\RDRBE.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCF.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE0.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFA.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER11A.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: d69a7242-86a1-466d-88ab-32360f45a84a
Report Status: 268435456
Hashed bucket: 90206cb8882a62a92da991ed59dae3dd
Cab Guid: 0 }
--------------
{ TimeGenerated = 11/3/2021 5:04:51 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1397969068706127840, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.7.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\madde\AppData\Local\Temp\RDRADF1.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAE02.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAE03.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAE20.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAE40.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 1d658d2f-6645-426b-9549-380f47595ed1
Report Status: 268435456
Hashed bucket: a9e621fc64de545c1366957613365fe0
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/1/2021 7:34:05 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1775098558742058606, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.5.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\madde\AppData\Local\Temp\RDRD227.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD228.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD229.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD240.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD260.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: ee57ef09-197f-496b-8f0d-ff16a147979f
Report Status: 268435456
Hashed bucket: d490f7f3f456e29178a26abbfb20d66e
Cab Guid: 0 }
```

Possibly related stack traces that occured  12 seconds prior.

```
12.1.2022 21:41:59 [Error] Exception thrown during OnTesselation() of block entity Vintagestory.GameContent.BlockEntityPitKiln@25185/168/25482: System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityPitKiln.DetermineBuildStages()
   at Vintagestory.GameContent.BlockEntityPitKiln.OnTesselation(ITerrainMeshPool meshdata, ITesselatorAPI tesselator)
   at Vintagestory.Client.NoObf.JsonTesselator.Tesselate(TCTCache vars). Block will probably not be rendered as intended.
12.1.2022 21:41:59 [Error] Exception thrown during OnTesselation() of block entity Vintagestory.GameContent.BlockEntityPitKiln@25185/168/25482: System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityPitKiln.DetermineBuildStages()
   at Vintagestory.GameContent.BlockEntityPitKiln.OnTesselation(ITerrainMeshPool meshdata, ITesselatorAPI tesselator)
   at Vintagestory.Client.NoObf.JsonTesselator.Tesselate(TCTCache vars). Block will probably not be rendered as intended.
```

**Comment by Craluminum2413** [comment]
I cannot reproduce that

**Comment by Craluminum2413** [comment]
Closing due to inactivity
