### ISSUE TITLE
Game Crashing on loading world on PC

### ISSUE THREAD

**Issue by GamerMindset** [anegostudios/VintageStory-Issues#1579]
Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0 (Stable)2022-01-13 8:42:22 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.TextureSource..ctor(ClientMain game, Size2i atlasSize, Block block, Boolean forInventory)
   at Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateBlock(Block block, Nullable`1 quantityElements)
   at Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateBlocks(IList`1 blocks)
   at Vintagestory.Client.NoObf.ClientMain.OnServerBlocksItemsReceivedStep4(Action onCompleted, Int32 blockCount)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _0dbBCVS4kT4NsuDZA84yDu7r3AG._1NlBQQ8qS5idQptIBQaAbARuOfxA(Single )
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._HuDdfzha8ZKZvU2y0RbH58r7VzR(Single )
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._XZOFA2JA54yZjH15yys9W7vL9hj(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _FKpOpQGqqf3cJWdQyWh1ysxsDBb._pYad7oBcQ5qtzQkYGDu4NFHQxhK(_5x3PJgrln4IBXPDNSNN0fecxKFb , String[] )
   at _sejP0Tcz8wTg70ptIdRr3CwQmrE._pYad7oBcQ5qtzQkYGDu4NFHQxhK(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2022-01-11 7:19:08 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2137399946764805085, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\KarlV\AppData\Local\Temp\RDR70E7.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER70E8.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER70F8.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7116.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7136.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: df0d2364-ce00-4b34-9436-88788c224c44
Report Status: 268435456
Hashed bucket: 90206cb8882a62a92da991ed59dae3dd
Cab Guid: 0 }
--------------
{ TimeGenerated = 2021-12-10 7:20:36 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2031197943922000226, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.10.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\KarlV\AppData\Local\Temp\RDR3211.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3221.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3232.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER325F.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER327F.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 91710c86-ee23-4ea3-a752-b69cbe42f0fc
Report Status: 268435456
Hashed bucket: 9abb75f1824b165bdc3043c4abf98162
Cab Guid: 0 }
--------------
{ TimeGenerated = 2021-11-10 7:17:37 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1184350925928560925, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.9.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\KarlV\AppData\Local\Temp\RDRFA2F.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFA40.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFA51.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFA6E.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFA9E.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 7f6f8760-0ba7-4554-a3ef-a425d13956ac
Report Status: 268435456
Hashed bucket: c2c985ff2ae211a1c06fa8e46560791d
Cab Guid: 0 }

**Comment by copygirl** [comment]
See #1572. Does reinstalling the game work?

**Comment by GamerMindset** [comment]
Yes, uninstalling and reinstalling seems to have worked. Thank you

**Comment by copygirl** [comment]
Will close as a duplicate then. I will let the team know that something is going wrong, however.
