### ISSUE TITLE
game crashes for all people who join a server

### ISSUE THREAD

**Issue by DELTACX10** [anegostudios/VintageStory-Issues#1587]
the game crashes whilst loading into a stock server (1.16 on windows)

this happens even after a fresh install of the server and happens 100% of the time to any player who tries to load in.

```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.16.0 (Stable)1/14/2022 2:44:48 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.TextureSource..ctor(ClientMain game, Size2i atlasSize, Block block, Boolean forInventory)
   at Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateBlock(Block block, Nullable`1 quantityElements)
   at Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateBlocks(IList`1 blocks)
   at Vintagestory.Client.NoObf.ClientMain.OnServerBlocksItemsReceivedStep4(Action onCompleted, Int32 blockCount)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _0dbBCVS4kT4NsuDZA84yDu7r3AG._1NlBQQ8qS5idQptIBQaAbARuOfxA(Single )
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._HuDdfzha8ZKZvU2y0RbH58r7VzR(Single )
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._XZOFA2JA54yZjH15yys9W7vL9hj(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _FKpOpQGqqf3cJWdQyWh1ysxsDBb._pYad7oBcQ5qtzQkYGDu4NFHQxhK(_5x3PJgrln4IBXPDNSNN0fecxKFb , String[] )
   at _sejP0Tcz8wTg70ptIdRr3CwQmrE._pYad7oBcQ5qtzQkYGDu4NFHQxhK(ThreadStart )
-------------------------------
```

**Comment by copygirl** [comment]
Related to #1582 and similar issues? I'll keep this issue open since it seems to occur a lot and definitely needs looking into. Have your players reinstalled the game? When reinstalling the server, I assume you deleted all non-world related files rather than overwriting them, correct?

**Comment by DELTACX10** [comment]
Yes, the guy who is paying for the server did wipe everything on the server
side and reinstalled his own game and got the same result.

At this time he has been talking to the support at the hosting company
(host havoc I think) and they are looking into things on their end to make
sure but we have seen other people saying this is a issue so we don't know.

**Comment by Craluminum2413** [comment]
Closing due to inactivity
