### ISSUE TITLE
Client crash on world start/worldgen/server loading

### ISSUE THREAD

**Issue by neonhazmat** [anegostudios/VintageStory-Issues#1596]
**Game Version:** 1.16.0
**Platform:** Windows   
**Modded:** No 
Singleplayer 

### Description
Game crashes partway through loading

### How to reproduce
Attempt  to enter a world
It crashes 

### Expected behavior
Game would load.

### Logs
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.16.0 (Stable)1/16/2022 11:36:23 AM: Critical error occurred
System.MissingMethodException: Method not found: 'System.String[] Vintagestory.API.Datastructures.JsonObject.AsStringArray(System.String[])'.
   at RangedWeapons.ItemRangedWeapon.OnLoaded(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientMain.OnServerBlocksItemsReceivedStep5(Action onCompleted)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _0dbBCVS4kT4NsuDZA84yDu7r3AG._1NlBQQ8qS5idQptIBQaAbARuOfxA(Single )
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._HuDdfzha8ZKZvU2y0RbH58r7VzR(Single )
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._XZOFA2JA54yZjH15yys9W7vL9hj(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _FKpOpQGqqf3cJWdQyWh1ysxsDBb._pYad7oBcQ5qtzQkYGDu4NFHQxhK(_5x3PJgrln4IBXPDNSNN0fecxKFb , String[] )
   at _sejP0Tcz8wTg70ptIdRr3CwQmrE._pYad7oBcQ5qtzQkYGDu4NFHQxhK(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 1/16/2022 1:16:09 AM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.16.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 2c9c

Start Time: 01d80adae7d95ce9

Termination Time: 9

Application Path: C:\Users\neon_\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: fda4bafc-61b7-44e1-a90e-679aa34544bd

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 1/16/2022 1:16:09 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1585882993095566661, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 61dc5145
P4: bae6
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER26F1.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4354.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4365.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4579.tmp.txt
\\?\C:\Users\neon_\AppData\Local\Temp\WER73EA.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_3ff0ba3bdc3c8ac6ed7e31f37a4726e1a4d0092_d5c93aa4_ae007805-1e87-45b8-a0f9-2313e174482f

Analysis symbol: 
Rechecking for solution: 0
Report Id: fda4bafc-61b7-44e1-a90e-679aa34544bd
Report Status: 268435457
Hashed bucket: eae9b1d8db1c0960c602302e0acb6545
Cab Guid: 0 }
--------------
{ TimeGenerated = 1/16/2022 1:13:45 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 61dc5145
P4: f9d7
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDA90.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE148.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE147.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE455.tmp.txt
\\?\C:\Users\neon_\AppData\Local\Temp\WER4F74.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_f2ba6adb6198ea9486d2c62283c8d7edce6740_d5c93aa4_e2845131-5132-4127-924e-11abf7a77441

Analysis symbol: 
Rechecking for solution: 0
Report Id: e55c138a-b750-4e26-a672-53f6cdb74873
Report Status: 97
Hashed bucket: 
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment]
The problem is in Ranged Weapons mod

**Comment by neonhazmat** [comment]
Ah, sorry, I did a fresh reinstall for the .16 update and thought I'd disabled all my mods, thanks for the quick reply!

**Comment by copygirl** [comment]
> `at RangedWeapons.ItemRangedWeapon.OnLoaded(ICoreAPI api)`

Indeed. This line in the crash log was what hinted at the problem being with the mod.
