### ISSUE TITLE
Game crashes for other players if sleeping in Hay Bed.

### ISSUE THREAD

**Issue by Demmon1** [anegostudios/VintageStory-Issues#1599]
**Game Version:** 1.16.1-rc.2
**Platform:** Windows
**Modded:** Yes, but still occurs with all mods disabled.
**SP/MP:** Multiplayer

### Description
Right-clicking to sleep in a hay bed causes the game to crash for other players except the one sleeping. Unknown if this happens to other beds.

### How to reproduce
1. Place a hay bed.
2. Have other player sleep in it.
3. You crash! (other player doesn't)

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.16.1-rc.2 (Unstable)
Loaded Mods: game@1.16.1-rc.2, creative@1.16.1-rc.2, survival@1.16.1-rc.2
1/16/2022 4:36:13 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityShapeRenderer.DoRender2D(Single dt)
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderFrame2D(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _DamzNweBDxmMicnVulmwlMVMgM0._sMengaVDGYAisCAjabTHQK1RXqp(Single )
   at _WdmvE2d6J9HzNHSLADtYYbMD8ON._yMRD15GhtGxOhlM5XwrrrhTIRjg(Single )
   at _WdmvE2d6J9HzNHSLADtYYbMD8ON._tUTr5b63b3ZOBglH3L8fLMXFFhE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _onk6uFpqwcbPW6YzuZhhUdPywZf._VX8KgZtGV3ZCueYlgfrjdPvyuhh(_eyDkp85wcsatK4hyRtVBSqG8y9l , String[] )
   at _RE6vupBBnuxpHTQrO531ET777xk._VX8KgZtGV3ZCueYlgfrjdPvyuhh(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 1/16/2022 4:34:33 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1597126746590980470, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.1.0
P3: 61e3e36b
P4: KERNELBASE.dll
P5: 10.0.19041.1466
P6: e01c7650
P7: c000041d
P8: 0000000000034f69
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8B44.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8F3D.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8F4D.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8F5D.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8F7D.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_7e2e08177a8976fb805882c455c35dfc796b34_7fd92063_ba7d89b1-21cb-4250-af02-017b32de38d1

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9b347858-82e8-43d2-a1e4-dbb5cdfe632a
Report Status: 268435456
Hashed bucket: aca8076d4c6d1e8a662a225067d4a976
Cab Guid: 0 }
--------------
{ TimeGenerated = 1/16/2022 4:34:31 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.16.1.0, time stamp: 0x61e3e36b
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1466, time stamp: 0xe01c7650
Exception code: 0xc000041d
Fault offset: 0x0000000000034f69
Faulting process id: 0xe74
Faulting application start time: 0x01d80b20b18876e4
Faulting application path: C:\Users\Demmon1\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 9b347858-82e8-43d2-a1e4-dbb5cdfe632a
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 1/16/2022 4:34:30 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2252807566908109657, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.1.0
P3: 61e3e36b
P4: KERNELBASE.dll
P5: 10.0.19041.1466
P6: e01c7650
P7: c0020001
P8: 0000000000034f69
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7E34.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER823C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER825D.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER825B.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER827B.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_c8621959d1566ee26f4765bcb35153d6a7738c_7fd92063_399123bc-8488-41ba-bc56-ce00029f92c9

Analysis symbol: 
Rechecking for solution: 0
Report Id: 8478e79b-173d-44e2-9914-39d60bf53ac2
Report Status: 268435456
Hashed bucket: 09fca2dbd46c70d78f43948bd4deb359
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
