### ISSUE TITLE
1.5.2.1 knapping red clay crash

### ISSUE THREAD

**Issue by radiocrack** [anegostudios/VintageStory-Issues#16]
I tried knapping with red clay

I had 4 red clay and shift-click on the ground to begin knapping

```
2018-03-20 11:15:52 PM: Critical error occurred
System.Exception: Can't create itemstack without item!
   at Vintagestory.API.Common.ItemStack..ctor(Item item, Int32 stacksize)
   at Vintagestory.GameContent.BlockEntityClayForm.PutClay(IItemSlot slot)
   at Vintagestory.GameContent.ItemClay.OnHeldInteractStart(IItemSlot slot, IEntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.API.Common.CollectibleObject.OnHeldUseStart(IItemSlot slot, IEntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, EnumHeldItemUse useType)
   at _R5fCX5y0aB2nX8CvaWbAx4z8bhU._YijDZmXHMZ4dHBJfgC4YPeDTbMhA(BlockSelection , EntitySelection , EnumHeldItemUse )
   at _R5fCX5y0aB2nX8CvaWbAx4z8bhU._mMDoGUm6ydUVYozlxmYoabMIQoo(Single )
   at _R5fCX5y0aB2nX8CvaWbAx4z8bhU._ESA8Ol9vzMlwXtyPPdxLO8JBy7i(Single )
   at _dMEBIj2d4rGFMeJLUtorzMHWE2M._2U0T3QxpvTg6S99WFxFrX2tLdoH(EnumRenderStage , Single )
   at _dMEBIj2d4rGFMeJLUtorzMHWE2M._TIHlmhWjRxybDgBGwqNXNX3IekB(Single )
   at _dQ8UsaC1cx3V0luDwfnOC9V16Y._TIHlmhWjRxybDgBGwqNXNX3IekB(Single )
   at _sPDuh4gIO8FyRaA657gG8bYlN6b._5xT15N45LDO7iR4pvkchveIBjjA(Single )
   at _sPDuh4gIO8FyRaA657gG8bYlN6b._AS2ij50wecyOwxvpI96wDEDDAzP(Single )
   at _HGE7K6wFiUDXaxEbdSNDd7Y4uYp._TVE3QsNRO891pCPkbuOE0MlzxJp(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _yfC6KJ78gHaaRrzSYs8upw66O7b._sZWHZ3ytYqe9vtV5yWoqJna6w9b(_D4acqzKIQfPOuworRl9XU0LuzBK , String[] )
   at _hhVpdfZdAmYMOIGo8UOCEY1JNd8._sZWHZ3ytYqe9vtV5yWoqJna6w9b(ThreadStart )
```

**Comment by tyronx** [comment]
There is no red clay in the game, is that from a mod?

**Comment by copygirl** [comment]
Came crashes for me when the stack is completely used up as I start clayforming, as in when I'm holding just 1 clay ball. Not the same error though in this case:

```
System.NullReferenceException: Object reference not set to an instance of an object
  at Vintagestory.GameContent.BlockEntityClayForm.OpenDialog (Vintagestory.API.Client.IClientWorldAccessor world, Vintagestory.API.MathTools.BlockPos pos, Vintagestory.API.Common.ItemStack ingredient) [0x00006] in <55c0945eee644ee890c30837a49e36ad>:0 
  at Vintagestory.GameContent.ItemClay.OnHeldInteractStart (Vintagestory.API.Common.IItemSlot slot, Vintagestory.API.Common.Entities.IEntityAgent byEntity, Vintagestory.API.Common.BlockSelection blockSel, Vintagestory.API.Common.EntitySelection entitySel) [0x0011c] in <55c0945eee644ee890c30837a49e36ad>:0 
  at Vintagestory.API.Common.CollectibleObject.OnHeldUseStart (Vintagestory.API.Common.IItemSlot slot, Vintagestory.API.Common.Entities.IEntityAgent byEntity, Vintagestory.API.Common.BlockSelection blockSel, Vintagestory.API.Common.EntitySelection entitySel, Vintagestory.API.Common.EnumHeldItemUse useType) [0x00005] in <9aef57b7b0a448cca773b93746f8390e>:0 
  at _R5fCX5y0aB2nX8CvaWbAx4z8bhU._YijDZmXHMZ4dHBJfgC4YPeDTbMhA (Vintagestory.API.Common.BlockSelection , Vintagestory.API.Common.EntitySelection , Vintagestory.API.Common.EnumHeldItemUse ) [0x00078] in <84c3bca7706045cc85a1cbe08b2cf2a1>:0 
  at _R5fCX5y0aB2nX8CvaWbAx4z8bhU._mMDoGUm6ydUVYozlxmYoabMIQoo (System.Single ) [0x002d7] in <84c3bca7706045cc85a1cbe08b2cf2a1>:0 
  at _R5fCX5y0aB2nX8CvaWbAx4z8bhU._DJRUdNiiujGyYBPpakOU3UO7MCb (System.Single ) [0x0008c] in <84c3bca7706045cc85a1cbe08b2cf2a1>:0 
  at _R5fCX5y0aB2nX8CvaWbAx4z8bhU._ESA8Ol9vzMlwXtyPPdxLO8JBy7i (System.Single ) [0x00031] in <84c3bca7706045cc85a1cbe08b2cf2a1>:0 
  at _dMEBIj2d4rGFMeJLUtorzMHWE2M._2U0T3QxpvTg6S99WFxFrX2tLdoH (Vintagestory.API.Client.EnumRenderStage , System.Single ) [0x00024] in <84c3bca7706045cc85a1cbe08b2cf2a1>:0 
  at _dMEBIj2d4rGFMeJLUtorzMHWE2M._TIHlmhWjRxybDgBGwqNXNX3IekB (System.Single ) [0x000b7] in <84c3bca7706045cc85a1cbe08b2cf2a1>:0 
  at _dQ8UsaC1cx3V0luDwfnOC9V16Y._TIHlmhWjRxybDgBGwqNXNX3IekB (System.Single ) [0x00034] in <84c3bca7706045cc85a1cbe08b2cf2a1>:0 
  at _sPDuh4gIO8FyRaA657gG8bYlN6b._5xT15N45LDO7iR4pvkchveIBjjA (System.Single ) [0x0010b] in <84c3bca7706045cc85a1cbe08b2cf2a1>:0 
  at _sPDuh4gIO8FyRaA657gG8bYlN6b._AS2ij50wecyOwxvpI96wDEDDAzP (System.Single ) [0x000bf] in <84c3bca7706045cc85a1cbe08b2cf2a1>:0 
  at _HGE7K6wFiUDXaxEbdSNDd7Y4uYp._TVE3QsNRO891pCPkbuOE0MlzxJp (System.Object , OpenTK.FrameEventArgs ) [0x000c3] in <84c3bca7706045cc85a1cbe08b2cf2a1>:0 
  at (wrapper delegate-invoke) System.EventHandler`1[OpenTK.FrameEventArgs].invoke_void_object_TEventArgs(object,OpenTK.FrameEventArgs)
  at OpenTK.GameWindow.OnRenderFrame (OpenTK.FrameEventArgs e) [0x00000] in <3b8abd1853f347e298f7bcc0ea7c6465>:0 
  at OpenTK.GameWindow.OnRenderFrameInternal (OpenTK.FrameEventArgs e) [0x00010] in <3b8abd1853f347e298f7bcc0ea7c6465>:0 
  at OpenTK.GameWindow.RaiseRenderFrame (System.Double elapsed, System.Double& timestamp) [0x0000c] in <3b8abd1853f347e298f7bcc0ea7c6465>:0 
  at OpenTK.GameWindow.DispatchRenderFrame () [0x00038] in <3b8abd1853f347e298f7bcc0ea7c6465>:0 
  at OpenTK.GameWindow.Run (System.Double updates_per_second, System.Double frames_per_second) [0x00104] in <3b8abd1853f347e298f7bcc0ea7c6465>:0 
  at OpenTK.GameWindow.Run () [0x00000] in <3b8abd1853f347e298f7bcc0ea7c6465>:0 
  at _yfC6KJ78gHaaRrzSYs8upw66O7b._sZWHZ3ytYqe9vtV5yWoqJna6w9b (_D4acqzKIQfPOuworRl9XU0LuzBK , System.String[] ) [0x0015c] in <ba59571e6ab44b76882c87bef0c81faa>:0 
  at _yfC6KJ78gHaaRrzSYs8upw66O7b+_WXWJqdyDLk99JOyXnlbghFXs8fH._9KU2y1DqBMvAe9MUU3kxGo8IN7r () [0x00000] in <ba59571e6ab44b76882c87bef0c81faa>:0 
  at _hhVpdfZdAmYMOIGo8UOCEY1JNd8._sZWHZ3ytYqe9vtV5yWoqJna6w9b (System.Threading.ThreadStart ) [0x00007] in <84c3bca7706045cc85a1cbe08b2cf2a1>:0 
```

**Comment by tyronx** [comment]
That should be a seperate issue copygirl but i fixed your crash now, also the recipe selector got opened twice, also fixed.

**Comment by radiocrack** [comment]
Sorry it must have been a mod.  I thought have been playing this new version without mods.  I was wondering where "red clay" came from.  I'll be more careful next time.
