### ISSUE TITLE
Hacked locusts produce NullReferenceExceptions in "server-main" logs until "hacker" joins.

### ISSUE THREAD

**Issue by Demmon1** [anegostudios/VintageStory-Issues#1600]
**Game Version:** 1.16.1-rc.2
**Platform:** Windows
**Modded:** Yes, but still occurs with all mods disabled.
**SP/MP:** Multiplayer

### Description
Constant NullReferenceExceptions recorded in the "server-main.txt" log before player with hacked-locust follower joins the game. No crash.

### How to reproduce
1. Have another player hack a locust.
2. Re-open the server.
3. Have said player join.
4. Check the "server-main.txt" logs for NullReferenceExceptions.
5. Note that they stop as soon as said player joins.

### Logs
(For clarity: "Piwix" is the one who hacked the locust)
```
(Snippet of "server-main.txt")
16.1.2022 16:35:16 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.AiTaskStayCloseToGuardedEntity.GetGuardedEntity()
   at Vintagestory.GameContent.AiTaskStayCloseToGuardedEntity.ShouldExecute()
   at Vintagestory.GameContent.AiTaskManager.OnGameTick(Single dt)
   at Vintagestory.GameContent.EntityBehaviorTaskAI.OnGameTick(Single deltaTime)
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt)
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt)
   at Vintagestory.GameContent.EntityLocust.OnGameTick(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt)
   at Vintagestory.Server.ServerMain.Process()
16.1.2022 16:35:16 [Notification] A Client attempts connecting via TCP, assigning client id 2
16.1.2022 16:35:16 [Notification] Client uid CI2NUGyK7+T/KzFysJADgf7S attempting identification. Name: Piwix
16.1.2022 16:35:16 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.AiTaskBaseTargetable.GetGuardedEntity()
   at Vintagestory.GameContent.AiTaskJealousMeleeAttack.ShouldExecute()
   at Vintagestory.GameContent.AiTaskManager.OnGameTick(Single dt)
   at Vintagestory.GameContent.EntityBehaviorTaskAI.OnGameTick(Single deltaTime)
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt)
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt)
   at Vintagestory.GameContent.EntityLocust.OnGameTick(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt)
   at Vintagestory.Server.ServerMain.Process()
16.1.2022 16:35:16 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.AiTaskBaseTargetable.GetGuardedEntity()
   at Vintagestory.GameContent.AiTaskJealousMeleeAttack.ShouldExecute()
   at Vintagestory.GameContent.AiTaskManager.OnGameTick(Single dt)
   at Vintagestory.GameContent.EntityBehaviorTaskAI.OnGameTick(Single deltaTime)
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt)
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt)
   at Vintagestory.GameContent.EntityLocust.OnGameTick(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt)
   at Vintagestory.Server.ServerMain.Process()
16.1.2022 16:35:16 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.AiTaskBaseTargetable.GetGuardedEntity()
   at Vintagestory.GameContent.AiTaskJealousSeekEntity.ShouldExecute()
   at Vintagestory.GameContent.AiTaskManager.OnGameTick(Single dt)
   at Vintagestory.GameContent.EntityBehaviorTaskAI.OnGameTick(Single deltaTime)
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt)
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt)
   at Vintagestory.GameContent.EntityLocust.OnGameTick(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt)
   at Vintagestory.Server.ServerMain.Process()
16.1.2022 16:35:16 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.AiTaskBaseTargetable.GetGuardedEntity()
   at Vintagestory.GameContent.AiTaskJealousMeleeAttack.ShouldExecute()
   at Vintagestory.GameContent.AiTaskManager.OnGameTick(Single dt)
   at Vintagestory.GameContent.EntityBehaviorTaskAI.OnGameTick(Single deltaTime)
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt)
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt)
   at Vintagestory.GameContent.EntityLocust.OnGameTick(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt)
   at Vintagestory.Server.ServerMain.Process()
16.1.2022 16:35:17 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.AiTaskBaseTargetable.GetGuardedEntity()
   at Vintagestory.GameContent.AiTaskJealousSeekEntity.ShouldExecute()
   at Vintagestory.GameContent.AiTaskManager.OnGameTick(Single dt)
   at Vintagestory.GameContent.EntityBehaviorTaskAI.OnGameTick(Single deltaTime)
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt)
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt)
   at Vintagestory.GameContent.EntityLocust.OnGameTick(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt)
   at Vintagestory.Server.ServerMain.Process()
16.1.2022 16:35:17 [Notification] Placing player at 516425.71875 110.125 517491.75
16.1.2022 16:35:18 [Event] Device with external ip 69.47.119.238 found. Created mapping for port 42420!
16.1.2022 16:35:27 [Event] Piwix [::ffff:76.19.239.222]:62299 joins.
(End of "server-main.txt")
```
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/7878029/server-main.txt)

**Comment by Craluminum2413** [comment]
Closing due to inactivity
