### ISSUE TITLE
Client crashing after mod update on server

### ISSUE THREAD

**Issue by cyraxan** [anegostudios/VintageStory-Issues#1601]
**Game Version:** 1.16.0  
**Platform:** Windows  
**Modded:** Yes, any mod  
**SP/MP:** Multiplayer 

### Description
Client crashing after mod update on server.
Version: v1.16.0 (Stable) 16.01.2022 10:57:53: Critical error occurred
System.ArgumentException: An item with the same key has already been added.

### How to reproduce
1. Install mod_v.1.1 with "ModID": "anCustomMod" and  "Version": "1.1" by copy "anCustomMod_v1.1.zip" to \Mods 
2. Start VintageStoryServer.exe, confirm that anCustomMod v1.1 loaded.
2. Connect client to server, let it download mod and joins server.
3. Stop server
4. Delete \Mods\anCustomMod_v1.1.zip 
5. Install mod_v.1.2 with "ModID": "anCustomMod" by copy "anCustomMod_v1.2.zip" to \Mods 
6. Start VintageStoryServer.exe, confirm that anCustomMod v.1.2 loaded.
7. Connect client to server, let it download anCustomMod v.1.2.
8. Confirm that both "anCustomMod_v1.1.zip" and "anCustomMod_v1.2.zip" exists in Client\ModsByServer\[IP]\ folder.
9. Connect client to server and get crash with error:
Critical error occurred
System.ArgumentException: An item with the same key has already been added.

### Expected behavior
Crash, error 
Critical error occurred
System.ArgumentException: An item with the same key has already been added.

### Logs
Version: v1.16.0 (Stable) 16.01.2022 10:57:53: Critical error occurred
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Vintagestory.Common.ModLoader.CheckAndSortDependencies(IEnumerable`1 mods)
   at Vintagestory.Common.ModLoader.DisableAndVerify(List`1 mods, IEnumerable`1 disabledModsByIdAndVersion)
   at Vintagestory.Client.NoObf.SystemModHandler.OnServerIdentificationReceived()
   at Vintagestory.Client.NoObf.ClientMain.ProcessServerIdentification(_hpqb4cNQuSfxZLdFacKLPiYYWAN packet)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerIdent(_hpqb4cNQuSfxZLdFacKLPiYYWAN packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _0dbBCVS4kT4NsuDZA84yDu7r3AG._1NlBQQ8qS5idQptIBQaAbARuOfxA(Single )

**Comment by eruptionx** [comment]
блин, сурахан, где найти этот мод то? нигде не могу найти его

**Comment by cyraxan** [comment]
> блин, сурахан, где найти этот мод то? нигде не могу найти его

имелся ввиду "любой мод"

**Comment by tyronx** [comment]
Thanks for the report, this is fixed since 1.16.1-rc.1
