### ISSUE TITLE
Sleeping in bed crashes other players on server

### ISSUE THREAD

**Issue by ZUCOZUCO** [anegostudios/VintageStory-Issues#1602]
**Game Version:**  v1.16.1-rc.2   
**Platform:** Windows  
**Modded:** No
**SP/MP:** Multiplayer

### Description
Everyone else on the server's client crashes immediately when a player tries to sleep in a bed.
The player who sleeps does not get kicked.

### How to reproduce
1. Make a bed.
2. Sleep in bed when other players are online.
3. watch everyone crash
4. ???
5. profit?

### Expected behavior
No crash, just normal sleep cycle

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

Apparently this can happen as well:

![vintage story sleep glitch](https://user-images.githubusercontent.com/97935257/149877541-2111c14d-f7c7-488c-9975-0bc1e63e68de.PNG)

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.1-rc.2 (Unstable)
Loaded Mods: game@1.16.1-rc.2, creative@1.16.1-rc.2, survival@1.16.1-rc.2
1/18/2022 12:31:55 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityShapeRenderer.DoRender2D(Single dt)
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderFrame2D(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _DamzNweBDxmMicnVulmwlMVMgM0._sMengaVDGYAisCAjabTHQK1RXqp(Single )
   at _WdmvE2d6J9HzNHSLADtYYbMD8ON._yMRD15GhtGxOhlM5XwrrrhTIRjg(Single )
   at _WdmvE2d6J9HzNHSLADtYYbMD8ON._tUTr5b63b3ZOBglH3L8fLMXFFhE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _onk6uFpqwcbPW6YzuZhhUdPywZf._VX8KgZtGV3ZCueYlgfrjdPvyuhh(_eyDkp85wcsatK4hyRtVBSqG8y9l , String[] )
   at _RE6vupBBnuxpHTQrO531ET777xk._VX8KgZtGV3ZCueYlgfrjdPvyuhh(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 1/3/2022 5:29:23 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1478716220082461302, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Nick\AppData\Local\Temp\RDRDC36.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDC47.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDC58.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDC75.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDC95.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 8a87e71b-118c-486a-8563-36049f1a7814
Report Status: 268435456
Hashed bucket: 1f92a0c50d25295c648574914d9f9a76
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
