### ISSUE TITLE
Game crashes while using any create single player save buttons.

### ISSUE THREAD

**Issue by clericcraft** [anegostudios/VintageStory-Issues#1604]
**Game Version:** 1.16  
**Platform:** Windows   
**Modded:** No
**SP/MP:** Singleplayer 

### Description
Game crashes while attempting to create a new save and soft freezes attempting to load old saves.       

### How to reproduce
1. Go to single player tab
2. Attempt to create new save
3. click the name generator (dice) or any other button to do with creating a new save.

### Expected behavior
Game crashes to desk top and gives crash report

### Screenshots
http://prntscr.com/26f0osj
http://prntscr.com/26f0owp
http://prntscr.com/26f0pbo
http://prntscr.com/26f0pfk
http://prntscr.com/26f0phj

### Logs
```
Version: v1.16.0 (Stable)1/17/2022 10:47:13 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _rxPAXt24X4agovgG2TbC86mg9hfB._XLABfJKtw1XD31jxj9E9fawtnIq()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _kRNQrTEidJmQaGU3FH7i4dBfjO._XLAW09aTr2yuQomhR4MaXizqtMf(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at _FKpOpQGqqf3cJWdQyWh1ysxsDBb._pYad7oBcQ5qtzQkYGDu4NFHQxhK(_5x3PJgrln4IBXPDNSNN0fecxKFb , String[] )
   at _sejP0Tcz8wTg70ptIdRr3CwQmrE._pYad7oBcQ5qtzQkYGDu4NFHQxhK(ThreadStart )
```

**Comment by clericcraft** [comment]
I had used mods to this point, however moving the instal and completely uninstalling and reinstalling the game did not solve the issue.

**Comment by clericcraft** [comment]
I may have been an idiot. 

The game has 3 core nodes that are for some reason currently found in the "mods" section. Unchecking and/or removing these doesn't help you play the game.

For reference, DO NOT remove or uncheck:
Creative Mode (Code)
Essentials (Code)
or
Survival Mode (Code)

**Comment by copygirl** [comment]
I was thinking this was the problem, but the game is supposed to let you know when you don't have the default mods selected. I will bug the developers about this as well.
