### ISSUE TITLE
Player unable to load onto any server, singleplayer unresponsive

### ISSUE THREAD

**Issue by VintageCiv** [anegostudios/VintageStory-Issues#1626]
1.16.0
Vanilla and Modded

We have already done a clean install, and tried multiple servers, as well as vanilla. His net framework is up to date.
[client-main (1).txt](https://github.com/anegostudios/VintageStory-Issues/files/7916383/client-main.1.txt)
[client-crash (1).txt](https://github.com/anegostudios/VintageStory-Issues/files/7916385/client-crash.1.txt)

**Comment by Ragolution** [comment]
Windows, Linux, Mac or Emulated?

**Comment by copygirl** [comment]
Looks like this is the error:
```
21.1.2022 13:30:34 [Fatal] Version: v1.16.0 (Stable)1/21/2022 1:30:34 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.CharacterSystem.Event_PlayerJoin(IClientPlayer byPlayer)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(_hpqb4cNQuSfxZLdFacKLPiYYWAN packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
```

**Comment by VintageCiv** [comment]
> Looks like this is the error:
> 
> ```
> 21.1.2022 13:30:34 [Fatal] Version: v1.16.0 (Stable)1/21/2022 1:30:34 PM: Critical error occurred
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Vintagestory.GameContent.CharacterSystem.Event_PlayerJoin(IClientPlayer byPlayer)
>    at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(_hpqb4cNQuSfxZLdFacKLPiYYWAN packet)
>    at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
> ```

I agree. He was able to play in 1.15, updated the game, and now he cant play pretty much at all.

**Comment by tyronx** [comment]
Disable all mods, try again, send me log files if it still fails

**Comment by VintageCiv** [comment]
He has no mods

**Comment by tyronx** [comment]
he does according to the log files

**Comment by tyronx** [comment]
21.1.2022 13:28:35 [Notification] Found 22 mods (0 disabled)
21.1.2022 13:28:35 [Notification] Mods, sorted by dependency: ancienttools, civmods, globalbloc, instruments, moreroads, primitivesurvival, qptech, shacklegear, tradeomat, vintageciv, game, carrycapacity, medievalexpansion, stonequarry, creative, survival, workbenchexpansion, xlib, xmelee, xrowboat, bricklayers, xskills
21.1.2022 13:28:36 [Notification] Instantiated 117 mod systems from 22 enabled mods

**Comment by VintageCiv** [comment]
huh, he said he did a clean install. Those are the logs from when he tried to join the server... One second.

**Comment by VintageCiv** [comment]
> 21.1.2022 13:28:35 [Notification] Found 22 mods (0 disabled) 21.1.2022 13:28:35 [Notification] Mods, sorted by dependency: ancienttools, civmods, globalbloc, instruments, moreroads, primitivesurvival, qptech, shacklegear, tradeomat, vintageciv, game, carrycapacity, medievalexpansion, stonequarry, creative, survival, workbenchexpansion, xlib, xmelee, xrowboat, bricklayers, xskills 21.1.2022 13:28:36 [Notification] Instantiated 117 mod systems from 22 enabled mods

I cant get ahold of him at the moment, but he essentially gets the same error when he joins any server. His vanilla mod-less experience, he kind of just crashes with no logs. He played 1.15 just fine, but he updated to 1.16, did 2 clean installs, and got this result without mods either.

**Comment by tyronx** [comment]
Uninstalling the game does not remove any installed mods, it only removes the installed files, so my above request still stands. Disable all mods, send me log files if the problem persists.

**Comment by VintageCiv** [comment]
> Uninstalling the game does not remove any installed mods, it only removes the installed files, so my above request still stands - disable all mods, send me log files if the problem persists.

Respectfully, he deleted vintage story from his hard drive, and installed it. I will have him remake log files today.

**Comment by tyronx** [comment]
Oh and let him join a singleplayer or a vanilla server, if he joins vintageciv he'll have the mods installed again

**Comment by copygirl** [comment]
I believe the uninstaller does not touch your files in `%AppData%/VintagestoryData`, where for example your worlds (might not want them gone forever) but also your mods are (or should be) stored.

**Comment by VintageCiv** [comment]
> Oh and let him join a singleplayer or a vanilla server for the test, if he joins vintageciv he'll have the mods installed again

I am tracking that. It was hard to get logs with vanilla because it would just stutter and hard crash. He got the same errors when joining a vanilla server if I remember correctly.

**Comment by VintageCiv** [comment]
[client-main (2).txt](https://github.com/anegostudios/VintageStory-Issues/files/7918812/client-main.2.txt)
[client-crash (2).txt](https://github.com/anegostudios/VintageStory-Issues/files/7918813/client-crash.2.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/7918814/client-debug.txt)


Vanilla game, vanilla server

**Comment by copygirl** [comment]
The new logs don't mention any mods anymore. Was the server previously modded? Did something else occur before the player was unable to connect? Just trying to find anything that might make it easier to pinpoint the cause for Tyron.

**Comment by VintageCiv** [comment]
No. He has this issue with vanilla servers and singleplayer. You guys just wanted logs that had no mods on them, so thats what we replicated

**Comment by copygirl** [comment]
Ah, my fault, I misread your messages. I had a short-ish look at the game code and can't quite make sense of why the error is occurring in that particular function. My only guess so far is there is another problem that causes the client player to disconnect before even fully connected, and then a null parameter is passed to `Event_PlayerJoin` - or somehow the world or `world.Player` is null?

This all seems very weird and certainly unique to ... only this specific player, right?

Since that error seems to occur when connecting to the server - is there anything suspicious in the server's log file when the player connects?

Is the error when joining a singleplayer world the same?

**Comment by VintageCiv** [comment]
He crashes when he does singleplayer. server recognizes it as a player crashed

**Comment by VintageCiv** [comment]
> Ah, my fault, I misread your messages. I had a short-ish look at the game code and can't quite make sense of why the error is occurring in that particular function. My only guess so far is there is another problem that causes the client player to disconnect before even fully connected, and then a null parameter is passed to `Event_PlayerJoin` - or somehow the world or `world.Player` is null?
> 
> This all seems very weird and certainly unique to ... only this specific player, right?
> 
> Since that error seems to occur when connecting to the server - is there anything suspicious in the server's log file when the player connects?
> 
> Is the error when joining a singleplayer world the same?

and yes only this player. His game is fine on 1.15

**Comment by Ragolution** [comment]
> My only guess so far is there is another problem that causes the client player to disconnect before even fully connected, and then a null parameter is passed to `Event_PlayerJoin` - or somehow the world or `world.Player` is null?

I don't know if Kickflip ever said anything, but I mentioned this in a message I was expecting to be conveyed to you. This amy seem exceptionally silly, but do you have him disabling the mods in the game client?

**Comment by copygirl** [comment]
> I don't know if Kickflip ever said anything, but I mentioned this in a message I was expecting to be conveyed to you. This may seem exceptionally silly, but do you have him disabling the mods in the game client?

There were no mods loaded when the most recent log files were created:
```
22.1.2022 12:06:30 [Notification] Found 3 mods (0 disabled)
22.1.2022 12:06:30 [Notification] Mods, sorted by dependency: game, creative, survival
22.1.2022 12:06:31 [Notification] Instantiated 76 mod systems from 3 enabled mods
```

**Comment by Ragolution** [comment]
Ah damn I didn't even see that 2nd set of log files, thank you. Time for me to lern2read.

**Comment by tyronx** [comment]
ooooh, I might have a theory.
```
22.1.2022 12:04:09 [Notification] 0: {X=0,Y=0,Width=1360,Height=768}, \\.\DISPLAY1 (primary)
22.1.2022 12:04:10 [Notification] Graphics Card Renderer: Intel(R) HD Graphics 4000
```

What are the hardware specs of this computer? (CPU, RAM and GPU). Judging by above lines and the time stamps of the log file, this seems to be *very* low end hardware.

It might be that the very slow startup triggers a race condition that might otherwise not happen if the game would load up faster.

**Comment by VintageCiv** [comment]
![image](https://user-images.githubusercontent.com/96968356/150679716-a6fbbd81-64a1-464a-beb9-c6eb67b3dbc8.png)
He was able to play 1.15 just fine. It was this update that made his computer break.

**Comment by tyronx** [comment]
Thanks, seems not too bad actually. Can you also send me his local server-main.txt please. Actually DM me his entire VintageStoryData folder as a zip file, please

**Comment by Ragolution** [comment]
From what I understand, this issue was resolved when plant swaying was disabled.

**Comment by Aledark789** [comment]
> From what I understand, this issue was resolved when plant swaying was disabled.

Yup that,s what i've been told too by Southern and iii ( who had this bug)

**Comment by Craluminum2413** [comment]
Closing due to inactivity
