### ISSUE TITLE
1.16.1 (stable)- Fruit trees classname DynamicTreeBranch: System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Aledark789** [anegostudios/VintageStory-Issues#1632]
**Game Version:** 1.16.1 (stable)
**Platform:** Windows
**Modded:** Yes
bettercrates@1.4.1, 
extrachests@1.5.1, 
instruments@1.1.1, 
specializedbags-10Slot@0.4.1, 
tradeomat@1.6.0, 
farmlanddropssoil@1.4.0, 
medievalexpansion@3.7.1, 
workbenchexpansion@1.4.1,
bricklayers@0.8.1,
carrycapacity@0.6.4, 
[AF-Mods.zip](https://github.com/anegostudios/VintageStory-Issues/files/7921062/AF-Mods.zip)
**SP/MP:** Multiplayer (Aura Fury test server)  

### How to reproduce
the client was exploring and eventually server kicked her. I suppose it has to do with the fruit trees?

### Logs
```
22.1.2022 16:36:38 [Notification] Track music/daylight.ogg now started
22.1.2022 16:44:30 [Error] Exception thrown when initializing a block entity with classname DynamicTreeBranch: System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AssetLocation.Create(String domainAndPath, String defaultDomain)
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.Initialize(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientChunk.InitBlockEntitiesFromPacket(ClientMain game)
22.1.2022 16:44:30 [Error] Exception thrown when initializing a block entity with classname DynamicTreeBranch: System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AssetLocation.Create(String domainAndPath, String defaultDomain)
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.Initialize(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientChunk.InitBlockEntitiesFromPacket(ClientMain game)
22.1.2022 16:50:56 [Notification] Track music/adventuring.ogg now started
22.1.2022 16:50:59 [Error] Exception thrown when initializing a block entity with classname DynamicTreeBranch: System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AssetLocation.Create(String domainAndPath, String defaultDomain)
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.Initialize(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientChunk.InitBlockEntitiesFromPacket(ClientMain game)
22.1.2022 16:50:59 [Error] Exception thrown when initializing a block entity with classname DynamicTreeBranch: System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AssetLocation.Create(String domainAndPath, String defaultDomain)
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.Initialize(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientChunk.InitBlockEntitiesFromPacket(ClientMain game)
22.1.2022 16:55:00 [Error] Exception thrown when initializing a block entity with classname DynamicTreeBranch: System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AssetLocation.Create(String domainAndPath, String defaultDomain)
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.Initialize(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientChunk.InitBlockEntitiesFromPacket(ClientMain game)
22.1.2022 16:55:00 [Error] Exception thrown when initializing a block entity with classname DynamicTreeBranch: System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AssetLocation.Create(String domainAndPath, String defaultDomain)
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.Initialize(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientChunk.InitBlockEntitiesFromPacket(ClientMain game)
22.1.2022 17:05:26 [Error] Exception thrown when initializing a block entity with classname DynamicTreeBranch: System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AssetLocation.Create(String domainAndPath, String defaultDomain)
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.Initialize(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientChunk.InitBlockEntitiesFromPacket(ClientMain game)
22.1.2022 17:05:26 [Error] Exception thrown when initializing a block entity with classname DynamicTreeBranch: System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AssetLocation.Create(String domainAndPath, String defaultDomain)
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.Initialize(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientChunk.InitBlockEntitiesFromPacket(ClientMain game)
22.1.2022 17:05:50 [Notification] Track music/to-dawn.ogg now started
22.1.2022 17:08:19 [Error] Exception thrown when initializing a block entity with classname DynamicTreeBranch: System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AssetLocation.Create(String domainAndPath, String defaultDomain)
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.Initialize(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientChunk.InitBlockEntitiesFromPacket(ClientMain game)
22.1.2022 17:08:19 [Error] Exception thrown when initializing a block entity with classname DynamicTreeBranch: System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AssetLocation.Create(String domainAndPath, String defaultDomain)
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.Initialize(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientChunk.InitBlockEntitiesFromPacket(ClientMain game)
22.1.2022 17:18:42 [Error] The connection closed unexpectedly.
22.1.2022 17:18:42 [Error] System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.TCPNetworkConnection.OnBytesReceived(IAsyncResult result)
22.1.2022 17:18:42 [Notification] Destroying game session, waiting up to 200ms for client threads to exit
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
