### ISSUE TITLE
Tried to log on to VS Public Server and WHAM!

### ISSUE THREAD

**Issue by Nashtyfos** [anegostudios/VintageStory-Issues#1654]
**Game Version:** 1.16.1 (Stable)
**Platform:** Windows
**Modded:** Yes
**SP/MP:** Multiplayer

### Description
I read on Discord #devlog @Tyron stated on 1/27/2022 @ 02:21 PDT:
"To server owners suffering..."

So, I decided to try logging onto the VS Public Server to help him out...maybe...not likely, but maybe.

### How to reproduce
First attempt ever.  It downloaded mods and then...

![VSCrash01-27-2022](https://user-images.githubusercontent.com/33052308/151637268-8e6941f9-d144-4246-9447-b200be43a7ff.PNG)

### Expected behavior
I was hoping to join the Public VS Server and poke around.

### Screenshots
See above.

### Logs
```
client-crash.txt
-------------------------------
Game Version: v1.16.1 (Stable)
Loaded Mods: game@1.16.1, prospectorinfo@3.1.2, creative@1.16.1, redirectlogs@1.0.0, survival@1.16.1
1/28/2022 3:47:09 PM: Critical error occurred
System.InvalidCastException: Unable to cast object of type 'Vintagestory.API.Client.GuiElementRichtext' to type 'Vintagestory.API.Client.GuiElementDynamicText'.
   at _VfkAUIUQoAyIUELY5ebUPRA3t5P._0fDBrXXINkFltoPe1Y5E3YrafRu(Single )
   at Vintagestory.API.Client.GuiElementScrollbar.OnMouseWheel(ICoreClientAPI api, MouseWheelEventArgs args)
   at Vintagestory.API.Client.GuiComposer.OnMouseWheel(MouseWheelEventArgs mouse)
   at _tIGPm6FZhZZPikhMAd5JFvTPNWK._noQcSbBr1ZCv1hBT2E86Q7ia2Dt(MouseWheelEventArgs )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_WheelChanged(Object sender, MouseWheelEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnMouseWheel(Single dx, Single dy) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\NativeWindowBase.cs:line 306
   at OpenTK.Platform.Windows.WinGLNative.HandleMouseWheel(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 548
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 784
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at _WBb7CwUzEOAcHICLKAiVW6NVIeN._6uyy3n9Ds2iEHGU5xys7eJtJVNh(_Bv3M5I4kdGBjvWkB5zNcVsHESud , String[] )
   at _rip5UQmdVBLCq6ZoAXXnaN9jQJc._6uyy3n9Ds2iEHGU5xys7eJtJVNh(ThreadStart )
-------------------------------

client-main.txt had no information.  (I restarted the client accidentally and the log must have been over written.)
server-main.txt had no information.  (It had information from last sucessful single player game.)

Crash screen dump:  (temp files could not be found, sorry.)
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.1 (Stable)
Loaded Mods: game@1.16.1, prospectorinfo@3.1.2, creative@1.16.1, redirectlogs@1.0.0, survival@1.16.1
1/28/2022 3:47:09 PM: Critical error occurred
System.InvalidCastException: Unable to cast object of type 'Vintagestory.API.Client.GuiElementRichtext' to type 'Vintagestory.API.Client.GuiElementDynamicText'.
   at _VfkAUIUQoAyIUELY5ebUPRA3t5P._0fDBrXXINkFltoPe1Y5E3YrafRu(Single )
   at Vintagestory.API.Client.GuiElementScrollbar.OnMouseWheel(ICoreClientAPI api, MouseWheelEventArgs args)
   at Vintagestory.API.Client.GuiComposer.OnMouseWheel(MouseWheelEventArgs mouse)
   at _tIGPm6FZhZZPikhMAd5JFvTPNWK._noQcSbBr1ZCv1hBT2E86Q7ia2Dt(MouseWheelEventArgs )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_WheelChanged(Object sender, MouseWheelEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnMouseWheel(Single dx, Single dy) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\NativeWindowBase.cs:line 306
   at OpenTK.Platform.Windows.WinGLNative.HandleMouseWheel(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 548
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 784
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at _WBb7CwUzEOAcHICLKAiVW6NVIeN._6uyy3n9Ds2iEHGU5xys7eJtJVNh(_Bv3M5I4kdGBjvWkB5zNcVsHESud , String[] )
   at _rip5UQmdVBLCq6ZoAXXnaN9jQJc._6uyy3n9Ds2iEHGU5xys7eJtJVNh(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 1/19/2022 11:26:47 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1478716220082461302, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\bensl\AppData\Local\Temp\RDRB88A.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB8AA.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB8BB.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB8D8.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB908.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: d26fb191-12bc-4d0b-bafe-dbc7dc5e45dd
Report Status: 268435456
Hashed bucket: 1f92a0c50d25295c648574914d9f9a76
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/20/2021 1:22:45 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1999085723610005733, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\bensl\AppData\Local\Temp\RDR9AB9.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9ACA.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9ADA.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9B07.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9B28.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 2c82b89d-6307-46ec-ac51-6eafa9a816b1
Report Status: 268435456
Hashed bucket: ee3def5252484136fbbe2ddfbf5440e5
Cab Guid: 0 }
--------------
{ TimeGenerated = 4/3/2021 11:26:22 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1822032227626530173, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\bensl\AppData\Local\Temp\RDRBEC6.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBEF6.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBF07.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBF21.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBF51.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: f8e6728f-4b84-418c-90a5-26efa3022aa1
Report Status: 268435456
Hashed bucket: a995c73cc234971ef94928a850fe357d
Cab Guid: 0 }
```

**Comment by Nashtyfos** [comment]
It downloaded all the mods except for xskills@0.6.7

**Comment by Aledark789** [comment]
> Should disable all your mods including xskills when you go to official test server.
Whats redirectlogs mod?

**Comment by Ragolution** [comment]
For clarification, which server were you trying to connect to? 
VSPTS or another one? 
Interestingly, this appears to be a memory leak issue.

**Comment by Craluminum2413** [comment]
Closing due to inactivity
