### ISSUE TITLE
Crash on the official test server when walking on path. 

### ISSUE THREAD

**Issue by Marcafk** [anegostudios/VintageStory-Issues#1661]
1.16.1
windows
no mods loaded
MP TOPTS

```Running on 64 bit Windows with 24 GB RAM 
Game Version: v1.16.1 (Stable)
Loaded Mods: game@1.16.1, creative@1.16.1, survival@1.16.1
1/31/2022 9:44:41 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at XSkills.EntityAgentPatch.Postfix(EntityAgent __instance, Block ___insideBlock)
   at Vintagestory.API.Common.EntityAgent.GetWalkSpeedMultiplier_Patch1(EntityAgent this, Double groundDragFactor)
   at Vintagestory.API.Common.EntityPlayer.GetWalkSpeedMultiplier(Double groundDragFactor)
   at Vintagestory.API.Common.EntityPlayer.updateEyeHeight(Single dt)
   at Vintagestory.Client.NoObf.PlayerCamera.OnBeforeRenderFrame3D(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _vRo5OUTQG1GrM9nJI04WT53NTfD._up6Bx1j7zVizDBWAE3yF6nNCGNeA(Single )
   at _aMv7wPQlA8cgDnAEfSbEgoGdVfy._5b9xtkxs5cZMXJBpJdsFujTxqHg(Single )
   at _aMv7wPQlA8cgDnAEfSbEgoGdVfy._CZCOZeGO1GrDP5k5hCtFGOFJtVO(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _WBb7CwUzEOAcHICLKAiVW6NVIeN._6uyy3n9Ds2iEHGU5xys7eJtJVNh(_Bv3M5I4kdGBjvWkB5zNcVsHESud , String[] )
   at _rip5UQmdVBLCq6ZoAXXnaN9jQJc._6uyy3n9Ds2iEHGU5xys7eJtJVNh(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 1/30/2022 3:42:27 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1709886045862808946, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.1.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\User\AppData\Local\Temp\RDR2C8E.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2CCE.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2CEE.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2DC4.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2E13.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 82a4411f-7d93-4483-9d04-02c88361f1eb
Report Status: 268435456
Hashed bucket: b1952a3a00b9be9a07babc4ca20ccd72
Cab Guid: 0 }
--------------
{ TimeGenerated = 1/21/2022 3:47:57 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
   at System.Linq.Enumerable.ToDictionary[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Func`2<System.__Canon,System.__Canon>, System.Func`2<System.__Canon,System.__Canon>, System.Collections.Generic.IEqualityComparer`1<System.__Canon>)
   at Vintagestory.Common.ModLoader.CheckAndSortDependencies(System.Collections.Generic.IEnumerable`1<Vintagestory.Common.ModContainer>)
   at Vintagestory.Common.ModLoader.DisableAndVerify(System.Collections.Generic.List`1<Vintagestory.Common.ModContainer>, System.Collections.Generic.IEnumerable`1<System.String>)
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._stt3ckg04XAvVNS4fr54wm89CXe()
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._hndzNoMYcegNh6f26ARDQKxU9eE()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 1/19/2022 3:32:04 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
   at System.Linq.Enumerable.ToDictionary[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Func`2<System.__Canon,System.__Canon>, System.Func`2<System.__Canon,System.__Canon>, System.Collections.Generic.IEqualityComparer`1<System.__Canon>)
   at Vintagestory.Common.ModLoader.CheckAndSortDependencies(System.Collections.Generic.IEnumerable`1<Vintagestory.Common.ModContainer>)
   at Vintagestory.Common.ModLoader.DisableAndVerify(System.Collections.Generic.List`1<Vintagestory.Common.ModContainer>, System.Collections.Generic.IEnumerable`1<System.String>)
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._stt3ckg04XAvVNS4fr54wm89CXe()
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._hndzNoMYcegNh6f26ARDQKxU9eE()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }```

**Comment by Craluminum2413** [comment]
The problem is in XSkills mod

**Comment by Marcafk** [comment]
Thats well and good but the game shouldnt be even touching a mod that isnt loaded.

**Comment by Craluminum2413** [comment]
Crash log has XSkills

**Comment by copygirl** [comment]
Yeah if the so-called "stack trace" mentions the name of a mod, that mod is loaded.
`at XSkills.EntityAgentPatch.Postfix(EntityAgent __instance, Block ___insideBlock)`

Not sure why it's not in the list of loaded mods here. I will ask Tyron. Keeping the issue open due to that.

**Comment by tyronx** [comment]
Please also upload the client-main.txt

**Comment by copygirl** [comment]
It could be that you played singleplayer with XSkills which modifies the game code using Harmony, but does not properly undo the code patch when the mod is unloaded. This might be something to report to the mod author.

**Comment by Craluminum2413** [comment]
Closing due to inactivity
