### ISSUE TITLE
1.16.4-rc.1 : Game Crash on Burning Pit Kiln Chunk Load

### ISSUE THREAD

**Issue by metachaos** [anegostudios/VintageStory-Issues#1691]
**Game Version:** 1.16.4-rc.1  
**Platform:** Windows   
**Modded:** Yes 
**SP/MP:** Multiplayer

### Description
Crashed on loading chunks with pit kilns that were still burning.

I created several pit kilns with tier 1 refractory bricks (12 in each kiln). One pit kiln also had a chicken trapped in it. I started them all and then went far enough away to unload them. On coming back close enough for their chunk(s) to load, the game crashed. It was less than a day, so I assume they were still burning.

### How to reproduce
1. Make several pit kilns and start them burning. Maybe trap a chicken in one of them.
2. Run far away to unload chunk(s) with pit kilns.
3. Head toward pit kilns in order to load the chunk(s) again.
4. Game crashes.

### Expected behavior
Game to not crash. (Maybe to have a whole cooked chicken, but that's more of a wish.)

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/8045566/client-crash.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/8045567/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/8045569/server-main.txt)
```
Game Version: v1.16.4-rc.1 (Unstable)
Loaded Mods: game@1.16.4-rc.1, automap@0.1.8, prospectorinfo@3.1.2, stepup@1.2.0, creative@1.16.4-rc.1, survival@1.16.4-rc.1
2/10/2022 9:06:40 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityPitKiln.DetermineBuildStages()
   at Vintagestory.GameContent.BlockEntityPitKiln.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving)
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(_4c1CYHXEoXzFSMOjT85CwBq6ixd p, ClientMain game)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(_M2cHG9a7tYxrZ8I30mQSoFBARTK packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   [...]
```

**Comment by copygirl** [comment]
Edited the issue with what appears to be the crash. (This helps when others search for the error.)

**Comment by Craluminum2413** [comment]
Closing due to inactivity
