### ISSUE TITLE
Vines crash

### ISSUE THREAD

**Issue by Azuzuzuli** [anegostudios/VintageStory-Issues#1698]
**GamRunning on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.3 (Stable)
Loaded Mods: game@1.16.3, wildfarming@1.0.1, creative@1.16.3, survival@1.16.3
2/11/2022 7:09:31 PM: Critical error occurred
System.MissingMethodException: Method not found: 'Vintagestory.API.MathTools.BlockFacing Vintagestory.GameContent.BlockVines.GetOrientation()'.
   at WildFarming.BlockEnhancedVines.CanVineStay(IWorldAccessor world, BlockPos pos)
   at WildFarming.BlockEnhancedVines.OnNeighbourBlockChange(IWorldAccessor world, BlockPos pos, BlockPos neibpos)
   at Vintagestory.Client.NoObf.ClientMain.TriggerNeighbourBlocksUpdate(BlockPos pos)
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryDestroyBlock(BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _TcPKe0ld0EAbHR8YsMG1OLy9q8O._vg1QFi5yvtdWtcWdYGzwV9j9PVf(Single )
   at _SbWHHe8Ad6lBV8IRbvWFqut7ren._mSnyaJUIQhBb8A1j3UUn7uh5BBO(Single )
   at _SbWHHe8Ad6lBV8IRbvWFqut7ren._b365Cpnna1p8GSaDyyO3EH2VfOD(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _muFH2BhSjNKo8GSc2o33Nm6Ckup._SwLkq72vc0vcc3OnHXTAS19pm9p(_tVmXPdKJ3JBDWFc8tBtvgftcfhl , String[] )
   at _XL1Xa21FKJVFetNmIumId5p6UDU._SwLkq72vc0vcc3OnHXTAS19pm9p(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2/11/2022 3:59:16 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2017630819501840923, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.3.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\azuzu\AppData\Local\Temp\RDRD3A6.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD3B6.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD3D7.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD3F4.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD433.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: b41758c9-065a-4678-a634-1d05048eb0dd
Report Status: 268435456
Hashed bucket: 3f5d984b56cce389fc00108a5c499a1b
Cab Guid: 0 }
--------------
{ TimeGenerated = 8/31/2021 6:49:32 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1658733256924091269, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.5.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\azuzu\AppData\Local\Temp\RDR929D.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER92AD.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER92CE.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER92FA.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER932A.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: a46908e4-251f-48ef-8c59-7b2444590099
Report Status: 268435456
Hashed bucket: eb8d9853264150393705011bdc165385
Cab Guid: 0 }
--------------
{ TimeGenerated = 8/1/2021 3:12:55 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1865855461800047684, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.3.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\azuzu\AppData\Local\Temp\RDRA29F.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA2AF.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA2D0.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA2ED.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA31D.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 53d8f023-b2d9-4a63-b221-12a42136edbf
Report Status: 268435456
Hashed bucket: d8335772fa343c1ee9e4d9a822d07444
Cab Guid: 0 }e Version:** X.Y.Z  
**Platform:** Windows / Mac / Linux (which?)   
**Modded:** No / Yes (which?)  
**SP/MP:** Singleplayer / Multiplayer (which?)  

### Description
Explain the issue you're running into.

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by Craluminum2413** [comment]
The problem is in Wild Farming mod

**Comment by Azuzuzuli** [comment]
Thanks, I just finally noticed the mod. It was below the mods that are part of the game, so I had assumed it was part of the new update. I haven't played in a few months. :(

**Comment by copygirl** [comment]
The mod likely just need to be updated. It tries to access a method that has been changed or removed in the game.
