### ISSUE TITLE
Crash when accessing task manager on Windows

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#174]
Reported by **Demmon1** on Discord:

> Ok, game crashed after I ctrl+alt+del'ed into task manager. Just started a singleplayer world and paused the game beforehand.
> 
> Update: Tried to repeat what I did but no crash this time. Not sure what happened originally.

```
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at OpenTK.Platform.Windows.WinGLNative.HandleMouseMove(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _PkglWYgXxKoeSWDNiPQDOtOzd8A._WwcLROIGCSsEdcyWiCRVwgDfGLe(_uxEboymA8xOTitFU1L0Xt1f4edY , String[] )
   at _DLldCwzmWxAc7YkftgyEl6oNBYAA._WwcLROIGCSsEdcyWiCRVwgDfGLe(ThreadStart )
```

**Comment by tyronx** [comment]
What the... smells like 3rd party issue in OpenTK

**Comment by tyronx** [comment]
is this still an issue?

**Comment by Craluminum2413** [comment]
Close issue? This was fixed a long time ago and hasn't been repeated in latest versions
