### ISSUE TITLE
Ruin generator sometimes produces overlapping ruins, deleting block entities and thus causing exceptions on the client

### ISSUE THREAD

**Issue by tyronx** [anegostudios/VintageStory-Issues#177]
```
13:55:19 [Client Error] Exception thrown when initializing a block entity with classname GenericTypedContainer: System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityGenericTypedContainer.GenMesh() in C:\Users\tyron\Documents\vintagestory\game\VSSurvivalMod\BlockEntity\BEGenericTypedContainer.cs:line 226
   at Vintagestory.GameContent.BlockEntityGenericTypedContainer.Initialize(ICoreAPI api) in C:\Users\tyron\Documents\vintagestory\game\VSSurvivalMod\BlockEntity\BEGenericTypedContainer.cs:line 58
   at Vintagestory.Client.ClientSystemEntities.createBlockEntityFromPacket(Packet_BlockEntity packet, ClientMain game) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Entitites.cs:line 514

```

Requires a new engine feature to store ruin boundaries with the world and test for those during ruin generation. Alternatively, make sure blockentities are deleted during worldgen

**Comment by tyronx** [comment]
this is fixed in v1.9
