### ISSUE TITLE
Crashing when opening all of a sudden

### ISSUE THREAD

**Issue by pchard** [anegostudios/VintageStory-Issues#1774]
**Game Version:** 1.16.4
**Platform:** Windows
**Modded:** No   
**SP/MP:** Singleplayer / Multiplayer 

### Description
Game crashes when opening

### How to reproduce

It crashes

### Expected behavior
To open.

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Event viewer:

Faulting application name: Vintagestory.exe, version: 1.16.4.0, time stamp: 0x6219e03d
Faulting module name: openal32.DLL, version: 0.0.0.0, time stamp: 0x53ed5701
Exception code: 0xc0000005
Fault offset: 0x000000000001e217
Faulting process id: 0x29b4
Faulting application start time: 0x01d82e7bce41a036
Faulting application path: C:\Users\User\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\User\AppData\Roaming\Vintagestory\Lib64\openal32.DLL
Report Id: 2b06a2b9-1fc6-4465-b637-7158b5d78809
Faulting package full name: 
Faulting package-relative application ID:

And:

Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Audio.OpenAL.Alc.CloseDevice(IntPtr)
   at OpenTK.Audio.AudioContext.Dispose(Boolean)
   at OpenTK.Audio.AudioContext.Finalize()


Crash Report:

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.16.4 (Stable)
Loaded Mods: 
3/2/2022 10:22:38 PM: Critical error occurred
System.DllNotFoundException: Unable to load DLL 'openal32.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at OpenTK.Audio.OpenAL.AL.GetStringPrivate(ALGetString param)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.LogAndTestHardwareInfos()
   at _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK(_3HJA5NvAIx31LXjscc3HGjXaR6q , String[] )
   at _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/2/2022 10:23:51 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1624931480071118191, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.4.0
P3: 6219e03d
P4: openal32.DLL
P5: 0.0.0.0
P6: 53ed5701
P7: c0000005
P8: 000000000001e217
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6F12.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER709A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER70AB.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER70B8.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER70C9.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_4705f9ab6cc42e45dbfe010b1597a6e7daf03d_81245bb0_20cdd7da-20e9-4c2b-b965-4887d78a582a

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2b06a2b9-1fc6-4465-b637-7158b5d78809
Report Status: 268435456
Hashed bucket: c854503fdbd1bd16668cea9265fd1d6f
Cab Guid: 0 }
--------------
{ TimeGenerated = 3/2/2022 10:23:49 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.16.4.0, time stamp: 0x6219e03d
Faulting module name: openal32.DLL, version: 0.0.0.0, time stamp: 0x53ed5701
Exception code: 0xc0000005
Fault offset: 0x000000000001e217
Faulting process id: 0x29b4
Faulting application start time: 0x01d82e7bce41a036
Faulting application path: C:\Users\User\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\User\AppData\Roaming\Vintagestory\Lib64\openal32.DLL
Report Id: 2b06a2b9-1fc6-4465-b637-7158b5d78809
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 3/2/2022 10:23:49 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Audio.OpenAL.Alc.CloseDevice(IntPtr)
   at OpenTK.Audio.AudioContext.Dispose(Boolean)
   at OpenTK.Audio.AudioContext.Finalize()

 }
```

**Comment by l1ving** [comment]
You don't have the 32bit version of OpenAL installed anymore, try getting it from here? https://www.openal.org/downloads/

**Comment by copygirl** [comment]
Windows should come with OpenAL. Do you have any idea why it could be missing from your system?
This is not an issue with the game, so I will close this.
