### ISSUE TITLE
Charcoal block placement crashed game, world now crashes on load

### ISSUE THREAD

**Issue by Lochingbird** [anegostudios/VintageStory-Issues#1776]
**Game Version:** X.Y.Z  
**Platform:** Windows 10
**Modded:** no added mods
**SP/MP:** Singleplayer survival/creative

### Description
I went into creative mode on my single player world (as i've done many times for building/exploring) and was building up a smithing area. I was putting down charcoal stacks when my game crashed, and now that world crashes when I tried to load it.

*edit* Running in repair mode allows me to enter the world, but immediately provides the screenshotted pop up "Host not responding. Possible causes: Server overloaded or crashed" which does not crash the game in repair mode, but still crashes if I try to load normally.

### How to reproduce
Untested: Begin a survival world, use command to enter creative mode, then stack charcoal? I can't reenter that world currently and don't want to brick another.

### Screenshots

![2022-03-03_11-19-56](https://user-images.githubusercontent.com/100861921/156607673-be26c3c6-a78a-4641-b254-fe90da5bcf07.png)

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.4 (Stable)
Loaded Mods: game@1.16.4, creative@1.16.4, survival@1.16.4
3/3/2022 8:26:23 AM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockCoalPile.GetSelectionBoxes(IBlockAccessor blockAccessor, BlockPos pos)
   at Vintagestory.Client.NoObf.ClientMain.GetBlockIntersectionBoxes(BlockPos pos)
   at Vintagestory.API.MathTools.AABBIntersectionTest.RayIntersectsBlockSelectionBox(BlockPos pos, BlockFilter filter)
   at Vintagestory.API.MathTools.AABBIntersectionTest.GetSelectedBlock(Single maxDistance, BlockFilter filter)
   at Vintagestory.Common.GameMain.RayTraceForSelection(IWorldIntersectionSupplier supplier, Ray ray, BlockSelection& blockSelection, EntitySelection& entitySelection, BlockFilter bfilter, EntityFilter efilter)
   at Vintagestory.Common.GameMain.RayTraceForSelection(IPlayer player, BlockSelection& blockSelection, EntitySelection& entitySelection, BlockFilter bfilter, EntityFilter efilter)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.UpdateCurrentSelection()
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.UpdatePicking(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _4Bi1AGVssrIO0El8b8ygdS9FIfm._LvzIyYpsQCoC78JubjSO0HCjtTg(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._JvY4M2412YZu1OS3Ull8wgZBu1j(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._KmBeEx15nyyLrVqNDW6geSArpNr(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK(_3HJA5NvAIx31LXjscc3HGjXaR6q , String[] )
   at _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2/17/2022 12:37:09 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2017630819501840923, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.3.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\GMLOCH~1\AppData\Local\Temp\RDRA191.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA1A1.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA1B2.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA1EE.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA20F.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 7d1aec7c-882f-4520-9688-139df54459e1
Report Status: 268435456
Hashed bucket: 3f5d984b56cce389fc00108a5c499a1b
Cab Guid: 0 }
```

**Comment by copygirl** [comment]
Just in case the issue is not immediately obvious to the developers when looking at the affected code, could you upload your world somewhere (for example [WeTransfer](https://wetransfer.com/)) so the team can quickly reproduce and fix the issue?

**Comment by Lochingbird** [comment]
I've started the world/save data upload and I'll provide it when it's done

**Comment by Lochingbird** [comment]
Here is the link to the world/save file https://we.tl/t-qYqZCN2lfq

**Comment by Lochingbird** [comment]
I got an idea, since I could move around in repair mode, I moved myself out of the chunk I was crashing in then loaded back in normally. Game didn't crash, and I was able to move myself back. Looking at the charcoal stacks crashed the game again, but just standing near them didn't. Moved myself away in repair mode, loaded back, then I used the world edit tools to erase the blocks without looking directly at them, and it seems like the world is playable again. Placing charcoal in survival and creative so far has not reproduced the bug, but it might be specific to placing charcoal when it's actively being affected by gravity?

**Comment by copygirl** [comment]
You're essentially crashing because the code that generates the selection box (faint black outline around the block you look at) for the charcoal pile is doing something naughty. I think you're right in that it has to do with falling charcoal piles.

**Comment by copygirl** [comment]
@Zelfior provided a world download in #1885.
Also confirmed to still occur in 1.16.5

**Comment by Zelfior** [comment]
Now that i read his description, it also was in a survival world from which in entered creative mode through console, and not in a creative world as i said in my post

**Comment by radfast** [comment]
I can't reproduce the issue in 1.18, but it looks like we never fixed it, and it has been twice reported, so may be something I am missing.   Anyhow, the code is now updated in 1.18.2 so that any repeat of this type of issue should be resolved.
