### ISSUE TITLE
basic cube issues

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#178]
```
Running on 64 bit Windows with 16GB RAM 
8/8/2018 6:00:18 AM: Critical error occurred
System.ArgumentException: 'block/basic/cube.json' is not a valid asset location!
   at Vintagestory.API.Common.AssetLocation.Validate()
   at _tJUe9rmTq39XUByzXgmXALzrJ2e.TryGet(String Path)
   at Vintagestory.GameContent.BlockGenericTypedContainer.GenMesh(ICoreClientAPI capi, String type, String shapename)
   at Vintagestory.GameContent.BlockGenericTypedContainer.GenGuiMeshes(ICoreClientAPI capi)
   at Vintagestory.GameContent.BlockGenericTypedContainer.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   at _LGLCh0eNYQldEQTKWUt43z4EuxI._0Nju5FmalMmFung4jrZ2E9waLwh(_aLbBODgWWfHyBvXUSZVqZxcrwii , ItemStack , EnumItemRenderTarget )
   at _LGLCh0eNYQldEQTKWUt43z4EuxI._nsQY4eHPTAIwFKXDbp4hDldP4Z2(ItemStack , Double , Double , Double , Single , Int32 , Boolean , Boolean , Boolean )
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.RenderInteractiveElements(Single deltaTime)
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime)
   at Vintagestory.API.Client.GuiDialog.OnRender2D(Single deltaTime)
   at _hONAOK9TE8BCfx6eHCtWUzOZCMZ._Xdq0xxufTFCm861bHw7jnN3dtmY(Single )
   at _4LcPxGGcEVYMPqciNFgiiayhT4v._j4CLIwlWvDfEBBVg3Z8z4EF1dzk(EnumRenderStage , Single )
   at _aLbBODgWWfHyBvXUSZVqZxcrwii._NfchtQTHZMsKaUWFBDyUDtlthcl(Single )
   at _c9r7y7mkVz2jyxe7lBAOCduecvP._NfchtQTHZMsKaUWFBDyUDtlthcl(Single )
   at _k62zWU6Ao7iw97XG8fXg7QyQOAJ._KTVMbt9Hj9WGcr1zdJHHoYcJelu(Single )
   at _k62zWU6Ao7iw97XG8fXg7QyQOAJ._50Pmv8tXkk0gKcv0epSds2d21mg(Single )
   at _AR6VEGddtQTdz8MajxDahjZ0O7PA._H62PZMTterQdlXUlDCwBkeC4KJm(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _aIorzg135olA91fb1yMDeCYmNVu._mzhdH02mA94rjdDTOXZTelMHNnt(_XWBucJDkhzJZPloDkH2EuBmPy5d , String[] )
   at _ankaJ9EhOuHfHVD4ZoiUyif84gE._mzhdH02mA94rjdDTOXZTelMHNnt(ThreadStart )
-------------------------------
```

[storagecrates.zip](https://github.com/anegostudios/VintageStory-Issues/files/2270314/storagecrates.zip)

**Comment by copygirl** [comment]
I reproduced the problem in my dev environment and found an issue with the exception message, it should be `'shapes/game:block/basic/cube.json' is not a valid asset location!`. Investigating further...

**Comment by copygirl** [comment]
Created a merge request to fix this issue - should be in the next version!
