### ISSUE TITLE
Crash after teleporting

### ISSUE THREAD

**Issue by Wishydane** [anegostudios/VintageStory-Issues#1819]
**Game Version:** v1.16.4 (Stable) 
**Platform:** Windows
**Modded:** Yes
**SP/MP:** Multiplayer 

### Description
This has nothing to do with the mods I have. This issue happened in Vanilla Vintage Story but I didn't report it until now.

### How to reproduce
1. Travel some distance from my home base
2. Teleport back to my home base. 
3. I take a couple of steps away from the teleport point.
4. Game Crashes

### Expected behavior
I expected not to crash. 

### Screenshots
n/a

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.4 (Stable)
Loaded Mods: animalcages@2.0.6, dragonflies@1.2.0, game@1.16.4, creative@1.16.4, survival@1.16.4
3/21/2022 5:25:25 PM: Critical error occurred
System.IO.IOException: The file or directory is corrupted and unreadable.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Vintagestory.Common.PathOrigin.TryLoadAsset(IAsset asset)
   at Vintagestory.Common.AssetManager.TryGet(AssetLocation Location, Boolean loadAsset)
   at Vintagestory.GameContent.BlockBarrel.GenMesh(ItemStack contentStack, ItemStack liquidContentStack, Boolean issealed, BlockPos forBlockPos)
   at Vintagestory.GameContent.BlockEntityBarrel.GenMesh()
   at Vintagestory.GameContent.BlockEntityBarrel.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving)
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(_RnAkbdxlwtrQq8SBPd9hyLO5yYc p, ClientMain game)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(_zqyp7oNseOe29EJgSPWAkirfxhw packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _4Bi1AGVssrIO0El8b8ygdS9FIfm._o5h005s1ovnxSPPqKWgI4tZUoCh(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._JvY4M2412YZu1OS3Ull8wgZBu1j(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._KmBeEx15nyyLrVqNDW6geSArpNr(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK(_3HJA5NvAIx31LXjscc3HGjXaR6q , String[] )
   at _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/21/2022 5:25:26 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.16.4.0, time stamp: 0x6219e03d
Faulting module name: KERNELBASE.dll, version: 10.0.22000.527, time stamp: 0x71a5cb5d
Exception code: 0xc0020001
Fault offset: 0x000000000004478c
Faulting process id: 0x17c
Faulting application start time: 0x01d83d63f7accdd3
Faulting application path: D:\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 0f691b25-b16f-4545-805f-7ef52853d60f
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 3/21/2022 5:25:25 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFB9EED478C
Stack:
 }
--------------
{ TimeGenerated = 3/21/2022 2:42:10 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1937563273474348038, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.4.0
P3: 6219e03d
P4: KERNELBASE.dll
P5: 10.0.22000.527
P6: 71a5cb5d
P7: c0020001
P8: 000000000004478c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4cae9154-4ccf-481a-b640-b31abcd84b31.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e428d9b6-5f1a-4310-b9ad-b53548e85901.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d973d13b-b3af-4b11-a4bb-eb85c22bdd6c.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4b342ca4-cae3-411e-9fb7-cdedf085315c.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d264ef65-38e4-489b-ac6a-e514aa426219.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_fcdf8a4145d8f5559e5764312da17e8e46b01785_81245bb0_f653e6d2-8c82-4ffa-946e-27e80987c916

Analysis symbol: 
Rechecking for solution: 0
Report Id: fe328b08-1533-44b4-adff-fa4a92729f9c
Report Status: 268566528
Hashed bucket: ae70895fe1b18f686ae39b8815481406
Cab Guid: 0 }
```

**Comment by copygirl** [comment]
Potentially related: #634

Looks like it breaks when attempting to load something related to barrel models, in the game files. Have you tried reinstalling the game yet? Might be worth a try. Also check my comment on the linked issue.

**Comment by Wishydane** [comment]
that makes sense because every time my husband (who is the only other player to play multiplayer with me) closes a barrel my game will ALWAYS crash. Always. Without fail. So it's gotten to the point where he gets ready to seal up some barrels, I have to log off the server, and then he can do his barrel thing and I can come back and play.

**Comment by copygirl** [comment]
I will close this issue as I don't think there's anything we can do within the game to fix the problem.
If you find out anything to the contrary, or if my recommended solution works, please let us know.
