### ISSUE TITLE
Out of range exception with map open after player fell below bedrock

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#182]
The issue also seemed to occur when a player enabled the map after the effected players were already kicked from the game.

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.ChunkMapLayer.GenerateChunkImage(Vec2i chunkPos, IMapChunk mc)
   at Vintagestory.GameContent.ChunkMapLayer.OnOffThreadTick()
   at Vintagestory.GameContent.WorldMapManager.<OnLoaded>b__19_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by tyronx** [comment]
Fixed for 1.6.9
