### ISSUE TITLE
BlockEntityBed.DidMount NRE

### ISSUE THREAD

**Issue by mixxit** [anegostudios/VintageStory-Issues#1822]
**Game Version:** 1.16.4
**Platform:** Windows
**Modded:** Loaded Mods: game@1.16.4, vsroleplayclasses@1.16.4-rc.27, vsroleplayraces@1.16.4-rc.3, nobells@1.0.0, nodrifters@1.0.0, creative@1.16.4, survival@1.16.4
**SP/MP:** Multiplayer

### Description
```22/03/2022 12:48:32: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityBed.DidMount(EntityAgent entityAgent)
   at Vintagestory.API.Datastructures.SyncedTreeAttribute.FromBytes(BinaryReader stream)
   at Vintagestory.API.Common.Entities.Entity.FromBytes(BinaryReader reader, Boolean fromServer)
   at Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.API.Common.EntityPlayer.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.Client.NoObf.ClientSystemEntities.createOrUpdateEntityFromPacket(_yBL8zoBecliFkS2tQXGQIuD4v3j entitypacket, ClientMain game, Boolean addToLoadQueue)
   at Vintagestory.Client.NoObf.ClientChunk.LoadEntitiesFromPacket(_yBL8zoBecliFkS2tQXGQIuD4v3j[] entities, Int32 entitiesCount, ClientMain game)
   at Vintagestory.Client.NoObf.ClientWorldMap.loadChunkMT(_rRUf25tOqmvtcmyjeOruY6FKLsb p, ClientChunk chunk)
   at Vintagestory.Client.NoObf.ClientWorldMap.<>c__DisplayClass102_0.<LoadChunkFromPacket>b__0()
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _4Bi1AGVssrIO0El8b8ygdS9FIfm._o5h005s1ovnxSPPqKWgI4tZUoCh(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._JvY4M2412YZu1OS3Ull8wgZBu1j(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._KmBeEx15nyyLrVqNDW6geSArpNr(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK(_3HJA5NvAIx31LXjscc3HGjXaR6q , String[] )
   at _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK(ThreadStart )
-------------------------------
```

### How to reproduce
1. Make a bed
2. Use it on floor
3. Go to sleep and exit game

### Expected behavior
Not crash when logging back in 

### Screenshots
![image](https://user-images.githubusercontent.com/233287/159486144-8ca8422c-44a6-4a1d-a8b8-ca87231e4edd.png)

**Comment by mixxit** [comment]
https://github.com/anegostudios/vssurvivalmod/blob/d4e6f37001dd1a8a9f1f8f9bae72102c4ef7f572/BlockEntity/BEBed.cs#L181

Not sure if this is cause entityAgent is null

Or 

https://github.com/anegostudios/vssurvivalmod/blob/d4e6f37001dd1a8a9f1f8f9bae72102c4ef7f572/BlockEntity/BEBed.cs#L189

one of these is null

everything else looks to be checked?

**Comment by 5HT2** [comment]
`Api.World.Calendar.TotalHours` is probably set and used elsewhere when logging in, it would make more sense for `entityAgent` to be null here.

**Comment by mixxit** [comment]
![image](https://user-images.githubusercontent.com/233287/159806788-baf2bd44-9f07-4ba4-bd43-c8cc8cf74ae9.png)

**Comment by 5HT2** [comment]
huh. Now that's not what I expected to be null.

**Comment by mixxit** [comment]
same! added a patch for now https://github.com/mixxit/vsfixes/blob/0ac357d858389639bd7d9aeb791293122b84b233/mods/vsfixes/src/Systems/Bedfix.cs#L67

**Comment by copygirl** [comment]
Could this be because the method is called before block entities have been properly initialized? Could also look into the order of calls / initialization when a world is loaded. Just patching this specific issue could mean overlooking the root cause.

@mixxit By the way, the extra `?` after `__instance` is not required, as `__instance` is already accessed a number of times before.

**Comment by carlitoss98** [comment]
-Is there a way to "fix it" so it stops crashing and I can keep playing? 
-Are there any extra details I could give so it gets easier to fix?

**Comment by 5HT2** [comment]
> - Is there a way to "fix it" so it stops crashing and I can keep playing?

Using the patch the @mixxit created would work around it temporarily. Having an admin break the bed might also fix it.

> - Are there any extra details I could give so it gets easier to fix?

The problem and solution is already solved here, so not in this case.

**Comment by tyronx** [comment]
Yea, this is caused by the load order of chunks, more specifically these 2 lines in loadChunkMT
```
chunk.LoadEntitiesFromPacket(p.Entities, p.EntitiesCount, game);
chunk.InitBlockEntitiesFromPacket(game);
```

Entities are intialized before block entities are. It would make sense to me to flip these 2 lines, which should fix the crash, while (hopefully) not cause other issues. 

Thanks the report and everyones debugging efforts!
