### ISSUE TITLE
Don't know how to instantiate item of class 'ItemLiquidPortion' did you forget to register a mapping?

### ISSUE THREAD

**Issue by mixxit** [anegostudios/VintageStory-Issues#1824]
**Game Version:** 1.16.4
**Platform:** Linux Server, Windows Client
**Modded:** Loaded Mods: game@1.16.4, vsroleplayclasses@1.16.4-rc.27, vsroleplayraces@1.16.4-rc.3, nobells@1.0.0, nodrifters@1.0.0, creative@1.16.4, survival@1.15.10
**SP/MP:** Multiplayer 

### Description
```23/03/2022 20:23:55: Critical error occurred
System.Exception: Don't know how to instantiate item of class 'ItemLiquidPortion' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass)
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(_V5KVIg6AZCt8Xw4s8zyEyfYSGfh packet, IWorldAccessor world, ClassRegistry registry)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssetsStep1()
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _eaiE9OWXDVmX2r6n7JaWPscBEkO._LvzIyYpsQCoC78JubjSO0HCjtTg(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._JvY4M2412YZu1OS3Ull8wgZBu1j(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._KmBeEx15nyyLrVqNDW6geSArpNr(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK(_3HJA5NvAIx31LXjscc3HGjXaR6q , String[] )
   at _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK(ThreadStart )
```

### How to reproduce
Im just logging in

### Expected behavior
Let me login without crashing

### Screenshots
![image](https://user-images.githubusercontent.com/233287/159789806-9eab71d1-3b4f-430f-8e6e-06f447776215.png)

### Logs
```
23.3.2022 20:48:21 [Notification] Client logger started.
23.3.2022 20:48:21 [Notification] Game Version: v1.16.4 (Stable)
23.3.2022 20:48:21 [Notification] Screens:
23.3.2022 20:48:21 [Notification] 0: {X=0,Y=0,Width=1920,Height=1080}, \\.\DISPLAY1 (primary)
23.3.2022 20:48:21 [Notification] 1: {X=1920,Y=0,Width=1920,Height=1080}, \\.\DISPLAY2 
23.3.2022 20:48:22 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
23.3.2022 20:48:22 [Notification] Graphics Card Vendor: ATI Technologies Inc.
23.3.2022 20:48:22 [Notification] Graphics Card Version: 3.3.14761 Core Profile Context 21.30.23.04 30.0.13023.4001
23.3.2022 20:48:22 [Notification] Graphics Card Renderer: Radeon (TM) RX 480 Graphics
23.3.2022 20:48:22 [Notification] Graphics Card ShadingLanguageVersion: 4.60
23.3.2022 20:48:22 [Notification] Cairo Graphics Version: 1.17.3
23.3.2022 20:48:22 [Notification] OpenAL Version: 1.1 ALSOFT 1.16.0
23.3.2022 20:48:22 [Notification] C# Framework: .net Framework 4.0.30319.42000
23.3.2022 20:48:22 [Notification] OpenTK Version: 3.3.2 (A set of fast, low-level C# bindings for OpenGL, OpenGL ES and OpenAL.)
23.3.2022 20:48:22 [Notification] Start discovering assets
23.3.2022 20:48:22 [Notification] Found 18 base assets in category lang
23.3.2022 20:48:22 [Notification] Found 0 base assets in category patches
23.3.2022 20:48:22 [Notification] Found 22 base assets in category config
23.3.2022 20:48:22 [Notification] Found 0 base assets in category worldproperties
23.3.2022 20:48:22 [Notification] Found 50 base assets in category sounds
23.3.2022 20:48:22 [Notification] Found 96 base assets in category shapes
23.3.2022 20:48:22 [Notification] Found 74 base assets in category shaders
23.3.2022 20:48:22 [Notification] Found 16 base assets in category shaderincludes
23.3.2022 20:48:22 [Notification] Found 128 base assets in category textures
23.3.2022 20:48:22 [Notification] Found 4 base assets in category music
23.3.2022 20:48:22 [Notification] Found 0 base assets in category dialog
23.3.2022 20:48:22 [Notification] Found 408 base assets in total
23.3.2022 20:48:22 [Notification] Loading sounds
23.3.2022 20:48:22 [Notification] (Re-)loaded frame buffers
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass . 
23.3.2022 20:48:22 [Notification] CPU Cores: 12
23.3.2022 20:48:22 [Notification] Window was resized to 1920 1080, rebuilding framebuffers...
23.3.2022 20:48:22 [Notification] (Re-)loaded frame buffers
23.3.2022 20:48:22 [Notification] Waiting for async sound loading...
23.3.2022 20:48:22 [Notification] Sounds loaded
23.3.2022 20:48:22 [Notification] Begin loading shaders
23.3.2022 20:48:22 [Notification] Load shaders now
23.3.2022 20:48:22 [Notification] Loading shaders...
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass standard. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass particlescube. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass particlesquad. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass sky. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass nightsky. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass woittest. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass transparentcompose. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass helditem. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass chunkopaque. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass chunkliquid. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass decals. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass final. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass gui. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass blur. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass chunktransparent. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass findbright. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass chunktopsoil. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass godrays. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass autocamera. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass blockhighlights. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass wireframe. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass entityanimated. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass luma. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass blit. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass particlesquad2d. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass texture2texture. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass celestialobject. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass guitopsoil. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass entityanimatedtransparent. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass colorgrade. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass guigear. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass ssao. 
23.3.2022 20:48:22 [Notification] Loaded Shaderprogramm for render pass bilateralblur. 
23.3.2022 20:48:22 [Notification] Cached session key is valid, validating with server
23.3.2022 20:48:23 [Notification] Server validation response: Good
23.3.2022 20:48:23 [Notification] Will search the following paths for mods:
23.3.2022 20:48:23 [Notification]     C:\Users\mike\AppData\Roaming\Vintagestory\Mods
23.3.2022 20:48:23 [Notification]     C:\Users\mike\AppData\Roaming\VintagestoryData\Mods
23.3.2022 20:48:29 [Notification] Initialized GUI Manager
23.3.2022 20:48:29 [Notification] Initialized Server Connection
23.3.2022 20:48:29 [Notification] Server args parsed
23.3.2022 20:48:29 [Notification] GuiScreenConnectingToServer constructed
23.3.2022 20:48:29 [Notification] Server main instantiated
23.3.2022 20:48:30 [Fatal] System.Exception: This save game requires world generator standard but no such generator was found! I cannot continue like this, sorry :(
If you really need the contents of the save game, build a tiny mod that registers such world generator that just generates air blocks
   at Vintagestory.Server.ServerSystemSupplyChunks.LoadWorldgenHandlerAndSpawnChunks()
   at Vintagestory.Server.ServerMain.EnterRunPhase(EnumServerRunPhase runPhase)
   at Vintagestory.Server.ServerMain.Launch()
   at _TRhArnJABwZoV9Vt7Ld2l65Xzgg._55FJfeMcDB5NT6lsb5fDE3bzUPI()
23.3.2022 20:49:03 [Notification] Destroying game session, waiting up to 200ms for client threads to exit
23.3.2022 20:49:03 [Notification] Found 18 base assets in category lang
23.3.2022 20:49:03 [Notification] Found 0 base assets in category patches
23.3.2022 20:49:03 [Notification] Found 22 base assets in category config
23.3.2022 20:49:03 [Notification] Found 0 base assets in category worldproperties
23.3.2022 20:49:03 [Notification] Found 50 base assets in category sounds
23.3.2022 20:49:03 [Notification] Found 96 base assets in category shapes
23.3.2022 20:49:03 [Notification] Found 74 base assets in category shaders
23.3.2022 20:49:03 [Notification] Found 16 base assets in category shaderincludes
23.3.2022 20:49:03 [Notification] Found 128 base assets in category textures
23.3.2022 20:49:03 [Notification] Found 4 base assets in category music
23.3.2022 20:49:03 [Notification] Found 0 base assets in category dialog
23.3.2022 20:49:03 [Notification] Found 0 base assets in category compatibility
23.3.2022 20:49:03 [Notification] GuiScreenConnectingToServer constructed
23.3.2022 20:49:05 [Notification] Connecting to 142.132.193.226...
23.3.2022 20:49:05 [Error] Unable to read srv record, will connect to supplied hostname. Error: Non-Existent Domain
;; ->>HEADER<<- opcode: Query, status: Non-Existent Domain, id: 42475
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
23.3.2022 20:49:05 [Notification] Initialized GUI Manager
23.3.2022 20:49:05 [Notification] Initialized Server Connection
23.3.2022 20:49:05 [Notification] GuiScreenConnectingToServer constructed
23.3.2022 20:49:05 [Notification] Connected to server, downloading data...
0 kilobyte received
23.3.2022 20:49:06 [Notification] Loading and pre-starting client side mods...
23.3.2022 20:49:06 [Notification] Will search the following paths for mods:
23.3.2022 20:49:06 [Notification]     C:\Users\mike\AppData\Roaming\Vintagestory\Mods
23.3.2022 20:49:06 [Notification]     C:\Users\mike\AppData\Roaming\VintagestoryData\Mods
23.3.2022 20:49:06 [Notification]     C:\Users\mike\AppData\Roaming\VintagestoryData\ModsByServer\142.132.193.226
23.3.2022 20:49:06 [Notification] Found 8 mods (1 disabled)
23.3.2022 20:49:06 [Notification] Mods, sorted by dependency: game, vsroleplayclasses, vsroleplayraces, nobells, nodrifters, creative, survival
23.3.2022 20:49:07 [Error] [survival] Exception thrown when attempting to retrieve all types of the assembly VSSurvivalMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Vintagestory.Common.ModContainer.GetModSystems(Assembly assembly), InnerException: . Will ignore asssembly. Loader exceptions:
23.3.2022 20:49:07 [Error] [survival] System.TypeLoadException: Method 'GrowTree' in type 'Vintagestory.ServerMods.TreeGen' from assembly 'VSSurvivalMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
23.3.2022 20:49:07 [Error] [survival] System.TypeLoadException: Method 'GrowTree' in type 'Vintagestory.GameContent.BlockFernTree' from assembly 'VSSurvivalMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
23.3.2022 20:49:07 [Error] [survival] System.TypeLoadException: Method 'get_MountSupplier' in type 'Vintagestory.GameContent.BlockEntityBed' from assembly 'VSSurvivalMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
23.3.2022 20:49:07 [Error] [survival] System.TypeLoadException: Method 'GrowTree' in type 'Vintagestory.GameContent.BlockBamboo' from assembly 'VSSurvivalMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
23.3.2022 20:49:07 [Error] [survival] System.MissingMethodException: Method not found: 'Boolean Vintagestory.API.Common.IWorldChunk.BreakDecorPart(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.MathTools.BlockPos, Vintagestory.API.MathTools.BlockFacing, Int32)'.
23.3.2022 20:49:07 [Warning] [survival] Is a Code mod, but no ModSystems found
23.3.2022 20:49:07 [Notification] Instantiated 41 mod systems from 7 enabled mods
23.3.2022 20:49:07 [Notification] Done loading and pre-starting client side mods.
23.3.2022 20:49:07 [Notification] External Origins in load order: modorigin@C:\Users\mike\AppData\Roaming\Vintagestory\assets\creative\, mod@vsroleplayclasses_v1.16.4-rc.28.zip, mod@No Bells - VS 1.16.0.zip, mod@No Drifters - VS 1.16.0.zip
23.3.2022 20:49:07 [Notification] Found 2 external assets in category lang
23.3.2022 20:49:07 [Notification] Found 11 external assets in category patches
23.3.2022 20:49:07 [Notification] Found 2 external assets in category config
23.3.2022 20:49:07 [Notification] Found 0 external assets in category worldproperties
23.3.2022 20:49:07 [Notification] Found 12 external assets in category sounds
23.3.2022 20:49:07 [Notification] Found 7 external assets in category shapes
23.3.2022 20:49:07 [Notification] Found 0 external assets in category shaders
23.3.2022 20:49:07 [Notification] Found 0 external assets in category shaderincludes
23.3.2022 20:49:07 [Notification] Found 348 external assets in category textures
23.3.2022 20:49:07 [Notification] Found 4 external assets in category music
23.3.2022 20:49:07 [Notification] Found 16 external assets in category dialog
23.3.2022 20:49:07 [Notification] Found 0 external assets in category compatibility
23.3.2022 20:49:07 [Notification] Reloaded lang file now with mod assets
23.3.2022 20:49:07 [Notification] JsonPatch Loader: 18 patches total, missing files on 3 patches, no errors
23.3.2022 20:49:07 [Warning] Shader : Is not defining a shader version via #version
23.3.2022 20:49:07 [Warning] Shader : Is not defining a shader version via #version
23.3.2022 20:49:07 [Error] Link error in shader program for pass aurora: Vertex shader(s) failed to link, fragment shader(s) failed to link.
Vertex link error: INVALID_OPERATION.
ERROR: error(#97) No program main found
fragment link error: INVALID_OPERATION.
ERROR: error(#97) No program main found
23.3.2022 20:49:07 [Notification] Started 31 systems on Client:
23.3.2022 20:49:07 [Notification]     Mod 'VSEssentials.dll' (game):
23.3.2022 20:49:07 [Notification]         Vintagestory.ServerMods.Core
23.3.2022 20:49:07 [Notification]         Vintagestory.GameContent.EntityPartitioning
23.3.2022 20:49:07 [Notification]         Vintagestory.GameContent.ErrorReporter
23.3.2022 20:49:07 [Notification]         Vintagestory.ServerMods.ModCompatiblityUtil
23.3.2022 20:49:07 [Notification]         Vintagestory.ServerMods.NoObf.ModJsonPatchLoader
23.3.2022 20:49:07 [Notification]         Vintagestory.GameContent.FallingBlockParticlesModSystem
23.3.2022 20:49:07 [Notification]         Vintagestory.GameContent.CharacterExtraDialogs
23.3.2022 20:49:07 [Notification]         Vintagestory.GameContent.EntityNameTagRendererRegistry
23.3.2022 20:49:07 [Notification]         Vintagestory.GameContent.POIRegistry
23.3.2022 20:49:07 [Notification]         Vintagestory.GameContent.RoomRegistry
23.3.2022 20:49:07 [Notification]         Vintagestory.GameContent.WeatherSystemCommands
23.3.2022 20:49:07 [Notification]         Vintagestory.GameContent.WeatherSystemClient
23.3.2022 20:49:07 [Notification]         Vintagestory.GameContent.WorldMapManager
23.3.2022 20:49:07 [Notification]         Vintagestory.ServerMods.LoadColorMaps
23.3.2022 20:49:07 [Notification]         Vintagestory.GameContent.ClothManager
23.3.2022 20:49:07 [Notification]     Mod 'VSCreativeMod.dll' (creative):
23.3.2022 20:49:07 [Notification]         Vintagestory.ServerMods.Core
23.3.2022 20:49:07 [Notification]         Vintagestory.ServerMods.WorldEdit.WorldEdit
23.3.2022 20:49:07 [Notification]     Mod 'vsroleplayclasses_v1.16.4-rc.28.zip' (vsroleplayclasses):
23.3.2022 20:49:07 [Notification]         vsroleplayclasses.src.VSRoleplayClassesMod
23.3.2022 20:49:07 [Notification]         vsroleplayclasses.src.Systems.SystemSpellCrafting
23.3.2022 20:49:07 [Notification]         vsroleplayclasses.src.Systems.SystemWho
23.3.2022 20:49:07 [Notification]         vsroleplayclasses.src.Systems.SystemSkills
23.3.2022 20:49:07 [Notification]         vsroleplayclasses.src.Systems.SystemActiveEffects
23.3.2022 20:49:07 [Notification]         vsroleplayclasses.src.Systems.SystemMana
23.3.2022 20:49:07 [Notification]         vsroleplayclasses.src.Systems.SystemStatistics
23.3.2022 20:49:07 [Notification]         vsroleplayclasses.src.Systems.SystemAbilities
23.3.2022 20:49:07 [Notification]         vsroleplayclasses.src.Systems.SystemExperience
23.3.2022 20:49:07 [Notification]         vsroleplayclasses.src.Systems.EntityAgentOnDamageReplacerMod
23.3.2022 20:49:07 [Notification]         vsroleplayclasses.src.Systems.SystemCompassInventory
23.3.2022 20:49:07 [Notification]         vsroleplayclasses.src.Systems.SystemCharacterMemorisationInventory
23.3.2022 20:49:07 [Notification]     Mod 'vsroleplayraces_v1.16.4-rc.3.zip' (vsroleplayraces):
23.3.2022 20:49:07 [Notification]         vsroleplayraces.src.CharacterSystemCharSelectReplacerMod
23.3.2022 20:49:07 [Notification]         vsroleplayraces.src.VSRoleplayRacesMod
23.3.2022 20:49:07 [Notification] Loading shaders...
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass standard. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass particlescube. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass particlesquad. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass sky. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass nightsky. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass woittest. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass transparentcompose. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass helditem. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass chunkopaque. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass chunkliquid. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass decals. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass final. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass gui. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass blur. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass chunktransparent. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass findbright. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass chunktopsoil. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass godrays. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass autocamera. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass blockhighlights. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass wireframe. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass entityanimated. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass luma. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass blit. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass particlesquad2d. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass texture2texture. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass celestialobject. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass guitopsoil. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass entityanimatedtransparent. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass colorgrade. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass guigear. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass ssao. 
23.3.2022 20:49:07 [Notification] Loaded Shaderprogramm for render pass bilateralblur. 
23.3.2022 20:49:07 [Warning] Shader : Is not defining a shader version via #version
23.3.2022 20:49:07 [Warning] Shader : Is not defining a shader version via #version
23.3.2022 20:49:07 [Error] Link error in shader program for pass aurora: Vertex shader(s) failed to link, fragment shader(s) failed to link.
Vertex link error: INVALID_OPERATION.
ERROR: error(#97) No program main found
fragment link error: INVALID_OPERATION.
ERROR: error(#97) No program main found
23.3.2022 20:49:07 [Notification] Reloaded shaders now with mod assets
23.3.2022 20:49:07 [Notification] Processed server identification
23.3.2022 20:49:07 [Notification] Map initialized
23.3.2022 20:49:07 [Notification] Reloaded sounds (async), now with mod assets
23.3.2022 20:49:07 [Notification] Connected to server, downloading data...
92 kilobyte received
23.3.2022 20:49:07 [Warning] Improperly configured mod. Server sends me channel name survivalCoreConfig, but no client side mod registered it.
23.3.2022 20:49:07 [Warning] Improperly configured mod. Server sends me channel name latitudedata, but no client side mod registered it.
23.3.2022 20:49:07 [Warning] Improperly configured mod. Server sends me channel name upgradeTasks, but no client side mod registered it.
23.3.2022 20:49:07 [Warning] Improperly configured mod. Server sends me channel name auctionHouse, but no client side mod registered it.
23.3.2022 20:49:07 [Warning] Improperly configured mod. Server sends me channel name charselection, but no client side mod registered it.
23.3.2022 20:49:07 [Warning] Improperly configured mod. Server sends me channel name rifts, but no client side mod registered it.
23.3.2022 20:49:07 [Warning] Improperly configured mod. Server sends me channel name riftWeather, but no client side mod registered it.
23.3.2022 20:49:07 [Warning] Improperly configured mod. Server sends me channel name temporalstability, but no client side mod registered it.
23.3.2022 20:49:07 [Warning] Improperly configured mod. Server sends me channel name blockreinforcement, but no client side mod registered it.
23.3.2022 20:49:07 [Warning] Improperly configured mod. Server sends me channel name gameeffects, but no client side mod registered it.
23.3.2022 20:49:07 [Warning] Improperly configured mod. Server sends me channel name journal, but no client side mod registered it.
23.3.2022 20:49:07 [Warning] Improperly configured mod. Server sends me channel name lootrandomizer, but no client side mod registered it.
23.3.2022 20:49:07 [Warning] Improperly configured mod. Server sends me channel name sleeping, but no client side mod registered it.
23.3.2022 20:49:07 [Warning] Improperly configured mod. Server sends me channel name tpManager, but no client side mod registered it.
23.3.2022 20:49:07 [Warning] Improperly configured mod. Server sends me channel name vsmechnetwork, but no client side mod registered it.
23.3.2022 20:49:07 [Notification] Received level init
23.3.2022 20:49:07 [Notification] Connected to server, downloading data...
236 kilobyte received
23.3.2022 20:49:07 [Notification] Connected to server, downloading data...
412 kilobyte received
23.3.2022 20:49:08 [Notification] Connected to server, downloading data...
540 kilobyte received
23.3.2022 20:49:08 [Notification] Connected to server, downloading data...
527 kilobyte received
23.3.2022 20:49:08 [Notification] Received server assets
23.3.2022 20:49:08 [Fatal] Game Version: v1.16.4 (Stable)
Loaded Mods: game@1.16.4, vsroleplayclasses@1.16.4-rc.28, vsroleplayraces@1.16.4-rc.3, nobells@1.0.0, nodrifters@1.0.0, creative@1.16.4, survival@1.15.10
23/03/2022 20:49:08: Critical error occurred
System.Exception: Don't know how to instantiate item of class 'ItemLiquidPortion' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass)
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(_V5KVIg6AZCt8Xw4s8zyEyfYSGfh packet, IWorldAccessor world, ClassRegistry registry)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssetsStep1()
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _eaiE9OWXDVmX2r6n7JaWPscBEkO._LvzIyYpsQCoC78JubjSO0HCjtTg(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._JvY4M2412YZu1OS3Ull8wgZBu1j(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._KmBeEx15nyyLrVqNDW6geSArpNr(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK(_3HJA5NvAIx31LXjscc3HGjXaR6q , String[] )
   at _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK(ThreadStart )
-------------------------------
Crash written to file at "C:\Users\mike\AppData\Roaming\VintagestoryData\Logs\client-crash.txt"

23.3.2022 20:49:08 [Notification] Exiting game now. Server running=False. Exit reason: Game crashed

```

**Comment by mixxit** [comment]
Reinstalling the game fixed it but i dont know why this would happen

**Comment by copygirl** [comment]
From looking at the log files, the VSSurvival mod was disabled (or broken) when you attempted to play.

There is a tiny chance that an anti-virus thought the file was offensive and deleted it.
But it also could also have any number of other causes.
