### ISSUE TITLE
(Modded) Crash on trying to draw on a crate's label

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1837]
**Game Version:** 1.16.5-rc.1
**Platform:** Windows
**Modded:** Yes  
**SP/MP:** Singleplayer

### How to reproduce
1. Use this mod 
[BiggerCrates-v1.0.0.zip](https://github.com/anegostudios/VintageStory-Issues/files/8408775/BiggerCrates-v1.0.0.zip)
3. Place a crate with label (from the mod)
4. Put any item inside
5. Try to draw on it using charcoal etc.
6. It crashed

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.5-rc.1 (Unstable)
Loaded Mods: game@1.16.5-rc.1, bigcrate@1.0.0, creative@1.16.5-rc.1, survival@1.16.5-rc.1
04/04/2022 13:12:04: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockCrate.get_AtlasSize()
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(Int32 indexForLogging, MeshData meshdata, ShapeElement element, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(Shape shapeBase, MeshData& modeldata, Vec3f wholeMeshRotation, Vec3f wholeMeshOffset, Single wholeMeshScale, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(String typeForLogging, Shape shapeBase, MeshData& modeldata, ITexPositionSource texSource, Vec3f wholeMeshRotation, Int32 generalGlowLevel, Byte climateColorMapId, Byte seasonColorMapId, Nullable`1 quantityElements, String[] selectiveElements)
   at Vintagestory.GameContent.BlockCrate.GenLabelMesh(ICoreClientAPI capi, String label, TextureAtlasPosition texPos, Boolean editableVariant, Vec3f rotation)
   at Vintagestory.GameContent.BlockEntityCrate.GenLabelMeshWithItemStack(Int32 textureSubId)
   at Vintagestory.GameContent.BlockEntityCrate.<>c__DisplayClass42_0.<genLabelMesh>b__0(Int32 texSubid)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemStackToAtlas(ItemStack stack, ITextureAtlasAPI atlas, Int32 size, Action`1 onComplete, Int32 color, Single sepiaLevel, Single scale)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _o9akP4VIsdbyLDvrrQ5yRuFW0kf._KZvgpn2RkMFbKaA2m1tAYrJFxYx(Single )
   at _nAidxnGe1HRzSfUOv4SH07I37vf._TnM5TSdghGddEZQuPFQ5q1SaaVy(Single )
   at _nAidxnGe1HRzSfUOv4SH07I37vf._9fUzz7LJZg9L6MxVIrYbozYhi9m(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _TMlc0SVi1veOk3WmBa9fJGYHBkJ._nKpQGPZPKMHALS5qaTLoxqhCR9O(_KkN6emy6owjnJ1fsZJmPr1AZx0f , String[] )
   at _iv6cwviezE8MtOIBckvWYzXitAC._nKpQGPZPKMHALS5qaTLoxqhCR9O(ThreadStart )
```

**Comment by Craluminum2413** [comment]
What's weird is when I was able to get this to work (still using only JSON), it got corrupted rotation for North and corrupted textures for North and West
![image](https://user-images.githubusercontent.com/69315569/161524212-1dc490c6-d947-409d-b9ad-d4f24d9b333a.png)

**Comment by tyronx** [comment]
odd. should no longer crash next release
