### ISSUE TITLE
I just Opened up my Vintage Story Singleplayer World and it crashes before it opens up

### ISSUE THREAD

**Issue by Pokeofproz** [anegostudios/VintageStory-Issues#1841]
```
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.16.4 (Stable)
Loaded Mods: weaponpacka@1.2.4, ancienttools@1.4.0, tonwexp@1.0.9, backpackpackplus@1.0.3, weaponpackbeta@1.0.0, betterarchery@3.0.0, betterdrifters@2.1.3, betterpoultice@1.0.0, cavecontent@1.0.1, cralutweaks@1.0.1, dragonflies@1.2.0, extrachests@1.5.2, foundrymod@1.0.0, fulldrop@1.0.0, weaponpackg@1.0.0, hideandfabric@1.1.0, moreclasses@1.2.4, moreroads@1.4.3, MoreStoneDrops@1.0.0, orepulverizer@1.1.1, preservationmod@1.0.0, primitivesurvival@2.8.0, quickerbarrel@1.1.0, spidersilk@1.2.2, spyglass@0.4.5, stackables@2.0.5, locustmod@2.3.5, usefulscrap@2.0.2, viescraftmachines@1.17.0, game@1.16.4, alchemy@1.6.3, carrycapacity@0.6.5, fromgoldencombs@1.3.11, lichen@1.6.1, medievalexpansion@3.7.1, playercorpse@1.3.1, stonequarry@1.6.5, tpnet@1.5.1, temporalmirror@1.6.0, temporalprospector@1.0.0, usefulstuff@2.3.2, creative@1.16.4, survival@1.16.4, wildfarming@1.2.8, campaigncartographer@2.2.1, bricklayers@0.9.0, ensisswordpack@1.0.0
4/6/2022 9:47:54 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Config.GamePaths.ReplaceInvalidChars(String filename)
   at _XQuI7L5BE6dAsLDHzu050LJypSs._uaO693atCSm36WKadzeuNHFKcAi()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _juEYJh7silYnjjiyZdSa883OJLM._KvJNcV8GrsgzamN9IXT0EqLOYtL(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK(_3HJA5NvAIx31LXjscc3HGjXaR6q , String[] )
   at _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/17/2022 6:41:46 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2014295197708983878, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.4.0
P3: 10.0.22000.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Poke\AppData\Local\Temp\RDR9C4A.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.498315ef-128c-4abb-b2cc-bf5a68b3705f.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6aad08ad-1371-490e-b73f-24b99c9b5f16.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.aa0cc551-bda5-46f1-b348-4800458e3735.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.93dec055-15cc-42f4-ae8b-c0e4ac381b67.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 55fd83de-49ef-4254-975b-d950631906ba
Report Status: 268435456
Hashed bucket: 428485356ff57c418bf436cf64381e46
Cab Guid: 0 }
--------------
{ TimeGenerated = 2/15/2022 5:38:28 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2139890591295858499, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.3.0
P3: 10.0.22000.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Poke\AppData\Local\Temp\RDR484F.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d9541bf7-4f24-4eee-837d-8476e4b19e27.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.85c3a443-7e1c-45aa-91aa-c35b526fd9a9.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.96e5c06e-3f75-410e-8527-977257d27f66.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.17462844-2c21-41bd-a297-6b63be5c9cea.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 2403ef4e-d8cf-4016-8fd3-7ffd56b15747
Report Status: 268435456
Hashed bucket: 1c52b57ea5e52c300db26b27b863e743
Cab Guid: 0 }
--------------
{ TimeGenerated = 1/15/2022 8:38:44 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1954671979241337967, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 10.0.22000.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Poke\AppData\Local\Temp\RDRA6A3.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0d54fd5d-b9dc-40cf-9cae-aaf7e749c5f8.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.1145cf5d-67c4-436b-98f5-178ee738732e.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8cc720de-8ea8-4e75-b14e-6b3605032ab1.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.fdc844b2-577e-4132-8c92-4d16434e0416.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 8608e2f3-a3cd-406e-b199-80183b3c864a
Report Status: 268435456
Hashed bucket: 48a6bebc62a6e26bcb2063cf0f16f46f
Cab Guid: 0 }
```

**Comment by copygirl** [comment]
Could you upload your `client-main.txt`?

**Comment by Pokeofproz** [comment]
> Could you upload your `client-main.txt`?

i found out the issue already it was the campaigncartographer@2.2.1 mod, i just deleted it and replaced it with campaigncartographer@2.2.0

**Comment by copygirl** [comment]
Related issue by the author: #1843

**Comment by ApacheTech** [comment]
> 

Hi, version 2.2.2 is now out that resolves this issue (by reverting the changes from 2.2.1).

Apologies for the issues that my mod caused you.
