### ISSUE TITLE
Having `RequiredOnClient` as true, and `RequiredOnServer` as false on a Universal mod causes Fatal client crash.

### ISSUE THREAD

**Issue by ApacheTech** [anegostudios/VintageStory-Issues#1843]
**Game Version:** 1.16.4
**Platform:** N/A
**Modded:** Yes
**SP/MP:** Both

### User Story

```
As a mod author,
Given I am making a Universal mod that can be used Client-Side only,
When `RequiredOnClient` is set to true,
Then the mod should be downloaded to the client, via auto-downloads.
```

### Details

Using Campaign Cartographer as a working example. This mod is a Universal Mod that has both `RequiredOnServer` and `RequiredOnClient` set to `false`. This is so that while it can be used as a Client-Side only mod, if it is installed on a server, then extra functionality is available.

The drawback to this is that the mod is not downloaded to the client, via the auto-download system, when the mod is added to a server.

In v.2.2.1, I tried to remedy this by setting `RequiredOnClient` to `true`. However, this caused all clients to crash, including when playing on Single-Player, as it could not find the file to download. Even in a single-player world, the game tried to download the mod, when it was already in the Mods folder.

The change was reverted in v2.2.2.

https://github.com/ApacheTechSolutions/ApacheTech.VintageMods.CampaignCartographer

### Logs
```
Running on 64 bit Windows with 128 GB RAM 
Game Version: v1.16.4 (Stable)
Loaded Mods: game@1.16.4, creative@1.16.4, survival@1.16.4, campaigncartographer@2.2.1
08/04/2022 17:01:22: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Config.GamePaths.ReplaceInvalidChars(String filename)
   at _XQuI7L5BE6dAsLDHzu050LJypSs._uaO693atCSm36WKadzeuNHFKcAi()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _juEYJh7silYnjjiyZdSa883OJLM._KvJNcV8GrsgzamN9IXT0EqLOYtL(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK(_3HJA5NvAIx31LXjscc3HGjXaR6q , String[] )
   at _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK(ThreadStart )
-------------------------------
```

Debugging this error leads to the line, 

```csharp
var installPath = Path.Combine(GamePaths.DataPathServerMods, GamePaths.ReplaceInvalidChars(_IB8b5zDAPUcuuIsCF7ZHJlnRfhb._TsArNBsFJ27ApD3e9Mj4KcNR3JC));
```
Within the `_uaO693atCSm36WKadzeuNHFKcAi` method in the `_XQuI7L5BE6dAsLDHzu050LJypSs` class; where `_IB8b5zDAPUcuuIsCF7ZHJlnRfhb._TsArNBsFJ27ApD3e9Mj4KcNR3JC` evaluates to `null`.

**Comment by ApacheTech** [comment]
Yes, it crashes the game before even logging into the world. It's as it tries to download the mod.

**Comment by Craluminum2413** [comment]
Fixed no idea when
