### ISSUE TITLE
Opening Existing Single-Player Game crashes

### ISSUE THREAD

**Issue by northofnow** [anegostudios/VintageStory-Issues#1845]
**Game Version:** 1.16.5-rc
**Platform:** Windows 
**Modded:** No
**SP/MP:** Singleplayer 

### Description
Every time I try to open up my singleplayer game with 199 hours on it, the game crashes right at the moment of loading. The background on the opening screen also changed to the rainbow church from a few game versions ago? IDK if that is related.

### How to reproduce
1. Open game
2. Wait
3. Crash

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.5-rc.1 (Unstable)
Loaded Mods: game@1.16.5-rc.1, creative@1.16.5-rc.1, survival@1.16.5-rc.1
4/8/2022 8:49:21 PM: Critical error occurred
System.Exception: EndOfStreamException thrown while reading entity, you might be able to recover your savegame through repair mode ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.MemoryStream.InternalReadInt32()
   at Vintagestory.API.Common.EntityControls.FromBytes(BinaryReader reader, Boolean ignoreData)
   at Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   --- End of inner exception stack trace ---
   at Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.API.Common.EntityPlayer.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.Client.NoObf.ClientSystemEntities.createOrUpdateEntityFromPacket(_sPXDIGJ2B2ZoDRisCyuh75Nx8Qw entitypacket, ClientMain game, Boolean addToLoadQueue)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityLoadedPacket(_8R4QhXL39MNDFRPX4qfWzA66mkk serverpacket)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _o9akP4VIsdbyLDvrrQ5yRuFW0kf._2dpBBqlpuf9EIYFNx69ARY96FDv(Single )
   at _nAidxnGe1HRzSfUOv4SH07I37vf._TnM5TSdghGddEZQuPFQ5q1SaaVy(Single )
   at _nAidxnGe1HRzSfUOv4SH07I37vf._9fUzz7LJZg9L6MxVIrYbozYhi9m(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _TMlc0SVi1veOk3WmBa9fJGYHBkJ._nKpQGPZPKMHALS5qaTLoxqhCR9O(_KkN6emy6owjnJ1fsZJmPr1AZx0f , String[] )
   at _iv6cwviezE8MtOIBckvWYzXitAC._nKpQGPZPKMHALS5qaTLoxqhCR9O(ThreadStart )
-------------------------------
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.MemoryStream.InternalReadInt32()
   at Vintagestory.API.Common.EntityControls.FromBytes(BinaryReader reader, Boolean ignoreData)
   at Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/30/2022 4:53:23 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1715359538913174117, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.4.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\marsr\AppData\Local\Temp\RDRC29A.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC29B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC2AC.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC2D2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC302.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 0daf4d7e-489e-42f2-bae4-2be7cb40c971
Report Status: 268435456
Hashed bucket: 2de2e32f95852db547ce2e698aff6265
Cab Guid: 0 }
--------------
{ TimeGenerated = 2/26/2022 7:59:56 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1715359538913174117, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.4.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\marsr\AppData\Local\Temp\RDRE998.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE9B9.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE9C9.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREA06.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREA64.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 0e1a602c-4f86-451a-9b47-e4ddd525540a
Report Status: 268435456
Hashed bucket: 2de2e32f95852db547ce2e698aff6265
Cab Guid: 0 }
--------------
{ TimeGenerated = 1/24/2022 6:46:01 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1478716220082461302, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\marsr\AppData\Local\Temp\RDR9A32.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9A43.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9A53.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9A70.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9A91.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: a8c686a2-c338-4d02-857c-c250081e3c4f
Report Status: 268435456
Hashed bucket: 1f92a0c50d25295c648574914d9f9a76
Cab Guid: 0 }

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by copygirl** [comment]
The background switches out every couple of days. That is normal.

Have you tried opening the world in repair mode yet?

**Comment by copygirl** [comment]
Closing due to inactivity.
