### ISSUE TITLE
Syntax causing handbook crashing

### ISSUE THREAD

**Issue by l33tmaan** [anegostudios/VintageStory-Issues#1858]
**Game Version:** 1.16.4 
**Platform:** Windows
**Modded:** Yes (Expanded Foods)  
**SP/MP:** Singleplayer 

### Description

Baking is a relatively new feature and I think I've found an issue with the "bakingProperties" function. 
It appears that having an "initialCode" of more than one item makes the handbook freak out and crash when you try and pull up certain items.
For example, this causes a crash:
```
			"*-partbaked": {
				temp: 160,
				levelFrom: 0.25,
				levelTo: 0.5,
				startScaleY: 1.05,
				endScaleY: 1.10,
				resultCode: "expandedfoods:breadedball-{type}-cooked",
				initialCode: "expandedfoods:breadedball-{type}-{raw|oiled}",
			},
```
While this does not:
```
			"*-cooked": {
				temp: 160,
				levelFrom: 0.5,
				levelTo: 0.75,
				startScaleY: 1.10,
				endScaleY: 1.10,
				resultCode: "expandedfoods:breadedball-{type}-charred",
				initialCode: "expandedfoods:breadedball-{type}-partbaked",
			},
```
This is probably an oversight, but it would be nice if it could be addressed at some point. Raw breaded food and oiled breaded food both cook fine, this only affects the part-baked foods in the handbook when you try and look them up - so it's halfway there!

### How to reproduce
1. You can either download Expanded Foods, then search for "part-baked" in the handbook and try and look at any of the fried items...
2. Or you can add this syntax to the 'initialCode' of bread: {variant1|variant2}

### Expected behavior
Handbook shouldn't crash; maybe says something like "Baked from: Variant 1 & Variant 2". I'm fine as long as it doesn't crash anymore.

### Logs
```
System.Exception: Can't create itemstack without item!
   at Vintagestory.API.Common.ItemStack..ctor(Item item, Int32 stacksize)
   at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.GetHandbookInfo_Patch0(CollectibleBehaviorHandbookTextAndExtraInfo this, ItemSlot inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.GameContent.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.GameContent.GuiDialogHandbook.initDetailGui_Patch1(GuiDialogHandbook this)
   at Vintagestory.GameContent.GuiElementFlatList.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
```

**Comment by Craluminum2413** [comment]
Could you try to use `@expandedfoods:breadedball-{type}-(raw|oiled)`?

**Comment by l33tmaan** [comment]
Nice try, but that doesn't seem to change anything.

**Comment by Craluminum2413** [comment]
I guess {variant1|variant2} are not supported at all

**Comment by Craluminum2413** [comment]
I close it because {type1|type2} is not a thing
