### ISSUE TITLE
Click dragging into empty backpack slots crashes VS

### ISSUE THREAD

**Issue by Llama3013** [anegostudios/VintageStory-Issues#1867]
**Game Version:** 1.16.5
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Game crashes when click dragging into empty backpack slot while there is already one backpack already equipped. **Does not crash on creative mode.**

### How to reproduce
1. Make two hand basket
2. Equip one hand basket
3. Click drag the second hand basket into any other two empty backpack slots
4. Game crashes

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.5 (Stable)
Loaded Mods: game@1.16.5, survival@1.16.5
18/04/2022 1:05:07 PM: Critical error occurred
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._vvUTh6X5xLRNnjtX2xSE7z8yMeh(_SUsdg1ytavxaRcNNkhfDrODGhGP , String[] )
   at _yA4PJazdKq1OMm8H6js6v5AhQB._vvUTh6X5xLRNnjtX2xSE7z8yMeh(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 17/04/2022 6:20:34 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2032600941693231522, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 625674b5
P4: 7434
P5: 67246080
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER700E.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\Critical_Vintagestory.exe_6963c255cf2a83259bcf80c53e0702917213db1_1f70e3ae_feef26d3-465e-4d5f-a7b9-49db0789acba

Analysis symbol: 
Rechecking for solution: 0
Report Id: 314f0c1e-695c-4a24-ad47-0527d0ee0b59
Report Status: 268435456
Hashed bucket: 38df08c21c1fe118ec353fc98bbfe1a2
Cab Guid: 0 }
--------------
{ TimeGenerated = 17/04/2022 6:20:33 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.16.5.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 2348

Start Time: 01d8523296faa9e0

Termination Time: 4294967295

Application Path: F:\Games\Vintagestory\Vintagestory.exe

Report Id: 314f0c1e-695c-4a24-ad47-0527d0ee0b59

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Top level window is idle
 }
--------------
{ TimeGenerated = 17/04/2022 6:20:33 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 625674b5
P4: 7434
P5: 67246080
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\Critical_Vintagestory.exe_6963c255cf2a83259bcf80c53e0702917213db1_1f70e3ae_feef26d3-465e-4d5f-a7b9-49db0789acba

Analysis symbol: 
Rechecking for solution: 0
Report Id: 314f0c1e-695c-4a24-ad47-0527d0ee0b59
Report Status: 4
Hashed bucket: 
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
