### ISSUE TITLE
Crash when choosing 4 raw crucibles in clay crafting.

### ISSUE THREAD

**Issue by Kaperios** [anegostudios/VintageStory-Issues#188]
Vintage Story version: 1.6.11
Is it modded: Yes
Crashlog:
```
Running on 64 bit Windows with 8GB RAM 
09/09/2018 20:36:48: Critical error occurred
System.Exception: The dialogue GuiDialogBlockEntityRecipeSelector was not added yet. Missing call to api.Gui.RegisterDialog()
   at _TBIlhH3vSzCBx0zPjllT4NVqTrC._fHkRLHEA0nG9UiMcFwqX9RpDILO(GuiDialog )
   at _TBIlhH3vSzCBx0zPjllT4NVqTrC._KUSgKibzt2fJIlaiw49LxUb94wF(MouseEvent )
   at _DiufGW68SvMbVaAsZfQM0Hxy5Jo._KUSgKibzt2fJIlaiw49LxUb94wF(MouseEvent )
   at _wBzvKPrX9UL1M27bH52vbRfijjk._rgaeByCeRSbGuuSTORdYCd77c4hA(Object , MouseButtonEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _LkuRhaQi2csuYkiSJ7OawRUtl5B._SwgdyeohaAdZwoTSgjLzyRUaEXC(_qxKBIIYHRbIS2ztIWz44Pw8ydcP , String[] )
   at _HL8HdS33SaPAV3PFtWs6H3ikCVW._SwgdyeohaAdZwoTSgjLzyRUaEXC(ThreadStart )
```

**Comment by tyronx** [comment]
In Singleplayer? And what mods?

**Comment by Kaperios** [comment]
multiplayer, darkagecraft modpack

**Comment by tyronx** [comment]
Most likely fixed, please reopen if not.
