### ISSUE TITLE
Game crashing every time i try to open a save

### ISSUE THREAD

**Issue by ninepppppp** [anegostudios/VintageStory-Issues#1881]
**Game Version:** 1.16.5 
**Platform:** Windows
**Modded:** No
**SP/MP:** first crashed while playing multiplayer, now crashes when trying to open at all in single player

### Description
Was playing over internet with a friend on my world when it just kind of crashed randomly. We had been playing for a couple hours and were upset when we saw it didn't save but when I tried to open the save the next day (today) it kept crashing once it got through the loading screen each time (i tried multiple times), idk what's happening

### How to reproduce
load vintage story, attempt to open world, wait for it to load, game crashes.

### Expected behavior
the game to load

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.5 (Stable)
Loaded Mods: game@1.16.5, creative@1.16.5, survival@1.16.5
4/26/2022 4:30:52 PM: Critical error occurred
System.Exception: EndOfStreamException thrown while reading entity, you might be able to recover your savegame through repair mode ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.MemoryStream.InternalReadInt32()
   at Vintagestory.API.Common.EntityControls.FromBytes(BinaryReader reader, Boolean ignoreData)
   at Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   --- End of inner exception stack trace ---
   at Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.API.Common.EntityPlayer.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.Client.NoObf.ClientSystemEntities.createOrUpdateEntityFromPacket(_c4zW6iXC6q7Xom9edSwgw3G8Alm entitypacket, ClientMain game, Boolean addToLoadQueue)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityLoadedPacket(_m4CVIcO3UJPLI62MuOxE8163nQH serverpacket)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _vuG4DGUoqAIliPHbC5Jd2S4bgWAA._DPQfPEsBXX5ftH8l1sqqtyB2Itl(Single )
   at _8UC8FAMhwKY89IbtSRDjsNSApPJ._KbwUAfxjCHyIG0aK445AAA9FHl5(Single )
   at _8UC8FAMhwKY89IbtSRDjsNSApPJ._R0wAt2N0TpONMxGD0HJG3bDrRcI(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._vvUTh6X5xLRNnjtX2xSE7z8yMeh(_SUsdg1ytavxaRcNNkhfDrODGhGP , String[] )
   at _yA4PJazdKq1OMm8H6js6v5AhQB._vvUTh6X5xLRNnjtX2xSE7z8yMeh(ThreadStart )
-------------------------------
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.MemoryStream.InternalReadInt32()
   at Vintagestory.API.Common.EntityControls.FromBytes(BinaryReader reader, Boolean ignoreData)
   at Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 4/10/2022 2:31:09 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1456929448466166237, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.4.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\aliza\AppData\Local\Temp\RDREBA.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF38.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1014.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER10FC.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1216.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: ce6cf5e8-3205-4d68-a06a-b24086b05898
Report Status: 268435456
Hashed bucket: 1ba30f5b996e5abc24380d9d3ea1b1dd
Cab Guid: 0 }```

**Comment by copygirl** [comment]
This is an ongoing issue (see #1163) though you might be able to resolve it by opening the world in repair mode.

**Comment by copygirl** [comment]
No update in some time, closing issue.
