### ISSUE TITLE
Game crash when waypointing

### ISSUE THREAD

**Issue by Iplay2L8** [anegostudios/VintageStory-Issues#1889]
**Game Version:** 1.15.5
**Platform:** Windows / Mac / Linux (which?)   
**Modded:** No  
**SP/MP:** Singleplayer   

### Description
game crashes when trying to make a waypoint 

### How to reproduce
1. updated to current version using update download
2. deselected mods in mod folder
3. started new singleplayer world
4. open map and right click to make waypoint.
5. It crashes 
6. Deleted mod folder contents containing older verion mods
7. ran update again
8. still crashes.  Game plays well otherwise

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.5 (Stable)
Loaded Mods: game@1.16.5, sharemywaypoints@1.0.0, creative@1.16.5, survival@1.16.5
5/6/2022 10:25:22 AM: Critical error occurred
System.TypeLoadException: Could not load type 'Vintagestory.API.Common.Action`1' from assembly 'VintagestoryAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at NeverLost.ShareMyWayPoints.PatchWaypointAdd.GuiPatch.AddShareButton(GuiComposer composer, ElementBounds bounds)
   at Vintagestory.GameContent.GuiDialogAddWayPoint.ComposeDialog_Patch0(GuiDialogAddWayPoint this)
   at Vintagestory.GameContent.GuiDialogWorldMap.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 816
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._vvUTh6X5xLRNnjtX2xSE7z8yMeh(_SUsdg1ytavxaRcNNkhfDrODGhGP , String[] )
   at _yA4PJazdKq1OMm8H6js6v5AhQB._vvUTh6X5xLRNnjtX2xSE7z8yMeh(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/6/2022 10:25:27 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1751710256771471147, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 625674b5
P4: KERNELBASE.dll
P5: 10.0.19041.1645
P6: 630193b4
P7: c0020001
P8: 0000000000034f69
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE15F.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERECBA.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERECCB.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERECD9.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERECE9.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_fbcee4937a49bb958aa62e485c4132b41ff4180_1f70e3ae_fac4177e-6c07-4d67-8d70-8d45401f6527

Analysis symbol: 
Rechecking for solution: 0
Report Id: e3dcb00a-c9e5-49e2-960c-67b7a2e632dd
Report Status: 268435456
Hashed bucket: fe5ec7b7078725eaf84f53329445972b
Cab Guid: 0 }
--------------
{ TimeGenerated = 5/6/2022 10:25:23 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.16.5.0, time stamp: 0x625674b5
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1645, time stamp: 0x630193b4
Exception code: 0xc0020001
Fault offset: 0x0000000000034f69
Faulting process id: 0x3138
Faulting application start time: 0x01d861368978697f
Faulting application path: C:\Users\iplay\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: e3dcb00a-c9e5-49e2-960c-67b7a2e632dd
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 5/6/2022 10:25:23 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFF30F54F69
Stack:
 }
```

**Comment by copygirl** [comment]
Indeed. Not sure what you did wrong, but the waypoint mod is still loaded, as can be seen in the crash report:
```
Loaded Mods: game@1.16.5, sharemywaypoints@1.0.0, creative@1.16.5, survival@1.16.5
   at NeverLost.ShareMyWayPoints.PatchWaypointAdd.GuiPatch.AddShareButton(GuiComposer composer, ElementBounds bounds)
```
Make sure to check both mods folders. The one that opens when you click "Open Mods Folder" in the mod manager, as well as the mods folder in the install directory - which is intended to be for official mods provided by the game, but will nonetheless load custom mods as well.

Report to the mod author if you wish them to look into the issue.
