### ISSUE TITLE
Critical Error 'fogdrygrass'??

### ISSUE THREAD

**Issue by Juliustice** [anegostudios/VintageStory-Issues#1898]
Game Crash When trying to connect right after downloading.

```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.5 (Stable)
Loaded Mods: acorns@0.5.1, tonwexp@1.0.9, backpackpack@1.0.3, cavepaintings@1.3.1, cellardoor@1.2.1, compass@1.2.0, dragonflies@1.2.0, expandedfoods@1.5.3-pre.10, HangingOilLamps@1.0.1, moreclasses@1.2.4, potatoes@1.0.8, moremetals@1.0.9, moreroads@1.4.3, MoreTorchHolders@1.0.0, nightwatcher@1.2.0, oxygennotincluded@0.2.4, speararrowheadbits@1.1.0, specializedbags-18Slot@0.4.2, spyglass@0.4.5, viescraftmachines@1.17.1, game@1.16.5, alchemy@1.6.3, carrycapacity@0.6.5, fancyplanters@1.0.5, lichen@1.6.1, petai@1.4.4, playercorpse@1.3.1, usefulstuff@2.3.2, creative@1.16.5, survival@1.16.5, xlib@0.6.8, xrowboat@0.0.3, metalrecovery@0.1.17, bricklayers@0.9.1, cats@1.4.2, feverstonehorses@1.2.7, packanimals@1.0.1, wildcraft@1.2.3, wolftaming@1.4.1, xskillspatched@0.6.9-dev.8, xskills@0.6.8, blammfix@0.0.1
5/16/2022 10:27:26 PM: Critical error occurred
System.Exception: Don't know how to instantiate item of class 'fogdrygrass' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass)
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(_QPqp7qxo7PD3uWV1E8Ca41IBkSS packet, IWorldAccessor world, ClassRegistry registry)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssetsStep1()
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _vuG4DGUoqAIliPHbC5Jd2S4bgWAA._DPQfPEsBXX5ftH8l1sqqtyB2Itl(Single )
   at _8UC8FAMhwKY89IbtSRDjsNSApPJ._KbwUAfxjCHyIG0aK445AAA9FHl5(Single )
   at _8UC8FAMhwKY89IbtSRDjsNSApPJ._R0wAt2N0TpONMxGD0HJG3bDrRcI(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._vvUTh6X5xLRNnjtX2xSE7z8yMeh(_SUsdg1ytavxaRcNNkhfDrODGhGP , String[] )
   at _yA4PJazdKq1OMm8H6js6v5AhQB._vvUTh6X5xLRNnjtX2xSE7z8yMeh(ThreadStart )
-------------------------------
```

**Comment by Juliustice** [comment]
Now having with Itemhide

**Comment by copygirl** [comment]
Do any other players have this issue? Can you get us a modlist from the server? Also please post your `client-main.txt` log file.

**Comment by Craluminum2413** [comment]
fogdrygrass is item from Fields of Gold mod

**Comment by copygirl** [comment]
Closing due to inactivity.
