### ISSUE TITLE
Game crashes when starting or editing a singleplayer world!

### ISSUE THREAD

**Issue by Rembisz** [anegostudios/VintageStory-Issues#1901]
**Game Version:** v1.16.5 (Stable) 
**Platform:** Windows 10 Pro
**Modded:** No  
**SP/MP:** Singleplayer
### Description
The game client will crash if I choose to create a singleplayer world or edit one in any way; including randomizing the world name.

### How to reproduce
1. Select "Singleplayer" on the main menu
2. Select "Create New World" or select the pencil icon next to an existing world
3. If the pencil icon was selected, it crashes. If "Create new world" was selected, the world name was randomized, "Customize" was selected, or "Create World" was selected, it crashes.

### Expected behavior
To create a new singleplayer world or edit an existing one for a playthrough.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.5 (Stable)
Loaded Mods: 
5/21/2022 12:04:55 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _zXtrAlwcMxPDN3pkprgKfNJKDxy._CN6APN3drRhFjyu5nqigqRRs43X()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _eiwcWjWOiipEBFF56arDK3XkTvG._NjwaSHiLd2LGFKsjyFwy2EWUdSw(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._vvUTh6X5xLRNnjtX2xSE7z8yMeh(_SUsdg1ytavxaRcNNkhfDrODGhGP , String[] )
   at _yA4PJazdKq1OMm8H6js6v5AhQB._vvUTh6X5xLRNnjtX2xSE7z8yMeh(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/21/2022 11:38:26 AM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.16.5.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: f38

Start Time: 01d86d28a74ca700

Termination Time: 3

Application Path: C:\Users\mremb\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: 117ebe12-95a0-4239-b278-2668a61b27dc

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 5/20/2022 11:28:25 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1381417961401207149, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\mremb\AppData\Local\Temp\RDRA619.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA61A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA62A.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA63C.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA65C.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 4706b9fb-77ee-4d6e-9858-f9659c4992b0
Report Status: 268435456
Hashed bucket: 6ce2bbf81ba2523d132bc8511ba9c96d
Cab Guid: 0 }
--------------
{ TimeGenerated = 5/20/2022 10:25:49 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.16.5.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 4c0

Start Time: 01d86cb9d6cbbd88

Termination Time: 4

Application Path: C:\Users\mremb\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: 1a263c37-6214-43b5-b813-1f21133147ef

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
```

**Comment by Rembisz** [comment]
After some troubleshooting, I realized that the three core mods for the base game had not been installed. This fixed my issue after a game reboot!
