### ISSUE TITLE
Multiple crashes: all while just running around in the world

### ISSUE THREAD

**Issue by Rastrick** [anegostudios/VintageStory-Issues#191]
```
Running on 64 bit Windows with 16GB RAM 
9/24/2018 12:43:57 PM: Critical error occurred
System.Exception:  - OpenGL threw an error: InvalidOperation
   at _GFVFLLQwNnXcf7ZUhOhOU2Bd7tj._dHvq0RDewsa4buS97sur4nrWpYF(String )
   at _jdBWFgsE0kU1bPiHLbrPlwR543e._dyjV3fM3p663C83QcyjQeC8vnNE(EnumRenderStage , Single )
   at _cLQRHAYLYEVovKXPTvKbEo1MqUN._dyjV3fM3p663C83QcyjQeC8vnNE(EnumRenderStage , Single )
   at _cLQRHAYLYEVovKXPTvKbEo1MqUN._SHUzVGaZ8i0GhKYQihuznV5yIQB(Single )
   at _cWZXLDhoYltsQ4g1nKLu875c3s._SHUzVGaZ8i0GhKYQihuznV5yIQB(Single )
   at _lKWzMCfprexVlHApWYCx3JV5vFA._36pAeoByfDWnKFTgbRVKLgKzAId(Single )
   at _lKWzMCfprexVlHApWYCx3JV5vFA._5rp0leJJQTi4nJffdTWM3kSyIOG(Single )
   at _GFVFLLQwNnXcf7ZUhOhOU2Bd7tj._WWR3R3sBgWPehyHC086pBdlVMtR(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _tcQesChOYyaLtNtJ3AEPIUj55sd._t1KRpETI2li0DF5RB8KGvdv15Oe(_E6oBzJm7yNRoREiHPanngY7CGto , String[] )
   at _iiDuEMwoYNZoUo3c0D6lzcKnrWn._t1KRpETI2li0DF5RB8KGvdv15Oe(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 9/21/2018 10:49:00 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at _JJC1FjbmfTUzh0UtoYqPtkQ7i0A._tyntGUuwzTfsPnIYHa2chttMTCe(System.String)
   at _bADWtu3wWjMHSGjpq0jXqhGLjjB._Sb6TikVoKiDoe8LxrR9Jp39rlEH(Boolean, Single)
   at _bADWtu3wWjMHSGjpq0jXqhGLjjB._qj0LpJLHIACbgLg5hk6wYUY64Nd(Single)
   at _2EGRB9NEQ0F7tg0ZlMkQby5GXUi._bFxJam23lE4U707O5V4UCkrw9GA(Vintagestory.API.Client.EnumRenderStage, Single)
   at _6ZYP4I8bZ3OFriU531TV3qO8wFL._l7kaqJUlzfMJgZoOz6vTd6aRqLF(Single)
   at _6ZYP4I8bZ3OFriU531TV3qO8wFL._t0XCKgOaOdNHjvFkA1bdjycB0p7(Single)
   at _ytZDA9e6dLzoDc8jRQCHk41FfTJ._zRUUMHTj3pckyvW1yTYyJwWBUGA(Single)
   at _mS743LsjN0xGpTEpLeV0WHGWfhg._Sb6TikVoKiDoe8LxrR9Jp39rlEH(Single)
   at _mS743LsjN0xGpTEpLeV0WHGWfhg._NhrisRdCCX0qGxlbFs79h2W4fAf(Single)
   at _JJC1FjbmfTUzh0UtoYqPtkQ7i0A._NQXJsTI8WFKiWVTwzNdb1quCL0Z(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _tUQ0wd7Yg3zJ0Y8RPnU7lSmMkkH._nk1CWne996bqayKRw7SThbyR57g(_QK4sXQ3qxOSMsnq3xWa64KQNllF, System.String[])
   at _zwG29E5b0OAErM97rzrfge97vBl._nk1CWne996bqayKRw7SThbyR57g(System.Threading.ThreadStart)

 }
{ TimeGenerated = 9/19/2018 7:04:52 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00000000756A4432
 }
{ TimeGenerated = 9/18/2018 9:06:14 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00000000756A4432
 }
```
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/2412200/client-crash.txt)

**Comment by copygirl** [comment]
Crash logs really need to log the version of the game. Which version is this?

**Comment by tyronx** [comment]
rc-3, probably. Added version logging now,

**Comment by tyronx** [comment]
These 2 should be fixed by now
