### ISSUE TITLE
Crash on trying to take salt from barrel with a bucket

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1913]
**Game Version:** 1.16.5
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Explain the issue you're running into.

### How to reproduce
1. Place a barrel
2. Get an empty bucket
3. Put salt into the barrel
4. Open the barrel inventory
5. Right-click on the slot using the bucket
6. It crashed

### Logs
```
Game Version: v1.16.5 (Stable)
Loaded Mods: aaamakeitcompatible@0.0.2, game@1.16.5, creative@1.16.5, survival@1.16.5
05/31/2022 19:03:42: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.ItemSlotBarrelInput.ActivateSlotRightClick(ItemSlot sourceSlot, ItemStackMoveOperation& op)
   at Vintagestory.API.Common.InventoryBase.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse)
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs)
   at Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 800
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._vvUTh6X5xLRNnjtX2xSE7z8yMeh(_SUsdg1ytavxaRcNNkhfDrODGhGP , String[] )
   at _yA4PJazdKq1OMm8H6js6v5AhQB._vvUTh6X5xLRNnjtX2xSE7z8yMeh(ThreadStart )
```

**Comment by Craluminum2413** [comment]
Cannot longer reproduce it, I guess it is fixed

**Comment by Craluminum2413** [comment]
Reproduced in 1.19.0-rc.7

**Comment by Elinty** [comment]
reproduce dit in 1.20

put water inside barrel added wrong amount of salt
then used a bucket to remove the water
salt now went inside barrel, added lime in the barrel slot, then removed lime.
used bucket left click on the barrel slot to take salt = crash 

Running on 64 bit Windows 10.0.19044.0 with 65425 MB RAM
Game Version: v1.20.12 (Stable)
29/08/2025 1:39:26: Critical error occurred
Loaded Mods: axleinblocks@1.21.0, prospecttogether@2.0.7, game@1.20.12, vsimgui@1.1.8, accessibilitytweaks@3.8.5, betterruins@0.4.15, carryon@1.9.9, foodshelves@2.2.1, nbcartographer@2.1.1, creative@1.20.12, survival@1.20.12, xlib@0.8.16, cavebeacons@1.0.9, xskillgilded@1.1.0, xskills@0.8.19
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.ItemSlotBarrelInput.ActivateSlotRightClick(ItemSlot sourceSlot, ItemStackMoveOperation& op) in VSSurvivalMod\Inventory\ItemSlotBarrelInput.cs:line 95
   at Vintagestory.API.Common.InventoryBase.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op) in VintagestoryApi\Common\Inventory\InventoryBase.cs:line 442
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 966
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 762
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs) in VintagestoryApi\Client\UI\GuiComposer.cs:line 477
   at Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 559
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 390
   at Vintagestory.Client.NoObf.ClientMain.UpdateMouseButtonState(EnumMouseButton button, Boolean down) in VintagestoryLib\Client\ClientMain.cs:line 1972
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean isGlobal, Boolean fallBack, Boolean keyup) in VintagestoryLib\Client\HotkeyManager.cs:line 431
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 198
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
