### ISSUE TITLE
Crash on trying to display shield in handbook

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1920]
**Game Version:** 1.17.0-pre.1
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Open the handbook
2. Search for `leather`
3. Try to open handbook page of any `leather`
4. It crashed

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-pre.1 (Unstable)
Loaded Mods: game@1.17.0-pre.1, creative@1.17.0-pre.1, survival@1.17.0-pre.1
06/14/2022 17:37:24: Critical error occurred
System.ArgumentNullException: Value cannot be null.
Parameter name: Unable to find a texture for texture code 'handle' in item game:shield-woodmetalleather. Giving up. Sorry.
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(Int32 indexForLogging, MeshData meshdata, ShapeElement element, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(Shape shapeBase, MeshData& modeldata, Vec3f wholeMeshRotation, Vec3f wholeMeshOffset, Single wholeMeshScale, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(String type, AssetLocation name, CompositeShape compositeShape, MeshData& modeldata, ITexPositionSource texSource, Int32 generalGlowLevel, Byte climateColorMapIndex, Byte seasonColorMapIndex, Nullable`1 quantityElements, String[] selectiveElements)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateItem(Item item, MeshData& modeldata, ITexPositionSource texSource)
   at Vintagestory.GameContent.ItemShield.GenMesh(ItemStack itemstack)
   at Vintagestory.GameContent.ItemShield.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Boolean shading, Boolean origRotate, Boolean showStackSize)
   at Vintagestory.API.Client.SlideshowItemstackTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY)
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime)
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime)
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt)
   at Vintagestory.Client.ScreenManager.Render(Single dt)
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
```

**Comment by BlindSE** [comment]
Same issue here, crash log is also identical to #1932 

```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-pre.1 (Unstable)
Loaded Mods: game@1.17.0-pre.1, creative@1.17.0-pre.1, survival@1.17.0-pre.1
19-Jun-22 19:01:52: Critical error occurred
System.ArgumentNullException: Value cannot be null.
Parameter name: Unable to find a texture for texture code 'handle' in item game:shield-woodmetalleather. Giving up. Sorry.
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(Int32 indexForLogging, MeshData meshdata, ShapeElement element, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(Shape shapeBase, MeshData& modeldata, Vec3f wholeMeshRotation, Vec3f wholeMeshOffset, Single wholeMeshScale, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(String type, AssetLocation name, CompositeShape compositeShape, MeshData& modeldata, ITexPositionSource texSource, Int32 generalGlowLevel, Byte climateColorMapIndex, Byte seasonColorMapIndex, Nullable`1 quantityElements, String[] selectiveElements)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateItem(Item item, MeshData& modeldata, ITexPositionSource texSource)
   at Vintagestory.GameContent.ItemShield.GenMesh(ItemStack itemstack)
   at Vintagestory.GameContent.ItemShield.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Boolean shading, Boolean origRotate, Boolean showStackSize)
   at Vintagestory.API.Client.SlideshowItemstackTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY)
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime)
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime)
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt)
   at Vintagestory.Client.ScreenManager.Render(Single dt)
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)

```

**Comment by TheK0tYaRa** [comment]
Happened when looking up bronze or copper saw (don't remember which) from the acacia plank recipe
```
Running on 64 bit Linux with 15 GB. 
Game Version: v1.17.0-pre.1 (Unstable)
Loaded Mods: game@1.17.0-pre.1, creative@1.17.0-pre.1, survival@1.17.0-pre.1
6/20/2022 9:58:44 PM: Critical error occurred
System.ArgumentNullException: Value cannot be null.
Parameter name: Unable to find a texture for texture code 'handle' in item game:shield-woodmetalleather. Giving up. Sorry.
  at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement (System.Int32 indexForLogging, Vintagestory.API.Client.MeshData meshdata, Vintagestory.API.Common.ShapeElement element, Vintagestory.API.Client.TesselationMetaData meta) [0x0030b] in <941b00a03cf0410ca4ed938380fb42ad>:0 
  at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements (Vintagestory.API.Client.MeshData meshdata, Vintagestory.API.Common.ShapeElement[] elements, Vintagestory.API.Client.TesselationMetaData meta) [0x0032a] in <941b00a03cf0410ca4ed938380fb42ad>:0 
  at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements (Vintagestory.API.Client.MeshData meshdata, Vintagestory.API.Common.ShapeElement[] elements, Vintagestory.API.Client.TesselationMetaData meta) [0x00380] in <941b00a03cf0410ca4ed938380fb42ad>:0 
  at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements (Vintagestory.API.Client.MeshData meshdata, Vintagestory.API.Common.ShapeElement[] elements, Vintagestory.API.Client.TesselationMetaData meta) [0x00380] in <941b00a03cf0410ca4ed938380fb42ad>:0 
  at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape (Vintagestory.API.Common.Shape shapeBase, Vintagestory.API.Client.MeshData& modeldata, Vintagestory.API.MathTools.Vec3f wholeMeshRotation, Vintagestory.API.MathTools.Vec3f wholeMeshOffset, System.Single wholeMeshScale, Vintagestory.API.Client.TesselationMetaData meta) [0x0012a] in <941b00a03cf0410ca4ed938380fb42ad>:0 
  at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape (System.String type, Vintagestory.API.Common.AssetLocation name, Vintagestory.API.Common.CompositeShape compositeShape, Vintagestory.API.Client.MeshData& modeldata, Vintagestory.API.Client.ITexPositionSource texSource, System.Int32 generalGlowLevel, System.Byte climateColorMapIndex, System.Byte seasonColorMapIndex, System.Nullable`1[T] quantityElements, System.String[] selectiveElements) [0x00470] in <941b00a03cf0410ca4ed938380fb42ad>:0 
  at Vintagestory.Client.NoObf.ShapeTesselator.TesselateItem (Vintagestory.API.Common.Item item, Vintagestory.API.Client.MeshData& modeldata, Vintagestory.API.Client.ITexPositionSource texSource) [0x000a9] in <941b00a03cf0410ca4ed938380fb42ad>:0 
  at Vintagestory.GameContent.ItemShield.GenMesh (Vintagestory.API.Common.ItemStack itemstack) [0x003a6] in <c705ef60167d4c8dbc0d37a8c425943d>:0 
  at Vintagestory.GameContent.ItemShield.OnBeforeRender (Vintagestory.API.Client.ICoreClientAPI capi, Vintagestory.API.Common.ItemStack itemstack, Vintagestory.API.Client.EnumItemRenderTarget target, Vintagestory.API.Client.ItemRenderInfo& renderinfo) [0x000e8] in <c705ef60167d4c8dbc0d37a8c425943d>:0 
  at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo (Vintagestory.Client.NoObf.ClientMain game, Vintagestory.API.Common.ItemSlot inSlot, Vintagestory.API.Client.EnumItemRenderTarget target, System.Single dt) [0x002d9] in <941b00a03cf0410ca4ed938380fb42ad>:0 
  at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui (Vintagestory.API.Common.ItemSlot inSlot, System.Double posX, System.Double posY, System.Double posZ, System.Single size, System.Int32 color, System.Boolean shading, System.Boolean origRotate, System.Boolean showStackSize) [0x00007] in <941b00a03cf0410ca4ed938380fb42ad>:0 
  at Vintagestory.Client.NoObf.RenderAPIGame.RenderItemstackToGui (Vintagestory.API.Common.ItemSlot inSlot, System.Double posX, System.Double posY, System.Double posZ, System.Single size, System.Int32 color, System.Boolean shading, System.Boolean rotate, System.Boolean showStacksize) [0x00000] in <941b00a03cf0410ca4ed938380fb42ad>:0 
  at Vintagestory.API.Client.SlideshowItemstackTextComponent.RenderInteractiveElements (System.Single deltaTime, System.Double renderX, System.Double renderY) [0x001af] in <8a8374656465408b90cdf970c6e30f76>:0 
  at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements (System.Single deltaTime) [0x000ca] in <8a8374656465408b90cdf970c6e30f76>:0 
  at Vintagestory.API.Client.GuiComposer.Render (System.Single deltaTime) [0x000b7] in <8a8374656465408b90cdf970c6e30f76>:0 
  at Vintagestory.API.Client.GuiDialog.OnRenderGUI (System.Single deltaTime) [0x0001c] in <8a8374656465408b90cdf970c6e30f76>:0 
  at Vintagestory.GameContent.GuiDialogHandbook.OnRenderGUI (System.Single deltaTime) [0x0006a] in <c705ef60167d4c8dbc0d37a8c425943d>:0 
  at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI (System.Single deltaTime) [0x00034] in <941b00a03cf0410ca4ed938380fb42ad>:0 
  at Vintagestory.API.Client.DummyRenderer.OnRenderFrame (System.Single deltaTime, Vintagestory.API.Client.EnumRenderStage stage) [0x00000] in <8a8374656465408b90cdf970c6e30f76>:0 
  at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage (Vintagestory.API.Client.EnumRenderStage stage, System.Single dt) [0x00072] in <941b00a03cf0410ca4ed938380fb42ad>:0 
  at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage (Vintagestory.API.Client.EnumRenderStage stage, System.Single dt) [0x00028] in <941b00a03cf0410ca4ed938380fb42ad>:0 
  at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer (System.Single dt) [0x0005a] in <941b00a03cf0410ca4ed938380fb42ad>:0 
  at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer (System.Single dt) [0x0003e] in <941b00a03cf0410ca4ed938380fb42ad>:0 
  at Vintagestory.Client.ScreenManager.Render (System.Single dt) [0x001df] in <941b00a03cf0410ca4ed938380fb42ad>:0 
  at Vintagestory.Client.ScreenManager.OnNewFrame (System.Single dt) [0x000cc] in <941b00a03cf0410ca4ed938380fb42ad>:0 
  at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame (System.Object sender, OpenTK.FrameEventArgs e) [0x00141] in <941b00a03cf0410ca4ed938380fb42ad>:0 
  at (wrapper delegate-invoke) System.EventHandler`1[OpenTK.FrameEventArgs].invoke_void_object_TEventArgs(object,OpenTK.FrameEventArgs)
  at OpenTK.GameWindow.OnRenderFrame (OpenTK.FrameEventArgs e) [0x00000] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.GameWindow.OnRenderFrameInternal (OpenTK.FrameEventArgs e) [0x00010] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.GameWindow.RaiseRenderFrame (System.Double elapsed, System.Double& timestamp) [0x0000c] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.GameWindow.DispatchRenderFrame () [0x00038] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.GameWindow.Run (System.Double updates_per_second, System.Double frames_per_second) [0x00104] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.GameWindow.Run () [0x00000] in <a4886e33f9fc416195d24950e7205b94>:0 
  at Vintagestory.Client.ClientProgram.Start (Vintagestory.Client.ClientProgramArgs args, System.String[] rawArgs) [0x003dc] in <07663b59d87744ea870f482293519ba1>:0 
  at Vintagestory.Client.ClientProgram+<>c__DisplayClass14_0.<.ctor>b__0 () [0x00000] in <07663b59d87744ea870f482293519ba1>:0 
  at Vintagestory.ClientNative.CrashReporter.Start (System.Threading.ThreadStart start) [0x00007] in <941b00a03cf0410ca4ed938380fb42ad>:0 
-------------------------------
```

**Comment by Craluminum2413** [comment]
@TheK0tYaRa Your crash log says that shield is to blame
