### ISSUE TITLE
Crash on trying to see shield's attributes in the handbook

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1932]
**Game Version:** 1.17.0-pre.1
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Open handbook
2. Search for `board` and open its handbook page
3. Hover over a shield while holding `Shift`/`Sneak` button
4. It crashes when reaches the shield without handle?

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-pre.1 (Unstable)
Loaded Mods: game@1.17.0-pre.1, creative@1.17.0-pre.1, survival@1.17.0-pre.1
06/15/2022 14:33:00: Critical error occurred
System.ArgumentNullException: Value cannot be null.
Parameter name: Unable to find a texture for texture code 'handle' in item game:shield-woodmetalleather. Giving up. Sorry.
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(Int32 indexForLogging, MeshData meshdata, ShapeElement element, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(Shape shapeBase, MeshData& modeldata, Vec3f wholeMeshRotation, Vec3f wholeMeshOffset, Single wholeMeshScale, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(String type, AssetLocation name, CompositeShape compositeShape, MeshData& modeldata, ITexPositionSource texSource, Int32 generalGlowLevel, Byte climateColorMapIndex, Byte seasonColorMapIndex, Nullable`1 quantityElements, String[] selectiveElements)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateItem(Item item, MeshData& modeldata, ITexPositionSource texSource)
   at Vintagestory.GameContent.ItemShield.GenMesh(ItemStack itemstack)
   at Vintagestory.GameContent.ItemShield.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Boolean shading, Boolean origRotate, Boolean showStackSize)
   at Vintagestory.API.Client.SlideshowItemstackTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY)
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime)
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime)
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt)
   at Vintagestory.Client.ScreenManager.Render(Single dt)
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
```

**Comment by copygirl** [comment]
Probably safe to close this since crash is identical to #1920 as noted by @BlindSE.
