### ISSUE TITLE
Crash after a while when staying close to growing fruit tree

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1945]
**Game Version:** 1.17.0-pre.1
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Generate a new world
2. Find a fruit tree
3. Stay near it for a minute or two
4. It crashed

### Logs
```
Game Version: v1.17.0-pre.1 (Unstable)
Loaded Mods: game@1.17.0-pre.1, paw@1.0.0, creative@1.17.0-pre.1, survival@1.17.0-pre.1
06/16/2022 13:01:18: Critical error occurred
System.Exception: Call to RegisterCallback while game is paused. ExtendedDebug info and developermode is enabled, so will crash on this for reporting reasons.
   at Vintagestory.Client.NoObf.ClientMain.RegisterCallback(Action`1 OnTimePassed, Int32 millisecondDelay)
   at Vintagestory.API.Common.BlockEntity.RegisterDelayedCallback(Action`1 OnDelayedCallbackTick, Int32 millisecondInterval)
   at Vintagestory.GameContent.BlockEntityFruitTreePart.Initialize(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientWorldMap.SpawnBlockEntity(String classname, BlockPos position, ItemStack byItemStack)
   at Vintagestory.API.Common.Block.OnBlockPlaced(IWorldAccessor world, BlockPos blockPos, ItemStack byItemStack)
   at Vintagestory.Common.BlockAccessorBase.SetBlock_Unsafe(Int32 blockId, BlockPos pos, IWorldChunk chunk, Boolean synchronize, Boolean relight, ItemStack byItemstack)
   at Vintagestory.Common.BlockAccessorRelaxed.SetBlock(Int32 blockId, BlockPos pos, ItemStack byItemstack)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleSetBlock(Packet_Server packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt)
   at Vintagestory.Client.ScreenManager.Render(Single dt)
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
```

**Comment by tyronx** [comment]
You can avoid the issue by disabling extended debug info via `.edi`

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
