### ISSUE TITLE
Crash on typing `.debug perceptioneffect` command

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1971]
**Game Version:** 1.17.0-pre.1
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Type `.debug perceptioneffect` command
2. It crashed

### Logs
```
Game Version: v1.17.0-pre.1 (Unstable)
Loaded Mods: game@1.17.0-pre.1, creative@1.17.0-pre.1, survival@1.17.0-pre.1
06/25/2022 19:12:59: Critical error occurred
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at Vintagestory.API.Client.PerceptionEffects.TriggerEffect(String code, Single intensity, Nullable`1 on)
   at Vintagestory.Client.NoObf.ClientSystemDebugCommands.cDebug(Int32 groupId, CmdArgs args)
   at Vintagestory.Client.NoObf.HudDialogChat.OnNewClientToServerChatLine(Int32 groupId, String message, EnumChatType chattype, String data)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerNewClientChatLine(Int32 groupid, String message, EnumChatType chattype, String data)
   at Vintagestory.Client.NoObf.HudDialogChat.OnKeyDown(KeyEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnKeyDown(KeyEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(Object sender, KeyboardKeyEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnKeyDown(Key key, Boolean repeat) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\NativeWindowBase.cs:line 130
   at OpenTK.Platform.Windows.WinGLNative.HandleKeyboard(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 646
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 828
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
```

**Comment by Craluminum2413** [comment]
Just a note: I know that there are only two values, but it would be nice to have a null check

**Comment by tyronx** [comment]
thanks for the report, this will be fixed in pre.3
