### ISSUE TITLE
Game just crash when i'm trying to create world or set the creating settings.

### ISSUE THREAD

**Issue by HackedHuman** [anegostudios/VintageStory-Issues#1979]
```
Running on 64 bit Windows with 4 GB RAM 
Game Version: v1.16.5 (Stable)
Loaded Mods: 
6/27/2022 23:02:33: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.WorldConfig.Clone()
   at _zXtrAlwcMxPDN3pkprgKfNJKDxy._ysE57KiT3L8iz46mfuMvooa0rnD()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _eiwcWjWOiipEBFF56arDK3XkTvG._NjwaSHiLd2LGFKsjyFwy2EWUdSw(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._vvUTh6X5xLRNnjtX2xSE7z8yMeh(_SUsdg1ytavxaRcNNkhfDrODGhGP , String[] )
   at _yA4PJazdKq1OMm8H6js6v5AhQB._vvUTh6X5xLRNnjtX2xSE7z8yMeh(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/27/2022 22:38:53, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.16.5.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 1d88

Start Time: 01d88a5d45671a11

Termination Time: 16

Application Path: C:\Games\Vintagestory\Vintagestory.exe

Report Id: fa53a9f5-2b87-408a-91cf-f0847ce01f65

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 6/27/2022 22:38:49, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 625674b5
P4: 69a4
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCD5C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCD9B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCD9A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCDCA.tmp.txt
\\?\C:\Users\bylat\AppData\Local\Temp\WERA38.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_f39c1bff869f8da277b1ab65e2cd1262bd4945b_1f70e3ae_03e361d7-51d8-461f-b04a-554110ecbc6e

Analysis symbol: 
Rechecking for solution: 0
Report Id: fa53a9f5-2b87-408a-91cf-f0847ce01f65
Report Status: 97
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/27/2022 22:36:10, Site = , Source = Windows Error Reporting, Message = Fault bucket 2059630762467349402, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 625674b5
P4: ntdll.dll
P5: 10.0.19041.1741
P6: 77755782
P7: c00000fd
P8: 0000000000051d81
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER90BA.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9956.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9976.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9986.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9997.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_5ab5ef1707f536f3e75a0b6e784f5d53d75d137_1f70e3ae_c1c91d1d-b1f3-43c0-8354-4ae1d284fec4

Analysis symbol: 
Rechecking for solution: 0
Report Id: d776c81a-5b81-4893-9bd5-31d351ef7355
Report Status: 268435456
Hashed bucket: 4b271a7ecd4a2a89ec9547441d55539a
Cab Guid: 0 }
```

**Comment by tyronx** [comment]
Hi, is there any way to reproduce this?

**Comment by Craluminum2413** [comment]
Closing due to inactivity
