### ISSUE TITLE
1.17pre2 :memory leak and texture id missing Dispose call

### ISSUE THREAD

**Issue by Aledark789** [anegostudios/VintageStory-Issues#1990]
**Game Version:**1.17pre2
**Platform:** Windows 
**Modded:** No
**SP/MP:** Singleplayer 

### Description
Explain the issue you're running into.

1.7.2022 18:06:16 [Warning] Texture with texture id 639 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 637 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 638 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 636 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 634 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 635 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 633 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 632 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 631 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 630 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 629 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 628 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 627 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 626 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 625 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 624 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 623 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 622 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 621 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 620 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 619 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 643 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 642 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 640 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:06:16 [Warning] Texture with texture id 641 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
1.7.2022 18:21:03 [Notification] DebugSeverityMedium DebugTypePerformance | Pixel-path performance warning: Pixel transfer is synchronized with 3D rendering.
1.7.2022 18:25:24 [Warning] OpenAL Error during SetPitch of sound game:sounds/weather/tracks/rain-leafless.ogg: InvalidValue
1.7.2022 18:25:30 [Notification] Client pause state is now on
1.7.2022 18:25:30 [Notification] Destroying game session, waiting up to 200ms for client threads to exit
1.7.2022 18:25:31 [Notification] Stopping single player server
1.7.2022 18:25:32 [Notification] Exiting current game to main menu, reason: leave world button pressed
1.7.2022 18:25:32 [Notification] GuiScreenConnectingToServer constructed
1.7.2022 18:25:35 [Warning] Texture with texture id 42 is leaking memory, missing call to Dispose. Allocated at    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at Vintagestory.Client.GuiCompositeMainMenuLeft.Compose()
   at Vintagestory.Client.ScreenManager.initMainMenu()
   at Vintagestory.Client.GuiScreenExitingServer.RenderToDefaultFramebuffer(Single dt)
   at Vintagestory.Client.ScreenManager.Render(Single dt)
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
   at Vintagestory.Client.ClientProgram.Main(String[] rawArgs).
1.7.2022 18:25:35 [Warning] MeshRef with vao id 5 with 6 indices is leaking memory, missing call to Dispose. Allocated at    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at Vintagestory.Client.NoObf.VAO..ctor()
   at Vintagestory.Client.NoObf.ClientPlatformWindows.UploadMesh(MeshData data)
   at Vintagestory.Client.ParticlePool2D..ctor(ICoreClientAPI capi, Int32 poolSize)
   at Vintagestory.Client.ParticleRenderer2D..ctor(ScreenManager screenManager, ICoreClientAPI api, Int32 poolSize)
   at Vintagestory.Client.GuiCompositeMainMenuLeft..ctor(ScreenManager screenManager)
   at Vintagestory.Client.ScreenManager.initMainMenu()
   at Vintagestory.Client.GuiScreenExitingServer.RenderToDefaultFramebuffer(Single dt)
   at Vintagestory.Client.ScreenManager.Render(Single dt)
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
   at Vintagestory.Client.ClientProgram.Main(String[] rawArgs).
1.7.2022 18:26:42 [Notification] Exiting game now. Server running=False. Exit reason: Main screen quit button was pressed

### Logs
```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in pre.3
