### ISSUE TITLE
1.17 pre3 Crash when loading savegame Vintagestory.Client.NoObf.TextureAtlasManager.ComposeTextureAtlasses_StageC()

### ISSUE THREAD

**Issue by hlangeveld** [anegostudios/VintageStory-Issues#2001]
**Game Version:** 1.17 pre3
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Explain the issue you're running into.

### How to reproduce

Not really.

#### How it happened

1. See a bear. ;-)
2. Save and Exit into Main menu.
3. Load game.
4. Crash

### Expected behavior
Back in the game.

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-pre.3 (Unstable)
Loaded Mods: game@1.17.0-pre.3, creative@1.17.0-pre.3, survival@1.17.0-pre.3
07/07/2022 18:11:20: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.Client.NoObf.TextureAtlasManager.ComposeTextureAtlasses_StageC()
   at Vintagestory.Client.NoObf.ClientMain.FinaliseTextureAtlas_StageC(TextureAtlasManager manager, String type, Action onCompleted)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 07/07/2022 18:11:23, Site = , Source = Windows Error Reporting, Message = Fault bucket 1293406959397321074, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 62c4393e
P4: VintagestoryLib
P5: 1.17.0.0
P6: 62c4393e
P7: 29f9
P8: 0
P9: System.IndexOutOfRangeException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCCCF.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCF22.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCF33.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCF31.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCF41.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_244472dba1c6bae36ad6953a58deab23a7b01e_9cc63e72_98dc0c7d-503e-4c50-b8dc-bfb164dc470a

Analysis symbol: 
Rechecking for solution: 0
Report Id: 24c2a837-ba46-491f-9fc6-443b2ddeceea
Report Status: 268435456
Hashed bucket: c57cd2a27d2a6fa511f31ac6dce53972
Cab Guid: 0 }
--------------
{ TimeGenerated = 07/07/2022 18:11:21, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.0.0, time stamp: 0x62c4393e
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1741, time stamp: 0xe9b4a91b
Exception code: 0xe0434352
Fault offset: 0x0000000000034fd9
Faulting process ID: 0x5e1c
Faulting application start time: 0x01d892180778a19f

```

I will try to restart the game to see if this happens again.

**Comment by hlangeveld** [comment]
Reloading the game was fine.  Perhaps a race condition?

> 1. See a bear. ;-)

Saved and reloaded again, once with bear in sight, once without.  No difference. Game loaded fine.

> Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCCCF.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCF22.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCF33.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCF31.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCF41.tmp.txt

WER\Temp Directory was empty. No dump attached.

**Comment by copygirl** [comment]
It does sound like a race condition. Maybe something odd caused by the startup optimizations @radfast did for 1.17?

**Comment by tyronx** [comment]
That does sound like a race condition, indeed

**Comment by Craluminum2413** [comment]
Closing due to inactivity
