### ISSUE TITLE
Mod Issue - mods are supposed to work with 1.17.3

### ISSUE THREAD

**Issue by Amestad** [anegostudios/VintageStory-Issues#2007]
**Game Version:** 1.17.3
**Platform:** Windows / Mac / Linux (which?)   
**Modded:** No / Yes (which?)  
**SP/MP:** Singleplayer / Multiplayer (which?)  

### Description
Crashes on load world when trying to run either Carry Capacity, or primitive survival. 
Other mods work ok and I've been told that these mods work on1.17.3 
I also tried them with 1.17.0, 1.17.1,1.17.2etc
game runs fine when these mods are turned off.

Not sure if it makes a difference but although I've deleted old versions of these mods they still show up in the mod manager (see image). does this mean there's a cache file or something that needs clearing?

### How to reproduce
start world with either carry capacity or primite survival turned on or both. 
other mods work ok.

### Expected behavior
N/A
### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.
![image](https://user-images.githubusercontent.com/109076900/178252385-f41d9447-1b1c-45ff-b680-740feea1210e.png)

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-pre.3 (Unstable)
Loaded Mods: buzzwords@1.0.0, vtpp@1.0.0, game@1.17.0-pre.3, egocaribautomapmarkers@2.4.0-pre.1, hudclock@2.5.0, creative@1.17.0-pre.3, vsprospectorinfo@4.1.0, survival@1.17.0-pre.3
11/07/2022 9:04:19 PM: Critical error occurred
System.Exception: Don't know how to instantiate collectible behavior of class 'Carryable' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateCollectibleBehavior(CollectibleObject collectible, String code)
   at Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType packet, IWorldAccessor world, ClassRegistry registry)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateBlocks(Block[] blocks, Int32 start, Int32 maxCount)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.LoadBlockTypes()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/07/2022 9:04:20 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Vintagestory.Common.ClassRegistry.CreateCollectibleBehavior(Vintagestory.API.Common.CollectibleObject, System.String)
   at Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateBlocks(Vintagestory.API.Common.Block[], Int32, Int32)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.LoadBlockTypes()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 11/07/2022 9:02:01 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2237563695530838248, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 62c4393e
P4: StackHash_0000
P5: 0.0.0.0
P6: 00000000
P7: 00000000
P8: PCH_84
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5C1B.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_768cc43cfac89dc21d9baaa545afcedb3fcff2d_9cc63e72_b98adc79-82c3-4a3e-aac8-b2835345e7c0

Analysis symbol: 
Rechecking for solution: 0
Report Id: 206b9158-a9c9-4949-8e8a-e95bf60e7ddb
Report Status: 268566528
Hashed bucket: ce539e459b2c73810f0d6c53726d08e8
Cab Guid: 0 }
--------------
{ TimeGenerated = 11/07/2022 9:02:00 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 62c4393e
P4: StackHash_0000
P5: 0.0.0.0
P6: 00000000
P7: 00000000
P8: PCH_84
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_768cc43cfac89dc21d9baaa545afcedb3fcff2d_9cc63e72_b98adc79-82c3-4a3e-aac8-b2835345e7c0

Analysis symbol: 
Rechecking for solution: 0
Report Id: 206b9158-a9c9-4949-8e8a-e95bf60e7ddb
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }


and with primitive survival


Game Version: v1.17.0-pre.3 (Unstable)
Loaded Mods: buzzwords@1.0.0, vtpp@1.0.0, game@1.17.0-pre.3, egocaribautomapmarkers@2.4.0-pre.1, hudclock@2.5.0, creative@1.17.0-pre.3, vsprospectorinfo@4.1.0, survival@1.17.0-pre.3
11/07/2022 9:19:26 PM: Critical error occurred
System.Exception: Don't know how to instantiate item of class 'itemhide' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass)
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType packet, IWorldAccessor world, ClassRegistry registry)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateItems(List`1 items, Int32 listSize)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.LoadItemTypes()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()



```

**Comment by Craluminum2413** [comment]
Clear your VintagestoryData/Cache folder

**Comment by copygirl** [comment]
Very likely an issue with the mods, instead of the game. (Until proven otherwise, anyway.)

I happen to be the author of CarryCapacity. It'd be lovely if you could crash the game one more time with my mod and give me a `.zip` with all the log files so I can have a look at them. I suppose you can attach them to this issue. But you can also send me a Discord message or message me on the forums.

**Comment by Amestad** [comment]
[Logs.zip](https://github.com/anegostudios/VintageStory-Issues/files/9088148/Logs.zip)
Thanks Copygirl
Please find the zip file of the logs attached here. 



> Very likely an issue with the mods, instead of the game. (Until proven otherwise, anyway.)
> 
> I happen to be the author of CarryCapacity. It'd be lovely if you could crash the game one more time with my mod and give me a `.zip` with all the log files so I can have a look at them. I suppose you can attach them to this issue. But you can also send me a Discord message or message me on the forums.

**Comment by Amestad** [comment]
> 1.17.1, 1.17.2 and 1.17.3 versions don't exist

Apologies, you are right I meant  pre1, pre 2 and pre 3

**Comment by Amestad** [comment]
> Clear your Roaming/VintagestoryData/Cache folder

Thanks I'll try that now that I have the zip of the logs for copygirl from a fresh crash.

**Comment by Amestad** [comment]
> 
No luck after clearing the cache folder. crashes as normal At the exact same place as always on the loading screen when it gets to the dialogue simple tools...


> > Clear your Roaming/VintagestoryData/Cache folder
> 
> Thanks I'll try that now that I have the zip of the logs for copygirl from a fresh crash.

**Comment by Craluminum2413** [comment]
Do you have any mods in `Roaming/Vintagestory/Mods` folder?

**Comment by Amestad** [comment]
![image](https://user-images.githubusercontent.com/109076900/178455969-f66425e8-0314-444f-84d8-ac1da8a6e607.png)
If you mean the windows folder then you can see the mods here. 
Regarding the mods list in VS mod manager, I have a couple of mods most of which work. 

I have previously removed all mods from the folder bar primitive and carry capacity individually e.g. i tried only the 1 mod at a time. 
See again the screenshot where everything except carry capacity is removed from the mods folder and when i hit reload mods nearly all mods disappear from the list.  crash report after trying to run the game with carry capacity is below.



![image](https://user-images.githubusercontent.com/109076900/178457509-566eaaf9-bee7-4f47-b8da-07f65d407ac0.png)

if i reove all mods from the folder and hit reload mods i still have these 4 mods listed... i think this is the route of the issue somehow but i have cleared the cache so where else is this lingering mods data hiding??

![image](https://user-images.githubusercontent.com/109076900/178458599-a393928f-8ca5-4211-ad77-3731d0bc89d1.png)

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-pre.3 (Unstable)
Loaded Mods: game@1.17.0-pre.3, creative@1.17.0-pre.3, survival@1.17.0-pre.3
12/07/2022 7:23:23 PM: Critical error occurred
System.Exception: Don't know how to instantiate collectible behavior of class 'Carryable' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateCollectibleBehavior(CollectibleObject collectible, String code)
   at Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType packet, IWorldAccessor world, ClassRegistry registry)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateBlocks(Block[] blocks, Int32 start, Int32 maxCount)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.LoadBlockTypes()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/07/2022 7:23:23 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Vintagestory.Common.ClassRegistry.CreateCollectibleBehavior(Vintagestory.API.Common.CollectibleObject, System.String)
   at Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateBlocks(Vintagestory.API.Common.Block[], Int32, Int32)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.LoadBlockTypes()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 12/07/2022 9:47:40 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Vintagestory.Common.ClassRegistry.CreateCollectibleBehavior(Vintagestory.API.Common.CollectibleObject, System.String)
   at Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateBlocks(Vintagestory.API.Common.Block[], Int32, Int32)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.LoadBlockTypes()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 12/07/2022 9:43:42 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Vintagestory.Common.ClassRegistry.CreateCollectibleBehavior(Vintagestory.API.Common.CollectibleObject, System.String)
   at Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateBlocks(Vintagestory.API.Common.Block[], Int32, Int32)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.LoadBlockTypes()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by Craluminum2413** [comment]
There are two Mods folders, they are listed in `VintagestoryData/serverconfig.json` and `VintagestoryData/clientsettings.json` files

**Comment by Craluminum2413** [comment]
This is the first Mods folder:
![image](https://user-images.githubusercontent.com/69315569/178460081-241bb040-477f-4fb0-8883-ea41314d61fa.png)
This is the second Mods folder:
![image](https://user-images.githubusercontent.com/69315569/178460171-fd9fe170-f299-4c81-85a9-3d4689902901.png)

**Comment by Craluminum2413** [comment]
Sometimes the solution is very simple
