### ISSUE TITLE
Game CTD when making copper helmet

### ISSUE THREAD

**Issue by TheOtherEricSchmidt** [anegostudios/VintageStory-Issues#2013]
### How to reproduce
1. Make a Copper Helmet
2. Use it on Put it back in the crafting grid and add more scales
3. It CTD

### Expected behavior
I expected it not to crash

### Screenshots
[Attach a screenshot if it helps explain the issue / shows a visual bug.](https://clips.twitch.tv/FrigidPoorStrawberryStinkyCheese-1Y8jBu0VeC4LljId)

### Logs
```
14.7.2022 08:58:56 [Notification] Client logger started.
14.7.2022 08:58:56 [Notification] Game Version: v1.17.0-pre.3 (Unstable)
14.7.2022 08:58:56 [Notification] Screens:
14.7.2022 08:58:56 [Notification] 0: {X=0,Y=0,Width=1920,Height=1080}, \\.\DISPLAY1 (primary)
14.7.2022 08:58:56 [Notification] 1: {X=1920,Y=0,Width=1920,Height=1080}, \\.\DISPLAY2 
14.7.2022 08:58:57 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
14.7.2022 08:58:57 [Notification] Graphics Card Vendor: NVIDIA Corporation
14.7.2022 08:58:57 [Notification] Graphics Card Version: 3.3.0 NVIDIA 516.59
14.7.2022 08:58:57 [Notification] Graphics Card Renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
14.7.2022 08:58:57 [Notification] Graphics Card ShadingLanguageVersion: 3.30 NVIDIA via Cg compiler
14.7.2022 08:58:57 [Notification] Cairo Graphics Version: 1.17.3
14.7.2022 08:58:57 [Notification] OpenAL Version: 1.1 ALSOFT 1.16.0
14.7.2022 08:58:57 [Notification] C# Framework: .net Framework 4.0.30319.42000
14.7.2022 08:58:57 [Notification] OpenTK Version: 3.3.2 (A set of fast, low-level C# bindings for OpenGL, OpenGL ES and OpenAL.)
14.7.2022 08:58:57 [Notification] Start discovering assets
14.7.2022 08:58:57 [Notification] Found 18 base assets in category lang
14.7.2022 08:58:57 [Notification] Found 0 base assets in category patches
14.7.2022 08:58:57 [Notification] Found 22 base assets in category config
14.7.2022 08:58:57 [Notification] Found 0 base assets in category worldproperties
14.7.2022 08:58:57 [Notification] Found 46 base assets in category sounds
14.7.2022 08:58:57 [Notification] Found 97 base assets in category shapes
14.7.2022 08:58:57 [Notification] Found 82 base assets in category shaders
14.7.2022 08:58:57 [Notification] Found 16 base assets in category shaderincludes
14.7.2022 08:58:57 [Notification] Found 128 base assets in category textures
14.7.2022 08:58:57 [Notification] Found 4 base assets in category music
14.7.2022 08:58:57 [Notification] Found 0 base assets in category dialog
14.7.2022 08:58:57 [Notification] Found 413 base assets in total
14.7.2022 08:58:57 [Notification] Loading sounds
14.7.2022 08:58:57 [Notification] Sounds loaded
14.7.2022 08:58:57 [Notification] (Re-)loaded frame buffers
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass .
14.7.2022 08:58:57 [Notification] CPU Cores: 12
14.7.2022 08:58:57 [Notification] Window was resized to 1920 1080, rebuilding framebuffers...
14.7.2022 08:58:57 [Notification] (Re-)loaded frame buffers
14.7.2022 08:58:57 [Notification] Begin loading shaders
14.7.2022 08:58:57 [Notification] Load shaders now
14.7.2022 08:58:57 [Notification] Loading shaders...
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass standard.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass particlescube.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass particlesquad.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass sky.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass nightsky.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass woittest.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass helditem.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass decals.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass final.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass gui.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass blur.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass findbright.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass godrays.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass autocamera.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass wireframe.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass entityanimated.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass luma.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass blit.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass texture2texture.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass celestialobject.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass colorgrade.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass guigear.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass ssao.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass grass.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass flowers.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass shadowgrass.
14.7.2022 08:58:57 [Notification] Loaded Shaderprogramm for render pass shadowflowers.
14.7.2022 08:58:57 [Notification] Cached session key is valid, validating with server
14.7.2022 08:58:58 [Notification] Server validation response: Good
14.7.2022 08:58:58 [Notification] Will search the following paths for mods:
14.7.2022 08:58:58 [Notification]     C:\Users\erica\AppData\Roaming\Vintagestory\Mods
14.7.2022 08:58:58 [Notification]     C:\Users\erica\AppData\Roaming\VintagestoryData\Mods
14.7.2022 08:59:05 [Notification] Will search the following paths for mods:
14.7.2022 08:59:05 [Notification]     C:\Users\erica\AppData\Roaming\Vintagestory\Mods
14.7.2022 08:59:05 [Notification]     C:\Users\erica\AppData\Roaming\VintagestoryData\Mods
14.7.2022 08:59:09 [Notification] Initialized GUI Manager
14.7.2022 08:59:09 [Notification] Initialized Server Connection
14.7.2022 08:59:09 [Notification] Server args parsed
14.7.2022 08:59:09 [Notification] GuiScreenConnectingToServer constructed
14.7.2022 08:59:10 [Notification] Server main instantiated
14.7.2022 08:59:13 [Notification] Received server assets
14.7.2022 08:59:13 [Notification] Loading and pre-starting client side mods...
14.7.2022 08:59:13 [Notification] Will search the following paths for mods:
14.7.2022 08:59:13 [Notification]     C:\Users\erica\AppData\Roaming\Vintagestory\Mods
14.7.2022 08:59:13 [Notification]     C:\Users\erica\AppData\Roaming\VintagestoryData\Mods
14.7.2022 08:59:13 [Notification] Found 4 mods (1 disabled)
14.7.2022 08:59:13 [Notification] Mods, sorted by dependency: game, creative, survival
14.7.2022 08:59:13 [Notification] Instantiated 77 mod systems from 3 enabled mods
14.7.2022 08:59:13 [Notification] Done loading and pre-starting client side mods.
14.7.2022 08:59:13 [Notification] External Origins in load order: modorigin@C:\Users\erica\AppData\Roaming\Vintagestory\assets\creative\, modorigin@C:\Users\erica\AppData\Roaming\Vintagestory\assets\survival\
14.7.2022 08:59:13 [Notification] Found 0 external assets in category lang
14.7.2022 08:59:13 [Notification] Found 8 external assets in category patches
14.7.2022 08:59:13 [Notification] Found 42 external assets in category config
14.7.2022 08:59:13 [Notification] Found 24 external assets in category worldproperties
14.7.2022 08:59:13 [Notification] Found 327 external assets in category sounds
14.7.2022 08:59:13 [Notification] Found 2671 external assets in category shapes
14.7.2022 08:59:13 [Notification] Found 11 external assets in category shaders
14.7.2022 08:59:13 [Notification] Found 0 external assets in category shaderincludes
14.7.2022 08:59:13 [Notification] Found 4475 external assets in category textures
14.7.2022 08:59:13 [Notification] Found 63 external assets in category music
14.7.2022 08:59:13 [Notification] Found 17 external assets in category dialog
14.7.2022 08:59:13 [Notification] Found 0 external assets in category compatibility
14.7.2022 08:59:13 [Notification] Reloaded lang file now with mod assets
14.7.2022 08:59:13 [Notification] JsonPatch Loader: 23 patches total, successfully applied 6 patches, unmet conditions on 1 patches, no issues
14.7.2022 08:59:14 [Notification] Received 2408 item types from server
14.7.2022 08:59:14 [Notification] Loaded 8470 block types from server
14.7.2022 08:59:14 [Notification] Reloaded sounds, now with mod assets
14.7.2022 08:59:14 [Notification] Composed 1 4096x4096 entities texture atlases from 184 textures (last textureid = 196)
14.7.2022 08:59:15 [Notification] Collected 1573 shapes to tesselate.
14.7.2022 08:59:15 [Notification] Composed 1 4096x4096 items texture atlases from 1232 textures (last textureid = 197)
14.7.2022 08:59:16 [Notification] Server launched
14.7.2022 08:59:16 [Notification] Composed 1 4096x4096 blocks texture atlases from 3836 textures (last textureid = 198)
14.7.2022 08:59:16 [Notification] Server assets loaded
14.7.2022 08:59:16 [Notification] Loaded Shaderprogramm for render pass anvilworkitem.
14.7.2022 08:59:16 [Notification] Loaded Shaderprogramm for render pass lines.
14.7.2022 08:59:16 [Notification] Loaded Shaderprogramm for render pass aurora.
14.7.2022 08:59:16 [Notification] Loaded Shaderprogramm for render pass rift.
14.7.2022 08:59:16 [Notification] Loaded Shaderprogramm for render pass machinegear.
14.7.2022 08:59:16 [Notification] Loaded Shaderprogramm for render pass sleepoverlay.
14.7.2022 08:59:16 [Notification] Started 48 systems on Client:
14.7.2022 08:59:16 [Notification]     Mod 'VSEssentials.dll' (game):
14.7.2022 08:59:16 [Notification]         Vintagestory.ServerMods.Core
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.EntityPartitioning
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.ErrorReporter
14.7.2022 08:59:16 [Notification]         Vintagestory.ServerMods.ModCompatiblityUtil
14.7.2022 08:59:16 [Notification]         Vintagestory.ServerMods.NoObf.ModJsonPatchLoader
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.FallingBlockParticlesModSystem
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.CharacterExtraDialogs
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.EntityNameTagRendererRegistry
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.POIRegistry
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.RoomRegistry
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.WeatherSystemCommands
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.WeatherSystemClient
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.WorldMapManager
14.7.2022 08:59:16 [Notification]         Vintagestory.ServerMods.LoadColorMaps
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.ClothManager
14.7.2022 08:59:16 [Notification]     Mod 'VSSurvivalMod.dll' (survival):
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.SaplingControl
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.SurvivalCoreSystem
14.7.2022 08:59:16 [Notification]         Vintagestory.ServerMods.GenFromHeightmap
14.7.2022 08:59:16 [Notification]         Vintagestory.ServerMods.GenMaps
14.7.2022 08:59:16 [Notification]         Vintagestory.ServerMods.DebugSystem
14.7.2022 08:59:16 [Notification]         Vintagestory.ServerMods.UpgradeTasks
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.MyceliumSystem
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.ModSystemAuction
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.ModSystemHandbook
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.LiquidItemStackRenderer
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.CharacterSystem
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.FruitingSystem
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.ModSystemRifts
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.ModSystemRiftWeather
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.ModTemperature
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.SystemTemporalStability
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.MealMeshCache
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.ModSystemWearableStats
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.ModSystemBlockReinforcement
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.ChiselBlockModelCache
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.TemporalStabilityEffects
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.ModJournal
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.ModLootRandomizer
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.ModSleeping
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.TeleporterManager
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.Mechanics.MechanicalPowerMod
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.TradeHandbookInfo
14.7.2022 08:59:16 [Notification]         Vintagestory.ServerMods.GenStructures
14.7.2022 08:59:16 [Notification]         Vintagestory.ServerMods.GenStructuresPosPass
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.RecipeRegistrySystem
14.7.2022 08:59:16 [Notification]         Vintagestory.GameContent.TraderOutfits
14.7.2022 08:59:16 [Notification]     Mod 'VSCreativeMod.dll' (creative):
14.7.2022 08:59:16 [Notification]         Vintagestory.ServerMods.Core
14.7.2022 08:59:16 [Notification]         Vintagestory.ServerMods.WorldEdit.WorldEdit
14.7.2022 08:59:17 [Notification] Loading shaders...
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass standard.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass particlescube.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass particlesquad.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass sky.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass nightsky.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass woittest.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass helditem.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass decals.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass final.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass gui.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass blur.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass findbright.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass godrays.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass autocamera.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass wireframe.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass entityanimated.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass luma.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass blit.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass texture2texture.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass celestialobject.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass colorgrade.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass guigear.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass ssao.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass grass.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass flowers.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass shadowgrass.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass shadowflowers.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass anvilworkitem.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass lines.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass aurora.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass rift.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass machinegear.
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass sleepoverlay.
14.7.2022 08:59:17 [Notification] Reloaded shaders now with mod assets
14.7.2022 08:59:17 [Notification] Processed server identification
14.7.2022 08:59:17 [Notification] Map initialized
14.7.2022 08:59:17 [Notification] Blocks tesselated
14.7.2022 08:59:17 [Notification] Received level init
14.7.2022 08:59:17 [Notification] Loaded Shaderprogramm for render pass instanced.
14.7.2022 08:59:17 [Notification] Loading world map cache db...
14.7.2022 08:59:17 [Notification] Initialized Music Engine
14.7.2022 08:59:17 [Notification] Texture size is 32 so decal atlas size of 128x128 should suffice
14.7.2022 08:59:18 [Notification] Received level finalize
14.7.2022 08:59:18 [Notification] Loaded Shaderprogramm for render pass clouds.
14.7.2022 08:59:30 [Notification] Finished fully loading sounds (async)
14.7.2022 09:00:03 [Fatal] Game Version: v1.17.0-pre.3 (Unstable)
Loaded Mods: game@1.17.0-pre.3, creative@1.17.0-pre.3, survival@1.17.0-pre.3
7/14/2022 9:00:03 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemWearable.OnCreatedByCrafting(ItemSlot[] allInputslots, ItemSlot outputSlot, GridRecipe byRecipe)
   at Vintagestory.Common.InventoryCraftingGrid.FindMatchingRecipe()
   at Vintagestory.API.Common.InventoryBase.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack)
   at Vintagestory.API.Common.ItemSlot.OnItemSlotModified(ItemStack sinkStack)
   at Vintagestory.API.Common.ItemSlot.ActivateSlotRightClick(ItemSlot sourceSlot, ItemStackMoveOperation& op)
   at Vintagestory.API.Common.InventoryBase.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op)
   at Vintagestory.Common.InventoryCraftingGrid.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse)
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs)
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 800
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
-------------------------------
Crash written to file at "C:\Users\erica\AppData\Roaming\VintagestoryData\Logs\client-crash.txt"

14.7.2022 09:00:03 [Notification] Exiting game now. Server running=True. Exit reason: Game crashed
```
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/9113492/client-main.txt)

**Comment by Craluminum2413** [comment]
I reproduce that, it will crash on second pelt here
![image](https://user-images.githubusercontent.com/69315569/179489164-c9f76499-7c2d-4a92-954a-6cb34eb7fcd4.png)

**Comment by tyronx** [comment]
I assume its fixed in pre.5, otherwise please reopen
