### ISSUE TITLE
v1.17.0-pre.4 crashes on start with mod: carrycapacity@0.6.5

### ISSUE THREAD

**Issue by Kagesh** [anegostudios/VintageStory-Issues#2017]
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-pre.4 (Unstable)
Loaded Mods: game@1.17.0-pre.4, carrycapacity@0.6.5, creative@1.17.0-pre.4, survival@1.17.0-pre.4
7/15/2022 3:49:47 PM: Critical error occurred
System.MissingMethodException: Method not found: 'Vintagestory.API.Common.Block Vintagestory.API.Common.IBlockAccessor.GetBlock(Vintagestory.API.MathTools.BlockPos)'.
   at CarryCapacity.Common.CarryHandler.OnGameTick(Single deltaTime)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\EventManager.cs:line 106
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1200
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1104
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 125
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 666
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 610
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 132
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 87
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/20/2022 10:42:14 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2141744315486943026, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Mark\AppData\Local\Temp\RDR97B4.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9842.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9872.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9880.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER98BF.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 512daf53-f158-44cb-80d3-fb23a4e8b78d
Report Status: 268435456
Hashed bucket: 5ba4867f167f40b4adb9011b844fb732
Cab Guid: 0 }
--------------
{ TimeGenerated = 5/21/2022 10:37:33 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1169322480264892805, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Mark\AppData\Local\Temp\RDR9ABD.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9B3B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9B5B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9B68.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9BA8.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 0f3a6786-9524-4eb9-94d3-06d87f997389
Report Status: 268435456
Hashed bucket: 66b2146b18168122903a4499b8115185
Cab Guid: 0 }
--------------
{ TimeGenerated = 3/22/2022 9:20:15 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1404892564174130458, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.4.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Mark\AppData\Local\Temp\RDRD79D.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD81B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD84B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD859.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD898.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: ad8d93dd-3fec-403d-8587-1970ce5331c0
Report Status: 268435456
Hashed bucket: 7bdc35654b5a35c0737f2e57fb2fcd1a
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
1.17.0-pre.4 changed something in the code, thus, all modders that use certain methods should update their mods

**Comment by copygirl** [comment]
This is technically a mod issue, but I've addressed it with the team to see if they could revert this change as I have some problems with the current API anyway, and it's not a change that should have broken these mods. However, due to the nature of this issue it is not technically a bug within the game.

Either the next version of game will have the change reverted, and mods will work again, or us modders will have to re-compile our mods to fix the issue from our end.
