### ISSUE TITLE
Game crashes when I sleep, and compost barrel ticks

### ISSUE THREAD

**Issue by TheOtherEricSchmidt** [anegostudios/VintageStory-Issues#2021]
```
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.0-pre.5 (Unstable)
Loaded Mods: game@1.17.0-pre.5, prospectorinfo@3.1.2, creative@1.17.0-pre.5, survival@1.17.0-pre.5
7/18/2022 1:51:57 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockBarrel.getContentMesh(ItemStack stack, BlockPos forBlockPos, String shapefilename) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:line 208
   at Vintagestory.GameContent.BlockBarrel.GenMesh(ItemStack contentStack, ItemStack liquidContentStack, Boolean issealed, BlockPos forBlockPos) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:line 152
   at Vintagestory.GameContent.BlockEntityBarrel.GenMesh() in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BEBarrel.cs:line 320
   at Vintagestory.GameContent.BlockEntityBarrel.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BEBarrel.cs:line 292
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Model\ClientChunk.cs:line 409
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1138
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 123
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 664
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 608
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 125
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 87
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/7/2022 9:12:32 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2177858694758095880, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\erica\AppData\Local\Temp\RDRED79.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERED8A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREDAA.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREDC7.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREDE8.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 96753d98-ecb2-4086-af69-5e194db60b1b
Report Status: 268435456
Hashed bucket: cd7dc5185a521ef09e394ef1b00d5c08
Cab Guid: 0 }

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/9135720/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/9135723/server-main.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/9135729/client-crash.txt)

**Comment by TheOtherEricSchmidt** [comment]
Nope, nothing with my barrels, only have 4 and really only have 1 with anything in it....
I can no longer sleep on this save, crashes when I wake up after sleeping. 
Log without mod just in case

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.0-pre.5 (Unstable)
Loaded Mods: game@1.17.0-pre.5, creative@1.17.0-pre.5, survival@1.17.0-pre.5
7/18/2022 2:07:27 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockBarrel.getContentMesh(ItemStack stack, BlockPos forBlockPos, String shapefilename) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:line 208
   at Vintagestory.GameContent.BlockBarrel.GenMesh(ItemStack contentStack, ItemStack liquidContentStack, Boolean issealed, BlockPos forBlockPos) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:line 152
   at Vintagestory.GameContent.BlockEntityBarrel.GenMesh() in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BEBarrel.cs:line 320
   at Vintagestory.GameContent.BlockEntityBarrel.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BEBarrel.cs:line 292
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Model\ClientChunk.cs:line 409
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1138
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 123
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 664
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 608
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 125
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 87
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/7/2022 9:12:32 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2177858694758095880, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\erica\AppData\Local\Temp\RDRED79.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERED8A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREDAA.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREDC7.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREDE8.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 96753d98-ecb2-4086-af69-5e194db60b1b
Report Status: 268435456
Hashed bucket: cd7dc5185a521ef09e394ef1b00d5c08
Cab Guid: 0 }


[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/9135813/server-main.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/9135815/client-main.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/9135816/client-debug.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/9135817/client-crash.txt)

**Comment by TheOtherEricSchmidt** [comment]
I have a composting barrel that when it clicks over to 20 0days crashes...

https://clips.twitch.tv/SecretiveSuspiciousClipsdadSoBayed-ovK1WmtShIuOmILr

**Comment by Craluminum2413** [comment]
Okay, I reproduced that in superflat world

**Comment by Saricane** [comment]
Same crash with barrel.
The barrel is present, but invisible. I can retrieve the prepared hides. This makes the barrel become visible again. When I try to place the prepared hides in another barrel with strong tannin, the game crashes.

**Comment by Void-Seeker** [comment]
I have this crash when trying to place oak logs into the barrel.
