### ISSUE TITLE
Undefined Entity Health causing Fatal Server NullReferenceException error when damaged by Lava

### ISSUE THREAD

**Issue by Snailic** [anegostudios/VintageStory-Issues#2029]
**Game Version:** 1.16.5 
**Platform:** Windows 
**Modded:** Yes (Ran into this with CoB Server Exclusives but applies to any mod)
**SP/MP:** Both (Causes internal server to hang for SP/MP)

### Description
Modded Entity without a defined health value causes the server to hang when damaged. Server hangs for the entire duration something is ticking damage.

### How to reproduce
1. Make a custom EntityAgent entity
2. Don't define server.behaviors.health in the entity.json (or comment it out for testing)
3. Have the entity touch lava

### Expected behavior
Entity ignores damage (effectively invulnerable at least that's what the usecase is intended for CoB Server Exclusives) or dies to any damage > 0.

### Screenshots
Tested by commenting out the HP value in another mod's file.
![image](https://user-images.githubusercontent.com/6479130/180189779-a8ff16d6-0f33-4ded-b513-75eb109db1c9.png)

### Logs
```
[Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorEmotionStates.OnEntityReceiveDamage(DamageSource damageSource, Single& damage)
   at Vintagestory.API.Common.Entities.Entity.ReceiveDamage(DamageSource damageSource, Single damage)
   at Vintagestory.GameContent.BlockLava.OnEntityInside(IWorldAccessor world, Entity entity, BlockPos pos)
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.DisplaceWithBlockCollision(EntityPos pos, EntityControls controls, Single dt)
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.TickEntityPhysics(EntityPos pos, EntityControls controls, Single dt)
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.TickEntityPhysicsPre(Entity entity, Single dt)
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.onPhysicsTick(Single deltaTime)
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.OnGameTick(Single deltaTime)
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt)
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt)
   at Vintagestory.Server.ServerMain.Process()
```

**Comment by Craluminum2413** [comment]
Does this apply to lava only or to any damage source?

**Comment by Snailic** [comment]
Applies to any damage source. Actually doesn't straight up crash the server, its just that when something hits lava it causes the server to hang while the thing is in lava.

```[Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorEmotionStates.OnEntityReceiveDamage(DamageSource damageSource, Single& damage)
   at Vintagestory.API.Common.Entities.Entity.ReceiveDamage(DamageSource damageSource, Single damage)
   at Vintagestory.GameContent.BlockLava.OnEntityInside(IWorldAccessor world, Entity entity, BlockPos pos)
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.DisplaceWithBlockCollision(EntityPos pos, EntityControls controls, Single dt)
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.TickEntityPhysics(EntityPos pos, EntityControls controls, Single dt)
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.TickEntityPhysicsPre(Entity entity, Single dt)
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.onPhysicsTick(Single deltaTime)
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.OnGameTick(Single deltaTime)
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt)
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt)
   at Vintagestory.Server.ServerMain.Process()```
