### ISSUE TITLE
Chiseling created an invisible block that crashes the client when touched

### ISSUE THREAD

**Issue by Pontenerd** [anegostudios/VintageStory-Issues#2040]
**Game Version:** X.Y.Z  
**Platform:** Windows 
**Modded:** No /
**SP/MP:**  Multiplayer 

### Description
(making this report as a third party) Was doing some sculpting with a chisel on basalt cobblestone, which then created an invisible object which crashed the client when touched
### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Logs

Paste crash between the triple backticks.
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.5 (Stable)
Loaded Mods: game@1.16.5, creative@1.16.5, survival@1.16.5
23/07/2022 07:01:06: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.Client.NoObf.SystemRenderDecals.UpdateDecal(BlockDecal decal)
   at Vintagestory.Client.NoObf.SystemRenderDecals.AddBlockBreakDecal(BlockPos pos, Int32 stage)
   at Vintagestory.Client.NoObf.SystemRenderDecals.OnPlayerBreakingBlock(_dUMdSRYWwkPRAgCF1VLBqj7zle3 blockDamage)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockBreaking(_dUMdSRYWwkPRAgCF1VLBqj7zle3 blockDamage)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _esGsESICkihAc8ShXuIoQwZFwP4._DPQfPEsBXX5ftH8l1sqqtyB2Itl(Single )
   at _8UC8FAMhwKY89IbtSRDjsNSApPJ._KbwUAfxjCHyIG0aK445AAA9FHl5(Single )
   at _8UC8FAMhwKY89IbtSRDjsNSApPJ._R0wAt2N0TpONMxGD0HJG3bDrRcI(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._vvUTh6X5xLRNnjtX2xSE7z8yMeh(_SUsdg1ytavxaRcNNkhfDrODGhGP , String[] )
   at _yA4PJazdKq1OMm8H6js6v5AhQB._vvUTh6X5xLRNnjtX2xSE7z8yMeh(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 02/07/2022 01:28:22, Site = , Source = Windows Error Reporting, Message = Fault bucket 1381417961401207149, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\owalt\AppData\Local\Temp\RDRBD3F.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBD4F.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBD60.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBD6D.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBD9D.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 9ea358d8-ab9b-4134-9daa-069b680cc321
Report Status: 268435456
Hashed bucket: 6ce2bbf81ba2523d132bc8511ba9c96d
Cab Guid: 0 }
```
In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by tyronx** [comment]
hey, thanks for the report, is it reproducible by any chance?

**Comment by Pontenerd** [comment]
> hey, thanks for the report, is it reproducible by any chance?

Yes, we had this issue crop up a few times, although I am unsure how to do so, appologies

**Comment by Craluminum2413** [comment]
Closing due to inactivity
