### ISSUE TITLE
Unexpected server crash

### ISSUE THREAD

**Issue by TarikYuzkiv** [anegostudios/VintageStory-Issues#2043]
**Game Version:** v1.17.0-pre.5 (Unstable)
**Platform:** Windows
**Modded:** No
**SP/MP:** Multiplayer

Unfortunately idk what are players did at this time, server just turned off after this...

```
23.7.2022 18:57:14 [Fatal] Caught unhandled exception in pathfinding thread.
23.7.2022 18:57:14 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockBookShelf.GetTypeProps(String code, ItemStack stack, BlockEntityShapeFromAttributes be) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Block\BlockBookshelf.cs:line 228
   at Vintagestory.GameContent.BlockShapeFromAttributes.GetCollisionBoxes(IBlockAccessor blockAccessor, BlockPos pos) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Block\BlockShapeFromAttributes.cs:line 250
   at Vintagestory.API.MathTools.CollisionTester.GetCollidingBlock(IBlockAccessor blockAccessor, Cuboidf entityBoxRel, Vec3d pos, Boolean alsoCheckTouch)
   at Vintagestory.Essentials.AStar.traversable(PathNode node, Single stepHeight, Int32 maxFallHeight, Cuboidf entityCollBox, Cardinal fromDir, Single& extraCost) in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Entity\Pathfinding\Astar\AStar.cs:line 130
   at Vintagestory.Essentials.AStar.FindPath(BlockPos start, BlockPos end, Int32 maxFallHeight, Single stepHeight, Cuboidf entityCollBox, Int32 searchDepth, Int32 mhdistanceTolerance) in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Entity\Pathfinding\Astar\AStar.cs:line 87
   at Vintagestory.Essentials.PathfindingAsync.ProcessQueue(AStar astar, Int32 maxCount) in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Entity\Pathfinding\PathfindingAsync.cs:line 124
   at Vintagestory.Essentials.PathfindingAsync.SeparateThreadLoop() in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Entity\Pathfinding\PathfindingAsync.cs:line 71
23.7.2022 18:57:14 [Event] Игрок Footer исключен. Причина: Server shutting down - Shutdown through Server API
23.7.2022 18:57:14 [Event] Игрок Almos исключен. Причина: Server shutting down - Shutdown through Server API
23.7.2022 18:57:14 [Event] Игрок lilac исключен. Причина: Server shutting down - Shutdown through Server API
23.7.2022 18:57:14 [Event] Игрок Sosatelb исключен. Причина: Server shutting down - Shutdown through Server API
23.7.2022 18:57:14 [Event] Игрок RIVALLIF исключен. Причина: Server shutting down - Shutdown through Server API
23.7.2022 18:57:14 [Event] Игрок necafjf исключен. Причина: Server shutting down - Shutdown through Server API
23.7.2022 18:57:14 [Notification] Last player disconnected, compacting large object heap...
23.7.2022 18:57:15 [Event] Игрок VladimirHack исключен. Причина: Server shutting down - Shutdown through Server API
23.7.2022 18:57:15 [Notification] Server stop requested, begin shutdown sequence. Stop reason: Shutdown through Server API
```

**Comment by tyronx** [comment]
ooof lol. A creature tried to step on an invalid bookshelf it seems. Not sure how it came to that in the first place, but it should no longer crash on next release. Thanks for the report.
