### ISSUE TITLE
Crash after "Validating server"

### ISSUE THREAD

**Issue by Ribky** [anegostudios/VintageStory-Issues#206]
Crashing on startup.  This wasn't an issue earlier this morning and it ran just fine.  

Here's the error report.
```
Running on 64 bit Windows with 8GB RAM 
Version: 1.7.3 Survival Mode Edition (Stable)10/7/2018 4:55:50 PM: Critical error occurred
System.MissingMethodException: Method not found: 'Void System.Runtime.GCSettings.set_LargeObjectHeapCompactionMode(System.Runtime.GCLargeObjectHeapCompactionMode)'.
   at _IDKV09UOS7vd8flimq5x2lP7DOA._NkNUQSFA6LSBHixz7Low20pSFIb(Single )
   at _jB8PGkZvmV1MEwf9s1dsMllbcU._Sm1veUsokjm2ejTDBUYCBk9VL0(Single )
   at _jB8PGkZvmV1MEwf9s1dsMllbcU._3TvLi6o9q5EoUtV9FkGVbix5cCh(Single )
   at _UHOboDhqFr8kkxnQcdyFGkcIt2T._RvX0NZRecQaIiKbPLFlG7yTFbqV(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _veX1k27ELMT3YEQeuy3VRTN4yRb._kzSkvioOdlPvAytfREVDL8TchXc(_O2vbPFDX8XrsU0KZbWpNtJoa8sy , String[] )
   at _ggZEaGVfcLlJoMgWF2gpbmwaE3z._kzSkvioOdlPvAytfREVDL8TchXc(ThreadStart )
```

**Comment by tyronx** [comment]
Hm, thats highly unusual.  Could it be that your .net framework is outdated? You can get the latest (.net framework 4.7.2) one here: https://www.microsoft.com/net/download

Alternatively you should be able to avoid the bug from triggering by unchecking the optimize ram setting.

**Comment by tyronx** [comment]
No feedback supplied in 2 months. Closing issue.
