### ISSUE TITLE
Client crashing when loading into specific server grid

### ISSUE THREAD

**Issue by GamerRaven81** [anegostudios/VintageStory-Issues#2064]
We think its being caused by the placement of a ladder and bed? We're unsure what to do

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.5 (Stable)
Loaded Mods: backpackpack@1.0.3, bears@1.0.1, dragonflies@1.2.0, expandedfoods@1.5.4, FlexibleTools@1.3.1, juicyores@1.0.0, potatoes@1.0.8, moreroads@1.4.3, orepulverizer@1.1.1, primitivesurvival@2.9.5, sortablestorage@1.0.3, game@1.16.5, zeekea@1.6.1, zoombuttonreborn@1.2.0, egocaribautomapmarkers@2.3.0, captureanimals@2.1.1, carrycapacity@0.6.5, coinage@1.0.0-pre.9, extraoverlays@1.1.0, hudclock@2.7.0, outlawmod@1.1.4, petai@1.4.4, playercorpse@1.3.2, prospectorinfo@3.1.2, stonequarry@2.0.0-pre.5, creative@1.16.5, survival@1.16.5, vsvillage@0.0.6, xlib@0.6.9, xrowboat@0.0.3, metalrecovery@0.1.17, cats@1.4.5, compatibilityfix@1.0.0, feverstonehorses@1.2.8, floating-landmasses@1.0.5, foxtaming@1.0.0-pre.1, packanimals@1.0.1, wolftaming@1.4.2, xskills@0.6.9, bricklayers@0.9.2
7/29/2022 1:13:32 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityBed.get_MountPosition()
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.TickEntityPhysics(EntityPos pos, EntityControls controls, Single dt)
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.TickEntityPhysicsPre(Entity entity, Single dt)
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.onPhysicsTick(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _esGsESICkihAc8ShXuIoQwZFwP4._lPY9uZeagiMGC6tvSE11dF7naaz(Single )
   at _8UC8FAMhwKY89IbtSRDjsNSApPJ._KbwUAfxjCHyIG0aK445AAA9FHl5(Single )
   at _8UC8FAMhwKY89IbtSRDjsNSApPJ._R0wAt2N0TpONMxGD0HJG3bDrRcI(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._vvUTh6X5xLRNnjtX2xSE7z8yMeh(_SUsdg1ytavxaRcNNkhfDrODGhGP , String[] )
   at _yA4PJazdKq1OMm8H6js6v5AhQB._vvUTh6X5xLRNnjtX2xSE7z8yMeh(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/29/2022 1:13:34 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2005454861689089211, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 625674b5
P4: KERNELBASE.dll
P5: 10.0.22000.795
P6: 960371d1
P7: c0020001
P8: 000000000004474c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a3422f41-d6d3-493e-89b2-a10b312fe0d5.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.10878f34-0b0a-47b8-bfc4-378abb6cc28d.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.aa70f2c2-16ce-4f31-83e2-d83d5c88bcf1.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.30a084a9-ce63-491e-9a1a-82437b2546d4.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.179476e7-ba2c-4b05-b4f9-257c8c797618.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_ccb71dc766c471a29dbb957b99197869ad9887d_1f70e3ae_a3ef285c-8117-4fcd-8c09-6f48c4fc90df

Analysis symbol: 
Rechecking for solution: 0
Report Id: f1d27aa1-62c1-4858-bc12-a565c94bcbaf
Report Status: 268435456
Hashed bucket: bcd29b714892a18c8bd4ce92440eecbb
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/29/2022 1:13:33 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.16.5.0, time stamp: 0x625674b5
Faulting module name: KERNELBASE.dll, version: 10.0.22000.795, time stamp: 0x960371d1
Exception code: 0xc0020001
Fault offset: 0x000000000004474c
Faulting process id: 0x43f0
Faulting application start time: 0x01d8a309b0f09580
Faulting application path: F:\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: f1d27aa1-62c1-4858-bc12-a565c94bcbaf
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 7/29/2022 1:13:32 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FF89F44474C
Stack:
 }

**Comment by Craluminum2413** [comment]
Closing due to inactivity
