### ISSUE TITLE
Server stopped working

### ISSUE THREAD

**Issue by TarikYuzkiv** [anegostudios/VintageStory-Issues#2085]
**Game Version:** v1.17.0-rc.3
**Platform:** Windows
**Modded:** No
**SP/MP:** Multiplayer

Unfortunately, I don't know what the players did before that.
The entire console was be full with this error, it was impossible to connect to the server.

```
1.8.2022 22:18:07 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorBodyTemperature.OnGameTick(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Entity\Behavior\BehaviorBodyTemperature.cs:line 204
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt)
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt)
   at Vintagestory.Server.ServerMain.Process()
1.8.2022 22:18:07 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorBodyTemperature.OnGameTick(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Entity\Behavior\BehaviorBodyTemperature.cs:line 204
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt)
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt)
   at Vintagestory.Server.ServerMain.Process()
1.8.2022 22:18:07 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorBodyTemperature.OnGameTick(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Entity\Behavior\BehaviorBodyTemperature.cs:line 204
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt)
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt)
   at Vintagestory.Server.ServerMain.Process()
```

**Comment by TarikYuzkiv** [comment]
And again...
Now on another server and with stable 1.17.3.

**Comment by Craluminum2413** [comment]
Closing due to inactivity
