### ISSUE TITLE
Crash on trying to open handbook page for any pie

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#2109]
**Game Version:** 1.17.0-rc.5
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Open creative inventory
2. Search for "pie"
3. Hover over any pie there and press "H" to open handbook page for it
4. It crashed

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-rc.5 (Unstable)
Loaded Mods: game@1.17.0-rc.5, creative@1.17.0-rc.5, survival@1.17.0-rc.5
08/10/2022 13:22:33: Critical error occurred
System.Exception: Can't create itemstack without item!
   at Vintagestory.API.Common.ItemStack..ctor(Item item, Int32 stacksize) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Collectible\ItemStack.cs:line 213
   at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.GetHandbookInfo(ItemSlot inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Handbook\CollectibleBehaviorHandbookTextAndExtraInfo.cs:line 923
   at Vintagestory.GameContent.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 110
   at Vintagestory.GameContent.GuiDialogHandbook.initDetailGui() in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 256
   at Vintagestory.GameContent.GuiDialogHandbook.OpenDetailPageFor(String pageCode) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 320
   at Vintagestory.GameContent.ModSystemHandbook.OnHelpHotkey(KeyCombination key) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Handbook\Handbook.cs:line 70
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean isGlobal, Boolean fallBack) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\HotkeyManager.cs:line 365
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 2169
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(Object sender, KeyboardKeyEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\Input.cs:line 251
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnKeyDown(Key key, Boolean repeat) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\NativeWindowBase.cs:line 130
   at OpenTK.Platform.Windows.WinGLNative.HandleKeyboard(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 646
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 828
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 87
```

**Comment by mrgeoffkat** [comment]
Can confirm, just had this happen in my own MP server, and I tested in SP (1.17rc5).  

My own crash log: 

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-rc.5 (Unstable)
Loaded Mods: betterdrifters@2.1.3, game@1.17.0-rc.5, egocaribautomapmarkers@2.4.0-pre.1, carrycapacity@0.6.5, prospectorinfo@3.2.0, creative@1.17.0-rc.5, survival@1.17.0-rc.5
8/11/2022 8:27:58 PM: Critical error occurred
System.Exception: Can't create itemstack without item!
   at Vintagestory.API.Common.ItemStack..ctor(Item item, Int32 stacksize) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Collectible\ItemStack.cs:line 213
   at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.GetHandbookInfo(ItemSlot inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Handbook\CollectibleBehaviorHandbookTextAndExtraInfo.cs:line 923
   at Vintagestory.GameContent.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 110
   at Vintagestory.GameContent.GuiDialogHandbook.initDetailGui() in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 256
   at Vintagestory.GameContent.GuiElementFlatList.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Handbook\Gui\GuiElementFlatList.cs:line 119
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 670
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\GuiComposer.cs:line 439
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 564
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 416
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 2288
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\Input.cs:line 230
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 87
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 8/8/2022 9:43:55 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1411415592385249154, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 62ef7eff
P4: KERNELBASE.dll
P5: 10.0.19041.1826
P6: 299341e8
P7: e0434352
P8: 0000000000034fd9
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER796A.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_44ca7959795f34cb687b4cf0c969ffc0c91850e_89e9a2e0_57058d63-1e8f-453d-98bc-dce964fb2844

Analysis symbol: 
Rechecking for solution: 0
Report Id: b4b3217f-4621-431b-a387-7f4414d0f426
Report Status: 268566528
Hashed bucket: 7d466271ec1f17f8b3965b00d691ff82
Cab Guid: 0 }
--------------
{ TimeGenerated = 8/8/2022 9:43:53 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 62ef7eff
P4: KERNELBASE.dll
P5: 10.0.19041.1826
P6: 299341e8
P7: e0434352
P8: 0000000000034fd9
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_44ca7959795f34cb687b4cf0c969ffc0c91850e_89e9a2e0_57058d63-1e8f-453d-98bc-dce964fb2844

Analysis symbol: 
Rechecking for solution: 0
Report Id: b4b3217f-4621-431b-a387-7f4414d0f426
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 8/8/2022 9:43:49 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.0.0, time stamp: 0x62ef7eff
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1826, time stamp: 0x299341e8
Exception code: 0xe0434352
Fault offset: 0x0000000000034fd9
Faulting process id: 0x4434
Faulting application start time: 0x01d8ab918249bdf8
Faulting application path: F:\VintageStory\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: b4b3217f-4621-431b-a387-7f4414d0f426
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by tyronx** [comment]
thanks for the report, should be fixed for next release
