### ISSUE TITLE
Game crashes when putting hide in barrel 

### ISSUE THREAD

**Issue by Tokimimoo** [anegostudios/VintageStory-Issues#2111]

**Comment by Craluminum2413** [comment]
There is nothing in description, what exact version are you using? Is it 1.17.0-rc.5?

**Comment by Craluminum2413** [comment]
Is it 1.17.0-rc.5?

**Comment by Tokimimoo** [comment]
Yes, the last version available

Le jeu. 11 août 2022 à 19:49, Craluminum2413 ***@***.***> a
écrit :

**Comment by Craluminum2413** [comment]
Can you reproduce it and paste crash log into description?

**Comment by Tokimimoo** [comment]
I’ll try if I can but for now I changed versions and mods that I had at the
time :/ sorry for that
Le jeu. 11 août 2022 à 19:56, Craluminum2413 ***@***.***> a
écrit :

**Comment by Saricane** [comment]
Mods ? You should start with no mod, and then add mods 1 by 1 until the game crashes. So you can point the mod responsible for this bug.

**Comment by josyph** [comment]
I had this issue on 1.17-rc.5 as well.  I wish I knew more about coding but here is my error log.  Items still exist in barrels prior to the update, but any state change that occurs to the barrel causes a crash, such as a processing step in leathermaking accruing or trying to place something in the barrel. Here's the log:

 Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-pre.5 (Unstable)
Loaded Mods: armordurability2@1.0.0, buzzwords@1.1.0, chess@1.0.1, composter@1.0.4, fancysky@1.0.4, HangingOilLamps@1.0.1, hideandfabric@1.2.3, moredungeons@0.1.1, RelightTorches@1.0.0, sortablestorage@1.4.0, visibleore@1.0.1, game@1.17.0-pre.5, vsquest@0.0.3, calendar@1.0.0, carrycapacity@0.6.4, jlj@1.0.3, lichen@1.6.1, medievalexpansion@3.7.1, prospectorinfo@3.2.0, creative@1.17.0-pre.5, survival@1.17.0-pre.5, vsvillage@0.2.2
8/12/2022 4:56:12 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockBarrel.getContentMesh(ItemStack stack, BlockPos forBlockPos, String shapefilename) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:line 208
   at Vintagestory.GameContent.BlockBarrel.GenMesh(ItemStack contentStack, ItemStack liquidContentStack, Boolean issealed, BlockPos forBlockPos) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:line 152
   at Vintagestory.GameContent.BlockEntityBarrel.GenMesh() in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BEBarrel.cs:line 320
   at Vintagestory.GameContent.BlockEntityBarrel.Inventory_SlotModified(Int32 slotId) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BEBarrel.cs:line 110
   at Vintagestory.API.Common.InventoryBase.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Inventory\InventoryBase.cs:line 480
   at Vintagestory.API.Common.ItemSlot.OnItemSlotModified(ItemStack sinkStack) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Inventory\ItemSlot.cs:line 418
   at Vintagestory.API.Common.ItemSlotBarrelInput.OnItemSlotModified(ItemStack stack) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Inventory\ItemSlotBarrelInput.cs:line 26
   at Vintagestory.API.Common.InventoryBase.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Inventory\InventoryBase.cs:line 448
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 979
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 772
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 638
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 536
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 394
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 2248
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\Input.cs:line 220
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 792
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 87
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/31/2022 5:34:18 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2141744315486943026, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Joseph\AppData\Local\Temp\RDR52A7.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER52B8.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER52B9.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER52D0.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER52E1.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: b27a5e65-8e21-48d6-9625-a0bb80a84654
Report Status: 268435456
Hashed bucket: 5ba4867f167f40b4adb9011b844fb732
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/27/2022 10:15:23 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1701269864880877238, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 62e01e15
P4: VintagestoryLib
P5: 1.17.0.0
P6: 62e01e15
P7: 1551
P8: 23
P9: System.Exception
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER37B5.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3A07.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3A18.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3A2C.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3A3C.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_b95cc86676a4dab0e8bcf4a820183f1a794_30d1a8e0_1096143b-8d44-4fe9-b868-494774b2bae5

Analysis symbol: 
Rechecking for solution: 0
Report Id: 6290dae1-94c8-49b8-9c06-7b321f735e3f
Report Status: 268435456
Hashed bucket: 238123ade8dbaa27779c1fedab4d2eb6
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/27/2022 10:15:22 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.0.0, time stamp: 0x62e01e15
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1826, time stamp: 0x299341e8
Exception code: 0xe0434352
Fault offset: 0x0000000000034fd9
Faulting process id: 0xcf4
Faulting application start time: 0x01d8a2303323ad15
Faulting application path: D:\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 6290dae1-94c8-49b8-9c06-7b321f735e3f
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
pre.5 is not rc.5, download 1.17.0-rc.5 here https://account.vintagestory.at/
