### ISSUE TITLE
Firepit causing crash upon being re-loaded in area 1.17.0-rc.5

### ISSUE THREAD

**Issue by Desektion** [anegostudios/VintageStory-Issues#2112]
**Game Version:** 1.17.0-rc.5
**Platform:** Windows 
**Modded:** No 
**SP/MP:** Singleplayer 

### Description
I put food or items into the firepit to cook and then leave the area by going a good 300-400 blocks away, upon coming back and getting close to the area where the firepit is, the game crashes.

### How to reproduce
1. Put meat/cattails into a firepit to cook that is currently lit and on fire
2. Leave the area (causing it to unload?)
3. Come back and it will cause a crash

Logs

```
Game Version: v1.17.0-rc.5 (Unstable)
Loaded Mods: game@1.17.0-rc.5, creative@1.17.0-rc.5, survival@1.17.0-rc.5
8/10/2022 11:53:47 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BEBehaviorFirepitAmbient.OnTick3s(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\BlockEntityBehavior\BEBehaviorFirepitAmbient.cs:line 108
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\EventManager.cs:line 105
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1196
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1103
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 123
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 664
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 608
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 125
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 87
```

I think this may be related to another issue with the firepit on issue #2106

**Comment by tyronx** [comment]
added a small change to prevent the crash, but i don't know yet the true cause of it
