### ISSUE TITLE
glitchy behavior when moving crafting grid items using hotbar keybindings  

### ISSUE THREAD

**Issue by wasakoki** [anegostudios/VintageStory-Issues#2116]
**Game Version:** 1.17.0-rc5
**Platform:** Windows   
**Modded:** No
**SP/MP:** both  

### Description
whenever i go to craft a bunch of skeps for my bee farm, i try use the number (hotbar slot) keys to quickly move the skeps from the crafting output to empty slots on my hotbar, however whenever i do this, every other item crafted bugs out the crafting grid and forces me to use mouse inputs to craft the skeps. further testing shows this affects all recipes, and also using "q" (to drop the item on crafting) bugs out with this behavior.

### How to reproduce
1. place the crafting materials to make a bunch of skeps into your crafting grid (or any other recipe)
2. attempt to output the skep recipe onto an empty hotbar slot OR by pressing "q". this will craft the item as expected
3. attempt to output ANOTHER empty skep recipe onto another hotbar slot (or by pressing q). the crafting result will fail, no items are consumed, and the output recipe will disappear from the crafting grid.

### Screenshots
![image](https://user-images.githubusercontent.com/65874132/184463482-6d76fb9f-f248-4f57-8873-beb487a7c76d.png)

**Comment by tyronx** [comment]
hm, not able to reproduce this

**Comment by wasakoki** [comment]
well, i didn't expect it to not be reproducible. i even did a fresh install on my other windows pc and reproduced on my first test. is there any other info i can give in hopes of resolving it? here's a video of what i see when the bug happens for starts
https://user-images.githubusercontent.com/65874132/184494283-874d8b8d-faca-4e3f-b1ea-efdc33faf635.mp4

**Comment by tyronx** [comment]
very strange. can you upload the server-main.txt and client-main.txt please? They are located in %appdata%/VintageStoryData/Logs

**Comment by wasakoki** [comment]
sure, here they are from my other computer (logs are smaller on that one cause i've done nothing with the game except test the bug on it ^^)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/9349113/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/9349114/server-main.txt)

**Comment by wasakoki** [comment]
ok, i found 2 more bugs that involve crafting recipes that (are supposed to) use durability of tools (i.e. firewood, rough-hewn fences, etc.). these issues seem to closely relate to the issue i originally have (if not the same bug manifesting differently) hence why i am posting them here. issue 1: if i craft an item like firewood by outputting the recipe to a hotbar slot, and then click the output recipe with lmb, the game crashes. issue 2: similar to 1, i craft an item like firewood, but i output the recipe by pressing "q" (drop item), this doesn't actually craft the item, but instead drops the item from the crafting output as if it was in item in an inventory container.

### to reproduce issue 1:
1. place the crafting materials to make a bunch of firewood into your crafting grid (other recipes like rough hewn fence works too)
2. attempt to output the firewood recipe onto an empty hotbar slot. this will craft the item as expected
3. attempt to output the firewood recipe by clicking on the output this time. the game will crash.

### to reproduce issue 2:
1. place the crafting materials to make a bunch of firewood into your crafting grid (other recipes like rough hewn fence works too)
2. take note of the amount of logs in your inventory, and your axe's durability.
3. attempt to output the firewood recipe by pressing "q" (drop item). you will notice 3 things: 1. the dropped crafting result is only 1x firewood, not 4x as the recipe entails. 2. your logs and axe durability did not decrease at all. 3. the firewood output changed from "4x firewood" to "3x firewood"
4. repeating step 3 will decrease the crafting output result of firewood each time, and crash the game when you "q" the craft after the 4th attempt (in the case of firewood)

### Logs for issue 1:
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-rc.5 (Unstable)
Loaded Mods: game@1.17.0-rc.5, droparmorondeath@1.0.0, creative@1.17.0-rc.5, survival@1.17.0-rc.5
19-Aug-22 07:29:52: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.ItemSlotCraftingOutput.TryPutInto(ItemSlot sinkSlot, ItemStackMoveOperation& op) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\GameContent\Inventory\ItemSlotCraftingOutput.cs:line 37
   at Vintagestory.API.Common.ItemSlotOutput.ActivateSlot(ItemSlot sourceSlot, ItemStackMoveOperation& op) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Inventory\ItemSlotOutput.cs:line 39
   at Vintagestory.API.Common.InventoryBase.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Inventory\InventoryBase.cs:line 448
   at Vintagestory.Common.InventoryCraftingGrid.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\GameContent\Inventory\InventoryCraftingGrid.cs:line 112
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 979
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 772
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 638
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\GuiComposer.cs:line 459
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnMouseDown(MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 546
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 394
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 2253
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\Input.cs:line 220
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 792
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 87
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 14-Aug-22 19:15:06, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException
   at Vintagestory.Client.NoObf.TextureAtlasManager.ComposeTextureAtlasses_StageC()
   at Vintagestory.Client.NoObf.ClientMain.FinaliseTextureAtlas_StageC(Vintagestory.Client.NoObf.TextureAtlasManager, System.String, System.Action)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 14-Aug-22 11:32:43, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.17.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 750c

Start Time: 01d8afccda34725f

Termination Time: 181

Application Path: E:\installs SSD\Vintagestory\Vintagestory.exe

Report Id: 9d1c266d-6ca5-4562-909f-9252c76215cc

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 14-Aug-22 02:09:37, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FF96D884FD9
Stack:
 }
```

### Logs for Issue 2:
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-rc.5 (Unstable)
Loaded Mods: game@1.17.0-rc.5, droparmorondeath@1.0.0, creative@1.17.0-rc.5, survival@1.17.0-rc.5
19-Aug-22 07:31:14: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.ItemSlotCraftingOutput.TryPutInto(ItemSlot sinkSlot, ItemStackMoveOperation& op) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\GameContent\Inventory\ItemSlotCraftingOutput.cs:line 37
   at Vintagestory.Client.NoObf.ClientPlayerInventoryManager.DropItem(ItemSlot slot, Boolean fullStack) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Util\ClientPlayerInventoryManager.cs:line 95
   at Vintagestory.Client.SystemHotkeys.KeyDropItem(KeyCombination viaKeyComb) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Player\Hotkeys.cs:line 126
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean isGlobal, Boolean fallBack) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\HotkeyManager.cs:line 365
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 2169
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(Object sender, KeyboardKeyEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\Input.cs:line 265
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnKeyDown(Key key, Boolean repeat) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\NativeWindowBase.cs:line 129
   at OpenTK.Platform.Windows.WinGLNative.HandleKeyboard(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 639
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 828
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 87
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 14-Aug-22 19:15:06, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException
   at Vintagestory.Client.NoObf.TextureAtlasManager.ComposeTextureAtlasses_StageC()
   at Vintagestory.Client.NoObf.ClientMain.FinaliseTextureAtlas_StageC(Vintagestory.Client.NoObf.TextureAtlasManager, System.String, System.Action)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 14-Aug-22 11:32:43, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.17.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 750c

Start Time: 01d8afccda34725f

Termination Time: 181

Application Path: E:\installs SSD\Vintagestory\Vintagestory.exe

Report Id: 9d1c266d-6ca5-4562-909f-9252c76215cc

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 14-Aug-22 02:09:37, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FF96D884FD9
Stack:
 }
```

**Comment by wasakoki** [comment]
here's a friend duping copper bits on the same server i reproduced the bug on. for some reason instead of their game crashing after dropping the last bit, the slot gets replaced with dirt instead

https://user-images.githubusercontent.com/65874132/185801794-e3b7ba87-6666-428e-897f-33f7b3e62da7.mp4

**Comment by tyronx** [comment]
thanks for the report, issue 2 should be fixed for 1.17.1

**Comment by wasakoki** [comment]
if it's easier to keep track of the other problems i can open up separate issue trackers for it and close this one, just let me know. (i couldn't really tell if it was the same issue or not at first with all of them involving the crafting grid)

**Comment by tyronx** [comment]
thanks for the report, issue 1 should be fixed as well for 1.17.4
