### ISSUE TITLE
Create/manage or destroy a player group - Crash and inability of invitee to join. 

### ISSUE THREAD

**Issue by Rastrick** [anegostudios/VintageStory-Issues#212]
Messing with private group chat today. Can create, can invite, invited user cannot join. Invalid parameters.
When I tried to disband the channel, I was kicked out of game.

```
Running on 64 bit Windows with 16GB RAM 
Version: 1.7.3 Survival Mode Edition (Stable)10/13/2018 6:33:04 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _ipXVGF3UvRMcO61V6PvivgvUKtD._w0ArzWlXcnC4oA7FakxEg1WzGnL(Single )
   at Vintagestory.API.Client.GuiElementScrollbar.SetNewTotalHeight(Single totalHeight)
   at _ipXVGF3UvRMcO61V6PvivgvUKtD._HKdZukXaAScQAqCz3PdEVyv76WI()
   at _ipXVGF3UvRMcO61V6PvivgvUKtD._B7Yad4jKyZXOoUuISZ29j1nMW2AA(_8ADwahgN3wRwE6xiQ00SC7SBHkd )
   at _lz7Y2rran9lWealIcNnFPhsen8u._qHJYrsnqqQXhf94F7nBB85czfnI(_foI2hCxGcDzKqqjfeABpB6CpNBLA , Single )
   at _foI2hCxGcDzKqqjfeABpB6CpNBLA._URdAXcHFfND81Eof8pdIZJav4euA(Single )
   at _yBerEqrmF1A2pLBr3f3xuktAEsA._xrR6ZX9alCEnpvwvvi3izCbbqYG(Single )
   at _jB8PGkZvmV1MEwf9s1dsMllbcU._Sm1veUsokjm2ejTDBUYCBk9VL0(Single )
   at _jB8PGkZvmV1MEwf9s1dsMllbcU._3TvLi6o9q5EoUtV9FkGVbix5cCh(Single )
   at _UHOboDhqFr8kkxnQcdyFGkcIt2T._RvX0NZRecQaIiKbPLFlG7yTFbqV(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _veX1k27ELMT3YEQeuy3VRTN4yRb._kzSkvioOdlPvAytfREVDL8TchXc(_O2vbPFDX8XrsU0KZbWpNtJoa8sy , String[] )
   at _ggZEaGVfcLlJoMgWF2gpbmwaE3z._kzSkvioOdlPvAytfREVDL8TchXc(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 9/28/2018 2:45:21 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 0000000065D3D0F0
 }
{ TimeGenerated = 9/28/2018 12:37:56 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Graphics.OpenGL.GL.DrawElements(OpenTK.Graphics.OpenGL.PrimitiveType, Int32, OpenTK.Graphics.OpenGL.DrawElementsType, Int32)
   at _12z3llz2Ih13PLLq0DDWmg00ZTf._si8N8xHfiqP6H43XtajI3JSP5mD(Vintagestory.API.Client.MeshRef)
   at Vintagestory.GameContent.EntityShapeRenderer.DoRender3DOpaqueBatched(Single, Boolean)
   at _OqTIr4dzUfbxDIwbBdInvYjJsmo._MyutoLtch81DGVYKdNGelbKhFFc(Single)
   at _6BrWdlQQJzOiXRuLAeH7zh8oniG._axMCH9jJ5mxl0dMGmc11e3UMD6I(Vintagestory.API.Client.EnumRenderStage, Single)
   at _wc67swsNdWMJdQYLX0qMRazG5eJ._axMCH9jJ5mxl0dMGmc11e3UMD6I(Vintagestory.API.Client.EnumRenderStage, Single)
   at _wc67swsNdWMJdQYLX0qMRazG5eJ._zBCypqIzbqVtxltVJ5JZpEFprkA(Single)
   at _wc67swsNdWMJdQYLX0qMRazG5eJ._cAv7xQ11hcLBJGDmE090mm1OMJp(Single)
   at _wm0Hlhxs3bgUDGpNDepmY8mRGlg._hKlPHuToDIfTeNGPyG8fDVzJkij(Single)
   at _oNrpzUsvtbzft674AAen5Ezu9LD._BC9ZAlV4eVMGR1X4bflUhXnKsqd(Single)
   at _oNrpzUsvtbzft674AAen5Ezu9LD._MYGbyOgB8YbGCLfjhSzUGtvMYsE(Single)
   at _12z3llz2Ih13PLLq0DDWmg00ZTf._PPv1Z4M6jGMXogBldn9iOa7l4TN(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _fLmmDbZYjY0sNfaZvFsVCB7n4Kd._ojSCEfHKsaoJXnEPci0YlQPhugB(_9VRnweNDgKXKxDaGFibNnY74hZoA, System.String[])
   at _ljlkvsUodPVcR4V8rKWapbcTC0t._ojSCEfHKsaoJXnEPci0YlQPhugB(System.Threading.ThreadStart)
   at _fLmmDbZYjY0sNfaZvFsVCB7n4Kd._H5mDDjtdI7hMcAEWuvA85N3bVbyA(System.String[])

 }
{ TimeGenerated = 9/26/2018 10:01:39 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 000000005FFEF430
 }
```

**Comment by tyronx** [comment]
Could you supply me with the exact sequence of commands to produce this crash please? A quick disband test did not result in a crash for me.

**Comment by tyronx** [comment]
No feedback supplied in over a month. Closing issue.
