### ISSUE TITLE
Fatal error when making and entering 1.17.0 worlds

### ISSUE THREAD

**Issue by ChrisAE123** [anegostudios/VintageStory-Issues#2145]
Game Version: 1.17.0
Platform: Windows
Modded: No
Singleplayer 

 Game runs fine but every 1.17.0 world I make and enter will produce a fatal error.

Logs
31.8.2022 14:46:35 [Fatal] Exception in async LoadSounds thread:
31.8.2022 14:46:35 [Fatal] System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at Vintagestory.Client.ScreenManager.LoadSoundsSlow(ClientMain game) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 448
   at Vintagestory.Client.LoadSoundsThread.ProcessSlow() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 1244

**Comment by tyronx** [comment]
thanks for the report, should be fixed in 1.17.1
