### ISSUE TITLE
Client crash while browsing survival guide about honey

### ISSUE THREAD

**Issue by Makaifren** [anegostudios/VintageStory-Issues#2147]
**Game Version:** 1.17.0 (stable) 
**Platform:** Windows
**Modded:** Yes (Workbench Expansion, for duplicating chiseling things)
**SP/MP:** Multiplayer

### Description
Crashed navigating through the survival guide through honey and honey-related recipes.

### How to reproduce
See description.

### Logs
Note that none of the "attached files" listed below appear to exist on my computer, at least not in the folders given.
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/9468297/client-debug.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/9468287/client-crash.txt)
```
Running on 64 bit Windows with 0 GB RAM 
Game Version: v1.17.0 (Stable)
9/1/2022 1:33:05 AM: Critical error occurred
Loaded Mods: game@1.17.0, creative@1.17.0, survival@1.17.0, workbenchexpansion@1.4.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockLiquidContainerBase.OnHandbookRecipeRender(ICoreClientAPI capi, GridRecipe gridRecipe, ItemSlot dummyslot, Double x, Double y, Double z, Double size) in VSSurvivalMod\Systems\Liquid\BlockLiquidContainerBase.cs:line 250
   at Vintagestory.API.Client.SlideshowGridRecipeTextComponent.<>c__DisplayClass9_0.<.ctor>b__0() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\SlideshowGridRecipeTextComponent.cs:line 161
   at Vintagestory.API.Client.GuiElementItemstackInfo.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 225
   at Vintagestory.API.Client.ItemstackComponentBase.RenderItemstackTooltip(ItemSlot slot, Double renderX, Double renderY, Single dt) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\ItemstackComponentBase.cs:line 109
   at Vintagestory.API.Client.SlideshowGridRecipeTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY, Double renderZ) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\SlideshowGridRecipeTextComponent.cs:line 336
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 484
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 709
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 373
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 302
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 201
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1174
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1348
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 202
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 705
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 609
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 125
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 8/14/2022 7:01:56 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1169322480264892805, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
C:\Users\Makaifren\AppData\Local\Temp\RDR21DB.tmp\empty.txt
C:\ProgramData\Microsoft\Windows\WER\Temp\WER21DC.tmp.WERInternalMetadata.xml
C:\ProgramData\Microsoft\Windows\WER\Temp\WER21ED.tmp.xml
C:\ProgramData\Microsoft\Windows\WER\Temp\WER2211.tmp.csv
C:\ProgramData\Microsoft\Windows\WER\Temp\WER2231.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: c6a4a4d0-9f99-4784-9057-6b9628333619
Report Status: 268435456
Hashed bucket: 66b2146b18168122903a4499b8115185
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment]
Fixed in [1.17.1](https://www.vintagestory.at/forums/topic/9392-stable-de-jank-and-game-juice-update-1170/#comment-40175:~:text=Fixed%3A%20Hitting%20%27H%27%20while%20hovering%20water%20bowl%20opened%20the%20page%20on%20the%20honey%20bowl)
