### ISSUE TITLE
Crash on multiple occasions without knowledgeable cause

### ISSUE THREAD

**Issue by Xaeiune** [anegostudios/VintageStory-Issues#2156]
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.2 (Stable)
9/2/2022 7:41:55 PM: Critical error occurred
Loaded Mods: leadroof@1.2.0, necessaries@1.1.3, pieontheshelf@1.0.0, potontheshelf@1.0.0, primitivesurvival@3.0.5, sticksfromfirewood@1.16.4, translocatorengineeringredux@1.2.0, game@1.17.2, alchemy@1.6.4, autosifter@1.0.1, carrycapacity@0.6.5, roadworks@1.0.1, smeltableingots@1.0.0, vgaas@1.0.0, creative@1.17.2, survival@1.17.2, woodchests@1.0.3, xlib@0.6.10-rc.2, tradercamps@1.0.2, em@1.0.0, xskills@0.6.10-rc.2, bricklayers@1.0.0
System.ArgumentNullException: Value cannot be null.
Parameter name: Unable to find a texture for texture code '0' in storagePile. Giving up. Sorry.
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(Int32 indexForLogging, MeshData meshdata, ShapeElement element, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 390
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 364
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(Shape shapeBase, MeshData& modeldata, Vec3f wholeMeshRotation, Vec3f wholeMeshOffset, Single wholeMeshScale, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 279
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(String typeForLogging, Shape shapeBase, MeshData& modeldata, ITexPositionSource texSource, Vec3f wholeMeshRotation, Int32 generalGlowLevel, Byte climateColorMapId, Byte seasonColorMapId, Nullable`1 quantityElements, String[] selectiveElements) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 204
   at Vintagestory.GameContent.BlockEntityGroundStorage.getOrCreateMesh(ItemSlot itemSlot, Vec3f offset) in VSSurvivalMod\BlockEntity\BlockEntityGroundStorage.cs:line 1034
   at Vintagestory.GameContent.BlockEntityGroundStorage.updateMeshes() in VSSurvivalMod\BlockEntity\BlockEntityGroundStorage.cs:line 1017
   at Vintagestory.GameContent.BlockEntityGroundStorage.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving) in VSSurvivalMod\BlockEntity\BlockEntityGroundStorage.cs:line 823
   at Vintagestory.GameContent.BlockEntityPitKiln.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving) in VSSurvivalMod\BlockEntity\BEPitKiln.cs:line 409
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 427
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 818
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1139
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 125
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 671
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 615
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 132
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 9/2/2022 7:41:58 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.2.0, time stamp: 0x63120498
Faulting module name: KERNELBASE.dll, version: 10.0.22000.918, time stamp: 0xb42fa627
Exception code: 0xc000041d
Fault offset: 0x000000000004474c
Faulting process id: 0x2a64
Faulting application start time: 0x01d8bf2504f9e9d0
Faulting application path: C:\Users\Dale\AppData\Roaming\Vintagestory1.17\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: b0382e2d-e965-4165-be8e-eb13cdc69def
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 9/2/2022 7:41:57 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2152601297660262436, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.2.0
P3: 63120498
P4: KERNELBASE.dll
P5: 10.0.22000.918
P6: b42fa627
P7: c0020001
P8: 000000000004474c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.5901b03c-5446-42fa-bda5-2a6082b19364.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8c4aff0f-c17b-4680-a5f3-aa5cb1f718dd.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ccc5149f-b071-48d4-a172-f1190c3fc651.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.2b2b709b-94fe-442e-82a2-b1cd69943df0.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9b499791-6958-42c6-adce-1d9f02a3fb04.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_9e37931cd795a91029fea3dc71ab77d88f78985_84fbe18f_1ea1bcce-046c-4520-958f-74821a5c7256

Analysis symbol: 
Rechecking for solution: 0
Report Id: d8c0f7ba-b242-4781-9094-baa0e2cc7fcc
Report Status: 268435456
Hashed bucket: 239e527bff2cc255addf9379aa15b824
Cab Guid: 0 }
--------------
{ TimeGenerated = 9/2/2022 7:41:56 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.2.0, time stamp: 0x63120498
Faulting module name: KERNELBASE.dll, version: 10.0.22000.918, time stamp: 0xb42fa627
Exception code: 0xc0020001
Fault offset: 0x000000000004474c
Faulting process id: 0x2a64
Faulting application start time: 0x01d8bf2504f9e9d0
Faulting application path: C:\Users\Dale\AppData\Roaming\Vintagestory1.17\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: d8c0f7ba-b242-4781-9094-baa0e2cc7fcc
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
What were you doing right before the crash?

**Comment by Xaeiune** [comment]
Nothing out of the ordinary. The following are the last 5 crashes.

Standing in front of a double door. Fighting a wolf with a copper Falx.
Jumping over a 30 block drop. Cooking a hefty meat stew.
And rummaging through inventory.

**Comment by Craluminum2413** [comment]
Crash log says that you placed/interacted with something on the ground

**Comment by Xaeiune** [comment]
Only thing I can think of would be stacking or unstacking firewood.

**Comment by Craluminum2413** [comment]
Maybe, but pit kiln cannot have firewood pile

**Comment by Xaeiune** [comment]
I use firewood for kiln fuel.

**Comment by tyronx** [comment]
likely caused by a mod, please uninstall them
