### ISSUE TITLE
Crashes when useing Xskills mod on initalizing game

### ISSUE THREAD

**Issue by Drondra** [anegostudios/VintageStory-Issues#2161]
**Game Version:** 1.17.0 
**Platform:** Windows
**Modded:**Yes  xskills
**SP/MP:*/ Multiplayer 

### Description
goes to intiate server and crashes 

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0 (Stable)
9/3/2022 7:29:13 PM: Critical error occurred in the following mod: xskills@0.6.10-rc.2
Loaded Mods: armordurability2@1.0.0, weaponpacka@1.2.4, animalcages@2.0.6, backpackpackplus@1.0.3, betterarchery@3.0.0, bettercrates@1.4.2, fancydoors@1.1.1, weaponpackg@1.0.0, geothermalinsanity@1.1.0, guicompositesettingsex@1.0.1, HangingOilLamps@1.0.1, hqzlights@1.0.0, knappingmastery@1.0.1, reducedarmornegatives@1.0.2, moreclasses@1.2.4, moreenemyloot@1.0.0, moreminerals@1.0.3, MoreTorchHolders@1.0.0, necessaries@1.1.2, nomolding@2.0.0, nooffhandhunger@1.0.0, oneshotpropick@1.0.0, orepulverizer@1.1.1, preservationmod@1.0.0, primitivesurvival@3.0.5, qptech@1.10.2, rope-bridges@1.1.0, rustandrails@1.0.0, ruststones@1.0.1, specializedbags-18Slot@0.4.2, stackables@2.0.5, survivalcats@1.2.3-rc.2, locustmod@2.3.5, viescraftmachines@1.17.2, game@1.17.0, additionalmolds@1.0.1, egocaribautomapmarkers@2.3.0, cosmosis@0.1.0, electricity@0.0.1, helvehammerext@1.2.1, jlj@1.0.3, liquidcontainers@1.0.0, medievalexpansion@3.7.1, miningtools@1.1.4, mcrate@1.0.4, petai@1.5.3, playercorpse@1.3.2, roadworks@1.0.1, SimpleMobFootSteps@1.0.3, techmolds@1.0.0, creative@1.17.0, survival@1.17.0, worldconfiggui@1.0.0, xlib@0.6.10-rc.2, xrowboat@0.0.3, cats@1.5.1, compatibilityfix@1.0.0, constructionsupport@0.1.2, feverstonehorses@1.2.9, foxtaming@1.0.1, moremolds@1.2.0, wolftaming@1.5.2, xinvtweaks@1.4.1, xskills@0.6.10-rc.2, bricklayers@0.9.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at XSkills.XSkillsItemPlantableSeed.GetHeldInteractionHelp(ItemSlot inSlot)
   at Vintagestory.Client.NoObf.HudHotbar.RecomposeActiveSlotHoverText(Int32 newSlotIndex) in VintagestoryLib\Client\Systems\Gui\Huds\HudHotbar.cs:line 495
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1138
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 123
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 665
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 609
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 125
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 9/3/2022 4:51:35 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1560273419725633225, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 630f7e18
P4: KERNELBASE.dll
P5: 10.0.19041.1889
P6: e9ede6d6
P7: c000041d
P8: 0000000000034fd9
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER18F4.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1EA2.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1EB2.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1EC2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1EE2.tmp.txt
\\?\C:\Users\Ladyd\AppData\Local\Temp\WER2145.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_f7bba52ba4c24c1222a3b0ebde66d94869de374_764b180f_e04ce30d-705f-4b64-ba80-c42ae1a4f1ad

Analysis symbol: 
Rechecking for solution: 0
Report Id: ba8a0ef9-1193-4c83-8529-abaa429e3f6e
Report Status: 268435456
Hashed bucket: 942959f4e200467d85a73468973af6c9
Cab Guid: 0 }
--------------
{ TimeGenerated = 9/3/2022 4:51:34 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 630f7e18
P4: KERNELBASE.dll
P5: 10.0.19041.1889
P6: e9ede6d6
P7: c000041d
P8: 0000000000034fd9
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER18F4.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1EA2.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1EB2.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1EC2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1EE2.tmp.txt
\\?\C:\Users\Ladyd\AppData\Local\Temp\WER2145.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_f7bba52ba4c24c1222a3b0ebde66d94869de374_764b180f_cab_e04ce30d-705f-4b64-ba80-c42ae1a4f1ad

Analysis symbol: 
Rechecking for solution: 0
Report Id: ba8a0ef9-1193-4c83-8529-abaa429e3f6e
Report Status: 4
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 9/3/2022 4:51:32 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.0.0, time stamp: 0x630f7e18
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1889, time stamp: 0xe9ede6d6
Exception code: 0xc000041d
Fault offset: 0x0000000000034fd9
Faulting process id: 0x580
Faulting application start time: 0x01d8bfc4f49d55a0
Faulting application path: G:\Vintagestory\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: ba8a0ef9-1193-4c83-8529-abaa429e3f6e
Faulting package full name: 
Faulting package-relative application ID:  }
```

**Comment by Craluminum2413** [comment]
Write it on the mod page
https://mods.vintagestory.at/show/mod/247
