### ISSUE TITLE
crash while looting drifter

### ISSUE THREAD

**Issue by diegokilla** [anegostudios/VintageStory-Issues#2163]
**Game Version:** 1.17.2
**Platform:** Windows   
**Modded:** Yes (lots)  
**SP/MP:** Singleplayer   

### Description
crashed while looting a drifter

### Logs
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.2 (Stable)
9/4/2022 10:05:36 PM: Critical error occurred
Loaded Mods: actuallyquicklime@1.0.6, composter@1.0.4, game@1.17.2, egocaribautomapmarkers@2.4.0-pre.1, carrycapacity@0.6.5, morepiles@1.2.2, prospectorinfo@3.2.0, th3restock@1.0.2, creative@1.17.2, survival@1.17.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorHarvestable.<OnInteract>b__27_0() in VSEssentials\Entity\Behavior\BehaviorHarvestable.cs:line 265
   at Vintagestory.API.Client.GuiDialog.TryClose() in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 300
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1138
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 123
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 669
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 613
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 125
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 8/7/2022 2:55:05 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2141744315486943026, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\REDBEA~1\AppData\Local\Temp\RDR741.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER752.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER762.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER770.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER790.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: bca295b1-b282-4864-aab7-2ed67b5c5a09
Report Status: 268435456
Hashed bucket: 5ba4867f167f40b4adb9011b844fb732
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
Have you tried to reproduce that without any mods enabled?

**Comment by Craluminum2413** [comment]
Very rare crash

**Comment by Craluminum2413** [comment]
Closing due to inactivity
