### ISSUE TITLE
Client crash Issue when placing raw firebricks on ground

### ISSUE THREAD

**Issue by Moonshadow360** [anegostudios/VintageStory-Issues#2181]
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.3 (Stable)
9/9/2022 6:32:18 AM: Critical error occurred
Loaded Mods: weaponpacka@1.2.4, backpackpackplus@1.0.3, blacksmithname@1.0.5, canmods@1.0.1, cralutweaks@1.0.2, weaponpackg@1.0.1, HangingOilLamps@1.0.1, harptech@0.1.1, meteoricexpansion@1.2.1, moreclasses@1.2.4, potatoes@1.0.8, moreminerals@1.0.3, leadroof@1.1.1, OresAPlenty@3.0.0, speararrowheadbits@1.1.0, game@1.17.3, alchemy@1.6.3, autosifter@1.0.1, carrycapacity@0.6.5, civbastion@1.0.5, civlockfix@1.0.0, fromgoldencombs@1.3.14-pre.1, hudclock@2.8.0, immersivecrafting@1.1.0, liquidcontainers@1.1.0, medievalexpansion@3.8.0, morepiles@1.2.2, mcrate@1.0.4, smeltableingots@1.0.0, stonequarry@1.6.5, vanvar@2.0.1, creative@1.17.3, survival@1.17.3, weapontest@1.0.0, xmelee@0.0.10, xrowboat@0.0.4, em@1.0.0, bricklayers@1.0.0
System.ArgumentNullException: Value cannot be null.
Parameter name: Unable to find a texture for texture code '0' in storagePile. Giving up. Sorry.
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(Int32 indexForLogging, MeshData meshdata, ShapeElement element, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 390
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 364
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(Shape shapeBase, MeshData& modeldata, Vec3f wholeMeshRotation, Vec3f wholeMeshOffset, Single wholeMeshScale, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 279
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(String typeForLogging, Shape shapeBase, MeshData& modeldata, ITexPositionSource texSource, Vec3f wholeMeshRotation, Int32 generalGlowLevel, Byte climateColorMapId, Byte seasonColorMapId, Nullable`1 quantityElements, String[] selectiveElements) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 204
   at Vintagestory.GameContent.BlockEntityGroundStorage.getOrCreateMesh(ItemSlot itemSlot, Vec3f offset) in VSSurvivalMod\BlockEntity\BlockEntityGroundStorage.cs:line 1035
   at Vintagestory.GameContent.BlockEntityGroundStorage.updateMeshes() in VSSurvivalMod\BlockEntity\BlockEntityGroundStorage.cs:line 1018
   at Vintagestory.GameContent.BlockEntityGroundStorage.OnPlayerInteractStart(IPlayer player, BlockSelection bs) in VSSurvivalMod\BlockEntity\BlockEntityGroundStorage.cs:line 473
   at Vintagestory.GameContent.BlockGroundStorage.CreateStorage(IWorldAccessor world, BlockSelection blockSel, IPlayer player) in VSSurvivalMod\Block\BlockGroundStorage.cs:line 240
   at Vintagestory.GameContent.CollectibleBehaviorGroundStorable.Interact(ItemSlot itemslot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handHandling, EnumHandling& handling) in VSSurvivalMod\CollectibleBehavior\BehaviorGroundStorable.cs:line 170
   at Vintagestory.API.Common.CollectibleObject.<>c__DisplayClass97_0.<OnHeldInteractStart>b__0(CollectibleBehavior bh, EnumHandling& hd) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1092
   at Vintagestory.API.Common.CollectibleObject.WalkBehaviors(CollectibleBehaviorDelegate onBehavior, Action defaultAction) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2713
   at Vintagestory.API.Common.CollectibleObject.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1095
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 860
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 835
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 563
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 199
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1176
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1364
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 204
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 711
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 615
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 132
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 9/8/2022 7:39:08 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1883176495466600515, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.2.0
P3: 63120498
P4: KERNELBASE.dll
P5: 10.0.19041.1889
P6: e9ede6d6
P7: c0020001
P8: 0000000000034fd9
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6BEE.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_9f09074b69d2780248206727c76ccd6a4bfa9_84fbe18f_c21037ab-3f75-4601-a0e1-e1cd106d1cad

Analysis symbol: 
Rechecking for solution: 0
Report Id: 753b8ff8-fa57-4b94-81f8-5ce3e01cd827
Report Status: 268566528
Hashed bucket: 7bf47298b594d6f8ba22630b8da6d843
Cab Guid: 0 }
--------------
{ TimeGenerated = 9/8/2022 7:39:07 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.2.0
P3: 63120498
P4: KERNELBASE.dll
P5: 10.0.19041.1889
P6: e9ede6d6
P7: c0020001
P8: 0000000000034fd9
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_9f09074b69d2780248206727c76ccd6a4bfa9_84fbe18f_c21037ab-3f75-4601-a0e1-e1cd106d1cad

Analysis symbol: 
Rechecking for solution: 0
Report Id: 753b8ff8-fa57-4b94-81f8-5ce3e01cd827
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 9/8/2022 7:39:07 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.2.0, time stamp: 0x63120498
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1889, time stamp: 0xe9ede6d6
Exception code: 0xc0020001
Fault offset: 0x0000000000034fd9
Faulting process id: 0x938
Faulting application start time: 0x01d8c376b63c7390
Faulting application path: G:\New folder\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 753b8ff8-fa57-4b94-81f8-5ce3e01cd827
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Can you try to reproduce that without mods?

**Comment by Craluminum2413** [comment]
I don't know much about mods, but the most likely culprit is the Bricklayers mod
