### ISSUE TITLE
Server crashing for unknown reason

### ISSUE THREAD

**Issue by TarikYuzkiv** [anegostudios/VintageStory-Issues#2183]
**Game Version:** 1.17.3
**Platform:** Windows
**Modded:** No
**SP/MP:** Multiplayer

Unfortunately, I don't know what the players did before that.

### Logs
```
10.9.2022 22:30:50 [Event] borik_kotik [::ffff:x.x.x.x]:43028 joins.
10.9.2022 22:30:51 [Fatal] Caught unhandled exception in thread 'chunkdbthread'. Shutting down server.
10.9.2022 22:30:51 [Fatal] System.IO.InvalidDataException: Found invalid data while decoding.
   at Vintagestory.Common.Compression.Decompress(Byte[] dataCompressed, Int32[][]& output, Int32 slicesCount, Func`1 createNewSlice)
   at Vintagestory.Common.ChunkDataLayer.DecompressSeparate(Byte[] dataCompressed, Byte[] paletteCompressed)
   at Vintagestory.Common.WorldChunk.unpackNoLock()
   at Vintagestory.Common.WorldChunk.UnpackAndReadBlock(Int32 index, Int32 layer)
   at Vintagestory.Common.WorldChunk.GetLocalBlockAtBlockPos(IWorldAccessor world, Int32 posX, Int32 posY, Int32 posZ, Int32 layer)
   at Vintagestory.Common.WorldChunk.GetLocalBlockAtBlockPos(IWorldAccessor world, BlockPos position)
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.UpdateSnowLayer(SnowAccumSnapshot sumsnapshot, Boolean ignoreOldAccum, IServerMapChunk mc, Vec2i chunkPos, IWorldChunk[] chunksCol) in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Systems\Weather\WeatherSimulationSnowAccum.cs:line 634
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.GetSnowUpdate(WeatherSimulationRegion simregion, IServerMapChunk mc, Vec2i chunkPos, IWorldChunk[] chunksCol) in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Systems\Weather\WeatherSimulationSnowAccum.cs:line 547
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.TryImmediateSnowUpdate(WeatherSimulationRegion simregion, IServerMapChunk mc, Vec2i chunkCoord, IWorldChunk[] chunksCol) in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Systems\Weather\WeatherSimulationSnowAccum.cs:line 283
   at Vintagestory.Server.ServerSystemSupplyChunks.loadOrGenerateChunkColumn()
   at Vintagestory.Server.ServerSystemSupplyChunks.OnSeparateThreadTick()
   at Vintagestory.Server.ServerThread.Update()
   at Vintagestory.Server.ServerThread.Process()
10.9.2022 22:30:51 [Event] Игрок Otaku исключен. Причина: Server shutting down - Exeption during Process
```

**Comment by TarikYuzkiv** [comment]
Okay, I regenerated the chunks and that fixed the problem, but the reason has not been found.

**Comment by Nidelon** [comment]
The same problem, the world was converted from version 1.16.5 to 1.17.3, and was playable. But the next day, as soon as I tried to enter it, it gives an error of mismatch of the block length. If you create another world, then everything works.
`11.9.2022 16:21:28 [Fatal] System.IO.InvalidDataException: Длина блока не соответствует дополнению.
   в System.IO.Compression.Inflater.DecodeUncompressedBlock(Boolean& end_of_block)
   в System.IO.Compression.Inflater.Decode()
   в System.IO.Compression.Inflater.Inflate(Byte[] bytes, Int32 offset, Int32 length)
   в System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
   в Vintagestory.Common.CompressionDeflate.Decompress(Byte[] fi, Byte[] dest)
   в Vintagestory.Common.ChunkData.OldStyleUnpack(Byte[] blocksCompressed, Byte[] lightCompressed, Byte[] lightSatCompressed)
   в Vintagestory.Common.WorldChunk.unpackNoLock()
   в Vintagestory.Common.WorldChunk.UnpackAndReadBlock(Int32 index, Int32 layer)
   в Vintagestory.Common.WorldChunk.GetLocalBlockAtBlockPos(IWorldAccessor world, Int32 posX, Int32 posY, Int32 posZ, Int32 layer)
   в Vintagestory.Common.WorldChunk.GetLocalBlockAtBlockPos(IWorldAccessor world, BlockPos position)
   в Vintagestory.GameContent.WeatherSimulationSnowAccum.UpdateSnowLayer(SnowAccumSnapshot sumsnapshot, Boolean ignoreOldAccum, IServerMapChunk mc, Vec2i chunkPos, IWorldChunk[] chunksCol) в C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Systems\Weather\WeatherSimulationSnowAccum.cs:строка 634
   в Vintagestory.GameContent.WeatherSimulationSnowAccum.GetSnowUpdate(WeatherSimulationRegion simregion, IServerMapChunk mc, Vec2i chunkPos, IWorldChunk[] chunksCol) в C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Systems\Weather\WeatherSimulationSnowAccum.cs:строка 547
   в Vintagestory.GameContent.WeatherSimulationSnowAccum.TryImmediateSnowUpdate(WeatherSimulationRegion simregion, IServerMapChunk mc, Vec2i chunkCoord, IWorldChunk[] chunksCol) в C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Systems\Weather\WeatherSimulationSnowAccum.cs:строка 283
   в Vintagestory.Server.ServerSystemSupplyChunks.loadOrGenerateChunkColumn()
   в Vintagestory.Server.ServerSystemSupplyChunks.loadChunkAreaBlocking(Int32 chunkX1, Int32 chunkZ1, Int32 chunkX2, Int32 chunkZ2, Boolean isStartupLoad, ITreeAttribute chunkGenParams)
   в Vintagestory.Server.ServerSystemSupplyChunks.LoadWorldgenHandlerAndSpawnChunks()
   в Vintagestory.Server.ServerMain.EnterRunPhase(EnumServerRunPhase runPhase)
   в Vintagestory.Server.ServerMain.Launch()
   в Vintagestory.Client.ClientProgram.ServerThreadStart()`

**Comment by Craluminum2413** [comment]
Closing due to inactivity
