### ISSUE TITLE
Crash on trying to place an item with overlays into Ground Storage

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#2187]
**Game Version:** 1.17.3
**Platform:** Windows 
**Modded:** Yes
**SP/MP:** Singleplayer

### How to reproduce
1. Add item with GroundStorable behavior (tested with Quadrants)
2. Add texture and overlays
3. Place it on the ground
4. It crashes

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.3 (Stable)
2022-09-11 17:33:28: Critical error occurred
Loaded Mods: examplemod@, game@1.17.3, creative@1.17.3, survival@1.17.3
System.ArgumentNullException: Value cannot be null.
Parameter name: Unable to find a texture for texture code 'mono' in item examplemod:itemwithoverlay. Giving up. Sorry.
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(Int32 indexForLogging, MeshData meshdata, ShapeElement element, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 390
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 364
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(Shape shapeBase, MeshData& modeldata, Vec3f wholeMeshRotation, Vec3f wholeMeshOffset, Single wholeMeshScale, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 279
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(String type, AssetLocation name, CompositeShape compositeShape, MeshData& modeldata, ITexPositionSource texSource, Int32 generalGlowLevel, Byte climateColorMapIndex, Byte seasonColorMapIndex, Nullable`1 quantityElements, String[] selectiveElements) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 155
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateItem(Item item, MeshData& modeldata, ITexPositionSource texSource) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 633
   at Vintagestory.GameContent.BlockEntityDisplay.genMesh(ItemStack stack) in VSSurvivalMod\BlockEntity\BlockEntityContainerDisplay.cs:line 200
   at Vintagestory.GameContent.BlockEntityGroundStorage.getOrCreateMesh(ItemSlot itemSlot, Vec3f offset) in VSSurvivalMod\BlockEntity\BlockEntityGroundStorage.cs:line 1035
   at Vintagestory.GameContent.BlockEntityGroundStorage.updateMeshes() in VSSurvivalMod\BlockEntity\BlockEntityGroundStorage.cs:line 1012
   at Vintagestory.GameContent.BlockEntityGroundStorage.OnPlayerInteractStart(IPlayer player, BlockSelection bs) in VSSurvivalMod\BlockEntity\BlockEntityGroundStorage.cs:line 473
   at Vintagestory.GameContent.BlockGroundStorage.CreateStorage(IWorldAccessor world, BlockSelection blockSel, IPlayer player) in VSSurvivalMod\Block\BlockGroundStorage.cs:line 240
   at Vintagestory.GameContent.CollectibleBehaviorGroundStorable.Interact(ItemSlot itemslot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handHandling, EnumHandling& handling) in VSSurvivalMod\CollectibleBehavior\BehaviorGroundStorable.cs:line 170
   at Vintagestory.API.Common.CollectibleObject.<>c__DisplayClass97_0.<OnHeldInteractStart>b__0(CollectibleBehavior bh, EnumHandling& hd) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1092
   at Vintagestory.API.Common.CollectibleObject.WalkBehaviors(CollectibleBehaviorDelegate onBehavior, Action defaultAction) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2713
   at Vintagestory.API.Common.CollectibleObject.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1095
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 860
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 835
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 563
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 192
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1176
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1364
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 204
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 711
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 615
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 132
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 104
   at Vintagestory.Client.ClientProgram.Main(String[] rawArgs)
```

**Comment by tyronx** [comment]
could you upload a small sample mod.zip to reproduce the crash please

**Comment by Craluminum2413** [comment]
[examplemod.zip](https://github.com/anegostudios/VintageStory-Issues/files/9547505/examplemod.zip)

**Comment by tels-git** [comment]
Can confirm this on Linux. Some of the combinations do work, tho, like this one:
```
        "texturesByType": {
                "@.*-raw-(lavender|paleblue|palegreen|palered|sunflower|white)": {
                        "ceramic": { "base": "bricklayers:block/clay/raw/{color}",
                                "overlays": [ "bricklayers:block/clay/raw/overlay" ] },
                        "top": { "base": "bricklayers:block/clay/raw/{color}",
                                "overlays": [ "bricklayers:block/clay/raw/overlay_flowerpot" ] },
                        "bottom": { "base": "bricklayers:block/clay/raw/{color}",
                                "overlays": [ "bricklayers:block/clay/raw/overlay_flowerpot" ] },
                        "soil": { "base": "game:block/transparent" }
                },
     ...
```

**Comment by tyronx** [comment]
thanks for the report. This should be fixed for next release
