### ISSUE TITLE
`IndexOutOfRangeException` within `Vintagestory.Client.NoObf.HudHotbar::UpdateCurrentToolMode(int)` (With Fix)

### ISSUE THREAD

**Issue by ApacheTech** [anegostudios/VintageStory-Issues#2199]
**Game Version:** 1.17.3
**Platform:** All
**Modded:** Yes... and no.  
**SP/MP:** Both

### Scenario
In my mod, `Knapster`, I add new tool modes for [Clay Forming](https://github.com/ApacheTechSolutions/ApacheTech.VintageMods.Knapster/blob/master/src/ApacheTech.VintageMods.Knapster/Features/EasyClayForming/EasyClayForming.cs#L108), and [Smithing](https://github.com/ApacheTechSolutions/ApacheTech.VintageMods.Knapster/blob/master/src/ApacheTech.VintageMods.Knapster/Features/EasySmithing/EasySmithing.cs#L109) (ItemClay, and ItemHammer). This can cause the following crash, because there is no fallback within `Vintagestory.Client.NoObf.HudHotbar::UpdateCurrentToolMode(int)` if an index is not found. This would happen if the mod is removed from the server, while any player still has a custom tool mode set.

```
Running on 64 bit Windows with 128 GB RAM 
Game Version: v1.17.3 (Stable)
17/09/2022 22:26:42: Critical error occurred
Loaded Mods: game@1.17.3, creative@1.17.3, survival@1.17.3
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.Client.NoObf.HudHotbar.UpdateCurrentToolMode(Int32 newSlotIndex) in VintagestoryLib\Client\Systems\Gui\Huds\HudHotbar.cs:line 139
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 106
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1200
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1104
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 125
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 671
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 615
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 132
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

While this happens with my mod, it would also happen with anything that adds/removes tool modes from any item that has different modes. This includes proprietary changes to vanilla items. I expect this bug has never been uncovered, because modes have only ever been added, and not removed, within the proprietary mods.

In my mod, I do [add a failsafe](https://github.com/ApacheTechSolutions/ApacheTech.VintageMods.Knapster/blob/master/src/ApacheTech.VintageMods.Knapster/Features/EasySmithing/EasySmithing.cs#L144), while the mod is still loaded, which resets the current tool mode to 0, if the mode set within the attributes is outside the bounds of the array. However, once the mod is removed, this safety mechanism is no longer in place.

### Proposed Fix:

Within `Vintagestory.Client.NoObf.HudHotbar::UpdateCurrentToolMode(int)`:

**Current:**
```csharp
var curModeIndex = slot.Itemstack.Collectible.GetToolMode(slot, capi.World.Player, this.World.Player.CurrentBlockSelection);
currentToolModeTexture = toolModes[curModeIndex].Texture;
```

**Fixed:**
```csharp
var byPlayer = capi.World.Player;
var blockSel = byPlayer.CurrentBlockSelection;
var curModeIndex = slot.Itemstack.Collectible.GetToolMode(slot, byPlayer , blockSel);
if (curModeIndex >= toolModes.Length)
{
    curModeIndex = 0;
    slot.Itemstack.Collectible.SetToolMode(slot, byPlayer, blockSel, 0);
}
currentToolModeTexture = toolModes[curModeIndex].Texture;
```

**Comment by tyronx** [comment]
Your fix wouldn't work correctly because its client side only - it would make the stack desync. But thanks for the report. I'll address it for 1.17.4
