### ISSUE TITLE
World edit crash and save file won't load for me, others unaffected

### ISSUE THREAD

**Issue by aidantorchard** [anegostudios/VintageStory-Issues#2200]
**Game Version:** 1.17.3  
**Platform:** Windows
**Modded:** No
**SP/MP:** Multiplayer

### Description
Made the sphere too big in world generation and now unable to return to the world.  Other people on the server are unaffected.

### How to reproduce
1. On a multiplayer server, go into world edit and make a solid sphere 200 by 200 by 200
2. Crashes the game and unable to return

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.3 (Stable)
18/09/2022 21:47:47: Critical error occurred
Loaded Mods: game@1.17.3, prospectorinfo@3.1.2, creative@1.17.3, survival@1.17.3
System.OutOfMemoryException: Array dimensions exceeded supported range.
   at Vintagestory.API.Client.MeshData..ctor(Int32 capacityVertices, Int32 capacityIndices, Boolean withNormals, Boolean withUv, Boolean withRgba, Boolean withFlags) in VintagestoryApi\Client\Model\Mesh\MeshData.cs:line 639
   at Vintagestory.Client.NoObf.BlockHighlight.TesselateArbitraryModel(ClientMain game, BlockPos[] positions, Int32[] colors) in VintagestoryLib\Client\Systems\Render\HighlightBlocks.cs:line 222
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1139
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 383
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 711
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 615
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 132
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 18/09/2022 21:19:05, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.17.3.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 11b0

Start Time: 01d8cb86a6b1c645

Termination Time: 4

Application Path: C:\Users\mrnad\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: d983fca1-e022-4d6d-b748-ad29159bd1ab

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 18/09/2022 21:19:03, Site = , Source = Windows Error Reporting, Message = Fault bucket 1352492965441982761, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.3.0
P3: 631af235
P4: bef4
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7243118a-8338-4a7f-9477-4a308fbacefd.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a9fff509-040f-4e3c-b23f-8f61ff90a23b.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6cbd0571-19af-4d6b-af38-e86e79301bb3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.400a3bc8-10e6-4fb9-a76f-cb29864b9cf5.tmp.txt
\\?\C:\Users\mrnad\AppData\Local\Temp\WER.8c330844-c4c8-4ace-a326-84c55421b852.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_5b9a1b68ac70fcccc8edc8489c3ea2a1a92f291_1e73f8c4_7606e2c8-dff1-4407-9a5e-4504ed84770a

Analysis symbol: 
Rechecking for solution: 0
Report Id: d983fca1-e022-4d6d-b748-ad29159bd1ab
Report Status: 268435456
Hashed bucket: 747a5abe2c97f88562c5052fae625129
Cab Guid: 0 }
--------------
{ TimeGenerated = 25/08/2022 20:01:18, Site = , Source = Windows Error Reporting, Message = Fault bucket 1726649466493275827, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 10.0.22000.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\mrnad\AppData\Local\Temp\RDRD735.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8b7c2494-680c-4f4e-b7ea-0e04194b6041.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7458bdf5-b884-4906-8108-3a94a43e6045.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.2acff98d-e66e-42a9-a146-2853ac548429.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7caef4c5-6ce3-4530-81b6-f63352e044b6.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: f416a087-8588-4837-8ce7-6e3c5d852017
Report Status: 268435456
Hashed bucket: 366589d3cc86a9fd17f64a8aa5f30eb3
Cab Guid: 0 }

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by tyronx** [comment]
Thanks for the report. This should be fixed in 1.17.4 - it will replace the exact preview shape with a simplified cube to prevent lag/out of memory exceptions like these.

It'll still freeze the server for ~10 minutes if you were to actually use a 200x200x200 brush, tough
