### ISSUE TITLE
Can't fire arrows

### ISSUE THREAD

**Issue by HeliosAnavatis** [anegostudios/VintageStory-Issues#2210]
Since upgrading my multiplayer server to 1.17.4, client crashes when drawing a bow
:

`Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.4 (Stable)
22/09/2022 20:37:42: Critical error occurred
Loaded Mods: harptech@0.2.3, game@1.17.4, autosifter@1.0.0, hudclock@2.8.0, prospectorinfo@4.1.0, creative@1.17.4, survival@1.17.4
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemBow.<>c__DisplayClass3_0.<GetNextArrow>b__0(ItemSlot invslot) in VSSurvivalMod\Item\ItemBow.cs:line 59
   at Vintagestory.API.Common.EntityPlayer.WalkInventory(OnInventorySlot handler) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 1120
   at Vintagestory.GameContent.ItemBow.GetNextArrow(EntityAgent byEntity) in VSSurvivalMod\Item\ItemBow.cs:line 57
   at Vintagestory.GameContent.ItemBow.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling) in VSSurvivalMod\Item\ItemBow.cs:line 98
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 852
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 835
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 389
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 86
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 201
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1174
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1362
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 202
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 709
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 613
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 125
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 06/09/2022 22:51:01, Site = , Source = Windows Error Reporting, Message = Fault bucket 2006920362229108847, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.2.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\John\AppData\Local\Temp\RDR530A.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER530B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER531C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5329.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5349.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 237705f7-adf8-4c31-a414-106db1c21a91
Report Status: 268435456
Hashed bucket: da2be6635593937aebda036fb32a106f
Cab Guid: 0 }`

**Comment by Craluminum2413** [comment]
I cannot reproduce that

**Comment by Craluminum2413** [comment]
@HeliosAnavatis Did you find the reason?
