### ISSUE TITLE
Crash on trying to get texture path with mod domain by texture key

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#2219]
**Game Version:** 1.17.4  
**Platform:** Windows
**Modded:** Yes
**SP/MP:** Singleplayer

### Description
When trying to get path by texture key, it doesn't respect mod domain.

```cs
new AssetLocation(Textures[team + "-crown"].Base.Path)
```
This will crash
```json
"textures": {
    "black-crown": { "base": "tabletopgames:item/whitecrown" }
}
```
This will not crash
```json
"textures": {
    "black-crown": { "base": "game:item/whitecrown" }
}
```
For the case:
```cs
        public TextureAtlasPosition this[string textureCode] => GetOrCreateTexPos(tmpTextures[textureCode]);

        protected TextureAtlasPosition GetOrCreateTexPos(AssetLocation texturePath)
        {
            var texAsset = capi.Assets.TryGet(texturePath.Clone().WithPathPrefixOnce("textures/").WithPathAppendixOnce(".png"));
            var texPos = targetAtlas[texturePath];

            if (texPos != null) return texPos;
            if (texAsset != null) targetAtlas.GetOrInsertTexture(texturePath, out var _, out texPos, () => texAsset.ToBitmap(capi));

            return texPos;
        }
```

Here textures are assigned:
```cs
            tmpTextures["team"] = new AssetLocation(Textures[team].Base.Path);
            if (crown) tmpTextures["crown"] = new AssetLocation(Textures[team + "-crown"].Base.Path);
```

### How to reproduce
1. Make an item/block with dynamic textures like ItemShield does (based on `ITreeAttribute` attributes)
2. Try to assign textures from non-game domain, as in description above
3. It crashes on loading

### Logs
```
Game Version: v1.17.4 (Stable)
2022-09-26 23:31:21: Critical error occurred in the following mod: tabletopgames@
Loaded Mods: tabletopgames@, game@1.17.4, creative@1.17.4, survival@1.17.4
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TabletopGames.ItemChecker.get_Item(String textureCode)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(Int32 indexForLogging, MeshData meshdata, ShapeElement element, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 477
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 364
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 379
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(Shape shapeBase, MeshData& modeldata, Vec3f wholeMeshRotation, Vec3f wholeMeshOffset, Single wholeMeshScale, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 279
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(String type, AssetLocation name, CompositeShape compositeShape, MeshData& modeldata, ITexPositionSource texSource, Int32 generalGlowLevel, Byte climateColorMapIndex, Byte seasonColorMapIndex, Nullable`1 quantityElements, String[] selectiveElements) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 155
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateItem(Item item, MeshData& modeldata, ITexPositionSource texSource) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 633
   at TabletopGames.ItemChecker.GenMesh(ItemStack itemstack, ITextureAtlasAPI targetAtlas)
   at TabletopGames.ItemChecker.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 385
   at Vintagestory.GameContent.EntityShapeRenderer.RenderHeldItem(Single dt, Boolean isShadowPass, Boolean right) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 558
   at Vintagestory.GameContent.EntityShapeRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 537
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderFrameShadows(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 226
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 192
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1176
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1228
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1104
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 125
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 671
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 615
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 132
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 104
   at Vintagestory.Client.ClientProgram.Main(String[] rawArgs)
```

**Comment by tyronx** [comment]
`new AssetLocation(Textures[team + "-crown"].Base.Path)`

With this you explicitly remove the domain. Remove the `.Path` suffice.
