### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by mac69mano** [anegostudios/VintageStory-Issues#2240]
Running on 64 bit Windows with 12 GB RAM 
Game Version: v1.17.7 (Stable)
12.10.2022 г. 17:04:00: Critical error occurred
Loaded Mods: game@1.17.7, creative@1.17.7, survival@1.17.7
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityMicroBlock.genCube(Int32 voxelX, Int32 voxelY, Int32 voxelZ, Int32 width, Int32 height, Int32 length, ICoreClientAPI capi, ITexPositionSource texSource, Single subPixelPaddingx, Single subPixelPaddingy, Block block, UInt32[] originalVoxelCuboids) in C:\Users\tyron\Documents\vintagestory\game\VSSurvivalMod\BlockEntity\BEMicroBlock.cs:line 1229
   at Vintagestory.GameContent.BlockEntityMicroBlock.CreateDecalMesh(ICoreClientAPI coreClientAPI, List`1 voxelCuboids, ITexPositionSource decalTexSource, UInt32[] originalVoxelCuboids) in C:\Users\tyron\Documents\vintagestory\game\VSSurvivalMod\BlockEntity\BEMicroBlock.cs:line 1128
   at Vintagestory.GameContent.BlockMicroBlock.GetDecal(IWorldAccessor world, BlockPos pos, ITexPositionSource decalTexSource, MeshData& decalModelData, MeshData& blockModelData) in C:\Users\tyron\Documents\vintagestory\game\VSSurvivalMod\Block\BlockMicroBlock.cs:line 442
   at Vintagestory.Client.NoObf.SystemRenderDecals.UpdateDecal(BlockDecal decal) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Render\RenderDecals.cs:line 264
   at Vintagestory.Client.NoObf.SystemRenderDecals.AddBlockBreakDecal(BlockPos pos, Int32 stage) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Render\RenderDecals.cs:line 208
   at Vintagestory.Client.NoObf.SystemRenderDecals.OnPlayerBreakingBlock(BlockDamage blockDamage) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Render\RenderDecals.cs:line 170
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockBreaking(BlockDamage blockDamage) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Util\ClientEventManager.cs:line 401
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 819
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 598
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 86
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Util\ClientEventManager.cs:line 201
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1174
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1362
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 202
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 718
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 622
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 124
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
Does it happen only when you break certain chiseled block or just while you loading a world?

**Comment by Craluminum2413** [comment]
Reproduced it by breaking chiseled soil block

**Comment by Craluminum2413** [comment]
Fixed in [1.17.8](https://www.vintagestory.at/forums/topic/10266-spooktober-update-v1177-v1178/#comment-42147:~:text=fix%20a%20crash%20with%20chiseled%20blocks)
