### ISSUE TITLE
Crashing on Load

### ISSUE THREAD

**Issue by annachibi2** [anegostudios/VintageStory-Issues#2262]
I'm honestly not sure what the problem is except that my computer is running quite slowly suddenly and if I try to connect to my server, Aura Fury, it crashes upon trying to load me in. Here is the log:

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.9 (Stable)
10/23/2022 8:30:30 AM: Critical error occurred in the following mod: automap@0.1.8-pre.3
Loaded Mods: bettercrates@1.5.2, chiseltools@1.5.6, extrachests@1.6.0, specializedbags-10Slot@0.4.2, tradeomat@1.6.3, game@1.17.9, automap@0.1.8-pre.3, carrycapacity@0.6.5, farmlanddropssoil@1.4.0, hudclock@2.8.0, medievalexpansion@3.8.1, miningtools@1.1.4, prospectorinfo@4.1.0, creative@1.17.9, survival@1.17.9, workbenchexpansion@1.5.1, accessibilitytweaks@3.0.4, em@1.0.1, bricklayers@1.1.1
System.Exception: error reading, 0 !=2263
   at Hjg.Pngcs.PngHelperInternal.ReadBytes(Stream mask0, Byte[] b, Int32 offset, Int32 len)
   at Hjg.Pngcs.Chunks.ChunkRaw.ReadChunkData(Stream stream, Boolean checkCrc)
   at Hjg.Pngcs.PngReader.ReadChunk(Byte[] chunkid, Int32 clen, Boolean skipforced)
   at Hjg.Pngcs.PngReader.ReadLastChunks()
   at Hjg.Pngcs.PngReader.ReadLastAndClose()
   at Hjg.Pngcs.PngReader.ReadSkippingAllRows()
   at Automap.AutomapSystem.Reload_Metadata()
   at Automap.AutomapSystem.EngageAutomap()
   at System.Action.Invoke()
   at Vintagestory.Client.NoObf.ClientMain.OnLevelFinalize() in VintagestoryLib\Client\ClientMain.cs:line 1044
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleLevelFinalize(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 219
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1139
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 381
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 720
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 624
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 131
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10/17/2022 2:22:33 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1808742895449807768, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.8.0
P3: 6346ee48
P4: VintagestoryLib
P5: 1.17.8.0
P6: 6346ee48
P7: 15e5
P8: 12
P9: System.Exception
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7EBA.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA9B3.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAA31.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAAAC.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAAFB.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_b0c28811f32d836d31ffabce47ec9fa4d5c7753_123e9cbf_ad08ae69-bbb6-42e8-b25a-0d2ba09ebcfc

Analysis symbol: 
Rechecking for solution: 0
Report Id: b3f01113-dfd9-49eb-8725-55035cbf23c5
Report Status: 268435456
Hashed bucket: 4a362840d0d7fa522919f2148d4c1b98
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/17/2022 2:22:16 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.8.0, time stamp: 0x6346ee48
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2130, time stamp: 0xb0fac6c9
Exception code: 0xe0434352
Fault offset: 0x000000000002cd29
Faulting process id: 0x2e08
Faulting application start time: 0x01d8e1f0ae80c990
Faulting application path: C:\Games\Vintagestory\117\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: b3f01113-dfd9-49eb-8725-55035cbf23c5
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 10/17/2022 2:22:10 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Vintagestory.Common.AssetManager.TryGet(Vintagestory.API.Common.AssetLocation, Boolean)
   at Vintagestory.Client.NoObf.UnloadableShape.Load(Vintagestory.Client.NoObf.ClientMain, Vintagestory.API.Common.AssetLocationAndSource)
   at Vintagestory.Client.NoObf.ShapeTesselatorManager.LoadShapes(System.Collections.Generic.HashSet`1<Vintagestory.API.Common.AssetLocationAndSource>, System.Collections.Generic.IDictionary`2<Vintagestory.API.Common.AssetLocation,Vintagestory.Client.NoObf.UnloadableShape>, System.String)
   at Vintagestory.Client.NoObf.ShapeTesselatorManager.LoadBlockShapesAsync(System.Collections.Generic.HashSet`1<Vintagestory.API.Common.AssetLocationAndSource>, System.Collections.Generic.Dictionary`2<Vintagestory.API.Common.AssetLocation,Vintagestory.Client.NoObf.UnloadableShape>)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }

**Comment by Craluminum2413** [comment]
Automap mod is causing this crash
