### ISSUE TITLE
Game crashed while trying to knap with chert an axe

### ISSUE THREAD

**Issue by technocritter** [anegostudios/VintageStory-Issues#2263]
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.9 (Stable)
10/23/2022 9:32:50 AM: Critical error occurred
Loaded Mods: game@1.17.9, creative@1.17.9, survival@1.17.9
System.InvalidOperationException: Tried to remove mesh that does not exist. This shouldn't happen
   at Vintagestory.API.Client.MeshDataPool.RemoveLocation(ModelDataPoolLocation location) in VintagestoryApi\Client\MeshPool\MeshDataPool.cs:line 309
   at Vintagestory.Client.NoObf.SystemRenderDecals.OnBlockChanged(BlockPos pos, Block oldBlock) in VintagestoryLib\Client\Systems\Render\RenderDecals.cs:line 130
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockChanged(ClientMain game, BlockPos pos, Block oldBlock) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 520
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 810
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1139
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 125
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 680
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 624
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 131
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10/23/2022 9:32:50 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFB1833FB0C
Stack:
 }
--------------
{ TimeGenerated = 10/22/2022 5:32:23 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1942268786250236586, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 10.0.22621.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\fishincritter\AppData\Local\Temp\RDRD8D0.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.531bdd17-de1a-4e53-94e5-85d6b6fa1593.tmp.WERInternalMetadata.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20220920_1_EC_0_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.51305cc9-dcb4-4b0b-89e6-bfaef2526e07.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a948afa6-224b-4c73-abfb-8799b7dd423c.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.45441c32-8237-4b0b-a2cc-7874dcd811eb.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.923ab374-aae9-47bb-9c32-e2cbfa103a6c.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a799e29e-406c-4d1d-97ed-3295f1329d6c.tmp.xml

These files may be available here:
NULL

Analysis symbol: 
Rechecking for solution: 0
Report Id: 708be351-dedb-4efd-9c84-b5cea75249e1
Report Status: 268435456
Hashed bucket: 777753bbb04a2bcd3af4532ba6c642aa
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
I can't reproduce that

**Comment by Craluminum2413** [comment]
Closing due to inactivity
