### ISSUE TITLE
Crash: Put pie on top of table while it is already sliced by other player

### ISSUE THREAD

**Issue by adamdoda** [anegostudios/VintageStory-Issues#2265]
**Game Version:** v1.17.9 (Stable)
**Platform:** Windows
**Modded:** No
**SP/MP:** Multiplayer

### Description
One player puts pie on the table while the other targets where the pie will go with the knife in hand holding right click will crash the game.

### How to reproduce
1. P1 Target top table of table where pie will go and hold right click with knife in hand
2. P2 Put the pie on top of table
3. Crash on P1 (server)

### Expected behavior
Not crash.

### Screenshots
N/A

### Logs
```
Running on 64 bit Windows with 64 GB RAM 
Game Version: v1.17.9 (Stable)
2022-10-25 21:26:47: Critical error occurred
Loaded Mods: game@1.17.9, carrycapacity@0.6.5, creative@1.17.9, survival@1.17.9
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityPie.OnInteract(IPlayer byPlayer) in VSSurvivalMod\BlockEntity\BEPie.cs:line 173
   at Vintagestory.GameContent.BlockPie.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in VSSurvivalMod\Block\BlockPie.cs:line 492
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 890
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 536
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 86
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 201
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1174
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1362
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 202
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 718
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 622
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 124
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2022-10-18 20:18:26, Site = , Source = Windows Error Reporting, Message = Fault bucket 1657125845687650063, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.8.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\adam\AppData\Local\Temp\RDR9257.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9268.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9278.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER92A5.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER92C5.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 8933de4c-3ff4-4af1-8214-73a9e1f5d1f5
Report Status: 268435456
Hashed bucket: a0cac4661686de0ec6ff4b2d4454c70f
Cab Guid: 0 }
--------------
{ TimeGenerated = 2022-09-17 11:27:20, Site = , Source = Windows Error Reporting, Message = Fault bucket 1634411583996066492, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.3.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\adam\AppData\Local\Temp\RDRACC4.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERACD5.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERACE5.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAD03.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAD23.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 8989cdd2-46ef-47ad-977c-bb02f1d84a73
Report Status: 268435456
Hashed bucket: 1fe2057b327d0931a6ae98ad18de7abc
Cab Guid: 0 }
--------------
{ TimeGenerated = 2022-08-17 20:37:30, Site = , Source = Windows Error Reporting, Message = Fault bucket 1381417961401207149, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\adam\AppData\Local\Temp\RDRD6BE.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD6CF.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD6E0.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD70A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD739.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: e900d10a-e5ef-40a2-9730-00d2dcbc2a67
Report Status: 268435456
Hashed bucket: 6ce2bbf81ba2523d132bc8511ba9c96d
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment]
Have you tried to reproduce it without mods?

**Comment by adamdoda** [comment]
Sorry, I forgot I have mods installed. No and as it can't be reproduced alone I won't be able try to to reproduce it for a couple of weeks.

**Comment by Craluminum2413** [comment]
Closing due to inactivity
