### ISSUE TITLE
Crash: Lightning Flash

### ISSUE THREAD

**Issue by kurazarrh** [anegostudios/VintageStory-Issues#2267]
**Game Version:** 1.17.9
**Platform:** Windows
**Modded:** Yes (see log pasted below)
**SP/MP:** Singleplayer

### Description
Game crashed to desktop.

### How to reproduce
Reproduction steps uncertain, but looking at the log, it appears there is an issue with the lightning flash causing a CTD due to an out-of-bounds exception.

### Expected behavior
Lightning flashes should not cause CTDs.

### Logs
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.9 (Stable)
25-Oct-22 22:37:32: Critical error occurred
Loaded Mods: bettercrates@1.5.1, emotemenu@1.0.4, extrachests@1.6.0, vertplanks@1.0.0, game@1.17.9, carrycapacity@0.6.5, farmlanddropssoil@1.4.0, hudclock@2.8.0, prospectorinfo@4.1.1, creative@1.17.9, survival@1.17.9, workbenchexpansion@1.5.1, xrowboat@0.0.5, campaigncartographer@3.0.2
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Vintagestory.GameContent.LightningFlash.ClientInit() in VSEssentials\Systems\Weather\LightningFlash.cs:line 56
   at Vintagestory.GameContent.WeatherSimulationLightning.genLightningFlash(Vec3d pos, Nullable`1 seed) in VSEssentials\Systems\Weather\WeatherSimulationLightning.cs:line 258
   at Vintagestory.Client.NoObf.NetworkChannel.<>c__DisplayClass12_0`1.<SetMessageHandler>b__0(Packet_CustomPacket p) in VintagestoryLib\Client\API\NetworkChannel.cs:line 74
   at Vintagestory.Client.NoObf.NetworkAPI.HandleCustomPacket(Packet_Server packet) in VintagestoryLib\Client\API\NetworkAPI.cs:line 108
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1139
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 125
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 680
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 624
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 131
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 25-Oct-22 22:37:35, Site = , Source = Windows Error Reporting, Message = Fault bucket 1748203002226985351, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 63501532
P4: atio6axx.dll
P5: 30.0.15020.1001
P6: 6272a8c8
P7: 0000000001bfee85
P8: c0000409
P9: 0000000000000007
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6187.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6512.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6513.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6521.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6531.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_d3c47d2a45b3330e5bbf730a089234d8be7bf26_7fba9aec_10910b2b-bcfa-4942-a422-4c6bb804917d

Analysis symbol: 
Rechecking for solution: 0
Report Id: b3ff6c85-0aee-4049-8c17-82070ab46c6e
Report Status: 268566528
Hashed bucket: 85805b885315758bc842dd5e3f02c987
Cab Guid: 0 }
--------------
{ TimeGenerated = 25-Oct-22 22:37:33, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.9.0, time stamp: 0x63501532
Faulting module name: atio6axx.dll, version: 30.0.15020.1001, time stamp: 0x6272a8c8
Exception code: 0xc0000409
Fault offset: 0x0000000001bfee85
Faulting process id: 0xc78
Faulting application start time: 0x01d8e8d4f35e1e41
Faulting application path: C:\Users\Falconis\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\u0379228.inf_amd64_d3f9915970900266\B379127\atio6axx.dll
Report Id: b3ff6c85-0aee-4049-8c17-82070ab46c6e
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 22-Oct-22 23:58:11, Site = , Source = Windows Error Reporting, Message = Fault bucket 1748203002226985351, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 63501532
P4: atio6axx.dll
P5: 30.0.15020.1001
P6: 6272a8c8
P7: 0000000001bfee85
P8: c0000409
P9: 0000000000000007
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD31A.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD889.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD89A.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD898.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD8B8.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_d3c47d2a45b3330e5bbf730a089234d8be7bf26_7fba9aec_1b3bde42-094f-485a-a888-5a3a2e2c177d

Analysis symbol: 
Rechecking for solution: 0
Report Id: 4a643e9f-26a8-4b69-a24b-9bf77ee8f7e0
Report Status: 268566528
Hashed bucket: 85805b885315758bc842dd5e3f02c987
Cab Guid: 0 }

**Comment by kurazarrh** [comment]
I'm not able to get to my gaming computer at the moment, but it's the default world size for the "Standard Survival" option. If that's not enough info to go on, let me know and I can provide an update later on tonight. In case it matters, I was exploring the area around 28,000 blocks south of spawn (temperate spawn), roughly 1,500 blocks positive on the X axis.
