### ISSUE TITLE
Cheese crashes game when another player places it on the block you're hovering over

### ISSUE THREAD

**Issue by ghastings322** [anegostudios/VintageStory-Issues#2271]
**Game Version:** Client 1.17.9, Server 1.17.8
**Platform:** Windows 
**Modded:** No
**SP/MP:** Multiplayer

### Description
Player's client will crash when looking at a block when another player places cheese on said block, or more specifically where the cheese block will be placed. This works with both cheese slices and cheese wheels. Tested only with cheddar cheese.

### How to reproduce
1. Get cheese.
2. Place cheese in front of another player's camera.
3. Second player's client will crash.

### Expected behavior
The secondary player's client will crash.

### Screenshots
N/A

### Logs
```
Running on 64 bit Windows with 48 GB RAM 
Game Version: v1.17.9 (Stable)
10/28/2022 11:24:52 AM: Critical error occurred
Loaded Mods: game@1.17.9, creative@1.17.9, survival@1.17.9
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BECheese.get_SlicesLeft() in VSSurvivalMod\BlockEntity\BECheese.cs:line 46
   at Vintagestory.GameContent.BlockCheese.<>c__DisplayClass1_0.<OnLoaded>b__1(WorldInteraction wi, BlockSelection bs, EntitySelection es) in VSSurvivalMod\Block\BlockCheese.cs:line 45
   at Vintagestory.Client.NoObf.DrawWorldInteractionUtil.ComposeBlockWorldInteractionHelp(WorldInteraction[] wis) in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockInteractionHelp.cs:line 72
   at Vintagestory.Client.NoObf.HudElementBlockInteractionHelp.BlockInView() in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockInteractionHelp.cs:line 375
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 105
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1196
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1103
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 123
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 678
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 622
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 124
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
