### ISSUE TITLE
GL error GL_INVALID_OPERATION

### ISSUE THREAD

**Issue by Matiaan** [anegostudios/VintageStory-Issues#2277]
I get this error since v1.17.4.
v1.17.3 was still working correctly.
Causes all animations (opening basket, animals and traders) to not show.

I'm using a DELL Latitude E6430 with Intel HD Graphics 4000.

```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.4 (Stable)
2022-11-05 16:25:33: Critical error occurred
Loaded Mods: game@1.17.4, creative@1.17.4, survival@1.17.4
System.Exception: GL error GL_INVALID_OPERATION
   at Vintagestory.Client.NoObf.ClientPlatformWindows.DebugCallback(DebugSource source, DebugType type, Int32 id, DebugSeverity severity, Int32 length, IntPtr message, IntPtr userParam) in VintagestoryLib\Client\ClientPlatform\GLFramebuffer.cs:line 1272
   at OpenTK.Graphics.OpenGL.GL.UniformMatrix4(Int32 location, Int32 count, Boolean transpose, Single[] value) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Graphics\OpenGL\GL.cs:line 72851
   at Vintagestory.GameContent.BEAnimatableRenderer.OnRenderFrame(Single dt, EnumRenderStage stage) in VSEssentials\BlockEntityRenderer\BEAnimatableRenderer.cs:line 111
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 199
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1176
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1259
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1104
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 125
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 671
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 615
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 132
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2022-11-05 10:23:03, Site = , Source = Windows Error Reporting, Message = Fault bucket 1952854560596989694, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\DELL-U~1\AppData\Local\Temp\RDRF844.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF874.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF894.tmp.xml

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 99cb79eb-66e1-4213-9785-78ab810eb5b8
Report Status: 268435456
Hashed bucket: 78bd6b9a4e12ad376b19eee04e6296fe
Cab Guid: 0 }
```

Picture of basket when it is open and working:
![2022-11-05 16_16_55-Vintage Story](https://user-images.githubusercontent.com/40113408/200124710-c06a4b83-c3b2-42b1-878b-85929e173dd8.png)

Picture of basket when it is open and this error happens:
![2022-11-05 16_23_18-Vintage Story](https://user-images.githubusercontent.com/40113408/200124717-49af986b-d180-46fd-8ae6-a99498b548ab.png)

**Comment by dr-bright** [comment]
Same effect on a different machine, Lenovo ThinkPad x230, Intel HD Graphics 4000, Windows 10

All entities and animations seem to be broken. Everything that's moving becomes invisible, including thrown stones or spears in air and after hitting the ground.


`contents of Logs/client-main.txt`
```
11.11.2022 16:24:10 [Notification] Client logger started.
11.11.2022 16:24:10 [Notification] Game Version: v1.17.9 (Stable)
11.11.2022 16:24:10 [Notification] Screens:
11.11.2022 16:24:10 [Notification] 0: {X=0,Y=0,Width=1366,Height=768}, \\.\DISPLAY1 (primary)
11.11.2022 16:24:11 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
11.11.2022 16:24:11 [Notification] CPU Cores: 4
11.11.2022 16:24:11 [Notification] Available RAM: 4096 MB
11.11.2022 16:24:11 [Notification] Graphics Card Vendor: Intel
11.11.2022 16:24:11 [Notification] Graphics Card Version: 3.3.0 - Build 10.18.10.4358
11.11.2022 16:24:11 [Notification] Graphics Card Renderer: Intel(R) HD Graphics 4000
11.11.2022 16:24:11 [Notification] Graphics Card ShadingLanguageVersion: 3.30 - Build 10.18.10.4358
11.11.2022 16:24:11 [Notification] Cairo Graphics Version: 1.17.3
11.11.2022 16:24:11 [Notification] OpenAL Version: 1.1 ALSOFT 1.16.0
11.11.2022 16:24:11 [Notification] C# Framework: .net Framework 4.0.30319.42000
11.11.2022 16:24:11 [Notification] OpenTK Version: 3.3.2 (A set of fast, low-level C# bindings for OpenGL, OpenGL ES and OpenAL.)
...
...
11.11.2022 16:26:08 [Fatal] Game Version: v1.17.9 (Stable)
11.11.2022 16:26:01: Critical error occurred
Loaded Mods: game@1.17.9, creative@1.17.9, survival@1.17.9
System.Exception: GL error GL_INVALID_OPERATION
   в Vintagestory.Client.NoObf.ClientPlatformWindows.DebugCallback(DebugSource source, DebugType type, Int32 id, DebugSeverity severity, Int32 length, IntPtr message, IntPtr userParam)
   в OpenTK.Graphics.OpenGL.GL.UniformMatrix4(Int32 location, Int32 count, Boolean transpose, Single[] value)
   в Vintagestory.GameContent.EntityShapeRenderer.DoRender3DOpaqueBatched(Single dt, Boolean isShadowPass)
   в Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderOpaque3D(Single deltaTime)
   в Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   в Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   в Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   в Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   в Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt)
   в Vintagestory.Client.ScreenManager.Render(Single dt)
   в Vintagestory.Client.ScreenManager.OnNewFrame(Single dt)
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   в OpenTK.GameWindow.DispatchRenderFrame()
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   в Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   в Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
```

**Comment by tyronx** [comment]
thanks for the reports, please install this version and provide me with the client-main.txt again
Windows: https://cdn.vintagestory.at/gamefiles/dev/vs_update_1.17.10-dev.1.exe
Linux: https://cdn.vintagestory.at/gamefiles/dev/vs_archive_1.17.10-dev.1.tar.gz


After you have done that, please edit the clientsettings.json and set `MaxAnimatedElements` to 34. That should temporarily fix your issue.

**Comment by Matiaan** [comment]
thanks, can confirm this fixed it

**Comment by tyronx** [comment]
Just for your info, we need this value to be higher in 1.18 and some mods might begin relying on it as well. A low value will break some animations on complex cratures.

**Comment by Matiaan** [comment]
considering my laptop is 10 years old, I don't think its unreasonable to move forward. I need to get a new computer anyways.

**Comment by Aledark789** [comment]
> 

Just for testing purposes could someone using an old computer use this pre-version to test while connecting to a 1.17.9 server or you dont recommend it?

**Comment by tyronx** [comment]
Oh yea thats completely fine you can use 1.17.10-dev.1 to connect to a 1.17.9 server. There should be no issues.

**Comment by jaesaber** [comment]
tyronx your link no longer works for the 1.17.10 dev for windows

**Comment by tyronx** [comment]
oh sorry, restored the files now

**Comment by Aledark789** [comment]
Do you happend to have a mac version. Got a user on server whom has very old mac book pro 2010 and wanted to check if that could help her fps wise.

**Comment by tyronx** [comment]
this change has no impact fps wise

**Comment by dr-bright** [comment]
Same crash report as in previously seen in 1.17.9 (OpenGL Debug Mode = On, just invis entities otherwise)
Observed with maxAnimatedElements = 36, 60, 100...
maxAnimatedElements = 34 precisely somehow works though, feels like magic
Thanks for the fix! :)
```
28.1.2023 06:36:01 [Notification] Client logger started.
28.1.2023 06:36:01 [Notification] Game Version: v1.17.10 (Stable)
28.1.2023 06:36:01 [Notification] Screens:
28.1.2023 06:36:01 [Notification] 0: {X=0,Y=0,Width=1366,Height=768}, \\.\DISPLAY1 (primary)
28.1.2023 06:36:01 [Notification] 1: {X=-294,Y=-1080,Width=1920,Height=1080}, \\.\DISPLAY2 
28.1.2023 06:36:01 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
28.1.2023 06:36:01 [Notification] CPU Cores: 4
28.1.2023 06:36:01 [Notification] Available RAM: 4096 MB
28.1.2023 06:36:01 [Notification] Graphics Card Vendor: Intel
28.1.2023 06:36:01 [Notification] Graphics Card Version: 3.3.0 - Build 10.18.10.4425
28.1.2023 06:36:01 [Notification] Graphics Card Renderer: Intel(R) HD Graphics 4000
28.1.2023 06:36:01 [Notification] Graphics Card ShadingLanguageVersion: 3.30 - Build 10.18.10.4425
28.1.2023 06:36:01 [Notification] GL.MaxVertexUniformComponents: 4096
28.1.2023 06:36:01 [Notification] GL.MaxUniformBlockSize: 65536
28.1.2023 06:36:01 [Notification] Cairo Graphics Version: 1.17.3
28.1.2023 06:36:01 [Notification] OpenAL Version: 1.1 ALSOFT 1.16.0
28.1.2023 06:36:01 [Notification] C# Framework: .net Framework 4.0.30319.42000
28.1.2023 06:36:01 [Notification] OpenTK Version: 3.3.2 (A set of fast, low-level C# bindings for OpenGL, OpenGL ES and OpenAL.)
...
28.01.2023 6:38:39: Critical error occurred
Loaded Mods: game@1.17.10, creative@1.17.10, survival@1.17.10
System.Exception: GL error GL_INVALID_OPERATION
   в Vintagestory.Client.NoObf.ClientPlatformWindows.DebugCallback(DebugSource source, DebugType type, Int32 id, DebugSeverity severity, Int32 length, IntPtr message, IntPtr userParam)
   в OpenTK.Graphics.OpenGL.GL.UniformMatrix4(Int32 location, Int32 count, Boolean transpose, Single[] value)
   в Vintagestory.GameContent.EntityShapeRenderer.DoRender3DOpaqueBatched(Single dt, Boolean isShadowPass)
   в Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderOpaque3D(Single deltaTime)
   в Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   в Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   в Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   в Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   в Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt)
   в Vintagestory.Client.ScreenManager.Render(Single dt)
   в Vintagestory.Client.ScreenManager.OnNewFrame(Single dt)
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   в OpenTK.GameWindow.DispatchRenderFrame()
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   в Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   в Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
```

**Comment by Th3Dilli** [comment]
closing as we wont support very old hardware anymore
you may also see this issue #3072
Feel free to submit a refund request if you are running hardware that does not work anymore

**Comment by tyronx** [comment]
For Reference: Intel HD 4000 is over 12 years old by now
