### ISSUE TITLE
Crash while using Xandus Inventory Tweaks mod

### ISSUE THREAD

**Issue by Jimzawy** [anegostudios/VintageStory-Issues#2290]
### Game Version

v1.17.9 (Stable)

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.9 (Stable)
15-Nov-22 6:55:59 AM: Critical error occurred in the following mod: xinvtweaks@1.4.2
Loaded Mods: animalcages@2.0.6, arrowrecovery@1.0.0, betterruins@0.0.6, bushmeat_meals@1.0.7, buzzwords@1.2.0, cralutweaks@1.0.2, djsvanillatools@1.0.4, fancysky@1.0.2, sticksarefirewood@1.0.0, sticksfromfirewood@1.16.4, visibleore@1.0.1, game@1.17.9, vshud@2.1.0, zoombuttonreborn@1.3.0, zyrails0break0down0tools@1.17.8, alloycalculator@1.0.0, carryon@0.7.1, prospectorinfo@4.1.2, vanvar@2.0.1, vgaas@1.0.0, creative@1.17.9, survival@1.17.9, vsvillage@0.4.1, xrowboat@0.0.5, metalrecovery@0.1.18-rc.2, xinvtweaks@1.4.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at XInvTweaks.InventoryUtil.SortInventory(ICoreClientAPI capi, IInventory inventory)
   at XInvTweaks.InventoryUtil.SortOpenInventories(ICoreClientAPI capi)
   at XInvTweaks.InventoryUtil.SortIntoInventory(ICoreClientAPI capi)
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean isGlobal, Boolean fallBack) in VintagestoryLib\Client\HotkeyManager.cs:line 365
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 2167
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(Object sender, KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 265
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnKeyDown(Key key, Boolean repeat) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\NativeWindowBase.cs:line 129
   at OpenTK.Platform.Windows.WinGLNative.HandleKeyboard(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 639
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 828
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 15-Nov-22 6:56:07 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.9.0, time stamp: 0x63501532
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2193, time stamp: 0x7f7062e1
Exception code: 0xc000041d
Fault offset: 0x000000000002cd29
Faulting process id: 0x4d2c
Faulting application start time: 0x01d8f8ac59104101
Faulting application path: C:\Users\Jimzawy\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 7d4e26f9-96dd-44dc-9059-41fd9ddb9ae2
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 15-Nov-22 6:56:05 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1628320419242396532, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 63501532
P4: KERNELBASE.dll
P5: 10.0.19041.2193
P6: 7f7062e1
P7: c0020001
P8: 000000000002cd29
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1A75.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER20B0.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER20D0.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER20CE.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER20FE.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_e02851070c2b25297d948e7a872e2aab9dd237_7fba9aec_7bb6e015-c589-4124-9eaa-f3c4eb681db6

Analysis symbol: 
Rechecking for solution: 0
Report Id: de885275-faf2-4a30-9474-8c8268685eca
Report Status: 268435456
Hashed bucket: 87cc699fe67a4567b698f4cb49754b74
Cab Guid: 0 }
--------------
{ TimeGenerated = 15-Nov-22 6:56:01 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.9.0, time stamp: 0x63501532
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2193, time stamp: 0x7f7062e1
Exception code: 0xc0020001
Fault offset: 0x000000000002cd29
Faulting process id: 0x4d2c
Faulting application start time: 0x01d8f8ac59104101
Faulting application path: C:\Users\Jimzawy\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: de885275-faf2-4a30-9474-8c8268685eca
Faulting package full name: 
Faulting package-relative application ID:  }

### How to reproduce

Using auto sort feature on Xandus Inventory Tweaks  mod

### Logs

[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/10009417/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/10009420/server-main.txt)

**Comment by Craluminum2413** [comment]
The mod is not part of the game
