### ISSUE TITLE
start crash 

### ISSUE THREAD

**Issue by nesstom** [anegostudios/VintageStory-Issues#2299]
### Game Version

_1.17.9_

### Platform

Windows

### Description

i start the game and i have this message 

### Logs

```Log``` Running on 64 bit Windows with 8 GB RAM 
Game Version: v1.17.9 (Stable)
29/11/2022 12:05:20: Critical error occurred
Loaded Mods: 
System.NotSupportedException: Your graphics card does not support the extensions GL_ARB_framebuffer_object, GL_ARB_vertex_array_object, GL_ARB_draw_instanced, GL_ARB_explicit_attrib_location which is required to start the game
   à Vintagestory.Client.NoObf.ClientPlatformWindows.LogAndTestHardwareInfos() dans VintagestoryLib\Client\ClientPlatform\GameWindow.cs:ligne 204
   à Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   à Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) dans VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:ligne 93

**Comment by lortews** [comment]
it gives me an error too but different

Running on 64 bit Windows with 4 GB RAM 
Game Version: v1.17.9 (Stable) by OverF1X  
29/11/2022 01:30:46 a.m.: Critical error occurred
Loaded Mods: 
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)



how do i fix it ,please and thank you

**Comment by Craluminum2413** [comment]
@lortews The pirate versions of the game are not supported

**Comment by bronco351m** [comment]
I am also receiving the same error message when I try to open the application.

Running on 64 bit Windows with 8 GB RAM 
Game Version: v1.17.11 (Stable)
3/15/2023 5:40:19 PM: Critical error occurred
Loaded Mods: 
System.NotSupportedException: Your graphics card does not support the extensions GL_ARB_framebuffer_object, GL_ARB_vertex_array_object, GL_ARB_draw_instanced, GL_ARB_explicit_attrib_location which is required to start the game
   at Vintagestory.Client.NoObf.ClientPlatformWindows.LogAndTestHardwareInfos() in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 207
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
@bronco351m Could you send logs? Especially client-main.txt

**Comment by Craluminum2413** [comment]
Closing due to inactivity
