### ISSUE TITLE
Game crash when loading world

### ISSUE THREAD

**Issue by akaminara** [anegostudios/VintageStory-Issues#2322]
### Game Version

1.17.9

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I have recently freshly installed the latest stable version of the game, and can join other people's worlds with no issues, but get a crash anytime I try to load any local worlds.

### How to reproduce

1. Create a new singleplayer world / load into an existing singleplayer world
2. Let the game load into it
3. As soon as it's done, the game crashes

### Logs

```Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.9 (Stable)
16/12/2022 17:44:45: Critical error occurred
Loaded Mods: game@1.17.9, creative@1.17.9, survival@1.17.9
System.Exception: Don't know how to instantiate item of class 'pigmentitem' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass) in VintagestoryLib\Common\ClassRegistry.cs:line 273
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType packet, IWorldAccessor world, ClassRegistry registry) in VintagestoryLib\Common\Network\ItemTypeNet.cs:line 19
   at Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateItems(List`1 items, Int32 listSize) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 561
   at Vintagestory.Client.NoObf.GeneralPacketHandler.LoadItemTypes() in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 471
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1() in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 414
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 16/12/2022 17:44:45, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.9.0, time stamp: 0x63501532
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0x00000000
Fault offset: 0x0000000000000000
Faulting process id: 0x3f74
Faulting application start time: 0x01d9116d85881e68
Faulting application path: F:\Juegos\VintageStory\Vintagestory.exe
Faulting module path: unknown
Report Id: c12f3ba9-21fe-4585-a7b3-ed54ce234996
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 16/12/2022 17:44:45, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Vintagestory.Common.ClassRegistry.CreateItem(System.String)
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateItems(System.Collections.Generic.List`1<Vintagestory.API.Common.Item>, Int32)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.LoadItemTypes()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 16/12/2022 17:42:54, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Vintagestory.Common.ClassRegistry.CreateItem(System.String)
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateItems(System.Collections.Generic.List`1<Vintagestory.API.Common.Item>, Int32)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.LoadItemTypes()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }```

**Comment by akaminara** [comment]
If anyone else encounter this, it probably means your server configuration is corrupted or from a previous version. Close your game, navigate to `/AppData/Roaming/VintagestoryData` and delete the file `serverconfig.json`, then try to load your world again.
