### ISSUE TITLE
Old tropical world crashes when moving around the map - possibly bell pepper related

### ISSUE THREAD

**Issue by JRbBrown** [anegostudios/VintageStory-Issues#2328]
Problem: an old tropical world (created in 1.15 or so, since updated to 1.17.19) crashes when traveling around the map. This has happened consistently in this specific world (and no other - I have several equally old, updated worlds which have no problems) since the last version or two. The crash log below shows the mods I usually have enabled (mainly UI related), but these crashes still occur even if I disable all mods. I suspect the crashes may be related to proximity to bell peppers (which this world has - none of my other old worlds do); the game is stable so long as I stay near my base, which has no bell peppers nearby, and will reliably crash when I approach the couple of locations where I know there is a wild bell pepper plant.

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.9 (Stable)
12/23/2022 7:35:53 PM: Critical error occurred
Loaded Mods: buzzwords@1.1.0, Creepless@1.1.2, game@1.17.9, egocaribautomapmarkers@2.4.0-pre.1, hudclock@2.8.0, prospectorinfo@4.1.2, creative@1.17.9, survival@1.17.9
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at Vintagestory.Client.NoObf.ClientChunk.InitBlockEntitiesFromPacket(ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 371
   at Vintagestory.Client.NoObf.ClientWorldMap.loadChunkMT(Packet_ServerChunk p, ClientChunk chunk) in VintagestoryLib\Client\ClientWorldMap.cs:line 701
   at Vintagestory.Client.NoObf.ClientWorldMap.<>c__DisplayClass104_0.<LoadChunkFromPacket>b__0() in VintagestoryLib\Client\ClientWorldMap.cs:line 685
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1139
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 125
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 680
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 624
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 131
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/23/2022 10:14:20 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1735362837284431206, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 10.0.22000.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\[username]\AppData\Local\Temp\RDR544D.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0b291c0b-526c-4407-9c00-ac297628a2c0.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.bde3bcc2-3dd6-48e2-befd-c8a1b3ba4dfb.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f45a1445-e071-4700-a162-70df2b75f2d3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.2fe66e50-2487-40d4-9c81-20915739db4f.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: cbd4c7b2-3156-4d71-98aa-b37fd403e735
Report Status: 268435456
Hashed bucket: a84515fe61be8dad98153f4e60c0a566
Cab Guid: 0 }
--------------
{ TimeGenerated = 11/13/2022 4:40:58 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1735362837284431206, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 10.0.22000.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\[username]\AppData\Local\Temp\RDR7F58.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0fb20cc7-7dbb-45a3-8f54-6db789e2ac24.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b70a4046-a451-4460-bc51-0b2b40c9bb12.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b1bd4a5f-0745-4225-a3b3-b183c58b5047.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.3bf9ead8-60c9-4245-8f64-d94016dd3728.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 09636fd5-f7c2-4743-ac2f-09a498acc7c3
Report Status: 268435456
Hashed bucket: a84515fe61be8dad98153f4e60c0a566
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/10/2022 2:28:11 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1950803431869135999, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.6.0
P3: 10.0.22000.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\[username]\AppData\Local\Temp\RDR988.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.50a6e4e6-1eb5-41b6-a758-78bea3da282e.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ae2d9793-014a-4ad8-8f48-b1ecb30b46cf.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c1a3e4ae-3b72-4e7c-abe1-748f54d9f765.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b138eaf5-6b33-4275-a41f-379ca1d6bd09.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5e95990b-744f-4663-8432-29479fa1301b
Report Status: 268435456
Hashed bucket: 1c4e49eddf78ca144b12a562af2c3c7f
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
Does it happen without any mods installed?

**Comment by JRbBrown** [comment]
Yes, here's a crash log with no mods, triggered by walking towards the same map area I was in for the crash in the initial report:

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.9 (Stable)
12/23/2022 9:04:52 PM: Critical error occurred
Loaded Mods: game@1.17.9, creative@1.17.9, survival@1.17.9
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at Vintagestory.Client.NoObf.ClientChunk.InitBlockEntitiesFromPacket(ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 371
   at Vintagestory.Client.NoObf.ClientWorldMap.loadChunkMT(Packet_ServerChunk p, ClientChunk chunk) in VintagestoryLib\Client\ClientWorldMap.cs:line 701
   at Vintagestory.Client.NoObf.ClientWorldMap.<>c__DisplayClass104_0.<LoadChunkFromPacket>b__0() in VintagestoryLib\Client\ClientWorldMap.cs:line 685
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1139
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 125
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 680
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 624
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 131
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/23/2022 10:14:20 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1735362837284431206, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 10.0.22000.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\[username]\AppData\Local\Temp\RDR544D.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0b291c0b-526c-4407-9c00-ac297628a2c0.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.bde3bcc2-3dd6-48e2-befd-c8a1b3ba4dfb.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f45a1445-e071-4700-a162-70df2b75f2d3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.2fe66e50-2487-40d4-9c81-20915739db4f.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: cbd4c7b2-3156-4d71-98aa-b37fd403e735
Report Status: 268435456
Hashed bucket: a84515fe61be8dad98153f4e60c0a566
Cab Guid: 0 }
--------------
{ TimeGenerated = 11/13/2022 4:40:58 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1735362837284431206, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 10.0.22000.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\[username]\AppData\Local\Temp\RDR7F58.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0fb20cc7-7dbb-45a3-8f54-6db789e2ac24.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b70a4046-a451-4460-bc51-0b2b40c9bb12.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b1bd4a5f-0745-4225-a3b3-b183c58b5047.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.3bf9ead8-60c9-4245-8f64-d94016dd3728.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 09636fd5-f7c2-4743-ac2f-09a498acc7c3
Report Status: 268435456
Hashed bucket: a84515fe61be8dad98153f4e60c0a566
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/10/2022 2:28:11 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1950803431869135999, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.6.0
P3: 10.0.22000.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\[username]\AppData\Local\Temp\RDR988.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.50a6e4e6-1eb5-41b6-a758-78bea3da282e.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ae2d9793-014a-4ad8-8f48-b1ecb30b46cf.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c1a3e4ae-3b72-4e7c-abe1-748f54d9f765.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b138eaf5-6b33-4275-a41f-379ca1d6bd09.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 5e95990b-744f-4663-8432-29479fa1301b
Report Status: 268435456
Hashed bucket: 1c4e49eddf78ca144b12a562af2c3c7f
Cab Guid: 0 }

**Comment by tyronx** [comment]
Heya, I'd need the savegame to reproduce this. Can you upload it on wetransfer.com or similar please

**Comment by Craluminum2413** [comment]
Closing due to inactivity
