### ISSUE TITLE
Game keeps crashing and wont run anything

### ISSUE THREAD

**Issue by RunWithStik** [anegostudios/VintageStory-Issues#2331]
### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

singleplayer and multyplayer, just randomly started craashing and showing black and blank screens.

### How to reproduce

Just start the game and try to go singlelayer or multyplayer

### Logs

```Log```Running on 64 bit Windows with 4 GB RAM 
Game Version: v1.17.9 (Stable)
12/28/2022 2:46:06 PM: Critical error occurred
Loaded Mods: game@1.17.9, creative@1.17.9, survival@1.17.9
System.OutOfMemoryException: Your graphics card ran out of memory! Please close other programs and reduce your view distance to prevent the game from crashing.
   at Vintagestory.Client.NoObf.ClientPlatformWindows.CheckGlErrorAlways(String errmsg) in VintagestoryLib\Client\ClientPlatform\GLImpl.cs:line 85
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 692
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 624
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 131
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/28/2022 2:35:58 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2120871913152871983, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 63501532
P4: atio6axx.dll
P5: 31.0.12029.10015
P6: 6387ad05
P7: c0000005
P8: 000000000034e136
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER22EF.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3203.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3782.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER37A6.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER37D6.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_187d5732a1d588c4c3acd6e9de8a459d7a8afb7_7fba9aec_7063df7e-a9bf-4907-91ee-0bc7271b5c7c

Analysis symbol: 
Rechecking for solution: 0
Report Id: ddd30f9c-cbb1-404c-8ab3-f9cb1d0fc857
Report Status: 268435456
Hashed bucket: 76fa064f109e89395d6ed9c4a5947e2f
Cab Guid: 0 }
--------------
{ TimeGenerated = 12/28/2022 2:35:45 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.9.0, time stamp: 0x63501532
Faulting module name: atio6axx.dll, version: 31.0.12029.10015, time stamp: 0x6387ad05
Exception code: 0xc0000005
Fault offset: 0x000000000034e136
Faulting process id: 0x1fec
Faulting application start time: 0x01d91af35545b0f1
Faulting application path: C:\Users\epick\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\u0386458.inf_amd64_e0283e9e7966f704\B386218\atio6axx.dll
Report Id: ddd30f9c-cbb1-404c-8ab3-f9cb1d0fc857
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/28/2022 2:35:36 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFC347BE136
 }

**Comment by noelle-lavenza** [comment]
What GPU do you have? Also, have you tried updating your graphics drivers and/or restarting your computer?

**Comment by Craluminum2413** [comment]
#1712

**Comment by Craluminum2413** [comment]
Closing due to inactivity
