### ISSUE TITLE
Game Crashed with mods, but I have no clue what the problem is. 

### ISSUE THREAD

**Issue by Markles123** [anegostudios/VintageStory-Issues#2333]
### Game Version

1.17.9

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer (technically)

### Description

World is single player, but I opened to LAN + Internet so friends could join. It's crashed a few times on the same world with the same friends.

### How to reproduce

Play the game like normal. Will randomly crash. I could be cooking food, cutting grass, or placing blocks, the problem seems to happen inconsistently.

### Logs

(https://pastebin.com/56UUnwZE)

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.9 (Stable)
12/31/2022 3:17:06 PM: Critical error occurred in the following mod: tabletopgames@1.2.0
Loaded Mods: aculinaryartillery@1.0.10, weaponpacka@1.3.1, animalcages@2.0.6, attributer@1.0.3, backpackpack@1.0.3, betterarchery@3.0.0, betterruins@0.0.6, LargerStacks@1.0.3, moredrifterloot@1.5.4, primitivesurvival@3.1.1, rpgitemrarity@1.0.2, sticksfromfirewood@1.16.4, game@1.17.9, expandedfoods@1.6.4, moreicons@1.0.2, petai@1.5.5, tabletopgames@1.2.0, useplanksinpitkiln@1.0.0, creative@1.17.9, vsquest@0.3.0, survival@1.17.9, vsvillage@0.5.0, cats@1.5.3, tradercamps@1.0.4, feverstonehorses@1.3.9-rc.2, wolftaming@1.5.4
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at Newtonsoft.Json.Linq.JObject.get_Item(Object key)
   at Vintagestory.API.Datastructures.JsonObject.get_Item(String key) in VintagestoryApi\Datastructures\JsonObject.cs:line 43
   at TabletopGames.Utils.ModUtils.GetShapeFromAttributesByKey(ICoreAPI api, ItemStack stack, String key)
   at TabletopGames.ItemChessPiece.GenMesh(ItemStack stack, ITextureAtlasAPI targetAtlas)
   at TabletopGames.ItemWithAttributes.OnBeforeRender(ICoreClientAPI capi, ItemStack stack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 389
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Single dt, Boolean shading, Boolean origRotate, Boolean showStackSize) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 197
   at Vintagestory.Client.NoObf.RenderAPIGame.RenderItemstackToGui(ItemStack itemstack, Double posX, Double posY, Double posZ, Single size, Int32 color, Boolean shading, Boolean rotate, Boolean showStacksize) in VintagestoryLib\Client\API\RenderAPIGame.cs:line 275
   at Vintagestory.Client.NoObf.DrawWorldInteractionUtil.<>c__DisplayClass11_1.<ComposeBlockWorldInteractionHelp>b__0(Single dt, ElementBounds bounds) in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockInteractionHelp.cs:line 92
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 711
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 373
   at Vintagestory.API.Client.HudElement.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\HudElement.cs:line 31
   at Vintagestory.Client.NoObf.HudElementBlockInteractionHelp.OnRenderGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockInteractionHelp.cs:line 440
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 303
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 199
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1176
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1350
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 204
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 720
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 624
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 131
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
 
Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/17/2022 2:47:00 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1875362396384641666, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0
 
Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 63501532
P4: nvoglv64.dll
P5: 31.0.15.2756
P6: 638e842a
P7: c0000005
P8: 0000000000e50f24
P9: 
P10: 
 
Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8D28.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9268.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9289.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9287.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER92A7.tmp.txt
 
These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_6586dfe859c681f58614f51628f4a1e26d41264a_7fba9aec_3ba0e696-82b7-439f-b15f-efd420a81882
 
Analysis symbol: 
Rechecking for solution: 0
Report Id: 38b96f32-67cd-413f-834f-9d73d64b7931
Report Status: 268435456
Hashed bucket: 14172eed4f6afa5fda06a029d5a1c282
Cab Guid: 0 }
--------------
{ TimeGenerated = 12/17/2022 2:46:58 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.9.0, time stamp: 0x63501532
Faulting module name: nvoglv64.dll, version: 31.0.15.2756, time stamp: 0x638e842a
Exception code: 0xc0000005
Fault offset: 0x0000000000e50f24
Faulting process id: 0x260c
Faulting application start time: 0x01d9120172f77d17
Faulting application path: D:\Users\Markles\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_18524371942b1cc3\nvoglv64.dll
Report Id: 38b96f32-67cd-413f-834f-9d73d64b7931
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/17/2022 2:46:57 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Graphics.OpenGL.GL.EnableVertexAttribArray(Int32)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.RenderMeshInstanced(Vintagestory.API.Client.MeshRef, Int32)
   at Vintagestory.Client.ParticleRenderer2D.Render(Single)
   at Vintagestory.Client.GuiCompositeMainMenuLeft.Render(Single, Int64, Boolean)
   at Vintagestory.Client.ScreenManager.Render(Single)
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at Vintagestory.Client.ClientProgram.Start(Vintagestory.Client.ClientProgramArgs, System.String[])
   at Vintagestory.ClientNative.CrashReporter.Start(System.Threading.ThreadStart)
   at Vintagestory.Client.ClientProgram.Main(System.String[])
 
 }

**Comment by Craluminum2413** [comment]
The issue is caused by Tabletop Games mod
