### ISSUE TITLE
Game crashing after trying to start singleplayer world

### ISSUE THREAD

**Issue by SilentStrider224** [anegostudios/VintageStory-Issues#2337]
### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I go to make a world, it will start making it and then the game crashes and gives me a crash log.

### How to reproduce

Make a new world...

### Logs

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.9 (Stable)
1/7/2023 1:21:38 PM: Critical error occurred in the following mod: carrycapacity@0.6.3
Loaded Mods: usefulstuff@2.2.1, game@1.17.9, carrycapacity@0.6.3, hudclock@2.5.0, creative@1.17.9, survival@1.17.9
System.MissingMethodException: Method not found: '!!0[] Vintagestory.API.Datastructures.JsonObject.AsArray(!!0[])'.
   at CarryCapacity.Common.BlockBehaviorCarryable.TryGetVec3f(JsonObject json, String key, Vec3f& result)
   at CarryCapacity.Common.BlockBehaviorCarryable.GetTransform(JsonObject json, ModelTransform baseTransform)
   at CarryCapacity.Common.BlockBehaviorCarryable.Initialize(JsonObject properties)
   at Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType packet, IWorldAccessor world, ClassRegistry registry) in VintagestoryLib\Common\Network\BlockTypeNet.cs:line 387
   at Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateBlocks(Block[] blocks, Int32 start, Int32 maxCount) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 536
   at Vintagestory.Client.NoObf.GeneralPacketHandler.LoadBlockTypes() in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 451
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1() in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 418
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 1/7/2023 1:21:40 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1882200760685359493, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 63501532
P4: CarryCapacity
P5: 0.6.3.0
P6: e72a83a5
P7: 5f
P8: 0
P9: System.MissingMethodException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER70C7.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7339.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7349.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER735D.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER737D.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_be23f0785dfdeb9365cc20299d5f31ef4c3361f7_7fba9aec_e560a241-2884-4a5c-b94e-76bcc285e2eb

Analysis symbol: 
Rechecking for solution: 0
Report Id: 3e767336-6ed7-4f6f-aae8-0ed006c8ae07
Report Status: 268435456
Hashed bucket: f4f2ad881d125aaada1eeb9e989ef185
Cab Guid: 0 }
--------------
{ TimeGenerated = 1/7/2023 1:21:38 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.9.0, time stamp: 0x63501532
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2364, time stamp: 0x5b7d4d22
Exception code: 0xe0434352
Fault offset: 0x000000000002cd29
Faulting process id: 0x19b4
Faulting application start time: 0x01d922c4ab83974b
Faulting application path: G:\Games\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 3e767336-6ed7-4f6f-aae8-0ed006c8ae07
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 1/7/2023 1:21:38 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.MissingMethodException
   at CarryCapacity.Common.BlockBehaviorCarryable.TryGetVec3f(Vintagestory.API.Datastructures.JsonObject, System.String, Vintagestory.API.MathTools.Vec3f ByRef)
   at CarryCapacity.Common.BlockBehaviorCarryable.GetTransform(Vintagestory.API.Datastructures.JsonObject, Vintagestory.API.Common.ModelTransform)
   at CarryCapacity.Common.BlockBehaviorCarryable.Initialize(Vintagestory.API.Datastructures.JsonObject)
   at Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateBlocks(Vintagestory.API.Common.Block[], Int32, Int32)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.LoadBlockTypes()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }

**Comment by Craluminum2413** [comment]
The problem is in Carry Capacity mod
