### ISSUE TITLE
Can't use mixing bowl without game crashing

### ISSUE THREAD

**Issue by maestrogaffney** [anegostudios/VintageStory-Issues#2344]
### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Using the mixing bowl to mix dough and berries to make berry bread crashes the game when the arrow gets filled.

### How to reproduce

1. Put dough in first slot of mixing bowl, blueberry in second slot.
2. Right click on mixing bowl to get the green arrow to fill.
3. Arrow is filled and the game pauses to place item in final window.
4. Game crashes instead.

### Logs

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.9 (Stable)
1/16/2023 8:07:27 PM: Critical error occurred in the following mod: aculinaryartillery@1.0.11
Loaded Mods: aculinaryartillery@1.0.11, advancedsmithing@1.2.0, animalcages@2.0.6, betterruins@0.0.6, composter@1.0.4, morecrops@1.0.2, furniturelibrary@1.0.6, hideandfabric@1.2.9, medieval@1.1.1, pieontheshelf@1.0.0, potontheshelf@1.0.0, game@1.17.9, wildcraft@1.4.3, WoodenPathFix@1.0.0, xrowboat@, carryon@0.10.3, farmlanddropssoil@1.4.0, fromgoldencombs@1.3.15, lc@1.0.0, medievalexpansion@3.8.1, creative@1.17.9, survival@1.17.9, woodbarrels@1.0.3, em@1.1.0, ensisswordpack@2.0.0, bricklayers@1.2.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at ACulinaryArtillery.ItemExpandedRawFood.GenMesh(ICoreClientAPI capi, String[] ings, Vec3f rot, ITesselatorAPI tesselator)
   at ACulinaryArtillery.ItemExpandedRawFood.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 389
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Single dt, Boolean shading, Boolean origRotate, Boolean showStackSize) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 197
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 490
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 711
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 373
   at Vintagestory.API.Client.GuiDialogBlockEntity.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialogBlockEntity.cs:line 115
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 303
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 199
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1176
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1350
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 204
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 720
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 624
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 131
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 1/16/2023 8:00:21 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Vintagestory.Common.ClassRegistry.CreateItem(System.String)
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateItems(System.Collections.Generic.List`1<Vintagestory.API.Common.Item>, Int32)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.LoadItemTypes()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 1/16/2023 7:50:51 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Vintagestory.Common.ClassRegistry.CreateItem(System.String)
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateItems(System.Collections.Generic.List`1<Vintagestory.API.Common.Item>, Int32)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.LoadItemTypes()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 1/16/2023 7:45:52 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Vintagestory.Common.ClassRegistry.CreateItem(System.String)
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateItems(System.Collections.Generic.List`1<Vintagestory.API.Common.Item>, Int32)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.LoadItemTypes()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }

**Comment by Craluminum2413** [comment]
Mixing bowl is not part of the game
