### ISSUE TITLE
Intermittent game crash when clicking disengaging clutch

### ISSUE THREAD

**Issue by RTHauke** [anegostudios/VintageStory-Issues#2352]
### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Game crashes randomly when disengaging a clutch that is running.  Crashes to desktop when the clutch is clicked.

### How to reproduce

Unfortunately this happens intermittently and I cannot reproduce it reliably.
1. My wind power system has 2 full windmills with a large gear atop the tower to accept power and one at the bottom to distribute.  Loads are run 1:1 to the windmill speed.
2. Last crash wind power was at about 80%.
3. Engage clutch to run quern.
4. Click clutch to disengage power to quern.

[Logs.zip](https://github.com/anegostudios/VintageStory-Issues/files/10473586/Logs.zip)

### Screenshots

![2023-01-21_21-13-43](https://user-images.githubusercontent.com/15672554/213897614-7b6d3f58-3e0e-47ba-b0e8-fa72169992b9.png)
![2023-01-21_21-12-48](https://user-images.githubusercontent.com/15672554/213897616-7f49414e-4601-4e9f-9105-174450bbc421.png)
![2023-01-21_21-13-12](https://user-images.githubusercontent.com/15672554/213897618-d4a94690-4eba-41a7-a98a-93816416b903.png)

### Logs

Crash report:
Running on 64 bit Windows with 48 GB RAM 
Game Version: v1.17.9 (Stable)
1/21/2023 8:26:16 PM: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.11, advancedsmithing@1.2.0, animalcages@2.0.6, armorrepair@1.0.3, backpackpack@1.0.3, bettercrates@1.5.2, chiseltools@1.5.6, extrachests@1.6.0, guicompositesettingsex@1.0.1, midnight-texturepackNS@1.1.0, MoreResin@1.1.0, MoreTorchHolders@1.0.0, necessaries@1.1.3, primitivesurvival@3.0.5, qptech@1.10.5, rustandrails@1.0.4, spyglass@0.4.5, survivalcats@1.2.3-rc.2, viesblocks@2.0.4, viescraftmachines@1.17.2, game@1.17.9, vshud@2.1.0, wildcraft@1.5.1, zeekea@1.6.2, alchemy@1.6.4, egocaribautomapmarkers@2.4.0-pre.1, automap@0.1.8-pre.3, carryon@0.7.0, cosmosis@0.5.0, expandedfoods@1.6.4, extraoverlays@1.1.1, farmlanddropssoil@1.4.0, fixhandbookclutter@1.0.5, fromgoldencombs@1.3.15, hudclock@2.8.0, medievalexpansion@3.8.1, playercorpse@1.5.1, prospectorinfo@4.1.2, resinlightsbymad@1.0.1, techmolds@1.0.0, creative@1.17.9, survival@1.17.9, workbenchexpansion@1.5.1, worldconfiggui@1.0.0, xrowboat@0.0.5, metalrecovery@0.1.18-rc.2, accessibilitytweaks@3.0.4, bullseye@2.4.1, em@1.0.1, bricklayers@1.1.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.Mechanics.BEBehaviorMPBase.JoinAndSpreadNetworkToNeighbours(ICoreAPI api, MechanicalNetwork network, MechPowerPath exitTurnDir, Vec3i& missingChunkPos) in VSSurvivalMod\Systems\MechanicalPower\BlockEntityBehavior\BEBehaviorMPBase.cs:line 483
   at Vintagestory.GameContent.Mechanics.BEBehaviorMPBase.spreadTo(ICoreAPI api, MechanicalNetwork network, BlockPos exitPos, MechPowerPath propagatePath, Vec3i& missingChunkPos) in VSSurvivalMod\Systems\MechanicalPower\BlockEntityBehavior\BEBehaviorMPBase.cs:line 517
   at Vintagestory.GameContent.Mechanics.BEBehaviorMPBase.JoinAndSpreadNetworkToNeighbours(ICoreAPI api, MechanicalNetwork network, MechPowerPath exitTurnDir, Vec3i& missingChunkPos) in VSSurvivalMod\Systems\MechanicalPower\BlockEntityBehavior\BEBehaviorMPBase.cs:line 488
   at Vintagestory.GameContent.Mechanics.BEBehaviorMPBase.spreadTo(ICoreAPI api, MechanicalNetwork network, BlockPos exitPos, MechPowerPath propagatePath, Vec3i& missingChunkPos) in VSSurvivalMod\Systems\MechanicalPower\BlockEntityBehavior\BEBehaviorMPBase.cs:line 517
   at Vintagestory.GameContent.Mechanics.BEBehaviorMPBase.JoinAndSpreadNetworkToNeighbours(ICoreAPI api, MechanicalNetwork network, MechPowerPath exitTurnDir, Vec3i& missingChunkPos) in VSSurvivalMod\Systems\MechanicalPower\BlockEntityBehavior\BEBehaviorMPBase.cs:line 488
   at Vintagestory.GameContent.Mechanics.BEBehaviorMPBase.spreadTo(ICoreAPI api, MechanicalNetwork network, BlockPos exitPos, MechPowerPath propagatePath, Vec3i& missingChunkPos) in VSSurvivalMod\Systems\MechanicalPower\BlockEntityBehavior\BEBehaviorMPBase.cs:line 517
   at Vintagestory.GameContent.Mechanics.BEBehaviorMPBase.CreateJoinAndDiscoverNetwork(BlockFacing powerOutFacing) in VSSurvivalMod\Systems\MechanicalPower\BlockEntityBehavior\BEBehaviorMPBase.cs:line 425
   at Vintagestory.GameContent.Mechanics.MechanicalPowerMod.RebuildNetwork(MechanicalNetwork network, IMechanicalPowerDevice nowRemovedNode) in VSSurvivalMod\Systems\MechanicalPower\MechanicalPowerMod.cs:line 238
   at Vintagestory.GameContent.Mechanics.BEBehaviorMPTransmission.ChangeState(Boolean newEngaged) in VSSurvivalMod\Systems\MechanicalPower\BlockEntityBehavior\BEBehaviorTransmission.cs:line 127
   at Vintagestory.GameContent.Mechanics.BEBehaviorMPTransmission.CheckEngaged(IBlockAccessor access, Boolean updateNetwork) in VSSurvivalMod\Systems\MechanicalPower\BlockEntityBehavior\BEBehaviorTransmission.cs:line 89
   at Vintagestory.GameContent.Mechanics.BEClutch.OnInteract(IPlayer byPlayer) in VSSurvivalMod\Systems\MechanicalPower\BlockEntity\BEClutch.cs:line 216
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 890
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 536
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 86
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 201
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1174
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1362
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 202
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 718
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 622
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 124
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 1/21/2023 10:07:27 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangTransient
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 63501532
P4: unknown
P5: unknown
P6: unknown
P7: unknown
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2743.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2773.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2772.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER27A2.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 7fb48016-3c13-428c-ad15-0941f5155749
Report Status: 2049
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 1/15/2023 6:27:42 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1632951646305068015, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\rhauk\AppData\Local\Temp\RDRD73D.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD73E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD74F.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD760.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD790.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9d5f92fe-4f73-4f4a-a579-a76d912e2901
Report Status: 268435456
Hashed bucket: 1dc75c8e8b60a89926a968dedd6723ef
Cab Guid: 0 }
--------------
{ TimeGenerated = 1/15/2023 11:17:28 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangTransient
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 63501532
P4: unknown
P5: unknown
P6: unknown
P7: unknown
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAFEF.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB01F.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB01E.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB05D.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 48329c12-5ecd-4bd6-99eb-7f00680f9944
Report Status: 2049
Hashed bucket: 
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
Closing due to inactivity
