### ISSUE TITLE
Modding in a new firestarter causes crash

### ISSUE THREAD

**Issue by SunnyOpossum** [anegostudios/VintageStory-Issues#2361]
### Game Version

v1.17.10

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

An item in your mod with the class "ItemFirestarter" will cause a crash when looking at a block that can be lit with a firestarter. Causes crash when the item in either assets/modname/itemtypes or assets/game/itemtypes.

### How to reproduce

1. Create an item json file 
2. Define class as "ItemFirestarter"
3. Look at a block that can be lit with a firestarter (such as an extinguished torch)

### Logs

```Game Version: v1.17.10 (Stable)
1/29/2023 3:09:15 PM: Critical error occurred
Loaded Mods: uncaves@0.0.1, game@1.17.10, creative@1.17.10, survival@1.17.10
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetTextureAtlasPosition(ClientMain game, IItemStack itemstack) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 414
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 368
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Single dt, Boolean shading, Boolean origRotate, Boolean showStackSize) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 197
   at Vintagestory.Client.NoObf.RenderAPIGame.RenderItemstackToGui(ItemStack itemstack, Double posX, Double posY, Double posZ, Single size, Int32 color, Boolean shading, Boolean rotate, Boolean showStacksize) in VintagestoryLib\Client\API\RenderAPIGame.cs:line 274
   at Vintagestory.Client.NoObf.DrawWorldInteractionUtil.<>c__DisplayClass11_1.<ComposeBlockWorldInteractionHelp>b__0(Single dt, ElementBounds bounds) in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockInteractionHelp.cs:line 91
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 709
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 373
   at Vintagestory.API.Client.HudElement.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\HudElement.cs:line 30
   at Vintagestory.Client.NoObf.HudElementBlockInteractionHelp.OnRenderGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockInteractionHelp.cs:line 439
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 302
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 191
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1174
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1348
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 202
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 718
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 622
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 124
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93```

**Comment by Craluminum2413** [comment]
Could you send json file of your firestarter?

**Comment by SunnyOpossum** [comment]
{
	code: "cavefirestarter",
	class: "ItemFirestarter",
	attributes: {
		groundStorageTransform: {
			translation: { x: 0, y: -0.06, z: 0.035 },
			rotation: { x: 108, y: 45, z: -180 },
			scale: 0.81
		}
	},
	behaviors: [{ 
		name: "GroundStorable",
		properties: {
			layout: 'WallHalves',
			wallOffY: 1,
			sprintKey: true,
			selectionBox: { x1: 0, y1: 0, z1: 0, x2: 1, y2: 0.1, z2: 1 },
			collisionBox: { x1: 0, y1: 0, z1: 0, x2: 0, y2: 0, z2: 0 },
		}
	}],
	shape: { base: "game:item/tool/firestarter" },
	textures: {
		"singlehay2": { base: "plants/leaves-caveshrub-2" },
		"oak": { base: "resources/debarkcave" },
		"normal-top": { base: "resources/cavestring" }
	},
	heldTpHitAnimation: "breaktool",
	durability: 40,
	creativeinventory: { "general": ["*"], "items": ["*"], "tools": ["*"] },
	guiTransform: {
		translation: { x: 0, y: 0, z: 0 },
		rotation: { x: -42, y: -2, z: -180 },
		origin: { x: 0.55, y: 0.3, z: 0.5 },
		scale: 1.5
	},
	fpHandTransform: {
		translation: { x: 0, y: 0, z: 0 },
		rotation: { x: 14, y: -11, z: 1 },
		scale: 1.42
	},
	groundTransform: {
		translation: { x: 0, y: 0, z: 0 },
		rotation: { x: 90, y: 0, z: 45 },
		origin: { x: 0.51, y: 0, z: 0.5 },
		scale: 3.6
	},
	tpHandTransform: {
		translation: { x: -1.05, y: -0.12, z: -0.95 },
		rotation: { x: -14, y: -141, z: 0 },
		origin: { x: 0.5, y: 0, z: 0.5 },
		scale: 0.52
	}
}

**Comment by SunnyOpossum** [comment]
Sorry for the delay, I dont check github too often

**Comment by Craluminum2413** [comment]
Have you checked if your textures lead to `moddomain:textures/plants/leaves-caveshrub-2.png` etc.?
```json
textures: {
"singlehay2": { base: "plants/leaves-caveshrub-2" },
"oak": { base: "resources/debarkcave" },
"normal-top": { base: "resources/cavestring" }
},
```

**Comment by SunnyOpossum** [comment]
Yes, the textures are working just fine https://cdn.discordapp.com/attachments/868621869509656607/1077324293412769925/image.png

**Comment by Craluminum2413** [comment]
Closing due to inactivity
