### ISSUE TITLE
playable but annoying 

### ISSUE THREAD

**Issue by reaverreaper** [anegostudios/VintageStory-Issues#2365]
### Game Version

1.17.10

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

with and withoutmods 

getting host not responding server error or overload error, lag in picking up items, animals either not moving or rubberband

### Logs

```Log```

**Comment by reaverreaper** [comment]
Running on 64 bit Windows with 12 GB RAM 
Game Version: v1.17.10 (Stable)
2/2/2023 11:58:35 PM: Critical error occurred
Loaded Mods: game@1.17.10, creative@1.17.10, survival@1.17.10
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.WeatherSystemClient.OnRenderFrame(Single dt, EnumRenderStage stage) in VSEssentials\Systems\Weather\WeatherSystemClient.cs:line 131
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 201
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1174
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1216
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1103
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 123
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 678
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 622
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 124
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2/2/2023 2:54:14 AM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.17.10.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: b60

Start Time: 01d936d23259d3c0

Termination Time: 4329

Application Path: C:\Users\name\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: 1f327c24-1fb7-454f-a8f2-850e45b13e59

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 1/27/2023 11:28:24 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2009216382812850656, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.10.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\name\AppData\Local\Temp\RDR9221.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER928F.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER92DE.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER938F.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER93DE.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 398840fb-91b3-48a0-b37a-f6be8256ca9f
Report Status: 268435456
Hashed bucket: 51c702eadadf948febe22ba7a67489e0
Cab Guid: 0 }
--------------
{ TimeGenerated = 1/26/2023 4:07:20 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1938568505527818434, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.10.0
P3: 63bbdc3a
P4: Vintagestory
P5: 1.17.10.0
P6: 63bbdc3a
P7: 1c
P8: 2f
P9: System.IO.FileLoadException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3BC7.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_99eeb56d5a7d352bb5146d36b1a74ab139e9d1_90e27403_f230c56b-4ad0-460a-9956-65d5985e2157

Analysis symbol: 
Rechecking for solution: 0
Report Id: bc222e24-5c2f-40ef-94c1-24c28702d079
Report Status: 268435456
Hashed bucket: 2028869da129ab16eae72dc8e8bed8c2
Cab Guid: 0 }

**Comment by PaulBlay** [comment]
I am familiar with this from playing on a popular server when there are a lot of people online. Pretty sure it doesn't happen when there are only a few on.

**Comment by smilensilly** [comment]
After purchasing, playing and hosting my own server, this is not limited to high population servers.  I host this on a Dell R815 with far more resources than is / should be required.  It sits on a 10GB LAN and my gaming PC is more than capable to handle this game.   It happens when I play solo on the server just as when there are a few of us.  The biggest impact to the frequency seems to be creating a reduced world size out of sheer frustration, but that was short lived once everyone starts exploring.  It is most relevant while saving server side and people are running amuck enjoying them selves. But then it comes in 30-60 second issues while opening or closing chest, looting animals causing them to glitch and loot be lost. 
Information about this issue is sparse and difficult to find, but there is some.  The oldest report I found was in 2020.  I have seen a few suggestions and tried them with 0 success.  
I have played a lot of early Alpha games, I truly enjoy them and prefer them over the current pay to beta test  A titles of today.  This seems to be an issues that has been part of many i have played in early stages, in the many limited responses by Devs in those games it almost always had to do with back end networking.  I am not a programmer, but I have been hosting games for a long time and know a bit about networking and hardware and it is not causing this issue.  
I would have hoped this issue would get some serious attention by now.  It is minimal at first, but the longer you play the more of a "silly issue to have" it becomes.  It quite honestly is holding the game back and I would imagine creates a "this sucks" mentality and cause many to quit playing. My buddies and I that picked this up truly enjoy the game and have gotten into playing around with mods.  Oddly this that has not made the issues worse, which tells me it is at the core of the game.  I hope someone addresses it soon.  If someone is willing to truly address this issue i will be more than happy to provide them with any screen shots, logs or whatever is needed to work with and help resolve the issue.

**Comment by smilensilly** [comment]
![image](https://user-images.githubusercontent.com/46857020/221381761-d6f44222-c84d-4311-9d9e-34fc253e3b04.png)

**Comment by reaverreaper** [comment]
single player and yet i have a server? it was running fine again for the past two weeks and then the problem appeared again

**Comment by Craluminum2413** [comment]
@reaverreaper Send those files here

**Comment by reaverreaper** [comment]
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/10837940/client-crash.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/10837943/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/10837944/server-main.txt)

**Comment by smilensilly** [comment]
It does at this time, i played quite a bit without any at first.  Oddly installing the mods did not negatively impact this issue.  It is there either way.

**Comment by reaverreaper** [comment]
with or without mods my singleplayer world has host not responding

**Comment by Craluminum2413** [comment]
Closing due to inactivity
