### ISSUE TITLE
Game Crashes-Critical Error

### ISSUE THREAD

**Issue by deedenis31** [anegostudios/VintageStory-Issues#2366]
### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Was forced to wipe my laptop after the latest Windows update "bricked" my laptop. As expected, all my files, apps and programs were deleted from the reset. Installed the latest version without any issues but encountered the following message when I attempted to launch the program: 
Game Version: v1.17.10 (Stable)
2/2/2023 11:16:50 PM: Critical error occurred
Loaded Mods: 
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 94

Then deleted Vintage story completely and tried to do a fresh install using v.1.17.9 and received the same message as before: 
2/2/2023 11:57:13 PM: Critical error occurred
Loaded Mods: 
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 94

Right now I am unable to launch the application. Please help

### How to reproduce

1. Click on the Vintage Story Shortcut located on the desktop

**Comment by deedenis31** [comment]
Resolved...updated windows, uninstalled then installed v1.17.8.
