### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by FrankRock80** [anegostudios/VintageStory-Issues#2367]
### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I play this game with mods it worked fine at first then i got this error I do not know what to do to fix it i first thought it was due to cobl mods which i removed not realizing i had some but is there still cobl mods or something? please help

### How to reproduce

i'm not sure how

### Screenshots

![Screenshot (1)](https://user-images.githubusercontent.com/124549898/216890259-5ad447a2-1d56-4c54-9f7a-5474f66ca8a8.png)
![Screenshot (4)](https://user-images.githubusercontent.com/124549898/216890629-1782ee97-5f10-44d2-a33c-c834cd148dac.png)
![Screenshot (6)](https://user-images.githubusercontent.com/124549898/216890760-03381c23-b4cf-4854-a041-ea1d5faae15a.png)
![Screenshot (7)](https://user-images.githubusercontent.com/124549898/216890967-1f96a063-3e99-454f-b610-e0edef19a422.png)
![Screenshot (8)](https://user-images.githubusercontent.com/124549898/216891043-65ee2ce4-e404-4575-a220-b5526ef591dc.png)
![Screenshot (9)](https://user-images.githubusercontent.com/124549898/216891067-53581c6e-85f5-4279-9928-d63048c95afd.png)

### Logs

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.10 (Stable)
2/5/2023 11:48:55 PM: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.11, advancedsmithing@1.3.0, ancienttools@1.4.9, ArmorRework@1.0.2, arrowheadsrecovery@1.0.1, atwatersedge@1.2.1, axleinblocks@1.0.13, hgnewlandforms@2.0.2, betterberries@1.0.1, bettercrates@1.5.3, BetterGrass@0.0.1, bettershears@1.0.0, bike@1.1.2, brigandinerebalance@1.0.0, buildersblocks@1.0.0, buildinggadgets@0.3.0, bushmeat_meals@1.0.7, bushmeatpemmican@0.1.3, cellardoor@1.3.0, Ceramos@0.2.4, chiseltools@1.7.2, claims@0.1.16, composter@1.0.4, connectedblocks@1.0.0, cwcolors@1.0.9, cwmodular@1.0.9, cottagewindows@1.0.9, cwtall@1.0.9, cwwide@1.0.9, craftablesticks@1.0.0, cralutweaks@1.0.2, dragonflies@1.2.0, DeepStorage@0.0.1, djsvanillatools@1.0.4, drdecor@1.1.0, driedpeat@1.0.2, emotemenu@1.0.4, evaporite@1.0.0, extrachests@1.6.2, ezbread@1.4.0, fancysky@1.0.4, fancytools@0.4.0, morecrops@1.0.2, quickerbarrel@1.1.1, fastermetal@1.0.0, fieldsofgold@2.1.4, fireclayfrompanning@1.0.0, flagsmaterials@1.1.1, FlexibleTools@2.0.0, furniturelibrary@1.0.6, weaponpackg@1.0.1, gravelsandfix@1.0.2, harptech@0.2.3, hideandfabric@1.2.9, HoneyPress@1.1.1, hqzlights@1.0.0, HumanSkinTones@0.0.3, burntimetimes3@1.0.0, indappledgroves@0.4.7, instruments@1.1.4, juicyores@1.0.0, justmoreruins@0.4.0, knappingmastery@1.0.1, lantern@2.0.2, lascaux@1.0.1, layoftheland@1.0.0, leaflanternlining@1.0.0, longerburntime@1.0.0, longertorchtime@1.0.0, lumbersling@1.0.0, medieval@1.1.1, midnight-texturepack@1.1.0, mineralinguistics@1.0.0, books@1.2.6, moreanimalloot@1.0.0, GreaterChanceForTerraPretaX40@0.4.0, moreclasses@1.2.5, moreclay@1.0.1, potatoes@1.0.8, moredrygrass@0.2.0, morefirewood@1.0.0, moreminerals@1.0.3, leadroof@1.2.4, moretreesmoreseeds@1.0.0, moremeat@1.2.0, mysticalmetals@1.0.1, naturalpatchesdense@0.0.2, necessariesfix@1.1.3-rc.1, neededthings@1.0.0, neosadditions@1.0.2-rc.1, nomadmodemod@1.0.8, oildeposits@1.2.1, OresAPlenty@3.0.0, pikaclothes@0.3.5, plantmat@1.4.0, primitivesurvival@3.0.4, qptech@1.12.26, qptechapi@1.1.0, quarryworks@1.4.8, quickstep@1.0.1, ragnamans-seeds-from-crops-recipes@1.0.0, ReducedDrifterGroupsandLightLevelSpawn@1.0.0, shinglesandthethings@1.0.2-rc.1, rope-bridges@1.1.0, ropebucket@1.0.0, rustandrails@1.0.4, ruststones@1.0.2, seedharvest@1.0.0, sexyswords@0.1.2, simplealchemy@2.0.5, simpleelevator@1.3.0, sleevesdecor@1.0.2, riflemod@1.0.0, smokychimneys@1.0.0, sortablestorage@1.6.0, spidersilk@1.2.2, spyglass@0.4.5, stablecandles@1.0.0, sterilebandages@1.0.0, superfuel@2.0.7, tailor@0.1.0, temperaturescales@1.0.1, locustmod@2.3.6, thecritterpack@0.7.6, tieredsoil@1.0.0, tradeomat@1.6.3, translocatorengineeringredux@1.3.0, trkstr@1.0.0, Unbreakable_Arrows@1.0.0, usefulscrap@2.0.2, veganmilksimplified@1.0.1, vtpp@1.0.0, game@1.17.10, whetstone@1.1.1, wildcrafttrees@1.1.4, wildcraft@1.5.1, witchsticks@1.0.2, zeekea@1.6.2, zoombuttonreborn@1.3.0, alchemy@1.6.6, arrowsmelt@1.0.0, attachit@1.0.0, beehivekiln@1.2.1, bigpainting@1.1.0, bonfires@0.2.0, calendar@1.0.0, captureanimals@2.3.0, carrycapacity@0.6.5, carryon@0.10.3, carryonmore@1.3.1, claimsext@0.2.3, claycrafting@1.0.1, claywheel@1.0.0, coinage@1.0.2, cosmosis@0.5.0, cuniculture@1.0.1, darkerdrifterspawns@1.0.1, diamondcrate@1.0.1, dreamcatchers@1.5.1, driftersounds@1.0.0, dsdebarkedlogs@1.0.7, dssilicatebricks@1.0.1, electricity@0.0.4, expandedfoods@1.6.4, exlico@1.1.0, extrachutes@1.0.0, extrajuice@1.0.1, fancyplanters@1.0.5, fartempleaxe@1.0.0, foolshat@1.0.0, fromgoldencombs@1.3.15, hammersringingfall@1.2.5, harphoh@1.1.0, helvehammerext@1.3.1, hudclock@2.8.0, immersivecrafting@1.1.0, jlj@1.0.3, keg@1.0.1, khat@1.0.0, kilnspreading@1.0.0, kilntimeviewer@1.0.0, knifecut@1.2.0, lc@1.0.0, lecheesedecubique@1.0.0, lessclasspenalties@1.0.0, lichen@1.6.2, liquidcontainers@1.1.0, medievalexpansion@3.8.1, moreicons@1.0.3, moreanimals@1.2.3, morebags@1.2.0, moredoor@1.0.0, morepiles@1.2.2, mcrate@1.0.4, obviousresin@1.0.0, outlawmodredux@1.2.3, paxel@1.1.1, petai@1.5.5, postsandbeams@1.1.0, prospectorinfo@4.1.2, rainbowroads@1.0.1, resmeltableslight@1.0.0, resinlights@1.0.0, roadworks@1.0.9, rocksalt@1.0.1, signals@0.1.1, SimpleMobFootStepsUpdate@1.0.1, SimpleMobFootSteps@1.0.3, sleevesblox@1.0.5, slidingdoor@1.0.0, smeltableingots@1.0.0, spearfix@1.0.0, ssppvv@1.0.3, stonequarry@2.0.0-rc.4, stonerailings@1.0.4, tabletopgames@1.2.0, targetDotMedium@1.1.0, techmolds@1.0.0, tprunes@1.0.7, temporalmirror@1.7.0, th3expansion@1.0.2, thatch@1.0.0, usefulstuff17@1.0.2, vanvar@2.0.1, vesselbuff@1.0.4, sacks@0.9.4, creative@1.17.10, vsmovemod@1.0.95, survival@1.17.10, vsvillage@0.6.0, weaversweed@0.4.17, woodbarrels@1.0.4, woodchests@1.0.4, woodfp@1.0.0, wopbecreative@0.0.1, wopnaturalvanilladecorations@0.0.1, workbenchexpansion@1.5.1, xmelee@0.0.10, xorberax-shader-mod@0.7.0, xorberax-bloodmod@0.3.2, xrowboat@0.0.5, metalrecovery@0.1.18-rc.2, campaigncartographer@3.1.2, knapster@2.3.1, blacksmiths@0.3.0-pre.1, bullseye@2.4.1, cats@1.5.3, debarkfix@1.0.1, defensive@0.1.7-pre.0, depositstretcher@0.1.1, doffanddonagain@2.0.0, em@1.1.1, ferrospear@1.0.1, feverstonehorses@1.3.9-rc.2, feverstonewilds@1.0.9, foxtaming@1.2.0, frames@0.0.2, glassmaking@1.3.3, linearpower@0.2.0, morecandles@1.0.3, onestick@1.0.1, packanimals@1.0.1, ensisswordpack@2.0.0, stonepiles@1.0.6, sacksroadworks@0.9.4, wolftaming@1.5.4, bricklayers@1.2.1, moreroads@1.5.1, bricklayerglassmakingcompat@1.0.2, coloredjugs@1.0.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockLiquidContainerTopOpened.get_CapacityLitres() in VSSurvivalMod\Systems\Liquid\BlockLiquidContainerBase.cs:line 28
   at Vintagestory.GameContent.BlockFruitPress.<>c__DisplayClass3_0.<OnLoaded>b__1() in VSSurvivalMod\Block\BlockFruitPress.cs:line 39
   at Vintagestory.API.Util.ObjectCacheUtil.GetOrCreate[T](ICoreAPI api, String key, CreateCachableObjectDelegate`1 onRequireCreate) in VintagestoryApi\Util\ObjectCacheUtil.cs:line 29
   at Vintagestory.GameContent.BlockFruitPress.<>c__DisplayClass3_0.<OnLoaded>b__0() in VSSurvivalMod\Block\BlockFruitPress.cs:line 32
   at Vintagestory.Server.ServerMain.ProcessMainThreadTasks() in VintagestoryLib\Server\ServerMain.cs:line 2655
   at Vintagestory.Server.ServerMain.ProcessMain() in VintagestoryLib\Server\ServerMain.cs:line 828
   at Vintagestory.Server.ServerMain.Stop(String reason) in VintagestoryLib\Server\ServerMain.cs:line 1049
   at Vintagestory.Client.ClientProgram.ServerThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2/5/2023 11:48:55 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.GameContent.BlockLiquidContainerTopOpened.get_CapacityLitres()
   at Vintagestory.GameContent.BlockFruitPress+<>c__DisplayClass3_0.<OnLoaded>b__1()
   at Vintagestory.API.Util.ObjectCacheUtil.GetOrCreate[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Vintagestory.API.Common.ICoreAPI, System.String, Vintagestory.API.Util.CreateCachableObjectDelegate`1<System.__Canon>)
   at Vintagestory.GameContent.BlockFruitPress+<>c__DisplayClass3_0.<OnLoaded>b__0()
   at Vintagestory.Server.ServerMain.ProcessMainThreadTasks()
   at Vintagestory.Server.ServerMain.ProcessMain()
   at Vintagestory.Server.ServerMain.Stop(System.String)
   at Vintagestory.Client.ClientProgram.ServerThreadStart()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

 }
--------------
{ TimeGenerated = 2/5/2023 11:33:16 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.GameContent.BlockLiquidContainerTopOpened.get_CapacityLitres()
   at Vintagestory.GameContent.BlockFruitPress+<>c__DisplayClass3_0.<OnLoaded>b__1()
   at Vintagestory.API.Util.ObjectCacheUtil.GetOrCreate[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Vintagestory.API.Common.ICoreAPI, System.String, Vintagestory.API.Util.CreateCachableObjectDelegate`1<System.__Canon>)
   at Vintagestory.GameContent.BlockFruitPress+<>c__DisplayClass3_0.<OnLoaded>b__0()
   at Vintagestory.Server.ServerMain.ProcessMainThreadTasks()
   at Vintagestory.Server.ServerMain.ProcessMain()
   at Vintagestory.Server.ServerMain.Stop(System.String)
   at Vintagestory.Client.ClientProgram.ServerThreadStart()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

 }
--------------
{ TimeGenerated = 2/5/2023 11:02:43 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.GameContent.BlockLiquidContainerTopOpened.get_CapacityLitres()
   at Vintagestory.GameContent.BlockFruitPress+<>c__DisplayClass3_0.<OnLoaded>b__1()
   at Vintagestory.API.Util.ObjectCacheUtil.GetOrCreate[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Vintagestory.API.Common.ICoreAPI, System.String, Vintagestory.API.Util.CreateCachableObjectDelegate`1<System.__Canon>)
   at Vintagestory.GameContent.BlockFruitPress+<>c__DisplayClass3_0.<OnLoaded>b__0()
   at Vintagestory.Server.ServerMain.ProcessMainThreadTasks()
   at Vintagestory.Server.ServerMain.ProcessMain()
   at Vintagestory.Server.ServerMain.Stop(System.String)
   at Vintagestory.Client.ClientProgram.ServerThreadStart()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

 }

**Comment by Craluminum2413** [comment]
Could you try to reproduce it without mods?

**Comment by FrankRock80** [comment]
I cant reproduce it it works fine without mods it was working fine with the mods at first then this happened

**Comment by Craluminum2413** [comment]
It looks like it is related to fruit press

**Comment by FrankRock80** [comment]
ok
i'll check it

**Comment by Craluminum2413** [comment]
Closing due to inactivity
