### ISSUE TITLE
Crash on trying to load any world after launching 1.17.11-rc.1 at least once

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#2369]
### Game Version

v1.17.11

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Removed `clientsettings.json` and `serverconfig.json`, it didn't help

### How to reproduce

1. Start the game in 1.17.11-rc.1
2. Close the game
3. Start the game in 1.17.11 Stable
4. Create new world or load existing world
5. It crashes

### Logs

```Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.11 (Stable)
2023-02-06 17:36:38: Critical error occurred
Loaded Mods: game@1.17.11, stepup@1.2.0, creative@1.17.11, survival@1.17.11
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.Client.NoObf.ClientMain.UpdateFreeMouse() in VintagestoryLib\Client\ClientMain.cs:line 2372
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1186
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1104
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 125
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 680
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 624
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 131
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93```

**Comment by Nyuhnyash** [comment]
Reset your controls before loading the world.

**Comment by Craluminum2413** [comment]
@Nyuhnyash Thanks, it helped
