### ISSUE TITLE
VintagestoryAPI classes/methods differ between net462 & net7

### ISSUE THREAD

**Issue by DoctorVanGogh** [anegostudios/VintageStory-Issues#2372]
### Game Version

1.17.11-(rc1)

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Some `VintagestoryAPI` classes have different signatures between 1.17.11 (net462) and 1.17.11-rc1 (net7).

Specifically noticed this with `Vintagestory.API.Client.IInputAPI`:

| Version | Signature |
|---|---|
| 1.17.11 <br/> (net462) |  `void RegisterHotKey(string hotkeyCode, string name, GlKeys key, HotkeyType type = HotkeyType.CharacterControls, bool altPressed = false, bool ctrlPressed = false, bool shiftPressed = false);` | 
| 1.17.11-rc1 <br/> (net7) | `void RegisterHotKey(string hotkeyCode, string name, Keys key, HotkeyType type = HotkeyType.CharacterControls, bool altPressed = false, bool ctrlPressed = false, bool shiftPressed = false);` |

Note how `GlKeys` has become `Keys`.

Same change also applies to the `RegisterHotKeyFirst` method.

---

Noticed this when trying to run my usual mod set on the net7 client. HudClock blew :un

### How to reproduce

Look at source code - or dnSpy ;)

### Logs

```
06.02.2023 18:23:17: Critical error occurred in the following mod: hudclock@2.8.0
Loaded Mods: autoclose@1.0.1, backpackpack@1.0.3, carcassesdropbones@1.0.0, composter@1.0.4, orepulverizer@1.1.1, pieontheshelf@1.0.0, potontheshelf@1.0.0, primitivesurvival@3.1.1, rope-bridges@1.1.0, ropebucket@1.0.0, specializedbags-18Slot@0.4.2, vtpp@1.0.0, vgaas@1.0.1, volumetricshading@0.7.0, game@1.17.11-rc.1, additionalmolds@1.0.1, carryon@0.10.3, claywheel@1.0.0, farmlanddropssoil@1.4.0, hudclock@2.8.0, prospectorinfo@4.1.2, stepup@1.2.0, stonerailings@1.0.4, translocatorlocator@1.0.2-dirty, useplanksinpitkiln@1.0.0, sacks@0.9.4, vsborderless@0.1.0-alpha, creative@1.17.11-rc.1, survival@1.17.11-rc.1, wildfarming@1.2.1, woodchests@1.0.4, aculinaryartillery@1.0.11, metalrecovery@0.1.18-rc.2, campaigncartographer@3.1.2, expandedfoods@1.6.5
System.MissingMethodException: Method not found: 'Void Vintagestory.API.Client.IInputAPI.RegisterHotKey(System.String, System.String, Vintagestory.API.Client.GlKeys, Vintagestory.API.Client.HotkeyType, Boolean, Boolean, Boolean)'.
   at hudclock.src.busineslogic.ClockModSettingsController.RegisterHotKey()
   at hudclock.src.busineslogic.ClockModSettingsController..ctor(ICoreClientAPI clientApi) in D:\development\VintageStoryMods\solution\Mods\hudclock\src\busineslogic\ClockModSettingsController.cs:line 31
   at hudlock.src.HUDClockMod.PlayerReady(EnumHandling& handling) in D:\development\VintageStoryMods\solution\Mods\hudclock\src\HUDClockMod.cs:line 39
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerIsPlayerReady() in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\API\ClientEventAPI.cs:line 352
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(Packet_Server packet) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 710
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\Systems\NetworkProcess.cs:line 443
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\Systems\NetworkProcess.cs:line 437
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientMain.cs:line 1173
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 435
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ScreenManager.cs:line 658
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ScreenManager.cs:line 633
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 65
   at OpenTK.Windowing.Desktop.GameWindow.DispatchRenderFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientProgram.cs:line 320
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientProgram.cs:line 149
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Th3Dilli** [comment]
this was not intentional to break the API and is sorta related to #2368

**Comment by Th3Dilli** [comment]
thank you for bringing this up, while we can revert the methode signature wich will prevent the the game from crashing the keycodes have changed, so they wont work.
Either the player has to manually reasign them or the mod needs to be recompiled

Here are the relevant enums for reference
OpenTK3:
https://github.com/opentk/opentk/blob/3.x/src/OpenTK/Input/Key.cs
OpenTK4
https://github.com/opentk/opentk/blob/master/src/OpenTK.Windowing.GraphicsLibraryFramework/Enums/Keys.cs

**Comment by Th3Dilli** [comment]
alright we now implemented the keyhandling so there are no changes to the API and old net46 mods will work fine on net7
