### ISSUE TITLE
Crash in CloudRenderer on startup in dotnet7 experimental - oneoff

### ISSUE THREAD

**Issue by hlangeveld** [anegostudios/VintageStory-Issues#2379]
### Game Version

dotnet7 experimental 1.17.11

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Crash on loading my dedicated dotnet7 savegame, which is a clone from my original 1.17 savegame (created in 1.17.9)

Log suggests a problem with CloudRenderer.

### How to reproduce

Unsure if this is reproducable.
After saving the log, I restarted the game and it started properly.

That suggests some kind of race condition.

### Logs

```
Running on 64 bit Windows with 16121 MB RAM
Game Version: .net7 Experimental build - v1.17.11-rc.1 (Unstable)
13/02/2023 01:04:27: Critical error occurred
Loaded Mods: game@1.17.11-rc.1, prospectorinfo@3.2.0, creative@1.17.11-rc.1, survival@1.17.11-rc.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Vintagestory.Client.NoObf.ClientWorldMap.GetMapRegion(Int32 regionX, Int32 regionZ) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientWorldMap.cs:line 1267
   at Vintagestory.GameContent.WeatherSystemBase.getOrCreateWeatherSimForRegion(Int32 regionX, Int32 regionZ) in C:\Users\Tyron\Documents\vintagestory\game-net7\VSEssentials\Systems\Weather\WeatherSystemBase.cs:line 198
   at Vintagestory.GameContent.WeatherDataReaderBase.LoadAdjacentSims(Vec3d pos) in C:\Users\Tyron\Documents\vintagestory\game-net7\VSEssentials\Systems\Weather\WeatherDataReader.cs:line 186
   at Vintagestory.GameContent.CloudRenderer.UpdateCloudTilesOffThread(Int32 changeSpeed) in C:\Users\Tyron\Documents\vintagestory\game-net7\VSEssentials\Systems\Weather\CloudRenderer.cs:line 396
   at Vintagestory.GameContent.CloudRenderer.<.ctor>b__31_2() in C:\Users\Tyron\Documents\vintagestory\game-net7\VSEssentials\Systems\Weather\CloudRenderer.cs:line 164
```****

**Comment by hlangeveld** [comment]
Maybe I was looking at clouds during save?

No new occurrence though. Low prio.

**Comment by Craluminum2413** [comment]
Related #2196

**Comment by Craluminum2413** [comment]
Closing due to inactivity
