### ISSUE TITLE
The game (client) crashes when entering a server that require a password

### ISSUE THREAD

**Issue by KDeWals** [anegostudios/VintageStory-Issues#2380]
### Game Version

v1.17.11

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

When entering into a server that require a password, the client crashes.
The client let me go in the server when i disable the password

### How to reproduce

1. Launching the server
2. Going into the server with the client and noticing that everything works alright
3. Logging out
4. Enable the password restriction in the server with the command /serverconfig password <password>
5. Try to reconnect with the client 
6. The client crashes

### Logs

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.11 (Stable)
13-02-23 19:10:52: Critical error occurred
Loaded Mods: 
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) dans VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:ligne 407
   à Vintagestory.Client.ScreenManager.Render(Single dt) dans VintagestoryLib\Client\ScreenManager.cs:ligne 718
   à Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) dans VintagestoryLib\Client\ScreenManager.cs:ligne 622
   à Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) dans VintagestoryLib\Client\ClientPlatform\GameWindow.cs:ligne 124
   à System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   à OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) dans C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:ligne 476
   à OpenTK.GameWindow.DispatchRenderFrame() dans C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:ligne 452
   à OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) dans C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:ligne 375
   à Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   à Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) dans VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:ligne 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10-02-23 10:53:06, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.17.9.0, horodatage : 0x63501532
Nom du module défaillant : KERNELBASE.dll, version : 10.0.19041.2193, horodatage : 0x7f7062e1
Code d’exception : 0xe0434352
Décalage d’erreur : 0x000000000002cd29
ID du processus défaillant : 0x4404
Heure de début de l’application défaillante : 0x01d93d357944a73a
Chemin d’accès de l’application défaillante : D:\Games\Vintage.Story.v1.17.9\Vintagestory.exe
Chemin d’accès du module défaillant: C:\WINDOWS\System32\KERNELBASE.dll
ID de rapport : e3ba3f2a-c488-4764-bf28-ec92bc715fdf
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }
--------------
{ TimeGenerated = 10-02-23 10:53:06, Site = , Source = .NET Runtime, Message = Application : Vintagestory.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.NotSupportedException

Informations sur l'exception : System.IO.FileLoadException
   à System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   à System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   à System.Reflection.RuntimeAssembly.InternalLoadFrom(System.String, System.Security.Policy.Evidence, Byte[], System.Configuration.Assemblies.AssemblyHashAlgorithm, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   à System.Reflection.Assembly.LoadFrom(System.String)
   à Vintagestory.Client.ClientProgram.AssemblyResolve(System.Object, System.ResolveEventArgs)

Informations sur l'exception : System.Exception
   à Vintagestory.Client.ClientProgram.AssemblyResolve(System.Object, System.ResolveEventArgs)
   à System.AppDomain.OnAssemblyResolveEvent(System.Reflection.RuntimeAssembly, System.String)

Informations sur l'exception : System.IO.FileLoadException
   à Vintagestory.Client.ClientProgram..ctor(System.String[])
   à Vintagestory.Client.ClientProgram.Main(System.String[])

 }
--------------
{ TimeGenerated = 10-02-23 10:52:28, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.17.9.0, horodatage : 0x63501532
Nom du module défaillant : KERNELBASE.dll, version : 10.0.19041.2193, horodatage : 0x7f7062e1
Code d’exception : 0xe0434352
Décalage d’erreur : 0x000000000002cd29
ID du processus défaillant : 0x2644
Heure de début de l’application défaillante : 0x01d93d356286990e
Chemin d’accès de l’application défaillante : D:\Games\Vintage.Story.v1.17.9\Vintagestory.exe
Chemin d’accès du module défaillant: C:\WINDOWS\System32\KERNELBASE.dll
ID de rapport : 862e66d1-92c7-484c-82ea-b4e21ddec620
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }

**Comment by spielerflo97330** [comment]
Cool das alles wegen duplikaten geschlossen wird, aber wie kann man diesem dämlichen Bug jetzt umgehen?

**Comment by Craluminum2413** [comment]
@spielerflo97330 What mods are you using when you get this error?

**Comment by BASIC-BIT** [comment]
I had this error, read the Issues, and I found a fix after struggling for a bit- so, I'll share my experience.

I had `1.18.0-pre.6` installed on my computer, and was trying to join a multiplayer server I thought was running on the same version, but was actually still running `1.17.11`.

Upon trying to join, I crashed.  Here's the crash log:
```
Game Version: v1.18.0-pre.6 (Unstable)
3/15/2023 9:59:17 AM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.GuiScreenConnectingToServer.exitToDisconnectScreen() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 427
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 715
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 618
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Game Version: v1.18.0-pre.6 (Unstable)
3/15/2023 10:00:49 AM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.GuiScreenConnectingToServer.exitToDisconnectScreen() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 427
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 715
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 618
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Game Version: v1.18.0-pre.6 (Unstable)
3/15/2023 10:07:48 AM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.GuiScreenConnectingToServer.exitToDisconnectScreen() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 427
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 715
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 618
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Game Version: v1.18.0-pre.6 (Unstable)
3/15/2023 9:41:09 PM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.GuiScreenConnectingToServer.exitToDisconnectScreen() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 427
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 715
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 618
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Game Version: v1.18.0-pre.6 (Unstable)
3/15/2023 9:45:01 PM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.GuiScreenConnectingToServer.exitToDisconnectScreen() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 427
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 715
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 618
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Game Version: v1.18.0-pre.6 (Unstable)
3/15/2023 9:50:41 PM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.GuiScreenConnectingToServer.exitToDisconnectScreen() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 427
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 715
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 618
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Game Version: v1.18.0-pre.6 (Unstable)
3/15/2023 9:52:28 PM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.GuiScreenConnectingToServer.exitToDisconnectScreen() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 427
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 715
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 618
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Game Version: v1.18.0-pre.6 (Unstable)
3/15/2023 9:53:04 PM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.GuiScreenConnectingToServer.exitToDisconnectScreen() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 427
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 715
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 618
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

Detailed Reason: Obviously I should have figured out that the server wasn't on the same version, I had no obvious indications in the client until I finally looked at the server logs.  I'm running a dedicated server on a Pterodactyl server, and I was using an old version of the Vintage Story egg.  On an existing server being ported from `1.17.11`, even with no mods and a new world; I set the version setting to `1.18.0-pre.6`, and reinstalled, thinking that it would work.  It didn't.  Eventually I tried my Vintage Story egg in PT with the new updates from [Parkers Pterodactyl eggs repo](https://github.com/parkervcp/eggs/blob/ac70978d893e72d318a8f0ea079777fad758170c/game_eggs/vintage_story/egg-vintage-story.json).  To fix it after updating the egg version, I updated the branch setting to `pre`, and with a reinstall everything updated in-place, and I was able to join.

Hopefully that's helpful to somebody, especially considering all related issues have been collated into this Issue.  I suspect that the opposite situation (a client on the stable version trying to connect to a server on the pre version) could maybe cause the same issue.

**Comment by KDeWals** [comment]
> @spielerflo97330 What mods are you using when you get this error?

I was using no mods it was pure vanilla

**Comment by mikola-rollun** [comment]
Somehow my ticker #2500 is now a duplicate. What happens in my ticker 
`The player is unable to play the game because "respawn" button makes player disconnected from the server`

**Comment by tyronx** [comment]
thanks for the report, this should be fixed since 1.18.0-pre.8
