### ISSUE TITLE
Pasting Non-Text Into the Log In Crashes Game

### ISSUE THREAD

**Issue by harleyndavis** [anegostudios/VintageStory-Issues#2381]
### Game Version

v1.17.11.rc.2

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

When trying to log in, was trying to paste in username/password and has something non text in the clipboard. This crashed the game.

Definitely happens when an image is in the clipboard such as from snipping tool. 

### How to reproduce

1. Start up game.
2. Paste non-text into username or password.
3. Game crashes

### Logs

Running on 64 bit Windows with 32655 MB RAM
Game Version: .net7 Experimental build - v1.17.11-rc.2 (Unstable)
2/13/2023 6:24:43 PM: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: Win32: Failed to convert clipboard to string: The operation completed successfully. 
   at OpenTK.Windowing.Desktop.GLFWProvider.<>c.<.cctor>b__10_0(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwGetClipboardString(Window* window)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.GetClipboardString(Window* window)
   at VSPlatform.XPlatImpl.GetClipboardText() in C:\Users\Tyron\Documents\vintagestory\game-net7\XPlatformInterface\PlatformFormsImpl.cs:line 23
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyDown(ICoreClientAPI api, KeyEvent args) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 415
   at Vintagestory.API.Client.GuiElementTextInput.OnKeyDown(ICoreClientAPI api, KeyEvent args) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementTextInput.cs:line 133
   at Vintagestory.API.Client.GuiComposer.OnKeyDown(KeyEvent args, Boolean haveFocus) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryApi\Client\UI\GuiComposer.cs:line 561
   at GuiScreen.OnKeyDown(KeyEvent e) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\MainMenu\Screens\Special\GuiScreen.cs:line 154
   at Vintagestory.Client.GuiScreenLogin.OnKeyDown(KeyEvent e) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\MainMenu\Screens\GuiScreenLogin.cs:line 91
   at Vintagestory.Client.ScreenManager.OnKeyDown(KeyEvent e) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ScreenManager.cs:line 852
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(KeyboardKeyEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientPlatform\Input.cs:line 250
   at OpenTK.Windowing.Desktop.NativeWindow.OnKeyDown(KeyboardKeyEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.KeyCallback(Window* window, Keys key, Int32 scancode, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.DispatchUpdateFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientProgram.cs:line 149
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2/3/2023 1:14:57 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at System.Threading.ThreadLocal`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetValueSlow()
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot)
   at Vintagestory.API.Common.CollectibleObject.AppendPerishableInfoText(Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor)
   at DynamicClass.Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo_Patch2(Vintagestory.API.Common.CollectibleObject, Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor, Boolean)
   at Vintagestory.API.Common.ItemStack.GetDescription(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot, Boolean)
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Common.ItemStack)
   at Vintagestory.GameContent.GuiDialogHandbook.BuildPages_Async(System.Collections.Generic.List`1<Vintagestory.API.Common.ItemStack>)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 1/29/2023 12:11:20 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangTransient
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.10.0
P3: 63bbdc3a
P4: unknown
P5: unknown
P6: unknown
P7: unknown
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6181.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER61B0.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER61BF.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER61FF.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 21407609-e799-42c8-9eca-13168a2aae49
Report Status: 2049
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 1/27/2023 7:53:05 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FF87DABCD29
Stack:
   at System.Environment._Exit(Int32)
   at System.Environment._Exit(Int32)
   at System.Environment.Exit(Int32)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double, Double)
   at Vintagestory.Client.ClientProgram.Start(Vintagestory.Client.ClientProgramArgs, System.String[])
   at Vintagestory.ClientNative.CrashReporter.Start(System.Threading.ThreadStart)
   at Vintagestory.Client.ClientProgram.Main(System.String[])
 }

**Comment by Th3Dilli** [comment]
thank you for reporting, it will be resolved in the next release
