### ISSUE TITLE
Particulator causes crashing on MP server

### ISSUE THREAD

**Issue by lazim5276** [anegostudios/VintageStory-Issues#2382]
### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

The particulator causes a hard crash whenever it is used. I have a good PC so hardware isn't an issue and the server owner (who plays on a far weaker laptop) is unaffected. The crash occurs even when out of render distance from the particulator and the particles. We used the dedicated vintage story server hoster.

### How to reproduce

1. Get a particulator and just turn it on
2. Toggle settings until crashes occur

### Logs

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.9 (Stable)
2023-02-13 10:03:55 PM: Critical error occurred in the following mod: primitivesurvival@3.0.5
Loaded Mods: aculinaryartillery@1.0.9, atwatersedge@1.1.0, instruments@1.1.4, primitivesurvival@3.0.5, rustandrails@1.0.4, game@1.17.9, carryon@0.7.0, expandedfoods@1.6.3, petai@1.5.5, playercorpse@1.5.1, stonequarry@2.0.0-rc.4, creative@1.17.9, survival@1.17.9, em@1.1.0, feverstonewilds@1.4.0, morecandles@1.0.1, bricklayers@1.2.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at PrimitiveSurvival.ModSystem.BEParticulator.OnBlockPlaced(ItemStack byItemStack)
   at Vintagestory.Client.NoObf.ClientWorldMap.SpawnBlockEntity(String classname, BlockPos position, ItemStack byItemStack) in VintagestoryLib\Client\ClientWorldMap.cs:line 1101
   at Vintagestory.API.Common.Block.OnBlockPlaced(IWorldAccessor world, BlockPos blockPos, ItemStack byItemStack) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 1278
   at PrimitiveSurvival.ModSystem.BlockParticulator.OnBlockPlaced(IWorldAccessor world, BlockPos pos, ItemStack stack)
   at Vintagestory.Common.BlockAccessorBase.SetSolidBlockInternal(Int32 blockId, BlockPos pos, IWorldChunk chunk, Boolean synchronize, Boolean relight, ItemStack byItemstack) in VintagestoryLib\Common\API\BlockAccessorBase.cs:line 153
   at Vintagestory.Common.BlockAccessorRelaxed.SetBlock(Int32 blockId, BlockPos pos, ItemStack byItemstack) in VintagestoryLib\Common\API\BlockAccessorRelaxed.cs:line 76
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleSetBlock(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 238
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1138
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 123
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 678
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 622
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 124
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2023-02-01 11:04:51 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1632951646305068015, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\MIROSL~1\AppData\Local\Temp\RDR7715.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7726.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7727.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7744.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7764.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: b8952bf7-f0bb-4091-b129-079228ab96b9
Report Status: 268435456
Hashed bucket: 1dc75c8e8b60a89926a968dedd6723ef
Cab Guid: 0 }
--------------
{ TimeGenerated = 2023-01-02 5:47:53 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1632951646305068015, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\MIROSL~1\AppData\Local\Temp\RDR1E4A.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1E5B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1E5C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1E79.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1E99.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: f7b12cef-2b0a-4158-b4c2-779eb2c74768
Report Status: 268435456
Hashed bucket: 1dc75c8e8b60a89926a968dedd6723ef
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
The problem is in Primitive Survival mod
