### ISSUE TITLE
Cooking crash

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#239]
`Running on 64 bit Windows with 16 GB RAM 
Version: 1.8.0-rc.1 Survival Mode Edition (Unstable)12/14/2018 5:54:51 PM: Critical error occurred
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Vintagestory.API.Config.Lang.Get(String key, Object[] param)
   at Vintagestory.GameContent.BlockCookingContainer.GetOutputText(IWorldAccessor world, ISlotProvider cookingSlotsProvider, IItemSlot inputSlot)
   at Vintagestory.GameContent.BlockEntityFirepit.SetDialogValues(ITreeAttribute dialogTree)
   at Vintagestory.GameContent.BlockEntityFirepit.OnSlotModifid(Int32 slotid)
   at Vintagestory.API.Common.Action`1.Invoke(T t1)
   at Vintagestory.GameContent.InventorySmelting.DidModifyItemSlot(IItemSlot slot, IItemStack extractedStack)
   at Vintagestory.API.Common.ItemSlot.OnItemSlotModified(IItemStack sinkStack)
   at Vintagestory.API.Common.ItemSlot.TakeOutWhole()
   at Vintagestory.API.Common.ItemSlot.TryPutInto(IItemSlot sinkSlot, ItemStackMoveOperation& op)
   at Vintagestory.API.Common.InventoryBase.ActivateSlot(Int32 slotId, IItemSlot sourceSlot, ItemStackMoveOperation& op)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse)
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouse)
   at Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args)
   at _h4WYpTzjVbOfPs0p2CbaCVULlOw._vYTCvDWesCevjx2Z7KVZ1Va7PKC(MouseEvent )
   at _uvKGIQb0gYxyaNlMKJjm7rS4iC._vYTCvDWesCevjx2Z7KVZ1Va7PKC(MouseEvent )
   at _Z5kRz3NOtXL8upC9whsAeI8Lx7r._VCyn0xbOnKeV5sQiwc116w78tDC(Object , MouseButtonEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _hP6gnpvaqvdYD3qmaiOswnK02Yr._hsbPpjAoNJrdZhFanM9RsTU3xqk(_URBtiEwX9vTE4zzssShJ9mim4Rc , String[] )
   at _ljwl5tGblWloUU2SibW97syEfP._hsbPpjAoNJrdZhFanM9RsTU3xqk(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 7/18/2018 12:22:24 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at OpenTK.NativeWindow.EnsureUndisposed()
   at OpenTK.GameWindow.Exit()
   at _ss8XnL443c6iKET9r8uH2mngrdC._46d84DTFhVDR4AQkWqfy2lnK6IC(System.Exception)
   at _ss8XnL443c6iKET9r8uH2mngrdC._w8zrVg3BYSI3s61BfPPbtf3kXdAA(System.Threading.ThreadStart)
   at _qTvBRfrZHmQZLV0omvHFpK3LT9y._3rwoMTDKer19bpKUCIO6vKjdQbe(System.String[])

 }
{ TimeGenerated = 7/16/2018 6:43:13 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at OpenTK.NativeWindow.EnsureUndisposed()
   at OpenTK.GameWindow.Exit()
   at _ss8XnL443c6iKET9r8uH2mngrdC._46d84DTFhVDR4AQkWqfy2lnK6IC(System.Exception)
   at _ss8XnL443c6iKET9r8uH2mngrdC._w8zrVg3BYSI3s61BfPPbtf3kXdAA(System.Threading.ThreadStart)
   at _qTvBRfrZHmQZLV0omvHFpK3LT9y._3rwoMTDKer19bpKUCIO6vKjdQbe(System.String[])

 }
{ TimeGenerated = 7/16/2018 6:36:42 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at OpenTK.NativeWindow.EnsureUndisposed()
   at OpenTK.GameWindow.Exit()
   at _ss8XnL443c6iKET9r8uH2mngrdC._46d84DTFhVDR4AQkWqfy2lnK6IC(System.Exception)
   at _ss8XnL443c6iKET9r8uH2mngrdC._w8zrVg3BYSI3s61BfPPbtf3kXdAA(System.Threading.ThreadStart)
   at _qTvBRfrZHmQZLV0omvHFpK3LT9y._3rwoMTDKer19bpKUCIO6vKjdQbe(System.String[])

 }`
Crash happened when cooking food as seen.
https://www.twitch.tv/videos/349170724?t=00h13m56s

**Comment by sirStroam** [comment]
In the pot were grain and two vegetables. Upon removing the grain it crashes.

**Comment by sirStroam** [comment]
crashed again with 3 vegetables in slot one and then 3 in slot 2. Check the video for more info and probably more crashes.
