### ISSUE TITLE
Crash when interacting with tutorial

### ISSUE THREAD

**Issue by zerotheliger** [anegostudios/VintageStory-Issues#2398]
### Game Version

1.18 pre 3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### How to reproduce

Opening tutorial tab

following the tutorial steps untill you get to the mouse tutorial ask to click a link

dont click it in the pop up window bring the guide book back up go to tutorial click the link from within the guide book gui and it causes the crash

### Logs

```Log```

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.0-pre.3 (Unstable)
2/25/2023 5:43:40 PM: Critical error occurred
Loaded Mods: game@1.18.0-pre.3, creative@1.18.0-pre.3, survival@1.18.0-pre.3
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ModSystemTutorial.onTutorialCmd(Int32 groupId, CmdArgs args) in VSSurvivalMod\Systems\Handbook\Tutorial\ModSystemTutorial.cs:line 150
   at Vintagestory.Common.ChatCommandApi.<>c__DisplayClass24_0.<RegisterCommand>b__0(TextCommandCallingArgs args) in VintagestoryLib\Common\API\Command\ChatCommandApi.cs:line 245
   at Vintagestory.Common.ChatCommandImpl.callHandler(TextCommandCallingArgs callargs, Action`1 onCommandComplete, Dictionary`2 asyncParseResults) in VintagestoryLib\Common\API\Command\ChatCommandImpl.cs:line 282
   at Vintagestory.Client.NoObf.HudDialogChat.HandleClientCommand(String message, Int32 groupid) in VintagestoryLib\Client\Systems\Gui\Huds\HudDialogChat.cs:line 782
   at Vintagestory.Client.NoObf.HudDialogChat.OnNewClientToServerChatLine(Int32 groupId, String message, EnumChatType chattype, String data) in VintagestoryLib\Client\Systems\Gui\Huds\HudDialogChat.cs:line 735
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerNewClientChatLine(Int32 groupid, String message, EnumChatType chattype, String data) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 337
   at Vintagestory.Client.SystemClientCommands.onCommandLinkClicked(LinkTextComponent linkComp) in VintagestoryLib\Client\Systems\Player\ClientCommands.cs:line 72
   at Vintagestory.API.Client.LinkTextComponent.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\TextLinkComponent.cs:line 185
   at Vintagestory.API.Client.GuiElementRichtext.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 525
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 564
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 416
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 2308
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 229
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2/19/2023 2:05:37 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1397819255080914307, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 63e108be
P4: KERNELBASE.dll
P5: 10.0.19041.2364
P6: 5b7d4d22
P7: c000041d
P8: 000000000002cd29
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER74C3.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER77F0.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7801.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7811.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7831.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_40e68a1a58b8b8d58dadd0d6f6ab3939e7e1892b_1112ccc3_0535dd08-49a0-41b5-96ee-05a2156a86fe

Analysis symbol: 
Rechecking for solution: 0
Report Id: bfe0b088-8c8b-4608-b153-7ba119f45c83
Report Status: 268435456
Hashed bucket: c7828feb58b829c833660d34df4c8d83
Cab Guid: 0 }
--------------
{ TimeGenerated = 2/19/2023 2:05:35 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.11.0, time stamp: 0x63e108be
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2364, time stamp: 0x5b7d4d22
Exception code: 0xc000041d
Fault offset: 0x000000000002cd29
Faulting process id: 0x11a8
Faulting application start time: 0x01d94374ed79bc19
Faulting application path: C:\Users\Zerotheliger\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: bfe0b088-8c8b-4608-b153-7ba119f45c83
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 2/19/2023 2:05:31 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1614422380190080281, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 63e108be
P4: KERNELBASE.dll
P5: 10.0.19041.2364
P6: 5b7d4d22
P7: c0020001
P8: 000000000002cd29
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER59C9.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5D83.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5D93.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5DA1.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5DC1.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_4c3217bb22c404a496e1fdb6a451cd343a03ca8_1112ccc3_03b6eade-6d69-499c-84bc-6cf93e693921

Analysis symbol: 
Rechecking for solution: 0
Report Id: a9396fba-1708-4010-a18a-ede4077f0698
Report Status: 268435456
Hashed bucket: c8bba2f8b0169a6c66679499e8ab9d19
Cab Guid: 0 }

**Comment by zerotheliger** [comment]
after restarting i cannot get this to crash in the same way again. dont know if this is a weird intermittent bug? was talking with another user in the discord bug section and they were having crashes just clicking the tutorial tab intermittently.

**Comment by zerotheliger** [comment]
after more testing and have been able to getting it to crash again it seems like it can be triggered more easily if you really push the game with rendering more chunks at once dont know if that can help reproduce the crash reliably but i was mid range settings when i originally got the crash. (ive noticed minecraft like block lag appearing from that even on a shorter render distance ive noticed on pre 2 i wasnt having block lag but thats another bug report entirely)

**Comment by Craluminum2413** [comment]
Not clear how to reproduce

**Comment by Th3Dilli** [comment]
thank you for the report, this should be fixed in the next release

I was able to reproduce it by getting till you have to click the link and
then open the handbook and stop the tutorial
then click the link in the tutorial
