### ISSUE TITLE
NRE when equipping freshly crafted handbasket

### ISSUE THREAD

**Issue by ryougishiki0001** [anegostudios/VintageStory-Issues#2400]
### Game Version

v1.18.0-pre.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I put 10 reeds in the crafting grid, pulled out a handbasket, put the handbasket in a bag slot, saw the three slots appear, and then the game crashed.

### How to reproduce

1. Make a handbasket
2. Put handbasket in bag slot
3. Crash?

### Logs

```Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.0-pre.1 (Unstable)
2/26/2023 08:20:06: Critical error occurred
Loaded Mods: game@1.18.0-pre.1, creative@1.18.0-pre.1, survival@1.18.0-pre.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.ItemSlotCraftingOutput.triggerEvent(ItemStack craftedStack, Int32 moved, IPlayer actingPlayer) in VintagestoryLib\Common\GameContent\Inventory\ItemSlotCraftingOutput.cs:line 70
   at Vintagestory.Common.ItemSlotCraftingOutput.TryPutInto(ItemSlot sinkSlot, ItemStackMoveOperation& op) in VintagestoryLib\Common\GameContent\Inventory\ItemSlotCraftingOutput.cs:line 61
   at Vintagestory.Common.PlayerInventoryManager.TryTransferAway(ItemSlot sourceSlot, ItemStackMoveOperation& op, Boolean onlyPlayerInventory, StringBuilder shiftClickDebugText, Boolean slotNotifyEffect) in VintagestoryLib\Common\GameContent\Inventory\PlayerInventoryManager.cs:line 239
   at Vintagestory.Common.PlayerInventoryManager.TryTransferAway(ItemSlot sourceSlot, ItemStackMoveOperation& op, Boolean onlyPlayerInventory, Boolean slotNotifyEffect) in VintagestoryLib\Common\GameContent\Inventory\PlayerInventoryManager.cs:line 217
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnGuiClosed() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 481
   at Vintagestory.API.Client.GuiDialog.TryClose() in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 299
   at Vintagestory.Client.NoObf.GuiManager.OnEscapePressed() in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 153
   at Vintagestory.Client.NoObf.GuiManager.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 352
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 2175
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(Object sender, KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 264
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnKeyDown(Key key, Boolean repeat) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\NativeWindowBase.cs:line 129
   at OpenTK.Platform.Windows.WinGLNative.HandleKeyboard(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 639
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 828
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2/24/2023 11:22:42, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.0.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\CENSORED\AppData\Local\Temp\RDR8FB1.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8FB2.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8FC3.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8FC1.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8FE1.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: add46567-fd12-461a-8985-4dc187babc90
Report Status: 536871008
Hashed bucket: 
Cab Guid: 0 }```

**Comment by Craluminum2413** [comment]
I can't reproduce that

**Comment by Craluminum2413** [comment]
Closing due to inactivity
