### ISSUE TITLE
Game Crashing When Joining Any Server

### ISSUE THREAD

**Issue by MrLudo1** [anegostudios/VintageStory-Issues#2403]
### Game Version

v1.17.11

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Every time I attempt to join a multiplayer server in Vintage Story my game crashes and I am met with the following crash notes. I would appreciate any possible help. I have already done a full reinstall of the game and it is still crashing.

### How to reproduce

1. Launch Vintage Story
2. Select Multiplayer
3. Select a Public Server or Add A Private One
4. Attempt to Join Server

### Screenshots

![Screenshot 2023-02-26 191417](https://user-images.githubusercontent.com/126429183/221447649-edc18b25-f52b-478b-9bb2-85908f11629b.png)
![Screenshot 2023-02-26 191443](https://user-images.githubusercontent.com/126429183/221447655-fdbf7668-2fd8-4c31-9043-8da76ba6373c.png)

### Logs

```Log```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.11 (Stable)
2/26/2023 7:31:14 PM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 407
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 718
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 622
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 124
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2/26/2023 1:34:33 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1160639168186786326, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.0.0
P3: 63f87318
P4: KERNELBASE.dll
P5: 10.0.22621.1194
P6: faa44dd0
P7: c000041d
P8: 000000000009051c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f712cd06-26f0-48db-a138-13db7ebf2b21.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_abce6fd9df1a5443e5bd7c4922bddb291dda3e7_fc12c943_af8018ae-e915-49fe-8409-c75da3c6f773

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5297779c-939e-4c44-890a-51b343220538
Report Status: 268435456
Hashed bucket: 6ea00d4779838a17b01b6b2c942da216
Cab Guid: 0 }
--------------
{ TimeGenerated = 2/26/2023 1:34:20 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.0.0
P3: 63f87318
P4: KERNELBASE.dll
P5: 10.0.22621.1194
P6: faa44dd0
P7: c000041d
P8: 000000000009051c
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_abce6fd9df1a5443e5bd7c4922bddb291dda3e7_fc12c943_af8018ae-e915-49fe-8409-c75da3c6f773

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5297779c-939e-4c44-890a-51b343220538
Report Status: 4
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 2/26/2023 1:34:20 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1737180586821420333, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.0.0
P3: 63f87318
P4: KERNELBASE.dll
P5: 10.0.22621.1194
P6: faa44dd0
P7: c0020001
P8: 000000000009051c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.df624c9a-da80-454b-8c8d-17c778b93ede.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_14793310264455a14c1c5f7bcec9bc38506d7c4_fc12c943_bec12aca-a5bf-464f-b6fb-4b09947cdc57

Analysis symbol: 
Rechecking for solution: 0
Report Id: 27f904bf-ebb1-4a3f-9949-db6bf1ff2eb5
Report Status: 268435456
Hashed bucket: 0820b5443c38a54fa81bb48a2c32052d
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
Why you closed it?
