### ISSUE TITLE
Game Crash on Save and Close

### ISSUE THREAD

**Issue by fmlstudios** [anegostudios/VintageStory-Issues#2404]
### Game Version

1.18.3

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Everytime I save and close a world, the game crashes. Game still saves the world data. Only two small mods. One changes crosshair, the other adds in a zoom function. Nothing that should make this happen (that I know of... not that I would know anyway. lol)

### How to reproduce

Save and close a world

### Logs

```Log```Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.0-pre.3 (Unstable)
2/26/2023 8:34:02 PM: Critical error occurred
Loaded Mods: 
System.MissingMethodException: Method not found: 'Void Vintagestory.API.Client.IShaderProgram.Dispose()'.
   at ZoomButton.SquintOverlayRenderer.Dispose()
   at Vintagestory.Client.NoObf.ClientEventManager.Dispose() in VintagestoryLib\Client\Util\ClientEventManager.cs:line 556
   at Vintagestory.Client.NoObf.ClientMain.Dispose() in VintagestoryLib\Client\ClientMain.cs:line 3104
   at Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected) in VintagestoryLib\Client\ClientMain.cs:line 3004
   at Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnLeaveWorld() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogEscapeMenu.cs:line 323
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 304
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 677
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 292
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 564
   at Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogEscapeMenu.cs:line 388
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 416
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 229
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2/26/2023 7:15:55 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangTransient
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.0.0
P3: 63fa7873
P4: unknown
P5: unknown
P6: unknown
P7: unknown
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER680D.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER681E.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER682D.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER685C.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: cdc31a63-9265-42c2-bc68-189aa415f5ee
Report Status: 2049
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 2/25/2023 11:07:16 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1510786282797937733, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.0.0
P3: 63fa7873
P4: KERNELBASE.dll
P5: 10.0.19041.2546
P6: e8e9ac9b
P7: c000041d
P8: 000000000002cd29
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER65D7.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_dde5675874814177f057fcfc06e3bec0ef9f_104d6787_82bbcf24-382a-4706-aa68-f5b3a2e880ee

Analysis symbol: 
Rechecking for solution: 0
Report Id: b8a26ea7-a3fa-4568-97ae-b9585a7a71c3
Report Status: 268566528
Hashed bucket: 49f9f11c94e2afebe4f7641ea5b43445
Cab Guid: 0 }
--------------
{ TimeGenerated = 2/25/2023 11:07:15 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.0.0
P3: 63fa7873
P4: KERNELBASE.dll
P5: 10.0.19041.2546
P6: e8e9ac9b
P7: c000041d
P8: 000000000002cd29
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_dde5675874814177f057fcfc06e3bec0ef9f_104d6787_82bbcf24-382a-4706-aa68-f5b3a2e880ee

Analysis symbol: 
Rechecking for solution: 0
Report Id: b8a26ea7-a3fa-4568-97ae-b9585a7a71c3
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }

**Comment by Fulgen301** [comment]
> at ZoomButton.SquintOverlayRenderer.Dispose()

Not a vanilla bug, but an issue with [ZoomButton](https://mods.vintagestory.at/zoombutton).

**Comment by SpearAndFang** [comment]
Also, this was fixed in the latest version of ZoomButton.
