### ISSUE TITLE
Exception thrown at launch

### ISSUE THREAD

**Issue by bbouchard95** [anegostudios/VintageStory-Issues#2433]
### Game Version

 v1.17.11 (Stable)

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.11 (Stable)
2023-03-06 12:07:22 PM: Critical error occurred
Loaded Mods: 
System.NotSupportedException: Your graphics card does not support the extensions GL_ARB_framebuffer_object, GL_ARB_vertex_array_object, GL_ARB_draw_instanced, GL_ARB_explicit_attrib_location which is required to start the game
   at Vintagestory.Client.NoObf.ClientPlatformWindows.LogAndTestHardwareInfos() in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 207
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

### How to reproduce

Open App

### Logs

```Log```

**Comment by tyronx** [comment]
What graphics card do you have?

**Comment by bbouchard95** [comment]
> What graphics card do you have?

NVIDIA GeForce GTX 1650 Ti


I was able to fix the issues by updating my intel drivers

**Comment by Craluminum2413** [comment]
Closing due to inactivity
