### ISSUE TITLE
Generic crash to desktop while swimming.  Mods disabled.

### ISSUE THREAD

**Issue by greymane98** [anegostudios/VintageStory-Issues#2440]
Originally continued to crash while just running south (swimming across lake),  Disabled all mods exceptr the required ones but continues to happen.  

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.11 (Stable)
3/6/2023 3:46:53 PM: Critical error occurred
Loaded Mods: game@1.17.11, creative@1.17.11, survival@1.17.11
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityFruitTreePart.GenFoliageMesh(Boolean withSticks, MeshData& foliageMesh, MeshData& sticksMesh) in VSSurvivalMod\Systems\FruitTree\BEFruitTreePart.cs:line 212
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMeshes() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 250
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMesh() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 236
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving) in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 386
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 422
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 817
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1138
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 123
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 678
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 622
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 124
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/10903104/client-crash.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/10903105/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/10903107/client-main.txt)

**Comment by skwerl56767** [comment]
I too started having this same crash. My circumstances, in case they help:

   I was building a second house in a region far from my first house. I discovered the region by repairing a translocator. This location is at X: 4952, Y: 119, Z: 6179. My first house is near spawn, at X: 754, Z: 133.

   My last save was at 8:00 am in-game time. If I wait until 9:32 am in-game time, I crash with the above error, every time. Speeding up the in-game time produces the same result at that timestamp.

   If I leave the area I've loaded around my second house, I don't crash at all. Everything proceeds as normal. If I return to that region after leaving, even after the in-game timestamp of 9:32 am, it crashes.

   Whatever is causing the crash is surface-level, because if I use the translocator to teleport to the second region, I'm underground (at Y: 66), and I don't crash. As soon as the surface loads however, when I'm nearing the top of my mineshaft to exit the cave (about Y: 100), that's when the game crashes.

   The top of my mineshaft exit is at X: 4949, Y: 128, Z: 5862. I have my view distance set to 800. I crash at this location as consistently as I do at the location of my second house, so whatever the game is trying to do, it's having an issue in this big area I've loaded.

   I don't crash if I leave the game paused, so it's related to the in-game time.

   This particular save has 118 hours and 50 minutes of playtime. In-game time is the 2nd of December of the second year. It has Patchy worldgen. It's a Survival world, with custom settings.
   I don't think the issue is biome-related, because the trouble area has a lot of the same or similar biomes to the "safe" area I've loaded around spawn: mountains, alpine, deciduous forests, deserts, lakes, etc. The safe area is also much bigger, so the trouble area has a very localized problem.

   This is the first time I've encountered this crash on this particular world. I remember having a similar one on an older world, but it's several game versions old, so I can't confirm if it's the same crash, or if it's a new one.

   I was originally playing on this world with version 1.17.9 (Stable). When I crashed the first time (and several times after that to confirm it was repeatable), I updated my game to version 1.17.11 (Stable). The crash continues to occur, however; nothing has changed.
   This is a fully vanilla save. I haven't modded my game at all.

   I suspect that something is trying to spawn, update, or generate in this particular region, which is why I always crash at a specific time and only in specific areas on the surface. I'll have to play some more to see if that region is cursed forever, or if the issue disappears after a certain amount of in-game time passes.

   Here are my world settings for this save:
<img width="277" alt="World_Settings_for_Crashing_Save" src="https://user-images.githubusercontent.com/15080719/223277020-700c7caf-e938-4f84-bc6b-d2475469f2da.png">
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/10903780/client-crash.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/10903782/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/10903785/client-main.txt)
