### ISSUE TITLE
World not saving but player data is on exiting an updated world - and Crash

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2465]
### Game Version

1.18.0pre6 from 1.18.0pre5

### Platform

Windows

### Modded

None

### SP/MP

Single & LAN
### Description

Been playing on a LAN world with the new pre-1 and have been updating with the updater to each new pre version as it comes out. Updated to pre6 from pre5 and now when I exit the world (in single player or when open to LAN) it crashes out and doesn't save any world progress and only saves the player progress.

To give an example, I had nothing in my inventory, picked up a berry from a storage. then left the world causing it to crash. I log back in and the berry is still in my inventory and it is still in the inventory. I can take/stack/eat both. This also happens to the LAN player if the world is set to LAN including the crash.

Playing a NEW world on pre6 does NOT have this issue.

### Logs

Server main.txt: 
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/10944862/server-main.txt)

Crash screen (no mods and even deleting the only raft we have changes nothing):
```
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.0-pre.6 (Unstable)
10/03/2023 18:10:27: Critical error occurred
Loaded Mods: 
System.NotImplementedException: The method or operation is not implemented.
   at Vintagestory.GameContent.EntityBoat.Dispose() in VSSurvivalMod\Systems\Boats\EntityBoat.cs:line 482
   at Vintagestory.Client.NoObf.ClientEventManager.Dispose() in VintagestoryLib\Client\Util\ClientEventManager.cs:line 556
   at Vintagestory.Client.NoObf.ClientMain.Dispose() in VintagestoryLib\Client\ClientMain.cs:line 2621
   at Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected) in VintagestoryLib\Client\ClientMain.cs:line 2536
   at Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnLeaveWorld() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogEscapeMenu.cs:line 323
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 304
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 677
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 292
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 564
   at Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogEscapeMenu.cs:line 388
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 416
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 229
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 03/03/2023 18:47:59, Site = , Source = Windows Error Reporting, Message = Fault bucket 1917238252916211325, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.0.0
P3: 63fa7873
P4: nvoglv64.dll
P5: 31.0.15.2756
P6: 638e842a
P7: c0000005
P8: 0000000000e50f24
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD662.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD9FC.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD9FD.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDA0B.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDA2B.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_f4e9a714b87acb73af5c5896da9fbea1d3a629b8_104d6787_cce2ea51-dd40-4f0c-bd9e-7dc3d61e63f9

Analysis symbol: 
Rechecking for solution: 0
Report Id: 4c22622d-d1cd-4228-a848-642e98fb2566
Report Status: 268435456
Hashed bucket: 6bf35c0b50df62663a9b660876dc7e7d
Cab Guid: 0 }
--------------
{ TimeGenerated = 03/03/2023 18:47:58, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.0.0, time stamp: 0x63fa7873
Faulting module name: nvoglv64.dll, version: 31.0.15.2756, time stamp: 0x638e842a
Exception code: 0xc0000005
Fault offset: 0x0000000000e50f24
Faulting process id: 0x6350
Faulting application start time: 0x01d94e000b236ac3
Faulting application path: C:\Users\valle\AppData\Roaming\Vintagestory1.18RC1\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\nvmdsi.inf_amd64_b2fe8840215ee00f\nvoglv64.dll
Report Id: 4c22622d-d1cd-4228-a848-642e98fb2566
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 03/03/2023 18:47:56, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Graphics.OpenGL.GL.EnableVertexAttribArray(Int32)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.RenderMeshInstanced(Vintagestory.API.Client.MeshRef, Int32)
   at Vintagestory.Client.ParticleRenderer2D.Render(Single)
   at Vintagestory.Client.GuiCompositeMainMenuLeft.Render(Single, Int64, Boolean, Boolean)
   at Vintagestory.Client.GuiCompositeMainMenuLeft.RenderBg(Single, Boolean)
   at Vintagestory.Client.ScreenManager.Render(Single)
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at Vintagestory.Client.ClientProgram.Start(Vintagestory.Client.ClientProgramArgs, System.String[])
   at Vintagestory.ClientNative.CrashReporter.Start(System.Threading.ThreadStart)
   at Vintagestory.Client.ClientProgram.Main(System.String[])

 }
```

**Comment by Craluminum2413** [comment]
This line <https://github.com/anegostudios/vssurvivalmod/blob/26d5e833a38d1d3d72ba477c1cbce22db70920cb/Systems/Boats/EntityBoat.cs#L480-L483>
