### ISSUE TITLE
Crash on trying to "upgrade" the world from v1.18.0-pre3 to pre-6

### ISSUE THREAD

**Issue by BoredEngineer** [anegostudios/VintageStory-Issues#2475]
### Game Version

v1.18.0-pre 6

### Platform

Windows

### Modded

Modded/Vanilla

### SP/MP

SP

### Description

Game crashes when trying to "update" the world to the latest game version.
The world is modded but the crash happens with or without the mods enabled.
As it points to the "boat", I've picked up raft (vanilla) from the water and placed it into inventory, the game still crashes during save/exit with the same error. I've dropped raft on the ground and waited for it to despawn, still crashed on the save/exit, with the same error.

Attaching Crash log from crash window, client-main and server-main

### How to reproduce

I can't narrow it down to a specific case. Experimented with removing the raft that was placed in the water but even after waiting for it to despawn the game still crashed on save/exit.

### Logs

Crash log from the crash window:
```Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.0-pre.6 (Unstable)
13-Mar-23 22:40:56: Critical error occurred
Loaded Mods: 
System.NotImplementedException: The method or operation is not implemented.
   at Vintagestory.GameContent.EntityBoat.Dispose() in VSSurvivalMod\Systems\Boats\EntityBoat.cs:line 482
   at Vintagestory.Client.NoObf.ClientEventManager.Dispose() in VintagestoryLib\Client\Util\ClientEventManager.cs:line 556
   at Vintagestory.Client.NoObf.ClientMain.Dispose() in VintagestoryLib\Client\ClientMain.cs:line 2621
   at Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected) in VintagestoryLib\Client\ClientMain.cs:line 2536
   at Vintagestory.Client.GuiScreenRunningGame.ExitOrRedirect(Boolean isDisconnect, String reason) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 275
   at Vintagestory.Client.GuiScreenRunningGame.ReloadWorld(String reason) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 262
   at Vintagestory.Client.ScreenManager.<setupHotkeyHandlers>b__46_1(KeyCombination viaKeyComb) in VintagestoryLib\Client\ScreenManager.cs:line 277
   at Vintagestory.Client.NoObf.GuiDialogConfirmRemapping.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogConfirmRemapping.cs:line 97
   at Vintagestory.Client.NoObf.GuiManager.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 328
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 199
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 778
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 970
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 243
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 717
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 620
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

client-main as gist:
<script src="https://gist.github.com/BoredEngineer/a084bb40da200d59f067c2508a58874a.js"></script>

server-main as gist:
<script src="https://gist.github.com/BoredEngineer/c3ac3e3933e3b3bf91fbf308652e62ce.js"></script>

**Comment by BoredEngineer** [comment]
My mistake - didn't update game correctly, after installing v18.0 pre-6 from scratch it works correctly and not crashing.
