### ISSUE TITLE
Crash on load at WeatherSimulationSnowAccum.GetSnowUpdate

### ISSUE THREAD

**Issue by Arven14** [anegostudios/VintageStory-Issues#2479]
### Game Version

v1.18.0-pre.6 

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Saved an exited my game as per normal. Later when I attempted to load again I receive an index out of bounds error for WeatherSimulationSnowAccum.GetSnowUpdate. Mods are disabled, running a repair doesn't help.

### Logs

```Log```Running on 64 bit Windows with 24 GB RAM 
Game Version: v1.18.0-pre.6 (Unstable)
3/14/2023 10:34:29 PM: Critical error occurred
Loaded Mods: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.GetSnowUpdate(WeatherSimulationRegion simregion, IServerMapChunk mc, Vec2i chunkPos, IWorldChunk[] chunksCol) in VSEssentials\Systems\Weather\WeatherSimulationSnowAccum.cs:line 475
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.UpdateSnowLayerOffThread(WeatherSimulationRegion simregion, IServerMapChunk mc, Vec2i chunkPos) in VSEssentials\Systems\Weather\WeatherSimulationSnowAccum.cs:line 432
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.onThreadStart() in VSEssentials\Systems\Weather\WeatherSimulationSnowAccum.cs:line 268
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/14/2023 10:34:29 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.GetSnowUpdate(Vintagestory.GameContent.WeatherSimulationRegion, Vintagestory.API.Common.IServerMapChunk, Vintagestory.API.MathTools.Vec2i, Vintagestory.API.Common.IWorldChunk[])
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.UpdateSnowLayerOffThread(Vintagestory.GameContent.WeatherSimulationRegion, Vintagestory.API.Common.IServerMapChunk, Vintagestory.API.MathTools.Vec2i)
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.onThreadStart()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

 }
--------------
{ TimeGenerated = 3/14/2023 10:20:14 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.GetSnowUpdate(Vintagestory.GameContent.WeatherSimulationRegion, Vintagestory.API.Common.IServerMapChunk, Vintagestory.API.MathTools.Vec2i, Vintagestory.API.Common.IWorldChunk[])
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.UpdateSnowLayerOffThread(Vintagestory.GameContent.WeatherSimulationRegion, Vintagestory.API.Common.IServerMapChunk, Vintagestory.API.MathTools.Vec2i)
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.onThreadStart()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

 }
--------------
{ TimeGenerated = 3/14/2023 10:16:09 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.GetSnowUpdate(Vintagestory.GameContent.WeatherSimulationRegion, Vintagestory.API.Common.IServerMapChunk, Vintagestory.API.MathTools.Vec2i, Vintagestory.API.Common.IWorldChunk[])
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.UpdateSnowLayerOffThread(Vintagestory.GameContent.WeatherSimulationRegion, Vintagestory.API.Common.IServerMapChunk, Vintagestory.API.MathTools.Vec2i)
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.onThreadStart()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

 }

**Comment by Arven14** [comment]
Just noticed this in Server-main.txt

14.3.2023 22:34:28 [Error] Exception throwing during chunk Unpack() at chunkpos xz 7981/8004. Likely corrupted. Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.GetSnowUpdate(WeatherSimulationRegion simregion, IServerMapChunk mc, Vec2i chunkPos, IWorldChunk[] chunksCol) in **C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Systems\Weather\WeatherSimulationSnowAccum.cs:line 475**
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.TryImmediateSnowUpdate(WeatherSimulationRegion simregion, IServerMapChunk mc, Vec2i chunkCoord, IWorldChunk[] chunksCol) in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Systems\Weather\WeatherSimulationSnowAccum.cs:line 235
   at Vintagestory.Server.ServerSystemSupplyChunks.loadOrGenerateChunkColumn() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 699

**Comment by Craluminum2413** [comment]
Could you send your save game file?

**Comment by Arven14** [comment]
https://drive.google.com/file/d/1eYZcu1NfjSZaXV98i3wOiw6FJU_bn4Rs/view?usp=sharing

**Comment by tyronx** [comment]
thanks for the report, i was able to reproduce it using your savegame, will be fixed next pre-release
