### ISSUE TITLE
[v1.18.0-pre6] frequent and severe network-like lag in local play

### ISSUE THREAD

**Issue by EatThePath** [anegostudios/VintageStory-Issues#2486]
### Game Version

v1.18.0-pre6

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

While playing pre6 I've noted increasing instances of long hiccups in the game world, cases where my inventory and the world blocks refuse to respond for several seconds and then catch up like I'm playing on server over a flakey internet connection. The game has always had the occasional oddity like this, but in past versions or even earlier previews of 1.18 it's been minor and rare enough to ignore. Now the lags are becoming a serious obstacle to enjoying the game, sometime happening multiple times a minute and each extending several seconds. If they occur during combat it can result in enemies that I can't hurt and my position being rolled back dozens of feet to take damage.

Upon looking in the logs at the prompting of this page, I found my most recent session's server event log as somewhere close to 19k copies of the exception I put in the log box here.

I am using the Prospecting Info mod, which as far as I know is a purely client side UI thing. I have not yet had the presence of mind to disable it before a prolonged session to figure out if it is somehow related anyway.

### How to reproduce

specific steps to trigger it have not been evident

### Logs

```
16.3.2023 21:57:33 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.BlockAccessorBulkMinimalUpdate.FastCommit() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\API\BlockAccessorBulkMinimalUpdate.cs:line 118
   at Vintagestory.Common.BlockAccessorBulkMinimalUpdate.Commit() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\API\BlockAccessorBulkMinimalUpdate.cs:line 32
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.OnServerTick100ms(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Systems\Weather\WeatherSimulationSnowAccum.cs:line 154
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\EventManager.cs:line 84
   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerEventManager.cs:line 122
   at Vintagestory.Server.ServerMain.Process() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 766
   ```

**Comment by EatThePath** [comment]
One further note, I see in the discord some people have brought up similar issues and slower chunk generation was suggested as a possible cause. I've had it happen while sticking close to my main home for extended periods, and have previously explored in all directions a good distance, so I don't think any new chunks should be getting generated at all.

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in pre7
