### ISSUE TITLE
Just crashed while I was using the baskets

### ISSUE THREAD

**Issue by xellysiax** [anegostudios/VintageStory-Issues#2518]
### Platform

None

### Modded

None

### SP/MP

None

### Logs

```Log```

**Comment by xellysiax** [comment]
> 

https://github.com/anegostudios/VintageStory-Issues/issues/2518#issue-1644377947

**Comment by Craluminum2413** [comment]
No info

**Comment by xellysiax** [comment]
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.11 (Stable)
3/28/2023 6:32:18 PM: Critical error occurred
Loaded Mods: game@1.17.11, creative@1.17.11, survival@1.17.11
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityFruitTreePart.GenFoliageMesh(Boolean withSticks, MeshData& foliageMesh, MeshData& sticksMesh) in VSSurvivalMod\Systems\FruitTree\BEFruitTreePart.cs:line 212
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMeshes() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 250
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMesh() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 236
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving) in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 386
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 422
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 817
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1138
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 123
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 678
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 622
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 124
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/28/2023 6:29:59 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1857557184126262820, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 63e108be
P4: KERNELBASE.dll
P5: 10.0.19041.2728
P6: e7e53a4e
P7: c0020001
P8: 000000000002cd29
P9: 
P10: 

Attached files:
\\?\C:\Users\ellys\AppData\Local\Temp\WER5DB5.tmp.WERDataCollectionStatus.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6D75.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6D95.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6D92.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6DC2.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_4f14cb37fe7b85e2ed7b3b85a54ece8c4d43adc2_1112ccc3_3dad7dd7-3cb7-46c1-9927-8eac2bfe9df5

Analysis symbol: 
Rechecking for solution: 0
Report Id: cfb64198-f79e-459e-a37a-d52498e294e6
Report Status: 268566528
Hashed bucket: e0279c219ddd09df69c75e6acdd21e24
Cab Guid: 0 }
--------------
{ TimeGenerated = 3/28/2023 6:29:33 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.11.0, time stamp: 0x63e108be
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2728, time stamp: 0xe7e53a4e
Exception code: 0xc0020001
Fault offset: 0x000000000002cd29
Faulting process id: 0x4234
Faulting application start time: 0x01d961ccf95fd109
Faulting application path: C:\Users\ellys\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: cfb64198-f79e-459e-a37a-d52498e294e6
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 3/28/2023 6:29:31 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFE3A82CD29
Stack:
 }

**Comment by Craluminum2413** [comment]
Duplicate of #2102
