### ISSUE TITLE
Can't join server without an immediate crash v1.17.11

### ISSUE THREAD

**Issue by zendor911** [anegostudios/VintageStory-Issues#2549]
### Game Version

v1.17.11

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Can't join my server after a reboot.  

Every time I click to join the multiplayer world it crashes immediately.  Single player loads fine.

### How to reproduce

Load the game, choose my multiplayer server and it crashes.  Every single time

### Logs

```Log```
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.11 (Stable)
4/6/2023 8:37:18 PM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 407
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 718
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 622
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 124
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/17/2023 2:05:24 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1734681066625210042, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 63e108be
P4: nvoglv64.dll
P5: 31.0.15.2686
P6: 636a86dc
P7: c0000005
P8: 0000000000e4f694
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8A80.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8C07.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8C18.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8C16.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8C36.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_985e8fb9947f5fb24fd0937e275e3cf11fd259_1112ccc3_4836e090-3163-4ad4-a057-d66cb9a7c304

Analysis symbol: 
Rechecking for solution: 0
Report Id: 4384e791-124b-45b8-b81b-54dcf9ae0520
Report Status: 268435456
Hashed bucket: 53a434befe87198ea812d33d46ca96ba
Cab Guid: 0 }
--------------
{ TimeGenerated = 3/17/2023 2:05:22 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.11.0, time stamp: 0x63e108be
Faulting module name: nvoglv64.dll, version: 31.0.15.2686, time stamp: 0x636a86dc
Exception code: 0xc0000005
Fault offset: 0x0000000000e4f694
Faulting process id: 0x59ac
Faulting application start time: 0x01d958f3d11f447c
Faulting application path: C:\Users\scott\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_bd530e4cbd42e0a3\nvoglv64.dll
Report Id: 4384e791-124b-45b8-b81b-54dcf9ae0520
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 3/17/2023 2:05:22 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Graphics.OpenGL.GL.EnableVertexAttribArray(Int32)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.RenderMesh(Vintagestory.API.Client.MeshRef)
   at Vintagestory.Client.Gui.MainMenuRenderAPI.Render2DTexture(Int32, Single, Single, Single, Single, Single, Vintagestory.API.MathTools.Vec4f)
   at Vintagestory.Client.GuiCompositeMainMenuLeft.Render(Single, Int64, Boolean)
   at Vintagestory.Client.ScreenManager.Render(Single)
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at Vintagestory.Client.ClientProgram.Start(Vintagestory.Client.ClientProgramArgs, System.String[])
   at Vintagestory.ClientNative.CrashReporter.Start(System.Threading.ThreadStart)
   at Vintagestory.Client.ClientProgram.Main(System.String[])

 }

**Comment by Craluminum2413** [comment]
Fixed in 1.18
