### ISSUE TITLE
Can`t create new word  [Fatal] System.NullReferenceException

### ISSUE THREAD

**Issue by BeardVis** [anegostudios/VintageStory-Issues#2569]
### Game Version

v1.18.0-rc.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I am trying to create a new 'Standard' word. The game starts loading, events stop appearing after 10s, and among them is the following event:
`Something went awry...please check the program logs... (Exception thrown by server during startup or process)`
I have no user with the name 'Tyron' as writed in logs

### How to reproduce

Just create a new Standard word

### Screenshots

![1](https://user-images.githubusercontent.com/43556313/231193670-d7093591-bd2b-4af7-a72e-af65b5ad1c33.png)

### Logs

11.4.2023 17:07:49 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockDisplayCase.OnLoaded(ICoreAPI api) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Block\BlockDisplayCase.cs:line 17
   at Vintagestory.Server.ServerSystemBlockSimulation.OnBeginModsAndConfigReady() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 234
   at Vintagestory.Server.ServerMain.EnterRunPhase(EnumServerRunPhase runPhase) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 573
   at Vintagestory.Server.ServerMain.Launch() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 496
   at Vintagestory.Client.ClientProgram.ServerThreadStart()

**Comment by Craluminum2413** [comment]
Have you reinstalled or updated to new version?
