### ISSUE TITLE
Crash on input during final stage of startup - easily avoided

### ISSUE THREAD

**Issue by hlangeveld** [anegostudios/VintageStory-Issues#2574]
### Game Version

1.18-rc5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

This is easily avoided, but it's still a crash.

Enter text after the final message "launching single player instance ... ... " appears in the launcher. Game will crash.

Just don't push any buttons while the game is still loading.

How I found out:

I wanted to lookup something in the built in help, so I launched the game and pressed 'h' too quickly.

### How to reproduce

1. Single player
2. Load game
3. Wait for "launching single player instance ... ... "
4. Press 'h'

Game now crashes.

### Workaround

Don't enter any input until game window renders fully.

### Logs

```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.0-rc.5 (Unstable)
11/04/2023 17:51:19: Critical error occurred
Loaded Mods: game@1.18.0-rc.5, prospectorinfo@4.1.5-pre, creative@1.18.0-rc.5, survival@1.18.0-rc.5
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.MathTools.Mat4d.Multiply(Double[] output, Double[] a, Double[] b) in VintagestoryApi\Math\Matrix\Mat4d.cs:line 318
   at Vintagestory.Client.NoObf.SystemRenderSunMoon.OnRenderFrame3D(Single dt) in VintagestoryLib\Client\Systems\Render\RenderSunMoon.cs:line 238
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 191
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 785
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 869
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 709
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 681
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 625
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
