### ISSUE TITLE
Crash when exiting clayforming window

### ISSUE THREAD

**Issue by theishiopian** [anegostudios/VintageStory-Issues#259]
Version: 1.9 rc1

how to reproduce:
place a clayforming block, close the window without selecting anything to make.

Exception stacktrace:

```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.9.0-rc.1 (Unstable)4/24/2019 9:05:35 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityClayForm.LayerBounds(Int32 layer)
   at Vintagestory.GameContent.BlockEntityClayForm.InBounds(Vec3i voxelPos, Int32 layer)
   at Vintagestory.GameContent.BlockEntityClayForm.OnAdd(Vec3i voxelPos, Int32 radius, Int32 layer)
   at Vintagestory.GameContent.BlockEntityClayForm.OnUseOver(IPlayer byPlayer, Vec3i voxelPos, BlockFacing facing, Boolean mouseBreakMode)
   at Vintagestory.GameContent.ItemClay.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at _7qZBn81DJsyhovz2Njc5BwVzM4n._h9kelbSV1QckErPazUe5jsEdSMk()
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at _mQ28lD3JU3Sbv6uFw7wLKOuph2O._w9PGHQrcy3Z3SSTx4dRSkEQMvvC(Single )
   at _mQ28lD3JU3Sbv6uFw7wLKOuph2O._qz2jWbpSOdLyPp6gXDWctRPec3L(Single )
   at _hcqhIhQbNkrp0W9fK2g0Qkgxstb._bzfpbYwnIF4xjakdn2bgyb2BO8DA(Single )
   at _ud2LLsLvbi6QVfrNye4sePwSWIB._RxQfvfohdvHjdJh9OClM06kzoWb(Single )
   at _ud2LLsLvbi6QVfrNye4sePwSWIB._SoI7P851i32w5zFFVlxCQGx85nD(Single )
   at _IGyp9CHsHo7ym62QLcVJCX4TtSg._AJe6FYkbiRWJcItFYDFBPTN03N2(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _oqzKscaLYbGLTEM2t0sDtYSYQS._6ChnFoSLOvjhNwureFy5eFL3zph(_RTHC1CpU011Q3xEK2AS268yMROp , String[] )
   at _dXsSQH6iUKNAvGuRQ4Y4s7qEi2q._6ChnFoSLOvjhNwureFy5eFL3zph(ThreadStart )
```

**Comment by tyronx** [comment]
Thank you, fixed for rc.2
