### ISSUE TITLE
Reading scroll crashed the game

### ISSUE THREAD

**Issue by moxian** [anegostudios/VintageStory-Issues#2590]
### Game Version

1.18.0-rc6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Got a scroll ("seems to be some sort of diary")

Read it

Got Huge Epic Words across my screeen which i couldn't read in time (i think it had "1/8" somewhere in there)

Had the client crash

### Logs

```
Running on 64 bit Windows with 24 GB RAM 
Game Version: v1.18.0-rc.6 (Unstable)
2023-04-13 19:48:25: Critical error occurred
Loaded Mods: game@1.18.0-rc.6, creative@1.18.0-rc.6, survival@1.18.0-rc.6
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockMultiblock.OnBlockInteractCancel(Single secondsUsed, IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel, EnumItemUseCancelReason cancelReason) in VSEssentials\Block\BlockMultiblock.cs:line 0
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 114
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 84
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 807
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 709
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 681
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 625
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by moxian** [comment]
p.s.: This was on multiplayer server and I crashed. My friend who was next to me heard the bell, but didn't crash. I think he didn't see the letters across the screen either? unsure. Now whenever he uses the scroll the bell can be heard (both for him and me). When he places the scroll it's heard as well. After reconnecting i can read the scroll, but not invoke the bell.
