### ISSUE TITLE
single player

### ISSUE THREAD

**Issue by Nickytheace** [anegostudios/VintageStory-Issues#2602]
### Platform

None

### Modded

None

### SP/MP

Singleplayer

### Description

The game will not let me in single player idk why but when i try to make a new world it turns off I tried uninstalling and reinstalling the game but it did nothing idk what to do now

### How to reproduce

idk try adding somemods then uninstaling them i think 

### Screenshots

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.11 (Stable)
4/16/2023 8:44:57 PM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.GuiScreenSingleplayerNewWorld.OnCreate() in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayerNewWorld.cs:line 300
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 293
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 668
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 279
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 439
   at GuiScreen.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\MainMenu\Screens\Special\GuiScreen.cs:line 206
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 230
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 4/14/2023 9:38:43 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.17.11.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 4fd0

Start Time: 01d96f17e8ceb38d

Termination Time: 4

Application Path: C:\Users\15875\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: cfa24d7c-9ae2-47c1-b021-204a9d7d300f

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 4/14/2023 9:38:40 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1447391175523157740, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 63e108be
P4: 8073
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0eae1998-31e6-4d72-86a0-99cb0849188f.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8559fafc-b135-4022-8444-66c7f515e621.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.57d5f4ad-7b88-403f-8b5e-38e6f4acf005.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e2e7bb42-ee57-4cb0-b194-aa9d2a4c337b.tmp.txt
\\?\C:\Users\15875\AppData\Local\Temp\WER.b82ee4e1-092d-4ad4-852f-5a788c99f89f.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_9443ef9a2de6c80bec5d55fd977e11c9c718c7c_1112ccc3_862730ab-fe9e-4177-81cb-f566f045a29e

Analysis symbol: 
Rechecking for solution: 0
Report Id: cfa24d7c-9ae2-47c1-b021-204a9d7d300f
Report Status: 268435456
Hashed bucket: 84507e10361df5daa4162a9b0417c6ec
Cab Guid: 0 }
--------------
{ TimeGenerated = 4/10/2023 7:00:37 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1982424499073691712, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 10.0.21996.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\15875\AppData\Local\Temp\RDR1E36.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.22d63a3c-8913-4b31-94a9-a20876f54dc4.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c2f0596d-c7ff-4b01-aca6-80488dfa97d1.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.fbacbb57-945f-4ea2-aa1d-72afd098fcc5.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ae7d0a29-e256-40a2-8cbd-fd308d5df417.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 739d3c5e-cd37-42f7-8f3c-5f07f38083bc
Report Status: 268435456
Hashed bucket: 218642ae4da69ad3db82fc941d51b040
Cab Guid: 0 }

this what shows

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Could you try to reproduce it in 1.17.12?

**Comment by Nickytheace** [comment]
how is it completed
what do you mean
should i try that

**Comment by Nickytheace** [comment]
nvm you did it yay
ty
