### ISSUE TITLE
Reproducable crash 1.18.0-rc.8

### ISSUE THREAD

**Issue by timothyfbowen** [anegostudios/VintageStory-Issues#2610]
### Game Version

1.18.0-rc.8

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### How to reproduce

Walk toward  a certain square I have marked (save available on request - I couldn't upload it due to file size limits)  

### Logs

```Running on 64 bit Windows with 64 GB RAM 
Game Version: v1.18.0-rc.8 (Unstable)
4/18/2023 11:33:28 PM: Critical error occurred
Loaded Mods: game@1.18.0-rc.8, creative@1.18.0-rc.8, survival@1.18.0-rc.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityFruitTreePart.GenFoliageMesh(Boolean withSticks, MeshData& foliageMesh, MeshData& sticksMesh) in VSSurvivalMod\Systems\FruitTree\BEFruitTreePart.cs:line 212
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMeshes() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 250
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMesh() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 236
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving) in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 386
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 399
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 409
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 744
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 681
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 625
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 4/17/2023 10:57:22 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1763125670306319217, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.0.0
P3: 640994ff
P4: KERNELBASE.dll
P5: 10.0.19041.2788
P6: 62e593d6
P7: c0020001
P8: 000000000002cb69
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFC78.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFF0A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFF0B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFF18.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFF38.tmp.txt
\\?\C:\Users\timfb\AppData\Local\Temp\WERE1.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_c0728ace44f4fdf4ed1251198c3c993c8d1eef6d_fefb5991_52280805-dc3c-4452-b58b-845d01e0e79d

Analysis symbol: 
Rechecking for solution: 0
Report Id: e14401fc-b9ab-4fdb-bd68-537dfc072836
Report Status: 268566528
Hashed bucket: ba8a00de7336dcaa0877e174a8fb0b71
Cab Guid: 0 }
--------------
{ TimeGenerated = 4/17/2023 10:56:57 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.0.0
P3: 640994ff
P4: KERNELBASE.dll
P5: 10.0.19041.2788
P6: 62e593d6
P7: c0020001
P8: 000000000002cb69
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFC78.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFF0A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFF0B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFF18.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFF38.tmp.txt
\\?\C:\Users\timfb\AppData\Local\Temp\WERE1.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_c0728ace44f4fdf4ed1251198c3c993c8d1eef6d_fefb5991_cab_52280805-dc3c-4452-b58b-845d01e0e79d

Analysis symbol: 
Rechecking for solution: 0
Report Id: e14401fc-b9ab-4fdb-bd68-537dfc072836
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 4/17/2023 10:56:56 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.0.0, time stamp: 0x640994ff
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2788, time stamp: 0x62e593d6
Exception code: 0xc0020001
Fault offset: 0x000000000002cb69
Faulting process id: 0x2668
Faulting application start time: 0x01d971a1562b2e7d
Faulting application path: C:\Users\timfb\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: e14401fc-b9ab-4fdb-bd68-537dfc072836
Faulting package full name: 
Faulting package-relative application ID:  }```

[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11268262/server-main.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11268263/client-main.txt)

**Comment by Craluminum2413** [comment]
Upload save file to WeTransfer

**Comment by TirNaAisling** [comment]
Getting a similar problem except it seems to be random or with multiple locations after loading into the game and walking/running in any direction the game crashes after about 1 minute or so with a similar stacktrace as below. I switched from 1.18.5 to the RC and it was ok for about 3 hours then same scenario.

Game Version: 1.18.5 and 1.18.6.rc.1

Platform: Windows

Modded: Many including Wildcraft Trees

SP/MP: Singleplayer

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.6-rc.1 (Unstable)
17/06/2023 15:53:39: Critical error occurred
Loaded Mods: ancienttools@1.5.6, backpackpackplus@1.0.3, bettercrates@1.6.0-rc.1, bth@1.2.6, bettertraders@0.0.2, chiseltools@1.8.4, composter@1.0.4, TA_fieldsandplateaus@1.0.0, pantherinae@1.0.5, furniturelibrary@1.0.9, HangingOilLamps@1.0.1, hudrealtimeclock@1.0.0, medieval@2.01.17, leadroof@1.3.4, nailsmold@1.0.1, natseasystonebricks@1.0.0, primitivesurvival@3.2.2, RelightTorches@1.0.0, simpleelevator@1.3.0, sortablestorage@1.8.0, ssppvv@1.0.5, temporalstormgear@1.0.1, translocatorengineeringredux@1.4.2, usefuldrifterloot@1.0.3, game@1.18.6-rc.1, wildcrafttrees@1.2.2, wildcraft@1.6.6, zoombuttonreborn@1.4.0, animalcages@2.1.5, canbeignited@1.1.0, carps@1.0.1, carryon@1.2.0, commonlib@2.1.1, fromgoldencombs@1.4.16-rc.1, hudclock@3.2.0, immersivecrafting@1.1.1, sailboat@1.1.0, medievalexpansion@3.9.3, petai@1.7.9, claywheel@1.1.0, primitivetools@1.4.1, prospectorinfo@4.3.0, statushud@1.2.0, stepup@1.2.0, stonebakeoven@1.0.3, stonerailings@1.1.0, creative@1.18.6-rc.1, survival@1.18.6-rc.1, woodbarrels@1.0.4, woodchests@1.0.5, workbenchexpansion@1.6.2, xlib@0.7.2, cats@1.7.0, em@2.2.1, playercorpse@1.7.1, tpnet@1.11.0-rc.1, xinvtweaks@1.5.4, xskills@0.7.3, yeet@4.0.1, bricklayers@2.2.0
Involved Harmony IDs: XSkillsPatch
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Vintagestory.GameContent.ErrorReporter.Logger_EntryAdded(EnumLogType logType, String message, Object[] args) in VSEssentials\Systems\ErrorReporter.cs:line 161
   at Vintagestory.API.Common.LogEntryDelegate.Invoke(EnumLogType logType, String message, Object[] args)
   at Vintagestory.GameContent.BlockEntityFruitTreePart.getOrCreateTexPos(AssetLocation texturePath) in VSSurvivalMod\Systems\FruitTree\BEFruitTreePart.cs:line 171
   at Vintagestory.GameContent.BlockEntityFruitTreePart.GenFoliageMesh(Boolean withSticks, MeshData& foliageMesh, MeshData& sticksMesh) in VSSurvivalMod\Systems\FruitTree\BEFruitTreePart.cs:line 190
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMeshes() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 253
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMesh() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 236
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.FromTreeAttributes_Patch1(BlockEntityFruitTreeBranch this, ITreeAttribute tree, IWorldAccessor worldForResolving)
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 420
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 424
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 747
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 165
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 683
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 17/06/2023 15:45:12, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFB514DCF19
Stack:
 }
--------------
{ TimeGenerated = 16/06/2023 17:41:11, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFB514DCF19
Stack:
 }
--------------
{ TimeGenerated = 31/05/2023 12:41:38, Site = , Source = Windows Error Reporting, Message = Fault bucket 1335260304986376884, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.5.0
P3: 64668a12
P4: KERNELBASE.dll
P5: 10.0.19041.2913
P6: a1c3e870
P7: c0020001
P8: 000000000002cf19
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER686B.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_f8c46167974585c2f0bf13ab68a82645f522526_099fad0f_870ccd38-48fe-4348-99dd-9f00c454570c

Analysis symbol: 
Rechecking for solution: 0
Report Id: b462cc36-2d30-41c6-ac3e-bcafa897db35
Report Status: 268566528
Hashed bucket: e693b9dce1462a6ab287cc2c41648ab4
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
@TirNaAisling Your issue is causedby XSkills mod

**Comment by Craluminum2413** [comment]
Closing due to inactivity
