### ISSUE TITLE
Game crashed while I stood in the middle of my burning house

### ISSUE THREAD

**Issue by Miraldin** [anegostudios/VintageStory-Issues#2631]
### Game Version

1.18.0.0

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Accidentally lit my house on fire with pit kiln, was chopping pieces of the house down to save them, and the game crashed

### Logs

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.0 (Stable)
4/20/2023 9:45:55 PM: Critical error occurred
Loaded Mods: game@1.18.0, creative@1.18.0, survival@1.18.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockBehaviorDoor.GetCollisionBoxes(IBlockAccessor blockAccessor, BlockPos pos, EnumHandling& handled) in VSSurvivalMod\BlockBehavior\BehaviorDoor.cs:line 261
   at Vintagestory.API.Common.BlockGeneric.GetCollisionBoxes(IBlockAccessor blockAccessor, BlockPos pos) in VintagestoryApi\Common\Collectible\Block\BlockGeneric.cs:line 119
   at Vintagestory.GameContent.BEBehaviorBurning.RandomBlockPos(IBlockAccessor blockAccess, BlockPos pos, Block block, BlockFacing facing) in VSSurvivalMod\BlockEntityBehavior\BEBehaviorBurning.cs:line 451
   at Vintagestory.GameContent.BEBehaviorBurning.OnTick(Single dt) in VSSurvivalMod\BlockEntityBehavior\BEBehaviorBurning.cs:line 268
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 84
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 807
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 709
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 681
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 625
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 4/20/2023 7:59:06 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2067791412495284563, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.0.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Trist\AppData\Local\Temp\RDR5AF9.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5B19.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5B1A.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5B2E.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5B4E.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: cefbda99-052b-4db5-bf57-e17334f00eee
Report Status: 268435456
Hashed bucket: f60bf9350d4e0c5a0cb2455583627953
Cab Guid: 0 }

**Comment by noelle-lavenza** [comment]
This happened on another server just now, with an independent third party—confirmed that it was a door catching fire.
The trivial solution would be this:
```diff
-    return blockAccessor.GetBlockEntity(pos)?.GetBehavior<BEBehaviorDoor>().ColSelBoxes ?? null;
+    return blockAccessor.GetBlockEntity(pos)?.GetBehavior<BEBehaviorDoor>()?.ColSelBoxes ?? null;
```
but it doesn't answer the question of why it doesn't have a BEBehaviorDoor in the first place. My blind guess is that `OnFireTick?.Invoke(dt);` consumes the fuel block, in this case a door, on the server-side on the same tick that it tries to spawn particles on the block on the client-side. It might also have something to do with doors breaking their other half in `OnBlockRemoved` but I'm not totally sure.

**Comment by tyronx** [comment]
also not totally sure tbh, but there does seem to be cases where for very short moments blocks on the client are not fully initialized. Will indeed fix it that way for now. thanks for the report and research
