### ISSUE TITLE
Game crashes on closing trading window

### ISSUE THREAD

**Issue by klimchd** [anegostudios/VintageStory-Issues#2634]
### Game Version

v1.18.0 

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

The game crashes when closing the trading window with Escape, while some other window are opened (see steps to reproduce).
The only mode I have is prospectorinfo. 

### How to reproduce

Possibly, some steps are not required, but with this steps the game crashes consistently for me:
1. Start talking to a trader
2. Open Inventory
3. Open Handbook
4. Open the trading window
5. Switch to Action house tab
6. Swithc back to Local goods tab
7. Press Escape button to close windows
8. Game crashes

### Logs

```Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.0 (Stable)
4/21/2023 3:24:01 PM: Critical error occurred
Loaded Mods: game@1.18.0, prospectorinfo@4.1.4, creative@1.18.0, survival@1.18.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.GuiDialogTrader.updateScrollbarBounds()
   at Vintagestory.Client.NoObf.NetworkChannel.<>c__DisplayClass12_0`1.<SetMessageHandler>b__0(Packet_CustomPacket p)
   at Vintagestory.Client.NoObf.NetworkChannel.OnPacket(Packet_CustomPacket p)
   at Vintagestory.Client.NoObf.NetworkAPI.HandleCustomPacket(Packet_Server packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt)
   at Vintagestory.Client.ScreenManager.Render(Single dt)
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 4/21/2023 3:14:43 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFF144FFE7C
Stack:
 }
--------------
{ TimeGenerated = 4/19/2023 12:00:01 AM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.17.11.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 }
--------------
{ TimeGenerated = 4/15/2023 8:47:21 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.17.11.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 }```

**Comment by DArkHekRoMaNT** [comment]
Probably fixed
> Fixed: Server side exception that kicks the player when talking to traders

**Comment by klimchd** [comment]
I believe it was fixed in later builds. Wasn't reproducible after an update.
