### ISSUE TITLE
it wont let me load or edit worlds

### ISSUE THREAD

**Issue by greymesa101** [anegostudios/VintageStory-Issues#2638]
### Game Version

v1.18

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

it will go to uh oh client after trying to load or edit worlds 

### Logs

```Log```Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.0 (Stable)
4/21/2023 2:47:21 PM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.WorldConfig.loadWorldConfigValuesFromPlaystyle() in VintagestoryLib\Common\Config\WorldConfig.cs:line 109
   at Vintagestory.Common.WorldConfig.loadFromSavegame(SaveGame savegame) in VintagestoryLib\Common\Config\WorldConfig.cs:line 57
   at Vintagestory.Client.GuiScreenSingleplayerModify.initGui(SaveGame savegame) in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayerModify.cs:line 52
   at Vintagestory.Client.GuiScreenSingleplayerModify.OnScreenLoaded() in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayerModify.cs:line 175
   at Vintagestory.Client.ScreenManager.LoadScreen(GuiScreen screen) in VintagestoryLib\Client\ScreenManager.cs:line 941
   at Vintagestory.API.Client.GuiElementMainMenuCell.OnMouseUpOnElement(MouseEvent args, Int32 elementIndex) in VintagestoryApi\Client\UI\Elements\Impl\Misc\GuiElementMainMenuCell.cs:line 312
   at Vintagestory.API.Client.GuiElementCellList`1.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 241
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 675
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at GuiScreen.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\MainMenu\Screens\Special\GuiScreen.cs:line 205
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 229
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 4/21/2023 2:38:32 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2189012429644942853, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.0.0
P3: 64400ea0
P4: VintagestoryAPI
P5: 1.7.0.0
P6: 64400e9c
P7: 1bea
P8: 4d1
P9: System.NullReferenceException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6b9b7341-007d-4542-a17b-76402232aa51.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.65275840-36ef-4652-8e60-cbf44f41f448.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e31b64ad-2254-4a62-ba24-958063aca200.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c6c52db8-1fa5-4e7d-a3b1-7cab93b3c4e5.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.abc39aec-1963-4b60-9ee2-a754b5eff502.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_25f4ae942d663e4e57cff655ecca21e43e633cb_020c1ab9_49fc80fc-2b49-43fc-9719-55226b138157

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2836770e-62b4-4d71-b086-6f3399a6f4bd
Report Status: 268435456
Hashed bucket: 78823a52c7e58c923e60ef34f5e6ce05
Cab Guid: 0 }
--------------
{ TimeGenerated = 4/21/2023 2:38:29 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.0.0, time stamp: 0x64400ea0
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ffe5976bc43
Faulting process id: 0x0x1bb8
Faulting application start time: 0x0x1d97488b43dac69
Faulting application path: C:\Users\Sean Krop\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: unknown
Report Id: 2836770e-62b4-4d71-b086-6f3399a6f4bd
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 4/21/2023 2:38:18 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor, Boolean)
   at UsefulStuff.ItemToolhead.GetHeldItemInfo(Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor, Boolean)
   at Vintagestory.API.Common.ItemStack.GetDescription(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot, Boolean)
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Common.ItemStack)
   at Vintagestory.GameContent.ModSystemHandbook.onCreatePagesAsync()
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }

**Comment by greymesa101** [comment]
help

**Comment by noelle-lavenza** [comment]
It looks like you might have disabled the base-game survival/creative/game 'mods'. Can you go into the mods menu and make sure those are enabled?

**Comment by Th3Dilli** [comment]
I assume the issue is resolved if not let us know
