### ISSUE TITLE
Crashing when generating world on 1.18.0

### ISSUE THREAD

**Issue by UrsulaWinters** [anegostudios/VintageStory-Issues#2641]
### Game Version

v1.18.0

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Getting a crash to desktop right at the end of generating a world, so the world doesn't load up. 'Uh Oh Crash' dialogue opens with this text:

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.0 (Stable)
22/04/2023 6:44:53 PM: Critical error occurred in the following mod: hudclock@2.8.0
Loaded Mods: game@1.18.0, carryon@0.10.3, hudclock@2.8.0, creative@1.18.0, survival@1.18.0
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.Pos'.
   at hudclock.src.ui.ClaimAreaDialog.RequestClaimInfoOfPlayerPosition(Single gameTick)
   at hudclock.src.ui.ClaimAreaDialog.Build()
   at hudclock.src.busineslogic.ClaimDialogController..ctor(ICoreClientAPI clientApi, ClockModSettingsController clockModSettingsController)
   at hudlock.src.HUDClockMod.PlayerReady(EnumHandling& handling)
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerIsPlayerReady() in VintagestoryLib\Client\API\ClientEventAPI.cs:line 379
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 300
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 745
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 304
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 724
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

### How to reproduce

1. Open VS v1.18.0
2. Create new world
3. Wait while it generates
4. Crash right before you would appear in the world 

### Logs

```Log```

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.0 (Stable)
22/04/2023 6:44:53 PM: Critical error occurred in the following mod: hudclock@2.8.0
Loaded Mods: game@1.18.0, carryon@0.10.3, hudclock@2.8.0, creative@1.18.0, survival@1.18.0
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.Pos'.
   at hudclock.src.ui.ClaimAreaDialog.RequestClaimInfoOfPlayerPosition(Single gameTick)
   at hudclock.src.ui.ClaimAreaDialog.Build()
   at hudclock.src.busineslogic.ClaimDialogController..ctor(ICoreClientAPI clientApi, ClockModSettingsController clockModSettingsController)
   at hudlock.src.HUDClockMod.PlayerReady(EnumHandling& handling)
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerIsPlayerReady() in VintagestoryLib\Client\API\ClientEventAPI.cs:line 379
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 300
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 745
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 304
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 724
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by UrsulaWinters** [comment]
Uninstalled and re-installed, fixed the issue.
