### ISSUE TITLE
Crash upon joining Server

### ISSUE THREAD

**Issue by Burgersim** [anegostudios/VintageStory-Issues#2643]
### Game Version

v1.18.1

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

I can't seem to join our Server anymore, I get a crash when I want to join, but even removing the Mod in question didn't fix the issue, neither did restarting my PC, so I think it might be something else, and maybe worthwhile sharing as a bug report.

### How to reproduce

1. Start Game
2. Join Server [it was a modded server, specifically with the "Wooden Barrels" mod installed, but then I removed it after the crash of my client]
4. Crash

### Logs

```Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.1 (Stable)
22/04/2023 15:31:04: Critical error occurred
Loaded Mods: chiseltools@1.8.4, fieldsofgold@2.1.6, HangingOilLamps@1.0.1, indappledgroves@0.4.9-rc.1, moreclasses@1.2.5, primitivesurvival@3.1.6, game@1.18.1, wildcrafttrees@1.1.5, wildcraft@1.6.4, canbeignited@1.1.0, carryon@1.0.0, fromgoldencombs@1.4.16-rc.1, morepiles@1.3.0, petai@1.7.0, usefulstuff17@1.1.3, creative@1.18.1, survival@1.18.1, woodbarrels@1.0.4, bullseye@2.5.0-rc.1, cats@1.7.0, foxtaming@1.2.0, wolftaming@1.7.1
System.IO.FileNotFoundException: Unable to find the specified file.
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(String type, AssetLocation name, CompositeShape compositeShape, MeshData& modeldata, ITexPositionSource texSource, Int32 generalGlowLevel, Byte climateColorMapIndex, Byte seasonColorMapIndex, Nullable`1 quantityElements, String[] selectiveElements) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 51
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateItem(Item item, CompositeShape forShape, MeshData& modeldata) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 679
   at Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateItems(IList`1 itemtypes, Int32 offset, Int32 maxCount) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselatorManager.cs:line 848
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step7(Int32 index, Int32 frameCount) in VintagestoryLib\Client\Systems\Startup.cs:line 713
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 755
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 304
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 724
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 22/04/2023 13:15:45, Site = , Source = Windows Error Reporting, Message = Fault bucket 1705107713394937137, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.1.0
P3: 6443b447
P4: clr.dll
P5: 4.8.9105.0
P6: 632272c6
P7: c00000fd
P8: 000000000019dffb
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c904cb98-1e65-46a3-9c43-0cd40351eb3b.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a2050161-d7fd-49e5-8fae-233d7b143f99.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c8d940fe-a77c-4097-ae59-6b1782398dd3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4eba4e1c-129f-4f8a-a164-4248e6c03f8f.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e3c12553-5806-44a0-977b-5e53076693dd.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_652b1c2f10b55dffe150eeeb4af079b19c818061_844f11b8_1f70321f-cfcd-499f-8afa-c2a6abd8f793

Analysis symbol: 
Rechecking for solution: 0
Report Id: 828a53b6-8e77-4613-a8f6-8d9456c7c555
Report Status: 268435456
Hashed bucket: 8e517102bb8ffe4dd7a9c26e68af0d31
Cab Guid: 0 }
--------------
{ TimeGenerated = 22/04/2023 13:15:16, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.1.0, time stamp: 0x6443b447
Faulting module name: clr.dll, version: 4.8.9105.0, time stamp: 0x632272c6
Exception code: 0xc00000fd
Fault offset: 0x000000000019dffb
Faulting process id: 0x0x16f4
Faulting application start time: 0x0x1d9750b169c7b09
Faulting application path: C:\Users\Mika\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: 828a53b6-8e77-4613-a8f6-8d9456c7c555
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 22/04/2023 10:52:10, Site = , Source = Windows Error Reporting, Message = Fault bucket 1812512002548946840, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.0.0
P3: 10.0.22621.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Mika\AppData\Local\Temp\RDRD8B1.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e61e888f-c266-449a-afd9-d868dad94886.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.565dfc95-7e64-4999-a90b-48f917b0cfc9.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d4dd5a18-244f-47bc-a853-8c147eacc11e.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.01e5469a-7f03-4023-b4aa-46b3bd42d905.tmp.xml

These files may be available here:
NULL

Analysis symbol: 
Rechecking for solution: 0
Report Id: 655fc886-2839-4a13-88a1-6d30bf67480f
Report Status: 268435456
Hashed bucket: 7d8d6ab9eea4b436192756102f0fd798
Cab Guid: 0 }```

**Comment by radfast** [comment]
It's a mod issue, but I don't know which mod.  If it's your server, please carefully check that you have on your own client PC all the exact same mod files which are on the server, none of them was edited somehow.

Try also starting with the same selection of mods in single player, see if you get the same issue.  If so, you can maybe try disabling one or two mods at a time until the issue stops, then you will know which one and can inform the mod's author.

We can add to a future version of the game some code which messages which mod is erroring at this point, but that won't help you right now unfortunately.

**Comment by radfast** [comment]
Actually ... the `client-main.txt` log will already have a log line near the end reading something like this:
`Could not find shape NNNNN for Item XXXXXX`
This will probably tell you which mod, it may be named in the NNNNN.   If the NNNNN is a vanilla game item then look for mods which alter that item.
