### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by virror** [anegostudios/VintageStory-Issues#2649]
### Game Version

1.18.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Game crashed at world generation

### Logs

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.1 (Stable)
2023-04-22 22:55:15: Critical error occurred
Loaded Mods: game@1.18.1, playercorpse@1.3.1, prospectorinfo@3.1.2, creative@1.18.1, survival@1.18.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.ServerMods.ModStdWorldGen.LoadGlobalConfig(ICoreServerAPI api) in VSSurvivalMod\Systems\WorldGen\Standard\ModStdWorldGen.cs:line 31
   at Vintagestory.ServerMods.GenRockStrataNew.initWorldGen(Int32 seedDiff) in VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\2.GenRockStrata\GenRockStrata.cs:line 71
   at Vintagestory.GameContent.ProPickWorkSpace.<>c__DisplayClass5_0.<OnLoaded>b__0() in VSSurvivalMod\Item\ItemProspectingPick.cs:line 40
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2023-04-22 22:55:15, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.ServerMods.ModStdWorldGen.LoadGlobalConfig(Vintagestory.API.Server.ICoreServerAPI)
   at Vintagestory.ServerMods.GenRockStrataNew.initWorldGen(Int32)
   at Vintagestory.GameContent.ProPickWorkSpace+<>c__DisplayClass5_0.<OnLoaded>b__0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 2022-06-07 10:03:41, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.16.5.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 2d14

Start Time: 01d87a44fd5d5d74

Termination Time: 6

Application Path: D:\spel\Vintagestory\Vintagestory.exe

Report Id: d1747c95-4eca-4e10-a08d-940ac8aac8b5

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 2022-05-20 17:50:19, Site = , Source = Windows Error Reporting, Message = Fault bucket 1169322480264892805, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Victor\AppData\Local\Temp\RDR407E.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER407F.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER409F.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER40AD.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER40CD.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: f0a3b041-49db-4083-b33d-0513352bd81b
Report Status: 268435456
Hashed bucket: 66b2146b18168122903a4499b8115185
Cab Guid: 0 }

**Comment by lOmicronl** [comment]
You specify "vanilla", but the crashlog clearly shows third-party mods being loaded. Try disabling them first.
