### ISSUE TITLE
Game Crash While Hoeing Tera Preta With Vanilla Hoe

### ISSUE THREAD

**Issue by TirNaAisling** [anegostudios/VintageStory-Issues#2653]
Game crash while hoeing tera preta (loads of mods but was not interacting with modded items)

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.1 (Stable)
23/04/2023 16:45:48: Critical error occurred
Loaded Mods: backpackpackplus@1.0.3, beekeeper@1.0.0, bettercrates@1.6.0-rc.1, bth@1.2.4, chiseltools@1.8.4, composter@1.0.4, DeepStorage@0.0.3, extrachests@1.7.0, fancysky@1.0.6, TA_fieldsandplateaus@1.0.0, furniturelibrary@1.0.8, HangingOilLamps@1.0.1, hudrealtimeclock@1.0.0, medieval@2.01.06, nailsmold@1.0.1, pieontheshelf@1.0.0, primitivesurvival@3.1.6, qptech@1.13.02, RangedWeapons@0.5.2, RelightTorches@1.0.0, ruststones@1.0.3, simpleelevator@1.3.0, sortablestorage@1.8.0, temporalstormgear@1.0.1, translocatorengineeringredux@1.4.1, game@1.18.1, wildcrafttrees@1.1.5, wildcraft@1.6.4, zoombuttonreborn@1.4.0, animalcages@2.1.4, canbeignited@1.1.0, carps@1.0.1, carryon@1.0.0-rc.2, commonlib@2.0.4, fromgoldencombs@1.4.16-rc.1, glidervar@1.1.0, hudclock@2.9.1, immersivecrafting@1.1.1, sailboat@1.0.0, medievalexpansion@3.9.0, mcrate@1.0.4, petai@1.7.0, claywheel@1.0.1, primitivetools@1.3.2, scarecrow@1.1.0, stepup@1.2.0, creative@1.18.1, survival@1.18.1, woodbarrels@1.0.4, woodchests@1.0.5, cats@1.7.0, em@2.0.0-pre.5, playercorpse@1.7.1, tpnet@1.10.1, treetapping@1.0.0, wolftaming@1.7.0, yeet@4.0.1, bricklayers@2.0.0-pre.4
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockGroundStorage.GetRandomColor(ICoreClientAPI capi, BlockPos pos, BlockFacing facing, Int32 rndIndex) in VSSurvivalMod\Block\BlockGroundStorage.cs:line 321
   at Vintagestory.GameContent.ChunkMapLayer.GenerateChunkImage(Vec2i chunkPos, IMapChunk mc, Int32[]& tintedImage, Boolean withSnow) in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 426
   at Vintagestory.GameContent.ChunkMapLayer.OnOffThreadTick(Single dt) in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 265
   at Vintagestory.GameContent.WorldMapManager.<OnLoaded>b__23_0() in VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 231
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 23/04/2023 16:46:02, Site = , Source = Windows Error Reporting, Message = Fault bucket 1351333418635644546, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.1.0
P3: 6443b447
P4: VSSurvivalMod
P5: 1.18.1.0
P6: 6443b446
P7: e33
P8: 0
P9: System.NullReferenceException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER47BC.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_15401836cecf2c015bffb6ca6692ead944d7af7_844f11b8_f2fcc122-ae73-424a-9b96-8f26b448b5e2

Analysis symbol: 
Rechecking for solution: 0
Report Id: c5da2315-caa8-49b8-a28b-4d2ada59f24b
Report Status: 268435456
Hashed bucket: d9e5a724a70a1999d2c0e695a6e44e82
Cab Guid: 0 }
--------------
{ TimeGenerated = 23/04/2023 16:46:00, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.1.0
P3: 6443b447
P4: VSSurvivalMod
P5: 1.18.1.0
P6: 6443b446
P7: e33
P8: 0
P9: System.NullReferenceException
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_15401836cecf2c015bffb6ca6692ead944d7af7_844f11b8_f2fcc122-ae73-424a-9b96-8f26b448b5e2

Analysis symbol: 
Rechecking for solution: 0
Report Id: c5da2315-caa8-49b8-a28b-4d2ada59f24b
Report Status: 4
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 23/04/2023 16:45:57, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.1.0, time stamp: 0x6443b447
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ff9b6414fbe
Faulting process ID: 0x63e8
Faulting application start time: 0x01d975e7ae076ce6
Faulting application path: C:\Users\rodtm\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: unknown
Report ID: c5da2315-caa8-49b8-a28b-4d2ada59f24b
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Is it easily reproduceable? Could you try to reproduce it without any mods installed?

**Comment by Craluminum2413** [comment]
Closing due to inactivity
