### ISSUE TITLE
DivideByZeroException

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#2682]
### Game Version

1.18.1

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Logs

```[Server Worldgen] An error was thrown in pass TerrainFeatures when generating chunk column X=860,Z=1338 in world 'CoB' with seed 982821

Exception System.DivideByZeroException: Attempted to divide by zero.

   at Vintagestory.API.MathTools.LCGRandom.NextInt(Int32 max) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Math\LCGRandom.cs:line 149

   at Vintagestory.ServerMods.WorldGenStructure.TryGenerateRuinAtSurface(IBlockAccessor blockAccessor, IWorldAccessor worldForCollectibleResolve, BlockPos pos) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\6.GenStructures\WorldGenStructure.cs:line 438

   at Vintagestory.ServerMods.WorldGenStructure.TryGenerate(IBlockAccessor blockAccessor, IWorldAccessor worldForCollectibleResolve, BlockPos startPos, Int32 climateUpLeft, Int32 climateUpRight, Int32 climateBotLeft, Int32 climateBotRight) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\6.GenStructures\WorldGenStructure.cs:line 225

   at Vintagestory.ServerMods.GenStructures.DoGenStructures(IMapRegion region, Int32 chunkX, Int32 chunkZ, Boolean postPass, ITreeAttribute chunkGenParams) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\6.GenStructures\GenStructures.cs:line 228

   at Vintagestory.ServerMods.GenStructures.OnChunkColumnGen(IChunkColumnGenerateRequest request) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\6.GenStructures\GenStructures.cs:line 159

   at Vintagestory.Server.ServerSystemSupplyChunks.runGenerators(ChunkColumnLoadRequest chunkRequest, Int32 forPass) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 1474```

**Comment by WickedSchnitzel** [comment]
We have mods installed that add new ruins, not sure if that has to do with it.

**Comment by Craluminum2413** [comment]
Judging by log it is most likely the mod is to blame

**Comment by radfast** [comment]
Thanks for reporting.  I've fixed the crash next build.   But like Craluminum2413 said, it is a mod causing the issue.  One (or more) of the ruins which the mod adds, most likely has a JSON parsing error causing loading of the ruins to fail.   The DivideByZero occurred because there are zero ruins loaded.

Check your `server-main` log for loading errors, that should help you find which mod file is the problem.
