### ISSUE TITLE
crash on join game, or immediate connection problem if join happens

### ISSUE THREAD

**Issue by psy-borg** [anegostudios/VintageStory-Issues#2688]
### Game Version

v1.18.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Was able to join my friend through hamachi and play fine yesterday, now I cannot though.
Connecting takes a very long time (5ish minutes compared to maybe 1 min yesterday)
after receiving about 800kb of data it either crashes or I load in and then I get an error in the top right saying host not responding
we both restarted our PCs, as well as making an new hamachi server, so I don't really know what else to do...

### Logs

```Log```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.1 (Stable)
4/30/2023 12:45:14 AM: Critical error occurred
Loaded Mods: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2283
   at Vintagestory.API.Common.CollectibleObject.AppendPerishableInfoText(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1650
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1502
   at Vintagestory.API.Common.Block.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 2173
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 403
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(ICoreClientAPI capi, ItemStack stack) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 42
   at Vintagestory.GameContent.ModSystemHandbook.onCreatePagesAsync() in VSSurvivalMod\Systems\Handbook\Handbook.cs:line 79
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 489
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 4/30/2023 12:45:14 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at System.Threading.ThreadLocal`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetValueSlow()
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot)
   at Vintagestory.API.Common.CollectibleObject.AppendPerishableInfoText(Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor)
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor, Boolean)
   at Vintagestory.API.Common.Block.GetHeldItemInfo(Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor, Boolean)
   at Vintagestory.API.Common.ItemStack.GetDescription(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot, Boolean)
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Common.ItemStack)
   at Vintagestory.GameContent.ModSystemHandbook.onCreatePagesAsync()
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 4/30/2023 12:28:33 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at System.Threading.ThreadLocal`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetValueSlow()
   at Vintagestory.GameContent.BlockClutterBookshelf.RandomType(System.String)
   at Vintagestory.GameContent.BlockClutterBookshelf.GetTypeProps(System.String, Vintagestory.API.Common.ItemStack, Vintagestory.GameContent.BEBehaviorShapeFromAttributes)
   at Vintagestory.GameContent.BlockShapeFromAttributes.GetLightHsv(Vintagestory.API.Common.IBlockAccessor, Vintagestory.API.MathTools.BlockPos, Vintagestory.API.Common.ItemStack)
   at Vintagestory.API.Common.Block.GetHeldItemInfo(Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor, Boolean)
   at Vintagestory.GameContent.BlockShapeFromAttributes.GetHeldItemInfo(Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor, Boolean)
   at Vintagestory.API.Common.ItemStack.GetDescription(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot, Boolean)
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Common.ItemStack)
   at Vintagestory.GameContent.ModSystemHandbook.onCreatePagesAsync()
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 4/28/2023 10:27:25 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1670071779740885116, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.1.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Morgan\AppData\Local\Temp\RDR9F2E.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9F3E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9F3F.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9F5A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9F8A.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 92d7138b-1f91-4731-b8ff-f9fee3778fa5
Report Status: 268435456
Hashed bucket: 02f805af833ad552072d496f6cdc207c
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
Have you tried to use Radmin VPN instead? What mods are installed on the server?

**Comment by psy-borg** [comment]
> 

I haven't, but I'll give that a shot. Also, there are no mods installed except the 3 that are preinstalled.

**Comment by radfast** [comment]
Please post a full `server-main` log for a server run when the issue happens, also `server-debug` log

**Comment by Craluminum2413** [comment]
Closing due to inactivity

**Comment by Natsew** [comment]
I have a player on my server that seems to be encountering similar problem. He was playing just fine, then one day his connection take 5+ minutes, and often he can't join at all. His client log is this:

`Running on 64 bit Windows 10.0.22621.0 with 32559 MB RAM
Game Version: v1.19.7 (Stable)
4/21/2024 6:26:56 PM: Critical error occurred
Loaded Mods: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2466
   at Vintagestory.API.Common.CollectibleObject.AppendPerishableInfoText(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1822
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1759
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(ICoreClientAPI capi, ItemStack stack) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 33
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onCreatePagesAsync() in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 79
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 418
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()`
   
   Server log has no issues at all, the server seems to be placing player in the world like everyone else, the problem with client somewhere.
   
   Any ideas oe what info we can collect to pinpoint this?

**Comment by Craluminum2413** [comment]
@Natsew Any mods?

**Comment by Natsew** [comment]
@Craluminum2413 Quite a few, but this issue happend to me/people I know randomly at random server that not run the same mods, so not sure what affects it, maybe the presence of mods in the first place?

Game version: 1.19.7
Mods:
  A Culinary Artillery @ 1.1.4 | Universal
  chiseltools @ 1.11.2 | Universal
  Fauna of the Stone Age: Caninae @ 1.0.11 | Universal
  Fauna of the Stone Age: Capreolinae @ 1.1.0 | Universal
  Fauna of the Stone Age: Casuariidae @ 1.0.1 | Universal
  Fauna of the Stone Age: Machairodontinae @ 1.0.4 | Universal
  Fauna of the Stone Age: Pantherinae @ 1.1.4 | Universal
  Fauna of the Stone Age: Sirenia @ 1.0.1 | Universal
  Hanging Oil Lamps @ 1.0.1 | Universal
  Immersive Corpse Drop @ 1.0.2 | Universal
  Millwright @ 1.1.4 | Universal
  Primitive Survival @ 3.5.1 | Universal
  Spyglass @ 0.5.1 | Universal
  Translocator Engineering Redux @ 1.4.9 | Universal
  VanillaPlus WorldGen @ 1.3.5 | Server
  Essentials @ 1.19.7 | Universal
  Animal cages @ 3.0.2 | Universal
  Animation Manager @ 0.7.14 | Universal
  Carry On @ 1.7.4 | Universal
  CommonLib @ 2.3.7 | Universal
  Expanded Foods @ 1.6.9 | Universal
  FairPlayGuardian @ 1.1.7 | Universal
  Immersive Wood Chopping @ 0.7.1 | Universal
  Joy of Sailing @ 1.3.0 | Universal
  Meteoric Expansion @ 1.2.5 | Universal
  PelagusAI @ 1.0.1 | Server
  PelagusTweaks @ 1.0.1 | Server
  Pelagus Winds @ 1.0.0 | Universal
  Th3Dungeon @ 0.2.1 | Universal
  Vinconomy @ 0.2.5 | Universal
  Creative Mode @ 1.19.7 | Universal
  Survival Mode @ 1.19.7 | Universal
  Bullseye @ 2.5.8 | Universal
  Expanded Matter @ 2.5.2 | Universal
  Player Corpse @ 1.9.0 | Universal
  Stone Quarry @ 3.2.1 | Universal
  Th3DungeonTopEntrance @ 0.1.0 | Server
  Th3Essentials @ 2.8.1 | Server
  Bricklayers @ 2.5.1 | Universal

**Comment by Natsew** [comment]
Now we try random things, and he is unable to even download mods for the server if clearing data folder - game freezes without a crash log. Trying to see if any errors in log files.

**Comment by Craluminum2413** [comment]
@Natsew Can't help with mods sadly

**Comment by Natsew** [comment]
@Craluminum2413 Isn't the mod downloader core part of the game? Just asking, I'm fine if it's provided 'as it' for now.

**Comment by Craluminum2413** [comment]
@Natsew Mods can be absolutely unpredictable

**Comment by Natsew** [comment]
@Craluminum2413 I agree with that completely, but I'm not sure the mod downloader is a mod, it's part of the game, and it's not working too for some reason for that player. Well, I guess I'll try to remove mod-by-mod to at least see if it helps him.
