### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by MedakOfVoid** [anegostudios/VintageStory-Issues#2692]
### Game Version

v1.18.1 (Stable

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Every time I try to customize a world it crashes to desktop

### Logs

```Log```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.1 (Stable)
5/2/2023 12:22:49 AM: Critical error occurred
Loaded Mods: game@1.18.1, creative@1.18.1, survival@1.18.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.WorldConfig.loadWorldConfigValuesFromPlaystyle() in VintagestoryLib\Common\Config\WorldConfig.cs:line 109
   at Vintagestory.Common.WorldConfig.loadFromSavegame(SaveGame savegame) in VintagestoryLib\Common\Config\WorldConfig.cs:line 57
   at Vintagestory.Client.GuiScreenSingleplayerModify.initGui(SaveGame savegame) in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayerModify.cs:line 52
   at Vintagestory.Client.GuiScreenSingleplayerModify.OnScreenLoaded() in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayerModify.cs:line 175
   at Vintagestory.Client.ScreenManager.LoadScreen(GuiScreen screen) in VintagestoryLib\Client\ScreenManager.cs:line 941
   at Vintagestory.API.Client.GuiElementMainMenuCell.OnMouseUpOnElement(MouseEvent args, Int32 elementIndex) in VintagestoryApi\Client\UI\Elements\Impl\Misc\GuiElementMainMenuCell.cs:line 312
   at Vintagestory.API.Client.GuiElementCellList`1.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 241
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 675
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at GuiScreen.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\MainMenu\Screens\Special\GuiScreen.cs:line 205
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 229
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/26/2022 8:43:24 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1356069915386531490, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Notandi\AppData\Local\Temp\RDR38D2.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER38D3.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER38E4.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3911.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3931.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 6108b295-1715-49e0-8760-2a22efffbd1d
Report Status: 268435456
Hashed bucket: b6682851523a865272d1ba673d354ea2
Cab Guid: 0 }

**Comment by radfast** [comment]
Thanks for reporting.  Which playstyle are you choosing?  (Standard / Exploration / Wilderness Survival / Homo Sapiens / Creative Building)

**Comment by radfast** [comment]
Looks like you are trying to modify the configs on an existing world - not create a new world.

If I'm right, then the likely cause was that the save game was made previously with a playstyle which no longer exists (possible reason: you were testing a mod before, and now you disabled or uninstalled that mod; maybe even an earlier version of Vintage Story but I don't remember us having other playstyles).

If that's the reason for the crash then you will not be able to modify this particular save game until you re-install/re-enable that mod.  Unless you do that, modifying this one will always crash.  Hopefully meanwhile you are able to create and modify other savegames, for example ones newly created in 1.18.1?

**Comment by Craluminum2413** [comment]
Closing due to inactivity
