### ISSUE TITLE
Game Crash in Resonance Archive

### ISSUE THREAD

**Issue by Haloroy** [anegostudios/VintageStory-Issues#2701]
### Game Version

v1.18.1

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

Game crashes as soon as I login and try to move, I am in the resonance archive

### How to reproduce

I don't know how to reproduce it as I cannot actually get into the server to do anything without my game immediately crashing

### Screenshots

![image](https://user-images.githubusercontent.com/132730735/236598916-3ef7785a-48ef-4f66-88a8-6d91b544f86a.png)

### Logs

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.1 (Stable)
5/5/2023 8:58:41 PM: Critical error occurred
Loaded Mods: game@1.18.1, creative@1.18.1, survival@1.18.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.CollectibleBehaviorArtPigment.SuitablePosition(IBlockAccessor blockAccessor, BlockSelection blockSel) in VSSurvivalMod\CollectibleBehavior\BehaviorArtPigment.cs:line 291
   at Vintagestory.GameContent.CollectibleBehaviorArtPigment.GetToolModes(ItemSlot slot, IClientPlayer forPlayer, BlockSelection blockSel) in VSSurvivalMod\CollectibleBehavior\BehaviorArtPigment.cs:line 304
   at Vintagestory.API.Common.CollectibleObject.GetToolModes(ItemSlot slot, IClientPlayer forPlayer, BlockSelection blockSel) in VintagestoryApi\Common\Collectible\Collectible.cs:line 848
   at Vintagestory.Client.NoObf.HudHotbar.UpdateCurrentToolMode(Int32 newSlotIndex) in VintagestoryLib\Client\Systems\Gui\Huds\HudHotbar.cs:line 139
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 84
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 807
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 709
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 681
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 625
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 4/8/2023 1:12:29 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1402421717052153672, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 10.0.22621.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\seang\AppData\Local\Temp\RDR8A7B.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0c266e4a-fb99-471f-9bee-a68196bff413.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b032fca2-a11b-4fd9-ab2d-bb770499ec78.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.3a469ba0-46cf-40ca-bb27-8453d7b5dfc4.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.77030f1c-4cca-4a11-8b4a-1da39a028f09.tmp.xml

These files may be available here:
NULL

Analysis symbol: 
Rechecking for solution: 0
Report Id: 079a61d0-8bfa-45c4-a9a7-453dcc230eed
Report Status: 268435456
Hashed bucket: 84f56296e9742f3d9376671f0e2fdf48
Cab Guid: 0 }
--------------
{ TimeGenerated = 4/8/2023 1:05:17 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1337532351180295070, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.6.0
P3: 633bf838
P4: KERNELBASE.dll
P5: 10.0.22621.1413
P6: 5129184b
P7: c000041d
P8: 000000000008fe7c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.642f7f82-7ece-41ce-9cee-a449b5652c5e.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_568c15754455634a8f360d949e240a860d134da_9614c485_11ac2620-345e-493a-a3b8-df511ce95b7f

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2d7e7b02-0e53-4813-94f6-0b8caf4bec46
Report Status: 268439552
Hashed bucket: 988c081f30eba3ab828fde963bb1cb9e
Cab Guid: 0 }
--------------
{ TimeGenerated = 4/8/2023 1:04:55 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1448050012886150870, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.6.0
P3: 633bf838
P4: KERNELBASE.dll
P5: 10.0.22621.1413
P6: 5129184b
P7: c0020001
P8: 000000000008fe7c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.79c2acfa-aacf-449b-9b28-5a529c7ee89a.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.15742c78-f39d-4095-bf63-9aabe621e6ad.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.cd7d03a0-a8ac-4457-843c-f07375c7d41a.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ac63c397-95a9-4b8f-a0b4-5e5905945343.tmp.txt
\\?\C:\Users\seang\AppData\Local\Temp\WER.6f7b4ec4-226a-4f63-8890-508ed6909051.tmp.appcompat.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9c9a5ddf-84b4-4c03-9ecf-9bd1ca45fbb3.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_ed42f41dc64d20eb9bb876abf8013702d66830_9614c485_e1b09525-a050-4cf9-a669-2fc58ab880b5

Analysis symbol: 
Rechecking for solution: 0
Report Id: a8149d66-7f5a-48b4-8b81-38aff6bf3fc1
Report Status: 268435456
Hashed bucket: 4af5d8f90548fe79a41881d08b142ed6
Cab Guid: 0 }

**Comment by radfast** [comment]
Thanks for reporting.  This issue was reported also on Discord #bug-reports channel.  We believe it is fixed in next 1.18.2 release. If you still can't get into your game when the next release comes out (likely tonight or tomorrow but no guarantee), please re-open this issue.

**Comment by radfast** [comment]
1.18.2-rc3 is now out, please try it.  Should fix this issue, hopefully no more issues.  :)
