### ISSUE TITLE
Game Crashes when attempting to talk to trader/merchant

### ISSUE THREAD

**Issue by Razotar** [anegostudios/VintageStory-Issues#2703]
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.2-rc.2 (Unstable)
5/6/2023 1:51:38 PM: Critical error occurred
Loaded Mods: game@1.18.2-rc.2, creative@1.18.2-rc.2, survival@1.18.2-rc.2
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.DlgTalkComponent.Execute() in VSSurvivalMod\Systems\Dialogue\Component\DlgTalkComponent.cs:line 17
   at Vintagestory.GameContent.DialogueController.ContinueExecute() in VSSurvivalMod\Systems\Dialogue\DialogueController.cs:line 92
   at Vintagestory.GameContent.EntityBehaviorConversable.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode, EnumHandling& handled) in VSSurvivalMod\Systems\Dialogue\BehaviorConversable.cs:line 249
   at Vintagestory.API.Common.EntityAgent.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 293
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 438
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 197
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 789
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 981
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 243
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 724
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 4/14/2023 4:28:35 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1812512002548946840, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.0.0
P3: 10.0.22621.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\razot\AppData\Local\Temp\RDR5512.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.2c4c7f2c-289f-4e5d-be28-f8234205f2d8.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.65908a98-0633-498a-b187-c494b8eba4d8.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.657af034-4e68-4fd1-b9b9-e4cffa7cc80b.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d3a14afe-6475-4a54-b7f0-01741cd27a8d.tmp.xml

These files may be available here:
NULL

Analysis symbol: 
Rechecking for solution: 0
Report Id: 78a3aaed-0ee7-4551-91c8-75d43ca6a350
Report Status: 268435456
Hashed bucket: 7d8d6ab9eea4b436192756102f0fd798
Cab Guid: 0 }
--------------
{ TimeGenerated = 2/18/2023 8:04:28 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1402421717052153672, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 10.0.22621.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\razot\AppData\Local\Temp\RDR5388.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f36ddcad-70d3-4ff6-a543-180a0b74f76e.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.36762c03-e843-4c51-840a-71ff56936e27.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.75f72fa8-7c33-410f-b31f-178c71919b88.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.370c7091-b851-4b13-ba23-7a3bf17da3e5.tmp.xml

These files may be available here:
NULL

Analysis symbol: 
Rechecking for solution: 0
Report Id: 448da4b3-1e24-4321-a5c2-5dfc1d941192
Report Status: 268435456
Hashed bucket: 84f56296e9742f3d9376671f0e2fdf48
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
[Duplicate](https://github.com/anegostudios/VintageStory-Issues/issues/2700#issuecomment-1537158145)

**Comment by radfast** [comment]
1.18.2-rc3 is now out, please try it.  Fixes the trader issues, hopefully no more issues.  :)
