### ISSUE TITLE
Crash log, talking to NPC on new world

### ISSUE THREAD

**Issue by Jesper-Andersson** [anegostudios/VintageStory-Issues#2707]
Created a new world.

Walked around for 5 minutes gathering items.

Changed some graphics settings.

Attempted to talk to a NPC in a cart which caused CTD

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.2-rc.2 (Unstable)
07/05/2023 20:50:23: Critical error occurred
Loaded Mods: game@1.18.2-rc.2, creative@1.18.2-rc.2, survival@1.18.2-rc.2
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.DlgTalkComponent.Execute() in VSSurvivalMod\Systems\Dialogue\Component\DlgTalkComponent.cs:line 17
   at Vintagestory.GameContent.DialogueController.ContinueExecute() in VSSurvivalMod\Systems\Dialogue\DialogueController.cs:line 92
   at Vintagestory.GameContent.EntityBehaviorConversable.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode, EnumHandling& handled) in VSSurvivalMod\Systems\Dialogue\BehaviorConversable.cs:line 249
   at Vintagestory.API.Common.EntityAgent.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 293
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 438
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 197
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 789
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 981
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 243
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 724
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 07/05/2023 20:36:19, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.9.0, time stamp: 0x63501532
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1680, time stamp: 0x0a48b2f9
Exception code: 0xc000041d
Fault offset: 0x000000000006536c
Faulting process ID: 0x0x4618
Faulting application start time: 0x0x1d9810a58691d06
Faulting application path: C:\Users\Jesper\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 7f5bec14-cec8-409f-86c3-e4892f52f446
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 07/05/2023 20:36:18, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.9.0, time stamp: 0x63501532
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1680, time stamp: 0x0a48b2f9
Exception code: 0xc0020001
Fault offset: 0x000000000006536c
Faulting process ID: 0x0x4618
Faulting application start time: 0x0x1d9810a58691d06
Faulting application path: C:\Users\Jesper\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: eba9e0db-4d1e-4e46-bcc6-f44b6b895f86
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 07/05/2023 20:36:18, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFBAEF6536C
Stack:
   at System.Environment._Exit(Int32)
   at System.Environment._Exit(Int32)
   at System.Environment.Exit(Int32)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   at OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double, Double)
   at Vintagestory.Client.ClientProgram.Start(Vintagestory.Client.ClientProgramArgs, System.String[])
   at Vintagestory.ClientNative.CrashReporter.Start(System.Threading.ThreadStart)
   at Vintagestory.Client.ClientProgram.Main(System.String[])
 }

[client-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/11415653/client-audit.txt)
[server-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/11415654/server-audit.txt)
[server-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/11415655/server-debug.txt)
[client-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/11415656/client-chat.txt)
[server-event.txt](https://github.com/anegostudios/VintageStory-Issues/files/11415657/server-event.txt)
[server-storyevent.txt](https://github.com/anegostudios/VintageStory-Issues/files/11415658/server-storyevent.txt)
[server-build.txt](https://github.com/anegostudios/VintageStory-Issues/files/11415659/server-build.txt)
[server-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/11415660/server-chat.txt)
[server-worldgen.txt](https://github.com/anegostudios/VintageStory-Issues/files/11415661/server-worldgen.txt)
[xlevelingdescription.txt](https://github.com/anegostudios/VintageStory-Issues/files/11415662/xlevelingdescription.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/11415663/client-crash.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11415664/client-main.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/11415665/client-debug.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11415666/server-main.txt)

**Comment by Craluminum2413** [comment]
[Duplicate](https://github.com/anegostudios/VintageStory-Issues/issues/2700#issuecomment-1537158145)
