### ISSUE TITLE
Game crash when interacting with traders

### ISSUE THREAD

**Issue by Zelger98** [anegostudios/VintageStory-Issues#2708]
### Game Version

v1.18.2-rc2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When trying to right click on a trader the game immediatly crashes. Started happening since 1.18.2-rc1.

### How to reproduce

Try to rightclick on any trader

### Logs

Running on 64 bit Windows with 8 GB RAM 
Game Version: v1.18.2-rc.2 (Unstable)
2023-05-07 21:58:14: Critical error occurred
Loaded Mods: game@1.18.2-rc.2, deathwaypoints@1.0.3, creative@1.18.2-rc.2, survival@1.18.2-rc.2
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.DlgTalkComponent.Execute() in VSSurvivalMod\Systems\Dialogue\Component\DlgTalkComponent.cs:line 17
   at Vintagestory.GameContent.DialogueController.ContinueExecute() in VSSurvivalMod\Systems\Dialogue\DialogueController.cs:line 92
   at Vintagestory.GameContent.EntityBehaviorConversable.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode, EnumHandling& handled) in VSSurvivalMod\Systems\Dialogue\BehaviorConversable.cs:line 249
   at Vintagestory.API.Common.EntityAgent.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 293
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 438
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 197
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 789
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 981
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 243
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 724
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2023-04-17 21:18:21, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.Client.GuiScreenGetUpdate.onReleasesDownloadComplete(System.Exception)
   at Vintagestory.Client.GuiScreenGetUpdate.<BeginDownload>b__6_0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 2023-04-17 08:17:50, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FF9549ACB69
Stack:
 }
--------------
{ TimeGenerated = 2023-03-16 19:22:44, Site = , Source = Application Error, Message = Sugadintos taikomosios programos pavadinimas: Vintagestory.exe, versija: 1.18.0.0, laiko žyma: 0x640994ff
Sugadinto modulio pavadinimas: KERNELBASE.dll, versija: 10.0.19041.2546, laiko žyma: 0xe8e9ac9b
Išimties kodas: 0xc0020001
Sugadintas poslinkis: 0x000000000002cd29
Sugadinto proceso ID: 0x26e0
Sugadintos taikomosios programos paleidimo laikas: 0x01d9581cafc710d7
Sugadintos taikomosios programos kelias: C:\Users\Rimaz\AppData\Roaming\Vintagestory\Vintagestory.exe
Sugadinto modulio kelias: C:\Windows\System32\KERNELBASE.dll
Ataskaitos ID: 57906a8f-703a-4807-b65e-41427dc23652
Sugadinto paketo visas pavadinimas: 
Su sugadintu paketu susijusios taikomosios programos ID:  }

**Comment by Craluminum2413** [comment]
[Duplicate](https://github.com/anegostudios/VintageStory-Issues/issues/2700#issuecomment-1537158145)

**Comment by radfast** [comment]
1.18.2-rc3 is now out, please try it.  Fixes the trader issues, hopefully no more issues.  :)
