### ISSUE TITLE
Game crashes when I try to talk to any trader

### ISSUE THREAD

**Issue by ZombeeWhisperer** [anegostudios/VintageStory-Issues#2709]
### Game Version

v1.18.2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Game crashes when I try to talk to any trader

### How to reproduce

Game crashes when I try to talk to any trader

### Logs

```Log```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.2-rc.2 (Unstable)
5/8/2023 1:07:57 AM: Critical error occurred
Loaded Mods: game@1.18.2-rc.2, creative@1.18.2-rc.2, survival@1.18.2-rc.2
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.DlgTalkComponent.Execute() in VSSurvivalMod\Systems\Dialogue\Component\DlgTalkComponent.cs:line 17
   at Vintagestory.GameContent.DialogueController.ContinueExecute() in VSSurvivalMod\Systems\Dialogue\DialogueController.cs:line 92
   at Vintagestory.GameContent.EntityBehaviorConversable.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode, EnumHandling& handled) in VSSurvivalMod\Systems\Dialogue\BehaviorConversable.cs:line 249
   at Vintagestory.API.Common.EntityAgent.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 293
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 438
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 197
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 789
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 981
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 243
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 724
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/4/2023 10:02:43 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2254817472815847875, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.2.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\J\AppData\Local\Temp\RDR3B38.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3B68.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3B79.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3BD4.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3C04.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 707e2f32-4a15-4de3-abcd-45089ef93a6a
Report Status: 268435456
Hashed bucket: f166d56c3c55a3da4f4ab88b848859c3
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
[Duplicate](https://github.com/anegostudios/VintageStory-Issues/issues/2700#issuecomment-1537158145)
