### ISSUE TITLE
Game Crash when Talking to a Trader. Game V 1.18.1

### ISSUE THREAD

**Issue by Bulwark77** [anegostudios/VintageStory-Issues#2711]
I have a different save and have same mods and have no issue with Traders. This save crashes. 
Just not going to talk to the Trader any longer until issue is resolved. It may be his trade craft maybe? I know some of the mods I am running are not updated to this version of the game. They don't seem to be causing any issues in the other save game I have.

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.1 (Stable)
5/8/2023 3:28:05 PM: Critical error occurred in the following mod: egocaribautomapmarkers@2.4.0-pre.1
Loaded Mods: angelbelt@1.4.0, backpackpackplus@1.0.3, bettercrates@1.6.0, BuggisRandomChanges@3.3.0, chiseltools@1.8.4, craftingtable@0.4.0, extrachests@1.7.0, FastPitkilns@1.0.0, FlexibleTools@2.1.0, HoneyPress@1.1.2, moreclassestweak@1.2.5, moredrygrass@0.2.0, moremolds@1.4.12, MoreTreeSeeds@1.0.0, natseasystonebricks@1.0.0, nightwatcher@1.4.0, nooffhandhunger@1.0.0, OresAPlenty@3.1.0, pondfrogsi@1.0.3, qptech@1.13.02, QuartzBlocks@1.1.0, RockBlocks@1.0.0, standardcrates@1.0.0, game@1.18.1, zoombuttonreborn@1.4.0, egocaribautomapmarkers@2.4.0-pre.1, betterbloomeriesreborn@1.0.4, carryon@1.0.0, hudclockuniversal@2.9.1, sailboat@1.1.0, petai@1.7.2, techmolds@1.0.0, creative@1.18.1, survival@1.18.1, em@2.1.0, feverstonehorses@1.5.0, simplewinddirection@1.0.2, bricklayers@2.0.0
Involved Harmony IDs: Egocarib.AutoMapMarkers.Patches
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.Pos'.
   at Egocarib.AutoMapMarkers.EntityBehavior.TraderMarkerBehavior.OnInteract(EntityAgent byEntity, ItemSlot itemslot, Vec3d hitPosition, EnumInteractMode mode, EnumHandling& handled)
   at Egocarib.AutoMapMarkers.Patches.EntityTrader.Base_OnInteract_Patch0(Object instance, EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode)
   at Egocarib.AutoMapMarkers.Patches.EntityTrader.Prefix(EntityTrader __instance, EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode) in C:\Users\justin\source\repos\VintageStory\vsmodtemplate-1.5.5\mods\egocaribautomapmarkers\src\Patches\EntityTrader.cs:line 25
   at Vintagestory.GameContent.EntityTrader.OnInteract_Patch1(EntityTrader this, EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 438
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 197
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 787
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 979
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 243
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 724
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/5/2023 7:30:27 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2088810280912897721, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.1.0
P3: 6443b447
P4: VSSurvivalMod
P5: 1.18.1.0
P6: 6443b446
P7: a7e
P8: 0
P9: System.NullReferenceException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3261.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER360B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER361C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER362A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3659.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_c316c9b538614c5eeef31bb37c8af7c04295ec8b_844f11b8_3d924adf-6bd3-4aeb-8c61-de048f4bae82

Analysis symbol: 
Rechecking for solution: 0
Report Id: 501eda11-df70-4381-85eb-4e523375de0c
Report Status: 268435456
Hashed bucket: 5cfcfe7dba6af578acfcf1e22cff46b9
Cab Guid: 0 }
--------------
{ TimeGenerated = 5/5/2023 7:30:26 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.1.0, time stamp: 0x6443b447
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ff937a5dfba
Faulting process id: 0x1a44
Faulting application start time: 0x01d97fb1d10f98e0
Faulting application path: C:\Users\jayat\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: unknown
Report Id: 501eda11-df70-4381-85eb-4e523375de0c
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 5/5/2023 7:30:25 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.GameContent.BlockLiquidContainerTopOpened.get_CapacityLitres()
   at Vintagestory.GameContent.BlockFruitPress+<>c__DisplayClass3_0.<OnLoaded>b__1()
   at Vintagestory.API.Util.ObjectCacheUtil.GetOrCreate[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Vintagestory.API.Common.ICoreAPI, System.String, Vintagestory.API.Util.CreateCachableObjectDelegate`1<System.__Canon>)
   at Vintagestory.GameContent.BlockFruitPress+<>c__DisplayClass3_0.<OnLoaded>b__0()
   at Vintagestory.Server.ServerMain.ProcessMainThreadTasks()
   at Vintagestory.Server.ServerMain.ProcessMain()
   at Vintagestory.Server.ServerMain.Stop(System.String)
   at Vintagestory.Client.ClientProgram.ServerThreadStart()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

 }

**Comment by Craluminum2413** [comment]
[Duplicate](https://github.com/anegostudios/VintageStory-Issues/issues/2700#issuecomment-1537158145)

**Comment by Craluminum2413** [comment]
[Duplicate](https://github.com/anegostudios/VintageStory-Issues/issues/2700#issuecomment-1537158145)

**Comment by radfast** [comment]
1.18.2-rc3 is now out, please try it.  Fixes the trader issues, hopefully no more issues.  :)

**Comment by Bulwark77** [comment]
I found an issue with the auto markers mod was causing the crash. I checked the version of the game when I was having the crash. The 1.18.2 version was still for testers. I will check again. Thanks for the tip radfast. ;)
