### ISSUE TITLE
1.18.2-rc.2 Crash when interacting with Traders

### ISSUE THREAD

**Issue by lyrah** [anegostudios/VintageStory-Issues#2712]
Anytime you talk to any type of trader, the game immediately crashes. This includes old traders and newly spawned traders. Problem persists with and without mods.

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.2-rc.2 (Unstable)
5/8/2023 6:25:21 PM: Critical error occurred
Loaded Mods: betterruins@0.1.0, game@1.18.2-rc.2, creative@1.18.2-rc.2, survival@1.18.2-rc.2
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.DlgTalkComponent.Execute() in VSSurvivalMod\Systems\Dialogue\Component\DlgTalkComponent.cs:line 17
   at Vintagestory.GameContent.DialogueController.ContinueExecute() in VSSurvivalMod\Systems\Dialogue\DialogueController.cs:line 92
   at Vintagestory.GameContent.EntityBehaviorConversable.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode, EnumHandling& handled) in VSSurvivalMod\Systems\Dialogue\BehaviorConversable.cs:line 249
   at Vintagestory.API.Common.EntityAgent.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 293
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 438
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 197
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 789
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 981
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 243
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 724
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/3/2023 8:56:49 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1248370421850872525, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.1.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\uxode\AppData\Local\Temp\RDR95C4.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER95D4.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER95D5.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER95F3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9613.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 72c4ca43-5ad0-4a4b-9043-672e5cd0132f
Report Status: 268435456
Hashed bucket: 14d5118b5bf73c7861531a48d6869acd
Cab Guid: 0 }
--------------
{ TimeGenerated = 4/10/2023 8:52:08 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1735025689157924198, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.0.0
P3: 642c31fe
P4: KERNELBASE.dll
P5: 10.0.19041.2728
P6: e7e53a4e
P7: c000041d
P8: 000000000002cd29
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER85D6.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_630edea9b50799c1b199b88f8a1aa39bcc3225c_749552bb_314d48ce-19a4-474e-b9a6-f4c759f42c93

Analysis symbol: 
Rechecking for solution: 0
Report Id: 36739ba1-fee9-47e4-be6d-0175fef5d56d
Report Status: 268435456
Hashed bucket: 84db1a2dbbdfcdfc58140cabf66f7566
Cab Guid: 0 }
--------------
{ TimeGenerated = 4/10/2023 8:52:04 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.0.0
P3: 642c31fe
P4: KERNELBASE.dll
P5: 10.0.19041.2728
P6: e7e53a4e
P7: c000041d
P8: 000000000002cd29
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_630edea9b50799c1b199b88f8a1aa39bcc3225c_749552bb_314d48ce-19a4-474e-b9a6-f4c759f42c93

Analysis symbol: 
Rechecking for solution: 0
Report Id: 36739ba1-fee9-47e4-be6d-0175fef5d56d
Report Status: 4
Hashed bucket: 
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
[Duplicate](https://github.com/anegostudios/VintageStory-Issues/issues/2700#issuecomment-1537158145)

**Comment by radfast** [comment]
1.18.2-rc3 is now out, please try it.  Fixes the trader issues, hopefully no more issues.  :)
