### ISSUE TITLE
Cannot hover Metal Parts from Broken tools in inventory, game crashes

### ISSUE THREAD

**Issue by malachi26** [anegostudios/VintageStory-Issues#2713]
### Game Version

1.18.1 (Stable

### Platform

None

### Modded

None

### SP/MP

None

### Description

Trying to hover over Tin Bronze Metal parts causes the game to crash

> Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.1 (Stable)
5/8/2023 8:20:08 PM: Critical error occurred in the following mod: metalrecovery@0.1.19-pre.0
Loaded Mods: hideandfabric@1.3.0, KreaturesAndKritters@1.0.0, primitivesurvival@3.1.7, game@1.18.1, animalcages@2.1.5, kreaturesandkritters@1.0.3, creative@1.18.1, survival@1.18.1, metalrecovery@0.1.19-pre.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at AnvilMetalRecovery.VariableMetalItem.RegenerateCombustablePropsFromStack(ItemStack contStack)
   at AnvilMetalRecovery.VariableMetalItem.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 401
   at Vintagestory.API.Client.GuiElementItemstackInfo.AsyncRecompose() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 126
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot, Boolean forceRecompose) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 252
   at Vintagestory.Client.NoObf.HudMouseTools.OnMouseEnterSlot(ItemSlot slot) in VintagestoryLib\Client\Systems\Gui\Huds\HudMouseTools.cs:line 216
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerOnMouseEnterSlot(ClientMain game, ItemSlot slot) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 510
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseMove(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 880
   at Vintagestory.API.Client.GuiComposer.OnMouseMove(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 495
   at Vintagestory.API.Client.GuiDialog.OnMouseMove(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 588
   at Vintagestory.Client.NoObf.GuiManager.OnMouseMove(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 440
   at Vintagestory.Client.NoObf.ClientMain.OnMouseMove(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1926
   at Vintagestory.Client.NoObf.ClientPlatformWindows.UpdateMousePosition() in VintagestoryLib\Client\ClientPlatform\Input.cs:line 148
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 109
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

### How to reproduce

Attempt to hover over Tin Bronze Metal Parts from Broken Tool in inventory, Inventory window is visible with Tin Bronze Metal scraps

### Screenshots

![image](https://user-images.githubusercontent.com/1625035/236971894-55417924-97d1-40b4-aed1-da717a3ab1ee.png)

### Logs

https://gist.github.com/malachi26/559fb8c804a68b1b167680630bea7907

**Comment by Craluminum2413** [comment]
Crash caused by Anvil Metal Recovery mod

**Comment by malachi26** [comment]
@Craluminum2413 sorry, I didn't realize this was only Vanilla.  thank you! Have an awesome day!
