### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by Razotar** [anegostudios/VintageStory-Issues#2758]
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.5 (Stable)
5/19/2023 2:10:47 PM: Critical error occurred
Loaded Mods: game@1.18.5, creative@1.18.5, survival@1.18.5
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AnimationUtil.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Common\Model\Animation\AnimationUtil.cs:line 108
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 199
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 787
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 871
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 711
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 681
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 625
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/17/2023 3:56:59 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1619560240869659823, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.3.0
P3: 645e772c
P4: clr.dll
P5: 4.8.9139.0
P6: 639963b4
P7: c0000005
P8: 000000000009a619
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.fb66ac84-a1d3-4a44-848a-f30e263e509c.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_6e6146517f4958cb2a948b11c76e7e3e401c8_64055eb0_ae332ea8-34f4-4cc5-af37-899d05113912

Analysis symbol: 
Rechecking for solution: 0
Report Id: b49a2e3d-99cc-47e2-a0d0-862b58b9a1ed
Report Status: 268435456
Hashed bucket: a8a41ebe445e5c084679d5755161d4af
Cab Guid: 0 }
--------------
{ TimeGenerated = 5/17/2023 3:56:57 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.3.0
P3: 645e772c
P4: clr.dll
P5: 4.8.9139.0
P6: 639963b4
P7: c0000005
P8: 000000000009a619
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_6e6146517f4958cb2a948b11c76e7e3e401c8_64055eb0_ae332ea8-34f4-4cc5-af37-899d05113912

Analysis symbol: 
Rechecking for solution: 0
Report Id: b49a2e3d-99cc-47e2-a0d0-862b58b9a1ed
Report Status: 4
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 5/17/2023 3:56:57 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.3.0, time stamp: 0x645e772c
Faulting module name: clr.dll, version: 4.8.9139.0, time stamp: 0x639963b4
Exception code: 0xc0000005
Fault offset: 0x000000000009a619
Faulting process id: 0x0x26f8
Faulting application start time: 0x0x1d9890203d3151d
Faulting application path: C:\Users\razot\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: b49a2e3d-99cc-47e2-a0d0-862b58b9a1ed
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by noelle-lavenza** [comment]
It looks like the game crashed while it was trying to render an animation. What were you doing when the crash occurred? Any enemies nearby? Temporal storm? Weird noises? Uploading your client-main and client-debug log files would help as well.

**Comment by Razotar** [comment]
Sorry it has taken a little while to get back to this. The game crashed when I opened a door. I don't think there were any other weird noises or nearby enemies. 

Here are the files requested below:

[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11568680/client-main.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/11568684/client-debug.txt)

**Comment by noelle-lavenza** [comment]
If it crashes again with the same error, please upload those two files again before restarting the game. Those logs you uploaded appear to be from a later play session and I can't see any obvious issues there that would have caused this crash. Thanks for the additional information, though! Seems likely to be an issue with door animations.

**Comment by Craluminum2413** [comment]
Closing due to inactivity
