### ISSUE TITLE
Crashes when we log onto server 

### ISSUE THREAD

**Issue by Ralo1969** [anegostudios/VintageStory-Issues#276]
Running on 64 bit Windows with 32 GB RAM 
Version: v1.9.2 (Stable)5/7/2019 3:37:48 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemOre.GetHeldItemName(ItemStack itemStack)
   at Vintagestory.Common.CreativeTab.CreateSearchCache(IWorldAccessor world)
   at Vintagestory.Common.CreativeTabs.CreateSearchCache(IWorldAccessor world)
   at _r6tvNwMB2X4idaSEIw8v6E9ZkVg._PlGhVmEAG9H7pZKPnmVZxSrPULi()
   at _4tEiYgqX9Tbp0u6XQgZRQN2C00j._PlGhVmEAG9H7pZKPnmVZxSrPULi()
   at _EFmd3P0Rx0MFcv1pj3dOv76GHriA._noHgQ4m6HvGIvbjmM5XhAR6FKmf(_b9SchT89xcOmE0zODRc77nUBb1n )
   at _4tEiYgqX9Tbp0u6XQgZRQN2C00j._Pfjw6a3qrLYw9JsiL9q7bkcU93e(Single )
   at _duZYLxim88ECcRVhD79dcjSPYM2._VX1QbjWJlmLJSVlUtjvd8V08RfE(Single )
   at _qMOZ0nqoV8D9qK6wSKJdms05DFe._OdjmEOIogayAlqcQz2BA7nx7rdy(Single )
   at _qMOZ0nqoV8D9qK6wSKJdms05DFe._DkcD3GjMcE3kO8Lf23ZEl9l0FvC(Single )
   at _Q4GkhL8fdNnbyajnFduEGWeDb1f._QoMfbzHHgFiFq1oQkgreZCSLDQX(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _i2ESdD37oIQUDTNBET1OO6KKA5P._sEL4TL65ecQmjpf9cyH76MTBAuO(_PeiLuq7npShFRqWQoaqgQ2aAB7L , String[] )
   at _xzOEtcS097gqlSlz75yjjYiA28I._sEL4TL65ecQmjpf9cyH76MTBAuO(ThreadStart )
-------------------------------

**Comment by tyronx** [comment]
thanks, should be fixed for the upcoming v1.9.3
