### ISSUE TITLE
Traders still bugged

### ISSUE THREAD

**Issue by Kelemvore** [anegostudios/VintageStory-Issues#2775]
### Game Version

1.18.5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

just trying to open the trader dialog menu and get crashing on almost every trader. 

### How to reproduce

find treasure trader or commodities trader,  right click to talk to them, game crashes

### Logs

```Log```Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.5 (Stable)
5/23/2023 3:55:43 PM: Critical error occurred in the following mod: egocaribautomapmarkers@2.4.0-pre.1
Loaded Mods: arachnidreplacer@1.0.0, autowalk@1.0.2, backpackpackplus@1.0.3, bettercrates@1.6.0, craftingtable@0.4.0, drdecor@1.2.0, extrachests@1.7.0, TA_fieldsandplateaus@1.0.1, HangingOilLamps@1.0.1, less-squeaky-chests@1.0.0, meteoricexpansion@1.2.4, panninshit@1.18.1, TA_plainsandvalleys@1.0.2, primitivesurvival@3.2.0, sortablestorage@1.8.0, sticksfromfirelogs@1.3.0, temperaturescales@1.0.2, vtpp@1.0.0, vgaas@1.0.1, game@1.18.5, worldgenfix@1.2.0, zoombuttonreborn@1.4.0, abcsreborn@0.0.5, ABCSReborn@0.0.2, egocaribautomapmarkers@2.4.0-pre.1, betterfirepit@1.1.0, bodyheatbar@1.0.0, carryon@1.2.0, commonlib@2.1.1, hudclock@3.0.1, naturalnight@1.0.0, prospectorinfo@4.3.0, roadworks@1.0.9, scarecrow@1.2.3, stonerailings@1.1.0, creative@1.18.5, survival@1.18.5, vsvillage@0.7.2, metalrecovery@0.1.19-pre.1, accessibilitytweaks@3.3.2, onebedsleeping@2.2.0, awearablelight@1.0.8, em@2.1.3, extraoverlays@1.3.1, playercorpse@1.7.1, xinvtweaks@1.5.3, bricklayers@2.1.0
Involved Harmony IDs: Egocarib.AutoMapMarkers.Patches
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.Pos'.
   at Egocarib.AutoMapMarkers.EntityBehavior.TraderMarkerBehavior.OnInteract(EntityAgent byEntity, ItemSlot itemslot, Vec3d hitPosition, EnumInteractMode mode, EnumHandling& handled)
   at Egocarib.AutoMapMarkers.Patches.EntityTrader.Base_OnInteract_Patch0(Object instance, EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode)
   at Egocarib.AutoMapMarkers.Patches.EntityTrader.Prefix(EntityTrader __instance, EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode) in C:\Users\justin\source\repos\VintageStory\vsmodtemplate-1.5.5\mods\egocaribautomapmarkers\src\Patches\EntityTrader.cs:line 25
   at Vintagestory.GameContent.EntityTrader.OnInteract_Patch1(EntityTrader this, EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 438
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 197
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 789
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 981
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 243
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 724
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/23/2023 3:34:21 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.18.5.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 }

**Comment by Craluminum2413** [comment]
Issues is in auto map markers mod
