### ISSUE TITLE
Kicked out to main menu, then crash creating a new world using "1 click install"

### ISSUE THREAD

**Issue by VoidsHeiress** [anegostudios/VintageStory-Issues#2789]
### Game Version

1.18.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Downloading a mod using the automatic download feature kicks you out to the menu, and seems to cause issues, like possibly not unloading the world you are actively in. 

This seems evident from the fact that the world you were just in remains inacessible from the main menu with the game stating it is possibly loaded elsewhere, and of course crashing on attempting to create another world.

I haven't explored the full possibility of interactions in this unintended state, but the steps provided will reliably create a crash.

While I do use mods almost all the time playing this game, I have disabled all of them while reproducing this crash.

### How to reproduce

1. Open a singleplayer world.
2. Go to the mod database, and pick out a mod to download.
3. Download that mod with the "1 click install" feature.
4. You will now get kicked out of your world into the mod install screen.
5. Press cancel to get booted to the main menu.
6. Create a new world and crash.

### Screenshots

![2469023589](https://github.com/anegostudios/VintageStory-Issues/assets/83094683/b4578e9a-9c0a-42d6-a4ad-93dbc517a350)

### Logs

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.5 (Stable)
31/05/2023 21:19:48: Critical error occurred
Loaded Mods: game@1.18.5, creative@1.18.5, survival@1.18.5
System.Exception: soundconfig.json not loaded. Is it missing or are you trying to load sounds before the client has received the level finalize event?
   at Vintagestory.Client.NoObf.ClientMain.ResolveSoundPath(AssetLocation location) in VintagestoryLib\Client\Systems\Audio\SoundEngine.cs:line 26
   at Vintagestory.Client.NoObf.ClientMain.LoadSound(SoundParams sound) in VintagestoryLib\Client\Systems\Audio\SoundEngine.cs:line 199
   at Vintagestory.API.Util.EntityTalkUtil..ctor(ICoreAPI api, Entity atEntity) in VintagestoryApi\Common\Entity\EntityTalkUtil.cs:line 98
   at Vintagestory.API.Common.EntityPlayer.Initialize(EntityProperties properties, ICoreAPI api, Int64 chunkindex3d) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 348
   at Vintagestory.Client.NoObf.ClientSystemEntities.entityFromPacket(Packet_Entity entitypacket, ClientMain game) in VintagestoryLib\Client\Systems\Entities.cs:line 542
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntitySpawnPacket(Packet_Server serverpacket) in VintagestoryLib\Client\Systems\Entities.cs:line 253
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 747
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 323
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 724
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 31/05/2023 21:19:49, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.5.0, time stamp: 0x64668a12
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18666, time stamp: 0x58f33794
Exception code: 0xc0020001
Fault offset: 0x00000000000095fc
Faulting process ID: 0xf60
Faulting application start time: 0x01d993f4ac83f622
Faulting application path: C:\Users\Admeme\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report ID: 1bb33b18-ffe8-11ed-829e-dcfe07e07a4a
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 31/05/2023 21:19:48, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFF6B6F95FC
Stack:
 }
--------------
{ TimeGenerated = 31/05/2023 21:15:45, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFF6B6F95FC
Stack:
 }
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/11618149/client-crash.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/11618151/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11618162/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11618164/server-main.txt)
[server-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/11618165/server-debug.txt)

**Comment by Craluminum2413** [comment]
Closing due to inactivity
