### ISSUE TITLE
Crash to Desktop

### ISSUE THREAD

**Issue by ZachBN** [anegostudios/VintageStory-Issues#2790]
### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Walking down road, game began to lag, then crashed.

### How to reproduce

Unsure.

### Logs

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.5 (Stable)
5/31/2023 2:48:26 PM: Critical error occurred
Loaded Mods: game@1.18.5, creative@1.18.5, survival@1.18.5
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityMycelium.setMushroomBlock(Block block) in VSSurvivalMod\BlockEntity\BEMycelium.cs:line 192
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 399
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 423
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 746
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 681
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 625
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/30/2023 3:46:53 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1246685165573697992, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.5.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\iwatc\AppData\Local\Temp\RDRCD8F.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCD9F.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCDB0.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCDBE.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCDDE.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 88a509c2-8d76-4115-ba9b-67e4fbe324bf
Report Status: 268435456
Hashed bucket: b0981a297909f6cdf14d1d8d88c4f1c8
Cab Guid: 0 }
--------------
{ TimeGenerated = 5/30/2023 3:41:26 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2067693443680614393, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 63501532
P4: KERNELBASE.dll
P5: 10.0.19041.2913
P6: a1c3e870
P7: c000041d
P8: 000000000002cf19
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCC9D.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCDC7.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCDD7.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCDD7.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCDF8.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_8645b8052a65d7ed24509ee0c6cd94e6c3be94_7fba9aec_7e44d6ab-5809-44b7-a11d-2ddc8dfacb6c

Analysis symbol: 
Rechecking for solution: 0
Report Id: 425bcc47-49f4-49ee-8995-8f0edce3738e
Report Status: 268435456
Hashed bucket: 4b77b9963ec84f0c2cb1ec3b5efcb7f9
Cab Guid: 0 }
--------------
{ TimeGenerated = 5/30/2023 3:41:25 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.9.0, time stamp: 0x63501532
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2913, time stamp: 0xa1c3e870
Exception code: 0xc000041d
Fault offset: 0x000000000002cf19
Faulting process id: 0x2c0c
Faulting application start time: 0x01d9933709e09df3
Faulting application path: C:\Users\iwatc\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 425bcc47-49f4-49ee-8995-8f0edce3738e
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by ZachBN** [comment]
> No response

Game Version is current new update.
