### ISSUE TITLE
Purchasing crock on Auction House causes CTD

### ISSUE THREAD

**Issue by Maldaris** [anegostudios/VintageStory-Issues#2796]
### Game Version

1.18.5

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

A player listed a crock on the AH for me to purchase. When I open the AH and press buy on the item, the client immediately CTDs with a NullReferenceException.

### How to reproduce

1. List a crock with food on the AH
2. On a second character, attempt to purchase the crock.

### Logs

```Log
Running on 64 bit Windows with 64 GB RAM 
Game Version: v1.18.5 (Stable)
6/3/2023 4:58:57 AM: Critical error occurred
Loaded Mods: cairns@1.0.0, chiseltools@1.8.4, capreolinae@1.0.1, hideandfabric@1.3.0, honeypressmittim@1.0.2, morenails@1.0.1, unochre@1.1.0, RangedWeapons@0.6.2, sticksfromfirelogs@1.3.0, ssppvv@1.0.5, viescraftmachines@2.2.1, game@1.18.5, zoombuttonreborn@1.4.0, alloycalculator@1.0.0, animalcages@2.1.5, blacksmithgloves@1.0.1, carryon@1.2.0, coinage@1.5.0, commonlib@2.1.1, cooperativecombat@1.0.0, fromgoldencombs@1.4.16-rc.2, grassiergrass@1.0.0, hudclock@2.9.1, sailboat@1.1.0, medievalexpansion@3.9.2, petai@1.7.8, claywheel@1.1.0, temporalprospector@1.0.1, creative@1.18.5, survival@1.18.5, wildfarmingrevival@1.0.5, xlib@0.7.1, metalrecovery@0.1.19-pre.1, barrelagedwood@1.0.0, chemistrylib@1.1.1, em@2.1.3, feverstonehorses@1.5.0, playercorpse@1.7.1, simplewinddirection@1.0.2, stonequarry@3.0.1, xskills@0.7.1, bricklayers@2.1.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockCrock.<>c__DisplayClass18_0.<GetHeldItemInfo>b__0(EnumTransitionType transType, ItemStack stack, Single mul) in VSSurvivalMod\Block\BlockCrock.cs:line 420
   at Vintagestory.API.Common.InventoryBase.GetTransitionSpeedMul(EnumTransitionType transType, ItemStack stack) in VintagestoryApi\Common\Inventory\InventoryBase.cs:line 798
   at Vintagestory.API.Common.CollectibleObject.GetTransitionRateMul(IWorldAccessor world, ItemSlot inSlot, EnumTransitionType transType) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2207
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2327
   at Vintagestory.API.Common.CollectibleObject.AppendPerishableInfoText(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1650
   at Vintagestory.GameContent.BlockCrock.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VSSurvivalMod\Block\BlockCrock.cs:line 0
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 401
   at Vintagestory.GameContent.GuiDialogConfirmPurchase.Init() in VSSurvivalMod\Systems\Auction\GuiDialogConfirmPurchase.cs:line 65
   at Vintagestory.GameContent.GuiDialogTrader.OnBuyAuctionClicked() in VSSurvivalMod\Gui\GuiDialogTrader.cs:line 279
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 304
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 675
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 290
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 564
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 416
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1867
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 229
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/2/2023 6:36:46 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1246685165573697992, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.5.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\robot\AppData\Local\Temp\RDRA35F.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA370.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA380.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA388.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA3A8.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: cd36a306-f18c-4d52-8d65-140780d46e70
Report Status: 268435456
Hashed bucket: b0981a297909f6cdf14d1d8d88c4f1c8
Cab Guid: 0 }
--------------
{ TimeGenerated = 5/29/2023 3:51:37 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFBB0ABCF19
Stack:
 }
--------------
{ TimeGenerated = 5/28/2023 8:00:53 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1948043743081104186, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.5.0
P3: 64668a12
P4: f49f
P5: 67246080
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC8FB.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\Critical_Vintagestory.exe_d14a20293f1efa1323998b3d768cb9f87cdec28_099fad0f_e14644c5-77e4-4776-b2fe-87a5ce16802e

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9f71b98e-ba13-492b-b6d4-625513e0d4d0
Report Status: 268435456
Hashed bucket: 6c1bd59a601f75859b08d7769145833a
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment]
What is AH?

**Comment by radfast** [comment]
Auction House I think - an auction run by a trader

**Comment by Maldaris** [comment]
Correct.

**Comment by Craluminum2413** [comment]
Closing due to inactivity
