### ISSUE TITLE
Crash on log in

### ISSUE THREAD

**Issue by MammaJamma88** [anegostudios/VintageStory-Issues#2820]
### Game Version

1.18.5

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Logged in, crashed

### Logs

Running on 64 bit Windows with 12 GB RAM 
Game Version: v1.18.5 (Stable)
6/14/2023 2:10:14 PM: Critical error occurred in the following mod: aculinaryartillery@1.0.12
Loaded Mods: acorns@0.5.1, aculinaryartillery@1.0.12, advancedsmithing@1.3.0, backpackpack@1.0.3, beekeeper@1.0.0, betterruins@0.2.0, cairns@1.0.0, chiseltools@1.8.4, coppercoldforging1@1.0.1, instruments@1.2.1, lumbersling@1.0.0, leadroof@1.3.2, MoreTorchHolders@1.0.0, moretreesmoreseeds@1.0.0, nightwatcher@1.4.0, NoMoreDrifterThrowing@1.0.0, ragnamans-seeds-from-crops-recipes@1.0.0, ruststones@1.0.4, tieredsoil@1.0.0, translocatorengineeringredux@1.4.2, usefuldrifterloot@1.0.3, game@1.18.5, wildcrafttrees@1.2.0, wildcraft@1.6.6, bonfires@0.2.1, butterfly@1.0.0, carryon@1.1.0, commonlib@2.1.1, expandedfoods@1.6.6, flintchisel@1.0.2, lessbears@1.0.0, morepiles@1.3.0, prospectorinfo@3.1.2, scarecrow@1.2.3, vanvar@3.1.1, creative@1.18.5, survival@1.18.5, wildfarmingrevival@1.0.6, xlib@0.7.2, barrelagedwood@1.0.0, em@2.2.1, tpnet@1.11.0-rc.1, xskills@0.7.3, bricklayers@2.2.0, wildcraftxskillspatch@0.2.0
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Cannot get item of id 270, item list count is only until 0!
   at Vintagestory.Client.NoObf.ClientMain.GetItem(Int32 itemId) in VintagestoryLib\Client\ClientMain.cs:line 2136
   at Vintagestory.API.Common.ItemStack..ctor(BinaryReader reader, IWorldAccessor resolver) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 187
   at Vintagestory.API.Common.CraftingRecipeIngredient.FromBytes(BinaryReader reader, IWorldAccessor resolver) in VintagestoryApi\Common\Crafting\CraftingRecipeIngredient.cs:line 270
   at ACulinaryArtillery.DoughIngredient.FromBytes(BinaryReader reader, IWorldAccessor resolver)
   at ACulinaryArtillery.DoughRecipe.FromBytes(BinaryReader reader, IWorldAccessor resolver)
   at ACulinaryArtillery.RecipeUploadSystem.OnServerMessage(RecipeUpload networkMessage)
   at Vintagestory.Client.NoObf.NetworkChannel.<>c__DisplayClass12_0`1.<SetMessageHandler>b__0(Packet_CustomPacket p) in VintagestoryLib\Client\API\NetworkChannel.cs:line 74
   at Vintagestory.Client.NoObf.NetworkAPI.HandleCustomPacket(Packet_Server packet) in VintagestoryLib\Client\API\NetworkAPI.cs:line 108
   at Vintagestory.Client.NoObf.NetworkAPI.HandleChannelsPacket(Packet_Server packet) in VintagestoryLib\Client\API\NetworkAPI.cs:line 87
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 747
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 323
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 724
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/13/2023 8:05:24 AM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.18.5.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 }
--------------
{ TimeGenerated = 6/11/2023 12:39:05 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.18.5.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 }
--------------
{ TimeGenerated = 5/20/2023 7:37:24 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1402421717052153672, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 10.0.22621.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\17073\AppData\Local\Temp\RDRB4A3.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8202a11d-aeff-499c-902c-673d0930e8e1.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.3857767d-794e-4449-ba66-24b1b6fd2b45.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b05fdaca-10bd-471d-8d9b-d06baf8958bd.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d6484fd7-e4ef-49e7-ba75-3c4654a72f70.tmp.xml

These files may be available here:
NULL

Analysis symbol: 
Rechecking for solution: 0
Report Id: c8ad9780-a851-4207-aeff-1fcc11305361
Report Status: 268435456
Hashed bucket: 84f56296e9742f3d9376671f0e2fdf48
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
Culinary mod is to blame
