### ISSUE TITLE
Constant Crashing / Freezing

### ISSUE THREAD

**Issue by adavis565** [anegostudios/VintageStory-Issues#2823]
Hello,
VS is crashing a lot on me. I am not sure if its a certain mod causing it or if there is another issue. I am not sure how to read the below. If its a mod, please let me know. 

Running on 64 bit Windows with 8 GB RAM 
Game Version: v1.18.5 (Stable)
6/16/2023 8:21:04 AM: Critical error occurred
Loaded Mods: detonateredux@1.0.3, furniturelibrary@1.0.9, hideandfabric@1.3.0, juicyores@1.0.0, medieval@2.01.17, moredrifterloot@1.5.4, primitivesurvival@3.2.0, sleevesdecor@1.0.2, game@1.18.5, carryon@1.2.0, hudclock@3.1.0, medievalexpansion@3.9.2, creative@1.18.5, survival@1.18.5
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityResonator.<>c__DisplayClass20_0.<onTrackLoaded>b__0() in VSSurvivalMod\BlockEntity\BEResonator.cs:line 162
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 746
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 681
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 625
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/17/2023 11:02:18 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangTransient
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.5.0
P3: 64668a12
P4: unknown
P5: unknown
P6: unknown
P7: unknown
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.5da6bade-9b1d-498c-8a25-5ae96fac2c28.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d32fe0da-d9b8-4556-9546-2ba22038bed4.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.1719c44f-5d2f-4025-b964-39c86a2cee20.tmp.txt

These files may be available here:
NULL

Analysis symbol: 
Rechecking for solution: 0
Report Id: 066e467f-feee-4cb0-af4c-b552a496c9aa
Report Status: 2049
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/17/2023 10:55:05 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangTransient
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.5.0
P3: 64668a12
P4: unknown
P5: unknown
P6: unknown
P7: unknown
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.24ebef1a-41fc-49cf-a1da-69752abe4e4c.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b334dcb3-3083-448e-9c01-c405daed64bd.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.93401188-af09-4760-94eb-c36f0f758dff.tmp.txt

These files may be available here:
NULL

Analysis symbol: 
Rechecking for solution: 0
Report Id: f1d27259-3c1f-43e7-afec-dc54c6d08c9f
Report Status: 2049
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/17/2023 10:47:14 AM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.18.5.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 }

**Comment by Craluminum2413** [comment]
Closing due to inactivity
