### ISSUE TITLE
Crashed when opening tutorial (Singleplayer)

### ISSUE THREAD

**Issue by sossololpipi** [anegostudios/VintageStory-Issues#2824]
### Game Version

v1.18.5 (Stable)

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

During a temporal storm and with the game unpaused, clicking the "First Steps" tutorial crashed my game. I was playing on a single-life Wilderness Survival world. I happened to be standing on the edge of a hay bed, if that has any effect.

### How to reproduce

1. be in a temporal storm
2. open the guidebook, and unpause the game while within
3. click the "first steps" tutorial

### Logs

```Log```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.5 (Stable)
6/17/2023 10:54:33 PM: Critical error occurred
Loaded Mods: game@1.18.5, creative@1.18.5, survival@1.18.5
System.InvalidOperationException: Stack empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Stack`1.Peek()
   at Vintagestory.GameContent.GuiDialogHandbook.ReloadPage() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 256
   at Vintagestory.GameContent.ModSystemTutorial.onStateUpdate(ActionBoolReturn`1 stepCall) in VSSurvivalMod\Systems\Handbook\Tutorial\ModSystemTutorial.cs:line 239
   at Vintagestory.Client.NoObf.InputAPI.TriggerInWorldAction(EnumEntityAction action, Boolean on, EnumHandling& handling) in VintagestoryLib\Client\API\InputAPI.cs:line 45
   at Vintagestory.API.Common.EntityControls.AttemptToggleAction(EnumEntityAction action, Boolean on) in VintagestoryApi\Common\Entity\EntityControls.cs:line 341
   at Vintagestory.API.Common.EntityPlayer.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 608
   at Vintagestory.Client.NoObf.ClientSystemEntities.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Entities.cs:line 96
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 85
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 813
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 712
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 165
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 683
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by sossololpipi** [comment]
Upon re-attempting this, the crash does not occur. I should note that this game was freshly updated a few hours prior.

**Comment by sossololpipi** [comment]
This has happened again, in the same situation, but at another temporal storm.

**Comment by korobya** [comment]
it seems to be fixed with https://github.com/anegostudios/vssurvivalmod/pull/27
