### ISSUE TITLE
Crash when CTRL-clicking item in creative

### ISSUE THREAD

**Issue by harofax** [anegostudios/VintageStory-Issues#2827]
### Game Version

v1.18.5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I switched to creative to grab some peridot cobblestone, and when I CTRL-click the peridot cobble, the game crashes and the Uh Oh! Crash! window pops up.

### How to reproduce

1. Start game, load into my save
2. Enter Creative
3. Search for Peridot
4. Mouse-over Peridot Cobblestone
5. CTRL-Click
6. CRASH

### Logs

Uh Oh! Crash! copy-to-clipboard logs:
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.5 (Stable)
18/06/2023 19:52:40: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.12, primitivesurvival@3.2.0, game@1.18.5, alchemy@1.6.11, betterfirepit@1.1.0, carryon@1.2.0, commonlib@2.1.1, expandedfoods@1.6.6, hudclock@3.2.0, medievalexpansion@3.9.3, prospectorinfo@4.3.0, creative@1.18.5, survival@1.18.5, playercorpse@1.7.1, xinvtweaks@1.5.4
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.InventoryPlayerCreative.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op) in VintagestoryLib\Common\GameContent\Inventory\InventoryPlayerCreative.cs:line 96
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 980
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 773
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 645
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs) in VintagestoryApi\Client\UI\GuiComposer.cs:line 460
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnMouseDown(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 551
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 394
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1834
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 219
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 792
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 14/06/2023 23:18:33, Site = , Source = Windows Error Reporting, Message = Fault bucket 1439906720436316324, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.5.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\harofax\AppData\Local\Temp\RDRB624.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB635.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB636.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB650.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB670.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 0592a46f-df23-4f3b-8411-4bb02600113f
Report Status: 268435456
Hashed bucket: 612b0510fcf7881ee3fb9388854de8a4
Cab Guid: 0 }
--------------
{ TimeGenerated = 15/05/2023 15:56:55, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.3.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\harofax\AppData\Local\Temp\RDRB8E7.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB907.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB908.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB925.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB945.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: e91cd42b-6dad-4032-a90d-4d9a42d53acb
Report Status: 536871008
Hashed bucket: 
Cab Guid: 0 }
```

And link to logs in VintageStoryData/Logs/:
https://gist.github.com/harofax/e5b849c6a0c3b9619c70c8470d67020f

**Comment by Craluminum2413** [comment]
Closing due to inactivity
