### ISSUE TITLE
Crashed when entering server

### ISSUE THREAD

**Issue by ThaumHunter** [anegostudios/VintageStory-Issues#2829]
### Game Version

v1.18.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Join server insta crash

### How to reproduce

I join the server and I crash

### Logs

```
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.5 (Stable)
6/18/2023 7:37:12 PM: Critical error occurred
Loaded Mods: game@1.18.5, creative@1.18.5, survival@1.18.5
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockWateringCan.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VSSurvivalMod\Block\BlockWateringCan.cs:line 319
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 403
   at Vintagestory.API.Client.GuiElementItemstackInfo.AsyncRecompose() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 126
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot, Boolean forceRecompose) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 252
   at Vintagestory.Client.NoObf.HudMouseTools.OnMouseEnterSlot(ItemSlot slot) in VintagestoryLib\Client\Systems\Gui\Huds\HudMouseTools.cs:line 217
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerOnMouseEnterSlot(ClientMain game, ItemSlot slot) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 510
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseMove(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 880
   at Vintagestory.API.Client.GuiComposer.OnMouseMove(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 495
   at Vintagestory.API.Client.GuiDialog.OnMouseMove(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 588
   at Vintagestory.Client.NoObf.GuiManager.OnMouseMove(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 440
   at Vintagestory.Client.NoObf.ClientMain.OnMouseMove(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1928
   at Vintagestory.Client.NoObf.ClientPlatformWindows.UpdateMousePosition() in VintagestoryLib\Client\ClientPlatform\Input.cs:line 148
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 109
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/18/2023 3:47:28 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1246685165573697992, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.5.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\schlo\AppData\Local\Temp\RDR3627.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3638.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3639.tmp.xml

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 90026410-8c64-4c4f-b766-70d4b9269e54
Report Status: 268435456
Hashed bucket: b0981a297909f6cdf14d1d8d88c4f1c8
Cab Guid: 0 }
--------------
{ TimeGenerated = 5/14/2023 12:36:24 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1651664509778262611, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.3.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\schlo\AppData\Local\Temp\RDR5D.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6D.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7E.tmp.xml

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: f7b094f4-35da-414e-8546-195703107fcd
Report Status: 268435456
Hashed bucket: e68624ee6927bee9e6ebe41ee973fa53
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment]
https://github.com/anegostudios/vssurvivalmod/pull/73
