### ISSUE TITLE
Game crash on server join

### ISSUE THREAD

**Issue by Pimpmaster007** [anegostudios/VintageStory-Issues#2832]
### Game Version

1.18.5 stable

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

when I join my locally hosted server it joins then instantly crashes

### How to reproduce

anytime I join my server

### Logs

```Log```
Running on 64 bit Windows with 64 GB RAM 
Game Version: v1.18.5 (Stable)
6/19/2023 7:31:21 AM: Critical error occurred
Loaded Mods: 
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Vintagestory.Client.NoObf.TextureAtlasManager.<>c__DisplayClass53_0.<runtimeUpdateTexture>b__1() in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 323
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 747
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 165
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 683
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/12/2023 5:29:18 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1246685165573697992, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.5.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Hotho\AppData\Local\Temp\RDRF35.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF36.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF47.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF22.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF42.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 28c7efc5-6079-4d72-87ed-7aea4a7807ce
Report Status: 268435456
Hashed bucket: b0981a297909f6cdf14d1d8d88c4f1c8
Cab Guid: 0 }

**Comment by Pimpmaster007** [comment]
I found what was causing the crash in case it helps anyone else i changed the server welcome message from null to welcome and it instantly fixed my crashing
