### ISSUE TITLE
Second crash in an hour.

### ISSUE THREAD

**Issue by Luxianos** [anegostudios/VintageStory-Issues#2836]
### Game Version

v1.18.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Not sure, first time a player was placing down coal and myself and another suddenly crashed. This time no-one was actively doing anything, I crashed but the other player did not.

### Logs

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.5 (Stable)
20/06/2023 9:38:26 PM: Critical error occurred
Loaded Mods: game@1.18.5, creative@1.18.5, survival@1.18.5
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityMycelium.setMushroomBlock(Block block) in VSSurvivalMod\BlockEntity\BEMycelium.cs:line 192
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 399
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 423
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 746
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 681
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 625
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 13/06/2023 9:21:41 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1813180379713846513, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.5.0
P3: 10.0.22621.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Luxianus\AppData\Local\Temp\RDR17BE.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f5ef9123-4d24-456d-a310-79f257f0d8e3.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.58338302-1afd-4aa2-9b06-26116573c160.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.46d652d8-c760-4d43-8037-26f99c8fe1ac.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a199626b-3709-42b1-b9da-250930aff53d.tmp.xml

These files may be available here:
NULL

Analysis symbol: 
Rechecking for solution: 0
Report Id: 3200a918-1418-4546-9f5a-d40e5d6db16e
Report Status: 268435456
Hashed bucket: ee80768c6970f7acd929b5f2de8d3cf1
Cab Guid: 0 }
[client-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/11799992/client-audit.txt)
[client-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/11799993/client-chat.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/11799994/client-crash.txt)
[client-debug.txt](https://github.com/an
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11799998/client-main.txt)
egostudios/VintageStory-Issues/files/11799995/client-debug.txt)

**Comment by Accellerant** [comment]
I myself and my partner experienced this issue as well on our server.

We crashed 3 times in less than an hour with the same error. I'll copy/paste the format Luxianos has above with our own situation.



> ### Game Version
> 
> v1.18.5
> ### Platform
> 
> Windows
> ### Modded
> 
> Modded
> ### SP/MP
> 
> Multiplayer
> ### Description
> 
> We crashed randomly while playing on the server. We were primarily doing what any VS player would be doing between the three crashes at our main home: eating, breaking blocks, going through doors, or hell just running around. The in game date was Early February and it's year 1. 
> ### How to reproduce
> 
> _No response_
> ### Screenshots
> 
> _No response_
> ### Logs
> 
> Game Version: v1.18.5 (Stable)
6/21/2023 12:39:03 AM: Critical error occurred
Loaded Mods: juicyores@1.0.0, game@1.18.5, animalcages@2.1.5, petai@1.7.9, claywheel@1.1.0, prospecttogether@1.0.0-rc.2, creative@1.18.5, survival@1.18.5, foxtaming@1.2.0, koboldplayermodel@1.0.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityMycelium.setMushroomBlock(Block block) in VSSurvivalMod\BlockEntity\BEMycelium.cs:line 192
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 399
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 423
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 746
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 681
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 625
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
Closing due to inactivity
