### ISSUE TITLE
1.18.6-rc.1 (Unstable) .NET7 has a Flint Shovel on Forest Floor = Crash from Critical Error bug

### ISSUE THREAD

**Issue by Diometus** [anegostudios/VintageStory-Issues#2846]
### Game Version

v.1.18.6-rc.1 (Unstable) .NET7 build

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

I used a Flint Shovel with 1/90 durability that I had created from Flint Shovel Head + Stick and was trying to clear Forest Floor with the flint shovel and game crashed. At first I thought it was due to Red Eagle Furn trying to be broken but this wasn't the case. This was on Rogue House server; however, it has bound to occur also on other servers too with same mod list.

### How to reproduce

1. Year 2 of October 7
2. Flint Shovel Head used on a stick to create a Flint Shovel
3. Make sure Flint Shovel is at 1/90 Durability
4. Use Flint Shovel on Forest Floor

### Logs

```Running on 64 bit Windows with 65442 MB RAM
Game Version: v1.18.6-rc.1 (Unstable)
6/27/2023 7:37:16 AM: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.12, ancienttools@1.5.5, autowalk@1.0.2, canmarket@0.2.7, chiseltools@1.8.4, emotemenu@1.0.4, instruments@1.2.1, mannequinstand@1.0.1, meteoricexpansion@1.2.4, leadroof@1.3.2, primitivesurvival@3.2.0, spyglass@0.4.5, tprunes@1.0.8, temperaturescales@1.0.2, temporalstormgear@1.0.1, game@1.18.6-rc.1, wildcraft@1.6.6, beehivekiln@1.2.2, bodyheatbar@1.0.1, calendar@1.0.0, carryon@1.2.0, commonlib@2.1.1, expandedfoods@1.6.6, fairplayguardian@1.1.2, hudclock@3.2.1, sailboat@1.1.0, naturalnight@1.0.0, petai@1.7.9, pixelwaypoints@1.0.0, claywheel@1.1.0, prospectorinfo@4.3.0, rhadditions@3.0.11, scarecrow@1.2.3, statushud@1.3.1, stonebakeoven@1.0.3, targetDotMedium@1.1.0, creative@1.18.6-rc.1, vsquest@0.4.1, survival@1.18.6-rc.1, xlib@0.7.2, bullseye@2.5.0-rc.1, cats@1.7.0, doffanddonagain@3.0.0, em@2.2.1, playercorpse@1.7.1, rifteye@0.2.3, simplewinddirection@1.0.2, stonequarry@3.0.1, wolftaming@1.7.3, xinvtweaks@1.5.3, xskills@0.7.3, bricklayers@2.2.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.ItemSlotCraftingOutput.triggerEvent(ItemStack craftedStack, Int32 moved, IPlayer actingPlayer)
   at Vintagestory.Common.ItemSlotCraftingOutput.TryPutInto(ItemSlot sinkSlot, ItemStackMoveOperation& op)
   at Vintagestory.API.Common.ItemSlot.TryPutInto(IWorldAccessor world, ItemSlot sinkSlot, Int32 quantity)
   at Vintagestory.API.Common.CollectibleObject.<>c__DisplayClass79_0.<RefillSlotIfEmpty>b__0(ItemSlot invslot)
   at Vintagestory.API.Common.EntityPlayer.WalkInventory(OnInventorySlot handler)
   at Vintagestory.API.Common.CollectibleObject.RefillSlotIfEmpty(ItemSlot slot, EntityAgent byEntity, ActionConsumable`1 matcher)
   at Vintagestory.API.Common.CollectibleObject.DamageItem_Patch1(CollectibleObject this, IWorldAccessor world, Entity byEntity, ItemSlot itemslot, Int32 amount)
   at Vintagestory.API.Common.CollectibleObject.OnBlockBrokenWith_Patch2(CollectibleObject this, IWorldAccessor world, Entity byEntity, ItemSlot itemslot, BlockSelection blockSel, Single dropQuantityMultiplier)
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryDestroyBlock(BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at Vintagestory.Client.ScreenManager.Render(Single dt)
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e)
   at OpenTK.Windowing.Desktop.GameWindow.DispatchRenderFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/27/2023 7:34:59 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1880357656339671929, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.6.0
P3: 638f99ee
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER636B.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_429d1884e4154ce84ac24791dbb411b784966a1e_a47ecedf_1a01e56a-00a4-4bcf-a718-cb16dcd6fb40

Analysis symbol: 
Rechecking for solution: 0
Report Id: 8e3cd2ee-4872-40c7-8f9e-cc25e89fd69b
Report Status: 268566528
Hashed bucket: 0e6a3f4f1527bf7a2a185f536ccfeb79
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/27/2023 7:34:58 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.6.0
P3: 638f99ee
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_429d1884e4154ce84ac24791dbb411b784966a1e_a47ecedf_1a01e56a-00a4-4bcf-a718-cb16dcd6fb40

Analysis symbol: 
Rechecking for solution: 0
Report Id: 8e3cd2ee-4872-40c7-8f9e-cc25e89fd69b
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/27/2023 7:34:56 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.6.0, time stamp: 0x638f99ee
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x2e90
Faulting application start time: 0x01d9a8f335311be6
Faulting application path: F:\Vintagestory\Vintagestory.exe
Faulting module path: F:\Vintagestory\Lib\openal32.dll
Report Id: 8e3cd2ee-4872-40c7-8f9e-cc25e89fd69b
Faulting package full name: 
Faulting package-relative application ID:  }```

**Comment by Th3Dilli** [comment]
I was not able to reproduce this with a 1/90 durability flint shovel on the forest floor

and looking at the log that should have been the same as #2741
