### ISSUE TITLE
Game crashes when left clicking on Stationary Basket

### ISSUE THREAD

**Issue by MrGREGhimself** [anegostudios/VintageStory-Issues#288]
When left clicking on the stationary basket (game:block-normal-generic-stationarybasket-east) game crashes. 
![Capture](https://user-images.githubusercontent.com/12535527/57574367-af9b8280-742f-11e9-90c0-cf5893c8e385.PNG)

Crash log below:

```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.9.3 (Stable)11/05/2019 20:45:01: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AssetLocation.ResolveToDomainAndPath(String domainAndPath, String& domain, String& path)
   at Vintagestory.GameContent.BlockGenericTypedContainer.GetDecal(IWorldAccessor world, BlockPos pos, ITexPositionSource decalTexSource, MeshData& decalModelData, MeshData& blockModelData)
   at _93mt80E27xA4nBcyBOSKfouBApi._fcm1KCYGtafeOnD8BUqJWXzT4tP(_enUkWr6bwaG5IEdylBh4g0qxFEo )
   at _93mt80E27xA4nBcyBOSKfouBApi._Kt41SknnZyWWczKnrL0cBDwosJm(BlockPos , Int32 )
   at _93mt80E27xA4nBcyBOSKfouBApi._VDJhK4246SBLP5nboq5GESmk8rf(_HyxARMaGJrpEjQejUfcoZ1FWdPs )
   at _GUwD6VYkgVQ73AlLfKTdTWGrvUH._Zt0sYm95TOFnQ7wgatkDU6xBG6z(_HyxARMaGJrpEjQejUfcoZ1FWdPs )
   at _xi7KDbdiMIrqJD7ntvragbgJs3u._RmhXCovMSwlTjt4wJvmDrcGhc8D(BlockSelection , Block , Single )
   at _xi7KDbdiMIrqJD7ntvragbgJs3u._WneujhymtJGtG6lxbHLkEkR3sLg(Single )
   at _xi7KDbdiMIrqJD7ntvragbgJs3u._4ghaIAKi7XxXq7aLGOlHreRuIec(Single )
   at _GUwD6VYkgVQ73AlLfKTdTWGrvUH._NqNCafwIuVnrN0APAIQT44l6CVR(EnumRenderStage , Single )
   at _PndAABz6mbLrIVY3bGkjFENAKYE._NqNCafwIuVnrN0APAIQT44l6CVR(EnumRenderStage , Single )
   at _PndAABz6mbLrIVY3bGkjFENAKYE._8Q0lcHKBmMsrZdVz5CTBHXVZQIW(Single )
   at _NkoWRZbO8vbo2P0bHOmeWW5HFZm._8Q0lcHKBmMsrZdVz5CTBHXVZQIW(Single )
   at _ClwmnLe1V7vR8n56XkbHz2NmshG._v6KGki9QaYXffAVL8MxroiYvLHZ(Single )
   at _ClwmnLe1V7vR8n56XkbHz2NmshG._bWLdqbxl84dj0WzW4hexmUSwPWP(Single )
   at _mEhEzZ8DmIQe7K9d4tBswO1fhgX._0oOO2PQajHpBpSzMJCyLMiw7tG(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _3vfvgrHj6ymQxm8FJtx4Ruzypih._Z3lNUjeecYm8PMLFsAqAg3ack5w(_mmIyrGEQIkHEG3raFL54FrKNncQ , String[] )
   at _VPmpDmTQc9Jyy6X2oS97VHCLE8A._Z3lNUjeecYm8PMLFsAqAg3ack5w(ThreadStart )
-------------------------------
****
```

**Comment by tyronx** [comment]
If you encounter this one again, can you please stand in the trader hut, type the command `/wgen pos structures` and send me the output please. That'll let me figure out which of the trader huts contains this broken chest.

**Comment by Craluminum2413** [comment]
Not the same crash, but.. I spawned small-5.json in the world, then opened stationary basket and got this crash:
**"assets\survival\worldgen\schematics\tradeoutposts\caravan-wagon\small-5.json"**
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.2 (Unstable)06/04/2021 23:28:28: Critical error occurred
System.Exception: Chunk retesselated listener number 0 threw an exception (a=False, b=False, b=False)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityAnimationUtil.<StartAnimation>b__16_0()
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerChunkRetesselated(Vec3i chunkPos, ClientChunk chunk)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerChunkRetesselated(Vec3i chunkPos, ClientChunk chunk)
   at Vintagestory.Client.NoObf.ChunkTesselatorManager.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _xArlFw5lpThzIY0BN36UerAlHzU._14ww1iwrPaPwPpAZqZCUdf3d4Sm(Single )
   at _uFwaliVbJcYmzlP3dwic7HSHMr2._EuQCmN4cQf8FBHYrlJxd8EhIdNnA(Single )
   at _uFwaliVbJcYmzlP3dwic7HSHMr2._HlDCi3DfsJHaHE4jniBarrjFlHLB(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _EKato5MKvGk9ELCMKyl4BGVO7pe._ninJWCWaWyMG9ZSA1Eyytms1G5F(_BjQ4x8rTRChySIeXrK1HK1YSqec , String[] )
   at _btwtpE4G1MfBqD34njKFCvBcSRd._ninJWCWaWyMG9ZSA1Eyytms1G5F(ThreadStart )
```

**Comment by copygirl** [comment]
@Craluminum2413 That's a different crash. Could you open a new issue for that?

**Comment by tyronx** [comment]
i think we can close this one, no new reports on this issue
