### ISSUE TITLE
Caught unhandled exception in thread 'tesselateterrain'.

### ISSUE THREAD

**Issue by Nicholuhhs** [anegostudios/VintageStory-Issues#2885]
### Game Version

v1.18.6

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Game keeps crashing saying, "Whoops, a client game thread crashed, please check the client-main.txt for more Information. I will now exit the game (and stop the server if in singleplayer.) Sorry about t hat :(". This a single player world this no mods and this just kinda happened randomly so idk.

### Logs

```Log```

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/2/2023 12:17:28 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2109719376181572131, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.6.0
P3: 649be5a4
P4: clr.dll
P5: 4.8.4644.0
P6: 64531a0f
P7: c0000005
P8: 00000000001d1bb7
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6B7A.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6F25.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6F35.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6F33.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6F63.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_8b702988ddd65de14c77b61f214e639bd946b5_9674cd4f_04780f0e-5c8f-4d4e-8636-7d4f36741c57

Analysis symbol: 
Rechecking for solution: 0
Report Id: 794c387f-0725-409a-bc71-453acbe390e1
Report Status: 268435456
Hashed bucket: 6777c3b52b1764318d473a98490fb223
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/2/2023 12:17:25 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.6.0, time stamp: 0x649be5a4
Faulting module name: clr.dll, version: 4.8.4644.0, time stamp: 0x64531a0f
Exception code: 0xc0000005
Fault offset: 0x00000000001d1bb7
Faulting process id: 0xbb0
Faulting application start time: 0x01d9ad0569c1f8c3
Faulting application path: C:\Users\User\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: 794c387f-0725-409a-bc71-453acbe390e1
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 7/2/2023 12:17:25 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FF8DEB01BB7 (00007FF8DE930000) with exit code 80131506.
 }

This was in the client-main.txt \/

[Fatal] Caught unhandled exception in thread 'tesselateterrain'. Exiting game.
4.7.2023 11:08:00 [Fatal] System.Exception: Exception thrown when trying to tesselate chunk 16004/5/15977. Details see inner exception. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.Common.BlockChunkDataLayer.getBlockGeneralCase(Int32 index3d) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\Model\BlockChunkDataLayer.cs:line 172
   at Vintagestory.Client.NoObf.ClientChunkData.GetRange_Faster(Block[] currentChunkBlocksExt, Block[] currentChunkFluidsExt, Int32[] currentChunkRgbsExt, Int32 extIndex3d, Int32 index3d, Int32 index3dEnd, Block[] blocksFast, LightUtil lightConverter) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Model\ClientChunkData.cs:line 178
   at Vintagestory.Client.NoObf.ChunkTesselator.BuildExtendedChunkData(ClientChunk curChunk, Int32 chunkX, Int32 chunkY, Int32 chunkZ, Boolean atMapEdge, Boolean skipChunkCenter) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Render\Tesselation\ChunkTesselator.cs:line 1095
   at Vintagestory.Client.NoObf.ChunkTesselator.BeginProcessChunk(Int32 chunkX, Int32 chunkY, Int32 chunkZ, ClientChunk chunk, Boolean skipChunkCenter) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Render\Tesselation\ChunkTesselator.cs:line 312
   --- End of inner exception stack trace ---

**Comment by Craluminum2413** [comment]
Closing due to inactivity
