### ISSUE TITLE
Game crash on start up

### ISSUE THREAD

**Issue by Alqueos** [anegostudios/VintageStory-Issues#2887]
### Game Version

1.18.6

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

Like title says booting up the game and it crashed a second after hitting run. No mods installed. Does this from fresh install.

Have tried a ton of problem solving and nothing changes. Keep getting same error.
-Multiple downloads and on different browsers
-Different versions of the game
-Disabling antivirus
-Running install and game as admin
-Window repair for possible corrupt files
-Reinstall the redist files

Running on 64 bit Windows with 32 GB RAM
Game Version: v1.18.5 (Stable)
6/9/2023 12:06:37 PM: Critical error occurred
Loaded Mods:
System.BadImageFormatException: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
at Vintagestory.API.Datastructures.JsonObject.FromJson(String jsonCode)
at Vintagestory.API.Config.Lang.PreLoad(ILogger logger, String assetsPath, String defaultLanguage) in VintagestoryApi\Localization\Lang.cs:line 99
at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

### How to reproduce

Run the exe file from folder or even on fresh install when finished(have the check box selected to run the game)

### Logs

```Log```
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/11951435/client-crash.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11951436/client-main.txt)

**Comment by Craluminum2413** [comment]
Have you tried 1.18.6?

**Comment by Alqueos** [comment]
> Have you tried 1.18.6?

Yes I have

**Comment by Craluminum2413** [comment]
Closing due to inactivity
