### ISSUE TITLE
Game crashes on joining game

### ISSUE THREAD

**Issue by Altaelor** [anegostudios/VintageStory-Issues#2889]
### Game Version

v1.18.6

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The game simply crashes whenever I try to join the server, both in SP and MP.

I am playing on the .net 7 Experimental build 1.18.6 version. My OS is Linux Mint, with .net7 installed as specified in the instructions. No mods installed.

### How to reproduce

1. Download the .net 7 Experimental build 1.18.6
2. Install the game
3. Launch it
4. Main menu runs fine
5. Game crashes on joining any game

### Logs

Running on 64 bit Linux with 15381 MB RAM
Game Version: .net7 Experimental build - v1.18.6 (Unstable)
7/5/2023 9:09:23 PM: Critical error occurred
Loaded Mods: game@1.18.6, creative@1.18.6, survival@1.18.6
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Vintagestory.Common.ArrayConvert.ByteToByte(Byte[] data, Int32 length) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Common\Convert\ArrayConvert.cs:line 73
   at Vintagestory.Common.CompressionZSTD.Decompress(Byte[] fi) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Common\Convert\Compression.cs:line 678
   at Vintagestory.Common.Compression.Decompress(Byte[] data) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Common\Convert\Compression.cs:line 113
   at Vintagestory.Common.BlockTypeNet.UnpackBlockPositions(Byte[] setBlocks) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Common\Network\BlockTypeNet.cs:line 899
   at Vintagestory.Client.NoObf.SystemHighlightBlocks.HandlePacket(Packet_Server packet) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\Systems\Render\HighlightBlocks.cs:line 300
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\Systems\NetworkProcess.cs:line 452
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\Systems\NetworkProcess.cs:line 446
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientMain.cs:line 712
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 73
   at OpenTK.Windowing.Desktop.GameWindow.DispatchRenderFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientProgram.cs:line 300
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientProgram.cs:line 127
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Altaelor** [comment]
The issue was fixed
