### ISSUE TITLE
Caught unhandled exception in thread 'tesselateterrain'. 

### ISSUE THREAD

**Issue by Nicholuhhs** [anegostudios/VintageStory-Issues#2895]
New vanilla world, error just happened randomly. As soon as I load up the world I get a pop up saying, "Whoops, a client game thread crashed, please check the client-main.txt for more information. I will now exit the game (and stop the server if in singleplayer). Sorry about that :(".
```
Going into client-main.txt I find this \/
7.7.2023 18:15:47 [Fatal] Caught unhandled exception in thread 'tesselateterrain'. Exiting game.
7.7.2023 18:15:47 [Fatal] System.Exception: Exception thrown when trying to tesselate chunk 16004/5/15977. Details see inner exception. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.Common.BlockChunkDataLayer.getBlockGeneralCase(Int32 index3d) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\Model\BlockChunkDataLayer.cs:line 172
   at Vintagestory.Client.NoObf.ClientChunkData.GetRange_Faster(Block[] currentChunkBlocksExt, Block[] currentChunkFluidsExt, Int32[] currentChunkRgbsExt, Int32 extIndex3d, Int32 index3d, Int32 index3dEnd, Block[] blocksFast, LightUtil lightConverter) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Model\ClientChunkData.cs:line 178
   at Vintagestory.Client.NoObf.ChunkTesselator.BuildExtendedChunkData(ClientChunk curChunk, Int32 chunkX, Int32 chunkY, Int32 chunkZ, Boolean atMapEdge, Boolean skipChunkCenter) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Render\Tesselation\ChunkTesselator.cs:line 1095
   at Vintagestory.Client.NoObf.ChunkTesselator.BeginProcessChunk(Int32 chunkX, Int32 chunkY, Int32 chunkZ, ClientChunk chunk, Boolean skipChunkCenter) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Render\Tesselation\ChunkTesselator.cs:line 312
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
