### ISSUE TITLE
Game Crash Log While Playing

### ISSUE THREAD

**Issue by mindshadow2k** [anegostudios/VintageStory-Issues#292]
Running on 64 bit Windows with 8 GB RAM 
Version: v1.9.3 (Stable)5/13/2019 7:30:52 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorHarvestable.onDropsModified()
   at Vintagestory.API.Datastructures.SyncedTreeAttribute.FromBytes(BinaryReader stream)
   at Vintagestory.API.Common.Entities.Entity.FromBytes(BinaryReader reader, Boolean fromServer)
   at Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   at _gbFD3yYlRfBk1tqchEM6hob48Vj._Q4PVdYGB2BKUNKxv2EfJkSoe1fc(_FAkyBp9dPDmLGm26jdRGgUK5LOh )
   at _gbFD3yYlRfBk1tqchEM6hob48Vj._zDgbRGBXt1aolWi3HMSqISPmoGD(_KYxNu4d2OW6yqTN3KdJcfo89cyI )
   at _PndAABz6mbLrIVY3bGkjFENAKYE._u2KBdQ1YadwFfy9QyaDloxApjuq(Single )
   at _NkoWRZbO8vbo2P0bHOmeWW5HFZm._VuoWA1NI32ePh577QetkPcWgv1j(Single )
   at _ClwmnLe1V7vR8n56XkbHz2NmshG._v6KGki9QaYXffAVL8MxroiYvLHZ(Single )
   at _ClwmnLe1V7vR8n56XkbHz2NmshG._bWLdqbxl84dj0WzW4hexmUSwPWP(Single )
   at _mEhEzZ8DmIQe7K9d4tBswO1fhgX._0oOO2PQajHpBpSzMJCyLMiw7tG(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _3vfvgrHj6ymQxm8FJtx4Ruzypih._Z3lNUjeecYm8PMLFsAqAg3ack5w(_mmIyrGEQIkHEG3raFL54FrKNncQ , String[] )
   at _VPmpDmTQc9Jyy6X2oS97VHCLE8A._Z3lNUjeecYm8PMLFsAqAg3ack5w(ThreadStart )
-------------------------------

**Comment by tyronx** [comment]
Thanks, should be fixed for v1.9.4
