### ISSUE TITLE
Crash on start up, Want to play help!! 

### ISSUE THREAD

**Issue by a5thOfa-changeling** [anegostudios/VintageStory-Issues#2921]
### Game Version

v1.18.6

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

When I try to open the game it crashes. Been doing so ever since, I had to Task manger close it Then restarted fine lagged and crash. Update: CAN NOT RUN OTHER GAME THEY ARE ALSO CRASHING!! WHAT THE CHUCK!?

### How to reproduce

I guess, task closed while your house is burring. log in pre-fire and then have it crashed, I dont mate. I Cranked up my View distance so to where it lagged and crash. usually  

### Logs

```Log```

Running on 64 bit Windows with 8 GB RAM 
Game Version: v1.18.6 (Stable)
2023-07-14 7:14:55 PM: Critical error occurred
Loaded Mods: 
System.NotSupportedException: Your graphics card does not support the extensions GL_ARB_framebuffer_object, GL_ARB_vertex_array_object, GL_ARB_draw_instanced, GL_ARB_explicit_attrib_location which is required to start the game
   at Vintagestory.Client.NoObf.ClientPlatformWindows.LogAndTestHardwareInfos() in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 202
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2023-07-14 6:45:38 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2259151214105495750, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.6.0
P3: 649be5a4
P4: KERNELBASE.dll
P5: 10.0.19041.3155
P6: bf300201
P7: c000041d
P8: 000000000002cf19
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER77E7.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_c8a35614dbce42b68c8b6992aaa1408515ab94d_9674cd4f_377c24c6-78ff-4a07-a614-4a70c084a027

Analysis symbol: 
Rechecking for solution: 0
Report Id: 159ea131-4ffc-4f6b-ab56-6e97bed7782b
Report Status: 268435456
Hashed bucket: d376a9af5bdd19ca0f5a1e0f4aa688c6
Cab Guid: 0 }
--------------
{ TimeGenerated = 2023-07-14 6:45:38 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1366889846499977137, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.6.0
P3: 649be5a4
P4: KERNELBASE.dll
P5: 10.0.19041.3155
P6: bf300201
P7: c0020001
P8: 000000000002cf19
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER76EC.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_891f3be0d4322a70a23397eecf674a86985fb2a_9674cd4f_76687439-1043-429b-9a35-90cc1e572f73

Analysis symbol: 
Rechecking for solution: 0
Report Id: 8ab97e74-f75b-4574-a013-7ec0bc26477f
Report Status: 268435456
Hashed bucket: 5b78820416cdd0d232f82b12c3b827b1
Cab Guid: 0 }
--------------
{ TimeGenerated = 2023-07-14 6:45:25 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.6.0
P3: 649be5a4
P4: KERNELBASE.dll
P5: 10.0.19041.3155
P6: bf300201
P7: c000041d
P8: 000000000002cf19
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_c8a35614dbce42b68c8b6992aaa1408515ab94d_9674cd4f_377c24c6-78ff-4a07-a614-4a70c084a027

Analysis symbol: 
Rechecking for solution: 0
Report Id: 159ea131-4ffc-4f6b-ab56-6e97bed7782b
Report Status: 4
Hashed bucket: 
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
Closing due to inactivity
