### ISSUE TITLE
Game crash during First Steps, making firestarter.  Crash log included. 

### ISSUE THREAD

**Issue by b12arr0** [anegostudios/VintageStory-Issues#2928]
### Game Version

1.18.6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Created a firestarter as part of First Steps and game crashed. 

### How to reproduce

1. Made Firestarter and then game crashed. Crash report below. 

### Logs

Running on 64 bit Windows with 64 GB RAM 
Game Version: v1.18.6 (Stable)
7/17/2023 11:37:30 PM: Critical error occurred
Loaded Mods: game@1.18.6, creative@1.18.6, survival@1.18.6
System.InvalidOperationException: Stack empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Stack`1.Peek()
   at Vintagestory.GameContent.GuiDialogHandbook.ReloadPage() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 256
   at Vintagestory.GameContent.ModSystemTutorial.onStateUpdate(ActionBoolReturn`1 stepCall) in VSSurvivalMod\Systems\Handbook\Tutorial\ModSystemTutorial.cs:line 239
   at Vintagestory.Client.NoObf.NetworkChannel.<>c__DisplayClass12_0`1.<SetMessageHandler>b__0(Packet_CustomPacket p) in VintagestoryLib\Client\API\NetworkChannel.cs:line 74
   at Vintagestory.Client.NoObf.NetworkAPI.HandleCustomPacket(Packet_Server packet) in VintagestoryLib\Client\API\NetworkAPI.cs:line 108
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 747
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 165
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 683
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/17/2023 11:18:12 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1773731324452487587, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.6.0
P3: 10.0.22621.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\b12ar\AppData\Local\Temp\RDR278B.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a0507df6-d594-45f2-8898-19f5196e4c87.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.41518c82-89bc-4286-99ce-216027c75f94.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.50b38be0-714e-432a-bbc6-2df4c106607b.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9f98ded7-682c-496c-8a4f-05a77d7d3574.tmp.xml

These files may be available here:
NULL

Analysis symbol: 
Rechecking for solution: 0
Report Id: afd8a6d6-b5eb-40e2-b84a-913a8dd402b6
Report Status: 268435456
Hashed bucket: 8a7eca116fb9fed0589d8f3df0f941a3
Cab Guid: 0 }

**Comment by korobya** [comment]
it seems to be fixed with https://github.com/anegostudios/vssurvivalmod/pull/27
