### ISSUE TITLE
Immediate crash when default audio output device is VoiceMeeter Input (Windows 10)

### ISSUE THREAD

**Issue by readcollin0** [anegostudios/VintageStory-Issues#2934]
### Game Version

v1.18.6

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

While using VoiceMeeter (Banana, in my case, haven't tested it with other versions), the game has a crash-to-desktop (no message) shortly after starting. It specifically occurs only when the VoiceMeeter Input is set as default. It usually crashes during the "Loading Shaders", but once got to what I think was "Validating with Server" (was supported by logs).

### How to reproduce

1. Install VoiceMeeter Banana (full setup, including restart).
2. Set the VoiceMeeter virtual input as the default audio output.
3. Launch Vintage Story, and witness crash.

Note: I haven't tested other versions of VoiceMeeter, but I believe they're pretty similar under-the-hood. I also haven't experimented much with the setup of VoiceMeeter.

### Logs

`client-main.txt`:
```19.7.2023 21:05:07 [Notification] Client logger started.
19.7.2023 21:05:07 [Notification] Game Version: v1.18.6 (Stable)
19.7.2023 21:05:07 [Notification] Screens:
19.7.2023 21:05:07 [Notification] 0: {X=0,Y=0,Width=2560,Height=1440}, \\.\DISPLAY1 (primary)
19.7.2023 21:05:07 [Notification] 1: {X=-1080,Y=-342,Width=1080,Height=1920}, \\.\DISPLAY2 
19.7.2023 21:05:07 [Notification] 2: {X=2560,Y=-334,Width=3072,Height=1728}, \\.\DISPLAY3 
19.7.2023 21:05:08 [Error] Failed creating audio context (OpenTK.Audio.AudioContextException: The audio context could not be created with the specified parameters.
   at OpenTK.Audio.AudioContext.CreateContext(String device, Int32 freq, Int32 refresh, Boolean sync, Int32 monoSources, Int32 stereoSources, Boolean enableEfx, MaxAuxiliarySends efxAuxiliarySends) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Audio\AudioContext.cs:line 350
   at OpenTK.Audio.AudioContext..ctor(String device) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Audio\AudioContext.cs:line 66
   at Vintagestory.Client.AudioOpenAl.initContext(ILogger logger, String desiredDevice) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\AudioOpenAl.cs:line 41) and oalinst.exe is missing, please download it at https://www.openal.org/downloads/ and put it alongside VintageStory.exe
19.7.2023 21:05:08 [Notification] CPU Cores: 24
19.7.2023 21:05:08 [Notification] Available RAM: 32768 MB
19.7.2023 21:05:08 [Notification] Graphics Card Vendor: NVIDIA Corporation
19.7.2023 21:05:08 [Notification] Graphics Card Version: 3.3.0 NVIDIA 527.56
19.7.2023 21:05:08 [Notification] Graphics Card Renderer: NVIDIA GeForce RTX 3070/PCIe/SSE2
19.7.2023 21:05:08 [Notification] Graphics Card ShadingLanguageVersion: 3.30 NVIDIA via Cg compiler
19.7.2023 21:05:08 [Notification] GL.MaxVertexUniformComponents: 4096
19.7.2023 21:05:08 [Notification] GL.MaxUniformBlockSize: 65536
19.7.2023 21:05:08 [Notification] Cairo Graphics Version: 1.17.3
19.7.2023 21:05:08 [Notification] OpenAL Version: 
19.7.2023 21:05:08 [Notification] C# Framework: .net Framework 4.0.30319.42000
19.7.2023 21:05:08 [Notification] OpenTK Version: 3.3.2 (A set of fast, low-level C# bindings for OpenGL, OpenGL ES and OpenAL.)
19.7.2023 21:05:08 [Notification] Start discovering assets
19.7.2023 21:05:08 [Notification] Found 22 base assets in category lang
19.7.2023 21:05:08 [Notification] Found 0 base assets in category patches
19.7.2023 21:05:08 [Notification] Found 22 base assets in category config
19.7.2023 21:05:08 [Notification] Found 0 base assets in category worldproperties
19.7.2023 21:05:08 [Notification] Found 46 base assets in category sounds
19.7.2023 21:05:08 [Notification] Found 97 base assets in category shapes
19.7.2023 21:05:08 [Notification] Found 72 base assets in category shaders
19.7.2023 21:05:08 [Notification] Found 16 base assets in category shaderincludes
19.7.2023 21:05:08 [Notification] Found 131 base assets in category textures
19.7.2023 21:05:08 [Notification] Found 4 base assets in category music
19.7.2023 21:05:08 [Notification] Found 0 base assets in category dialog
19.7.2023 21:05:08 [Notification] Found 410 base assets in total
19.7.2023 21:05:08 [Notification] Loading sounds
19.7.2023 21:05:08 [Notification] Sounds loaded
19.7.2023 21:05:08 [Notification] (Re-)loaded frame buffers
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass .
19.7.2023 21:05:08 [Notification] Window was resized to 2560 1377, rebuilding framebuffers...
19.7.2023 21:05:08 [Notification] (Re-)loaded frame buffers
19.7.2023 21:05:08 [Notification] Begin loading shaders
19.7.2023 21:05:08 [Notification] Load shaders now
19.7.2023 21:05:08 [Notification] Loading shaders...
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass standard.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass particlescube.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass particlesquad.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass sky.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass nightsky.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass woittest.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass helditem.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass decals.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass final.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass gui.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass blur.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass findbright.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass godrays.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass autocamera.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass wireframe.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass entityanimated.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass luma.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass blit.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass texture2texture.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass celestialobject.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass colorgrade.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass guigear.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass ssao.
19.7.2023 21:05:08 [Notification] Loaded Shaderprogramm for render pass bilateralblur.```
Note: once had a line about validating with server at the end.

`client-debug.txt`:
```19.7.2023 21:05:07 [Debug] Creating game window with window mode Maximized
19.7.2023 21:05:08.232 [VerboseDebug] Loadsounds, found 46 sounds```

**Comment by readcollin0** [comment]
I have just found out that this issue also applies when using the VB-Audio Virtual Cable device as well. It is made by the same people as VoiceMeeter.

For the record, I also have not had any other issues with software crashing while using VoiceMeeter.
