### ISSUE TITLE
Large Trough disappears when placed. Subsequent Large Trough placement glitches, then causes crash

### ISSUE THREAD

**Issue by tehflambo** [anegostudios/VintageStory-Issues#2938]
### Game Version

1.18.6

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Sequence of events prior to crash:
1. I had been placing large troughs on natural terrain.
2. One particular trough disappeared when placed
- was placed atop harvestable grass, which itself was atop grassy, medium fertility soil
- harvestable grass was removed by placing the trough
3. I mined one soil block, directly under 1 of the 2 blocks where this (disappeared) large trough was expected to be
- I had hoped perhaps this would trigger the (disappeared) large trough to drop
- it did not
4. I replaced the soil block to its original location
5. I attempted to place another Large Trough in the same location as the disappeared one
6. glitched "half trough" appears
- of the two soil blocks atop which the trough *should* have appeared, this "half trough" appeared above the soil block I *had not* already removed and replaced
- the "half trough" was facing the wrong direction... probably north?
7. half a second passes, screen goes black, another second passes, crash log appears
8. and here we are!

### How to reproduce

I really don't know, but here's my guess:
1. try to place a large trough atop a grass plant
2. if the large trough disappears, try repeating steps 3-6 from "Description" field, above.

### Screenshots

Alas, no. I was not recording at the time.

### Logs

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.6 (Stable)
7/20/2023 12:48:47 PM: Critical error occurred
Loaded Mods: game@1.18.6, creative@1.18.6, survival@1.18.6
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Vintagestory.GameContent.BlockEntityTrough.get_contentConfigs() in VSSurvivalMod\BlockEntity\BETrough.cs:line 70
   at Vintagestory.GameContent.BlockEntityTrough.get_IsFull() in VSSurvivalMod\BlockEntity\BETrough.cs:line 77
   at Vintagestory.GameContent.BlockTroughBase.<init>b__3_3(WorldInteraction wi, BlockSelection bs, EntitySelection es) in VSSurvivalMod\Block\BlockTrough.cs:line 71
   at Vintagestory.Client.NoObf.DrawWorldInteractionUtil.ComposeBlockWorldInteractionHelp(WorldInteraction[] wis) in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockInteractionHelp.cs:line 72
   at Vintagestory.Client.NoObf.HudElementBlockInteractionHelp.BlockInView() in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockInteractionHelp.cs:line 355
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 85
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 813
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 712
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 165
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 683
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/20/2023 12:48:47 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFF71B4CF19
Stack:
 }
--------------
{ TimeGenerated = 7/15/2023 6:48:55 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1691657990988444316, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.6.0
P3: 649be5a4
P4: nvoglv64.dll
P5: 31.0.15.3179
P6: 64480cf6
P7: c0000005
P8: 0000000000ee7f84
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7875.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7A1C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7A2C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7A2A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7A3B.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_61e3c6292026d7b63f6158baf30ecbedff4f434_9674cd4f_aa33a767-6565-490d-b809-1ca6c9a85da8

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9d307677-0245-47fe-9e04-c62a8afb1cf9
Report Status: 268435456
Hashed bucket: f832d53a3f9162a7d779f9fae251329c
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/15/2023 6:48:54 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.6.0, time stamp: 0x649be5a4
Faulting module name: nvoglv64.dll, version: 31.0.15.3179, time stamp: 0x64480cf6
Exception code: 0xc0000005
Fault offset: 0x0000000000ee7f84
Faulting process id: 0x4b58
Faulting application start time: 0x01d9b709e52a2129
Faulting application path: C:\Users\Flambo\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_19f3764f95906f94\nvoglv64.dll
Report Id: 9d307677-0245-47fe-9e04-c62a8afb1cf9
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Closing due to inactivity
