### ISSUE TITLE
Framerate Drops and Crashes

### ISSUE THREAD

**Issue by DarkDragon1254** [anegostudios/VintageStory-Issues#2948]
### Game Version

v1.18.6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

So I have a problem of framerates falling all the way down to 1 FPS sometimes and my single player server seems to have client crashes every couple minutes and usually in large batches before letting me continue what I was doing. I tried to change the graphics to a lower setting but it kept happening.

### How to reproduce

I don't know what the problem is, I'll just be playing for a bit and then all the problems begin to appear.

### Logs

Running on 64 bit Windows with 8 GB RAM 
Game Version: v1.18.6 (Stable)
7/23/2023 7:09:34 PM: Critical error occurred
Loaded Mods: 
System.Exception: Coding error: Mods must not get assets before AssetsLoaded stage - do not load assets in a Start() method!
   at Vintagestory.Client.NoObf.TextureAtlasManager.LoadBitmap(ClientMain game, AssetLocationAndSource textureLoc) in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 836
   at Vintagestory.Client.NoObf.TextureAtlasManager.LoadCompositeBitmap_NoOverlayDispose(ClientMain game, AssetLocationAndSource compositeTextureLocation) in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 753
   at Vintagestory.Client.NoObf.TextureAtlasManager.LoadBitmaps(BakedBitmap[] bitmaps) in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 449
   at Vintagestory.API.Util.AsyncHelper.Multithreaded.OnWorkerThread(Action task) in VintagestoryApi\Util\AsyncHelper.cs:line 52
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/23/2023 7:09:50 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.6.0, time stamp: 0x649be5a4
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1928, time stamp: 0xe9af6ed4
Exception code: 0xc0020001
Fault offset: 0x0000000000064b2c
Faulting process id: 0x0x2410
Faulting application start time: 0x0x1d9bdc1c7a1028d
Faulting application path: C:\Users\judah\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 2cc0c2c1-bd94-4536-abb3-5b577b21ea2e
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 7/23/2023 7:09:41 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFC718A4B2C
Stack:
   at System.Environment._Exit(Int32)
   at System.Environment._Exit(Int32)
   at System.Environment.Exit(Int32)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double, Double)
   at Vintagestory.Client.ClientProgram.Start(Vintagestory.Client.ClientProgramArgs, System.String[])
   at Vintagestory.ClientNative.CrashReporter.Start(System.Threading.ThreadStart)
   at Vintagestory.Client.ClientProgram.Main(System.String[])
 }
--------------
{ TimeGenerated = 7/21/2023 7:36:11 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.6.0
P3: 649be5a4
P4: 4699
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c18f60d7-d445-4490-879b-b33c884f3668.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f7684c48-4fc7-4520-a906-669670a9f5d7.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4defc9ef-d660-483a-85f9-e64d689ea2f1.tmp.txt
\\?\C:\Users\judah\AppData\Local\Temp\WER.6d1ba162-3b8c-4626-b262-badd557b7d65.tmp.appcompat.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e338ae2e-2317-46d6-a914-0d4f65d941e6.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_6d151223942da2f9f2856b1868fa9c485851ca68_9674cd4f_4bc02f8a-9f2f-4638-a090-8d4b1ed903d2

Analysis symbol: 
Rechecking for solution: 0
Report Id: 025d7861-59c7-4e48-85e1-a1ae7ea64685
Report Status: 97
Hashed bucket: 
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
Closing due to inactivity
