### ISSUE TITLE
graphics card not responding

### ISSUE THREAD

**Issue by slarzyer** [anegostudios/VintageStory-Issues#2962]
### Platform

None

### Modded

None

### SP/MP

None

### Description

not really sure this is a bug with the game... but its more a bug on my computer or with my graphics card... i was playing the game just fine and crashed... after rebooting i keep getting this error

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.4 (Stable)
7/27/2023 6:40:29 PM: Critical error occurred
Loaded Mods: 
System.NotSupportedException: Your graphics card does not support the extensions GL_ARB_framebuffer_object, GL_ARB_vertex_array_object, GL_ARB_draw_instanced, GL_ARB_explicit_attrib_location which is required to start the game
   at Vintagestory.Client.NoObf.ClientPlatformWindows.LogAndTestHardwareInfos() in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 202
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/13/2023 4:09:26 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1246685165573697992, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.5.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\no\AppData\Local\Temp\RDR5A68.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5A88.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5A99.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5AD6.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5B15.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 28968e11-5ba2-4a20-be6b-353f7b594d41
Report Status: 268435456
Hashed bucket: b0981a297909f6cdf14d1d8d88c4f1c8
Cab Guid: 0 }

can i fix this?

### Logs

```Log```

**Comment by kurazarrh** [comment]
Since you were previously able to play the game, it sounds like your graphics card driver may have become corrupted. Have you tried uninstalling the driver (preferably using DDU/Display Driver Uninstaller) and then reinstalling with the latest installer package?

**Comment by slarzyer** [comment]
issue was fixed from display montior driver replacement(reinstalled previous version)... windows auto updates keep screwing with my drivers

**Comment by Craluminum2413** [comment]
Closing due to inactivity
