### ISSUE TITLE
Crash loading all single player instances

### ISSUE THREAD

**Issue by Deathsblow316** [anegostudios/VintageStory-Issues#2967]
### Game Version

v1.18.7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I was using mods at first but turned them off to verify they were not causing the issue.  I can log on to my multiplayer server with no issues seams to only effect the single player side and is not effected by the game mode selected.  I closed everything down and restarted my computer, same issue.

### How to reproduce

Unknown

### Screenshots

![Screenshot 2023-07-29 093145](https://github.com/anegostudios/VintageStory-Issues/assets/140898164/67a6b75d-a996-4edc-b937-7b8ed458b291)

### Logs

```Log```Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.7 (Stable)
7/29/2023 9:18:10 AM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ClientMain.cs:line 727
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 302
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ScreenManager.cs:line 722
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ScreenManager.cs:line 625
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/18/2023 8:52:11 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1333656502140834437, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.6.0
P3: 649be5a4
P4: nvoglv64.dll
P5: 31.0.15.3598
P6: 646dfba9
P7: c0000005
P8: 0000000000f003b4
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f8226c18-c7fa-46aa-a748-6142bbafe101.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.605a32c1-2c54-4f42-aee2-1dc77f76d9d4.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0f703b92-028f-424e-a4d2-98ea823fb43b.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.fe6ee977-fd32-4c48-8bf6-125f0cef8e3b.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.db59a9af-49ee-42ed-a760-cb201420e676.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_5d78ef3592e63f1c873ef3c3c508632c0f40a_9674cd4f_0c155e67-eb1c-4c32-a97f-99d8b2ff08ea

Analysis symbol: 
Rechecking for solution: 0
Report Id: da2ccdc2-9586-4fcb-a89e-6b8c6b47d81d
Report Status: 268435456
Hashed bucket: 8d860ccf3fb4e20632821985ce7e9285
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/18/2023 8:52:10 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.6.0, time stamp: 0x649be5a4
Faulting module name: nvoglv64.dll, version: 31.0.15.3598, time stamp: 0x646dfba9
Exception code: 0xc0000005
Fault offset: 0x0000000000f003b4
Faulting process id: 0x0x66b4
Faulting application start time: 0x0x1d9b9bdaf5dc529
Faulting application path: C:\Users\John Jacobsen\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\nvmisi.inf_amd64_e11caa7a98a62a03\nvoglv64.dll
Report Id: da2ccdc2-9586-4fcb-a89e-6b8c6b47d81d
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 7/18/2023 8:52:09 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Graphics.OpenGL.GL.EnableVertexAttribArray(Int32)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.RenderMeshInstanced(Vintagestory.API.Client.MeshRef, Int32)
   at Vintagestory.Client.ParticleRenderer2D.Render(Single)
   at Vintagestory.Client.GuiCompositeMainMenuLeft.Render(Single, Int64, Boolean, Boolean)
   at Vintagestory.Client.GuiCompositeMainMenuLeft.RenderBg(Single, Boolean)
   at Vintagestory.Client.ScreenManager.Render(Single)
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at Vintagestory.Client.ClientProgram.Start(Vintagestory.Client.ClientProgramArgs, System.String[])
   at Vintagestory.ClientNative.CrashReporter.Start(System.Threading.ThreadStart)
   at Vintagestory.Client.ClientProgram.Main(System.String[])

 }

**Comment by Craluminum2413** [comment]
Could you send all logs from `\AppData\Roaming\VintagestoryData\Logs`?

**Comment by Deathsblow316** [comment]
[server-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/12208381/server-audit.txt)
[server-build.txt](https://github.com/anegostudios/VintageStory-Issues/files/12208382/server-build.txt)
[server-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/12208383/server-chat.txt)
[server-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/12208384/server-debug.txt)
[server-event.txt](https://github.com/anegostudios/VintageStory-Issues/files/12208385/server-event.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/12208386/server-main.txt)
[server-storyevent.txt](https://github.com/anegostudios/VintageStory-Issues/files/12208387/server-storyevent.txt)
[server-worldgen.txt](https://github.com/anegostudios/VintageStory-Issues/files/12208388/server-worldgen.txt)
[client-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/12208389/client-audit.txt)
[client-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/12208390/client-chat.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/12208391/client-crash.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/12208392/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/12208393/client-main.txt)

**Comment by Craluminum2413** [comment]
You are using too much mods, try to disable them and try again

**Comment by Deathsblow316** [comment]
I did that as well still nothing

**Comment by Deathsblow316** [comment]
[client-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/12209113/client-audit.txt)
[client-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/12209114/client-chat.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/12209115/client-crash.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/12209116/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/12209117/client-main.txt)
[server-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/12209118/server-audit.txt)
[server-build.txt](https://github.com/anegostudios/VintageStory-Issues/files/12209119/server-build.txt)
[server-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/12209120/server-chat.txt)
[server-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/12209121/server-debug.txt)
[server-event.txt](https://github.com/anegostudios/VintageStory-Issues/files/12209122/server-event.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/12209123/server-main.txt)
[server-storyevent.txt](https://github.com/anegostudios/VintageStory-Issues/files/12209124/server-storyevent.txt)
[server-worldgen.txt](https://github.com/anegostudios/VintageStory-Issues/files/12209125/server-worldgen.txt)

**Comment by Deathsblow316** [comment]
I am still unable to create or log into a single player world with the mods off or on.  Any input would be greatly appreciated.

**Comment by Craluminum2413** [comment]
Closing due to inactivity
