### ISSUE TITLE
Assembly with same name is already loaded

### ISSUE THREAD

**Issue by mard** [anegostudios/VintageStory-Issues#2975]
### Game Version

v1.18.6-rc.1

### Platform

Linux

### Modded

Modded

### SP/MP

Multiplayer

### Description

The game will crash upon joining the modded multiplayer server, if user previously played on some other server containing the same mod in different version, with the following message: `System.IO.FileLoadException: Assembly with same name is already loaded`.

Running on 64 bit Linux with 15887 MB RAM
Game Version: .net7 Experimental build - v1.18.6 (Unstable)

### How to reproduce

1. Host two game servers containing the same mod (possibly in different versions)
2. Join the first server, exit the server, but don't exit the game.
3. Join the second server. The game should crash

### Workaround

Exit the game and rejoin the server.

### Logs

```
1.8.2023 14:54:09 [Notification] Connecting to [Server #1]...
...
Checking carryon@1.3.0... found! Downloading...<font color="#80ff80">success</font>! 188 kb downloaded. Mod installed.
...
1.8.2023 14:54:21 [Notification] Connecting to [Server #1]...
...
1.8.2023 14:54:24 [Notification] Found 23 mods (1 disabled)
1.8.2023 14:54:24 [Notification] Mods, sorted by dependency: chiseltools, hqzlights, foundrymod, mannequinstand, leadroof, game, zumdorfkrug, canmarket, carryon, fishing, sailboat, medievalexpansion, paxel, scarecrow, creative, survival, workbenchexpansion, xlib, em, rifteye, xskills, bricklayers
1.8.2023 14:54:24 [Notification] Instantiated 117 mod systems from 22 enabled mods
1.8.2023 14:54:24 [Event] started 'CarryOn' mod
...
1.8.2023 14:54:46 [Notification] Exiting current game to main menu, reason: leave world button pressed
...
1.8.2023 14:54:57 [Notification] Connecting to [Server #2]...
...
Checking carryon@1.0.0... found! Downloading...<font color="#80ff80">success</font>! 187 kb downloaded. Mod installed.
...
1.8.2023 14:55:14 [Notification] Connecting to [Server #2]...
...
1.8.2023 14:55:17 [Notification] Found 30 mods (1 disabled)
1.8.2023 14:55:17 [Notification] Mods, sorted by dependency: bedrespawner, betterruins, chiseltools, hqzlights, fieldsofgold, capreolinae, pantherinae, indappledgroves, instruments, moreminerals, game, wildcrafttrees, animalcages, beehivekiln, carryon, commonlib, fromgoldencombs, sailboat, morepiles, petai, stonebakeoven, tablet, creative, survival, em, playercorpse, stonequarry, wolftaming, bricklayers
1.8.2023 14:55:19 [Error] [carryon] An exception was thrown when trying to load assembly:
System.IO.FileLoadException: Assembly with same name is already loaded
   at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr ptrNativeAssemblyBinder, UInt16* ilPath, UInt16* niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Vintagestory.Common.ModAssemblyLoader.LoadFrom(String path) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Common\API\ModAssemblyLoader.cs:line 34
   at Vintagestory.Common.ModContainer.<>c__DisplayClass35_0.<LoadAssembly>b__0(String path) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Common\API\ModContainer.cs:line 448
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at Vintagestory.Common.ModContainer.LoadAssembly(ModCompilationContext compilationContext, ModAssemblyLoader loader) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Common\API\ModContainer.cs:line 447
...
8/1/2023 2:55:25 PM: Critical error occurred
Loaded Mods: bedrespawner@1.0.0, betterruins@0.2.1, chiseltools@1.8.4, hqzlights@1.1.1, fieldsofgold@2.1.6, capreolinae@1.0.3, pantherinae@1.0.6, indappledgroves@0.4.9-rc.8, instruments@1.2.1, moreminerals@1.0.3, game@1.18.6, wildcrafttrees@1.2.3, animalcages@2.1.5, beehivekiln@1.2.2, commonlib@2.1.1, fromgoldencombs@1.4.16-rc.2, sailboat@1.1.0, morepiles@1.4.3, petai@1.7.10, stonebakeoven@1.0.2, tablet@0.1.4, creative@1.18.6, survival@1.18.6, em@2.1.2, playercorpse@1.7.2, stonequarry@3.0.2, wolftaming@1.7.1, bricklayers@2.1.0
System.Exception: Don't know how to instantiate collectible behavior of class 'Carryable' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateCollectibleBehavior(CollectibleObject collectible, String code) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Common\ClassRegistry.cs:line 220
   at Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType packet, IWorldAccessor world, ClassRegistry registry) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Common\Network\BlockTypeNet.cs:line 399
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateBlocks(Block[] blocks, Int32 start, Int32 maxCount) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\Systems\Startup.cs:line 555
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadBlockTypes() in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\Systems\Startup.cs:line 363
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\Systems\Startup.cs:line 338
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Crash written to file at "/home/mard/.var/app/at.vintagestory.VintageStory/config/VintagestoryDataNet7/Logs/client-crash.txt"
```

**Comment by Craluminum2413** [comment]
Caused by mod
