### ISSUE TITLE
Crashing on New World Customize

### ISSUE THREAD

**Issue by Fight-Master** [anegostudios/VintageStory-Issues#2989]
### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Why I try to Customize a new work it crashes.

### How to reproduce

1. Create New World
2. Click Customize button.
3. Crash

### Logs

```Log```Running on 64 bit Windows with 12 GB RAM 
Game Version: v1.18.7 (Stable)
8/5/2023 10:52:02 PM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.GuiScreenWorldCustomize.<>c.<InitGui>b__9_0(PlaystyleListEntry c) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenWorldCustomize.cs:line 87
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Vintagestory.Client.GuiScreenWorldCustomize.InitGui() in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenWorldCustomize.cs:line 87
   at Vintagestory.Client.ScreenManager.LoadScreen(GuiScreen screen) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ScreenManager.cs:line 941
   at Vintagestory.Client.GuiScreenSingleplayerNewWorld.OnCustomize() in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayerNewWorld.cs:line 280
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 304
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 733
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 290
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at GuiScreen.OnMouseUp(MouseEvent e) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\MainMenu\Screens\Special\GuiScreen.cs:line 205
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ClientPlatform\Input.cs:line 229
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/29/2023 6:55:20 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1882708855462422800, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.7.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Shadow\AppData\Local\Temp\RDR6097.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER60C7.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER60E7.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6152.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER61A1.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 62fdb69f-ea0d-4ae1-b6c1-95173757d2b2
Report Status: 268435456
Hashed bucket: 4beace18ff2961a00a20b9baa151e910
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
Closing due to inactivity
