### ISSUE TITLE
Re-downloaded game after not playing for a while and keep getting  "exception was thrown"message

### ISSUE THREAD

**Issue by breeze108** [anegostudios/VintageStory-Issues#2993]
### Game Version

v1.18.7

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Downloaded game after a year+ absence and cant get it to work.  it started loading and then crashes.  I deleted my old game, and the new download, deleted all mods not by Tyron and tried again. No improvement.  this is the  bug report. 

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.7 (Stable)
8/7/2023 7:26:57 PM: Critical error occurred in the following mod: vshud@2.0.31
Loaded Mods: game@1.18.7, vshud@2.0.31, creative@1.18.7, survival@1.18.7
System.MissingMethodException: Method not found: 'Vintagestory.API.Client.GuiComposer Vintagestory.API.Client.GuiComposerHelpers.AddDialogBG(Vintagestory.API.Client.GuiComposer, Vintagestory.API.Client.ElementBounds, Boolean)'.
   at VSHUD.GuiDialogWaypointFrontEnd.OnOwnPlayerDataReceived()
   at VSHUD.WaypointUtils.<>c__DisplayClass16_0.<StartClientSide>b__1()
   at System.Action.Invoke()
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleLevelFinalize(Packet_Server packet) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\Systems\Startup.cs:line 1010
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ClientMain.cs:line 747
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 305
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ScreenManager.cs:line 724
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 8/6/2023 3:40:45 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2148783583060527821, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\ELIZAB~1\AppData\Local\Temp\RDR4076.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER40A6.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER40B6.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER40E3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER40F4.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: d1c13be9-2369-425f-8f15-e7db8e64d4bf
Report Status: 268435456
Hashed bucket: dd06e511597e390a2dd20348b7838acd
Cab Guid: 0 }

### How to reproduce

try and start a new game, and it will crash every time.

### Logs

```Log```Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.7 (Stable)
8/7/2023 7:26:57 PM: Critical error occurred in the following mod: vshud@2.0.31
Loaded Mods: game@1.18.7, vshud@2.0.31, creative@1.18.7, survival@1.18.7
System.MissingMethodException: Method not found: 'Vintagestory.API.Client.GuiComposer Vintagestory.API.Client.GuiComposerHelpers.AddDialogBG(Vintagestory.API.Client.GuiComposer, Vintagestory.API.Client.ElementBounds, Boolean)'.
   at VSHUD.GuiDialogWaypointFrontEnd.OnOwnPlayerDataReceived()
   at VSHUD.WaypointUtils.<>c__DisplayClass16_0.<StartClientSide>b__1()
   at System.Action.Invoke()
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleLevelFinalize(Packet_Server packet) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\Systems\Startup.cs:line 1010
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ClientMain.cs:line 747
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 305
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ScreenManager.cs:line 724
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 8/6/2023 3:40:45 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2148783583060527821, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\ELIZAB~1\AppData\Local\Temp\RDR4076.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER40A6.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER40B6.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER40E3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER40F4.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: d1c13be9-2369-425f-8f15-e7db8e64d4bf
Report Status: 268435456
Hashed bucket: dd06e511597e390a2dd20348b7838acd
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
It is VSHUD to blame, not vanilla issue

**Comment by breeze108** [comment]
Thanks so much. I disabled it and now the game works.
