### ISSUE TITLE
Crash when loading saved game

### ISSUE THREAD

**Issue by FoxHawk** [anegostudios/VintageStory-Issues#2999]
### Game Version

1.18.8

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When loading a saved game, the loading event log says "Something went awry" and it doesn't load the save

### How to reproduce

1. Create a new game save
2. Save and quit the world
3. Load the saved game

### Screenshots

![Screenshot_20230809_180721_VS](https://github.com/anegostudios/VintageStory-Issues/assets/95636478/41fcd4de-4221-4316-8255-13c79dbb53ba)

### Logs

```Log```
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/12305121/server-main.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/12305122/client-main.txt)

**Comment by tyronx** [comment]
looks like a corrupt chunk. try repair mode

**Comment by FoxHawk** [comment]
I tried repair mode on a new world but got the same result. I also got the following error message when i tried to load the new world normally:
`Running on 64 bit Linux with 31490 MB RAM
Game Version: v1.18.8 (Stable)
12/08/2023 20:40:28: Critical error occurred
Loaded Mods: 
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Vintagestory.Client.NoObf.TextureAtlasManager.RegenMipMaps(Int32 atlasNumber) in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 353
   at Vintagestory.Client.NoObf.TextureAtlasManager.<>c__DisplayClass51_0.<runtimeUpdateTexture>b__1() in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 319
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 75
   at OpenTK.Windowing.Desktop.GameWindow.DispatchRenderFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 312
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
`
However, I only got this error message once.

here are the log files generated from trying repair mode:
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/12328170/server-main.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/12328171/client-main.txt)

**Comment by FoxHawk** [comment]
I just tested loading this world in 1.18.7 (not in repair mode) and it loaded up without issues. 

Also are there any new dependencies that need to be installed for 1.18.8 other than .net7? I just want to rule out me not installing a new dependency.

**Comment by tyronx** [comment]
The crash you posted above is not related to any dependencies, as far as I can tell. Can you attach the affected savegame please.

**Comment by FoxHawk** [comment]
Here is the save I was testing this on. The "something went awry" thing occurs with every save when loaded in 1.18.8 (both ones made in 1.18.8 and ones made in 1.18.7).

[vintage hermit valley.vcdbs.zip](https://github.com/anegostudios/VintageStory-Issues/files/12352069/vintage.hermit.valley.vcdbs.zip)

**Comment by tyronx** [comment]
On first try i was not able to reproduce this crash at spawn, i'll ask dilli if he has any input on this.

**Comment by Th3Dilli** [comment]
what linux are you using?


can you show me the output of this command
`ldd --version`

we had an issue with a recent version of libc for zstd but we now use a version shipped with the oldest stable debian version so right now it ships with 2.28 so this one and any newer should work fine maybe that is also the issue here but i am not 100% sure

**Comment by FoxHawk** [comment]
I'm using Ubuntu 22.04.

Here's the output of the command:
```ldd (Ubuntu GLIBC 2.35-0ubuntu3.1) 2.35
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.```

**Comment by Th3Dilli** [comment]
ah its missing the first line with the libc version

should look l ike this (ubuntu 23.04 )
```
ldd (Ubuntu GLIBC 2.37-0ubuntu2) 2.37
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

```

**Comment by FoxHawk** [comment]
Ah sorry about that. Here is that line: `ldd (Ubuntu GLIBC 2.35-0ubuntu3.1) 2.35`

**Comment by Th3Dilli** [comment]
hmm ok yeah ubuntu 22.04 should be fine with 2.35, ill dig some more thank you so far

**Comment by Th3Dilli** [comment]
seems the same as #3009 
closing in favor of it
