### ISSUE TITLE
Crash happened after crafting a knife

### ISSUE THREAD

**Issue by CrayonsAreDelicious** [anegostudios/VintageStory-Issues#3005]
### Game Version

1.18

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Game crashed for a second time after updating 

### Logs

```Log```
Running on 64 bit Windows with 16122 MB RAM
Game Version: v1.18.8 (Stable)
8/10/2023 8:56:33 AM: Critical error occurred in the following mod: primitivesurvival@3.0.5
Loaded Mods: weaponpacka@1.3.1, betterruins@0.0.2, BuggisRandomChanges@3.1.0, extrachests@1.6.0, hideandfabric@1.2.5, justmoreruins@0.3.1, aaamakeitcompatible@0.0.2, meteoricexpansion@1.2.1, moredungeons@0.1.1, primitivesurvival@3.0.5, qptech@1.10.4, rustandrails@1.0.3, riflemod@1.0.0, game@1.18.8, wildcraft@1.4.2, autosifter@1.0.1, captureanimals@2.2.0, medievalexpansion@3.8.1, playercorpse@1.4.1, ruinvariants@1.0.1, sluicefork@1.0.0, creative@1.18.8, survival@1.18.8, metalrecovery@0.1.18-rc.2, blacksmiths@0.3.0-pre.1, tradercamps@1.0.2
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.ModelTransform.Translation'.
   at PrimitiveSurvival.ModSystem.ItemStick.OnHeldIdle(ItemSlot slot, EntityAgent byEntity)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 165
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 59
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 796
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 712
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 75
   at OpenTK.Windowing.Desktop.GameWindow.DispatchRenderFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 312
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 8/9/2023 8:01:00 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1273209627708249444, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.8.0
P3: 6492041a
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ee836ef7-b2ed-494d-b0ae-7e844a908e7a.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.956fb1b6-0f0a-4a4a-9650-32b3bb61f50e.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.aadae3c7-ab6f-483d-b703-6c869e378a9f.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6085208c-58f1-43f4-bcb0-0bac8134e481.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b2b45505-998e-4a8c-b54e-ef34aa1b857f.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_8de098f737c744fcb2cfb2449b6f09668c35b_9d23d9f5_e3d28f06-b808-40b4-a14a-ca6b9ac24b07

Analysis symbol: 
Rechecking for solution: 0
Report Id: 1f11df70-4cdf-4b68-9c7c-0958aa9b86e4
Report Status: 268566528
Hashed bucket: 42c222969642167ad1ab596920285564
Cab Guid: 0 }
--------------
{ TimeGenerated = 8/9/2023 8:00:57 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.8.0, time stamp: 0x6492041a
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x10a4
Faulting application start time: 0x0x1d9cb1db15f1c86
Faulting application path: C:\gaming\Vintagestory\Vintagestory\Vintagestory.exe
Faulting module path: C:\gaming\Vintagestory\Vintagestory\Lib\openal32.dll
Report Id: 1f11df70-4cdf-4b68-9c7c-0958aa9b86e4
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 8/9/2023 7:59:34 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1273209627708249444, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.8.0
P3: 6492041a
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b5255e7d-fb30-46f5-ae91-0b6b0eb6b7d8.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6a6887de-1990-45ea-822d-9f22c6b9cc34.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e48ce019-fd5a-476e-b296-6346a662f413.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.300ca97b-e9a6-4247-8d73-aec6c967408d.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0e1ea713-4f2b-4621-b31c-53ef1074ef3f.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_8de098f737c744fcb2cfb2449b6f09668c35b_9d23d9f5_bd6bc8dc-a6db-4051-bf7f-b282e99f9ef6

Analysis symbol: 
Rechecking for solution: 0
Report Id: 7f2abb55-a738-4635-b6fd-a5156c98e8ca
Report Status: 268566528
Hashed bucket: 42c222969642167ad1ab596920285564
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
Primitive Survival mod is to blame
