### ISSUE TITLE
Structures replacewithblocklayers not working everytime

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#3011]
### Game Version

v1.18.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Its working better than prev versions but still sometimes happens that it doesnt convert the blocks correctly.

The following mod will spawn custom traders every 100 blockish with a bit flying around you could get some examples

### How to reproduce

[Testmod for replacewithblocklayers.zip](https://github.com/anegostudios/VintageStory-Issues/files/12313930/Testmod.for.replacewithblocklayers.zip)

### Screenshots

![2023-08-10_16-32-10](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/8874cead-9de8-41fe-a521-b13663083c6d)
![2023-08-10_16-39-50](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/ac0acc6a-0db2-4a6c-b349-fa0c8d0e1af5)
![2023-08-10_16-38-26](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/9dc65b45-091a-4e85-a178-13da0c9bb872)

### Logs

```Exception System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.ServerMods.BlockSchematicStructure.PlaceRespectingBlockLayers(IBlockAccessor blockAccessor, IWorldAccessor worldForCollectibleResolve, BlockPos startPos, Int32 climateUpLeft, Int32 climateUpRight, Int32 climateBotLeft, Int32 climateBotRight, Dictionary`2 replaceBlocks, Int32[] replaceblockids, Boolean replaceMetaBlocks, Boolean replaceBlockEntities, Boolean suppressSoilIfAirBelow) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\Datastructures\BlockSchematicStructure.cs:line 99
   at Vintagestory.ServerMods.WorldGenVillage.TryGenerate(IBlockAccessor blockAccessor, IWorldAccessor worldForCollectibleResolve, BlockPos pos, Int32 climateUpLeft, Int32 climateUpRight, Int32 climateBotLeft, Int32 climateBotRight, DidGenerate didGenerateStructure) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\6.GenStructures\WorldGenVillage.cs:line 174
   at Vintagestory.ServerMods.GenStructures.DoGenVillages(IMapRegion region, Int32 chunkX, Int32 chunkZ, Boolean postPass, ITreeAttribute chunkGenParams)
   at Vintagestory.ServerMods.GenStructures.OnChunkColumnGen(IChunkColumnGenerateRequest request) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\6.GenStructures\GenStructures.cs:line 131
   at Vintagestory.Server.ServerSystemSupplyChunks.runGenerators(ChunkColumnLoadRequest chunkRequest, Int32 forPass) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 1481```

**Comment by AreYSerious** [comment]
I still encounter this in 1.19.3

**Comment by AreYSerious** [comment]
![2024-01-27_19-51-15](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/9760da7a-a87e-41b6-899d-66f21cb2fa8b)

**Comment by AreYSerious** [comment]
just replace all the blocks, not just the one going into terrain

**Comment by Craluminum2413** [comment]
Does it happen in 1.19 or 1.20?
