### ISSUE TITLE
Tried to put dry grass in multiplayer and crashed

### ISSUE THREAD

**Issue by aruacool** [anegostudios/VintageStory-Issues#3016]
### Game Version

v1.18.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

I tried making a pit kiln and when i put the dry leaves my game crashed

### How to reproduce

I tried making a pit kiln and when i put the dry leaves my game crashed

### Logs
```
Running on 64 bit Windows with 32671 MB RAM
Game Version: v1.18.8 (Stable)
12/08/2023 20:44:08: Critical error occurred
Loaded Mods: game@1.18.8, creative@1.18.8, survival@1.18.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemDryGrass.OnHeldInteractStart(ItemSlot itemslot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handHandling) in VSSurvivalMod\Item\ItemDryGrass.cs:line 78
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 857
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 447
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 92
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 790
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 983
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 75
   at OpenTK.Windowing.Desktop.GameWindow.DispatchRenderFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 312
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/08/2023 22:30:40, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.8.0, time stamp: 0x6492041a
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x4bf8
Faulting application start time: 0x0x1d9cc83b2330a5f
Faulting application path: C:\Users\MyUSER\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\MyUSER\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: eb0669c3-c7d3-4c6a-bd75-a5b3e9116089
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/08/2023 13:40:02, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.8.0, time stamp: 0x6492041a
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x94c
Faulting application start time: 0x0x1d9cc3b2183d8a3
Faulting application path: C:\Users\MyUSER\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\MyUSER\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 8aab33a4-728c-49b9-b648-6ef665b26564
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/08/2023 12:49:54, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.8.0, time stamp: 0x6492041a
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x4148
Faulting application start time: 0x0x1d9cc38d61aab32
Faulting application path: C:\Users\MyUSER\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\MyUSER\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 88abf01c-50be-48b6-905b-065632879062
Faulting package full name: 
Faulting package-relative application ID:  }
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
