### ISSUE TITLE
game crashes when hotswapping bags

### ISSUE THREAD

**Issue by niky45** [anegostudios/VintageStory-Issues#3017]
### Game Version

v1.18.8 

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

title, basically. happened at least twice, with a miner bag and a cattail basket. 

my game is modded but I don't think any of the handful of mods does anything to bags, 

### How to reproduce

(try to) hotswap bags. 

### Logs

Running on 64 bit Windows with 16221 MB RAM
Game Version: v1.18.8 (Stable)
2023-08-12 9:58:38 PM: Critical error occurred
Loaded Mods: bettercrates@1.6.0, bushmeatpemmican@0.1.3, HangingOilLamps@1.0.1, immersivecorpsedrop@1.0.1, knappingmastery@1.0.1, potontheshelf@1.0.0, ragnamans-seeds-from-crops-recipes@1.0.0, roas@1.0.0, sticksfromfirewood@1.0.0, visibleore@1.0.1, vtpp@1.0.0, game@1.18.8, animalcages@2.1.5, egocaribautomapmarkers@2.6.0, canbeignited@1.1.0, farmlanddropssoil@1.4.0, morepiles@1.4.3, claywheel@1.1.0, prospectorinfo@4.3.0, prospecttogether@1.1.0, creative@1.18.8, survival@1.18.8, metalrecovery@0.1.19-pre.1
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 578
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 412
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1862
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 209
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.DispatchUpdateFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 312
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2023-08-12 7:29:08 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1273209627708249444, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.8.0
P3: 6492041a
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a027ba00-8f14-4070-b7ef-57ab6d70b71e.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.68957dc5-dcf6-45f9-a85d-d72360dfda1a.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.34f3410b-ff00-4dc2-a684-8316b416a984.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6f2405c2-ef74-4e7c-8439-2868a1b6c073.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.26ea8995-fb7d-4b2c-a745-a7f304b4195a.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_8de098f737c744fcb2cfb2449b6f09668c35b_9d23d9f5_245864aa-3d6c-49c3-83c7-661f588156c2

Analysis symbol: 
Rechecking for solution: 0
Report Id: 8d03100a-b495-4e2e-9a49-ba0a2b9ef120
Report Status: 268566528
Hashed bucket: 42c222969642167ad1ab596920285564
Cab Guid: 0 }
--------------
{ TimeGenerated = 2023-08-12 7:29:05 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.8.0, time stamp: 0x6492041a
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x3e98
Faulting application start time: 0x0x1d9cd01f4a603fd
Faulting application path: C:\Games\Vintagestory\Vintagestory.exe
Faulting module path: C:\Games\Vintagestory\Lib\openal32.dll
Report Id: 8d03100a-b495-4e2e-9a49-ba0a2b9ef120
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 2023-08-12 1:33:41 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1273209627708249444, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.8.0
P3: 6492041a
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.be81d1d7-eb89-4612-a7c9-8f28e8afb7ba.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7663a77b-8021-4d95-b36d-8bbfa758c32d.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f18979c8-32ce-47f4-a9f3-fd8e0e8d1095.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4042af3d-a360-4e34-8dab-7450a8a9c73d.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7c0b5ef5-875f-498d-91ee-567fc9d4e1e2.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_8de098f737c744fcb2cfb2449b6f09668c35b_9d23d9f5_88920363-6e8e-4e84-980f-44d4ad8a6663

Analysis symbol: 
Rechecking for solution: 0
Report Id: b4f96308-079e-4e2c-817b-63991718fd62
Report Status: 268566528
Hashed bucket: 42c222969642167ad1ab596920285564
Cab Guid: 0 }

**Comment by tyronx** [comment]
what do you mean by hotswap bags?

**Comment by niky45** [comment]
basically you have one bag in the slot and other in the inventory, and try to drag the inventory one into the slot without unequipping the slot one first.  or the slot one into the same inv slot as the other bag. right now can't really remember which one happened.

**Comment by niky45** [comment]
update: happened again, when moving a cattail basket to a slot occupied by a linen bag. 
didn't happen the other way around.

**Comment by tyronx** [comment]
not able to reproduce this in unmodded v1.18.8

**Comment by niky45** [comment]
huh. started a new, local, unmoded save, and it didn't happen. 

... will try the mods next and update soon(tm)

but it may also be a multiplayer issue

**Comment by Craluminum2413** [comment]
Closing due to inactivity
