### ISSUE TITLE
Vintage Story 1.18 Not Starting

### ISSUE THREAD

**Issue by the1truewolf** [anegostudios/VintageStory-Issues#3020]
### Game Version

v1.18.8

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

I cannot start my game on single player or join online. The loading screen show 6 events and freezes. If I go back and try to go to settings for the world or play a multiplayer world the game instantly crashes.  

### How to reproduce

- Click single player 2. Find world name then look to pencil button and press it 3. It crashes instantly.   

- Starting on single player gets stuck on loading screen unless I click back.

### Screenshots

![Screenshot 2023-08-13 103640](https://github.com/anegostudios/VintageStory-Issues/assets/52417503/3ba7dd9c-a32d-4b96-9e6f-00ef09984c5c)

### Logs

```Log```  
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/12329852/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/12329854/client-main.txt)
[server-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/12329855/server-debug.txt)
[server-event.txt](https://github.com/anegostudios/VintageStory-Issues/files/12329856/server-event.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/12329858/server-main.txt)
[server-storyevent.txt](https://github.com/anegostudios/VintageStory-Issues/files/12329859/server-storyevent.txt)

 (CRASH REPORT BELOW)

Running on 64 bit Windows with 16291 MB RAM
Game Version: v1.18.8 (Stable)
8/13/2023 10:26:01 AM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.WorldConfig.loadWorldConfigValuesFromPlaystyle() in VintagestoryLib\Common\Config\WorldConfig.cs:line 108
   at Vintagestory.Common.WorldConfig.selectPlayStyle(String playstylecode) in VintagestoryLib\Common\Config\WorldConfig.cs:line 99
   at Vintagestory.Common.WorldConfig.loadFromSavegame(SaveGame savegame) in VintagestoryLib\Common\Config\WorldConfig.cs:line 57
   at Vintagestory.Client.GuiScreenSingleplayerModify.initGui(SaveGame savegame) in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayerModify.cs:line 52
   at Vintagestory.Client.GuiScreenSingleplayerModify.OnScreenLoaded() in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayerModify.cs:line 176
   at Vintagestory.Client.ScreenManager.LoadScreen(GuiScreen screen) in VintagestoryLib\Client\ScreenManager.cs:line 938
   at Vintagestory.Client.GuiScreenSingleplayer.OnClickCellRight(Int32 cellIndex) in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayer.cs:line 158
   at Vintagestory.API.Client.GuiElementMainMenuCell.OnMouseUpOnElement(MouseEvent args, Int32 elementIndex) in VintagestoryApi\Client\UI\Elements\Impl\Misc\GuiElementMainMenuCell.cs:line 312
   at Vintagestory.API.Client.GuiElementCellList`1.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 241
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at GuiScreen.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\MainMenu\Screens\Special\GuiScreen.cs:line 204
   at Vintagestory.Client.ScreenManager.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 883
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 212
   at OpenTK.Windowing.Desktop.NativeWindow.OnMouseUp(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.DispatchUpdateFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 312
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 8/13/2023 10:24:13 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1273209627708249444, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.8.0
P3: 6492041a
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.badab057-d6b3-407f-a23b-d5c984d3aefa.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9b893f28-b820-46b0-9d74-6ad0bc53988d.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.5279b1f3-a73d-4862-8519-c4503c70f1fe.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.1e5b7b8d-30f8-4a1f-bee7-4f16bc562b56.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.716b03ee-e9a6-43a5-a569-5e075c52f819.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_8de098f737c744fcb2cfb2449b6f09668c35b_9d23d9f5_dae69a49-b71c-4d95-89ce-8d2ab8c25777

Analysis symbol: 
Rechecking for solution: 0
Report Id: 97bf4471-d7ed-4360-b773-0bdb6dfd8992
Report Status: 268566528
Hashed bucket: 42c222969642167ad1ab596920285564
Cab Guid: 0 }
--------------
{ TimeGenerated = 8/13/2023 10:24:12 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.8.0, time stamp: 0x6492041a
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x506c
Faulting application start time: 0x0x1d9cdfa0a4a013a
Faulting application path: C:\Program Files (x86)\Vintage Story\Vintagestory\Vintagestory.exe
Faulting module path: C:\Program Files (x86)\Vintage Story\Vintagestory\Lib\openal32.dll
Report Id: 97bf4471-d7ed-4360-b773-0bdb6dfd8992
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 8/13/2023 10:06:55 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1273209627708249444, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.8.0
P3: 6492041a
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e675f12e-ab39-45c9-a1a1-5e6f3debb2b4.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.3b6077e9-c5aa-4ee0-a13b-4efd54009340.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.1371e985-be77-4a7e-a681-5d644d1489fe.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.bb9d8380-7337-4b8d-9aad-ac36f31f63f1.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6d252fea-4682-4e19-bda6-23f1e16a438a.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_8de098f737c744fcb2cfb2449b6f09668c35b_9d23d9f5_a6c752a4-4c3e-4bd5-8a58-402fa0e9f055

Analysis symbol: 
Rechecking for solution: 0
Report Id: b9d66dff-6d73-4e48-be3e-d1f33dc46355
Report Status: 268566528
Hashed bucket: 42c222969642167ad1ab596920285564
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
You disabled 3 vanilla mods, enable them and try again
