### ISSUE TITLE
Rift Ward crashes client's thread in multiplayer

### ISSUE THREAD

**Issue by BinaryEnigma01** [anegostudios/VintageStory-Issues#3023]
### Game Version

v1.18.7

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

I'm playing on a server, we have a few mods, (I included them in the logs), but everything was fine, I interacted with a friend's rift ward, turned it off and back on, nothing bad happened, I went off exploring, and when I returned, this resulted in the crash (getting close enough to render it was probably what did it, which I have confirmed by reducing the view distance to 32 - this allows me to actually exist and get away, but if I make the render distance higher and get close it happens again)

I think the only difference is that the Rift Ward ran out of charge (And I'm only talking about the Rift Ward specifically because it is mentioned in the error that seems to have crashed it)
Should also be noted that I was the only one this happened to, 2 other people have joined the server since and passed by the Rift Ward with no problems

### How to reproduce

I was not able to reproduce it in singleplayer, even with all the mods
My attempt was just plopping down a rift ward and powering it, speeding time up, it blocked two rifts, but powered down normally and nothing happened.

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/21149088/64ecf62e-7a13-41e4-a8f6-10b1ec253de9)

### Logs

```Log
14.8.2023 14:08:13 [Notification] External Origins in load order: modorigin@G:\Vintagestory\assets\creative\, modorigin@G:\Vintagestory\assets\survival\, mod@BetterRuinsv0.2.1.zip, mod@CraftableSticks 1.17.9.zip, mod@CraluTweaks-v1.0.2.zip, mod@ExtraInfo-v1.4.0.zip, mod@MoreClasses_v1.2.5.zip, mod@PrimitiveSurvival3.2.7.zip, mod@RangedWeapons-0.6.2.zip, mod@Rope Bridges v1.1.0 for VS1.15.zip, mod@rpgitemrarity-1.0.4.zip, mod@she1fish.zip, mod@canbeignited_v1.1.0.zip, mod@CarryOn-1.18_v1.3.0.zip, mod@petai_v1.7.10.zip, mod@ProspectTogether-1.1.0.zip, mod@statushud.zip, mod@th3dungeon_0.1.2.zip, mod@VanillaVariants-v3.2.2.zip, mod@xlib_v0.7.4.zip, mod@FeverstoneHorses-v1.5.0-1.18.x.zip, mod@OneStick_v1.0.1g1.17.0-rc.1.Release.zip, mod@wolftaming_v1.7.3_petai_v1.7.+.zip, mod@xinvtweaks_v1.5.7.zip, mod@xskills_v0.7.5.zip, mod@tablet_v0.1.4.zip
(...)
14.8.2023 14:08:23 [Fatal] Caught unhandled exception in thread 'networkproc'. Exiting game.
14.8.2023 14:08:23 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityRiftWard.ToggleAmbientSound(Boolean on) in C:\Users\Tyron\Documents\vintagestory\game-net4\VSSurvivalMod\BlockEntity\BERiftWard.cs:line 51
   at Vintagestory.GameContent.BlockEntityRiftWard.Deactivate() in C:\Users\Tyron\Documents\vintagestory\game-net4\VSSurvivalMod\BlockEntity\BERiftWard.cs:line 117
   at Vintagestory.Client.NoObf.ClientChunk.PreLoadBlockEntitiesFromPacket(Packet_BlockEntity[] blockEntities, Int32 blockEntitiesCount, ClientMain game) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\Model\ClientChunk.cs:line 335
   at Vintagestory.Client.NoObf.ClientWorldMap.LoadChunkFromPacket(Packet_ServerChunk p) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ClientWorldMap.cs:line 643
   at Vintagestory.Client.NoObf.SystemNetworkProcess.ProcessInBackground(Packet_Server packet) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\Systems\NetworkProcess.cs:line 222
   at Vintagestory.Client.NoObf.SystemNetworkProcess.TryReadPacket(Byte[] data, Int32 dataLength) in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\Systems\NetworkProcess.cs:line 159
   at Vintagestory.Client.NoObf.SystemNetworkProcess.NetworkProcess() in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\Systems\NetworkProcess.cs:line 133
   at Vintagestory.Client.NoObf.ClientThread.Update() in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ClientThread.cs:line 86
   at Vintagestory.Client.NoObf.ClientThread.Process() in C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ClientThread.cs:line 34
```

Also, it's kind of weird that the paths are specifically Users\Tyron etc, I wouldn't expect the dev's folder structure to be "leaked"

**Comment by BinaryEnigma01** [comment]
And it seems like the problem is really the Rift ward being off, then the chunk getting unloaded and reloaded by my client - as long as it is powered, nothing happens even if I move out and back into the chunk, when it runs out of power or gets turned off, nothing happens if I'm there, but as soon as I go away and come back I crash

**Comment by Craluminum2413** [comment]
Closing due to inactivity

**Comment by lisbonjoker** [comment]
> Closing due to inactivity
I mean nobody tried to get more information or replicate it?

**Comment by Craluminum2413** [comment]
@lisbonjoker I will reopen if it happens in 1.20 for someone

**Comment by lisbonjoker** [comment]
> @lisbonjoker I will reopen if it happens in 1.20 for someone 

Will try it when I get home
