### ISSUE TITLE
Unable to start 1.18.8 on Mac

### ISSUE THREAD

**Issue by Bewalticus** [anegostudios/VintageStory-Issues#3024]
### Game Version

v1.18.8

### Platform

Mac

### Modded

None

### SP/MP

None

### Description

VintageStory 1.18.8 does not start on MacOS.
It shows a black window for a few seconds and then dies.

### How to reproduce

1. Download VintageStory 1.18.8 Mac APP
2. Unpack the tar file
3. Move vintagestory file to /Applications
4. Try to start it -> Security warning about unsigned app
5. Allow vintagestory to be executed in system settings
6. Try to start it -> nothing happens
7. Look for the .NET 7 Runtime for Mac (arm64) and install it
8. Try to start vintagestory -> nothing happens
9. Looking at the program output and seeing that it is compiled for x64 and asks for the x64 .NET Runtime
10. Look for the .NET 7 Runtime for Mac (x64) and install it
11. Try to start vintagestory -> a black window appears for a few seconds and then vintagestory dies

### Logs

client-main.txt

```
14.8.2023 16:54:19 [Notification] Client logger started.
14.8.2023 16:54:19 [Notification] Game Version: v1.18.8 (Stable)
14.8.2023 16:54:21 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: /
14.8.2023 16:54:21 [Notification] CPU Cores: 8
14.8.2023 16:54:21 [Notification] Available RAM: 8192 MB
14.8.2023 16:54:21 [Notification] Graphics Card Vendor: Apple
14.8.2023 16:54:21 [Notification] Graphics Card Version: 4.1 Metal - 83.1
14.8.2023 16:54:21 [Notification] Graphics Card Renderer: Apple M1
14.8.2023 16:54:21 [Notification] Graphics Card ShadingLanguageVersion: 4.10
14.8.2023 16:54:21 [Notification] GL.MaxVertexUniformComponents: 4096
14.8.2023 16:54:21 [Notification] GL.MaxUniformBlockSize: 65536
14.8.2023 16:54:21 [Fatal] Game Version: v1.18.8 (Stable)
14.08.2023 16:54:21: Critical error occurred
Loaded Mods: 
System.DllNotFoundException: Unable to load shared library 'libcairo.2.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/Applications/vintagestory.app/libcairo.2.dylib.dylib, 0x0001): tried: '/Applications/vintagestory.app/libcairo.2.dylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/vintagestory.app/libcairo.2.dylib.dylib' (no such file), '/Applications/vintagestory.app/libcairo.2.dylib.dylib' (no such file)
dlopen(/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/libcairo.2.dylib.dylib, 0x0001): tried: '/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/libcairo.2.dylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/libcairo.2.dylib.dylib' (no such file), '/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/libcairo.2.dylib.dylib' (no such file)
dlopen(/Applications/vintagestory.app/Lib/libcairo.2.dylib.dylib, 0x0001): tried: '/Applications/vintagestory.app/Lib/libcairo.2.dylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/vintagestory.app/Lib/libcairo.2.dylib.dylib' (no such file), '/Applications/vintagestory.app/Lib/libcairo.2.dylib.dylib' (no such file)
dlopen(libcairo.2.dylib.dylib, 0x0001): tried: 'libcairo.2.dylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibcairo.2.dylib.dylib' (no such file), '/usr/lib/libcairo.2.dylib.dylib' (no such file, not in dyld cache), 'libcairo.2.dylib.dylib' (no such file), '/usr/local/lib/libcairo.2.dylib.dylib' (no such file), '/usr/lib/libcairo.2.dylib.dylib' (no such file, not in dyld cache)
dlopen(/Applications/vintagestory.app/liblibcairo.2.dylib.dylib, 0x0001): tried: '/Applications/vintagestory.app/liblibcairo.2.dylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/vintagestory.app/liblibcairo.2.dylib.dylib' (no such file), '/Applications/vintagestory.app/liblibcairo.2.dylib.dylib' (no such file)
dlopen(/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/liblibcairo.2.dylib.dylib, 0x0001): tried: '/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/liblibcairo.2.dylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/liblibcairo.2.dylib.dylib' (no such file), '/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/liblibcairo.2.dylib.dylib' (no such file)
dlopen(/Applications/vintagestory.app/Lib/liblibcairo.2.dylib.dylib, 0x0001): tried: '/Applications/vintagestory.app/Lib/liblibcairo.2.dylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/vintagestory.app/Lib/liblibcairo.2.dylib.dylib' (no such file), '/Applications/vintagestory.app/Lib/liblibcairo.2.dylib.dylib' (no such file)
dlopen(liblibcairo.2.dylib.dylib, 0x0001): tried: 'liblibcairo.2.dylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSliblibcairo.2.dylib.dylib' (no such file), '/usr/lib/liblibcairo.2.dylib.dylib' (no such file, not in dyld cache), 'liblibcairo.2.dylib.dylib' (no such file), '/usr/local/lib/liblibcairo.2.dylib.dylib' (no such file), '/usr/lib/liblibcairo.2.dylib.dylib' (no such file, not in dyld cache)
dlopen(/Applications/vintagestory.app/libcairo.2.dylib, 0x0001): tried: '/Applications/vintagestory.app/libcairo.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/vintagestory.app/libcairo.2.dylib' (no such file), '/Applications/vintagestory.app/libcairo.2.dylib' (no such file)
dlopen(/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/libcairo.2.dylib, 0x0001): tried: '/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/libcairo.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/libcairo.2.dylib' (no such file), '/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/libcairo.2.dylib' (no such file)
dlopen(/Applications/vintagestory.app/Lib/libcairo.2.dylib, 0x0001): Library not loaded: /opt/local/lib/libpixman-1.0.dylib
  Referenced from: <70976F19-7A5F-3D19-98BF-11F70DCBC2AF> /Applications/vintagestory.app/Lib/libcairo.2.dylib
  Reason: tried: '/opt/local/lib/libpixman-1.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libpixman-1.0.dylib' (no such file), '/opt/local/lib/libpixman-1.0.dylib' (no such file), '/usr/local/lib/libpixman-1.0.dylib' (no such file), '/usr/lib/libpixman-1.0.dylib' (no such file, not in dyld cache)
dlopen(libcairo.2.dylib, 0x0001): tried: 'libcairo.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibcairo.2.dylib' (no such file), '/usr/lib/libcairo.2.dylib' (no such file, not in dyld cache), 'libcairo.2.dylib' (no such file), '/usr/local/lib/libcairo.2.dylib' (no such file), '/usr/lib/libcairo.2.dylib' (no such file, not in dyld cache)
dlopen(/Applications/vintagestory.app/liblibcairo.2.dylib, 0x0001): tried: '/Applications/vintagestory.app/liblibcairo.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/vintagestory.app/liblibcairo.2.dylib' (no such file), '/Applications/vintagestory.app/liblibcairo.2.dylib' (no such file)
dlopen(/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/liblibcairo.2.dylib, 0x0001): tried: '/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/liblibcairo.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/liblibcairo.2.dylib' (no such file), '/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/liblibcairo.2.dylib' (no such file)
dlopen(/Applications/vintagestory.app/Lib/liblibcairo.2.dylib, 0x0001): tried: '/Applications/vintagestory.app/Lib/liblibcairo.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/vintagestory.app/Lib/liblibcairo.2.dylib' (no such file), '/Applications/vintagestory.app/Lib/liblibcairo.2.dylib' (no such file)
dlopen(liblibcairo.2.dylib, 0x0001): tried: 'liblibcairo.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSliblibcairo.2.dylib' (no such file), '/usr/lib/liblibcairo.2.dylib' (no such file, not in dyld cache), 'liblibcairo.2.dylib' (no such file), '/usr/local/lib/liblibcairo.2.dylib' (no such file), '/usr/lib/liblibcairo.2.dylib' (no such file, not in dyld cache)

   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at Cairo.CairoAPI.DllImportResolver(String libraryName, Assembly assembly, Nullable`1 searchPath) in Cairo\wrapper\Cairo.cs:line 70
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at Cairo.NativeMethods.cairo_version_string()
   at Cairo.CairoAPI.get_VersionString() in Cairo\wrapper\Cairo.cs:line 56
   at Vintagestory.Client.NoObf.ClientPlatformWindows.LogAndTestHardwareInfos() in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 155
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 294
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Crash written to file at "/Users/helge/.config/VintagestoryData/Logs/client-crash.txt"

14.8.2023 16:54:21 [Notification] Exiting game now. Server running=False. Exit reason: Game crashed
```

client-crash.txt

```
Game Version: v1.18.8 (Stable)
14.08.2023 16:54:21: Critical error occurred
Loaded Mods: 
System.DllNotFoundException: Unable to load shared library 'libcairo.2.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/Applications/vintagestory.app/libcairo.2.dylib.dylib, 0x0001): tried: '/Applications/vintagestory.app/libcairo.2.dylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/vintagestory.app/libcairo.2.dylib.dylib' (no such file), '/Applications/vintagestory.app/libcairo.2.dylib.dylib' (no such file)
dlopen(/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/libcairo.2.dylib.dylib, 0x0001): tried: '/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/libcairo.2.dylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/libcairo.2.dylib.dylib' (no such file), '/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/libcairo.2.dylib.dylib' (no such file)
dlopen(/Applications/vintagestory.app/Lib/libcairo.2.dylib.dylib, 0x0001): tried: '/Applications/vintagestory.app/Lib/libcairo.2.dylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/vintagestory.app/Lib/libcairo.2.dylib.dylib' (no such file), '/Applications/vintagestory.app/Lib/libcairo.2.dylib.dylib' (no such file)
dlopen(libcairo.2.dylib.dylib, 0x0001): tried: 'libcairo.2.dylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibcairo.2.dylib.dylib' (no such file), '/usr/lib/libcairo.2.dylib.dylib' (no such file, not in dyld cache), 'libcairo.2.dylib.dylib' (no such file), '/usr/local/lib/libcairo.2.dylib.dylib' (no such file), '/usr/lib/libcairo.2.dylib.dylib' (no such file, not in dyld cache)
dlopen(/Applications/vintagestory.app/liblibcairo.2.dylib.dylib, 0x0001): tried: '/Applications/vintagestory.app/liblibcairo.2.dylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/vintagestory.app/liblibcairo.2.dylib.dylib' (no such file), '/Applications/vintagestory.app/liblibcairo.2.dylib.dylib' (no such file)
dlopen(/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/liblibcairo.2.dylib.dylib, 0x0001): tried: '/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/liblibcairo.2.dylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/liblibcairo.2.dylib.dylib' (no such file), '/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/liblibcairo.2.dylib.dylib' (no such file)
dlopen(/Applications/vintagestory.app/Lib/liblibcairo.2.dylib.dylib, 0x0001): tried: '/Applications/vintagestory.app/Lib/liblibcairo.2.dylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/vintagestory.app/Lib/liblibcairo.2.dylib.dylib' (no such file), '/Applications/vintagestory.app/Lib/liblibcairo.2.dylib.dylib' (no such file)
dlopen(liblibcairo.2.dylib.dylib, 0x0001): tried: 'liblibcairo.2.dylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSliblibcairo.2.dylib.dylib' (no such file), '/usr/lib/liblibcairo.2.dylib.dylib' (no such file, not in dyld cache), 'liblibcairo.2.dylib.dylib' (no such file), '/usr/local/lib/liblibcairo.2.dylib.dylib' (no such file), '/usr/lib/liblibcairo.2.dylib.dylib' (no such file, not in dyld cache)
dlopen(/Applications/vintagestory.app/libcairo.2.dylib, 0x0001): tried: '/Applications/vintagestory.app/libcairo.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/vintagestory.app/libcairo.2.dylib' (no such file), '/Applications/vintagestory.app/libcairo.2.dylib' (no such file)
dlopen(/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/libcairo.2.dylib, 0x0001): tried: '/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/libcairo.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/libcairo.2.dylib' (no such file), '/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/libcairo.2.dylib' (no such file)
dlopen(/Applications/vintagestory.app/Lib/libcairo.2.dylib, 0x0001): Library not loaded: /opt/local/lib/libpixman-1.0.dylib
  Referenced from: <70976F19-7A5F-3D19-98BF-11F70DCBC2AF> /Applications/vintagestory.app/Lib/libcairo.2.dylib
  Reason: tried: '/opt/local/lib/libpixman-1.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libpixman-1.0.dylib' (no such file), '/opt/local/lib/libpixman-1.0.dylib' (no such file), '/usr/local/lib/libpixman-1.0.dylib' (no such file), '/usr/lib/libpixman-1.0.dylib' (no such file, not in dyld cache)
dlopen(libcairo.2.dylib, 0x0001): tried: 'libcairo.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibcairo.2.dylib' (no such file), '/usr/lib/libcairo.2.dylib' (no such file, not in dyld cache), 'libcairo.2.dylib' (no such file), '/usr/local/lib/libcairo.2.dylib' (no such file), '/usr/lib/libcairo.2.dylib' (no such file, not in dyld cache)
dlopen(/Applications/vintagestory.app/liblibcairo.2.dylib, 0x0001): tried: '/Applications/vintagestory.app/liblibcairo.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/vintagestory.app/liblibcairo.2.dylib' (no such file), '/Applications/vintagestory.app/liblibcairo.2.dylib' (no such file)
dlopen(/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/liblibcairo.2.dylib, 0x0001): tried: '/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/liblibcairo.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/liblibcairo.2.dylib' (no such file), '/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App/7.0.10/liblibcairo.2.dylib' (no such file)
dlopen(/Applications/vintagestory.app/Lib/liblibcairo.2.dylib, 0x0001): tried: '/Applications/vintagestory.app/Lib/liblibcairo.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/vintagestory.app/Lib/liblibcairo.2.dylib' (no such file), '/Applications/vintagestory.app/Lib/liblibcairo.2.dylib' (no such file)
dlopen(liblibcairo.2.dylib, 0x0001): tried: 'liblibcairo.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSliblibcairo.2.dylib' (no such file), '/usr/lib/liblibcairo.2.dylib' (no such file, not in dyld cache), 'liblibcairo.2.dylib' (no such file), '/usr/local/lib/liblibcairo.2.dylib' (no such file), '/usr/lib/liblibcairo.2.dylib' (no such file, not in dyld cache)

   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at Cairo.CairoAPI.DllImportResolver(String libraryName, Assembly assembly, Nullable`1 searchPath) in Cairo\wrapper\Cairo.cs:line 70
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at Cairo.NativeMethods.cairo_version_string()
   at Cairo.CairoAPI.get_VersionString() in Cairo\wrapper\Cairo.cs:line 56
   at Vintagestory.Client.NoObf.ClientPlatformWindows.LogAndTestHardwareInfos() in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 155
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 294
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
