### ISSUE TITLE
Temporal storms and server command /nexttempstorm not working on local windows server.

### ISSUE THREAD

**Issue by AnthonyGlaser** [anegostudios/VintageStory-Issues#3025]
### Game Version

v1.18.8

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

I'm running a local server for solo play to improve performance.  Temporal storms are not happening, and the server command /nexttemporalstorm results in [Server Fatal] error.

Object reference not set to an instance of an object.

### How to reproduce

1. Install Vintage story on windows.
2. Make a single save game in single player.
3. Exist single player.
4. Run VintagestoryServer.exe
5. Play in multiplayer, connecting to the local server.
6. Type /NextTempStorm in server window.

### Screenshots

![screenshot](https://github.com/anegostudios/VintageStory-Issues/assets/16389520/24ef6595-d4d7-459b-b594-48d8c03bc52e)

### Logs

```Log```

**Comment by Unrealomega** [comment]
Occurs on a Linux dedicated server as well. Possibly expects a player object as part of the command as it works fine in-game.

Current version is 1.18.15

`11.10.2023 14:51:23 [Server Notification] Handling Console Command /nexttempstorm 
[39;49m[39;49m[31m11.10.2023 14:51:23 [Server Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.SystemTemporalStability.onCmdNextStorm(IServerPlayer player, Int32 groupId, CmdArgs args) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\TemporalStability\TemporalStability.cs:line 250
   at Vintagestory.Common.ChatCommandApi.<>c__DisplayClass27_0.<RegisterCommand>b__0(TextCommandCallingArgs args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\API\Command\ChatCommandApi.cs:line 317
   at Vintagestory.Common.ChatCommandImpl.callHandler(TextCommandCallingArgs callargs, Action`1 onCommandComplete, Dictionary`2 asyncParseResults) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\API\Command\ChatCommandImpl.cs:line 230
   at Vintagestory.Common.ChatCommandApi.Execute(String commandName, TextCommandCallingArgs args, Action`1 onCommandComplete) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\API\Command\ChatCommandApi.cs:line 73
   at Vintagestory.Server.ServerMain.ReceiveServerConsole(String message) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 1214
   at Vintagestory.Server.ServerConsole.<>c__DisplayClass9_0.<readAsync>b__0() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\ServerConsole.cs:line 71
   at Vintagestory.Server.ServerMain.ProcessMainThreadTasks() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 2759
   at Vintagestory.Server.ServerMain.ProcessMain() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 888
   at Vintagestory.Server.ServerMain.Process() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 881`
