### ISSUE TITLE
Vintage Story Crash

### ISSUE THREAD

**Issue by mama-dynamite** [anegostudios/VintageStory-Issues#3028]
### Platform

None

### Modded

None

### SP/MP

None

### Logs

```Log```

**Comment by mama-dynamite** [comment]
Here is the crash report. Running 1.18.8. This happened after updating to latest version. I tried uninstalling and reinstalling. Same result. 

Running on 64 bit Windows with 8072 MB RAM
Game Version: v1.18.8 (Stable)
8/17/2023 4:08:44 PM: Critical error occurred
Loaded Mods: 
System.TypeInitializationException: The type initializer for 'OpenTK.Windowing.Desktop.Monitors' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'glfw' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.LoadLibrary(String libraryName, Version version, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.<>c.<.cctor>b__3_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwInit()
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.Init()
   at OpenTK.Windowing.Desktop.GLFWProvider.EnsureInitialized()
   at OpenTK.Windowing.Desktop.Monitors..cctor()
   --- End of inner exception stack trace ---
   at OpenTK.Windowing.Desktop.Monitors.GetPrimaryMonitor()
   at VSPlatform.XPlatImpl.GetScreenSize() in XPlatformInterface\PlatformFormsImpl.cs:line 30
   at Vintagestory.Client.NoObf.ClientPlatformWindows..ctor(Logger logger) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 60
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 167
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
System.DllNotFoundException: Unable to load DLL 'glfw' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.LoadLibrary(String libraryName, Version version, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.<>c.<.cctor>b__3_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwInit()
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.Init()
   at OpenTK.Windowing.Desktop.GLFWProvider.EnsureInitialized()
   at OpenTK.Windowing.Desktop.Monitors..cctor()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 8/12/2023 5:14:16 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1356069915386531490, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\TEACHE~1\AppData\Local\Temp\RDR649B.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6509.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6539.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER661C.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER665B.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 50106bc4-79af-44cc-91d3-c667c471b33d
Report Status: 268435456
Hashed bucket: b6682851523a865272d1ba673d354ea2
Cab Guid: 0 }
--------------
{ TimeGenerated = 11/3/2022 7:06:19 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1952854560596989694, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\TEACHE~1\AppData\Local\Temp\RDRBBFC.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBC5B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBC7B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBD54.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBDB2.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 561a323e-5a2d-463b-b087-73b970bff227
Report Status: 268435456
Hashed bucket: 78bd6b9a4e12ad376b19eee04e6296fe
Cab Guid: 0 }

**Comment by m-from-space** [comment]
I may be wrong, but the newest release needs `.net (dotnet) runtime version 7` installed, maybe you don't have it.
https://dotnet.microsoft.com/en-us/download

**Comment by pi-stone** [comment]
Exact same error even with the latest .net runtime version 7 :/

**Comment by Th3Dilli** [comment]
there is an issue with a 3rd party library we use that requires vc_redist installed please try to install that
https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by pi-stone** [comment]
Hey it solved my problem ! I had the exact same issue, and by installing vc_redist the crash is fixed ! 
@mama-dynamite you should try !
