### ISSUE TITLE
1.9.3 Handbook CTD when clicking "back"

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#303]
Guess who's baaack

Pastebin for your convenience: [https://pastebin.com/UNVFSPgv](url)

What I did was search for 'basket' in the handbook to check the recipe. The first time it crashed when I pressed 'back', the second time when I opened the placable basket entry, and then when I loaded the save.
Below is the final crash log

```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.9.3 (Stable)5/16/2019 10:12:33 PM: Critical error occurred
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at _EgWCGNlbrB4MWKcxyAvSW4CTWHK._gYXKGnawUm1GnLpmpdf3HbMtFSb()
   at _EgWCGNlbrB4MWKcxyAvSW4CTWHK._HLC6ajgkS5tK4GssG112qvat5AK()
   at _EgWCGNlbrB4MWKcxyAvSW4CTWHK._IIqQH45isFAJmGpBB7mREzB2Ldp()
   at _PndAABz6mbLrIVY3bGkjFENAKYE._u2KBdQ1YadwFfy9QyaDloxApjuq(Single )
   at _NkoWRZbO8vbo2P0bHOmeWW5HFZm._VuoWA1NI32ePh577QetkPcWgv1j(Single )
   at _ClwmnLe1V7vR8n56XkbHz2NmshG._v6KGki9QaYXffAVL8MxroiYvLHZ(Single )
   at _ClwmnLe1V7vR8n56XkbHz2NmshG._bWLdqbxl84dj0WzW4hexmUSwPWP(Single )
   at _mEhEzZ8DmIQe7K9d4tBswO1fhgX._0oOO2PQajHpBpSzMJCyLMiw7tG(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _3vfvgrHj6ymQxm8FJtx4Ruzypih._Z3lNUjeecYm8PMLFsAqAg3ack5w(_mmIyrGEQIkHEG3raFL54FrKNncQ , String[] )
   at _VPmpDmTQc9Jyy6X2oS97VHCLE8A._Z3lNUjeecYm8PMLFsAqAg3ack5w(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 5/16/2019 10:07:20 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
   at Newtonsoft.Json.Linq.JObject.get_Item(System.Object)
   at Vintagestory.API.JsonObject.get_Item(System.String)
   at Vintagestory.GameContent.BlockGenericTypedContainer.GetHeldItemInfo(Vintagestory.API.Common.ItemStack, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor, Boolean)
   at Vintagestory.API.Common.ItemStack.GetDescription(Vintagestory.API.Common.IWorldAccessor, Boolean)
   at Vintagestory.API.Client.GuiElementItemstackInfo.Recompose()
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(Vintagestory.API.Common.ItemSlot)
   at Vintagestory.API.Client.ItemstackComponentBase.RenderItemstackTooltip(Vintagestory.API.Common.ItemStack, Double, Double, Single)
   at Vintagestory.API.Client.SlideshowItemstackTextComponent.RenderInteractiveElements(Single, Double, Double)
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single)
   at Vintagestory.API.Client.GuiComposer.Render(Single)
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single)
   at _YrPLgRNoKqLkIJjZXGQBQZfF0ss._6WZTNVfTa7rWSKqb82sMCqgCFyP(Single)
   at _GUwD6VYkgVQ73AlLfKTdTWGrvUH._NqNCafwIuVnrN0APAIQT44l6CVR(Vintagestory.API.Client.EnumRenderStage, Single)
   at _PndAABz6mbLrIVY3bGkjFENAKYE._NqNCafwIuVnrN0APAIQT44l6CVR(Vintagestory.API.Client.EnumRenderStage, Single)
   at _PndAABz6mbLrIVY3bGkjFENAKYE._8Q0lcHKBmMsrZdVz5CTBHXVZQIW(Single)
   at _NkoWRZbO8vbo2P0bHOmeWW5HFZm._8Q0lcHKBmMsrZdVz5CTBHXVZQIW(Single)
   at _ClwmnLe1V7vR8n56XkbHz2NmshG._v6KGki9QaYXffAVL8MxroiYvLHZ(Single)
   at _ClwmnLe1V7vR8n56XkbHz2NmshG._bWLdqbxl84dj0WzW4hexmUSwPWP(Single)
   at _mEhEzZ8DmIQe7K9d4tBswO1fhgX._0oOO2PQajHpBpSzMJCyLMiw7tG(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _3vfvgrHj6ymQxm8FJtx4Ruzypih._Z3lNUjeecYm8PMLFsAqAg3ack5w(_mmIyrGEQIkHEG3raFL54FrKNncQ, System.String[])
   at _VPmpDmTQc9Jyy6X2oS97VHCLE8A._Z3lNUjeecYm8PMLFsAqAg3ack5w(System.Threading.ThreadStart)

 }
```

**Comment by tyronx** [comment]
Thanks for reporting. This bug should be fixed in v1.9.4, please reopen the issue if this kind of crash happens again after updating.
