### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by TheCatOfAges** [anegostudios/VintageStory-Issues#3034]
### Game Version

v1.18.8.0

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

i tried to do the tutorial, game proceeded to crash 

### How to reproduce

i clicked on the tutorial "start" button in the handbook

### Logs

```
Running on 64 bit Windows with 32745 MB RAM
Game Version: v1.18.8 (Stable)
8/19/2023 9:56:18 AM: Critical error occurred
Loaded Mods: game@1.18.8, creative@1.18.8, survival@1.18.8
System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Peek()
   at Vintagestory.GameContent.GuiDialogHandbook.ReloadPage() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 256
   at Vintagestory.GameContent.ModSystemTutorial.reloadTutorialPage() in VSSurvivalMod\Systems\Handbook\Tutorial\ModSystemTutorial.cs:line 267
   at Vintagestory.GameContent.ModSystemTutorial.onStateUpdate(ActionBoolReturn`1 stepCall) in VSSurvivalMod\Systems\Handbook\Tutorial\ModSystemTutorial.cs:line 241
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean isGlobal, Boolean fallBack) in VintagestoryLib\Client\HotkeyManager.cs:line 375
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1705
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 231
   at OpenTK.Windowing.Desktop.NativeWindow.KeyCallback(Window* window, Keys key, Int32 scancode, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.DispatchUpdateFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 312
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 8/19/2023 8:39:54 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.8.0
P3: 6492041a
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER887.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREE1.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREF2.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREFF.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF10.tmp.txt
\\?\C:\Users\Clayton\AppData\Local\Temp\WERFCF.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_8de098f737c744fcb2cfb2449b6f09668c35b_9d23d9f5_cab_cc374ec6-a624-4b3b-a3ef-d49654083dd6

Analysis symbol: 
Rechecking for solution: 0
Report Id: bcafda1c-6147-4356-a168-c82e2843a56e
Report Status: 131078
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 8/19/2023 4:45:56 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.8.0
P3: 6492041a
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER887.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREE1.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREF2.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREFF.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF10.tmp.txt
\\?\C:\Users\Clayton\AppData\Local\Temp\WERFCF.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_8de098f737c744fcb2cfb2449b6f09668c35b_9d23d9f5_cab_cc374ec6-a624-4b3b-a3ef-d49654083dd6

Analysis symbol: 
Rechecking for solution: 0
Report Id: bcafda1c-6147-4356-a168-c82e2843a56e
Report Status: 131078
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 8/19/2023 12:31:42 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.8.0
P3: 6492041a
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER887.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREE1.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREF2.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREFF.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF10.tmp.txt
\\?\C:\Users\Clayton\AppData\Local\Temp\WERFCF.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_8de098f737c744fcb2cfb2449b6f09668c35b_9d23d9f5_cab_cc374ec6-a624-4b3b-a3ef-d49654083dd6

Analysis symbol: 
Rechecking for solution: 0
Report Id: bcafda1c-6147-4356-a168-c82e2843a56e
Report Status: 131078
Hashed bucket: 
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
