### ISSUE TITLE
Game Crash after worldconfig.

### ISSUE THREAD

**Issue by Joniisan** [anegostudios/VintageStory-Issues#3036]
### Game Version

v1.18.8

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

After editting the world deposit, server would just crash, 

### Logs

Running on 64 bit Windows with 65445 MB RAM
Game Version: v1.18.8 (Stable)
8/19/2023 10:49:40 AM: Critical error occurred
Loaded Mods: game@1.18.8, creative@1.18.8, survival@1.18.8
Newtonsoft.Json.JsonReaderException: Failed deserializing deposits.json: Could not convert string to double: [2]. Path 'chanceMultiplier', line 3, position 27.
   at Vintagestory.Common.Asset.ToObject[T](JsonSerializerSettings settings) in VintagestoryLib\Common\Model\Asset.cs:line 65
   at Vintagestory.ServerMods.GenDeposits.initAssets(ICoreServerAPI api, Boolean blockCallbacks) in VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\5.GenDeposits\GenDeposits.cs:line 77
   at Vintagestory.GameContent.ProPickWorkSpace.<>c__DisplayClass5_0.<OnLoaded>b__0() in VSSurvivalMod\Item\ItemProspectingPick.cs:line 44
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 108
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 8/19/2023 10:46:44 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1273209627708249444, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.8.0
P3: 6492041a
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD08D.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD2A1.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD2B2.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD2B2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD2D2.tmp.txt
\\?\C:\Users\gomun\AppData\Local\Temp\WERD35F.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_8de098f737c744fcb2cfb2449b6f09668c35b_9d23d9f5_0ee3b794-36ac-492d-88a6-4c6518e4bbd3

Analysis symbol: 
Rechecking for solution: 0
Report Id: 915ae81f-3425-4dec-b276-85ef5fcd27ac
Report Status: 268566528
Hashed bucket: 42c222969642167ad1ab596920285564
Cab Guid: 0 }
--------------
{ TimeGenerated = 8/19/2023 10:46:44 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.8.0
P3: 6492041a
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD08D.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD2A1.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD2B2.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD2B2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD2D2.tmp.txt
\\?\C:\Users\gomun\AppData\Local\Temp\WERD35F.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_8de098f737c744fcb2cfb2449b6f09668c35b_9d23d9f5_cab_0ee3b794-36ac-492d-88a6-4c6518e4bbd3

Analysis symbol: 
Rechecking for solution: 0
Report Id: 915ae81f-3425-4dec-b276-85ef5fcd27ac
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 8/19/2023 10:46:43 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.8.0, time stamp: 0x6492041a
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x421c
Faulting application start time: 0x01d9d2aba3854e7d
Faulting application path: C:\Users\gomun\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\gomun\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 915ae81f-3425-4dec-b276-85ef5fcd27ac
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Joniisan** [comment]
After using this command /worldconfig surfaceCopperDeposits [0-5] and changing it from a 1 to 2. Server would just crash.
