### ISSUE TITLE
A pie floating in the water causes NullReferenceException on the server side

### ISSUE THREAD

**Issue by Dmitry221060** [anegostudios/VintageStory-Issues#3041]
### Game Version

1.18.8, 1.18.6 (.net4)

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

A pie floating in the water repeatedly causes NRE on the server side, causing a noticeable lag for everyone on the server. The game [tries to access](https://github.com/anegostudios/vssurvivalmod/blob/d1fed2053587ad4bec1fe4a6771d42d5cb29e760/Systems/Cooking/BlockMeal.cs#L805) "eatenBlock" attribute, but pies don't have it, which causes `NullReferenceException` down the line.

### How to reproduce

1. Make a pie or spawn it from creative menu
2. Find a body of water or make one yourself (1x1x1 is enough)
3. Throw a pie in the water 

### Logs

```
18.8.2023 17:22:43 [Server Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
at Vintagestory.API.Common.AssetLocation.ResolveToDomainAndPath(String domainAndPath, String& domain, String& path) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Assets\AssetLocation.cs:line 169
at Vintagestory.GameContent.BlockMeal.OnGroundIdle(EntityItem entityItem) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Cooking\BlockMeal.cs:line 781
at Vintagestory.API.Common.EntityItem.OnGameTick(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Entity\EntityItem.cs:line 150
at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\World\EntitySimulation.cs:line 326
at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\World\EntitySimulation.cs:line 165
at Vintagestory.Server.ServerMain.Process() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 849
```

**Comment by tyronx** [comment]
Fixed, thanks for the report

**Comment by scubamount** [comment]
dotyerts here.
I originally reported this on the VS discord a couple of weeks ago. The log you are reading is my server log. 

Unfortunately, fixing this bug will be the end of our "Death Pie cult", whereas my server members gather around a pie and sacrifice themselves as well as the pie in order to crash the server.

Thanks for the quick fix, and thanks for the exemplary quick fix you modded up for us, Dmitry. :) outstanding work to you both
