### ISSUE TITLE
while unable to load a singleplayer world, pressing on cancel throws an error

### ISSUE THREAD

**Issue by Saycrain** [anegostudios/VintageStory-Issues#3056]
### Game Version

1.18.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When the loading screen didn't want to load anything, I pressed on cancle to try and load it again and it gave me an error report. while the secoung go around worked like it should.

so I'm not exactly sure why it errord out but worked fine on the secound go without problems on the same world.
hopefully the log can give some insight into why for you guys

### How to reproduce

1. Try and open a singleplayer world
2. But when it doesn't load anything at all, press on cancel. it should stop almost emidiatly

As I can gether, it's an openal propblem somehow

### Logs

```Running on 64 bit Windows with 32693 MB RAM
Game Version: v1.18.8 (Stable)
28/08/2023 15.00.53: Critical error occurred
Loaded Mods: 
System.Exception: Coding error: Mods must not get assets before AssetsLoaded stage - do not load assets in a Start() method!
   at Vintagestory.Common.AssetManager.TryGet(AssetLocation Location, Boolean loadAsset) in VintagestoryLib\Common\FileIO\AssetManager.cs:line 239
   at Vintagestory.Client.NoObf.TextureAtlasManager.LoadBitmap(ClientMain game, AssetLocationAndSource textureLoc) in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 832
   at Vintagestory.Client.NoObf.TextureAtlasManager.LoadCompositeBitmap_Single(ClientMain game, AssetLocationAndSource compositeTextureLocation) in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 663
   at Vintagestory.Client.NoObf.TextureAtlasManager.LoadCompositeBitmap_NoOverlayDispose(ClientMain game, AssetLocationAndSource compositeTextureLocation) in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 784
   at Vintagestory.Client.NoObf.TextureAtlasManager.LoadBitmaps(BakedBitmap[] bitmaps) in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 445
   at Vintagestory.Client.NoObf.TextureAtlasManager.<>c__DisplayClass56_0.<PopulateTextureAtlassesFromTextures>b__0() in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 408
   at Vintagestory.API.Util.AsyncHelper.Multithreaded.OnWorkerThread(Action task) in VintagestoryApi\Util\AsyncHelper.cs:line 52
   at Vintagestory.API.Util.AsyncHelper.Multithreaded.<>c__DisplayClass3_0.<StartWorkerThread>b__0() in VintagestoryApi\Util\AsyncHelper.cs:line 44
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 108
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 27/08/2023 23.42.38, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.8.0, time stamp: 0x6492041a
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x113c
Faulting application start time: 0x01d9d92621fe4ead
Faulting application path: D:\Games\Other\Vintagestory\Vintagestory.exe
Faulting module path: D:\Games\Other\Vintagestory\Lib\openal32.dll
Report ID: 96b9a20e-f5a1-44d1-9f27-e54875844bdf
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 27/08/2023 22.36.02, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.8.0, time stamp: 0x6492041a
Faulting module name: atio6axx.dll, version: 31.0.12027.9001, time stamp: 0x64260186
Exception code: 0xc0000005
Fault offset: 0x00000000003effc5
Faulting process ID: 0x1b28
Faulting application start time: 0x01d9d916f21fb3d0
Faulting application path: D:\Games\Other\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\DriverStore\FileRepository\u0390451.inf_amd64_39377efdd62734d1\B390182\atio6axx.dll
Report ID: 8161bdc7-ef9c-480c-9d03-2c56e45d8c8d
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 27/08/2023 22.36.01, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
CoreCLR Version: 7.0.222.60605
.NET Version: 7.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFDA510FFC5
 }

**Comment by scubamount** [comment]
Try 1.18.9-rc1?

**Comment by Saycrain** [comment]
it was a random crash/error that I'm unsure if I'm able to replucate it reliably, so I'm unsurten if I'd be able to see if the never versions would fix it or not.
I were able to load the same world I tried right after the restarting the game somehow, so I'm not sure what the game did different after the fact 🤨

**Comment by Craluminum2413** [comment]
Closing due to inactivity
