### ISSUE TITLE
VintageStory crash

### ISSUE THREAD

**Issue by HardyYouTube** [anegostudios/VintageStory-Issues#3064]
### Game Version

v1.18.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I can`t open VintageStory
here log
Running on 64 bit Windows with 4095 MB RAM
Game Version: v1.18.8 (Stable)
31.08.2023 14:24:31: Critical error occurred
Loaded Mods: 
System.TypeInitializationException: The type initializer for 'OpenTK.Windowing.Desktop.Monitors' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'glfw' or one of its dependencies: Не найден указанный модуль. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.LoadLibrary(String libraryName, Version version, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.<>c.<.cctor>b__3_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwInit()
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.Init()
   at OpenTK.Windowing.Desktop.GLFWProvider.EnsureInitialized()
   at OpenTK.Windowing.Desktop.Monitors..cctor()
   --- End of inner exception stack trace ---
   at OpenTK.Windowing.Desktop.Monitors.GetPrimaryMonitor()
   at VSPlatform.XPlatImpl.GetScreenSize()
   at Vintagestory.Client.NoObf.ClientPlatformWindows..ctor(Logger logger)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
System.DllNotFoundException: Unable to load DLL 'glfw' or one of its dependencies: Не найден указанный модуль. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.LoadLibrary(String libraryName, Version version, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.<>c.<.cctor>b__3_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwInit()
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.Init()
   at OpenTK.Windowing.Desktop.GLFWProvider.EnsureInitialized()
   at OpenTK.Windowing.Desktop.Monitors..cctor()

### Logs

Running on 64 bit Windows with 4095 MB RAM
Game Version: v1.18.8 (Stable)
31.08.2023 14:24:31: Critical error occurred
Loaded Mods: 
System.TypeInitializationException: The type initializer for 'OpenTK.Windowing.Desktop.Monitors' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'glfw' or one of its dependencies: Не найден указанный модуль. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.LoadLibrary(String libraryName, Version version, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.<>c.<.cctor>b__3_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwInit()
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.Init()
   at OpenTK.Windowing.Desktop.GLFWProvider.EnsureInitialized()
   at OpenTK.Windowing.Desktop.Monitors..cctor()
   --- End of inner exception stack trace ---
   at OpenTK.Windowing.Desktop.Monitors.GetPrimaryMonitor()
   at VSPlatform.XPlatImpl.GetScreenSize()
   at Vintagestory.Client.NoObf.ClientPlatformWindows..ctor(Logger logger)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
System.DllNotFoundException: Unable to load DLL 'glfw' or one of its dependencies: Не найден указанный модуль. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.LoadLibrary(String libraryName, Version version, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.<>c.<.cctor>b__3_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwInit()
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.Init()
   at OpenTK.Windowing.Desktop.GLFWProvider.EnsureInitialized()
   at OpenTK.Windowing.Desktop.Monitors..cctor()

**Comment by Th3Dilli** [comment]
Duplicate #3028 and should be solved by since 1.18.09
