### ISSUE TITLE
Random crash in SP

### ISSUE THREAD

**Issue by Jimzawy** [anegostudios/VintageStory-Issues#3075]
### Game Version

v1.18.10 (Stable)

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Random crash while making a macro for waypoints on the night of the 2nd day and recieved a message that monsters start to appear

### How to reproduce

Just on the 2ns day sitting in the open, making a macro for clay and received a message that monsters started to appear

### Logs

Running on 64 bit Windows with 16317 MB RAM
Game Version: v1.18.10 (Stable)
9/3/2023 2:22:48 AM: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.15, arrowrecovery@1.0.0, betterruins@0.2.2, bushmeat_meals@1.0.7, buzzwords@1.3.0, composter@1.0.5, cralutweaks@1.0.2, extrainfo@1.5.0, fancysky@1.0.6, caninae@0.1.1, capreolinae@1.0.4, pantherinae@1.0.7, foundrymod@1.0.0, furniturelibrary@1.0.9, HangingOilLamps@1.0.1, millwright@1.0.7, primitivesurvival@3.2.7, RecycleSacksJimzawy@0.0.1, dzsalvageplus@1.0.1, she1fish@1.1.0, spyglass@0.4.5, sticksarefirewood@1.0.0, sticksfromfirelogs@1.3.0, visibleore@1.0.1, vgaas@1.0.1, game@1.18.10, alloycalculator@1.0.0, animalcages@2.1.5, canbeignited@1.1.0, carryon@1.5.0, danatweaks@1.1.0, expandedfoods@1.6.7, fieldsofsalt@1.1.2, hudclock@3.3.0, sailboat@1.1.0, mapautocenter@1.1.1, petai@1.8.0, claywheel@1.1.0, prospectorinfo@4.3.0, stillnecessaries@1.0.1, vanvar@3.2.2, creative@1.18.10, survival@1.18.10, vsvillage@0.7.3, metalrecovery@0.1.19-pre.1, bullseye@2.5.0-rc.1, cats@1.8.0, feverstonehorses@1.5.0, wolftaming@1.8.0, xinvtweaks@1.5.7
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyPress(ICoreClientAPI api, KeyEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 572
   at Vintagestory.API.Client.GuiComposer.OnKeyPress(KeyEvent args) in VintagestoryApi\Client\UI\GuiComposer.cs:line 615
   at Vintagestory.API.Client.GuiDialog.OnKeyPress(KeyEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 458
   at Vintagestory.Client.NoObf.GuiManager.OnKeyPress(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 379
   at Vintagestory.Client.NoObf.ClientMain.OnKeyPress(KeyEvent eventArgs) in VintagestoryLib\Client\ClientMain.cs:line 1795
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyPress(TextInputEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 219
   at OpenTK.Windowing.Desktop.NativeWindow.CharCallback(Window* window, UInt32 codepoint)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 312
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 9/2/2023 8:17:14 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2214170192790503688, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.10.0
P3: 64b07659
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7187.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER78DB.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER78FC.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER78FA.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7949.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_38893ed42eb8d1a668828edf5bed1a44a4c7eb_93d687c4_d95cf13a-9568-4814-9337-6a2acc3cfb97

Analysis symbol: 
Rechecking for solution: 0
Report Id: a715e828-47b2-4431-a284-6e356a02c1b7
Report Status: 268566528
Hashed bucket: e045985d4f8a18ca4eba500f25894108
Cab Guid: 0 }
--------------
{ TimeGenerated = 9/2/2023 8:17:11 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.10.0, time stamp: 0x64b07659
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x44e4
Faulting application start time: 0x01d9ddbe728e65c6
Faulting application path: C:\Users\Jimzawy\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Jimzawy\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: a715e828-47b2-4431-a284-6e356a02c1b7
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 9/2/2023 7:54:21 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2214170192790503688, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.10.0
P3: 64b07659
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7ECC.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8555.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8575.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8573.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER85C2.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_38893ed42eb8d1a668828edf5bed1a44a4c7eb_93d687c4_4afcbbdc-aa1f-49ae-9362-a2d8bd209556

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5e83c636-9916-43a4-9697-645a5bc7289c
Report Status: 268566528
Hashed bucket: e045985d4f8a18ca4eba500f25894108
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
Closing due to inactivity
