### ISSUE TITLE
Crash after joining the server, opening the creative menu and starting to search type

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#3077]
### Game Version

1.18.10

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Logs

```Running on 64 bit Windows with 32723 MB RAM
Game Version: v1.18.10 (Stable)
03.09.2023 20:48:36: Critical error occurred
Loaded Mods: acorns@0.5.2, aculinaryartillery@1.0.15, ancienttools@1.5.8, beardeddragons@1.0.0, bettercrates@1.6.0, betterruins@0.2.2, Ceramos@0.4.1, chiseltools@1.8.4, drdecor@1.2.0, extrachests@1.7.0, fantasycreatures@0.6.2, capreolinae@1.0.4, foundrymod@1.0.0, furniturelibrary@1.0.9, giantgouramis@1.0.1, ClaimsRadar@1.0.1, instruments@1.2.2, leopardgeckos@1.2.1, millwright@1.0.7, newworldgianttortoises@1.0.2, peacockbasses@1.1.0, primitivesurvival@3.2.7, spyglass@0.4.5, tprunes@1.0.8, thecritterpack@0.7.6, translocatorengineeringredux@1.4.6, truesunfishes@1.1.0, game@1.18.10, altgliderimplementation@1.1.3, betterfirepit@1.1.1, canmarket@0.3.10, carryon@1.0.0, commonlib@2.2.0, expandedfoods@1.6.7, fishing@1.1.5, fromgoldencombs@1.4.21, fruittreebranchfix@1.0.0, glidervar@1.1.1, sailboat@1.1.0, morepiles@1.4.3, petai@1.8.0, simplestep@1.0.8, stonebakeoven@1.0.6, th3dungeon@0.1.3, usefulstuff17@1.1.6, creative@1.18.10, vsquest@0.5.0, survival@1.18.10, workbenchexpansion@1.7.0, xlib@0.7.4, awearablelight@1.0.8, betterbamboo@1.0.2, bugnetcompatibility@1.0.1, captureanimals@2.5.3, cob@1.4.0, cobserver@1.0.0, em@2.3.0, playercorpse@1.8.0, rifteye@0.2.4, stonequarry@3.1.5, wolftaming@1.8.0, xskills@0.7.5, bricklayers@2.2.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.FilterItemsBySearchText(String text, Dictionary`2 searchCache, Dictionary`2 searchCacheNames) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 557
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnTextChanged(String text) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 421
   at Vintagestory.API.Client.GuiElementEditableTextBase.TextChanged() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 327
   at Vintagestory.API.Client.GuiElementEditableTextBase.LoadValue(List`1 newLines) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 291
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyPress(ICoreClientAPI api, KeyEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 593
   at Vintagestory.API.Client.GuiComposer.OnKeyPress(KeyEvent args) in VintagestoryApi\Client\UI\GuiComposer.cs:line 615
   at Vintagestory.API.Client.GuiDialog.OnKeyPress(KeyEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 452
   at Vintagestory.Client.NoObf.GuiManager.OnKeyPress(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 382
   at Vintagestory.Client.NoObf.ClientMain.OnKeyPress(KeyEvent eventArgs) in VintagestoryLib\Client\ClientMain.cs:line 1782
   at Vintagestory.Client.GuiScreenRunningGame.OnKeyPress(KeyEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 320
   at Vintagestory.Client.ScreenManager.OnKeyPress(KeyEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 864
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyPress(TextInputEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 221
   at OpenTK.Windowing.Desktop.NativeWindow.OnTextInput(TextInputEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.CharCallback(Window* window, UInt32 codepoint)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 312
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 03.09.2023 20:47:26, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.18.10.0, Zeitstempel: 0x64b07659
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x9614
Startzeit der fehlerhaften Anwendung: 0x01d9de96da23cde5
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 563a6450-04e4-4c00-b411-c9d1cf7e872a
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 03.09.2023 20:45:07, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.18.10.0, Zeitstempel: 0x64b07659
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x2634
Startzeit der fehlerhaften Anwendung: 0x01d9de96a0ef09ec
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 7e95d075-f9ac-4456-ae87-0ad3cf49ca10
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 03.09.2023 20:37:25, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.18.10.0, Zeitstempel: 0x64b07659
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x886c
Startzeit der fehlerhaften Anwendung: 0x01d9de93d04ba1da
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 16de7970-969d-48d2-bdbf-afc97310d2bf
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
