### ISSUE TITLE
Finally logged in and it started giving me this

### ISSUE THREAD

**Issue by TonTon149** [anegostudios/VintageStory-Issues#3081]
### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

started the game. managed to log in and before iteven started it gave me this

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.1 (Stable)
05/09/2023 10:07:30: Critical error occurred
Loaded Mods: 
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: b. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Vintagestory.Client.MaxObf.SessionManager.<>c__DisplayClass6_0.<DoLogin>b__0(CompletedArgs args) in VintagestoryLib\Client\Util\SessionManager.cs:line 192
   at Vintagestory.Common.MyWebClient.onComplete(Object sender, UploadValuesCompletedEventArgs e) in VintagestoryLib\Common\Network\MyWebClient.cs:line 121
   at System.Net.WebClient.OnUploadValuesCompleted(UploadValuesCompletedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

### How to reproduce

start, log in, crash

### Logs

```Log```

**Comment by TonTon149** [comment]
> Update to 1.18.10

it is already on that version?

**Comment by Craluminum2413** [comment]
@TonTon149 You are using 1.18.1

**Comment by TonTon149** [comment]
that is whats avalable on itch.io?

**Comment by TonTon149** [comment]
> @TonTon149 You are using 1.18.1, it is 9 versions behind

do they just have to update the version avalable on itch.io?

**Comment by TonTon149** [comment]
i think i may have solved it

**Comment by Th3Dilli** [comment]
Probably a issue with some assets file, a reinstall may fix that, where you able to solve it?
