### ISSUE TITLE
Crash upon starting

### ISSUE THREAD

**Issue by Redacted12345** [anegostudios/VintageStory-Issues#3084]
### Game Version

v1.18.10

### Platform

Windows

### Modded

Modded

### SP/MP

None

### Description

Crashes the moment i open the app

### Logs

Running on 64 bit Windows with 8012 MB RAM
Game Version: v1.18.10 (Stable)
06/09/2023 19:39:50: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: The driver does not appear to support OpenGL
   at OpenTK.Windowing.Desktop.GLFWProvider.<>c.<.cctor>b__10_0(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings) in VintagestoryLib\Client\ClientPlatform\GameWindowNative.cs:line 15
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 273
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 05/09/2023 21:49:10, Site = , Source = Windows Error Reporting, Message = Fault bucket 1580861368582747900, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.10.0
P3: 64b07659
P4: KERNELBASE.dll
P5: 10.0.19041.3324
P6: 6967c799
P7: e0434352
P8: 000000000002cf19
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1E8D.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3a643eee2fdf8e3b3c78d432193083558631cf_93d687c4_3f067819-b067-4b39-a210-4fc138647853

Analysis symbol: 
Rechecking for solution: 0
Report Id: 97da7882-2bc5-49ed-858f-a7989efeef46
Report Status: 268435456
Hashed bucket: def0fe22d4429dd3c5f05909f98336fc
Cab Guid: 0 }
--------------
{ TimeGenerated = 05/09/2023 21:49:09, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.10.0
P3: 64b07659
P4: KERNELBASE.dll
P5: 10.0.19041.3324
P6: 6967c799
P7: e0434352
P8: 000000000002cf19
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_3a643eee2fdf8e3b3c78d432193083558631cf_93d687c4_3f067819-b067-4b39-a210-4fc138647853

Analysis symbol: 
Rechecking for solution: 0
Report Id: 97da7882-2bc5-49ed-858f-a7989efeef46
Report Status: 4
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 05/09/2023 21:49:09, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.10.0, time stamp: 0x64b07659
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3324, time stamp: 0x6967c799
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process ID: 0x1280
Faulting application start time: 0x01d9e03a673e44cb
Faulting application path: C:\Users\spencer\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 97da7882-2bc5-49ed-858f-a7989efeef46
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Th3Dilli** [comment]
What Graphics card or what System/Hardware do you have?
> OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: The driver does not appear to support OpenGL

Have you been able to run prior version or is this th first time trying it out?

**Comment by Redacted12345** [comment]
> 
> Have you been able to run prior version or is this th first time trying it out?

ive got near 100 hours of playtime, it sorted itself out that time but has happened again in v1.18.13

**Comment by Redacted12345** [comment]
tried reinstalling, didnt work
Running on 64 bit Windows with 8012 MB RAM
Game Version: v1.18.13 (Stable)
22/09/2023 21:53:50: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: The driver does not appear to support OpenGL
   at OpenTK.Windowing.Desktop.GLFWProvider.<>c.<.cctor>b__10_0(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings) in VintagestoryLib\Client\ClientPlatform\GameWindowNative.cs:line 15
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 273
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 22/09/2023 19:09:22, Site = , Source = Windows Error Reporting, Message = Fault bucket 2094801885999319479, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.7.0
P3: 64bd7a7d
P4: Vintagestory
P5: 1.18.7.0
P6: 64bd7a7d
P7: 1c
P8: 2f
P9: System.IO.FileLoadException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDE56.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_5d1e3799ed71d3d3186c316c15da1df1236c97bf_229aabcc_ce943e53-41eb-4970-a066-4bef72200da7

Analysis symbol: 
Rechecking for solution: 0
Report Id: 39314b40-f45d-4e12-8bb9-0480543a7da2
Report Status: 268435456
Hashed bucket: 5561d77b9d22be59cd123b3771cec9b7
Cab Guid: 0 }
--------------
{ TimeGenerated = 22/09/2023 19:09:22, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.7.0
P3: 64bd7a7d
P4: Vintagestory
P5: 1.18.7.0
P6: 64bd7a7d
P7: 1c
P8: 2f
P9: System.IO.FileLoadException
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_5d1e3799ed71d3d3186c316c15da1df1236c97bf_229aabcc_ce943e53-41eb-4970-a066-4bef72200da7

Analysis symbol: 
Rechecking for solution: 0
Report Id: 39314b40-f45d-4e12-8bb9-0480543a7da2
Report Status: 4
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 22/09/2023 19:09:21, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.7.0, time stamp: 0x64bd7a7d
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3393, time stamp: 0x6b4de7c9
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process ID: 0x2584
Faulting application start time: 0x01d9ed7fe9646f26
Faulting application path: C:\Users\spencer\AppData\Roaming\Vintage.Story.v1.18.7\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 39314b40-f45d-4e12-8bb9-0480543a7da2
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Update drivers
