### ISSUE TITLE
Crash while trying to search for an schematic to paste in worledit

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#3094]
### Game Version

1.18.10

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Using the text field/ search bar will immediately make the game crash every time. pasted one schematic into the same sp world before (big ones)

### Logs

```Running on 64 bit Windows with 32723 MB RAM
Game Version: v1.18.10 (Stable)
12.09.2023 17:52:42: Critical error occurred
Loaded Mods: ClaimsRadar@1.0.1, TA_plainsandvalleys@1.0.5, game@1.18.10, creative@1.18.10, survival@1.18.10, cob@1.4.0, cobserver@1.0.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.ServerMods.WorldEdit.WorldEditClientHandler.OnSetValueToolOptions(String code, String elem, String newval) in VSCreativeMod\WorldEditClientHandler.cs:line 660
   at Vintagestory.ServerMods.WorldEdit.WorldEditClientHandler.<>c__DisplayClass29_0.<OpenToolOptionsDialog>b__1(String elem, String newval) in VSCreativeMod\WorldEditClientHandler.cs:line 616
   at Vintagestory.API.Client.GuiJsonDialog.<>c__DisplayClass11_0.<ComposeElement>b__3(String newval) in VintagestoryApi\Client\UI\Dialog\GuiJsonDialog.cs:line 181
   at Vintagestory.API.Client.GuiElementEditableTextBase.TextChanged() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 327
   at Vintagestory.API.Client.GuiElementEditableTextBase.LoadValue(List`1 newLines) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 291
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyPress(ICoreClientAPI api, KeyEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 593
   at Vintagestory.API.Client.GuiComposer.OnKeyPress(KeyEvent args) in VintagestoryApi\Client\UI\GuiComposer.cs:line 615
   at Vintagestory.API.Client.GuiDialog.OnKeyPress(KeyEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 458
   at Vintagestory.Client.NoObf.GuiManager.OnKeyPress(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 382
   at Vintagestory.Client.NoObf.ClientMain.OnKeyPress(KeyEvent eventArgs) in VintagestoryLib\Client\ClientMain.cs:line 1787
   at Vintagestory.Client.GuiScreenRunningGame.OnKeyPress(KeyEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 320
   at Vintagestory.Client.ScreenManager.OnKeyPress(KeyEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 864
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyPress(TextInputEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 221
   at OpenTK.Windowing.Desktop.NativeWindow.OnTextInput(TextInputEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.CharCallback(Window* window, UInt32 codepoint)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 312
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12.09.2023 17:51:44, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.18.10.0, Zeitstempel: 0x64b07659
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x35c8
Startzeit der fehlerhaften Anwendung: 0x01d9e58f9e609ea6
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 746a8e18-785b-4b71-88f8-76e0222fb9ca
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 12.09.2023 15:50:52, Site = , Source = Application Hang, Message = Das Programm Vintagestory.exe Version 1.18.10.0 hat die Interaktion mit Windows beendet und wurde geschlossen. Überprüfen Sie den Problemverlauf in der Systemsteuerung "Sicherheit und Wartung", um nach weiteren Informationen zum Problem zu suchen.

Prozess-ID: 6f48

Startzeit: 01d9e56f3816e391

Beendigungszeit: 0

Anwendungspfad: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe

Bericht-ID: 6a1b21be-2df6-47ef-8c3c-a0b5b9aa7b1a

Vollständiger Name des fehlerhaften Pakets: 

Relative Anwendungs-ID des fehlerhaften Pakets: 

Absturztyp: Unknown
 }
--------------
{ TimeGenerated = 11.09.2023 22:08:15, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.18.10.0, Zeitstempel: 0x64b07659
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x5e30
Startzeit der fehlerhaften Anwendung: 0x01d9e4eb06317f68
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: fa7a2c1e-6a2c-4ed0-817a-bb56973c1c4f
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
