### ISSUE TITLE
Modded server entrance issue

### ISSUE THREAD

**Issue by DarkWalf88** [anegostudios/VintageStory-Issues#3095]
### Game Version

1.18.10

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

I get this problem whenever I try to enter newfie's modded server

### How to reproduce

1. start Vintage story
2. got to multiplayer
3. browse public servers
4. search newfies server
5. join server
6. download mod
7. crash 

### Logs

Running on 64 bit Windows with 20413 MB RAM
Game Version: v1.18.10 (Stable)
12/09/2023 20:52:01: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.15, ancienttools@1.5.8, axleinblocks@1.0.18, signs@1.0.1, bettercrates@1.6.0, betterruins@0.2.2, blacksmithname@1.1.1, cellardoor@1.3.0, Ceramos@0.4.1, chiseltools@1.8.4, hqzlights@1.1.1, driedpeat@1.0.2, extrachests@1.7.0, morecrops@1.0.3, furniturelibrary@1.0.9, gwb@1.0.1, HangingOilLamps@1.0.1, hideandfabric@1.3.0, materialaging@1.1.0, meteoricexpansion@1.2.4, millwright@1.0.7, mbpc@1.0.0, moreclay@1.0.1, leadroof@1.3.4, nacatfish@1.0.1, pondfrogsiii@1.2.2, palisademod@1.1.0, pieontheshelf@1.0.0, playerlist@1.5.2, potontheshelf@1.0.0, primitivesurvival@3.2.8, rackablefirestarter@1.0.0, resinglue@0.0.2, she1fish@1.1.0, smokychimneys@1.0.0, sortablestorage@1.9.0, spyglass@0.4.5, tprunes@1.0.9, translocatorengineeringredux@1.4.6, game@1.18.10, wildcraft@1.6.6, abcsreborn@0.1.2, animalcages@2.2.0, autoatlas@1.0.1, blacksmithgloves@1.0.1, canbeignited@1.1.0, canjewelry@0.1.15, canmarket@0.3.12, carryon@1.5.0, commonlib@2.2.0, expandedfoods@1.6.7, fairplayguardian@1.1.3, fancyplanters@1.2.0, fishing@1.1.5, fromgoldencombs@1.4.21, sailboat@1.1.0, kreaturesandkritters@1.0.3, lc@1.0.0, lavoisier@1.3.0, liquidcontainers@1.1.0, medievalexpansion@3.10.0, moreanimals@1.2.4, petai@1.8.0, claywheel@1.1.0, resingluetools@0.0.5, scarecrow@1.3.1, scythemold@1.0.0, stonebakeoven@1.0.6, storageoptions@1.0.1, usefulstuff17@1.2.0, vanvar@3.2.2, creative@1.18.10, survival@1.18.10, woodenfortifications@0.0.4, woodfp@1.0.0, xlib@0.7.4, xmelee@0.0.12, awearablelight@1.0.8, bugnetcompatibility@1.0.1, bullseye@2.5.0, cats@1.8.0, chemistrylib@1.1.5, em@2.3.0, feverstonewilds@1.4.1, linearpower@0.2.1, playercorpse@1.8.0, simplewinddirection@1.0.2, stonequarry@3.1.5, wolftaming@1.8.0, xskills@0.7.5, bricklayers@2.2.0, kos-goldamalgam@1.0.0, moreroads@1.5.4
System.Exception: Something went wrong in the startup process, no item shapes have been loaded at all. Please try disabling all mods apart from Essentials, Survival, Creative. If that solves the issue, check which mod is causing this. If that does not solve the issue, please report.
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(String type, AssetLocation name, CompositeShape compositeShape, MeshData& modeldata, ITexPositionSource texSource, Int32 generalGlowLevel, Byte climateColorMapIndex, Byte seasonColorMapIndex, Nullable`1 quantityElements, String[] selectiveElements) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 115
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateItem(Item item, CompositeShape forShape, MeshData& modeldata) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 681
   at Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateItems(IList`1 itemtypes, Int32 offset, Int32 maxCount) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselatorManager.cs:line 859
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step7(Int32 index, Int32 frameCount) in VintagestoryLib\Client\Systems\Startup.cs:line 777
   at Vintagestory.Client.NoObf.ClientSystemStartup.<BeginItemTesselation>b__42_1() in VintagestoryLib\Client\Systems\Startup.cs:line 772
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 322
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 76
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 312
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/09/2023 20:42:02, Site = , Source = Application Error, Message = Nome dell'applicazione che ha generato l'errore: Vintagestory.exe, versione: 1.18.10.0, timestamp: 0x64b07659
Nome del modulo che ha generato l'errore: KERNELBASE.dll, versione: 10.0.19041.3324, timestamp: 0x6967c799
Codice eccezione: 0xe0434352
Offset errore 0x000000000002cf19
ID processo che ha generato l'errore: 0x2a9c
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d9e5a806646014
Percorso dell'applicazione che ha generato l'errore: C:\Users\murar\AppData\Roaming\Vintagestory\Vintagestory.exe
Percorso del modulo che ha generato l'errore: C:\Windows\System32\KERNELBASE.dll
ID segnalazione: d777e02a-68b5-463e-9cef-2ff2b94bae2f
Nome completo pacchetto che ha generato l'errore: 
ID applicazione relativo al pacchetto che ha generato l'errore:  }
--------------
{ TimeGenerated = 12/09/2023 20:42:01, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
CoreCLR Version: 7.0.1023.36312
.NET Version: 7.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception: Don't know how to instantiate block of class 'BlockCoconutTree' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateBlock(String blockClass) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\ClassRegistry.cs:line 129
   at Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType packet, IWorldAccessor world, ClassRegistry registry) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\Network\BlockTypeNet.cs:line 399
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateBlocks(Block[] blocks, Int32 start, Int32 maxCount) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Startup.cs:line 546
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadBlockTypes() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Startup.cs:line 363
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Startup.cs:line 338
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\TyronThreadPool.cs:line 108
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
 }
--------------
{ TimeGenerated = 12/09/2023 20:35:58, Site = , Source = Application Error, Message = Nome dell'applicazione che ha generato l'errore: Vintagestory.exe, versione: 1.18.10.0, timestamp: 0x64b07659
Nome del modulo che ha generato l'errore: openal32.dll, versione: 1.23.0.0, timestamp: 0x63dd31ad
Codice eccezione: 0x40000015
Offset errore 0x00000000000df046
ID processo che ha generato l'errore: 0x2a50
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d9e5a66bb66270
Percorso dell'applicazione che ha generato l'errore: C:\Users\murar\AppData\Roaming\Vintagestory\Vintagestory.exe
Percorso del modulo che ha generato l'errore: C:\Users\murar\AppData\Roaming\Vintagestory\Lib\openal32.dll
ID segnalazione: 8ab3f12a-608a-4cb1-aef8-88d6f6262a5b
Nome completo pacchetto che ha generato l'errore: 
ID applicazione relativo al pacchetto che ha generato l'errore:  }

**Comment by mirkodun** [comment]
same here

**Comment by Th3Dilli** [comment]
Please try to contact the server owner since it maybe a issue related to a mod since I cant reproduce that without mods.
