### ISSUE TITLE
GAME REFUSES TO LAUNCH CLIENT / / GAME REFUSES TO UPDATE //

### ISSUE THREAD

**Issue by D-Aubigne** [anegostudios/VintageStory-Issues#3107]
### Game Version

1.18.10/12

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Yesterday I got the game downloaded on my pc to play with friends and when I tried playing with them I encounter an issue were it will start up and the menu will work perfectly, but it refuses to launch the game client when trying to join a server *modded or vanilla it doesn't matter* or trying to launch singleplayer, the game just remains in this frozen unanimate state launching client stance after receiving data (sometimes just going flat out unresponsive) like this.

![image](https://github.com/anegostudios/VintageStory-Issues/assets/116299299/e91ff864-77a2-42f8-bfe6-1eef0baee19d)

Tonight, I opened the game to see if it (stupidly enough) went away magically, but the issue persisted; I've already reinstalled the game, wiped it off clean off my hard drive and redownloaded the installer and installed it, yet the issue still persists. Apart from that when I started the game I got the notification to update the VS to the latest version to which 

![image](https://github.com/anegostudios/VintageStory-Issues/assets/116299299/41142b11-0aac-477f-b86a-a3d7c6a580a7)

this happens whenever it reaches either 87% or 100% like in this case.

### How to reproduce

1. Launch the game
2. Launch Singleplayer/Multiplayer
3. (...)

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/116299299/e91ff864-77a2-42f8-bfe6-1eef0baee19d)

![image](https://github.com/anegostudios/VintageStory-Issues/assets/116299299/41142b11-0aac-477f-b86a-a3d7c6a580a7)

### Logs

```Log```

(2 logs included, modded and vanilla)

**------------------------------------------ MODDED LOG:**
Running on 64 bit Windows with 8192 MB RAM
Game Version: v1.18.10 (Stable)
9/20/2023 4:28:43 AM: Critical error occurred
Loaded Mods: hideandfabric@1.3.0, medieval@2.01.26, leadroof@1.3.4, game@1.18.10, carryon@1.6.0, commonlib@2.2.0, cooperativecombat@1.1.1, expandedfoods@1.6.7, fromgoldencombs@1.4.21, sailboat@1.1.0, medievalexpansion@3.10.0, petai@1.8.1, creative@1.18.10, survival@1.18.10, xlib@0.7.4, xmelee@0.0.12, bullseye@2.5.0, feverstonehorses@1.5.0, playercorpse@1.8.0, simplewinddirection@1.0.2, wolftaming@1.8.0, xskills@0.7.5
System.Exception: Don't know how to instantiate item of class 'ExpandedDough' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass) in VintagestoryLib\Common\ClassRegistry.cs:line 273
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType packet, IWorldAccessor world, ClassRegistry registry) in VintagestoryLib\Common\Network\ItemTypeNet.cs:line 19
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(List`1 items, Int32 listSize) in VintagestoryLib\Client\Systems\Startup.cs:line 580
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes() in VintagestoryLib\Client\Systems\Startup.cs:line 392
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in VintagestoryLib\Client\Systems\Startup.cs:line 334
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 108
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 9/20/2023 4:08:50 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2214170192790503688, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.10.0
P3: 64b07659
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6BE8.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1161.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER14BD.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1538.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER15A7.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_38893ed42eb8d1a668828edf5bed1a44a4c7eb_93d687c4_091d576c-3718-44b3-92cd-50b30badb650

Analysis symbol: 
Rechecking for solution: 0
Report Id: 8de79fd8-4d46-4bd0-b540-fbe0c1f0806f
Report Status: 268566528
Hashed bucket: e045985d4f8a18ca4eba500f25894108
Cab Guid: 0 }
--------------
{ TimeGenerated = 9/20/2023 4:07:43 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.10.0, time stamp: 0x64b07659
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x2a6c
Faulting application start time: 0x01d9eb66d99de224
Faulting application path: C:\Users\mar\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\mar\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 8de79fd8-4d46-4bd0-b540-fbe0c1f0806f
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 9/20/2023 3:55:01 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2214170192790503688, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.10.0
P3: 64b07659
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB10A.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB38C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB39C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB3AE.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB3CE.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_38893ed42eb8d1a668828edf5bed1a44a4c7eb_93d687c4_7989b45c-8870-41e1-b7eb-ce239d63deb2

Analysis symbol: 
Rechecking for solution: 0
Report Id: ffb07d24-3079-48e9-881e-139bbff8e980
Report Status: 268566528
Hashed bucket: e045985d4f8a18ca4eba500f25894108
Cab Guid: 0 }

**------------------------------------------ VANILLA LOG:**

Running on 64 bit Windows with 6077 MB RAM
Game Version: v1.18.10 (Stable)
9/20/2023 4:33:39 AM: Critical error occurred
Loaded Mods: hideandfabric@1.3.0, medieval@2.01.26, leadroof@1.3.4, expandedfoods@1.6.7
System.Exception: Don't know how to instantiate item of class 'ItemMagicWand' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass) in VintagestoryLib\Common\ClassRegistry.cs:line 273
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType packet, IWorldAccessor world, ClassRegistry registry) in VintagestoryLib\Common\Network\ItemTypeNet.cs:line 19
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(List`1 items, Int32 listSize) in VintagestoryLib\Client\Systems\Startup.cs:line 580
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes() in VintagestoryLib\Client\Systems\Startup.cs:line 392
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in VintagestoryLib\Client\Systems\Startup.cs:line 334
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 108
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 9/20/2023 4:32:36 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1343159327827012213, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.10.0
P3: 64b07659
P4: KERNELBASE.dll
P5: 10.0.19041.3393
P6: 6b4de7c9
P7: e0434352
P8: 000000000002cf19
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD7E6.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1677.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1743.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1750.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1790.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_e77daa69aebee95687a992133ae6bb5d399ca4_93d687c4_cb0215c4-fe27-4943-8af3-bef5fa58339a

Analysis symbol: 
Rechecking for solution: 0
Report Id: b4f37d12-fe01-4601-94c2-2f510c6d4404
Report Status: 268566528
Hashed bucket: 3b7c31f4cf95fe7662a3dc4ad3e1aa75
Cab Guid: 0 }
--------------
{ TimeGenerated = 9/20/2023 4:32:17 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.10.0, time stamp: 0x64b07659
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3393, time stamp: 0x6b4de7c9
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process id: 0xe40
Faulting application start time: 0x01d9eb6773c7d53d
Faulting application path: C:\Users\mar\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: b4f37d12-fe01-4601-94c2-2f510c6d4404
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 9/20/2023 4:32:13 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
CoreCLR Version: 7.0.1023.36312
.NET Version: 7.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception: Don't know how to instantiate item of class 'ExpandedDough' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\ClassRegistry.cs:line 273
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType packet, IWorldAccessor world, ClassRegistry registry) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\Network\ItemTypeNet.cs:line 19
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(List`1 items, Int32 listSize) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Startup.cs:line 580
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Startup.cs:line 392
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Startup.cs:line 334
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\TyronThreadPool.cs:line 108
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
 }

**Comment by D-Aubigne** [comment]
UPDT:

Manually updated the game, issue still persists.

**Comment by Th3Dilli** [comment]
The issues with the auto updating is resolved since 1.18.11

for the error not able to join it seems to be a mod issue
`System.Exception: Don't know how to instantiate item of class 'ExpandedDough' did you forget to register a mapping?`
going by the log it should be a item from ExpandedFoods please contact the server owner if there is a new version available or the author.
