### ISSUE TITLE
Crash on single player server start

### ISSUE THREAD

**Issue by Jimzawy** [anegostudios/VintageStory-Issues#3113]
### Game Version

v1.18.13 (Stable)

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Crash on single player server start

### How to reproduce

Start the game, start the single player server

### Logs

```Log```Running on 64 bit Windows with 16317 MB RAM
Game Version: v1.18.13 (Stable)
9/24/2023 10:22:39 PM: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.15, arrowrecovery@1.0.0, betterruins@0.2.2, bushmeat_meals@1.0.7, buzzwords@1.3.0, composter@1.0.5, extrainfo@1.5.3, fancysky@1.0.6, caninae@0.1.1, capreolinae@1.0.4, pantherinae@1.0.7, foundrymod@1.0.0, furniturelibrary@1.0.9, HangingOilLamps@1.0.1, millwright@1.0.7, packeddirtpaths@1.1.0, TA_plainsandvalleys@1.0.5, primitivesurvival@3.2.7, RecycleSacksJimzawy@0.0.1, dzsalvageplus@1.0.1, she1fish@1.1.0, spyglass@0.4.5, sticksfromfirewood@1.0.0, visibleore@1.0.1, vgaas@1.0.1, game@1.18.13, alloycalculator@1.0.0, animalcages@2.2.0, butchering@1.0.9, canbeignited@1.1.0, carryon@1.5.0, commonlib@2.2.0, danatweaks@1.1.0, dropresinanyway@1.0.2, expandedfoods@1.6.7, fieldsofsalt@1.1.2, hudclock@3.3.0, sailboat@1.1.0, mapautocenter@1.1.1, morepiles@1.4.3, nohands@0.1.1, petai@1.8.1, claywheel@1.1.0, prospectorinfo@4.3.0, stillnecessaries@1.0.1, storageoptions@1.0.0, vanvar@3.2.2, creative@1.18.13, survival@1.18.13, vsvillage@0.7.3, metalrecovery@0.1.19-pre.1, bullseye@2.5.0-rc.1, cats@1.8.0, feverstonehorses@1.5.0, moreropeplease@1.0.0, onestick@1.0.1, playercorpse@1.8.0, wolftaming@1.8.0, xinvtweaks@1.5.7
System.Exception: SendServerAssets failed. See log files.
   at Vintagestory.Server.ServerMain.BuildServerAssetsPacket() in VintagestoryLib\Server\ServerMainNetworking.cs:line 1078
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass13_0.<QueueLongDurationTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 122
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 9/24/2023 10:21:06 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1237268411382838093, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.13.0
P3: 64b07659
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREE4D.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF33F.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF350.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF35E.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF3AD.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_2ec7e698813894950b9b93e32146592f2344b2_ae564f4f_52db67c1-46ca-439f-8c00-046a7773260b

Analysis symbol: 
Rechecking for solution: 0
Report Id: 3929109e-1ee9-451b-a0e0-954c34dac17e
Report Status: 268566528
Hashed bucket: 2245dcdc53ace9ebc12ba9109849334d
Cab Guid: 0 }
--------------
{ TimeGenerated = 9/24/2023 10:21:03 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.13.0, time stamp: 0x64b07659
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x1878
Faulting application start time: 0x01d9ef1c0fcce429
Faulting application path: C:\Users\Jimzawy\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Jimzawy\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 3929109e-1ee9-451b-a0e0-954c34dac17e
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 9/24/2023 10:20:52 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
CoreCLR Version: 7.0.1123.42427
.NET Version: 7.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception: SendServerAssets failed. See log files.
   at Vintagestory.Server.ServerMain.BuildServerAssetsPacket() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMainNetworking.cs:line 1078
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass13_0.<QueueLongDurationTask>b__0(Object a) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\TyronThreadPool.cs:line 122
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
 }

**Comment by Craluminum2413** [comment]
Closing due to inactivity
