### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by Cainsdreams** [anegostudios/VintageStory-Issues#3130]
Running on 64 bit Windows with 8138 MB RAM
Game Version: v1.18.13 (Stable)
03/10/2023 20:01:12: Critical error occurred in the following mod: campaigncartographer@3.1.2
Loaded Mods: nailsmold@1.0.1, primitivesurvival@3.2.9, game@1.18.13, zoombutton@1.1.0, betterfirepit@1.1.1, carryon@1.6.0, crateful@1.0.3, creative@1.18.13, survival@1.18.13, workbenchexpansion@1.7.0, campaigncartographer@3.1.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at ApacheTech.Common.Extensions.Harmony.HarmonyReflectionExtensions.GetField[T](Object instance, String fieldName)
   at ApacheTech.VintageMods.FluentChatCommands.Extensions.ChatCommandsApiExtensions.UnregisterCommand(ICoreClientAPI capi, String commandName)
   at ApacheTech.VintageMods.FluentChatCommands.Extensions.ChatCommandsApiExtensions.<>c__DisplayClass6_0.<UnregisterCommand>b__0(ICoreClientAPI c)
   at ApacheTech.VintageMods.FluentChatCommands.Extensions.SideAgnosticApiExtensions.RunOneOf(ICoreAPI api, Action`1 clientAction, Action`1 serverAction)
   at ApacheTech.VintageMods.FluentChatCommands.Extensions.ChatCommandsApiExtensions.UnregisterCommand(ICoreAPI api, String commandName)
   at ApacheTech.VintageMods.FluentChatCommands.FluentChat.UnregisterCommand(String commandName, ICoreAPI api)
   at ApacheTech.VintageMods.FluentChatCommands.FluentChat.ClearCommands(ICoreAPI api)
   at ApacheTech.VintageMods.CampaignCartographer.Program.Dispose()
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerLeftWorld() in VintagestoryLib\Client\API\ClientEventAPI.cs:line 358
   at Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected) in VintagestoryLib\Client\ClientMain.cs:line 2542
   at Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnLeaveWorld() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogEscapeMenu.cs:line 322
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 304
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 293
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 564
   at Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogEscapeMenu.cs:line 387
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 415
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1849
   at Vintagestory.Client.GuiScreenRunningGame.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 349
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 209
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 03/10/2023 19:54:24, Site = , Source = Windows Error Reporting, Message = Fault bucket 1237268411382838093, type 4
Event Name: APPCRASH
Response: Nie je k dispozícii
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.13.0
P3: 64b07659
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3882.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_2ec7e698813894950b9b93e32146592f2344b2_ae564f4f_c3dc55f9-db17-4b95-9c4c-85a365a07443

Analysis symbol: 
Rechecking for solution: 0
Report Id: ea4101b7-e68d-4bde-afe8-e7ebddbb5736
Report Status: 268566528
Hashed bucket: 2245dcdc53ace9ebc12ba9109849334d
Cab Guid: 0 }
--------------
{ TimeGenerated = 03/10/2023 19:54:23, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.13.0
P3: 64b07659
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_2ec7e698813894950b9b93e32146592f2344b2_ae564f4f_c3dc55f9-db17-4b95-9c4c-85a365a07443

Analysis symbol: 
Rechecking for solution: 0
Report Id: ea4101b7-e68d-4bde-afe8-e7ebddbb5736
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 03/10/2023 19:54:20, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.13.0, time stamp: 0x64b07659
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x2288
Faulting application start time: 0x01d9f62262d769ce
Faulting application path: F:\Vintagestory\Vintagestory.exe
Faulting module path: F:\Vintagestory\Lib\openal32.dll
Report ID: ea4101b7-e68d-4bde-afe8-e7ebddbb5736
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Saricane** [comment]
Please try to disable all your mods first before retrying. If the game still crashes, please add a textual description of the context of the crash, how to reproduce it, and all element that could help the devs (screenshots ...)
Thank you.

**Comment by PapuutekAPT** [comment]
Hello,
I think a have the same issue.
It happens randomly, in my case on self-hosted server without mods, but I think only in 1.18.14. I didn't experience this error in previous versions.

**Comment by Th3Dilli** [comment]
this seems related to `campaigncartographer`

maybe @ApacheTech can take a look at it

**Comment by ApacheTech** [comment]
Campaign Cartographer has not been updated since game version 1.16. I'm not surprised it crashed. The mod will not be updated for a while, yet. Likely 1.19, maybe 1.20.
