### ISSUE TITLE
Crash from swinging a modded sword

### ISSUE THREAD

**Issue by BriskMan7** [anegostudios/VintageStory-Issues#3131]
### Game Version

v1.18.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Running on 64 bit Windows with 16270 MB RAM
Game Version: v1.18.8 (Stable)
2023-10-04 11:05:39 PM: Critical error occurred in the following mod: weaponpacka@1.3.1
Loaded Mods: weaponpacka@1.3.1, reducedarmornegatives@1.0.4, game@1.18.8, bodyheatbar@1.0.1, coinage@1.6.1, loreweapons@1.0.1, prospecttogether@1.1.0, creative@1.18.8, survival@1.18.8, maltiezfirearms@0.1.11
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.ModelTransform.Translation'.
   at CustomWeaponSpeed.NormalSwordChargeNone.OnHeldAttackStep(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSelection, EntitySelection entitySel)
   at Vintagestory.API.Common.CollectibleObject.OnHeldUseStep(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1044
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 310
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 165
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 59
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 796
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 712
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 75
   at OpenTK.Windowing.Desktop.GameWindow.DispatchRenderFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 312
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2023-10-04 11:02:37 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1273209627708249444, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.8.0
P3: 6492041a
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB997.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_8de098f737c744fcb2cfb2449b6f09668c35b_9d23d9f5_ee4518cb-b973-4715-b447-1a49584ea2ec

Analysis symbol: 
Rechecking for solution: 0
Report Id: 36c0fd03-c907-4fa5-86ae-cd03f6e60ce8
Report Status: 268566528
Hashed bucket: 42c222969642167ad1ab596920285564
Cab Guid: 0 }
--------------
{ TimeGenerated = 2023-10-04 11:02:32 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.8.0
P3: 6492041a
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_8de098f737c744fcb2cfb2449b6f09668c35b_9d23d9f5_ee4518cb-b973-4715-b447-1a49584ea2ec

Analysis symbol: 
Rechecking for solution: 0
Report Id: 36c0fd03-c907-4fa5-86ae-cd03f6e60ce8
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 2023-10-04 11:02:24 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.8.0, time stamp: 0x6492041a
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x570
Faulting application start time: 0x01d9f73f58c4fd57
Faulting application path: C:\Users\melch\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\melch\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report ID: 36c0fd03-c907-4fa5-86ae-cd03f6e60ce8
Faulting package full name: 
Faulting package-relative application ID:  }

### How to reproduce

using the "WeaponPack Alpha" mod I used the spatha and I swing the sword and it crashed

### Logs

```Log```

**Comment by Craluminum2413** [comment]
It is caused by mod, not the game itself
