### ISSUE TITLE
ArgumentNullException

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#3138]
### Game Version

1.18.14

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

From the console, no clue why and if its even a vanilla problem.

### Logs

```[Fatal] System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at Vintagestory.Common.BlockTypeNet.PackSetDecorsList(WorldChunk chunk, Int64 chunkIndex, IBlockAccessor blockAccessor) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\Network\BlockTypeNet.cs:line 789
   at Vintagestory.Server.ServerMain.SendSetDecorsPackets(List`1 positions) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMainNetworking.cs:line 741
   at Vintagestory.Server.ServerSystemBlockSimulation.HandleDirtyAndUpdatedBlocks() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 852
   at Vintagestory.Server.ServerSystemBlockSimulation.UpdateEvery100ms(Single t1) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 772
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\EventManager.cs:line 59
   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerEventManager.cs:line 124
   at Vintagestory.Server.ServerMain.Process() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 881```

**Comment by Craluminum2413** [comment]
Does it still happen? If so, could you send all logs?

**Comment by Craluminum2413** [comment]
Closing due to inactivity
