### ISSUE TITLE
Vintage story crash please help

### ISSUE THREAD

**Issue by Kzistu** [anegostudios/VintageStory-Issues#3139]
Running on 64 bit Windows with 32653 MB RAM
Game Version: v1.18.14 (Stable)
08/10/2023 15:53:52: Critical error occurred in the following mod: hudclock@2.8.0
Loaded Mods: bettercrates@1.5.3, extrachests@1.6.2, game@1.18.14, carryon@0.10.3, farmlanddropssoil@1.4.0, hudclock@2.8.0, prospectorinfo@4.1.2, creative@1.18.14, survival@1.18.14, workbenchexpansion@1.5.1, campaigncartographer@3.1.2
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.BitmapExternal.bmp'.
   at hudclock.src.ui.StormDialog.OnDraw(Context ctx, ImageSurface surface, ElementBounds currentBounds)
   at Vintagestory.API.Client.GuiElementCustomDraw.ComposeElements(Context ctxStatic, ImageSurface surfaceStatic) in VintagestoryApi\Client\UI\Elements\Impl\Static\GuiElementCustomDraw.cs:line 34
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 396
   at hudclock.src.ui.StormDialog.DefineGuiComposer() in D:\development\VintageStoryMods\solution\Mods\hudclock\src\ui\StormDialog.cs:line 198
   at hudclock.src.ui.StormDialog.Build() in D:\development\VintageStoryMods\solution\Mods\hudclock\src\ui\StormDialog.cs:line 38
   at hudclock.src.busineslogic.StormDialogController..ctor(ICoreClientAPI clientApi, ClockModSettingsController settings) in D:\development\VintageStoryMods\solution\Mods\hudclock\src\busineslogic\StormDialogController.cs:line 30
   at hudlock.src.HUDClockMod.PlayerReady(EnumHandling& handling) in D:\development\VintageStoryMods\solution\Mods\hudclock\src\HUDClockMod.cs:line 42
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerIsPlayerReady() in VintagestoryLib\Client\API\ClientEventAPI.cs:line 379
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 316
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 452
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 446
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 322
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
The problem is in Hud clock mod
