### ISSUE TITLE
Player exiting boat sometimes causes NullReferenceExceptions

### ISSUE THREAD

**Issue by Unrealomega** [anegostudios/VintageStory-Issues#3145]
### Game Version

1.18.15

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Player exiting a boat has a chance to cause nearby players to sometime crash. This does not appear to affect everyone in the immediate area. I was also alt-tabbed out of the window at the time.

### How to reproduce

This is assumed and to be determined if this is the case.

1. Be alt-tabbed while someone is in a boat.
2. Have the person in the boat exit.

### Logs

```
Running on 64 bit Windows with 32694 MB RAM
Game Version: v1.18.15 (Stable)
10/12/2023 11:42:35 AM: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.15, game@1.18.15, commonlib@2.2.0, expandedfoods@1.6.7, hudclock@3.3.0, creative@1.18.15, survival@1.18.15, koboldplayermodel@1.1.0, playercorpse@1.8.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBoatSeat.DidUnmount(EntityAgent entityAgent) in VSSurvivalMod\Systems\Boats\BoatSeat.cs:line 115
   at Vintagestory.API.Common.EntityAgent.TryUnmount() in VintagestoryApi\Common\Entity\EntityAgent.cs:line 254
   at Vintagestory.API.Common.EntityAgent.updateMountedState() in VintagestoryApi\Common\Entity\EntityAgent.cs:line 204
   at Vintagestory.API.Datastructures.SyncedTreeAttribute.FromBytes(BinaryReader stream) in VintagestoryApi\Datastructures\AttributeTree\Other\SyncedTreeAttribute.cs:line 254
   at Vintagestory.API.Common.Entities.Entity.FromBytes(BinaryReader reader, Boolean isSync) in VintagestoryApi\Common\Entity\Entity.cs:line 1599
   at Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 680
   at Vintagestory.API.Common.EntityPlayer.FromBytes(BinaryReader reader, Boolean forClient) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 1316
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityAttributesPacket(Packet_EntityAttributes packet) in VintagestoryLib\Client\Systems\Entities.cs:line 447
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityBulkAttributesPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\Entities.cs:line 379
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10/11/2023 4:36:48 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER55B7.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5D1B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5D2C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5D39.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5D59.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_8d646f18-bf7f-40f1-a7aa-64220b091661

Analysis symbol: 
Rechecking for solution: 0
Report Id: 96bd3aae-b192-4a89-bc22-fdd053903167
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/11/2023 4:36:44 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x2010
Faulting application start time: 0x01d9fc3ffdcf72a3
Faulting application path: C:\Users\Pickra\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Pickra\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 96bd3aae-b192-4a89-bc22-fdd053903167
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 10/10/2023 10:59:46 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER96AD.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9D26.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9D46.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9D44.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9D64.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_f42158b1-2e00-4681-9564-73f9f7378bc1

Analysis symbol: 
Rechecking for solution: 0
Report Id: 23664409-fb3a-4361-818d-73abce6ec7dd
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
