### ISSUE TITLE
game crash when throwing a spear and game try to pull one from crafting output

### ISSUE THREAD

**Issue by jal21** [anegostudios/VintageStory-Issues#3150]
### Game Version

v1.18.15

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I was making a mass amount of spears for a rust storm, so i had some ready to craft in my crafting window. I throw all of the ones that I had in my inventory and the game crash.

### How to reproduce

whats needed for the crash: immersive mouse mode on, 1 spear, 1 stick, 1 spear head
1. place stick and spear head in crafting window to make a spear
2. throw spear 
3. game crashes

### Logs

Running on 64 bit Windows with 32694 MB RAM
Game Version: v1.18.15 (Stable)
10/13/2023 12:21:54 AM: Critical error occurred
Loaded Mods: game@1.18.15, creative@1.18.15, survival@1.18.15
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.ItemSlotCraftingOutput.triggerEvent(ItemStack craftedStack, Int32 moved, IPlayer actingPlayer) in VintagestoryLib\Common\GameContent\Inventory\ItemSlotCraftingOutput.cs:line 72
   at Vintagestory.Common.ItemSlotCraftingOutput.TryPutInto(ItemSlot sinkSlot, ItemStackMoveOperation& op) in VintagestoryLib\Common\GameContent\Inventory\ItemSlotCraftingOutput.cs:line 63
   at Vintagestory.API.Common.ItemSlot.TryPutInto(IWorldAccessor world, ItemSlot sinkSlot, Int32 quantity) in VintagestoryApi\Common\Inventory\ItemSlot.cs:line 176
   at Vintagestory.API.Common.CollectibleObject.<>c__DisplayClass79_0.<RefillSlotIfEmpty>b__0(ItemSlot invslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 843
   at Vintagestory.API.Common.EntityPlayer.WalkInventory(OnInventorySlot handler) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 1203
   at Vintagestory.API.Common.CollectibleObject.RefillSlotIfEmpty(ItemSlot slot, EntityAgent byEntity, ActionConsumable`1 matcher) in VintagestoryApi\Common\Collectible\Collectible.cs:line 834
   at Vintagestory.GameContent.ItemSpear.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel) in VSSurvivalMod\Item\ItemSpear.cs:line 125
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 332
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 165
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 59
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 796
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 712
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10/13/2023 12:13:27 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2104807058015840095, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.14.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER885D.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8A04.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8A14.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8A12.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8A33.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_89f5a4e45df3a76ed03cdc7d2338fc9a85c43d64_e6f85633_62f5609d-a619-4974-8dc3-1fae920f1f91

Analysis symbol: 
Rechecking for solution: 0
Report Id: 97ad2c4c-0b6d-45d3-8551-725dde865529
Report Status: 268566528
Hashed bucket: e910dae5c6c8120b1d35c6de15c4e75f
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/13/2023 12:13:26 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.14.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x4d10
Faulting application start time: 0x01d9fda4b94898e1
Faulting application path: C:\Users\selfh\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\selfh\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 97ad2c4c-0b6d-45d3-8551-725dde865529
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 10/12/2023 11:43:10 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2104807058015840095, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.14.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC629.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCB3B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCB4C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCB4A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCB6A.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_89f5a4e45df3a76ed03cdc7d2338fc9a85c43d64_e6f85633_f1f182c6-5991-48e8-8324-d4371df3694f

Analysis symbol: 
Rechecking for solution: 0
Report Id: 8e813481-1f8b-400b-8d8f-1ae0180fdfa8
Report Status: 268566528
Hashed bucket: e910dae5c6c8120b1d35c6de15c4e75f
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
Closing due to inactivity
