### ISSUE TITLE
Can listen music with cylinder and  the "phonographe"

### ISSUE THREAD

**Issue by LyriellePepeste** [anegostudios/VintageStory-Issues#3151]
The error message. This crash append when i try play musig whith a cylinder and the phonograph
```
Running on 64 bit Windows with 8057 MB RAM
Game Version: v1.18.15 (Stable)
13/10/2023 19:47:00: Critical error occurred
Loaded Mods: backpackpackplus@1.0.3, FarmSurvival@1.3.0, moreenemyloot@1.1.0, primitivesurvival@3.2.1, ropebucket@1.0.0, game@1.18.15, wildcrafttrees@1.1.9, lessbears@1.0.0, petai@1.7.7, creative@1.18.15, survival@1.18.15, cats@1.7.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityResonator.<>c__DisplayClass20_0.<onTrackLoaded>b__0() in VSSurvivalMod\BlockEntity\BEResonator.cs:line 162
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 13/10/2023 16:53:13, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.18.13.0, horodatage : 0x64b07659
Nom du module défaillant : openal32.dll, version : 1.23.0.0, horodatage : 0x63dd31ad
Code d’exception : 0x40000015
Décalage d’erreur : 0x00000000000df046
ID du processus défaillant : 0x2014
Heure de début de l’application défaillante : 0x01d9fde4d3e661a3
Chemin d’accès de l’application défaillante : C:\Users\GILLES\AppData\Roaming\Vintagestory\Vintagestory.exe
Chemin d’accès du module défaillant: C:\Users\GILLES\AppData\Roaming\Vintagestory\Lib\openal32.dll
ID de rapport : f830b483-426b-4dcd-ba19-21115dc0be04
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }
--------------
{ TimeGenerated = 03/10/2023 17:52:58, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.18.13.0, horodatage : 0x64b07659
Nom du module défaillant : openal32.dll, version : 1.23.0.0, horodatage : 0x63dd31ad
Code d’exception : 0x40000015
Décalage d’erreur : 0x00000000000df046
ID du processus défaillant : 0x1420
Heure de début de l’application défaillante : 0x01d9f611a7121c79
Chemin d’accès de l’application défaillante : C:\Users\GILLES\AppData\Roaming\Vintagestory\Vintagestory.exe
Chemin d’accès du module défaillant: C:\Users\GILLES\AppData\Roaming\Vintagestory\Lib\openal32.dll
ID de rapport : 007bc5a2-c78c-4288-a872-feb3adbe1bdb
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }
--------------
{ TimeGenerated = 03/10/2023 17:49:57, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.18.10.0, horodatage : 0x64b07659
Nom du module défaillant : openal32.dll, version : 1.23.0.0, horodatage : 0x63dd31ad
Code d’exception : 0x40000015
Décalage d’erreur : 0x00000000000df046
ID du processus défaillant : 0x21f8
Heure de début de l’application défaillante : 0x01d9f61118225ddd
Chemin d’accès de l’application défaillante : C:\Users\GILLES\AppData\Roaming\Vintagestory\Vintagestory.exe
Chemin d’accès du module défaillant: C:\Users\GILLES\AppData\Roaming\Vintagestory\Lib\openal32.dll
ID de rapport : c0c0b6ec-3820-4fd6-9b8a-c5e91136dffe
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
