### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by cedricponcet** [anegostudios/VintageStory-Issues#3156]
### Game Version

1.18.15

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

the game crash when I open "Your game server" tab on the main menu.

### How to reproduce

Open game, click "your game server" tab, crash.

### Logs

```Log```
Running on 64 bit Windows with 32682 MB RAM
Game Version: v1.18.15 (Stable)
15/10/2023 15:34:50: Critical error occurred
Loaded Mods: game@1.18.15, creative@1.18.15, survival@1.18.15
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.Client.GuiElementDropDown.ComposeCurrentValue() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementDropDown.cs:line 241
   at Vintagestory.API.Client.GuiElementDropDown.ComposeDynamicElements() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementDropDown.cs:line 233
   at Vintagestory.API.Client.GuiElementDropDown.ComposeElements(Context ctx, ImageSurface surface) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementDropDown.cs:line 149
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 396
   at Vintagestory.Client.GuiScreenServerDashboard.screenSelectRegion(GameServerStatus status) in VintagestoryLib\Client\MainMenu\Screens\HostedServer\GuiScreenServerDashboard.cs:line 728
   at Vintagestory.Client.GuiScreenServerDashboard.onStatusReady(EnumAuthServerResponse reqStatus, GameServerStatus gameServerStatus) in VintagestoryLib\Client\MainMenu\Screens\HostedServer\GuiScreenServerDashboard.cs:line 57
   at Vintagestory.Client.Util.ServerCtrlBackendInterface.<>c__DisplayClass8_0.<GetStatus>b__0(EnumAuthServerResponse status, GameServerStatus response) in VintagestoryLib\Client\Util\ServerCtrlBackend\ServerCtrlBackendInterface.cs:line 121
   at Vintagestory.Client.Util.ServerCtrlBackendInterface.<>c__DisplayClass13_1`1.<runAction>b__1() in VintagestoryLib\Client\Util\ServerCtrlBackend\ServerCtrlBackendInterface.cs:line 203
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 15/10/2023 15:34:18, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.18.15.0, horodatage : 0x64e841c5
Nom du module défaillant : openal32.dll, version : 1.23.0.0, horodatage : 0x63dd31ad
Code d’exception : 0x40000015
Décalage d’erreur : 0x00000000000df046
ID du processus défaillant : 0x5680
Heure de début de l’application défaillante : 0x01d9ff6c46c334f3
Chemin d’accès de l’application défaillante : D:\jeux\Vintagestory\Vintagestory.exe
Chemin d’accès du module défaillant: D:\jeux\Vintagestory\Lib\openal32.dll
ID de rapport : c913d4ec-5a5d-4d89-af1c-c53882d4aee8
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }
--------------
{ TimeGenerated = 15/10/2023 15:34:08, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.18.15.0, horodatage : 0x64e841c5
Nom du module défaillant : openal32.dll, version : 1.23.0.0, horodatage : 0x63dd31ad
Code d’exception : 0x40000015
Décalage d’erreur : 0x00000000000df046
ID du processus défaillant : 0x1e84
Heure de début de l’application défaillante : 0x01d9ff6c3fbae3f4
Chemin d’accès de l’application défaillante : D:\jeux\Vintagestory\Vintagestory.exe
Chemin d’accès du module défaillant: D:\jeux\Vintagestory\Lib\openal32.dll
ID de rapport : 2b60999c-b13b-4f3c-91c7-2eb059e848c9
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }
--------------
{ TimeGenerated = 15/10/2023 15:33:55, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.18.15.0, horodatage : 0x64e841c5
Nom du module défaillant : openal32.dll, version : 1.23.0.0, horodatage : 0x63dd31ad
Code d’exception : 0x40000015
Décalage d’erreur : 0x00000000000df046
ID du processus défaillant : 0x2124
Heure de début de l’application défaillante : 0x01d9ff6c0af34a7e
Chemin d’accès de l’application défaillante : D:\jeux\Vintagestory\Vintagestory.exe
Chemin d’accès du module défaillant: D:\jeux\Vintagestory\Lib\openal32.dll
ID de rapport : 8c8c3144-81fe-4bd2-96de-21f41d49cedb
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }

**Comment by cedricponcet** [comment]
Tried to reinstall the game but the problem is still there.
