### ISSUE TITLE
Game crashes on server dashboard launch

### ISSUE THREAD

**Issue by osorioricardo** [anegostudios/VintageStory-Issues#3157]
### Game Version

v1.18.15

### Platform

None

### Modded

None

### SP/MP

None

### Description

When trying to open the server hosting dashboard from the game, it crashes and gives me an error.

### How to reproduce

1. Open game
2. Click on Server Dashboard option from main menu
3. Crashes, closes and opens crash reporter

### Logs

Running on 64 bit Windows with 31892 MB RAM
Game Version: v1.18.15 (Stable)
10/15/2023 10:52:00 AM: Critical error occurred
Loaded Mods: game@1.18.15, creative@1.18.15, survival@1.18.15
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.Client.GuiElementDropDown.ComposeCurrentValue() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementDropDown.cs:line 241
   at Vintagestory.API.Client.GuiElementDropDown.ComposeDynamicElements() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementDropDown.cs:line 233
   at Vintagestory.API.Client.GuiElementDropDown.ComposeElements(Context ctx, ImageSurface surface) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementDropDown.cs:line 149
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 396
   at Vintagestory.Client.GuiScreenServerDashboard.screenSelectRegion(GameServerStatus status) in VintagestoryLib\Client\MainMenu\Screens\HostedServer\GuiScreenServerDashboard.cs:line 728
   at Vintagestory.Client.GuiScreenServerDashboard.onStatusReady(EnumAuthServerResponse reqStatus, GameServerStatus gameServerStatus) in VintagestoryLib\Client\MainMenu\Screens\HostedServer\GuiScreenServerDashboard.cs:line 57
   at Vintagestory.Client.Util.ServerCtrlBackendInterface.<>c__DisplayClass8_0.<GetStatus>b__0(EnumAuthServerResponse status, GameServerStatus response) in VintagestoryLib\Client\Util\ServerCtrlBackend\ServerCtrlBackendInterface.cs:line 121
   at Vintagestory.Client.Util.ServerCtrlBackendInterface.<>c__DisplayClass13_1`1.<runAction>b__1() in VintagestoryLib\Client\Util\ServerCtrlBackend\ServerCtrlBackendInterface.cs:line 203
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10/15/2023 10:51:20 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0faa659e-e094-4651-8591-5a3210468d7c.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ddea130f-92fa-4989-8034-e95204c8b03a.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.3118072a-6512-46cf-8d41-57f4cc94a0b0.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f8a10bf6-c09b-45d2-a796-c3be6f767256.tmp.txt
\\?\C:\Users\Chrono\AppData\Local\Temp\WER.da460c6c-6af5-467f-b363-d1a8d52cbb01.tmp.appcompat.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ee90deb1-b44d-44d7-8050-d0fbfabe19cc.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_a1d57cb7-19f5-4fb4-8f77-fd4cc903a50b

Analysis symbol: 
Rechecking for solution: 0
Report Id: d8b5465c-858d-407c-aa3b-e01741d62c93
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/15/2023 10:51:19 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0faa659e-e094-4651-8591-5a3210468d7c.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ddea130f-92fa-4989-8034-e95204c8b03a.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.3118072a-6512-46cf-8d41-57f4cc94a0b0.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f8a10bf6-c09b-45d2-a796-c3be6f767256.tmp.txt
\\?\C:\Users\Chrono\AppData\Local\Temp\WER.da460c6c-6af5-467f-b363-d1a8d52cbb01.tmp.appcompat.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ee90deb1-b44d-44d7-8050-d0fbfabe19cc.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_cab_a1d57cb7-19f5-4fb4-8f77-fd4cc903a50b

Analysis symbol: 
Rechecking for solution: 0
Report Id: d8b5465c-858d-407c-aa3b-e01741d62c93
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/15/2023 10:51:18 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x5368
Faulting application start time: 0x0x1d9ff768e790966
Faulting application path: C:\Users\Chrono\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Chrono\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: d8b5465c-858d-407c-aa3b-e01741d62c93
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Closing due to inactivity

**Comment by Craluminum2413** [comment]
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/3158
