### ISSUE TITLE
Game crashes when selecting 'Your Game Server' 

### ISSUE THREAD

**Issue by bbenjem** [anegostudios/VintageStory-Issues#3158]
### Game Version

v1.18.15

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Game crashing when selecting 'Your game server' for newly opened server.

### How to reproduce

1. Select 'Vintage Story' from desktop
2. Select 'Your game Server'

### Screenshots

![Screenshot 2023-10-15 171311](https://github.com/anegostudios/VintageStory-Issues/assets/147998500/764c04d0-cec8-402c-b97d-35a4118a1ab2)

### Logs
```
Running on 64 bit Windows with 16299 MB RAM
Game Version: v1.18.15 (Stable)
15/10/2023 17:12:12: Critical error occurred
Loaded Mods: game@1.18.15, creative@1.18.15, survival@1.18.15
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.Client.GuiElementDropDown.ComposeCurrentValue() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementDropDown.cs:line 241
   at Vintagestory.API.Client.GuiElementDropDown.ComposeDynamicElements() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementDropDown.cs:line 233
   at Vintagestory.API.Client.GuiElementDropDown.ComposeElements(Context ctx, ImageSurface surface) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementDropDown.cs:line 149
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 396
   at Vintagestory.Client.GuiScreenServerDashboard.screenSelectRegion(GameServerStatus status) in VintagestoryLib\Client\MainMenu\Screens\HostedServer\GuiScreenServerDashboard.cs:line 728
   at Vintagestory.Client.GuiScreenServerDashboard.onStatusReady(EnumAuthServerResponse reqStatus, GameServerStatus gameServerStatus) in VintagestoryLib\Client\MainMenu\Screens\HostedServer\GuiScreenServerDashboard.cs:line 57
   at Vintagestory.Client.Util.ServerCtrlBackendInterface.<>c__DisplayClass8_0.<GetStatus>b__0(EnumAuthServerResponse status, GameServerStatus response) in VintagestoryLib\Client\Util\ServerCtrlBackend\ServerCtrlBackendInterface.cs:line 121
   at Vintagestory.Client.Util.ServerCtrlBackendInterface.<>c__DisplayClass13_1`1.<runAction>b__1() in VintagestoryLib\Client\Util\ServerCtrlBackend\ServerCtrlBackendInterface.cs:line 203
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by MikeSmeuMare** [comment]
I encounter the same issue.

**Comment by Craluminum2413** [comment]
Closing due to inactivity
