### ISSUE TITLE
Game crashes does not load up

### ISSUE THREAD

**Issue by Catnip12** [anegostudios/VintageStory-Issues#3162]
### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

This happened when I tried runnning  it in vanilla as well and I even installed the Visual C+++ thing listed, because I thought it would fix the issue. I do not under stand the game code but I will try to drop it in below.

Running on 64 bit Windows with 15307 MB RAM
Game Version: v1.18.15 (Stable)
10/20/2023 11:08:51 AM: Critical error occurred in the following mod: hudclock@2.8.0
Loaded Mods: moreundergarments@0.0.1, game@1.18.15, carryon@1.6.0, hudclock@2.8.0, prospecttogether@1.2.4, SimpleMobFootStepsUpdate@1.0.1, statushud@1.4.3, temporalstormtimer@1.1.1, creative@1.18.15, survival@1.18.15, xlib@0.6.14, xskills@0.6.14
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.BitmapExternal.bmp'.
   at hudclock.src.ui.StormDialog.OnDraw(Context ctx, ImageSurface surface, ElementBounds currentBounds)
   at Vintagestory.API.Client.GuiElementCustomDraw.ComposeElements(Context ctxStatic, ImageSurface surfaceStatic) in VintagestoryApi\Client\UI\Elements\Impl\Static\GuiElementCustomDraw.cs:line 34
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 431
   at hudclock.src.ui.StormDialog.DefineGuiComposer() in D:\development\VintageStoryMods\solution\Mods\hudclock\src\ui\StormDialog.cs:line 198
   at hudclock.src.ui.StormDialog.Build() in D:\development\VintageStoryMods\solution\Mods\hudclock\src\ui\StormDialog.cs:line 38
   at hudclock.src.busineslogic.StormDialogController..ctor(ICoreClientAPI clientApi, ClockModSettingsController settings) in D:\development\VintageStoryMods\solution\Mods\hudclock\src\busineslogic\StormDialogController.cs:line 30
   at hudlock.src.HUDClockMod.PlayerReady(EnumHandling& handling) in D:\development\VintageStoryMods\solution\Mods\hudclock\src\HUDClockMod.cs:line 42
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerIsPlayerReady() in VintagestoryLib\Client\API\ClientEventAPI.cs:line 379
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 316
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 452
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 446
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 322
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 9/30/2023 12:03:30 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1237268411382838093, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.13.0
P3: 64b07659
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREF9.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER196A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER197B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1988.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER19B8.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_2ec7e698813894950b9b93e32146592f2344b2_ae564f4f_4250477b-e497-4855-85a4-8c4a38e80a5d

Analysis symbol: 
Rechecking for solution: 0
Report Id: ace5246d-6908-40e1-b016-3eb03a927e22
Report Status: 268566528
Hashed bucket: 2245dcdc53ace9ebc12ba9109849334d
Cab Guid: 0 }
--------------
{ TimeGenerated = 9/30/2023 12:03:24 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.13.0, time stamp: 0x64b07659
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x2178
Faulting application start time: 0x01d9f35ac5ec2a2d
Faulting application path: C:\Users\flyingCatPhillips PC\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\flyingCatPhillips PC\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: ace5246d-6908-40e1-b016-3eb03a927e22
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 9/29/2023 11:24:28 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1237268411382838093, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.13.0
P3: 64b07659
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5B05.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5E33.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5E43.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5E61.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5E90.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_2ec7e698813894950b9b93e32146592f2344b2_ae564f4f_bca3b891-ecf5-4070-bdab-c85d8f0009e2

Analysis symbol: 
Rechecking for solution: 0
Report Id: 7ad13f67-87cf-4351-8473-a19b27413006
Report Status: 268566528
Hashed bucket: 2245dcdc53ace9ebc12ba9109849334d
Cab Guid: 0 }

### How to reproduce

I don't know I just tried loading up the world I was playing or create a new one; it happened either way.

### Logs

```Log```

For some reason windows cannot find my log folder for this version.

**Comment by Craluminum2413** [comment]
Issue caused by hud clock mod

**Comment by Catnip12** [comment]
how can I fix the game to play it?

**Comment by Craluminum2413** [comment]
> how can I fix the game to play it?

Remove hud clock mod

**Comment by Craluminum2413** [comment]
It should be somewhere here
"\AppData\Roaming\VintagestoryData\Mods"
"\AppData\Roaming\Vintagestory\Mods"

**Comment by Catnip12** [comment]
yeah, it's not registering my windows location, I can't mess with the mods through the mod manager,

**Comment by Catnip12** [comment]
Actually I can't mess with them at all. Do you know when this issue started? I will have to load up to a version before that since Windows lost my file(?)

**Comment by Craluminum2413** [comment]
You can try to reinstall the game

**Comment by Catnip12** [comment]
yeah, that's not it. But at least I know know how to access the game unfortunatley I think it may have renamed my user profile... no clue how that happened or how to fix it. Here's the new gobbly guck. I will try an earlier version this problem is also in 1.18.14 and 1.18.13 so I guess I will slowly work back in time to fix it. I know it is not in 1.17.9


Running on 64 bit Windows with 15307 MB RAM
Game Version: v1.18.15 (Stable)
10/20/2023 11:51:57 AM: Critical error occurred in the following mod: xskills@0.6.14
Loaded Mods: moreundergarments@0.0.1, game@1.18.15, carryon@1.6.0, prospecttogether@1.2.4, SimpleMobFootStepsUpdate@1.0.1, statushud@1.4.3, temporalstormtimer@1.1.1, creative@1.18.15, survival@1.18.15, xlib@0.6.14, xskills@0.6.14
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.Pos'.
   at XSkills.XSkillsPlayerBehavior.OnGameTick(Single deltaTime)
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\Entity.cs:line 874
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 527
   at Vintagestory.API.Common.EntityPlayer.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 608
   at Vintagestory.Client.NoObf.ClientSystemEntities.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Entities.cs:line 96
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 84
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 711
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10/20/2023 11:50:34 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER218B.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2B8F.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2BAF.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2BBD.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2BED.tmp.txt
\\?\C:\Users\flyingCatPhillips PC\AppData\Local\Temp\WER2D47.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_24454424-ebe0-4068-8470-73b3436ad64e

Analysis symbol: 
Rechecking for solution: 0
Report Id: 6015b858-ccc6-42cf-8ccf-3ac45293b7f2
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/20/2023 11:50:34 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER218B.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2B8F.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2BAF.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2BBD.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2BED.tmp.txt
\\?\C:\Users\flyingCatPhillips PC\AppData\Local\Temp\WER2D47.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_cab_24454424-ebe0-4068-8470-73b3436ad64e

Analysis symbol: 
Rechecking for solution: 0
Report Id: 6015b858-ccc6-42cf-8ccf-3ac45293b7f2
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/20/2023 11:50:31 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x1238
Faulting application start time: 0x01da037512640347
Faulting application path: C:\Users\flyingCatPhillips PC\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\flyingCatPhillips PC\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 6015b858-ccc6-42cf-8ccf-3ac45293b7f2
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
You are using very old version of xskills, the latest is 0.7.5

**Comment by Catnip12** [comment]
Yeah, I am currently stymied. I don't know why the application path is not working and how that got messed up, but I know there is a path to the application because I through difficulty pulled it up.

**Comment by Catnip12** [comment]
Okay the path I used to the files is 

C:\Users\flyingCatPhillips PC\AppData\Roaming\Vintagestory

but it's not working.... even tough all the files are there

**Comment by Catnip12** [comment]
Is there some way for me to verify the integrity of the files? Because It would just be weird if I always download the files and they are getting corrupted no matter what. I cannot even download 1.18.12 due to Windows fonts
