### ISSUE TITLE
the previous issue was closed before it was even resolved

### ISSUE THREAD

**Issue by Catnip12** [anegostudios/VintageStory-Issues#3164]
### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I cannot play any instances of the game and the past one is messed up now too! It's not the hud clock because I took that out and it still crashes. It's not reading the path and it's claiming it's not there. The game crashes when trying to load in a world either new or old. 

### How to reproduce

Running on 64 bit Windows with 15307 MB RAM
Game Version: v1.18.15 (Stable)
10/20/2023 1:40:03 PM: Critical error occurred in the following mod: hudclock@2.8.0
Loaded Mods: moreundergarments@0.0.1, game@1.18.15, carryon@1.6.0, hudclock@2.8.0, prospecttogether@1.2.4, SimpleMobFootStepsUpdate@1.0.1, statushud@1.4.3, temporalstormtimer@1.1.1, creative@1.18.15, survival@1.18.15, xlib@0.6.14, xskills@0.6.14
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.BitmapExternal.bmp'.
   at hudclock.src.ui.StormDialog.OnDraw(Context ctx, ImageSurface surface, ElementBounds currentBounds)
   at Vintagestory.API.Client.GuiElementCustomDraw.ComposeElements(Context ctxStatic, ImageSurface surfaceStatic) in VintagestoryApi\Client\UI\Elements\Impl\Static\GuiElementCustomDraw.cs:line 34
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 396
   at hudclock.src.ui.StormDialog.DefineGuiComposer() in D:\development\VintageStoryMods\solution\Mods\hudclock\src\ui\StormDialog.cs:line 198
   at hudclock.src.ui.StormDialog.Build() in D:\development\VintageStoryMods\solution\Mods\hudclock\src\ui\StormDialog.cs:line 38
   at hudclock.src.busineslogic.StormDialogController..ctor(ICoreClientAPI clientApi, ClockModSettingsController settings) in D:\development\VintageStoryMods\solution\Mods\hudclock\src\busineslogic\StormDialogController.cs:line 30
   at hudlock.src.HUDClockMod.PlayerReady(EnumHandling& handling) in D:\development\VintageStoryMods\solution\Mods\hudclock\src\HUDClockMod.cs:line 42
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerIsPlayerReady() in VintagestoryLib\Client\API\ClientEventAPI.cs:line 379
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 316
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 452
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 446
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 322
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10/20/2023 1:33:35 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER787C.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7B8A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7B9B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7BBA.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7BEA.tmp.txt
\\?\C:\Users\flyingCatPhillips PC\AppData\Local\Temp\WER7C58.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_595ba176-fe94-476f-84ef-7da6a7fa4f18

Analysis symbol: 
Rechecking for solution: 0
Report Id: 1c46aa5f-4448-4e45-a2be-1406bd8c798f
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/20/2023 1:33:35 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER787C.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7B8A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7B9B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7BBA.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7BEA.tmp.txt
\\?\C:\Users\flyingCatPhillips PC\AppData\Local\Temp\WER7C58.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_cab_595ba176-fe94-476f-84ef-7da6a7fa4f18

Analysis symbol: 
Rechecking for solution: 0
Report Id: 1c46aa5f-4448-4e45-a2be-1406bd8c798f
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/20/2023 1:33:33 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x7b0
Faulting application start time: 0x01da0383e7047d50
Faulting application path: C:\Users\flyingCatPhillips PC\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\flyingCatPhillips PC\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 1c46aa5f-4448-4e45-a2be-1406bd8c798f
Faulting package full name: 
Faulting package-relative application ID:  }

### Logs

```Log```

**Comment by Catnip12** [comment]
Just for proof that it's NOT the Hud Clock here is the crash log after I took it off

Running on 64 bit Windows with 15307 MB RAM
Game Version: v1.18.15 (Stable)
10/20/2023 1:48:19 PM: Critical error occurred in the following mod: xskills@0.6.14
Loaded Mods: moreundergarments@0.0.1, game@1.18.15, carryon@1.6.0, prospecttogether@1.2.4, SimpleMobFootStepsUpdate@1.0.1, statushud@1.4.3, temporalstormtimer@1.1.1, creative@1.18.15, survival@1.18.15, xlib@0.6.14, xskills@0.6.14
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.Pos'.
   at XSkills.XSkillsPlayerBehavior.OnGameTick(Single deltaTime)
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\Entity.cs:line 874
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 527
   at Vintagestory.API.Common.EntityPlayer.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 608
   at Vintagestory.Client.NoObf.ClientSystemEntities.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Entities.cs:line 96
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 84
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 711
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10/20/2023 1:46:53 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA445.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA772.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA783.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA7A2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA7F1.tmp.txt
\\?\C:\Users\flyingCatPhillips PC\AppData\Local\Temp\WERA850.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_5735c7b8-4e69-42cd-bc1c-e73dcd823b9f

Analysis symbol: 
Rechecking for solution: 0
Report Id: 07004625-6e20-428d-8e15-78ea9d2e63f9
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/20/2023 1:46:52 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA445.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA772.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA783.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA7A2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA7F1.tmp.txt
\\?\C:\Users\flyingCatPhillips PC\AppData\Local\Temp\WERA850.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_cab_5735c7b8-4e69-42cd-bc1c-e73dcd823b9f

Analysis symbol: 
Rechecking for solution: 0
Report Id: 07004625-6e20-428d-8e15-78ea9d2e63f9
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/20/2023 1:46:51 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x140c
Faulting application start time: 0x01da0385c1063118
Faulting application path: C:\Users\flyingCatPhillips PC\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\flyingCatPhillips PC\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 07004625-6e20-428d-8e15-78ea9d2e63f9
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
You need to remove xskills mod

**Comment by Catnip12** [comment]
I can get into the game after removing all the mods, but the mod manager is still broken and the path is still not reading correctly so I can no longer access it in game to open the mod folder. I will the hard way add the mods 1 at a time to see which is causing the problem. I don't know how a mod causes the problem with the mod manager path but oh, well.

**Comment by Catnip12** [comment]
It's both HudClock and xlib I have been checking them starting from my added one's to the ones that downloaded long ago like years ago.

**Comment by EnigmaticaGH** [comment]
Xskills/Xlib and Hudclock were causing the issue. It shows right in the crashes you provided. From your crash log 19h ago.

System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.Pos'.
at **XSkills.XSkillsPlayerBehavior.OnGameTick**(Single deltaTime)

If the mods directory is not opening in the correct location, it is because Vintage Story thinks it's installed in a different directory. You'll have to uninstall and reinstall the game to fix it (there's probably an easier way but this is what fixed it for me).

**Comment by Catnip12** [comment]
The problem was the hudclock and xlib. I uninstalled and reinstalled the
game but still can't access the mod manager the way your supposed to. I
have never read a crash log before so it's just a bunch of gobbly guck to
me. I ended up taking off all the mods and adding them back 1 at a time
skills was not the problem but I don't even know what xlib is but it is now
gone.

**Comment by Ragolution** [comment]
I guess this can be closed?
