### ISSUE TITLE
Game doesn´t Start

### ISSUE THREAD

**Issue by derheimbach** [anegostudios/VintageStory-Issues#3165]
### Game Version

V1.18.15

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

Running on 64 bit Windows with 32636 MB RAM
Game Version: v1.18.15 (Stable)
20.10.2023 23:00:47: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: Win32: Failed to query monitor DPI
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwGetMonitorContentScale(Monitor* monitor, Single* xscale, Single* yscale)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.GetMonitorContentScale(Monitor* monitor, Single& xScale, Single& yScale)
   at OpenTK.Windowing.Desktop.MonitorInfo..ctor(MonitorHandle handle)
   at OpenTK.Windowing.Desktop.Monitors.GetPrimaryMonitor()
   at VSPlatform.XPlatImpl.GetScreenSize() in XPlatformInterface\PlatformFormsImpl.cs:line 30
   at Vintagestory.Client.NoObf.ClientPlatformWindows..ctor(Logger logger) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 62
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 167
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

### Screenshots

![Unbenannt](https://github.com/anegostudios/VintageStory-Issues/assets/148590047/dea648e7-96c5-4bc8-85d2-331c55d98d49)

### Logs

```Log```
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13058629/client-main.txt)
[client-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/13058630/client-audit.txt)
[client-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/13058631/client-chat.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/13058632/client-crash.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/13058633/client-debug.txt)

**Comment by Zak0feill** [comment]
у меня похожая проблема как её решыть?

Running on 64 bit Windows with 5606 MB RAM

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 24.10.2023 20:13:07, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.18.15.0, метка времени: 0x64e841c5
Имя сбойного модуля: coreclr.dll, версия: 7.0.1223.47720, метка времени: 0x6514cca2
Код исключения: 0xc0000005
Смещение ошибки: 0x00000000001c97b2
Идентификатор сбойного процесса: 0x1ad4
Время запуска сбойного приложения: 0x01da069d574964da
Путь сбойного приложения: F:\Games\Vintage Story v1.18.15\Vintagestory.exe
Путь сбойного модуля: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\coreclr.dll
Идентификатор отчета: 4511584c-cb02-4b6d-99cd-dc1fc18c0461
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 24.10.2023 20:13:07, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
CoreCLR Version: 7.0.1223.47720
.NET Version: 7.0.12
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at OpenTK.Graphics.OpenGL.GL.Disable(OpenTK.Graphics.OpenGL.EnableCap)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.set_GlDebugMode(Boolean)
   at Vintagestory.Client.ScreenManager.Start(Vintagestory.Client.ClientProgramArgs, System.String[])
   at Vintagestory.Client.ClientProgram.Start(Vintagestory.Client.ClientProgramArgs, System.String[])
   at Vintagestory.Client.ClientProgram+<>c__DisplayClass10_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(System.Threading.ThreadStart)
   at Vintagestory.Client.ClientProgram..ctor(System.String[])
   at Vintagestory.Client.ClientProgram.Main(System.String[])
   at VintagestoryClientWindows.ClientWindows.Main(System.String[])
 }
--------------
{ TimeGenerated = 24.10.2023 19:59:44, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.18.15.0, метка времени: 0x64e841c5
Имя сбойного модуля: coreclr.dll, версия: 7.0.1223.47720, метка времени: 0x6514cca2
Код исключения: 0xc0000005
Смещение ошибки: 0x00000000001c97b2
Идентификатор сбойного процесса: 0x11e8
Время запуска сбойного приложения: 0x01da069b7b0f86af
Путь сбойного приложения: D:\VintageStory\Vintagestory.exe
Путь сбойного модуля: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\coreclr.dll
Идентификатор отчета: 44a9306d-41d6-448b-a93c-7841a7ccf889
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }

**Comment by Craluminum2413** [comment]
@Zak0feill send logs from VintagestoryData folder

**Comment by Craluminum2413** [comment]
Update drivers
