### ISSUE TITLE
Game crashes when connecting to server, launching client instance 

### ISSUE THREAD

**Issue by ItsCheif** [anegostudios/VintageStory-Issues#3166]
### Game Version

v1.18.15

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

When connecting to modded server hosted via BisectHosting, occasionally the game will just crash when trying to connect. The strange thing is that I might want to disconnect for 5 mins and come back, so despite playing perfectly normally for hours, I disconnect, then I can't join back in. Game just keeps repeatedly crashing.

I've disabled all the mods except the base 3 and it still crashes.

### How to reproduce

1. Connect to a modded server with the required mods on
2. It might work or it might not
3. Try it again, eventually it wont work and the game will crash every time you try to join
4. Disable all mods, it will still keep crashing upon join attempt

### Logs

Running on 64 bit Windows with 65433 MB RAM
Game Version: v1.18.15 (Stable)
2023/10/22 午前 4:29:57: Critical error occurred
Loaded Mods: game@1.18.15, farmlanddropssoil@1.4.0, prospecttogether@1.2.4, creative@1.18.15, survival@1.18.15, VsWaypointSharing@1.0.6
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.WeatherSystemClient.OnRenderFrame(Single dt, EnumRenderStage stage) in VSEssentials\Systems\Weather\WeatherSystemClient.cs:line 130
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 199
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 787
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 829
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 711
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2023/10/22 午前 4:29:26, Site = , Source = Application Error, Message = 障害が発生しているアプリケーション名: Vintagestory.exe、バージョン: 1.18.15.0、タイム スタンプ: 0x64e841c5
障害が発生しているモジュール名: openal32.dll、バージョン: 1.23.0.0、タイム スタンプ: 0x63dd31ad
例外コード: 0x40000015
障害オフセット: 0x00000000000df046
障害が発生しているプロセス ID: 0x6acc
障害が発生しているアプリケーションの開始時刻: 0x01da045d33a422c1
障害が発生しているアプリケーション パス: C:\Users\OWNER\AppData\Roaming\Vintagestory\Vintagestory.exe
障害が発生しているモジュール パス: C:\Users\OWNER\AppData\Roaming\Vintagestory\Lib\openal32.dll
レポート ID: e49557e2-3423-42da-8608-22637aa7c6f5
障害が発生しているパッケージの完全な名前: 
障害が発生しているパッケージに関連するアプリケーション ID:  }
--------------
{ TimeGenerated = 2023/10/22 午前 4:28:44, Site = , Source = Application Error, Message = 障害が発生しているアプリケーション名: Vintagestory.exe、バージョン: 1.18.15.0、タイム スタンプ: 0x64e841c5
障害が発生しているモジュール名: openal32.dll、バージョン: 1.23.0.0、タイム スタンプ: 0x63dd31ad
例外コード: 0x40000015
障害オフセット: 0x00000000000df046
障害が発生しているプロセス ID: 0x30fc
障害が発生しているアプリケーションの開始時刻: 0x01da045d0abd925a
障害が発生しているアプリケーション パス: C:\Users\OWNER\AppData\Roaming\Vintagestory\Vintagestory.exe
障害が発生しているモジュール パス: C:\Users\OWNER\AppData\Roaming\Vintagestory\Lib\openal32.dll
レポート ID: 65f11a74-d566-4682-9b9b-44489b32171f
障害が発生しているパッケージの完全な名前: 
障害が発生しているパッケージに関連するアプリケーション ID:  }
--------------
{ TimeGenerated = 2023/10/22 午前 4:27:36, Site = , Source = Application Error, Message = 障害が発生しているアプリケーション名: Vintagestory.exe、バージョン: 1.18.15.0、タイム スタンプ: 0x64e841c5
障害が発生しているモジュール名: openal32.dll、バージョン: 1.23.0.0、タイム スタンプ: 0x63dd31ad
例外コード: 0x40000015
障害オフセット: 0x00000000000df046
障害が発生しているプロセス ID: 0x1ab4
障害が発生しているアプリケーションの開始時刻: 0x01da045cf90b8c8d
障害が発生しているアプリケーション パス: C:\Users\OWNER\AppData\Roaming\Vintagestory\Vintagestory.exe
障害が発生しているモジュール パス: C:\Users\OWNER\AppData\Roaming\Vintagestory\Lib\openal32.dll
レポート ID: 85fb87a2-15f4-46ac-ba65-276be81b50c5
障害が発生しているパッケージの完全な名前: 
障害が発生しているパッケージに関連するアプリケーション ID:  }

**Comment by Craluminum2413** [comment]
Closing due to inactivity
