### ISSUE TITLE
crash in help menu on key press

### ISSUE THREAD

**Issue by anovickis** [anegostudios/VintageStory-Issues#3175]
```
Running on 64 bit Windows with 130763 MB RAM
Game Version: v1.18.15 (Stable)
10/26/2023 5:37:27 PM: Critical error occurred
Loaded Mods: game@1.18.15, creative@1.18.15, survival@1.18.15
System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Peek()
   at Vintagestory.GameContent.GuiDialogHandbook.ReloadPage() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 256
   at Vintagestory.GameContent.ModSystemTutorial.reloadTutorialPage() in VSSurvivalMod\Systems\Handbook\Tutorial\ModSystemTutorial.cs:line 267
   at Vintagestory.GameContent.ModSystemTutorial.onStateUpdate(ActionBoolReturn`1 stepCall) in VSSurvivalMod\Systems\Handbook\Tutorial\ModSystemTutorial.cs:line 241
   at Vintagestory.Client.NoObf.InputAPI.TriggerInWorldAction(EnumEntityAction action, Boolean on, EnumHandling& handling) in VintagestoryLib\Client\API\InputAPI.cs:line 42
   at Vintagestory.API.Common.EntityControls.AttemptToggleAction(EnumEntityAction action, Boolean on) in VintagestoryApi\Common\Entity\EntityControls.cs:line 337
   at Vintagestory.Client.NoObf.SystemPlayerControl.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Player\PlayerControl.cs:line 68
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 59
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 796
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 712
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10/26/2023 4:17:34 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.67be8955-e9d1-483e-87d7-05f02f6185f2.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a0e2def5-8d1a-48c2-8c35-4edcee8c58e2.tmp.WERInternalMetadata.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20231023_1_EC_0_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9e61f305-b7cf-470f-8cdf-cdfeb0c70aac.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7b8a9ad2-9b70-4376-a90b-f9b70231ad2e.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.bcba28fc-f4fb-4d69-9aec-a3d1fae47d55.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.eede30d8-2bcd-4d07-9a43-9480d9adeb4e.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b6d5f12b-7cb3-45d6-a6f9-8c488c4233e9.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_509800df-3a8b-4400-b5b8-ba0590c16888

Analysis symbol: 
Rechecking for solution: 0
Report Id: 0146ab74-1fa8-4615-ad97-bea02b746783
Report Status: 2147618816
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/26/2023 4:17:30 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x2fac0
Faulting application start time: 0x0x1da07c7177a0f3f
Faulting application path: C:\Users\Alex P. Novickis.QCE3X\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Alex P. Novickis.QCE3X\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 0146ab74-1fa8-4615-ad97-bea02b746783
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 10/24/2023 5:53:35 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0






Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b951d614-d11a-4a26-8ac8-b0a6d9b55f1d.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e7cc9b67-5063-4e5c-a1f7-0ee4c2b935be.tmp.WERInternalMetadata.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20231023_1_EC_0_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.48273dfe-9682-4d7c-9ac8-94abe7958ae9.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.fb8cfaab-7375-4049-8113-27770289372d.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.719a2d5c-f75c-4c56-a692-17f0be07f16d.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e51dfe51-27c3-4ad5-8f85-1d030b865d67.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ebac631b-969f-485f-9d73-f4d1acf51684.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_b12d0890-9eef-43e8-a52d-a5a02e9f0e9c

Analysis symbol: 
Rechecking for solution: 0
Report Id: 57fbabee-1caf-4f2f-8487-3d79563d629c
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
```

help menu opened, selected tutorial, then pressed D

**Comment by Craluminum2413** [comment]
Closing due to inactivity
