### ISSUE TITLE
Crash on character customisation confirmation

### ISSUE THREAD

**Issue by maltiez2** [anegostudios/VintageStory-Issues#3178]
### Game Version

v1.19.0-pre.2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

After creating new world and customizing character after pressing _Confirm_ button game crashes

### How to reproduce

1. Create new world
2. Go through character creation
3. Press confirm button

### Logs

```Running on 64 bit Windows with 32607 MB RAM
Game Version: v1.19.0-pre.2 (Unstable)
28/10/2023 19:51:59: Critical error occurred
Loaded Mods: game@1.19.0-pre.2, creative@1.19.0-pre.2, survival@1.19.0-pre.2
System.Exception: Call to RegisterCallback while game is paused. ExtendedDebug info and developermode is enabled, so will crash on this for reporting reasons.
   at Vintagestory.Client.NoObf.ClientMain.RegisterCallback(Action`1 OnTimePassed, Int32 millisecondDelay) in VintagestoryLib\Client\ClientMain.cs:line 3092
   at Vintagestory.Client.NoObf.ClientEventAPI.RegisterCallback(Action`1 OnTimePassed, Int32 millisecondDelay) in VintagestoryLib\Client\API\ClientEventAPI.cs:line 514
   at Vintagestory.Client.NoObf.ClientSystemIntroMenu.onEventBus(String eventName, EnumHandling& handling, IAttribute data) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogFirstlaunchInfo.cs:line 32
   at Vintagestory.Client.NoObf.ClientEventAPI.PushEvent(String eventName, IAttribute data) in VintagestoryLib\Client\API\ClientEventAPI.cs:line 461
   at Vintagestory.GameContent.CharacterSystem.ClientSelectionDone(IInventory characterInv, String characterClass, Boolean didSelect) in VSSurvivalMod\Systems\Character\Character.cs:line 579
   at Vintagestory.GameContent.GuiDialogCreateCharacter.OnGuiClosed() in VSSurvivalMod\Gui\GuiDialogCreateCharacter.cs:line 339
   at Vintagestory.API.Client.GuiDialog.TryClose() in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 299
   at Vintagestory.GameContent.GuiDialogCreateCharacter.OnConfirm() in VSSurvivalMod\Gui\GuiDialogCreateCharacter.cs:line 352
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 304
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 290
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 445
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 564
   at Vintagestory.GameContent.GuiDialogCreateCharacter.OnMouseUp(MouseEvent args) in VSSurvivalMod\Gui\GuiDialogCreateCharacter.cs:line 506
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 415
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1854
   at Vintagestory.Client.GuiScreenRunningGame.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 349
   at Vintagestory.Client.ScreenManager.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 883
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 213
   at OpenTK.Windowing.Desktop.NativeWindow.OnMouseUp(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 28/10/2023 19:51:37, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x6514d416
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x20b8
Faulting application start time: 0x01da09bebc4c8a27
Faulting application path: D:\Projects\Firearms\game_19\Vintagestory.exe
Faulting module path: D:\Projects\Firearms\game_19\Lib\openal32.dll
Report Id: f4d9fbc8-3db7-44ce-a4d6-4fe003184522
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 28/10/2023 19:50:08, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x6514d416
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x2664
Faulting application start time: 0x01da09be9dea9786
Faulting application path: D:\Projects\Firearms\game_19\Vintagestory.exe
Faulting module path: D:\Projects\Firearms\game_19\Lib\openal32.dll
Report Id: f5b3de4c-147e-4a17-890b-d5a21d182510
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 28/10/2023 19:48:44, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x6514d416
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x17f4
Faulting application start time: 0x01da09be8df28052
Faulting application path: D:\Projects\Firearms\game_19\Vintagestory.exe
Faulting module path: D:\Projects\Firearms\game_19\Lib\openal32.dll
Report Id: 0c574c13-7edc-479b-98ce-ec895a5ef880
Faulting package full name: 
Faulting package-relative application ID:  }```

**Comment by Mandikor** [comment]
I can confirm this since the first Pre version. Clean installation, no mods.

```
Running on 64 bit Windows with 16107 MB RAM
Game Version: v1.19.0-pre.4 (Unstable)
30.10.2023 17:48:39: Critical error occurred
Loaded Mods: game@1.19.0-pre.4, creative@1.19.0-pre.4, survival@1.19.0-pre.4
System.Exception: Call to RegisterCallback while game is paused. ExtendedDebug info and developermode is enabled, so will crash on this for reporting reasons.
   at Vintagestory.Client.NoObf.ClientMain.RegisterCallback(Action`1 OnTimePassed, Int32 millisecondDelay) in VintagestoryLib\Client\ClientMain.cs:line 3092
   at Vintagestory.Client.NoObf.ClientEventAPI.RegisterCallback(Action`1 OnTimePassed, Int32 millisecondDelay) in VintagestoryLib\Client\API\ClientEventAPI.cs:line 514
   at Vintagestory.Client.NoObf.ClientSystemIntroMenu.onEventBus(String eventName, EnumHandling& handling, IAttribute data) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogFirstlaunchInfo.cs:line 32
   at Vintagestory.Client.NoObf.ClientEventAPI.PushEvent(String eventName, IAttribute data) in VintagestoryLib\Client\API\ClientEventAPI.cs:line 461
   at Vintagestory.GameContent.CharacterSystem.ClientSelectionDone(IInventory characterInv, String characterClass, Boolean didSelect) in VSSurvivalMod\Systems\Character\Character.cs:line 579
   at Vintagestory.GameContent.GuiDialogCreateCharacter.OnGuiClosed() in VSSurvivalMod\Gui\GuiDialogCreateCharacter.cs:line 339
   at Vintagestory.API.Client.GuiDialog.TryClose() in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 299
   at Vintagestory.GameContent.GuiDialogCreateCharacter.OnConfirm() in VSSurvivalMod\Gui\GuiDialogCreateCharacter.cs:line 352
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 304
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 293
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 449
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 578
   at Vintagestory.GameContent.GuiDialogCreateCharacter.OnMouseUp(MouseEvent args) in VSSurvivalMod\Gui\GuiDialogCreateCharacter.cs:line 506
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 415
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1854
   at Vintagestory.Client.GuiScreenRunningGame.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 349
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 210
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

```

**Comment by Th3Dilli** [comment]
thanks, this should be fixed since pre 8
