### ISSUE TITLE
Crash when dragging Reed Basket across 2 bag slots (with 1 bag already equipped)

### ISSUE THREAD

**Issue by inariakagane** [anegostudios/VintageStory-Issues#3179]
### Game Version

v.19.0-pre.2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Across 2 worlds, I make 2 reed baskets (the backpack type):

I equip one.
I (accidentally the first time) click + drag a second bag across 2 backpack slots (both slots highlight blue, 2nd slot has the bag), release, crash.

### How to reproduce

1. 2 reed baskets
2. Equip one
3. Click and drag the other across backpack slots 2/3
4. Release when 2 slots are highlighted with the bag in 1 slot.
5. Crash.

### Logs

```Running on 64 bit Windows with 32677 MB RAM
Game Version: v1.19.0-pre.2 (Unstable)
10/28/2023 6:34:15 PM: Critical error occurred
Loaded Mods: game@1.19.0-pre.2, creative@1.19.0-pre.2, survival@1.19.0-pre.2
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 578
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 412
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1867
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 210
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93```

**Comment by DejFidOFF** [comment]
Windows. Experiencing the same.

**Comment by tyronx** [comment]
not able to reproduce this anymore in rc4. Please reopen if this still happens
