### ISSUE TITLE
Massive Log spam for Chiseled Blocks and crashing.

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#3182]
### Game Version

v1.19 pre2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Pages of Warnings
![image](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/502c0025-3159-463a-bcea-c920e5102bf5)

### How to reproduce

1. Open a world
2. Check Logs
3. Teleport to the blocks in the warnings 
4. Right click them 
5. Crashs your game

### Logs

[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13198221/server-main.txt)

Client Crash
```Running on 64 bit Windows with 32705 MB RAM
Game Version: v1.19.0-pre.2 (Unstable)
29.10.2023 14:42:48: Critical error occurred
Loaded Mods: rlmoonsun@0.1.1, vanillaruinfixes@0.1.0, game@1.19.0-pre.2, zoombuttonreborn@1.4.0, creative@1.19.0-pre.2, survival@1.19.0-pre.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityChisel.Interact(IPlayer byPlayer, BlockSelection blockSel) in VSSurvivalMod\Systems\Microblock\BEChisel.cs:line 108
   at Vintagestory.GameContent.BlockChisel.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in VSSurvivalMod\Systems\Microblock\BlockChisel.cs:line 30
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 876
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 456
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 101
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 796
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 989
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 29.10.2023 14:34:12, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.18.15.0, Zeitstempel: 0x64e841c5
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x0x5f08
Startzeit der fehlerhaften Anwendung: 0x0x1da0a6ab6fa3790
Pfad der fehlerhaften Anwendung: S:\VintageStory1.18.13\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: S:\VintageStory1.18.13\Vintagestory\Lib\openal32.dll
Berichtskennung: e28a296e-7d0a-46f0-bb83-b79459faa49f
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 29.10.2023 14:20:25, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.18.15.0, Zeitstempel: 0x64e841c5
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x0x819c
Startzeit der fehlerhaften Anwendung: 0x0x1da0a6924a5da1e
Pfad der fehlerhaften Anwendung: S:\VintageStory1.18.13\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: S:\VintageStory1.18.13\Vintagestory\Lib\openal32.dll
Berichtskennung: 1e9dcc73-3a1f-4c25-8b0a-38de870a62a6
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 29.10.2023 14:20:14, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.18.15.0, Zeitstempel: 0x64e841c5
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.22621.2506, Zeitstempel: 0x5a736bb8
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000006565c
ID des fehlerhaften Prozesses: 0x0x819c
Startzeit der fehlerhaften Anwendung: 0x0x1da0a6924a5da1e
Pfad der fehlerhaften Anwendung: S:\VintageStory1.18.13\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: fc72663a-c330-41b9-9fa6-7b4adffde8d3
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }```

**Comment by Rosethorns** [comment]
Can confirm. Getting this particularly around the Archives.

**Comment by tyronx** [comment]
hm, not getting any such errors looged when teleporting to the archives in a new world. Can you upload me a savegame where this problem occurs?

**Comment by Rosethorns** [comment]
[too big for git. I promise it isn't viruses xD](https://drive.google.com/file/d/1wNMM3zkypvQB80P4perxnaAq0Y6ABbxW/view?usp=drive_link)
Make sure you wander around in there for up to 5 minutes it doesn't immediately pop off sometimes.

**Comment by tyronx** [comment]
thanks for the reports, this should be fixed by now. Please reopen otherwise
