### ISSUE TITLE
no clue what happened. 1.19. 2

### ISSUE THREAD

**Issue by TheCatOfAges** [anegostudios/VintageStory-Issues#3184]
Running on 64 bit Windows with 32745 MB RAM
Game Version: v1.19.0-pre.2 (Unstable)
10/29/2023 3:09:09 PM: Critical error occurred
Loaded Mods: betterruins@0.2.2, fulldrop@1.0.0, natshumanskin@1.0.0, game@1.19.0-pre.2, freedomunits@1.1.0, immersivewoodchopping@0.4.0, simplestep@1.0.8, statushud@1.4.3, stickemup@1.0.0, useplanksinpitkiln@1.1.0, vesselbuff@1.0.6, creative@1.19.0-pre.2, survival@1.19.0-pre.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.WorldMapManager.mapAllowedClient() in VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 199
   at Vintagestory.GameContent.WorldMapManager.OnLoaded() in VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 204
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerBlockTexturesLoaded() in VintagestoryLib\Client\API\ClientEventAPI.cs:line 383
   at Vintagestory.Client.NoObf.SystemModHandler.OnBlockTexturesLoaded() in VintagestoryLib\Client\Systems\ModHandler.cs:line 236
   at Vintagestory.Client.NoObf.ClientSystemStartup.OnAllAssetsLoaded_ClientSystems(Int32 i) in VintagestoryLib\Client\Systems\Startup.cs:line 916
   at Vintagestory.Client.NoObf.ClientSystemStartup.<AllAssetsLoadedAndSpawnChunkReceived>b__52_0() in VintagestoryLib\Client\Systems\Startup.cs:line 906
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 763
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 322
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10/28/2023 12:47:21 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.19.0.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Clayton\AppData\Local\Temp\RDR51DD.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER51EE.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER51FE.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER521C.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER524B.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 204288b8-08e1-40a5-8d6f-3348b2989f3a
Report Status: 536870914
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/28/2023 12:03:08 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1273209627708249444, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.8.0
P3: 6492041a
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCF90.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD1D3.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD1E4.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD1F6.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD216.tmp.txt
\\?\C:\Users\Clayton\AppData\Local\Temp\WERD253.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_8de098f737c744fcb2cfb2449b6f09668c35b_9d23d9f5_4c17cff1-3a64-40c5-88b1-5ba8c1e63162

Analysis symbol: 
Rechecking for solution: 0
Report Id: 995f380d-1175-4ed4-a85a-8b24f2f43805
Report Status: 268566528
Hashed bucket: 42c222969642167ad1ab596920285564
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/28/2023 12:03:07 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.8.0
P3: 6492041a
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCF90.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD1D3.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD1E4.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD1F6.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD216.tmp.txt
\\?\C:\Users\Clayton\AppData\Local\Temp\WERD253.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_8de098f737c744fcb2cfb2449b6f09668c35b_9d23d9f5_cab_4c17cff1-3a64-40c5-88b1-5ba8c1e63162

Analysis symbol: 
Rechecking for solution: 0
Report Id: 995f380d-1175-4ed4-a85a-8b24f2f43805
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }

**Comment by tyronx** [comment]
should be fixed in pre4, please reopen if it happens again
