### ISSUE TITLE
Scroll rack crashs my game on left click

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#3187]
### Game Version

v1.19 pre2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### How to reproduce

Place scroll rack
try to break scroll rack
in creative

### Logs

```Running on 64 bit Windows with 32705 MB RAM
Game Version: v1.19.0-pre.2 (Unstable)
30.10.2023 15:58:55: Critical error occurred
Loaded Mods: rlmoonsun@0.1.1, vanillaruinfixes@0.1.0, game@1.19.0-pre.2, zoombuttonreborn@1.4.0, creative@1.19.0-pre.2, survival@1.19.0-pre.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockScrollRack.GetSelectionBoxes(IBlockAccessor blockAccessor, BlockPos pos) in VSSurvivalMod\Block\BlockScrollRack.cs:line 91
   at Vintagestory.API.Common.Block.GetParticleBreakBox(IBlockAccessor blockAccess, BlockPos pos, BlockFacing facing) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 508
   at Vintagestory.API.Common.CollectibleParticleProperties.RandomBlockPos(IBlockAccessor blockAccess, BlockPos pos, Block block, BlockFacing facing) in VintagestoryApi\Common\Particle\CollectibleParticleProperties.cs:line 161
   at Vintagestory.API.Common.BlockBrokenParticleProps.get_Pos() in VintagestoryApi\Common\Particle\CollectibleParticleProperties.cs:line 95
   at Vintagestory.Client.NoObf.ParticlePoolQuads.SpawnParticles(IParticlePropertiesProvider particleProperties) in VintagestoryLib\Client\Systems\Render\Particle\ParticlePoolQuads.cs:line 209
   at Vintagestory.Client.NoObf.ParticleManager.SpawnParticles(IParticlePropertiesProvider properties) in VintagestoryLib\Client\Util\ParticleManager.cs:line 107
   at Vintagestory.Client.NoObf.ClientMain.SpawnParticles(IParticlePropertiesProvider particlePropertiesProvider, IPlayer dualCallByPlayer) in VintagestoryLib\Client\ClientMain.cs:line 3161
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleSpawnParticles(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 521
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 763
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Craluminum2413** [comment]
Fixed in pre.4
