### ISSUE TITLE
Tring to pick up an open or closed crate in a TL room crashes game

### ISSUE THREAD

**Issue by Ashantin** [anegostudios/VintageStory-Issues#3189]
### Game Version

v1.19 pre3

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

I was using an axe on a chest in a TL chamber when I crashed.

### How to reproduce

Mend a TL. Try to pick up an open or closed crate with an axe.

### Logs
```
Running on 64 bit Windows with 65397 MB RAM
Game Version: v1.19.0-pre.3 (Unstable)
30/10/2023 15:38:01: Critical error occurred
Loaded Mods: game@1.19.0-pre.3, creative@1.19.0-pre.3, survival@1.19.0-pre.3
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AnimationCache.InitManager(ICoreAPI api, IAnimationManager manager, Entity entity, Shape entityShape, RunningAnimation[] copyOverAnims, String[] requireJointsForElements) in VintagestoryApi\Common\Model\Animation\AnimationCache.cs:line 59
   at Vintagestory.API.Common.Entities.Entity.OnTesselation(Shape& entityShape, String shapePathForLogging) in VintagestoryApi\Common\Entity\Entity.cs:line 1025
   at Vintagestory.API.Common.EntityPlayer.OnTesselation(Shape& entityShape, String shapePathForLogging) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 393
   at Vintagestory.GameContent.EntityShapeRenderer.TesselateShape(Action`1 onMeshDataReady, String[] overrideSelectiveElements) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 270
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.TesselateShape() in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 49
   at Vintagestory.GameContent.EntityShapeRenderer.BeforeRender(Single dt) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 451
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 796
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 718
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 30/10/2023 14:41:45, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x6514d416
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x2118
Faulting application start time: 0x01da0b3f033e8b18
Faulting application path: D:\Vintagestory\Vintagestory\Vintagestory.exe
Faulting module path: D:\Vintagestory\Vintagestory\Lib\openal32.dll
Report ID: 829022e3-edac-4c0d-a92a-2a76d19f1202
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 30/10/2023 14:37:02, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x4108
Faulting application start time: 0x01da0b3a35a2a4bc
Faulting application path: D:\Vintagestory\Vintagestory\Vintagestory.exe
Faulting module path: D:\Vintagestory\Vintagestory\Lib\openal32.dll
Report ID: 4456be31-0390-4ee9-bc9b-e57d90e0ec3f
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 30/10/2023 14:05:31, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x38d4
Faulting application start time: 0x01da0b3a1d46203c
Faulting application path: D:\Vintagestory\Vintagestory\Vintagestory.exe
Faulting module path: D:\Vintagestory\Vintagestory\Lib\openal32.dll
Report ID: 93b6dc14-574e-47a9-9f30-9c0ee558fb64
Faulting package full name: 
Faulting package-relative application ID:  }
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
