### ISSUE TITLE
update 1.9.14 did not fix chisel bug for me

### ISSUE THREAD

**Issue by jhendrix61978** [anegostudios/VintageStory-Issues#319]
**Game Version:** 1.9.14
**Platform:** Windows 10
**Modded:** Yes (The Neolithic Mod)

### Description
right click with chisle not facing block caused crash

### How to reproduce
right click on nothing

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.9.14 (Stable)7/16/2019 3:57:22 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemChisel.OnHeldAttackStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, EnumHandHandling& handling)
   at _59O9yDZ9MPMaePsB1vpmbtB751J._VtOJ3fr4TX3jm8mUB0x54drC3eF(BlockSelection , EntitySelection , EnumHandInteract , EnumHandHandling& )
   at _59O9yDZ9MPMaePsB1vpmbtB751J._X99KL09dDLMlhTvvE0n9KOvV1Pq(Single )
   at _59O9yDZ9MPMaePsB1vpmbtB751J._XOubv8mKCnGEWFElDNm5uYoKtSB(Single )
   at _le0ZSxaKl7hP8MShwGMesNiExBi._yFNDEHMQZY9G1iqOhIIExpWwrBN(EnumRenderStage , Single )
   at _mAyHjkDLCsjrx9ggTQeqjFyCeVn._yFNDEHMQZY9G1iqOhIIExpWwrBN(EnumRenderStage , Single )
   at _mAyHjkDLCsjrx9ggTQeqjFyCeVn._ZzwbGfsAE3HE8mqmDVJG7Vbf8Pq(Single )
   at _iShPTtVoykHbcDC0SKrD3EpQsGI._ZzwbGfsAE3HE8mqmDVJG7Vbf8Pq(Single )
   at _utdxxfMlqCSGdfrASwv1F8kSGlO._SILC5Ctu2J4u4V83zL8s1u4sfNG(Single )
   at _utdxxfMlqCSGdfrASwv1F8kSGlO._T9Xfz9KBFjRtpFK0Uff1jPp6aCP(Single )
   at _JxxbRaMer3tvxBdMUrRprDa3Ubp._AYfShIydr9fkqDkIh9Oxl5JSsxC(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _o7qpMLpZx4RXtcPyppf0Dr5cYmp._8toUOL3ACNPVa1vMlJqNlZdHV3Nb(_RDMdnizeIvfX9H5lvU7GJtlAZkK , String[] )
   at _dHd2HwfkClrbQffaAeWuWBjEjKw._8toUOL3ACNPVa1vMlJqNlZdHV3Nb(ThreadStart )
-------------------------------

```

**Comment by tyronx** [comment]
is this still a thing in v1.10

**Comment by jhendrix61978** [comment]
Not sure have been busy and have not had time to test I will let you know
as soon as I can get time to test

**Comment by Craluminum2413** [comment]
It looks like the bug has been fixed. Otherwise, there would have been a bunch of answers here long ago
