### ISSUE TITLE
crash on windows11 each time i save or leave a server

### ISSUE THREAD

**Issue by Night-Sky1970** [anegostudios/VintageStory-Issues#3192]
### Game Version

v1.18.15

### Platform

Windows

### Modded

Modded

### SP/MP

None

### Description

i get this error..

doesnt mater if i got mods or not...

or singleplayer or multi.. 

### How to reproduce

1 start game..
2 pick a save game or join server
3 save the game or leave server.
4 crash...

### Screenshots

well ahum.. i give ya the log.. as just the crasreporter does open..

### Logs

Running on 64 bit Windows with 32676 MB RAM
Game Version: v1.18.15 (Stable)
31/10/2023 15:13:44: Critical error occurred
Loaded Mods: 
System.TypeLoadException: Could not load type 'Vintagestory.API.Client.MultiTextureMeshRef' from assembly 'VintagestoryAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at SortableStorage.ModSystem.BlockGenericSortableTypedContainer.OnUnloaded(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientMain.Dispose() in VintagestoryLib\Client\ClientMain.cs:line 2649
   at Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected) in VintagestoryLib\Client\ClientMain.cs:line 2544
   at Vintagestory.Client.NoObf.GuiDialogDead.OnLeaveWorld() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogDead.cs:line 105
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 304
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 290
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 578
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 415
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1849
   at Vintagestory.Client.GuiScreenRunningGame.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 349
   at Vintagestory.Client.ScreenManager.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 883
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 212
   at OpenTK.Windowing.Desktop.NativeWindow.OnMouseUp(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 31/10/2023 15:02:34, Site = , Source = Application Error, Message = Naam van toepassing met fout: Vintagestory.exe, versie: 1.18.15.0, tijdstempel: 0x64e841c5
Naam van module met fout: openal32.dll, versie: 1.23.0.0, tijdstempel: 0x63dd31ad
Uitzonderingscode: 0x40000015
Foutmarge: 0x00000000000df046
Id van proces met fout: 0x0xc20
Starttijd van toepassing met fout: 0x0x1da0c0112d21134
Pad naar toepassing met fout: C:\Users\night\AppData\Roaming\Vintagestory\Vintagestory.exe
Pad naar module met fout: C:\Users\night\AppData\Roaming\Vintagestory\Lib\openal32.dll
Rapport-id: ac17280a-05d5-4c94-9d79-5d8bee85c11a
Volledige pakketnaam met fout: 
Relatieve toepassings-id van pakket met fout:  }
--------------
{ TimeGenerated = 31/10/2023 13:23:17, Site = , Source = Application Error, Message = Naam van toepassing met fout: Vintagestory.exe, versie: 1.18.15.0, tijdstempel: 0x64e841c5
Naam van module met fout: openal32.dll, versie: 1.23.0.0, tijdstempel: 0x63dd31ad
Uitzonderingscode: 0x40000015
Foutmarge: 0x00000000000df046
Id van proces met fout: 0x0x234c
Starttijd van toepassing met fout: 0x0x1da0bf0e3184a68
Pad naar toepassing met fout: C:\Users\night\AppData\Roaming\Vintagestory\Vintagestory.exe
Pad naar module met fout: C:\Users\night\AppData\Roaming\Vintagestory\Lib\openal32.dll
Rapport-id: b0ad3695-2648-4a81-b336-0cae1dc65631
Volledige pakketnaam met fout: 
Relatieve toepassings-id van pakket met fout:  }
--------------
{ TimeGenerated = 31/10/2023 12:34:08, Site = , Source = Application Error, Message = Naam van toepassing met fout: Vintagestory.exe, versie: 1.18.15.0, tijdstempel: 0x64e841c5
Naam van module met fout: openal32.dll, versie: 1.23.0.0, tijdstempel: 0x63dd31ad
Uitzonderingscode: 0x40000015
Foutmarge: 0x00000000000df046
Id van proces met fout: 0x0x644c
Starttijd van toepassing met fout: 0x0x1da0bea12674ced
Pad naar toepassing met fout: C:\Users\night\AppData\Roaming\Vintagestory\Vintagestory.exe
Pad naar module met fout: C:\Users\night\AppData\Roaming\Vintagestory\Lib\openal32.dll
Rapport-id: 4739518a-cb38-46dd-955c-dac3a227e5c5
Volledige pakketnaam met fout: 
Relatieve toepassings-id van pakket met fout:  }

**Comment by Hymlock** [comment]
This is happening with me also. Find a cause yet?

**Comment by FireFrost76** [comment]
same here in single player , normal world cant open save file , nor mod folder from the game itself , can not save and exit with out it crashing , uninstalled the entire game deleted every folder in appdata and c drive , restarted and made sure there was nothing vintage story related on the pc at all , no web pages saved nothing , no pictures and still does it , very frustrating , worked fine before the net 7 update ,  multiple fresh installs , same results no mods , tons of mods makes no difference

**Comment by Craluminum2413** [comment]
@Hymlock @FireFrost76 Do you have SortableStorage in crash log?

**Comment by Craluminum2413** [comment]
I close it as SortableStorage mod issue for now
