### ISSUE TITLE
Game crash on interract with chiseled block

### ISSUE THREAD

**Issue by GerMilitaryLoli** [anegostudios/VintageStory-Issues#3193]
### Game Version

v1.19.0-pre 3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I was climbing up the stairs, eating bread, and there is a hatch on the stairs that closes when I hold RMB, because i eat bread,  and the game crashes.
But in log, game trying interact with chiseled block, my ladder place in floor near window, where i use chiseled blocks

### How to reproduce

1. Take food 
2. Climb in ladder
3. Touch trapdoor while holding RMB for eat
4. Get crash(It happened to me like that)

### Logs

Running on 64 bit Windows with 16335 MB RAM
Game Version: v1.19.0-pre.3 (Unstable)
02.11.2023 20:18:09: Critical error occurred
Loaded Mods: game@1.19.0-pre.3, creative@1.19.0-pre.3, survival@1.19.0-pre.3
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityChisel.Interact(IPlayer byPlayer, BlockSelection blockSel) in VSSurvivalMod\Systems\Microblock\BEChisel.cs:line 108
   at Vintagestory.GameContent.BlockChisel.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in VSSurvivalMod\Systems\Microblock\BlockChisel.cs:line 30
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 876
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 456
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 101
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 796
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 989
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 31.10.2023 20:39:57, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.18.15.0, метка времени: 0x64e841c5
Имя сбойного модуля: openal32.dll, версия: 1.23.0.0, метка времени: 0x63dd31ad
Код исключения: 0x40000015
Смещение ошибки: 0x00000000000df046
Идентификатор сбойного процесса: 0x0x45c
Время запуска сбойного приложения: 0x0x1da0c1e3b72d0db
Путь сбойного приложения: D:\Games\Vintagestory\Vintagestory.exe
Путь сбойного модуля: D:\Games\Vintagestory\Lib\openal32.dll
Идентификатор отчета: 85aaf992-7212-426c-bc53-df5d88e73e3c
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 29.10.2023 18:34:39, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.18.15.0, метка времени: 0x64e841c5
Имя сбойного модуля: openal32.dll, версия: 1.23.0.0, метка времени: 0x63dd31ad
Код исключения: 0x40000015
Смещение ошибки: 0x00000000000df046
Идентификатор сбойного процесса: 0x0x2e38
Время запуска сбойного приложения: 0x0x1da0a792ce1fc1b
Путь сбойного приложения: D:\Games\Vintagestory\Vintagestory.exe
Путь сбойного модуля: D:\Games\Vintagestory\Lib\openal32.dll
Идентификатор отчета: 2f127102-e168-46cf-b326-cf6f4ee42985
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 29.10.2023 14:12:21, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.18.15.0, метка времени: 0x64e841c5
Имя сбойного модуля: openal32.dll, версия: 1.23.0.0, метка времени: 0x63dd31ad
Код исключения: 0x40000015
Смещение ошибки: 0x00000000000df046
Идентификатор сбойного процесса: 0x0xe5c
Время запуска сбойного приложения: 0x0x1da0a40c09cc152
Путь сбойного приложения: D:\Games\Vintagestory\Vintagestory.exe
Путь сбойного модуля: D:\Games\Vintagestory\Lib\openal32.dll
Идентификатор отчета: b1b6ed49-d717-471f-b2a1-e4ef1dcc5137
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }

**Comment by Craluminum2413** [comment]
Duplicate of #3182
