### ISSUE TITLE
Crash après avoir cliquer sur le coffre dans le guide

### ISSUE THREAD

**Issue by valtou79** [anegostudios/VintageStory-Issues#3194]
### Game Version

v1.18.15

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Crash après avoir cliquer sur le coffre dans le guide

### How to reproduce

1.aller dans le guide
2.cliquer sur coffre en bois 
3.le jeu crash a chaque fois

### Logs

```Log```Running on 64 bit Windows with 12203 MB RAM
Game Version: v1.18.15 (Stable)
02/11/2023 20:27:47: Critical error occurred
Loaded Mods: game@1.18.15, creative@1.18.15, survival@1.18.15
System.DivideByZeroException: Attempted to divide by zero.
   at Vintagestory.API.Client.SlideshowGridRecipeTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY, Double renderZ) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\SlideshowGridRecipeTextComponent.cs:line 269
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 477
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 695
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 379
   at Vintagestory.GameContent.GuiDialogHandbook.OnRenderGUI(Single deltaTime) in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 571
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 318
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 790
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 983
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 02/11/2023 20:16:59, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.18.15.0, horodatage : 0x64e841c5
Nom du module défaillant : openal32.dll, version : 1.23.0.0, horodatage : 0x63dd31ad
Code d’exception : 0x40000015
Décalage d’erreur : 0x00000000000df046
ID du processus défaillant : 0x3224
Heure de début de l’application défaillante : 0x01da0dba8c8c9b1d
Chemin d’accès de l’application défaillante : C:\Users\valen\AppData\Roaming\Vintagestory\Vintagestory.exe
Chemin d’accès du module défaillant: C:\Users\valen\AppData\Roaming\Vintagestory\Lib\openal32.dll
ID de rapport : bdf632c4-6051-4746-8b09-5614d640acae
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }
--------------
{ TimeGenerated = 02/11/2023 19:29:44, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.18.15.0, horodatage : 0x64e841c5
Nom du module défaillant : openal32.dll, version : 1.23.0.0, horodatage : 0x63dd31ad
Code d’exception : 0x40000015
Décalage d’erreur : 0x00000000000df046
ID du processus défaillant : 0x89c
Heure de début de l’application défaillante : 0x01da0db9934cc8e5
Chemin d’accès de l’application défaillante : C:\Users\valen\AppData\Roaming\Vintagestory\Vintagestory.exe
Chemin d’accès du module défaillant: C:\Users\valen\AppData\Roaming\Vintagestory\Lib\openal32.dll
ID de rapport : 57f4c12a-c186-457e-a7a3-4669b331a37e
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }
--------------
{ TimeGenerated = 02/11/2023 18:58:49, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.18.15.0, horodatage : 0x64e841c5
Nom du module défaillant : openal32.dll, version : 1.23.0.0, horodatage : 0x63dd31ad
Code d’exception : 0x40000015
Décalage d’erreur : 0x00000000000df046
ID du processus défaillant : 0x31c4
Heure de début de l’application défaillante : 0x01da0dad6bcabb0a
Chemin d’accès de l’application défaillante : C:\Users\valen\AppData\Roaming\Vintagestory\Vintagestory.exe
Chemin d’accès du module défaillant: C:\Users\valen\AppData\Roaming\Vintagestory\Lib\openal32.dll
ID de rapport : dc96fdd5-31b8-49d9-b255-64183353dac9
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }

**Comment by Craluminum2413** [comment]
Closing due to inactivity
