### ISSUE TITLE
The game often crashes at various moments

### ISSUE THREAD

**Issue by StefanTBW** [anegostudios/VintageStory-Issues#3195]
### Game Version

v1.19.0-pre.3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The game sometimes crashes in different situations. 

Sometimes this can happen due to jumping into water, breaking a block, or taking damage. 

Reinstallation didn't help

### Logs

Running on 64 bit Windows with 16314 MB RAM
Game Version: v1.19.0-pre.3 (Unstable)
03.11.2023 13:55:53: Critical error occurred
Loaded Mods: game@1.19.0-pre.3, creative@1.19.0-pre.3, survival@1.19.0-pre.3
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AnimationCache.InitManager(ICoreAPI api, IAnimationManager manager, Entity entity, Shape entityShape, RunningAnimation[] copyOverAnims, String[] requireJointsForElements) in VintagestoryApi\Common\Model\Animation\AnimationCache.cs:line 59
   at Vintagestory.API.Common.Entities.Entity.OnTesselation(Shape& entityShape, String shapePathForLogging) in VintagestoryApi\Common\Entity\Entity.cs:line 1025
   at Vintagestory.API.Common.EntityPlayer.OnTesselation(Shape& entityShape, String shapePathForLogging) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 390
   at Vintagestory.GameContent.EntityShapeRenderer.TesselateShape(Action`1 onMeshDataReady, String[] overrideSelectiveElements) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 270
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.Tesselate() in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 61
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.TesselateShape() in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 30
   at Vintagestory.GameContent.EntityShapeRenderer.BeforeRender(Single dt) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 451
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 796
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 718
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by tyronx** [comment]
thanks for the report, this is most likely fixed by rc4, please reopen otherwise
