### ISSUE TITLE
Crash when emptying a bucket of dried bees wax 

### ISSUE THREAD

**Issue by Bulwark77** [anegostudios/VintageStory-Issues#3203]
### Game Version

v 1.18.5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I had a bucket of wax that was drying and when it finally was dry. I attempted to dump it out on the floor to get the wax out. The game crashed. 

### How to reproduce

1. get a full bucket of wax. 2. let it sit for months and a day. 3. pick it up when it is FINALY dry. 4. Attempt to empty it by dumping it out by hitting control right click. 

### Logs

`Running on 64 bit Windows with 32700 MB RAM
Game Version: v1.18.15 (Stable)
11/5/2023 11:59:20 PM: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.15, AMFinder@1.3.1, angelbelt@1.4.0, autosifter@1.1.0, backpackpackplus@1.0.3, bettercrates@1.6.0, BuggisRandomChanges@3.3.0, buildinggadgets@0.4.0, chiseltools@1.8.4, composter@1.0.4, craftingtable@0.4.0, EasyFruitTrees@1.0.1, extrachests@1.7.0, extraclayforming@1.0.0, FarmSurvival@1.3.0, FastPitkilns@1.0.0, fernslikegrass@1.0.0, FlexibleTools@2.1.0, HoneyPress@1.1.2, mcd1@1.0.0, moreclassestweak@1.2.5, moredrygrass@0.2.0, moremolds@1.4.12, MoreTreeSeeds@1.0.0, nightwatcher@1.4.0, nooffhandhunger@1.0.0, OresAPlenty@3.1.0, qptech@1.14.1, QuartzBlocks@1.1.0, roas@1.0.0, RockBlocks@1.0.0, simpleelevator@1.3.0, standardcrates@1.0.0, tprunes@1.0.8, vtpp@1.0.0, game@1.18.15, zoombuttonreborn@1.4.0, alloycalculator@1.0.0, animalcages@2.1.5, betterbloomeriesreborn@1.0.4, betterfirepit@1.1.0, carryon@1.0.0, commonlib@2.1.1, diamondcrate@1.0.2, expandedfoods@1.6.8, farmlanddropssoil@1.4.0, hudclock@3.3.0, sailboat@1.1.0, medievalexpansion@3.9.2, petai@1.7.2, claywheel@1.1.0, prospectorinfo@4.3.0, scarecrow@1.2.3, stillnecessaries@1.0.0, techmolds@1.0.0, temporalstormtimer@1.0.0, translocatorlocator@1.0.2, creative@1.18.15, survival@1.18.15, wildfarmingrevival@1.0.5, metalrecovery@0.1.18-rc.2, tradercamps@1.0.4, em@2.1.0, feverstonehorses@1.5.0, morecandles@1.1.3, simplewinddirection@1.0.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockLiquidContainerBase.SpillContents(ItemSlot containerSlot, EntityAgent byEntity, BlockSelection blockSel) in VSSurvivalMod\Systems\Liquid\BlockLiquidContainerBase.cs:line 1156
   at Vintagestory.GameContent.BlockLiquidContainerBase.OnHeldInteractStart(ItemSlot itemslot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handHandling) in VSSurvivalMod\Systems\Liquid\BlockLiquidContainerBase.cs:line 941
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 857
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 447
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 92
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 790
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 983
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/5/2023 4:06:34 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1231118928236256338, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: coreclr.dll
P5: 7.0.423.11508
P6: 63ed7a18
P7: c0000005
P8: 00000000001ca906
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER383B.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER42AC.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER42BD.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER42CA.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER42FA.tmp.txt
\\?\C:\Users\jayat\AppData\Local\Temp\WER461A.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_a8d9d233d40fef82db912512bda8a814e59ad51_ee8069fc_bd55265d-10bd-47bb-984e-da986854dd26

Analysis symbol: 
Rechecking for solution: 0
Report Id: 15511dc0-2705-430d-82b7-4b6802638c61
Report Status: 268435456
Hashed bucket: d03f42bff9db5e919115d02479c81c52
Cab Guid: 0 }
--------------
{ TimeGenerated = 11/5/2023 4:06:33 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: coreclr.dll
P5: 7.0.423.11508
P6: 63ed7a18
P7: c0000005
P8: 00000000001ca906
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER383B.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER42AC.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER42BD.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER42CA.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER42FA.tmp.txt
\\?\C:\Users\jayat\AppData\Local\Temp\WER461A.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_a8d9d233d40fef82db912512bda8a814e59ad51_ee8069fc_cab_bd55265d-10bd-47bb-984e-da986854dd26

Analysis symbol: 
Rechecking for solution: 0
Report Id: 15511dc0-2705-430d-82b7-4b6802638c61
Report Status: 4
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 11/5/2023 4:06:29 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: coreclr.dll, version: 7.0.423.11508, time stamp: 0x63ed7a18
Exception code: 0xc0000005
Fault offset: 0x00000000001ca906
Faulting process id: 0x48c4
Faulting application start time: 0x01da10332ce3acbb
Faulting application path: C:\Users\jayat\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.4\coreclr.dll
Report Id: 15511dc0-2705-430d-82b7-4b6802638c61
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Dried beeswax is noy vanilla liquid
