### ISSUE TITLE
 v1.19.0-pre.5 crash near ruins

### ISSUE THREAD

**Issue by f33dback89** [anegostudios/VintageStory-Issues#3205]
### Game Version

 v1.19.0-pre.5

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

The game crashes when I approached some new ruins

### How to reproduce

Approach ruins that contain microblocks

### Logs

Running on 64 bit Windows with 32540 MB RAM
Game Version: v1.19.0-pre.5 (Unstable)
2023-11-06 8:51:58 PM: Critical error occurred
Loaded Mods: game@1.19.0-pre.5, creative@1.19.0-pre.5, survival@1.19.0-pre.5
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Vintagestory.GameContent.MicroBlockSounds.get_block() in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 45
   at Vintagestory.GameContent.MicroBlockSounds.get_Walk() in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 23
   at Vintagestory.API.Common.EntityPlayer.PlayWalkSound(IPlayer player) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 538
   at Vintagestory.API.Common.EntityPlayer.updateEyeHeight(Single dt) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 398
   at Vintagestory.Client.NoObf.PlayerCamera.OnBeforeRenderFrame3D(Single dt) in VintagestoryLib\Client\Render\PlayerCamera.cs:line 58
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 796
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 718
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by TRex8319** [comment]
Heres another crash log:

Game Version: v1.19.0-pre.5 (Unstable)
2023-11-07 2:20:57 AM: Critical error occurred
Loaded Mods: buzzwords@1.6.0, sortablestorage@2.2.0, game@1.19.0-pre.5, zoombuttonreborn@1.6.0, carryon@1.7.0-pre.1, farmlanddropssoil@1.4.0, hudclock@3.3.0, stepup@1.2.0, creative@1.19.0-pre.5, survival@1.19.0-pre.5, em@2.5.0-pre.1, bricklayers@2.5.0-pre.1
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at Vintagestory.GameContent.MicroBlockSounds.get_block() in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 45
   at Vintagestory.GameContent.MicroBlockSounds.get_Walk() in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 23
   at Vintagestory.API.Common.EntityPlayer.PlayWalkSound(IPlayer player) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 538
   at Vintagestory.API.Common.EntityPlayer.updateEyeHeight(Single dt) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 398
   at Vintagestory.Client.NoObf.PlayerCamera.OnBeforeRenderFrame3D(Single dt) in VintagestoryLib\Client\Render\PlayerCamera.cs:line 58
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 796
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 718
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by NNx3** [comment]
Having a similar crash as well. Seems that walking on the gravel side of, or simply hitting a granite cobble+gravel chiseled block (atleast the ones located around ruins) causes an instant crash. 

Running on 64 bit Windows with 16268 MB RAM
Game Version: v1.19.0-pre.5 (Unstable)
11/8/2023 10:49:53 PM: Critical error occurred
Loaded Mods: game@1.19.0-pre.5, creative@1.19.0-pre.5, survival@1.19.0-pre.5
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Vintagestory.GameContent.MicroBlockSounds.get_block() in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 45
   at Vintagestory.GameContent.MicroBlockSounds.get_Hit() in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 20
   at Vintagestory.API.Common.BlockSounds.GetHitSound(IPlayer byPlayer) in VintagestoryApi\Common\Collectible\Block\BlockSounds.cs:line 67
   at Vintagestory.API.Common.Block.OnGettingBroken(IPlayer player, BlockSelection blockSel, ItemSlot itemslot, Single remainingResistance, Single dt, Int32 counter) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 956
   at Vintagestory.GameContent.BlockMicroBlock.OnGettingBroken(IPlayer player, BlockSelection blockSel, ItemSlot itemslot, Single remainingResistance, Single dt, Int32 counter) in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 467
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 783
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 456
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 101
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 796
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 989
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by vintage-seraph** [comment]
Same here.  v1.19.0-pre.5  

Some, not all, of the composite cobble/gravel blocks cause a crash.  I excavated the ruin to reveal all the composite blocks and found walking on the tops.. or breaking any of them..  caused the crash.  See screenshots.

Running on 64 bit Windows with 32464 MB RAM
Game Version: v1.19.0-pre.5 (Unstable)
11/10/2023 12:17:09 AM: Critical error occurred
Loaded Mods: game@1.19.0-pre.5, creative@1.19.0-pre.5, survival@1.19.0-pre.5
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Vintagestory.GameContent.MicroBlockSounds.get_block() in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 45
   at Vintagestory.GameContent.MicroBlockSounds.get_Walk() in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 23
   at Vintagestory.API.Common.EntityPlayer.PlayWalkSound(IPlayer player) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 538
   at Vintagestory.API.Common.EntityPlayer.updateEyeHeight(Single dt) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 398
   at Vintagestory.Client.NoObf.PlayerCamera.OnBeforeRenderFrame3D(Single dt) in VintagestoryLib\Client\Render\PlayerCamera.cs:line 58
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 796
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 718
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/9/2023 11:47:02 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x6514d416
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x201c
Faulting application start time: 0x0x1da138f9e1d10c7
Faulting application path: C:\Users\b0bb0\AppData\Roaming\vintagestory19\Vintagestory.exe
Faulting module path: C:\Users\b0bb0\AppData\Roaming\vintagestory19\Lib\openal32.dll
Report Id: 81238484-f9cc-4e77-862c-d35c02e1e707
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/9/2023 11:37:30 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x6514d416
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x2ad0
Faulting application start time: 0x0x1da138f444e226c
Faulting application path: C:\Users\b0bb0\AppData\Roaming\vintagestory19\Vintagestory.exe
Faulting module path: C:\Users\b0bb0\AppData\Roaming\vintagestory19\Lib\openal32.dll
Report Id: 9c9517b6-8693-49ca-b014-c19d81b5f230
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/9/2023 11:33:21 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x6514d416
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x2220
Faulting application start time: 0x0x1da138eb5d8cfc2
Faulting application path: C:\Users\b0bb0\AppData\Roaming\vintagestory19\Vintagestory.exe
Faulting module path: C:\Users\b0bb0\AppData\Roaming\vintagestory19\Lib\openal32.dll
Report Id: 5f00250d-dacf-4313-bba6-86a1aa0452d1
Faulting package full name: 
Faulting package-relative application ID:  }

![2023-11-09_22-38-54](https://github.com/anegostudios/VintageStory-Issues/assets/117089510/23bf7d3a-6728-4f1b-a471-37e570ccb019)

![2023-11-10_00-16-43](https://github.com/anegostudios/VintageStory-Issues/assets/117089510/0c4dace5-ca3a-47e9-8af7-72cec9249f4b)

**Comment by Th3Dilli** [comment]
this should be fixed since pre 6

**Comment by TRex8319** [comment]
Danke! Yes all fixed.
