### ISSUE TITLE
smelted crucible causes crashes

### ISSUE THREAD

**Issue by barrowisp** [anegostudios/VintageStory-Issues#3206]
### Game Version

v1.18.15

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Selecting a smelted crucible causes crash to desktop.

I want to add itemcodes and blockcodes to the wiki.  As part of the process, I'm spot-checking id numbers in the Creative menu, and checking non-code names of items/blocks.  1 of the 3 crucible blockcodes causes a crash.  There seems to be no way to get the problematic block other than with `/giveblock` so it's probably not an issue many would encounter.

### How to reproduce

1) In an existing or new world, with at least 1 empty inventory slot, type `/giveblock game:crucible-smelted` and hit enter.  

A crucible icon appears in the hotbar, with the same dark appearance as a fired Crucible.  In the chat console the following message appears: "An Exception was thrown while executing Command: Object reference not set to an instance of an object.. Check error log for more detail."

2)  Mousing over the given `game:crucible-smelted` always produces a crash, whether by moving the pointer or using the mousewheel.  

Using the mousewheel to select other items in the hotbar produces no crash. 
The normal fired Crucible and Raw crucible do not cause crashes when acquired via `/giveblock`.

### Logs

[logs](https://gist.github.com/barrowisp/2af70d8b84ec7970c82e6cd6253d234a) because I don't know which parts are useful and which aren't

There's also a world I haven't been able to log back into.  Perhaps the smelted crucible is in the active hotbar slot, causing a crash before I see the world load:

Running on 64 bit Windows with 20354 MB RAM
Game Version: v1.18.15 (Stable)
11/6/2023 7:13:34 PM: Critical error occurred
Loaded Mods: game@1.18.15, creative@1.18.15, survival@1.18.15
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockSmeltedContainer.GetHeldItemName(ItemStack itemStack) in VSSurvivalMod\Block\BlockSmeltedContainer.cs:line 430
   at Vintagestory.Client.NoObf.HudHotbar.RecomposeActiveSlotHoverText(Int32 newSlotIndex) in VintagestoryLib\Client\Systems\Gui\Huds\HudHotbar.cs:line 522
   at Vintagestory.Client.NoObf.HudHotbar.<>c__DisplayClass42_0.<OnActiveSlotChanged>b__0() in VintagestoryLib\Client\Systems\Gui\Huds\HudHotbar.cs:line 461
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/6/2023 7:01:58 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF80C.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER174.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER194.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER192.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1B2.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_ae9784a4-8a72-4e98-a847-483a6612ee78

Analysis symbol: 
Rechecking for solution: 0
Report Id: f306de8f-2f76-43c0-a565-7c170ac64cb9
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 11/6/2023 7:01:55 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x5d64
Faulting application start time: 0x01da1125c5c54bfc
Faulting application path: C:\Users\Tiane\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Tiane\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: f306de8f-2f76-43c0-a565-7c170ac64cb9
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/6/2023 6:12:20 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8597.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8F9A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8FAB.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8FA9.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8FC9.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_58f981e2-1166-417b-8c1a-ca04b369cf08

Analysis symbol: 
Rechecking for solution: 0
Report Id: 26d45317-20f0-4a68-9512-5f5653430c88
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }

**Comment by barrowisp** [comment]
seems to be a non-issue in 1.19.8.  `crucible-smelted` no longer appears in the creative inventory.

**Comment by barrowisp** [comment]
seems to be a non-issue in 1.19.8.  `crucible-smelted` no longer appears in the creative inventory.
