### ISSUE TITLE
i can start the game

### ISSUE THREAD

**Issue by ivanprado12** [anegostudios/VintageStory-Issues#3209]
### Game Version

v1.18.14

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

the games crashes while opening 

### How to reproduce

Running on 64 bit Windows with 5992 MB RAM
Game Version: v1.18.14 (Stable)
11/8/2023 5:51:51 PM: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: OpenGL profile requested but WGL_ARB_create_context_profile is unavailable
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/8/2023 5:51:25 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2140627544722796143, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.14.0
P3: 64e841c5
P4: KERNELBASE.dll
P5: 10.0.19041.3570
P6: da674bb7
P7: e0434352
P8: 000000000002cf19
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7A3A.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER88F0.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER899D.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_169595e225b3a4af528f8836a0dc5d4c58e_e6f85633_d42f0a0a-53eb-40ce-a2e2-a4460b387ed7

Analysis symbol: 
Rechecking for solution: 0
Report Id: 87c9e289-fcb8-432b-b16e-e8ee4c04761a
Report Status: 268435456
Hashed bucket: d3d0ab1178ec461ebdb509690f9e6e6f
Cab Guid: 0 }
--------------
{ TimeGenerated = 11/8/2023 5:51:16 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.14.0, time stamp: 0x64e841c5
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3570, time stamp: 0xda674bb7
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process id: 0x570
Faulting application start time: 0x01da12287b5c8fd2
Faulting application path: C:\Users\ivan\Desktop\VIntage\Vintage Story\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 87c9e289-fcb8-432b-b16e-e8ee4c04761a
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/8/2023 5:51:15 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
CoreCLR Version: 7.0.1323.51816
.NET Version: 7.0.13
Description: The process was terminated due to an unhandled exception.
Exception Info: OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: You can only dispose windows on the main thread. The window needs to be disposed as it cannot safely be disposed in the finalizer.
   at OpenTK.Windowing.Desktop.NativeWindow.Dispose(Boolean disposing)
   at OpenTK.Windowing.Desktop.NativeWindow.Finalize()
 }

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Update drivers
