### ISSUE TITLE
Crash on start-up

### ISSUE THREAD

**Issue by scifiguy60** [anegostudios/VintageStory-Issues#3210]
### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Game consistently crashes on start-up.  This is a new issue.  Never completes loading.

### How to reproduce

Happens consistently on start-up

### Logs

```
Running on 64 bit Windows with 16196 MB RAM
Game Version: v1.18.15 (Stable)
11/8/2023 12:58:32 PM: Critical error occurred
Loaded Mods: fancysky@1.0.4, game@1.18.15, medievalexpansion@3.11.1, creative@1.18.15, survival@1.18.15
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.VanillaCookingRecipeNames.GetNameForIngredients(IWorldAccessor worldForResolve, String recipeCode, ItemStack[] stacks) in VSSurvivalMod\Systems\Cooking\CookingRecipe.cs:line 238
   at Vintagestory.GameContent.CookingRecipe.GetOutputName(IWorldAccessor worldForResolve, ItemStack[] inputStacks) in VSSurvivalMod\Systems\Cooking\CookingRecipe.cs:line 482
   at Vintagestory.GameContent.BlockEntityShelf.CrockInfoCompact(ItemSlot inSlot) in VSSurvivalMod\BlockEntity\BEShelf.cs:line 339
   at Vintagestory.GameContent.BlockEntityShelf.GetBlockInfo(IPlayer forPlayer, StringBuilder sb) in VSSurvivalMod\BlockEntity\BEShelf.cs:line 199
   at Vintagestory.API.Common.Block.GetPlacedBlockInfo(IWorldAccessor world, BlockPos pos, IPlayer forPlayer) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 2097
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.ComposeBlockInfoHud() in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 57
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.BlockInView() in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 190
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.Every15ms(Single dt) in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 156
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 59
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 711
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/7/2023 9:49:51 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.fbb780f8-a3f4-45e3-b52c-fa10982c59b2.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.55ce28b7-e711-4075-9125-16c0a42e3542.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a7d67ea9-db78-4c25-8610-0fa2a57e91c8.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.89a959ef-601f-422f-a11e-eb4d4704d5e2.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.417458b8-06bb-4302-b38e-a4c8a7a0d12a.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_77728d87-439a-493a-8c91-a190a62b6630

Analysis symbol: 
Rechecking for solution: 0
Report Id: 10c68fe2-ea3c-4d63-b877-06eea023dd92
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 11/7/2023 9:49:48 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x50ec
Faulting application start time: 0x0x1da11f62e6c346d
Faulting application path: D:\Vintagestory\Vintagestory.exe
Faulting module path: D:\Vintagestory\Lib\openal32.dll
Report Id: 10c68fe2-ea3c-4d63-b877-06eea023dd92
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/7/2023 9:43:37 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.de9b48fc-ee50-4dc4-b94c-b92162e853b6.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.301c1ffa-caf3-4237-9818-f9d422168928.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b83c0fca-b1c9-4ce0-97f4-1da9cce4676e.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.99f4ff15-8981-46e4-9181-50f1d5e93d6c.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.06ce1460-8854-4436-b666-87114a4e833e.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_03badf14-426d-415f-af13-a7577e8d7a6e

Analysis symbol: 
Rechecking for solution: 0
Report Id: e85a389f-2cc5-41d7-a044-d9e7a1f95f1e
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
```

**Comment by scifiguy60** [comment]
Removed all mods...still crashes.  See below:

Running on 64 bit Windows with 16196 MB RAM
Game Version: v1.18.15 (Stable)
11/8/2023 1:36:42 PM: Critical error occurred
Loaded Mods: game@1.18.15, creative@1.18.15, survival@1.18.15
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.VanillaCookingRecipeNames.GetNameForIngredients(IWorldAccessor worldForResolve, String recipeCode, ItemStack[] stacks) in VSSurvivalMod\Systems\Cooking\CookingRecipe.cs:line 238
   at Vintagestory.GameContent.CookingRecipe.GetOutputName(IWorldAccessor worldForResolve, ItemStack[] inputStacks) in VSSurvivalMod\Systems\Cooking\CookingRecipe.cs:line 482
   at Vintagestory.GameContent.BlockEntityShelf.CrockInfoCompact(ItemSlot inSlot) in VSSurvivalMod\BlockEntity\BEShelf.cs:line 339
   at Vintagestory.GameContent.BlockEntityShelf.GetBlockInfo(IPlayer forPlayer, StringBuilder sb) in VSSurvivalMod\BlockEntity\BEShelf.cs:line 199
   at Vintagestory.API.Common.Block.GetPlacedBlockInfo(IWorldAccessor world, BlockPos pos, IPlayer forPlayer) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 2097
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.ComposeBlockInfoHud() in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 57
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.BlockInView() in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 190
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.Every15ms(Single dt) in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 156
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 84
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 711
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/8/2023 1:35:31 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.914bdea4-da3a-4a9f-af19-e5356ca2b618.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_5ff48aeb-38b5-4fee-8162-d659b6b720e2

Analysis symbol: 
Rechecking for solution: 0
Report Id: 00457971-f57f-41e6-804b-00faa918b94d
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 11/8/2023 1:35:30 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_5ff48aeb-38b5-4fee-8162-d659b6b720e2

Analysis symbol: 
Rechecking for solution: 0
Report Id: 00457971-f57f-41e6-804b-00faa918b94d
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 11/8/2023 1:35:28 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x11d0
Faulting application start time: 0x0x1da127a4526a97d
Faulting application path: D:\Vintagestory\Vintagestory.exe
Faulting module path: D:\Vintagestory\Lib\openal32.dll
Report Id: 00457971-f57f-41e6-804b-00faa918b94d
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by scifiguy60** [comment]
It appears I can start a new game...but the previous game cannot be accessed

**Comment by Craluminum2413** [comment]
Closing due to inactivity
