### ISSUE TITLE
Game crashes on all saves and new game creation

### ISSUE THREAD

**Issue by Bulwark77** [anegostudios/VintageStory-Issues#3211]
I had the Carryon mod installed and when I went to pick up a container. It did not work. I thought it may need to be updated. Even though I had used it on this save before without any issues.
I updated to the version that is supposed to be good for my version of the game. 
NOW NONE of the save files work no matter what I do!!!!

Crash log file.

Running on 64 bit Windows with 32700 MB RAM
Game Version: v1.18.15 (Stable)
11/8/2023 6:43:26 PM: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.15, AMFinder@1.3.1, angelbelt@1.4.0, autosifter@1.1.0, backpackpackplus@1.0.3, bettercrates@1.6.0, BuggisRandomChanges@3.3.0, buildinggadgets@0.4.0, chiseltools@1.8.4, composter@1.0.4, craftingtable@0.4.0, EasyFruitTrees@1.0.1, extrachests@1.7.0, extraclayforming@1.0.0, FarmSurvival@1.3.0, FastPitkilns@1.0.0, fernslikegrass@1.0.0, FlexibleTools@2.1.0, HoneyPress@1.1.2, mcd1@1.0.0, moreclassestweak@1.2.5, moredrygrass@0.2.0, moremolds@1.4.12, MoreTreeSeeds@1.0.0, nightwatcher@1.4.0, nooffhandhunger@1.0.0, OresAPlenty@3.1.0, qptech@1.14.1, QuartzBlocks@1.1.0, roas@1.0.0, RockBlocks@1.0.0, simpleelevator@1.3.0, standardcrates@1.0.0, tprunes@1.0.8, vtpp@1.0.0, game@1.18.15, zoombuttonreborn@1.4.0, alloycalculator@1.0.0, animalcages@2.1.5, betterbloomeriesreborn@1.0.4, betterfirepit@1.1.0, commonlib@2.2.0, diamondcrate@1.0.2, expandedfoods@1.6.8, farmlanddropssoil@1.4.0, hudclock@3.3.0, sailboat@1.1.0, kegrevival@1.0.3, medievalexpansion@3.9.2, petai@1.7.2, claywheel@1.1.0, prospectorinfo@4.3.0, scarecrow@1.2.3, stillnecessaries@1.0.0, techmolds@1.0.0, temporalstormtimer@1.0.0, translocatorlocator@1.0.2, creative@1.18.15, survival@1.18.15, wildfarmingrevival@1.0.5, metalrecovery@0.1.18-rc.2, tradercamps@1.0.4, em@2.4.1, feverstonehorses@1.5.0, morecandles@1.1.3, simplewinddirection@1.0.2
System.Exception: Don't know how to instantiate collectible behavior of class 'Carryable' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateCollectibleBehavior(CollectibleObject collectible, String code) in VintagestoryLib\Common\ClassRegistry.cs:line 220
   at Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType packet, IWorldAccessor world, ClassRegistry registry) in VintagestoryLib\Common\Network\BlockTypeNet.cs:line 377
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateBlocks(Block[] blocks, Int32 start, Int32 maxCount) in VintagestoryLib\Client\Systems\Startup.cs:line 555
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadBlockTypes() in VintagestoryLib\Client\Systems\Startup.cs:line 363
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in VintagestoryLib\Client\Systems\Startup.cs:line 338
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 108
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by Craluminum2413** [comment]
Caused by Carry On or Carry Capacity mod
