### ISSUE TITLE
NullReferenceException 

### ISSUE THREAD

**Issue by Tromenos** [anegostudios/VintageStory-Issues#3217]
### Game Version

v1.18.15

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Sudden crash due to NullReferenceException

### How to reproduce

I don't know
(Maybe AUR build issue?)

### Logs

From client-crash.txt:
```Running on 64 bit Linux with 32036 MB RAM
Game Version: v1.18.15 (Stable)
11/12/2023 11:17:43AM: Critical error occurred
Loaded Mods: game@1.18.15, creative@1.18.15, survival@1.18.15
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Client.ModelDataPoolLocation.IsVisible(EnumFrustumCullMode mode, FrustumCulling culler) in VintagestoryApi\Client\MeshPool\MeshDataPool.cs:line 500
   at Vintagestory.API.Client.MeshDataPool.FrustumCull(FrustumCulling frustumCuller, EnumFrustumCullMode frustumCullMode) in VintagestoryApi\Client\MeshPool\MeshDataPool.cs:line 345
   at Vintagestory.API.Client.MeshDataPoolManager.Render(Vec3d playerpos, String originUniformName, EnumFrustumCullMode frustumCullMode) in VintagestoryApi\Client\MeshPool\MeshDataPoolManager.cs:line 113
   at Vintagestory.Client.NoObf.ChunkRenderer.RenderOpaque(Single dt) in VintagestoryLib\Client\Render\ChunkRenderer.cs:line 382
   at Vintagestory.Client.NoObf.SystemRenderTerrain.OnRenderOpaque(Single deltaTime) in VintagestoryLib\Client\Systems\Render\RenderTerrain.cs:line 117
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 790
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 796
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 712
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13327733/client-main.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/13327737/client-debug.txt)

**Comment by Craluminum2413** [comment]
Closing due to inactivity
