### ISSUE TITLE
Corrupted world after death

### ISSUE THREAD

**Issue by Zelger98** [anegostudios/VintageStory-Issues#3218]
### Game Version

v1.19.0-pre5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I was playing on my singleplayer world, then I accidentaly flew into the ground with my glider equiped and most likely died. I say most likely because upon impact with the ground my game crashed. When I relaunch the save,k the game instantly crashes upon loading the map. Crash report in the logs.

### Logs

Running on 64 bit Windows with 8130 MB RAM
Game Version: v1.19.0-pre.5 (Unstable)
2023-11-12 14:49:55: Critical error occurred
Loaded Mods: game@1.19.0-pre.5, creative@1.19.0-pre.5, survival@1.19.0-pre.5
System.IndexOutOfRangeException: MapRegion data, index was -2147483585 but length was 512
   at Vintagestory.API.Datastructures.IntDataMap2D.GetUnpaddedColorLerped(Single x, Single z) in VintagestoryApi\Datastructures\IntDataMap2D.cs:line 71
   at Vintagestory.GameContent.WeatherDataReaderBase.LoadLerp(Vec3d pos, Boolean useArgValues, Single lerpRainCloudOverlay, Single lerpRainOverlay, Single dt) in VSEssentials\Systems\Weather\WeatherDataReader.cs:line 247
   at Vintagestory.GameContent.WeatherDataReaderBase.LoadAdjacentSimsAndLerpValues(Vec3d pos, Boolean useArgValues, Single lerpRainCloudOverlay, Single lerpRainOverlay, Single dt) in VSEssentials\Systems\Weather\WeatherDataReader.cs:line 201
   at Vintagestory.GameContent.WeatherDataReaderPreLoad.LoadAdjacentSimsAndLerpValues(Vec3d pos, Single dt) in VSEssentials\Systems\Weather\WeatherDataReader.cs:line 72
   at Vintagestory.GameContent.WeatherSystemClient.OnRenderFrame(Single dt, EnumRenderStage stage) in VSEssentials\Systems\Weather\WeatherSystemClient.cs:line 130
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 199
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 793
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 835
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 717
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by lufog** [comment]
I have the same problem, I was flying on a glider and got stuck in the ground. Now, every time I log into the server, the game crashes.

```
Running on 64 bit Windows 10.0.22631.0 with 16297 MB RAM
Game Version: v1.19.0-rc.1 (Unstable)
12/27/2023 6:37:10 PM: Critical error occurred
Loaded Mods: game@1.19.0-rc.1, creative@1.19.0-rc.1, survival@1.19.0-rc.1
System.IndexOutOfRangeException: MapRegion data, index was -2147483585 but length was 512
   at Vintagestory.API.Datastructures.IntDataMap2D.GetUnpaddedColorLerped(Single x, Single z) in VintagestoryApi\Datastructures\IntDataMap2D.cs:line 71
   at Vintagestory.GameContent.WeatherDataReaderBase.LoadLerp(Vec3d pos, Boolean useArgValues, Single lerpRainCloudOverlay, Single lerpRainOverlay, Single dt) in VSEssentials\Systems\Weather\WeatherDataReader.cs:line 245
   at Vintagestory.GameContent.WeatherSystemClient.OnRenderFrame(Single dt, EnumRenderStage stage) in VSEssentials\Systems\Weather\WeatherSystemClient.cs:line 122
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 724
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/27/2023 6:36:17 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x33f0
Faulting application start time: 0x0x1da38da39e83129
Faulting application path: D:\Game Files\Vintage Story\Vintagestory.exe
Faulting module path: D:\Game Files\Vintage Story\Lib\openal32.dll
Report Id: ab1b2339-6563-4d9c-8496-7fa6d117c1aa
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/27/2023 6:33:22 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x351c
Faulting application start time: 0x0x1da38d9f7213d70
Faulting application path: D:\Game Files\Vintage Story\Vintagestory.exe
Faulting module path: D:\Game Files\Vintage Story\Lib\openal32.dll
Report Id: 0d77d924-0e4e-4b10-bbaa-7e37d78f97d9
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/27/2023 6:32:50 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x3024
Faulting application start time: 0x0x1da38d9e05bbef2
Faulting application path: D:\Game Files\Vintage Story\Vintagestory.exe
Faulting module path: D:\Game Files\Vintage Story\Lib\openal32.dll
Report Id: abe4c893-8888-4ae8-ab80-b1997152bb72
Faulting package full name: 
Faulting package-relative application ID:  }
```

**Comment by tyronx** [comment]
the glider crash is fixed, would still be interested in looking at that crash on load though - can you provide me with a savegame?

**Comment by Zelger98** [comment]
Sorry the world is long gone by now. I think this bug might be more potent
on lower end pc setups.

**Comment by Craluminum2413** [comment]
Closing due to inactivity
