### ISSUE TITLE
Crash while breaking chiseled ruin block

### ISSUE THREAD

**Issue by linaritara** [anegostudios/VintageStory-Issues#3220]
### Game Version

v1.19.0-pre5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Game crashed while breaking a chiseled ruin block (limestone, if that matters). Had broken 7 or 8 already in the session, not sure why this one caused a crash.

### How to reproduce

Break chiseled ruin blocks with hands.

### Logs

Running on 64 bit Windows with 12115 MB RAM
Game Version: v1.19.0-pre.5 (Unstable)
11/12/2023 10:51:39 AM: Critical error occurred
Loaded Mods: game@1.19.0-pre.5, creative@1.19.0-pre.5, survival@1.19.0-pre.5
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockMicroBlock.IsSoilNonSoilMix(BlockEntityMicroBlock be) in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 366
   at Vintagestory.GameContent.BlockMicroBlock.GetBlockMaterial(IBlockAccessor blockAccessor, BlockPos pos, ItemStack stack) in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 355
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 539
   at Vintagestory.API.Common.EntityPlayer.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 543
   at Vintagestory.Client.NoObf.ClientSystemEntities.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Entities.cs:line 99
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 718
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by linaritara** [comment]
Happened again on the same save, also with limestone cobble:

Running on 64 bit Windows with 12115 MB RAM
Game Version: v1.19.0-pre.5 (Unstable)
11/12/2023 1:06:42 PM: Critical error occurred
Loaded Mods: game@1.19.0-pre.5, creative@1.19.0-pre.5, survival@1.19.0-pre.5
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockMicroBlock.IsSoilNonSoilMix(BlockEntityMicroBlock be) in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 366
   at Vintagestory.GameContent.BlockMicroBlock.GetBlockMaterial(IBlockAccessor blockAccessor, BlockPos pos, ItemStack stack) in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 355
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 539
   at Vintagestory.API.Common.EntityPlayer.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 543
   at Vintagestory.Client.NoObf.ClientSystemEntities.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Entities.cs:line 99
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 718
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by TRex8319** [comment]
Theres also a similar crash with the microblock. Mine is related to fetching the sounds. Good luck! I sort of dont mess with the ruins at the moment.

**Comment by Th3Dilli** [comment]
this should be fixed since pre7
