### ISSUE TITLE
Cant not eat - 1.19.0 rev6

### ISSUE THREAD

**Issue by StrikerBAY** [anegostudios/VintageStory-Issues#3229]
### Game Version

1.19.0 pre6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Can't eat anymore

### How to reproduce

New game in vanilla - harvest some berries

### Logs

```Log```

**Comment by StrikerBAY** [comment]
15.11.2023 17:43:37 [Notification] Received level finalize
15.11.2023 17:43:38 [Error] Could not load sound
15.11.2023 17:43:38 [Error] Exception: The specified sound format is not supported.
   at Vintagestory.Client.AudioOpenAl.GetSoundFormat(Int32 channels, Int32 bits) in VintagestoryLib\Client\ClientPlatform\ClientNative\AudioOpenAl.cs:line 168
   at Vintagestory.Client.LoadedSoundNative.createSoundSource() in VintagestoryLib\Client\ClientPlatform\ClientNative\LoadedSound.cs:line 170
15.11.2023 17:43:38 [Notification] Loaded Shaderprogramm for render pass clouds.
15.11.2023 17:43:38 [Notification] Loading world map cache db...
15.11.2023 17:43:38 [Warning] ===============================================================
15.11.2023 17:43:38 [Warning] (x_x) Captured 2 issues during startup:
15.11.2023 17:43:38 [Error] Could not load sound
15.11.2023 17:43:38 [Error] Exception: The specified sound format is not supported.
   at Vintagestory.Client.AudioOpenAl.GetSoundFormat(Int32 channels, Int32 bits) in VintagestoryLib\Client\ClientPlatform\ClientNative\AudioOpenAl.cs:line 168
   at Vintagestory.Client.LoadedSoundNative.createSoundSource() in VintagestoryLib\Client\ClientPlatform\ClientNative\LoadedSound.cs:line 170
15.11.2023 17:43:38 [Warning] ===============================================================

**Comment by tyronx** [comment]
thanks for the report, the eating bug will be fixed in pre7.
as for the sound error, pre7 should provide more information to track that one down.
