### ISSUE TITLE
Game crash2

### ISSUE THREAD

**Issue by Vicgamer24** [anegostudios/VintageStory-Issues#3233]
### Game Version

v1.18.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Logs

```Running on 64 bit Windows with 4001 MB RAM
Game Version: v1.18.15 (Stable)
15/11/2023 07:42:42 p. m.: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: OpenGL profile requested but WGL_ARB_create_context_profile is unavailable
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings) in VintagestoryLib\Client\ClientPlatform\GameWindowNative.cs:line 15
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 273
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 15/11/2023 07:42:06 p. m., Site = , Source = Application Error, Message = Nombre de la aplicación con errores: Vintagestory.exe, versión: 1.18.15.0, marca de tiempo: 0x64e841c5
Nombre del módulo con errores: KERNELBASE.dll, versión: 10.0.19041.3636, marca de tiempo: 0x326edcef
Código de excepción: 0xe0434352
Desplazamiento de errores: 0x000000000002cf19
Identificador del proceso con errores: 0x22fc
Hora de inicio de la aplicación con errores: 0x01da182e153997ea
Ruta de acceso de la aplicación con errores: C:\Users\Patricia\AppData\Roaming\Vintagestory\Vintagestory.exe
Ruta de acceso del módulo con errores: C:\Windows\System32\KERNELBASE.dll
Identificador del informe: 475b25f2-5d06-441e-b0e8-e48be3890dd8
Nombre completo del paquete con errores: 
Identificador de aplicación relativa del paquete con errores:  }
--------------
{ TimeGenerated = 15/11/2023 07:42:06 p. m., Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
CoreCLR Version: 7.0.1023.36312
.NET Version: 7.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: You can only dispose windows on the main thread. The window needs to be disposed as it cannot safely be disposed in the finalizer.
   at OpenTK.Windowing.Desktop.NativeWindow.Dispose(Boolean disposing)
   at OpenTK.Windowing.Desktop.NativeWindow.Finalize()
 }
--------------
{ TimeGenerated = 15/11/2023 07:03:02 p. m., Site = , Source = Application Error, Message = Nombre de la aplicación con errores: Vintagestory.exe, versión: 1.18.15.0, marca de tiempo: 0x64e841c5
Nombre del módulo con errores: KERNELBASE.dll, versión: 10.0.19041.3636, marca de tiempo: 0x326edcef
Código de excepción: 0xe0434352
Desplazamiento de errores: 0x000000000002cf19
Identificador del proceso con errores: 0x1cec
Hora de inicio de la aplicación con errores: 0x01da182743573013
Ruta de acceso de la aplicación con errores: C:\Users\Patricia\AppData\Roaming\Vintagestory\Vintagestory.exe
Ruta de acceso del módulo con errores: C:\Windows\System32\KERNELBASE.dll
Identificador del informe: 5e6e444d-97b3-4175-911a-a23847884dc4
Nombre completo del paquete con errores: 
Identificador de aplicación relativa del paquete con errores:  }```

**Comment by Craluminum2413** [comment]
Update your graphics drivers
