### ISSUE TITLE
1.18.15 WorldEdit crash

### ISSUE THREAD

**Issue by max152309** [anegostudios/VintageStory-Issues#3236]
### Game Version

v1.18.15

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### How to reproduce

move this structure up/down with WorldEdit

### Screenshots

![crash](https://github.com/anegostudios/VintageStory-Issues/assets/43575349/2146f336-9bb6-4d4e-ae43-da9dc76b2d21)

### Logs

```
Running on 64 bit Linux with 31857 MB RAM
Game Version: v1.18.15 (Stable)
11/17/2023 8:06:21PM: Critical error occurred
Loaded Mods: game@1.18.15, creative@1.18.15, survival@1.18.15
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.Mechanics.BEBehaviorMPAngledGears.SetOrientations() in VSSurvivalMod\Systems\MechanicalPower\BlockEntityBehavior\BEBehaviorAngledGears.cs:line 70
   at Vintagestory.GameContent.Mechanics.BEBehaviorMPBase.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldAccessForResolve) in VSSurvivalMod\Systems\MechanicalPower\BlockEntityBehavior\BEBehaviorMPBase.cs:line 302
   at Vintagestory.GameContent.Mechanics.BEBehaviorMPAngledGears.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldAccessForResolve) in VSSurvivalMod\Systems\MechanicalPower\BlockEntityBehavior\BEBehaviorAngledGears.cs:line 357
   at Vintagestory.API.Common.BlockEntity.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldAccessForResolve) in VintagestoryApi\Common\Collectible\Block\BlockEntity.cs:line 302
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 408
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 423
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
