### ISSUE TITLE
[v1.19.0-pre.7] Crash when opening server settings in server management gui

### ISSUE THREAD

**Issue by sakari119** [anegostudios/VintageStory-Issues#3238]
```Running on 64 bit Windows with 64663 MB RAM
Game Version: v1.19.0-pre.7 (Unstable)
18/11/2023 3:42:44 PM: Critical error occurred
Loaded Mods: game@1.19.0-pre.7, creative@1.19.0-pre.7, survival@1.19.0-pre.7
System.InvalidCastException: Unable to cast object of type 'Vintagestory.API.Client.GuiElementTextInput' to type 'Vintagestory.API.Client.GuiElementTextArea'.
   at Vintagestory.API.Client.GuiComposerHelpers.GetTextArea(GuiComposer composer, String key) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementTextArea.cs:line 127
   at Vintagestory.Client.GuiScreenServerDashboard.onServerConfigReceived(EnumAuthServerResponse reqStatus, GameServerConfigResponse response) in VintagestoryLib\Client\MainMenu\Screens\HostedServer\GuiScreenServerConfig.cs:line 110
   at Vintagestory.Client.Util.ServerCtrlBackendInterface.<>c__DisplayClass18_1`1.<runAction>b__1() in VintagestoryLib\Client\Util\ServerCtrlBackend\ServerCtrlBackendInterface.cs:line 225
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by tyronx** [comment]
thanks for the report, this is fixed in rc.4
