### ISSUE TITLE
[1.19 pre7] crashs on opening mod manager

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#3239]
### Game Version

v1.19 pre7

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

I disabled all mods but getting this crash when opening modmanager

Works on 1.18.15

### Logs

```Running on 64 bit Windows with 32705 MB RAM
Game Version: v1.19.0-pre.7 (Unstable)
18.11.2023 10:56:12: Critical error occurred
Loaded Mods: game@1.19.0-pre.7, creative@1.19.0-pre.7, survival@1.19.0-pre.7
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.GuiElementModCell..ctor(ICoreClientAPI capi, ModCellEntry cell, ElementBounds bounds, IAsset warningIcon) in VintagestoryLib\Client\MainMenu\Screens\GuiElementModCell.cs:line 74
   at Vintagestory.Client.GuiScreenMods.createCellElem(ModCellEntry cell, ElementBounds bounds) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 176
   at Vintagestory.API.Client.GuiElementCellList`1.AddCell(T cell, Int32 afterPosition) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 204
   at Vintagestory.API.Client.GuiElementCellList`1.Initialize() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 106
   at Vintagestory.API.Client.GuiElementCellList`1.BeforeCalcBounds() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 140
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 365
   at Vintagestory.Client.GuiScreenMods.InitGui() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 139
   at Vintagestory.Client.GuiScreenMods..ctor(ScreenManager screenManager, GuiScreen parentScreen) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 24
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Vintagestory.Client.ScreenManager.LoadAndCacheScreen(Type screenType) in VintagestoryLib\Client\ScreenManager.cs:line 917
   at Vintagestory.Client.GuiCompositeMainMenuLeft.OnMods() in VintagestoryLib\Client\MainMenu\Composite\GuiCompositeMainMenuLeft.cs:line 303
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 304
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 714
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 290
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 445
   at Vintagestory.Client.GuiCompositeMainMenuLeft.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\MainMenu\Composite\GuiCompositeMainMenuLeft.cs:line 362
   at GuiScreen.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\MainMenu\Screens\Special\GuiScreen.cs:line 198
   at Vintagestory.Client.ScreenManager.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 883
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 213
   at OpenTK.Windowing.Desktop.NativeWindow.OnMouseUp(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.GuiElementModCell..ctor(ICoreClientAPI capi, ModCellEntry cell, ElementBounds bounds, IAsset warningIcon) in VintagestoryLib\Client\MainMenu\Screens\GuiElementModCell.cs:line 74
   at Vintagestory.Client.GuiScreenMods.createCellElem(ModCellEntry cell, ElementBounds bounds) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 176
   at Vintagestory.API.Client.GuiElementCellList`1.AddCell(T cell, Int32 afterPosition) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 204
   at Vintagestory.API.Client.GuiElementCellList`1.Initialize() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 106
   at Vintagestory.API.Client.GuiElementCellList`1.BeforeCalcBounds() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 140
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 365
   at Vintagestory.Client.GuiScreenMods.InitGui() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 139
   at Vintagestory.Client.GuiScreenMods..ctor(ScreenManager screenManager, GuiScreen parentScreen) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 24
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 13.11.2023 20:12:58, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.0.0, Zeitstempel: 0x6514d416
Name des fehlerhaften Moduls: coreclr.dll, Version: 7.0.1023.36312, Zeitstempel: 0x64b06d6c
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00000000001c98a6
ID des fehlerhaften Prozesses: 0x0x2c2c
Startzeit der fehlerhaften Anwendung: 0x0x1da166512df65e2
Pfad der fehlerhaften Anwendung: S:\VintageStoryv1.19\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.10\coreclr.dll
Berichtskennung: 07a65dce-822e-4a6e-9823-2675e7d3d285
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 13.11.2023 20:10:26, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.0.0, Zeitstempel: 0x6514d416
Name des fehlerhaften Moduls: coreclr.dll, Version: 7.0.1023.36312, Zeitstempel: 0x64b06d6c
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00000000001c98a6
ID des fehlerhaften Prozesses: 0x0xd34
Startzeit der fehlerhaften Anwendung: 0x0x1da1662d25e437f
Pfad der fehlerhaften Anwendung: S:\VintageStoryv1.19\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.10\coreclr.dll
Berichtskennung: d9aae473-cf2f-4e12-a522-925534535968
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 30.10.2023 11:54:00, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.0.0, Zeitstempel: 0x6514d416
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x0x2e40
Startzeit der fehlerhaften Anwendung: 0x0x1da0b1f437d7b03
Pfad der fehlerhaften Anwendung: S:\VintageStoryv1.19\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: S:\VintageStoryv1.19\Vintagestory\Lib\openal32.dll
Berichtskennung: 2f259017-7dba-4632-a19f-65af7cf33913
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }```

**Comment by AreYSerious** [comment]
Crashes on 1.19 pre 6 aswell


Works on 1.19 pre 5 tho and earlier

**Comment by Craluminum2413** [comment]
It happens when there are empty folders

**Comment by AreYSerious** [comment]
But why was this added? Was this on purpose had no issues yet.
And otherwise might be good to add a error message or something

**Comment by AreYSerious** [comment]
I have no empty folders in the mods folder BTW.
I just have a archive folder which I dump all my mods into and which wasn't loaded in all the previous versions

**Comment by Craluminum2413** [comment]
Well it crashes when there is archive or folder with no modinfo

**Comment by Hogopillis** [comment]
yeah I have the same issue

**Comment by AreYSerious** [comment]
I wana point out removing my archive folder which wasn't a correct mod but loaded in every version before and just disable it. With it removed it now works

**Comment by Th3Dilli** [comment]
this will be fixed with the next version 
ty
