### ISSUE TITLE
Crashed when applying rope to oak fence

### ISSUE THREAD

**Issue by OriginalGulli** [anegostudios/VintageStory-Issues#3246]
### Game Version

v1.18.15

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Was in a creative world where i turned off instability which has been working fine. Until i added rope onto a fence with rope already fastened to it

### How to reproduce

Place fence 2 fences 4 blocks away from eachother, attatched to the side of a log. Apply rope to the 2 fences then apply rope to the original fencepost

### Logs

```Log```
Running on 64 bit Windows with 32709 MB RAM
Game Version: v1.18.15 (Stable)
21/11/2023 00:53:30: Critical error occurred
Loaded Mods: game@1.18.15, creative@1.18.15, survival@1.18.15
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ClothPoint.PinTo(Entity toEntity, Vec3f pinOffset) in VSEssentials\Systems\Cloth\ClothPoint.cs:line 101
   at Vintagestory.GameContent.BlockBehaviorRopeTieable.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel, EnumHandling& handling) in VSEssentials\BlockBehavior\BehaviorRopeTieable.cs:line 63
   at Vintagestory.API.Common.Block.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 1328
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 888
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 447
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 92
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 790
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 983
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 18/11/2023 20:24:09, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9B32.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9F4A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9F5B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9F59.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9F79.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_fbc615fc-b723-407c-94f6-f69597629d88

Analysis symbol: 
Rechecking for solution: 0
Report Id: f261bb33-a6a2-4b5e-b255-bf122b4e9cc7
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 18/11/2023 20:24:06, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x6340
Faulting application start time: 0x01da1a54f1816b49
Faulting application path: C:\Users\gulli\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\gulli\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report ID: f261bb33-a6a2-4b5e-b255-bf122b4e9cc7
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 18/11/2023 01:21:00, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6F1.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAAB.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAAC.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAAA.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERACA.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_824b4587-2eb3-4415-b7f5-97cbb65f2f84

Analysis symbol: 
Rechecking for solution: 0
Report Id: c4007432-1d23-427a-9743-bf733389bba5
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }

**Comment by RedramVS** [comment]
I could not reproduce this, but regardless, the attaching of ropes to fences is part of an unfinished feature, that'd I'd suggest be disabled for now.

**Comment by CookieBoy21** [comment]
It's look like devs add new feature, but I think this issue can be close because there is no longer crash after use rope on fence. I tested it in v1.19.7 (Stable).

<img width="1280" alt="Vintagestory Screenshot 2024 04 21 - 18 30 35 72" src="https://github.com/anegostudios/VintageStory-Issues/assets/132950198/6301da4a-4201-42a0-ba1c-7fc556584046">

<img width="1280" alt="Vintagestory Screenshot 2024 04 21 - 18 30 53 41" src="https://github.com/anegostudios/VintageStory-Issues/assets/132950198/0ac6d45f-6bcc-432b-a9a4-da5b0c29818c">
