### ISSUE TITLE
1.19.0-pre.7 Evil Bamboo

### ISSUE THREAD

**Issue by Knight1400** [anegostudios/VintageStory-Issues#3247]
### Game Version

1.19.0-pre.7

### Platform

Mac

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

trying to break bamboo with an axe caused crashes

### How to reproduce

Slap a bamboo tree with an axe

### Screenshots

![VSCrashReporter_gRHlhXoU0M](https://github.com/anegostudios/VintageStory-Issues/assets/151706160/456c7838-aa95-45f6-a722-c8c814bae5a7)
![Vintagestory_u3JNQt3K5e](https://github.com/anegostudios/VintageStory-Issues/assets/151706160/a8cd9a57-f2e9-412d-8a31-2eef7bbcba0e)

### Logs

Running on 64 bit Windows with 65454 MB RAM
Game Version: v1.19.0-pre.7 (Unstable)
11/21/2023 8:19:04 PM: Critical error occurred
Loaded Mods: game@1.19.0-pre.7, creative@1.19.0-pre.7, survival@1.19.0-pre.7
System.FormatException: Input string was not in a correct format.
   at System.Text.ValueStringBuilder.ThrowFormatInvalidString()
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.Format(String format, Object[] args)
   at Vintagestory.GameContent.ErrorReporter.Logger_EntryAdded(EnumLogType logType, String message, Object[] args) in VSEssentials\Systems\ErrorReporter.cs:line 170
   at Vintagestory.API.Common.LoggerBase.Error(String format, Object[] args) in VintagestoryApi\Common\API\ILogger.cs:line 237
   at Vintagestory.Client.NoObf.SystemRenderDecals.tesselateBlockDecal(Int32 blockId) in VintagestoryLib\Client\Systems\Render\RenderDecals.cs:line 103
   at Vintagestory.Client.NoObf.SystemRenderDecals.UpdateDecal(BlockDecal decal) in VintagestoryLib\Client\Systems\Render\RenderDecals.cs:line 275
   at Vintagestory.Client.NoObf.SystemRenderDecals.AddBlockBreakDecal(BlockPos pos, Int32 stage) in VintagestoryLib\Client\Systems\Render\RenderDecals.cs:line 237
   at Vintagestory.Client.NoObf.SystemRenderDecals.OnPlayerBreakingBlock(BlockDamage blockDamage) in VintagestoryLib\Client\Systems\Render\RenderDecals.cs:line 201
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockBreaking(BlockDamage blockDamage) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 376
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 803
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 604
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.UpdatePicking(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 232
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 84
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 82
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 199
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 793
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 985
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 241
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 11/21/2023 6:38:43 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x6514d416
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x3030
Faulting application start time: 0x01da1cecf1a5cab8
Faulting application path: D:\Vintage Story\Vintagestory\Vintagestory.exe
Faulting module path: D:\Vintage Story\Vintagestory\Lib\openal32.dll
Report Id: ca3e3f0b-5e43-4faf-bbde-d8f649e9b9a8
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by RedramVS** [comment]
Confirmed.  It is specific to green bamboo only, brown bamboo is fine.

**Comment by Th3Dilli** [comment]
ty, fixed with the next version
