### ISSUE TITLE
Crashes when burning lots of vegetation and objets

### ISSUE THREAD

**Issue by Volks64** [anegostudios/VintageStory-Issues#3266]
### Game Version

v.1.19.0-pre7

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

When burning lots of vegetation (Making clay bowl for exemple) it often crash. It's quite consistent actually

### How to reproduce

When burning lots of vegetation

### Logs

Running on 64 bit Windows with 32174 MB RAM
Game Version: v1.19.0-pre.7 (Unstable)
2023-11-30 9:44:33 PM: Critical error occurred
Loaded Mods: game@1.19.0-pre.7, creative@1.19.0-pre.7, survival@1.19.0-pre.7
System.OutOfMemoryException: Either the graphics card or the OS ran out of memory! Please close other programs and reduce your view distance to prevent the game from crashing.
   at Vintagestory.Client.NoObf.ClientPlatformWindows.CheckGlErrorAlways(String errmsg) in VintagestoryLib\Client\ClientPlatform\GLImpl.cs:line 75
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 2023-11-30 9:40:33 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x6514d416
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x28dc
Faulting application start time: 0x01da23ffa3a57441
Faulting application path: C:\Users\Volkie\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Volkie\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report ID: cfa66fbf-3420-4486-8256-2dd80cf56c20
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
#1712

**Comment by Craluminum2413** [comment]
Closing due to inactivity
