### ISSUE TITLE
Crash When Deleting Prospecting map Markers

### ISSUE THREAD

**Issue by Dalorend** [anegostudios/VintageStory-Issues#3271]
### Game Version

v1.19.0-pre.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Attempted to delete 3 closely grouped prospecting markers. crashed on the third one.

### Logs

```Log```
Running on 64 bit Windows with 16313 MB RAM
Game Version: v1.19.0-pre.5 (Unstable)
3/12/2023 4:26:46 PM: Critical error occurred
Loaded Mods: game@1.19.0-pre.5, creative@1.19.0-pre.5, survival@1.19.0-pre.5
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at Vintagestory.GameContent.OreMapLayer.Delete(IPlayer player, Int32 waypointIndex) in VSSurvivalMod\Systems\Prospecting\OreMapLayer\OreMapLayer.cs:line 269
   at Vintagestory.GameContent.OreMapComponent.onConfirmDone(Boolean confirm) in VSSurvivalMod\Systems\Prospecting\OreMapLayer\OreMapComponent.cs:line 135
   at Vintagestory.API.Client.GuiDialogConfirm.<Compose>b__7_1() in VintagestoryApi\Client\UI\Dialog\GuiDialogConfirm.cs:line 45
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 304
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 293
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 449
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 578
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 412
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1867
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 210
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 9/11/2023 10:00:08 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x6514d416
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x83b4
Faulting application start time: 0x01da12ed89cdf365
Faulting application path: C:\Users\Speedy_SoB\AppData\Roaming\VintagestoryBeta\Vintagestory.exe
Faulting module path: C:\Users\Speedy_SoB\AppData\Roaming\VintagestoryBeta\Lib\openal32.dll
Report Id: 5dcb7fc8-94c4-428f-a12c-38cf7bb6ead8
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 8/11/2023 6:50:24 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x6514d416
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x863c
Faulting application start time: 0x01da121811fb2646
Faulting application path: C:\Users\Speedy_SoB\AppData\Roaming\VintagestoryBeta\Vintagestory.exe
Faulting module path: C:\Users\Speedy_SoB\AppData\Roaming\VintagestoryBeta\Lib\openal32.dll
Report Id: 382321ef-1f57-43cd-aaf2-e27fb2b96c9d
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 8/11/2023 6:47:52 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x6514d416
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x8054
Faulting application start time: 0x01da1217cb04a6fd
Faulting application path: C:\Users\Speedy_SoB\AppData\Roaming\VintagestoryBeta\Vintagestory.exe
Faulting module path: C:\Users\Speedy_SoB\AppData\Roaming\VintagestoryBeta\Lib\openal32.dll
Report Id: 7d6e41ee-58c2-4b02-8a52-74643edd1042
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Does it happen in pre.7?

**Comment by Jceb1** [comment]
crashes on pre.7 and pre.8 aswell
I tried deleting a single marker and nothing happened, tried it again and that's when the game crashed

here's my crash log

**log**
Running on 64 bit Windows with 16326 MB RAM
Game Version: v1.19.0-pre.8 (Unstable)
12/3/2023 9:36:51 PM: Critical error occurred
Loaded Mods: game@1.19.0-pre.8, creative@1.19.0-pre.8, survival@1.19.0-pre.8
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at Vintagestory.GameContent.OreMapLayer.Delete(IPlayer player, Int32 waypointIndex) in VSSurvivalMod\Systems\Prospecting\OreMapLayer\OreMapLayer.cs:line 269
   at Vintagestory.GameContent.OreMapComponent.onConfirmDone(Boolean confirm) in VSSurvivalMod\Systems\Prospecting\OreMapLayer\OreMapComponent.cs:line 134
   at Vintagestory.API.Client.GuiDialogConfirm.<Compose>b__7_1() in VintagestoryApi\Client\UI\Dialog\GuiDialogConfirm.cs:line 45
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 317
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 307
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 449
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 583
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 415
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1863
   at Vintagestory.Client.GuiScreenRunningGame.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 349
   at Vintagestory.Client.ScreenManager.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 889
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 213
   at OpenTK.Windowing.Desktop.NativeWindow.OnMouseUp(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 12/3/2023 7:50:27 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x6514d416
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x3618
Faulting application start time: 0x01da2615b8d4a65a
Faulting application path: C:\Users\a\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\a\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: a1739a33-ef3a-406a-b393-43adf3be5631
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by RedramVS** [comment]
This should be fixed in pre10
