### ISSUE TITLE
[v1.19-pre.7/8] Blocks with question marks in ruins

### ISSUE THREAD

**Issue by sk4r** [anegostudios/VintageStory-Issues#3274]
### Game Version

v1.19.0-pre.8

### Platform

Linux

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

In survival mode started in v1.19.0-pre.7, then upgraded to v1.19.0-pre.8, I found ruins with some blocks marked with `?`. Breaking them crashed the game.

I recreated the same world seed but the ruins look fine.

Is there a way to regenerate them properly?

### Screenshots

![2023-12-03_19-22-42](https://github.com/anegostudios/VintageStory-Issues/assets/19878249/c078b07d-7a75-49fe-acb5-a5432c8cca80)

![2023-12-03_19-32-08](https://github.com/anegostudios/VintageStory-Issues/assets/19878249/4e7048f9-0238-47eb-9ed3-1cfb87bad044)

### Logs

```
Running on 64 bit Linux with 39446 MB RAM
Game Version: v1.19.0-pre.8 (Unstable)
12/3/2023 7:23:07PM: Critical error occurred
Loaded Mods: game@1.19.0-pre.8, creative@1.19.0-pre.8, survival@1.19.0-pre.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockMicroBlock.TryToRemoveSoilFirst(IWorldAccessor world, BlockPos pos, IPlayer byPlayer) in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 503
   at Vintagestory.GameContent.BlockMicroBlock.OnBlockBroken(IWorldAccessor world, BlockPos pos, IPlayer byPlayer, Single dropQuantityMultiplier) in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 487
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryDestroyBlock(BlockSelection blockSelection) in VintagestoryLib\Client\ClientMain.cs:line 1687
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 802
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 451
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 96
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1006
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by tyronx** [comment]
the crash is fixed, but the appearence of these blocks is not - its been difficult to find a reproducible case and might have been fixed already. Please let us know if this still appears in rc.4
