### ISSUE TITLE
[v1.19.0-pre.8] System.Exception: Max joint cap of 36 reached

### ISSUE THREAD

**Issue by AncletYinglet** [anegostudios/VintageStory-Issues#3276]
### Game Version

v1.19.0-pre.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Logs

```Running on 64 bit Windows with 16335 MB RAM
Game Version: v1.19.0-pre.8 (Unstable)
12/3/2023 9:12:00 PM: Critical error occurred
Loaded Mods: game@1.19.0-pre.8, creative@1.19.0-pre.8, survival@1.19.0-pre.8
System.Exception: Max joint cap of 36 reached, needs to be at least 36. In clientsettings.json, please try increasing the "maxAnimatedElements": setting to 46.  This works for most GPUs.  Otherwise you might need to disable the creature.
   at Vintagestory.API.Common.Animation.GenerateAllFrames(ShapeElement[] rootElements, Dictionary`2 jointsById, Boolean recursive) in VintagestoryApi\Common\Model\Animation\Animation.cs:line 97
   at Vintagestory.API.Common.ClientAnimator.AnimNowActive(RunningAnimation anim, AnimationMetaData animData) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 225
   at Vintagestory.API.Common.AnimatorBase.OnFrame(Dictionary`2 activeAnimationsByAnimCode, Single dt) in VintagestoryApi\Common\Model\Animation\AnimatorBase.cs:line 115
   at Vintagestory.API.Common.AnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Model\Animation\AnimationManager.cs:line 347
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 724
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Craluminum2413** [comment]
Try this:
`In clientsettings.json, please try increasing the "maxAnimatedElements": setting to 46`

**Comment by AncletYinglet** [comment]
> Try this: `In clientsettings.json, please try increasing the "maxAnimatedElements": setting to 46`

Right, yeah that worked. Sorry, I should've read the log a little more closely haha.

**Comment by RedramVS** [comment]
The next update should hopefully automatically update everyone's clientsettings to the correct number, hopefully.
