### ISSUE TITLE
The game wont start

### ISSUE THREAD

**Issue by dann1kid** [anegostudios/VintageStory-Issues#3279]
### Game Version

1.18.15

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Just stopped running. After reinstall too

### Logs

```Game Version: v1.18.15 (Stable)
04.12.2023 18:22:13: Critical error occurred
Loaded Mods: game@1.18.15, creative@1.18.15, survival@1.18.15
System.Exception: GL_INVALID_OPERATION error generated. The required buffer is missing.
   at Vintagestory.Client.NoObf.ClientPlatformWindows.DebugCallback(DebugSource source, DebugType type, Int32 id, DebugSeverity severity, Int32 length, IntPtr message, IntPtr userParam) in VintagestoryLib\Client\ClientPlatform\GLFramebuffer.cs:line 1270
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwSwapBuffers(Window* window)
   at OpenTK.Windowing.Desktop.GLFWGraphicsContext.SwapBuffers()
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93```

**Comment by dann1kid** [comment]
Fixed by update graphics driver.

**Comment by Craluminum2413** [comment]
Closing due to inactivity
