### ISSUE TITLE
Not starting :(

### ISSUE THREAD

**Issue by LionsFace** [anegostudios/VintageStory-Issues#3282]
### Platform

Windows

### Modded

Modded

### SP/MP

None

### Description

Running on 64 bit Windows with 7528 MB RAM
Game Version: v1.18.15 (Stable)
12/5/2023 8:20:29 PM: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: The driver does not appear to support OpenGL
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings) in VintagestoryLib\Client\ClientPlatform\GameWindowNative.cs:line 15
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 273
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/4/2023 5:10:20 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7baa571c-7792-42e7-8329-2964214f1804.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.836563d1-56d4-474e-b141-88166853df67.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c3d0de0b-a47e-4a36-b48c-27e316f7a2d7.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.3838e4e9-5104-4d99-94d9-0e6b1fe40e28.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9b84000e-dd08-494b-b68c-2b43299e7f6f.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_43a2ceaa-14ab-431a-aa23-43bdc50c0487

Analysis symbol: 
Rechecking for solution: 0
Report Id: 7cdf6618-07b5-4367-82c3-2824ebe6613f
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 12/4/2023 5:10:15 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x62e0
Faulting application start time: 0x0x1da2710453b2cf8
Faulting application path: C:\Users\aaron\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\aaron\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 7cdf6618-07b5-4367-82c3-2824ebe6613f
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/4/2023 4:16:18 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.18.15.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 }

### Logs

Running on 64 bit Windows with 7528 MB RAM
Game Version: v1.18.15 (Stable)
12/5/2023 8:20:29 PM: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: The driver does not appear to support OpenGL
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings) in VintagestoryLib\Client\ClientPlatform\GameWindowNative.cs:line 15
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 273
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/4/2023 5:10:20 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7baa571c-7792-42e7-8329-2964214f1804.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.836563d1-56d4-474e-b141-88166853df67.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c3d0de0b-a47e-4a36-b48c-27e316f7a2d7.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.3838e4e9-5104-4d99-94d9-0e6b1fe40e28.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9b84000e-dd08-494b-b68c-2b43299e7f6f.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_43a2ceaa-14ab-431a-aa23-43bdc50c0487

Analysis symbol: 
Rechecking for solution: 0
Report Id: 7cdf6618-07b5-4367-82c3-2824ebe6613f
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 12/4/2023 5:10:15 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x62e0
Faulting application start time: 0x0x1da2710453b2cf8
Faulting application path: C:\Users\aaron\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\aaron\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 7cdf6618-07b5-4367-82c3-2824ebe6613f
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/4/2023 4:16:18 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.18.15.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 }

**Comment by Craluminum2413** [comment]
Update your graphics drivers
