### ISSUE TITLE
can't open my mods tab to try disabling some mods after updating to a test version

### ISSUE THREAD

**Issue by Torisk-Ablinsky** [anegostudios/VintageStory-Issues#3287]
### Game Version

1.19.0 pre-8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I updated my game to Pre-8 of 1.19 and.. let's just say the mods list crashes the game if you updated with mods enabled

### How to reproduce

1. Update to 1.19 pre-8 when you have mods installed and enabled (Might not be required, I don't have another computer to test it with)
2. click the button that takes you to the mod enable/disable menu..

### Logs

Running on 64 bit Windows with 3534 MB RAM
Game Version: v1.19.0-pre.8 (Unstable)
12/8/2023 1:07:45 PM: Critical error occurred
Loaded Mods: armordurabilityiix@1.0.2, ancienttools@1.5.4, armoroverhaulsuite@1.0.0, awearablelight@1.0.3, cebbyseeds@1.0.0, coppercoldforging1@1.0.1, hqzlights@1.1.0, easyjam@1.0.0, fireclayfrompanning@1.0.0, capreolinae@1.0.1, immersivecorpsedrop@1.0.1, reducedarmornegatives@1.0.4, materialaging@1.0.0, moreflaxloot@1.0.1, nomolding@2.0.1, ragnamans-seeds-from-crops-recipes@1.0.0, RangedWeapons@0.4.6, samshumcreat@0.0.1, SmallWindows@1.2.1, temperaturescales@1.0.1, game@1.19.0-pre.8, woodmallet@1.0.1, alloycalculator@1.0.0, betterfirepit@1.1.1, blacksmithgloves@1.0.1, carryon@1.2.0, commonlib@2.0.3, conquest@0.0.18, fenceclimbable@1.0.0, flintchisel@1.0.2, kilntimeviewer@1.0.0, metaltongs@1.0.1, morepiles@1.3.0, petai@1.6.0, pei@1.3.0, primitivetools@1.3.1, resmeltableslight@1.0.0, seraphclass@1.0.0, seraphfaces@1.2.0, statushud@1.4.2, stickscrafting@1.0.16, tablet@0.0.2, creative@1.19.0-pre.8, survival@1.19.0-pre.8, betterbamboo@1.0.2, extraoverlays@1.3.1, mcbpicks@1.1.1, RelightableTorch@1.1.0, rifteye@0.1.0, wolftaming@1.6.0
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.GuiElementModCell..ctor(ICoreClientAPI capi, ModCellEntry cell, ElementBounds bounds, IAsset warningIcon) in VintagestoryLib\Client\MainMenu\Screens\GuiElementModCell.cs:line 74
   at Vintagestory.Client.GuiScreenMods.createCellElem(ModCellEntry cell, ElementBounds bounds) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 176
   at Vintagestory.API.Client.GuiElementCellList`1.AddCell(T cell, Int32 afterPosition) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 204
   at Vintagestory.API.Client.GuiElementCellList`1.Initialize() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 106
   at Vintagestory.API.Client.GuiElementCellList`1.BeforeCalcBounds() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 140
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 365
   at Vintagestory.Client.GuiScreenMods.InitGui() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 139
   at Vintagestory.Client.GuiScreenMods..ctor(ScreenManager screenManager, GuiScreen parentScreen) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 24
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Vintagestory.Client.ScreenManager.LoadAndCacheScreen(Type screenType) in VintagestoryLib\Client\ScreenManager.cs:line 923
   at Vintagestory.Client.GuiCompositeMainMenuLeft.OnMods() in VintagestoryLib\Client\MainMenu\Composite\GuiCompositeMainMenuLeft.cs:line 301
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 317
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 310
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 449
   at Vintagestory.Client.GuiCompositeMainMenuLeft.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\MainMenu\Composite\GuiCompositeMainMenuLeft.cs:line 360
   at GuiScreen.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\MainMenu\Screens\Special\GuiScreen.cs:line 198
   at Vintagestory.Client.ScreenManager.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 889
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 213
   at OpenTK.Windowing.Desktop.NativeWindow.OnMouseUp(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.GuiElementModCell..ctor(ICoreClientAPI capi, ModCellEntry cell, ElementBounds bounds, IAsset warningIcon) in VintagestoryLib\Client\MainMenu\Screens\GuiElementModCell.cs:line 74
   at Vintagestory.Client.GuiScreenMods.createCellElem(ModCellEntry cell, ElementBounds bounds) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 176
   at Vintagestory.API.Client.GuiElementCellList`1.AddCell(T cell, Int32 afterPosition) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 204
   at Vintagestory.API.Client.GuiElementCellList`1.Initialize() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 106
   at Vintagestory.API.Client.GuiElementCellList`1.BeforeCalcBounds() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 140
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 365
   at Vintagestory.Client.GuiScreenMods.InitGui() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 139
   at Vintagestory.Client.GuiScreenMods..ctor(ScreenManager screenManager, GuiScreen parentScreen) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 24
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

**Comment by Craluminum2413** [comment]
Remove any folders or archives that contain mods

**Comment by Craluminum2413** [comment]
Fixed in v1.19.0-rc.1
