### ISSUE TITLE
[v1.19.0-pre.9] Unhandled exception while harvesting creature

### ISSUE THREAD

**Issue by AncletYinglet** [anegostudios/VintageStory-Issues#3289]
### Game Version

v1.19.0-pre.9

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Harvesting creatures (so far encountered: drifter, bear) in multiplayer environment leads to throwing an exception and disconnection from the server.

### How to reproduce

- Join multiplayer session
- Kill a creature
- Harvest with knife

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/148595378/608ed342-3f3c-4149-9f10-3a3fe800a2bc)

### Logs

```
8.12.2023 19:33:05 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorHarvestable.generateDrops(IPlayer byPlayer, Single dropQuantityMultiplier) in VSEssentials\Entity\Behavior\BehaviorHarvestable.cs:line 421
   at Vintagestory.GameContent.EntityBehaviorHarvestable.SetHarvested(IPlayer byPlayer, Single dropQuantityMultiplier) in VSEssentials\Entity\Behavior\BehaviorHarvestable.cs:line 377
   at Vintagestory.GameContent.ItemKnife.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel) in VSSurvivalMod\Item\ItemKnife.cs:line 244
   at Vintagestory.Server.ServerSystemInventory.HandleHandInteraction(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\Inventory.cs:line 252
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\ServerMainNetworking.cs:line 138

**Comment by RedramVS** [comment]
This will be fixed in pre10
