### ISSUE TITLE
Mod Maker error

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#3300]
### Game Version

1.19.0-pre.9

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Mod Maker does not seem to work, see log

### Logs

```Detected game version is 1.19.0-pre.9. Hit enter if that is correct or type in actual version
Version [1.19.0-pre.9]:
Modded folder is C:\Users\Kai\AppData\Roaming\Vintagestory\assets
No cached data found at C:\Users\Kai\AppData\Local\Temp\VintageStoryModMaker\1.19.0-pre.9\assets.
Downloading vanilla assets for v1.19.0-pre.9...
Exception thrown trying to extract a mod :<
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'System.Collections.Generic.Dictionary`2[System.String,Vintagestory.API.Net.GameReleaseVersion]' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at ModMaker.ModMaker.EnsureAssetsAvailable(String vanillaAssetsFolder) in C:\Users\Tyron\Documents\vintagestory\game\ModMaker\ModMaker.cs:line 293
   at ModMaker.ModMaker.Run(String[] args) in C:\Users\Tyron\Documents\vintagestory\game\ModMaker\ModMaker.cs:line 57```

**Comment by Craluminum2413** [comment]
You most likely have broken syntax
