### ISSUE TITLE
Chiseling collider cubes after rotating them can sometimes crash the game

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#3301]
### Game Version

1.19.0-pre9

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

This bug has been around for a while.

Chiseling collider blocks after rotating them (or chisel them first, then rotate, then chisel again) can result in the chisel performing the wrong action (like selecting the chisel function will still rotate the cube nonetheless) and eventually crash the game sooner or later. May also be a problem with other block types.

### Logs

```Running on 64 bit Windows with 32723 MB RAM
Game Version: v1.19.0-pre.9 (Unstable)
11.12.2023 10:39:50: Critical error occurred
Loaded Mods: game@1.19.0-pre.9, creative@1.19.0-pre.9, survival@1.19.0-pre.9, cob@1.5.3, cobserver@1.0.0
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer)
   at Vintagestory.GameContent.BlockEntityMicroBlock.getMajorityMaterial(List`1 voxelCuboids, Int32[] blockIds, ActionBoolReturn`1 filterblockId)
   at Vintagestory.GameContent.BlockMicroBlock.GetRandomColor(ICoreClientAPI capi, BlockPos pos, BlockFacing facing, Int32 rndIndex) in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 627
   at Vintagestory.API.Common.BlockBreakingParticleProps.GetRgbaColor(ICoreClientAPI capi) in VintagestoryApi\Common\Particle\CollectibleParticleProperties.cs:line 39
   at Vintagestory.Client.NoObf.ParticlePoolQuads.SpawnParticles(IParticlePropertiesProvider particleProperties) in VintagestoryLib\Client\Systems\Render\Particle\ParticlePoolQuads.cs:line 209
   at Vintagestory.Client.NoObf.ParticleManager.SpawnParticles(IParticlePropertiesProvider properties) in VintagestoryLib\Client\Util\ParticleManager.cs:line 91
   at Vintagestory.API.Common.Block.SpawnBlockBrokenParticles(BlockPos pos) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 1058
   at Vintagestory.API.Common.Block.OnBlockBroken(IWorldAccessor world, BlockPos pos, IPlayer byPlayer, Single dropQuantityMultiplier) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 1043
   at Vintagestory.GameContent.BlockMicroBlock.OnBlockBroken(IWorldAccessor world, BlockPos pos, IPlayer byPlayer, Single dropQuantityMultiplier) in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 509
   at Vintagestory.API.Common.CollectibleObject.OnBlockBrokenWith(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, BlockSelection blockSel, Single dropQuantityMultiplier) in VintagestoryApi\Common\Collectible\Collectible.cs:line 581
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryDestroyBlock(BlockSelection blockSelection) in VintagestoryLib\Client\ClientMain.cs:line 1670
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 451
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 96
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1006
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11.12.2023 10:15:22, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.0.0, Zeitstempel: 0x65310000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x7b24
Startzeit der fehlerhaften Anwendung: 0x01da2c126d97edb6
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: f4635a46-b4d1-4a40-9d8f-22a08ae5c4b5
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 11.12.2023 10:06:50, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.0.0, Zeitstempel: 0x65310000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x50a8
Startzeit der fehlerhaften Anwendung: 0x01da2c10e49e97b4
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 78979449-6c15-4ef9-b1aa-c863964a9fbe
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 11.12.2023 10:02:28, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.0.0, Zeitstempel: 0x65310000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x7b60
Startzeit der fehlerhaften Anwendung: 0x01da2c106ee80e7f
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 3974bcb6-121a-4864-b045-3b060337fc9f```

**Comment by tyronx** [comment]
thanks for the report, will be fixed in rc5
