### ISSUE TITLE
game error

### ISSUE THREAD

**Issue by sushimarshmallow** [anegostudios/VintageStory-Issues#3307]
### Platform

None

### Modded

None

### SP/MP

None

### Description

Running on 64 bit Windows with 3899 MB RAM
Game Version: v1.18.10 (Stable)
2023/12/13 12:03:08 pm: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: The driver does not appear to support OpenGL
   at OpenTK.Windowing.Desktop.GLFWProvider.<>c.<.cctor>b__10_0(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2023/12/13 12:01:32 pm, Site = , Source = Windows Error Reporting, Message = Fault bucket 2002654256128517211, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.10.0
P3: 64b07659
P4: KERNELBASE.dll
P5: 10.0.19041.3570
P6: da674bb7
P7: e0434352
P8: 000000000002cf19
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4F3A.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER52E5.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5305.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5313.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5352.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_88b44eade373e73aa6a4b010df4ac0bf7b5da7b1_93d687c4_52f62420-90d9-4f78-a393-2e84b85687c8

Analysis symbol: 
Rechecking for solution: 0
Report Id: cb5408b6-c145-4b63-9230-d63779765d07
Report Status: 268435456
Hashed bucket: 16d0b21601fcf8bcabcadb6f7876e45b
Cab Guid: 0 }
--------------
{ TimeGenerated = 2023/12/13 12:01:28 pm, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.10.0, time stamp: 0x64b07659
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3570, time stamp: 0xda674bb7
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process id: 0xc4c
Faulting application start time: 0x01da2daac2c4b3d6
Faulting application path: C:\Users\Danie Terblanche\Downloads\Vintage.Story.v1.18.10\Vintage.Story.v1.18.10\Game\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: cb5408b6-c145-4b63-9230-d63779765d07
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 2023/12/13 12:01:28 pm, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
CoreCLR Version: 7.0.1423.51910
.NET Version: 7.0.14
Description: The process was terminated due to an unhandled exception.
Exception Info: OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: You can only dispose windows on the main thread. The window needs to be disposed as it cannot safely be disposed in the finalizer.
   at OpenTK.Windowing.Desktop.NativeWindow.Dispose(Boolean disposing)
   at OpenTK.Windowing.Desktop.NativeWindow.Finalize()
 }

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Update graphics drivers
