### ISSUE TITLE
Animals not dropping meat or hide

### ISSUE THREAD

**Issue by elandreneau** [anegostudios/VintageStory-Issues#3317]
### Game Version

v1.19.0-pre.9

### Platform

None

### Modded

None

### SP/MP

None

### Description

No meat or leather is dropping from animals. I have killed and harvested many rabbits of varying type, and they have not dropped anything. I've killed a few raccoons and not even bushmeat drops. 

See the attached log snippet for what appears to be an error in Vintagestory.GameContent.EntityBehaviorHarvestable.generateDrops()

 [Error] Exception: Object reference not set to an instance of an object.

### How to reproduce

Create a world with seed 768546040
Kill various critters (raccoons, rabbits) and skin with a flint knife. Notice no meat or hide drops.

Active mods: Farmland Drops Soil, HUD Clock, ProspectorInfo, Better Firepit

### Screenshots

19.12.2023 10:04:38 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorHarvestable.generateDrops(IPlayer byPlayer, Single dropQuantityMultiplier) in VSEssentials\Entity\Behavior\BehaviorHarvestable.cs:line 421
   at Vintagestory.GameContent.EntityBehaviorHarvestable.SetHarvested(IPlayer byPlayer, Single dropQuantityMultiplier) in VSEssentials\Entity\Behavior\BehaviorHarvestable.cs:line 377
   at Vintagestory.GameContent.ItemKnife.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel) in VSSurvivalMod\Item\ItemKnife.cs:line 244
   at Vintagestory.Server.ServerSystemInventory.HandleHandInteraction(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\Inventory.cs:line 252
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\ServerMainNetworking.cs:line 138
19.12.2023 10:05:11 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorHarvestable.generateDrops(IPlayer byPlayer, Single dropQuantityMultiplier) in VSEssentials\Entity\Behavior\BehaviorHarvestable.cs:line 421
   at Vintagestory.GameContent.EntityBehaviorHarvestable.SetHarvested(IPlayer byPlayer, Single dropQuantityMultiplier) in VSEssentials\Entity\Behavior\BehaviorHarvestable.cs:line 377
   at Vintagestory.GameContent.ItemKnife.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel) in VSSurvivalMod\Item\ItemKnife.cs:line 244
   at Vintagestory.Server.ServerSystemInventory.HandleHandInteraction(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\Inventory.cs:line 252
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\ServerMainNetworking.cs:line 138
19.12.2023 10:05:38 [Warning] Cannot load chiseled block id mapping @ 511649, 53, 512824, block id 3492 not found block registry. Will not display correctly.
19.12.2023 10:05:38 [Warning] Cannot load chiseled block id mapping @ 511649, 54, 512824, block id 3492 not found block registry. Will not display correctly.
19.12.2023 10:06:53 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorHarvestable.generateDrops(IPlayer byPlayer, Single dropQuantityMultiplier) in VSEssentials\Entity\Behavior\BehaviorHarvestable.cs:line 421
   at Vintagestory.GameContent.EntityBehaviorHarvestable.SetHarvested(IPlayer byPlayer, Single dropQuantityMultiplier) in VSEssentials\Entity\Behavior\BehaviorHarvestable.cs:line 377
   at Vintagestory.GameContent.ItemKnife.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel) in VSSurvivalMod\Item\ItemKnife.cs:line 244
   at Vintagestory.Server.ServerSystemInventory.HandleHandInteraction(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\Inventory.cs:line 252
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\ServerMainNetworking.cs:line 138
19.12.2023 10:07:23 [Notification] Handling Command /waypoint addati apple =511988.47727538185 =115 =512412.4082577917 False #94C948 pear
19.12.2023 10:07:44 [Notification] Handling Command /tp 0 110 289
19.12.2023 10:07:48 [Notification] Handling Command /tp 0 115 289
19.12.2023 10:08:48 [Notification] Handling Command /tp 0 115 437

### Logs

19.12.2023 10:17:00 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorHarvestable.generateDrops(IPlayer byPlayer, Single dropQuantityMultiplier) in VSEssentials\Entity\Behavior\BehaviorHarvestable.cs:line 421
   at Vintagestory.GameContent.EntityBehaviorHarvestable.SetHarvested(IPlayer byPlayer, Single dropQuantityMultiplier) in VSEssentials\Entity\Behavior\BehaviorHarvestable.cs:line 377
   at Vintagestory.GameContent.ItemKnife.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel) in VSSurvivalMod\Item\ItemKnife.cs:line 244
   at Vintagestory.Server.ServerSystemInventory.HandleHandInteraction(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\Inventory.cs:line 252
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\ServerMainNetworking.cs:line 138

**Comment by Craluminum2413** [comment]
Will be fixed in pre.10
