### ISSUE TITLE
Game Crash When Updating World Settings For Server Using Client Version 1.19rc.1

### ISSUE THREAD

**Issue by lolzme** [anegostudios/VintageStory-Issues#3328]
### Game Version

1.19rc.1

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

The game crashes when trying to setup a new multiplayer server. It only crashes when using the new game client but seems to work with the 1.18.15 version oddly enough.

### How to reproduce

1. Download 1.19rc.1
2. Select World Settings on the Your Game Server section in the client.
3. Game crashes.

### Logs

Running on 64 bit Windows 10.0.19045.0 with 64662 MB RAM
Game Version: v1.19.0-rc.1 (Unstable)
12/22/2023 2:37:03 PM: Critical error occurred
Loaded Mods: game@1.19.0-rc.1, creative@1.19.0-rc.1, survival@1.19.0-rc.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.GuiScreenServerDashboard.onWorldConfigReceived(EnumAuthServerResponse reqStatus, GameServerConfigResponse response) in VintagestoryLib\Client\MainMenu\Screens\HostedServer\GuiScreenServerDashboard.cs:line 271
   at Vintagestory.Client.Util.ServerCtrlBackendInterface.<>c__DisplayClass18_1`1.<runAction>b__1() in VintagestoryLib\Client\Util\ServerCtrlBackend\ServerCtrlBackendInterface.cs:line 219
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by tyronx** [comment]
thanks for the report, this should already be fixed in rc4
