### ISSUE TITLE
The game does not start after the first time (1.18.15)

### ISSUE THREAD

**Issue by Rororost** [anegostudios/VintageStory-Issues#3332]
### Game Version

v1.18.15

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

Game Version: v1.18.15 (Stable)
24.12.2023 0:43:50: Critical error occurred
Loaded Mods: 
System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Не удается найти указанный файл.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Eto.Wpf.Platform.<>c.<AddTo>b__10_89()
   at Eto.Widget..ctor()
   at Eto.Forms.Application..ctor(InitHelper init)
   at Eto.Forms.Application..ctor(Platform platform)
   at VSPlatform.XPlatImpl.ShowMessageBox(String title, String text)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
Game Version: v1.18.15 (Stable)
24.12.2023 0:44:23: Critical error occurred
Loaded Mods: 
System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Не удается найти указанный файл.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Eto.Wpf.Platform.<>c.<AddTo>b__10_89()
   at Eto.Widget..ctor()
   at Eto.Forms.Application..ctor(InitHelper init)
   at Eto.Forms.Application..ctor(Platform platform)
   at VSPlatform.XPlatImpl.ShowMessageBox(String title, String text)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
Game Version: v1.18.15 (Stable)
24.12.2023 0:49:31: Critical error occurred
Loaded Mods: 
System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Не удается найти указанный файл.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Eto.Wpf.Platform.<>c.<AddTo>b__10_89()
   at Eto.Widget..ctor()
   at Eto.Forms.Application..ctor(InitHelper init)
   at Eto.Forms.Application..ctor(Platform platform)
   at VSPlatform.XPlatImpl.ShowMessageBox(String title, String text)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
Game Version: v1.18.15 (Stable)
24.12.2023 0:50:58: Critical error occurred
Loaded Mods: 
System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Не удается найти указанный файл.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Eto.Wpf.Platform.<>c.<AddTo>b__10_89()
   at Eto.Widget..ctor()
   at Eto.Forms.Application..ctor(InitHelper init)
   at Eto.Forms.Application..ctor(Platform platform)
   at VSPlatform.XPlatImpl.ShowMessageBox(String title, String text)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
Game Version: v1.18.15 (Stable)
24.12.2023 0:52:36: Critical error occurred
Loaded Mods: 
System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Не удается найти указанный файл.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Eto.Wpf.Platform.<>c.<AddTo>b__10_89()
   at Eto.Widget..ctor()
   at Eto.Forms.Application..ctor(InitHelper init)
   at Eto.Forms.Application..ctor(Platform platform)
   at VSPlatform.XPlatImpl.ShowMessageBox(String title, String text)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
Game Version: v1.18.15 (Stable)
24.12.2023 12:06:17: Critical error occurred
Loaded Mods: 
System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Не удается найти указанный файл.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Eto.Wpf.Platform.<>c.<AddTo>b__10_89()
   at Eto.Widget..ctor()
   at Eto.Forms.Application..ctor(InitHelper init)
   at Eto.Forms.Application..ctor(Platform platform)
   at VSPlatform.XPlatImpl.ShowMessageBox(String title, String text)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
Game Version: v1.18.15 (Stable)
24.12.2023 12:12:26: Critical error occurred
Loaded Mods: 
System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Не удается найти указанный файл.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Eto.Wpf.Platform.<>c.<AddTo>b__10_89()
   at Eto.Widget..ctor()
   at Eto.Forms.Application..ctor(InitHelper init)
   at Eto.Forms.Application..ctor(Platform platform)
   at VSPlatform.XPlatImpl.ShowMessageBox(String title, String text)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
Game Version: v1.18.15 (Stable)
24.12.2023 12:14:40: Critical error occurred
Loaded Mods: 
System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Не удается найти указанный файл.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Eto.Wpf.Platform.<>c.<AddTo>b__10_89()
   at Eto.Widget..ctor()
   at Eto.Forms.Application..ctor(InitHelper init)
   at Eto.Forms.Application..ctor(Platform platform)
   at VSPlatform.XPlatImpl.ShowMessageBox(String title, String text)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
Game Version: v1.18.15 (Stable)
24.12.2023 12:18:32: Critical error occurred
Loaded Mods: 
System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Не удается найти указанный файл.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Eto.Wpf.Platform.<>c.<AddTo>b__10_89()
   at Eto.Widget..ctor()
   at Eto.Forms.Application..ctor(InitHelper init)
   at Eto.Forms.Application..ctor(Platform platform)
   at VSPlatform.XPlatImpl.ShowMessageBox(String title, String text)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
Game Version: v1.18.15 (Stable)
24.12.2023 12:36:12: Critical error occurred
Loaded Mods: 
System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Не удается найти указанный файл.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Eto.Wpf.Platform.<>c.<AddTo>b__10_89()
   at Eto.Widget..ctor()
   at Eto.Forms.Application..ctor(InitHelper init)
   at Eto.Forms.Application..ctor(Platform platform)
   at VSPlatform.XPlatImpl.ShowMessageBox(String title, String text)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
Game Version: v1.18.15 (Stable)
24.12.2023 12:38:30: Critical error occurred
Loaded Mods: 
System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Не удается найти указанный файл.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Eto.Wpf.Platform.<>c.<AddTo>b__10_89()
   at Eto.Widget..ctor()
   at Eto.Forms.Application..ctor(InitHelper init)
   at Eto.Forms.Application..ctor(Platform platform)
   at VSPlatform.XPlatImpl.ShowMessageBox(String title, String text)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
Game Version: v1.18.15 (Stable)
24.12.2023 18:08:32: Critical error occurred
Loaded Mods: 
System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Не удается найти указанный файл.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Eto.Wpf.Platform.<>c.<AddTo>b__10_89()
   at Eto.Widget..ctor()
   at Eto.Forms.Application..ctor(InitHelper init)
   at Eto.Forms.Application..ctor(Platform platform)
   at VSPlatform.XPlatImpl.ShowMessageBox(String title, String text)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Incorrect install
