### ISSUE TITLE
Crash on startup after updating to 1.18.8 and 1.18.15

### ISSUE THREAD

**Issue by Burntat3rs** [anegostudios/VintageStory-Issues#3333]
### Game Version

1.18.15

### Platform

None

### Modded

None

### SP/MP

None

### Description

Recently decided to try updating to version 1.18.8 from 1.18.6 for a new mod after determining it needed that update to function. However after updating I kept getting crashes related to .net7. I downloaded several versions, first the new version 7.0.14, then the 7.0.9 the log specifically calls for, but none of those worked. So I then updated my video drivers, but those failed to change the crash as well. I tried updating all the way to 1.18.15 as well to see if the update was the issue, but the type of crash is the same.

Now I'm at a loss, one of the first things I did when the crashes began was remove all my mods from the mods folder, so I don't think that's the problem. I tried finding out what the OpenTk error was about, but it's beyond my technical knowledge for sure. I also installed the Visual C++ link the update download page called out for startup crashes, but that didn't change the error or crash either. It looks like it's not finding the .Net7 from what the log is detailing, but I don't know how to fix that or manually point it in the right direction.  I've reached the limits of what I can troubleshoot on my own  by googling now, help would be much appreciated. 
 

### Logs

```Running on 64 bit Windows with 16269 MB RAM
Game Version: v1.18.15 (Stable)
12/24/2023 2:07:03 PM: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: Win32: Failed to set video mode: Graphics mode not supported
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwSetWindowMonitor(Window* window, Monitor* monitor, Int32 x, Int32 y, Int32 width, Int32 height, Int32 refreshRate)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.SetWindowMonitor(Window* window, Monitor* monitor, Int32 x, Int32 y, Int32 width, Int32 height, Int32 refreshRate)
   at OpenTK.Windowing.Desktop.NativeWindow.set_WindowState(WindowState value)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 284
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/24/2023 12:07:23 PM, Site = , Source = .NET Runtime, Message = Description: A .NET application failed.
Application: Vintagestory.exe
Path: C:\Users\burnt\AppData\Roaming\Vintagestory\Vintagestory.exe
Message: You must install .NET to run this application.

App: C:\Users\burnt\AppData\Roaming\Vintagestory\Vintagestory.exe
Architecture: x64
App host version: 7.0.9
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=7.0.9

 }
--------------
{ TimeGenerated = 12/5/2023 12:04:00 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2101769553295251946, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.6.0
P3: 649be5a4
P4: nvoglv64.dll
P5: 31.0.15.2824
P6: 63c43af3
P7: c0000005
P8: 0000000000e52804
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5457.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5C85.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5CF4.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5D01.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5D22.tmp.txt
\\?\C:\Users\burnt\AppData\Local\Temp\WER5E7C.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_d3604ab32dc436f5f54c941be2b8208211fe97b2_9674cd4f_bf2dfa5c-4845-412d-89c7-fe31696c268a

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2616f39e-9409-414d-8f89-864b58d0f874
Report Status: 268435456
Hashed bucket: 12d6518ae75c368c7d2afc45e7e519ea
Cab Guid: 0 }
--------------
{ TimeGenerated = 12/5/2023 12:03:58 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.6.0
P3: 649be5a4
P4: nvoglv64.dll
P5: 31.0.15.2824
P6: 63c43af3
P7: c0000005
P8: 0000000000e52804
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5457.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5C85.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5CF4.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5D01.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5D22.tmp.txt
\\?\C:\Users\burnt\AppData\Local\Temp\WER5E7C.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_d3604ab32dc436f5f54c941be2b8208211fe97b2_9674cd4f_cab_bf2dfa5c-4845-412d-89c7-fe31696c268a

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2616f39e-9409-414d-8f89-864b58d0f874
Report Status: 4
Hashed bucket: 
Cab Guid: 0 }```

**Comment by Burntat3rs** [comment]
Yeah I have a laptop with an intel and Nvidia, I updated the drivers on both, but no luck

**Comment by Craluminum2413** [comment]
Closing due to inactivity
