### ISSUE TITLE
Game crasheв when my friend give me merchant amulet/Игра вылетела, когда мой друг дал мне амулет торговца

### ISSUE THREAD

**Issue by TheSokol** [anegostudios/VintageStory-Issues#3335]
### Game Version

v1.19.0-rc.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

When I played with a friend for several real days, the game crashed on one of them when my friend gave me a merchant's amulet, after which I could not connect to him, but the game worked for me without any problems at all.
Also, I just discovered that I can connect to the new created world without problems, even when I logged in from another account and connected to a friend on the world where he gave me an amulet, it didn’t crash and I was able to play, I have a guess that it was the amulet that “broke” my old character./Когда я играл с другом несколько реальных дней, на одном из них игра вылетела, когда мой друг дал мне амулет торговца, после чего я не смог к нему подключиться, но у меня игра работала вообще без проблем.
Также только что я обнаружил что к новому созданному миру я могу подключится без проблем ,ещё когда я зашёл с другого аккаунта и подсоеденился к другу на мир где он дал мне амулет ,то у меня не вылетело и я смог играть ,у меня есть догадка что именно амулет "сломал" моего старого персонажа.

### How to reproduce

no response/нет ответа

### Screenshots

no response/нет ответа

### Logs

```Log```Running on 64 bit Windows 10.0.19045.0 with 8077 MB RAM
Game Version: v1.19.0-rc.1 (Unstable) by OverF1X  
25.12.2023 20:34:42: Critical error occurred
Loaded Mods: game@1.19.0-rc.1, creative@1.19.0-rc.1, survival@1.19.0-rc.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.RenderAPIBase.RenderMultiTextureMesh(MultiTextureMeshRef mmr, String textureSampleName, Int32 textureNumber) in VintagestoryLib\Client\API\RenderAPIBase.cs:line 107
   at Vintagestory.GameContent.EntityShapeRenderer.RenderHeldItem(Single dt, Boolean isShadowPass, Boolean right) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 471
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 246
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderFrameShadows(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 165
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 724
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 25.12.2023 20:23:26, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.19.0.0, метка времени: 0x65310000
Имя сбойного модуля: openal32.dll, версия: 1.23.0.0, метка времени: 0x63dd31ad
Код исключения: 0x40000015
Смещение ошибки: 0x00000000000df046
Идентификатор сбойного процесса: 0x3ba4
Время запуска сбойного приложения: 0x01da3756b2f7a6bb
Путь сбойного приложения: C:\Games\Vintage Story\Vintagestory.exe
Путь сбойного модуля: C:\Games\Vintage Story\Lib\openal32.dll
Идентификатор отчета: 6b6d3287-066f-41e8-b0fc-2b044aaa8115
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 25.12.2023 19:56:10, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.19.0.0, метка времени: 0x65310000
Имя сбойного модуля: openal32.dll, версия: 1.23.0.0, метка времени: 0x63dd31ad
Код исключения: 0x40000015
Смещение ошибки: 0x00000000000df046
Идентификатор сбойного процесса: 0x524
Время запуска сбойного приложения: 0x01da37531efa08b0
Путь сбойного приложения: C:\Games\Vintage Story\Vintagestory.exe
Путь сбойного модуля: C:\Games\Vintage Story\Lib\openal32.dll
Идентификатор отчета: e5aeae0e-8ba4-485b-84a6-43c47a58c717
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 25.12.2023 19:17:32, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.19.0.0, метка времени: 0x65310000
Имя сбойного модуля: openal32.dll, версия: 1.23.0.0, метка времени: 0x63dd31ad
Код исключения: 0x40000015
Смещение ошибки: 0x00000000000df046
Идентификатор сбойного процесса: 0x4070
Время запуска сбойного приложения: 0x01da374dcbf089d9
Путь сбойного приложения: C:\Games\Vintage Story\Vintagestory.exe
Путь сбойного модуля: C:\Games\Vintage Story\Lib\openal32.dll
Идентификатор отчета: 5d6fc149-e140-49b8-8c7a-122819be184a
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }

**Comment by Craluminum2413** [comment]
Pirated versions of the game are not supported

**Comment by TheSokol** [comment]
Well, excuse me that I was born in a country where $18, even for adults, is a significant price for a game
