### ISSUE TITLE
Game will not start with this version.

### ISSUE THREAD

**Issue by Hunter0697** [anegostudios/VintageStory-Issues#3336]
### Game Version

v1.19.0-rc.2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I updated to the new version and was unable to play on my world it would crash immediately upon entering. Afterwards I tested on a completely new world with no mods and it still had the same error.

### How to reproduce

All I did was start up the game.

### Logs

```Log```Running on 64 bit Windows 10.0.19045.0 with 12227 MB RAM
Game Version: v1.19.0-rc.2 (Unstable)
12/25/2023 1:13:22 PM: Critical error occurred
Loaded Mods: game@1.19.0-rc.2, creative@1.19.0-rc.2, survival@1.19.0-rc.2
System.Collections.Generic.KeyNotFoundException: The given key 'zNear' was not present in the dictionary.
   at Vintagestory.Client.NoObf.ShaderProgramBase.Uniform(String uniformName, Single value) in VintagestoryLib\Client\ClientPlatform\ShaderProgramBase.cs:line 131
   at Vintagestory.Client.NoObf.ShaderProgramBase.Use() in VintagestoryLib\Client\ClientPlatform\ShaderProgramBase.cs:line 281
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 221
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderOpaque3D(Single deltaTime) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 93
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 199
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 799
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 894
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 723
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/25/2023 1:11:47 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x746c
Faulting application start time: 0x01da375d8959c930
Faulting application path: C:\Users\hunts\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\hunts\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 00ade8c4-ff47-4b96-8b30-d676f5365638
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/25/2023 1:09:45 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x5394
Faulting application start time: 0x01da375d3a684924
Faulting application path: C:\Users\hunts\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\hunts\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 9d31b4e8-e8ce-45ee-a9d9-a4803549d70b
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/25/2023 1:07:29 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0xac04
Faulting application start time: 0x01da375d04382265
Faulting application path: C:\Users\hunts\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\hunts\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 217daec4-6870-4e21-b5ab-35d25dd0851d
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Fixed in v1.19.0-rc.3
