### ISSUE TITLE
Game crashes in handbook with System.NullReferenceException when modded harvestables.

### ISSUE THREAD

**Issue by AedisV** [anegostudios/VintageStory-Issues#3343]
### Game Version

v1.19.1-rc3

### Platform

Linux

### Modded

Modded

### SP/MP

Singleplayer

### Description

Game crashes on handbook
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.addObtainedThroughInfo(ICoreClientAPI capi, ActionConsumable`1 openDetailPageFor, ItemStack stack, List`1 components, Single marginTop, List`1 breakBlocks) in VSSurvivalMod\Systems\Handbook\CollectibleBehaviorHandbookTextAndExtraInfo.cs:line 218
All you need is some json changes to harvestables (for example hide and fabric does so), prior to 1.19.0pre1 it wasn't crashing on same json content.
https://github.com/anegostudios/vssurvivalmod/blob/2bfd75697208df8f1d5386e117f7f791df596cc6/Systems/Handbook/CollectibleBehaviorHandbookTextAndExtraInfo.cs#L218

### How to reproduce

1. Add Hide and Fabric mod
2. Launch game with mod enabled
3. Open handbook
4. Type 'resin' in search box
5. Click on resin entry.

### Logs

```Running on 64 bit Linux (Devuan GNU/Linux 3 (beowulf)) [Kernel 4.19.0.24] with 32114 MB RAM
Game Version: v1.19.0-rc.3 (Unstable)
12/26/2023 19:40:04: Critical error occurred
Loaded Mods: acorns@0.5.3, aehacknbits@0.0.1, bushmeatpemmican@0.1.3, composter@1.0.4, gwb@1.0.1, HangingOilLamps@1.0.1, hideandfabric@1.3.0, unochre@1.1.0, pieontheshelf@1.0.0, primitivesurvival@3.4.5, vgaas@1.0.1, game@1.19.0-rc.3, wildcraft@1.6.6, animalcages@3.0.0, creaturekilledby@1.0.0, extrainfo@1.6.0, greenbegone@1.0.0, hudclock@3.3.0, jhome@1.0.5, liquidcontainers@1.2.0, moreanimals@1.3.1, morepiles@1.5.0, resmeltableslight@1.0.0, storageoptions@1.0.2, creative@1.19.0-rc.3, survival@1.19.0-rc.3, metalrecovery@0.1.19-pre.1, UPDirt@1.0.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.addObtainedThroughInfo(ICoreClientAPI capi, ActionConsumable`1 openDetailPageFor, ItemStack stack, List`1 components, Single marginTop, List`1 breakBlocks) in VSSurvivalMod\Systems\Handbook\CollectibleBehaviorHandbookTextAndExtraInfo.cs:line 218
   at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.GetHandbookInfo_Patch1(CollectibleBehaviorHandbookTextAndExtraInfo this, ItemSlot inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.GameContent.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 116
   at Vintagestory.GameContent.GuiHandbookItemStackPage.ComposePage(GuiComposer detailViewGui, ElementBounds textBounds, ItemStack[] allstacks, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 110
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onComposePage(GuiHandbookPage page, GuiComposer detailViewGui, ElementBounds textBounds, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 97
   at Vintagestory.GameContent.GuiDialogHandbook.initDetailGui() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 258
   at Vintagestory.GameContent.GuiDialogHandbook.onLeftClickListElement(Int32 index) in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 349
   at Vintagestory.GameContent.GuiElementFlatList.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VSSurvivalMod\Systems\Handbook\Gui\GuiElementFlatList.cs:line 117
   at Vintagestory.GameContent.GuiElementFlatList.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VSSurvivalMod\Systems\Handbook\Gui\GuiElementFlatList.cs:line 172
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 449
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 583
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 412
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1874
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 208
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by AedisV** [comment]
As requested, removed extra info, crash stays where it was, also updated to 1.19.1rc4, I tried removing mod one by one, and this way I found that content (jsons as code does not touch anything in that area) trigger necesary change in harvestables that isn't happilly accepted by vssurvival

Running on 64 bit Linux (Devuan GNU/Linux 3 (beowulf)) [Kernel 4.19.0.24] with 32114 MB RAM
Game Version: v1.19.0-rc.4 (Unstable)
12/27/2023 20:20:03: Critical error occurred
Loaded Mods: acorns@0.5.3, aehacknbits@0.0.1, bushmeatpemmican@0.1.3, composter@1.0.4, gwb@1.0.1, HangingOilLamps@1.0.1, hideandfabric@1.3.0, unochre@1.1.0, pieontheshelf@1.0.0, primitivesurvival@3.4.5, vgaas@1.0.1, game@1.19.0-rc.4, animalcages@3.0.0, creaturekilledby@1.0.0, cuniculture@1.0.1, greenbegone@1.0.0, hudclock@3.3.0, jhome@1.0.5, kilntimeviewer@1.0.0, liquidcontainers@1.2.0, moreanimals@1.3.1, morepiles@1.5.0, resmeltableslight@1.0.0, storageoptions@1.0.2, creative@1.19.0-rc.4, survival@1.19.0-rc.4, metalrecovery@0.1.19-pre.1, UPDirt@1.0.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.addObtainedThroughInfo(ICoreClientAPI capi, ActionConsumable`1 openDetailPageFor, ItemStack stack, List`1 components, Single marginTop, List`1 breakBlocks) in VSSurvivalMod\Systems\Handbook\CollectibleBehaviorHandbookTextAndExtraInfo.cs:line 218
   at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.GetHandbookInfo(ItemSlot inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\CollectibleBehaviorHandbookTextAndExtraInfo.cs:line 51
   at Vintagestory.GameContent.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 116
   at Vintagestory.GameContent.GuiHandbookItemStackPage.ComposePage(GuiComposer detailViewGui, ElementBounds textBounds, ItemStack[] allstacks, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 110
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onComposePage(GuiHandbookPage page, GuiComposer detailViewGui, ElementBounds textBounds, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 97
   at Vintagestory.GameContent.GuiDialogHandbook.initDetailGui() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 258
   at Vintagestory.GameContent.GuiDialogHandbook.onLeftClickListElement(Int32 index) in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 349

**Comment by tyronx** [comment]
I can fix the crash, but the mod still needs to fix its misconfiguration for this to work correctly. Will be in rc5

**Comment by AedisV** [comment]
Will misconfiguration cause at least printout what object has wrong harvestable config?

**Comment by AedisV** [comment]
Would it be possible that aside of not crashing it would print what mod/object is misconfigured? I peeked at github with vssurvival but seems it is not visible there, I guess you might update it once rc5 is there.

**Comment by tyronx** [comment]
yes it will print an error in the log files
