### ISSUE TITLE
The game wont start

### ISSUE THREAD

**Issue by Cogodino** [anegostudios/VintageStory-Issues#3347]
### Game Version

v1.18.12

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

When I try to lauch the game it's crash.

### Logs

Running on 64 bit Windows with 4043 MB RAM
Game Version: v1.18.12 (Stable)
27/12/2023 13:56:15: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: OpenGL profile requested but WGL_ARB_create_context_profile is unavailable
   at OpenTK.Windowing.Desktop.GLFWProvider.<>c.<.cctor>b__10_0(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)

**Comment by Craluminum2413** [comment]
Update your graphics drivers
