### ISSUE TITLE
Found a ruins with air blocks and question mark blocks

### ISSUE THREAD

**Issue by Featheredbat** [anegostudios/VintageStory-Issues#3349]
### Game Version

v1.19.0-rc4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

While exploring I found a ruins with air blocks and question mark blocks, and when I broke one of the question mark blocks, my game crashed and save corrupted.

### How to reproduce

Not sure if it was the ruins model itself or how the ruins generated in the world

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32708 MB RAM
Game Version: v1.19.0-rc.4 (Unstable)
12/27/2023 4:31:08 PM: Critical error occurred
Loaded Mods: game@1.19.0-rc.4, creative@1.19.0-rc.4, survival@1.19.0-rc.4
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockMicroBlock.TryToRemoveSoilFirst(IWorldAccessor world, BlockPos pos, IPlayer byPlayer) in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 520
   at Vintagestory.GameContent.BlockMicroBlock.OnBlockBroken(IWorldAccessor world, BlockPos pos, IPlayer byPlayer, Single dropQuantityMultiplier) in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 504
   at Vintagestory.API.Common.CollectibleObject.OnBlockBrokenWith(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, BlockSelection blockSel, Single dropQuantityMultiplier) in VintagestoryApi\Common\Collectible\Collectible.cs:line 589
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryDestroyBlock(BlockSelection blockSelection) in VintagestoryLib\Client\ClientMain.cs:line 1687
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 802
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 451
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 96
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1006
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by tyronx** [comment]
thanks for the report. the crash should be fixed in rc.5 - the appearence of those blocks is another issue we need to address though
