### ISSUE TITLE
Torch Lighting crash

### ISSUE THREAD

**Issue by WretchedAbyss** [anegostudios/VintageStory-Issues#3362]
### Game Version

v1.19.0-rc.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

When someone walks in front of you while you are lighting your touch the game hard crashes 

### How to reproduce

1. Have a touch 
2. Have a friend
3. try to light touch 
4. Have a friend walk in front of you, blocking your path to the fire source (another torch, for example).
5. Crash 

### Logs

```Log Running on 64 bit Windows 10.0.19045.0 with 65449 MB RAM
Game Version: v1.19.0-rc.4 (Unstable)
2024-01-02 10:51:21 AM: Critical error occurred
Loaded Mods: game@1.19.0-rc.4, creative@1.19.0-rc.4, survival@1.19.0-rc.4
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockTorch.OnHeldInteractStep(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel) in VSSurvivalMod\Block\BlockTorch.cs:line 118
   at Vintagestory.API.Common.CollectibleObject.OnHeldUseStep(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1094
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 336
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 169
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 724
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 2023-12-31 12:41:02 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x65310000
Faulting module name: coreclr.dll, version: 7.0.1423.51910, time stamp: 0x6531bbbf
Exception code: 0xc0000005
Fault offset: 0x00000000000578a4
Faulting process id: 0x3924
Faulting application start time: 0x01da3ba88e702efe
Faulting application path: C:\Users\Alec\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.14\coreclr.dll
Report Id: 82768abf-848f-42f7-9654-4e0c3d8dbec4
Faulting package full name: 
Faulting package-relative application ID:  }```

**Comment by Th3Dilli** [comment]
thank you this will be fixed in next release
