### ISSUE TITLE
Crash upon opening handbook

### ISSUE THREAD

**Issue by schall86** [anegostudios/VintageStory-Issues#3363]
### Game Version

v1.19.0-rc.4

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Program crashed when I tried to open the handbook via hotkey.

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32672 MB RAM
Game Version: v1.19.0-rc.4 (Unstable)
1/2/2024 3:04:04 PM: Critical error occurred
Loaded Mods: primitivesurvival@3.4.5, game@1.19.0-rc.4, fieldsofsalt@1.2.0, kreaturesandkritters@1.0.3, petai@2.2.0, statushud@1.4.3, creative@1.19.0-rc.4, survival@1.19.0-rc.4, feverstonehorses@1.6.0-rc.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.addObtainedThroughInfo(ICoreClientAPI capi, ActionConsumable`1 openDetailPageFor, ItemStack stack, List`1 components, Single marginTop, List`1 breakBlocks) in VSSurvivalMod\Systems\Handbook\CollectibleBehaviorHandbookTextAndExtraInfo.cs:line 218
   at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.GetHandbookInfo_Patch0(CollectibleBehaviorHandbookTextAndExtraInfo this, ItemSlot inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.GameContent.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 116
   at Vintagestory.GameContent.GuiHandbookItemStackPage.ComposePage(GuiComposer detailViewGui, ElementBounds textBounds, ItemStack[] allstacks, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 110
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onComposePage(GuiHandbookPage page, GuiComposer detailViewGui, ElementBounds textBounds, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 97
   at Vintagestory.GameContent.GuiDialogHandbook.initDetailGui() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 258
   at Vintagestory.GameContent.GuiDialogHandbook.OpenDetailPageFor(String pageCode) in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 314
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.OnSurvivalHandbookHotkey(KeyCombination key) in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 145
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean isGlobal, Boolean fallBack) in VintagestoryLib\Client\HotkeyManager.cs:line 375
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1714
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 230
   at OpenTK.Windowing.Desktop.NativeWindow.KeyCallback(Window* window, Keys key, Int32 scancode, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
Most likely caused by mods
