### ISSUE TITLE
Crashes When Clicking on Linen in Handbook 

### ISSUE THREAD

**Issue by BadBurrito10** [anegostudios/VintageStory-Issues#3373]
### Game Version

1.19.0-rc.5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Any time I click on something related to Linen (plain cloth, linen bag, and linen itself) in the handbook, my game crashes. I have the logs below. I disabled the spyglass and tera preta particle mods and retried since I installed them alongside the new version. Might downgrade a version to see if it gets fixed.

### How to reproduce

1. Open Handbook
2. Search Linen 
3. Right-Click

### Logs

```Running on 64 bit Windows 10.0.19045.0 with 32681 MB RAM
Game Version: v1.19.0-rc.5 (Unstable)
1/4/2024 10:00:42 AM: Critical error occurred
Loaded Mods: spyglass@0.4.7, game@1.19.0-rc.5, carryon@1.7.0-pre.3, hudclock@3.4.0, vtpp@1.1.0, creative@1.19.0-rc.5, survival@1.19.0-rc.5
System.DivideByZeroException: Attempted to divide by zero.
   at Vintagestory.API.Client.SlideshowGridRecipeTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY, Double renderZ) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\SlideshowGridRecipeTextComponent.cs:line 315
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 472
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 716
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 384
   at Vintagestory.GameContent.GuiDialogHandbook.OnRenderGUI(Single deltaTime) in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 493
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 318
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1006
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 1/4/2024 9:59:37 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x65310000
Faulting module name: coreclr.dll, version: 7.0.1023.36312, time stamp: 0x64b06d6c
Exception code: 0xc0000005
Fault offset: 0x00000000001c98a6
Faulting process id: 0x4510
Faulting application start time: 0x01da3f26f04da78b
Faulting application path: C:\Games\Vintagestory\Vintagestory.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.10\coreclr.dll
Report Id: 79efdc46-9d04-4777-81ec-35c677a03034
Faulting package full name: 
Faulting package-relative application ID:  }```

**Comment by BadBurrito10** [comment]
Saw the other thread way too late.

**Comment by Craluminum2413** [comment]
Duplicate of #3366
