### ISSUE TITLE
v1.18.15 (Stable) Crash when Joining Server (moded)

### ISSUE THREAD

**Issue by HexaCross17** [anegostudios/VintageStory-Issues#3382]
### Game Version

v1.18.15 (Stable)

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

So This happened spontaneously, I was playing, and quit the game. 30 minutes later tried to hop into the game again then the crash begin. The Server is heavily Modded, this issue only happened to me and I can't figure out so far what this issue is. I had Unistall and Reinstalled the game and mods, nothing so far.

### How to reproduce

Enter the game > Join Server > Crash Happens.

### Logs

```Log```
Running on 64 bit Windows with 16228 MB RAM
Game Version: v1.18.15 (Stable)
1/4/2024 11:10:18 PM: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.15, betterruins@0.2.4, bettersticks@1.0.0, buzzwords@1.5.0, femininity@0.1.2, caninae@1.0.4, pantherinae@1.0.9, HangingOilLamps@1.0.1, millwright@1.1.1, moredrygrass@0.2.0, palisademod@1.1.0, pieontheshelf@1.0.0, primitivesurvival@3.3.0, rainfrogs@1.2.1, roas@1.0.0, rustcreatures@1.2.0, sortablestorage@2.1.0, spyglass@0.4.7, Swordz@1.1.4, litbrig@0.5.0, translocatorengineeringredux@1.4.7, game@1.18.15, ancienttools@1.5.11, animalcages@2.2.0, animationmanagerlib@0.2.1, beehivekiln@1.5.1, blacksmithenhancements@1.0.3, butchering@1.1.5, carryon@1.6.1, commonlib@2.2.0, composter@1.1.0, cooperativecombat@1.1.1, expandedfoods@1.6.8, fishing@1.1.5, fromgoldencombs@1.4.25, immersivewoodchopping@0.5.2, medievalexpansion@3.11.1, outlawmod@1.1.5, petai@1.8.1, postsandbeams@1.2.0, claywheel@1.1.0, prospecttogether@1.2.4, simplestep@1.0.8, chunkstaboverride@1.1.0, stonebakeoven@1.1.1, storageoptions@1.0.1, th3dungeon@0.2.0, creative@1.18.15, vsquest@0.5.0, survival@1.18.15, vsvillage@0.7.3, wildfarmingrevival@1.1.6, awearablelight@1.0.10, bugnetcompatibility@1.0.1, bullseye@2.5.1, feverstonewilds@1.4.3, fishjenga@1.0.0, fsmlib@0.1.13, playercorpse@1.8.0, fsmbullseye@1.1.0, maltiezcrossbows@0.1.4, maltiezfirearms@0.3.9
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.HudMouseTools.OnOwnPlayerDataReceived() in VintagestoryLib\Client\Systems\Gui\Huds\HudMouseTools.cs:line 132
   at Vintagestory.Client.NoObf.GuiManager.OnOwnPlayerDataReceived() in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 274
   at Vintagestory.Client.NoObf.ClientMain.OnOwnPlayerDataReceived() in VintagestoryLib\Client\ClientMain.cs:line 683
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 277
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 452
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 446
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 322
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 1/4/2024 8:16:24 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF623.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFD48.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFD97.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFD95.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFDB5.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_eff71838-87da-4b82-b9ae-bc2ff403c6a7

Analysis symbol: 
Rechecking for solution: 0
Report Id: dcf84013-94c4-4d39-b9d4-5291689604df
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 1/4/2024 8:16:22 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x4710
Faulting application start time: 0x01da3f743cf2c6d0
Faulting application path: C:\Users\sahar\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\sahar\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: dcf84013-94c4-4d39-b9d4-5291689604df
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 1/4/2024 8:12:16 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2AC3.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3246.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3295.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3293.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER32C3.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_6f526ab5-e0f2-4bbb-a494-e2ba8d8279dd

Analysis symbol: 
Rechecking for solution: 0
Report Id: 43b986b5-58c4-4890-b610-9c8e14d9647f
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82

**Comment by HexaCross17** [comment]
The issue was solved.
