### ISSUE TITLE
Crash on first world generation

### ISSUE THREAD

**Issue by KBlecharczyk** [anegostudios/VintageStory-Issues#339]
**Game Version:** v1.10.18 
**Platform:**  Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0 with WSL and Hyper-V enabled.
**Modded:** No

### Description
Fresh install, first time playing VintageStory(freshly bought account). Runned app with no admin permissions. Went to world creation. Messed with height settings. Decided to use Survival with realistic band preset with no other worlds. Rolled name for world, Tried editing it, rolled again(gloomy cave story/lands in case name is correlated with the seed).. Clicked generate. Alt tabbed out. Alt tabbed back few seconds later, getting crash. Second world generation worked okay.

### How to reproduce
No Idea

### Logs
```
Running on 64 bit Windows with 20 GB RAM 
Version: v1.10.18 (Stable)19.10.2019 22:33:48: Critical error occurred
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at _1qHcnU5YADyh4WIuNfLUSHZdjVO._G9TkEnOr47QcGgFa7c7elamt0rU()
   at _9MF4S3lnqVnQ4xI6Ackl5ZVwanR._I0CdhvfdqaMAQoGkkdxTwEs9Ezc()
   at _1WEuyKuTnWDFWrafG4xdCFGrXtH._I0CdhvfdqaMAQoGkkdxTwEs9Ezc(Boolean , StartServerArgs , _lZebIoeYuSyEDomhx3sbaAVAeRh )
   at _PXJOUXrP78RmXPXIPYgoC6FP6Lg._AvVeng2B1EoAUBLpJpIAaAqSntcA(Boolean , StartServerArgs , _lZebIoeYuSyEDomhx3sbaAVAeRh )
   at _9DhWjb38ROOMAIWA1cDVbcF1q8n._i57ekSagZwYwdtXj0PC7ZmdsPFe()
   at _9DhWjb38ROOMAIWA1cDVbcF1q8n._ipj0CH8EV6mpgiIPNlMCieXaOAY()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _N4fKSrr2fRoWPWflmmJHNqDFyxg._jgUP9dQtVvRAJzSE1kJqh4DNTjb(MouseEvent )
   at _6vDbRyzDuE6CssHK7I3JZGFOCYd._rzKyaVhUB2EuHBPq61xTR8IlkGE(Object , MouseButtonEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _MVDJ7sKqoCU6ZOzpfQhXy08EXGD._I0CdhvfdqaMAQoGkkdxTwEs9Ezc(_2LhAOY5KhSgs9rfdEp5aN8LB1TH , String[] )
   at _UpTNXPJKqAuDHMEkFP3vjHQojsCA._I0CdhvfdqaMAQoGkkdxTwEs9Ezc(ThreadStart )
-------------------------------
```

**Comment by tyronx** [comment]
Thanks for the report, will bring out v1.10.19 today to fix this.
