### ISSUE TITLE
Memory leak in title screen mod manager

### ISSUE THREAD

**Issue by Gravydigger** [anegostudios/VintageStory-Issues#3413]
### Game Version

v1.19.0-rc.6

### Platform

Windows

### Modded

Modded

### SP/MP

None

### Description

When debugging my mods in Visual Studio, I noticed that the log mentions a texture is leaking memory inside the title screens mod manager whenever I press "Reload Button".

### How to reproduce

1. Load Vintage Story
2. Head to Mod Manager
3. Press the "Reload Mod" button

### Logs

Log was captured with enviroment variables `TEXTURE_DEBUG_DISPOSE` & `VAO_DEBUG_DISPOSE` set.

client-main.txt
```
8.1.2024 22:10:58 [Notification] Client logger started.
8.1.2024 22:10:58 [Notification] Game Version: v1.19.0-rc.6 (Unstable)
8.1.2024 22:11:00 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
8.1.2024 22:11:00 [Notification] Process path: F:\Non-Steam Games\Vintagestory\Vintagestory.exe
8.1.2024 22:11:00 [Notification] Operating System: Windows 10.0.19045.0
8.1.2024 22:11:00 [Notification] CPU Cores: 12
8.1.2024 22:11:00 [Notification] Available RAM: 16318 MB
8.1.2024 22:11:00 [Notification] Graphics Card Vendor: NVIDIA Corporation
8.1.2024 22:11:00 [Notification] Graphics Card Version: 3.3.0 NVIDIA 546.33
8.1.2024 22:11:00 [Notification] Graphics Card Renderer: NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2
8.1.2024 22:11:00 [Notification] Graphics Card ShadingLanguageVersion: 3.30 NVIDIA via Cg compiler
8.1.2024 22:11:00 [Notification] GL.MaxVertexUniformComponents: 4096
8.1.2024 22:11:00 [Notification] GL.MaxUniformBlockSize: 65536
8.1.2024 22:11:00 [Notification] Cairo Graphics Version: 1.17.3
8.1.2024 22:11:00 [Notification] OpenAL Version: 1.1 ALSOFT 1.23.0
8.1.2024 22:11:00 [Notification] C# Framework: .net 7.0.14
8.1.2024 22:11:00 [Notification] OpenTK Version: 3.3.2 (A set of fast, low-level C# bindings for OpenGL, OpenGL ES and OpenAL.)
8.1.2024 22:11:00 [Notification] Zstd Version: 1.5.5
8.1.2024 22:11:00 [Notification] Start discovering assets
8.1.2024 22:11:00 [Notification] Found 23 base assets in category lang
8.1.2024 22:11:00 [Notification] Found 0 base assets in category patches
8.1.2024 22:11:00 [Notification] Found 24 base assets in category config
8.1.2024 22:11:00 [Notification] Found 0 base assets in category worldproperties
8.1.2024 22:11:00 [Notification] Found 48 base assets in category sounds
8.1.2024 22:11:00 [Notification] Found 95 base assets in category shapes
8.1.2024 22:11:00 [Notification] Found 72 base assets in category shaders
8.1.2024 22:11:00 [Notification] Found 16 base assets in category shaderincludes
8.1.2024 22:11:00 [Notification] Found 133 base assets in category textures
8.1.2024 22:11:00 [Notification] Found 4 base assets in category music
8.1.2024 22:11:00 [Notification] Found 0 base assets in category dialog
8.1.2024 22:11:00 [Notification] Found 415 base assets in total
8.1.2024 22:11:00 [Notification] Loading sounds
8.1.2024 22:11:00 [Notification] (Re-)loaded frame buffers
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass .
8.1.2024 22:11:00 [Notification] Sounds loaded
8.1.2024 22:11:00 [Notification] Begin loading shaders
8.1.2024 22:11:00 [Notification] Load shaders now
8.1.2024 22:11:00 [Notification] Loading shaders...
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass standard.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass particlescube.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass particlesquad.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass sky.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass nightsky.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass woittest.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass helditem.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass decals.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass final.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass gui.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass blur.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass findbright.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass godrays.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass autocamera.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass wireframe.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass entityanimated.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass luma.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass blit.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass texture2texture.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass celestialobject.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass colorgrade.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass guigear.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass ssao.
8.1.2024 22:11:00 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
8.1.2024 22:11:00 [Notification] Cached session key is valid, validating with server
8.1.2024 22:11:01 [Notification] Window was resized to 2560 1440, rebuilding framebuffers...
8.1.2024 22:11:01 [Notification] (Re-)loaded frame buffers
8.1.2024 22:11:01 [Notification] Window probably resized, recalculating dialog bounds and recomposing gameloadingscreen...
8.1.2024 22:11:02 [Notification] Server validation response: Good
8.1.2024 22:11:02 [Notification] Will search the following paths for mods:
8.1.2024 22:11:02 [Notification]     F:\Non-Steam Games\Vintagestory\Mods
8.1.2024 22:11:02 [Notification]     C:\Users\Gravy\AppData\Roaming\VintagestoryData\Mods
8.1.2024 22:11:02 [Notification]     D:\Git Repositories\statushud\statushud\bin\Debug\Mods
8.1.2024 22:11:02 [Warning] Multiple mods share the mod ID 'statushudcont' ('mod', 'statushudcont_2.0.1.zip'). Will only load the highest version one - v2.0.1.
8.1.2024 22:11:07 [Notification] Will search the following paths for mods:
8.1.2024 22:11:07 [Notification]     F:\Non-Steam Games\Vintagestory\Mods
8.1.2024 22:11:07 [Notification]     C:\Users\Gravy\AppData\Roaming\VintagestoryData\Mods
8.1.2024 22:11:07 [Notification]     D:\Git Repositories\statushud\statushud\bin\Debug\Mods
8.1.2024 22:11:08 [Warning] Multiple mods share the mod ID 'statushudcont' ('mod', 'statushudcont_2.0.1.zip'). Will only load the highest version one - v2.0.1.
8.1.2024 22:11:08 [Warning] Texture with texture id 67 is leaking memory, missing call to Dispose. Allocated at    at System.Environment.get_StackTrace()
   at Vintagestory.API.Client.LoadedTexture..ctor(ICoreClientAPI capi) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\Texture\LoadedTexture.cs:line 48
   at Vintagestory.API.Client.TextTextureUtil.GenTextTexture(String text, CairoFont font, TextBackground background) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\TextTextureUtil.cs:line 192
   at Vintagestory.Client.NoObf.GuiElementModCell..ctor(ICoreClientAPI capi, ModCellEntry cell, ElementBounds bounds, IAsset warningIcon) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiElementModCell.cs:line 84
   at Vintagestory.Client.GuiScreenMods.createCellElem(ModCellEntry cell, ElementBounds bounds) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 176
   at Vintagestory.API.Client.GuiElementCellList`1.AddCell(T cell, Int32 afterPosition) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 204
   at Vintagestory.API.Client.GuiElementCellList`1.Initialize() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 106
   at Vintagestory.API.Client.GuiElementCellList`1.BeforeCalcBounds() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 140
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\GuiComposer.cs:line 365
   at Vintagestory.Client.GuiScreenMods.InitGui() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 139
   at Vintagestory.Client.GuiScreenMods.OnScreenLoaded() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 54
   at Vintagestory.Client.GuiScreenMods.OnReloadMods() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 185
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 317
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 719
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 307
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\GuiComposer.cs:line 445
   at GuiScreen.OnMouseUp(MouseEvent e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\Special\GuiScreen.cs:line 204
   at Vintagestory.Client.ScreenManager.OnMouseUp(MouseEvent e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 889
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\Input.cs:line 211
   at OpenTK.Windowing.Desktop.NativeWindow.OnMouseUp(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwPollEvents()
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwPollEvents()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 102
   at Vintagestory.Client.ClientProgram..ctor(String[] rawArgs) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.Client.ClientProgram.Main(String[] rawArgs) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientProgram.cs:line 47
   at VintagestoryClientWindows.ClientWindows.Main(String[] args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryClient\Windows\ClientWindows.cs:line 9.
8.1.2024 22:11:11 [Notification] Exiting game now. Server running=False. Exit reason: Main screen quit button was pressed
```

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
