### ISSUE TITLE
System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by Rodabon** [anegostudios/VintageStory-Issues#3415]
Running on 64 bit Windows 10.0.19045.0 with 16307 MB RAM
Game Version: v1.19.0-rc.6 (Unstable)
1/8/2024 4:06:56 PM: Critical error occurred
Loaded Mods: game@1.19.0-rc.6, creative@1.19.0-rc.6, survival@1.19.0-rc.6
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityItemRenderer..ctor(Entity entity, ICoreClientAPI api) in VSEssentials\EntityRenderer\EntityItemRenderer.cs:line 112
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at Vintagestory.Common.ClassRegistry.CreateEntityRenderer(String className, Object[] args) in VintagestoryLib\Common\ClassRegistry.cs:line 383
   at Vintagestory.Client.NoObf.ClientSystemEntities.OnEntitySpawnOrLoaded(Entity entity, Boolean loaded) in VintagestoryLib\Client\Systems\Entities.cs:line 148
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerEntityLoaded(Entity entity) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 442
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityLoadedPacket(Packet_Server serverpacket) in VintagestoryLib\Client\Systems\Entities.cs:line 210
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 769
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityItemRenderer..ctor(Entity entity, ICoreClientAPI api) in VSEssentials\EntityRenderer\EntityItemRenderer.cs:line 112
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

**Comment by tyronx** [comment]
I would need information on this. How/When did this crash happen?

**Comment by tyronx** [comment]
Please reopen ticket when you have more info available for me, thanks
