### ISSUE TITLE
(linux) Login Failed error. Unable to connect to auth server

### ISSUE THREAD

**Issue by sumixodia** [anegostudios/VintageStory-Issues#3424]
### Game Version

Most recent flatpak

### Platform

Linux

### Modded

Vanilla

### SP/MP

None

### Description

Unable to login. 
My IP is 73.239.52.53 and I am running a Linux OS (Fedora 39)
When I enter my email and password on login page, it gives me an error message saying "Login failed; unable to connect to auth server. I definitely paid for my account, verified my email, even changed my password a few times, and I ran cert-sync before but it didn't fix the issue.

### How to reproduce

1. Launch vintage story
2. Enter login information correctly (from https://account.vintagestory.at/profile)
3. Click "Login" button
4. Error message pops up
Additionally, upon clicking the hyperlink saying "cert-sync" my game crashes before it can send me to the Linux troubleshooting page (which honestly wasn't of too much help anyways)

### Screenshots

https://cdn.discordapp.com/attachments/1194561171592843284/1194561171827736596/image.png?ex=65b0ccc9&is=659e57c9&hm=1921539302371007425618192f5f9bc3bd5ee4816d63112b3e9ea434169dd74f&

![image](https://github.com/anegostudios/VintageStory-Issues/assets/140917659/2c43cc26-4bb3-419c-872a-54af1f6afc45)

### Logs

from client-debug.txt
```10.1.2024 01:21:28 [Debug] Login attempt failed: Unexpected character encountered while parsing value: b. Path '', line 0, position 0.```
```10.1.2024 01:21:30 [Debug] After gamewindow.Run()```

**Comment by sumixodia** [comment]
Here's the crash log that shows up when I click the "cert-sync" link btw, if this helps
```Running on 64 bit Linux with 15945 MB RAM
Game Version: v1.18.15 (Stable)
1/11/2024 7:20:26 PM: Critical error occurred
Loaded Mods: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'https://wiki.vintagestory.at/index.php?title=Installing_the_game_on_Linux#Troubleshooting' with working directory '/app/extra/vintagestory'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Vintagestory.Client.Gui.MainMenuGuiAPI.OpenLink(String href) in VintagestoryLib\Client\MainMenu\API\MainMenuGuiAPI.cs:line 120
   at Vintagestory.API.Client.LinkTextComponent.Trigger() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\TextLinkComponent.cs:line 217
   at Vintagestory.API.Client.LinkTextComponent.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\TextLinkComponent.cs:line 185
   at Vintagestory.API.Client.GuiElementRichtext.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 533
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at GuiScreen.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\MainMenu\Screens\Special\GuiScreen.cs:line 204
   at Vintagestory.Client.ScreenManager.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 883
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 212
   at OpenTK.Windowing.Desktop.NativeWindow.OnMouseUp(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by sumixodia** [comment]
I also tried changing my profile password to only lowercase characters and numbers in case having unsupported characters was the issue but i'm still getting the ```11.1.2024 23:51:36 [Client Debug] Login attempt failed: Unexpected character encountered while parsing value: b. Path '', line 0, position 0.``` error

**Comment by tyronx** [comment]
hi, this should now yield a better error message, but this is caused  by too many login attempts from a given IP. I've removed the block now.

**Comment by sumixodia** [comment]
> hi, this should now yield a better error message, but this is caused by too many login attempts from a given IP. I've removed the block now.

thats it? LOL tysm for the help i can play the game now !!
