### ISSUE TITLE
VS 1.11 RC3 crashed firing bowls in a fire

### ISSUE THREAD

**Issue by CaptainCJH** [anegostudios/VintageStory-Issues#343]
**Game Version:**  v1.11.0-rc.3
**Platform:** Windows10
**Modded:** No

### Description
Game crashed when firing a bowl with firepit dialog open, then tried to grab more firewood at same time. I originally had rot burning then replaced with firewood when rot burned out.

### How to reproduce
1. Open firepit dialog (with log pile in view)
2. Place 5 rot in log area
3. Put unfired bowl in the fire
4. When rot burns off with firepit dialog still open, left click on log pile to grab 2 logs
5. Try to put logs in fire 

### Expected behavior
Expected to simply grab more firewood and add it to the fire.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.11.0-rc.3 (Unstable)11/9/2019 10:09:39 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.InventoryPlayerHotbar.OnItemSlotModified(ItemSlot slot)
   at Vintagestory.API.Common.InventoryBase.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack)
   at Vintagestory.Common.InventoryNetworkUtil.UpdateFromPacket(IWorldAccessor resolver, _s8MGrJZxOnRB0qgEfIVVD8jzCTF packet)
   at _TpRMJqWgRjvAJbNjp2Z144CUmDq._29326LK0w6ywlOTLzsUL162jqaG(_QEPEYij60eKszijwzC0EVWkpHhE , _SJCHe5jAkE2MAbFcaqhPVhGD41J )
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(_DaS9Zjxd7npk8wgf073Pe7MuI2b packet)
   at _QEPEYij60eKszijwzC0EVWkpHhE._6Gy9gcF1PawqlFrPwdXKobeFcXj(Single )
   at _UOQCtSgEAsp0ocCoqKbeL3crPvC._Tm57L6HQTurfUjq8Bw08hqlVBnk(Single )
   at _BPGgoZlHAKyZlEpA7ktkdf6RiUE._8EuUEMQA9TNz4gnPVDnL1wfhKjc(Single )
   at _BPGgoZlHAKyZlEpA7ktkdf6RiUE._a20t8Xifqh6odhUZ22l9SQj89nD(Single )
   at _2zGZhyy3YWEzvl6MfnO9xBmPnKc._foAARl13yqYzHGkILV5BAHB1PMK(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _ZjX6NKIyjhzVAFAfphvX5gY1KXg._Cw9UAQo2NFrmlkmg1ljAaTZHphd(_gyfa5oLIydG9BcOFsQB2fuhMVOp , String[] )
   at _Wl7b32DOsvAzmIvRD4GrQHohuli._Cw9UAQo2NFrmlkmg1ljAaTZHphd(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 11/3/2019 6:25:09 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Graphics.OpenGL.GL.BindFramebuffer(OpenTK.Graphics.OpenGL.FramebufferTarget, Int32)
   at _M5lODpRYCMzH0xb1sYcAxh23W9q._HdmDzPdNcMOEHsiEQA125rQ2Hwb(Vintagestory.API.Client.FrameBufferRef)
   at _4Dp7juVrPdkASmnyujSHfz8fgsw._STC0LlBwKIJqdkKQ0oZ85GGBkek(Vintagestory.API.Client.LoadedTexture, Single, Single, Single, Single, Vintagestory.API.Client.FrameBufferRef, Single, Single, Single)
   at Vintagestory.Client.NoObf.TextureAtlasManager.InsertTexture(Vintagestory.API.Common.BitmapRef, Int32 ByRef, Vintagestory.API.Client.TextureAtlasPosition ByRef, Single)
   at Vintagestory.GameContent.ContainerTextureSource.<get_Item>b__6_0()
   at Vintagestory.API.Util.ObjectCacheUtil.GetOrCreate[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Vintagestory.API.Common.ICoreAPI, System.String, Vintagestory.API.Util.CreateCachableObjectDelegate`1<Int32>)
   at Vintagestory.GameContent.ContainerTextureSource.get_Item(System.String)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(System.String, Int32, Vintagestory.API.Client.MeshData, Vintagestory.API.Common.ShapeElement, Vintagestory.API.Client.ITexPositionSource, Int32, Int32, Vintagestory.API.MathTools.Vec3f, Int32, Int32, Boolean)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(System.String, Vintagestory.API.Client.MeshData, Vintagestory.API.Common.ShapeElement[], Vintagestory.API.Client.ITexPositionSource, Int32, Int32, System.Nullable`1<Int32> ByRef, Vintagestory.API.MathTools.Vec3f, Int32, Int32, Boolean, System.String[])
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(System.String, Vintagestory.API.Client.MeshData, Vintagestory.API.Common.ShapeElement[], Vintagestory.API.Client.ITexPositionSource, Int32, Int32, System.Nullable`1<Int32> ByRef, Vintagestory.API.MathTools.Vec3f, Int32, Int32, Boolean, System.String[])
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(System.String, Vintagestory.API.Common.Shape, Vintagestory.API.Client.MeshData ByRef, Vintagestory.API.Client.ITexPositionSource, Vintagestory.API.MathTools.Vec3f, Int32, Int32, System.Nullable`1<Int32>, Boolean, System.String[])
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(System.String, Vintagestory.API.Common.Shape, Vintagestory.API.Client.MeshData ByRef, Vintagestory.API.Client.ITexPositionSource, Vintagestory.API.MathTools.Vec3f, Int32, Int32, System.Nullable`1<Int32>, System.String[])
   at Vintagestory.GameContent.BlockBucket.GenMesh(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Common.ItemStack, Vintagestory.API.MathTools.BlockPos)
   at Vintagestory.GameContent.BlockEntityBucket.OnTesselation(Vintagestory.API.Client.ITerrainMeshPool, Vintagestory.API.Client.ITesselatorAPI)
   at Vintagestory.Client.NoObf.JsonTesselator.Tesselate(Vintagestory.Client.NoObf.TCTCache)
   at Vintagestory.Client.NoObf.ChunkTesselator.BuildBlockPolygons(Int32, Int32, Int32)
   at Vintagestory.Client.NoObf.ChunkTesselator.ProcessChunk(Int32, Int32, Int32, Vintagestory.API.Common.IChunkBlocks, Int32[], UInt16[], Byte[], Vintagestory.API.Datastructures.IntRef)
   at Vintagestory.Client.NoObf.ChunkTesselatorManager.TesselateChunk(Int32, Int32, Int32, Boolean)
   at Vintagestory.Client.NoObf.ChunkTesselatorManager.OnSeperateThreadGameTick(Single)
   at _RxmU4a7VlL3xYg4pHPT14xey2Hh._cZ5agt2nfpoyiHCyZ5pG54VQiIG()
   at _RxmU4a7VlL3xYg4pHPT14xey2Hh._7wfA4TSvohlYy5GT8Q647TJzerg()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

 }
{ TimeGenerated = 11/3/2019 6:07:41 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Graphics.OpenGL.GL.BindFramebuffer(OpenTK.Graphics.OpenGL.FramebufferTarget, Int32)
   at _M5lODpRYCMzH0xb1sYcAxh23W9q._HdmDzPdNcMOEHsiEQA125rQ2Hwb(Vintagestory.API.Client.FrameBufferRef)
   at _4Dp7juVrPdkASmnyujSHfz8fgsw._STC0LlBwKIJqdkKQ0oZ85GGBkek(Vintagestory.API.Client.LoadedTexture, Single, Single, Single, Single, Vintagestory.API.Client.FrameBufferRef, Single, Single, Single)
   at Vintagestory.Client.NoObf.TextureAtlasManager.InsertTexture(Vintagestory.API.Common.BitmapRef, Int32 ByRef, Vintagestory.API.Client.TextureAtlasPosition ByRef, Single)
   at Vintagestory.GameContent.ContainerTextureSource.<get_Item>b__6_0()
   at Vintagestory.API.Util.ObjectCacheUtil.GetOrCreate[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Vintagestory.API.Common.ICoreAPI, System.String, Vintagestory.API.Util.CreateCachableObjectDelegate`1<Int32>)
   at Vintagestory.GameContent.ContainerTextureSource.get_Item(System.String)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(System.String, Int32, Vintagestory.API.Client.MeshData, Vintagestory.API.Common.ShapeElement, Vintagestory.API.Client.ITexPositionSource, Int32, Int32, Vintagestory.API.MathTools.Vec3f, Int32, Int32, Boolean)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(System.String, Vintagestory.API.Client.MeshData, Vintagestory.API.Common.ShapeElement[], Vintagestory.API.Client.ITexPositionSource, Int32, Int32, System.Nullable`1<Int32> ByRef, Vintagestory.API.MathTools.Vec3f, Int32, Int32, Boolean, System.String[])
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(System.String, Vintagestory.API.Client.MeshData, Vintagestory.API.Common.ShapeElement[], Vintagestory.API.Client.ITexPositionSource, Int32, Int32, System.Nullable`1<Int32> ByRef, Vintagestory.API.MathTools.Vec3f, Int32, Int32, Boolean, System.String[])
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(System.String, Vintagestory.API.Common.Shape, Vintagestory.API.Client.MeshData ByRef, Vintagestory.API.Client.ITexPositionSource, Vintagestory.API.MathTools.Vec3f, Int32, Int32, System.Nullable`1<Int32>, Boolean, System.String[])
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(System.String, Vintagestory.API.Common.Shape, Vintagestory.API.Client.MeshData ByRef, Vintagestory.API.Client.ITexPositionSource, Vintagestory.API.MathTools.Vec3f, Int32, Int32, System.Nullable`1<Int32>, System.String[])
   at Vintagestory.GameContent.BlockBucket.GenMesh(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Common.ItemStack, Vintagestory.API.MathTools.BlockPos)
   at Vintagestory.GameContent.BlockEntityBucket.OnTesselation(Vintagestory.API.Client.ITerrainMeshPool, Vintagestory.API.Client.ITesselatorAPI)
   at Vintagestory.Client.NoObf.JsonTesselator.Tesselate(Vintagestory.Client.NoObf.TCTCache)
   at Vintagestory.Client.NoObf.ChunkTesselator.BuildBlockPolygons(Int32, Int32, Int32)
   at Vintagestory.Client.NoObf.ChunkTesselator.ProcessChunk(Int32, Int32, Int32, Vintagestory.API.Common.IChunkBlocks, Int32[], UInt16[], Byte[], Vintagestory.API.Datastructures.IntRef)
   at Vintagestory.Client.NoObf.ChunkTesselatorManager.TesselateChunk(Int32, Int32, Int32, Boolean)
   at Vintagestory.Client.NoObf.ChunkTesselatorManager.OnSeperateThreadGameTick(Single)
   at _RxmU4a7VlL3xYg4pHPT14xey2Hh._cZ5agt2nfpoyiHCyZ5pG54VQiIG()
   at _RxmU4a7VlL3xYg4pHPT14xey2Hh._7wfA4TSvohlYy5GT8Q647TJzerg()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

 }
{ TimeGenerated = 11/3/2019 6:05:50 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Graphics.OpenGL.GL.BindFramebuffer(OpenTK.Graphics.OpenGL.FramebufferTarget, Int32)
   at _M5lODpRYCMzH0xb1sYcAxh23W9q._HdmDzPdNcMOEHsiEQA125rQ2Hwb(Vintagestory.API.Client.FrameBufferRef)
   at _4Dp7juVrPdkASmnyujSHfz8fgsw._STC0LlBwKIJqdkKQ0oZ85GGBkek(Vintagestory.API.Client.LoadedTexture, Single, Single, Single, Single, Vintagestory.API.Client.FrameBufferRef, Single, Single, Single)
   at Vintagestory.Client.NoObf.TextureAtlasManager.InsertTexture(Vintagestory.API.Common.BitmapRef, Int32 ByRef, Vintagestory.API.Client.TextureAtlasPosition ByRef, Single)
   at Vintagestory.GameContent.ContainerTextureSource.<get_Item>b__6_0()
   at Vintagestory.API.Util.ObjectCacheUtil.GetOrCreate[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Vintagestory.API.Common.ICoreAPI, System.String, Vintagestory.API.Util.CreateCachableObjectDelegate`1<Int32>)
   at Vintagestory.GameContent.ContainerTextureSource.get_Item(System.String)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(System.String, Int32, Vintagestory.API.Client.MeshData, Vintagestory.API.Common.ShapeElement, Vintagestory.API.Client.ITexPositionSource, Int32, Int32, Vintagestory.API.MathTools.Vec3f, Int32, Int32, Boolean)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(System.String, Vintagestory.API.Client.MeshData, Vintagestory.API.Common.ShapeElement[], Vintagestory.API.Client.ITexPositionSource, Int32, Int32, System.Nullable`1<Int32> ByRef, Vintagestory.API.MathTools.Vec3f, Int32, Int32, Boolean, System.String[])
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(System.String, Vintagestory.API.Client.MeshData, Vintagestory.API.Common.ShapeElement[], Vintagestory.API.Client.ITexPositionSource, Int32, Int32, System.Nullable`1<Int32> ByRef, Vintagestory.API.MathTools.Vec3f, Int32, Int32, Boolean, System.String[])
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(System.String, Vintagestory.API.Common.Shape, Vintagestory.API.Client.MeshData ByRef, Vintagestory.API.Client.ITexPositionSource, Vintagestory.API.MathTools.Vec3f, Int32, Int32, System.Nullable`1<Int32>, Boolean, System.String[])
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(System.String, Vintagestory.API.Common.Shape, Vintagestory.API.Client.MeshData ByRef, Vintagestory.API.Client.ITexPositionSource, Vintagestory.API.MathTools.Vec3f, Int32, Int32, System.Nullable`1<Int32>, System.String[])
   at Vintagestory.GameContent.BlockBucket.GenMesh(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Common.ItemStack, Vintagestory.API.MathTools.BlockPos)
   at Vintagestory.GameContent.BlockEntityBucket.OnTesselation(Vintagestory.API.Client.ITerrainMeshPool, Vintagestory.API.Client.ITesselatorAPI)
   at Vintagestory.Client.NoObf.JsonTesselator.Tesselate(Vintagestory.Client.NoObf.TCTCache)
   at Vintagestory.Client.NoObf.ChunkTesselator.BuildBlockPolygons(Int32, Int32, Int32)
   at Vintagestory.Client.NoObf.ChunkTesselator.ProcessChunk(Int32, Int32, Int32, Vintagestory.API.Common.IChunkBlocks, Int32[], UInt16[], Byte[], Vintagestory.API.Datastructures.IntRef)
   at Vintagestory.Client.NoObf.ChunkTesselatorManager.TesselateChunk(Int32, Int32, Int32, Boolean)
   at Vintagestory.Client.NoObf.ChunkTesselatorManager.OnSeperateThreadGameTick(Single)
   at _RxmU4a7VlL3xYg4pHPT14xey2Hh._cZ5agt2nfpoyiHCyZ5pG54VQiIG()
   at _RxmU4a7VlL3xYg4pHPT14xey2Hh._7wfA4TSvohlYy5GT8Q647TJzerg()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

 }
```

**Comment by tyronx** [comment]
thanks a lot for the report. will be fixed in rc.4
