### ISSUE TITLE
1.19rc6 Scrolling through creative inv crashed

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#3430]
### Game Version

v1.19rc6

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Logs

```Running on 64 bit Windows 10.0.22631.0 with 32705 MB RAM
Game Version: v1.19.0-rc.6 (Unstable)
12.01.2024 22:47:28: Critical error occurred
Loaded Mods: betterruins@0.2.5, chiseltools@1.10.1, game@1.19.0-rc.6, blocksoverlay@2.1.2, creativehotbar@0.2.2, th3dungeon@0.2.1-rc.1, creative@1.19.0-rc.6, survival@1.19.0-rc.6, vsvillage@0.8.0
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.Client.MeshData.AddMeshData(MeshData data, MeshDataFilterDelegate dele) in VintagestoryApi\Client\Model\Mesh\MeshData.cs:line 725
   at Vintagestory.API.Client.MeshData.SplitByTextureId()
   at Vintagestory.Client.RenderAPIBase.UploadMultiTextureMesh(MeshData data) in VintagestoryLib\Client\API\RenderAPIBase.cs:line 84
   at Vintagestory.GameContent.BlockClutterBookshelfWithLore.genCombinedMesh(ItemStack itemstack) in VSSurvivalMod\Lore\ResoArchives\BlockClutterBookshelfWithLore.cs:line 63
   at Vintagestory.GameContent.BlockClutterBookshelfWithLore.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo) in VSSurvivalMod\Lore\ResoArchives\BlockClutterBookshelfWithLore.cs:line 39
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 315
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Single dt, Boolean shading, Boolean origRotate, Boolean showStackSize) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 194
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 509
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 716
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 384
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 318
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1006
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 06.01.2024 20:41:53, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.0.0, Zeitstempel: 0x65310000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x0x7880
Startzeit der fehlerhaften Anwendung: 0x0x1da40d846190a97
Pfad der fehlerhaften Anwendung: S:\VintageStoryv1.19\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: S:\VintageStoryv1.19\Vintagestory\Lib\openal32.dll
Berichtskennung: 4ce52944-10c8-47f1-b3da-9aeb9e1c0def
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 13.11.2023 20:12:58, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.0.0, Zeitstempel: 0x6514d416
Name des fehlerhaften Moduls: coreclr.dll, Version: 7.0.1023.36312, Zeitstempel: 0x64b06d6c
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00000000001c98a6
ID des fehlerhaften Prozesses: 0x0x2c2c
Startzeit der fehlerhaften Anwendung: 0x0x1da166512df65e2
Pfad der fehlerhaften Anwendung: S:\VintageStoryv1.19\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.10\coreclr.dll
Berichtskennung: 07a65dce-822e-4a6e-9823-2675e7d3d285
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 13.11.2023 20:10:26, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.0.0, Zeitstempel: 0x6514d416
Name des fehlerhaften Moduls: coreclr.dll, Version: 7.0.1023.36312, Zeitstempel: 0x64b06d6c
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00000000001c98a6
ID des fehlerhaften Prozesses: 0x0xd34
Startzeit der fehlerhaften Anwendung: 0x0x1da1662d25e437f
Pfad der fehlerhaften Anwendung: S:\VintageStoryv1.19\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.10\coreclr.dll
Berichtskennung: d9aae473-cf2f-4e12-a522-925534535968
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }```

**Comment by tyronx** [comment]
Please disable 3rd party mods and try again
