### ISSUE TITLE
OutOfMemoryException 3 seconds after loading the world 

### ISSUE THREAD

**Issue by MihasKonopelko** [anegostudios/VintageStory-Issues#3432]
### Game Version

 v1.19.0-rc.6 (Unstable)

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I loaded into the single-player world.  After 2 or so seconds, the game has crashed with OutOfMemoryException.

Ram is 32 GB, Video Card is Radeon RTX 6800 XT.

Next attempt to load the same safe was successful and no crashes.  Backed up the save just in case.

### How to reproduce

1. Load into the world
2. Look around for 2 seconds or so
3. Crash

(cant really tell anything)

### Logs

Running on 64 bit Windows 10.0.22631.0 with 31962 MB RAM
Game Version: v1.19.0-rc.6 (Unstable)
13/01/2024 19:14:22: Critical error occurred
Loaded Mods: game@1.19.0-rc.6, creative@1.19.0-rc.6, survival@1.19.0-rc.6
System.OutOfMemoryException: Either the graphics card or the OS ran out of memory! Please close other programs and reduce your view distance to prevent the game from crashing.
   at Vintagestory.Client.NoObf.ClientPlatformWindows.CheckGlErrorAlways(String errmsg) in VintagestoryLib\Client\ClientPlatform\GLImpl.cs:line 75
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by pingouyn** [comment]
If that helps, extremely similar error message and steps to reproduce than #3428, just slightly different line numbers in some files.  3428 refers to VS 1.18.15.  Current report is for v1.19.0.rc6.

**Comment by tyronx** [comment]
Is this crash specific to one savegame or it happens on all savegames / multiplayer servers?

**Comment by MihasKonopelko** [comment]
It happened once on that specific save file.  At that moment I did not have any other saves.  The only thing I can offer is a backup of the save if it is of any use.

**Comment by tyronx** [comment]
do please upload if the crash is reproducible in there

**Comment by MihasKonopelko** [comment]
Attempted to reproduce it by loading the save file few times - no more crashes.  I attempted to include the file but it is too big.  Sorry for trouble

**Comment by tyronx** [comment]
ok, lets us know when it happens again
