### ISSUE TITLE
Player not able to connect and crashing with applyTraitAttributes

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#3436]
### Game Version

1.19.0 rc6

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

A player is crashing every time they try to connect to our modded multiplayer server. I did already wipe their data including xskills data and it still continues on. This problem persists since a long time already, i believe at least since 1.18.5

I am not sure if this is getting caused by a mod. Could not find any reference to one.

### Logs

[Server Error] Mod exception: OnPlayerJoinSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.CharacterSystem.applyTraitAttributes(EntityPlayer eplr) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Character\Character.cs:line 287
   at Vintagestory.GameContent.CharacterSystem.setCharacterClass(EntityPlayer player, String classCode, Boolean initializeGear) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Character\Character.cs:line 254
   at Vintagestory.GameContent.CharacterSystem.Event_PlayerJoinServer(IServerPlayer byPlayer) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Character\Character.cs:line 394
   at Vintagestory.Server.ServerEventManager.TriggerPlayerJoin(IServerPlayer player) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerEventManager.cs:line 636

**Comment by WickedSchnitzel** [comment]
Here is the clients log:

Running on 64 bit Windows with 15741 MB RAM
Game Version: v1.18.15 (Stable)
14/01/2024 16:07:21: Critical error occurred
Loaded Mods: acorns@0.5.2, aculinaryartillery@1.0.15, bettercrates@1.6.0, betterruins@0.2.4, Ceramos@0.4.2, chiseltools@1.9.2, drdecor@1.2.0, extrachests@1.7.0, fantasycreatures@0.6.2, capreolinae@1.0.4, foundrymod@1.0.0, furniturelibrary@1.0.9, giantgouramis@1.0.1, instruments@1.2.2, millwright@1.1.0, moreicons_cs@1.1.0, peacockbasses@1.1.1, primitivesurvival@3.3.0, spyglass@0.4.5, tprunes@1.1.0, thecritterpack@0.7.6, translocatorengineeringredux@1.4.7, truesunfishes@1.1.1, game@1.18.15, ancienttools@1.5.9, betterfirepit@1.1.1, betterjonasdevices@1.0.1, canbeignited@1.1.0, carryon@1.0.0, commonlib@2.2.0, expandedfoods@1.6.8, fishing@1.1.5, fromgoldencombs@1.4.21, fsmlib@0.1.8, glidervar@1.1.1, sailboat@1.1.0, medievalexpansion@3.11.1, morepiles@1.4.3, petai@1.8.1, simplestep@1.0.8, stonebakeoven@1.1.0, th3dungeon@0.2.0, usefulstuff17@1.1.6, vinconomy@0.1.3, creative@1.18.15, vsquest@0.5.0, survival@1.18.15, workbenchexpansion@1.7.0, xlib@0.7.4, awearablelight@1.0.8, betterbamboo@1.0.2, bugnetcompatibility@1.0.1, captureanimals@2.5.3, cob@1.5.2, em@2.4.1, maltiezfirearms@0.3.2, playercorpse@1.8.0, rifteye@0.2.4, stonequarry@3.1.7, wolftaming@1.8.0, xskills@0.7.5, bricklayers@2.4.0, vsvillagecob@0.1.4
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.CharacterSystem.applyTraitAttributes(EntityPlayer eplr) in VSSurvivalMod\Systems\Character\Character.cs:line 287
   at Vintagestory.GameContent.CharacterSystem.setCharacterClass(EntityPlayer player, String classCode, Boolean initializeGear) in VSSurvivalMod\Systems\Character\Character.cs:line 254
   at Vintagestory.GameContent.GuiDialogCreateCharacter.OnGuiOpened() in VSSurvivalMod\Gui\GuiDialogCreateCharacter.cs:line 278
   at Vintagestory.API.Client.GuiDialog.TryOpen() in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 283
   at Vintagestory.GameContent.GuiDialogCreateCharacter.PrepAndOpen() in VSSurvivalMod\Gui\GuiDialogCreateCharacter.cs:line 438
   at Vintagestory.GameContent.CharacterSystem.Event_PlayerJoin(IClientPlayer byPlayer) in VSSurvivalMod\Systems\Character\Character.cs:line 324
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerPlayerJoin(IClientPlayer plr) in VintagestoryLib\Client\API\ClientEventAPI.cs:line 235
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 297
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 452
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 446
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 322
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by tyronx** [comment]
hi, I would need the savegame and player name/uid to reproduce this

**Comment by tyronx** [comment]
perhaps you could create a local copy and run `/db prune`. That should greatly decrease the size, I'll see if we can get some service up for you to upload the file

**Comment by WickedSchnitzel** [comment]
The file is gone now since we have wiped and created a new world. The
player was able to join again. If it should happen again ill reach out.

Tyron Madlener ***@***.***> schrieb am Mo., 22. Jan. 2024,
18:11:

**Comment by tyronx** [comment]
👍
