### ISSUE TITLE
Random crash in VSsurvivalMod?!

### ISSUE THREAD

**Issue by MuscleLord** [anegostudios/VintageStory-Issues#3448]
### Game Version

v1.18.15

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Im just walking around and it randomly crashes. Only thing i can think about is that i have new dirtblocks placed and something maybe happpens when grass regrows or new mushrooms popsup?
Probebly comes from some mod, havent tested that yet.

### Logs

Running on 64 bit Windows with 16266 MB RAM
Game Version: v1.18.15 (Stable)
2024-01-17 17:00:23: Critical error occurred
Loaded Mods: autoclose@1.0.1, betterruins@0.2.5, cellardoor@1.4.0, chiseltools@1.10.0, primitivesurvival@3.3.0, spyglass@0.4.7, tprunes@1.1.0, volumetricshadingupdated@0.7.2 -pre.2, game@1.18.15, egocaribautomapmarkers@2.6.0, carryon@1.6.1, commonlib@2.2.0, hudclock@3.3.0, prospecttogether@1.2.4, th3dungeon@0.2.0, creative@1.18 .15, survival@1.18.15, plankstick@1.0.1, playercorpse@1.8.0, tpnet@1.13.2, tieredtradebags@1.0.1
System.NullReferenceException: Object reference not set to an instance of an object.
    at Vintagestory.GameContent.BlockEntityMycelium.setMushroomBlock(Block block) in VSSurvivalMod\BlockEntity\BEMycelium.cs:line 198
    at Vintagestory.GameContent.BlockEntityMycelium.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldAccessForResolve) in VSSurvivalMod\BlockEntity\BEMycelium.cs:line 346
    at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 429
    at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 414
    at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 757
    at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
    at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
    at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
    at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
    at OpenTK.Windowing.Desktop.GameWindow.Run()
    at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
    at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
    at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
=================================
{ TimeGenerated = 2024-01-16 20:13:47, Site = , Source = Application Error, Message = The error occurred in the program named: Vintagestory.exe, version 1.18.15.0, timestamp 0x64e841c5
, the error occurred in the module named: openal32.dll, version 1.23.0.0, timestamp 0x63dd31ad
Exception code: 0x40000015
Error offset: 0x00000000000df046
Process ID: 0x61e0
Program start time: 0x01da48a85c63c399
Program path: D:\Vintagestory\Vintagestory.exe
Path to module: D:\Vintagestory\Lib\openal32.dll
Report ID: 5b55fcea-0f8b-4246-85fb-e70a86385fff
Full name of invalid package:
Program ID relative to invalid package: }
--------------
{ TimeGenerated = 2024-01-16 19:16:55, Site = , Source = Application Error, Message = The error occurred in the program named: Vintagestory.exe, version 1.18.15.0, timestamp 0x64e841c5
, the error occurred in the module named: openal32.dll, version 1.23.0.0, timestamp 0x63dd31ad
Exception code: 0x40000015
Error offset: 0x00000000000df046
Process ID: 0x6368
Program start time: 0x01da48a7fd73c990
Program path: D:\Vintagestory\Vintagestory.exe
Path to module: D:\Vintagestory\Lib\openal32.dll
Report ID: 45117d7f-288f-4e4c-bf56-6dd7a9b2a884
Full name of invalid package:
Program ID relative to invalid package: }
--------------
{ TimeGenerated = 2024-01-16 17:54:34, Site = , Source = Application Error, Message = The error occurred in the program named: Vintagestory.exe, version 1.18.15.0, timestamp 0x64e841c5
, the error occurred in the module named: openal32.dll, version 1.23.0.0, timestamp 0x63dd31ad
Exception code: 0x40000015
Error offset: 0x00000000000df046
Process ID: 0x42b8
Program start time: 0x01da48975012f75e
Program path: D:\Vintagestory\Vintagestory.exe
Path to module: D:\Vintagestory\Lib\openal32.dll
Report ID: fad81f4a-7246-4477-9414-fd21c7651800
Full name of invalid package:
Program ID relative to invalid package: }

**Comment by tyronx** [comment]
I believe this should be fixed in 1.19.0, otherwise please reopen issue
