### ISSUE TITLE
crash 1.11.0 vintage story

### ISSUE THREAD

**Issue by rblueter** [anegostudios/VintageStory-Issues#345]
**Game Version:** 1.11.0
**Platform:** Windows 10
**Modded:** Yes standard ones that install with game
### Description
Game crashed. I think I was looking at a tin bronze bar. Running on a private server. Other players are ok. Crashes every time I log in now.

```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.11.0 (Stable)11/14/2019 11:20:20 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityShapeRenderer.RenderHeldItem(Boolean isShadowPass, Boolean right)
   at Vintagestory.GameContent.EntityShapeRenderer.DoRender3DAfterOIT(Single dt, Boolean isShadowPass)
   at Vintagestory.GameContent.EntityShapeRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass)
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderFrameShadows(Single dt)
   at _AJmwB9gjRtQfKbEhJwx3zt8nBMo._1P3gicAQ2f0W4MdXai0ehZEgtGP(EnumRenderStage , Single )
   at _KTck4LCOI9Iqo8fFumFwcvnhzEf._1P3gicAQ2f0W4MdXai0ehZEgtGP(EnumRenderStage , Single )
   at _KTck4LCOI9Iqo8fFumFwcvnhzEf._BgMbS1c8vdWFI9ITYEhHyeLQERO(Single )
   at _KTck4LCOI9Iqo8fFumFwcvnhzEf._FLbpMrcIgl3spbpL8iz1r63qykf(Single )
   at _D00tv15uR3atThWOWk7dLtkesZS._SLythNsnnZcuxuabMIHFFIqHPBs(Single )
   at _Uzs3ZIOcbeuAACiw0HSA5XAvMcKA._yE1rUldb2bSjw6eqwxEqzSn0q9O(Single )
   at _Uzs3ZIOcbeuAACiw0HSA5XAvMcKA._vNGHYtGKMIbjKqT6XUSd3vg0qMf(Single )
   at _k7exH1LagwKlon0bbWt5grgXY46._w10jFEuqMXWmlNpDfpiNvzId7nn(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _BpmYDwte9UgHL1NeHQCFwWPUFoAA._Sczbg0FjRjmNsd8yOfTFweX0FGBA(_dQW71ep8GlJRb0IDfmlVgByPa4e , String[] )
   at _NMmYWPalISDmLBuhcXuBforA4SJ._Sczbg0FjRjmNsd8yOfTFweX0FGBA(ThreadStart )
-------------------------------
```

**Comment by tyronx** [comment]
Thanks for the report. Is it possible for you to upload that world somewhere? Its a bit difficult to track down the source of this issue otherwise

**Comment by rblueter** [comment]
I replied with a link to the world file. Was it received?

**Comment by tyronx** [comment]
Where did you reply? Here on github? I haven't received any link.

By the way, while I still haven't found the cause of this bug, version 1.11.1-rc.1 will at least prevent the game from crashing. You'll probably have some invisible/broken items in your inventory though.

**Comment by rblueter** [comment]
Here is the link to the world.
https://drive.google.com/open?id=19dHNz2v5SxBTJB8htvyVr5CmEKJTgChr

**Comment by rblueter** [comment]
Version 1.11.1 seems to have fixed the issue.
