### ISSUE TITLE
1.19.0 Crash

### ISSUE THREAD

**Issue by REZ026** [anegostudios/VintageStory-Issues#3451]
### Game Version

1.19.0

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

I used mod before switching to 1.19.0.
Then when I go to my "Castle", it crashes.
See with the linked vid.

https://www.youtube.com/watch?v=AE-XSZp0MJA

### Logs

Running on 64 bit Windows 10.0.22631.0 with 32525 MB RAM
Game Version: v1.19.0 (Stable)
17/01/2024 20:30:09: Critical error occurred
Loaded Mods: game@1.19.0, creative@1.19.0, survival@1.19.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 315
   at Vintagestory.GameContent.EntityItemRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityItemRenderer.cs:line 146
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderFrameShadows(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 165
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 724
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by REZ026** [comment]
new log 

Running on 64 bit Windows 10.0.22631.0 with 32525 MB RAM
Game Version: v1.19.0 (Stable)
17/01/2024 21:11:15: Critical error occurred
Loaded Mods: game@1.19.0, creative@1.19.0, survival@1.19.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 367
   at Vintagestory.Client.NoObf.RenderAPIGame.GetItemStackRenderInfo(ItemSlot inSlot, EnumItemRenderTarget target, Single dt) in VintagestoryLib\Client\API\RenderAPIGame.cs:line 189
   at Vintagestory.GameContent.EntityItemRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityItemRenderer.cs:line 146
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderFrameShadows(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 177
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 199
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 799
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 862
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 723
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 2
==================================
{ TimeGenerated = 17/01/2024 21:10:40, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.19.0.0, horodatage : 0x65310000
Nom du module défaillant : coreclr.dll, version : 7.0.1023.36312, horodatage : 0x64b06d6c
Code d’exception : 0xc0000005
Décalage d’erreur : 0x00000000001c98a6
ID du processus défaillant : 0x0x5cec
Heure de début de l’application défaillante : 0x0x1da498114616d7c
Chemin d’accès de l’application défaillante : C:\Users\gogue\Desktop\Logiciels autres\Vintagestory.exe
Chemin d’accès du module défaillant: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.10\coreclr.dll
ID de rapport : a7e6074f-e741-4e60-aa46-5b0b120b9e6c
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }
--------------
{ TimeGenerated = 17/01/2024 20:35:25, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.19.0.0, horodatage : 0x65310000
Nom du module défaillant : openal32.dll, version : 1.23.0.0, horodatage : 0x63dd31ad
Code d’exception : 0x40000015
Décalage d’erreur : 0x00000000000df046
ID du processus défaillant : 0x0x4600
Heure de début de l’application défaillante : 0x0x1da497c39e32577
Chemin d’accès de l’application défaillante : C:\Users\gogue\Desktop\Logiciels autres\Vintagestory.exe
Chemin d’accès du module défaillant: C:\Users\gogue\Desktop\Logiciels autres\Lib\openal32.dll
ID de rapport : 2374b4ed-9327-41fc-8511-8870aa3c2d67
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }

**Comment by REZ026** [comment]
update, I went back on 1.18.15, and I just lost 50% of my armor stand, dunno why...

**Comment by Th3Dilli** [comment]
how big is your savegame, is it possible that you can provide us with that for testing?

**Comment by Craluminum2413** [comment]
Closing due to inactivity
