### ISSUE TITLE
Crashing due to usage of cleaver on hens

### ISSUE THREAD

**Issue by GarrettRB** [anegostudios/VintageStory-Issues#3453]
### Game Version

1.19.0

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

I am getting a CDT crash when I try to kill some of my hens to harvest them. (World was just updated from latest 1.18 release today.

### How to reproduce

1. Pick up a cleaver
2. Right click or left click to kill a gen 4 hen
3. be unlucky and crash on the 4th kill

### Logs

```Running on 64 bit Windows 10.0.19045.0 with 65437 MB RAM
Game Version: v1.19.0 (Stable)
1/17/2024 5:32:16 PM: Critical error occurred
Loaded Mods: game@1.19.0, creative@1.19.0, survival@1.19.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemCleaver.hitEntity(EntityAgent byEntity) in VSSurvivalMod\Item\ItemCleaver.cs:line 94
   at Vintagestory.GameContent.ItemSword.<>c__DisplayClass8_0.<startAttack>b__1() in VSSurvivalMod\Item\ItemSword.cs:line 76
   at Vintagestory.API.Common.AnimationManager.runTriggers() in VintagestoryApi\Common\Model\Animation\AnimationManager.cs:line 357
   at Vintagestory.API.Common.PlayerAnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Entity\PlayerAnimationManager.cs:line 32
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 724
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 1/17/2024 2:07:15 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x65310000
Faulting module name: coreclr.dll, version: 7.0.1023.36312, time stamp: 0x64b06d6c
Exception code: 0xc0000005
Fault offset: 0x00000000001c98a6
Faulting process id: 0xda0c
Faulting application start time: 0x01da4977751d46bd
Faulting application path: C:\Users\Eides\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.10\coreclr.dll
Report Id: e7e565c7-58cd-4811-8f2c-5608a98441ec
Faulting package full name: 
Faulting package-relative application ID:  }```

**Comment by Shadenessness** [comment]
Same happens to me, but they were gen 7 and 8 chickens.

`Running on 64 bit Windows 10.0.22631.0 with 32495 MB RAM
Game Version: v1.19.0 (Stable)
18/01/2024 10:42:03: Critical error occurred
Loaded Mods: game@1.19.0, prospecttogether@1.3.0-rc.3, creative@1.19.0, survival@1.19.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemCleaver.hitEntity(EntityAgent byEntity) in VSSurvivalMod\Item\ItemCleaver.cs:line 94
   at Vintagestory.GameContent.ItemSword.<>c__DisplayClass8_0.<startAttack>b__1() in VSSurvivalMod\Item\ItemSword.cs:line 76
   at Vintagestory.API.Common.AnimationManager.runTriggers() in VintagestoryApi\Common\Model\Animation\AnimationManager.cs:line 357
   at Vintagestory.API.Common.PlayerAnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Entity\PlayerAnimationManager.cs:line 32
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 724
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
`

**Comment by radfast** [comment]
Thanks for reporting, will be fixed in next build.  The report is correct, this can happen whenever the target moves out of the crosshairs while the Cleaver is swinging ... and not only hens.
