### ISSUE TITLE
Crash with CarryOn for 1.19.1

### ISSUE THREAD

**Issue by EldritchLemon** [anegostudios/VintageStory-Issues#3478]
Running on 64 bit Windows 10.0.19045.0 with 20429 MB RAM
Game Version: v1.19.1 (Stable)
1/19/2024 5:30:39 PM: Critical error occurred in the following mod: carryon@1.7.0-pre.3
Loaded Mods: butchering@1.1.0, chiseltools@1.10.1, caninae@1.0.8, capreolinae@1.0.5, pantherinae@1.0.9, immersivecorpsedrop@1.0.2, moremolds@1.4.2, pondfrogsiii@1.2.3, newzealandfrogs@1.1.1, pondfrogsi@1.2.3, OresAPlenty@3.1.0, primitivesurvival@3.4.5, rainfrogs@1.2.1, riflemod@1.1.0, game@1.19.1, abcsreborn@0.1.4, alchemy@1.6.22, betterfirepit@1.1.3, carryon@1.7.0-pre.3, commonlib@2.3.2, cooperativecombat@1.1.1, divisionoflabor@1.0.8, fieldsofsalt@1.2.0, fromgoldencombs@1.4.25, petai@2.2.1, temporalprospector@1.0.1, th3dungeon@0.2.1-rc.1, creative@1.19.1, survival@1.19.1, tpnet@1.14.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockBehaviorCreatureContainer.HasAnimal(ItemStack itemStack) in VSSurvivalMod\BlockBehavior\BehaviorCreatureContainer.cs:line 31
   at Vintagestory.GameContent.BlockBehaviorCreatureContainer.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, EnumHandling& handling, String& failureCode) in VSSurvivalMod\BlockBehavior\BehaviorCreatureContainer.cs:line 123
   at Vintagestory.API.Common.Block.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, String& failureCode) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 791
   at CarryOn.API.Common.CarriedBlock.PlaceDown(IWorldAccessor world, BlockSelection selection, Entity entity, Boolean dropped, Boolean playSound) in G:\git\github\Nerdscurvy\CarryOn\src\API\Common\CarriedBlock.cs:line 195
   at CarryOn.API.Common.CarriedBlockExtensions.PlaceCarried(IPlayer player, BlockSelection selection, CarrySlot slot) in G:\git\github\Nerdscurvy\CarryOn\src\API\Common\CarriedBlockExtensions.cs:line 135
   at CarryOn.Common.CarryHandler.PlaceDown(IPlayer player, CarriedBlock carried, BlockSelection selection, BlockPos& placedAt) in G:\git\github\Nerdscurvy\CarryOn\src\Common\CarryHandler.cs:line 525
   at CarryOn.Common.CarryHandler.OnGameTick(Single deltaTime) in G:\git\github\Nerdscurvy\CarryOn\src\Common\CarryHandler.cs:line 355
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 82
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 831
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 723
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
Caused by mod

**Comment by SpearAndFang** [comment]
There's a newer version of Carry On.  Should fix it.
