### ISSUE TITLE
1.19.1 Crashes Upon Loading Worlds

### ISSUE THREAD

**Issue by GunnerLD413** [anegostudios/VintageStory-Issues#3482]
### Game Version

V1.19.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Tried creating a new world from the seed of the previous 1.19.0 world so I could use creative mode to scout the map, game crashes right before loading the world. Disabled all mods in belief it was a modded issue, and still crashing.

### Logs

```Log```
Running on 64 bit Windows 10.0.22621.0 with 32703 MB RAM
Game Version: v1.19.1 (Stable)
1/20/2024 1:01:26 AM: Critical error occurred
Loaded Mods: game@1.19.1, creative@1.19.1, survival@1.19.1
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.Format(String format, Object[] args)
   at Vintagestory.GameContent.ErrorReporter.Logger_EntryAdded(EnumLogType logType, String message, Object[] args) in VSEssentials\Systems\ErrorReporter.cs:line 173
   at Vintagestory.Client.GuiScreenRunningGame.printWarningsAndEndCapture() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 383
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 1/20/2024 12:58:44 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.1.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x3e78
Faulting application start time: 0x0x1da4b6586e8f8c2
Faulting application path: S:\Vintagestory\Vintagestory.exe
Faulting module path: S:\Vintagestory\Lib\openal32.dll
Report Id: b1241529-f289-478e-8e86-35517b074627
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 1/20/2024 12:52:55 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.1.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0xdc
Faulting application start time: 0x0x1da4b64abb9e980
Faulting application path: S:\Vintagestory\Vintagestory.exe
Faulting module path: S:\Vintagestory\Lib\openal32.dll
Report Id: 336bb76a-836c-47a7-9c13-1e29eda93713
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 1/20/2024 12:51:05 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.1.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x64c
Faulting application start time: 0x0x1da4b64171836fb
Faulting application path: S:\Vintagestory\Vintagestory.exe
Faulting module path: S:\Vintagestory\Lib\openal32.dll
Report Id: 75c48304-4ffe-4290-870c-75062958bb00
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Th3Dilli** [comment]
can you reproduce this without mods when creating a new world?
if so can you send the full server-main and client-main log files

**Comment by Craluminum2413** [comment]
Closing due to inactivity
