### ISSUE TITLE
AiTaskSeekFoodAndEat error

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#3486]
### Game Version

1.19.1

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Found this in the server console. Not sure if vanilla or caused by a mod though.

### Logs

[Server Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.AiTaskSeekFoodAndEat.suitableFoodSource(ItemStack itemStack) in VSEssentials\Entity\AI\Task\TasksImpl\AiTaskSeekFoodAndEat.cs:line 159
   at Vintagestory.GameContent.AiTaskSeekFoodAndEat.<ShouldExecute>b__25_0(Entity e) in VSEssentials\Entity\AI\Task\TasksImpl\AiTaskSeekFoodAndEat.cs:line 122
   at Vintagestory.GameContent.EntityPartitioning.WalkEntities(Vec3d centerPos, Double radius, ActionConsumable`1 callback, RangeTestDelegate onRangeTest, Boolean interactable) in VSEssentials\Systems\EntityPartitioning.cs:line 313
   at Vintagestory.GameContent.AiTaskSeekFoodAndEat.ShouldExecute() in VSEssentials\Entity\AI\Task\TasksImpl\AiTaskSeekFoodAndEat.cs:line 147
   at Vintagestory.GameContent.AiTaskManager.OnGameTick(Single dt) in VSEssentials\Entity\AI\Task\AiTaskManager.cs:line 174
   at Vintagestory.GameContent.EntityBehaviorTaskAI.OnGameTick(Single deltaTime) in VSEssentials\Entity\AI\Task\BehaviorTaskAI.cs:line 114
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\Entity.cs:line 867
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 537
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt) in VintagestoryLib\Server\Systems\World\EntitySimulation.cs:line 329
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt) in VintagestoryLib\Server\Systems\World\EntitySimulation.cs:line 168
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 886

**Comment by radfast** [comment]
Mod issue.  Look at mods which add new creatures.  Look at the .json files for those creatures.  Probably they do not specify the diet.

**Comment by radfast** [comment]
Meanwhile, I've made it so that in the next game version (hopefully 1.19.2) it won't crash and there will be an informative Warning in the log file, so hopefully the mod author understands what to fix.
