### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#3487]
### Game Version

1.19.1

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Using chiseled schematics in the vsvillage mod to let villages spawn in game will result in this error if used in conjunction with some other mods. I am not sure if this is a problem of the mod or if it may have to do with the recent changes that have been made in the vanilla game. I just thought someone might notice something in the logs leading to vanilla. if not, ignore this post.

Also when this occurs, the game seems not to be able to let the player spawn. 

[Server Notification] Trying another spawn location (2/5)...
20.1.2024 09:14:22 [Server Event] 0% (171 in queue)
20.1.2024 09:14:22 [Server Notification] Trying another spawn location (3/5)...
20.1.2024 09:14:23 [Server Event] 0% (207 in queue)
20.1.2024 09:14:25 [Server Event] 0% (235 in queue)
20.1.2024 09:14:26 [Server Notification] Trying another spawn location (4/5)...

..will be seen in the console only when the crash is not occuring

### Logs

[Server Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityMicroBlock.OnTransformed(IWorldAccessor worldAccessor, ITreeAttribute tree, Int32 byDegrees, Dictionary`2 oldBlockIdMapping, Dictionary`2 oldItemIdMapping, Nullable`1 flipAroundAxis) in VSSurvivalMod\Systems\Microblock\BEMicroBlock.cs:line 481
   at Vintagestory.API.Common.BlockSchematic.TransformWhilePacked(IWorldAccessor worldForResolve, EnumOrigin aroundOrigin, Int32 angle, Nullable`1 flipAxis) in VintagestoryApi\Common\Collectible\Block\BlockSchematic.cs:line 925
   at VsVillage.WorldGenVillageStructure.Init(ICoreServerAPI api) in E:\VS Arbeitsdateien\Projekte\VSVillageCoB\src\Systems\WorldGen\VillageStructure.cs:line 50
   at VsVillage.VillageGenerator.initWorldGen() in E:\VS Arbeitsdateien\Projekte\VSVillageCoB\src\Systems\WorldGen\Villagegenerator.cs:line 108
   at Vintagestory.Server.ServerSystemSupplyChunks.LoadWorldgenHandlerAndSpawnChunks() in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 1333
   at Vintagestory.Server.ServerSystemLoadAndSaveGame.OnWorldgenStartup() in VintagestoryLib\Server\Systems\World\LoadThread\LoadSaveGame.cs:line 185
   at Vintagestory.Server.ServerEventManager.TriggerWorldgenStartup() in VintagestoryLib\Server\ServerEventManager.cs:line 481
   
   and
   
   [Server Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.Server.ServerMain.EntityPosFromSpawnPos(PlayerSpawnPos playerSpawn) in VintagestoryLib\Server\ServerMain.cs:line 1473
   at Vintagestory.Server.ServerMain.GetSpawnPosition(String playerUID, Boolean onlyGlobalDefaultSpawn, Boolean consumeSpawn) in VintagestoryLib\Server\ServerMain.cs:line 1451
   at Vintagestory.Server.ServerMain.FinalizePlayerIdentification(Packet_ClientIdentification packet, ConnectedClient client, String entitlements) in VintagestoryLib\Server\ServerMainNetworking.cs:line 259
   at Vintagestory.Server.ServerMain.<>c__DisplayClass292_1.<VerifyPlayerWithAuthServer>b__1() in VintagestoryLib\Server\ServerMainNetworking.cs:line 179
   at Vintagestory.Server.ServerMain.ProcessMainThreadTasks() in VintagestoryLib\Server\ServerMain.cs:line 2777
   at Vintagestory.Server.ServerMain.ProcessMain() in VintagestoryLib\Server\ServerMain.cs:line 893
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 886

**Comment by WickedSchnitzel** [comment]
I have just noted that if one does add the vsvillage mod with chiseled schematics to the server first, let the savegame generate and then add the other mods that are causing the error, it will work without errors. But not the other way around. 

As mentioned, i am not sure if this is even a vanilla problem.

**Comment by radfast** [comment]
Looks like the same problem has been reported on [Discord](https://discord.com/channels/302152934249070593/1198652047529099325)

We can investigate this.  It would help if you can share a chiseled schematic file which has this problem, unless you're saying it's a problem with literally every chiseled block?

**Comment by radfast** [comment]
[Server Error] Exception: Object reference not set to an instance of an object.
    at Vintagestory.Server.ServerMain.EntityPosFromSpawnPos(PlayerSpawnPos playerSpawn) in VintagestoryLib\Server\ServerMain.cs:line 1473

^^^ This seems to be an unrelated issue, caused by mods erroring during the game's startup, therefore breaking stuff.  Is your `server-main.txt` log clean - no errors or warnings - prior to this?  If not a clean prior log, then fix the earlier errors, most likely by removing or updating mods, then re-test.

**Comment by WickedSchnitzel** [comment]
I believe its them all. But i can send one later.

radfast ***@***.***> schrieb am Mo., 22. Jan. 2024, 15:11:

**Comment by WickedSchnitzel** [comment]
as i wrote, it seems to not matter which schematic.
![Vintagestory Screenshot 2024 01 22 - 21 03 16 51](https://github.com/anegostudios/VintageStory-Issues/assets/61825560/31669459-42fa-422c-af52-e7dccadae266)
[server-spawn-biome-119.json](https://github.com/anegostudios/VintageStory-Issues/files/14014863/server-spawn-biome-119.json)

**Comment by WickedSchnitzel** [comment]
this may not be the best example for you, because there will be missing blocks if you should test with this, since it also uses modded blocks. but this error will display with all schematics, even if they do not use modded blocks

**Comment by WickedSchnitzel** [comment]
> ```
> [Server Error] Exception: Object reference not set to an instance of an object.
> at Vintagestory.Server.ServerMain.EntityPosFromSpawnPos(PlayerSpawnPos playerSpawn) in VintagestoryLib\Server\ServerMain.cs:line 1473
> ```
> 
> ^^^ This seems to be an unrelated issue, caused by mods erroring during the game's startup, therefore breaking stuff. Is your `server-main.txt` log clean - no errors or warnings - prior to this? If not a clean prior log, then fix the earlier errors, most likely by removing or updating mods, then re-test.

by the way, that happens only together with the above Dictionary2 oldBlockIdMapping, Dictionary2 oldItemIdMapping error. It's related to the schematic problem.

**Comment by radfast** [comment]
We have now found the issue with schematics in the **unmodded game** and found the explanation why it didn't show up in simple testing: the issue only occurred if the same schematic was rotated multiple times.

That issue is resolved, fix will be in next game version 1.19.2.  Thank you for the report.

You are correct that it related to block mappings.  If block mappings break during loading (likely a mod issue) then this schematics /with chiseled blocks issue might come back.  If that's an issue only with mods present, we can't fix it but the relevant mod author should be able to.
