### ISSUE TITLE
Server startup "Failed registering block" on startup

### ISSUE THREAD

**Issue by Anthony-Mariotti** [anegostudios/VintageStory-Issues#3490]
### Game Version

v1.19.1

### Platform

Linux

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Upon updating my server from `v1.18.15` to `v1.19.0` and I started to receive console outputs about blocks failed to be registered and need to be a unique id. I never had any mods installed and it's purely vanilla. The errors continue through to version `v1.19.1`

This doesn't seem, for now, to affect any gameplay of users on the server, but I just wonder if it would be expected to actually have these errors being triggered in the first place or it's because of the update. So it would probably be a lower priority to even look into something like this.

My server is running on pterodactyl and using docker container: `ghcr.io/parkervcp/yolks:dotnet_7`

### Logs

```
20.1.2024 23:04:39 [Notification] JsonPatch Loader: 2 patches total, successfully applied 2 patches, no issues
20.1.2024 23:04:44 [Notification] Loaded 3318 unique items
20.1.2024 23:04:51 [Error] Failed registering block game:conditionalblock-east
20.1.2024 23:04:51 [Error] Exception: Block must have a unique code ('game:conditionalblock-east' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.Server.ServerCoreAPI.RegisterBlock(Block block) in VintagestoryLib\Server\API\ServerCoreAPI.cs:line 131
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 263
20.1.2024 23:04:51 [Error] Failed registering block game:conditionalblock-north
20.1.2024 23:04:51 [Error] Exception: Block must have a unique code ('game:conditionalblock-north' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.Server.ServerCoreAPI.RegisterBlock(Block block) in VintagestoryLib\Server\API\ServerCoreAPI.cs:line 131
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 263
20.1.2024 23:04:51 [Error] Failed registering block game:conditionalblock-west
20.1.2024 23:04:51 [Error] Exception: Block must have a unique code ('game:conditionalblock-west' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.Server.ServerCoreAPI.RegisterBlock(Block block) in VintagestoryLib\Server\API\ServerCoreAPI.cs:line 131
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 263
20.1.2024 23:04:51 [Error] Failed registering block game:conditionalblock-south
20.1.2024 23:04:51 [Error] Exception: Block must have a unique code ('game:conditionalblock-south' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.Server.ServerCoreAPI.RegisterBlock(Block block) in VintagestoryLib\Server\API\ServerCoreAPI.cs:line 131
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 263
20.1.2024 23:04:51 [Error] Failed registering block game:worldgenhook-normal
20.1.2024 23:04:51 [Error] Exception: Block must have a unique code ('game:worldgenhook-normal' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.Server.ServerCoreAPI.RegisterBlock(Block block) in VintagestoryLib\Server\API\ServerCoreAPI.cs:line 131
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 263
20.1.2024 23:04:51 [Error] Failed registering block game:tickerblock-normal
20.1.2024 23:04:51 [Error] Exception: Block must have a unique code ('game:tickerblock-normal' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.Server.ServerCoreAPI.RegisterBlock(Block block) in VintagestoryLib\Server\API\ServerCoreAPI.cs:line 131
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 263
20.1.2024 23:04:51 [Error] Failed registering block game:commandblock-normal
20.1.2024 23:04:51 [Error] Exception: Block must have a unique code ('game:commandblock-normal' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.Server.ServerCoreAPI.RegisterBlock(Block block) in VintagestoryLib\Server\API\ServerCoreAPI.cs:line 131
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 263
20.1.2024 23:04:51 [Error] Failed registering block game:initcommandblock-normal
20.1.2024 23:04:51 [Error] Exception: Block must have a unique code ('game:initcommandblock-normal' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.Server.ServerCoreAPI.RegisterBlock(Block block) in VintagestoryLib\Server\API\ServerCoreAPI.cs:line 131
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 263
20.1.2024 23:04:54 [Error] Failed registering block game:stationarybasket-north
20.1.2024 23:04:54 [Error] Exception: Block must have a unique code ('game:stationarybasket-north' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
20.1.2024 23:04:54 [Error] Failed registering block game:stationarybasket-east
20.1.2024 23:04:54 [Error] Exception: Block must have a unique code ('game:stationarybasket-east' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
20.1.2024 23:04:54 [Error] Failed registering block game:stationarybasket-south
20.1.2024 23:04:54 [Error] Exception: Block must have a unique code ('game:stationarybasket-south' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
20.1.2024 23:04:54 [Error] Failed registering block game:stationarybasket-west
20.1.2024 23:04:54 [Error] Exception: Block must have a unique code ('game:stationarybasket-west' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
20.1.2024 23:04:54 [Error] Failed registering block game:meta-filler
20.1.2024 23:04:54 [Error] Exception: Block must have a unique code ('game:meta-filler' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
20.1.2024 23:04:54 [Error] Failed registering block game:meta-pathway
20.1.2024 23:04:54 [Error] Exception: Block must have a unique code ('game:meta-pathway' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
20.1.2024 23:04:54 [Error] Failed registering block game:meta-underground
20.1.2024 23:04:54 [Error] Exception: Block must have a unique code ('game:meta-underground' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
20.1.2024 23:04:54 [Error] Failed registering block game:meta-spawner
20.1.2024 23:04:54 [Error] Exception: Block must have a unique code ('game:meta-spawner' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
20.1.2024 23:04:54 [Error] Failed registering block game:meta-collider
20.1.2024 23:04:54 [Error] Exception: Block must have a unique code ('game:meta-collider' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
20.1.2024 23:04:54 [Error] Failed registering block game:meta-music
20.1.2024 23:04:54 [Error] Exception: Block must have a unique code ('game:meta-music' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
20.1.2024 23:04:54 [Notification] Loaded 9328 unique blocks
20.1.2024 23:04:54 [Notification] Loaded 612 unique entities
20.1.2024 23:04:54 [Notification] BlockLoader: Entities, Blocks and Items loaded
```

**Comment by Craluminum2413** [comment]
Have you tried to clean reinstall the game?

**Comment by Anthony-Mariotti** [comment]
> Have you tried to clean reinstall the game?

When you mean full install do you mean. Removing all directories and files except for the our main data folder where our save is?

`assets`
`Lib`
`Mods`
`*.{dll,json,dll,etc`

**Comment by Craluminum2413** [comment]
Folder with Vintagestory.exe should be clear after uninstalling, this is what clear install is

**Comment by Anthony-Mariotti** [comment]
Clear install does seem to clear up the issue, looks like during installation on the server host, the installation script did not clear out those directories. There is an update to the installation script for pterodactyl in the works.
