### ISSUE TITLE
Game crashes after clicking tong name in guide.

### ISSUE THREAD

**Issue by tomekatomek123456789** [anegostudios/VintageStory-Issues#3496]
### Game Version

v1.19.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### How to reproduce

1. Play about 30min.
2. Open guide with smelting and click tong name.
3. Unhandled exception is thrown.

### Logs

```
Running on 64 bit Windows 10.0.19045.0 with 31608 MB RAM
Game Version: v1.19.1 (Stable)
21.01.2024 18:23:25: Critical error occurred
Loaded Mods: game@1.19.1, creative@1.19.1, survival@1.19.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Client.LinkTextComponent.HandleLink() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\TextLinkComponent.cs:line 208
   at Vintagestory.API.Client.LinkTextComponent.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\TextLinkComponent.cs:line 185
   at Vintagestory.API.Client.GuiElementRichtext.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 524
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 449
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 583
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 412
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1874
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 208
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

```

**Comment by radfast** [comment]
I can't reproduce this. Tongs link in the Smelting guide (in English) works OK for me. Are you playing the game in English? Could be a typo in that guide text translated in a different language.  The `<a href` code to create a good link is case-sensitive.

Anyhow we can make it not crash here in future, just fail silently. But would be good to know why the tongs is not working for you, please do let us know which language.

**Comment by tomekatomek123456789** [comment]
> If it's the Polish translation ... Please talk to the Polish translators in the Discord channel, #wiki-and-translations. They translated the links in the Smelting guide, they should not have. For example `<a href=\"handbooksearch://drewniane szczypce>` should be `<a href=\"handbooksearch://tongs\">` Note, they also missed off this punctuation at the end `\"` which is important in formatting, that's what actually caused the crash! Other links in the Smelting / Metallurgy 101 guide have the same problem, maybe in other guides also, it's worth checking them all.

Thanks for response. And yes, it's Polish translation.

**Comment by Craluminum2413** [comment]
Doesn't crash anymore
