### ISSUE TITLE
The given key 'nightVisionStrength' was not present in the dictionary

### ISSUE THREAD

**Issue by UnProgramator** [anegostudios/VintageStory-Issues#3498]
### Game Version

v1.19.1

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

I created a world (standard settings, 1024 hight), It cashes when starting with  "The given key 'nightVisionStrength' was not present in the dictionary"

### How to reproduce

starting any world gives the crash

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32718 MB RAM
Game Version: v1.19.1 (Stable)
21.01.2024 20:59:58: Critical error occurred
Loaded Mods: cloudy3dx@1.0.9, game@1.19.1, creative@1.19.1, survival@1.19.1
System.Collections.Generic.KeyNotFoundException: The given key 'nightVisionStrength' was not present in the dictionary.
   at Vintagestory.Client.NoObf.ShaderProgramBase.Uniform(String uniformName, Single value) in VintagestoryLib\Client\ClientPlatform\ShaderProgramBase.cs:line 131
   at Vintagestory.Client.NoObf.ShaderProgramBase.Use() in VintagestoryLib\Client\ClientPlatform\ShaderProgramBase.cs:line 281
   at Vintagestory.Client.Gui.MainMenuRenderAPI.Render2DTexture(Int32 textureid, Single posX, Single posY, Single width, Single height, Single z, Vec4f color) in VintagestoryLib\Client\MainMenu\API\MainMenuRenderAPI.cs:line 131
   at Vintagestory.Client.GuiCompositeMainMenuLeft.Render(Single dt, Int64 ellapsedMs, Boolean mainMenuVisible, Boolean onlyBackground) in VintagestoryLib\Client\MainMenu\Composite\GuiCompositeMainMenuLeft.cs:line 462
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 21.01.2024 20:59:30, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.1.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x1c04
Faulting application start time: 0x01da4c99c47f759b
Faulting application path: E:\Games\Vintagestory\Vintagestory.exe
Faulting module path: E:\Games\Vintagestory\Lib\openal32.dll
Report Id: 0b88fa92-dc80-4c40-ac45-b0111bbe8c34
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by UnProgramator** [comment]
I forgot to mention, I tried to open three different worlds, two of them which could be opened on 1.19.0 (stable)

**Comment by UnProgramator** [comment]
I checked again the mods and found that I have installed for some reason "Cloudy 3DX (Content)" 1.0.9, which cause the error, I probably forgot to check if the mod worked when I installed it and forgot I installed  it.

**Comment by radfast** [comment]
No worries, thanks for the update.  If you report this to the Cloudy 3DX mod author it might help, they might not be aware of it.
