### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by level70elite** [anegostudios/VintageStory-Issues#3500]
### Game Version

V1.19.1

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I opened the guide book and searched up "bask" to find the recipe for a basket. The moment I pressed K, the game crashed

### Logs

Running on 64 bit Windows 10.0.19045.0 with 22456 MB RAM
Game Version: v1.19.1 (Stable)
22/01/2024 9:36:51 PM: Critical error occurred in the following mod: sortablestorage@1.8.0
Loaded Mods: moreicons_cs@1.1.0, playercorpse@1.6.0-rc.1, sortablestorage@1.8.0, sticksfromfirewood@1.0.0, game@1.19.1, egocaribautomapmarkers@3.1.0, creative@1.19.1, survival@1.19.1, metalrecovery@0.1.19-pre.1, bullseye@2.5.1, treetapping@1.0.0
System.MissingFieldException: Field not found: 'Vintagestory.API.Client.ItemRenderInfo.ModelRef'.
   at SortableStorage.ModSystem.BlockGenericSortableTypedContainer.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 315
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Single dt, Boolean shading, Boolean origRotate, Boolean showStackSize) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 194
   at Vintagestory.Client.NoObf.RenderAPIGame.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Boolean shading, Boolean rotate, Boolean showStacksize) in VintagestoryLib\Client\API\RenderAPIGame.cs:line 274
   at Vintagestory.GameContent.GuiHandbookItemStackPage.RenderListEntryTo(ICoreClientAPI capi, Single dt, Double x, Double y, Double cellWidth, Double cellHeight) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 102
   at Vintagestory.GameContent.GuiElementFlatList.RenderInteractiveElements(Single deltaTime) in VSSurvivalMod\Systems\Handbook\Gui\GuiElementFlatList.cs:line 194
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 716
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 384
   at Vintagestory.GameContent.GuiDialogHandbook.OnRenderGUI(Single deltaTime) in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 493
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 318
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1006
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
Caused by mod

**Comment by radfast** [comment]
@level70elite look at SortableStorage.  My recommendation would be disable it for now until it's updated, and report this to the mod author, they may not know about it otherwise...

**Comment by SpearAndFang** [comment]
Or better yet, just download the correct version of the mod.  That one that crashed is for an old version of the game. ;)
