### ISSUE TITLE
Unable to load existing saves or create new ones

### ISSUE THREAD

**Issue by WilliamSivlar** [anegostudios/VintageStory-Issues#3510]
### Game Version

v1.19.1(stable)

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Whenever I load an existing save or try to create a new one, the console reads out the loading texts like normal.
Eventually, it stops loading and the console displays "Something went awry...please check the program logs... (Exception thrown by server during startup or process)" and the only thing I can do is open logs and cancel back to the main menu. If I go back and try to load the same save, the save's name is displayed as the file name with the ".vcdbs" file extension, and red text in the description which reads "Unable to load savegame and no write access, likely already opened elsewhere." When I boot task manager, the game itself is the only thing that should be accessing the save files. If I try to run the save anyways, it brings up a corrupted world error and gives me the option to repair it. If I attempt to repair it, it attempts to repair and immediately stops.

### How to reproduce

Make a new world or load an existing one.

### Screenshots

![Screenshot (877)](https://github.com/anegostudios/VintageStory-Issues/assets/143749393/6a6cf7bb-f71d-40df-8b5e-0da312c09bdc)
![Screenshot (878)](https://github.com/anegostudios/VintageStory-Issues/assets/143749393/8d9472fc-d4ba-462d-be32-30962e78c1cc)
![Screenshot (880)](https://github.com/anegostudios/VintageStory-Issues/assets/143749393/a1b1cf94-2085-47cb-a1a6-67944d3dcb7b)
![Screenshot (882)](https://github.com/anegostudios/VintageStory-Issues/assets/143749393/ce64a6e7-b700-4166-8b1b-d2d26fcf0ab2)
![Screenshot (884)](https://github.com/anegostudios/VintageStory-Issues/assets/143749393/8b49be09-9f5f-4655-a145-ce65f9d35a42)
![Screenshot (890)](https://github.com/anegostudios/VintageStory-Issues/assets/143749393/37566bc9-138c-43e1-9f94-7e3320b7c6cb)

### Logs

Server Main
```25.1.2024 02:30:13 [Notification] Server logger started.
25.1.2024 02:30:13 [Notification] Game Version: v1.19.1 (Stable)
25.1.2024 02:30:13 [Event] Launching server...
25.1.2024 02:30:13 [Event] Server v1.19.1, network v1.19.4, api v1.19.0
25.1.2024 02:30:13 [Notification] Entering runphase Initialization
25.1.2024 02:30:13 [Event] Loading configuration...
25.1.2024 02:30:13 [Notification] Entering runphase Configuration
25.1.2024 02:30:13 [Fatal] Unable to open or create savegame.
25.1.2024 02:30:13 [Error] Exception: Cannot open savegame database file C:\Users\will0\AppData\Roaming\VintagestoryData\Saves\gloomy adventure story.vcdbs, it seems to be not writable!
   at Vintagestory.API.Common.SQLiteDBConnection.OpenOrCreate(String filename, String& errorMessage, Boolean requireWriteAccess, Boolean corruptionProtection, Boolean doIntegrityCheck) in VintagestoryApi\Common\IO\SQLiteDBConnection.cs:line 42
   at Vintagestory.Common.Database.SQLiteDbConnectionv2.Vintagestory.Common.Database.IGameDbConnection.OpenOrCreate(String filename, String& errorMessage, Boolean requireWriteAccess, Boolean corruptionProtection, Boolean doIntegrityCheck)
   at Vintagestory.Common.GameDatabase.OpenConnection(String databaseFilename, Int32 databaseVersion, String& errorMessage, Boolean requireWriteAccess, Boolean corruptionProtection, Boolean doIntegrityCheck) in VintagestoryLib\Common\FileIO\Database\GameDatabase.cs:line 89
   at Vintagestory.Common.GameDatabase.ProbeOpenConnection(String databaseFilename, Boolean corruptionProtection, Int32& foundVersion, String& errorMessage, Boolean& isReadonly, Boolean requireWrite) in VintagestoryLib\Common\FileIO\Database\GameDatabase.cs:line 139
   at Vintagestory.Server.ServerSystemLoadAndSaveGame.OnBeginConfiguration() in VintagestoryLib\Server\Systems\World\LoadThread\LoadSaveGame.cs:line 72
25.1.2024 02:30:13 [Notification] Server stop requested, begin shutdown sequence. Stop reason: Failed opening savegame
25.1.2024 02:30:13 [Notification] Entering runphase Shutdown
25.1.2024 02:30:13 [Event] Shutting down 4 server threads... 
25.1.2024 02:30:13 [Event] Killed console thread
25.1.2024 02:30:13 [Event] All threads gracefully shut down
25.1.2024 02:30:13 [Event] Doing last tick...
25.1.2024 02:30:13 [Event] Stopped the server!
```

Client Main

```25.1.2024 02:09:47 [Notification] Client logger started.
25.1.2024 02:09:47 [Notification] Game Version: v1.19.1 (Stable)
25.1.2024 02:09:48 [Notification] Process path: E:\Vintagestory\Vintagestory.exe
25.1.2024 02:09:48 [Notification] Operating System: Windows 10.0.19045.0
25.1.2024 02:09:48 [Notification] CPU Cores: 6
25.1.2024 02:09:48 [Notification] Available RAM: 32623 MB
25.1.2024 02:09:49 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
25.1.2024 02:09:49 [Notification] Graphics Card Vendor: NVIDIA Corporation
25.1.2024 02:09:49 [Notification] Graphics Card Version: 3.3.0 NVIDIA 545.92
25.1.2024 02:09:49 [Notification] Graphics Card Renderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
25.1.2024 02:09:49 [Notification] Graphics Card ShadingLanguageVersion: 3.30 NVIDIA via Cg compiler
25.1.2024 02:09:49 [Notification] GL.MaxVertexUniformComponents: 4096
25.1.2024 02:09:49 [Notification] GL.MaxUniformBlockSize: 65536
25.1.2024 02:09:49 [Notification] Cairo Graphics Version: 1.17.3
25.1.2024 02:09:49 [Notification] C# Framework: .net 7.0.10
25.1.2024 02:09:49 [Notification] OpenAL Version: 1.1 ALSOFT 1.23.0
25.1.2024 02:09:49 [Notification] Zstd Version: 1.5.5
25.1.2024 02:09:49 [Notification] Start discovering assets
25.1.2024 02:09:49 [Notification] Found 23 base assets in category lang
25.1.2024 02:09:49 [Notification] Found 0 base assets in category patches
25.1.2024 02:09:49 [Notification] Found 24 base assets in category config
25.1.2024 02:09:49 [Notification] Found 0 base assets in category worldproperties
25.1.2024 02:09:49 [Notification] Found 48 base assets in category sounds
25.1.2024 02:09:49 [Notification] Found 100 base assets in category shapes
25.1.2024 02:09:49 [Notification] Found 72 base assets in category shaders
25.1.2024 02:09:49 [Notification] Found 16 base assets in category shaderincludes
25.1.2024 02:09:49 [Notification] Found 133 base assets in category textures
25.1.2024 02:09:49 [Notification] Found 4 base assets in category music
25.1.2024 02:09:49 [Notification] Found 0 base assets in category dialog
25.1.2024 02:09:49 [Notification] Found 420 base assets in total
25.1.2024 02:09:49 [Notification] Loading sounds
25.1.2024 02:09:49 [Notification] (Re-)loaded frame buffers
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass .
25.1.2024 02:09:49 [Notification] Sounds loaded
25.1.2024 02:09:49 [Notification] Begin loading shaders
25.1.2024 02:09:49 [Notification] Load shaders now
25.1.2024 02:09:49 [Notification] Loading shaders...
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass standard.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass particlescube.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass particlesquad.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass sky.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass nightsky.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass woittest.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass helditem.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass decals.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass final.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass gui.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass blur.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass findbright.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass godrays.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass autocamera.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass wireframe.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass entityanimated.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass luma.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass blit.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass texture2texture.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass celestialobject.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass colorgrade.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass guigear.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass ssao.
25.1.2024 02:09:49 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
25.1.2024 02:09:49 [Notification] Cached session key is valid, validating with server
25.1.2024 02:09:50 [Notification] Server validation response: Good
25.1.2024 02:09:50 [Notification] Will search the following paths for mods:
25.1.2024 02:09:50 [Notification]     E:\Vintagestory\Mods
25.1.2024 02:09:50 [Notification]     C:\Users\will0\AppData\Roaming\VintagestoryData\Mods
25.1.2024 02:12:16 [Notification] Initialized GUI Manager
25.1.2024 02:12:16 [Notification] Initialized Server Connection
25.1.2024 02:12:16 [Notification] Server args parsed
25.1.2024 02:12:16 [Notification] Server main instantiated
25.1.2024 02:12:48 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockTroughBase.init() in VSSurvivalMod\Block\BlockTrough.cs:line 56
   at Vintagestory.GameContent.BlockTroughDoubleBlock.OnLoaded(ICoreAPI api) in VSSurvivalMod\Block\BlockTroughDoubleBlock.cs:line 20
   at Vintagestory.API.Common.CollectibleObject.OnLoadedNative(ICoreAPI api) in VintagestoryApi\Common\Collectible\Collectible.cs:line 261
   at Vintagestory.Server.ServerSystemBlockSimulation.OnBeginModsAndConfigReady() in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 306
   at Vintagestory.Server.ServerMain.EnterRunPhase(EnumServerRunPhase runPhase) in VintagestoryLib\Server\ServerMain.cs:line 614
   at Vintagestory.Server.ServerMain.Launch() in VintagestoryLib\Server\ServerMain.cs:line 534
   at Vintagestory.Client.ClientProgram.ServerThreadStart() in VintagestoryLib\Client\ClientProgram.cs:line 384
25.1.2024 02:12:58 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:13:25 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:15:06 [Notification] Destroying game session, waiting up to 200ms for client threads to exit
25.1.2024 02:15:20 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:16:00 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:16:48 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:18:49 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:20:17 [Notification] Initialized GUI Manager
25.1.2024 02:20:17 [Notification] Initialized Server Connection
25.1.2024 02:20:17 [Notification] Server args parsed
25.1.2024 02:20:17 [Notification] Server main instantiated
25.1.2024 02:20:29 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:20:46 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockTroughBase.init() in VSSurvivalMod\Block\BlockTrough.cs:line 56
   at Vintagestory.GameContent.BlockTroughDoubleBlock.OnLoaded(ICoreAPI api) in VSSurvivalMod\Block\BlockTroughDoubleBlock.cs:line 20
   at Vintagestory.Server.ServerSystemBlockSimulation.OnBeginModsAndConfigReady() in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 311
   at Vintagestory.Server.ServerMain.EnterRunPhase(EnumServerRunPhase runPhase) in VintagestoryLib\Server\ServerMain.cs:line 614
   at Vintagestory.Server.ServerMain.Launch() in VintagestoryLib\Server\ServerMain.cs:line 534
   at Vintagestory.Client.ClientProgram.ServerThreadStart() in VintagestoryLib\Client\ClientProgram.cs:line 384
25.1.2024 02:20:48 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:20:54 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:20:58 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:21:00 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:21:06 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:21:13 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:21:15 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:21:24 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:21:31 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:21:36 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:22:17 [Notification] Destroying game session, waiting up to 200ms for client threads to exit
25.1.2024 02:22:26 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:22:46 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:22:52 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:22:56 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:23:18 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:23:30 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:23:37 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:23:42 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:23:46 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:23:50 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:23:55 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:24:51 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:25:31 [Notification] Initialized GUI Manager
25.1.2024 02:25:31 [Notification] Initialized Server Connection
25.1.2024 02:25:31 [Notification] Server args parsed
25.1.2024 02:25:31 [Notification] Server main instantiated
25.1.2024 02:25:31 [Notification] Server launched
25.1.2024 02:26:30 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:26:47 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:27:17 [Notification] Destroying game session, waiting up to 200ms for client threads to exit
25.1.2024 02:27:20 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:27:46 [Notification] Initialized GUI Manager
25.1.2024 02:27:46 [Notification] Initialized Server Connection
25.1.2024 02:27:46 [Notification] Server args parsed
25.1.2024 02:27:46 [Notification] Server main instantiated
25.1.2024 02:28:16 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockTroughBase.init() in VSSurvivalMod\Block\BlockTrough.cs:line 56
   at Vintagestory.GameContent.BlockTroughDoubleBlock.OnLoaded(ICoreAPI api) in VSSurvivalMod\Block\BlockTroughDoubleBlock.cs:line 20
   at Vintagestory.Server.ServerSystemBlockSimulation.OnBeginModsAndConfigReady() in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 311
   at Vintagestory.Server.ServerMain.EnterRunPhase(EnumServerRunPhase runPhase) in VintagestoryLib\Server\ServerMain.cs:line 614
   at Vintagestory.Server.ServerMain.Launch() in VintagestoryLib\Server\ServerMain.cs:line 534
   at Vintagestory.Client.ClientProgram.ServerThreadStart() in VintagestoryLib\Client\ClientProgram.cs:line 384
25.1.2024 02:28:20 [Notification] Destroying game session, waiting up to 200ms for client threads to exit
25.1.2024 02:28:28 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:28:34 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
25.1.2024 02:30:13 [Notification] Initialized GUI Manager
25.1.2024 02:30:13 [Notification] Initialized Server Connection
25.1.2024 02:30:13 [Notification] Server args parsed
25.1.2024 02:30:13 [Notification] Server main instantiated
25.1.2024 02:30:13 [Notification] Server launched
25.1.2024 02:30:14 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
```

**Comment by CuroSalus** [comment]
Encountered on 1.19.3 server on Linux.

`
28.1.2024 02:28:54 [Server Fatal] Unable to open or create savegame.
28.1.2024 02:28:54 [Server Error] Exception: Data/Saves
    at Vintagestory.API.Common.SQLiteDBConnection.HaveWriteAccessFolder(String folderPath) in VintagestoryApi\Common\IO\SQLiteDBConnection.cs:line 167
    at Vintagestory.API.Common.SQLiteDBConnection.OpenOrCreate(String filename, String& errorMessage, Boolean requireWriteAccess, Boolean corruptionProtection, Boolean doIntegrityCheck) in VintagestoryApi\Common\IO\SQLiteDBConnection.cs:line 30
    at Vintagestory.Common.Database.SQLiteDbConnectionv2.Vintagestory.Common.Database.IGameDbConnection.OpenOrCreate(String filename, String& errorMessage, Boolean requireWriteAccess, Boolean corruptionProtection, Boolean doIntegrityCheck)
    at Vintagestory.Common.GameDatabase.OpenConnection(String databaseFilename, Int32 databaseVersion, String& errorMessage, Boolean requireWriteAccess, Boolean corruptionProtection, Boolean doIntegrityCheck) in VintagestoryLib\Common\FileIO\Database\GameDatabase.cs:line 89
    at Vintagestory.Common.GameDatabase.ProbeOpenConnection(String databaseFilename, Boolean corruptionProtection, Int32& foundVersion, String& errorMessage, Boolean& isReadonly, Boolean requireWrite) in VintagestoryLib\Common\FileIO\Database\GameDatabase.cs:line 127
    at Vintagestory.Server.ServerSystemLoadAndSaveGame.OnBeginConfiguration() in VintagestoryLib\Server\Systems\World\LoadThread\LoadSaveGame.cs:line 72
 28.1.2024 02:28:54 [Server Notification] Server stop requested, begin shutdown sequence. Stop reason: Failed opening savegame
`

**Comment by WilliamSivlar** [comment]
I've tried reinstalling the game, installing to other drives, running without mods, and running as an admin. Same issue persists and it's happening on 1.19.2 and .3 as well.

**Comment by WilliamSivlar** [comment]
I've found a fix. When there are outdated mods on the system, whether they are in the mods folder or not, VS sees that and removes write access. Not sure why this is a thing, but the fix is to go through, find out which mods are outdated, and test each of them to see which one(s) cause the issue. After the culprit is found, simply wipe it from your PC. Problem solved.
