### ISSUE TITLE
Multiple crashes when dying to drifter in temporal storm

### ISSUE THREAD

**Issue by MikeHollisJr2021** [anegostudios/VintageStory-Issues#3512]
### Game Version

1.19.2

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

Back to back crashes to drifters when dying in a storm

### How to reproduce

honestly I don't know, I just died, try dying? 

### Logs

```Running on 64 bit Windows 10.0.22621.0 with 28652 MB RAM
Game Version: v1.19.2 (Stable)
1/25/2024 4:57:39 PM: Critical error occurred
Loaded Mods: game@1.19.2, creative@1.19.2, survival@1.19.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemBow.OnHeldInteractCancel(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, EnumItemUseCancelReason cancelReason) in VSSurvivalMod\Item\ItemBow.cs:line 128
   at Vintagestory.Common.PlayerInventoryNetworkUtil.UpdateFromPacket(IWorldAccessor world, Packet_InventoryUpdate packet) in VintagestoryLib\Common\GameContent\Inventory\InventoryNetworkUtil.cs:line 33
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleInventoryUpdate(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 366
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 769
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Wigglestick** [comment]
Same crash for me, both times being attacked once by wolf once by bear, both from behind.

Running on 64 bit Windows 10.0.19045.0 with 32675 MB RAM
Game Version: v1.19.2 (Stable)
1/25/2024 5:20:19 PM: Critical error occurred
Loaded Mods: game@1.19.2, creative@1.19.2, survival@1.19.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemBow.OnHeldInteractCancel(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, EnumItemUseCancelReason cancelReason) in VSSurvivalMod\Item\ItemBow.cs:line 128
   at Vintagestory.Common.PlayerInventoryNetworkUtil.UpdateFromPacket(IWorldAccessor world, Packet_InventoryUpdate packet) in VintagestoryLib\Common\GameContent\Inventory\InventoryNetworkUtil.cs:line 33
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleInventoryUpdate(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 366
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 769
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by MikeHollisJr2021** [comment]
I should add, that with mine anyway, it was the death blow that crashed

**Comment by Th3Dilli** [comment]
thank you will be fixed in next version
