### ISSUE TITLE
Error on multiple computers when trying to connect to my local hosted server

### ISSUE THREAD

**Issue by Deszeraeth** [anegostudios/VintageStory-Issues#3525]
Running on 64 bit Windows 10.0.23619.0 with 32628 MB RAM
Game Version: v1.19.3 (Stable)
1/27/2024 3:58:33 PM: Critical error occurred
Loaded Mods: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Vintagestory.GameContent.BlockClutterBookshelf.RandomType(String variant) in VSSurvivalMod\Lore\ResoArchives\BlockClutterBookshelf.cs:line 277
   at Vintagestory.GameContent.BlockClutterBookshelf.GetTypeProps(String code, ItemStack stack, BEBehaviorShapeFromAttributes be) in VSSurvivalMod\Lore\ResoArchives\BlockClutterBookshelf.cs:line 170
   at Vintagestory.GameContent.BlockShapeFromAttributes.GetLightHsv(IBlockAccessor blockAccessor, BlockPos pos, ItemStack stack) in VSSurvivalMod\Block\BlockShapeFromAttributes.cs:line 576
   at Vintagestory.API.Common.Block.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 2208
   at Vintagestory.GameContent.BlockShapeFromAttributes.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VSSurvivalMod\Block\BlockShapeFromAttributes.cs:line 644
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 400
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(ICoreClientAPI capi, ItemStack stack) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 40
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onCreatePagesAsync() in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 84
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 411
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 120
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by Craluminum2413** [comment]
What mods are installed?

**Comment by Craluminum2413** [comment]
Closing due to inactivity
