### ISSUE TITLE
Server without rain

### ISSUE THREAD

**Issue by jonnypotseed** [anegostudios/VintageStory-Issues#3527]
### Game Version

1.18 - 1.19.1

### Platform

None

### Modded

None

### SP/MP

None

### Description

The server Glitchendor doesn't seem to have any rain in it's 25 (in game) years. I'm unsure if it may be related to the world gen being set to 2 million, Similar to our previous grass growth issue.  

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Is it still an issue?

**Comment by a-cim** [comment]
Hi @Craluminum2413! Confirming that we're still having this issue. Let me know if you need more information, but the short-version is that we're not experiencing precipitation across the map, including rain and snow.

When 1.18 first released we had a similar and possibly-related issue with our grass blocks not ticking properly. This was resolved in [this thread](https://github.com/anegostudios/VintageStory-Issues/issues/2705#issuecomment-1640046872), with the primary culprit being an int overflow due to the size of our map (2 mil x 2 mil blocks.)  Not sure if the precipitation is caused by something similar, but hopefully that's helpful insight.

Let me know if there's anything else we can provide to help, and thanks in advance for your help.

**Comment by jonnypotseed** [comment]
Hi, This is still an ongoing issue with our public server. Any help would be greatly appreciated.

**Comment by a-cim** [comment]
Hi @Craluminum2413 - we have more updates on this issue for you and your team, though we think the error log at the end may be the most useful piece of information. Please let us know if we can provide anything else.

## Filling in the Gaps

### Platform
PC

### Modded
Vanilla with Th3Essentials mod and some non-default map settings

### SP/MP
Multiplayer

### How to Reproduce
There weren't any specific conditions that caused this issue, but here are some non-default server settings that may have played into this issue:
- Map size is set to 2 million x 2 million blocks
- Map world height is larger than default at 320

We do think this issue started around the release of 1.19 but we can't confirm when our server updated to 1.19 since our host auto-updates and doesn't keep logs of when these updates occurred.


## Testing Server Commands

Here, we tested some of the effects of weather commands on the server:
- Testing with weather patterns (such as  `/weather setir cumulonimbusr`) does not result in rain.
- `/weather setprecip .7` causes rainfall; `/weather setprecip auto` does not seem to work as intended.
- Confirmed `/weather acp` has been on/true
- Testing with weather events (such as `/weather setevr heavythunder`) does not result in rain or clouds changing, though the thunder sounds can be heard.

## Server-worldgen.txt

Here is an error from the server-worlgen.txt log that lines up with the time we started experiencing this issue (around the release of 1.19.) This looks suspiciously relevant.
```
14.12.2023 01:47:33 [Worldgen] An error was thrown in pass TerrainFeatures when generating chunk column X=62494,Z=599 in world 'Glitchendor' with seed -1537621634
Exception System.NullReferenceException: Object reference not set to an instance of an object.
at Vintagestory.ServerMods.BlockSchematicStructure.PlaceRespectingBlockLayers(IBlockAccessor blockAccessor, IWorldAccessor worldForCollectibleResolve, BlockPos startPos, Int32 climateUpLeft, Int32 climateUpRight, Int32 climateBotLeft, Int32 climateBotRight, Dictionary`2 replaceBlocks, Int32[] replaceblockids, Boolean replaceMetaBlocks, Boolean replaceBlockEntities, Boolean suppressSoilIfAirBelow) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\Datastructures\BlockSchematicStructure.cs:line 99
at Vintagestory.ServerMods.WorldGenVillage.TryGenerate(IBlockAccessor blockAccessor, IWorldAccessor worldForCollectibleResolve, BlockPos pos, Int32 climateUpLeft, Int32 climateUpRight, Int32 climateBotLeft, Int32 climateBotRight, DidGenerate didGenerateStructure) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\6.GenStructures\WorldGenVillage.cs:line 174
at Vintagestory.ServerMods.GenStructures.DoGenVillages(IMapRegion region, Int32 chunkX, Int32 chunkZ, Boolean postPass, ITreeAttribute chunkGenParams)
at Vintagestory.Server.ServerSystemSupplyChunks.runGenerators(ChunkColumnLoadRequest chunkRequest, Int32 forPass) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 148
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity

**Comment by brickbuckett** [comment]
I believe I have encountered this issue. It started happening after I changed precipitation values to "test" something. Even though I changed it to precip auto, and acp to auto, it has never rained, stormed, snowed.. really anything ever since. It's been an in-game year and still nothing.

**Comment by Craluminum2413** [comment]
@brickbuckett It should be fixed in 1.20

**Comment by brickbuckett** [comment]
@Craluminum2413 Thank you for the swift response. Is there anything I can do for my server to get it working normally again? I've tried forcing weather patterns, and toggling back to auto. Same with precip in the hopes that toggling something "on and off" again would fix it lol.

**Comment by Craluminum2413** [comment]
@brickbuckett No idea, to be honest

**Comment by jonnypotseed** [comment]
> @Craluminum2413 Thank you for the swift response. Is there anything I can do for my server to get it working normally again? I've tried forcing weather patterns, and toggling back to auto. Same with precip in the hopes that toggling something "on and off" again would fix it lol.

We have not found a fix for the issue on the Glitchendor server. We are wiping for the 1.20 update and the weather does work on the new server. I'm leaning towards the idea that the world size may have something to do with the issue. Our server is set at 2 mil X 2 mil.
