### ISSUE TITLE
Crash on join to server.

### ISSUE THREAD

**Issue by Aionith** [anegostudios/VintageStory-Issues#3529]
### Game Version

v1.19.3

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Game crashes to desktop while joing the server, server console indicates that player was placed in the game world, but imidiately crashes. Set of mods listed in the error log didn't reproduce CTD in new singleplayer world.

### How to reproduce

Crash on joining the server.

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32693 MB RAM
Game Version: v1.19.3 (Stable)
28.01.2024 10:12:15: Critical error occurred
Loaded Mods: chiseltools@1.10.1, claycasting@1.1.4, hqzlights@1.1.1, primitivesurvival@3.4.5, sortablestorage@2.2.1, game@1.19.3, alchemy@1.6.23, ancienttools@1.5.12, butchering@1.4.3, carryon@1.7.4, commonlib@2.3.2, fromgoldencombs@1.4.25, sailboat@1.2.6, medievalexpansion@3.13.1, morepiles@1.5.0, playerlist@1.7.2, rivers@1.3.0, th3dungeon@0.2.1-rc.1, vinconomy@0.2.1, creative@1.19.3, survival@1.19.3, em@2.5.0, playercorpse@1.9.0, stonequarry@3.2.1, tpnet@1.14.2, bricklayers@2.5.0-pre.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityItemRenderer.LoadModelMatrix(ItemRenderInfo renderInfo, Boolean isShadowPass, Single dt) in VSEssentials\EntityRenderer\EntityItemRenderer.cs:line 280
   at Vintagestory.GameContent.EntityItemRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityItemRenderer.cs:line 150
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderFrameShadows(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 177
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 199
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 799
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 862
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 723
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 28.01.2024 10:09:21, Site = , Source = Application Error, Message = Nazwa aplikacji powodującej błąd: Vintagestory.exe, wersja: 1.19.3.0, sygnatura czasowa: 0x65310000
Nazwa modułu powodującego błąd: openal32.dll, wersja: 1.23.0.0, sygnatura czasowa: 0x63dd31ad
Kod wyjątku: 0x40000015
Przesunięcie błędu: 0x00000000000df046
Identyfikator procesu powodującego błąd: 0xf7c
Godzina uruchomienia aplikacji powodującej błąd: 0x01da51c95f8aa9e0
Ścieżka aplikacji powodującej błąd: E:\Vintagestory\Vintagestory.exe
Ścieżka modułu powodującego błąd: E:\Vintagestory\Lib\openal32.dll
Identyfikator raportu: bbf09698-99a9-496d-bf34-1c9647fbdd6b
Pełna nazwa pakietu powodującego błąd: 
Identyfikator aplikacji względem pakietu powodującego błąd:  }
--------------
{ TimeGenerated = 28.01.2024 09:11:21, Site = , Source = Application Error, Message = Nazwa aplikacji powodującej błąd: Vintagestory.exe, wersja: 1.19.3.0, sygnatura czasowa: 0x65310000
Nazwa modułu powodującego błąd: openal32.dll, wersja: 1.23.0.0, sygnatura czasowa: 0x63dd31ad
Kod wyjątku: 0x40000015
Przesunięcie błędu: 0x00000000000df046
Identyfikator procesu powodującego błąd: 0x2720
Godzina uruchomienia aplikacji powodującej błąd: 0x01da51c1827fa087
Ścieżka aplikacji powodującej błąd: E:\Vintagestory\Vintagestory.exe
Ścieżka modułu powodującego błąd: E:\Vintagestory\Lib\openal32.dll
Identyfikator raportu: dd31b9f1-c9ea-464d-b451-d268ae4ddbcb
Pełna nazwa pakietu powodującego błąd: 
Identyfikator aplikacji względem pakietu powodującego błąd:  }
--------------
{ TimeGenerated = 28.01.2024 09:05:59, Site = , Source = Application Error, Message = Nazwa aplikacji powodującej błąd: Vintagestory.exe, wersja: 1.19.3.0, sygnatura czasowa: 0x65310000
Nazwa modułu powodującego błąd: openal32.dll, wersja: 1.23.0.0, sygnatura czasowa: 0x63dd31ad
Kod wyjątku: 0x40000015
Przesunięcie błędu: 0x00000000000df046
Identyfikator procesu powodującego błąd: 0x31f0
Godzina uruchomienia aplikacji powodującej błąd: 0x01da51c00d1fba05
Ścieżka aplikacji powodującej błąd: E:\Vintagestory\Vintagestory.exe
Ścieżka modułu powodującego błąd: E:\Vintagestory\Lib\openal32.dll
Identyfikator raportu: cc0c054c-7b8c-45d8-bdd3-f00949a15dc3
Pełna nazwa pakietu powodującego błąd: 
Identyfikator aplikacji względem pakietu powodującego błąd:  }

**Comment by Craluminum2413** [comment]
Does it happen without mods?

**Comment by Aionith** [comment]
Doesn't matter, because mods are required by server. If you turn off mods on server, the map will immediately get filled with question marks. On version 1.19.1, i was able to play on server without any crashes.

**Comment by thebongmaster** [comment]
its happening with or without mods :x logs are mentioning openal32.dll within the games folder. is this the issue?

**Comment by thebongmaster** [comment]
> Does it happen without mods?

yes it happens without mods too. game worked fine b4 latest update

**Comment by vasyl-purchel** [comment]
Same issue here:
```
Game Version: v1.19.3 (Stable)
2/02/2024 5:31:55 PM: Critical error occurred
Loaded Mods: angelbelt@1.5.0, bedrespawner@1.0.0, betterruins@0.3.0, carpet@1.0.2, chiseltools@1.10.1, decor@1.0.13, millwright@1.1.3, primitivesurvival@3.4.5, qptech@1.14.2, roas@1.0.0, temporal_gears_stack@1.0.0, game@1.19.3, abcsreborn@0.1.5, egocaribautomapmarkers@3.1.0, betterfirepit@1.1.3, carryon@1.7.2, commonlib@2.3.2, cuniculture@1.0.2, decoclock@0.9.3, jopainting@1.4.0, sailboat@1.2.6, medievalexpansion@3.13.1, moreplaster@1.0.1, nbcartographer@2.0.9, playerlist@1.7.2, qpquests@1.0.0-pre.1, rivers@1.2.0, stonebakeoven@1.1.2, storagecontroller@1.0.6, th3expansion@1.2.0, usefulstuff17@1.3.0, vanvar@3.3.0, creative@1.19.3, survival@1.19.3, workbenchexpansion@1.8.0, em@2.5.0-pre.1, gespileslib@1.1.1, helvehammerext@1.6.0, onebedsleeping@2.3.0, playercorpse@1.9.0, bricklayers@2.5.0-pre.2, gespilesgran@1.0.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityItemRenderer.LoadModelMatrix(ItemRenderInfo renderInfo, Boolean isShadowPass, Single dt) in VSEssentials\EntityRenderer\EntityItemRenderer.cs:line 280
   at Vintagestory.GameContent.EntityItemRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityItemRenderer.cs:line 150
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderOpaque3D(Single deltaTime) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 93
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 199
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 799
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 894
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 723
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

Previously connection was working, on 1.19.3 it keeps crashing. No client side mods, everything is downloaded from the server. Other players can connect to the server.

Server logs show:
```
1.2.2024 22:31:37 [Notification] Client uid *** attempting identification. Name: L1d
1.2.2024 22:31:38 [Notification] Delayed join, need to load one spawn chunk first.
1.2.2024 22:31:38 [Notification] Sending server identification with remap False.  Server control privilege is False
1.2.2024 22:31:38 [Notification] Placing player at 509358.0848352539 110 521072.8724042969
1.2.2024 22:31:54 [Event] L1d *** joins.
1.2.2024 22:31:54 [Notification] A client reconnected, resuming game calendar.
1.2.2024 22:31:57 [Notification] Last player disconnected, compacting large object heap...
1.2.2024 22:31:59 [Event] Player L1d got removed. Reason: The Players client crashed
```

Any ideas how can we debug what item is causing this?

**Comment by Craluminum2413** [comment]
@Aionith @vasyl-purchel do you have zoom mod?

**Comment by vasyl-purchel** [comment]
Hi, no, originally zoom mod did cause renderer crashes and it was removed. Game was reinstalled from scratch and zoom mod is not on the server so wasn't downloaded.

**Comment by vasyl-purchel** [comment]
Ok, we managed to fix the issue for the user, we tried to do a binary search on the mods removing them, restarting server, cleaning server mods folder, then we started adding them back trying to get to a crash again but it never happened... so we're not sure what mod was causing it or any other aspect, but now we're back to full list of mods and player can join the server.
