### ISSUE TITLE
the game crashen when i try to run it

### ISSUE THREAD

**Issue by ziiiiiiggs** [anegostudios/VintageStory-Issues#3530]
### Game Version

v1.19.2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

the game crashes when i try to load it

### Logs

```Log```Running on 64 bit Windows 6.1.7601.0 with 3984 MB RAM
Game Version: v1.19.2 (Stable) by OverF1X
2024.01.28 16:20:37: Critical error occurred
Loaded Mods:
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: OpenGL profile requested but WGL_ARB_create_context_profile is unavailable
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings) in VintagestoryLib\Client\ClientPlatform\GameWindowNative.cs:line 14
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 280
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 2024.01.28 16:20:40, Site = , Source = Application Error, Message = Corrupt Application Name: Vintagestory.exe, Version: 1.19.2.0, Timestamp: 0x65310000
Damaged module name: KERNELBASE.dll, version: 6.1.7601.24545, timestamp 0x5e0eb6bd
Exception code: 0xe0434352
Corrupt offset: 0x000000000000b87d
Corrupt process identifier: 0x1060
Corrupt application launch time: 0x01da51f52183922d
Corrupt application path: C:\Users\children\AppData\Local\Temp\Rar$EXa5244.8235\Vintage.Story.v1.19.2.Stable\Vintagestory.exe
Corrupt module path: C:\Windows\system32\KERNELBASE.dll
Report ID: 694bf298-bde8-11ee-b58b-3cd92b77fe43 }

**Comment by thebongmaster** [comment]
Hi, try running the full installer and not the updater. it seemed to fix it for me. if its the same issue i was having

**Comment by ziiiiiiggs** [comment]
how do i do that
