### ISSUE TITLE
Fruit tree crashes

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#3531]
### Game Version

1.19.3

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Server crashed

### Logs

28.1.2024 20:08:09 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.Server.ServerWorldMap.GetClimateAt(BlockPos pos, ClimateCondition baseClimate, EnumGetClimateMode mode, Double totalDays) in VintagestoryLib\Server\ServerWorldMap.cs:line 616
   at Vintagestory.GameContent.FruitTreeRootBH.onRootTick(Single dt) in VSSurvivalMod\Systems\FruitTree\FruitTreeRootBH.cs:line 292
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Server\ServerEventManager.cs:line 123
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 886

**Comment by WickedSchnitzel** [comment]
2.2.2024 09:50:40 [Server Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.Server.ServerWorldMap.GetClimateAt(BlockPos pos, ClimateCondition baseClimate, EnumGetClimateMode mode, Double totalDays) in VintagestoryLib\Server\ServerWorldMap.cs:line 616
   at Vintagestory.GameContent.FruitTreeRootBH.onRootTick(Single dt) in VSSurvivalMod\Systems\FruitTree\FruitTreeRootBH.cs:line 292
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Server\ServerEventManager.cs:line 123
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 886
Game Version: v1.19.3 (Stable)
02/02/2024 09:50:44: Critical error occurred
Loaded Mods: 
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at System.Exception.get_StackTrace()
   at Vintagestory.API.Common.LoggerBase.Fatal(Exception e) in VintagestoryApi\Common\API\ILogger.cs:line 258
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 886
   at Vintagestory.Server.ServerProgram.Main() in VintagestoryLib\Server\ServerProgram.cs:line 139
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Crash written to file at "./data/Logs/server-crash.txt"

**Comment by Craluminum2413** [comment]
@WickedSchnitzel if there is mod that adds fruit trees, I mark it as 3rd party issue

**Comment by WickedSchnitzel** [comment]
Vanilla had this issue in the past i believe. That's why i am not sure if its a vanilla or mod issue.

**Comment by WickedSchnitzel** [comment]
May have nothing to do with it, but the server crashed with the fruit tree error again, then my client crashed with

Running on 64 bit Windows 10.0.19045.0 with 32723 MB RAM
Game Version: v1.19.3 (Stable)
11.02.2024 21:38:00: Critical error occurred
Loaded Mods: weaponpacka@1.3.1, bettercrates@1.7.0, Ceramos@0.4.3, chiseltools@1.10.2, cobbgm@1.0.1, emotemenu@1.0.4, extrachests@1.8.0, fixedpaths@1.0.1, flourbags@1.0.2, giantgouramis@1.0.2, ClaimsRadar@1.1.0, millwright@1.1.4, moreicons_cs@1.1.0, peacockbasses@1.1.2, primitivesurvival@3.4.5, spyglass@0.5.0, Swordz@1.1.4, thecritterpack@0.8.6, translocatorengineeringredux@1.4.9, truesunfishes@1.1.2, game@1.19.3, alphaweaponpackfix@1.0.0, ancienttools@1.5.12, barbershop@0.4.0, beehivekiln@1.5.1, betterfirepit@1.1.4, betterjonasdevices@1.1.0, betterruins@0.3.3, carryon@1.7.4, commonlib@2.3.2, fairplayguardian@1.1.7, furniturelibrary@1.0.11, herbarium@1.0.5, sailboat@1.2.7, meteoricexpansion@1.2.5, morepiles@1.5.0, moreplaster@1.0.1, petai@2.2.3, rivers@2.4.0, simplestep@1.1.6, steadycam@1.2.0, stonebakeoven@1.1.3, tentbag@1.1.0, th3dungeon@0.2.1-rc.1, usefulstuff17@1.3.1, vinconomy@0.2.2, creative@1.19.3, vsinstruments@1.2.7, vsquest@1.2.0, survival@1.19.3, workbenchexpansion@1.8.0, xlib119@0.7.4-dev.119, awearablelight@1.1.1, cob2@1.5.7, cobserver@1.0.0, em@2.5.0, outerspacetunesmaster@1.0.0, outerspacetunesvolume1@1.0.0, outerspacetunesvolume2@1.0.0, playercorpse@1.9.0, rifteye@0.3.4, simplewinddirection@1.0.2, stonequarry@3.2.1, wildcraftfruit@1.0.1, wolftaming@2.1.0, xskills119@0.7.5-dev.1191, bricklayers@2.5.0, cob@1.6.7, vsvillagecob@0.1.9
System.Exception: soundconfig.json not loaded. Is it missing or are you trying to load sounds before the client has received the level finalize event?
   at Vintagestory.Client.NoObf.ClientMain.ResolveSoundPath(AssetLocation location) in VintagestoryLib\Client\Systems\Audio\SoundEngine.cs:line 24
   at Vintagestory.Client.NoObf.ClientMain.PlaySoundAtInternal(AssetLocation location, Double x, Double y, Double z, Single volume, Single pitch, Single range, EnumSoundType soundType) in VintagestoryLib\Client\Systems\Audio\SoundEngine.cs:line 154
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleSound(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 201
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 769
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 07.02.2024 08:36:54, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.3.0, Zeitstempel: 0x65310000
Name des fehlerhaften Moduls: coreclr.dll, Version: 7.0.1323.51816, Zeitstempel: 0x6530618b
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00000000001c87cc
ID des fehlerhaften Prozesses: 0x738
Startzeit der fehlerhaften Anwendung: 0x01da59985c08f211
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.13\coreclr.dll
Berichtskennung: 2fc4d2b5-8fc3-44a6-9c46-86b76f3fcc71
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 07.02.2024 00:48:00, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.3.0, Zeitstempel: 0x65310000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x1fc
Startzeit der fehlerhaften Anwendung: 0x01da5956d97af068
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 948642cb-20f6-49e2-b799-f4e93d5432b6
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 02.02.2024 15:29:25, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.3.0, Zeitstempel: 0x65310000
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.3930, Zeitstempel: 0x9141f979
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000002cf19
ID des fehlerhaften Prozesses: 0x5eac
Startzeit der fehlerhaften Anwendung: 0x01da55dd0f4635b8
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: a8db6754-6ea7-4e2b-a8a1-e06d9b764067
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }

**Comment by Craluminum2413** [comment]
Closing due to inactivity, if it happens again, I will reopen it
