### ISSUE TITLE
System.NullReferenceException crashing server regularly

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#3535]
### Game Version

1.19.3

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Logs

Game Version: v1.19.3 (Stable)
1/29/2024 4:53:06 AM: Critical error occurred
Loaded Mods: weaponpacka@1.3.1, bettercrates@1.7.0, Ceramos@0.4.3, chiseltools@1.10.1, extrachests@1.8.0, fantasycreatures@0.6.2, fixedpaths@1.0.1, flourbags@1.0.2, giantgouramis@1.0.2, millwright@1.1.4, moreicons_cs@1.1.0, peacockbasses@1.1.2, primitivesurvival@3.4.5, spyglass@0.5.0, Swordz@1.1.4, translocatorengineeringredux@1.4.9, truesunfishes@1.1.2, game@1.19.3, alphaweaponpackfix@1.0.0, ancienttools@1.5.12, barbershop@0.4.0, beehivekiln@1.5.1, betterjonasdevices@1.1.0, betterruins@0.3.1, carryon@1.7.4, commonlib@2.3.2, fairplayguardian@1.1.5, furniturelibrary@1.0.11, herbarium@1.0.4, icecold@0.5.1, sailboat@1.2.6, meteoricexpansion@1.2.5, morepiles@1.5.0, moreplaster@1.0.1, petai@2.2.3, rivers@1.2.0, simplestep@1.1.2, steadycam@1.2.0, stonebakeoven@1.1.3, tentbag@1.0.2, th3dungeon@0.2.1-rc.1, vinconomy@0.2.1, creative@1.19.3, vsinstruments@1.2.4, vsquest@1.2.0, survival@1.19.3, workbenchexpansion@1.8.0, xmelee@0.0.12, cob2@1.5.5, em@2.5.0, outerspacetunesmaster@1.0.0, outerspacetunesvolume1@1.0.0, outerspacetunesvolume2@1.0.0, playercorpse@1.9.0, rifteye@0.3.4, simplewinddirection@1.0.2, stonequarry@3.2.1, wildcraftfruit@1.0.1, wolftaming@2.0.2, bricklayers@2.5.0-pre.2, cob@1.5.7, vsvillagecob@0.1.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\Entity.cs:line 965
   at Vintagestory.API.Common.EntityItem.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityItem.cs:line 149
   at Vintagestory.Client.NoObf.ClientSystemEntities.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Entities.cs:line 95
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 82
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 831
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 723
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Th3Dilli** [comment]
how often is it regularly?

most likely it is caused by a mod since we run topts and have not encountered such issues yet

but if there is a specific region you can narrow that down and test that it is a vanilla bug (no mods) and provide the savegame with that area we should be able to fix it

or I can join and check out the location on the server

also is there any log on the server since you just provided the client log?
