### ISSUE TITLE
Client crash while inspecting a block in Survival Handbook

### ISSUE THREAD

**Issue by mag8n** [anegostudios/VintageStory-Issues#3560]
### Game Version

v1.19.3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

The client will crash if a certain block is hovered over in the handbook -- see how to reproduce and screenshot.

### How to reproduce

1. open the handbook
2. open any of the pages of "Stony rubble"
3. hover the cursor over the block listed under "Drops when broken"

### Screenshots

![2024-02-05_10-44-23](https://github.com/anegostudios/VintageStory-Issues/assets/158755487/1d192d73-6f83-458a-9a9b-fd80a4e873e3)

### Logs

```
Running on 64 bit Windows 6.1.7601.0 with 8191 MB RAM
Game Version: v1.19.3 (Stable)
05/02/2024 10:41:12: Critical error occurred
Loaded Mods: game@1.19.3, creative@1.19.3, survival@1.19.3
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockRockTyped.getRockType(String type) in VSSurvivalMod\Block\BlockRockTyped.cs:line 123
   at Vintagestory.GameContent.BlockRockTyped.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VSSurvivalMod\Block\BlockRockTyped.cs:line 106
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 401
   at Vintagestory.API.Client.ItemstackComponentBase.OnRequireInfoText(ItemSlot slot) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\ItemstackComponentBase.cs:line 62
   at Vintagestory.API.Client.SlideshowItemstackTextComponent.OnRequireInfoText(ItemSlot slot) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\SlideshowItemstackTextComponent.cs:line 178
   at Vintagestory.API.Client.GuiElementItemstackInfo.AsyncRecompose() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 142
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot, Boolean forceRecompose) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 252
   at Vintagestory.API.Client.ItemstackComponentBase.RenderItemstackTooltip(ItemSlot slot, Double renderX, Double renderY, Single dt) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\ItemstackComponentBase.cs:line 67
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 472
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 716
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 384
   at Vintagestory.GameContent.GuiDialogHandbook.OnRenderGUI(Single deltaTime) in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 493
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 318
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1006
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Th3Dilli** [comment]
thank you this will be fixed in the next release
