### ISSUE TITLE
Crash on trying to place bushmeat in firepit

### ISSUE THREAD

**Issue by brummbar7** [anegostudios/VintageStory-Issues#357]
I was able to reproduce this.  It's a firepit that is already somewhat hot (from making torches).  I try to place in bushmeat and it crashes.

Running on 64 bit Windows with 8 GB RAM 
Version: v1.12.0-pre.1 (Unstable)12/29/2019 12:58:33 PM: Critical error occurred
Newtonsoft.Json.JsonSerializationException: Error converting value "Cooking" to type 'Vintagestory.GameContent.EnumFirepitModel'. Path 'useFirepitModel', line 20, position 30. ---> System.ArgumentException: Requested value 'Cooking' was not found.
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Vintagestory.GameContent.BlockEntityFirepit.GetRenderProps(ItemStack contentStack)
   at Vintagestory.GameContent.BlockEntityFirepit.UpdateRenderer()
   at Vintagestory.GameContent.BlockEntityFirepit.OnSlotModifid(Int32 slotid)
   at Vintagestory.API.Common.Action`1.Invoke(T t1)
   at Vintagestory.API.Common.InventoryBase.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack)
   at Vintagestory.GameContent.InventorySmelting.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack)
   at Vintagestory.API.Common.ItemSlot.OnItemSlotModified(ItemStack sinkStack)
   at Vintagestory.API.Common.InventoryBase.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse)
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs)
   at Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args)
   at _CN91mCMlpQpCaBZLmsPbOScXZ4T._YzUXIvz6WOMZoI1bA4tv7DDUvdI(MouseEvent )
   at _RUhAMTwoeTm3UIzPvbmExVNxwZS._YzUXIvz6WOMZoI1bA4tv7DDUvdI(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _HNwbMcYiXQRrlyWmBPhh5e6PJng._5CuF6gy2KqJWuYcud2uoqVrKwVf(_buT4CNDAMIeemONEo45dWwDVMql , String[] )
   at _Jp6BgTKiHL83WuxLAU16RGRCzK5._5CuF6gy2KqJWuYcud2uoqVrKwVf(ThreadStart )
-------------------------------
System.ArgumentException: Requested value 'Cooking' was not found.
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 11/23/2019 10:42:43 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 000007FEFD2EBE0D
Stack:
   at System.Environment._Exit(Int32)
   at System.Environment._Exit(Int32)
   at System.Environment.Exit(Int32)
   at _VldAfBcjwmRvkrBZ0d2PMcNnh3T._YMA6WIYEaEfkbPVGtUgmK2MEzQ3()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(Vintagestory.API.Client.MouseEvent)
   at _tgRwJBaebfUFsjKAmpD5hPIQC4GA._KdLz83Czctyg4wqUBN73HB3AG3o(Vintagestory.API.Client.MouseEvent)
   at _93p1ko0VOT3s5orIQ8NaBwI5pPD._Lym1bgz5Lo6FmXkn3dmk5WQoaMC(System.Object, OpenTK.Input.MouseButtonEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double, Double)
   at _dlonPAHkYdoAFiGslNynsGbaDFq._8elR8MmcoDgjMIe2sgpAwab9Dnp(_BULmFtV7lvG1053qIyIBTMCX7RJ, System.String[])
   at _lQgBjjHoFrDHvmqhGD1SL0CDl4UA._8elR8MmcoDgjMIe2sgpAwab9Dnp(System.Threading.ThreadStart)
   at _dlonPAHkYdoAFiGslNynsGbaDFq._UNnU8de8Zoh1UV85gepl0DUf7ci(System.String[])
 }
{ TimeGenerated = 8/1/2018 8:47:35 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at OpenTK.NativeWindow.EnsureUndisposed()
   at OpenTK.GameWindow.Exit()
   at _DLldCwzmWxAc7YkftgyEl6oNBYAA._U6uRO7W7uIkj4O0YIefCOchvnbO(System.Exception)
   at _DLldCwzmWxAc7YkftgyEl6oNBYAA._WwcLROIGCSsEdcyWiCRVwgDfGLe(System.Threading.ThreadStart)
   at _PkglWYgXxKoeSWDNiPQDOtOzd8A._b2tO4qIHlm0Bno88k5FFEXcFADDA(System.String[])

 }

**Comment by tyronx** [comment]
thanks, fixed for pre.2
