### ISSUE TITLE
Dictionary Key not found, crashes on world generation

### ISSUE THREAD

**Issue by theishiopian** [anegostudios/VintageStory-Issues#358]
Version: 1.12.0 pre-1
Windows 10
Not modded

Description: game crashes on making a new world. Seems to not be able to find a key in a dictionary somewhere. Superficially similar to #339 

### How to reproduce
1. create a new world

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.12.0-pre.1 (Unstable)12/29/2019 1:47:40 PM: Critical error occurred
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Vintagestory.Client.NoObf.ShaderProgramBase.Uniform(String uniformName, Single value)
   at Vintagestory.GameContent.EntityShapeRenderer.DoRender3DOpaqueBatched(Single dt, Boolean isShadowPass)
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderFrameShadows(Single dt)
   at _EixPUZCf7tmgFNOoqkVbmIGbTRJ._NMOUhp8gvqMahlcbgMF4dw08fUF(EnumRenderStage , Single )
   at _RUhAMTwoeTm3UIzPvbmExVNxwZS._NMOUhp8gvqMahlcbgMF4dw08fUF(EnumRenderStage , Single )
   at _RUhAMTwoeTm3UIzPvbmExVNxwZS._3H9m2IPEldi2cvW0MAG44SnUHEf(Single )
   at _RUhAMTwoeTm3UIzPvbmExVNxwZS._MKvcQnL7gewtI1qbnjSdWSawdakA(Single )
   at _Igoc97ckqVljnCA2Dx2mnVWbVip._FIp9VQUZNHZG3Jb4CXrRGgBI31D(Single )
   at _5XjjhI61BtBodarbI94fAmLa126._8eCXolML3ezZJSsPYlapUuOoJTc(Single )
   at _5XjjhI61BtBodarbI94fAmLa126._zHlndzfzFZQHIMZKNhCw3HgyJ9(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _HNwbMcYiXQRrlyWmBPhh5e6PJng._5CuF6gy2KqJWuYcud2uoqVrKwVf(_buT4CNDAMIeemONEo45dWwDVMql , String[] )
   at _Jp6BgTKiHL83WuxLAU16RGRCzK5._5CuF6gy2KqJWuYcud2uoqVrKwVf(ThreadStart )
-------------------------------
```

**Comment by tyronx** [comment]
disable dynamic shadows until pre.2
