### ISSUE TITLE
Unable to start the world made in 1.19.3

### ISSUE THREAD

**Issue by Shionsan** [anegostudios/VintageStory-Issues#3583]
### Game Version

1.19.4-rc.1

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Unable to start the world after an update.

Logs mention spear. I have one set on the tool rack.

### Logs

```14.2.2024 04:43:26 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemSpear.OnLoaded(ICoreAPI api) in VSSurvivalMod\Item\ItemSpear.cs:line 19
   at Vintagestory.API.Common.CollectibleObject.OnLoadedNative(ICoreAPI api) in VintagestoryApi\Common\Collectible\Collectible.cs:line 261
   at Vintagestory.Server.ServerSystemBlockSimulation.<OnBeginModsAndConfigReady>b__13_0(Item item) in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 311
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Vintagestory.Server.ServerSystemBlockSimulation.OnBeginModsAndConfigReady() in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 312
   at Vintagestory.Server.ServerMain.EnterRunPhase(EnumServerRunPhase runPhase) in VintagestoryLib\Server\ServerMain.cs:line 614
   at Vintagestory.Server.ServerMain.Launch() in VintagestoryLib\Server\ServerMain.cs:line 534
   at Vintagestory.Client.ClientProgram.ServerThreadStart() in VintagestoryLib\Client\ClientProgram.cs:line 390```

**Comment by Craluminum2413** [comment]
@Shionsan Any mods? I suspect this is a mod problem

**Comment by Shionsan** [comment]
Yes. Any tips or pointers on which one I should look?

A Tad More Light.zip
AncientTools_V1.5.12.zip
animationmanagerlib_0.6.0.zip
APanserbjornStory-v0.9.2-1.19.zip
Auto Map Markers (1.19).zip
Autorotor1.1.2.zip
AWearableLight-v1.1.1.zip
BackpackPackPLUS_v1.0.3.zip
BeltCraft.zip
BetterBackpacksForAWearableLight-1.0.4.zip
BetterFirepit-1.1.4.zip
betterjonasdevices_1.1.0.zip
BetterMoisture.zip
betteroutline_1.3.0.zip
BetterRuinsv0.3.3.zip
BetterTradersv0.0.5.zip
BlackSmithEnhancements-v1.0.4.zip
blockoverlay-3.2.1.zip
BloomeryFullDrops.zip
brutalstory_1.0.0.zip
Bullseye_2.5.3.zip
Burn for Longer.zip
CarryOn-1.19_v1.7.4.zip
cats_v2.0.1_petai_v2.0.+.zip
cob_seraphvoices_1.0.0.zip
CommonLib_VS1.19.4-rc.1_net7_v2.3.4.zip
Composter-v1.1.0.zip
configlib_0.4.5.zip
Conquest Landform Overhaul v0.0.2.zip
Crateful_1.2.8.zip
crudearrowupgrade_V1_0_0.zip
Cuniculture_v1.0.2.zip
DanaTweaks-v1.2.0.zip
decorbazaar_v1.0.13.zip
dhyp_1.0.2.zip
Electricity.zip
ExtraInfo-v1.7.0.zip
fantasycreatures_0.7.1.zip
FixedPaths.zip
FotSA-Caninae-v1.0.10.zip
free_stone_drops_when_broken v1.0.1.zip
fsmlib_0.2.9.zip
hangingoillamps_1.0.1.zip
HealthierTreesv1.0.0.zip
Immersive Corpse Drop (1.19).zip
immersivewoodchopping_0.7.1.zip
immersivewoodsawing_0.1.1.zip
InstantFirepits_v5.0.0.zip
josailing-1.2.8.zip
Knapster_v2.7.0.zip
kusabimaru.zip
maltiezbows_1.0.1.zip
Mannequin-Stand-v1.0.3.zip
mcd1.zip
MetalSupports_v1.19.3_v1.0.3.zip
MeteoricExpansion_V1.2.5.zip
millwright_1.1.4.zip
MobsRadar-v2.0.0.zip
MoreAnimals-1.3.3.zip
naturalpatches_v0.1.3.zip
NoCokeLost-1.0.0.zip
nohands-0.1.1.zip
NoOffhandHunger_v1.0.0.zip
oneroof_0.9.9.zip
petai_v2.2.3.zip
PickUpFast.zip
pileful_1.1.5.zip
pixelwaypoints.zip
PlayerCorpse_VS1.19.0-rc.5_net7_v1.9.0.zip
Plumpkins-v1.0.1.zip
ragnamansSeedsFromCrops_v1.0.0.zip
rivers_2.5.0.zip
Roof Fix 1.18.10-v0.0.1.zip
Rust Creatures 1.3.0.zip
scarecrow_v1.4.3.zip
ScytheMore-v1.0.1.zip
simplefootsteps_1.1.6.zip
SmithableTorchHolders_1_0_0.zip
statushudcont_2.1.1.zip
stickemup_1.1.0.zip
StoneQuarry_VS1.19.0-rc.5_net7_v3.2.1.zip
temporal_gears_stack v1.zip
th3dungeon_0.2.1-rc.1.zip
th3restock_1.1.2.zip
translocatorengineeringredux_1.4.9.zip
tstools_v2.0.1.zip
undergroundmines_1.0.3.zip
Unpack Dirt.zip
vsimgui_0.3.5.zip
wildfarmingrevival_1.1.7.zip
zoombuttonreborn_1.6.0.zip

**Comment by Craluminum2413** [comment]
@Shionsan Does it happen without any mods installed?

**Comment by Shionsan** [comment]
Seems to be some mod, since without them - the game start.
Disabling all mods marked as "problematic" in the list didn't help.
I suppose I'll have to check them one by one, which is a major pain in the @$$ every damn time.

**Comment by Craluminum2413** [comment]
@Shionsan Remove mods this way https://en.wikipedia.org/wiki/Binary_search_algorithm

**Comment by Craluminum2413** [comment]
Okay then I close this issue
