### ISSUE TITLE
Fruit Press causing clients to crash

### ISSUE THREAD

**Issue by Darrkstarr** [anegostudios/VintageStory-Issues#3590]
### Game Version

1.9.3 Stable

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Clients are crashing when they get close to the Fruit Press

### How to reproduce

1. any client moving close to the Fruit Press will crash

### Logs

Running on 64 bit Windows 10.0.19045.0 with 16305 MB RAM
Game Version: v1.19.3 (Stable)
2024-02-15 6:07:52 PM: Critical error occurred
Loaded Mods: decor@1.0.13, flourbags@1.0.2, gildedsteel@1.0.1, thecritterpack@0.8.4, game@1.19.3, betterruins@0.3.2, blacksmithenhancements@1.0.4, butchering@1.4.4, carryon@1.7.4, commonlib@2.3.2, fromgoldencombs@1.4.25, sailboat@1.2.7, loreweapons@1.0.1, medievalexpansion@3.13.1, moreanimals@1.3.3, petai@2.2.3, scarecrow@1.4.3, sharablewaypoints@1.5.3, simplecloth@1.0.2, storageoptions@1.0.2, usefulstuff17@1.3.1, creative@1.19.3, survival@1.19.3, wildfarmingrevival@1.1.7, awearablelight@1.1.1, em@2.5.0, feverstonehorses@1.6.0, playercorpse@1.9.0, slanted_display_cases@1.1.0, tailorsdelight@1.2.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityFruitPress.GetBlockInfo(IPlayer forPlayer, StringBuilder dsc) in VSSurvivalMod\BlockEntity\BEFruitpress.cs:line 670
   at Vintagestory.API.Common.Block.GetPlacedBlockInfo_Patch1(Block this, IWorldAccessor world, BlockPos pos, IPlayer forPlayer)
   at Vintagestory.GameContent.BlockFruitPress.GetPlacedBlockInfo(IWorldAccessor world, BlockPos pos, IPlayer forPlayer) in VSSurvivalMod\Block\BlockFruitPress.cs:line 157
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.ComposeBlockInfoHud() in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 111
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 724
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by radfast** [comment]
Likely either a mod issue or the fruit press somehow had a wrong item placed in its bucket space.

Next version 1.19.4 will fix this specific client crash, but this fruit press may still then fail in other ways if there is something wrong with it; please also check logs when 1.19.4 comes.
