### ISSUE TITLE
Dragging & dropping a schematic while game being paused caused a crash

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#3609]
### Game Version

1.19.3

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I dragged and dropped a schematic to the game screen while the game was paused and it crashed

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32723 MB RAM
Game Version: v1.19.3 (Stable)
19.02.2024 02:52:29: Critical error occurred
Loaded Mods: fantasycreatures@0.7.1, ClaimsRadar@1.1.0, game@1.19.3, simplestep@1.1.6, creative@1.19.3, vsquest@1.2.0, survival@1.19.3, cob2@1.5.7, cobserver@1.0.0, outerspacetunesmaster@1.0.0, outerspacetunesvolume1@1.0.0, outerspacetunesvolume2@1.0.0, softcaveins@1.0.0, cob@1.6.9
System.Exception: Call to RegisterCallback while game is paused. ExtendedDebug info and developermode is enabled, so will crash on this for reporting reasons.
   at Vintagestory.Client.NoObf.ClientMain.RegisterCallback(Action`1 OnTimePassed, Int32 millisecondDelay) in VintagestoryLib\Client\ClientMain.cs:line 3106
   at Vintagestory.Client.NoObf.ClientEventAPI.RegisterCallback(Action`1 OnTimePassed, Int32 millisecondDelay) in VintagestoryLib\Client\API\ClientEventAPI.cs:line 526
   at Vintagestory.ServerMods.WorldEdit.WorldEditClientHandler.Event_FileDrop(FileDropEvent ev) in VSCreativeMod\WorldEditClientHandler.cs:line 301
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerFileDrop(String filename) in VintagestoryLib\Client\API\ClientEventAPI.cs:line 281
   at Vintagestory.Client.NoObf.ClientMain.OnFileDrop(String filename) in VintagestoryLib\Client\ClientMain.cs:line 2103
   at Vintagestory.Client.GuiScreenRunningGame.OnFileDrop(String filename) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 361
   at Vintagestory.Client.ScreenManager.onFileDrop(String filename) in VintagestoryLib\Client\ScreenManager.cs:line 1134
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Window_FileDrop(FileDropEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 446
   at OpenTK.Windowing.Desktop.NativeWindow.OnFileDrop(FileDropEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.DropCallback(Window* window, Int32 count, Byte** paths)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 13.02.2024 21:34:56, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.3.0, Zeitstempel: 0x65310000
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.3930, Zeitstempel: 0x9141f979
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000002cf19
ID des fehlerhaften Prozesses: 0x20d0
Startzeit der fehlerhaften Anwendung: 0x01da5eba1d78efc0
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: f0cb987c-a4d0-4b97-9645-3f49e807b787
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 13.02.2024 07:16:09, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.3.0, Zeitstempel: 0x65310000
Name des fehlerhaften Moduls: coreclr.dll, Version: 7.0.1323.51816, Zeitstempel: 0x6530618b
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00000000001c87cc
ID des fehlerhaften Prozesses: 0x5894
Startzeit der fehlerhaften Anwendung: 0x01da5e424d911bbc
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.13\coreclr.dll
Berichtskennung: ebe1863e-8ed8-457e-a416-1431b2ec2531
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 07.02.2024 08:36:54, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.3.0, Zeitstempel: 0x65310000
Name des fehlerhaften Moduls: coreclr.dll, Version: 7.0.1323.51816, Zeitstempel: 0x6530618b
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00000000001c87cc
ID des fehlerhaften Prozesses: 0x738
Startzeit der fehlerhaften Anwendung: 0x01da59985c08f211
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.13\coreclr.dll
Berichtskennung: 2fc4d2b5-8fc3-44a6-9c46-86b76f3fcc71
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }

**Comment by radfast** [comment]
Thanks for reporting.  Fixed in 1.19.4 upcoming.
