### ISSUE TITLE
Crash when removing ingots from the forge

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#3611]
### Game Version

1.19.3

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Tried to ignite a forge with ingots in it using a torch, but instead was removing the ingots from the forge via right click, then it crashed. flat creative world, it was raining and the flame went out before. build a roof of soil blocks, before i tried to ignite again.

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32723 MB RAM
Game Version: v1.19.3 (Stable)
19.02.2024 14:14:25: Critical error occurred
Loaded Mods: fantasycreatures@0.7.1, ClaimsRadar@1.1.0, game@1.19.3, petai@2.2.3, simplestep@1.1.6, creative@1.19.3, vsquest@1.2.0, survival@1.19.3, cob2@1.5.9, cobserver@1.0.0, outerspacetunesmaster@1.0.0, outerspacetunesvolume1@1.0.0, outerspacetunesvolume2@1.0.0, softcaveins@1.0.0, cob@1.6.9
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\Entity.cs:line 867
   at Vintagestory.API.Common.EntityItem.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityItem.cs:line 149
   at Vintagestory.Client.NoObf.ClientSystemEntities.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Entities.cs:line 99
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 724
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 13.02.2024 21:34:56, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.3.0, Zeitstempel: 0x65310000
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.3930, Zeitstempel: 0x9141f979
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000002cf19
ID des fehlerhaften Prozesses: 0x20d0
Startzeit der fehlerhaften Anwendung: 0x01da5eba1d78efc0
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: f0cb987c-a4d0-4b97-9645-3f49e807b787
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 13.02.2024 07:16:09, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.3.0, Zeitstempel: 0x65310000
Name des fehlerhaften Moduls: coreclr.dll, Version: 7.0.1323.51816, Zeitstempel: 0x6530618b
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00000000001c87cc
ID des fehlerhaften Prozesses: 0x5894
Startzeit der fehlerhaften Anwendung: 0x01da5e424d911bbc
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.13\coreclr.dll
Berichtskennung: ebe1863e-8ed8-457e-a416-1431b2ec2531
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 07.02.2024 08:36:54, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.3.0, Zeitstempel: 0x65310000
Name des fehlerhaften Moduls: coreclr.dll, Version: 7.0.1323.51816, Zeitstempel: 0x6530618b
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00000000001c87cc
ID des fehlerhaften Prozesses: 0x738
Startzeit der fehlerhaften Anwendung: 0x01da59985c08f211
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.13\coreclr.dll
Berichtskennung: 2fc4d2b5-8fc3-44a6-9c46-86b76f3fcc71
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }

**Comment by radfast** [comment]
I believe this issue is already fixed in 1.19.4-rc.1 and rc.2.
It is not specific to the forge or ingots, the reason appears to be either a race condition in multi-threaded code, or a mod.

Feel free to re-open if it happens in 1.19.4+, with a new stacktrace please (the line numbers will have changed)
