### ISSUE TITLE
[1.19.3] Player triggers a server error - locust nest

### ISSUE THREAD

**Issue by Prinzip** [anegostudios/VintageStory-Issues#3617]
### Game Version

v1.19.3

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Today player got kicked all time if he try's to destroy a locust nest with hands or tools. No Client Log failure, Server Log is attached.

### Logs

Feb 21 22:59:20 vs VintageStory[154117]: 21.2.2024 22:59:20 [Server Event] Spieler Leviation wurde entfernt. Grund: Threw an exception at the server
Feb 21 22:59:20 vs VintageStory[154117]: 21.2.2024 22:59:20 [Server Error] Exception: Index was outside the bounds of the array.
Feb 21 22:59:20 vs VintageStory[154117]:    at Vintagestory.GameContent.BlockEntityLocustNest.OnReceivedClientPacket(IPlayer fromPlayer, Int32 packetid, Byte[] bytes) in VSSurvivalMod\BlockEntity\BELocustNest.cs:line 78
Feb 21 22:59:20 vs VintageStory[154117]:    at Vintagestory.Server.ServerSystemBlockSimulation.HandleBlockEntityPacket(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 341
Feb 21 22:59:20 vs VintageStory[154117]:    at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\ServerMainNetworking.cs:line 138

**Comment by Greemole** [comment]
Just had this same issue with my friend on a server as well. 

Only the server-audit in the logs said this:
1.9.2024 01:38:03 [Audit] Client JaneDoe got removed: 'Threw an exception at the server' (An action you (or your client) did caused an unhandled exception)
