### ISSUE TITLE
Book backspace while writing crash

### ISSUE THREAD

**Issue by BananaProblem** [anegostudios/VintageStory-Issues#3618]
### Game Version

v1.19.3 (Stable)

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

While using a book I had a issue when getting to the end of a page you keep typing and it will get stuck typing on both pages and when you try to remove the letters on the second page it will crash immediately

### How to reproduce

Write until you fill a book page, keep typing but don't change the page, back space, switch to the second page, backspace, Crash
Note: a single backspace will delete an entire word when this is happening and I believe it will also take one letter typed on the second page(I hope I submitted this properly)

### Screenshots

![2024-02-22_17-24-07](https://github.com/anegostudios/VintageStory-Issues/assets/160827429/b99221f6-0eae-4240-870d-ff7cf29ea3f9)
![2024-02-22_17-24-11](https://github.com/anegostudios/VintageStory-Issues/assets/160827429/c39d223a-747d-4c1d-bb78-a22b6c0bc677)
![2024-02-22_17-24-17](https://github.com/anegostudios/VintageStory-Issues/assets/160827429/01adfdac-bc55-4c04-abb7-cdd1c6af016d)

### Logs

Running on 64 bit Windows 10.0.19045.0 with 8075 MB RAM
Game Version: v1.19.3 (Stable)
22/02/2024 5:24:21 PM: Critical error occurred
Loaded Mods: chiseltools@1.10.1, game@1.19.3, commonlib@2.3.2, farmlanddropssoil@1.4.0, th3dungeon@0.2.0, creative@1.19.3, survival@1.19.3, playercorpse@1.9.0, stonequarry@3.2.1
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Vintagestory.GameContent.GuiDialogEditableBook.onTryTextChange(List`1 lines) in VSSurvivalMod\Systems\WritingSystem\GuiDialogEditableBook.cs:line 78
   at Vintagestory.API.Client.GuiElementEditableTextBase.LoadValue(List`1 newLines) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 292
   at Vintagestory.API.Client.GuiElementEditableTextBase.SetValue(String text, Boolean setCaretPosToEnd) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 264
   at Vintagestory.GameContent.GuiDialogReadonlyBook.updatePage(Boolean setCaretPosToEnd) in VSSurvivalMod\Systems\WritingSystem\GuiDialogReadonlyBook.cs:line 176
   at Vintagestory.GameContent.GuiDialogEditableBook.onTextChanged(String text) in VSSurvivalMod\Systems\WritingSystem\GuiDialogEditableBook.cs:line 124
   at Vintagestory.API.Client.GuiElementEditableTextBase.TextChanged() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 329
   at Vintagestory.API.Client.GuiElementTextArea.TextChanged() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementTextArea.cs:line 31
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyBackSpace() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 562
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyDown(ICoreClientAPI api, KeyEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 423
   at Vintagestory.API.Client.GuiComposer.OnKeyDown(KeyEvent args, Boolean haveFocus) in VintagestoryApi\Client\UI\GuiComposer.cs:line 581
   at Vintagestory.API.Client.GuiDialog.OnKeyDown(KeyEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 440
   at Vintagestory.GameContent.GuiDialogReadonlyBook.OnKeyDown(KeyEvent args) in VSSurvivalMod\Systems\WritingSystem\GuiDialogReadonlyBook.cs:line 194
   at Vintagestory.GameContent.GuiDialogEditableBook.OnKeyDown(KeyEvent args) in VSSurvivalMod\Systems\WritingSystem\GuiDialogEditableBook.cs:line 266
   at Vintagestory.Client.NoObf.GuiManager.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 360
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1735
   at Vintagestory.Client.GuiScreenRunningGame.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 310
   at Vintagestory.Client.ScreenManager.OnKeyDown(KeyEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 848
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 247
   at OpenTK.Windowing.Desktop.NativeWindow.OnKeyDown(KeyboardKeyEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.KeyCallback(Window* window, Keys key, Int32 scancode, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 31/01/2024 11:00:01 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x31e4
Faulting application start time: 0x01da53dc66d3a1ec
Faulting application path: E:\Vintagestory\Vintagestory.exe
Faulting module path: E:\Vintagestory\Lib\openal32.dll
Report Id: b63325ee-e2eb-49b0-a5bb-ceaa972a8828
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Duplicate of #2740
