### ISSUE TITLE
Crash when moving stacks of hematite

### ISSUE THREAD

**Issue by Emspara** [anegostudios/VintageStory-Issues#362]
**Game Version:** 1.11.11
**Platform:** Windows 8.1
**Modded:** Yes. Vanilla mods for Darkagecraft Vanilla Multiplayer

### Description
Keep crashing client when moving stacks of 128 hematite ore. Has no problem for many series of moving them until just recently. Now I grab a stack from inventory bar and it crashes.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.11.11 (Stable)1/30/2020 4:58:14 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockMeal.GetContentNutritionFacts(IWorldAccessor world, ItemSlot inSlotorFirstSlot, ItemStack[] contentStacks, EntityAgent forEntity, Boolean mulWithStacksize)
   at Vintagestory.GameContent.BlockCookedContainer.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug)
   at Vintagestory.API.Client.GuiElementItemstackInfo.Recompose()
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot)
   at Vintagestory.Client.NoObf.HudMouseTools.OnMouseEnterSlot(ItemSlot slot)
   at _VDsWgzK30VQbGsNO9IbfdQ0yn0l._sR1SnTD3kdgIN7AFHblDCkki1Hr(_NG0ZnXmTtmPezIn9LSDyNwn1qcA , ItemSlot )
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseMove(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseMove(MouseEvent mouse)
   at Vintagestory.API.Client.GuiDialog.OnMouseMove(MouseEvent args)
   at _DbLXOrSSss3n9bUIQMlb1ZMI2CJ._AdGvwJeqjwmXyBanw7KqModEJgg(MouseEvent )
   at _NG0ZnXmTtmPezIn9LSDyNwn1qcA._AdGvwJeqjwmXyBanw7KqModEJgg(MouseEvent )
   at _k603ozcgxEWfTany0f4BuFkKaTO._tDgS1gbY9aAUQqKolwFspPjuCVj()
   at _k603ozcgxEWfTany0f4BuFkKaTO._cofRcWkjdUpiHnZj5DznYMVdHcb(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _KhnygRKbChlhNVZ6NoTIj4AppFv._CZt1ULfHsOfvWyybAWFzfZAPlmN(_v0QfrgDod6R3FrQXNUcbGgdKeRI , String[] )
   at _Vfez4jOq8l9qPflsxomPO9fBnuB._CZt1ULfHsOfvWyybAWFzfZAPlmN(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 1/30/2020 4:51:28 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.GameContent.BlockMeal.GetContentNutritionFacts(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot, Vintagestory.API.Common.ItemStack[], Vintagestory.API.Common.EntityAgent, Boolean)
   at Vintagestory.GameContent.BlockCookedContainer.GetHeldItemInfo(Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor, Boolean)
   at Vintagestory.API.Common.ItemStack.GetDescription(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot, Boolean)
   at Vintagestory.API.Client.GuiElementItemstackInfo.Recompose()
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(Vintagestory.API.Common.ItemSlot)
   at Vintagestory.Client.NoObf.HudMouseTools.OnMouseEnterSlot(Vintagestory.API.Common.ItemSlot)
   at _VDsWgzK30VQbGsNO9IbfdQ0yn0l._sR1SnTD3kdgIN7AFHblDCkki1Hr(_NG0ZnXmTtmPezIn9LSDyNwn1qcA, Vintagestory.API.Common.ItemSlot)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseMove(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiComposer.OnMouseMove(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiDialog.OnMouseMove(Vintagestory.API.Client.MouseEvent)
   at _DbLXOrSSss3n9bUIQMlb1ZMI2CJ._AdGvwJeqjwmXyBanw7KqModEJgg(Vintagestory.API.Client.MouseEvent)
   at _NG0ZnXmTtmPezIn9LSDyNwn1qcA._AdGvwJeqjwmXyBanw7KqModEJgg(Vintagestory.API.Client.MouseEvent)
   at _k603ozcgxEWfTany0f4BuFkKaTO._tDgS1gbY9aAUQqKolwFspPjuCVj()
   at _k603ozcgxEWfTany0f4BuFkKaTO._cofRcWkjdUpiHnZj5DznYMVdHcb(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _KhnygRKbChlhNVZ6NoTIj4AppFv._CZt1ULfHsOfvWyybAWFzfZAPlmN(_v0QfrgDod6R3FrQXNUcbGgdKeRI, System.String[])
   at _Vfez4jOq8l9qPflsxomPO9fBnuB._CZt1ULfHsOfvWyybAWFzfZAPlmN(System.Threading.ThreadStart)

 }
{ TimeGenerated = 1/30/2020 4:49:59 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.GameContent.BlockMeal.GetContentNutritionFacts(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot, Vintagestory.API.Common.ItemStack[], Vintagestory.API.Common.EntityAgent, Boolean)
   at Vintagestory.GameContent.BlockCookedContainer.GetHeldItemInfo(Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor, Boolean)
   at Vintagestory.API.Common.ItemStack.GetDescription(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot, Boolean)
   at Vintagestory.API.Client.GuiElementItemstackInfo.Recompose()
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(Vintagestory.API.Common.ItemSlot)
   at Vintagestory.Client.NoObf.HudMouseTools.OnMouseEnterSlot(Vintagestory.API.Common.ItemSlot)
   at _VDsWgzK30VQbGsNO9IbfdQ0yn0l._sR1SnTD3kdgIN7AFHblDCkki1Hr(_NG0ZnXmTtmPezIn9LSDyNwn1qcA, Vintagestory.API.Common.ItemSlot)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseMove(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiComposer.OnMouseMove(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiDialog.OnMouseMove(Vintagestory.API.Client.MouseEvent)
   at _DbLXOrSSss3n9bUIQMlb1ZMI2CJ._AdGvwJeqjwmXyBanw7KqModEJgg(Vintagestory.API.Client.MouseEvent)
   at _NG0ZnXmTtmPezIn9LSDyNwn1qcA._AdGvwJeqjwmXyBanw7KqModEJgg(Vintagestory.API.Client.MouseEvent)
   at _k603ozcgxEWfTany0f4BuFkKaTO._tDgS1gbY9aAUQqKolwFspPjuCVj()
   at _k603ozcgxEWfTany0f4BuFkKaTO._cofRcWkjdUpiHnZj5DznYMVdHcb(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _KhnygRKbChlhNVZ6NoTIj4AppFv._CZt1ULfHsOfvWyybAWFzfZAPlmN(_v0QfrgDod6R3FrQXNUcbGgdKeRI, System.String[])
   at _Vfez4jOq8l9qPflsxomPO9fBnuB._CZt1ULfHsOfvWyybAWFzfZAPlmN(System.Threading.ThreadStart)

 }
{ TimeGenerated = 1/30/2020 4:49:04 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.GameContent.BlockMeal.GetContentNutritionFacts(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot, Vintagestory.API.Common.ItemStack[], Vintagestory.API.Common.EntityAgent, Boolean)
   at Vintagestory.GameContent.BlockCookedContainer.GetHeldItemInfo(Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor, Boolean)
   at Vintagestory.API.Common.ItemStack.GetDescription(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot, Boolean)
   at Vintagestory.API.Client.GuiElementItemstackInfo.Recompose()
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(Vintagestory.API.Common.ItemSlot)
   at Vintagestory.Client.NoObf.HudMouseTools.OnMouseEnterSlot(Vintagestory.API.Common.ItemSlot)
   at _VDsWgzK30VQbGsNO9IbfdQ0yn0l._sR1SnTD3kdgIN7AFHblDCkki1Hr(_NG0ZnXmTtmPezIn9LSDyNwn1qcA, Vintagestory.API.Common.ItemSlot)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseMove(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiComposer.OnMouseMove(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiDialog.OnMouseMove(Vintagestory.API.Client.MouseEvent)
   at _DbLXOrSSss3n9bUIQMlb1ZMI2CJ._AdGvwJeqjwmXyBanw7KqModEJgg(Vintagestory.API.Client.MouseEvent)
   at _NG0ZnXmTtmPezIn9LSDyNwn1qcA._AdGvwJeqjwmXyBanw7KqModEJgg(Vintagestory.API.Client.MouseEvent)
   at _k603ozcgxEWfTany0f4BuFkKaTO._tDgS1gbY9aAUQqKolwFspPjuCVj()
   at _k603ozcgxEWfTany0f4BuFkKaTO._cofRcWkjdUpiHnZj5DznYMVdHcb(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _KhnygRKbChlhNVZ6NoTIj4AppFv._CZt1ULfHsOfvWyybAWFzfZAPlmN(_v0QfrgDod6R3FrQXNUcbGgdKeRI, System.String[])
   at _Vfez4jOq8l9qPflsxomPO9fBnuB._CZt1ULfHsOfvWyybAWFzfZAPlmN(System.Threading.ThreadStart)

 }

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```

**Comment by tyronx** [comment]
Thanks for the report, please let me know if version 1.12 still crashes

**Comment by tyronx** [comment]
Assuming to be fixed
