### ISSUE TITLE
Mod(s) crash game client side but not friends when joining my dedicated server

### ISSUE THREAD

**Issue by EldestHedge** [anegostudios/VintageStory-Issues#3646]
### Game Version

v1.19.3

### Platform

Linux

### Modded

Modded

### SP/MP

Multiplayer

### Description

I have a dedicated Vintage Story server with mods that I hosted through Hetzner running Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-94-generic x86_64). I followed the wiki instructions on how to set up the server. I run Artix Linux x86_64 kernal 6.7.6 zen; whenever I connect to the modded server my game crashes and gives the error log provided below. This critical error does not happen to my friends who use windows 10 & 11 to play vintage story. This crash does not happen when feverstonehorses@1.6.0 and petai@2.2.3 mods are removed.

### How to reproduce

1. Add petai@2.2.3 and feverstonehorses@1.6.0 mod to server mod directory
2. Attempt to join server
3. Critical error log pops up and game client is forced to close.

### Logs

```Running on 64 bit Linux (Artix Linux) [Kernel 6.7.6.1] with 15831 MB RAM
Game Version: v1.19.3 (Stable)
2/27/2024 8:25:18PM: Critical error occurred
Loaded Mods: chiseltools@1.10.2, pipeleaf@1.4.0, sortablestorage@2.2.1, game@1.19.3, animalcages@3.0.2, egocaribautomapmarkers@3.1.0, petai@2.2.3, prospecttogether@1.3.0, rivers@2.6.0, th3dungeon@0.2.1-rc.1, creative@1.19.3, survival@1.19.3, feverstonehorses@1.6.0
System.Exception: Don't know how to instantiate collectible behavior of class 'considerpetfood' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateCollectibleBehavior(CollectibleObject collectible, String code) in VintagestoryLib\Common\ClassRegistry.cs:line 221
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType packet, IWorldAccessor world, ClassRegistry registry) in VintagestoryLib\Common\Network\ItemTypeNet.cs:line 52
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(List`1 items, Int32 listSize) in VintagestoryLib\Client\Systems\Startup.cs:line 587
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes() in VintagestoryLib\Client\Systems\Startup.cs:line 399
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in VintagestoryLib\Client\Systems\Startup.cs:line 341
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 120
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by Craluminum2413** [comment]
Caused by mod
