### ISSUE TITLE
Crash when using right click + shift action to knap or clayform on new world/server

### ISSUE THREAD

**Issue by Burgersim** [anegostudios/VintageStory-Issues#365]
**Game Version:** 1.12.2
**Platform:** Windows
**Modded:** No

### Description
I just downloaded the new release, I made a new world on my server, but everytime I try to use the right click Action to knap or clayform my client crashes. It does seem like the server doesn't crash, as far as I can tell.

### How to reproduce
1. Start Version 1.12.2
2. Use Stone, Flint or Clay to craft in the world with shift+right-clicking the ground

### Expected behavior
Crafting in world as before

### Logs
```
Version: v1.12.2 (Stable)14.02.2020 17:38:27: Critical error occurred
System.Exception: Couldn't build bounds from children, there were probably no child elements using fixed sizing! (or they were size 0)
   bei Vintagestory.API.Client.ElementBounds.buildBoundsFromChildren()
   bei Vintagestory.API.Client.ElementBounds.CalcWorldBounds()
   bei Vintagestory.API.Client.GuiElementDialogBackground.ComposeElements(Context ctx, ImageSurface surface)
   bei Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement)
   bei Vintagestory.GameContent.GuiDialogBlockEntityRecipeSelector.SetupDialog()
   bei Vintagestory.GameContent.BlockEntityClayForm.OpenDialog(IClientWorldAccessor world, BlockPos pos, ItemStack ingredient)
   bei Vintagestory.GameContent.BlockEntityClayForm.PutClay(ItemSlot slot)
   bei Vintagestory.GameContent.ItemClay.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling)
   bei _zQ9uE9IDDGqd1cUeOFbpbRVoU5z._sg10Jr2vOJ4DUBD9PAqaNKyUFnM(BlockSelection , EntitySelection , EnumHandInteract , EnumHandHandling& )
   bei _zQ9uE9IDDGqd1cUeOFbpbRVoU5z._sg10Jr2vOJ4DUBD9PAqaNKyUFnM(BlockSelection , EntitySelection )
   bei _zQ9uE9IDDGqd1cUeOFbpbRVoU5z._MMx5HlRPiqA1xL0ABkS6IEt8dLC(Single )
   bei _zQ9uE9IDDGqd1cUeOFbpbRVoU5z._m26KtboZJZr48J6zxfhK7acVgJB(Single )
   bei _Qv8cPpvHmLSgykqkPh3zluyWiKh._LUBAgTU0FTeDc1F12xLikRPnkJaA(EnumRenderStage , Single )
   bei _TMyqtwUJcw5UgZJdnH0el0rnA7D._LUBAgTU0FTeDc1F12xLikRPnkJaA(EnumRenderStage , Single )
   bei _TMyqtwUJcw5UgZJdnH0el0rnA7D._8ml974wG0KppjKMq5q3L7ydfsPG(Single )
   bei _Mx4GrhIOAjHqp4zsXwfpKbb70sf._8ml974wG0KppjKMq5q3L7ydfsPG(Single )
   bei _CDwSs4MzMPdhbDTbD3dFYQ8jZoV._rUL2GZnjsWIJqtBU7kwyxLeo0YF(Single )
   bei _CDwSs4MzMPdhbDTbD3dFYQ8jZoV._bpLLVWEaSdhgOtm3J1pE2vv7xI6(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _7RqUZTv58k6spAnfNOrk8WFLysH._KB66ADTb9Dm65uHf0ghed8BNYJrA(_kP35w2hyfaJlcf0xtvGQq1yBClJ , String[] )
   bei _VuhE4Nw0xy3BVTVJaUM7AtakAAG._KB66ADTb9Dm65uHf0ghed8BNYJrA(ThreadStart )
-------------------------------
Version: v1.12.2 (Stable)14.02.2020 21:37:06: Critical error occurred
System.Exception: Couldn't build bounds from children, there were probably no child elements using fixed sizing! (or they were size 0)
   bei Vintagestory.API.Client.ElementBounds.buildBoundsFromChildren()
   bei Vintagestory.API.Client.ElementBounds.CalcWorldBounds()
   bei Vintagestory.API.Client.GuiElementDialogBackground.ComposeElements(Context ctx, ImageSurface surface)
   bei Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement)
   bei Vintagestory.GameContent.GuiDialogBlockEntityRecipeSelector.SetupDialog()
   bei Vintagestory.GameContent.BlockEntityClayForm.OpenDialog(IClientWorldAccessor world, BlockPos pos, ItemStack ingredient)
   bei Vintagestory.GameContent.BlockEntityClayForm.PutClay(ItemSlot slot)
   bei Vintagestory.GameContent.ItemClay.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling)
   bei _zQ9uE9IDDGqd1cUeOFbpbRVoU5z._sg10Jr2vOJ4DUBD9PAqaNKyUFnM(BlockSelection , EntitySelection , EnumHandInteract , EnumHandHandling& )
   bei _zQ9uE9IDDGqd1cUeOFbpbRVoU5z._sg10Jr2vOJ4DUBD9PAqaNKyUFnM(BlockSelection , EntitySelection )
   bei _zQ9uE9IDDGqd1cUeOFbpbRVoU5z._MMx5HlRPiqA1xL0ABkS6IEt8dLC(Single )
   bei _zQ9uE9IDDGqd1cUeOFbpbRVoU5z._m26KtboZJZr48J6zxfhK7acVgJB(Single )
   bei _Qv8cPpvHmLSgykqkPh3zluyWiKh._LUBAgTU0FTeDc1F12xLikRPnkJaA(EnumRenderStage , Single )
   bei _TMyqtwUJcw5UgZJdnH0el0rnA7D._LUBAgTU0FTeDc1F12xLikRPnkJaA(EnumRenderStage , Single )
   bei _TMyqtwUJcw5UgZJdnH0el0rnA7D._8ml974wG0KppjKMq5q3L7ydfsPG(Single )
   bei _Mx4GrhIOAjHqp4zsXwfpKbb70sf._8ml974wG0KppjKMq5q3L7ydfsPG(Single )
   bei _CDwSs4MzMPdhbDTbD3dFYQ8jZoV._rUL2GZnjsWIJqtBU7kwyxLeo0YF(Single )
   bei _CDwSs4MzMPdhbDTbD3dFYQ8jZoV._bpLLVWEaSdhgOtm3J1pE2vv7xI6(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _7RqUZTv58k6spAnfNOrk8WFLysH._KB66ADTb9Dm65uHf0ghed8BNYJrA(_kP35w2hyfaJlcf0xtvGQq1yBClJ , String[] )
   bei _VuhE4Nw0xy3BVTVJaUM7AtakAAG._KB66ADTb9Dm65uHf0ghed8BNYJrA(ThreadStart )
-------------------------------
Version: v1.12.2 (Stable)15.02.2020 00:24:05: Critical error occurred
System.Exception: Couldn't build bounds from children, there were probably no child elements using fixed sizing! (or they were size 0)
   bei Vintagestory.API.Client.ElementBounds.buildBoundsFromChildren()
   bei Vintagestory.API.Client.ElementBounds.CalcWorldBounds()
   bei Vintagestory.API.Client.GuiElementDialogBackground.ComposeElements(Context ctx, ImageSurface surface)
   bei Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement)
   bei Vintagestory.GameContent.GuiDialogBlockEntityRecipeSelector.SetupDialog()
   bei Vintagestory.GameContent.BlockEntityKnappingSurface.OpenDialog(IClientWorldAccessor world, BlockPos pos, ItemStack baseMaterial)
   bei Vintagestory.GameContent.ItemFlint.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling)
   bei _zQ9uE9IDDGqd1cUeOFbpbRVoU5z._sg10Jr2vOJ4DUBD9PAqaNKyUFnM(BlockSelection , EntitySelection , EnumHandInteract , EnumHandHandling& )
   bei _zQ9uE9IDDGqd1cUeOFbpbRVoU5z._sg10Jr2vOJ4DUBD9PAqaNKyUFnM(BlockSelection , EntitySelection )
   bei _zQ9uE9IDDGqd1cUeOFbpbRVoU5z._MMx5HlRPiqA1xL0ABkS6IEt8dLC(Single )
   bei _zQ9uE9IDDGqd1cUeOFbpbRVoU5z._m26KtboZJZr48J6zxfhK7acVgJB(Single )
   bei _Qv8cPpvHmLSgykqkPh3zluyWiKh._LUBAgTU0FTeDc1F12xLikRPnkJaA(EnumRenderStage , Single )
   bei _TMyqtwUJcw5UgZJdnH0el0rnA7D._LUBAgTU0FTeDc1F12xLikRPnkJaA(EnumRenderStage , Single )
   bei _TMyqtwUJcw5UgZJdnH0el0rnA7D._8ml974wG0KppjKMq5q3L7ydfsPG(Single )
   bei _Mx4GrhIOAjHqp4zsXwfpKbb70sf._8ml974wG0KppjKMq5q3L7ydfsPG(Single )
   bei _CDwSs4MzMPdhbDTbD3dFYQ8jZoV._rUL2GZnjsWIJqtBU7kwyxLeo0YF(Single )
   bei _CDwSs4MzMPdhbDTbD3dFYQ8jZoV._bpLLVWEaSdhgOtm3J1pE2vv7xI6(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _7RqUZTv58k6spAnfNOrk8WFLysH._KB66ADTb9Dm65uHf0ghed8BNYJrA(_kP35w2hyfaJlcf0xtvGQq1yBClJ , String[] )
   bei _VuhE4Nw0xy3BVTVJaUM7AtakAAG._KB66ADTb9Dm65uHf0ghed8BNYJrA(ThreadStart )
-------------------------------
```

**Comment by tyronx** [comment]
I noticed that the recipe selector dialog crashes in this way when it has nothing to display. At least this part is now fixed.

I think what happens here is that either the server does not properly send or the client does not properly receive the recipes. But the reason for that is a mystery for me still. Is that an unmodded server?

**Comment by Burgersim** [comment]
This is unmodded

Ok so then this will be fixed in the next version? or is there a fix I could apply now, so that I can play on the Server?

**Comment by copygirl** [comment]
> or is there a fix I could apply now, so that I can play on the Server?

If Tyron's guess is correct, then something's wrong with the recipes being transmitted. Even if the crash is fixed, you wouldn't be able to select anything to craft. He would like to look into this underlying issue before releasing a fix. I wonder how many other people are affected - or if this is somehow a special case.

**Comment by tyronx** [comment]
The client-main.txt and server-main.txt might give us some insights, could you upload those please?

**Comment by Burgersim** [comment]
Sure:

This is the Client-main.txt from my client:
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/4210339/client-main.txt)

And the Sercer-main.txt from my Server:
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/4210349/server-main.txt)


Hope that helps ^^

**Comment by tyronx** [comment]
Oh yea okay, there's tons of errors happening there. 

`16.2.2020 15:25:24 [Error] Failed registering item game:honeyportion: System.Exception: Attempted to register Item with code game:honeyportion, but an item with such code already exists. Must use a unique code
   at Vintagestory.Server.ServerMain.RegisterItem(Item item)
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.LoadItems()
`

Sounds like something got jumbled up with the installation files and they doubled up or something. I recommend you uninstall the game and delete the %appdata%/VintageStory folder. Keep %appdata%/VintageStoryData though.

**Comment by Burgersim** [comment]
Gonna try that and report back, thx for the quick help ^^

**Comment by Burgersim** [comment]
Well still crashing unfortunately, I uninstalled Vitage Story, deleted the folder, but I still get the crash when I try to knap flint for example, I guess I'm gonna attach the new Client Logs here, hope that's ok:

[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/4210459/client-crash.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/4210460/client-main.txt)
[client-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/4210461/client-chat.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/4210462/client-debug.txt)
[server-event.txt](https://github.com/anegostudios/VintageStory-Issues/files/4210463/server-event.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/4210464/server-main.txt)
[server-storyevent.txt](https://github.com/anegostudios/VintageStory-Issues/files/4210465/server-storyevent.txt)
[server-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/4210466/server-debug.txt)

**Comment by tyronx** [comment]
That server is modded though.

```
14.2.2020 21:40:02 [Error] Multiple mods share the mod ID 'theneolithicmod' ('VS-1.10.15-The-Neolithic-Mod-2.1.0.zip', 'VS-1.9.6-TheNeolithicMod-1.7.2.zip'). Will only load the first one.
14.2.2020 21:40:02 [Notification] Mods, sorted by dependency: graveyard, game, instrumentsmod, sortingmod, waypointutils, carrycapacity, earthworks, creative, survival, desertflora, lakeflowers, theneolithicmod, totems
14.2.2020 21:40:14 [Notification] Instantiated 77 mod systems from 13 enabled mods
14.2.2020 21:40:14 [Notification] External Origins in load order: custom@C:\Users\salze\AppData\Roaming\Vintagestory\assets\creative\, custom@C:\Users\salze\AppData\Roaming\Vintagestory\assets\survival\, mod@Graveyard-1.1.3.zip, mod@1.9.6-InstrumentsMod-1.0.1.zip, mod@CarryCapacity-0.4.4.zip, mod@Earthworks-1.0.1.zip, mod@Desertflora101.zip, mod@lakeflowers.zip, mod@VS-1.10.15-The-Neolithic-Mod-2.1.0.zip, mod@VS-1.9.6-Totems-1.1.5.zip
```

**Comment by Burgersim** [comment]
I'm sorry for the confusion, the server files here are not from my server, all files uploaded are from my client (from the folder on my PC), and the server, therefore, is not the one I am playing on. I don't use mods on the Server and the first server-main.txt I uploaded should show that.

**Comment by copygirl** [comment]
There's also this exception from the first `server-main.txt` file:
```
16.2.2020 15:25:38 [Error] Exception thrown during handling event OnSaveGameLoaded: Newtonsoft.Json.JsonSerializationException: Error converting value "##__##__##_" to type 'System.String[]'. Path 'pattern[0]'. ---> System.ArgumentException: Could not cast or convert from System.String to System.String[].
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at Vintagestory.ServerMods.RecipeLoader.LoadRecipes[T](String name, String path, Action`1 RegisterMethod)
```

**Comment by Burgersim** [comment]
But the Server is totally unmodded, I never installed any mods there, and there are no mods in the "Mods" folder on my Server
![chrome_9laIID0tCs](https://user-images.githubusercontent.com/26793150/74734872-c76e2580-524f-11ea-850d-e056894f52a3.png)

**Comment by copygirl** [comment]
You could also mod the server by modifying the assets folder directly. Or, more likely in this case, leaving some out..? Could you make sure all the asset files have been transferred properly? Not sure if that will be the issue but it's worth checking.

**Comment by Burgersim** [comment]
I didn't upload the server, I directly installed it, and one of the first things I did, because I thought there might be something wrong with the files, was to reinstall it again. So there shouldn't be any files left out

**Comment by copygirl** [comment]
I think I might have just found this issue while **updating** my own server. Be sure to remove the `assets` directory before updating the server, as otherwise there might still be old files which have been removed from newer versions of the game.

I got the same error after updating without doing this so I assume this must be what's going on.

**Comment by Burgersim** [comment]
Thank you very mch for your help, I deleted the asset folder, updated the server and now it works.
