### ISSUE TITLE
Random "soundconfig.json not loaded" crash when trying to connect to server (modded, 1.19.3 - 1.19.4)

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#3650]
### Game Version

1.19.4

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Logs
```
Running on 64 bit Windows 10.0.19045.0 with 32723 MB RAM
Game Version: v1.19.4 (Stable)
28.02.2024 23:09:40: Critical error occurred
Loaded Mods: weaponpacka@1.3.1, bettercrates@1.7.0, Ceramos@0.4.3, chiseltools@1.10.4, cobbgm@1.0.1, decor@1.0.14, extrachests@1.8.0, fantasycreatures@0.7.1, fixedpaths@1.0.1, flourbags@1.0.2, foundrymod@1.0.0, giantgouramis@1.0.2, millwright@1.1.4, moreicons_cs@1.1.0, peacockbasses@1.1.2, primitivesurvival@3.4.7, spyglass@0.5.1, Swordz@1.1.4, thecritterpack@0.8.8, translocatorengineeringredux@1.4.9, truesunfishes@1.1.2, game@1.19.4, alphaweaponpackfix@1.0.0, ancienttools@1.5.12, barbershop@0.4.0, beehivekiln@1.5.1, betterfirepit@1.1.4, betterjonasdevices@1.1.0, betterruins@0.3.3, carryon@1.7.4, commonlib@2.3.2, composter@1.1.0, fairplayguardian@1.1.7, furniturelibrary@1.0.11, herbarium@1.0.5, sailboat@1.2.8, medievalexpansion@3.13.1, meteoricexpansion@1.2.5, morepiles@1.5.0, moreplaster@1.0.1, petai@2.2.3, rivers@2.4.0, simplestep@1.1.6, steadycam@1.3.0, stonebakeoven@1.1.3, tentbag@1.1.1, th3dungeon@0.2.1-rc.1, usefulstuff17@1.3.1, vinconomy@0.2.3, creative@1.19.4, vsinstruments@1.2.7, vsquest@1.2.0, survival@1.19.4, workbenchexpansion@1.8.0, xlib119@0.7.4-dev.1191, awearablelight@1.1.1, cob2@1.6.0, em@2.5.0, linearpower@0.2.1, outerspacetunesmaster@1.0.0, outerspacetunesvolume1@1.0.0, outerspacetunesvolume2@1.0.0, playercorpse@1.9.0, rifteye@0.3.4, simplewinddirection@1.0.2, stonequarry@3.2.1, wildcraftfruit@1.0.1, wolftaming@2.1.0, xskills119@0.7.5-dev.1191, bricklayers@2.5.0, cob@1.7.5, vsvillagecob@0.1.9
System.Exception: soundconfig.json not loaded. Is it missing or are you trying to load sounds before the client has received the level finalize event?
   at Vintagestory.Client.NoObf.ClientMain.ResolveSoundPath(AssetLocation location) in VintagestoryLib\Client\Systems\Audio\SoundEngine.cs:line 26
   at Vintagestory.Client.NoObf.ClientMain.PlaySoundAtInternal(AssetLocation location, Double x, Double y, Double z, Single volume, Single pitch, Single range, EnumSoundType soundType) in VintagestoryLib\Client\Systems\Audio\SoundEngine.cs:line 152
   at Vintagestory.Client.NoObf.ClientMain.PlaySoundAt(AssetLocation location, Double posx, Double posy, Double posz, IPlayer dualCallByPlayer, EnumSoundType soundType, Single pitch, Single range, Single volume) in VintagestoryLib\Client\Systems\Audio\SoundEngine.cs:line 92
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleSound(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 190
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 446
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 440
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by radfast** [comment]
hmm, mysterious as SoundConfig.json obviously exists.  Maybe some kind of limit was reached on the number of files which can simultaneously be open, or some other similar limit of such a kind.  Do you experience the issue in vanilla or with a smaller mod list?

**Comment by Craluminum2413** [comment]
Closing due to inactivity

**Comment by WickedSchnitzel** [comment]
still happens in rc.6

Running on 64 bit Windows 10.0.19045.0 with 32723 MB RAM
Game Version: v1.20.0-rc.6 (Unstable)
25.12.2024 16:16:12: Critical error occurred
Loaded Mods: ancientarmory@1.0.6, bettercrates@1.8.0-rc.4, canoemod@1.0.2, chiseltools@1.14.4, decor@1.2.0, extrachests@1.8.0, fantasycreatures@0.7.1, fixedpaths@1.0.1, pantherinae@1.1.14, foundrymod@1.0.0, moreicons_cs@1.1.0, primitivesurvival@3.7.4, nvscaffolding@1.0.1, translocatorengineeringredux@1.5.4, game@1.20.0-rc.6, weaponpackalphaunoff@1.5.1, animalcages@3.0.3, apegrapes@1.1.3, betterruins@0.4.2, butterflycases@1.0.1, carryon@1.8.0-pre.1, commonlib@2.6.1, decayingcreatures@0.1.1, fairplayguardian@1.1.7, furniturelibrary@1.0.14, gourmand@1.2.7, heatretention@1.0.2, playerlist@2.1.5, rifteye@0.4.0, simplefootstepsredux@1.0.1, sleepvote@1.0.7, tentbag@2.2.0, th3dungeon@0.3.1, thecritterpack@0.9.1, vanity@2.2.1, vinconomy@0.4.0-rc.4, creative@1.20.0-rc.6, vsquest@1.2.0, vsserverpanel@0.1.5, survival@1.20.0-rc.6, wildgrass@1.1.3, xlibpatch@1.0.1, youvegotmail@1.0.8, cob2@1.6.9, cobserver@1.0.3, em@3.0.0-pre.3, outerspacetunesvolume1@1.0.2, outerspacetunesvolume2@1.0.2, playercorpse@1.11.0, stonequarry@3.4.2, xskillspatch@1.0.4, cob@2.0.0, outerspacetunesmaster@1.0.2
System.Exception: soundconfig.json not loaded. Is it missing or are you trying to load sounds before the client has received the level finalize event?
   at Vintagestory.Client.NoObf.ClientMain.ResolveSoundPath(AssetLocation location) in VintagestoryLib\Client\Systems\Audio\SoundEngine.cs:line 28
   at Vintagestory.Client.NoObf.ClientMain.PlaySoundAtInternal(AssetLocation location, Double x, Double y, Double z, Single volume, Single pitch, Single range, EnumSoundType soundType) in VintagestoryLib\Client\Systems\Audio\SoundEngine.cs:line 159
   at Vintagestory.Client.NoObf.ClientMain.PlaySoundAt(AssetLocation location, Double posx, Double posy, Double posz, IPlayer dualCallByPlayer, EnumSoundType soundType, Single pitch, Single range, Single volume) in VintagestoryLib\Client\Systems\Audio\SoundEngine.cs:line 94
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleSound(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 190
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 786
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 254
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10.11.2024 17:19:55, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.20.0.0, Zeitstempel: 0x66470000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x54f0
Startzeit der fehlerhaften Anwendung: 0x01db338c37998c05
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: bd0722d8-f2e3-4919-b9d2-22bd3b03b432
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 07.11.2024 21:48:24, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.20.0.0, Zeitstempel: 0x66470000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x6ab8
Startzeit der fehlerhaften Anwendung: 0x01db315643baa536
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 30893ec8-ce92-4c18-812d-9d94a10b2d19
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 07.11.2024 14:09:10, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.20.0.0, Zeitstempel: 0x66470000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x1228
Startzeit der fehlerhaften Anwendung: 0x01db311615ac4736
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: a8fe137c-4ea9-4b8c-9b6d-79a84f2bfad4
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }

**Comment by WickedSchnitzel** [comment]
This crash is still happening to a lot of people when trying to join my server btw. Still no clue how to fix this?

**Comment by Th3Dilli** [comment]
my best guess would be that a mod tries to play a sound early when a new client connects and the connecting client has not yet finished loading the games assets and so can not play the sound and then crashes

does this only happen on slower end clients or randomly on any?

**Comment by WickedSchnitzel** [comment]
Happens to many people when they are trying to connect to the server, but randomly.
No matter where they are or the machine. Going on since years.

**Comment by WickedSchnitzel** [comment]
Running on 64 bit Windows 10.0.19045.0 with 32725 MB RAM
Game Version: v1.21.1 (Stable)
30.09.2025 00:23:15: Critical error occurred
Loaded Mods: ancientarmory@1.1.6, bettercrates@1.9.0, bettertranslations@0.0.29, buzzybees@1.1.7, catchledge@0.5.8, cbr@1.0.0, chiseltools@1.15.2, craftablecompanion@1.3.0, crawlanddive@0.2.1, fantasycreatures@0.7.1, fixedpaths@1.0.1, floralzonescaperegion@1.0.23, floralzonescosmopolitanregion@1.0.5, floralzoneseastasiaticregion@1.0.13, floralzonesmediterraneanregion@1.0.14, floralzonesneozeylandicregion@1.0.14, flora@1.0.7, chelonioidea@1.0.4, foundrymod@1.0.0, mbr@1.0.0, millwright@1.2.8, moreiconscs@1.1.1, primitivesurvival@3.9.7, rustandrailroads@2.1.1, storagecontroller@1.2.1, translocatorengineeringredux@1.6.0, vintageengineering@0.4.0, game@1.21.1, vssherpaonnx@1.0.0, warmgambeson@1.0.0, animalcages@4.0.1, astriaporta@0.0.6, attributerenderinglibrary@2.1.1, awearablelight@1.1.4, betterfirepit@1.1.6, betterjonasdevicesfixed@2.0.4, betterruins@0.5.0, billposting@1.1.0, butterflycases@1.0.2, carryon@1.10.9, cartwrightscaravan@1.7.2, cobbgmpartone@1.0.1, cobbgmparttwo@1.0.1, commonlib@2.8.0, decayingcreatures@0.1.6, decorpatched@1.3.1, fairplayguardian@1.2.1, fromgoldencombs@1.9.4, furniturelibrary@1.0.18, gourmandbalance@1.1.0, gourmand@1.7.5, improvedsheepupdate@1.0.2, knapster@3.0.0, mannequinstand@1.0.7, morepiles@2.2.0, petai@4.0.0, PingMarkers@1.1.1, playerlist@2.1.5, purposefulstorage@1.4.1, realsmoke@1.1.2, rivers@4.7.3, rpgdifficulty@1.1.9, rptts@1.1.6, rpvoicechat@2.3.23, shovelimpervioustosnow@1.0.0, showcraftable@1.2.5, simplefootstepsredux@1.0.4, sleepvote@1.0.9, speedboat@1.0.0, stepupadvanced@1.2.1, stonebakeoven@1.2.0, tentbagreworked@3.1.1, th3dungeon@0.4.4, thecritterpack@1.3.3, vanity@2.4.4, vinconomy@5.0.3, vintagescarecrow@0.0.6, creative@1.21.1, vsquest@3.0.0, survival@1.21.1, vsvillage@3.0.1, weakteleporter@1.1.2, workbenchexpansionpatch@1.1.0, xblood@1.6.5, xlib@0.9.0-pre.2, cats@4.0.0, cobbgmmain@1.0.1, cob2@1.7.6, cobserver@1.0.5, em@3.3.1, hydraulics@1.1.0, outerspacetunesvolume1@1.0.2, outerspacetunesvolume2@1.0.2, playercorpse@1.12.0, realsmokeforchiseltools@1.1.1, snowshoes@2.1.2, stonequarry@3.5.1, tabletopgames@3.0.2, wolftaming@4.0.1, xskills@0.9.0-pre.2, bricklayers@3.1.1, cob@2.4.0, outerspacetunesmaster@1.0.2
System.Exception: soundconfig.json not loaded. Is it missing or are you trying to load sounds before the client has received the level finalize event? | game:sounds/notifications/arrival
   at Vintagestory.Client.NoObf.ClientMain.ResolveSoundPath(AssetLocation location) in /home/dilli/drive_linux/git_repos/anego/game_stable/VintagestoryLib/Client/Systems/Audio/SoundEngine.cs:line 31
   at Vintagestory.Client.NoObf.ClientMain.PlaySoundAtInternal(AssetLocation location, Double x, Double y, Double z, Single volume, Single pitch, Single range, EnumSoundType soundType) in /home/dilli/drive_linux/git_repos/anego/game_stable/VintagestoryLib/Client/Systems/Audio/SoundEngine.cs:line 180
   at Vintagestory.Client.NoObf.ClientMain.PlaySoundAt(AssetLocation location, Double posx, Double posy, Double posz, IPlayer dualCallByPlayer, EnumSoundType soundType, Single pitch, Single range, Single volume) in /home/dilli/drive_linux/git_repos/anego/game_stable/VintagestoryLib/Client/Systems/Audio/SoundEngine.cs:line 97
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleSound(Packet_Server packet) in /home/dilli/drive_linux/git_repos/anego/game_stable/VintagestoryLib/Client/Systems/GeneralPacketHandler.cs:line 191
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in /home/dilli/drive_linux/git_repos/anego/game_stable/VintagestoryLib/Client/Systems/ProcessPacketTask.cs:line 18
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in /home/dilli/drive_linux/git_repos/anego/game_stable/VintagestoryLib/Client/Systems/ProcessPacketTask.cs:line 12
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in /home/dilli/drive_linux/git_repos/anego/game_stable/VintagestoryLib/Client/ClientMain.cs:line 786
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in /home/dilli/drive_linux/git_repos/anego/game_stable/VintagestoryLib/Client/MainMenu/Screens/GuiScreenConnectingToServer.cs:line 298
   at Vintagestory.Client.ScreenManager.Render(Single dt) in /home/dilli/drive_linux/git_repos/anego/game_stable/VintagestoryLib/Client/ScreenManager.cs:line 760
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in /home/dilli/drive_linux/git_repos/anego/game_stable/VintagestoryLib/Client/ScreenManager.cs:line 663
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in /home/dilli/drive_linux/git_repos/anego/game_stable/VintagestoryLib/Client/ClientPlatform/GameWindow.cs:line 113
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in /home/dilli/drive_linux/git_repos/anego/game_stable/VintagestoryLib/Client/ClientProgram.cs:line 338
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in /home/dilli/drive_linux/git_repos/anego/game_stable/VintagestoryLib/Client/ClientProgram.cs:line 133
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in /home/dilli/drive_linux/git_repos/anego/game_stable/VintagestoryLib/Client/ClientPlatform/ClientNative/CrashReporter.cs:line 95

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 30.09.2025 00:20:08, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.21.1.0, Zeitstempel: 0x67fe0000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x558
Startzeit der fehlerhaften Anwendung: 0x01dc318f0eb94aca
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 5ade8f8b-1028-4f09-a2da-c07e1db0657b
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 25.09.2025 11:57:09, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.21.1.0, Zeitstempel: 0x67fe0000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x4ce0
Startzeit der fehlerhaften Anwendung: 0x01dc2e0223554162
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: c76c5324-eb16-47ef-bac0-ab0ad58fd13b
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 25.09.2025 11:48:28, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.21.1.0, Zeitstempel: 0x67fe0000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x5078
Startzeit der fehlerhaften Anwendung: 0x01dc2dffc5e039f6
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: d3fec985-a151-4480-b717-9c23ab62b035
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }

**Comment by Th3Dilli** [comment]
@WickedSchnitzel sorry for the late reply

System.Exception: soundconfig.json not loaded. Is it missing or are you trying to load sounds before the client has received the level finalize event? | game:sounds/notifications/arrival

can you check in your clients unpacked folder
if you can find any file called `arrival`

apparently it is looking for a sound
`game:sounds/notifications/arrival`
 but as far as I can see there is not such sound in the game so it must be a mod
