### ISSUE TITLE
Crash to desktop when attacking a boar - 

### ISSUE THREAD

**Issue by ILUJinPark** [anegostudios/VintageStory-Issues#3660]
### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Attack with any weapon and it instantly crashes. 

### How to reproduce

Attack with any weapon and it instantly crashes. 

### Logs

Running on 64 bit Windows 10.0.22631.0 with 32581 MB RAM
Game Version: v1.19.4 (Stable)
02-03-2024 09:22:47: Critical error occurred in the following mod: weaponpacka@1.3.1
Loaded Mods: aculinaryartillery@1.1.2, weaponpacka@1.3.1, autopanning@1.0.1, backpackpackplus@1.0.3, charcoalpitrebalance@1.0.1, driedfirefuels@1.1.1, extrachests@1.8.0, primitivesurvival@3.4.7, stackables@2.0.5, game@1.19.4, animationmanagerlib@0.7.0, betterfirepit@1.1.4, carryon@1.7.4, commonlib@2.3.5, expandedfoods@1.6.8, hudclock@3.4.0, knifemold@1.0.1, creative@1.19.4, vsimgui@1.0.0, survival@1.19.4, configlib@1.0.0, em@2.5.0, fsmlib@0.2.15
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.ModelTransform.Translation'.
   at CustomWeaponSpeed.SlowSwordChargeFast.OnHeldAttackStep(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSelection, EntitySelection entitySel)
   at Vintagestory.API.Common.CollectibleObject.OnHeldUseStep(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1136
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 307
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 162
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
Caused by weapon pack alpha mod
