### ISSUE TITLE
Client CTD when attempting to sleep as Ad-Hoc server host

### ISSUE THREAD

**Issue by HardcastFlare** [anegostudios/VintageStory-Issues#3664]
### Game Version

v1.19.4 Stable

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

I attempt to sleep at the same time as my friend so that we can pass time. My client crashes after a few ticks of the hunger-draining time passing mechanism, before I see the wake-up animation.

### Logs

```Version: v1.14.2 (Stable)12/13/2020 11:51:05 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at MeteoricExpansion.MeteoricExpansionHelpers.GetMinLifespan() in C:\Projects\vsmods\mods\meteoricexpansion\src\systems\MeteoricExpansionHelpers.cs:line 55
   at MeteoricExpansion.EntityMeteor.Initialize(EntityProperties properties, ICoreAPI api, Int64 InChunkIndex3d) in C:\Projects\vsmods\mods\meteoricexpansion\src\entities\Meteor.cs:line 44
   at Vintagestory.Client.NoObf.ClientSystemEntities.entityFromPacket(_jaIUFwW2RKvoWDz37OvretAqH4d entitypacket, ClientMain game)
   at Vintagestory.Client.NoObf.ClientSystemEntities.createOrUpdateEntityFromPacket(_jaIUFwW2RKvoWDz37OvretAqH4d entitypacket, ClientMain game, Boolean addToLoadQueue)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityLoadedPacket(_yYcLwwVgddc6OWOmqOfREe6xnKd serverpacket)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _uWwiuXC8cGTH1JnsWiUY9FUaXOo._0WtXQJqGAidcdKMfPHF0OxDIauE(Single )
   at _ydpin5JFjepNgd3JOZRb2z5I5Fg._LvRZFcsDWyPwKLB1F2UK7fQ2N6d(Single )
   at _ydpin5JFjepNgd3JOZRb2z5I5Fg._GO2qaUrk9dl0IceTLiA7P4LcpAB(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _Ine8FeGTtDXciSIfaZMHMwCLKGBA._8puLW8J44fiq3A5hthQTfB8WNxc(_SbVlAI6dJIZ4JRt0da0lu23DF14 , String[] )
   at _lErb0L2e9E9htuT2VVnAsXIZqc7A._8puLW8J44fiq3A5hthQTfB8WNxc(ThreadStart )
-------------------------------
Game Version: v1.19.4 (Stable)
2/28/2024 7:14:01 AM: Critical error occurred in the following mod: carrycapacity@0.5.2
Loaded Mods: rope-bridges@1.0.4, meteoricexpansion@1.0.2, orecrystals@1.2.0, paints@1.3.0, game@1.19.4, carrycapacity@0.5.2, medievalexpansion@3.1.2, creative@1.19.4, survival@1.19.4
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.AnimManager'.
   at CarryCapacity.Client.EntityCarryRenderer.RenderAllCarried(EntityAgent entity, Single deltaTime, Boolean isShadowPass)
   at CarryCapacity.Client.EntityCarryRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in /home/copygirl/projects/VintageStoryMods/CarryCapacity/src/Client/EntityCarryRenderer.cs:line 79
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 200
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 806
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 869
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 730
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Game Version: v1.19.4 (Stable)
3/3/2024 4:39:24 AM: Critical error occurred
Loaded Mods: game@1.19.4, creative@1.19.4, survival@1.19.4
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.MathTools.Mat4f.Multiply(Single[] output, Single[] a, Single[] b) in VintagestoryApi\Math\Matrix\Mat4f.cs:line 340
   at Vintagestory.API.Common.AnimationFrame.FinalizeMatrices(Dictionary`2 jointsById) in VintagestoryApi\Common\Model\Animation\AnimationFrame.cs:line 58
   at Vintagestory.API.Common.Animation.GenerateAllFrames(ShapeElement[] rootElements, Dictionary`2 jointsById, Boolean recursive) in VintagestoryApi\Common\Model\Animation\Animation.cs:line 97
   at Vintagestory.API.Common.ClientAnimator.AnimNowActive(RunningAnimation anim, AnimationMetaData animData) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 225
   at Vintagestory.API.Common.AnimatorBase.OnFrame(Dictionary`2 activeAnimationsByAnimCode, Single dt) in VintagestoryApi\Common\Model\Animation\AnimatorBase.cs:line 116
   at Vintagestory.API.Common.AnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Model\Animation\AnimationManager.cs:line 347
   at Vintagestory.API.Common.PlayerAnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Entity\PlayerAnimationManager.cs:line 34
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Game Version: v1.19.4 (Stable)
3/3/2024 5:26:00 AM: Critical error occurred
Loaded Mods: game@1.19.4, creative@1.19.4, survival@1.19.4
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.MathTools.Mat4f.Multiply(Single[] output, Single[] a, Single[] b) in VintagestoryApi\Math\Matrix\Mat4f.cs:line 340
   at Vintagestory.API.Common.AnimationFrame.FinalizeMatrices(Dictionary`2 jointsById) in VintagestoryApi\Common\Model\Animation\AnimationFrame.cs:line 58
   at Vintagestory.API.Common.Animation.GenerateAllFrames(ShapeElement[] rootElements, Dictionary`2 jointsById, Boolean recursive) in VintagestoryApi\Common\Model\Animation\Animation.cs:line 97
   at Vintagestory.API.Common.ClientAnimator.AnimNowActive(RunningAnimation anim, AnimationMetaData animData) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 225
   at Vintagestory.API.Common.AnimatorBase.OnFrame(Dictionary`2 activeAnimationsByAnimCode, Single dt) in VintagestoryApi\Common\Model\Animation\AnimatorBase.cs:line 116
   at Vintagestory.API.Common.AnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Model\Animation\AnimationManager.cs:line 347
   at Vintagestory.API.Common.PlayerAnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Entity\PlayerAnimationManager.cs:line 34
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by HardcastFlare** [comment]
No longer crashing after friend unequipped the Festive Cat Mask item and put it in a chest nearby. Suspect it's due to the animation in some way as the ears on top of the mask don't animate with the rest of the player model and mask. Could also be a coincidence!

**Comment by Th3Dilli** [comment]
seems mod related,
also carrycapacity is not update anymore see carryon for an updated version of it
