### ISSUE TITLE
Charcoal Ground Storage and Snow

### ISSUE THREAD

**Issue by MystRunner** [anegostudios/VintageStory-Issues#3668]
### Game Version

v1.19.4 (Stable)

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Winter in game and I'm adding charcoal to my ground storage pile near my forge. As the charcoal falls down the pile and lands on snow the game will crash. I've had this happen three times now exactly the same thing. I don't know if this happens with other similar collapsible storages but I can reproduce it with charcoal every time. I don't have any mods affecting charcoal at this point in time and the log seems to not mention an issue with a mod outside the main base game packs.

### How to reproduce

1. Winter time with snow on the ground.
2. Store charcoal until it starts collapsing.
3. Charcoal collapses on top of snow game crashes.

### Logs

```Log```
Running on 64 bit Windows 10.0.19045.0 with 31904 MB RAM
Game Version: v1.19.4 (Stable)
3/3/2024 3:37:46 PM: Critical error occurred
Loaded Mods: acorns@0.5.3, aculinaryartillery@1.1.3, driedpeat@1.0.3, giantgouramis@1.0.2, HangingOilLamps@1.0.1, moreicons@1.1.0, newworldgianttortoises@1.1.1, pondfrogsiii@1.2.3, peacockbasses@1.1.2, primitivesurvival@3.4.7, truesunfishes@1.1.2, game@1.19.4, betterfirepit@1.1.4, carryon@1.7.4, composter@1.1.0, expandedfoods@1.6.8, extendedhudinfo@1.1.0, farmlanddropssoil@1.4.0, fromgoldencombs@1.4.25, moreanimals@1.3.3, prospecttogether@1.3.0, simplestep@1.1.7, vtpp@1.1.1, creative@1.19.4, survival@1.19.4, wildfarmingrevival@1.1.8, woodbarrels@1.0.4, bugnetcompatibility@1.0.1, treetapping@1.0.0
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.MaxFloat[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Vintagestory.API.Common.EntityPlayer.canPlayEdgeSitAnim() in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 995
   at Vintagestory.API.Common.EntityPlayer.onAnimControls(AnimationMetaData anim, Boolean wasActive, Boolean nowActive) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 978
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 540
   at Vintagestory.API.Common.EntityPlayer.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 680
   at Vintagestory.Client.NoObf.ClientSystemEntities.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Entities.cs:line 99
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by radfast** [comment]
Already fixed in 1.19.5-rc.1
