### ISSUE TITLE
Crash while sleeping in a bed. 

### ISSUE THREAD

**Issue by Emspara** [anegostudios/VintageStory-Issues#368]
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.12.4 (Stable)2/20/2020 9:15:50 PM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.MathTools.SimplexNoiseOctave.Evaluate(Double x, Double y, Double z)
   at Vintagestory.API.MathTools.SimplexNoise.Noise(Double x, Double y, Double z)
   at Vintagestory.GameContent.WeatherPattern.RegenCloudTileCache(Vec3i tileOffset)
   at Vintagestory.GameContent.WeatherSystemClient.EnsureCloudTileCacheIsFresh(Vec3i tilePos)
   at Vintagestory.GameContent.CloudRenderer.UpdateCloudTilesOffThread(Int32 changeSpeed)
   at Vintagestory.GameContent.CloudRenderer.<.ctor>b__30_2()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 1/30/2020 4:51:28 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.GameContent.BlockMeal.GetContentNutritionFacts(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot, Vintagestory.API.Common.ItemStack[], Vintagestory.API.Common.EntityAgent, Boolean)
   at Vintagestory.GameContent.BlockCookedContainer.GetHeldItemInfo(Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor, Boolean)
   at Vintagestory.API.Common.ItemStack.GetDescription(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot, Boolean)
   at Vintagestory.API.Client.GuiElementItemstackInfo.Recompose()
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(Vintagestory.API.Common.ItemSlot)
   at Vintagestory.Client.NoObf.HudMouseTools.OnMouseEnterSlot(Vintagestory.API.Common.ItemSlot)
   at _VDsWgzK30VQbGsNO9IbfdQ0yn0l._sR1SnTD3kdgIN7AFHblDCkki1Hr(_NG0ZnXmTtmPezIn9LSDyNwn1qcA, Vintagestory.API.Common.ItemSlot)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseMove(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiComposer.OnMouseMove(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiDialog.OnMouseMove(Vintagestory.API.Client.MouseEvent)
   at _DbLXOrSSss3n9bUIQMlb1ZMI2CJ._AdGvwJeqjwmXyBanw7KqModEJgg(Vintagestory.API.Client.MouseEvent)
   at _NG0ZnXmTtmPezIn9LSDyNwn1qcA._AdGvwJeqjwmXyBanw7KqModEJgg(Vintagestory.API.Client.MouseEvent)
   at _k603ozcgxEWfTany0f4BuFkKaTO._tDgS1gbY9aAUQqKolwFspPjuCVj()
   at _k603ozcgxEWfTany0f4BuFkKaTO._cofRcWkjdUpiHnZj5DznYMVdHcb(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _KhnygRKbChlhNVZ6NoTIj4AppFv._CZt1ULfHsOfvWyybAWFzfZAPlmN(_v0QfrgDod6R3FrQXNUcbGgdKeRI, System.String[])
   at _Vfez4jOq8l9qPflsxomPO9fBnuB._CZt1ULfHsOfvWyybAWFzfZAPlmN(System.Threading.ThreadStart)

 }
{ TimeGenerated = 1/30/2020 4:49:59 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.GameContent.BlockMeal.GetContentNutritionFacts(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot, Vintagestory.API.Common.ItemStack[], Vintagestory.API.Common.EntityAgent, Boolean)
   at Vintagestory.GameContent.BlockCookedContainer.GetHeldItemInfo(Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor, Boolean)
   at Vintagestory.API.Common.ItemStack.GetDescription(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot, Boolean)
   at Vintagestory.API.Client.GuiElementItemstackInfo.Recompose()
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(Vintagestory.API.Common.ItemSlot)
   at Vintagestory.Client.NoObf.HudMouseTools.OnMouseEnterSlot(Vintagestory.API.Common.ItemSlot)
   at _VDsWgzK30VQbGsNO9IbfdQ0yn0l._sR1SnTD3kdgIN7AFHblDCkki1Hr(_NG0ZnXmTtmPezIn9LSDyNwn1qcA, Vintagestory.API.Common.ItemSlot)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseMove(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiComposer.OnMouseMove(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiDialog.OnMouseMove(Vintagestory.API.Client.MouseEvent)
   at _DbLXOrSSss3n9bUIQMlb1ZMI2CJ._AdGvwJeqjwmXyBanw7KqModEJgg(Vintagestory.API.Client.MouseEvent)
   at _NG0ZnXmTtmPezIn9LSDyNwn1qcA._AdGvwJeqjwmXyBanw7KqModEJgg(Vintagestory.API.Client.MouseEvent)
   at _k603ozcgxEWfTany0f4BuFkKaTO._tDgS1gbY9aAUQqKolwFspPjuCVj()
   at _k603ozcgxEWfTany0f4BuFkKaTO._cofRcWkjdUpiHnZj5DznYMVdHcb(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _KhnygRKbChlhNVZ6NoTIj4AppFv._CZt1ULfHsOfvWyybAWFzfZAPlmN(_v0QfrgDod6R3FrQXNUcbGgdKeRI, System.String[])
   at _Vfez4jOq8l9qPflsxomPO9fBnuB._CZt1ULfHsOfvWyybAWFzfZAPlmN(System.Threading.ThreadStart)

 }
{ TimeGenerated = 1/30/2020 4:49:04 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.GameContent.BlockMeal.GetContentNutritionFacts(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot, Vintagestory.API.Common.ItemStack[], Vintagestory.API.Common.EntityAgent, Boolean)
   at Vintagestory.GameContent.BlockCookedContainer.GetHeldItemInfo(Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor, Boolean)
   at Vintagestory.API.Common.ItemStack.GetDescription(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot, Boolean)
   at Vintagestory.API.Client.GuiElementItemstackInfo.Recompose()
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(Vintagestory.API.Common.ItemSlot)
   at Vintagestory.Client.NoObf.HudMouseTools.OnMouseEnterSlot(Vintagestory.API.Common.ItemSlot)
   at _VDsWgzK30VQbGsNO9IbfdQ0yn0l._sR1SnTD3kdgIN7AFHblDCkki1Hr(_NG0ZnXmTtmPezIn9LSDyNwn1qcA, Vintagestory.API.Common.ItemSlot)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseMove(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiComposer.OnMouseMove(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiDialog.OnMouseMove(Vintagestory.API.Client.MouseEvent)
   at _DbLXOrSSss3n9bUIQMlb1ZMI2CJ._AdGvwJeqjwmXyBanw7KqModEJgg(Vintagestory.API.Client.MouseEvent)
   at _NG0ZnXmTtmPezIn9LSDyNwn1qcA._AdGvwJeqjwmXyBanw7KqModEJgg(Vintagestory.API.Client.MouseEvent)
   at _k603ozcgxEWfTany0f4BuFkKaTO._tDgS1gbY9aAUQqKolwFspPjuCVj()
   at _k603ozcgxEWfTany0f4BuFkKaTO._cofRcWkjdUpiHnZj5DznYMVdHcb(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _KhnygRKbChlhNVZ6NoTIj4AppFv._CZt1ULfHsOfvWyybAWFzfZAPlmN(_v0QfrgDod6R3FrQXNUcbGgdKeRI, System.String[])
   at _Vfez4jOq8l9qPflsxomPO9fBnuB._CZt1ULfHsOfvWyybAWFzfZAPlmN(System.Threading.ThreadStart)

 }
```

**Comment by tyronx** [comment]
huh, thats highly unusual. I couldn't find any potential cause at first glance. Please do report when it happens again.

**Comment by Emspara** [comment]
will do. I saw something that said  a client memory issue when using
stairs. I walk up several stairs to go into my room and sleep. Don't know
if that helps or not. Maybe related, maybe not.

**Comment by Carltoffel** [comment]
I had such a crash, too. I was sleeping, the screen went black as always and after a moment not waking up, I tried shaking my mouse which might have crashed my game.

**Comment by DeaLuna241** [comment]
Occured the same problem while playing a while like two to three hours when i go to sleep it crashes.
Happened 4 times in total.

[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/4281691/client-crash.txt)

**Comment by Craluminum2413** [comment]
Maybe this is a fix
> https://www.vintagestory.at/forums/topic/3383-stabler-steel-age-and-character-customization-v1141-2/?tab=comments#comment-13467
> Fixed: Should fix rare client crash related to the weather system

**Comment by copygirl** [comment]
Let's close it for now - can always reopen or create a new issue if it still happens.
