### ISSUE TITLE
Game CTD on load after placing crock of 100% spoiled jam, soon to be rot, in ground storage. Save file currently unusable.

### ISSUE THREAD

**Issue by schall86** [anegostudios/VintageStory-Issues#3683]
### Game Version

v1.19.4

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Game crashed when I placed crock on ground. Save won't load now.

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32672 MB RAM
Game Version: v1.19.4 (Stable)
3/2/2024 5:30:11 PM: Critical error occurred
Loaded Mods: advancedsmithing@1.3.0, landformoverhaul@0.0.2, caninae@1.0.10, pantherinae@1.1.1, primitivesurvival@3.4.6, seedharvest@1.0.0, game@1.19.4, egocaribautomapmarkers@3.0.0, fieldsofsalt@1.2.0, fromgoldencombs@1.4.25, kreaturesandkritters@1.0.3, norottinghides@1.0.0, petai@2.2.3, rivers@2.5.0, creative@1.19.4, vsimgui@0.3.5, survival@1.19.4, configlib@0.4.5, feverstonehorses@1.6.0-rc.2, statushudcont@2.1.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.VanillaCookingRecipeNames.GetNameForIngredients(IWorldAccessor worldForResolve, String recipeCode, ItemStack[] stacks) in VSSurvivalMod\Systems\Cooking\CookingRecipe.cs:line 238
   at Vintagestory.GameContent.CookingRecipe.GetOutputName(IWorldAccessor worldForResolve, ItemStack[] inputStacks) in VSSurvivalMod\Systems\Cooking\CookingRecipe.cs:line 496
   at Vintagestory.GameContent.BlockCookedContainerBase.GetContainedInfo(ItemSlot inSlot) in VSSurvivalMod\Block\BlockCookedContainerBase.cs:line 312
   at Vintagestory.GameContent.BlockEntityGroundStorage.getContentSummary() in VSSurvivalMod\BlockEntity\BEGroundStorage.cs:line 968
   at Vintagestory.GameContent.BlockEntityGroundStorage.GetBlockName() in VSSurvivalMod\BlockEntity\BEGroundStorage.cs:line 915
   at Vintagestory.GameContent.BlockGroundStorage.GetPlacedBlockName(IWorldAccessor world, BlockPos pos) in VSSurvivalMod\Block\BlockGroundStorage.cs:line 344
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.ComposeBlockInfoHud() in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 53
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.BlockInView() in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 187
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.Every15ms(Single dt) in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 153
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 838
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 730
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 3/2/2024 5:28:59 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.4.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x3438
Faulting application start time: 0x01da6cf0e22f24a0
Faulting application path: C:\Users\steve\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\steve\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 9bbe99db-9fc2-4edf-bd0d-bc89cbf84349
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by schall86** [comment]
Crashes the same with no mods.

Crashes on 1.19.3

**Comment by schall86** [comment]
I removed and reinstalled 1.19.4 and it loads now. Don't know if installation or trying to load the save with 1.19.3 and then 1.19.4.

**Comment by Craluminum2413** [comment]
@schall86 Does it happen without any mods?

**Comment by schall86** [comment]
> Crashes the same with no mods.
> 
> Crashes on 1.19.3

**Comment by schall86** [comment]
Log with no mods

Running on 64 bit Windows 10.0.19045.0 with 32672 MB RAM
Game Version: v1.19.4 (Stable)
3/5/2024 11:02:20 AM: Critical error occurred
Loaded Mods: game@1.19.4, creative@1.19.4, survival@1.19.4
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.VanillaCookingRecipeNames.GetNameForIngredients(IWorldAccessor worldForResolve, String recipeCode, ItemStack[] stacks) in VSSurvivalMod\Systems\Cooking\CookingRecipe.cs:line 238
   at Vintagestory.GameContent.CookingRecipe.GetOutputName(IWorldAccessor worldForResolve, ItemStack[] inputStacks) in VSSurvivalMod\Systems\Cooking\CookingRecipe.cs:line 496
   at Vintagestory.GameContent.BlockCookedContainerBase.GetContainedInfo(ItemSlot inSlot) in VSSurvivalMod\Block\BlockCookedContainerBase.cs:line 312
   at Vintagestory.GameContent.BlockEntityGroundStorage.getContentSummary() in VSSurvivalMod\BlockEntity\BEGroundStorage.cs:line 968
   at Vintagestory.GameContent.BlockEntityGroundStorage.GetBlockName() in VSSurvivalMod\BlockEntity\BEGroundStorage.cs:line 915
   at Vintagestory.GameContent.BlockGroundStorage.GetPlacedBlockName(IWorldAccessor world, BlockPos pos) in VSSurvivalMod\Block\BlockGroundStorage.cs:line 344
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.ComposeBlockInfoHud() in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 53
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.BlockInView() in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 187
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.Every15ms(Single dt) in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 153
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 19
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 81
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 838
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 730
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by schall86** [comment]
Crash is related to the rendering of the container in question, perhaps the label on the front? game is stable as long as I don't look at the crocks. I stood on top of them and tried a /we block command to replace the ground storage, but it just layered the packed dirt block over the crocks and then crashed when I looked down.

**Comment by radfast** [comment]
Thanks, should be fixed in upcoming 1.19.5-stable (in around 10 days time).

If you would be kind enough to keep your save with the error until then and see if that fixes the issue (and there are no other issues!) that would be really appreciated!
