### ISSUE TITLE
game crashed and i dont know how to trouble shoot

### ISSUE THREAD

**Issue by Y0K0VR** [anegostudios/VintageStory-Issues#3686]
i have a few mods (the furry ones are for one of my friends)

Running on 64 bit Windows 10.0.19045.0 with 16318 MB RAM
Game Version: v1.19.4 (Stable)
3/6/2024 4:59:14 PM: Critical error occurred
Loaded Mods: AnthroFoxPlayerModel@1.0.1, bettertraders@0.0.5, driedfirefuels@1.1.1, femininity@0.1.3, she1fish@1.2.0, simpleclasses@2.0.2, game@1.19.4, animationmanagerlib@0.7.0, betterruins@0.3.3, clearerquartz@1.0.0, paxel@1.4.3, creative@1.19.4, vsimgui@0.3.3, survival@1.19.4, vsvillage@0.9.2, tradercamps@1.1.2, configlib@0.4.2, foxtaming@1.4.0, fsmlib@0.2.15, maltiezfirearms@0.5.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.EntityHeadController.OnFrame(Single dt) in VintagestoryApi\Common\Model\Animation\EntityHeadController.cs:line 196
   at Vintagestory.API.Common.AnimationManager.OnClientFrame_Patch1(AnimationManager this, Single dt)
   at Vintagestory.API.Common.PlayerAnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Entity\PlayerAnimationManager.cs:line 34
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by radfast** [comment]
Almost certainly a mod issue, as the unmodded game code does not have a `EntityHeadController.cs:line 196`

To trouble shoot:
1. Try to identify a way to reproduce the crash reliably  (or maybe it's now an instant crash if you log on to this world)
2. Backup your world - i.e. make a copy of the .vcdbs world save file and keep it somewhere safe, maybe outside the Vintage Story data folder so that you can't accidentally change it
3. Disable some of the mods (start with **code** mods - the in-game Mod Manager flags those) and see if the crash still occurs
4. If disabling mods stopped the crash now, try re-enabling _some_ of the ones you just disabled

Repeat (3) and (4) a few times and you should be able to figure out the exact mod causing the issue.  It helps to make notes of which ones you just disabled / re-enabled, and to work methodically in batches.  If you half the size of the batch each time, this is called a "Binary Search Method" and can lead you to the answer in 3 or 4 attempts.

**Comment by tyronx** [comment]
closing due to inactivity.
