### ISSUE TITLE
CTD with command .chatsize 

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#3687]
### Game Version

1.19.4

### Platform

Linux

### Modded

None

### SP/MP

Singleplayer

### Description

Setting chat window size to 0 0 leads to a CTD.

### How to reproduce

Issue the command `.chatsize 0 0`
As soon as there is something displayed on the chat (in MP) or you type something, the game crashes.

### Logs

```Running on 64 bit Linux (Linux Mint 21.3) [Kernel 5.15.0.97] with 15936 MB RAM
Game Version: v1.19.4 (Stable)
3/6/2024 11:06:42 PM: Critical error occurred
Loaded Mods: game@1.19.4, creative@1.19.4, survival@1.19.4
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Client.TextDrawUtil.Lineize(Context ctx, String text, EnumLinebreakBehavior linebreak, TextFlowPath[] flowPath, Double startOffsetX, Double startY, Double lineHeightMultiplier, Boolean keepLinebreakChar) in VintagestoryApi\Client\UI\TextDrawUtil.cs:line 317
   at Vintagestory.API.Client.RichTextComponent.CalcBounds(TextFlowPath[] flowPath, Double currentLineHeight, Double offsetX, Double lineY, Double& nextOffsetX) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\RichTextComponent.cs:line 119
   at Vintagestory.API.Client.GuiElementRichtext.CalcHeightAndPositions() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 142
   at Vintagestory.API.Client.GuiElementRichtext.SetNewTextWithoutRecompose(String vtmlCode, CairoFont baseFont, Action`1 didClickLink, Boolean recalcBounds) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 586
   at Vintagestory.API.Client.GuiElementRichtext.SetNewText(String vtmlCode, CairoFont baseFont, Action`1 didClickLink) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 553
   at Vintagestory.Client.NoObf.HudDialogChat.UpdateText() in VintagestoryLib\Client\Systems\Gui\Huds\HudDialogChat.cs:line 336
   at Vintagestory.Client.NoObf.HudDialogChat.CmdChatSize(TextCommandCallingArgs args) in VintagestoryLib\Client\Systems\Gui\Huds\HudDialogChat.cs:line 176
   at Vintagestory.Common.ChatCommandImpl.CallHandler(TextCommandCallingArgs callargs, Action`1 onCommandComplete, Dictionary`2 asyncParseResults) in VintagestoryLib\Common\API\Command\ChatCommandImpl.cs:line 311
   at Vintagestory.Common.ChatCommandImpl.Execute(TextCommandCallingArgs callargs, Action`1 onCommandComplete) in VintagestoryLib\Common\API\Command\ChatCommandImpl.cs:line 247
   at Vintagestory.Common.ChatCommandApi.Execute(String commandName, TextCommandCallingArgs args, Action`1 onCommandComplete) in VintagestoryLib\Common\API\Command\ChatCommandApi.cs:line 99
   at Vintagestory.Common.ChatCommandApi.Execute(String commandName, IClientPlayer player, Int32 groupId, String args, Action`1 onCommandComplete) in VintagestoryLib\Common\API\Command\ChatCommandApi.cs:line 185
   at Vintagestory.Client.NoObf.HudDialogChat.HandleClientCommand(String message, Int32 groupid) in VintagestoryLib\Client\Systems\Gui\Huds\HudDialogChat.cs:line 800
   at Vintagestory.Client.NoObf.HudDialogChat.HandleClientMessage(Int32 groupid, String message) in VintagestoryLib\Client\Systems\Gui\Huds\HudDialogChat.cs:line 813
   at Vintagestory.Client.NoObf.HudDialogChat.OnNewClientToServerChatLine(Int32 groupId, String message, EnumChatType chattype, String data) in VintagestoryLib\Client\Systems\Gui\Huds\HudDialogChat.cs:line 753
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerNewClientChatLine(Int32 groupid, String message, EnumChatType chattype, String data) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 336
   at Vintagestory.Client.NoObf.HudDialogChat.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\Huds\HudDialogChat.cs:line 540
   at Vintagestory.Client.NoObf.GuiManager.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 333
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1721
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 230
   at OpenTK.Windowing.Desktop.NativeWindow.KeyCallback(Window* window, Keys key, Int32 scancode, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Craluminum2413** [comment]
Doesn't happen anymore
