### ISSUE TITLE
Crashes when rendering certain locations

### ISSUE THREAD

**Issue by killypoja** [anegostudios/VintageStory-Issues#3696]
### Game Version

v1.19.4

### Platform

Linux

### Modded

Modded

### SP/MP

Multiplayer

### Description

While playing multiplayer with friends, a crash occurred when viewing or entering a certain building, so I am writing about this.

### How to reproduce

If you log in with the 'KillyPoja' ID or start as a 'KillyPoja' char single play, it crashes. 
Also, the same thing happened even if I removed all the mods.
but server is no crash 

A save file is enclosed.

savefile
https://drive.google.com/file/d/1yn3SVrc9AZRNCETmxJd9qXztxmZX-bw3/view?usp=sharing

### Logs

Running on 64 bit Windows 10.0.22621.0 with 32581 MB RAM
Game Version: v1.19.4 (Stable)
2024-03-09 오후 5:18:30: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.3, fantasycreatures@0.7.1, primitivesurvival@3.4.7, game@1.19.4, alchemy@1.6.25, ancienttools@1.5.12, betterruins@0.3.3, carryon@1.7.4, expandedfoods@1.6.8, petai@2.2.3, creative@1.19.4, survival@1.19.4, xlib119@0.7.4-dev.1191, wolftaming@2.1.0, xskills119@0.7.5-dev.1191
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityItemRenderer.LoadModelMatrix(ItemRenderInfo renderInfo, Boolean isShadowPass, Single dt) in VSEssentials\EntityRenderer\EntityItemRenderer.cs:line 280
   at Vintagestory.GameContent.EntityItemRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityItemRenderer.cs:line 150
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderOpaque3D(Single deltaTime) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 93
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 200
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 806
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 901
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 730
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2024-03-09 오후 5:17:01, Site = , Source = Application Error, Message = 오류 있는 응용 프로그램 이름: Vintagestory.exe, 버전: 1.19.4.0, 타임스탬프: 0x65310000
오류 있는 모듈 이름: openal32.dll, 버전: 1.23.0.0, 타임스탬프: 0x63dd31ad
예외 코드: 0x40000015
오류 오프셋: 0x00000000000df046
오류 있는 프로세스 ID: 0x0xb98
오류 있는 응용 프로그램 시작 시간: 0x0x1da71fa06fcf994
오류 있는 응용 프로그램 경로: C:\Users\killy\AppData\Roaming\Vintagestory\Vintagestory.exe
오류 있는 모듈 경로: C:\Users\killy\AppData\Roaming\Vintagestory\Lib\openal32.dll
보고서 ID: 7762a4b4-273a-4bb9-9491-565126d2b73f
오류 있는 패키지 전체 이름: 
오류 있는 패키지에 상대적인 응용 프로그램 ID:  }
--------------
{ TimeGenerated = 2024-03-09 오후 5:16:00, Site = , Source = Application Error, Message = 오류 있는 응용 프로그램 이름: Vintagestory.exe, 버전: 1.19.4.0, 타임스탬프: 0x65310000
오류 있는 모듈 이름: openal32.dll, 버전: 1.23.0.0, 타임스탬프: 0x63dd31ad
예외 코드: 0x40000015
오류 오프셋: 0x00000000000df046
오류 있는 프로세스 ID: 0x0x64c
오류 있는 응용 프로그램 시작 시간: 0x0x1da71f9e0b00ac0
오류 있는 응용 프로그램 경로: C:\Users\killy\AppData\Roaming\Vintagestory\Vintagestory.exe
오류 있는 모듈 경로: C:\Users\killy\AppData\Roaming\Vintagestory\Lib\openal32.dll
보고서 ID: 8c5d4d99-a888-4228-a327-80960a83e68d
오류 있는 패키지 전체 이름: 
오류 있는 패키지에 상대적인 응용 프로그램 ID:  }
--------------
{ TimeGenerated = 2024-03-09 오후 5:13:23, Site = , Source = Application Error, Message = 오류 있는 응용 프로그램 이름: Vintagestory.exe, 버전: 1.19.4.0, 타임스탬프: 0x65310000
오류 있는 모듈 이름: openal32.dll, 버전: 1.23.0.0, 타임스탬프: 0x63dd31ad
예외 코드: 0x40000015
오류 오프셋: 0x00000000000df046
오류 있는 프로세스 ID: 0x0x5a04
오류 있는 응용 프로그램 시작 시간: 0x0x1da71f98699e1ad
오류 있는 응용 프로그램 경로: C:\Users\killy\AppData\Roaming\Vintagestory\Vintagestory.exe
오류 있는 모듈 경로: C:\Users\killy\AppData\Roaming\Vintagestory\Lib\openal32.dll
보고서 ID: e478c508-a7d1-4a0a-88ed-980f1a80e1b9
오류 있는 패키지 전체 이름: 
오류 있는 패키지에 상대적인 응용 프로그램 ID:  }
```Log```

**Comment by Craluminum2413** [comment]
Does it happen in 1.19.5-rc.1?

**Comment by killypoja** [comment]
> 1.19.5-rc.1에서도 이런 일이 발생합니까?

Yes I just tested it. 

Running on 64 bit Windows 10.0.22621.0 with 32581 MB RAM
Game Version: v1.19.5-rc.1 (Unstable)
2024-03-09 오후 5:42:45: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.3, fantasycreatures@0.7.1, primitivesurvival@3.4.7, game@1.19.5-rc.1, alchemy@1.6.25, ancienttools@1.5.12, betterruins@0.3.3, carryon@1.7.4, expandedfoods@1.6.8, petai@2.2.3, creative@1.19.5-rc.1, survival@1.19.5-rc.1, xlib119@0.7.4-dev.1191, wolftaming@2.1.0, xskills119@0.7.5-dev.1191
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityItemRenderer.LoadModelMatrix(ItemRenderInfo renderInfo, Boolean isShadowPass, Single dt) in VSEssentials\EntityRenderer\EntityItemRenderer.cs:line 280
   at Vintagestory.GameContent.EntityItemRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityItemRenderer.cs:line 150
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderOpaque3D(Single deltaTime) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 92
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 200
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 806
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 901
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 730
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by killypoja** [comment]
> @killypoja모드 없이도 이런 일이 발생하나요?

yes 1.19.4 /1.19.5 same crash

Running on 64 bit Windows 10.0.22621.0 with 32581 MB RAM
Game Version: v1.19.5-rc.1 (Unstable)
2024-03-09 오후 6:36:36: Critical error occurred
Loaded Mods: game@1.19.5-rc.1, creative@1.19.5-rc.1, survival@1.19.5-rc.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityItemRenderer.LoadModelMatrix(ItemRenderInfo renderInfo, Boolean isShadowPass, Single dt) in VSEssentials\EntityRenderer\EntityItemRenderer.cs:line 280
   at Vintagestory.GameContent.EntityItemRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityItemRenderer.cs:line 150
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderOpaque3D(Single deltaTime) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 92
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 200
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 806
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 901
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 730
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by radfast** [comment]
The issue is caused by a dropped item in the save game, whose item is one which has been removed.  (Former item id 3509)
The likely cause is changing mods after the world was already played (including updating a mod).  Maybe, the mod did not include appropriate "remapping" config to remap old item 3509, I do not know ... there is no info about which mod created this item.

We will update game code not to crash in this situation, in version `1.19.5-stable` when it comes ... likely to be approximately 8-9 days from now, I apologize for the delay

**Comment by radfast** [comment]
Until then a server admin can attempt to fix the issue by using command `/entity wipeall` near to the building with the issue.  **CAUTION:** this command will also kill all animals, including domesticated animals.
