### ISSUE TITLE
Game closing at random moments

### ISSUE THREAD

**Issue by Shoog117** [anegostudios/VintageStory-Issues#3709]
### Game Version

1.19.4

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Multiplayer game crashes at seemingly random moments, such as other players opening chests and doors. Crashes do no occur when I (the host) do any of these things and I can't figure out a cause from the crash log.

### Logs

```Running on 64 bit Windows 10.0.19045.0 with 32719 MB RAM
Game Version: v1.19.4 (Stable)
12/03/2024 01:38:10: Critical error occurred
Loaded Mods: morecrops@1.0.3, game@1.19.4, abcsreborn@0.2.0, betterruins@0.3.3, butchering@1.5.3, carryon@1.7.4, commonlib@2.3.5, configureeverything@1.0.0, herbarium@1.1.0, sailboat@1.2.8, morepiles@1.5.0, rivers@2.7.0, simplestep@1.1.7, creative@1.19.4, vsinstruments@1.2.7, survival@1.19.4, xlib119@0.7.4-dev.1191, playercorpse@1.9.0, wildcraftfruit@1.1.1, xskills119@0.7.5-dev.1191
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.MaxFloat[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Vintagestory.API.Common.EntityPlayer.canPlayEdgeSitAnim() in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 995
   at Vintagestory.API.Common.EntityPlayer.onAnimControls(AnimationMetaData anim, Boolean wasActive, Boolean nowActive) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 978
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 540
   at Vintagestory.API.Common.EntityPlayer.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 680
   at Vintagestory.Client.NoObf.ClientSystemEntities.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Entities.cs:line 99
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Craluminum2413** [comment]
What mods are installed?

**Comment by radfast** [comment]
see #3668 and #3692
