### ISSUE TITLE
Chiseling cobblestone causes game to crash.

### ISSUE THREAD

**Issue by David-Garrancho** [anegostudios/VintageStory-Issues#3716]
### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

We were playing for about 2 hours, then a friend of mine decided to chisel a block for decor. When they began chiseling the block, then it crashed the moment he began.

### How to reproduce

1. Get a cobblestone block
2. Place cobblestone block
3. Chisel the placed cobblestone block 

### Screenshots

Can't provide as the block is preventing us from starting up the server.

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32598 MB RAM
Game Version: v1.19.4 (Stable)
13 Mar 2024 18:32:48: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ClientMain.UnregisterGameTickListener(Int64 listenerId) in VintagestoryLib\Client\ClientMain.cs:line 3233
   at Vintagestory.Client.NoObf.ClientEventAPI.UnregisterGameTickListener(Int64 listenerId) in VintagestoryLib\Client\API\ClientEventAPI.cs:line 572
   at Vintagestory.GameContent.GuiDialogWorldMap.Dispose() in VSEssentials\Systems\WorldMap\GuiDialogWorldMap.cs:line 286
   at Vintagestory.Client.NoObf.GuiManager.Dispose(ClientMain game) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 568
   at Vintagestory.Client.NoObf.ClientMain.Dispose() in VintagestoryLib\Client\ClientMain.cs:line 2678
   at Vintagestory.Client.GuiScreenConnectingToServer.exitToDisconnectScreen() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 416
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
I assume it is fixed so I close it now
