### ISSUE TITLE
game stop responding and crashes while gravity blocks and items bounce in the floor

### ISSUE THREAD

**Issue by NoreOtten** [anegostudios/VintageStory-Issues#3719]
### Game Version

v1.19.4

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

the game runs ok until items dropped stop responding and become impossible to pick up. i saw too gravity blocks such as dirt/gravel/unstable rocks with the "falling down" animation. this occurs ever since i updated the game and even lost a world because of it (a chunk corrupted and didn't loaded properly causing even more bugs).

### Screenshots

![2024-03-13_15-54-06](https://github.com/anegostudios/VintageStory-Issues/assets/163345117/3ca75037-ef1b-4a97-a458-8dfc30eb8074)
![2024-03-13_00-33-41](https://github.com/anegostudios/VintageStory-Issues/assets/163345117/c8128138-bd48-4abd-af47-68957a752c0e)
![2024-03-13_00-14-59](https://github.com/anegostudios/VintageStory-Issues/assets/163345117/0ed612ff-2bb3-40d7-8e23-219854dc2e21)
![2024-03-07_21-33-05](https://github.com/anegostudios/VintageStory-Issues/assets/163345117/b761393a-eea2-4a09-bdd5-a5db65cb7e51)
![2024-03-07_21-31-34](https://github.com/anegostudios/VintageStory-Issues/assets/163345117/5e92011a-f0b1-4046-916e-dcf7a7767533)
![2024-03-07_21-31-12](https://github.com/anegostudios/VintageStory-Issues/assets/163345117/a752d933-e48a-4707-bb48-e1b4471bcc83)

### Logs

[client-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/14592926/client-audit.txt)
[client-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/14592927/client-chat.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/14592928/client-crash.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/14592929/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/14592930/client-main.txt)
[server-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/14592931/server-audit.txt)
[server-build.txt](https://github.com/anegostudios/VintageStory-Issues/files/14592932/server-build.txt)
[server-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/14592933/server-chat.txt)
[server-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/14592934/server-debug.txt)
[server-event.txt](https://github.com/anegostudios/VintageStory-Issues/files/14592935/server-event.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/14592937/server-main.txt)
[server-storyevent.txt](https://github.com/anegostudios/VintageStory-Issues/files/14592941/server-storyevent.txt)

**_most recent crash log that i copied to clipboard:_**

Running on 64 bit Windows 10.0.19045.0 with 7530 MB RAM
Game Version: v1.19.4 (Stable)
13/03/2024 15:55:23: Critical error occurred
Loaded Mods: advancedsmithing@1.3.0, bettersticks@1.0.0, primitivesurvival@3.4.9, game@1.19.4, zoombuttonreborn@1.6.0, animalcages@3.0.2, carryon@1.7.4, commonlib@2.3.7, hudclock@3.3.0, morepiles@1.5.0, nbcartographer@2.0.9, nemi@1.1.0, outlawmod@1.2.1, petai@2.2.3, prospecttogether@1.3.0, recyclebags@1.0.1, recycleclothes@1.0.0, stickemup@1.1.0, creative@1.19.4, survival@1.19.4, playercorpse@1.9.0, stonequarry@3.2.1, wolftaming@2.1.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\Entity.cs:line 874
   at Vintagestory.API.Common.EntityItem.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityItem.cs:line 149
   at Vintagestory.Client.NoObf.ClientSystemEntities.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Entities.cs:line 99
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by NoreOtten** [comment]
Notice that the black chunk in the minimap is the chunk that got corrupted or bad loaded in my lost world.
(this is my first post here so pardon me if things don't look too good)

**Comment by Craluminum2413** [comment]
Does it happen without any mods?

**Comment by NoreOtten** [comment]
thank you so much! I was suspecting it was Outlaws mod, maybe the mobs interact with gravity blocks in parcially loaded chunks and that may cause the sloweness in the server. I updated the mod and this continued ocurring, sadly. I'm gonna turn that mod off until some new update or solution appear. Again, thank you to everybody who responded this post!
