### ISSUE TITLE
Translocator doesn't work, throws persistent "An error was thrown in pass Terrain when generating chunk column" due to System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by dandahlberg** [anegostudios/VintageStory-Issues#3725]
### Game Version

v1.19.4

### Platform

Linux

### Modded

None

### SP/MP

Multiplayer

### Description

After a translocator was repaired, it did not seem to function. At the same time, System.IO.FileNotFoundException started being persistently thrown several times a second in the `server-worldgen.txt` log file with different `X=` and `Y=` coordinates, as shown in the `Logs` section. Once the translocator is deleted, the exception stops. Once the translocator is respawned and repaired again, the exceptions resume.

### How to reproduce

1. Repair static translocator
2. The translocator will say "Warping spacetime.." but no animation will be present and standing on the device does nothing
3. The exceptions start being thrown in `server-worldgen.txt`
4. Deleting translocator causes them to stop.

This is a world created using 1.19.3, upgraded to 1.19.4

### Logs

```16.3.2024 05:46:10 [Worldgen] An error was thrown in pass Terrain when generating chunk column X=15769,Z=15773 in world 'A new world' with seed 889825547
Exception System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks.Parallel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Threading.Tasks.Parallel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Vintagestory.ServerMods.GenTerra.generate(IServerChunk[] chunks, Int32 chunkX, Int32 chunkZ, Boolean requiresChunkBorderSmoothing)
   at Vintagestory.ServerMods.GenTerra.OnChunkColumnGen(IChunkColumnGenerateRequest request) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\1.GenTerra\GenTerra.cs:line 170
   at Vintagestory.Server.ServerSystemSupplyChunks.runGenerators(ChunkColumnLoadRequest chunkRequest, Int32 forPass) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 1729
```

**Comment by dandahlberg** [comment]
It turns out (as implied by the exception) that this was related to the local dotnet7 runtime environment.

The server was originally setup using the dotnet-runtime-7.0 package via Linode's managed Ubuntu repository:

```Package: dotnet-runtime-7.0
Version: 7.0.117-0ubuntu1~22.04.1
Priority: optional
Section: universe/devel
Source: dotnet7
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 69.9 MB
Depends: dotnet-hostfxr-7.0, libicu70, libc6 (>= 2.34), libgcc-s1 (>= 3.0), liblttng-ust1 (>= 2.13.0), libssl3 (>= 3.0.0~~alpha1), libstdc++6 (>= 12), zlib1g (>= 1:1.1.4)
Breaks: dotnet-runtime-6.0 (<< 6.0.111~)
Homepage: https://dot.net/core
Download-Size: 24.5 MB
APT-Manual-Installed: no
APT-Sources: http://mirrors.linode.com/ubuntu jammy-updates/universe amd64 Packages
Description: dotNET runtime```

As a test, I uninstalled Linode's hosted version of the .NET 7.0 runtime and setup Microsoft's package repositories as described here: https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu

I installed Microsoft's runtime and its Microsoft-managed dependencies targeting 7.0.17 via:
`apt install dotnet-runtime-7.0=7.0.17-1 dotnet-hostfxr-7.0=7.0.17-1 dotnet-runtime-deps-7.0=7.0.17-1 dotnet-host=7.0.17-1
`

-- and it worked.

Appears to be environment related, but it's not clear why Linode's packages were deficient and missing expected libraries. I am also surprised this wasn't causing other worldgen issues.
