### ISSUE TITLE
Error while command movespeed used

### ISSUE THREAD

**Issue by Sury04** [anegostudios/VintageStory-Issues#3732]
### Game Version

v1.19.4

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Error in chat when I used the commande movespeed

### How to reproduce

/player [nametag] movespeed 1

### Screenshots

![2024-03-17_15-44-15](https://github.com/anegostudios/VintageStory-Issues/assets/155975652/b9c7d158-056d-4028-821a-b9dc268b8913)

### Logs

```Log```17.3.2024 15:34:48 [Error] Exception: Unable to cast object of type 'System.Double' to type 'System.Single'.
   at Vintagestory.Server.CmdPlayer.setMovespeed(PlayerUidName targetPlayer, TextCommandCallingArgs args) in VintagestoryLib\Server\Systems\Player\CmdPlayer.cs:line 1033
   at Vintagestory.Server.CmdPlayer.Each(TextCommandCallingArgs args, PlayerEachDelegate onPlayer) in VintagestoryLib\Server\Systems\Player\CmdPlayer.cs:line 1060
   at Vintagestory.Server.CmdPlayer.<.ctor>b__5_0(TextCommandCallingArgs args) in VintagestoryLib\Server\Systems\Player\CmdPlayer.cs:line 51
   at Vintagestory.Common.ChatCommandImpl.CallHandler(TextCommandCallingArgs callargs, Action`1 onCommandComplete, Dictionary`2 asyncParseResults) in VintagestoryLib\Common\API\Command\ChatCommandImpl.cs:line 311
   at Vintagestory.Common.ChatCommandImpl.Execute(TextCommandCallingArgs callargs, Action`1 onCommandComplete) in VintagestoryLib\Common\API\Command\ChatCommandImpl.cs:line 247
   at Vintagestory.Common.ChatCommandImpl.CallHandler(TextCommandCallingArgs callargs, Action`1 onCommandComplete, Dictionary`2 asyncParseResults) in VintagestoryLib\Common\API\Command\ChatCommandImpl.cs:line 274
   at Vintagestory.Common.ChatCommandImpl.Execute(TextCommandCallingArgs callargs, Action`1 onCommandComplete) in VintagestoryLib\Common\API\Command\ChatCommandImpl.cs:line 247
   at Vintagestory.Common.ChatCommandApi.Execute(String commandName, TextCommandCallingArgs args, Action`1 onCommandComplete) in VintagestoryLib\Common\API\Command\ChatCommandApi.cs:line 99
   at Vintagestory.Common.ChatCommandApi.Execute(String commandName, IServerPlayer player, Int32 groupId, String args, Action`1 onCommandComplete) in VintagestoryLib\Common\API\Command\ChatCommandApi.cs:line 143

**Comment by Craluminum2413** [comment]
@Sury04 Did you type `/player YourOwnUsername movespeed 1`?

**Comment by radfast** [comment]
Likely a code issue.

Movespeed can also be changed for one's own player (in Creative Mode) using the F1 and F2 keys, or the command `.movespeed 2` or `.movespeed 0.5`

**Comment by Sury04** [comment]
> @Sury04 Did you type `/player YourOwnUsername movespeed 1`?

Hello Craluminum2413, absolutly, I try "/player Suri04 movespeed 1"
I also try with 0.5 and 0.1 for test, and same problem

**Comment by Th3Dilli** [comment]
thank you for the report, will be fixed with 1.19.5
