### ISSUE TITLE
Can anyone help? game crashes when i join a server.

### ISSUE THREAD

**Issue by ItzKoril** [anegostudios/VintageStory-Issues#3741]
### Game Version

v1.19.4 (stable)

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Tried to join my own server, was met was an instant crash and this error. i dont understand what the error is saying really if anyone could help and walk me through.

### How to reproduce

1. launch game
2. join server
3. instant crash

### Logs

```Log```
Running on 64 bit Windows 10.0.22621.0 with 11599 MB RAM
Game Version: v1.19.4 (Stable)
3/20/2024 8:49:28 PM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ShaderAPI.ReloadShaders() in VintagestoryLib\Client\API\ShaderAPI.cs:line 53
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerReady(Packet_Server packet) in VintagestoryLib\Client\Systems\Startup.cs:line 881
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 446
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 440
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>cDisplayClass9_0.<.ctor>b1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
Fixed in 1.19.5-rc.1
