### ISSUE TITLE
Textures Leaking Memory on Game Window Resize 1.19.4

### ISSUE THREAD

**Issue by FlexibleGames** [anegostudios/VintageStory-Issues#3743]
### Game Version

v1.19.4

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Game version 1.19.4, apologize if this is fixed already. I looked through the .5 update posts and nothing jumped out at me.

Mods used are what I use to help me when debugging a mod (in this case Vintage Engineering) and for testing my own mods. 

22.3.2024 00:02:52 [Server Notification] Mods, sorted by dependency: angelbelt, backpackpackplus, bettercrates, BuggisRandomChanges, buildinggadgets, craftingtable, FlexibleTools, HoneyPress, vintageengineering, nightwatcher, oildeposits, OresAPlenty, game, diamondcrate, vmetp, creative, survival

22.3.2024 00:03:30 [Client Debug] Texture with texture id 339 is leaking memory, missing call to Dispose. Allocated at    at System.Environment.get_StackTrace()
   at Vintagestory.API.Client.LoadedTexture..ctor(ICoreClientAPI capi, Int32 textureId, Int32 width, Int32 height) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\Texture\LoadedTexture.cs:line 68
   at Vintagestory.Client.NoObf.SvgLoader.LoadSvg(IAsset svgAsset, Int32 textureWidth, Int32 textureHeight, Int32 width, Int32 height, Nullable`1 color) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\SvgLoader.cs:line 140
   at Vintagestory.Client.NoObf.GuiAPI.LoadSvg(AssetLocation loc, Int32 textureWidth, Int32 textureHeight, Int32 width, Int32 height, Nullable1 color) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\API\GuiAPI.cs:line 66
   at Vintagestory.GameContent.OreMapLayer.<>c__DisplayClass12_0.<.ctor>b__0() in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Prospecting\OreMapLayer\OreMapLayer.cs:line 47
   at Vintagestory.GameContent.OreMapLayer.ensureIconTexturesLoaded() in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Prospecting\OreMapLayer\OreMapLayer.cs:line 164
   at Vintagestory.GameContent.OreMapLayer.OnMapOpenedClient() in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Prospecting\OreMapLayer\OreMapLayer.cs:line 156
   at Vintagestory.GameContent.WorldMapManager.ToggleMap(EnumDialogType asType) in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 270
   at Vintagestory.GameContent.WorldMapManager.<StartClientSide>b__19_0(Boolean on) in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 102
   at Vintagestory.Common.SettingsClass`1.TriggerWatcher(String key) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\Config\SettingsBase.cs:line 75
   at Vintagestory.Common.SettingsClass`1.set_Item(String key, T value) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\Config\SettingsBase.cs:line 60
   at Vintagestory.GameContent.WorldMapManager.ToggleMap(EnumDialogType asType) in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 267
   at Vintagestory.GameContent.GuiDialogWorldMap.<ComposeDialog>b__19_0(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Systems\WorldMap\GuiDialogWorldMap.cs:line 164

### How to reproduce

Easily reproducible: Start game that is not full screen and while a world is loaded hit esc and resize the game window. When I exit the game I see about 8 of these warnings. Unfortunately the "Allocated at" is blank so I don't know what textures are doing it.

**Also, ticking the Texture debugging option under "Dev" doesn't stick, it resets to off every time I run the game.**

### Screenshots

NA, it's a text output.

### Logs

[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/14717680/client-debug.txt)

**Comment by tyronx** [comment]
thanks for the report, will fix!
