### ISSUE TITLE
Game doesn't allow me to join my multiplayer server

### ISSUE THREAD

**Issue by agentorange89** [anegostudios/VintageStory-Issues#3745]
### Game Version

v1.19.5 (Stable)

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Logs

Running on 64 bit Windows 10.0.19045.0 with 16332 MB RAM
Game Version: v1.19.5 (Stable)
3/23/2024 11:52:31 AM: Critical error occurred
Loaded Mods: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2502
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStates(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2450
   at Vintagestory.API.Common.CollectibleObject.AppendPerishableInfoText(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1809
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo_Patch0(CollectibleObject this, ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 400
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(ICoreClientAPI capi, ItemStack stack) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 40
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onCreatePagesAsync() in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 84
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 418
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 120
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by Craluminum2413** [comment]
What mods are installed?

**Comment by agentorange89** [comment]
![Untitled](https://github.com/anegostudios/VintageStory-Issues/assets/44745823/768edacb-9576-4495-b91c-f9544174d86e)

**Comment by Craluminum2413** [comment]
It is caused by some mod, but which one, you need to find it out yourself
