### ISSUE TITLE
Game crashing when pasting in text into the creative inventory search bar

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#3748]
### Game Version

1.19.5 stable

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I did paste in "mossy arc stone". Maybe the crash it mod related, no clue.

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32723 MB RAM
Game Version: v1.19.5 (Stable)
24.03.2024 14:20:18: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.3, ancientarmory@1.0.0, bettercrates@1.7.0, Ceramos@0.4.3, chiseltools@1.10.8, decor@1.0.15, extrachests@1.8.0, fantasycreatures@0.7.1, fixedpaths@1.0.1, flourbags@1.0.2, foundrymod@1.0.0, giantgouramis@1.0.2, millwright@1.1.4, moreicons_cs@1.1.0, peacockbasses@1.1.2, primitivesurvival@3.4.9, spyglass@0.5.1, Swordz@1.1.6, translocatorengineeringredux@1.4.9, truesunfishes@1.1.2, game@1.19.5, weaponpackalphaunoff@1.5.1, morecrops@1.0.3, TA_plainsandvalleys@1.0.5, ancienttools@1.5.16, beehivekiln@1.5.1, betterfirepit@1.1.4, betterjonasdevices@1.1.0, betterruins@0.3.4, carryon@1.7.4, commonlib@2.3.7, composter@1.1.0, expandedfoods@1.6.8, fairplayguardian@1.1.7, furniturelibrary@1.0.11, hangingbaskets@1.1.0, herbarium@1.1.0, sailboat@1.3.0, medievalexpansion@3.13.1, meteoricexpansion@1.2.5, morepiles@1.5.0, moreplaster@1.0.1, petai@2.2.3, rivers@2.4.0, simplestep@1.1.7, stonebakeoven@1.1.3, tentbag@1.1.1, th3dungeon@0.2.1-rc.1, thecritterpack@0.8.9, usefulstuff17@1.3.1, vinconomy@0.2.4, creative@1.19.5, vsinstruments@1.2.7, vsquest@1.2.0, survival@1.19.5, workbenchexpansion@1.8.0, xlib@0.8.0-rc.2, awearablelight@1.1.1, captureanimals@2.6.1, cob2@1.6.0, cobserver@1.0.1, em@2.5.1, linearpower@0.2.1, outerspacetunesmaster@1.0.0, outerspacetunesvolume1@1.0.0, outerspacetunesvolume2@1.0.0, playercorpse@1.9.0, rifteye@0.3.5, simplewinddirection@1.0.2, stonequarry@3.2.1, vanity@2.1.2, wildcraftfruit@1.1.1, wolftaming@2.1.0, xskills@0.8.0-rc.2, bunnybell119@1.0.3, bricklayers@2.5.1, cob@1.8.0, vsvillagecob@0.2.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.FilterItemsBySearchText(String text, Dictionary`2 searchCache, Dictionary`2 searchCacheNames) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 557
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnTextChanged(String text) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 421
   at Vintagestory.API.Client.GuiElementEditableTextBase.TextChanged() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 328
   at Vintagestory.API.Client.GuiElementEditableTextBase.LoadValue(List`1 newLines) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 292
   at Vintagestory.API.Client.GuiElementEditableTextBase.SetValue(String text, Boolean setCaretPosToEnd) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 264
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyDown(ICoreClientAPI api, KeyEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 486
   at Vintagestory.API.Client.GuiElementTextInput.OnKeyDown(ICoreClientAPI api, KeyEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementTextInput.cs:line 133
   at Vintagestory.API.Client.GuiComposer.OnKeyDown(KeyEvent args, Boolean haveFocus) in VintagestoryApi\Client\UI\GuiComposer.cs:line 581
   at Vintagestory.API.Client.GuiDialog.OnKeyDown(KeyEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 422
   at Vintagestory.Client.NoObf.GuiManager.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 341
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1737
   at Vintagestory.Client.GuiScreenRunningGame.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 310
   at Vintagestory.Client.ScreenManager.OnKeyDown(KeyEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 849
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 247
   at OpenTK.Windowing.Desktop.NativeWindow.OnKeyDown(KeyboardKeyEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.KeyCallback(Window* window, Keys key, Int32 scancode, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 2
==================================
{ TimeGenerated = 18.03.2024 18:13:06, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.5.0, Zeitstempel: 0x65310000
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.3996, Zeitstempel: 0xb756c9ff
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000002cf19
ID des fehlerhaften Prozesses: 0x58c4
Startzeit der fehlerhaften Anwendung: 0x01da795759c865d9
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: 7493be7a-b670-400e-901f-aca7e6252418
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 17.03.2024 22:18:20, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.5.0, Zeitstempel: 0x65310000
Name des fehlerhaften Moduls: coreclr.dll, Version: 7.0.1323.51816, Zeitstempel: 0x6530618b
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00000000001c87cc
ID des fehlerhaften Prozesses: 0x3ec0
Startzeit der fehlerhaften Anwendung: 0x01da78afd58dc68b
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.13\coreclr.dll
Berichtskennung: b3b73822-1cf0-4121-97ad-2fbe28e67cbe
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }

**Comment by Craluminum2413** [comment]
If it doesn't happen without mods, then it is mod related
