### ISSUE TITLE
Unable to join the game and subsequent game crash

### ISSUE THREAD

**Issue by KOKEIJN** [anegostudios/VintageStory-Issues#3759]
### Game Version

v1.19.5

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

Hello, I don't speak English very well, so I hope you can understand my problem.

Me and my brother bought your wonderful game and wanted to play.

So you know one, for example, I started a single player game and then I put LAN in the settings and my brother started entering the name, IP address and password. Then his character appeared in the game and the game loads for him everything is fine so far and when the download is almost finished it kicks him out of the game! but the game is still loading for him, and when the download is finished and he is typing (turning on the client), it suddenly turns off the game for the person in question and the given problem pops up.

We tried to reverse it so that he sets up and I connect and it does the exact same problem.
We even tried the internet through the second one, which is via LAN, and it still does it.

I don't know what to do, we've tried everything, please help me, I'm desperate, I want to enjoy this amazing game with my brother, but I can't.

### How to reproduce

1.Too bad the game isn't on Steam, I miss the option to simply start the game and invite someone, it's much easier and without problems.

2.Same when I bought the game, it took quite a while to click through it all.

3.And lastly keep up the good work the game is really good!

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/165269687/df908c90-6b0c-4048-bb01-478cb7fb8b06)

### Logs

```Log```Running on 64 bit Windows 10.0.19045.0 with 16308 MB RAM
Game Version: v1.19.5 (Stable)
28.03.2024 10:43:10: Critical error occurred
Loaded Mods: 
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Vintagestory.Client.NoObf.TextureAtlasManager.RegenMipMaps(Int32 atlasNumber) in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 359
   at Vintagestory.Client.NoObf.TextureAtlasManager.<>c__DisplayClass51_0.<runtimeUpdateTexture>b__1() in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 325
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 28.03.2024 10:43:10, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.19.5.0, časové razítko: 0x65310000
Název chybujícího modulu: KERNELBASE.dll, verze: 10.0.19041.3996, časové razítko: 0xb756c9ff
Kód výjimky: 0xe0434352
Posun chyby: 0x000000000002cf19
ID chybujícího procesu: 0x23bc
Čas spuštění chybující aplikace: 0x01da80ef049f8299
Cesta k chybující aplikaci: C:\Users\kejnc\AppData\Roaming\Vintagestory\Vintagestory.exe
Cesta k chybujícímu modulu: C:\WINDOWS\System32\KERNELBASE.dll
ID zprávy: 06239e99-05fe-44cf-8ca3-c137aac4bb0b
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }

**Comment by Saricane** [comment]
There is a problem with the way the game is installed : 
Your `Loaded mods` line should not be empty, it should be : 
`Loaded Mods: game@1.19.5, creative@1.19.5, survival@1.19.5`

So I suggest you reinstall your game from scratch.

**Comment by thalorn** [comment]
I have very similar issue. With my friend we are trying to connect via LAN with Hamachi/ZeroTier and after painstakingly long download of 1000 or so kilobytes him or I get disconected. We tried multiple clean installs but the error logs stay same.

**Logs**
```
1065 kilobyte received
30.3.2024 22:39:17 [Notification] Connected to server, downloading data...
1073 kilobyte received
30.3.2024 22:39:18 [Notification] Connected to server, downloading data...
1083 kilobyte received
30.3.2024 22:39:18 [Notification] Received server assets
30.3.2024 22:39:19 [Notification] Received 3336 item types from server
30.3.2024 22:39:19 [Notification] Loaded 9314 block types from server
30.3.2024 22:39:19 [Notification] Composed 1 4096x2048 entities texture atlases from 433 textures
30.3.2024 22:39:22 [Notification] Collected 2092 shapes to tesselate.
30.3.2024 22:39:22 [Notification] Composed 1 4096x2048 items texture atlases from 1684 textures
30.3.2024 22:39:24 [Notification] Composed 1 4096x2048 blocks texture atlases from 4441 textures
30.3.2024 22:39:25 [Notification] Server assets loaded
30.3.2024 22:39:25 [Notification] Loaded Shaderprogramm for render pass instanced.
30.3.2024 22:39:25 [Notification] Initialized Music Engine
30.3.2024 22:39:25 [Notification] Texture size is 32 so decal atlas size of 128x128 should suffice
30.3.2024 22:39:26 [Notification] Blocks tesselated
30.3.2024 22:39:26 [Notification] Received level finalize
30.3.2024 22:39:26 [Notification] Loaded Shaderprogramm for render pass clouds.
30.3.2024 22:39:26 [Notification] Loading world map cache db...
30.3.2024 22:39:27 [Notification] Wow, client daytime drifted off significantly from server daytime (15,9 mins)
30.3.2024 22:39:27 [Notification] Wow, client daytime drifted off significantly from server daytime (30 mins)
30.3.2024 22:39:27 [Notification] Disconnected by the server ()
30.3.2024 22:39:27 [Notification] Destroying game session, waiting up to 200ms for client threads to exit
30.3.2024 22:39:27 [Notification] Finished fully loading sounds (async)
30.3.2024 22:39:27 [Notification] Exiting current game
30.3.2024 22:39:27 [Notification] ===============================================================
30.3.2024 22:39:27 [Notification] (^_^) No issues captured during startup
30.3.2024 22:39:27 [Notification] ===============================================================
30.3.2024 22:39:27 [Fatal] Game Version: v1.19.5 (Stable)
30.03.2024 22:39:27: Critical error occurred
Loaded Mods: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Vintagestory.Client.NoObf.ClientMain.get_Rand() in VintagestoryLib\Client\ClientMain.cs:line 2926
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2502
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStates(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2450
   at Vintagestory.API.Common.CollectibleObject.AppendPerishableInfoText(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1809
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1652
   at Vintagestory.API.Common.Block.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 2257
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 400
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(ICoreClientAPI capi, ItemStack stack) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 40
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onCreatePagesAsync() in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 84
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 418
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 120
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Crash written to file at "%appData%\Roaming\VintagestoryData\Logs\client-crash.txt"
```

**Comment by KOKEIJN** [comment]
After reinstalling it still does the same thing.

also tested disabling: Loaded Mods: game@1.19.5, creative@1.19.5, survival@1.19.5 
After loading into the game, the complete game is missing, meaning colors, sky, flowers, you can see only all white and the cubes below are question marks/exclamation points and the game crashes by itself in less than five seconds.

But the game warns that these 3 mods are part of the standard game! If they are disabled, the game will not start or there will be some problems in the game.

Also tried the new version 1.19.7 and the problem persists there as well.

**Comment by Craluminum2413** [comment]
Closing due to inactivity
