### ISSUE TITLE
Crash on save load

### ISSUE THREAD

**Issue by misiakpol** [anegostudios/VintageStory-Issues#3780]
### Game Version

v1.19.7

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

When I was playing the save closed with a message that the server is offline. It was apparently caused by a bug because after that I wasn't able anymore to load my save file, I can still play in fresh generated worlds.

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/106669997/2a8e3e2b-1325-4498-a8f1-41a79abdf241)

### Logs

```Log```
Running on 64 bit Windows 10.0.22621.0 with 16347 MB RAM
Game Version: v1.19.7 (Stable)
05.04.2024 10:51:16: Critical error occurred
Loaded Mods: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.Initialize(EntityProperties properties, JsonObject typeAttributes) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 102
   at Vintagestory.API.Common.Entities.EntitySidedProperties.loadBehaviors(Entity entity, EntityProperties properties, IWorldAccessor world) in VintagestoryApi\Common\Entity\EntityProperties.cs:line 363
   at Vintagestory.API.Common.Entities.EntityProperties.Initialize(Entity entity, ICoreAPI api) in VintagestoryApi\Common\Entity\EntityProperties.cs:line 247
   at Vintagestory.API.Common.Entities.Entity.Initialize(EntityProperties properties, ICoreAPI api, Int64 InChunkIndex3d) in VintagestoryApi\Common\Entity\Entity.cs:line 558
   at Vintagestory.API.Common.EntityAgent.Initialize(EntityProperties properties, ICoreAPI api, Int64 InChunkIndex3d) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 122
   at Vintagestory.GameContent.EntityDrifter.Initialize(EntityProperties properties, ICoreAPI api, Int64 InChunkIndex3d) in VSSurvivalMod\Entities\EntityDrifter.cs:line 124
   at Vintagestory.Client.NoObf.ClientSystemEntities.entityFromPacket(Packet_Entity entitypacket, ClientMain game) in VintagestoryLib\Client\Systems\Entities.cs:line 553
   at Vintagestory.Client.NoObf.ClientSystemEntities.createOrUpdateEntityFromPacket(Packet_Entity entitypacket, ClientMain game, Boolean addToLoadQueue) in VintagestoryLib\Client\Systems\Entities.cs:line 515
   at Vintagestory.Client.NoObf.ClientSystemEntities.<>c__DisplayClass8_0.<HandleEntityLoadedPacket>b__0() in VintagestoryLib\Client\Systems\Entities.cs:line 218
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Second Log:
Running on 64 bit Windows 10.0.22621.0 with 16347 MB RAM
Game Version: v1.19.7 (Stable)
05.04.2024 10:51:11: Critical error occurred
Loaded Mods: game@1.19.7, creative@1.19.7, survival@1.19.7
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockEntityMicroBlock.getMajorityMaterial(List`1 voxelCuboids, Int32[] blockIds, ActionBoolReturn`1 filterblockId)
   at Vintagestory.GameContent.BlockEntityMicroBlock.GetMajorityMaterialId(ActionBoolReturn`1 filterblockId) in VSSurvivalMod\Systems\Microblock\BEMicroBlock.cs:line 311
   at Vintagestory.GameContent.BlockMicroBlock.GetRandomColor(ICoreClientAPI capi, BlockPos pos, BlockFacing facing, Int32 rndIndex) in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 634
   at Vintagestory.GameContent.ChunkMapLayer.GenerateChunkImage(Vec2i chunkPos, IMapChunk mc, Int32[]& tintedImage, Boolean colorAccurate) in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 582
   at Vintagestory.GameContent.ChunkMapLayer.OnOffThreadTick(Single dt) in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 322
   at Vintagestory.GameContent.WorldMapManager.<OnLvlFinalize>b__22_0() in VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 206

**Comment by Craluminum2413** [comment]
Send your save with https://wetransfer.com/ for example

**Comment by Craluminum2413** [comment]
Closing due to inactivity
