### ISSUE TITLE
Accessing full oven crash

### ISSUE THREAD

**Issue by Derrekito** [anegostudios/VintageStory-Issues#3782]
### Platform

None

### Modded

None

### SP/MP

None

### Description

Accessing a full oven instantly crashes client. Reproduced on Linux and Windows.

### How to reproduce

1. Access a full oven 

### Logs

```Running on 64 bit Linux (Arch Linux) [Kernel 6.8.2.2] with 15845 MB RAM
Game Version: v1.19.7 (Stable)
4/5/2024 9:00:26AM: Critical error occurred
Loaded Mods: game@1.19.7, creative@1.19.7, survival@1.19.7
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockEntityOven.TryTake(IPlayer byPlayer) in VSSurvivalMod\Systems\Cooking\Clayoven\BEClayOven.cs:line 304
   at Vintagestory.GameContent.BlockEntityOven.OnInteract(IPlayer byPlayer, BlockSelection bs) in VSSurvivalMod\Systems\Cooking\Clayoven\BEClayOven.cs:line 170
   at Vintagestory.GameContent.BlockClayOven.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection bs) in VSSurvivalMod\Block\BlockClayOven.cs:line 126
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 885
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 444
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93```

**Comment by Derrekito** [comment]
Issue occurred after updating to latest version. Breaking the block and placing it back fixed the issue.
