### ISSUE TITLE
Game crash when launching friend session

### ISSUE THREAD

**Issue by EtheRRnoLoL** [anegostudios/VintageStory-Issues#3792]
### Game Version

v1.19.4

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

see for yourself why I can't play with my friends :

### How to reproduce

launch party in 1.19.4

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/166402419/2dd3b824-f354-48b2-b7ab-1e73e892cc55)

### Logs

```Log```

Running on 64 bit Windows 10.0.19045.0 with 16326 MB RAM
Game Version: v1.19.4 (Stable)
08/04/2024 15:04:29: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ShaderAPI.ReloadShaders() in VintagestoryLib\Client\API\ShaderAPI.cs:line 53
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerReady(Packet_Server packet) in VintagestoryLib\Client\Systems\Startup.cs:line 881
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 446
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 440
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by EtheRRnoLoL** [comment]
it happens in 1.19.4 with modded servers
