### ISSUE TITLE
World crashing on load after using the Generate world with same seed menu.

### ISSUE THREAD

**Issue by BurdBruh** [anegostudios/VintageStory-Issues#3793]
### Game Version

v1.19.7 (Stable)

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

World crashing on load after clicking on generate world with same seed, after loading back into save, going back from menu not generating a copy of world. World also became corrupted after this, running in repair mode has seemed to fix save.

### How to reproduce

1.Use the generate world with same seed button to look at game settings of save. (was doing this to check the default range for a pro-pick.)
2.Load back into the original world, without generating a new world from the generate same seed world menu. crash on load immediately. 
3.after couple of retries game stated save was corrupt (Made back-up of corrupted save)
_Extra_: Ran save repair mode, worked and world is at normal function now.

### Logs

Running on 64 bit Windows 10.0.22631.0 with 16310 MB RAM
Game Version: v1.19.7 (Stable)
9/04/2024 12:32:04 AM: Critical error occurred
Loaded Mods: game@1.19.7, creative@1.19.7, survival@1.19.7
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 56
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 200
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 806
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 858
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 730
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 2
==================================
{ TimeGenerated = 9/04/2024 12:31:41 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.7.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x4004
Faulting application start time: 0x0x1da89c1681e7f11
Faulting application path: C:\Users\andre\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\andre\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: eea3fd69-069c-4cac-a321-2ec64bb9ab39
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 9/04/2024 12:31:12 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.7.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x3954
Faulting application start time: 0x0x1da899f795b40e7
Faulting application path: C:\Users\andre\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\andre\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 7b66af34-46d0-4279-9cfa-142e5ea974d9
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Duplicate of #3550

**Comment by BurdBruh** [comment]
Tried to replicate by doing same actions that caused issue to figure out sure if something I did in game caused issue. Was mining using prospecting pick to look for ore, before going into menus. Also have copy of corrupted save if that would help.

**Comment by Craluminum2413** [comment]
I look only at crash report and ignore everything else
