### ISSUE TITLE
Vintage Story Game crashing when loadinging into world. 

### ISSUE THREAD

**Issue by theswampmonkey** [anegostudios/VintageStory-Issues#3794]
### Game Version

v1.19.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Game crashes when i load into world. 

### How to reproduce

Every time i load into the world the game crashes. I cant move or do anything. 

### Logs

Running on 64 bit Windows 10.0.19045.0 with 16347 MB RAM
Game Version: v1.19.4 (Stable)
4/8/2024 5:35:39 PM: Critical error occurred
Loaded Mods: game@1.19.4, creative@1.19.4, survival@1.19.4
System.IO.IOException: Data error (cyclic redundancy check). : 'D:\Vintagestory\assets\survival\sounds\environment\waterwaves.ogg'
   at System.IO.RandomAccess.ReadAtOffset(SafeFileHandle handle, Span`1 buffer, Int64 fileOffset)
   at System.IO.File.ReadAllBytes(String path)
   at Vintagestory.Common.PathOrigin.LoadAsset(IAsset asset) in VintagestoryLib\Common\FileIO\Origins\PathOrigin.cs:line 32
   at Vintagestory.Client.NoObf.AudioMetaData.DoLoad() in VintagestoryLib\Client\ClientPlatform\ClientNative\OggDecoder.cs:line 37
   at Vintagestory.Client.NoObf.AudioMetaData.Load() in VintagestoryLib\Client\ClientPlatform\ClientNative\OggDecoder.cs:line 53
   at Vintagestory.Client.NoObf.ClientPlatformWindows.CreateAudio(SoundParams sound, AudioData data) in VintagestoryLib\Client\ClientPlatform\Audio.cs:line 70
   at Vintagestory.Client.NoObf.ClientMain.LoadSound(SoundParams sound) in VintagestoryLib\Client\Systems\Audio\SoundEngine.cs:line 238
   at Vintagestory.Client.NoObf.SystemPlayerSounds.OnAmbientSoundScan(List`1 newAmbientSounds) in VintagestoryLib\Client\Systems\Audio\AmbientSounds.cs:line 133
   at Vintagestory.Client.NoObf.SystemClientTickingBlocks.CommitScan() in VintagestoryLib\Client\Systems\ClientTickingBlocks.cs:line 278
   at Vintagestory.Client.NoObf.SystemClientTickingBlocks.<OnSeperateThreadGameTick>b__30_0() in VintagestoryLib\Client\Systems\ClientTickingBlocks.cs:line 448
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
Reinstall your game and update to 1.19.7

**Comment by Craluminum2413** [comment]
Closing due to inactivity
