### ISSUE TITLE
Loading to world error, modded game.

### ISSUE THREAD

**Issue by FunkiDori** [anegostudios/VintageStory-Issues#3795]
### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

While creating the world, at the end when "..." appears, the game crashes to the desktop showing this error log.

### How to reproduce

When trying to re-enter the world, the same error appears.

### Screenshots

![vs 1197 screen](https://github.com/anegostudios/VintageStory-Issues/assets/147675274/1da6b6b1-510d-423f-aaba-27ef65a6cbef)

### Logs

Running on 64 bit Windows 10.0.22621.0 with 32702 MB RAM
Game Version: v1.19.7 (Stable)
09.04.2024 21:54:10: Critical error occurred in the following mod: hudclock@3.1.0
Loaded Mods: game@1.19.7, egocaribautomapmarkers@3.1.0, betterfirepit@1.1.4, carryon@1.7.4, hudclock@3.1.0, creative@1.19.7, survival@1.19.7
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.BitmapExternal.bmp'.
   at hudclock.src.TimeDialog.StormDialog.OnDraw(Context ctx, ImageSurface surface, ElementBounds currentBounds)
   at Vintagestory.API.Client.GuiElementCustomDraw.ComposeElements(Context ctxStatic, ImageSurface surfaceStatic) in VintagestoryApi\Client\UI\Elements\Impl\Static\GuiElementCustomDraw.cs:line 33
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 399
   at hudclock.src.TimeDialog.StormDialog.DefineGuiComposer() in D:\development\VintageStoryMods\solution\Mods\hudclock\src\TemporalStorm\StormDialog.cs:line 201
   at hudclock.src.TimeDialog.StormDialog.Build() in D:\development\VintageStoryMods\solution\Mods\hudclock\src\TemporalStorm\StormDialog.cs:line 41
   at hudclock.src.TemporalStorm.StormDialogController..ctor(ICoreClientAPI clientApi, ClockModSettingsController settings) in D:\development\VintageStoryMods\solution\Mods\hudclock\src\TemporalStorm\StormDialogController.cs:line 32
   at hudlock.src.HUDClockMod.PlayerReady(EnumHandling& handling) in D:\development\VintageStoryMods\solution\Mods\hudclock\src\HUDClockMod.cs:line 40
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerIsPlayerReady() in VintagestoryLib\Client\API\ClientEventAPI.cs:line 414
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 316
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 448
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 442
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by FunkiDori** [comment]
Goddamn im blind, mod (hudclock) is causing the error. Huh... Why I saw it in this form on Git but not in the error log form?

**Comment by pingouyn** [comment]
There's a newer version 3.4.0 of Simple HUD Clock for VS 1.19.x that could/should solve your issue.

**Comment by Craluminum2413** [comment]
Crash caused by mod
