### ISSUE TITLE
Server FATAL ERROR

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#3802]
### Game Version

1.19.7

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Server report fatal error than shutdown

### Logs

10.4.2024 23:28:22 [Error] Failed deserializing a chunk. Not in repair mode, will exit.
10.4.2024 23:28:22 [Fatal] Caught unhandled exception in thread 'chunkdbthread'. Shutting down server.
10.4.2024 23:28:22 [Error] Exception: Unconsumed data left in the buffer; this suggests corrupt input
   at ProtoBuf.ProtoReader.CheckFullyConsumed() in C:\Code\pb-net_24\src\protobuf-net\ProtoReader.cs:line 1335
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context) in C:\Code\pb-net_24\src\protobuf-net\Meta\TypeModel.cs:line 599
   at Vintagestory.Server.ServerChunk.FromBytes(Byte[] serializedChunk, ChunkDataPool datapool, IWorldAccessor worldForResolve) in VintagestoryLib\Server\Models\ServerChunk.cs:line 218
   at Vintagestory.Server.ServerSystemSupplyChunks.TryLoadChunkColumn(ChunkColumnLoadRequest chunkRequest) in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 1258
   at Vintagestory.Server.ServerSystemSupplyChunks.loadOrGenerateChunkColumn_OnChunkThread(ChunkColumnLoadRequest chunkRequest, Int32 stage) in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 717
   at Vintagestory.Server.ServerSystemSupplyChunks.tryLoadOrGenerateChunkColumnsInQueue() in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 588
   at Vintagestory.Server.ServerSystemSupplyChunks.OnSeparateThreadTick() in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 438
   at Vintagestory.Server.ServerThread.Update() in VintagestoryLib\Server\ServerThread.cs:line 111
   at Vintagestory.Server.ServerThread.Process() in VintagestoryLib\Server\ServerThread.cs:line 92

**Comment by Craluminum2413** [comment]
Does it happen without mods?

**Comment by DejFidOFF** [comment]
Same results with zero mods loaded
![server_df_fatal](https://github.com/anegostudios/VintageStory-Issues/assets/98642082/44c0c4d8-c7bd-4e1a-a2d1-ad1fc6adedc9)
