### ISSUE TITLE
game fails to join multiplayer server. server is verison 1.19.3 

### ISSUE THREAD

**Issue by Woodstonks** [anegostudios/VintageStory-Issues#3803]
### Game Version

v1.19.3

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

i can't join i'm not sure why

### Logs

Running on 64 bit Windows 10.0.19045.0 with 16331 MB RAM
Game Version: v1.19.3 (Stable)
4/11/2024 6:37:54 PM: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.16, bettertraders@0.0.4, butchering@1.1.0, carpet@1.0.2, chiseltools@1.10.8, Clothez@1.0.0, compass2@3.0.0, craftingtable@0.6.0, driedfirefuels@1.1.1, flourbags@1.0.2, caninae@1.0.8, pantherinae@1.0.9, haybales@1.1.2, HumanSkinTones@0.0.3, instanddrifterdrops@1.1.0, jackofalltraits@1.0.0, lanternpost@1.0.8, mannequinstand@1.0.3, mbpc@1.0.1, MoveLikeKaji@0.0.5, pipeleaf@1.5.0, TA_plainsandvalleys@1.0.5, primitivesurvival@3.4.5, unpfix@1.0.0, roas@1.0.0, dzsalvageplus@1.0.1, sca@1.0.1, sortablestorage@2.2.2, spyglass@0.5.1, ot_SticksFromFirewood@1.1.0, Swordz@1.1.5, Vanilla_PlusWorldGen@1.3.3, visibleore@1.0.1, game@1.19.3, wallpaper@1.0.0, zoombuttonreborn@1.6.0, accessibilitytweaks@3.5.1, alchemy@1.6.25, ancienttools@1.5.12, animalcages@3.0.2, animationmanagerlib@0.6.0, egocaribautomapmarkers@3.1.0, betterfirepit@1.1.4, betterruins@0.3.3, blacksmithenhancements@1.0.4, blocksoverlay@3.2.1, canjewelry@0.2.12, carryon@1.7.4, commonlib@2.3.0, composter@1.1.0, cuniculture@1.0.2, displaycasewall@1.0.3, electricity@0.0.11, expandedfoods@1.6.8, fancyplanters@1.2.0, fieldsofsalt@1.2.1, fishing@1.1.5, flowerfarming@1.0.0, herbarium@1.0.4, hudclock@3.4.0, jopainting@1.4.0, sailboat@1.3.0, justanarrowheadmold@1.0.1, maltiezbows@1.0.3, metalsupports@1.0.3, minerz@0.0.7, moreanimals@1.3.1, nodriftersonloosestones@1.0.0, petai@2.2.1, prospecttogether@1.3.0, rivers@2.5.0, scarecrow@1.4.3, simplecloth@1.0.2, simplestep@1.1.6, steamandpower@1.0.1, stonebakeoven@1.1.3, storageoptions@1.0.2, strspawnchances@0.1.6, trailmod@1.0.7, vinconomy@0.2.4, visibleglass@1.0.0, vhfp@1.1.0, vtpp@1.1.1, creative@1.19.3, vsimgui@0.3.3, survival@1.19.3, vsvillage@0.9.2, wildfarmingrevival@1.1.8, metalrecovery@0.1.19-pre.1, betterruinslootchanges@0.0.3, bullseye@2.5.3, tradercamps@1.1.2, configlib@0.4.2, electricityextensions@0.0.3, em@2.5.0, extraoverlays@1.4.0, feverstonehorses@1.6.0, fsmlib@0.2.9, sleekdoorglass@1.0.0, grasscompost@1.0.0, helvehammerext@1.6.0, morefloors@2.0.0, playercorpse@1.9.0, simplewinddirection@1.0.2, stainedbeams@1.0.0, stonequarry@3.2.1, vanity@1.0.0, wolftaming@2.0.2, maltiezfirearms@0.4.0-pre.8, tailorsdelight@1.3.0
System.Exception: Don't know how to instantiate item of class 'langstrothpartcore' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass) in VintagestoryLib\Common\ClassRegistry.cs:line 274
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType packet, IWorldAccessor world, ClassRegistry registry) in VintagestoryLib\Common\Network\ItemTypeNet.cs:line 195
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(List`1 items, Int32 listSize) in VintagestoryLib\Client\Systems\Startup.cs:line 570
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes() in VintagestoryLib\Client\Systems\Startup.cs:line 388
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in VintagestoryLib\Client\Systems\Startup.cs:line 341
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 120
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries for Vintagestory.exe, the latest 2
==================================
{ TimeGenerated = 4/11/2024 6:31:16 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3996, time stamp: 0xb756c9ff
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process id: 0x2c44
Faulting application start time: 0x01da8c7863de59e1
Faulting application path: C:\Users\August\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 6dace9f8-5035-424b-9616-1f5276aebc41
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 4/11/2024 6:20:21 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3996, time stamp: 0xb756c9ff
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process id: 0x3ab4
Faulting application start time: 0x01da8c770356a05d
Faulting application path: C:\Users\August\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: bd250328-741b-41b4-b2a5-ec9bd6454dc8
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Woodstonks** [comment]
unfortunately the server i'm trying to join is in 1.19.3
