### ISSUE TITLE
Macro Command Causes Crash

### ISSUE THREAD

**Issue by nicksal21** [anegostudios/VintageStory-Issues#3812]
### Game Version

v1.19.7

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

The command `/waypoint addati grain ~0 ~0 ~0 false #080504 TerraPreta` does not fit on one line in the macro editor, causing the command to fail when executed.  Commands don't seem to run properly when they are over one line in length.  Additionally, waypoint names cannot have a space when created with a command.  The presence of mods doesn't seem to be related to the issue (though I probably have far too many).

### How to reproduce

1. Enter `/waypoint addati grain ~0 ~0 ~0 false #080504 TerraPreta` as a macro
2. Try to edit the macro to fit on one line
3. Try to run it two or more times

### Logs

```Log
Running on 64 bit Windows 10.0.19045.0 with 16331 MB RAM
Game Version: v1.19.7 (Stable)
4/14/2024 5:08:37 PM: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.3, chiseltools@1.11.0, claycasting@1.1.5, morecropsfix@1.0.6, floralzonescaperegion@1.0.6, floralzonescaribbeanregion@1.0.3, floralzonescentralaustralianregion@1.0.3, floralzoneseastasiaticregion@1.0.0, geodesandgemstones@1.1.0, geoaddons@1.3.3, hammercrushed@1.0.0, HangingOilLamps@1.0.1, healthiertrees@1.0.0, millwright@1.1.4, natshumanskin@1.0.0, oils@1.1.0, peacockbasses@1.1.2, pipeleaf@1.5.1, primitivesurvival@3.5.1, she1fish@1.2.0, sortablestorage@2.2.3, spyglass@0.5.1, translocatorengineeringredux@1.4.9, volumetricshadingreupdated@0.7.5, game@1.19.7, wlts@1.0.0, alchemy@1.6.28, beehivekiln@1.5.1, betterfirepit@1.1.4, canjewelry@0.2.25, carryon@1.7.4, chickenfeed@1.1.2, clrd@1.0.0, coinage@1.10.1, commonlib@2.3.0, composter@1.1.0, cropseedstage@1.0.1, debarkedlogintofirewood@1.0.0, earlychiseling@1.0.1, expandedfoods@1.6.9, farmlanddropssoil@1.4.0, fishing@1.1.5, flowerfarming@1.1.0, herbarium@1.1.0, hudclock@3.4.0, jopainting@1.4.0, sailboat@1.3.0, knapster@2.9.4, lavoisier@1.3.0, moreanimals@1.3.3, nemi@1.1.0, petai@2.2.3, pigfeed@1.0.4, rivers@2.7.0, simpleconcrete@1.0.1, simpleemotemenu@1.1.0, simplestep@1.1.7, stickemup@1.1.0, stonebakeoven@1.1.3, tablet@0.1.4, terrapretatrade@1.0.0, thecritterpack@0.9.1, vtpp@1.1.1, creative@1.19.7, vsinstruments@1.2.7, survival@1.19.7, wildfarmingrevival@1.1.8, workbenchexpansion@1.8.0, chemistrylib@1.1.5, em@2.5.2, feverstonehorses@1.6.1, gespileslib@1.2.0, morecandles@1.2.0, stonequarry@3.2.1, wildcraftfruit@1.1.1, wildcrafttree@1.1.0, wolftaming@2.1.0, bricklayers@2.5.1, tailorsdelight@1.4.0
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyPress(ICoreClientAPI api, KeyEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 573
   at Vintagestory.API.Client.GuiComposer.OnKeyPress(KeyEvent args) in VintagestoryApi\Client\UI\GuiComposer.cs:line 639
   at Vintagestory.API.Client.GuiDialog.OnKeyPress(KeyEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 464
   at Vintagestory.Client.NoObf.GuiManager.OnKeyPress(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 379
   at Vintagestory.Client.NoObf.ClientMain.OnKeyPress(KeyEvent eventArgs) in VintagestoryLib\Client\ClientMain.cs:line 1819
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyPress(TextInputEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 218
   at OpenTK.Windowing.Desktop.NativeWindow.CharCallback(Window* window, UInt32 codepoint)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 4/12/2024 11:43:18 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.7.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x18d4
Faulting application start time: 0x01da8d4a72365b93
Faulting application path: C:\Users\***\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\***\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: c1bfb4d7-f4c0-4dc7-b87a-2db33216d9ad
Faulting package full name: 
Faulting package-relative application ID:  }

```

**Comment by Craluminum2413** [comment]
Doesn't crash
