### ISSUE TITLE
Crash While Carving Suevite

### ISSUE THREAD

**Issue by DMC273** [anegostudios/VintageStory-Issues#3822]
### Game Version

v1.19.7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I built a tower of Suevite Cobblestone blocks, and began carving it to be more elegant. In the process of carving single (1x1x1) microblocks out of the bottom of my tower, one of the suevite block textures shifted, and shortly after the game shut down.
I used the 8x8x8, 4x4x4, and 2x2x2 carving modes without issue, but not even 20 of the 1x1x1 microblocks in, and the game gave up.

### How to reproduce

1. Make Suevite Cobble Stone
2. Carve until crash

### Logs
```
Running on 64 bit Windows 6.1.7601.0 with 16268 MB RAM
Game Version: v1.19.7 (Stable)
18-Apr-24 6:58:17 PM: Critical error occurred
Loaded Mods: game@1.19.7, creative@1.19.7, survival@1.19.7
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityMicroBlock.GetSounds() in VSSurvivalMod\Systems\Microblock\BEMicroBlock.cs:line 170
   at Vintagestory.GameContent.BlockMicroBlock.GetSounds(IBlockAccessor blockAccessor, BlockPos pos, ItemStack stack) in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 101
   at Vintagestory.API.Common.EntityPlayer.getSoundSourceBlockAt(Cuboidd entityBox, BlockPos tmpPos, Int32 blockLayer, Boolean usecollisionboxes) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 1144
   at Vintagestory.API.Common.EntityPlayer.GetInsideLegsBlockSoundSource(BlockPos tmpPos) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 561
   at Vintagestory.API.Common.EntityPlayer.PlayInsideSound(IPlayer player) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 588
   at Vintagestory.API.Common.EntityPlayer.updateEyeHeight(Single dt) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 448
   at Vintagestory.Client.NoObf.PlayerCamera.OnBeforeRenderFrame3D(Single dt) in VintagestoryLib\Client\Render\PlayerCamera.cs:line 58
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
