### ISSUE TITLE
Crash on startup on CentOS 7

### ISSUE THREAD

**Issue by DilanRona** [anegostudios/VintageStory-Issues#3827]
Running on 64 bit Linux (CentOS Linux 7 (Core)) [Kernel 3.10.0.1160] with 7714 MB RAM
Game Version: v1.19.7 (Stable)
2024/04/20 3:57:42 PM: Critical error occurred
Loaded Mods: 
System.EntryPointNotFoundException: Unable to find an entry point named 'glfwGetMonitorWorkarea' in shared library 'glfw3.dll'.
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwGetMonitorWorkarea(Monitor* monitor, Int32* xpos, Int32* ypos, Int32* width, Int32* height)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.GetMonitorWorkarea(Monitor* monitor, Int32& x, Int32& y, Int32& width, Int32& height)
   at OpenTK.Windowing.Desktop.MonitorInfo..ctor(MonitorHandle handle)
   at OpenTK.Windowing.Desktop.Monitors.GetPrimaryMonitor()
   at VSPlatform.XPlatImpl.GetScreenSize() in XPlatformInterface\PlatformFormsImpl.cs:line 30
   at Vintagestory.Client.NoObf.ClientPlatformWindows..ctor(Logger logger) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 63
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 166
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
========
dotnet output is as follows
.NET SDK:
 Version:   7.0.408
 Commit:    03a0111c2e

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.408/

Host:
  Version:      7.0.18
  Architecture: x64
  Commit:       544c7e6eb3

.NET SDKs installed:
  7.0.408 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.18 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.18 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by Craluminum2413** [comment]
Closing due to inactivity
