### ISSUE TITLE
Crate Parchment Label Crash

### ISSUE THREAD

**Issue by DMC273** [anegostudios/VintageStory-Issues#3845]
### Game Version

v1.19.7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I was converting multiple crates (one by one) from unlabeled, to labeled, and marking their contents with a chunk of malachite (since anything that writes will work), and after the fifth crate, the game started showing a missing texture placeholder for a moment before it would change to the correct item that the crates contained. After the 10th or so, the game just didn't like it anymore and closed itself.

### How to reproduce

1. Put parchment and crate in crafting menu
2. Place crate
3. Fill crate
4. Use malachite on parchment
5. Enjoy the crash.

### Logs
```
Running on 64 bit Windows 6.1.7601.0 with 16268 MB RAM
Game Version: v1.19.7 (Stable)
27-Apr-24 10:42:25 AM: Critical error occurred
Loaded Mods: game@1.19.7, creative@1.19.7, survival@1.19.7
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 434
   at Vintagestory.Client.NoObf.DrawWorldInteractionUtil.ComposeBlockWorldInteractionHelp(WorldInteraction[] wis) in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockInteractionHelp.cs:line 111
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockChanged(ClientMain game, BlockPos pos, Block oldBlock) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 499
   at Vintagestory.Client.NoObf.ClientWorldMap.MarkBlockDirty(BlockPos pos, IPlayer skipPlayer) in VintagestoryLib\Client\ClientWorldMap.cs:line 1258
   at Vintagestory.Common.BlockAccessorRelaxed.ExchangeBlock(Int32 blockId, BlockPos pos) in VintagestoryLib\Common\API\BlockAccessorRelaxed.cs:line 140
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleExchangeBlock(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 141
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 19-Apr-24 4:25:05 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.7.0, time stamp: 0x65310000
Faulting module name: nvoglv64.DLL, version: 30.0.14.7381, time stamp: 0x62cc685e
Exception code: 0x40000015
Fault offset: 0x00000000011fc53f
Faulting process id: 0x29b8
Faulting application start time: 0x01da925590f68889
Faulting application path: E:\My Games\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\system32\nvoglv64.DLL
Report Id: e7d51ead-fe8a-11ee-8762-d0509974828b }
```

**Comment by SpookiBoo** [comment]
This happened to me with chalk labels as well. I found that drawing the label with charcoal fixes it, or at least, I've not had the crash happen with extensive testing of charcoal labeled crates.

**Comment by Craluminum2413** [comment]
Closing due to inactivity
