### ISSUE TITLE
Vanishing Forge

### ISSUE THREAD

**Issue by KollegeX** [anegostudios/VintageStory-Issues#385]
**Game Version:** 1.12.5 Stable
**Platform:** Windows
**Modded:** No 

### Description
I removed a firepit and a forge (from its former position) and placed the forge in the place previously occupied by the firepit. I then built a new firepit on a 3rd unrelated square.

After a day of foraging, when i returned the forge had turned into a firepit.
It could be relevant that the firepit, when i removed it was in the process of cooling down. the forge was untouched.

### How to reproduce
 I have not attempted to reproduce it, though i may later and append this post

**Comment by copygirl** [comment]
I noticed a similar issue. When I place firewood on the ground, pick it up, then place for example a pot or bowl in that spot, for some reason the game renders the firewood from before. If I pick up the item and then place firewood again, it becomes invisible.

**Comment by Angelnoir** [comment]
I reproduced the issue successfully.

### How to reproduce
1. Build a Firepit on position A
2. Lit the Firepit and remove the 3 remaining wood, so that its burning out faster
3. Wait until its burned down
4. Remove the firepit from Position A
5. Place another item like the "Forge" on Position A
6. Move around 32 blocks away from Position A
7. Cut down a tree
8. Return to Position A

The Forge should now render as a Firepit.

I also tried without cutting a tree but couldn't trigger the issue. I should also mention that I reduced my viewing distance to 32 blocks for reproducing it.
I will try to shorten the steps for reproduction.

**Comment by Bloodsaw** [comment]
Discord user "Rizαrd" reported that he encountered the same issue but with the bloomery.

> My bloomery turned into a firepit and after trying to sleep, the game crashed

**Screenshot:**
![image](https://user-images.githubusercontent.com/61588797/75625878-7ef52700-5bc2-11ea-9036-c50f7ad8bc84.png)

**Logs:**
```
Version: v1.12.5 (Stable)01-Mar-20 13:24:51: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityBloomery.EmitParticles()
   at Vintagestory.GameContent.BlockEntityBloomery.OnGameTick(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at _cbodHKZNx5G5B0ajOJRiKOMUi6d._ykWNCOaup5AuVWVrjbcBvBqoivo(Single )
   at _cbodHKZNx5G5B0ajOJRiKOMUi6d._mNh2oavQCEJVrb6jUHjJh1mToWE(Single )
   at _2LdR0X5PHgIsH0Qq61AbDPLAlFo._jHkasPdfycueGbkSaxMFKzSMfh3(Single )
   at _lt8TgSVuBImgzFgAFlSeVzSFsSy._AjNkRnsn39TXAz2S4OVzXdXYu0h(Single )
   at _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   at _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )
-------------------------------
```

**Comment by tyronx** [comment]
Firepits no longer properly unregistered upon removal, fixed in v1.12.6

**Comment by copygirl** [comment]
@tyronx Is there a similar issue with piles of firewood? See [my comment](https://github.com/anegostudios/VintageStory-Issues/issues/385#issuecomment-592332036)

**Comment by tyronx** [comment]
That sounds like a different bug. Piles don't have game ticker listeners. The firepit had 2 which kept ticking after removal.
