### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by AliKat47** [anegostudios/VintageStory-Issues#3850]
### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Running on 64 bit Windows 10.0.22621.0 with 32580 MB RAM
Game Version: v1.19.7 (Stable)
4/27/2024 10:10:45 PM: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.4, decor@1.0.15, fantasycreatures@0.7.1, moredrifterloot@1.5.4, OresAPlenty@3.2.0, primitivesurvival@3.5.3, game@1.19.7, betterruins@0.3.4, electricity@0.0.11, expandedfoods@1.6.9, herbarium@1.1.0, meteoricexpansion@1.2.5, petai@2.2.4, th3dungeon@0.2.1, creative@1.19.7, vsinstruments@1.2.7, vsquest@1.2.0, survival@1.19.7, vsvillage@1.0.0-pre.2, feverstonehorses@1.6.1, wildcraftfruit@1.1.1, wildcrafttree@1.1.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityBed.get_MountPosition() in VSSurvivalMod\BlockEntity\BEBed.cs:line 31
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.TickEntityPhysics(EntityPos pos, EntityControls controls, Single dt) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 228
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.TickEntityPhysicsPre(Entity entity, Single dt) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 216
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.onPhysicsTick(Single deltaTime) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 182
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 119
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

### How to reproduce

In creative mode, day 1, flying around to explore our new map

### Logs

`Running on 64 bit Windows 10.0.22621.0 with 32580 MB RAM
Game Version: v1.19.7 (Stable)
4/27/2024 10:10:45 PM: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.4, decor@1.0.15, fantasycreatures@0.7.1, moredrifterloot@1.5.4, OresAPlenty@3.2.0, primitivesurvival@3.5.3, game@1.19.7, betterruins@0.3.4, electricity@0.0.11, expandedfoods@1.6.9, herbarium@1.1.0, meteoricexpansion@1.2.5, petai@2.2.4, th3dungeon@0.2.1, creative@1.19.7, vsinstruments@1.2.7, vsquest@1.2.0, survival@1.19.7, vsvillage@1.0.0-pre.2, feverstonehorses@1.6.1, wildcraftfruit@1.1.1, wildcrafttree@1.1.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityBed.get_MountPosition() in VSSurvivalMod\BlockEntity\BEBed.cs:line 31
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.TickEntityPhysics(EntityPos pos, EntityControls controls, Single dt) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 228
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.TickEntityPhysicsPre(Entity entity, Single dt) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 216
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.onPhysicsTick(Single deltaTime) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 182
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 119
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by AliKat47** [comment]
And now I can' get back in - game crashes immediately when I try to connect to the server
---------------------new crash report---------------------------
Running on 64 bit Windows 10.0.22621.0 with 32580 MB RAM
Game Version: v1.19.7 (Stable)
4/27/2024 10:16:57 PM: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.4, decor@1.0.15, fantasycreatures@0.7.1, moredrifterloot@1.5.4, OresAPlenty@3.2.0, primitivesurvival@3.5.3, game@1.19.7, betterruins@0.3.4, electricity@0.0.11, expandedfoods@1.6.9, herbarium@1.1.0, meteoricexpansion@1.2.5, petai@2.2.4, th3dungeon@0.2.1, creative@1.19.7, vsinstruments@1.2.7, vsquest@1.2.0, survival@1.19.7, vsvillage@1.0.0-pre.2, feverstonehorses@1.6.1, wildcraftfruit@1.1.1, wildcrafttree@1.1.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityBed.get_MountPosition() in VSSurvivalMod\BlockEntity\BEBed.cs:line 31
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.TickEntityPhysics(EntityPos pos, EntityControls controls, Single dt) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 293
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.TickEntityPhysicsPre(Entity entity, Single dt) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 210
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.onPhysicsTick(Single deltaTime) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 177
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 115
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 200
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 806
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 858
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 730
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 4/27/2024 10:16:32 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.7.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x514c
Faulting application start time: 0x0x1da991a3cee3109
Faulting application path: C:\Users\awkoc\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\awkoc\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 8686931c-a031-43a5-b76b-d85dcfd25147
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by AliKat47** [comment]
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/15140645/client-crash.txt)

**Comment by Craluminum2413** [comment]
Closing due to inactivity
