### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Krosis96** [anegostudios/VintageStory-Issues#3852]
### Game Version

V1.19.7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The game crashed after a sesion of about 20 min, after 2 frozen screens of about 10 secs. Not sure if related but the game consistently gets the image completely frozen while still running (can tell by the game sound) after sesions of more than an hour. The problem just gets solved for a while by reiniciating the game. I usually have to reiniciate the PC. The same happened before the last major update.

### Logs

```Log```
Running on 64 bit Windows 10.0.19045.0 with 7997 MB RAM
Game Version: v1.19.7 (Stable)
28/04/2024 23:38:11: Critical error occurred
Loaded Mods: game@1.19.7, creative@1.19.7, survival@1.19.7
System.OutOfMemoryException: Either the graphics card or the OS ran out of memory! Please close other programs and reduce your view distance to prevent the game from crashing.
   at Vintagestory.Client.NoObf.ClientPlatformWindows.CheckGlErrorAlways(String errmsg) in VintagestoryLib\Client\ClientPlatform\GLImpl.cs:line 75
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Agent00Ming** [comment]
Running out of memory is not really an issue with the game unless there's a memory leak. Try running the game for a while with nothing else open and monitor the memory usage with task manager and see if it grows. Otherwise you might be in a tough spot because 8G of ram is not a lot nowadays with all the chromium bloat (discord = electron app = chromium, etc).

**Comment by Craluminum2413** [comment]
Closing due to inactivity
