### ISSUE TITLE
Crash Report - TextDrawUtil getNextWord Index out of bounds

### ISSUE THREAD

**Issue by sakari119** [anegostudios/VintageStory-Issues#3853]
### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

ill comment on this if i find out why

System.IndexOutOfRangeException: Index was outside the bounds of the array.
Vintagestory.API.Client.TextDrawUtil.getNextWord(String fulltext, EnumLinebreakBehavior linebreakBh) in VintagestoryApi\Client\UI\TextDrawUtil.cs:line 408

### Logs

```Running on 64 bit Windows 10.0.19045.0 with 64663 MB RAM
Game Version: v1.19.7 (Stable)
29/04/2024 9:48:35 PM: Critical error occurred
Loaded Mods: ancientarmory@1.0.0, cavecontent@1.0.1, chiseltools@1.11.2, hqzlights@1.1.1, easysod@0.0.3, emotemenureload@1.0.5, femininity@0.1.3, floralzonescaperegion@1.0.6, floralzonescaribbeanregion@1.0.3, floralzonescentralaustralianregion@1.0.3, floralzoneseastasiaticregion@1.0.0, foundrymod@1.0.0, geoaddons@1.3.3, hideplayername@2.0.6, immersivecorpsedrop@1.0.2, knappingmastery@1.0.1, millwright@1.1.5, mycodiversity@1.0.2, primitivesurvival@3.5.2, rpgitemrarityreborn@1.0.5, rustcreatures@1.3.0, ssab@0.0.1, ssppvv@1.0.5, easytorchlight@1.0.0, game@1.19.7, zoombuttonreborn@1.7.0, AgeOfConfession@2.0.2, animationmanagerlib@0.7.14, beehivekiln@1.5.3, betterfirepit@1.1.4, betterruins@0.3.4, commonlib@2.3.0, cooperativecombat@1.1.1, divisionoflabor@1.0.8, electricity@0.0.11, fixhandbookclutter@1.0.5, grassiergrass@1.0.0, heatretention@1.0.2, herbarium@1.1.0, itemframe@1.0.0, sailboat@1.3.0, justanarrowheadmold@1.0.1, knifemold@1.0.1, mushroomroulette@1.1.0, norottinghides@1.0.0, oneroof@0.10.0, pelaguswinds@1.0.0, petai@2.2.4, claywheel@1.1.1, rockstratavariety@0.0.1, rustboundmagic@1.7.4, starvation@1.0.5, th3dungeon@0.2.1, vanvar@4.0.2, vmetp@1.1.1, creative@1.19.7, vsimgui@1.1.3, vsinstruments@1.2.7, survival@1.19.7, configlib@1.3.9, electricityaddon@0.0.2, feverstonehorses@1.6.1, foxtaming@1.4.0, fsmlib@0.4.5, onestick@1.0.1, playercorpse@1.9.0, stonepiles@1.1.2, stonequarry@3.2.1, wildcraftherb@0.0.0, wildcrafttree@1.1.0, wolftaming@2.1.2, maltiezcrossbows@0.3.4, maltiezfirearms@0.5.2, statushudcont@2.1.1
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.Client.TextDrawUtil.getNextWord(String fulltext, EnumLinebreakBehavior linebreakBh) in VintagestoryApi\Client\UI\TextDrawUtil.cs:line 408
   at Vintagestory.API.Client.TextDrawUtil.Lineize(Context ctx, String text, EnumLinebreakBehavior linebreak, TextFlowPath[] flowPath, Double startOffsetX, Double startY, Double lineHeightMultiplier, Boolean keepLinebreakChar) in VintagestoryApi\Client\UI\TextDrawUtil.cs:line 317
   at Vintagestory.API.Client.GuiElementTextBase.DrawMultilineTextAt(Context ctx, Double posX, Double posY, EnumTextOrientation orientation) in VintagestoryApi\Client\UI\Elements\Impl\Static\GuiElementTextBase.cs:line 58
   at Vintagestory.API.Client.GuiElementDynamicText.<RecomposeText>b__9_0() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementDynamicText.cs:line 71
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 28/04/2024 5:31:04 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.7.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x43c0
Faulting application start time: 0x01da993dedf31c88
Faulting application path: C:\Users\User\AppData\Roaming\Vintagestory_stable\Vintagestory.exe
Faulting module path: C:\Users\User\AppData\Roaming\Vintagestory_stable\Lib\openal32.dll
Report Id: d62bcdb2-c5ae-494a-b73f-fd7f0cfbc6e2
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 28/04/2024 5:30:20 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.7.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x1a2c
Faulting application start time: 0x01da993dd244b16b
Faulting application path: C:\Users\User\AppData\Roaming\Vintagestory_stable\Vintagestory.exe
Faulting module path: C:\Users\User\AppData\Roaming\Vintagestory_stable\Lib\openal32.dll
Report Id: 2063070e-27e4-47a4-8118-ef7750ebdb5f
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 28/04/2024 1:33:04 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.7.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x1c4
Faulting application start time: 0x01da991c85f36a6e
Faulting application path: C:\Users\User\AppData\Roaming\Vintagestory_stable\Vintagestory.exe
Faulting module path: C:\Users\User\AppData\Roaming\Vintagestory_stable\Lib\openal32.dll
Report Id: cd568774-7c27-4b2b-8478-acba191afd99
Faulting package full name: 
Faulting package-relative application ID:  }```

[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/15148672/client-crash.txt)

**Comment by Craluminum2413** [comment]
Most likely caused by some mod

**Comment by Craluminum2413** [comment]
Closing due to inactivity
