### ISSUE TITLE
opened the game and it crashes

### ISSUE THREAD

**Issue by Wolfgang612** [anegostudios/VintageStory-Issues#3854]
### Game Version

v1.19.7

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

I try to open the game and it crashes 

### Screenshots

Running on 64 bit Windows 10.0.19045.0 with 16319 MB RAM
Game Version: v1.19.7 (Stable)
4/30/2024 2:37:58 PM: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: The driver does not appear to support OpenGL
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings) in VintagestoryLib\Client\ClientPlatform\GameWindowNative.cs:line 14
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 281
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

### Logs

```Log```
Game Version: v1.19.7 (Stable)
4/30/2024 2:47:54 PM: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: The driver does not appear to support OpenGL
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings) in VintagestoryLib\Client\ClientPlatform\GameWindowNative.cs:line 14
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 281
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

30.4.2024 14:47:53 [Notification] Client logger started.
30.4.2024 14:47:53 [Notification] Game Version: v1.19.7 (Stable)
30.4.2024 14:47:53 [Notification] Process path: C:\Users\Hofle\AppData\Roaming\Vintagestory\Vintagestory.exe
30.4.2024 14:47:53 [Notification] Operating System: Windows 10.0.19045.0
30.4.2024 14:47:53 [Notification] CPU Cores: 6
30.4.2024 14:47:53 [Notification] Available RAM: 16319 MB
30.4.2024 14:47:54 [Fatal] Game Version: v1.19.7 (Stable)
4/30/2024 2:47:54 PM: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: The driver does not appear to support OpenGL
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings) in VintagestoryLib\Client\ClientPlatform\GameWindowNative.cs:line 14
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 281
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Crash written to file at "C:\Users\Hofle\AppData\Roaming\VintagestoryData\Logs\client-crash.txt"

**Comment by Craluminum2413** [comment]
Update your graphics drivers
