### ISSUE TITLE
1.19.7 Server Freeze Lock with Error Spam from CreatureDiet and BasketTrap

### ISSUE THREAD

**Issue by RogueRaiden** [anegostudios/VintageStory-Issues#3864]
### Game Version

1.19.7

### Platform

None

### Modded

None

### SP/MP

None

### Description

Something about a creature and its diet when attempted to be caught by a basket trap, perhaps not matching up properly or improper diet on an entity.

Yes, there are mods that add CreatureDiets to several creatures.

There should still be an error reported in the console, perhaps with what creature caused the error exactly, and it not lock the server with error spam

### Logs

```
6.5.2024 23:47:53 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.CreatureDiet.Matches(ItemStack itemstack) in VSEssentials\Systems\POIRegistry.cs:line 70
   at Vintagestory.GameContent.BlockEntityBasketTrap.IsSuitableFor(Entity entity, CreatureDiet diet) in VSSurvivalMod\BlockEntity\BEBasketTrap.cs:line 148
   at Vintagestory.GameContent.AiTaskSeekFoodAndEat.ContinueExecute_Patch1(AiTaskSeekFoodAndEat this, Single dt)
   at Vintagestory.GameContent.AiTaskManager.OnGameTick(Single dt) in VSEssentials\Entity\AI\Task\AiTaskManager.cs:line 174
   at Vintagestory.GameContent.EntityBehaviorTaskAI.OnGameTick(Single deltaTime) in VSEssentials\Entity\AI\Task\BehaviorTaskAI.cs:line 114
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\Entity.cs:line 874
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 540
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt) in VintagestoryLib\Server\Systems\World\EntitySimulation.cs:line 330
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt) in VintagestoryLib\Server\Systems\World\EntitySimulation.cs:line 169
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 886
```

**Comment by RogueRaiden** [comment]
sounds similar to this linked issue, except i dont see where it used to spam where in this situation it is spamming hardcore.

like i said above, its very likely a mod issue with the diet not being set correctly, however, it should not be locking the server with error spam.

https://github.com/anegostudios/VintageStory-Issues/issues/3486

**Comment by Craluminum2413** [comment]
Closing due to inactivity
