### ISSUE TITLE
WeatherSimulationSnowAccum crash to "Vintage Story Crash Reporter"

### ISSUE THREAD

**Issue by IBWare** [anegostudios/VintageStory-Issues#3891]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

When traveling in game to a prior traveled position I crash to Vintage Story Crash Report which notes an error relating to WeatherSimulationSnowAccum.

### Logs

Running on 64 bit Windows 10.0.22631.0 with 16319 MB RAM
Game Version: v1.19.8 (Stable)
5/27/2024 3:28:18 PM: Critical error occurred
Loaded Mods: game@1.19.8, carryon@1.7.4, creative@1.19.8, survival@1.19.8
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.UpdateSnowLayer(SnowAccumSnapshot sumsnapshot, Boolean ignoreOldAccum, IServerMapChunk mc, Vec2i chunkPos, IWorldChunk[] chunksCol) in VSEssentials\Systems\Weather\WeatherSimulationSnowAccum.cs:line 502
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.GetSnowUpdate(WeatherSimulationRegion simregion, IServerMapChunk mc, Vec2i chunkPos, IWorldChunk[] chunksCol) in VSEssentials\Systems\Weather\WeatherSimulationSnowAccum.cs:line 496
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.UpdateSnowLayerOffThread(WeatherSimulationRegion simregion, IServerMapChunk mc, Vec2i chunkPos) in VSEssentials\Systems\Weather\WeatherSimulationSnowAccum.cs:line 439
   at Vintagestory.GameContent.WeatherSimulationSnowAccum.onThreadStart() in VSEssentials\Systems\Weather\WeatherSimulationSnowAccum.cs:line 287

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/27/2024 2:48:07 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3527, time stamp: 0x83efbeab
Exception code: 0xe0434352
Fault offset: 0x000000000006543c
Faulting process id: 0x0x2b28
Faulting application start time: 0x0x1dab065cd84bf05
Faulting application path: E:\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: a2f256f6-48d0-444c-941f-5f73f4611f7f
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 5/27/2024 2:42:02 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3527, time stamp: 0x83efbeab
Exception code: 0xe0434352
Fault offset: 0x000000000006543c
Faulting process id: 0x0x3430
Faulting application start time: 0x0x1dab0656f5f82a3
Faulting application path: E:\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: d09271bb-8f89-4a84-b785-cccf1ff85bdc
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 5/27/2024 2:33:15 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3527, time stamp: 0x83efbeab
Exception code: 0xe0434352
Fault offset: 0x000000000006543c
Faulting process id: 0x0x2f30
Faulting application start time: 0x0x1dab0641223db9a
Faulting application path: E:\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 687a01d4-f199-4380-8b04-a0f6bf216e47
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by IBWare** [comment]
I just tried with no mods loaded and the same issue occurred.

**Comment by IBWare** [comment]
Accidently closed and had to reopen the issue.

**Comment by noelle-lavenza** [comment]
Do you use any unusual/nonstandard world generation settings? Do you have a small world file you can upload somewhere that reliably causes the crash?

**Comment by IBWare** [comment]
My world gen settings are out of the box.  I created the world fresh from
1.19.5 and performed the option to update as they were presented via
game load.
 dark adventure lands.vcdbs
<https://drive.google.com/file/d/1bO8tk4JiPoW5c3l7gT9zs04m5vajtEH7/view?usp=drive_web>
Provided is a link to the world file as well as the json file used in
creation of the world.  As a note I truly enjoy the game.

**Comment by Craluminum2413** [comment]
Closing due to inactivity
