### ISSUE TITLE
Crash: Game crashes after loading specific savegame

### ISSUE THREAD

**Issue by Bloodsaw** [anegostudios/VintageStory-Issues#390]
**Game Version:** 1.12.5
**Platform:** Windows 10 64 bit 1909
**Modded:** No

### Description
Exactly what the title says.

### How to reproduce
Just load the savegame and wait about 10-20secs, even without moving or pressing anything the game crashes. 
Is reproducible every single time I'm loading it, but only on my system. 
Tried two different installations without this issue. 

Not quite sure how I broke it, but I tried to replicate the issue of https://github.com/anegostudios/VintageStory-Issues/issues/386#issue-572847042 
Maybe, only maybe, it has something to do with it.

### Logs
```
Running on 64 bit Windows with 0 GB RAM 
Version: v1.12.5 (Stable)28.02.2020 15:13:05: Critical error occurred
System.IO.EndOfStreamException: Über das Ende des Datenstroms hinaus kann nicht gelesen werden.
   bei System.IO.__Error.EndOfFile()
   bei System.IO.MemoryStream.InternalReadInt32()
   bei Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   bei Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntitySpawnPacket(_ao2wb43bENgLDz41hdvNvtazUHu serverpacket)
   bei _cbodHKZNx5G5B0ajOJRiKOMUi6d._BhJwuFi29qoR0AeIVw0bFfSc9Yg(Single )
   bei _2LdR0X5PHgIsH0Qq61AbDPLAlFo._jHkasPdfycueGbkSaxMFKzSMfh3(Single )
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._AjNkRnsn39TXAz2S4OVzXdXYu0h(Single )
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   bei _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart ).
```
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/4270656/client-main.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/4270657/client-debug.txt)

Savegame Download:
https://drive.google.com/file/d/19wjZz0L4umC3fLVU0-3wmaDK8hjS3wKJ/view?usp=sharing

**Comment by guvvo** [comment]
I also am having this issue. johnwilson@770.net.au
My log follows:
Running on 64 bit Windows with 32 GB RAM 
Version: v1.12.5 (Stable)3/03/2020 9:46:56 PM: Critical error occurred
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.MemoryStream.InternalReadInt32()
   at Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.API.Common.EntityPlayer.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.Client.NoObf.ClientSystemEntities.createOrUpdateEntityFromPacket(_8dScwjQY5uofBfFnZ0b1RxQaDb0 entitypacket, _cbodHKZNx5G5B0ajOJRiKOMUi6d game, Boolean addToLoadQueue)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityLoadedPacket(_ao2wb43bENgLDz41hdvNvtazUHu serverpacket)
   at _cbodHKZNx5G5B0ajOJRiKOMUi6d._BhJwuFi29qoR0AeIVw0bFfSc9Yg(Single )
   at _eFf91QQdB7idG1E2ZqAM9ppaVVg._L70FVKtGSJalOIsw6MvDPGFXhpg(Single )
   at _lt8TgSVuBImgzFgAFlSeVzSFsSy._AjNkRnsn39TXAz2S4OVzXdXYu0h(Single )
   at _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   at _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )
-------------------------------

**Comment by copygirl** [comment]
The referenced issues contain other people running into the same issue. Some of them provided world file downloads to look into, as well, if necessary. Making the world saving more robust / redundant in case of a crash or power-outage will be important going forward.

**Comment by kadirstyle** [comment]
Im having the same issues, heres my savegame:

https://we.tl/t-irdp0caYvX

**Comment by tyronx** [comment]
In version 1.12.7 you will be able to load worlds in a repair mode that should theoretically fix the crash issues and afterwards regain the ability to start up the affected world normally again

**Comment by Bloodsaw** [comment]
Since 1.12.7 is released there should be an option to repair your savegame. 
If you edit your savegame (on the right side the little pencil), there is a button "Run in repair mode". Please check if it works. Thank you.

**Comment by Bloodsaw** [comment]
I have tried it with my own savegame (provided above) and can confirm that this worked for my savegame.
Just follow the instructions you see if using the repair mode.
I will close this issue for now, everyone whos not able to repair their savegame with this method should create a new issue with their complete crash log and a dowload link of the affected savegame!

**Comment by copygirl** [comment]
Just want to document a possible variation of this error: #468
