### ISSUE TITLE
Game crashes after playing in updated world

### ISSUE THREAD

**Issue by GMage413** [anegostudios/VintageStory-Issues#3908]
### Game Version

Newest but it happens in an old world updated to newest

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I had mods but turned them off before playing on an old world, I don't remember what version I started on. Now a block is a question mark and I can't open any container, including camp fires, besides chests. Then the game crashes when just walking around or interacting with broken things. Also a door just doesn't exist but still looks like it and blocks me from placing blocks there.

### How to reproduce

I either break a bugged storage vessel or I just existing for too long.

### Screenshots

![2024-06-03_18-47-04](https://github.com/anegostudios/VintageStory-Issues/assets/171634185/8108b84b-f2c3-4902-81fe-c3370eef7916)
![2024-06-03_18-46-08](https://github.com/anegostudios/VintageStory-Issues/assets/171634185/3da7448c-e8a4-4907-9d29-8d63bcc66294)
![2024-06-03_18-46-18](https://github.com/anegostudios/VintageStory-Issues/assets/171634185/ef53c4ee-09b1-45b4-b2e1-11a91a8a4d4d)

### Logs

```Log```
Running on 64 bit Windows 10.0.22621.0 with 64729 MB RAM
Game Version: v1.19.8 (Stable)
6/3/2024 6:51:25 PM: Critical error occurred
Loaded Mods: game@1.19.8, creative@1.19.8, survival@1.19.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockIngotMold.OnEntityCollide(IWorldAccessor world, Entity entity, BlockPos pos, BlockFacing facing, Vec3d collideSpeed, Boolean isImpact) in VSSurvivalMod\Block\BlockIngotMold.cs:line 216
   at Vintagestory.API.MathTools.CollisionTester.ApplyTerrainCollision(Entity entity, EntityPos entitypos, Single dtFac, Vec3d& outposition, Single stepHeight, Single YExtra) in VintagestoryApi\Math\CollisionTester.cs:line 176
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.DisplaceWithBlockCollision(EntityPos pos, EntityControls controls, Single dt) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 345
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.TickEntityPhysics(EntityPos pos, EntityControls controls, Single dt) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 228
   at Vintagestory.GameContent.EntityBehaviorPlayerPhysics.onPhysicsTick(Single deltaTime) in VSEssentials\Entity\Behavior\BehaviorPlayerPhysics.cs:line 108
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 6/2/2024 7:24:47 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x20e10
Faulting application start time: 0x0x1dab54c60eade2d
Faulting application path: C:\Users\User\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\User\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 5fa11bc2-da94-4586-80a3-1730fb24e430
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Most likely caused by mods

**Comment by Craluminum2413** [comment]
@GMage413 Press `Ctrl + F3` and send screenshots for every missing block while directly looking at it

**Comment by GMage413** [comment]
Ok, here they are. I also found a storage vessel that didn't get bugged out for some reason.
![2024-06-04_15-39-27](https://github.com/anegostudios/VintageStory-Issues/assets/171634185/ab9bf765-55dd-4b8d-9131-21eb333f94d2)
![2024-06-04_15-39-34](https://github.com/anegostudios/VintageStory-Issues/assets/171634185/f5401f8e-6059-4405-8602-93056721896e)
![2024-06-04_15-39-44](https://github.com/anegostudios/VintageStory-Issues/assets/171634185/07ea63fb-fb55-4079-99b4-f8a502cc32f4)
![2024-06-04_15-39-45](https://github.com/anegostudios/VintageStory-Issues/assets/171634185/f5c687f5-58d9-461e-8401-b71b2a4eb2ca)
![2024-06-04_15-39-47](https://github.com/anegostudios/VintageStory-Issues/assets/171634185/236a6ba0-03a1-466b-ba03-e1ce8f21b3f6)
![2024-06-04_15-39-53](https://github.com/anegostudios/VintageStory-Issues/assets/171634185/c95f1ba5-4bcf-4c87-80e8-5cfa8bd26370)
![2024-06-04_15-40-20](https://github.com/anegostudios/VintageStory-Issues/assets/171634185/ab2ed2a1-59f7-44cd-b794-f607b332edb7)
![2024-06-04_15-38-30](https://github.com/anegostudios/VintageStory-Issues/assets/171634185/d56e63ae-6d7a-4391-814c-f46a31b5c859)
![2024-06-04_15-38-38](https://github.com/anegostudios/VintageStory-Issues/assets/171634185/5c39280e-6759-4711-af4e-d83fd723871c)
![2024-06-04_15-38-40](https://github.com/anegostudios/VintageStory-Issues/assets/171634185/9055eb24-f8df-4767-bb72-bbff26130fd6)
![2024-06-04_15-38-43](https://github.com/anegostudios/VintageStory-Issues/assets/171634185/38edf5fa-7af9-4480-bc87-89c8426b2732)
![2024-06-04_15-38-44](https://github.com/anegostudios/VintageStory-Issues/assets/171634185/9e82d047-e104-417e-9bf3-95dc1c2ceead)
![2024-06-04_15-39-04](https://github.com/anegostudios/VintageStory-Issues/assets/171634185/55f8fe64-48d9-465f-b3c7-62873e3746f5)

**Comment by Craluminum2413** [comment]
Could you send a list of mods that you had for this world?

**Comment by Craluminum2413** [comment]
Closing due to inactivity
