### ISSUE TITLE
Labeled chests don't let you write "Miscellaneous Materials" on them.

### ISSUE THREAD

**Issue by ModarTheGreat** [anegostudios/VintageStory-Issues#3910]
### Game Version

v1.19.7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### How to reproduce

1. Place a labeled chest.
2. Set text size to 28.
3. Try to write "Miscellaneous Materials" on a chest.
4. Parts of the text are completely erased (in this particular example, the "e" letter from "Miscellaneous")

After tinkering with it for a bit I managed to crash my game, but I couldn't find a reliable way to reproduce it. I'm including my crash log, though.

### Screenshots

![screencap5](https://github.com/anegostudios/VintageStory-Issues/assets/171681294/13dbb9e3-15ab-487d-8142-69a3571c0247)

### Logs

Game Version: v1.19.7 (Stable)
04.06.2024 11:49:05: Critical error occurred
Loaded Mods: game@1.19.7, creative@1.19.7, survival@1.19.7
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyPress(ICoreClientAPI api, KeyEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 573
   at Vintagestory.API.Client.GuiComposer.OnKeyPress(KeyEvent args) in VintagestoryApi\Client\UI\GuiComposer.cs:line 639
   at Vintagestory.API.Client.GuiDialog.OnKeyPress(KeyEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 464
   at Vintagestory.Client.NoObf.GuiManager.OnKeyPress(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 379
   at Vintagestory.Client.NoObf.ClientMain.OnKeyPress(KeyEvent eventArgs) in VintagestoryLib\Client\ClientMain.cs:line 1819
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyPress(TextInputEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 218
   at OpenTK.Windowing.Desktop.NativeWindow.CharCallback(Window* window, UInt32 codepoint)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
Reproduced in 1.20

**Comment by maltiez2** [comment]
Addressed in MR1320
