### ISSUE TITLE
SERVER CRASH AFTER START

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#3914]
### Game Version

1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Server did not start and crash

### Logs

5.6.2024 06:05:12 [Error] Exception: SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Vintagestory.Common.Database.SQLiteDbConnectionv2.GetChunk(UInt64 position, String tablename) in VintagestoryLib\Common\FileIO\Database\SQLiteDbConnectionv2.cs:line 223
   at Vintagestory.Server.ServerSystemSupplyChunks.TryLoadMapRegion(Int32 regionX, Int32 regionZ) in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 1320
   at Vintagestory.Server.ServerSystemSupplyChunks.GetOrCreateMapRegion(Int32 chunkX, Int32 chunkZ, ITreeAttribute chunkGenParams) in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 1054
   at Vintagestory.Server.ServerSystemSupplyChunks.GetOrCreateMapRegionEnsureNeighbours(Int32 chunkX, Int32 chunkZ, ITreeAttribute chunkGenParams) in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 1007
   at Vintagestory.Server.ServerSystemSupplyChunks.GetOrCreateMapChunk(ChunkColumnLoadRequest chunkRequest, Boolean forceCreate) in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 1119
   at Vintagestory.Server.ServerSystemSupplyChunks.loadOrGenerateChunkColumn_OnChunkThread(ChunkColumnLoadRequest chunkRequest, Int32 stage) in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 717
   at Vintagestory.Server.ServerSystemSupplyChunks.loadChunkAreaBlocking(Int32 chunkX1, Int32 chunkZ1, Int32 chunkX2, Int32 chunkZ2, Boolean isStartupLoad, ITreeAttribute chunkGenParams) in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 1673
   at Vintagestory.Server.ServerSystemSupplyChunks.OnSeparateThreadTick() in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 386
   at Vintagestory.Server.ServerThread.Update() in VintagestoryLib\Server\ServerThread.cs:line 123
   at Vintagestory.Server.ServerThread.Process() in VintagestoryLib\Server\ServerThread.cs:line 53
5.6.2024 06:05:16 [Notification] Server stop requested, begin shutdown sequence. Stop reason: Exception during Process
5.6.2024 06:05:16 [Notification] Server ticking has been suspended
5.6.2024 06:05:16 [Notification] Entering runphase Shutdown

**Comment by DejFidOFF** [comment]
5.6.2024 06:32:46 [Event] It begins...
5.6.2024 06:32:46 [Event] It senses...
5.6.2024 06:35:10 [Event] Database integrity check failed. Attempt basic repair procedure (via VACUUM), this might take minutes to hours depending on the size of the save game...
5.6.2024 06:37:01 [Event] Unable to repair :(
5.6.2024 06:37:01 [Event] Something went awry...please check the program logs... (Exception thrown by server during startup or process)
5.6.2024 06:37:01 [Event] Alone again...
5.6.2024 06:37:01 [Event] Time to rest.

**Comment by Craluminum2413** [comment]
What mods are installed?

**Comment by DejFidOFF** [comment]
Tah happened even mods are not installed.

**Comment by DejFidOFF** [comment]
Game version: 1.19.8
Mods:
  Better Crates @ 1.7.1 | Universal
  chiseltools @ 1.12.0 | Universal
  Colored Eggs @ 2.0.0 | Universal
  Extra Chests @ 1.8.0 | Universal
  Larger Crock @ 1.0.2 | Universal
  Millwright @ 1.1.5 | Universal
  Primitive Survival @ 3.5.5 | Universal
  RP Voice Chat @ 2.3.9 | Universal
  Shelfish @ 1.2.1 | Server
  Temporal gears stack @ 1.0.0 | Universal
  Translocator Engineering Redux @ 1.5.1 | Universal
  Essentials @ 1.19.8 | Universal
  Alchemy @ 1.6.32 | Universal
  Better Firepit @ 1.1.4 | Universal
  CANMarket @ 0.3.32 | Universal
  Carry On @ 1.7.4 | Universal
  CommonLib @ 2.3.7 | Universal
  Composter @ 1.1.0 | Universal
  Electricity @ 0.0.11 | Universal
  Farmland Drops Soil @ 1.4.0 | Universal
  From Golden Combs @ 1.4.30 | Universal
  Server Leaderboards @ 1.1.2 | Universal
  Medieval Expansion @ 3.13.1 | Universal
  More Plaster @ 1.0.2 | Universal
  Nat's Achievements @ 1.1.0 | Universal
  Pet AI @ 2.2.4 | Universal
  PlayerList @ 1.7.4 | Universal
  Sleep Vote @ 1.0.7 | Universal
  Stone Bake Oven @ 1.1.3 | Universal
  Terra Preta Trade @ 1.0.0 | Server
  Creative Mode @ 1.19.8 | Universal
  Survival Mode @ 1.19.8 | Universal
  WebCartographer @ 0.5.5 | Server
  Wood Barrels @ 1.1.0 | Universal
  Workbench Expansion @ 1.8.0 | Universal
  XLib @ 0.8.3 | Universal
  Cats @ 2.0.2 | Universal
  Cave Beacons @ 1.0.8 | Universal
  Trader Camps @ 1.1.4 | Universal
  ElectricityAddon @ 0.0.2 | Universal
  Electricity Extensions @ 0.0.6 | Universal
  Expanded Matter @ 2.6.0 | Universal
  Player Corpse @ 1.10.1-rc.1 | Universal
  Teleportation Network @ 1.14.3 | Universal
  Th3Essentials @ 2.8.2 | Server
  Wolf taming @ 2.1.2 | Universal
  XSkills @ 0.8.5 | Universal

**Comment by Craluminum2413** [comment]
Closing due to inactivity
