### ISSUE TITLE
Game Crashed on Multiplayer Server

### ISSUE THREAD

**Issue by thekrazykitten** [anegostudios/VintageStory-Issues#3917]
### Platform

None

### Modded

None

### SP/MP

None

### Description

I was exploring on a multiplayer server and then I crashed. I don't know what happened necessarily, but I previously had issues with my client failing to sync blocks with the server, causing null block ids to appear

### Logs

Running on 64 bit Windows 10.0.22631.0 with 8023 MB RAM
Game Version: v1.19.8 (Stable)
6/6/2024 10:47:16 AM: Critical error occurred
Loaded Mods: game@1.19.8, creative@1.19.8, survival@1.19.8
System.IO.InvalidDataException: size was -72, should be 0
   at Vintagestory.Common.Compression.Decompress(Byte[] dataCompressed, Int32[][]& output, Func`1 createNewSlice) in VintagestoryLib\Common\Convert\Compression.cs:line 239
   at Vintagestory.Common.ChunkDataLayer.DecompressSeparate(Byte[] dataCompressed, Byte[] paletteCompressed) in VintagestoryLib\Common\Model\ChunkDataLayer.cs:line 770
   at Vintagestory.Common.ChunkData.DecompressFrom(Byte[] blocksCompressed, Byte[] lightCompressed, Byte[] lightPaletteCompressed, Byte[] fluidsCompressed, Int32 chunkdataVersion) in VintagestoryLib\Common\Model\ChunkData.cs:line 349
   at Vintagestory.Common.WorldChunk.unpackNoLock() in VintagestoryLib\Common\Datastructures\WorldChunk.cs:line 287
   at Vintagestory.Common.WorldChunk.UnpackAndReadBlock(Int32 index, Int32 layer) in VintagestoryLib\Common\Datastructures\WorldChunk.cs:line 223
   at Vintagestory.GameContent.ChunkMapLayer.GenerateChunkImage(Vec2i chunkPos, IMapChunk mc, Int32[]& tintedImage, Boolean colorAccurate) in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 493
   at Vintagestory.GameContent.ChunkMapLayer.OnOffThreadTick(Single dt) in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 344
   at Vintagestory.GameContent.WorldMapManager.<OnLvlFinalize>b__22_0()

**Comment by Craluminum2413** [comment]
Closing due to inactivity
