### ISSUE TITLE
Game crash when looting drifter

### ISSUE THREAD

**Issue by Featheredbat** [anegostudios/VintageStory-Issues#3928]
### Game Version

1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Looted 2 flax from a nightmare drifter during a temporal storm and crashed as soon as shift-clicking it into inventory

### How to reproduce

Not sure

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32708 MB RAM
Game Version: v1.19.8 (Stable)
6/13/2024 12:37:54 AM: Critical error occurred
Loaded Mods: game@1.19.8, creative@1.19.8, survival@1.19.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorHarvestable.<OnInteract>b__32_0() in VSEssentials\Entity\Behavior\BehaviorHarvestable.cs:line 333
   at Vintagestory.API.Client.GuiDialog.TryClose() in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 310
   at Vintagestory.GameContent.GuiDialogCreatureContents.TryClose() in VSEssentials\Gui\GuiDialogCreatureContents.cs:line 128
   at Vintagestory.GameContent.GuiDialogCreatureContents.<OnFinalizeFrame>b__18_0() in VSEssentials\Gui\GuiDialogCreatureContents.cs:line 122
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
Closing due to inactivity
