### ISSUE TITLE
Smelting Perish-able items with an output that doesn't perish fails with a NRE

### ISSUE THREAD

**Issue by usagirei** [anegostudios/VintageStory-Issues#3933]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

None

### Description

When smelting an item with a perish transition, and its output from a smelt operation doesn't have a perish transition, the game will try to recalculate the transition period of the output stack without checking if it has one, causing a null reference exception.

Code-wise, it's missing a null-check on smeltedState, in addition to the null-check on the input stack state before it (see screenshot)

### How to reproduce

See https://mods.vintagestory.at/show/mod/13084#cmt-32638

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/12700106/ea7d6a0c-8410-4987-9e36-55dd04068d6a)

### Logs

```
[Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.CollectibleObject.DoSmelt(IWorldAccessor world, ISlotProvider cookingSlotsProvider, ItemSlot inputSlot, ItemSlot outputSlot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2340
   at Vintagestory.GameContent.BlockEntityFirepit.smeltItems() in VSSurvivalMod\BlockEntity\Firepit\BEFirepit.cs:line 565
   at Vintagestory.GameContent.BlockEntityFirepit.OnBurnTick(Single dt) in VSSurvivalMod\BlockEntity\Firepit\BEFirepit.cs:line 293
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27```

**Comment by Guimoute** [comment]
It would help if you gave a few examples of perishable items that turn into non-perishable ones. None come to my mind.

**Comment by usagirei** [comment]
The one example i ran into, was converting willow leaves or wood spurge from wildcraft trees into bio-char (or EM plant-ash), as described here
https://mods.vintagestory.at/show/mod/13084#cmt-32638

But it can be triggered with just wildcraft trees and superfuel resumed, by putting some willow leaves (which rots) into a fire pit to transform it into bio-char (which doesn't rot)
