### ISSUE TITLE
have no idea what is crashing it 

### ISSUE THREAD

**Issue by Deathpupper** [anegostudios/VintageStory-Issues#3937]
### Platform

Windows

### Modded

Modded

### SP/MP

None

### Description

I have a mod pack i am building and i cant find what mod is make the crash keep happening 

### How to reproduce

start the game as a new game and see if it will lunch to the game 

### Logs

```Log```Running on 64 bit Windows 10.0.19045.0 with 32700 MB RAM
Game Version: v1.19.8 (Stable)
6/20/2024 10:54:34 PM: Critical error occurred in the following mod: configlib@1.2.0
Loaded Mods: aculinaryartillery@1.1.4, ancientarmory@1.0.0, chiseltools@1.10.7, decor@1.0.15, hqzlights@1.1.1, driedfirefuels@1.1.1, fancysky@1.0.6, fantasycreatures@0.7.1, caninae@1.0.10, machairodontinae@1.0.3, hackedlocusts@1.0.0, HangingOilLamps@1.0.1, indappledgroves@0.5.0-rc.2, instanddrifterdrops@1.1.0, juicyores@1.0.0, millwright@1.1.5, nightwatcher@2.1.0, OresAPlenty@3.2.0, pipeleaf@1.5.0, primitivesurvival@3.4.9, qptech@1.15.2, spyglass@0.5.1, Vanilla_PlusWorldGen@1.3.5, viescraftmachines@2.3.1, vintageengineering@0.1.4, game@1.19.8, accessibilitytweaks@3.4.1, ancienttools@1.5.18, animationmanagerlib@0.7.2, beartrap@1.0.5, betterfirepit@1.1.4, betterjonasdevices@1.1.0, betterruins@0.3.5, blacksmithenhancements@1.0.5, butchering@1.5.4, canjewelry@0.2.18, carryon@1.7.4, commonlib@2.3.7, decoclock@0.9.3, divisionoflabor@1.0.8, electricity@0.0.11, expandedfoods@1.6.9, fancyplanters@1.2.0, fromgoldencombs@1.4.31, hangingbaskets@1.1.0, herbarium@1.1.0, immersivewoodchopping@0.7.1, jopainting@1.4.0, sailboat@1.3.0, lavoisier@1.3.0, medievalexpansion@3.13.1, neverwinter@1.5.0, Spear-Expantion-by-Kanahaku@0.1.2, petai@2.2.4, postsandbeams@1.3.2, resmeltableslight@1.0.0, rustyshell@0.0.11, scarecrow@1.4.3, somethinginthewater@1.2.4, stonerailings@1.2.2, storageoptions@1.0.2, th3dungeon@0.2.1, usefulstuff17@1.3.2, creative@1.19.8, vsimgui@1.1.0, survival@1.19.8, vsvillage@1.0.0-pre.8, woodenfortifications@0.0.4, awearablelight@1.1.1, bullseye-continued@2.5.8, cats@2.0.1, chemistrylib@1.1.5, configlib@1.2.0, constructionsupport@0.1.2, electricityextensions@0.0.3, em@2.5.1, feverstonewilds@1.5.0-rc.2, fsmlib@0.4.1, glassmaking@1.4.0, koboldplayermodelport@1.2.8, morecandles@1.2.0, playercorpse@1.9.0, simplewinddirection@1.0.2, stonequarry@3.2.1, vanity@2.1.2, wildcrafttree@1.1.0, wolftaming@2.1.0, bricklayers@2.5.1, kosfire@1.1.3, kos-goldamalgam@1.0.0, kosphotography@1.4.1, maltiezcrossbows@0.3.11, maltiezfirearms@0.5.4, ropebridgescompatibility@1.0.0, tailorsdelight@1.3.1
System.UnauthorizedAccessException: Access to the path 'C:\Users\Dick Kick'em\AppData\Roaming\VintagestoryData\ModConfig' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at ConfigLib.Config.ReadConfigFile(String defaultConfig) in D:\Projects\VintageStory\configlib\configlib\source\Config\Config.cs:line 312
   at ConfigLib.Config.ParseJson(JsonObject json, Dictionary`2& settings, SortedDictionary`2& configBlocks, String& defaultConfig, String domain) in D:\Projects\VintageStory\configlib\configlib\source\Config\Config.cs:line 284
   at ConfigLib.Config..ctor(ICoreAPI api, String domain, JsonObject json, String file, Dictionary`2 serverSideSettings) in D:\Projects\VintageStory\configlib\configlib\source\Config\Config.cs:line 99
   at ConfigLib.ConfigRegistry.FromBytes(IWorldAccessor resolver, Int32 quantity, Byte[] data) in D:\Projects\VintageStory\configlib\configlib\source\ConfigLibModSystem.cs:line 299
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step11() in VintagestoryLib\Client\Systems\Startup.cs:line 850
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/20/2024 9:16:18 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x583c
Faulting application start time: 0x01dac390c5237f4f
Faulting application path: G:\Games\Vintagestory\Vintagestory.exe
Faulting module path: G:\Games\Vintagestory\Lib\openal32.dll
Report Id: c603bf1d-23f9-4645-8311-9b13d27bab55
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 6/20/2024 9:05:16 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x2dfc
Faulting application start time: 0x01dac38f6cecba62
Faulting application path: G:\Games\Vintagestory\Vintagestory.exe
Faulting module path: G:\Games\Vintagestory\Lib\openal32.dll
Report Id: 4b71a469-04aa-420c-afb1-f277672dbdcd
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 6/20/2024 3:00:03 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x4004
Faulting application start time: 0x01dac35c041264c0
Faulting application path: G:\Games\Vintagestory\Vintagestory.exe
Faulting module path: G:\Games\Vintagestory\Lib\openal32.dll
Report Id: 47a9922a-4fbc-4b47-a3c4-eba623f66238
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Caused by configlib mod
