### ISSUE TITLE
Two mods requiring two version of dependency

### ISSUE THREAD

**Issue by KermAtMeBro** [anegostudios/VintageStory-Issues#3941]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Maltiez's Crossbow, and Firearms, both seem to require two different versions of fsmlib and configlib
I have both versions installed, I can run one of two mods, but not both

### How to reproduce

Install both 'firearms' and 'crossbows' by Maltiez, install dependencies

### Logs

```Log```
Client-main.txt
23.6.2024 12:26:49 [Warning] Multiple mods share the mod ID 'configlib' ('configlib_0.4.2.zip', 'configlib_1.2.0.zip'). Will only load the highest version one - v1.2.0.
23.6.2024 12:26:49 [Warning] Multiple mods share the mod ID 'fsmlib' ('fsmlib_0.2.15.zip', 'fsmlib_0.4.1.zip'). Will only load the highest version one - v0.4.1.

23.6.2024 12:28:28 [Error] [maltiezcrossbows] Could not resolve some dependencies:
23.6.2024 12:28:28 [Error] [maltiezcrossbows]     fsmlib@0.4.1 - Missing
23.6.2024 12:28:28 [Error] [maltiezcrossbows]     configlib@1.2.0 - Missing
23.6.2024 12:28:28 [Error] [maltiezfirearms] Could not resolve some dependencies:
23.6.2024 12:28:28 [Error] [maltiezfirearms]     fsmlib@0.2.15 - Missing
23.6.2024 12:28:28 [Error] [maltiezfirearms]     configlib@0.4.2 - Missing

client-crash.txt
Game Version: v1.19.8 (Stable)
6/23/2024 12:24:46 PM: Critical error occurred in the following mod: configlib@1.2.0
Loaded Mods: aculinaryartillery@1.1.5, ArmorRework@1.0.3, betterruins@0.2.1, Bluesky@1.0.0, landformoverhaul@0.0.1, diagonalfences@0.0.1, inft1@, natshumanskin@1.0.0, primitivesurvival@3.5.5, game@1.19.8, animationmanagerlib@0.7.2, bedspawnv2@1.2.0, blacksmithenhancements@1.0.5, decayingcreatures@0.0.2, evenjugincrements@1.0.0, expandedfoods@1.6.9, levelup@1.2.1, creative@1.19.8, vsimgui@1.1.0, survival@1.19.8, configlib@1.2.0, fsmlib@0.4.1, maltiezcrossbows@0.3.11, maltiezfirearms@0.5.4
System.UnauthorizedAccessException: Access to the path 'C:\Users\Sean\AppData\Roaming\VintagestoryData\ModConfig' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at ConfigLib.Config.ReadConfigFile(String defaultConfig) in D:\Projects\VintageStory\configlib\configlib\source\Config\Config.cs:line 312
   at ConfigLib.Config.ParseJson(JsonObject json, Dictionary`2& settings, SortedDictionary`2& configBlocks, String& defaultConfig, String domain) in D:\Projects\VintageStory\configlib\configlib\source\Config\Config.cs:line 284
   at ConfigLib.Config..ctor(ICoreAPI api, String domain, JsonObject json, String file, Dictionary`2 serverSideSettings) in D:\Projects\VintageStory\configlib\configlib\source\Config\Config.cs:line 99
   at ConfigLib.ConfigRegistry.FromBytes(IWorldAccessor resolver, Int32 quantity, Byte[] data) in D:\Projects\VintageStory\configlib\configlib\source\ConfigLibModSystem.cs:line 299
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step11() in VintagestoryLib\Client\Systems\Startup.cs:line 850
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
This is caused by mod, install the latest version and it will be fine

**Comment by KermAtMeBro** [comment]
> This is caused by mod, install only the latest version of mods and it will be fine

Mods are both up to date
![image](https://github.com/anegostudios/VintageStory-Issues/assets/173628313/2c278303-4b17-4e95-af89-e2d0b47b064b)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/173628313/0aa69286-5a82-4119-a0e7-08b1ecf5dd94)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/173628313/24a0a2b5-5510-4406-a93a-37b08491f7f6)

**Comment by Craluminum2413** [comment]
@KermAtMeBro You have two versions of fsmlib, use only latest

**Comment by KermAtMeBro** [comment]
> @KermAtMeBro You have two versions of fsmlib and configlib, use only latest

Ah, my bad, before I read client-main, I was trying to find the problem-mod, I thought I tried using just the old/just the new versions of those dependencies, guess I only did it with the older versions
