### ISSUE TITLE
Game Crashes before launch

### ISSUE THREAD

**Issue by Shurlockbones** [anegostudios/VintageStory-Issues#3946]
### Platform

None

### Modded

None

### SP/MP

None

### Description

**I am getting this below error. I've deleted the MODS I wanted to use, and this did not fix the problem. I also made sure my antivirus was disabled. I should note I have C++ as well.**

Running on 64 bit Windows 10.0.22631.0 with 32485 MB RAM
Game Version: v1.19.8 (Stable)
6/28/2024 3:55:05 PM: Critical error occurred
Loaded Mods: 
System.Exception: Referenced library not found: Mods\VSCreativeMod.dll
   at Vintagestory.Common.ModCompilationContext..ctor() in VintagestoryLib\Common\API\ModCompilationContext.cs:line 62
   at Vintagestory.Common.ModLoader..ctor(ICoreAPI api, EnumAppSide side, ILogger logger, IEnumerable`1 modSearchPaths, Boolean traceLog) in VintagestoryLib\Common\API\ModLoader.cs:line 27
   at Vintagestory.Common.ModLoader..ctor(ILogger logger, EnumAppSide side, IEnumerable`1 modSearchPaths, Boolean traceLog) in VintagestoryLib\Common\API\ModLoader.cs:line 131
   at Vintagestory.Client.ScreenManager.loadMods() in VintagestoryLib\Client\ScreenManager.cs:line 515
   at Vintagestory.Client.ScreenManager.<DoGameInitStage4>b__56_0() in VintagestoryLib\Client\ScreenManager.cs:line 386
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 120
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

### How to reproduce

Game crashes. I don't think this is possible.

### Screenshots

![Screenshot 2024-06-28 162337](https://github.com/anegostudios/VintageStory-Issues/assets/174153812/c2f29af2-5aff-4b30-9b8a-8a9d561cd189)

### Logs

```Log```

**Comment by Shurlockbones** [comment]
Game crashes before it launches and provides this error.

**Comment by Shurlockbones** [comment]
I found the fix. Thanks. I delelted some files on accedent in the mods folder.
