### ISSUE TITLE
Game crash after run /tp to coordinance

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#3954]
### Game Version

1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### How to reproduce

removing large area 1500x1500 then perform /tp to some coordinates

mods: Primitive Survival & Wildfarming revival 

### Logs

3.7.2024 09:48:07 [Fatal] Game Version: v1.19.8 (Stable)
03.07.2024 9:48:07: Critical error occurred
Loaded Mods: primitivesurvival@3.5.7, game@1.19.8, hudclock@3.4.0, creative@1.19.8, survival@1.19.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ClientChunkData.EmptyAndReuseArrays(List`1 datas) in VintagestoryLib\Client\Model\ClientChunkData.cs:line 197
   at Vintagestory.Common.ChunkDataPool.FreeArraysAndReset(ChunkData cdata) in VintagestoryLib\Common\Datastructures\ChunkDataPool.cs:line 89
   at Vintagestory.Client.NoObf.SystemUnloadChunks.HandleChunkUnload(Packet_Server packet) in VintagestoryLib\Client\Systems\UnloadChunks.cs:line 87
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Crash written to file at "C:\Users\DejFidOFF\AppData\Roaming\VintagestoryData\Logs\client-crash.txt"

3.7.2024 09:48:35 [Notification] Exiting game now. Server running=True. Exit reason: Game crashed
3.7.2024 09:48:41 [Notification] Destroying game session, waiting up to 200ms for client threads to exit
3.7.2024 09:48:47 [Warning] OpenAL Error during stop of sound game:sounds/effect/rift.ogg: IllegalCommand
3.7.2024 09:48:47 [Warning] OpenAL Error during disposestop of sound game:sounds/effect/rift.ogg: IllegalCommand
3.7.2024 09:48:47 [Warning] OpenAL Error during dispose of sound game:sounds/effect/rift.ogg: IllegalCommand
3.7.2024 09:48:47 [Warning] OpenAL Error during stop of sound game:sounds/effect/rift.ogg: IllegalCommand
3.7.2024 09:48:47 [Warning] OpenAL Error during disposestop of sound game:sounds/effect/rift.ogg: IllegalCommand
3.7.2024 09:48:47 [Warning] OpenAL Error during dispose of sound game:sounds/effect/rift.ogg: IllegalCommand
3.7.2024 09:48:47 [Warning] OpenAL Error during stop of sound game:sounds/effect/rift.ogg: IllegalCommand
3.7.2024 09:48:47 [Warning] OpenAL Error during disposestop of sound game:sounds/effect/rift.ogg: IllegalCommand
3.7.2024 09:48:47 [Warning] OpenAL Error during dispose of sound game:sounds/effect/rift.ogg: IllegalCommand
3.7.2024 09:48:47 [Warning] OpenAL Error during stop of sound game:sounds/effect/rift.ogg: IllegalCommand
3.7.2024 09:48:47 [Warning] OpenAL Error during disposestop of sound game:sounds/effect/rift.ogg: IllegalCommand
3.7.2024 09:48:47 [Warning] OpenAL Error during dispose of sound game:sounds/effect/rift.ogg: IllegalCommand
3.7.2024 09:48:47 [Fatal] Caught unhandled exception in thread 'tesselateterrain'. Exiting game.
3.7.2024 09:48:47 [Error] Exception: Exception thrown when trying to tesselate chunk 713/0/671. Details see inner exception.
   at Vintagestory.Client.NoObf.ChunkTesselator.BeginProcessChunk(Int32 chunkX, Int32 chunkY, Int32 chunkZ, ClientChunk chunk, Boolean skipChunkCenter) in VintagestoryLib\Client\Render\Tesselation\ChunkTesselator.cs:line 325
   at Vintagestory.Client.NoObf.ChunkTesselator.NowProcessChunk(Int32 chunkX, Int32 chunkY, Int32 chunkZ, TesselatedChunk tessChunk, Boolean skipChunkCenter) in VintagestoryLib\Client\Render\Tesselation\ChunkTesselator.cs:line 413
   at Vintagestory.Client.NoObf.ChunkTesselatorManager.TesselateChunk(Int32 chunkX, Int32 chunkY, Int32 chunkZ, Boolean priority, Boolean skipChunkCenter, Boolean& requeue) in VintagestoryLib\Client\Systems\ChunkTesselatorManager.cs:line 380
   at Vintagestory.Client.NoObf.ChunkTesselatorManager.OnSeperateThreadGameTick(Single dt) in VintagestoryLib\Client\Systems\ChunkTesselatorManager.cs:line 242
   at Vintagestory.Client.NoObf.ClientThread.Update() in VintagestoryLib\Client\ClientThread.cs:line 75
   at Vintagestory.Client.NoObf.ClientThread.Process() in VintagestoryLib\Client\ClientThread.cs:line 61
3.7.2024 09:48:48 [Notification] Stopping single player server
3.7.2024 09:48:48 [Warning] OpenAL Error during stop of sound game:sounds/environment/wind.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during disposestop of sound game:sounds/environment/wind.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during dispose of sound game:sounds/environment/wind.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during stop of sound game:sounds/environment/underwater.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during disposestop of sound game:sounds/environment/underwater.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during dispose of sound game:sounds/environment/underwater.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during stop of sound game:sounds/weather/tracks/verylowtremble.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during disposestop of sound game:sounds/weather/tracks/verylowtremble.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during dispose of sound game:sounds/weather/tracks/verylowtremble.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during stop of sound game:sounds/weather/tracks/hail.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during disposestop of sound game:sounds/weather/tracks/hail.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during dispose of sound game:sounds/weather/tracks/hail.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during stop of sound game:sounds/weather/tracks/rain-leafless.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during disposestop of sound game:sounds/weather/tracks/rain-leafless.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during dispose of sound game:sounds/weather/tracks/rain-leafless.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during stop of sound game:sounds/weather/tracks/rain-leafy.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during disposestop of sound game:sounds/weather/tracks/rain-leafy.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during dispose of sound game:sounds/weather/tracks/rain-leafy.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during stop of sound game:sounds/weather/wind-leafy.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during disposestop of sound game:sounds/weather/wind-leafy.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during dispose of sound game:sounds/weather/wind-leafy.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during stop of sound game:sounds/weather/wind-leafless.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during disposestop of sound game:sounds/weather/wind-leafless.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during dispose of sound game:sounds/weather/wind-leafless.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during stop of sound game:sounds/raft-moving.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during disposestop of sound game:sounds/raft-moving.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during dispose of sound game:sounds/raft-moving.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during stop of sound game:sounds/raft-idle.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during disposestop of sound game:sounds/raft-idle.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during dispose of sound game:sounds/raft-idle.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during stop of sound game:sounds/effect/tempstab-drain.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during disposestop of sound game:sounds/effect/tempstab-drain.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during dispose of sound game:sounds/effect/tempstab-drain.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during stop of sound game:sounds/effect/tempstab-low.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during disposestop of sound game:sounds/effect/tempstab-low.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during dispose of sound game:sounds/effect/tempstab-low.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during stop of sound game:sounds/effect/tempstab-verylow.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during disposestop of sound game:sounds/effect/tempstab-verylow.ogg: IllegalCommand
3.7.2024 09:48:48 [Warning] OpenAL Error during dispose of sound game:sounds/effect/tempstab-verylow.ogg: IllegalCommand
3.7.2024 09:48:48 [Notification] Exiting current game to main menu, reason: window close event

**Comment by Craluminum2413** [comment]
Have you tried without mods?

**Comment by DejFidOFF** [comment]
I guess it´s not because mods. When perform deleting area 1500x3x1500 and do not wait few time after server replyied - it is done, than /tp crash the game. When wait 2 or more minutes, than everything is ok.
