### ISSUE TITLE
Game crashes whenever I type A in my inventory. Have been fiddling around with my mods but I'm not sure what is causing it

### ISSUE THREAD

**Issue by ok134** [anegostudios/VintageStory-Issues#3955]
### Game Version

v1.19.8 (Stable)

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I'm not sure why but my game crashes when I type A trying to search my inventory.  I've been trying to figure out which mods cause it but have not been able to deduce it

### How to reproduce

1. download the same mods
2. open inventory in creative mode
3. type A into the search bar
4. game crashes

### Logs

Running on 64 bit Windows 10.0.19045.0 with 16259 MB RAM
Game Version: v1.19.8 (Stable)
4/07/2024 2:56:43 am: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.5, decor@1.1.1, fieldsofgold@2.1.6, floralzonesneozeylandicregion@1.0.3, dinornithidae@0.6.0, hideandfabric@1.3.0, millwright@1.1.5, newzealandfrogs@1.1.1, TA_plainsandvalleys@1.0.5, primitivesurvival@3.5.7, smokychimneys@1.0.0, game@1.19.8, animationmanagerlib@0.8.8, butchering@1.6.1, decoclock@0.9.3, expandedfoods@1.6.9, fromgoldencombs@1.4.32, herbarium@1.2.0, kevinsfurniture@1.2.0, nobells@1.0.0, nodrifters@1.0.0, nolocusts@1.0.0, oneroof@0.11.3, sailboat@1.3.1, stepup@1.2.0, creative@1.19.8, vsimgui@1.1.5, survival@1.19.8, configlib@1.3.13, fsmlib@0.4.5, wildcraftfruit@1.2.1, wildcraftherb@0.0.1, maltiezfirearms@0.5.4, statushudcont@2.1.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.FilterItemsBySearchText(String text, Dictionary`2 searchCache, Dictionary`2 searchCacheNames) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 557
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnTextChanged(String text) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 421
   at Vintagestory.API.Client.GuiElementEditableTextBase.TextChanged() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 328
   at Vintagestory.API.Client.GuiElementEditableTextBase.LoadValue(List`1 newLines) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 292
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyPress(ICoreClientAPI api, KeyEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 594
   at Vintagestory.API.Client.GuiComposer.OnKeyPress(KeyEvent args) in VintagestoryApi\Client\UI\GuiComposer.cs:line 634
   at Vintagestory.API.Client.GuiDialog.OnKeyPress(KeyEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 458
   at Vintagestory.Client.NoObf.GuiManager.OnKeyPress(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 382
   at Vintagestory.Client.NoObf.ClientMain.OnKeyPress(KeyEvent eventArgs) in VintagestoryLib\Client\ClientMain.cs:line 1816
   at Vintagestory.Client.GuiScreenRunningGame.OnKeyPress(KeyEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 320
   at Vintagestory.Client.ScreenManager.OnKeyPress(KeyEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 871
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyPress(TextInputEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 220
   at OpenTK.Windowing.Desktop.NativeWindow.OnTextInput(TextInputEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.CharCallback(Window* window, UInt32 codepoint)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
Try without mods

**Comment by ok134** [comment]
I am trying, but do you have any idea which mod could be causing this? Or somewhere to direct me to find out? I can't find anything conclusive from searching here/ 
Thanks so much for your quick response :)

**Comment by Craluminum2413** [comment]
Too many mods I don't know

**Comment by Craluminum2413** [comment]
Closing due to inactivity
