### ISSUE TITLE
RANDOM SERVER CRASH

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#3956]
### Game Version

1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Logs

4.7.2024 14:44:06 [Fatal] Caught unhandled exception in thread 'CompressChunks'. Shutting down server.
4.7.2024 14:44:06 [Error] Exception: Likely code error! Compressing light mismatch: paletteCount 12, databits 0
   at Vintagestory.Common.ChunkDataLayer.CompressSeparate(Byte[]& paletteCompressed, Int32[] arrayStatic, Int32 chunkdataVersion) in VintagestoryLib\Common\Model\ChunkDataLayer.cs:line 750
   at Vintagestory.Common.ChunkData.CompressInto(Byte[]& blocksCompressed, Byte[]& lightCompressed, Byte[]& lightPaletteCompressed, Byte[]& fluidsCompressed, Int32 chunkdataVersion) in VintagestoryLib\Common\Model\ChunkData.cs:line 321
   at Vintagestory.Common.WorldChunk.Pack() in VintagestoryLib\Common\Datastructures\WorldChunk.cs:line 117
   at Vintagestory.Server.ServerSystemCompressChunks.OnSeparateThreadTick() in VintagestoryLib\Server\Systems\World\CompressThread\CompressChunks.cs:line 183
   at Vintagestory.Server.ServerThread.Update() in VintagestoryLib\Server\ServerThread.cs:line 111
   at Vintagestory.Server.ServerThread.Process() in VintagestoryLib\Server\ServerThread.cs:line 92

**Comment by Craluminum2413** [comment]
Closing due to inactivity
