### ISSUE TITLE
Random Crash with Chunk Map Layer

### ISSUE THREAD

**Issue by Lithios6608** [anegostudios/VintageStory-Issues#3959]
### Game Version

1.19.8(s)

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

When my wife or I walk into the chunk the game crashes with a critical error. Does not matter if sp/mp, anytime that chunk is stepped into the game crashes with the below exception. Have tried to load game in repair mode as well, it still crashes when that chunk is moved into.

### How to reproduce

walk into the chunk.

### Screenshots

N/A

### Logs

Running on 64 bit Windows 10.0.19045.0 with 65306 MB RAM
Game Version: v1.19.8 (Stable)
7/7/2024 5:35:54 PM: Critical error occurred
Loaded Mods: game@1.19.8, creative@1.19.8, survival@1.19.8
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.ChunkMapLayer.GenerateChunkImage(Vec2i chunkPos, IMapChunk mc, Int32[]& tintedImage, Boolean colorAccurate) in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 493
   at Vintagestory.GameContent.ChunkMapLayer.OnOffThreadTick(Single dt) in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 344
   at Vintagestory.GameContent.WorldMapManager.<OnLvlFinalize>b__22_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

*****REPAIR MODE REPORT*****
Running on 64 bit Windows 10.0.19045.0 with 65306 MB RAM
Game Version: v1.19.8 (Stable)
7/7/2024 5:47:21 PM: Critical error occurred
Loaded Mods: game@1.19.8, creative@1.19.8, survival@1.19.8
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.ChunkMapLayer.GenerateChunkImage(Vec2i chunkPos, IMapChunk mc, Int32[]& tintedImage, Boolean colorAccurate) in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 493
   at Vintagestory.GameContent.ChunkMapLayer.OnOffThreadTick(Single dt) in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 344
   at Vintagestory.GameContent.WorldMapManager.<OnLvlFinalize>b__22_0()

**Comment by Craluminum2413** [comment]
Closing due to inactivity
