### ISSUE TITLE
Crash upon game launch

### ISSUE THREAD

**Issue by TwisterCoyote** [anegostudios/VintageStory-Issues#3960]
### Game Version

1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Crash upon game launch. Heard some items dropping upon game loading but crashed immediately. I had been using one mod, NeutralAnimals, which should not have had any impact on anything aside from animals being immediately aggro. Crash persisted even after mod was disabled. Log is from when the mod was disabled.

### How to reproduce

launch game

### Logs

```Running on 64 bit Windows 10.0.19045.0 with 31967 MB RAM
Game Version: v1.19.8 (Stable)
7/7/2024 7:03:59 PM: Critical error occurred
Loaded Mods: game@1.19.8, creative@1.19.8, survival@1.19.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 56
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 200
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 806
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 858
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 730
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 2
==================================
{ TimeGenerated = 7/7/2024 7:03:35 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x25b0
Faulting application start time: 0x01dad0ca3ad9ccfb
Faulting application path: C:\Users\Twister\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Twister\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: db5b7895-886c-4b38-8c9e-c1a0ed76778e
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 7/7/2024 7:03:14 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x376c
Faulting application start time: 0x01dad0ca20bbbac1
Faulting application path: C:\Users\Twister\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Twister\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 048a64ba-e9d1-450c-8860-755fc00b663a
Faulting package full name: 
Faulting package-relative application ID:  }``

**Comment by SamDeNies** [comment]
I have also experienced this issue.  My game crashed while mining brown coal in chert.  When I try to load the game again I receive the top error.  I am also running 1.19.8, but on Arch Linux (flatpak).

I am able to load other worlds successfully.

`29.7.2024 20:39:45 [Notification] ===============================================================
29.7.2024 20:39:45 [Notification] (^_^) No issues captured during startup
29.7.2024 20:39:45 [Notification] ===============================================================
29.7.2024 20:39:45 [Error] Erroring EntityItem tick: please report this as a bug!
29.7.2024 20:39:45 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\Entity.cs:line 874
   at Vintagestory.API.Common.EntityItem.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityItem.cs:line 275
29.7.2024 20:39:45 [Fatal] Game Version: v1.19.8 (Stable)
7/29/2024 8:39:45 PM: Critical error occurred
Loaded Mods: game@1.19.8, creative@1.19.8, survival@1.19.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Crash written to file at "/home/XXXXXX/.var/app/at.vintagestory.VintageStory/config/VintagestoryData/Logs/client-crash.txt"

29.7.2024 20:39:46 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
29.7.2024 20:40:03 [Notification] Finished fully loading sounds (async)`

**Comment by SamDeNies** [comment]
The next day, this save loaded properly without error.

**Comment by TwisterCoyote** [comment]
I can confirm, after reading SamDeNeis' posts I tried relaunching the game and the world loaded. I had been cutting an oak tree and  many logs fell on the ground upon loading, This is not where I remember being when I had logged out; I had been waiting for a temporal storm to hit in my house but I am grateful the save game is restored.

**Comment by TwisterCoyote** [comment]
I had tried to use VS' built in recovery tool so perhaps this is why this happened, however, the game would not load at the time even after using the recovery tool

**Comment by TwisterCoyote** [comment]
I have tried to take a screenshot several times but each time I take one all I get is the loading menu 
![Uploading Screenshot (40).png…]()

**Comment by Craluminum2413** [comment]
Closing due to inactivity
