### ISSUE TITLE
crashing when clicking any block in handbook to inspect

### ISSUE THREAD

**Issue by drakogarnus** [anegostudios/VintageStory-Issues#3963]
### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

not sure why im crashing can someone help me find the issue here? my first time modding this game it runs fine but not sure whats causing this

### Logs

Running on 64 bit Windows 10.0.22631.0 with 49080 MB RAM
Game Version: v1.19.8 (Stable)
7/8/2024 2:48:04 PM: Critical error occurred
Loaded Mods: abandonedkingdom@0.0.4, ancientarmory@1.0.1, butcheringfix@1.0.0, buzzybees@1.0.3, cavecontent@1.0.1, compass2@3.0.0, samsdungeonsremastered@1.0.0, eldritchmonsters@2.6.0, fancysky@1.1.6, geodesandgemstones@1.1.1, hideandfabric@1.3.0, justmoreruins@0.9.8, moremeat@1.2.0, mysticalmetals@1.0.1, OBS@0.0.1, plantmat@1.7.2, preservationmod@1.0.0, primitivesurvival@3.5.7, sca@1.0.1, spidersilk@1.2.2, locustmod@2.3.6, game@1.19.8, wildcrafttrees@1.2.4, alchemy@1.6.34, ancienttools@1.5.18, flags@0.30.0, electricity@0.0.11, liquidcontainers@1.2.0, meteoricexpansion@1.2.5, morepiles@1.5.0, norottinghides@1.0.0, Spear-Expantion-by-Kanahaku@0.1.3, oregolems2@0.1.2, petai@2.2.6, claywheel@1.1.1, rivers@3.1.0, simplecloth@1.0.2, somethinginthewater@1.2.4, th3dungeon@0.2.1, creative@1.19.8, survival@1.19.8, cats@2.0.3, electricityaddon@0.0.2, feverstonewilds@1.5.0-rc.2, treetapping@1.0.0, wolftaming@2.1.3
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.addAlloyedFromInfo(ICoreClientAPI capi, ActionConsumable`1 openDetailPageFor, ItemStack stack, List`1 components, Single marginTop, Boolean haveText) in VSSurvivalMod\Systems\Handbook\CollectibleBehaviorHandbookTextAndExtraInfo.cs:line 413
   at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.GetHandbookInfo(ItemSlot inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\CollectibleBehaviorHandbookTextAndExtraInfo.cs:line 58
   at Vintagestory.GameContent.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 117
   at Vintagestory.GameContent.GuiHandbookItemStackPage.ComposePage(GuiComposer detailViewGui, ElementBounds textBounds, ItemStack[] allstacks, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 111
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onComposePage(GuiHandbookPage page, GuiComposer detailViewGui, ElementBounds textBounds, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 97
   at Vintagestory.GameContent.GuiDialogHandbook.initDetailGui() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 258
   at Vintagestory.GameContent.GuiDialogHandbook.onLeftClickListElement(Int32 index) in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 349
   at Vintagestory.GameContent.GuiElementFlatList.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VSSurvivalMod\Systems\Handbook\Gui\GuiElementFlatList.cs:line 93
   at Vintagestory.GameContent.GuiElementFlatList.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VSSurvivalMod\Systems\Handbook\Gui\GuiElementFlatList.cs:line 172
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 449
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 584
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 415
   at Vintagestory.Client.NoObf.ClientMain.UpdateMouseButtonState(EnumMouseButton button, Boolean down) in VintagestoryLib\Client\ClientMain.cs:line 1919
   at Vintagestory.Client.SystemHotkeys.OnPrimaryMouseButton(KeyCombination mb) in VintagestoryLib\Client\Systems\Player\Hotkeys.cs:line 50
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean isGlobal, Boolean fallBack, Boolean keyup) in VintagestoryLib\Client\HotkeyManager.cs:line 422
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean keyUp) in VintagestoryLib\Client\HotkeyManager.cs:line 392
   at Vintagestory.Client.HotkeyManager.OnMouseButton(ClientMain game, EnumMouseButton button, Int32 modifiers, Boolean buttonDown) in VintagestoryLib\Client\HotkeyManager.cs:line 574
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUpRaw(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1949
   at Vintagestory.Client.GuiScreenRunningGame.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 349
   at Vintagestory.Client.ScreenManager.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 890
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 211
   at OpenTK.Windowing.Desktop.NativeWindow.OnMouseUp(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 7/8/2024 2:37:09 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x3354
Faulting application start time: 0x0x1dad17e8da45899
Faulting application path: C:\Users\darko\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\darko\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 24e069b0-62c4-4336-bbf8-097fb1e94e9e
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by drakogarnus** [comment]
sorry kinda new to posting on github! not sure if i posted the log right or not x.x

**Comment by Craluminum2413** [comment]
Does it happen without any mods installed?

**Comment by Craluminum2413** [comment]
Closing due to inactivity
