### ISSUE TITLE
Possibly corrupted world, "Unable to load savegame and no write access, likely already opened elsewhere"

### ISSUE THREAD

**Issue by notmothman** [anegostudios/VintageStory-Issues#3964]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

My world randomly crashed and stopped working after 100hours, I tried running in repair mode but after almost an hour nothing happened.

### How to reproduce

1. Try to open world
2. Game automatically crashes and closes out of launcher
3. When I reopen it says "Unable to load savegame and no write access, likely already opened elsewhere"

### Logs

Running on 64 bit Windows 10.0.22631.0 with 16011 MB RAM
Game Version: v1.19.8 (Stable)
7/8/2024 7:24:29 PM: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.4, instanddrifterdrops@1.1.0, juicyores@1.0.0, mannequinstand@1.0.3, moreicons@1.1.0, moreclay@1.0.2, MoreTorchHolders@1.0.0, palisademod@1.1.0, primitivesurvival@3.5.5, roas@1.0.0, she1fish@1.2.1, smokychimneys@1.0.0, sortablestorage@2.2.5, stackables@2.0.5, tprunes@1.1.0, usefuldrifterloot@1.1.0, game@1.19.8, zoombuttonreborn@1.8.0, animalcages@3.0.2, beehivekiln@1.6.1, betterjonasdevices@1.1.0, betterruins@0.3.5, blacksmithenhancements@1.0.5, canbeignited@1.1.0, carryon@1.7.4, chickenSit@2.0.1, commonlib@2.3.7, displaycasewall@1.0.3, expandedfoods@1.6.9, fancyplanters@1.2.0, flintchisel@1.0.2, grassiergrass@1.0.0, hudclock@3.4.0, immersivewoodchopping@0.7.2, petai@2.2.4, claywheel@1.1.1, prospecttogether@1.3.0, scythemold@1.0.1, simplestep@1.1.7, stepup@1.2.0, stickemup@1.1.0, stickscrafting@1.0.16, creative@1.19.8, vsimgui@1.1.4, vsquest@1.2.0, survival@1.19.8, vsvillage@1.0.5, cats@2.0.2, configlib@1.3.13, extraoverlays@1.4.0, feverstonewilds@1.5.0-rc.2, helvehammerext@1.6.0, shellpan@1.0.0, stonequarry@3.2.1, wolftaming@2.1.2, xinvtweaks@1.6.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 56
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 200
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 806
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 858
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 730
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 2
==================================
{ TimeGenerated = 7/7/2024 8:47:11 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x4384
Faulting application start time: 0x0x1dac7573d4ccc81
Faulting application path: C:\Users\Laury\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Laury\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: e397b76a-56c0-44c5-a152-6d35cf35efa1
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 5/29/2024 7:33:30 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007fff3caf6948
Faulting process id: 0x0x23308
Faulting application start time: 0x0x1dab16ce62d4067
Faulting application path: C:\Users\Laury\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: unknown
Report Id: 6a6c7a19-b98b-47dd-991b-3d0eebabf638
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Does it happen without any mods?

**Comment by Craluminum2413** [comment]
Closing due to inactivity
