### ISSUE TITLE
Game crashed upon selecting item

### ISSUE THREAD

**Issue by ChimeraMusic** [anegostudios/VintageStory-Issues#3966]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

I was underwater. I switched to an item by spinning my mouse wheel and it landed on an item. Then I got kicked from the server. Upon relogging I get kicked and get the same crash log listed below.
I have no idea which item it could have been that I switched to.

### How to reproduce

Not possible

### Logs

```Log```

Running on 64 bit Windows 10.0.19045.0 with 32700 MB RAM
Game Version: v1.19.8 (Stable)
10-7-2024 21:16:24: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.5, ancientarmory@1.0.1, attributer@1.0.5, driftertweak@1.0.0, hideandfabric@1.3.0, primitivesurvival@3.5.7, rpgitemrarity@1.0.4, saltandsands@1.0.1, swordz@1.1.8, Vanilla_PlusWorldGen@1.3.5, game@1.19.8, accessibilitytweaks@3.7.1, alchemy@1.6.34, betteritemflags@0.1.0, betterruins@0.3.5, commonlib@2.5.0-rc.2, expandedfoods@1.6.9, fromgoldencombs@1.4.32, spawnersapi@1.0.7, th3dungeon@0.2.1, creative@1.19.8, vsquest@1.2.0, survival@1.19.8, vsvillage@1.0.5, xlib@0.8.5-pre.1, battletowers@1.0.1, em@2.6.3, gardenerz@0.1.1, playercorpse@1.10.1-rc.1, simplevillages@1.0.1, vsvillageviking@1.0.0, xskills@0.8.7, bricklayers@2.5.5
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Config.TranslationService.KeyWithDomain(String key, String domain) in VintagestoryApi\Localization\TranslationService.cs:line 546
   at Vintagestory.API.Config.TranslationService.HasTranslation(String key, Boolean findWildcarded, Boolean logErrors) in VintagestoryApi\Localization\TranslationService.cs:line 477
   at Vintagestory.API.Config.Lang.Get(String key, Object[] args) in VintagestoryApi\Localization\Lang.cs:line 173
   at Vintagestory.Client.NoObf.DrawWorldInteractionUtil.drawHelp(Context ctx, ImageSurface surface, ElementBounds currentBounds, ItemStack[] stacks, Double lineheight, WorldInteraction wi) in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockInteractionHelp.cs:line 198
   at Vintagestory.Client.NoObf.DrawWorldInteractionUtil.<>c__DisplayClass11_1.<ComposeBlockWorldInteractionHelp>b__1(Context ctx, ImageSurface surface, ElementBounds bounds) in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockInteractionHelp.cs:line 95
   at Vintagestory.API.Client.GuiElementCustomDraw.ComposeElements(Context ctxStatic, ImageSurface surfaceStatic) in VintagestoryApi\Client\UI\Elements\Impl\Static\GuiElementCustomDraw.cs:line 33
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 399
   at Vintagestory.Client.NoObf.DrawWorldInteractionUtil.ComposeBlockWorldInteractionHelp(WorldInteraction[] wis) in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockInteractionHelp.cs:line 109
   at Vintagestory.Client.NoObf.HudHotbar.RecomposeActiveSlotHoverText(Int32 newSlotIndex) in VintagestoryLib\Client\Systems\Gui\Huds\HudHotbar.cs:line 533
   at Vintagestory.Client.NoObf.HudHotbar.<>c__DisplayClass42_0.<OnActiveSlotChanged>b__0() in VintagestoryLib\Client\Systems\Gui\Huds\HudHotbar.cs:line 465
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
Try without mods

**Comment by ChimeraMusic** [comment]
> Try without mods

How can I try without mods, I am locked out of my server. If I head back in I have to download the mods again as the server uses them. Is there a way I can do this anyway? Can I remove the mods and launch the server on localhost without them?

**Comment by Craluminum2413** [comment]
I assume it is mod problem then
