### ISSUE TITLE
Crash When Sleeping

### ISSUE THREAD

**Issue by KoRv117** [anegostudios/VintageStory-Issues#3969]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Crash has happened a couple times when sleeping, started happening after installing the XSkills mod and the XLib mod, uninstalled them both but the crash is still happening

### Logs

```Game Version: v1.19.8 (Stable)
7/12/2024 7:49:45 PM: Critical error occurred
Loaded Mods: bettertraders@0.0.7, HangingOilLamps@1.0.1, primitivesurvival@3.5.7, game@1.19.8, wildcraft@1.6.6, betterruins@0.3.5, carryon@1.7.4, commonlib@2.5.0-rc.2, hudclock@3.4.0, increasedstepheight@1.2.0, meteoricexpansion@1.2.5, petai@2.2.6, rivers@3.1.0, rustboundmagic@1.9.74, trailmod@1.0.8, creative@1.19.8, survival@1.19.8, betterruinslootchanges@0.0.3, tradercamps@1.1.4, feverstonewilds@1.5.0-rc.2, playercorpse@1.10.1-rc.1, stonequarry@3.3.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.FastParticlePool.Kill(ParticleBase elem) in VintagestoryLib\Client\Systems\Render\Particle\IParticlePool.cs:line 79
   at Vintagestory.Client.NoObf.ParticlePoolQuads.OnNewFrame(Single dt, Vec3d cameraPos) in VintagestoryLib\Client\Systems\Render\Particle\ParticlePoolQuads.cs:line 272
   at Vintagestory.Client.NoObf.SystemRenderParticles.Render(Int32 poolindex, Single dt) in VintagestoryLib\Client\Systems\Render\Particle\RenderParticles.cs:line 193
   at Vintagestory.Client.NoObf.SystemRenderParticles.OnRenderFrame3DOIT(Single deltaTime) in VintagestoryLib\Client\Systems\Render\Particle\RenderParticles.cs:line 186
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93```

**Comment by Craluminum2413** [comment]
Does it happen without any mods?

**Comment by KoRv117** [comment]
not that ive experienced no

**Comment by Craluminum2413** [comment]
Closing due to inactivity
