### ISSUE TITLE
crash when change item in quick eq to chiseled block

### ISSUE THREAD

**Issue by vrona32** [anegostudios/VintageStory-Issues#3970]
Crash appears when I change from chisel to chiseled chalk block in eq

```
Running on 64 bit Windows 10.0.22631.0 with 49077 MB RAM
Game Version: v1.19.8 (Stable)
13.07.2024 16:24:40: Critical error occurred
Loaded Mods: game@1.19.8, creative@1.19.8, survival@1.19.8
System.Exception: GL_INVALID_VALUE error generated. Invalid texture format.
   at Vintagestory.Client.NoObf.ClientPlatformWindows.DebugCallback(DebugSource source, DebugType type, Int32 id, DebugSeverity severity, Int32 length, IntPtr message, IntPtr userParam) in VintagestoryLib\Client\ClientPlatform\GLFramebuffer.cs:line 1270
   at Vintagestory.Client.NoObf.ClientPlatformWindows.LoadOrUpdateCairoTexture(ImageSurface surface, Boolean linearMag, LoadedTexture& intoTexture) in VintagestoryLib\Client\ClientPlatform\GLImpl.cs:line 315
   at Vintagestory.API.Client.GuiElementHoverText.Recompose() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementHoverText.cs:line 136
   at Vintagestory.Client.NoObf.HudHotbar.RecomposeActiveSlotHoverText(Int32 newSlotIndex) in VintagestoryLib\Client\Systems\Gui\Huds\HudHotbar.cs:line 526
   at Vintagestory.Client.NoObf.HudHotbar.<>c__DisplayClass42_0.<OnActiveSlotChanged>b__0() in VintagestoryLib\Client\Systems\Gui\Huds\HudHotbar.cs:line 465
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 13.07.2024 16:21:48, Site = , Source = Application Error, Message = Nazwa aplikacji powodującej błąd: Vintagestory.exe, wersja: 1.19.8.0, sygnatura czasowa: 0x661e0000
Nazwa modułu powodującego błąd: openal32.dll, wersja: 1.23.0.0, sygnatura czasowa: 0x63dd31ad
Kod wyjątku: 0x40000015
Przesunięcie błędu: 0x00000000000df046
Identyfikator procesu powodującego błąd: 0x0x3204
Godzina uruchomienia aplikacji powodującej błąd: 0x0x1dad52fd93ba0fc
Ścieżka aplikacji powodującej błąd: C:\Users\macie\AppData\Roaming\Vintagestory\Vintagestory.exe
Ścieżka modułu powodującego błąd: C:\Users\macie\AppData\Roaming\Vintagestory\Lib\openal32.dll
Identyfikator raportu: 3a8a1b27-83a8-4677-9d62-3f0fbe049833
Pełna nazwa pakietu powodującego błąd: 
Identyfikator aplikacji względem pakietu powodującego błąd:  }
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
