### ISSUE TITLE
Crash Report: Lan play by Hamachi

### ISSUE THREAD

**Issue by oseiasflores** [anegostudios/VintageStory-Issues#3971]
### Game Version

1.19. (Stable)

### Platform

Windows 11

### Modded

No

### SP/MP

None

### Description

Another friend and I bought the game recently. The idea is to make a LAN play using Hamachi. Just like we did in the old days in other games. However, when trying to play on Lan the crash occurs.

### How to reproduce

Start a hamachi room and share ipv4 with another PC.
Create a new world and mark to open to Lan after character customization
Another PC try to connect using IPV4 from Hamachi.
There is a message: Connected to the server, and receiving data. This screen takes a while.
Then a Disconnect message is received an then the crash occurs.

### Screenshots

![image](https://github.com/user-attachments/assets/e390cc0b-f1e3-4c49-954d-fd928a409dc6)

### Logs

```Log```

Running on 64 bit Windows 10.0.22631.0 with 32616 MB RAM
Game Version: v1.19.8 (Stable)
13/07/2024 21:12:11: Critical error occurred
Loaded Mods: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Vintagestory.Client.NoObf.ClientMain.get_Rand() in VintagestoryLib\Client\ClientMain.cs:line 2936
   at Vintagestory.GameContent.BlockClutterBookshelf.RandomType(String variant) in VSSurvivalMod\Lore\ResoArchives\BlockClutterBookshelf.cs:line 277
   at Vintagestory.GameContent.BlockClutterBookshelf.GetTypeProps(String code, ItemStack stack, BEBehaviorShapeFromAttributes be) in VSSurvivalMod\Lore\ResoArchives\BlockClutterBookshelf.cs:line 170
   at Vintagestory.GameContent.BlockShapeFromAttributes.GetLightHsv(IBlockAccessor blockAccessor, BlockPos pos, ItemStack stack) in VSSurvivalMod\Block\BlockShapeFromAttributes.cs:line 575
   at Vintagestory.API.Common.Block.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 2241
   at Vintagestory.GameContent.BlockShapeFromAttributes.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VSSurvivalMod\Block\BlockShapeFromAttributes.cs:line 643
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 400
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(ICoreClientAPI capi, ItemStack stack) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 40
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onCreatePagesAsync() in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 84
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 418
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 120
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 09/07/2024 19:53:38, Site = , Source = Application Error, Message = Nome do aplicativo com falha: Vintagestory.exe, versão: 1.19.8.0, carimbo de data/hora: 0x661e0000
Nome do módulo com falha: KERNELBASE.dll, versão: 10.0.22621.3733, carimbo de data/hora: 0x44653e19
Código de exceção: 0xe0434352
Deslocamento da falha: 0x000000000005f39c
ID do processo com falha: 0x0x1c94
Hora de início do aplicativo com falha: 0x0x1dad24e1c76d4a2
Caminho do aplicativo com falha: C:\Games\FPlay.SU\Vintage Story\Vintagestory.exe
Caminho do módulo com falha: C:\Windows\System32\KERNELBASE.dll
ID do Relatório: f2b8eaa5-cd22-4d1f-b1ed-c014eeaed89a
Nome completo do pacote com falha: 
ID do aplicativo relativo ao pacote com falha:  }

**Comment by Craluminum2413** [comment]
Closing due to inactivity
