### ISSUE TITLE
Unhandled network error crashes multiplayer game

### ISSUE THREAD

**Issue by Monkeybrain73** [anegostudios/VintageStory-Issues#3975]
### Game Version

1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Client crashes randomly, not sure how to reproduce. Some times back to the menu, other times out to windows.

### Logs

17.7.2024 21:09:37 [Warning] OpenAL Error during setvolume(val) of sound game:sounds/weather/wind-leafless.ogg: InvalidValue
17.7.2024 21:09:50 [Warning] OpenAL Error during setvolume(val) of sound game:sounds/weather/wind-leafless.ogg: InvalidValue
17.7.2024 21:31:44 [Fatal] Caught unhandled exception in thread 'networkproc'. Exiting game.
17.7.2024 21:31:44 [Error] Exception: Index was outside the bounds of the array.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Vintagestory.Client.NoObf.SystemNetworkProcess.ProcessInBackground_Patch1(SystemNetworkProcess this, Packet_Server packet)
   at Vintagestory.Client.NoObf.SystemNetworkProcess.TryReadPacket(Byte[] data, Int32 dataLength) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 171
   at Vintagestory.Client.NoObf.SystemNetworkProcess.NetworkProcess() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 129
   at Vintagestory.Client.NoObf.ClientThread.Update() in VintagestoryLib\Client\ClientThread.cs:line 75
   at Vintagestory.Client.NoObf.ClientThread.Process() in VintagestoryLib\Client\ClientThread.cs:line 61
17.7.2024 21:31:44 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
17.7.2024 21:31:58 [Notification] Destroying game session, waiting up to 200ms for client threads to exit
17.7.2024 21:32:01 [Notification] Exiting current game to main menu, reason: client thread crash

**Comment by Craluminum2413** [comment]
Closing due to inactivity
