### ISSUE TITLE
crashed  game

### ISSUE THREAD

**Issue by Abraham26cc** [anegostudios/VintageStory-Issues#3976]
### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

just close the game

### How to reproduce

unknown 

### Logs

Running on 64 bit Windows 10.0.22631.0 with 24277 MB RAM
Game Version: v1.19.8 (Stable)
19/07/2024 08:34:35 a. m.: Critical error occurred in the following mod: fantasycreatures@0.6.4
Loaded Mods: ATadMoreLight@1.0.0, fantasycreatures@0.6.4, immersivecorpsedrop@1.0.1, mobsradar@1.0.3, moredrygrass@0.2.0, ragnamans-seeds-from-crops-recipes@1.0.0, rpgitemrarity@1.0.4, sticksfromfirewood@1.0.0, usefuldrifterloot@1.0.3, game@1.19.8, zyrails0break0down0tools@1.18.14, bedspawnv2@1.2.0, commonlib@2.5.0-rc.2, extendedhudinfo@1.1.0, oregolems@0.1.1, temporalstormtimer@1.1.1, creative@1.19.8, survival@1.19.8, cavebeacons@1.0.7, magicmushrooms@1.0.1, tradercamps@1.0.6, extraoverlays@1.4.0, playercorpse@1.10.1-rc.1
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.AnimManager'.
   at fantasycreatures.src.common.entity.EntityDragonFC.OnGameTick(Single dt)
   at Vintagestory.Client.NoObf.ClientSystemEntities.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Entities.cs:line 99
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
Caused by mod
