### ISSUE TITLE
[Solved?] Crash/Timout on server join: System.ObjectDisposedException: Cannot access a disposed object. Object name: 'The ThreadLocal object has been disposed.'.

### ISSUE THREAD

**Issue by NiemandNatural** [anegostudios/VintageStory-Issues#3986]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

I am a server admin.

After adding five more mods, three people couldn't join the server. Others could join fine.
The error switched between "Index can't be negative" (which was resolved by doubling both Atlas sizes to 8192) and "Can't access disposed object".

We tried the following solutions:
- Increasing Atlas size (cuz sometimes they get index errors and for some that helped).
- Restarting the client machine.
- Reinstalling the game.
- Restarting the server.
- Removing mods that I installed shortly before this error started to appear.

For one, it helped to reinstall. - I want todays results of them trying to connect.
For the second, it helped to increase Atlas size.
The (currently) last one is connecting from New Zealand - to Germany. They can connect to other servers.

They all get timed out for 151s ping timeout.
All of them are on 16GB RAM; At least two have old(er) systems.

A thought: Maybe the crash is because they get kicked by joining too long - and maybe a longer timeout limit would let their client catch itself and join? Can I increase that limit from 150 to maybe 300s?

It started after I added a few decoration/chisel mods (I removed all of those already):
> Bricklayers 2.5.6
> Chiseltools 1.13.3
> DecorBazaar 1.1.1
> 
> SteelBit1499
> HydrateOrDiedrate 1.1.6

### Logs

```Running on 64 bit Windows 10.0.19045.0 with 16279 MB RAM
Game Version: v1.19.8 (Stable)
26/07/2024 10:10:11 pm: Critical error occurred
Loaded Mods: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2466
   at Vintagestory.API.Common.CollectibleObject.AppendPerishableInfoText(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1822
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo_Patch0(CollectibleObject this, ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 401
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(ICoreClientAPI capi, ItemStack stack) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 40
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onCreatePagesAsync() in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 84
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 418
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 120
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 26/07/2024 10:10:12 pm, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: ntdll.dll, version: 10.0.19041.4522, time stamp: 0x8a1bb6f3
Exception code: 0xc0000374
Fault offset: 0x00000000000ff439
Faulting process id: 0x1e2c
Faulting application start time: 0x01dadf43123d5a4d
Faulting application path: C:\Users\ranic\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 0ce097ae-33da-4691-a295-67b42bb9923e
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 26/07/2024 9:59:19 pm, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.4648, time stamp: 0x5a4af933
Exception code: 0xe0434352
Fault offset: 0x000000000003b699
Faulting process id: 0x2e40
Faulting application start time: 0x01dadf41bec7efc8
Faulting application path: C:\Users\ranic\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 9deb430b-8d97-4100-9c0a-78538a17008b
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 26/07/2024 9:53:44 pm, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: coreclr.dll, version: 7.0.1023.36312, time stamp: 0x64b06d6c
Exception code: 0xc0000005
Fault offset: 0x00000000001c98a6
Faulting process id: 0x1640
Faulting application start time: 0x01dadf40ff339639
Faulting application path: C:\Users\ranic\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.10\coreclr.dll
Report Id: a00d1f19-2939-4f13-a709-86e213722a6c
Faulting package full name: 
Faulting package-relative application ID:  }```

**Comment by NiemandNatural** [comment]
This line looks weird with the "..":
```   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(ICoreClientAPI capi, ItemStack stack) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 40```

**Comment by Craluminum2413** [comment]
Does it happen without some mods?

**Comment by NiemandNatural** [comment]
So I think I found the solution:
Increase `ClientConnectionTimeout` in serverconfig.json - _I raised it from 150 to 600 (that's 10 minutes... which is unnecessarily long) but since then, at least "Player #3" does not crash. I even added the mods back in._

I guess my suspicion was correct:
The crash is caused by the client taking too long to join the server and being timedout by the server.
_Wrong wording, but what I understand: "Player is kicked so the thread object that is loading into the server is disposed - which makes the client crash."_

You can try reproducing the crash by setting a laughably low `ClientConnectionTimeout` and trying to join with a lowpower (<17GB RAM?) PC from further away (like Germany - NewZealand).

I will report back if there's any changes.

**Comment by Craluminum2413** [comment]
Closing due to inactivity
