### ISSUE TITLE
Fruit Press

### ISSUE THREAD

**Issue by SKamSP0406** [anegostudios/VintageStory-Issues#3988]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Mainly i am playing on my friends Server that he is renting, but for some odd reason every time we try to use the Fruit Press it crashes the game and kicks you out all we are trying to do is make seed oil or make juice. we arent sure if its a client-side issue because we even tried deleting game a reinstalling it and that still didnt work, i even had to buy a new account because at one point it got stuck in a crash loop where everytime id load the server my game would crash immediately.

also while y'all are at it we have 2 similar issues, which are honestly just annoying as shit but we have a work arounds to it (look at wiki lol). basically, we arent allowed to search how to make a Candle or physically try to make a pie, if you do try those 2 things the game crashes and if your unlucky like my dumbass, the game will put you in a crash loop and your account basically is stuck and you can never join the server again (solo world does work though)

also below are the mods we have on the server if it helps
aculinaryartillery@1.1.5, bedrespawner@1.0.0, chiseltools@1.12.3, primitivesurvival@3.5.7, game@1.19.8, animalcages@3.0.2, betterruins@0.3.5, commonlib@2.5.0-rc.2, expandedfoods@1.6.9, knapster@2.9.5, rivers@3.1.0, creative@1.19.8, survival@1.19.8, metalrecovery@0.1.19-pre.1, extraoverlays@1.4.0, stonequarry@3.3.1

### How to reproduce

make fruit press, have any type of grain in hot bar, try placing the grain in the fruit press game will stop split second then crash immediately. 

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32637 MB RAM
Game Version: v1.19.8 (Stable)
7/27/2024 10:43:53 PM: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.5, bedrespawner@1.0.0, chiseltools@1.12.3, primitivesurvival@3.5.7, game@1.19.8, animalcages@3.0.2, betterruins@0.3.5, commonlib@2.5.0-rc.2, expandedfoods@1.6.9, knapster@2.9.5, rivers@3.1.0, creative@1.19.8, survival@1.19.8, metalrecovery@0.1.19-pre.1, extraoverlays@1.4.0, stonequarry@3.3.1
System.ArgumentNullException: Value cannot be null. (Parameter 'Unable to find a texture for texture code 'mash' in fruitpress-mash. Giving up. Sorry.')
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(Int32 indexForLogging, MeshData meshdata, ShapeElement element, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 394
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 306
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(Shape shapeBase, MeshData& modeldata, Vec3f wholeMeshRotation, Vec3f wholeMeshOffset, Single wholeMeshScale, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 302
   at Vintagestory.GameContent.FruitpressContentsRenderer.reloadMeshes(JuiceableProperties props, Boolean mustReload) in VSSurvivalMod\BlockEntityRenderer\FruitpressContentsRenderer.cs:line 122
   at Vintagestory.GameContent.BlockEntityFruitPress.InteractMashContainer(IPlayer byPlayer, BlockSelection blockSel) in VSSurvivalMod\BlockEntity\BEFruitpress.cs:line 418
   at Vintagestory.GameContent.BlockEntityFruitPress.OnBlockInteractStart(IPlayer byPlayer, BlockSelection blockSel, EnumFruitPressSection section, Boolean firstEvent) in VSSurvivalMod\BlockEntity\BEFruitpress.cs:line 306
   at Vintagestory.GameContent.BlockFruitPressTop.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in VSSurvivalMod\Block\BlockFruitpressTop.cs:line 98
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 864
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 444
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by SKamSP0406** [comment]
BTW ALL I WANT IS TO TRY THE GETTING DRUNK FEATURE IN THE GAME LOL

**Comment by Craluminum2413** [comment]
Most likely caused by mods, grain mash doesn't exist in vanilla

**Comment by Craluminum2413** [comment]
Closing due to inactivity
