### ISSUE TITLE
crashing when loading into world

### ISSUE THREAD

**Issue by altlet** [anegostudios/VintageStory-Issues#3995]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Everytime i load into my mates world it crashes

### Logs

```Log```Running on 64 bit Windows 10.0.19045.0 with 16309 MB RAM
Game Version: v1.19.8 (Stable)
7/30/2024 10:09:53 PM: Critical error occurred
Loaded Mods: game@1.19.8, creative@1.19.8, survival@1.19.8
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Vintagestory.Common.ArrayConvert.ByteToByte(Byte[] data, Int32 length) in VintagestoryLib\Common\Convert\ArrayConvert.cs:line 73
   at Vintagestory.Common.CompressionZSTD.Decompress(Byte[] fi, Int32 offset, Int32 length) in VintagestoryLib\Common\Convert\Compression.cs:line 684
   at Vintagestory.Common.Compression.DecompressCombined(Byte[] blocksCompressed, Int32[][]& blocks, Int32& refCount, Func`1 newArray) in VintagestoryLib\Common\Convert\Compression.cs:line 207
   at Vintagestory.Common.ChunkDataLayer.Decompress(Byte[] layerCompressed) in VintagestoryLib\Common\Model\ChunkDataLayer.cs:line 756
   at Vintagestory.Common.ChunkData.DecompressFrom(Byte[] blocksCompressed, Byte[] lightCompressed, Byte[] lightPaletteCompressed, Byte[] fluidsCompressed, Int32 chunkdataVersion) in VintagestoryLib\Common\Model\ChunkData.cs:line 333
   at Vintagestory.Common.WorldChunk.unpackNoLock() in VintagestoryLib\Common\Datastructures\WorldChunk.cs:line 282
   at Vintagestory.Common.WorldChunk.UnpackAndReadBlock(Int32 index, Int32 layer) in VintagestoryLib\Common\Datastructures\WorldChunk.cs:line 220
   at Vintagestory.GameContent.ChunkMapLayer.GenerateChunkImage(Vec2i chunkPos, IMapChunk mc, Int32[]& tintedImage, Boolean colorAccurate) in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 493
   at Vintagestory.GameContent.ChunkMapLayer.OnOffThreadTick(Single dt) in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 322
   at Vintagestory.GameContent.WorldMapManager.<OnLvlFinalize>b__22_0() in VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 206

**Comment by Craluminum2413** [comment]
Closing due to inactivity
