### ISSUE TITLE
world is instantly crashing after loading it

### ISSUE THREAD

**Issue by IoIoPauly** [anegostudios/VintageStory-Issues#3996]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

My world is crashing, right after loading into it. Last time i've played the game crashed while remoddeling my base maybe theres an error connected to placing items in chests or in the world.
Other worlds are working

### How to reproduce

i'm not sure if theres a way to reproduce without my world save. 

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32692 MB RAM
Game Version: v1.19.8 (Stable)
31.07.2024 09:44:00: Critical error occurred
Loaded Mods: 
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Vintagestory.Client.NoObf.TextureAtlasManager.RegenMipMaps(Int32 atlasNumber) in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 359
   at Vintagestory.Client.NoObf.TextureAtlasManager.<>c__DisplayClass51_0.<runtimeUpdateTexture>b__1() in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 325
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 31.07.2024 09:44:01, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.8.0, Zeitstempel: 0x661e0000
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.4648, Zeitstempel: 0x5a4af933
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000003b699
ID des fehlerhaften Prozesses: 0x1a0
Startzeit der fehlerhaften Anwendung: 0x01dae31d597e9fd7
Pfad der fehlerhaften Anwendung: C:\Users\flo\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: fac74c9e-b45c-4b74-bd9c-938e342c32ea
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }

**Comment by IoIoPauly** [comment]
Hey guys
i tried fixing it with via the repair mode which worked fine. sorry for troubling you
