### ISSUE TITLE
Ubuntu Server trying to load from wrong folder

### ISSUE THREAD

**Issue by RogueFox** [anegostudios/VintageStory-Issues#4001]
### Game Version

v1.19.8

### Platform

Linux

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Despite launching with the argument `--dataPath /path/to/data/folder`, the server will attempt to load from the default data path of `/var/vintagestory/data`.

Interestingly enough, it seems to be using the correct folder to initially load the server settings as well as write the logs.

### How to reproduce

1. If it exists, delete the `/var/vintagestory` folder and its contents.
2. Create a new location for the data folder, such as `[server]/data`
3. Launch the server with the argument `--dataPath [server]/data`
4. The server will attempt to load from the default path provided in the `server.sh` script of `/var/vintagestory/data` and fail to start.

### Logs

```3.8.2024 05:57:18 [Event] Launching server...
3.8.2024 05:57:18 [Event] Server v1.19.8, network v1.19.8, api v1.19.0
3.8.2024 05:57:18 [Event] Loading configuration...
3.8.2024 05:57:18 [Fatal] Unable to open or create savegame.
3.8.2024 05:57:18 [Error] Exception: /var/vintagestory/data/Saves
   at Vintagestory.API.Common.SQLiteDBConnection.HaveWriteAccessFolder(String folderPath) in VintagestoryApi\Common\IO\SQLiteDBConnection.cs:line 167
   at Vintagestory.API.Common.SQLiteDBConnection.OpenOrCreate(String filename, String& errorMessage, Boolean requireWriteAccess, Boolean corruptionProtection, Boolean doIntegrityCheck) in VintagestoryApi\Common\IO\SQLiteDBConnection.cs:line 30
   at Vintagestory.Common.Database.SQLiteDbConnectionv2.Vintagestory.Common.Database.IGameDbConnection.OpenOrCreate(String filename, String& errorMessage, Boolean requireWriteAccess, Boolean corruptionProtection, Boolean doIntegrityCheck)
   at Vintagestory.Common.GameDatabase.OpenConnection(String databaseFilename, Int32 databaseVersion, String& errorMessage, Boolean requireWriteAccess, Boolean corruptionProtection, Boolean doIntegrityCheck) in VintagestoryLib\Common\FileIO\Database\GameDatabase.cs:line 89
   at Vintagestory.Common.GameDatabase.ProbeOpenConnection(String databaseFilename, Boolean corruptionProtection, Int32& foundVersion, String& errorMessage, Boolean& isReadonly, Boolean requireWrite) in VintagestoryLib\Common\FileIO\Database\GameDatabase.cs:line 127
   at Vintagestory.Server.ServerSystemLoadAndSaveGame.OnBeginConfiguration() in VintagestoryLib\Server\Systems\World\LoadThread\LoadSaveGame.cs:line 72
3.8.2024 05:57:18 [Event] Shutting down 4 server threads... 
3.8.2024 05:57:18 [Event] Killed console thread
3.8.2024 05:57:19 [Event] All threads gracefully shut down
3.8.2024 05:57:19 [Event] Doing last tick...
3.8.2024 05:57:19 [Event] Stopped the server!```

**Comment by RogueFox** [comment]
Update after working with Discord members on this issue:

This was likely caused by starting the server using the `server.sh` script which only uses `/var/vintagestory/data` for its `DATAPATH`. At some point, I noticed this and changed it to `"${VSPATH}/data"`. However, there was some server configuration file which was then left stale and was looking for the saved game at the old path which didn't exist. I think we can close this issue and call it user error.

I would suggest changing the default data path in `server.sh` to something like what I have, so it would be more likely to have read, write, and execute permissions in that folder instead of `/var/...`

Also of note, is that trying to run `server.sh setup [myuser] [mypath]` will fail since it first tries to set up its own defaults for user and path, both of which it was not allowed to do without root.

**Comment by RogueFox** [comment]
Update after working with Discord members on this issue:

This was likely caused by starting the server using the `server.sh` script which only uses `/var/vintagestory/data` for its `DATAPATH`. At some point, I noticed this and changed it to `"${VSPATH}/data"`. However, there was some server configuration file which was then left stale and was looking for the saved game at the old path which didn't exist. I think we can close this issue and call it user error.

I would suggest changing the default data path in `server.sh` to something like what I have, so it would be more likely to have read, write, and execute permissions in that folder instead of `/var/...`

Also of note, is that trying to run `server.sh setup [myuser] [mypath]` will fail since it first tries to set up its own defaults for user and path, both of which it was not allowed to do without root.
