### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by HyperBeast43** [anegostudios/VintageStory-Issues#4003]
### Game Version

v1.18.6

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

I can't get in to the game at all, just the title screen.

### How to reproduce

1. Launch the game.
2. Open a world.
3. Crash.

### Logs

```Running on 64 bit Windows with 64 GB RAM 
Game Version: v1.18.6 (Stable)
8/4/2024 1:27:35 PM: Critical error occurred
Loaded Mods: game@1.18.6, creative@1.18.6, survival@1.18.6
System.Exception: SendServerAssets failed. See log files.
   at Vintagestory.Server.ServerMain.BuildServerAssetsPacket() in VintagestoryLib\Server\ServerMainNetworking.cs:line 1168
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 8/4/2024 1:27:38 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Vintagestory.Server.ServerMain.BuildServerAssetsPacket()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 8/4/2024 1:23:34 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Vintagestory.Server.ServerMain.BuildServerAssetsPacket()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 8/2/2024 8:36:45 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Vintagestory.Server.ServerMain.BuildServerAssetsPacket()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }

**Comment by Craluminum2413** [comment]
Too old version
