### ISSUE TITLE
Crash when writing on a sign

### ISSUE THREAD

**Issue by pingouyn** [anegostudios/VintageStory-Issues#4005]
VS v1.19.8, only mod is hudclock.
Linux.

The game crashed to desktop whilst I was writing on a sign with a piece of malachite.  I was using arrow keys to move the cursor when it crashed.
I was typing something like this "<= jam &/ porridge".
Linux is in French, the keyboard is qwerty US in case it matters.

```
Running on 64 bit Linux (Ubuntu 24.04 LTS) [Kernel 6.8.0.39] with 32000 MB RAM
Game Version: v1.19.8 (Stable)
05/08/2024 04:03:20: Critical error occurred
Loaded Mods: game@1.19.8, hudclock@3.4.0, creative@1.19.8, survival@1.19.8
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Vintagestory.API.Client.GuiElementEditableTextBase.MoveCursor(Int32 dir, Boolean wholeWord) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 637
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyDown(ICoreClientAPI api, KeyEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 423
   at Vintagestory.API.Client.GuiComposer.OnKeyDown(KeyEvent args, Boolean haveFocus) in VintagestoryApi\Client\UI\GuiComposer.cs:line 610
   at Vintagestory.API.Client.GuiDialog.OnKeyDown(KeyEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 441
   at Vintagestory.Client.NoObf.GuiManager.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 333
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1731
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 230
   at OpenTK.Windowing.Desktop.NativeWindow.KeyCallback(Window* window, Keys key, Int32 scancode, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by pingouyn** [comment]
Update for 1.20-rc.8, unmodded.
Same world, converted to 1.20-rc.8 when asked.  Same PC, same OS (updated video drivers of course), same keyboard.

I tried my best to crash 1.20, doing the same sequence of events writing on a sign with a piece of malachite.  Same block location, same world.
Whereas the bug in 1.19.8 was repeatable and predictable, crashing to desktop every single time, it did not crash in 1.20-rc.8.

Something in the code has improved and fixed this.
The bug report can be closed.  Good job to the devs.
