### ISSUE TITLE
Limewater in barrels causing crashes

### ISSUE THREAD

**Issue by hyapapaya** [anegostudios/VintageStory-Issues#4015]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Limewater in barrels is making my game crash. It crashed first when I filled a barrel with 50 liters of water and 50 units of lime, but then it was fine for a while when i loaded it back up. Now I went to move one of my barrels (which appeared invisible) and the game crashed.

The crash logs mention something about not having a texture for raw-onion in barrel which is really weird since I wasn't putting onions in there. Also I tried uninstalling some mods and reloading the world but it produced an error on trying to get back into the world so I gave up on that.

### How to reproduce

I don't know honestly different things make the game crash

### Logs

Running on 64 bit Windows 10.0.19045.0 with 65485 MB RAM
Game Version: v1.19.8 (Stable)
8/9/2024 12:28:43 PM: Critical error occurred in the following mod: carryon@1.7.4
Loaded Mods: aculinaryartillery@1.1.5, chiseltools@1.12.3, koboldplayermodelport@1.2.10, primitivesurvival@3.6.3, sortablestorage@2.2.6, game@1.19.8, ancienttools@1.5.18, animalcages@3.0.2, betterfirepit@1.1.4, betterruins@0.3.7, carryon@1.7.4, commonlib@2.5.0-rc.2, expandedfoods@1.6.9, extrainfo@1.8.0, fromgoldencombs@1.5.1, hudclock@3.4.0, knapster@2.10.0, kscartographytable@1.0.1, claywheel@1.1.1, usefulstuff17@1.3.2, creative@1.19.8, vsimgui@1.1.5, survival@1.19.8, metalrecovery@0.1.19-pre.1, configlib@1.3.13, stickcrafting@1.0.0, stonequarry@3.3.1
System.ArgumentNullException: Value cannot be null. (Parameter 'Unable to find a texture for texture code 'raw-onion' in barrel. Giving up. Sorry.')
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(Int32 indexForLogging, MeshData meshdata, ShapeElement element, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 394
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 306
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(Shape shapeBase, MeshData& modeldata, Vec3f wholeMeshRotation, Vec3f wholeMeshOffset, Single wholeMeshScale, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 302
   at Vintagestory.GameContent.BlockBarrel.getContentMesh(ItemStack stack, BlockPos forBlockPos, String shapefilepath) in VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:line 250
   at Vintagestory.GameContent.BlockBarrel.getContentMeshLiquids(ItemStack contentStack, ItemStack liquidContentStack, BlockPos forBlockPos, JsonObject containerProps) in VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:line 202
   at Vintagestory.GameContent.BlockBarrel.GenMesh(ItemStack contentStack, ItemStack liquidContentStack, Boolean issealed, BlockPos forBlockPos) in VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:line 166
   at Vintagestory.GameContent.BlockBarrel.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo) in VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:line 55
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 315
   at CarryOn.Client.EntityCarryRenderer.GetRenderInfo(CarriedBlock carried) in G:\git\github\Nerdscurvy\CarryOn\src\Client\EntityCarryRenderer.cs:line 51
   at CarryOn.Client.EntityCarryRenderer.RenderCarried(EntityAgent entity, CarriedBlock carried, Single deltaTime, Boolean isFirstPerson, Boolean isImmersiveFirstPerson, Boolean isShadowPass, EntityShapeRenderer renderer, IAnimator animator) in G:\git\github\Nerdscurvy\CarryOn\src\Client\EntityCarryRenderer.cs:line 118
   at CarryOn.Client.EntityCarryRenderer.RenderAllCarried(EntityAgent entity, Single deltaTime, Boolean isShadowPass) in G:\git\github\Nerdscurvy\CarryOn\src\Client\EntityCarryRenderer.cs:line 94
   at CarryOn.Client.EntityCarryRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in G:\git\github\Nerdscurvy\CarryOn\src\Client\EntityCarryRenderer.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 8/7/2024 2:38:58 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x707c
Faulting application start time: 0x01dae8941da73971
Faulting application path: C:\Users\hyv0l\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\hyv0l\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 8ada5c70-0c8c-4d9e-b937-c8cefde1ef88
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Caused by mod

**Comment by hyapapaya** [comment]
can i at least get some help in reading the log files or something? i don't know where to start with fixing this issue

**Comment by Craluminum2413** [comment]
Carry On mod
