### ISSUE TITLE
Game crashes upon hovering over a prospecting pick reading in map

### ISSUE THREAD

**Issue by Wasatch-Wind** [anegostudios/VintageStory-Issues#4016]
### Game Version

_1.19.8_

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Finished I'm planning on a modded world, but have thus far had no issues with it after hours and hours of play. After smelting my first tin bronze anvil and pickaxe, I walked away from my blacksmith and then opened my map to look at my past prospecting pick readings to look for iron -

And then the game crashed. I thought it was odd, loaded up the game again. The game loaded just fine. I thought it might be a fluke, reopened the map. Once I scrolled my mouse pointer over to where a prospecting marker was, once it got close, another crash. I reloaded. I walked around for a bit, not crash, then opened the map, tried to find that prospecting marker, and once again, got a crash. The crash occurs when hovering over any prospecting pick reading.

### How to reproduce

smelt 1000 units of tin bronze, pour into anvil and pickaxe mold. Open map and hover over prospecting pick reading marker. Doesn't occur on a fresh world when using the prospecting pick, only this one. The issue does however persist if the world is opened in repair mode and you hover over prospecting icons on the map. Opened the world, got out the prospecting pick and made a new prospecting search. Hovering over this one caused no issues. Hovering over an old one however crashed the game.

### Logs

Running on 64 bit Windows 10.0.22631.0 with 32173 MB RAM
Game Version: v1.19.8 (Stable)
8/10/2024 6:53:23 PM: Critical error occurred
Loaded Mods: game@1.19.8, ancienttools@1.5.18, freedomunits@1.1.3, trailmod@1.0.8, creative@1.19.8, survival@1.19.8
System.Collections.Generic.KeyNotFoundException: The given key 'nativecopper' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Vintagestory.GameContent.PropickReading.ToHumanReadable(String languageCode, Dictionary`2 pageCodes) in VSSurvivalMod\Systems\Prospecting\OreMapLayer\PropickReading.cs:line 54
   at Vintagestory.GameContent.OreMapComponent.OnMouseMove(MouseEvent args, GuiElementMap mapElem, StringBuilder hoverText) in VSSurvivalMod\Systems\Prospecting\OreMapLayer\OreMapComponent.cs:line 105
   at Vintagestory.GameContent.OreMapLayer.OnMouseMoveClient(MouseEvent args, GuiElementMap mapElem, StringBuilder hoverText) in VSSurvivalMod\Systems\Prospecting\OreMapLayer\OreMapLayer.cs:line 240
   at Vintagestory.GameContent.GuiDialogWorldMap.OnMouseMove(MouseEvent args) in VSEssentials\Systems\WorldMap\GuiDialogWorldMap.cs:line 298
   at Vintagestory.Client.NoObf.GuiManager.OnMouseMove(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 433
   at Vintagestory.Client.NoObf.ClientMain.OnMouseMove(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1980
   at Vintagestory.Client.NoObf.ClientPlatformWindows.UpdateMousePosition() in VintagestoryLib\Client\ClientPlatform\Input.cs:line 111
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 2
==================================
{ TimeGenerated = 7/14/2024 12:12:48 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x5238
Faulting application start time: 0x0x1dad597e93231d4
Faulting application path: C:\Users\curti\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\curti\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: d6d4f0f3-09c3-4af3-a7bf-9c4e6309201a
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 6/21/2024 9:49:52 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: coreclr.dll, version: 7.0.1023.36312, time stamp: 0x64b06d6c
Exception code: 0xc0000005
Fault offset: 0x00000000001c98a6
Faulting process id: 0x0x113c
Faulting application start time: 0x0x1dac420aa4ff0e3
Faulting application path: C:\Users\curti\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.10\coreclr.dll
Report Id: ab5721a3-e48e-4917-99f5-5d3a1aa90e36
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Wasatch-Wind** [comment]
Update, here is the server-main log

[server-main.txt](https://github.com/user-attachments/files/16603108/server-main.txt)

**Comment by Wasatch-Wind** [comment]
**FIXED!**

The issue was due to me changing the world config settings in game in the command box. I'd wanted copper to show up less, and tin to show up more. I thought that I could just type in "uncommon" or "rare" like it had in the UI when making a world - but it gave me a warning saying that values were typically given numerically - when I should've typed in something like .02 instead. Upon changing this and reloading, my world was back to normal, no issues.
Thanks to everyone who helped me, may this be a cautionary tale that one should follow warnings xD

**Comment by Wasatch-Wind** [comment]
Issue was fixed.
