### ISSUE TITLE
Curved bow gives an crush when interacting

### ISSUE THREAD

**Issue by beginerinfuture** [anegostudios/VintageStory-Issues#4026]
### Game Version

v1.18.6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When playing as a scoundrel using a curved bow without arrows, the game crashes.

### How to reproduce

1. At the start of the game, select the scoundrel class
2. Just use curved bow on air

### Logs

Running on 64 bit Windows 10.0.19045.0 with 16334 MB RAM
Game Version: v1.19.8 (Stable) by OverF1X  
16.08.2024 23:30:21: Critical error occurred
Loaded Mods: betterruins@0.2.2, game@1.19.8, creative@1.19.8, survival@1.19.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemBow.<>c__DisplayClass4_0.<GetNextArrow>b__0(ItemSlot invslot) in VSSurvivalMod\Item\ItemBow.cs:line 65
   at Vintagestory.API.Common.EntityPlayer.WalkInventory(OnInventorySlot handler) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 1405
   at Vintagestory.GameContent.ItemBow.GetNextArrow(EntityAgent byEntity) in VSSurvivalMod\Item\ItemBow.cs:line 61
   at Vintagestory.GameContent.ItemBow.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling) in VSSurvivalMod\Item\ItemBow.cs:line 82
   at Vintagestory.API.Common.CollectibleObject.OnHeldUseStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, Boolean firstEvent, EnumHandHandling& handling) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1106
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 831
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 444
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 02.07.2024 13:01:27, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.19.8.0, метка времени: 0x661e0000
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.19041.4522, метка времени: 0xf7a99bd4
Код исключения: 0xe0434352
Смещение ошибки: 0x000000000002ba99
Идентификатор сбойного процесса: 0xb04
Время запуска сбойного приложения: 0x01dacc66cd7e8053
Путь сбойного приложения: D:\Vintage Story 1.19.8\Vintagestory.exe
Путь сбойного модуля: C:\Windows\System32\KERNELBASE.dll
Идентификатор отчета: 81ae0d49-570f-4ad1-ae62-b3000e7f1623
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 02.07.2024 13:01:05, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.19.8.0, метка времени: 0x661e0000
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.19041.4522, метка времени: 0xf7a99bd4
Код исключения: 0xe0434352
Смещение ошибки: 0x000000000002ba99
Идентификатор сбойного процесса: 0x3bc8
Время запуска сбойного приложения: 0x01dacc66c0867392
Путь сбойного приложения: D:\Vintage Story 1.19.8\Vintagestory.exe
Путь сбойного модуля: C:\Windows\System32\KERNELBASE.dll
Идентификатор отчета: 6323103a-e2c2-4760-8a8b-44bbd6fe455c
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 02.07.2024 13:00:39, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.19.8.0, метка времени: 0x661e0000
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.19041.4522, метка времени: 0xf7a99bd4
Код исключения: 0xe0434352
Смещение ошибки: 0x000000000002ba99
Идентификатор сбойного процесса: 0x1178
Время запуска сбойного приложения: 0x01dacc66b0ef82f7
Путь сбойного приложения: D:\Vintage Story 1.19.8\Vintagestory.exe
Путь сбойного модуля: C:\Windows\System32\KERNELBASE.dll
Идентификатор отчета: c64e4519-7e92-491e-aec0-72c89ec39595
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }

**Comment by Craluminum2413** [comment]
pirated versions are not supported
