### ISSUE TITLE
crach

### ISSUE THREAD

**Issue by Ming376** [anegostudios/VintageStory-Issues#4028]
### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Running on 64 bit Windows 10.0.19045.0 with 31887 MB RAM
Game Version: v1.19.8 (Stable)
20/08/2024 10:56:25: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: The driver does not appear to support OpenGL
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings) in VintagestoryLib\Client\ClientPlatform\GameWindowNative.cs:line 14
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 281
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

### Screenshots

Running on 64 bit Windows 10.0.19045.0 with 31887 MB RAM
Game Version: v1.19.8 (Stable)
20/08/2024 10:56:25: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: The driver does not appear to support OpenGL
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings) in VintagestoryLib\Client\ClientPlatform\GameWindowNative.cs:line 14
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 281
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

### Logs

```Log```

**Comment by Ming376** [comment]
impossible de lancez le jeu le désinstaller et le réinstaller n'y change rien même en ayant supprimer tout les mods et dossiers !

**Comment by Craluminum2413** [comment]
Update your graphics drivers

**Comment by Ming376** [comment]
already done yesterday and then my game won't work anymore !

**Comment by Craluminum2413** [comment]
What mods are installed?

**Comment by Ming376** [comment]
thats all the mods but i have already delete all those frome the game folders and uninstal the game but it won't work :/
AlloyCalculator-v1.0.0
AncientTools_V1.5.18
animalcages_v3.0.2
animationmanagerlib_0.7.0
AWearableLight-v1.1.1
battletowers_1.0.0
bedspawnv2_1.2.0
BetterFirepit-1.1.4
BetterRuinsLootChangesv0.0.3
BetterRuinsv0.3.5
BetterSticks_v1.1.0
BloomeryFullDrops
CarryOn-1.19_v1.7.4
CommonLib_VS1.19.8_net7_v2.5.0-rc.2
configlib_0.4.2
crackedrockweak
Craftable Jonas Parts
European Horde
ExtraInfo-v1.8.1
fsmlib_0.2.15
greenhousebuff_1.0.0
HelveHammerExtensions_VS1.19.0-rc.5_net7_v1.6.0
hidenotrot_1.19.7_v0.1.0
JuicyOres-v1.0.0
krpgenchantment_0.2.11
levelup_1.2.1
maltiezfirearms_0.5.4
medievalexpansion-3.13.1
millwright_1.1.6
Not_OnlySpear_Expantion_by_Kanahaku-v.0.1.3
sailboat_1.3.1
simplevillages_v1.0.1
StoneQuarry_VS1.19.8_net7_v3.3.1
Swordz 1.1.8
temporal_gears_stack v1
trailmod_1.0.8
translocatorengineeringredux_1.5.1
UsefulDrifterLoot 1.1.0
versionchecker_1.0.0
vsimgui_0.3.3
vsquest_v1.2.0
vsvillage_v1.0.0
VSVillageAgedv0.0.4
vsvillage_v1.0.6
VSVillageIndustrialv0.0.4
VSVillageTowersv0.0.4
xlib_v0.8.5-pre.1

**Comment by Ming376** [comment]
problem resolve i've reinstalled the pilots graphics, restart my computer and it just work ! sorry for the inconvenience and thanks
