### ISSUE TITLE
Client crash on joining server

### ISSUE THREAD

**Issue by RockyFoliage** [anegostudios/VintageStory-Issues#4035]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

When I try to log onto my server it downloads all the information, but then crashes when it trys to load my client instance. According to the crash log it has somthing to do with my audio library? The server is modded, but I don't think there is many audio changes. Everything worked before, and I didn't update the server or my game or change anything about the mods. My game just started crashing upon loading in foe some reason. Any idea what this might be or how to fix it?

### How to reproduce

I don't know how to recreate. It happens every time and I don't know why

### Logs

```Log```Running on 64 bit Windows 10.0.19045.0 with 8067 MB RAM
Game Version: v1.19.8 (Stable)
8/21/2024 4:47:19 PM: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.4, arrowheadsrecovery@1.0.1, irregularguybetterjam@1.0.0, cellardoor@1.4.0, chiseltools@1.11.3, craftingjonas@1.0.6, craftablecompanion@1.1.0, CutTheFat@1.0.0, morecrops@1.0.3, lumbersling@1.2.2, bgn_moreclasses@1.0.2, morefuel@0.0.3, morecaveart@1.0.0, orepulverizer@1.1.1, pipeleaf@1.6.0, primitivesurvival@3.5.3, repairablelocust@1.3.0, spyglass@0.5.1, upgradeablelocust@1.0.2, game@1.19.8, animationmanagerlib@0.7.14, blocksoverlay@3.2.2, butchering@1.5.5, carryon@1.7.4, chickenfeed@1.1.2, coinage@1.10.2, expandedfoods@1.6.9, hammersringingfall@1.2.5, hudclock@3.4.0, immersivewoodchopping@0.7.1, pigfeed@1.0.4, resinregrow@1.0.1, rustyshell@0.0.12, tabletopgames@1.2.0, traitacquirer@0.9.2, creative@1.19.8, vsimgui@1.1.3, survival@1.19.8, metalrecovery@0.1.19-pre.1, catchablebees@1.0.0, configlib@1.3.9, fsmlib@0.4.5, justchairs@0.0.1, maltiezcrossbows@0.3.9, maltiezfirearms@0.5.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.HudMouseTools.OnOwnPlayerDataReceived() in VintagestoryLib\Client\Systems\Gui\Huds\HudMouseTools.cs:line 131
   at Vintagestory.Client.NoObf.GuiManager.OnOwnPlayerDataReceived() in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 274
   at Vintagestory.Client.NoObf.ClientMain.OnOwnPlayerDataReceived() in VintagestoryLib\Client\ClientMain.cs:line 702
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 274
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 448
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 442
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 8/21/2024 4:41:24 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x349c
Faulting application start time: 0x01daf40806595a37
Faulting application path: C:\Users\MyPC\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\MyPC\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: f3eaf225-e949-44dd-9f18-2b4f03fc0a24
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 8/21/2024 2:01:01 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x3530
Faulting application start time: 0x01daf3f2360096c7
Faulting application path: C:\Users\MyPC\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\MyPC\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 8dad47e6-dcf3-49ec-8c89-538b18ada3ef
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 8/21/2024 1:46:01 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x2530
Faulting application start time: 0x01daf3f11ce1ec70
Faulting application path: C:\Users\MyPC\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\MyPC\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: d8751188-736a-40fc-b3c5-69b682917de0
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Does it happen without mods?

**Comment by RockyFoliage** [comment]
I haven't had the chance to take all the mods off the server yet, can I get back to you on that? And if it does or doesn't do have any Idea what might be causing it or where to look in the mods? If it is the mods, I might be able to fix them but I have no Idea where to start.
________________________________

**Comment by RockyFoliage** [comment]
I have no clientside mods, other than the essentials that come with the game
________________________________

**Comment by Craluminum2413** [comment]
Closing due to inactivity
