### ISSUE TITLE
Crash on world open attempt

### ISSUE THREAD

**Issue by maw1958** [anegostudios/VintageStory-Issues#4039]
Running on 64 bit Windows 10.0.19045.0 with 16316 MB RAM
Game Version: v1.19.8 (Stable)
23/08/2024 8:36:50 PM: Critical error occurred in the following mod: volumetricshadingcontinued@0.6.6
Loaded Mods: BuggisRandomChanges@2.0.1, cavecontent@1.0.1, extrachests@1.5.2, fancydoors@1.1.0, lazyknappingclayforming@1.0.0, moreenemyloot@1.0.0, orecrystals@1.3.6, OresAPlenty@2.2.0, quickerbarrel@1.1.0, stackables@2.0.5, superfuel@2.0.7, ldsurftrans@0.1.0, visibleore@1.0.1, volumetricshadingcontinued@0.6.6, game@1.19.8, medievalexpansion@3.7.1, creative@1.19.8, survival@1.19.8, yeet@2.0.0
System.MissingMethodException: Method not found: 'Void Vintagestory.API.Client.IShaderProgram.Dispose()'.
   at VolumetricShading.Effects.ScreenSpaceReflections.ReloadShaders()
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerReloadShaders() in VintagestoryLib\Client\Util\ClientEventManager.cs:line 432
   at Vintagestory.Client.NoObf.ShaderAPI.ReloadShaders() in VintagestoryLib\Client\API\ShaderAPI.cs:line 53
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerReady(Packet_Server packet) in VintagestoryLib\Client\Systems\Startup.cs:line 881
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 448
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 442
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 23/08/2024 8:35:17 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x12c0
Faulting application start time: 0x01daf547d0c4ad47
Faulting application path: C:\Users\Mandi Wilson\Documents\Games\VintageStory\Vintagestory.exe
Faulting module path: C:\Users\Mandi Wilson\Documents\Games\VintageStory\Lib\openal32.dll
Report Id: e9f8bb1e-2051-4d8d-832d-df325368ef40
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Caused by shaders mod
