### ISSUE TITLE
Mods on Linux 

### ISSUE THREAD

**Issue by Roy001-sudo** [anegostudios/VintageStory-Issues#4060]
### Game Version

V1.19.8

### Platform

Linux

### Modded

Modded

### SP/MP

Multiplayer

### Description

Allowed it to install the mods than clicked play and boom crash

### How to reproduce

Linux Tumbleweed than use Flatpack version of Game

### Logs

`Running on 64 bit Linux (Freedesktop SDK 22.08 (Flatpak runtime)) [Kernel 6.10.7.1] with 31907 MB RAM
Game Version: v1.19.8 (Stable)
9/3/2024 10:50:38 PM: Critical error occurred
Loaded Mods: ancientarmory@1.0.5, bettercrates@1.7.1, explosive@0.0.3, decor@1.1.4, extrachestsfantasyedition@1.9.0, fantasycreatures@0.7.1, fixedpaths@1.0.1, pantherinae@1.1.9, foundrymod@1.0.0, mannequinstand@1.0.3, millwright@1.1.6, moreicons_cs@1.1.0, primitivesurvival@3.6.1, shinglesandthethings@1.0.2-rc.1, saltandsands@1.0.2, spyglass@0.5.1, swordz@1.1.7, translocatorengineeringredux@1.5.1, game@1.19.8, weaponpackalphaunoff@1.5.1, ancienttools@1.5.18, animalcages@3.0.2, betterfirepit@1.1.4, betterjonasdevices@1.1.0, betterruins@0.3.7, butterflycases@1.0.1, carryon@1.7.4, decayingcreatures@0.0.5, expandedfoods@1.6.9, fairplayguardian@1.1.7, furniturelibrary@1.0.11, hangingbaskets@1.1.0, heatretention@1.0.2, medievalexpansion@3.13.1, morepiles@1.5.0, moreplaster@1.0.1, pelaguswinds@1.0.0, prospecttogether@1.3.0, rivers@2.7.0, simplefootstepsredux@1.0.0, sleepvote@1.0.7, stonebakeoven@1.1.3, tentbag@2.1.1, th3dungeon@0.2.1, thecritterpack@0.8.9, typing_indicator@1.1.2, usefulstuff17@1.3.1, creative@1.19.8, vsinstruments@1.2.7, vsquest@1.2.0, vsserverpanel@0.1.5, survival@1.19.8, workbenchexpansion@1.8.0, awearablelight@1.1.1, cob2@1.6.6, em@2.6.1, outerspacetunesvolume1@1.0.2, outerspacetunesvolume2@1.0.2, wolftaming@2.1.2, bricklayers@2.5.6, cob@1.9.5, outerspacetunesmaster@1.0.2, vsvillagecob@0.2.0
System.Exception: Don't know how to instantiate item of class 'ExpandedFood' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass) in VintagestoryLib\Common\ClassRegistry.cs:line 274
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType packet, IWorldAccessor world, ClassRegistry registry) in VintagestoryLib\Common\Network\ItemTypeNet.cs:line 195
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(List`1 items, Int32 listSize) in VintagestoryLib\Client\Systems\Startup.cs:line 570
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes() in VintagestoryLib\Client\Systems\Startup.cs:line 388
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in VintagestoryLib\Client\Systems\Startup.cs:line 341
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by Craluminum2413** [comment]
Could you try without mods?

**Comment by Roy001-sudo** [comment]
> Could you try without mods?

Yep, Game works without mods

**Comment by Craluminum2413** [comment]
Oh i see it is caused by mod ExpandedFoods
