### ISSUE TITLE
my game crash when i try to launch a game or create a new one

### ISSUE THREAD

**Issue by ketso31** [anegostudios/VintageStory-Issues#4065]
### Game Version

v1.19.8

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

I can lauch vintage story normaly but when i try to launch a previous game or create a new one, the game crash. I hadn't this problem until my holydays. When i come back this problem immediatly start.  Im on 1.19.8 with no mods.

### Logs

```Log```Running on 64 bit Windows 10.0.22631.0 with 16228 MB RAM
Game Version: v1.19.8 (Stable)
04/09/2024 19:39:00: Critical error occurred
Loaded Mods: game@1.19.8, creative@1.19.8, survival@1.19.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockBehaviorJonasGasifier.<>c__DisplayClass2_0.<OnLoaded>b__0() in VSSurvivalMod\Lore\ResoArchives\BlockBehaviorJonasGasifier.cs:line 29
   at Vintagestory.API.Util.ObjectCacheUtil.GetOrCreate[T](ICoreAPI api, String key, CreateCachableObjectDelegate`1 onRequireCreate) in VintagestoryApi\Util\ObjectCacheUtil.cs:line 24
   at Vintagestory.GameContent.BlockBehaviorJonasGasifier.OnLoaded(ICoreAPI api) in VSSurvivalMod\Lore\ResoArchives\BlockBehaviorJonasGasifier.cs:line 25
   at Vintagestory.API.Common.CollectibleObject.OnLoaded(ICoreAPI api) in VintagestoryApi\Common\Collectible\Collectible.cs:line 270
   at Vintagestory.API.Common.Block.OnLoaded(ICoreAPI api) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 396
   at Vintagestory.API.Common.CollectibleObject.OnLoadedNative(ICoreAPI api) in VintagestoryApi\Common\Collectible\Collectible.cs:line 261
   at Vintagestory.Client.NoObf.ClientSystemStartup.OnAllAssetsLoaded_Blocks(Int32 i) in VintagestoryLib\Client\Systems\Startup.cs:line 952
   at Vintagestory.Client.NoObf.ClientSystemStartup.<>c__DisplayClass53_0.<OnAllAssetsLoaded_ClientSystems>b__1() in VintagestoryLib\Client\Systems\Startup.cs:line 942
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 746
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 293
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by ketso31** [comment]
I just reinstall the game and it solved it self.
