### ISSUE TITLE
Crash when I open inventory

### ISSUE THREAD

**Issue by Genkelly** [anegostudios/VintageStory-Issues#4080]
### Game Version

1.19

### Platform

Windows

### Modded

Modded

### SP/MP

None

### Logs

Running on 64 bit Windows 10.0.19045.0 with 65489 MB RAM
Game Version: v1.19.8 (Stable)
9/11/2024 7:33:38 PM: Critical error occurred in the following mod: sortablestorage@1.8.0
Loaded Mods: bettercrates@1.6.0, bettertraders@0.0.2, composter@1.0.4, cralutweaks@1.0.2, extraclayforming@1.0.0, HoneyPress@1.1.2, mcd1@1.0.0, moreclay@1.0.1, moreflaxloot@1.0.1, morenails@1.1.0, OresAPlenty@3.1.0, roas@1.0.0, sortablestorage@1.8.0, tieredsoil@1.0.0, game@1.19.8, wildcraft@1.6.6, betterruins@0.3.7, carryon@1.7.4, commonlib@2.5.0-rc.2, fendragonbcs@0.0.8, fromgoldencombs@1.4.16-rc.2, hudclock@3.4.0, knapster@2.11.2, claywheel@1.1.1, prospecttogether@1.3.0, creative@1.19.8, survival@1.19.8, xlib@0.8.6, stonequarry@3.3.1, xskills@0.8.8, wildcraftxskillspatch@0.2.0
System.MissingFieldException: Field not found: 'Vintagestory.API.Client.ItemRenderInfo.ModelRef'.
   at SortableStorage.ModSystem.BlockGenericSortableTypedContainer.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 315
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Single dt, Boolean shading, Boolean origRotate, Boolean showStackSize) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 194
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 509
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 716
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 385
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 318
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 9/11/2024 7:30:02 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x203c
Faulting application start time: 0x01db04bb86ee1ebc
Faulting application path: C:\Users\Alpha\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Alpha\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: c5b7301a-e83a-4692-8347-33fcd2ec8032
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 9/8/2024 8:28:46 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x1748
Faulting application start time: 0x01db02038f96a354
Faulting application path: C:\Users\Alpha\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Alpha\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 19c4dabf-3bef-44c4-847a-2093ebe3165e
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 9/8/2024 8:27:08 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0xa5c
Faulting application start time: 0x01db01ffc1512bfb
Faulting application path: C:\Users\Alpha\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Alpha\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: a4b5abf0-1a4f-4663-a4fc-78b55ebabe1e
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Caused by mod sortable storage
