### ISSUE TITLE
Crash on attaching anything to sailboat's halyard cleat

### ISSUE THREAD

**Issue by Erik3003** [anegostudios/VintageStory-Issues#4093]
### Game Version

v1.20-pre.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Game crash on trying to apply (CTRL-Right Click) ratlines to (kapok-)sailboat

### How to reproduce

1. Place sailboat from creative inventory
2. CTRL-Right Click ratline in hand on ship on the part of the mast with the line (see screenshot)

### Screenshots

![2024-09-18_19-38-26](https://github.com/user-attachments/assets/94397887-7b18-430f-ab5a-566fd933a07c)

### Logs

```Running on 64 bit Windows 10.0.22631.0 with 31894 MB RAM
Game Version: v1.20.0-pre.1 (Unstable)
18.09.2024 19:35:16: Critical error occurred
Loaded Mods: game@1.20.0-pre.1, creative@1.20.0-pre.1, survival@1.20.0-pre.1
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.EntityBehaviorAttachable.TryAttach(ItemSlot itemslot, Int32 slotIndex) in VSSurvivalMod\Entity\Behavior\BehaviorAttachable.cs:line 270
   at Vintagestory.GameContent.EntityBehaviorAttachable.OnInteract(EntityAgent byEntity, ItemSlot itemslot, Vec3d hitPosition, EnumInteractMode mode, EnumHandling& handled) in VSSurvivalMod\Entity\Behavior\BehaviorAttachable.cs:line 223
   at Vintagestory.GameContent.EntityBehaviorRideableAccessories.OnInteract(EntityAgent byEntity, ItemSlot itemslot, Vec3d hitPosition, EnumInteractMode mode, EnumHandling& handled) in VSSurvivalMod\Entity\Behavior\BehaviorRideableAccessories.cs:line 47
   at Vintagestory.GameContent.EntityBoat.OnInteract(EntityAgent byEntity, ItemSlot itemslot, Vec3d hitPosition, EnumInteractMode mode) in VSSurvivalMod\Systems\Boats\EntityBoat.cs:line 475
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 394
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 819
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1023
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 694
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 669
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by maltiez2** [comment]
Can't reproduce in pre.10

**Comment by Haplo164** [comment]
I just did some testing in 1.20.1 and I can get it to crash by placing a chest spawned with `/giveitem chest-east`, but placing and picking up the chest then placing on the ship does not cause a crash.

**Comment by Craluminum2413** [comment]
@Haplo164 If you can't reproduce it in survival, then it won't crash in normal gameplay

**Comment by Haplo164** [comment]
I was in survival but I get the point, I still think its worth looking into since its a hard crash but it's pretty low priority.
