### ISSUE TITLE
Client instant crash when running vintagestoryserver.exe in separate process

### ISSUE THREAD

**Issue by Monkeybrain73** [anegostudios/VintageStory-Issues#4108]
### Game Version

v1.20.0 pre1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Starting VintageStoryServer.exe before the client, instantly crashes the client when trying to start.

### How to reproduce

1. Start VintageStoryServer.exe
2. Start VintageStory.exe

### Logs

```Running on 64 bit Windows 10.0.19045.0 with 32701 MB RAM
Game Version: v1.20.0-pre.1 (Unstable)
19.09.2024 11:38:22: Critical error occurred
Loaded Mods: 
System.IO.IOException: The process cannot access the file 'D:\Vintagestory\1.20-pre1\Data\Logs\server-main.log' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadLines(String path)
   at Vintagestory.Logger.GetSessionTimeStamp(String logFile) in VintagestoryLib\Common\FileIO\Logger.cs:line 136
   at Vintagestory.Logger.ArchiveLogFiles(Int32 archiveLogFileCount, Int32 archiveLogFileMaxSize) in VintagestoryLib\Common\FileIO\Logger.cs:line 89
   at Vintagestory.Logger..ctor(String program, Boolean clearOldFiles, Int32 archiveLogFileCount, Int32 archiveLogFileMaxSize) in VintagestoryLib\Common\FileIO\Logger.cs:line 52
   at Vintagestory.ClientLogger..ctor() in VintagestoryLib\Client\Util\ClientLogger.cs:line 12
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 165
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Monkeybrain73** [comment]
The same happens if you start the client first, then try to start vintagestoryserver.exe after, then the server will instantly crash

**Comment by Th3Dilli** [comment]
thank you

this was fixed in pre2
