### ISSUE TITLE
Game keeps crashing, probably related to a mod

### ISSUE THREAD

**Issue by Raybro29** [anegostudios/VintageStory-Issues#4126]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

None

### Description

My game has started to recently crash on me regularly, though I'm not sure what's causing it. One time a drifter threw a rock at me, other times I just go to sleep, or just seemingly randomly within the first few seconds of opening my world. I suspect it has something to do with one of my mods, though I'm not sure what. Rather than try and brute force it, I was hoping that i can be told what mod is causing the issue so I can disable it

### How to reproduce

No idea, just seems to happen randomly

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32699 MB RAM
Game Version: v1.19.8 (Stable)
9/20/2024 1:43:56 PM: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.5, alchemytrader@1.0.1, balancedthirst@0.0.42, irregularguybetterjam@1.0.0, bettertraders@0.0.7, flourbags@1.0.4, gildedsteel@1.0.5, HangingOilLamps@1.0.1, japanesemod@1.3.6, natshumanskin@1.0.0, primitivesurvival@3.6.5, roas@1.0.0, Rotcreatures@1.0.3, saltandsands@1.0.2, spyglass@0.5.1, TVSM@0.0.1, traderssellborax@1.0.1, game@1.19.8, weaponpackalphaunoff@1.5.2, alchemy@1.6.32, animalcages@3.0.3, animationmanagerlib@0.8.8, egocaribautomapmarkers@3.1.0, flags@0.33.1, beartrap@1.1.1, beehivekiln@1.6.1, betterfirepit@1.1.4, betterruins@0.3.7, biggercellars@1.0.0, carryon@1.7.4, commonlib@2.5.0-rc.2, decayingcreatures@0.0.7, doubleslabs@0.1.1, electricity@0.0.11, expandedfoods@1.6.9, foodshelves@1.3.0, fromgoldencombs@1.6.3, herbarium@1.3.0, hudclock@3.4.0, kegrevivedagain@1.1.0, krpgenchantment@0.4.5, maltiezbows@1.0.4, meteoricexpansion@1.2.5, morepiles@1.5.0, outlawmod@1.2.3, petai@2.2.6, claywheel@1.1.1, rivers@3.1.0, rustboundmagic@1.9.74, sailboat@1.3.1, simplefootstepsredux@1.0.0, slidingdoor@1.0.0, somethinginthewater@1.2.4, spawnersapi@1.0.9, stonebakeoven@1.1.3, storageoptions@1.0.2, th3dungeon@0.2.1, versionchecker@1.0.0, vmetp@1.1.1, creative@1.19.8, vsimgui@1.1.5, vsinstruments@1.2.7, vsquest@1.2.0, survival@1.19.8, vsvillage@1.0.6, wildfarmingrevival@1.2.5, xlib@0.8.6, awearablelight@1.1.1, battletowers@1.0.3, bullseye-continued@2.5.8, cats@2.0.3, configlib@1.3.13, electricityaddon@0.0.7, electricityextensions@0.0.7, em@2.7.0, feverstonehorses@1.6.1, foxtaming@1.4.0, fsmlib@0.4.5, helvehammerext@1.6.0, morefloors@2.1.1, playercorpse@1.10.1-rc.1, simplewinddirection@1.0.2, wildcraftfruit@1.2.2, wildcraftherb@0.0.1, wildcrafttree@1.2.0, wolftaming@2.1.3, maltiezcrossbows@0.3.11, maltiezfirearms@0.5.4
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.FastParticlePool.Kill(ParticleBase elem) in VintagestoryLib\Client\Systems\Render\Particle\IParticlePool.cs:line 79
   at Vintagestory.Client.NoObf.ParticlePoolQuads.OnNewFrame(Single dt, Vec3d cameraPos) in VintagestoryLib\Client\Systems\Render\Particle\ParticlePoolQuads.cs:line 272
   at Vintagestory.Client.NoObf.SystemRenderParticles.Render(Int32 poolindex, Single dt) in VintagestoryLib\Client\Systems\Render\Particle\RenderParticles.cs:line 193
   at Vintagestory.Client.NoObf.SystemRenderParticles.OnRenderFrame3DOIT(Single deltaTime) in VintagestoryLib\Client\Systems\Render\Particle\RenderParticles.cs:line 186
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 9/20/2024 11:36:59 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x3614
Faulting application start time: 0x01db0b8baaca86c0
Faulting application path: C:\Users\Jacob Lopez\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Jacob Lopez\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 27106801-342b-4897-a626-8cee18c0ffae
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Does it happen without any mods?

**Comment by Raybro29** [comment]
I just made the time to test the game out without mods for a solid hour and
it runs perfectly fine, no crashes whatsoever.
I know for a fact that it has to be at least one of my mods that is causing
the issue, but I was hoping that maybe I could be told which mod is causing
the crashes instead of me having to brute force it ^^;

**Comment by sekelsta** [comment]
We can't tell you that any easier than you can tell us. To find out which mod, try removing half and see if it still happens, if it does then repeat from a smaller list of suspect mods.
