### ISSUE TITLE
A crash on launch

### ISSUE THREAD

**Issue by 4193883-eng** [anegostudios/VintageStory-Issues#4135]
### Game Version

v1.19.8 (Stable)

### Platform

Mac

### Modded

None

### SP/MP

Singleplayer

### Description

So it basically doesn't launch, the resolution changes and then goes back to normal and nothing happens. 

### How to reproduce

1. Download Game from website
2. Double-click it.
3. Doesn't launch

### Logs

```
Game Version: v1.19.8 (Stable)
21.09.2024 20:57:34: Critical error occurred
Loaded Mods: 
System.Exception: sdfb-begin  - OpenGL threw an error: InvalidEnum
   at Vintagestory.Client.NoObf.ClientPlatformWindows.CheckGlError(String errmsg) in VintagestoryLib\Client\ClientPlatform\GLImpl.cs:line 68
   at Vintagestory.Client.NoObf.ClientPlatformWindows.SetupDefaultFrameBuffers() in VintagestoryLib\Client\ClientPlatform\GLFramebuffer.cs:line 188
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Start() in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 410
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 319
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
   
```client-main.txt```
21.9.2024 20:57:30 [Notification] Client logger started.
21.9.2024 20:57:30 [Notification] Game Version: v1.19.8 (Stable)
21.9.2024 20:57:31 [Notification] Process path: /private/var/folders/bq/98ld7fv12r3fx2l6yqd8s2hr0000gn/T/AppTranslocation/E29E2BF9-BA91-4ED7-86D8-F26219627DD9/d/vintagestory.app/Vintagestory
21.9.2024 20:57:31 [Notification] Operating System: Mac 15.0.0
21.9.2024 20:57:31 [Notification] CPU Cores: 8
21.9.2024 20:57:31 [Notification] Available RAM: 16384 MB
21.9.2024 20:57:31 [Notification] C# Framework: .net 7.0.15
21.9.2024 20:57:31 [Notification] Cairo Graphics Version: 1.17.6
21.9.2024 20:57:34 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: /
21.9.2024 20:57:34 [Notification] Graphics Card Vendor: Apple
21.9.2024 20:57:34 [Notification] Graphics Card Version: 4.1 Metal - 89.3
21.9.2024 20:57:34 [Notification] Graphics Card Renderer: Apple M1
21.9.2024 20:57:34 [Notification] Graphics Card ShadingLanguageVersion: 4.10
21.9.2024 20:57:34 [Notification] GL.MaxVertexUniformComponents: 4096
21.9.2024 20:57:34 [Notification] GL.MaxUniformBlockSize: 65536
21.9.2024 20:57:34 [Notification] OpenAL Version: 1.1
21.9.2024 20:57:34 [Notification] Zstd Version: 1.5.5
21.9.2024 20:57:34 [Error] GLFW Exception: ErrorCode:PlatformError Raw mouse motion is not supported on this system
21.9.2024 20:57:34 [Notification] Start discovering assets
21.9.2024 20:57:34 [Notification] Found 25 base assets in category lang
21.9.2024 20:57:34 [Notification] Found 0 base assets in category patches
21.9.2024 20:57:34 [Notification] Found 24 base assets in category config
21.9.2024 20:57:34 [Notification] Found 0 base assets in category worldproperties
21.9.2024 20:57:34 [Notification] Found 48 base assets in category sounds
21.9.2024 20:57:34 [Notification] Found 95 base assets in category shapes
21.9.2024 20:57:34 [Notification] Found 72 base assets in category shaders
21.9.2024 20:57:34 [Notification] Found 16 base assets in category shaderincludes
21.9.2024 20:57:34 [Notification] Found 133 base assets in category textures
21.9.2024 20:57:34 [Notification] Found 4 base assets in category music
21.9.2024 20:57:34 [Notification] Found 0 base assets in category dialog
21.9.2024 20:57:34 [Notification] Found 417 base assets in total
21.9.2024 20:57:34 [Notification] Loading sounds
21.9.2024 20:57:34 [Notification] Sounds loaded
21.9.2024 20:57:34 [Fatal] Game Version: v1.19.8 (Stable)
21.09.2024 20:57:34: Critical error occurred
Loaded Mods: 
System.Exception: sdfb-begin  - OpenGL threw an error: InvalidEnum
   at Vintagestory.Client.NoObf.ClientPlatformWindows.CheckGlError(String errmsg) in VintagestoryLib\Client\ClientPlatform\GLImpl.cs:line 68
   at Vintagestory.Client.NoObf.ClientPlatformWindows.SetupDefaultFrameBuffers() in VintagestoryLib\Client\ClientPlatform\GLFramebuffer.cs:line 188
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Start() in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 410
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 319
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Crash written to file at "/Users/vsevolodlavrusha/.config/VintagestoryData/Logs/client-crash.txt"

21.9.2024 20:57:34 [Notification] Exiting game now. Server running=False. Exit reason: Game crashed

```

**Comment by Craluminum2413** [comment]
Update, downgrade or reinstall your graphics drivers

**Comment by 4193883-eng** [comment]
I have mac, so that's pretty much impossible???

**Comment by Craluminum2413** [comment]
@4193883-eng sorry, but crash is related to graphics drivers

**Comment by 4193883-eng** [comment]
опа українка! не думав що зустріну когось з України тут! @Craluminum2413

**Comment by 4193883-eng** [comment]
нічого страшного

**Comment by Craluminum2413** [comment]
Closing due to inactivity

**Comment by Craluminum2413** [comment]
Accidentally closed

**Comment by madpanda3345** [comment]
hay my friend is having the same issue on windows 10 we tried all the fixes posseted but non have worked?
