### ISSUE TITLE
Crashed once and now cannot connect to server.

### ISSUE THREAD

**Issue by Nzl-ironic** [anegostudios/VintageStory-Issues#4149]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Was just playing as normal on hosted server with friends and it randomly crashed now when i connect i get the following error logs;

### How to reproduce

was able to replicate the crash every time i tried logging into the server.
can login to single player no problems.
tried with firewall disabled and enabled no change.
might pay to mention when trying to connect to server i have a chance of causing the others logged in to crash as well but they can reconnect no issues.

have reinstalled, deleted the data file as well. no change.

Do not believe it is a server issue as this is only affecting me so that part is nice.

any assistance here be great

### Logs
```
Running on 64 bit Windows 10.0.22631.0 with 16285 MB RAM
Game Version: v1.19.8 (Stable)
23/09/2024 12:29:30 pm: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.5, buildingplus@1.1.2, chiseltools@1.12.4, decor@1.1.5, materialaging@1.1.0, moreclasses@1.2.5, MoreTorchHolders@1.0.0, primitivesurvival@3.6.4, rope-bridges@1.1.0, rpgitemrarity@1.0.4, rpvoicechat@2.3.9, swordz@1.1.8, temporal_gears_stack@1.0.0, game@1.19.8, animalcages@3.0.2, beehivekiln@1.6.1, betterfirepit@1.1.4, betterruins@0.3.7, blacksmithenhancements@1.0.5, butchering@1.6.5, carryon@1.7.4, coinage@1.10.2, commonlib@2.5.0-rc.2, cooperativecombat@1.1.1, danacancook@0.2.1, expandedfoods@1.7.0, fromgoldencombs@1.6.3, krpgenchantment@0.4.4, lichenredux@1.8.3, medievalexpansion@3.13.1, nbcartographer@2.0.10, petai@2.2.6, claywheel@1.1.1, rivers@3.1.0, sailboat@1.3.1, stillnecessaries@1.1.2, stonerailings@1.2.2, th3dungeon@0.2.1, creative@1.19.8, survival@1.19.8, vsvillage@1.0.6, workbenchexpansion@1.8.0, xlib@0.8.6, awearablelight@1.1.1, helvehammerext@1.6.0, laverace@1.0.3, morecandles@1.2.2, xskills@0.8.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.RenderAPIBase.RenderMultiTextureMesh(MultiTextureMeshRef mmr, String textureSampleName, Int32 textureNumber) in VintagestoryLib\Client\API\RenderAPIBase.cs:line 107
   at Vintagestory.GameContent.EntityShapeRenderer.RenderHeldItem(Single dt, Boolean isShadowPass, Boolean right) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 558
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.RenderHeldItem(Single dt, Boolean isShadowPass, Boolean right) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 280
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 224
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderOpaque3D(Single deltaTime) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 92
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 200
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 806
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 901
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 730
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 23/09/2024 12:13:24 pm, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x1c20
Faulting application start time: 0x0x1db0d4d24c94494
Faulting application path: C:\Users\Dylan\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Dylan\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 7305577e-d6f6-4e63-b6e8-7f178a934362
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 23/09/2024 11:55:13 am, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0xd08
Faulting application start time: 0x0x1db0d4aaf31022e
Faulting application path: C:\Users\Dylan\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Dylan\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 5e3fe8ea-1866-45fa-b9c7-ba1b368e06df
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 23/09/2024 11:49:16 am, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x1370
Faulting application start time: 0x0x1db0d48b1d56e5b
Faulting application path: C:\Users\Dylan\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Dylan\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 61b32763-4f90-4fcc-ac0f-09d83efc100c
Faulting package full name: 
Faulting package-relative application ID:  }
```

**Comment by Nzl-ironic** [comment]
reattempted uninstalling but also included nuking anything to do with vintage story out of windows registry files and reinstalling.

same error downloads mods attempts to reconnect and then crashes again logs are identical as well

**Comment by Craluminum2413** [comment]
Most likely caused by some mod

**Comment by Nzl-ironic** [comment]
would that not cause everyone on the server to also have the same error? only ask cause its only me affected the others can log in fine

**Comment by Nzl-ironic** [comment]
issue is now fixed - Fault was determined by a mod that allowed us to share map markers, appears to be specific to sharing a marker with the ladder as an icon we disabled using that marker and things are good now
