### ISSUE TITLE
crash on world load

### ISSUE THREAD

**Issue by whitewerewolf87** [anegostudios/VintageStory-Issues#4171]
### Game Version

1.19.8

### Platform

None

### Modded

Modded

### SP/MP

Singleplayer

### Logs

Running on 64 bit Windows 10.0.22631.0 with 32598 MB RAM
Game Version: v1.19.8 (Stable)
27/09/2024 15:00:23: Critical error occurred in the following mod: primitivesurvival@3.6.6
Loaded Mods: primitivesurvival@3.6.6, game@1.19.8, betterruins@0.3.7, creative@1.19.8, survival@1.19.8
System.MissingMethodException: Method not found: 'Void Vintagestory.Client.NoObf.ShaderProgramBase.set_AssetDomain(System.String)'.
   at PrimitiveSurvival.ModSystem.PrimitiveSurvivalSystem.LoadCustomShaders()
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerReloadShaders() in VintagestoryLib\Client\Util\ClientEventManager.cs:line 432
   at Vintagestory.Client.NoObf.ShaderAPI.ReloadShaders() in VintagestoryLib\Client\API\ShaderAPI.cs:line 53
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerReady(Packet_Server packet) in VintagestoryLib\Client\Systems\Startup.cs:line 881
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 448
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 442
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 27/09/2024 14:58:01, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x5a9c
Faulting application start time: 0x0x1db10d4212e4458
Faulting application path: C:\Users\anton\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\anton\Vintagestory\Lib\openal32.dll
Report Id: c5e06eff-d8a4-4c48-9cd7-5b51dca9a7f8
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 27/09/2024 14:55:14, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0xacc
Faulting application start time: 0x0x1db10d40f9067e7
Faulting application path: C:\Users\anton\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\anton\Vintagestory\Lib\openal32.dll
Report Id: 2e6e851d-eb42-4ad7-90af-ef3554b85604
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 27/09/2024 14:54:42, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x5a70
Faulting application start time: 0x0x1db10d3e79f0901
Faulting application path: C:\Users\anton\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\anton\Vintagestory\Lib\openal32.dll
Report Id: d70981f7-f7b2-43ec-9073-bd7bbd151977
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Marcafk** [comment]
The version of primitive survival you are running is only for game version 1.20. The mod page states this multiple times.
