### ISSUE TITLE
crash at game load

### ISSUE THREAD

**Issue by whitewerewolf87** [anegostudios/VintageStory-Issues#4174]
### Game Version

v1.19.8

### Platform

Windows

### Modded

None

### SP/MP

None

### Logs
```
Running on 64 bit Windows 10.0.22631.0 with 32598 MB RAM
Game Version: v1.19.8 (Stable)
27/09/2024 20:59:27: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: The driver does not appear to support OpenGL
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings) in VintagestoryLib\Client\ClientPlatform\GameWindowNative.cs:line 14
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 281
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 27/09/2024 15:11:54, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x4ef0
Faulting application start time: 0x0x1db10d65c943f50
Faulting application path: C:\Users\anton\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\anton\Vintagestory\Lib\openal32.dll
Report Id: 5731e8f0-a286-49df-adda-9cdda4b973d6
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 27/09/2024 15:10:52, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.4111, time stamp: 0x03c619d0
Exception code: 0xe0434352
Fault offset: 0x000000000005fabc
Faulting process id: 0x0x4c28
Faulting application start time: 0x0x1db10d6453607c4
Faulting application path: C:\Users\anton\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: a39339eb-4cf0-4a09-8994-e8c1de217788
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 27/09/2024 15:07:43, Site = , Source = Application Error, Message = Faulting application name: VintageStory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x5b44
Faulting application start time: 0x0x1db10d4c109088e
Faulting application path: C:\Users\anton\Vintagestory\VintageStory.exe
Faulting module path: C:\Users\anton\Vintagestory\Lib\openal32.dll
Report Id: dc8dff3b-367e-4e93-bbca-4d42d4269bcf
Faulting package full name: 
Faulting package-relative application ID:  }
```

**Comment by Craluminum2413** [comment]
Update, downgrade or reinstall your graphics drivers
