### ISSUE TITLE
Crash when starting the game

### ISSUE THREAD

**Issue by CharsCov256** [anegostudios/VintageStory-Issues#4180]
### Game Version

v1.19.8

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

When I select the game and open it, it gives me an erro and won´t let me enter.

### Logs

```
Running on 64 bit Windows 10.0.19045.0 with 7990 MB RAM
Game Version: v1.19.8 (Stable)
28/09/2024 03:04:49 p. m.: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: OpenGL profile requested but WGL_ARB_create_context_profile is unavailable
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings) in VintagestoryLib\Client\ClientPlatform\GameWindowNative.cs:line 14
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 281
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Craluminum2413** [comment]
Update, downgrade or reinstall your graphics drivers
