### ISSUE TITLE
Game crash related to creative inventory (when there are tabs on the right)

### ISSUE THREAD

**Issue by SpearAndFang** [anegostudios/VintageStory-Issues#4191]
### Game Version

v1.20 pre 4

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Game crashes when using the creative inventory.  Seems to be tied to the number of tabs attached to the gui.   Tabs on the left - ok.  Tabs on the right - the game crashes relatively quickly.

I don't believe that this is mod specific.

### How to reproduce

1. add enough mods so that at least one tab appears on the right side of the creative inventory gui.
2. use the creative inventory for a bit.  Maybe open and close it a few times.  Click on a tab on the right.
3. Before long, when you open the creative inventory, the game crashes

### Screenshots

![Untitled](https://github.com/user-attachments/assets/f5fb8df3-af6a-4388-9286-56e558af4e26)

### Logs
```
Running on 64 bit Windows 10.0.22631.0 with 32565 MB RAM
Game Version: v1.20.0-pre.4 (Unstable)
2024-09-30 9:26:38 AM: Critical error occurred
Loaded Mods: buzzwords@1.7.0, millwright@1.1.7, primitivesurvival@3.6.7, sortablestorage@2.2.7, translocatorengineeringredux@1.5.2, game@1.20.0-pre.4, zoombuttonreborn@1.9.0, carryon@1.7.4, hudclock@3.4.0, natsachievements@1.1.0, stepupcontinued@0.0.1, creative@1.20.0-pre.4, vsimgui@1.1.5, survival@1.20.0-pre.4, configlib@1.3.13
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.Client.GuiElementVerticalTabs.SetValue(Int32 index, Boolean triggerHandler) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementVerticalTabs.cs:line 309
   at Vintagestory.Client.NoObf.GuiDialogInventory.ComposeCreativeInvDialog() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 248
   at Vintagestory.Client.NoObf.GuiDialogInventory.ComposeGui(Boolean firstBuild) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 91
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnGuiOpened() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 444
   at Vintagestory.API.Client.GuiDialog.TryOpen(Boolean withFocus) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 289
   at Vintagestory.API.Client.GuiDialog.TryOpen() in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 269
   at Vintagestory.Client.NoObf.GuiDialogInventory.TryOpen() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 437
   at Vintagestory.API.Client.GuiDialog.Toggle() in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 343
   at Vintagestory.API.Client.GuiDialog.OnKeyCombinationToggle(KeyCombination viaKeyComb) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 410
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnKeyCombinationToggle(KeyCombination viaKeyComb) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 541
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean isGlobal, Boolean fallBack, Boolean keyup) in VintagestoryLib\Client\HotkeyManager.cs:line 431
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1744
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 230
   at OpenTK.Windowing.Desktop.NativeWindow.KeyCallback(Window* window, Keys key, Int32 scancode, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by maltiez2** [comment]
Will be fixed in next update
