### ISSUE TITLE
Game crash when walking into a ladder above opened fence gate

### ISSUE THREAD

**Issue by RudyYelen** [anegostudios/VintageStory-Issues#4199]
### Game Version

v1.20.0-pre.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Walking into a ladder above a fence gate crashes the game

### How to reproduce

1. Place a ladder above a fence gate
2. Open fence gate
3. Try climb ladder

### Screenshots

![2024-10-01_11-05-48](https://github.com/user-attachments/assets/591480b7-3b88-45e9-8160-06264681f115)

### Logs
```
Running on 64 bit Windows 10.0.19045.0 with 16262 MB RAM
Game Version: v1.20.0-pre.4 (Unstable)
01.10.2024 10:54:10: Critical error occurred
Loaded Mods: game@1.20.0-pre.4, creative@1.20.0-pre.4, survival@1.20.0-pre.4
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.FindSteppableCollisionboxSmooth(Cuboidd entityCollisionBox, Cuboidd entitySensorBox, Double motionY, Vec3d walkVector) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 674
   at Vintagestory.GameContent.EntityBehaviorPlayerPhysics.HandleSteppingOnBlocks(EntityPos pos, Vec3d moveDelta, Single dtFac, EntityControls controls) in VSEssentials\Entity\Behavior\BehaviorPlayerPhysics.cs:line 393
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.ApplyTests(EntityPos pos, EntityControls controls, Single dt, Boolean remote) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 229
   at Vintagestory.GameContent.EntityBehaviorPlayerPhysics.SimPhysics(Single dt, EntityPos pos) in VSEssentials\Entity\Behavior\BehaviorPlayerPhysics.cs:line 243
   at Vintagestory.GameContent.EntityBehaviorPlayerPhysics.OnRenderFrame(Single dt, EnumRenderStage stage) in VSEssentials\Entity\Behavior\BehaviorPlayerPhysics.cs:line 326
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 819
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 825
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 741
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 207
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 694
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 669
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by maltiez2** [comment]
Should be fixed in next update
