### ISSUE TITLE
v1.20.0-pre.4 Server crash on player connect. (World/inventory corruption?)

### ISSUE THREAD

**Issue by AbortRetryFail** [anegostudios/VintageStory-Issues#4202]
### Game Version

v1.20.0-pre.4

### Platform

Linux

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

I first encountered this error not long after reporting #4200 , Now any time my player "ARF" joins the server, the game server crashes with this log message. I copied the world to my local machine and started it single player and it still crashes with the same error. Maybe whatever I did messing with that reed basket corrupted my player's inventory or the world's files?

It's only when "ARF" joins. The other person I'm playing with is still able to connect and play the game.

The world was started as 1.20.0-pre.2 and upgraded to 1.20.0-pre.4, but I've been able to play just fine for a while since then.

### How to reproduce

1. Be "ARF"
2. Connect to my broken world.
3. Get disconnected.

### Logs

On the client:
```Running on 64 bit Linux (Arch Linux) [Kernel 6.10.10.1] with 15965 MB RAM
Game Version: v1.20.0-pre.4 (Unstable)
10/1/2024 3:20:49PM: Critical error occurred
Loaded Mods: game@1.20.0-pre.4, creative@1.20.0-pre.4, survival@1.20.0-pre.4
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.Common.GameCalendar.getSunlightPixelRel(Single relx, Single rely) in VintagestoryLib\Common\GameCalendar.cs:line 494
   at Vintagestory.Common.ClientGameCalendar.Update() in VintagestoryLib\Common\ClientGameCalendar.cs:line 115
   at Vintagestory.Client.NoObf.SystemCalendar.Eventapi_LevelFinalize() in VintagestoryLib\Client\Systems\Calendar.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerLevelFinalize() in VintagestoryLib\Client\API\ClientEventAPI.cs:line 383
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleLevelFinalize(Packet_Server packet) in VintagestoryLib\Client\Systems\Startup.cs:line 1040
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\ProcessPacketTask.cs:line 16
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\ProcessPacketTask.cs:line 10
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 786
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 316
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 694
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 669
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

The server spews this, a lot:
```
1.10.2024 18:32:04 [Server Error] Exception: Index was outside the bounds of the array.                                                                                                                              
   at Vintagestory.Common.GameCalendar.getSunlightPixelRel(Single relx, Single rely) in VintagestoryLib\Common\GameCalendar.cs:line 494                                                                              
   at Vintagestory.Common.GameCalendar.GetDayLightStrength(Double x, Double z) in VintagestoryLib\Common\GameCalendar.cs:line 455                                                                                    
   at Vintagestory.GameContent.ModSystemRifts.GetRiftCap(String playerUid) in VSSurvivalMod\Systems\Rifts\Rifts.cs:line 291                                                                                          
   at Vintagestory.GameContent.ModSystemRifts.KillOldRifts(Dictionary`2 nearbyRiftsByPlayerUid) in VSSurvivalMod\Systems\Rifts\Rifts.cs:line 333                                                                     
   at Vintagestory.GameContent.ModSystemRifts.OnServerTick3s(Single dt) in VSSurvivalMod\Systems\Rifts\Rifts.cs:line 168                                                                                             
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27                                                                       
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57                                                           
   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Server\ServerEventManager.cs:line 123                                          
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 903
```

**Comment by AbortRetryFail** [comment]
Maybe this is also relevant?
```
1.10.2024 19:49:19 [Server Error] Exception: Index was outside the bounds of the array.                   
   at Vintagestory.Common.BlockAccessorBase.LoadChunksToCache(Int32 mincx, Int32 mincy, Int32 mincz, Int32
 maxcx, Int32 maxcy, Int32 maxcz, Action`3 onChunkMissing) in VintagestoryLib\Common\API\BlockAccessorBase
.cs:line 370                                                                                              
   at Vintagestory.Common.BlockAccessorBase.WalkBlocks(BlockPos minPos, BlockPos maxPos, Action`4 onBlock,
 Boolean centerOrder) in VintagestoryLib\Common\API\BlockAccessorBase.cs:line 277                         
   at Vintagestory.GameContent.EntityBehaviorBodyTemperature.OnGameTick(Single deltaTime) in VSSurvivalMod
\Entity\Behavior\BehaviorBodyTemperature.cs:line 122                                                      
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\Entit
y.cs:line 880                                                                                             
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityAge
nt.cs:line 567                                                                                            
   at Vintagestory.API.Common.EntityPlayer.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityPl
ayer.cs:line 676                                                                                          
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt) in VintagestoryLib\Server\S
ystems\World\EntitySimulation.cs:line 312                                                                 
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt) in VintagestoryLib\Server\S
ystems\World\EntitySimulation.cs:line 176                                                                 
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 903           
   ```
   
   I was able to reconnect by running `/player ARF wipedata`

**Comment by Craluminum2413** [comment]
Not even sure if it needs high priority, but I will label it as that because it is crash

**Comment by AbortRetryFail** [comment]
Probably not a high priority.

I've been playing for several hours since doing the `wipedata` without problems, so I'm leaning towards the cause of this being inventory corruption while experimenting with the reed basket on #4200. I still have the broken save file if the devs need it.
