### ISSUE TITLE
Random crash when updating transitionables

### ISSUE THREAD

**Issue by theCrius** [anegostudios/VintageStory-Issues#4225]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

I was doing a corpse run to retrieve my items in a small private multiplayer server and disconnected momentarily to do some stuff around the house.

When going back in, I realized I had forgotten something so, to not leave the character alone in the dark, disconnected immediately after the client finished connecting to the server.

I am relatively sure that it's been the quick “disconnect” while things were still loading that caused the issue.

### How to reproduce

As mentioned above, I can't be sure but connecting to a server and immediately disconnecting might reproduce the issue.

### Logs

```
Running on 64 bit Windows 10.0.19045.0 with 32620 MB RAM
Game Version: v1.19.8 (Stable)
04/10/2024 18:08:27: Critical error occurred
Loaded Mods: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2466
   at Vintagestory.API.Common.CollectibleObject.AppendPerishableInfoText(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1822
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1759
   at Vintagestory.API.Common.Block.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 2235
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(ICoreClientAPI capi, ItemStack stack) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 33
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onCreatePagesAsync() in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 79
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 418
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by Craluminum2413** [comment]
I will reopen if it happens in 1.20

**Comment by Aethandus** [comment]
How do you fix this issue?
