### ISSUE TITLE
Game cannot run on Wayland

### ISSUE THREAD

**Issue by TimovVeen** [anegostudios/VintageStory-Issues#4226]
### Game Version

v1.19.8

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

From what I've gathered the game should be able to run in Wayland natively, but I cannot get it to work. 
I have XDG_SESSION_TYPE set to wayland, which works for applications that use glfw. However, Vintage Story only launches in X11. When I remove the included glfw.so files, it does launch using Wayland, but crashes. I can reproduce this in both hyprland and tinywl, so it doesn't look like a compositor specific issue. Maybe the environment is not being passed to the runtime? When I try to force the game to use the discrete GPU with prime-run, it has no effect either.

### How to reproduce

[Environment variables](https://gist.github.com/TimovVeen/37ab95a1f14a123c586c8f7efb7d2b1b)
Game version: 1.19.8 or 1.20.0-pre4
OS: Linux 6.11.0-gentoo
WM: Hyprland (Wayland) + XWayland
.NET: dotnet-sdk-bin-7.0
- Extract tarball and execute run.sh
- The game will launch in X11 via Xwayland.
- Delete glfw .so files from Lib so native libraries are used
- The window is forced to use Wayland, and crashes with the errors below. 

### system GLFW 3.3.9 built with wayland only
```
Couldn't start NamedPipeServer.
4.10.2024 21:13:15 [Client Notification] Client logger started.
4.10.2024 21:13:15 [Client Notification] Game Version: v1.19.8 (Stable)
4.10.2024 21:13:16 [Client Notification] Process path: /home/timo/games/vintagestory/Vintagestory
4.10.2024 21:13:16 [Client Notification] Operating System: Linux (Gentoo Linux) [Kernel 6.11.0.0]
4.10.2024 21:13:16 [Client Notification] CPU Cores: 12
4.10.2024 21:13:16 [Client Notification] Available RAM: 63654 MB
4.10.2024 21:13:16 [Client Debug] Creating game window with window mode Fullscreen
4.10.2024 21:13:17 [Client Fatal] Game Version: v1.19.8 (Stable)
04/10/2024 21:13:16: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: Wayland: Focusing a window requires user interaction
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
Crashreport failed: System.UnauthorizedAccessException: Access to the path '/tmp/VSLastCrash.txt' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at Vintagestory.ClientNative.CrashReporter.Crash(Exception exCrash) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 212

4.10.2024 21:13:17 [Client Notification] Exiting game now. Server running=False. Exit reason: Game crashed
Unhandled exception. OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: Wayland: Focusing a window requires user interaction
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
./run.sh: line 3:  9439 Aborted                 DOTNET_ROOT=/opt/dotnet-sdk-bin-7.0/ ./Vintagestory
```

### system GLFW 3.4 X support disabled
```
Couldn't start NamedPipeServer.
4.10.2024 21:21:09 [Client Notification] Client logger started.
4.10.2024 21:21:09 [Client Notification] Game Version: v1.19.8 (Stable)
4.10.2024 21:21:09 [Client Notification] Process path: /home/timo/games/vintagestory/Vintagestory
4.10.2024 21:21:09 [Client Notification] Operating System: Linux (Gentoo Linux) [Kernel 6.11.0.0]
4.10.2024 21:21:09 [Client Notification] CPU Cores: 12
4.10.2024 21:21:09 [Client Notification] Available RAM: 63654 MB
4.10.2024 21:21:09 [Client Debug] Creating game window with window mode Fullscreen
4.10.2024 21:21:10 [Client Fatal] Game Version: v1.19.8 (Stable)
04/10/2024 21:21:10: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: Wayland: The platform does not provide the window position
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
Crashreport failed: System.UnauthorizedAccessException: Access to the path '/tmp/VSLastCrash.txt' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at Vintagestory.ClientNative.CrashReporter.Crash(Exception exCrash) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 212

4.10.2024 21:21:10 [Client Notification] Exiting game now. Server running=False. Exit reason: Game crashed
Unhandled exception. OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: Wayland: The platform does not provide the window position
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
./run.sh: line 3: 11827 Aborted                 DOTNET_ROOT=/opt/dotnet-sdk-bin-7.0/ ./Vintagestory
```
### vendored GLFW (launches successfully in Xwayland)
https://gist.github.com/TimovVeen/bcb1396f3c21b8ec8c671ecef0ca7b11

**Comment by Craluminum2413** [comment]
Does it happen in 1.20?

**Comment by TimovVeen** [comment]
Yes, it also happens on 1.20-pre4

**Comment by wqvi** [comment]
This is not exactly any help as my logs are effectively the same, however I have experienced the same issue. I am currently trying to finagle it into loading. It might involve patching GLFW to not throw an error at that moment. I am using Gentoo so I can apply the patch upon updating GLFW. I should mention I am using GLFW 3.4, the latest version in my distro. I tried with version 3.3.8 as well. If any help is needed I can lend a hand!

Here's the log:
```
Running on 64 bit Linux (Gentoo Linux) [Kernel 6.6.67.0] with 15716 MB RAM
Game Version: v1.20.1 (Stable)
1/24/2025 8:50:11PM: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: X11: The DISPLAY environment variable is missing
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
```

**Comment by TimovVeen** [comment]
Interesting, I suspected it might have something to do with glfw. I already have a number of patches applied to get wayland working for Minecraft (https://github.com/BoyOrigin/glfw-wayland). One of the patches has to do with applications asking to set the cursor position, which also isn't supported on wayland. Maybe a similar patch can be applied for the window position. 
I don't have much time right now to

**Comment by TimovVeen** [comment]
I did some very quick testing with the patch below, and I can get the game to start in wayland with 3.4 glfw X disabled by removing the vendored libs. 

```
diff --git a/src/wl_window.c b/src/wl_window.c
index 72c1a402..1938823d 100644
--- a/src/wl_window.c
+++ b/src/wl_window.c
@@ -2243,17 +2243,14 @@ void _glfwGetWindowPosWayland(_GLFWwindow* window, int* xpos, int* ypos)
 {
     // A Wayland client is not aware of its position, so just warn and leave it
     // as (0, 0)
-
-    _glfwInputError(GLFW_FEATURE_UNAVAILABLE,
-                    "Wayland: The platform does not provide the window position");
+    *xpos = 0;
+    *ypos = 0;
 }
 
 void _glfwSetWindowPosWayland(_GLFWwindow* window, int xpos, int ypos)
 {
     // A Wayland client can not set its position, so just warn
 
-    _glfwInputError(GLFW_FEATURE_UNAVAILABLE,
-                    "Wayland: The platform does not support setting the window position");
 }
 
 void _glfwGetWindowSizeWayland(_GLFWwindow* window, int* width, int* height)

```
On my 4K display the game is rendered in only a quarter of the window, even though the mouse registers the UI buttons in the correct positions. This might be an issue with my display however, since applications detect it as 1080p sometimes. Normally I use gamescope to fix this.
![Image](https://github.com/user-attachments/assets/92f5ba67-b1e3-4ca8-9dcf-3a38f79c8d04)

On my 1680x1050 display it seems to work fine in wayland though

**Comment by wqvi** [comment]
I forgot I had to remove the vendor libs to get it to use the system libraries. I applied the patch you sent, with the addition of the removal of the setting of the window icon. As I would get the error "Wayland: The platform does not support setting the window icon"

```
diff --git a/src/wl_window.c b/src/wl_window.c
index 5b491ffb..0ceb8a25 100644
--- a/src/wl_window.c
+++ b/src/wl_window.c
@@ -2227,8 +2227,8 @@ void _glfwSetWindowTitleWayland(_GLFWwindow* window, const char* title)
 void _glfwSetWindowIconWayland(_GLFWwindow* window,
                                int count, const GLFWimage* images)
 {
-    _glfwInputError(GLFW_FEATURE_UNAVAILABLE,
-                    "Wayland: The platform does not support setting the window icon");
+    //_glfwInputError(GLFW_FEATURE_UNAVAILABLE,
+    //                "Wayland: The platform does not support setting the window icon");
 }
 
 void _glfwGetWindowPosWayland(_GLFWwindow* window, int* xpos, int* ypos)
@@ -2236,16 +2236,19 @@ void _glfwGetWindowPosWayland(_GLFWwindow* window, int* xpos, int* ypos)
     // A Wayland client is not aware of its position, so just warn and leave it
     // as (0, 0)
 
-    _glfwInputError(GLFW_FEATURE_UNAVAILABLE,
-                    "Wayland: The platform does not provide the window position");
+    //_glfwInputError(GLFW_FEATURE_UNAVAILABLE,
+    //                "Wayland: The platform does not provide the window position");
+
+    *xpos = 0;
+    *ypos = 0;
 }
 
 void _glfwSetWindowPosWayland(_GLFWwindow* window, int xpos, int ypos)
 {
     // A Wayland client can not set its position, so just warn
 
-    _glfwInputError(GLFW_FEATURE_UNAVAILABLE,
-                    "Wayland: The platform does not support setting the window position");
+    //_glfwInputError(GLFW_FEATURE_UNAVAILABLE,
+    //                "Wayland: The platform does not support setting the window position");
 }
 
 void _glfwGetWindowSizeWayland(_GLFWwindow* window, int* width, int* height)
```

My Vintage story works just fine on my 1920x1200 display. I am currently using DWL, which might have something to do with it. Perhaps it's something to do with the _glfwSetWindowSizeWayland function? Have you tried using another Wayland client?

**Comment by TimovVeen** [comment]
I've tried niri, dwl and tinwl. It works on both tinywl and dwl. The issue is that I've scaled by display 2x on niri so UI elements are properly sized, as you can see from the display info below.
```
Output "AU Optronics 0x33EB Unknown" (eDP-1)
  Current mode: 3840x2160 @ 60.002 Hz (preferred)
  Variable refresh rate: not supported
  Physical size: 340x190 mm
  Logical position: 0, 0
  Logical size: 1920x1080
  Scale: 2
  Transform: normal
  Available modes:
    3840x2160@60.002 (current, preferred)
    3840x2160@40.002
```
When I set the scale back to 1, the game does render correctly in the entire window (albeit with small UI). So I believe the issue is that glfw (or Vintagestory maybe) thinks my logical display size is the actual resolution, so it renders the game too small. I don't have this issue with SatDump, which also uses glfw. Maybe later I will test if this issue can be reproduced on X11 with dwm or something.

Anyways, thanks a lot for the idea to patch out the glfw errors. I can finally play with non-slideshow performance now :)

**Comment by wqvi** [comment]
I believe you can scale the UI in game using settings. I was poking around for issues related to scaling and found this thread ["Using GLFW under Wayland"](https://discourse.glfw.org/t/using-glfw-under-wayland/1547). I think this might be on VintageStory's side. Unfortunately I can't peer into VintageStory to help here so this will have to be fixed by them. I hope this thread helps whomever fixes this!

**Comment by Agent00Ming** [comment]
@Craluminum2413 
This can be closed in the next stable release (1.21.0) as the relevant libraries used by the game have been updated to versions that support native Wayland windowing. (OpenTK 4.9.4 and GLFW 3.4.0+)
