### ISSUE TITLE
Out of memory crashes on setting above medium

### ISSUE THREAD

**Issue by shatalinra** [anegostudios/VintageStory-Issues#4227]
### Game Version

 v1.20.0-pre.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Games consistently crashes on attempts to use settings above medium on new saves, even just 'high' preset is enough to trigger it.
But RAM and GPU usage graph does not point to any consistent trend or jump in usage:

- 16GB of RAM and 50% of it is free both before and during crash
- NVIDIA RTX 4070 SUPER with 12 GB of VRAM, 2-3 GB used at max, GPU usage jump sometimes but not consistently

Also using medium with just view distance increased leads to crash.
On stable version, I was using maximum setting without any crashes.

### How to reproduce

1. Load the game.
2. Set setting to 'High' preset.
3. Start a new game.
4. Run through the world for 2-5 minutes.
5. The game crashes.
6. If 'Medium' preset is used instead, it does not crashes (although some freeze for less than a second is present).

### Logs

```Running on 64 bit Windows 10.0.19045.0 with 16332 MB RAM
Game Version: v1.20.0-pre.4 (Unstable)
04/10/2024 22:32:01: Critical error occurred
Loaded Mods: game@1.20.0-pre.4, creative@1.20.0-pre.4, survival@1.20.0-pre.4
System.OutOfMemoryException: Either the graphics card or the OS ran out of memory! Please close other programs and reduce your view distance to prevent the game from crashing.
   at Vintagestory.Client.NoObf.ClientPlatformWindows.CheckGlErrorAlways(String errmsg) in VintagestoryLib\Client\ClientPlatform\GLImpl.cs:line 75
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 694
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 669
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Craluminum2413** [comment]
Downgrade or reinstall your graphics drivers

**Comment by shatalinra** [comment]
I upgraded NVIDIA driver to 565.90 and used that for testing mentioned in the description.
Still, I forgot to reboot my PC and now everything works, thanks.
