### ISSUE TITLE
Crash on game load

### ISSUE THREAD

**Issue by EighteenRabbit** [anegostudios/VintageStory-Issues#4278]
### Game Version

v1.19.8.0

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Trying to load the game I've been playing for 40 odd hours and it is crashing before it finishes loading.  I saved the game and exited to menu last night so it was working fine then.

### Logs

```Running on 64 bit Windows 10.0.19045.0 with 16306 MB RAM
Game Version: v1.19.8 (Stable)
10/10/2024 7:41:19 AM: Critical error occurred
Loaded Mods: autopanning@1.0.1, bedrespawner@1.0.0, bettertraders@0.0.7, HangingOilLamps@1.0.1, lastingarmor@1.0.6, roas@1.0.0, spyglass@0.5.1, visibleore@1.0.1, game@1.19.8, vtr@3.0.3, egocaribautomapmarkers@3.1.0, betterruins@0.3.7, freedomunits@1.1.4, hudclock@3.4.0, prospecttogether@1.3.0, spawnhighlight@1.2.0, creative@1.19.8, survival@1.19.8, xlib@0.8.6, xskills@0.8.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.MathTools.Mat4d.Multiply(Double[] output, Double[] a, Double[] b) in VintagestoryApi\Math\Matrix\Mat4d.cs:line 315
   at Vintagestory.API.MathTools.Mat4d.Mul(Double[] output, Double[] a, Double[] b) in VintagestoryApi\Math\Matrix\Mat4d.cs:line 401
   at Vintagestory.Client.NoObf.SystemRenderSunMoon.OnRenderFrame3D(Single dt) in VintagestoryLib\Client\Systems\Render\RenderSunMoon.cs:line 305
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 200
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 806
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 901
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 730
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 2
==================================
{ TimeGenerated = 10/10/2024 7:38:03 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x27ac
Faulting application start time: 0x01db185269357ee1
Faulting application path: D:\Users\XXX\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: D:\Users\XXX\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: b518cce6-bb0e-4cd0-9b02-7068c75bdb64
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 10/1/2024 9:22:21 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x228c
Faulting application start time: 0x01db133746e21ec8
Faulting application path: D:\Users\XXX\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: D:\Users\XXX\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 3001ec14-15e9-42f5-99ba-40cc381da19b
Faulting package full name: 
Faulting package-relative application ID:  }```

**Comment by EighteenRabbit** [comment]
Rebooting my PC seems to have fixed whatever was blowing up.  "Turn it off and back on again"
