### ISSUE TITLE
GameCrash after respawn on death

### ISSUE THREAD

**Issue by morggin** [anegostudios/VintageStory-Issues#4289]
### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Intermittent client crash on respawn after death event. 

### How to reproduce

Die and respawn
[client-crash.txt](https://github.com/user-attachments/files/17350739/client-crash.txt)
[server-debug.txt](https://github.com/user-attachments/files/17350740/server-debug.txt)
[server-main.txt](https://github.com/user-attachments/files/17350741/server-main.txt)
[server-storyevent.txt](https://github.com/user-attachments/files/17350742/server-storyevent.txt)
[server-worldgen.txt](https://github.com/user-attachments/files/17350743/server-worldgen.txt)
[xlevelingdescription.txt](https://github.com/user-attachments/files/17350744/xlevelingdescription.txt)

### Logs

Running on 64 bit Windows 10.0.22631.0 with 64617 MB RAM
Game Version: v1.19.8 (Stable)
10/12/2024 9:20:13 AM: Critical error occurred
Loaded Mods: bloomeryfulldrops@1.0.0, extrachests@1.8.0, FlexibleTools@3.2.1, millwright@1.1.7, moremolds@1.4.2, simplerails@1.0.0, swordz@1.1.8, temporal_gears_stack@1.0.0, viescraftmachines@2.3.2, game@1.19.8, abcsreborn@0.2.2, ancienttools@1.5.18, animalcages@3.0.3, animationmanagerlib@0.8.8, betteroutline@1.3.0, betterruins@0.3.7, butchering@1.6.8, commonlib@2.5.0-rc.2, fromgoldencombs@1.6.3, glowingarrows@1.2.2, hudclock@3.4.0, jopainting@1.4.0, maltiezbows@1.0.4, spearexpantion@0.1.9, petai@2.2.6, playerlist@2.1.4, rustboundmagic@1.9.74, sailboat@1.3.1, vinconomy@0.3.4, creative@1.19.8, vsquest@1.2.0, survival@1.19.8, vsvillage@1.0.6, xlib@0.8.6, awearablelight@1.1.1, bullseye-continued@2.5.8, captureanimals@2.7.0, feverstonewilds@1.5.0-rc.2, foxtaming@1.4.1, fsmlib@0.4.5, hidenotrot@0.1.0, tpnet@1.14.3, wolftaming@2.1.3, xskills@0.8.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 8/18/2024 6:16:24 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: coreclr.dll, version: 7.0.1023.36312, time stamp: 0x64b06d6c
Exception code: 0xc0000005
Fault offset: 0x00000000001c98a6
Faulting process id: 0x0x5968
Faulting application start time: 0x0x1daf1c7acb95ddb
Faulting application path: C:\Users\morgg\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.10\coreclr.dll
Report Id: a6a20e3b-3424-47b1-b480-2fd542d9a06c
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Does it happen without mods?

**Comment by morggin** [comment]
It has not happened yet without mods.  I'm not sure what to look at to
determine if it was a mod that caused the crash or not. It wasn't apparent
in the surface error report that I could see.

**Comment by morggin** [comment]
This seems to be a rather common theme throughout the logs.

**_"Object reference not set to an instance of an object."_**
