### ISSUE TITLE
Crash when I tried load world.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4301]
### Game Version

v1.20 pre6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Logs

Running on 64 bit Windows 10.0.22631.0 with 16044 MB RAM
Game Version: v1.20.0-pre.6 (Unstable)
13.10.2024 21:01:35: Critical error occurred
Loaded Mods: game@1.20.0-pre.6, creative@1.20.0-pre.6, survival@1.20.0-pre.6
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AssetLocation.op_Implicit(AssetLocation loc) in VintagestoryApi\Common\Assets\AssetLocation.cs:line 516
   at Vintagestory.Client.NoObf.ClientSystemStartup.OnAllAssetsLoaded_Items(Int32 i) in VintagestoryLib\Client\Systems\Startup.cs:line 983
   at Vintagestory.Client.NoObf.ClientSystemStartup.<>c__DisplayClass55_0.<OnAllAssetsLoaded_Items>b__0() in VintagestoryLib\Client\Systems\Startup.cs:line 984
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 786
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 316
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
Does it happen for every new world?

**Comment by CookieBoy21** [comment]
It's happened only one time when I tried load creative world but now I can load it without any crash.
