### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Lullas3** [anegostudios/VintageStory-Issues#4310]
### Game Version

v1.19.8

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### How to reproduce

when I try to load in a world new or old it crashes

### Logs

Running on 64 bit Windows 10.0.22631.0 with 32694 MB RAM
Game Version: v1.19.8 (Stable)
15.10.2024 19:16:03: Critical error occurred in the following mod: carryon@1.7.0-pre.1
Loaded Mods: game@1.19.8, carryon@1.7.0-pre.1, creative@1.19.8, survival@1.19.8
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.AnimManager'.
   at CarryOn.Client.EntityCarryRenderer.RenderAllCarried(EntityAgent entity, Single deltaTime, Boolean isShadowPass)
   at CarryOn.Client.EntityCarryRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in G:\git\github\Nerdscurvy\CarryOn\src\Client\EntityCarryRenderer.cs:line 86
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 200
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 806
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 869
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 730
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 15.10.2024 19:00:57, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.8.0, Zeitstempel: 0x661e0000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x0x2348
Startzeit der fehlerhaften Anwendung: 0x0x1db1f23ba721479
Pfad der fehlerhaften Anwendung: C:\Users\Lukas\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Lukas\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: da6cccf4-f118-4e85-adc0-e6cb55bbc151
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 15.10.2024 18:59:22, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.8.0, Zeitstempel: 0x661e0000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x0x1378
Startzeit der fehlerhaften Anwendung: 0x0x1db1f237a2931bb
Pfad der fehlerhaften Anwendung: C:\Users\Lukas\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Lukas\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: eeaa53d5-acb1-47fd-a94b-112e9efbfd62
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 15.10.2024 18:58:20, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.8.0, Zeitstempel: 0x661e0000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x0x3af8
Startzeit der fehlerhaften Anwendung: 0x0x1db1f234a4df036
Pfad der fehlerhaften Anwendung: C:\Users\Lukas\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Lukas\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 639ef5d3-1f45-429e-adf2-a83a72242cfd
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }

**Comment by Craluminum2413** [comment]
Caused by CarryOn mod
