### ISSUE TITLE
Vintage Story has crashed every time 

### ISSUE THREAD

**Issue by MisterBricks** [anegostudios/VintageStory-Issues#4311]
### Game Version

1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Every time I start the game i see crash raport

### How to reproduce

Fix it ;3

### Screenshots

![Zrzut ekranu 2024-10-15 210713](https://github.com/user-attachments/assets/11f4f805-412a-4ede-a1aa-4759f4368862)

### Logs

`Running on 64 bit Windows 10.0.19045.0 with 8136 MB RAM
Game Version: v1.20.0-pre.6 (Unstable)
15.10.2024 20:57:52: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: The driver does not appear to support OpenGL
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings) in VintagestoryLib\Client\ClientPlatform\GameWindowNative.cs:line 14
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 285
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
Reinstall, update or downgrade your graphics drivers

**Comment by MisterBricks** [comment]
5 min ago it works, i have crash in game and i can't go back... 
I reinstall 2 times and try version 1,20 and this still dont work ;/

**Comment by Craluminum2413** [comment]
@MisterBricks Graphics drivers, not game

**Comment by MisterBricks** [comment]
Thank you <3 
The graphics driver crashed, it's a pity that I lost the world and mods, but that's okay
