### ISSUE TITLE
placing bacterial mat out of direct line of sight crashes and corrupts game

### ISSUE THREAD

**Issue by karrimara** [anegostudios/VintageStory-Issues#4315]
### Game Version

1.19.8

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

if i try to place a bacterial mat someplace where its not directly visible to me (such as in a 1 block hole but the bottom of it isnt visible) the game immediately crashes
subsequent attempts to open world reveals it's corrupted

if you place a block in said hole to replace the mat fast enough the game still crashes but doesn't corrupt

does not matter if the world is flat or normal

### How to reproduce

1. place bacterial mat out of sight
2. game crashes
3. game is corrupted on any attempt to reopen world

### Logs

```16.10.2024 03:42:46 [Fatal] Caught unhandled exception in thread 'tesselateterrain'. Exiting game.
16.10.2024 03:42:46 [Error] Exception: Index was outside the bounds of the array.
   at Vintagestory.Client.NoObf.JsonTesselator.AddJsonModelDataToMesh(MeshData sourceMesh, Int32 lodlevel, TCTCache vars, IMeshPoolSupplier poolSupplier, Single[] tfMatrix) in VintagestoryLib\Client\Render\Tesselation\ChunkTesselator\JsonTesselator.cs:line 255
   at Vintagestory.Client.NoObf.JsonTesselator.doMesh(TCTCache vars, MeshData sourceMesh, Int32 lodLevel) in VintagestoryLib\Client\Render\Tesselation\ChunkTesselator\JsonTesselator.cs:line 177
   at Vintagestory.Client.NoObf.JsonTesselator.Tesselate(TCTCache vars) in VintagestoryLib\Client\Render\Tesselation\ChunkTesselator\JsonTesselator.cs:line 152
   at Vintagestory.Client.NoObf.ChunkTesselator.TesselateBlock(Block block, Int32 lX, Int32 faceflags, Int32 posX, Int32 posZ, Int32 drawType) in VintagestoryLib\Client\Render\Tesselation\ChunkTesselator.cs:line 974
   at Vintagestory.Client.NoObf.ChunkTesselator.BuildDecorPolygons(Int32 chunkX, Int32 chunkY, Int32 chunkZ, Dictionary`2 decors, Boolean edgeonly) in VintagestoryLib\Client\Render\Tesselation\ChunkTesselator.cs:line 857
   at Vintagestory.Client.NoObf.ChunkTesselator.NowProcessChunk(Int32 chunkX, Int32 chunkY, Int32 chunkZ, TesselatedChunk tessChunk, Boolean skipChunkCenter) in VintagestoryLib\Client\Render\Tesselation\ChunkTesselator.cs:line 413
   at Vintagestory.Client.NoObf.ChunkTesselatorManager.TesselateChunk(Int32 chunkX, Int32 chunkY, Int32 chunkZ, Boolean priority, Boolean skipChunkCenter, Boolean& requeue) in VintagestoryLib\Client\Systems\ChunkTesselatorManager.cs:line 380
   at Vintagestory.Client.NoObf.ChunkTesselatorManager.OnSeperateThreadGameTick(Single dt) in VintagestoryLib\Client\Systems\ChunkTesselatorManager.cs:line 242
   at Vintagestory.Client.NoObf.ClientThread.Update() in VintagestoryLib\Client\ClientThread.cs:line 75
   at Vintagestory.Client.NoObf.ClientThread.Process() in VintagestoryLib\Client\ClientThread.cs:line 61```

**Comment by tyronx** [comment]
thanks for the report, this is fixed in the upcoming 1.20 update
