### ISSUE TITLE
crash when choosing classes

### ISSUE THREAD

**Issue by LuhanEB** [anegostudios/VintageStory-Issues#4326]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

basically after creating the world and when I choose the class the game simply closes and gives the error report

### How to reproduce

1. create the world 
2. choose the class 
3. confirm the class

### Logs
```
Running on 64 bit Windows 10.0.22631.0 with 16225 MB RAM
Game Version: v1.19.8 (Stable)
18/10/2024 21:53:11: Critical error occurred
Loaded Mods: aculinaryartillery@1.2.1, bettertraders@0.0.7, moreicons_cs@1.1.0, moreclasses@1.2.5, someextramolds@1.0.6, game@1.19.8, betterruins@0.3.7, commonlib@2.5.0-rc.2, lib2d@1.0.0, rivers@3.2.0, creative@1.19.8, survival@1.19.8, xlib@0.8.6, extraoverlays@1.4.0, fishing@2.0.2, playercorpse@1.10.1-rc.1, xskills@0.8.8
System.Collections.Generic.KeyNotFoundException: The given key 'claustrophobic' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Vintagestory.GameContent.GuiDialogCreateCharacter.<changeClass>b__25_0(String code) in VSSurvivalMod\Gui\GuiDialogCreateCharacter.cs:line 382
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at Vintagestory.GameContent.GuiDialogCreateCharacter.changeClass(Int32 dir) in VSSurvivalMod\Gui\GuiDialogCreateCharacter.cs:line 384
   at Vintagestory.GameContent.GuiDialogCreateCharacter.<ComposeGuis>b__13_5(Boolean on) in VSSurvivalMod\Gui\GuiDialogCreateCharacter.cs:line 215
   at Vintagestory.API.Client.GuiElementToggleButton.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementToggleButton.cs:line 195
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs) in VintagestoryApi\Client\UI\GuiComposer.cs:line 494
   at Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 542
   at Vintagestory.GameContent.GuiDialogCreateCharacter.OnMouseDown(MouseEvent args) in VSSurvivalMod\Gui\GuiDialogCreateCharacter.cs:line 496
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 393
   at Vintagestory.Client.NoObf.ClientMain.UpdateMouseButtonState(EnumMouseButton button, Boolean down) in VintagestoryLib\Client\ClientMain.cs:line 1919
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean isGlobal, Boolean fallBack, Boolean keyup) in VintagestoryLib\Client\HotkeyManager.cs:line 431
   at Vintagestory.Client.HotkeyManager.OnMouseButton(ClientMain game, EnumMouseButton button, Int32 modifiers, Boolean buttonDown) in VintagestoryLib\Client\HotkeyManager.cs:line 576
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDownRaw(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1862
   at Vintagestory.Client.GuiScreenRunningGame.OnMouseDown(MouseEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 329
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 198
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 2
==================================
{ TimeGenerated = 03/10/2024 14:19:15, Site = , Source = Application Error, Message = Nome do aplicativo com falha: Vintagestory.exe, versão: 1.19.8.0, carimbo de data/hora: 0x661e0000
Nome do módulo com falha: openal32.dll, versão: 1.23.0.0, carimbo de data/hora: 0x63dd31ad
Código de exceção: 0x40000015
Deslocamento da falha: 0x00000000000df046
ID do processo com falha: 0x0x3dec
Hora de início do aplicativo com falha: 0x0x1db15b080eca5ac
Caminho do aplicativo com falha: C:\Users\luhan\AppData\Roaming\Vintagestory\Vintagestory.exe
Caminho do módulo com falha: C:\Users\luhan\AppData\Roaming\Vintagestory\Lib\openal32.dll
ID do Relatório: 0e36493d-5840-4c69-8526-dd111e964b6f
Nome completo do pacote com falha: 
ID do aplicativo relativo ao pacote com falha:  }
--------------
{ TimeGenerated = 13/08/2024 17:37:18, Site = , Source = Application Error, Message = Nome do aplicativo com falha: Vintagestory.exe, versão: 1.19.8.0, carimbo de data/hora: 0x661e0000
Nome do módulo com falha: openal32.dll, versão: 1.23.0.0, carimbo de data/hora: 0x63dd31ad
Código de exceção: 0x40000015
Deslocamento da falha: 0x00000000000df046
ID do processo com falha: 0x0x1b58
Hora de início do aplicativo com falha: 0x0x1daedbf3e4445cf
Caminho do aplicativo com falha: C:\Users\luhan\AppData\Roaming\Vintagestory\Vintagestory.exe
Caminho do módulo com falha: C:\Users\luhan\AppData\Roaming\Vintagestory\Lib\openal32.dll
ID do Relatório: 7d552bc7-96fa-48b7-8523-a9580ba54847
Nome completo do pacote com falha: 
ID do aplicativo relativo ao pacote com falha:  }
```

**Comment by sekelsta** [comment]
This looks like a mod making an incorrect json patch to `assets/survival/config/traits.json` that removes the claustrophobic trait from the game.
