### ISSUE TITLE
Crash on launch with second display enabled

### ISSUE THREAD

**Issue by NoMemeWar** [anegostudios/VintageStory-Issues#4334]
### Game Version

v1.19.8

### Platform

Windows

### Modded

None

### SP/MP

None

### How to reproduce

Set the display mode to "Duplicate", "Extend", or "Second Screen Only." Launch the game. It should crash after a moment.

### Screenshots

![Screenshot 2024-10-19 201720](https://github.com/user-attachments/assets/5db1d4e4-a696-4bca-918c-bce14d57f392)

### Logs

Running on 64 bit Windows 10.0.22631.0 with 16307 MB RAM
Game Version: v1.19.8 (Stable)
10/19/2024 8:03:16 PM: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: Failed to make context current: The handle is invalid. 
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings) in VintagestoryLib\Client\ClientPlatform\GameWindowNative.cs:line 14
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 281
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
Try disable vsync, or try update, downgrade or reinstall your graphics drivers
