### ISSUE TITLE
1.20pre6 Game crash after try to pick aged AS

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#4344]
### Game Version

1.20pre6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

When try to pick up aged armor stand in the ruins it crashes the game

timestamp: 1:44:50
https://www.youtube.com/live/2KNK3wBXLe0

### How to reproduce

try to pick up aged armor stand generated in the ruins ( crouch and right mouse click )

### Logs

Running on 64 bit Windows 10.0.22631.0 with 65458 MB RAM
Game Version: v1.20.0-pre.6 (Unstable)
20.10.2024 19:22:29: Critical error occurred
Loaded Mods: ClaimsRadar@1.1.0, game@1.20.0-pre.6, extrainfo@1.8.1, hudclock@3.4.0, playerlist@2.1.4, creative@1.20.0-pre.6, vsserverpanel@0.1.5, survival@1.20.0-pre.6, pomnotes@0.7.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityArmorStand.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode) in VSSurvivalMod\Entities\EntityArmorStand.cs:line 59
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 394
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 819
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1023
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 18.10.2024 15:20:41, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.20.0.0, časové razítko: 0x66470000
Název chybujícího modulu: openal32.dll, verze: 1.23.0.0, časové razítko: 0x63dd31ad
Kód výjimky: 0x40000015
Posun chyby: 0x00000000000df046
ID chybujícího procesu: 0x0x2248
Čas spuštění chybující aplikace: 0x0x1db2160687e4add
Cesta k chybující aplikaci: C:\Games\Vintagestory1.20\Vintagestory.exe
Cesta k chybujícímu modulu: C:\Games\Vintagestory1.20\Lib\openal32.dll
ID zprávy: e8119c41-c32f-466f-b1db-f5cef15c140c
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }
--------------
{ TimeGenerated = 18.10.2024 14:17:38, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.20.0.0, časové razítko: 0x66470000
Název chybujícího modulu: openal32.dll, verze: 1.23.0.0, časové razítko: 0x63dd31ad
Kód výjimky: 0x40000015
Posun chyby: 0x00000000000df046
ID chybujícího procesu: 0x0x6d0c
Čas spuštění chybující aplikace: 0x0x1db215795d3dfae
Cesta k chybující aplikaci: C:\Games\Vintagestory1.20\Vintagestory.exe
Cesta k chybujícímu modulu: C:\Games\Vintagestory1.20\Lib\openal32.dll
ID zprávy: 5663c9fe-36bf-4a61-8b83-0ade8e3cb34f
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }
--------------
{ TimeGenerated = 18.10.2024 13:48:35, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.20.0.0, časové razítko: 0x66470000
Název chybujícího modulu: openal32.dll, verze: 1.23.0.0, časové razítko: 0x63dd31ad
Kód výjimky: 0x40000015
Posun chyby: 0x00000000000df046
ID chybujícího procesu: 0x0x6d40
Čas spuštění chybující aplikace: 0x0x1db21538e1a3f24
Cesta k chybující aplikaci: C:\Games\Vintagestory1.20\Vintagestory.exe
Cesta k chybujícímu modulu: C:\Games\Vintagestory1.20\Lib\openal32.dll
ID zprávy: 650413b9-4a3c-4eae-9f64-17816a136465
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }

**Comment by Craluminum2413** [comment]
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4183
