### ISSUE TITLE
1.20pre6 Barelcause crash

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#4351]
### Game Version

1.20pre6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Taking barel from creative inventory  causing instant crash

### How to reproduce

run game, set creative mode, take barel from creative inventory

### Logs

Running on 64 bit Windows 10.0.22631.0 with 65458 MB RAM
Game Version: v1.20.0-pre.6 (Unstable)
23.10.2024 12:41:14: Critical error occurred
Loaded Mods: game@1.20.0-pre.6, creative@1.20.0-pre.6, survival@1.20.0-pre.6
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1577
   at Vintagestory.API.Common.Block.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 2255
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 401
   at Vintagestory.API.Common.ItemSlot.GetStackDescription(IClientWorldAccessor world, Boolean extendedDebugInfo) in VintagestoryApi\Common\Inventory\ItemSlot.cs:line 476
   at Vintagestory.Client.NoObf.HudMouseTools.OnRequireInfoText(ItemSlot slot) in VintagestoryLib\Client\Systems\Gui\Huds\HudMouseTools.cs:line 167
   at Vintagestory.API.Client.GuiElementItemstackInfo.AsyncRecompose() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 142
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot, Boolean forceRecompose) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 252
   at Vintagestory.Client.NoObf.HudMouseTools.OnMouseEnterSlot(ItemSlot slot) in VintagestoryLib\Client\Systems\Gui\Huds\HudMouseTools.cs:line 211
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerOnMouseEnterSlot(ClientMain game, ItemSlot slot) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 516
   at Vintagestory.Client.NoObf.InputAPI.TriggerOnMouseEnterSlot(ItemSlot slot) in VintagestoryLib\Client\API\InputAPI.cs:line 48
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseMove(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 809
   at Vintagestory.API.Client.GuiComposer.OnMouseMove(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 514
   at Vintagestory.API.Client.GuiDialog.OnMouseMove(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 612
   at Vintagestory.Client.NoObf.GuiManager.OnMouseMove(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 433
   at Vintagestory.Client.NoObf.ClientMain.OnMouseMove(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1993
   at Vintagestory.Client.NoObf.ClientPlatformWindows.UpdateMousePosition() in VintagestoryLib\Client\ClientPlatform\Input.cs:line 111
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 23.10.2024 12:40:17, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.20.0.0, časové razítko: 0x66470000
Název chybujícího modulu: openal32.dll, verze: 1.23.0.0, časové razítko: 0x63dd31ad
Kód výjimky: 0x40000015
Posun chyby: 0x00000000000df046
ID chybujícího procesu: 0x0x1460
Čas spuštění chybující aplikace: 0x0x1db2537c98f1c72
Cesta k chybující aplikaci: C:\Games\Vintagestory1.20\Vintagestory.exe
Cesta k chybujícímu modulu: C:\Games\Vintagestory1.20\Lib\openal32.dll
ID zprávy: 2b455bd3-677f-4097-9598-04450ae36f79
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }
--------------
{ TimeGenerated = 23.10.2024 12:26:30, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.20.0.0, časové razítko: 0x66470000
Název chybujícího modulu: openal32.dll, verze: 1.23.0.0, časové razítko: 0x63dd31ad
Kód výjimky: 0x40000015
Posun chyby: 0x00000000000df046
ID chybujícího procesu: 0x0xc04
Čas spuštění chybující aplikace: 0x0x1db2535e7ae1120
Cesta k chybující aplikaci: C:\Games\Vintagestory1.20\Vintagestory.exe
Cesta k chybujícímu modulu: C:\Games\Vintagestory1.20\Lib\openal32.dll
ID zprávy: 1eb080e7-97d5-4075-86be-f8834a9627e8
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }
--------------
{ TimeGenerated = 23.10.2024 12:25:34, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.20.0.0, časové razítko: 0x66470000
Název chybujícího modulu: openal32.dll, verze: 1.23.0.0, časové razítko: 0x63dd31ad
Kód výjimky: 0x40000015
Posun chyby: 0x00000000000df046
ID chybujícího procesu: 0x0x8060
Čas spuštění chybující aplikace: 0x0x1db2535c7a6138a
Cesta k chybující aplikaci: C:\Games\Vintagestory1.20\Vintagestory.exe
Cesta k chybujícímu modulu: C:\Games\Vintagestory1.20\Lib\openal32.dll
ID zprávy: 41a0d217-5d29-42d3-b5b1-0d5b4eaa9c79
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }

**Comment by Craluminum2413** [comment]
Can't reproduce, it doesn't crash for me
