### ISSUE TITLE
pre.7 crashes when loading games & when trying to create a new world

### ISSUE THREAD

**Issue by hyapapaya** [anegostudios/VintageStory-Issues#4380]
### Game Version

1.20.0-pre.7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Trying to start a new single player game results in Vintage Story crashing partway through loading. 

I also can't launch any of my existing worlds, but those are modded.

### How to reproduce

1. Launch game
2. Create World in any singleplayer game mode
3. Game crashes partway through loading the world

### Logs
```cs
Running on 64 bit Windows 10.0.19045.0 with 65485 MB RAM
Game Version: v1.20.0-pre.7 (Unstable)
10/27/2024 12:07:21 AM: Critical error occurred
Loaded Mods: game@1.20.0-pre.7, creative@1.20.0-pre.7, survival@1.20.0-pre.7
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VSSurvivalMod\Systems\Handbook\CollectibleBehaviorHandbookTextAndExtraInfo.cs:line 1377
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1731
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 400
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(ICoreClientAPI capi, ItemStack stack) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 40
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onCreatePagesAsync() in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 86
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 418
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 120
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```
Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10/27/2024 12:07:24 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ffc335db750
Faulting process id: 0x19e4
Faulting application start time: 0x01db2825a1c78914
Faulting application path: C:\Users\hyv0l\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: unknown
Report Id: 3a148817-5901-4b6c-910f-fb2c615773e2
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 10/27/2024 12:06:35 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ffc338f5500
Faulting process id: 0x5f18
Faulting application start time: 0x01db2825488d09c3
Faulting application path: C:\Users\hyv0l\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: unknown
Report Id: 3163029d-058b-43be-8ed8-3a0e669124aa
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 10/23/2024 11:42:43 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ff7c60310a0
Faulting process id: 0x3738
Faulting application start time: 0x01db25c5e8ff7e47
Faulting application path: C:\Users\hyv0l\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: unknown
Report Id: d6e288b9-e614-4edd-b31c-c9776181087f
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Is there a way to reliably reproduce it?

**Comment by radfast** [comment]
@hyapapaya is this still an issue for you in version 1.20-rc.1, which should generally be more stable? 

If trying the rc.1 version, bearing in mind that because you have had an issue, it would be a good idea to make a fresh clean install of all the game files (a full download) in a new folder on your PC.  Don't try to install over an older, potentially broken, -pre.7 installation.

Please let us know how you get on - if the issue is still happening then please post a fresh crash report as it will have updated line numbers to help us find the issue

**Comment by radfast** [comment]
@hyapapaya  as above, but now please do try 1.20-rc.5 (or later depending on when you get to this)

**Comment by tyronx** [comment]
Please reopen ticket if it still crashes
