### ISSUE TITLE
playing on a server and it crashes

### ISSUE THREAD

**Issue by Mery457** [anegostudios/VintageStory-Issues#4381]
### Game Version

1.19.8

### Platform

None

### Modded

None

### SP/MP

None

### Description

I'm on a server and it keeps popping up and this is one of the mistakes that I make
I'm new and I don't know much sorry

### Screenshots

Running on 64 bit Windows 10.0.19045.0 with 32200 MB RAM
Game Version: v1.19.8 (Stable)
27/10/2024 04:00:27 a. m.: Critical error occurred
Loaded Mods: 
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Vintagestory.Client.NoObf.GuiManager.Dispose(ClientMain game) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 568
   at Vintagestory.Client.NoObf.ClientMain.Dispose() in VintagestoryLib\Client\ClientMain.cs:line 2688
   at Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected) in VintagestoryLib\Client\ClientMain.cs:line 2635
   at Vintagestory.Client.NoObf.ClientMain.<>c__DisplayClass204_0.<OnDisconnected>b__1() in VintagestoryLib\Client\ClientMain.cs:line 1482
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 27/10/2024 03:41:37 a. m., Site = , Source = Application Error, Message = Nombre de la aplicación con errores: Vintagestory.exe, versión: 1.19.8.0, marca de tiempo: 0x661e0000
Nombre del módulo con errores: KERNELBASE.dll, versión: 10.0.19041.4957, marca de tiempo: 0xc5225d0f
Código de excepción: 0xe0434352
Desplazamiento de errores: 0x000000000003b699
Identificador del proceso con errores: 0x218
Hora de inicio de la aplicación con errores: 0x01db285c804bcbdf
Ruta de acceso de la aplicación con errores: E:\Vintagestory\Vintagestory.exe
Ruta de acceso del módulo con errores: C:\Windows\System32\KERNELBASE.dll
Identificador del informe: e0a6c3f3-62ae-47ff-8632-dc7ebb0b3e0f
Nombre completo del paquete con errores: 
Identificador de aplicación relativa del paquete con errores:  }
--------------
{ TimeGenerated = 24/10/2024 02:58:20 p. m., Site = , Source = Application Error, Message = Nombre de la aplicación con errores: Vintagestory.exe, versión: 1.19.8.0, marca de tiempo: 0x661e0000
Nombre del módulo con errores: KERNELBASE.dll, versión: 10.0.19041.4842, marca de tiempo: 0xe6d00f33
Código de excepción: 0xe0434352
Desplazamiento de errores: 0x000000000003b699
Identificador del proceso con errores: 0x3a60
Hora de inicio de la aplicación con errores: 0x01db265f9f914264
Ruta de acceso de la aplicación con errores: E:\Vintagestory\Vintagestory.exe
Ruta de acceso del módulo con errores: C:\Windows\System32\KERNELBASE.dll
Identificador del informe: ba75f685-3916-48fb-a525-a73b01f62423
Nombre completo del paquete con errores: 
Identificador de aplicación relativa del paquete con errores:  }
--------------
{ TimeGenerated = 24/10/2024 02:23:36 p. m., Site = , Source = Application Error, Message = Nombre de la aplicación con errores: Vintagestory.exe, versión: 1.19.8.0, marca de tiempo: 0x661e0000
Nombre del módulo con errores: KERNELBASE.dll, versión: 10.0.19041.4842, marca de tiempo: 0xe6d00f33
Código de excepción: 0xe0434352
Desplazamiento de errores: 0x000000000003b699
Identificador del proceso con errores: 0x25c4
Hora de inicio de la aplicación con errores: 0x01db2659da226c60
Ruta de acceso de la aplicación con errores: E:\Vintagestory\Vintagestory.exe
Ruta de acceso del módulo con errores: C:\Windows\System32\KERNELBASE.dll
Identificador del informe: f0269932-3066-4370-a17e-78361bc0a541
Nombre completo del paquete con errores: 
Identificador de aplicación relativa del paquete con errores:  }

**Comment by Craluminum2413** [comment]
What mods are installed?

**Comment by Mery457** [comment]
![Uploading server.PNG…]()

**Comment by Mery457** [comment]
![server](https://github.com/user-attachments/assets/ac9bbbdd-f159-449c-b3e3-be1a984d7a5c)
