### ISSUE TITLE
copying/importing buildings causes objects, containers to corrupt causing anyone who looks at or interacts with them to crash

### ISSUE THREAD

**Issue by Ricomondo** [anegostudios/VintageStory-Issues#4394]
### Game Version

v 1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

we started a new world and imported some buildings into the new world. Some of the containers/items became corrupt so that anyone who looks at it or interacts with it automatically crashes. Then its very difficult for them to re-enter the world and stay there

### How to reproduce

1. Copy/download a building from a world
2. Import that building into a new world
3. walk through the building and check for corrupt items/containers. This means that the original contents of these containers have been switched out for others that weren't there originally
4. Pick them up and put them in your inventory. When you crash, it will repeatedly kick the player from the server

### Logs

Running on 64 bit Windows 10.0.22631.0 with 65323 MB RAM
Game Version: v1.19.8 (Stable)
10/29/2024 8:28:37 PM: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.5, chiseltools@1.12.7, ClaimsRadar@1.1.0, moremolds@1.4.2, rpvoicechat@2.3.9, game@1.19.8, betterfirepit@1.1.4, betterruins@0.3.7, carryon@1.7.4, commonlib@2.5.0-rc.2, divisionoflabor@1.0.8, expandedfoods@1.7.0, fromgoldencombs@1.6.3, knapster@2.11.2, sailboat@1.3.1, th3dungeon@0.2.1, vinconomy@0.3.3, creative@1.19.8, vsquest@1.2.0, survival@1.19.8, vsvillage@1.0.6, em@2.7.0, playercorpse@1.10.1-rc.1, stonequarry@3.3.1, bricklayers@2.5.6
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at Vintagestory.GameContent.BlockTapestry.GetBaseCode(String type) in VSSurvivalMod\Block\BlockTapestry.cs:line 189
   at Vintagestory.GameContent.BlockTapestry.GetWordedSection(ItemSlot slot, IWorldAccessor world) in VSSurvivalMod\Block\BlockTapestry.cs:line 370
   at Vintagestory.GameContent.BlockTapestry.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VSSurvivalMod\Block\BlockTapestry.cs:line 358
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 401
   at Vintagestory.API.Common.ItemSlot.GetStackDescription(IClientWorldAccessor world, Boolean extendedDebugInfo) in VintagestoryApi\Common\Inventory\ItemSlot.cs:line 475
   at Vintagestory.Client.NoObf.HudMouseTools.OnRequireInfoText(ItemSlot slot) in VintagestoryLib\Client\Systems\Gui\Huds\HudMouseTools.cs:line 167
   at Vintagestory.API.Client.GuiElementItemstackInfo.AsyncRecompose() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 125
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot, Boolean forceRecompose) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 252
   at Vintagestory.Client.NoObf.HudMouseTools.OnMouseEnterSlot(ItemSlot slot) in VintagestoryLib\Client\Systems\Gui\Huds\HudMouseTools.cs:line 211
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerOnMouseEnterSlot(ClientMain game, ItemSlot slot) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 516
   at Vintagestory.Client.NoObf.InputAPI.TriggerOnMouseEnterSlot(ItemSlot slot) in VintagestoryLib\Client\API\InputAPI.cs:line 48
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseMove(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 809
   at Vintagestory.API.Client.GuiComposer.OnMouseMove(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 512
   at Vintagestory.API.Client.GuiDialog.OnMouseMove(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 608
   at Vintagestory.Client.NoObf.GuiManager.OnMouseMove(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 433
   at Vintagestory.Client.NoObf.ClientMain.OnMouseMove(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1980
   at Vintagestory.Client.NoObf.ClientPlatformWindows.UpdateMousePosition() in VintagestoryLib\Client\ClientPlatform\Input.cs:line 111
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10/28/2024 1:38:54 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x3820
Faulting application start time: 0x0x1db291382352944
Faulting application path: C:\Users\ricar\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\ricar\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 1ed497e0-da03-49ae-b742-5a9a6810fdd1
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 10/28/2024 1:38:43 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.4249, time stamp: 0x0cf64c6a
Exception code: 0xe0434352
Fault offset: 0x000000000005fe4c
Faulting process id: 0x0x3820
Faulting application start time: 0x0x1db291382352944
Faulting application path: C:\Users\ricar\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: fb875ab5-7c9b-4159-af11-18bb660897df
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 9/23/2024 8:40:18 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x22b4
Faulting application start time: 0x0x1db0e24b7a3c5aa
Faulting application path: C:\Users\ricar\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\ricar\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 46fe7bfb-04fe-4dfa-999a-d3ba76d8ea1a
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
It would be very helpful if anyone tried to reproduce it on 1.20
