### ISSUE TITLE
Save doesn't load

### ISSUE THREAD

**Issue by dEnMations1** [anegostudios/VintageStory-Issues#4434]
### Game Version

v1.20.0 pre5 

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

i tried to load my world and the game crashes after the load

### How to reproduce

don't know

### Logs

Running on 64 bit Windows 10.0.19045.0 with 16310 MB RAM
Game Version: v1.20.0-pre.5 (Unstable)  
04.11.2024 15:32:55: Critical error occurred
Loaded Mods: game@1.20.0-pre.5, creative@1.20.0-pre.5, survival@1.20.0-pre.5
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityShapeRenderer.RenderItem(Single dt, Boolean isShadowPass, ItemStack stack, AttachmentPointAndPose apap, ItemRenderInfo renderInfo) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 533
   at Vintagestory.GameContent.EntityShapeRenderer.RenderHeldItem(Single dt, Boolean isShadowPass, Boolean right) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 472
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.RenderHeldItem(Single dt, Boolean isShadowPass, Boolean right) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 276
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 197
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderOpaque3D(Single deltaTime) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 92
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 200
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 910
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 739
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 170
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 04.11.2024 15:31:35, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.20.0.0, метка времени: 0x66470000
Имя сбойного модуля: openal32.dll, версия: 1.23.0.0, метка времени: 0x63dd31ad
Код исключения: 0x40000015
Смещение ошибки: 0x00000000000df046
Идентификатор сбойного процесса: 0x1dc
Время запуска сбойного приложения: 0x01db2eb4bc77cf4b
Путь сбойного приложения: D:\Vintage Story\Vintagestory.exe
Путь сбойного модуля: D:\Vintage Story\Lib\openal32.dll
Идентификатор отчета: 142a38bd-28af-4294-b7dc-2c45aaadceb7
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 04.11.2024 15:26:12, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.20.0.0, метка времени: 0x66470000
Имя сбойного модуля: openal32.dll, версия: 1.23.0.0, метка времени: 0x63dd31ad
Код исключения: 0x40000015
Смещение ошибки: 0x00000000000df046
Идентификатор сбойного процесса: 0x46dc
Время запуска сбойного приложения: 0x01db2eb4b0d45080
Путь сбойного приложения: D:\Vintage Story\Vintagestory.exe
Путь сбойного модуля: D:\Vintage Story\Lib\openal32.dll
Идентификатор отчета: 601c75ee-3ae6-4846-bec7-34d0ad12c0e6
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 04.11.2024 15:25:51, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.20.0.0, метка времени: 0x66470000
Имя сбойного модуля: openal32.dll, версия: 1.23.0.0, метка времени: 0x63dd31ad
Код исключения: 0x40000015
Смещение ошибки: 0x00000000000df046
Идентификатор сбойного процесса: 0x1e70
Время запуска сбойного приложения: 0x01db2eb4a00846b6
Путь сбойного приложения: D:\Vintage Story\Vintagestory.exe
Путь сбойного модуля: D:\Vintage Story\Lib\openal32.dll
Идентификатор отчета: b22a58ef-804d-470a-a3d7-85595f56a2ed
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }

**Comment by Craluminum2413** [comment]
Diplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4314

**Comment by radfast** [comment]
For info the issue was fixed in game version 1.20.0-pre.7
