### ISSUE TITLE
Pressing Random Keys Right After Loading World Crashes Game

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4453]
### Game Version

v1.20.0 pre-10

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Pressing seemingly any key right after a world loads will crash the game for me.

### Logs
```
Running on 64 bit Windows 10.0.19045.0 with 16147 MB RAM
Game Version: v1.20.0-pre.10 (Unstable)
6/11/2024 5:57:03 PM: Critical error occurred
Loaded Mods: game@1.20.0-pre.10, creative@1.20.0-pre.10, survival@1.20.0-pre.10
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.FilterItemsBySearchText(String text, Dictionary`2 searchCache, Dictionary`2 searchCacheNames) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 560
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnTextChanged(String text) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 421
   at Vintagestory.API.Client.GuiElementEditableTextBase.TextChanged() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 337
   at Vintagestory.API.Client.GuiElementEditableTextBase.LoadValue(List`1 newLines) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 301
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyPress(ICoreClientAPI api, KeyEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 603
   at Vintagestory.API.Client.GuiComposer.OnKeyPress(KeyEvent args) in VintagestoryApi\Client\UI\GuiComposer.cs:line 636
   at Vintagestory.API.Client.GuiDialog.OnKeyPress(KeyEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 462
   at Vintagestory.Client.NoObf.GuiManager.OnKeyPress(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 382
   at Vintagestory.Client.NoObf.ClientMain.OnKeyPress(KeyEvent eventArgs) in VintagestoryLib\Client\ClientMain.cs:line 1829
   at Vintagestory.Client.GuiScreenRunningGame.OnKeyPress(KeyEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 328
   at Vintagestory.Client.ScreenManager.OnKeyPress(KeyEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 895
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyPress(TextInputEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 220
   at OpenTK.Windowing.Desktop.NativeWindow.OnTextInput(TextInputEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.CharCallback(Window* window, UInt32 codepoint)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 2
```

**Comment by Craluminum2413** [comment]
Happened to me a few times too, I searched in creative inventory right after loaded world

**Comment by maltiez2** [comment]
Will be fixed in next update
