### ISSUE TITLE
won't launch after download

### ISSUE THREAD

**Issue by weegee789** [anegostudios/VintageStory-Issues#4459]
### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

game crashes everytime I open it even tho I just downloaded it

### Logs

Running on 64 bit Windows 10.0.22631.0 with 16075 MB RAM
Game Version: v1.19.8 (Stable)
11/6/2024 5:49:27 PM: Critical error occurred
Loaded Mods: 
System.IO.FileNotFoundException: Could not load file or assembly 'csvorbis, Version=1.0.4143.14181, Culture=neutral, PublicKeyToken=eaa89a1626beb708'. The system cannot find the file specified.
File name: 'csvorbis, Version=1.0.4143.14181, Culture=neutral, PublicKeyToken=eaa89a1626beb708'
   at Vintagestory.Client.NoObf.OggDecoder.OggToWav(Stream ogg, IAsset asset)
   at Vintagestory.Client.AudioOpenAl.GetSampleFromArray(IAsset asset) in VintagestoryLib\Client\ClientPlatform\ClientNative\AudioOpenAl.cs:line 227
   at Vintagestory.Client.NoObf.ClientPlatformWindows.CreateAudioData(IAsset asset) in VintagestoryLib\Client\ClientPlatform\Audio.cs:line 57
   at Vintagestory.Client.NoObf.AudioMetaData.DoLoad() in VintagestoryLib\Client\ClientPlatform\ClientNative\OggDecoder.cs:line 40
   at Vintagestory.Client.NoObf.AudioMetaData.Load() in VintagestoryLib\Client\ClientPlatform\ClientNative\OggDecoder.cs:line 54
   at Vintagestory.Client.ScreenManager.LoadSoundsInitial() in VintagestoryLib\Client\ScreenManager.cs:line 431
   at Vintagestory.Client.ScreenManager.DoGameInitStage1() in VintagestoryLib\Client\ScreenManager.cs:line 197

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/6/2024 5:36:12 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.4391, time stamp: 0x7433a115
Exception code: 0xe0434352
Fault offset: 0x000000000005fa4c
Faulting process id: 0x0x11f78
Faulting application start time: 0x0x1db309c47873250
Faulting application path: C:\Users\ajdep\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 1343c43c-cd4a-48aa-9670-f583ffdfec04
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/6/2024 5:35:49 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.4391, time stamp: 0x7433a115
Exception code: 0xe0434352
Fault offset: 0x000000000005fa4c
Faulting process id: 0x0x11450
Faulting application start time: 0x0x1db309c39de26a4
Faulting application path: C:\Users\ajdep\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: fabf0e97-98ef-42c1-8d63-477f3ccdae90
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/6/2024 5:33:50 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.4391, time stamp: 0x7433a115
Exception code: 0xe0434352
Fault offset: 0x000000000005fa4c
Faulting process id: 0x0xd9dc
Faulting application start time: 0x0x1db309bf34820ad
Faulting application path: C:\Users\ajdep\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: e9d3c307-5c3a-4470-86d9-6c08e25c2311
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Try reinstall the game
