### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by phoebeallsop** [anegostudios/VintageStory-Issues#446]
Running on 64 bit Windows with 8 GB RAM 
Version: v1.12.4 (Stable)06/03/2020 15:55:10: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   at _Nm2Dey99KsdwIYLpu4GOdoFloZP._qP4paZogWeAkBAdIetsRHNRsPeR()
   at _EQxWmablZ9e1a2ttf5sknNEhthE._ryUq828Jdon4eHk5toV3WI6D1nH()
   at _EQxWmablZ9e1a2ttf5sknNEhthE._TNhCFDnDMOpUfVxHZgPyWvoTAtF()
   at _EQxWmablZ9e1a2ttf5sknNEhthE._wVES3I4AcneyUTHpdRuLu6EHvCH(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _KgkCdVM1WnzOB8EQZYjMqMgiQif._FmdhOaaNJf4xNNi98fb5q9puBYb(_vzXUYcAd8hQnBWAaPoIw4RI2yoU , String[] )
   at _RenJRmDtixD6Tekd8S9clc9cPZV._FmdhOaaNJf4xNNi98fb5q9puBYb(ThreadStart )
-------------------------------

### Description
game crashes upon opening

**Comment by Bloodsaw** [comment]
Please update to 1.12.6, this was already fixed.
You can download it from main page.
