### ISSUE TITLE
PLEASE HELP!! Cant see public servers. Tried inputting manually.

### ISSUE THREAD

**Issue by bryngirl12** [anegostudios/VintageStory-Issues#4467]
### Game Version

v1.19.18

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

I cant access any public servers and when I do it manually through HOST IP. It crashes every time. Randomly this happened one day. I do live in a college dorm and I'm using their wifi... however it was totally fine for a week or two inside of the dorm. Weird stuff.

### How to reproduce

Open vintage story, go to public servers and what I see is "Cant find any supported servers"

### Logs
```
Running on 64 bit Windows 10.0.19045.0 with 16322 MB RAM
Game Version: v1.19.8 (Stable)
11/7/2024 7:23:12 PM: Critical error occurred
Loaded Mods: game@1.19.8, creative@1.19.8, survival@1.19.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.WeatherSystemClient.OnRenderFrame(Single dt, EnumRenderStage stage) in VSEssentials\Systems\Weather\WeatherSystemClient.cs:line 140
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 200
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 806
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 858
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 730
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/7/2024 7:19:24 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x51dc
Faulting application start time: 0x01db317bae3f5fcd
Faulting application path: C:\Users\bryng\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\bryng\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: a36ad5e7-b04f-4c72-ba37-f5262dfbd99e
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/7/2024 7:15:19 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x3784
Faulting application start time: 0x01db317b47595170
Faulting application path: C:\Users\bryng\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\bryng\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: b3e64883-051a-4102-870d-c529b9325557
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/1/2024 3:52:15 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x6510
Faulting application start time: 0x01db2c83b6338238
Faulting application path: C:\Users\bryng\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\bryng\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: ac71d1e2-b48e-42c5-bc6f-6a768af4a040
Faulting package full name: 
Faulting package-relative application ID:  }
```

**Comment by Craluminum2413** [comment]
Try reinstall the game

**Comment by bryngirl12** [comment]
> Try reinstall the game

Thank u gorgeous. it worked
