### ISSUE TITLE
Game Crash upon connecting to server

### ISSUE THREAD

**Issue by thekrazykitten** [anegostudios/VintageStory-Issues#4483]
### Game Version

1.19.8

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

I joined my friend's server and immediately crashed

### How to reproduce

1. Join a server
2. Crash maybe

### Logs

```
Running on 64 bit Windows 10.0.22631.0 with 8023 MB RAM
Game Version: v1.19.8 (Stable)
11/9/2024 9:10:22 PM: Critical error occurred
Loaded Mods: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Vintagestory.GameContent.BlockClutterBookshelf.RandomType(String variant) in VSSurvivalMod\Lore\ResoArchives\BlockClutterBookshelf.cs:line 276
   at Vintagestory.GameContent.BlockClutterBookshelf.GetTypeProps(String code, ItemStack stack, BEBehaviorShapeFromAttributes be) in VSSurvivalMod\Lore\ResoArchives\BlockClutterBookshelf.cs:line 150
   at Vintagestory.GameContent.BlockShapeFromAttributes.GetLightHsv(IBlockAccessor blockAccessor, BlockPos pos, ItemStack stack) in VSSurvivalMod\Block\BlockShapeFromAttributes.cs:line 582
   at Vintagestory.API.Common.Block.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 2235
   at Vintagestory.GameContent.BlockShapeFromAttributes.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VSSurvivalMod\Block\BlockShapeFromAttributes.cs:line 648
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(ICoreClientAPI capi, ItemStack stack) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 33
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onCreatePagesAsync() in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 79
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 418
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 6/6/2024 11:08:50 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3527, time stamp: 0x83efbeab
Exception code: 0xe0434352
Fault offset: 0x000000000006543c
Faulting process id: 0x0xf094
Faulting application start time: 0x0x1dab82c456d9dd3
Faulting application path: C:\Users\thekr\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 7d04f1d1-3649-4a25-82e5-acb0a8c1e872
Faulting package full name: 
Faulting package-relative application ID:  }
```

**Comment by thekrazykitten** [comment]
Correction: this is on version 1.19.8

**Comment by Craluminum2413** [comment]
1.20 had some fixes for bookshelves, I will reopen if someone reproduces it on 1.20
