### ISSUE TITLE
Crash while opening inventory 

### ISSUE THREAD

**Issue by Resserfis** [anegostudios/VintageStory-Issues#4485]
### Game Version

v1.20-pre.11

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I just was testing the maltiez firearms and i placed a block and when i was going to open the inventory i pressed E and my game crashed (this happened to me in 1.20-pre.9 with only combat overhaul mod)

### How to reproduce

1 Install combat overhaul mod 2 make the idiot placing blocks and testing 3 press E 4 Your game crashes

### Logs
```
Running on 64 bit Windows 10.0.19045.0 with 16307 MB RAM
Game Version: v1.20.0-pre.11 (Unstable)
10/11/2024 11:11:57: Critical error occurred
Loaded Mods: combatoverhaul@0.0.44, game@1.20.0-pre.11, maltiezcrossbows@0.5.1, maltiezfirearms@0.7.2, creative@1.20.0-pre.11, survival@1.20.0-pre.11
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.Client.GuiElementVerticalTabs.SetValue(Int32 index, Boolean triggerHandler) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementVerticalTabs.cs:line 309
   at Vintagestory.Client.NoObf.GuiDialogInventory.ComposeCreativeInvDialog() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 248
   at Vintagestory.Client.NoObf.GuiDialogInventory.ComposeGui(Boolean firstBuild) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 91
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnGuiOpened() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 444
   at Vintagestory.API.Client.GuiDialog.TryOpen(Boolean withFocus) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 274
   at Vintagestory.Client.NoObf.GuiDialogInventory.TryOpen() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 437
   at Vintagestory.API.Client.GuiDialog.Toggle() in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 343
   at Vintagestory.API.Client.GuiDialog.OnKeyCombinationToggle(KeyCombination viaKeyComb) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 410
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnKeyCombinationToggle(KeyCombination viaKeyComb) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 541
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean isGlobal, Boolean fallBack, Boolean keyup) in VintagestoryLib\Client\HotkeyManager.cs:line 431
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1744
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 230
   at OpenTK.Windowing.Desktop.NativeWindow.KeyCallback(Window* window, Keys key, Int32 scancode, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 13/10/2024 11:58:49, Site = , Source = Application Error, Message = Nombre de la aplicación con errores: Vintagestory.exe, versión: 1.20.0.0, marca de tiempo: 0x66470000
Nombre del módulo con errores: KERNELBASE.dll, versión: 10.0.19041.4842, marca de tiempo: 0xe6d00f33
Código de excepción: 0xe0434352
Desplazamiento de errores: 0x000000000003b699
Identificador del proceso con errores: 0x4be0
Hora de inicio de la aplicación con errores: 0x01db1ccd97ed8313
Ruta de acceso de la aplicación con errores: D:\Vintagestory\Vintagestory.exe
Ruta de acceso del módulo con errores: C:\WINDOWS\System32\KERNELBASE.dll
Identificador del informe: 24e2a75a-20fd-4f95-93eb-166199461d39
Nombre completo del paquete con errores: 
Identificador de aplicación relativa del paquete con errores:  }
```

**Comment by Craluminum2413** [comment]
@Resserfis Try without mods

**Comment by Resserfis** [comment]
yep is a problem from combat overhaul
