### ISSUE TITLE
Critical Error Loading Multiplayer Server

### ISSUE THREAD

**Issue by jBosh0404** [anegostudios/VintageStory-Issues#4489]
### Game Version

v1.20.0-pre.11

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

When attempting to load/log-in to a multiplayer server, a critical error message appears in the Crash Reporter at the point that the game reaches the "Data received, launching client instance" stage. The specific server I was attempting to load is named "Silent Meadows". The error message is as follows:

```
Running on 64 bit Windows 10.0.19045.0 with 32726 MB RAM
Game Version: v1.20.0-pre.11 (Unstable)
10-Nov-24 12:21:02 PM: Critical error occurred
Loaded Mods: game@1.20.0-pre.11, creative@1.20.0-pre.11, survival@1.20.0-pre.11
System.Exception: Don't know how to instantiate item of class 'ItemSkillTimeswitch' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass) in VintagestoryLib\Common\ClassRegistry.cs:line 274
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType packet, IWorldAccessor world, ClassRegistry registry) in VintagestoryLib\Common\Network\ItemTypeNet.cs:line 18
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(List`1 items, Int32 listSize) in VintagestoryLib\Client\Systems\Startup.cs:line 592
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes() in VintagestoryLib\Client\Systems\Startup.cs:line 404
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in VintagestoryLib\Client\Systems\Startup.cs:line 346
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 120
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

### How to reproduce

1. Run Vintage Story v1.20.0-pre.11
2. Select "Multiplayer"
3. Select "Browse public servers"
4. Select "Silent Meadows"
5. Select "Join Server"
6. Application will download data from server
7. Application will display "Data received, launching client instance..."
8. Application will throw critical error message in the Vintage Story Crash Reporter

### Screenshots

![image](https://github.com/user-attachments/assets/bb27ebaa-7959-46aa-9322-d34b31f352f1)

### Logs

```Log```
[client-main.log](https://github.com/user-attachments/files/17692636/client-main.log)

**Comment by jBosh0404** [comment]
Upon further investigation, this seems to have been a version mismatch issue. I just noticed that the server I was trying to connect to is on version pre.13, not pre.11.
