### ISSUE TITLE
World Generation

### ISSUE THREAD

**Issue by TheZuspect** [anegostudios/VintageStory-Issues#4510]
### Game Version

v. 1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Everytime when i will generate a world, its crashed. I have no idea what the problem is

### Logs

```Log```
Running on 64 bit Windows 10.0.22631.0 with 32693 MB RAM
Game Version: v1.19.8 (Stable)
14.11.2024 01:02:30: Critical error occurred
Loaded Mods: vshud@1.3.13, game@1.19.8, creative@1.19.8, survival@1.19.8
System.Collections.Generic.KeyNotFoundException: The given key 'applySsao' was not present in the dictionary.
   at Vintagestory.Client.NoObf.ShaderProgramBase.Uniform(String uniformName, Int32 value) in VintagestoryLib\Client\ClientPlatform\ShaderProgramBase.cs:line 141
   at Vintagestory.Client.NoObf.ShaderProgramStandard.set_ApplySsao(Int32 value) in VintagestoryLib\Client\Render\Shader\ShaderPrograms.cs:line 981
   at Vintagestory.Client.NoObf.SystemRenderSunMoon.OnRenderFrame3D(Single dt) in VintagestoryLib\Client\Systems\Render\RenderSunMoon.cs:line 281
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 200
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 806
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 901
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 730
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 2
==================================
{ TimeGenerated = 14.11.2024 01:01:06, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.8.0, Zeitstempel: 0x661e0000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x0x17ec
Startzeit der fehlerhaften Anwendung: 0x0x1db3627a183acd8
Pfad der fehlerhaften Anwendung: C:\Users\sebas\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\sebas\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: cd079242-7a47-436c-85b9-c4fb4a0db597
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 14.11.2024 00:56:08, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.8.0, Zeitstempel: 0x661e0000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x0x3fc8
Startzeit der fehlerhaften Anwendung: 0x0x1db3625a2bf0ddf
Pfad der fehlerhaften Anwendung: C:\Users\sebas\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\sebas\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: edc17145-f9f4-47f4-a398-7319225931a6
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }

**Comment by Craluminum2413** [comment]
Did you install any mods before?

**Comment by TheZuspect** [comment]
So I completely uninstalled and reinstalled the game, but it didn't help, it keeps crashing. And no i didnt install any mods


Running on 64 bit Windows 10.0.22631.0 with 32693 MB RAM
Game Version: v1.19.8 (Stable)
14.11.2024 01:17:50: Critical error occurred
Loaded Mods: vshud@1.3.13, game@1.19.8, creative@1.19.8, survival@1.19.8
System.Collections.Generic.KeyNotFoundException: The given key 'applySsao' was not present in the dictionary.
   at Vintagestory.Client.NoObf.ShaderProgramBase.Uniform(String uniformName, Int32 value) in VintagestoryLib\Client\ClientPlatform\ShaderProgramBase.cs:line 141
   at Vintagestory.Client.NoObf.ShaderProgramStandard.set_ApplySsao(Int32 value) in VintagestoryLib\Client\Render\Shader\ShaderPrograms.cs:line 981
   at Vintagestory.Client.NoObf.SystemRenderSunMoon.OnRenderFrame3D(Single dt) in VintagestoryLib\Client\Systems\Render\RenderSunMoon.cs:line 281
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 200
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 806
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 901
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 730
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
@misterMishler Your issue is caused by hudclock mod

**Comment by misterMishler** [comment]
JUST found that and came back to apologize and remove my post.  Apologies;  I'd not played in quite a while and didn't think I had any mods installed.

Impressively fast reply.

**Comment by radfast** [comment]
> Loaded Mods: vshud@1.3.13, game@1.19.8, creative@1.19.8, survival@1.19.8

Please report the issue to the VSHUD mod author, with a screenshot of your graphics settings.  That will, with any luck, help the mod author to ensure that other people do not have the same issue
