### ISSUE TITLE
Crash save multiplayer

### ISSUE THREAD

**Issue by CarbonCFRP** [anegostudios/VintageStory-Issues#4512]
### Game Version

v1.20 pre 13

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Game crash after playing 18 hours. When i play alone everything ok. but when friend join local net game crash

### How to reproduce

how i can save my progress, tired starting new games

### Logs

Running on 64 bit Windows 10.0.19045.0 with 16313 MB RAM
Game Version: v1.20.0-pre.13 (Unstable) by OverF1X  
14.11.2024 12:07:04: Critical error occurred
Loaded Mods: game@1.20.0-pre.13, creative@1.20.0-pre.13, survival@1.20.0-pre.13
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Vintagestory.GameContent.ClothSystem.UpdateMesh(MeshData updateMesh, Single dt) in VSEssentials\Systems\Cloth\ClothSystem.cs:line 343
   at Vintagestory.GameContent.ClothManager.OnRenderFrame(Single dt, EnumRenderStage stage) in VSEssentials\Systems\Cloth\ClothManager.cs:line 144
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 814
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 825
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 161
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 92
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3

**Comment by CarbonCFRP** [comment]
![Uploading Безымянный.png…]()
