### ISSUE TITLE
Game keeps crashing 

### ISSUE THREAD

**Issue by SixplyDev** [anegostudios/VintageStory-Issues#4518]
### Game Version

v1.19.8.0

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Every time I try to start up a singleplayer world, my game just crashes. It crashes whenever I customize the world and when I don't.

### How to reproduce

Uhh just boot up a singleplayer world I guess with the mods enabled.

### Logs

```Running on 64 bit Windows 10.0.22631.0 with 14029 MB RAM
Game Version: v1.19.8 (Stable)
11/15/2024 2:08:05 PM: Critical error occurred in the following mod: combatoverhaul@0.0.52
Loaded Mods: aculinaryartillery@1.2.1, amitipackforest@1.19.6, bettersticks@1.1.0, bettertraders@0.0.7, chiseltools@1.14.1, combatoverhaul@0.0.52, floralzonescaribbeanregion@1.0.8, millwright@1.1.8, thatchexpanded@1.1.1, Vanilla_PlusWorldGen@1.3.5, game@1.19.8, vsimgui@1.1.7, ancienttools@1.5.18, apegrapes@1.1.3, armory@0.0.5, bedspawnv2@1.2.0, betterruins@0.3.9, butchering@1.6.8, commonlib@2.4.0, expandedfoods@1.7.2, fromgoldencombs@1.6.3, hudclock@3.4.0, kitchwaypointlabeler@1.1.0, knapster@2.11.2, ksrealisticfarming@1.0.3, levelup@1.3.4, maltiezfirearms@0.7.3, medievalexpansion@3.13.1, sailboat@1.3.1, simpletailoring@1.1.0, stonebakeoven@1.1.3, creative@1.19.8, vskingdom@1.7.3, vsquest@1.2.0, survival@1.19.8, vsvillage@1.0.6, wildfarmingrevival@1.2.9, vsvillagedesert@1.0.0, vsvillageviking@1.0.0, vsvillageaged@0.0.4, vsvillageindustrial@0.0.4, vsvillagetowers@0.0.4
System.MissingMethodException: Method not found: 'Void Vintagestory.Client.NoObf.ShaderProgramBase.set_AssetDomain(System.String)'.
   at CombatOverhaul.CombatOverhaulAnimationsSystem.LoadAnimatedItemShaders()
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerReloadShaders() in VintagestoryLib\Client\Util\ClientEventManager.cs:line 432
   at Vintagestory.Client.NoObf.ShaderAPI.ReloadShaders() in VintagestoryLib\Client\API\ShaderAPI.cs:line 53
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerReady(Packet_Server packet) in VintagestoryLib\Client\Systems\Startup.cs:line 881
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 448
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 442
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/15/2024 2:05:31 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0xc38
Faulting application start time: 0x0x1db3793e39938c8
Faulting application path: C:\Users\user\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\user\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: a3578178-b577-4f82-9655-422491f4cf30
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/15/2024 1:23:32 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x31b0
Faulting application start time: 0x0x1db37939d1e4478
Faulting application path: C:\Users\user\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\user\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: a526e555-b0db-457c-b60e-52fa8d770edf
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/15/2024 1:17:43 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x3864
Faulting application start time: 0x0x1db3792e2da6803
Faulting application path: C:\Users\user\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\user\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 2215c17d-f9ef-4a36-8f62-03a2cd867f19
Faulting package full name: 
Faulting package-relative application ID:  }```

**Comment by Craluminum2413** [comment]
Caused by mod

**Comment by SixplyDev** [comment]
Obviously it's called by a mod but I don't know which. Is anyone able to help me?

**Comment by Craluminum2413** [comment]
> Obviously it's called by a mod but I don't know which. Is anyone able to help me?

Combat Overhaul

**Comment by SixplyDev** [comment]
Thank you
