### ISSUE TITLE
loaded mods

### ISSUE THREAD

**Issue by sponk3214** [anegostudios/VintageStory-Issues#4520]
Running on 32 bit Windows with 4 GB RAM 
Game Version: v1.17.9 (Stable) by OverF1X  
15/11/2024 07:00:35: Critical error occurred
Loaded Mods: 
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass14_0.<.ctor>b__0()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)

**Comment by Craluminum2413** [comment]
Pirated versions are not supported
