### ISSUE TITLE
Client crashes without loading any mods, even after clean re-install

### ISSUE THREAD

**Issue by Shinji170981** [anegostudios/VintageStory-Issues#4536]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

None

### Description

I had an issue that my client kept crashing during the boot up of singleplayer and multiplayer loading.

I already did a clean install and added only the mods and configs after booting up the game vanilla once.

So even after wiping all files, the game still keeps crashing and i am now at a loss. Already lost my multiplayer server with over 50 hours of playtime to this issue and was unable to stream the session any longer.
Also removed several mods before wiping the folders but that also didn't help.

If you need more files, i will gladly provide them.

### How to reproduce

Either start a singleplayer or multiplayer game and during the loading process, the client will crash.

### Logs

Running on 64 bit Windows 10.0.19045.0 with 65343 MB RAM
Game Version: v1.19.8 (Stable)
19.11.2024 18:36:07: Critical error occurred
Loaded Mods: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at ACulinaryArtillery.ItemExpandedRawFood.UpdateAndGetTransitionStates(IWorldAccessor world, ItemSlot inslot)
   at Vintagestory.API.Common.CollectibleObject.AppendPerishableInfoText(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1822
   at ACulinaryArtillery.ItemExpandedRawFood.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at ACulinaryArtillery.ItemExpandedFood.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(ICoreClientAPI capi, ItemStack stack) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 33
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onCreatePagesAsync() in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 84
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 418
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 120
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 19.11.2024 17:51:27, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x1c48
Faulting application start time: 0x01db3aa1bbdd137d
Faulting application path: D:\Vintagestory\Vintagestory.exe
Faulting module path: D:\Vintagestory\Lib\openal32.dll
Report ID: d1fb8f97-4e4f-463e-816a-9b701bad3660
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 19.11.2024 17:40:18, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: ntdll.dll, version: 10.0.19041.5007, time stamp: 0x688f8c4b
Exception code: 0xc0000005
Fault offset: 0x00000000000649e6
Faulting process ID: 0x6808
Faulting application start time: 0x01db3aa1a9c37714
Faulting application path: D:\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report ID: c33f4270-09b1-448e-a43e-1db764e66c5d
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 19.11.2024 16:55:07, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.5131, time stamp: 0x011921da
Exception code: 0xe0434352
Fault offset: 0x000000000003b699
Faulting process ID: 0x5f34
Faulting application start time: 0x01db3a9a69ca6d38
Faulting application path: D:\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: 4855712e-3f71-4ce8-9be9-8799d02eb9b7
Faulting package full name: 
Faulting package-relative application ID:  }
[client-audit.txt](https://github.com/user-attachments/files/17819300/client-audit.txt)
[client-crash.txt](https://github.com/user-attachments/files/17819301/client-crash.txt)
[client-debug.txt](https://github.com/user-attachments/files/17819302/client-debug.txt)
[client-main.txt](https://github.com/user-attachments/files/17819303/client-main.txt)

[server-audit.txt](https://github.com/user-attachments/files/17819264/server-audit.txt)
[server-build.txt](https://github.com/user-attachments/files/17819265/server-build.txt)
[server-chat.txt](https://github.com/user-attachments/files/17819266/server-chat.txt)
[server-debug.txt](https://github.com/user-attachments/files/17819267/server-debug.txt)
[server-event.txt](https://github.com/user-attachments/files/17819268/server-event.txt)
[server-main.txt](https://github.com/user-attachments/files/17819269/server-main.txt)

**Comment by Craluminum2413** [comment]
Cased bu aculinaryartillery mod
