### ISSUE TITLE
Crashing when i go from multiplayer to singleplayer(GIVE HELP IF YOU KNOW WHAT TO DO DONT JUST SAY DUPLICATE ISSUE)

### ISSUE THREAD

**Issue by Aethandus** [anegostudios/VintageStory-Issues#4539]
### Game Version

v1.19.8

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Going from a modded multiplayer server to a singleplayer non modded gamemode and i crash when i try and play singleplayer, but not when im playing multiplayer

### How to reproduce

it crashes (

### Logs

```Log```Running on 64 bit Windows 10.0.19045.0 with 8054 MB RAM
Game Version: v1.19.8 (Stable)
11/19/2024 8:31:28 PM: Critical error occurred
Loaded Mods: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2507
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStates(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2455
   at Vintagestory.API.Common.CollectibleObject.AppendPerishableInfoText(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1814
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1657
   at Vintagestory.API.Common.Block.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 2257
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 400
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(ICoreClientAPI capi, ItemStack stack) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 40
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onCreatePagesAsync() in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 84
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 418
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 120
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by Aethandus** [comment]
idk what to do i dont read code so it looks like jibberish to me guys

**Comment by Craluminum2413** [comment]
Sorry but this is a duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4225

**Comment by radfast** [comment]
Thanks, this is a crash seen only while something is still trying to be read during game shutdown while the game was still starting up - it should not affect normal gameplay. The fundamental reason was the client was still trying to build the handbook without noticing that the rest of the game had already shut down. For the future it is fixed in upcoming 1.20.2-rc.2.
