### ISSUE TITLE
Ran back to the base and got this.

### ISSUE THREAD

**Issue by Krontos** [anegostudios/VintageStory-Issues#4541]
### Game Version

v1.20.0-pre.13

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Running on 64 bit Windows 10.0.19045.0 with 16215 MB RAM
Game Version: v1.20.0-pre.13 (Unstable) by OverF1X  
20.11.2024 20:53:07: Critical error occurred
Loaded Mods: game@1.20.0-pre.13, creative@1.20.0-pre.13, survival@1.20.0-pre.13
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.Entities.Entity.get_FrustumSphereRadius() in VintagestoryApi\Common\Entity\Entity.cs:line 1087
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 825
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 161
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 92
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

### How to reproduce

Ran back to the base and got this.

### Logs

Running on 64 bit Windows 10.0.19045.0 with 16215 MB RAM
Game Version: v1.20.0-pre.13 (Unstable) by OverF1X  
20.11.2024 20:53:07: Critical error occurred
Loaded Mods: game@1.20.0-pre.13, creative@1.20.0-pre.13, survival@1.20.0-pre.13
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.Entities.Entity.get_FrustumSphereRadius() in VintagestoryApi\Common\Entity\Entity.cs:line 1087
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 825
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 161
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 92
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment]
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4163

**Comment by Krontos** [comment]
> Дубликат #4163

We don't have it

**Comment by Krontos** [comment]
We don't have a Terminus teleporter.

**Comment by Craluminum2413** [comment]
@Krontos Crash is exactly the same
