### ISSUE TITLE
Mayor's table game crash?

### ISSUE THREAD

**Issue by cooliestof** [anegostudios/VintageStory-Issues#4542]
### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Whenever I go to open my Mayors table in my village, my entire game crashes. 

### How to reproduce

Place a Mayor's table somewhere within a village, and try to open it.

### Logs

Running on 64 bit Windows 10.0.22631.0 with 32581 MB RAM
Game Version: v1.19.8 (Stable)
2024-11-20 10:57:00 PM: Critical error occurred in the following mod: vsvillage@1.0.6
Loaded Mods: floralzonescaperegion@1.0.10, floralzonescaribbeanregion@1.0.7, floralzonescentralaustralianregion@1.0.5, floralzoneseastasiaticregion@1.0.3, floralzonesneozeylandicregion@1.0.3, rope-bridges@1.1.0, ropebridgescompatibility@1.1.0, sgsclasses@1.0.0, sgstweaks@1.0.0, updatechange@, wildclay@1.0.0, game@1.19.8, vtr@3.0.3, egocaribautomapmarkers@3.1.0, betterfirepit@1.1.4, betterruins@0.3.7, carryon@1.7.4, commonlib@2.5.0-rc.2, farmlanddropssoil@1.4.0, herbarium@1.3.0, rivers@3.1.0, sgspatches-floralzones@1.0.0, stickemup@1.1.0, creative@1.19.8, survival@1.19.8, vsvillage@1.0.6, sgspatches-rivers@1.1.0, stonequarry@3.3.1, vsvillageaged@0.0.4, wildcraftfruit@1.2.2, wildcraftherb@0.0.1, wildcrafttree@1.2.0, sgspatches-stonequarry@1.0.0
System.Collections.Generic.KeyNotFoundException: The given key '32420, 144, 29202' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at VsVillage.Village.InitWayPoints() in E:\Workspace\vintage_story_mods\vsvillage\src\Systems\VillageSystem\Village.cs:line 151
   at VsVillage.Village.Init(ICoreAPI api) in E:\Workspace\vintage_story_mods\vsvillage\src\Systems\VillageSystem\Village.cs:line 36
   at VsVillage.VillageManager.OnVillageMessage(Village village, ICoreClientAPI capi) in E:\Workspace\vintage_story_mods\vsvillage\src\Systems\VillageSystem\VillageManager.cs:line 119
   at VsVillage.VillageManager.<>c__DisplayClass5_0.<StartClientSide>b__0(Village village) in E:\Workspace\vintage_story_mods\vsvillage\src\Systems\VillageSystem\VillageManager.cs:line 43
   at Vintagestory.Client.NoObf.NetworkChannel.<>c__DisplayClass12_0`1.<SetMessageHandler>b__0(Packet_CustomPacket p) in VintagestoryLib\Client\API\NetworkChannel.cs:line 74
   at Vintagestory.Client.NoObf.NetworkAPI.HandleCustomPacket(Packet_Server packet) in VintagestoryLib\Client\API\NetworkAPI.cs:line 95
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 2
==================================
{ TimeGenerated = 2024-11-20 8:46:30 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x73b0
Faulting application start time: 0x0x1db3bbf82257674
Faulting application path: C:\Users\User\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\User\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 1bb016d4-184f-488e-934f-8377d5adbb8d
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 2024-10-01 6:38:05 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x2850
Faulting application start time: 0x0x1db143cec7d763c
Faulting application path: C:\Users\User\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\User\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: d5f5c3c2-f16b-45d4-ab11-1d8821d0e607
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Caused by village mod
