### ISSUE TITLE
The tamed elk inventory is broken

### ISSUE THREAD

**Issue by iForged** [anegostudios/VintageStory-Issues#4559]
### Game Version

1.20.0-pre13

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

When trying to place any item into its inventory, the server kicks the player (although the item does appear in the inventory). If the player re-enters the game and tries to retrieve the item, they are either kicked again or the game crashes. After this, the item disappears from the game world.
p.s. This tamed elk has been on the server for about a week, and there were no issues with it before.

Video: https://youtu.be/IxtyImFqgIs
The video doesn't show the crash moment, as the recording stopped at the time of the crash.

### Logs

```Running on 64 bit Windows 10.0.19045.0 with 32694 MB RAM
Game Version: v1.20.0-pre.13 (Unstable)
23.11.2024 15:22:33: Critical error occurred
Loaded Mods: game@1.20.0-pre.13, betterruins@0.3.9, creative@1.20.0-pre.13, survival@1.20.0-pre.13
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorPlayerPhysics.OnRenderFrame(Single dt, EnumRenderStage stage) in VSEssentials\Entity\Behavior\BehaviorPlayerPhysics.cs:line 338
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 825
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 161
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 92
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10.11.2024 15:11:22, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x2768
Faulting application start time: 0x01db336999578b77
Faulting application path: F:\vs_client_win-x64_1.20.0-pre.11\Vintagestory.exe
Faulting module path: F:\vs_client_win-x64_1.20.0-pre.11\Lib\openal32.dll
Report ID: eec67112-99b0-4354-bab5-e65fe8b035e3
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 10.11.2024 13:40:20, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x6638
Faulting application start time: 0x01db335c7e057b82
Faulting application path: F:\vs_client_win-x64_1.20.0-pre.7\Vintagestory.exe
Faulting module path: F:\vs_client_win-x64_1.20.0-pre.7\Lib\openal32.dll
Report ID: f299116f-92e3-4789-94d9-4536a19d347c
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 09.11.2024 21:58:14, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x1200
Faulting application start time: 0x01db32d91e5c168d
Faulting application path: F:\vs_client_win-x64_1.20.0-pre.11\Vintagestory.exe
Faulting module path: F:\vs_client_win-x64_1.20.0-pre.11\Lib\openal32.dll
Report ID: cadbb739-5951-48d1-93e9-6b21eddb0a3b
Faulting package full name: 
Faulting package-relative application ID:  }```

**Comment by iForged** [comment]
Clearing the tamed elk inventory didn't help resolve the issue.

**Comment by iForged** [comment]
The issue was resolved by replacing the Saddlebags with Sturdy Saddlebags. Replacing the Saddlebags with identical ones still causes a crash.

**Comment by Th3Dilli** [comment]
this was probably fixed some time ago 

since I can not reproduce the issue
