### ISSUE TITLE
Sheep can´t pass gates - starts to spam server

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#4572]
### Game Version

1.20pre11

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

No player interaction, Sheep wants to pass trough the gate - but can´t .

### Logs

[Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.FindSteppableCollisionBox(Cuboidd entityCollisionBox, Double motionY, Vec3d walkVector) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 625
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.HandleSteppingOnBlocks(EntityPos pos, Vec3d moveDelta, Single dtFac, EntityControls controls) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 528
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.ApplyTests(EntityPos pos, EntityControls controls, Single dt, Boolean remote) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 229
   at Vintagestory.Server.PhysicsManager.DoWork() in VintagestoryLib\Server\PhysicsManager.cs:line 524
   at Vintagestory.Common.LoadBalancer.SynchroniseWorkToMainThread() in VintagestoryLib\Common\LoadBalancer.cs:line 81
   at Vintagestory.Server.PhysicsManager.TickFixedRate30TPS() in VintagestoryLib\Server\PhysicsManager.cs:line 299
   at Vintagestory.Server.PhysicsManager.ServerTick(Single dt) in VintagestoryLib\Server\PhysicsManager.cs:line 100
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 904

**Comment by Craluminum2413** [comment]
Does it happen in pre.13?

**Comment by DejFidOFF** [comment]
> Does it happen in pre.13?

idk did not using 13 cause major sc hand bug.

**Comment by DejFidOFF** [comment]
I think I faund what´s triggering this error spam at server. Sheep needs to pass the gate, but can´t. If gate is removed everything is ok.
![sheep1](https://github.com/user-attachments/assets/74f65c92-0385-4f26-873c-11d4b6bcc37d)

**Comment by DejFidOFF** [comment]
hope it´s helpful.

**Comment by tyronx** [comment]
this should already be fixed in one of the release candidates, otherwise please reopen ticket
