### ISSUE TITLE
System.Exception: No color exists for color code devastation on all worlds.

### ISSUE THREAD

**Issue by VileAce** [anegostudios/VintageStory-Issues#4573]
### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I install 1.20 and it ran fine.  I uninstalled 1.20 and installed 1.19.8 and it crashes every time I try to play a single player map.  I'm new to the game so not sure what to do.  I did run the map in repair mode and the game still crashed.

### How to reproduce

Create world in exploration mode.  
Modified some world creation setting.

Crash on first world creation and crashes on every start after that.
Attempted to create new worlds and all still crash.

Log files from 2 separate worlds attached.  All crash with System.Exception: No color exists for color code devastation

### Screenshots

![Vintagestory_24re71nH78](https://github.com/user-attachments/assets/cf7fbe1d-3c6e-46ff-a7f8-edba7c5e2528)

https://i.imgur.com/e39aNp1.jpeg

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32702 MB RAM
Game Version: v1.19.8 (Stable)
11/28/2024 1:36:13 PM: Critical error occurred
Loaded Mods: game@1.19.8, creative@1.19.8, survival@1.19.8
System.Exception: No color exists for color code devastation
   at Vintagestory.GameContent.ChunkMapLayer.OnLoaded() in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 230
   at Vintagestory.GameContent.WorldMapManager.OnLvlFinalize() in VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 197
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerLevelFinalize() in VintagestoryLib\Client\API\ClientEventAPI.cs:line 383
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleLevelFinalize(Packet_Server packet) in VintagestoryLib\Client\Systems\Startup.cs:line 1035
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 448
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 442
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/28/2024 1:35:37 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x9188
Faulting application start time: 0x01db41c42bc85fce
Faulting application path: E:\Games\Vintagestory\Vintagestory.exe
Faulting module path: E:\Games\Vintagestory\Lib\openal32.dll
Report Id: 32b8bb56-8bb3-4727-b671-31988a4a4d2c
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/28/2024 1:34:29 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x7644
Faulting application start time: 0x01db41c40ae826b9
Faulting application path: E:\Games\Vintagestory\Vintagestory.exe
Faulting module path: E:\Games\Vintagestory\Lib\openal32.dll
Report Id: 2c4b7294-4545-42eb-b844-bac155f77480
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/28/2024 1:32:39 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x91fc
Faulting application start time: 0x01db41c3b98aed96
Faulting application path: E:\Games\Vintagestory\Vintagestory.exe
Faulting module path: E:\Games\Vintagestory\Lib\openal32.dll
Report Id: decbf1be-0635-46bb-8348-551aafe42dda
Faulting package full name: 
Faulting package-relative application ID:  }

**SECOND WORLD CRASH**

Running on 64 bit Windows 10.0.19045.0 with 32702 MB RAM
Game Version: v1.19.8 (Stable)
11/28/2024 1:44:26 PM: Critical error occurred
Loaded Mods: game@1.19.8, creative@1.19.8, survival@1.19.8
System.Exception: No color exists for color code devastation
   at Vintagestory.GameContent.ChunkMapLayer.OnLoaded() in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 230
   at Vintagestory.GameContent.WorldMapManager.OnLvlFinalize() in VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 197
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerLevelFinalize() in VintagestoryLib\Client\API\ClientEventAPI.cs:line 383
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleLevelFinalize(Packet_Server packet) in VintagestoryLib\Client\Systems\Startup.cs:line 1035
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 448
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 442
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/28/2024 1:40:45 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x1df8
Faulting application start time: 0x01db41c45386897d
Faulting application path: E:\Games\Vintagestory\Vintagestory.exe
Faulting module path: E:\Games\Vintagestory\Lib\openal32.dll
Report Id: 14558a9f-20ad-493f-92c8-fb13af29781e
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/28/2024 1:35:37 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x9188
Faulting application start time: 0x01db41c42bc85fce
Faulting application path: E:\Games\Vintagestory\Vintagestory.exe
Faulting module path: E:\Games\Vintagestory\Lib\openal32.dll
Report Id: 32b8bb56-8bb3-4727-b671-31988a4a4d2c
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/28/2024 1:34:29 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x7644
Faulting application start time: 0x01db41c40ae826b9
Faulting application path: E:\Games\Vintagestory\Vintagestory.exe
Faulting module path: E:\Games\Vintagestory\Lib\openal32.dll
Report Id: 2c4b7294-4545-42eb-b844-bac155f77480
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
There is no way to fix it for 1.19, since it is 1.20 feature

**Comment by VileAce** [comment]
How do I get 1.19 to work.  I uninstalled 1.20 and install 1.19.  I just want 1.19 to work.

**Comment by Craluminum2413** [comment]
@VileAce Did you create world in 1.20 and then opened it in 1.19?
