### ISSUE TITLE
no arrows Bow crash

### ISSUE THREAD

**Issue by Flowfulfish** [anegostudios/VintageStory-Issues#4582]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

using a bow with no arrows in inventory crashes the game. works fine with arrows, the second you run out and right click with the bow, crashes immediately. this has happened to me four different times.

### How to reproduce

1. hold a bow 2. have arrows 2. fire bow 3. run out 4. keep right clicking bow with no arrows 5. crash

### Logs

Running on 64 bit Windows 10.0.19045.0 with 8087 MB RAM
Game Version: v1.19.8 (Stable)
2/12/2024 2:45:40 PM: Critical error occurred
Loaded Mods: game@1.19.8, creative@1.19.8, survival@1.19.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemBow.<>c__DisplayClass4_0.<GetNextArrow>b__0(ItemSlot invslot) in VSSurvivalMod\Item\ItemBow.cs:line 65
   at Vintagestory.API.Common.EntityPlayer.WalkInventory(OnInventorySlot handler) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 1405
   at Vintagestory.GameContent.ItemBow.GetNextArrow(EntityAgent byEntity) in VSSurvivalMod\Item\ItemBow.cs:line 61
   at Vintagestory.GameContent.ItemBow.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling) in VSSurvivalMod\Item\ItemBow.cs:line 82
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 854
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 386
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by radfast** [comment]
Thank for reporting.  Fixed in next upcoming release (1.20-rc.5)  If you need to continue playing 1.19.8, please be aware that we are no longer updating 1.19 versions, but 1.20.0 is getting close to stability
