### ISSUE TITLE
crash while making clay pot

### ISSUE THREAD

**Issue by johnplewis1969** [anegostudios/VintageStory-Issues#459]
**Game Version:** 1.12.6
**Platform:** Windows
**Modded:** No 

### Description
crash while making clay pot

### How to reproduce
It crashes 
### Logs
```
Running on 64 bit Windows with 12 GB RAM 
Version: v1.12.6 (Stable)3/7/2020 5:45:38 PM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockEntityClayForm.OnCopyLayer()
   at Vintagestory.GameContent.BlockEntityClayForm.OnUseOver(IPlayer byPlayer, Vec3i voxelPos, BlockFacing facing, Boolean mouseBreakMode)
   at Vintagestory.GameContent.ItemClay.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at _atfqQJs3jF5TiC7cub21O31NBFr._MAHEnO4oSxH1NJuEFByieYPY9p2()
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at _CeG6XgwLRetaWBDy7Vuk520qgAQ._1nx5JhWedGp2NbeAYbMQcrPTaEJ(Single )
   at _CeG6XgwLRetaWBDy7Vuk520qgAQ._NsSwcIXfXJazD9UNZT7ucuORhzk(Single )
   at _WgVFI8rJI44rVQv521oBIjuWBxl._5QlzzE5xabSDGWATlodeOUeMK2b(Single )
   at _3bQQdrrneYMg7sUqAp4FsQ2XEfN._lShc2IGpVH0SOA7ydOiSsErkATH(Single )
   at _3bQQdrrneYMg7sUqAp4FsQ2XEfN._k3aLAIz3swGZO8aqd7pDrKnxALc(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _TPKNmFO93xHjVpa9EspHS9LXWzH._TsFumLr7TNG7iLJEc5uVYqFSeNG(_qRgBLoQrmfmbiUcRN39BpLhs3mN , String[] )
   at _QHQMScYkRrkBYdQDlv19fyrujIx._TsFumLr7TNG7iLJEc5uVYqFSeNG(ThreadStart )
-------------------------------


In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```

**Comment by tyronx** [comment]
thanks for the report, is this reproducible?
Looking at the code i wouldn't know how such crash could trigger

**Comment by tyronx** [comment]
No new feedback in a long time, closing issue.
