### ISSUE TITLE
Unexpected crash while in the Resonance Archives

### ISSUE THREAD

**Issue by Alejo-el-cangrejo-2007** [anegostudios/VintageStory-Issues#4603]
### Game Version

v1.20.0 rc. 1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

El juego se cierra mientras estás en las nuevas estructuras (no siempre)

### Logs

Running on 64 bit Windows 10.0.19045.0 with 6376 MB RAM
Game Version: v1.20.0-rc.1 (Unstable)
5/12/2024 14:52:30: Critical error occurred
Loaded Mods: game@1.20.0-rc.1, creative@1.20.0-rc.1, survival@1.20.0-rc.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityMusicTrigger.<StopMusic>b__14_0() in VSSurvivalMod\Lore\ResoArchives\BlockEntityMusicTrigger.cs:line 134
   at Vintagestory.API.Client.MusicTrack.<>c__DisplayClass20_0.<FadeOut>b__0(ILoadedSound sound) in VintagestoryApi\Client\Audio\MusicTrack.cs:line 153
   at Vintagestory.Client.LoadedSoundNative.<>c__DisplayClass64_0.<FadeTo>b__1() in VintagestoryLib\Client\ClientPlatform\ClientNative\LoadedSound.cs:line 669
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 329
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by radfast** [comment]
Thank you for reporting. The game is crashing in the Resonance Archives structure, it's related to the special music played there.
I am investigating and we will look for a fix as soon as possible

**Comment by radfast** [comment]
Thank you for reporting. This error will be fixed in upcoming 1.20-rc.2
