### ISSUE TITLE
Object Reference Crash

### ISSUE THREAD

**Issue by NordicLink** [anegostudios/VintageStory-Issues#4605]
### Game Version

v1.20.0-rc.1

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

The Game randomly crashes while I'm moving and always near an animal. This is my third crash.

### How to reproduce

Unknown. Game crashes from time to time near animals.

### Logs
```
Running on 64 bit Windows 10.0.19045.0 with 32717 MB RAM
Game Version: v1.20.0-rc.1 (Unstable)
12/5/2024 10:29:18 AM: Critical error occurred
Loaded Mods: autosifter@1.1.0, entitiesinteract@1.0.8, game@1.20.0-rc.1, justanarrowheadmold@1.0.1, medievalexpansion@3.13.1, thecritterpack@0.9.1, creative@1.20.0-rc.1, vsquest@1.2.0, survival@1.20.0-rc.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.ClientAnimator.calculateMatrices(Single dt) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 294
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 188
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 824
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 161
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 329
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Craluminum2413** [comment]
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4243

**Comment by SpearAndFang** [comment]
No Primitive Survival here, you might want to reopen this...

**Comment by Craluminum2413** [comment]
@radfast

**Comment by radfast** [comment]
Based on #4243, this is an error in the animations specified for one of the creatures, in one of the mods.  For example, `thecritterpack` seems like a mod which probably adds creatures.

To trace the cause of the issue, in a Creative World, spawn one of the non-vanilla creature types (nothing else), wait a minute or two to see if it errors.  The non-vanilla creatures are usually listed at the end of the Creatures tab in the creative mode inventory.  If you want to save time, you could use a binary-search technique.  For example, make a creative world where you spawn 4 different creatures (maybe a few of each, but only those ones).  If the crash occurs, you know it was one of those 4.  Now you can try them individually.
