### ISSUE TITLE
Client Crashes

### ISSUE THREAD

**Issue by ashyvaane** [anegostudios/VintageStory-Issues#4610]
### Game Version

1.20-rc.1

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Client crashes a minute or two after login. Removed 3 of the 14 mods we had in hopes that was it - it was not. Reading the crash log, it looks like some entity has spawned that the game can't properly process.

I'm the server owner and nothing in the server logs indicates a specific cause, only noting that the player client has crashed. It's running fine independent of these repeated crashes. There have been maybe 6 crashes in the last ten minutes between three players.

I've attached the log of my most recent crash. 

### How to reproduce

1. log in
2.  be online for up to one minute - no movement or action needed
3. crash

### Logs
```
Running on 64 bit Windows 10.0.22631.0 with 15791 MB RAM
Game Version: v1.20.0-rc.1 (Unstable)
2024-12-05 10:10:37 PM: Critical error occurred
Loaded Mods: elkcrocks@1.0.1, flourbags@1.0.5, largercrock@1.0.2, game@1.20.0-rc.1, autoatlas@1.0.1, BedRespawning@1.0.1, chickenSit@2.0.1, hudclockpatch@1.0.0, knapster@2.11.2, nbcartographer@2.0.10, creative@1.20.0-rc.1, survival@1.20.0-rc.1, xinvtweaks@1.6.2
System.Exception: A mod's entity has 62 animation joints which exceeds the max joint cap of 56. Sorry, you'll have to either disable this creature or simplify the model.
   at Vintagestory.API.Common.Animation.GenerateAllFrames(ShapeElement[] rootElements, Dictionary`2 jointsById, Boolean recursive) in VintagestoryApi\Common\Model\Animation\Animation.cs:line 97
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 188
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 824
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 161
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 329
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2024-12-05 10:08:58 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x13ff8
Faulting application start time: 0x0x1db47a50b8bb3bc
Faulting application path: C:\Users\grace\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\grace\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 79a54545-23a6-46d3-998b-adf6176f55d4
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 2024-12-05 10:06:44 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x143b4
Faulting application start time: 0x0x1db47a4e8895c3b
Faulting application path: C:\Users\grace\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\grace\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 7731059b-aa9b-4649-add7-7e4a9d644f12
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 2024-12-05 10:04:22 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x11504
Faulting application start time: 0x0x1db47a487bae131
Faulting application path: C:\Users\grace\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\grace\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: d66ae598-8848-42cb-b2ee-1002c85ba499
Faulting package full name: 
Faulting package-relative application ID:  }
```

**Comment by Craluminum2413** [comment]
Set maxAnimatedElements to 230 in `\AppData\Roaming\VintagestoryData\clientsettings.json`

**Comment by ashyvaane** [comment]
The maxAnimatedElements is already set to 230 in that location, still having this problem

**Comment by Craluminum2413** [comment]
Try disable mods

**Comment by ashyvaane** [comment]
I removed all mods, the game crashes at login now:

Running on 64 bit Windows 10.0.22631.0 with 15791 MB RAM
Game Version: v1.20.0-rc.1 (Unstable)
2024-12-06 5:47:12 AM: Critical error occurred
Loaded Mods: game@1.20.0-rc.1, creative@1.20.0-rc.1, survival@1.20.0-rc.1
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: Cannot open worldmap database file C:\Users\grace\AppData\Roaming\VintagestoryData\Maps\9c507a54-b31b-4904-98ee-eb1693240438.db, it seems to be not writable!
   at Vintagestory.API.Common.SQLiteDBConnection.OpenOrCreate(String filename, String& errorMessage, Boolean requireWriteAccess, Boolean corruptionProtection, Boolean doIntegrityCheck) in VintagestoryApi\Common\IO\SQLiteDBConnection.cs:line 42
   at Vintagestory.GameContent.ChunkMapLayer..ctor(ICoreAPI api, IWorldMapManager mapSink) in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 118
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Vintagestory.GameContent.WorldMapManager.OnLvlFinalize() in VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 193
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerLevelFinalize() in VintagestoryLib\Client\API\ClientEventAPI.cs:line 384
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleLevelFinalize(Packet_Server packet) in VintagestoryLib\Client\Systems\Startup.cs:line 1040
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\ProcessPacketTask.cs:line 16
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 785
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 254
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 92
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 329
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
System.IO.IOException: Cannot open worldmap database file C:\Users\grace\AppData\Roaming\VintagestoryData\Maps\9c507a54-b31b-4904-98ee-eb1693240438.db, it seems to be not writable!
   at Vintagestory.API.Common.SQLiteDBConnection.OpenOrCreate(String filename, String& errorMessage, Boolean requireWriteAccess, Boolean corruptionProtection, Boolean doIntegrityCheck) in VintagestoryApi\Common\IO\SQLiteDBConnection.cs:line 42
   at Vintagestory.GameContent.ChunkMapLayer..ctor(ICoreAPI api, IWorldMapManager mapSink) in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 118
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2024-12-06 5:45:31 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x14384
Faulting application start time: 0x0x1db47e4e1e34670
Faulting application path: C:\Users\grace\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\grace\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: c65b3460-065c-4b41-9366-ab5ebc2e12aa
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 2024-12-05 10:08:58 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x13ff8
Faulting application start time: 0x0x1db47a50b8bb3bc
Faulting application path: C:\Users\grace\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\grace\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 79a54545-23a6-46d3-998b-adf6176f55d4
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 2024-12-05 10:06:44 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x143b4
Faulting application start time: 0x0x1db47a4e8895c3b
Faulting application path: C:\Users\grace\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\grace\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 7731059b-aa9b-4649-add7-7e4a9d644f12
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by ashyvaane** [comment]
For clarity - mods have been removed entirely from both server side and client side.

**Comment by Craluminum2413** [comment]
It looks like you savegame is corrupted

**Comment by ashyvaane** [comment]
When I run it with a fresh world it works.

**Comment by radfast** [comment]
The issue is in AutoAtlas mod, please discuss it with that mod author or update its configuration, or just don't use that mod at all it should not be necessary.  Please don't report mod issues on VS' own Github.

The world save corruption is unlikely to be a bug in VS itself. Possible causes are things like disk corruption or a hard-shutdown / power-loss of your PC hardware while it is writing to disk - both unlikely with modern PCs and modern disks but there is still a chance it can happen.

**Comment by Darkx352** [comment]
Change your json file on the client side for autoatlas animations from 56 to 230.
