### ISSUE TITLE
Raft Seating Crash

### ISSUE THREAD

**Issue by JerryMcarter** [anegostudios/VintageStory-Issues#4627]
### Game Version

v1.20.0-rc.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Got onto the new raft item while other player was rowing. Sat in the spot the main player was sitting in, then I got the prompt to sit in the back seat for the raft and right clicked, then game crashed :(

### How to reproduce

Have two people, one on raft rowing.
Other player right click to get on the raft where other player is sitting.
Then right click to move to back spot of raft.
Game should crash

### Screenshots

Not an actual screenshot just a picture of my honest reaction...
![Capture](https://github.com/user-attachments/assets/61af7cd7-494d-4b62-8c62-dc22a80cdb39)

### Logs

```Log```
Running on 64 bit Windows 10.0.19045.0 with 31863 MB RAM
Game Version: v1.20.0-rc.1 (Unstable)
12/8/2024 3:14:19 PM: Critical error occurred
Loaded Mods: game@1.20.0-rc.1, creative@1.20.0-rc.1, survival@1.20.0-rc.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.EntityAgent.TryMount(IMountableSeat onmount) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 185
   at Vintagestory.API.Common.EntityPlayer.TryMount(IMountableSeat onmount) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 1176
   at Vintagestory.GameContent.EntityBehaviorSeatable.OnInteract(EntityAgent byEntity, ItemSlot itemslot, Vec3d hitPosition, EnumInteractMode mode, EnumHandling& handled) in VSSurvivalMod\Systems\Boats\EntityBehaviorSeatable.cs:line 146
   at Vintagestory.GameContent.EntityBoat.OnInteract(EntityAgent byEntity, ItemSlot itemslot, Vec3d hitPosition, EnumInteractMode mode) in VSSurvivalMod\Systems\Boats\EntityBoat.cs:line 482
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 402
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 85
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 188
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 991
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 242
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 92
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 329
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by radfast** [comment]
Thanks for reporting. Probably a one-off issue, anyhow it will be fixed in next update 1.20-rc.2
