### ISSUE TITLE
Mac: New reverb system causing audio-related crash after going past a certain depth in caves

### ISSUE THREAD

**Issue by LucasFNT** [anegostudios/VintageStory-Issues#4639]
### Game Version

v1.20.0-rc.1

### Platform

Mac

### Modded

Vanilla

### SP/MP

None

### Description

Going past a certain depth causes the game to crash for mac users. It also prevent from loading the world as it keeps crashing.

### How to reproduce

1. Use a Mac
2. Create a world
3. Go deep in a cave (depends on the world height, with default about 80-90 I think)
4. Crash

### Logs

```
Game Version: v1.20.0-rc.1 (Unstable)
09/12/2024 22:12:13: Critical error occurred
Loaded Mods: game@1.20.0-rc.1, creative@1.20.0-rc.1, survival@1.20.0-rc.1
System.Exception: This OpenAL function could not be loaded. This likely means that this extension isn't present in the current context.
   at OpenAL_AL_Extension_Null_GetProcAddress_Exception_Delegate_65f50974-3c75-439e-acef-84176a4ceefa(Int32, Int32&)
   at OpenTK.Audio.OpenAL.ALC.EFX.DeleteFilters(Int32 count, Int32& filters)
   at OpenTK.Audio.OpenAL.ALC.EFX.DeleteFilter(Int32 filter)
   at Vintagestory.Client.AudioOpenAl.Dispose(Boolean disposing) in VintagestoryLib\Client\ClientPlatform\ClientNative\AudioOpenAl.cs:line 107
   at Vintagestory.Client.AudioOpenAl.Dispose() in VintagestoryLib\Client\ClientPlatform\ClientNative\AudioOpenAl.cs:line 121
   at Vintagestory.Client.NoObf.ClientPlatformWindows.StopAudio() in VintagestoryLib\Client\ClientPlatform\Audio.cs:line 33
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 342
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

```

**Comment by LucasFNT** [comment]
(Also happens when going inside water)

**Comment by LucasFNT** [comment]
Quoting @Krovolov on discord 

The issue with OpenAL EFX is that it’s supposed to activate underwater, but it doesn’t work on Macs with M-series processors. I’ve been digging through the code, but since I have no experience, I couldn’t figure out where this is defined. Basically, we just need to add a line of code so that if the PC doesn’t support EFX, it doesn’t activate. If anyone knows where to put this, here’s the code that should help:

`if (alcIsExtensionPresent(device, "ALC_EXT_EFX")) {
    ALC.EFX.DeleteFilter(filter);
} 
`

**Comment by radfast** [comment]
> Quoting @Krovolov on discord
> 
> The issue with OpenAL EFX is that it’s supposed to activate underwater, but it doesn’t work on Macs with M-series processors. I’ve been digging through the code, but since I have no experience, I couldn’t figure out where this is defined. Basically, we just need to add a line of code so that if the PC doesn’t support EFX, it doesn’t activate. If anyone knows where to put this, here’s the code that should help:
> 
> `if (alcIsExtensionPresent(device, "ALC_EXT_EFX")) { ALC.EFX.DeleteFilter(filter); } `

Thank you, very helpful.  I think highly likely it's the new "reverb" feature in the 1.20 sound which is causing this.  We can both delete the filter, and provide a client-side option to turn this off altogether.

I apologise that Mac users do keep encountering difficulties. Every new VintageStory release we get things working on a Mac, then we add new features, some of which are not available or implemented subtly differently on Mac hardware. Unfortunately the dev team are mainly using Windows and Linux, with some old Macs around the place (and I have Mac VMs). None of us has a latest-spec Mac handy for testing things on

**Comment by Th3Dilli** [comment]
it is now fixed in rc.2 by disabling it when it is not supported as it seems to be the case with mac os
