### ISSUE TITLE
Changes to BlockEntityGenericTypedContainer causing crashes with non-animatable containers

### ISSUE THREAD

**Issue by HydraCat** [anegostudios/VintageStory-Issues#4640]
### Game Version

1.20.0-rc.1

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

The new functions "OpenLid" and "CloseLid" in class "BlockEntityGenericTypedContainer" assume a reference to "animUtil" is set. This is only set if the container in question has the "Animatable" behaviour and otherwise causes a crash with the given log.

It does not seem unreasonable to want an unanimated container and therefore having to set the behaviour despite not intending to use it to prevent crashing to me constitutes a bug. Incidentally the names "OpenLid" and "CloseLid" seem a touch out of place in a generic container class.

### How to reproduce

1. Remove the animatable behaviour from a GenericTypedContainer, such as the storagevessel, or use a mod with non animated containers such as v1.1.9 of decorbazzar (The source of this discovery)
2. Place and attempt to open the container (For decorbazzar the vegetable storage block will do among most others)
3. Crash and recieve the given crash log

### Logs

Running on 64 bit Windows 10.0.19045.0 with 16234 MB RAM
Game Version: v1.20.0-rc.1 (Unstable)
09/12/2024 12:02:28: Critical error occurred
Loaded Mods: decor@1.1.9, game@1.20.0-rc.1, creative@1.20.0-rc.1, survival@1.20.0-rc.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityGenericTypedContainer.OpenLid() in VSSurvivalMod\BlockEntity\BEGenericTypedContainer.cs:line 238
   at Vintagestory.GameContent.BlockEntityGenericTypedContainer.OnInvOpened(IPlayer player) in VSSurvivalMod\BlockEntity\BEGenericTypedContainer.cs:line 232
   at Vintagestory.API.Common.InventoryBase.Open(IPlayer player) in VintagestoryApi\Common\Inventory\InventoryBase.cs:line 852
   at Vintagestory.API.Client.GuiDialogBlockEntity.OnGuiOpened() in VintagestoryApi\Client\UI\Dialog\GuiDialogBlockEntity.cs:line 152
   at Vintagestory.API.Client.GuiDialogBlockEntityInventory.OnGuiOpened() in VintagestoryApi\Client\UI\Dialog\GuiDialogBlockEntityInventory.cs:line 115
   at Vintagestory.API.Client.GuiDialog.TryOpen(Boolean withFocus) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 289
   at Vintagestory.API.Client.GuiDialog.TryOpen() in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 269
   at Vintagestory.API.Client.GuiDialogBlockEntity.TryOpen() in VintagestoryApi\Client\UI\Dialog\GuiDialogBlockEntity.cs:line 165
   at Vintagestory.GameContent.BlockEntityOpenableContainer.OnReceivedServerPacket(Int32 packetid, Byte[] data) in VSSurvivalMod\BlockEntity\BEOpenableContainer.cs:line 211
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntityMessage(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 439
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 785
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 161
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 329
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by maltiez2** [comment]
Will be fixed in next update
