### ISSUE TITLE
Крит ошибка при запуске сервера 

### ISSUE THREAD

**Issue by Ekac19** [anegostudios/VintageStory-Issues#4668]
### Game Version

1.19.8

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

крит ошибка при запуске сервера ,крашит игру 

### Logs

```Log```Running on 64 bit Windows 10.0.22631.0 with 15741 MB RAM
Game Version: v1.19.8 (Stable)
11.12.2024 16:55:24: Critical error occurred
Loaded Mods: game@1.19.8, creative@1.19.8, survival@1.19.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.WeatherSystemClient.OnRenderFrame(Single dt, EnumRenderStage stage) in VSEssentials\Systems\Weather\WeatherSystemClient.cs:line 140
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 200
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 806
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 858
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 730
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 2
==================================
{ TimeGenerated = 11.12.2024 16:54:42, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.19.8.0, метка времени: 0x661e0000
Имя сбойного модуля: openal32.dll, версия: 1.23.0.0, метка времени: 0x63dd31ad
Код исключения: 0x40000015
Смещение ошибки: 0x00000000000df046
Идентификатор сбойного процесса: 0x0x17148
Время запуска сбойного приложения: 0x0x1db4bd3a43dd28e
Путь сбойного приложения: C:\Users\Vladymyr\AppData\Roaming\Vintagestory\Vintagestory.exe
Путь сбойного модуля: C:\Users\Vladymyr\AppData\Roaming\Vintagestory\Lib\openal32.dll
Идентификатор отчета: 6cdaf03a-42ec-470e-8568-482927609b57
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 11.12.2024 16:50:27, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.19.8.0, метка времени: 0x661e0000
Имя сбойного модуля: openal32.dll, версия: 1.23.0.0, метка времени: 0x63dd31ad
Код исключения: 0x40000015
Смещение ошибки: 0x00000000000df046
Идентификатор сбойного процесса: 0x0x162f8
Время запуска сбойного приложения: 0x0x1db4bd388693fa4
Путь сбойного приложения: C:\Users\Vladymyr\AppData\Roaming\Vintagestory\Vintagestory.exe
Путь сбойного модуля: C:\Users\Vladymyr\AppData\Roaming\Vintagestory\Lib\openal32.dll
Идентификатор отчета: 29701ec0-bc64-4b42-86ae-c807c5d4c0d6
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }

**Comment by Craluminum2413** [comment]
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4553
