### ISSUE TITLE
Crash when attaching lantern from giveitem to sailboat

### ISSUE THREAD

**Issue by leehuk** [anegostudios/VintageStory-Issues#4677]
### Game Version

v1.20.0-rc1

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Crash attaching lantern from giveitem to sailboat

### How to reproduce

1. Run `/giveitem lantern-up{material="copper",glass="quartz"}
2. It'll provide a lantern with an invalid lining (I think thats the issue)
3. Attach lantern to a sailboat
4. Crash

### Logs

```
Running on 64 bit Windows 10.0.19045.0 with 31960 MB RAM
Game Version: v1.20.0-rc.1 (Unstable)
13/12/2024 16:34:29: Critical error occurred
Loaded Mods: terraprety@5.0.5, traderballoonsmod@1.0.0, game@1.20.0-rc.1, animalcages@3.0.3, betterfirepit@1.1.4, hudclockpatch@1.0.0, prospecttogether@1.4.0, creative@1.20.0-rc.1, survival@1.20.0-rc.1
System.Collections.Generic.KeyNotFoundException: The key  was not found
   at Vintagestory.API.Datastructures.FastSmallDictionary`2.get_Item(TKey key) in VintagestoryApi\Datastructures\Dictionary\FastSmallDictionary.cs:line 74
   at Vintagestory.GameContent.BlockLantern.Vintagestory.GameContent.IAttachableToEntity.CollectTextures(ItemStack itemstack, Shape intoShape, String texturePrefixCode, Dictionary`2 intoDict) in VSSurvivalMod\Block\BlockLantern.cs:line 34
   at Vintagestory.GameContent.EntityBehaviorContainer.addGearToShape(Shape entityShape, ItemStack stack, IAttachableToEntity iatta, String slotCode, String shapePathForLogging, String[]& willDeleteElements, Dictionary`2 overrideStepParent) in VSEssentials\Entity\Behavior\BehaviorContainer.cs:line 297
   at Vintagestory.GameContent.EntityBehaviorContainer.addGearToShape(Shape entityShape, ItemSlot gearslot, String slotCode, String shapePathForLogging, Boolean& shapeIsCloned, String[]& willDeleteElements, Dictionary`2 overrideStepParent) in VSEssentials\Entity\Behavior\BehaviorContainer.cs:line 247
   at Vintagestory.GameContent.EntityBehaviorAttachable.addGearToShape(Shape entityShape, ItemSlot gearslot, String slotCode, String shapePathForLogging, Boolean& shapeIsCloned, String[]& willDeleteElements, Dictionary`2 overrideStepParent) in VSSurvivalMod\Entity\Behavior\BehaviorAttachable.cs:line 369
   at Vintagestory.GameContent.EntityBehaviorContainer.addGearToShape(Shape& entityShape, String shapePathForLogging, Boolean& shapeIsCloned, String[]& willDeleteElements) in VSEssentials\Entity\Behavior\BehaviorContainer.cs:line 208
   at Vintagestory.GameContent.EntityBehaviorContainer.OnTesselation(Shape& entityShape, String shapePathForLogging, Boolean& shapeIsCloned, String[]& willDeleteElements) in VSEssentials\Entity\Behavior\BehaviorContainer.cs:line 178
   at Vintagestory.API.Common.Entities.Entity.OnTesselation(Shape& entityShape, String shapePathForLogging, Boolean& shapeIsCloned) in VintagestoryApi\Common\Entity\Entity.cs:line 1187
   at Vintagestory.API.Common.Entities.Entity.OnTesselation(Shape& entityShape, String shapePathForLogging) in VintagestoryApi\Common\Entity\Entity.cs:line 1132
   at Vintagestory.GameContent.EntityBoat.OnTesselation(Shape& entityShape, String shapePathForLogging) in VSSurvivalMod\Systems\Boats\EntityBoat.cs:line 214
   at Vintagestory.GameContent.EntityShapeRenderer.TesselateShape(Action`1 onMeshDataReady, String[] overrideSelectiveElements) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 229
   at Vintagestory.GameContent.EntityShapeRenderer.TesselateShape() in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 193
   at Vintagestory.GameContent.EntityShapeRenderer.BeforeRender(Single dt) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 347
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 70
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 202
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 867
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 739
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 170
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 92
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 329
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 13/12/2024 16:19:15, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x3ff28
Faulting application start time: 0x01db4d7aa8d9044b
Faulting application path: C:\Games\Misc\VintageStory\Vintagestory.exe
Faulting module path: C:\Games\Misc\VintageStory\Lib\openal32.dll
Report ID: 103ef62d-c8fb-4112-bf9e-44e6002e7f0f
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 13/12/2024 16:18:23, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x3bb50
Faulting application start time: 0x01db4d7a54cd8b8e
Faulting application path: C:\Games\Misc\VintageStory\Vintagestory.exe
Faulting module path: C:\Games\Misc\VintageStory\Lib\openal32.dll
Report ID: 94a2eceb-6810-4726-9f95-8ec89c911387
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 13/12/2024 16:14:57, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x3dff4
Faulting application start time: 0x01db4d798354700a
Faulting application path: C:\Games\Misc\VintageStory\Vintagestory.exe
Faulting module path: C:\Games\Misc\VintageStory\Lib\openal32.dll
Report ID: c73e91bf-10b6-484b-89dc-9be2ad33f2b1
Faulting package full name: 
Faulting package-relative application ID:  }
```

**Comment by tyronx** [comment]
because you are creating an invalid lantern that is missing the lining value (default 'plain').

I can prevent it from crashing from invalid lanterns though - wil be in rc2
