### ISSUE TITLE
[1.20.0-rc.2] Ruin generating with "?" blocks

### ISSUE THREAD

**Issue by Naxdar** [anegostudios/VintageStory-Issues#4684]
### Game Version

v1.20.0-rc.2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

A ruin generates with white "?" blocks.

### How to reproduce

Generate a new world with default settings (standard playstyle) and the seed : 1534609712
Go to the coordinates : 130/114/-325

### Screenshots

![Nx 174](https://github.com/user-attachments/assets/ed92efd1-6090-4df2-b1c4-6c82326d681e)

### Logs

In server-worldgen.log

```14.12.2024 00:26:54 [Worldgen] An error was thrown in pass TerrainFeatures when generating chunk column X=16009,Z=15973 in world 'Creepy Adventure Tales' with seed 1534609712
Exception System.InvalidCastException: At least one element in the source array could not be cast down to the destination array type.
   at System.Array.CopySlow(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at Vintagestory.Common.DTable`2.ValuesCopy() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Datastructures\ConcurrentSmallDictionary.cs:line 413
   at Vintagestory.GameContent.ItemLootRandomizer.Resolve(ItemSlot slot, IWorldAccessor worldForResolve, Boolean resolveImports) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Loot\ItemLootRandomizer.cs:line 57
   at Vintagestory.GameContent.InWorldContainer.OnLoadCollectibleMappings(IWorldAccessor worldForResolve, Dictionary`2 oldBlockIdMapping, Dictionary`2 oldItemIdMapping, Int32 schematicSeed, Boolean resolveImports) in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Inventory\InWorldContainer.cs:line 236
   at Vintagestory.API.Common.BlockSchematic.PlaceEntitiesAndBlockEntities(IBlockAccessor blockAccessor, IWorldAccessor worldForCollectibleResolve, BlockPos startPos, Dictionary`2 blockCodes, Dictionary`2 itemCodes, Boolean replaceBlockEntities, Dictionary`2 replaceBlocks, Int32 centerrockblockid, Dictionary`2 layerBlockForBlockEntities, Boolean resolveImports) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Collectible\Block\BlockSchematic.cs:line 1180
   at Vintagestory.ServerMods.BlockSchematicStructure.PlaceReplacingBlocks(IBlockAccessor blockAccessor, IWorldAccessor worldForCollectibleResolve, BlockPos startPos, EnumReplaceMode mode, Dictionary`2 replaceBlocks, Nullable`1 rockBlockId, Boolean replaceMetaBlocks) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\Datastructures\BlockSchematicStructure.cs:line 353
   at Vintagestory.ServerMods.WorldGenStructure.tryGenerateAttachedToCave(IBlockAccessor blockAccessor, IWorldAccessor worldForCollectibleResolve, BlockSchematicStructure[] schematicStruc, BlockPos targetPos, String locationCode) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\6.GenStructures\WorldGenStructure.cs:line 830
   at Vintagestory.ServerMods.WorldGenStructure.TryGenerateUnderground(IBlockAccessor blockAccessor, IWorldAccessor worldForCollectibleResolve, BlockPos pos, String locationCode) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\6.GenStructures\WorldGenStructure.cs:line 767
   at Vintagestory.ServerMods.WorldGenStructure.TryGenerate(IBlockAccessor blockAccessor, IWorldAccessor worldForCollectibleResolve, BlockPos startPos, Int32 climateUpLeft, Int32 climateUpRight, Int32 climateBotLeft, Int32 climateBotRight, String locationCode) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\6.GenStructures\WorldGenStructure.cs:line 274
   at Vintagestory.ServerMods.GenStructures.DoGenStructures(IMapRegion region, Int32 chunkX, Int32 chunkZ, Boolean postPass, String locationCode, ITreeAttribute chunkGenParams) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\6.GenStructures\GenStructures.cs:line 204
   at Vintagestory.ServerMods.GenStructures.OnChunkColumnGen(IChunkColumnGenerateRequest request) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\6.GenStructures\GenStructures.cs:line 163
   at Vintagestory.Server.ServerSystemSupplyChunks.runGenerators(ChunkColumnLoadRequest chunkRequest, Int32 forPass) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 1874```

**Comment by radfast** [comment]
Known issue - we apologise profusely.  Please see the release notes for 1.20.0-rc.2 which have been updated with a Note covering this.

We hope to have 1.20.0-rc.3 out, to fix this, some time on Saturday.  Will leave this open until then.
