### ISSUE TITLE
Game fails to recreate Macro directory when removed

### ISSUE THREAD

**Issue by Perturbee** [anegostudios/VintageStory-Issues#4688]
### Game Version

1.20.0-RC2/RC3

### Platform

Linux

### Modded

None

### SP/MP

Singleplayer

### Description

Game crashes when Macros folder is absent, I expected the game to recreate that as I have moved the Mods folder or even the VintagestoryData before during tests and then everything does get recreated.

### How to reproduce

Step 1. create some macros and find out they're glitching for some reason
Step 2. rename the Macros folder (to Macros.org or something) to test if fresh macros don't glitch
Step 3. Watch the game crash to desktop with the critical error

### Logs

```Log```
Running on 64 bit Linux (openSUSE Leap 15.6) [Kernel 6.4.0.150600] with 64265 MB RAM
Game Version: v1.20.0-rc.2 (Unstable)
12/14/2024 08:37:54: Critical error occurred
Loaded Mods: 
System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/rowena/.config/VintagestoryData/Macros'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Vintagestory.Client.NoObf.MacroManager.LoadMacros() in VintagestoryLib\Client\MacroManager.cs:line 75
   at Vintagestory.Client.NoObf.MacroManager..ctor(ClientMain game) in VintagestoryLib\Client\MacroManager.cs:line 66
   at Vintagestory.Client.NoObf.ClientMain.Start() in VintagestoryLib\Client\ClientMain.cs:line 532
   at Vintagestory.Client.GuiScreenRunningGame.Start(Boolean singleplayer, StartServerArgs serverargs, ServerConnectData connectData) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 100
   at Vintagestory.Client.ScreenManager.StartGame(Boolean singleplayer, StartServerArgs serverargs, ServerConnectData connectData) in VintagestoryLib\Client\ScreenManager.cs:line 1017
   at Vintagestory.Client.ScreenManager.ConnectToSingleplayer(StartServerArgs serverargs) in VintagestoryLib\Client\ScreenManager.cs:line 1082
   at Vintagestory.Client.GuiScreenSingleplayer.OnClickCellLeft(Int32 cellIndex) in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayer.cs:line 181
   at Vintagestory.API.Client.GuiElementMainMenuCell.OnMouseUpOnElement(MouseEvent args, Int32 elementIndex) in VintagestoryApi\Client\UI\Elements\Impl\Misc\GuiElementMainMenuCell.cs:line 325
   at Vintagestory.API.Client.GuiElementCellList`1.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 241
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 451
   at GuiScreen.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\MainMenu\Screens\Special\GuiScreen.cs:line 204
   at Vintagestory.Client.ScreenManager.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 914
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 211
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Perturbee** [comment]
I want to add to this that sometime macros stop working between play sessions, only when the macro that's somehow bugged is edited it works again for that session.

**Comment by Craluminum2413** [comment]
@Perturbee Do you use different keyboard layouts?

**Comment by Perturbee** [comment]
My keyboard setting is US-International and I didn't use any weird characters
