### ISSUE TITLE
Client crash while idling (PlayerAnimationManager)

### ISSUE THREAD

**Issue by bonenaut7** [anegostudios/VintageStory-Issues#4697]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Random crash happened when I was idling on the TOPS server, never seen that one before.
Mods in my game has nothing to do with player animations, game assets hasn't been altered in any way.

### How to reproduce

_I don't know how to reproduce the issue_

### Logs

```
Running on 64 bit Windows 10.0.19045.0 with 64730 MB RAM
Game Version: v1.19.8 (Stable)
15.12.2024 13:47:24: Critical error occurred
Loaded Mods: ClaimsRadar@1.1.0, game@1.19.8, inventorydeathlogger@1.0.0, guiclaims@0.0.1, spawnhighlight@1.2.0, creative@1.19.8, vsimgui@1.1.5, survival@1.19.8, configlib@1.3.13, statushudcont@2.1.2
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.Common.AnimatorBase.OnFrame(Dictionary`2 activeAnimationsByAnimCode, Single dt) in VintagestoryApi\Common\Model\Animation\AnimatorBase.cs:line 116
   at Vintagestory.API.Common.AnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Model\Animation\AnimationManager.cs:line 353
   at Vintagestory.API.Common.PlayerAnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Entity\PlayerAnimationManager.cs:line 34
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
   ```

**Comment by radfast** [comment]
@bonenaut7 I've looked at our code and see no reason that it could ever error at the line number seen in the crash report (AnimatorBase.cs:line 116).  I have double-checked the line number by making a custom 1.19.8 build with a deliberate error in that line 116, to check that the crash report I get from doing that looks identical - and it is.

You have 7 client-side mods installed.  It's possible one of those mods has changed something here, even if it seems unrelated to the main function of the mod.  Without looking in detail at all of them, I cannot be sure this is not a mod issue.  

Please can I suggest:
- if it was a one-off event, for now let's not worry about it
- if it happens again, please try playing without the client-side mods, see if that fixes it
