### ISSUE TITLE
Clicking on any handbook link crashes the game

### ISSUE THREAD

**Issue by Lonir-Ali** [anegostudios/VintageStory-Issues#4701]
### Game Version

1.20.0-rc.4

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Clicking on any handbook link crashes the game

### How to reproduce

Open the handbook and click on any link

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32541 MB RAM
Game Version: v1.20.0-rc.4 (Unstable)
15/12/2024 18:50:06: Critical error occurred in the following mod: extrainfo@1.8.1
Loaded Mods: bedrespawner@1.0.0, nightlight@1.3.6, game@1.20.0-rc.4, betterruins@0.4.0, commonlib@2.5.0-rc.2, extrainfo@1.8.1, hudclockpatch@1.0.0, creative@1.20.0-rc.4, survival@1.20.0-rc.4, extraoverlays@1.4.0, playercorpse@1.10.1-rc.1
Involved Harmony IDs: extrainfo
System.NullReferenceException: Object reference not set to an instance of an object.
   at ExtraInfo.HandbookExtensions.<>c__DisplayClass8_0.<AddTradersInfo>b__0(EntityProperties x) in F:\VSCode\Repos\Modding_VintageStory\ExtraInfo\src\Utility\HandbookExtensions.cs:line 327
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at ExtraInfo.HandbookExtensions.AddTradersInfo(List`1 list, ItemSlot inSlot, ICoreClientAPI capi, ActionConsumable`1 openDetailPageFor) in F:\VSCode\Repos\Modding_VintageStory\ExtraInfo\src\Utility\HandbookExtensions.cs:line 327
   at ExtraInfo.GetHandbookInfoPatch.Postfix(RichTextComponentBase[]& __result, ItemSlot inSlot, ICoreClientAPI capi, ActionConsumable`1 openDetailPageFor) in F:\VSCode\Repos\Modding_VintageStory\ExtraInfo\src\Systems\HarmonyPatches\GetHandbookInfoPatch.cs:line 17
   at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.GetHandbookInfo_Patch1(CollectibleBehaviorHandbookTextAndExtraInfo this, ItemSlot inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.GameContent.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 117
   at Vintagestory.GameContent.GuiHandbookItemStackPage.ComposePage(GuiComposer detailViewGui, ElementBounds textBounds, ItemStack[] allstacks, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 111
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onComposePage(GuiHandbookPage page, GuiComposer detailViewGui, ElementBounds textBounds, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 99
   at Vintagestory.GameContent.GuiDialogHandbook.initDetailGui() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 258
   at Vintagestory.GameContent.GuiDialogHandbook.onLeftClickListElement(Int32 index) in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 349
   at Vintagestory.GameContent.GuiElementFlatList.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VSSurvivalMod\Systems\Handbook\Gui\GuiElementFlatList.cs:line 117
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 719
   at Vintagestory.GameContent.GuiElementFlatList.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VSSurvivalMod\Systems\Handbook\Gui\GuiElementFlatList.cs:line 172
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 447
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 574
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 415
   at Vintagestory.Client.NoObf.ClientMain.UpdateMouseButtonState(EnumMouseButton button, Boolean down) in VintagestoryLib\Client\ClientMain.cs:line 1935
   at Vintagestory.Client.SystemHotkeys.OnPrimaryMouseButton(KeyCombination mb) in VintagestoryLib\Client\Systems\Player\Hotkeys.cs:line 50
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean isGlobal, Boolean fallBack, Boolean keyup) in VintagestoryLib\Client\HotkeyManager.cs:line 431
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean keyUp) in VintagestoryLib\Client\HotkeyManager.cs:line 392
   at Vintagestory.Client.HotkeyManager.OnMouseButton(ClientMain game, EnumMouseButton button, Int32 modifiers, Boolean buttonDown) in VintagestoryLib\Client\HotkeyManager.cs:line 574
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUpRaw(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1965
   at Vintagestory.Client.GuiScreenRunningGame.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 357
   at Vintagestory.Client.ScreenManager.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 914
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 211
   at OpenTK.Windowing.Desktop.NativeWindow.OnMouseUp(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 14/12/2024 13:04:51, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x36d4
Faulting application start time: 0x01db4e0cc0e23ddf
Faulting application path: C:\Users\imago\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\imago\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: b4916671-13e0-43cf-97d8-c5be287f0871
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 25/11/2024 8:03:03, Site = , Source = Application Error, Message = Faulting application name: VintageStory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x4554
Faulting application start time: 0x01db3eff8db9a77e
Faulting application path: C:\Users\imago\AppData\Roaming\Vintagestory\VintageStory.exe
Faulting module path: C:\Users\imago\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: afc00b09-b3e8-4a51-a4eb-0b2278279475
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 23/11/2024 22:38:40, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x499c
Faulting application start time: 0x01db3de799bf9367
Faulting application path: C:\Users\imago\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\imago\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: b590a821-4cd5-41ee-8ae0-faf82b3851ec
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Update extra info mod
