### ISSUE TITLE
crash after loading a map

### ISSUE THREAD

**Issue by neo-zzz** [anegostudios/VintageStory-Issues#4705]
### Game Version

v1.19.8 (Stable)

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Logs

```Log```

**Comment by neo-zzz** [comment]
Running on 64 bit Linux (Zorin OS 17.2) [Kernel 6.8.0.49] with 15940 MB RAM
Game Version: v1.19.8 (Stable)
15.12.2024 21:11:13: Critical error occurred
Loaded Mods: game@1.19.8, creative@1.19.8, survival@1.19.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.InventoryNetworkUtil.UpdateSlotStack(ItemSlot slot, ItemStack newStack) in VintagestoryLib\Common\GameContent\Inventory\InventoryNetworkUtil.cs:line 492
   at Vintagestory.Common.InventoryNetworkUtil.UpdateFromPacket(IWorldAccessor resolver, Packet_InventoryContents packet) in VintagestoryLib\Common\GameContent\Inventory\InventoryNetworkUtil.cs:line 438
   at Vintagestory.Client.NoObf.ClientPlayer.AddOrUpdateInventory(ClientMain game, Packet_InventoryContents packet) in VintagestoryLib\Client\Model\ClientPlayer.cs:line 137
   at Vintagestory.Client.NoObf.ClientPlayer.UpdateFromPacket(ClientMain game, Packet_PlayerData packet) in VintagestoryLib\Client\Model\ClientPlayer.cs:line 159
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 265
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 448
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 442
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
