### ISSUE TITLE
game crashed when i make slaked lime

### ISSUE THREAD

**Issue by survivergamer** [anegostudios/VintageStory-Issues#4744]
### Game Version

1.20 rc5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

i put 4 quicklime in a barrel with water and game crashed.

### Logs

Running on 64 bit Windows 10.0.17763.0 with 16241 MB RAM
Game Version: v1.20.0-rc.5 (Unstable) by OverF1X  
20.12.2024 11:35:37: Critical error occurred
Loaded Mods: millwright@1.1.8, primitivesurvival@3.7.4, game@1.20.0-rc.5, fromgoldencombs@1.8.1, claywheel@1.1.2, smithingplus@1.1.3, creative@1.20.0-rc.5, survival@1.20.0-rc.5
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Vintagestory.Client.NoObf.TextureAtlasManager.AllocateTextureSpace(Int32 width, Int32 height, Int32& textureSubId, TextureAtlasPosition& texPos) in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 390
   at Vintagestory.Client.NoObf.TextureAtlasManager.InsertTexture(IBitmap bmp, Int32& textureSubId, TextureAtlasPosition& texPos, Single alphaTest) in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 293
   at Vintagestory.Client.NoObf.TextureAtlasManager.GetOrInsertTexture(AssetLocationAndSource loc, Int32& textureSubId, TextureAtlasPosition& texPos, CreateTextureDelegate onCreate, Single alphaTest)
   at Vintagestory.GameContent.ContainerTextureSource.get_Item(String textureCode) in VSSurvivalMod\Systems\Liquid\ContainerTextureSource.cs:line 48
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(Int32 indexForLogging, MeshData meshdata, ShapeElement element, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 400
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 309
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(Shape shapeBase, MeshData& modeldata, Vec3f wholeMeshRotation, Vec3f wholeMeshOffset, Single wholeMeshScale, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 250
   at Vintagestory.GameContent.BlockBarrel.getContentMesh(ItemStack stack, BlockPos forBlockPos, AssetLocation shapefilepath) in VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:line 255
   at Vintagestory.GameContent.BlockBarrel.getContentMeshLiquids(ItemStack contentStack, ItemStack liquidContentStack, BlockPos forBlockPos, JsonObject containerProps) in VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:line 207
   at Vintagestory.GameContent.BlockBarrel.GenMesh(ItemStack contentStack, ItemStack liquidContentStack, Boolean issealed, BlockPos forBlockPos) in VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:line 171
   at Vintagestory.GameContent.BlockEntityBarrel.GenMesh() in VSSurvivalMod\Systems\Barrel\BEBarrel.cs:line 343
   at Vintagestory.GameContent.BlockEntityBarrel.Inventory_SlotModified(Int32 slotId) in VSSurvivalMod\Systems\Barrel\BEBarrel.cs:line 121
   at Vintagestory.API.Common.InventoryBase.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack) in VintagestoryApi\Common\Inventory\InventoryBase.cs:line 494
   at Vintagestory.Common.InventoryNetworkUtil.UpdateFromPacket(IWorldAccessor resolver, Packet_InventoryUpdate packet) in VintagestoryLib\Common\GameContent\Inventory\InventoryNetworkUtil.cs:line 451
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleInventoryUpdate(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 360
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 785
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 161
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 19.12.2024 10:02:01, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.20.0.0, метка времени: 0x66470000
Имя сбойного модуля: openal32.dll, версия: 1.23.0.0, метка времени: 0x63dd31ad
Код исключения: 0x40000015
Смещение ошибки: 0x00000000000df046
Идентификатор сбойного процесса: 0xaa0
Время запуска сбойного приложения: 0x01db51e3c8d03f5e
Путь сбойного приложения: D:\Games\FPlay.SU\rc5\Vintagestory.exe
Путь сбойного модуля: D:\Games\FPlay.SU\rc5\Lib\openal32.dll
Идентификатор отчета: ded5c0cf-a5f0-48c4-badb-94437a931f17
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 18.12.2024 9:38:50, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.20.0.0, метка времени: 0x66470000
Имя сбойного модуля: openal32.dll, версия: 1.23.0.0, метка времени: 0x63dd31ad
Код исключения: 0x40000015
Смещение ошибки: 0x00000000000df046
Идентификатор сбойного процесса: 0x99c
Время запуска сбойного приложения: 0x01db5117662bc5a8
Путь сбойного приложения: D:\Games\FPlay.SU\Vintage Story\Vintagestory.exe
Путь сбойного модуля: D:\Games\FPlay.SU\Vintage Story\Lib\openal32.dll
Идентификатор отчета: f31a0dd7-6653-4dde-a3c6-f01bc0f75709
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 18.12.2024 9:35:50, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.20.0.0, метка времени: 0x66470000
Имя сбойного модуля: openal32.dll, версия: 1.23.0.0, метка времени: 0x63dd31ad
Код исключения: 0x40000015
Смещение ошибки: 0x00000000000df046
Идентификатор сбойного процесса: 0x113c
Время запуска сбойного приложения: 0x01db5116c635f2db
Путь сбойного приложения: D:\Games\FPlay.SU\Vintage Story\Vintagestory.exe
Путь сбойного модуля: D:\Games\FPlay.SU\Vintage Story\Lib\openal32.dll
Идентификатор отчета: de8e9ae2-4764-4329-ac59-ce1f7d2dabdc
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }

**Comment by Craluminum2413** [comment]
Pirated versions are not supported
