### ISSUE TITLE
не могу запустить игру сразу выходит ошибка

### ISSUE THREAD

**Issue by ataman357159333** [anegostudios/VintageStory-Issues#4752]
### Game Version

1.20.0-rc.5 by OverF1X

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

не могу запустить игру сразу выходит ошибка

![Аннотация 2024-12-20 194428](https://github.com/user-attachments/assets/78d9668d-4abb-43a4-af48-43060e25849d)

### Logs

Running on 64 bit Windows 10.0.19045.0 with 16348 MB RAM
Game Version: v1.20.0-rc.5 (Unstable) by OverF1X  
20.12.2024 19:43:15: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: The driver does not appear to support OpenGL
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings) in VintagestoryLib\Client\ClientPlatform\GameWindowNative.cs:line 14
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 291
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 20.12.2024 19:43:15, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.20.0.0, метка времени: 0x66470000
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.19041.5198, метка времени: 0xd1eefc71
Код исключения: 0xe0434352
Смещение ошибки: 0x000000000003b699
Идентификатор сбойного процесса: 0x261c
Время запуска сбойного приложения: 0x01db52fe43320893
Путь сбойного приложения: D:\Games\FPlay.SU\Vintage Story\Vintagestory.exe
Путь сбойного модуля: C:\Windows\System32\KERNELBASE.dll
Идентификатор отчета: b6c42dab-9737-4db4-bcd2-0ef7a9ea6092
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 20.12.2024 19:33:51, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.20.0.0, метка времени: 0x66470000
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.19041.5198, метка времени: 0xd1eefc71
Код исключения: 0xe0434352
Смещение ошибки: 0x000000000003b699
Идентификатор сбойного процесса: 0x1f4c
Время запуска сбойного приложения: 0x01db52fcee9db27b
Путь сбойного приложения: D:\Games\FPlay.SU\Vintage Story\Vintagestory.exe
Путь сбойного модуля: C:\Windows\System32\KERNELBASE.dll
Идентификатор отчета: 32d4ab28-20c1-49a1-a1be-8eab5c855817
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 17.12.2024 20:52:31, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.20.0.0, метка времени: 0x66470000
Имя сбойного модуля: openal32.dll, версия: 1.23.0.0, метка времени: 0x63dd31ad
Код исключения: 0x40000015
Смещение ошибки: 0x00000000000df046
Идентификатор сбойного процесса: 0x2e18
Время запуска сбойного приложения: 0x01db50aba18cefa6
Путь сбойного приложения: D:\Games\FPlay.SU\Vintage Story\Vintagestory.exe
Путь сбойного модуля: D:\Games\FPlay.SU\Vintage Story\Lib\openal32.dll
Идентификатор отчета: a31f38c0-9538-4484-b6fc-a0ac125edc7e
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }

**Comment by Craluminum2413** [comment]
Pirated versions are not supported
