### ISSUE TITLE
The game crashes very often

### ISSUE THREAD

**Issue by Panciastko** [anegostudios/VintageStory-Issues#4771]
### Game Version

v1.20.0-rc.5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

The game crashes randomly, in the previous world it crashed when slaughtering animals. Anyone can help?

### Logs
```
Running on 64 bit Windows 10.0.19045.0 with 16344 MB RAM
Game Version: v1.20.0-rc.5 (Unstable)
22.12.2024 17:16:47: Critical error occurred
Loaded Mods: bettertraders@0.0.7, primitivesurvival@3.7.4, game@1.20.0-rc.5, betterruins@0.4.2, butchering@1.7.3, fromgoldencombs@1.8.1, creative@1.20.0-rc.5, survival@1.20.0-rc.5
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Vintagestory.Client.NoObf.TextureAtlasManager.AllocateTextureSpace(Int32 width, Int32 height, Int32& textureSubId, TextureAtlasPosition& texPos) in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 390
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemStackToAtlas(ItemStack stack, ITextureAtlasAPI atlas, Int32 size, Action`1 onComplete, Int32 color, Single sepiaLevel, Single scale) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 102
   at Vintagestory.Client.NoObf.InventoryItemRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 188
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 991
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 242
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 92
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by pingouyn** [comment]
Someone reported a very similar issue in the butchering mod 2 days ago.
[https://mods.vintagestory.at/butchering](url)

The mod author suggested this:
 "Lookes like a base game texture atlas issue:

Try running these two commands in game then restarting the game fully.

.clientconfig maxTextureAtlasWidth 8192
.clientconfig maxTextureAtlasHeight 8192"

**Comment by Panciastko** [comment]
It worked for now, thanks a lot for your help <3.

**Comment by radfast** [comment]
@Panciastko this issue is fixed in vanilla in latest version 1.20.0-rc.6.    If you like, try changing `maxTextureAtlasWidth` back to 4096 and `maxTextureAtlasHeight` back to 2048, those are their default values.  The default values may improve framerate on some graphics hardware (on other hardware, it may make no measurable difference).

**Comment by radfast** [comment]
(Duplicate of #4693)

**Comment by Panciastko** [comment]
okey, I will try, thx a lot.
