### ISSUE TITLE
Random crash after being afk for a little bit

### ISSUE THREAD

**Issue by Alectryonn** [anegostudios/VintageStory-Issues#4774]
### Game Version

v1.20.0-rc.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

eh just figured I'd share the crash log here, it seemed like my other stuff like discord was slowed at the same time, like not sending a message and not joining a call immediately. Hope this helps y'all, keep up the great work!

### Logs

"""
Running on 64 bit Windows 10.0.19045.0 with 16250 MB RAM
Game Version: v1.20.0-rc.5 (Unstable)
12/22/2024 1:48:01 PM: Critical error occurred
Loaded Mods: game@1.20.0-rc.5, creative@1.20.0-rc.5, survival@1.20.0-rc.5
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorPlayerPhysics.OnRenderFrame(Single dt, EnumRenderStage stage) in VSEssentials\Entity\Behavior\BehaviorPlayerPhysics.cs:line 352
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 188
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 824
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 161
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
"""

**Comment by radfast** [comment]
Thanks for reporting, we'll take a look. Hope you can still play meanwhile, i.e. this does not keep recurring?

If possible, please provide the full `client-main.log` for when this occurred (22/12/2024 1:48:01), the file is probably still in a subfolder of your `VintagestoryData/Logs/Archive` folder

**Comment by Alectryonn** [comment]
Thankfully no, I immediately got back into our server without any issues. Hopefully this is the right one, its the closest match to that time.
[client-main.log](https://github.com/user-attachments/files/18231517/client-main.log)
