### ISSUE TITLE
Mods unable to load assets due to Gear.svg being uppercase

### ISSUE THREAD

**Issue by kcalbxof** [anegostudios/VintageStory-Issues#4775]
### Game Version

v1.20 rc5

### Platform

Linux

### Modded

Modded

### SP/MP

Singleplayer

### Description

AutoMapMarkers unable to load marker icons because Gear.svg is named uppercase, and IAssetManager requires assets to be lowercase in order to successfully load them.

### How to reproduce

1. Install AutoMapMarkers 4.0.0
2. Enter the world
3. Try Ctrl+Shift+M, that should resolve to mod GUI, but in this case mod fails to load gear.svg and as such no GUI is loaded.
4. Try opening map, and create waypoint.
5. Press Ctrl+Shift+M, menu opens because Gear.svg is loaded internally with lowercase name and could be got from cache.

To fix: rename Gear.svg to gear.svg
That cost me two hours of debugging. Sigh.

### Logs

```log
22.12.2024 23:44:20 [Error] Map Marker Mod: Failed to initialize settings GUI. (System.Exception: Requested asset [game:textures/icons/worldmap/gear.svg] could not be found
   at Vintagestory.Common.PathOrigin.LoadAsset(IAsset asset) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\FileIO\Origins\PathOrigin.cs:line 46
   at Vintagestory.Common.AssetManager.GetMany(String partialPath, String domain, Boolean loadAsset) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\FileIO\AssetManager.cs:line 353
   at Egocarib.AutoMapMarkers.GUI.MapMarkerGUI.LoadIconTextures() in C:\Users\Justin\source\repos\VintageStory\automapmarkers\automapmarkers\src\GUI\MapMarkerGUI.cs:line 118
   at Egocarib.AutoMapMarkers.GUI.MapMarkerGUI.OnGuiOpened() in C:\Users\Justin\source\repos\VintageStory\automapmarkers\automapmarkers\src\GUI\MapMarkerGUI.cs:line 71)```

**Comment by radfast** [comment]
Thanks, sorry that you were put to the trouble ... of troubleshooting this.

I've fixed it in upcoming 1.20.0-rc.6, expected in approximately 5-8 days time.

Unfortunately nobody spotted this latent issue before now (the file has always had the name `Gear.svg` ever since it was added to the assets in November 2022). The likely reason is that Windows filesystem treats uppercase and lowercase as the same, and not too many people play on Linux **clients**: lots of Linux servers but a server would not be loading the .svg files.
