### ISSUE TITLE
EntityShapeRenderer.RenderItem crash

### ISSUE THREAD

**Issue by DieMieseBriese** [anegostudios/VintageStory-Issues#4777]
### Game Version

v1.20.0-rc.5 (Unstable)

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

When the crash occurred, I was AFK (in Creative-mode) for about an hour and 10-20 minutes and wanted to leave the game on overnight in LAN mode so that a friend could still play (via Hamachi). We've been building the world for a few days now, but so far there have been no crashes. I've also left the game on overnight several times, and so far there have been no crashes.

I hope it is helpful, if not just ignore it ^^.

### How to reproduce

I haven't tried reproducing it yet, let alone playing it again, but I'll let you know if it happens again.

### Logs

```Running on 64 bit Windows 10.0.19045.0 with 32689 MB RAM
Game Version: v1.20.0-rc.5 (Unstable)
22.12.2024 23:40:53: Critical error occurred
Loaded Mods: game@1.20.0-rc.5, creative@1.20.0-rc.5, survival@1.20.0-rc.5
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityShapeRenderer.RenderItem(Single dt, Boolean isShadowPass, ItemStack stack, AttachmentPointAndPose apap, ItemRenderInfo renderInfo) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 450
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.RenderHeldItem(Single dt, Boolean isShadowPass, Boolean right) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 261
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 167
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderFrameShadows(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 164
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 188
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 824
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 161
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 92
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93```

[client-main.log](https://github.com/user-attachments/files/18225537/client-main.log)

[server-main.log](https://github.com/user-attachments/files/18225541/server-main.log)

**Comment by radfast** [comment]
Thank you. Looking at your [log](https://github.com/user-attachments/files/18225537/client-main.log) I can see three separate, unrelated issues here:

1. The random crash you mentioned, we are investigating, plainly it relates to a _something_ being held but right now we do not know what.  Could be something another player was holding, while your friend was playing - if they were sometimes in your own field of view.  Could be related to the villagers (hope that's not a spoiler) if you discovered a village - please let us know?

2. There's log spam of an issue in the German translation, relating to "Aktive Nutzung" (shield-stats), that is easily fixable in CrowdIn.

3. There's log spam of an animation/clothing issue which the dev team is investigating:

     [Error] Shape game:entity/humanoid/seraph-faceless has a key frame element for which the referencing shape element shouldertextureBackTile cannot be found.
     [Error] Shape game:entity/humanoid/seraph-faceless has a key frame element for which the referencing shape element shouldertextureFrontTile cannot be found.

**Comment by XCompWiz** [comment]
```
Running on 64 bit Windows 10.0.19045.0 with 16309 MB RAM
Game Version: v1.20.3 (Stable)
13.02.2025 21:52:27: Critical error occurred
Loaded Mods: game@1.20.3, creative@1.20.3, survival@1.20.3
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityShapeRenderer.RenderItem(Single dt, Boolean isShadowPass, ItemStack stack, AttachmentPointAndPose apap, ItemRenderInfo renderInfo) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 450
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.RenderHeldItem(Single dt, Boolean isShadowPass, Boolean right) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 261
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 167
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderFrameShadows(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 174
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 188
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 825
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 161
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 92
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```
Still present in 1.20.3.

I was standing fairly far from anyone, and holding a knife. I was looking for a knife I had apparently dropped when jumped by a wolf.

I was looking in the direction of another wolf, I think, swimming. There was one other person on the server with me. I don't know what he was holding. Probably a hammer or an iron bloom.

I will attempt to investigate the direction I was looking in soon to see if it happens again.

**Comment by j5v** [comment]
From #5394, the item held by the client player was an **iron scythe**.

**Comment by j5v** [comment]
Related: in #5319, I see in their screenshot what looks like a chute for pulverizer output, which was also an issue with my report.

**Comment by j5v** [comment]
Another case. Client player was using a helve hammer to convert an iron bloom into an ingot. At the same time, in the adjacent block, the same player was manually hammering a bloom into an ingot on an anvil. When the manually-hammered ingot was ready and picked up, the crash occurred.

**Comment by Darkbrook** [comment]
Experiencing the same issue while holding a `Cupronickel rod` while using tongs. Had to use Harmony to wrap the method in a try-catch so I could log back into the game.

![Image](https://github.com/user-attachments/assets/586dc362-3d82-44f4-b4ee-b31f8938e478)

**Comment by 0rbiter** [comment]
for me it seems to be the iron rod. I made tons of other steel stuff before and also bismuthbronze plates, but with the iron rods I replicated the issue twice now

**Comment by Benimatic** [comment]
Also having this issue with VS 1.20.5-rc3. Downgrading back to 1.20.4 shows I was holding a cupronickel rod. Smithing another on an anvil nearby, with helve hammer and forge operating nearby, if that contributes.

Running on 64 bit Windows 10.0.19045.0 with 32677 MB RAM
Game Version: v1.20.5-rc.3 (Unstable)
3/9/2025 6:49:12 PM: Critical error occurred
Loaded Mods: game@1.20.5-rc.3, creative@1.20.5-rc.3, survival@1.20.5-rc.3
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityShapeRenderer.RenderItem(Single dt, Boolean isShadowPass, ItemStack stack, AttachmentPointAndPose apap, ItemRenderInfo renderInfo) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 462
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.RenderHeldItem(Single dt, Boolean isShadowPass, Boolean right) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 322
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 249
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderOpaque3D(Single deltaTime) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 104
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 202
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 816
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 911
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 740
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 170
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 2
==================================
{ TimeGenerated = 3/6/2025 9:29:12 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.5.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x114
Faulting application start time: 0x01db8f08a0896a6e
Faulting application path: C:\Users\benma\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\benma\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 26690919-56b7-44c2-99ba-f8f83a543ef7
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 3/6/2025 9:28:34 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.5.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x558
Faulting application start time: 0x01db8f088b5a5f30
Faulting application path: C:\Users\benma\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\benma\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 325231ba-5c6c-41e9-83de-6f94b4849fd1
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Dissssy** [comment]
Same here, holding a copper rod on a dedicated server I got this crash

```
Running on 64 bit Windows 10.0.26120.0 with 32693 MB RAM
Game Version: v1.20.5-rc.3 (Unstable)
3/9/2025 11:14:42 PM: Critical error occurred
Loaded Mods: game@1.20.5-rc.3, creative@1.20.5-rc.3, survival@1.20.5-rc.3
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityShapeRenderer.RenderItem(Single dt, Boolean isShadowPass, ItemStack stack, AttachmentPointAndPose apap, ItemRenderInfo renderInfo) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 462
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.RenderHeldItem(Single dt, Boolean isShadowPass, Boolean right) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 322
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 249
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderOpaque3D(Single deltaTime) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 104
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 202
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 816
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 911
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 740
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 170
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by radfast** [comment]
Thanks to all who have reported these issues.

We think these are now properly fixed in upcoming release 1.20.5-rc.4 and then 1.20.5-stable when it comes.

For now, with hot items such as iron rod, the workaround is to let it cool down on the anvil to less than 200 °C, before picking it up.  Or **don't** use tongs and take the damage ...

**Comment by Naiavita** [comment]
So... my issue was flagged as a duplicate, even though I was not smithing items. How does this fix my issue about crashing in Tobias' cave? Do I have to wait for the next stable version, and HOPE this completely unrelated bug being fixed somehow fixes my issue??

**Comment by Craluminum2413** [comment]
@radfast Bug is back

**Comment by mjlangan** [comment]
Also seeing this, just started recently while I was standing in my base waiting for some ingots to heat on the forge. I don't remember what items I had in my hands, unfortunately.

```
Running on 64 bit Windows 10.0.26100.0 with 64660 MB RAM
Game Version: v1.20.6 (Stable)
3/22/2025 6:53:16 PM: Critical error occurred
Loaded Mods: aculinaryartillery@1.2.3, axleinblocks@1.20.1-rc.5, chiseltools@1.14.12, dyedarmor@1.1.1, hangingoillamps@1.0.3, millwright@1.1.8, particlesplus@1.2.1, game@1.20.6, egocaribautomapmarkers@4.0.1, betterfirepit@1.1.5, betterruins@0.4.6, carryon@1.8.0-pre.1, expandedfoods@1.7.3, glowingarrows@1.2.2, knapster@2.14.1, oneroof@1.8.2, creative@1.20.6, survival@1.20.6, em@3.0.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.RenderAPIBase.RenderMultiTextureMesh(MultiTextureMeshRef mmr, String textureSampleName, Int32 textureNumber) in VintagestoryLib\Client\API\RenderAPIBase.cs:line 107
   at Vintagestory.GameContent.EntityShapeRenderer.RenderItem(Single dt, Boolean isShadowPass, ItemStack stack, AttachmentPointAndPose apap, ItemRenderInfo renderInfo) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 535
   at Vintagestory.GameContent.EntityShapeRenderer.RenderHeldItem(Single dt, Boolean isShadowPass, Boolean right) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 446
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.RenderHeldItem(Single dt, Boolean isShadowPass, Boolean right) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 330
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 249
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderFrameShadows(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 197
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 202
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 816
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 879
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 740
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 170
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/22/2025 6:47:47 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.6.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x31a0
Faulting application start time: 0x1db9b95761b7099
Faulting application path: C:\Users\Michael\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Michael\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: f4b4a415-5810-465c-af52-c842ae2eff52
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 3/22/2025 6:43:09 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.6.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x6b3c
Faulting application start time: 0x1db9b946b6dd44e
Faulting application path: C:\Users\Michael\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Michael\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 41bb5e90-c2d0-4d28-869e-3112f9afd107
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 3/22/2025 6:35:18 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.6.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x2ac80
Faulting application start time: 0x1db9b93c5aa51f6
Faulting application path: C:\Users\Michael\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Michael\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: bff7fffb-669f-49a1-a12a-bc86578f4a1b
Faulting package full name: 
Faulting package-relative application ID:  }
```

[client-debug.log](https://github.com/user-attachments/files/19406619/client-debug.log)

[client-main.log](https://github.com/user-attachments/files/19406620/client-main.log)

[client-crash.log](https://github.com/user-attachments/files/19406621/client-crash.log)

**Comment by timvandenhof** [comment]
Just reporting this on latest version (1.20.7) as well. I was just running in a straight line and removing some snow with bare hands. Not sure if that was the cause though, could be rendering something else. Created a copy of the logs in the Logs folder if needed.

```
Running on 64 bit Windows 10.0.26100.0 with 32710 MB RAM
Game Version: v1.20.7 (Stable)
31/03/2025 22:18:12: Critical error occurred
Loaded Mods: game@1.20.7, creative@1.20.7, survival@1.20.7
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityShapeRenderer.RenderItem(Single dt, Boolean isShadowPass, ItemStack stack, AttachmentPointAndPose apap, ItemRenderInfo renderInfo) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 451
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 214
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderFrameShadows(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 174
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 188
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 825
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 161
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

```

**Comment by The-Heinz** [comment]
I will add that I rolled back my Nvdia drivers back to a February stable version and had no crashes after thirty minutes of testing. I’ll play some more tonight to verify if that resolved my issue (originally under case #5661), and I can post what version I’m running when I get home.

**Comment by The-Heinz** [comment]
> I will add that I rolled back my Nvdia drivers back to a February stable version and had no crashes after thirty minutes of testing. I’ll play some more tonight to verify if that resolved my issue (originally under case [#5661](https://github.com/anegostudios/VintageStory-Issues/issues/5661)), and I can post what version I’m running when I get home.

I played for several hours this weekend after rolling back my NVIDIA drivers to a February release and had zero crashes. I only had rare freezing due to lag/desync with the server, which resolved after a second or two. I believe that resolved my original issue.

**Comment by TemporalWolf** [comment]
Just ran into this 3 times on TOPS with 1.21.1-rc2. Even with all mods disabled, as it currently stands:

I log into tops, 5 seconds later I crash. I went through a TL, I have a molybdochalkos lantern in my off hand and a stack of chalk in my hand hand, which I was previously using to write on signs.

I've left my character in the bugged state, I imagine in might be helpful to pull my character off tops to see what item is borked.

```
Running on 64 bit Windows 10.0.26100.0 with 32507 MB RAM
Game Version: v1.21.1-rc.2 (Unstable)
9/6/2025 8:12:08 PM: Critical error occurred
Loaded Mods: game@1.21.1-rc.2, creative@1.21.1-rc.2, survival@1.21.1-rc.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityShapeRenderer.RenderItem(Single dt, Boolean isShadowPass, ItemStack stack, AttachmentPointAndPose apap, ItemRenderInfo renderInfo) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 454
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.RenderHeldItem(Single dt, Boolean isShadowPass, Boolean right) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 323
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 250
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderFrameShadows(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 205
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 196
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 827
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 888
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 751
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 172
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 719
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 663
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 113
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 338
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 133
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 95

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 9/6/2025 8:11:01 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.21.1.0, time stamp: 0x67fe0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x20ec
Faulting application start time: 0x1dc1fa4ecd684cd
Faulting application path: C:\Users\Pu_23\AppData\Roaming\Vintagestory19\Vintagestory.exe
Faulting module path: C:\Users\Pu_23\AppData\Roaming\Vintagestory19\Lib\openal32.dll
Report Id: 4663bdfb-eb93-42f7-a715-5a57ebb335dd
Faulting package full name: 
Faulting package-relative application ID:  }
```

[client-crash.log](https://github.com/user-attachments/files/22192739/client-crash.log)

**Comment by Craluminum2413** [comment]
Logs from the duplicate:
[client-audit.log](https://github.com/user-attachments/files/22471629/client-audit.log)
[client-chat.log](https://github.com/user-attachments/files/22471636/client-chat.log)
[client-crash.log](https://github.com/user-attachments/files/22471633/client-crash.log)
[client-debug.log](https://github.com/user-attachments/files/22471639/client-debug.log)
[client-main.log](https://github.com/user-attachments/files/22471635/client-main.log)
[server-audit.log](https://github.com/user-attachments/files/22471634/server-audit.log)
[server-build.log](https://github.com/user-attachments/files/22471630/server-build.log)
[server-chat.log](https://github.com/user-attachments/files/22471637/server-chat.log)
[server-debug.log](https://github.com/user-attachments/files/22471631/server-debug.log)
[server-main.log](https://github.com/user-attachments/files/22471632/server-main.log)
[server-worldgen.log](https://github.com/user-attachments/files/22471638/server-worldgen.log)
