### ISSUE TITLE
Extremely out of range player coordinates immediately after/upon connecting to a server

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4778]
### Game Version

1.20.0-rc.5

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

All of the sudden the creative world I am using when translating crashed.

I had just created a female villager. Then equipped some more hand baskets in the backpack slots and had a basket trap ready to go over and try to capture a chicken. When I either turn around or start moving towards the chickens the game crashes. It seems something that got into the field of view or left it made the game crash.

Every time I start the world again I get the exact same crash before any rendering of the world is shown on the screen.

I have done many tests to see strings in action and have lots of items all over the place in this world, so the problem might have built up over time.

### Logs

```Running on 64 bit Linux (Pop!_OS 22.04 LTS) [Kernel 6.9.3.76060903] with 25035 MB RAM
Game Version: v1.20.0-rc.5 (Unstable)
23/12/2024 12:17:21: Critical error occurred
Loaded Mods: game@1.20.0-rc.5, creative@1.20.0-rc.5, survival@1.20.0-rc.5
System.ArithmeticException: Function does not accept floating point Not-a-Number values.
   at System.Math.Sign(Single value)
   at Vintagestory.Client.NoObf.AmbientManager.UpdateAmbient(Single dt) in VintagestoryLib\Client\Render\AmbientManager.cs:line 327
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 194
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 867
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 739
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 170
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 127
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```
[client-main.log](https://github.com/user-attachments/files/18228835/client-main.log)
[server-main.log](https://github.com/user-attachments/files/18228836/server-main.log)
[client-crash.log](https://github.com/user-attachments/files/18228838/client-crash.log)

**Comment by radfast** [comment]
Any chance you can upload the world save file for us please, @tannyl - either as an attachment here if Github will let you, or via any file sharing service of your preference.    A Vintage Story world save file can usually be zipped to about 20-50% of its original filesize before sharing, YMMV.

**Comment by tannyl** [comment]
@radfast sure thing. I put it up on dropbox: https://www.dropbox.com/scl/fi/ojqv9lk4wmuvyyxv68sz4/sunny-test-world.zip?rlkey=94jp51hdjn7gmsvk8w7qn0kap&st=i546ervu&dl=0

**Comment by radfast** [comment]
Thank you.  We have attempted to fix this in upcoming 1.20.0-rc.6 which I believe is likely to become available on 24 December, no guarantee.  Once you have that version, I'd appreciate if you can post back here if that resolves the issue.  There may be mild visual artifacts in fog or sunlight, with the same root cause - essentially the fix will prevent a crash but I did not yet find the underlying root cause.

The crash does not relate to your in-game actions such as making a basket trap or capturing a chicken, it relates to the world, the sky, the current weather, i.e. ambient conditions - the specific combination of conditions at the place your player currently happens to be at, triggered the crash.

**Comment by tannyl** [comment]
Great. I'll report back ones I have tested in the next rc.

**Comment by tannyl** [comment]
Ok I have tested.

Loading the world does not crash the game anymore. I am able to get into the game but this is what I see:
![Screenshot from 2024-12-25 10-23-11](https://github.com/user-attachments/assets/880eef07-29f4-4514-900a-87e3e9806c4b)

The remapping window is of course fine, but the local server seems to be struggling very hard and I am located way WAY WAAAAAYYYY! outside the world border.

Interacting with the remap window does not do anything. At times even the client hangs, but when it is not I am able to quit the world and the server is shut down.

Also in the linux terminal it spews out this again and again, most likely due to me being so far outside the world.
![Screenshot from 2024-12-25 10-13-12](https://github.com/user-attachments/assets/7a6cedc2-1ce2-4d20-a564-9088204e992e)

When I quit the world and the server shuts down I get the following in the linux terminal (notice errror at line 3):
```
25.12.2024 10:33:28 [Client Notification] Exiting current game to main menu, reason: leave world button pressed
25.12.2024 10:33:28 [Client Debug] GuiScreenConnectingToServer constructed
25.12.2024 10:33:31 [Server Error] Exception: Index was outside the bounds of the array.
   at Vintagestory.Common.BlockAccessorBase.LoadChunksToCache(Int32 mincx, Int32 mincy, Int32 mincz, Int32 maxcx, Int32 maxcy, Int32 maxcz, Action`3 onChunkMissing) in VintagestoryLib\Common\API\BlockAccessorBase.cs:line 372
   at Vintagestory.Common.BlockAccessorBase.WalkBlocks(BlockPos minPos, BlockPos maxPos, Action`4 onBlock, Boolean centerOrder) in VintagestoryLib\Common\API\BlockAccessorBase.cs:line 279
   at Vintagestory.GameContent.EntityBehaviorBodyTemperature.OnGameTick(Single deltaTime) in VSSurvivalMod\Entity\Behavior\BehaviorBodyTemperature.cs:line 301
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\Entity.cs:line 928
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 600
   at Vintagestory.API.Common.EntityPlayer.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 645
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt) in VintagestoryLib\Server\Systems\World\EntitySimulation.cs:line 331
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt) in VintagestoryLib\Server\Systems\World\EntitySimulation.cs:line 143
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 896
25.12.2024 10:33:31 [Server Notification] Last player disconnected, compacting large object heap...
25.12.2024 10:33:32 [Server Notification] UDP: client disconnected Drakxter
25.12.2024 10:33:32 [Server Event] Player Drakxter got removed. Reason: Server shutting down - Exit request by client
25.12.2024 10:33:32 [Server Notification] Server stop requested, begin shutdown sequence. Stop reason: Exit request by client
25.12.2024 10:33:32 [Server Notification] Server ticking has been suspended
25.12.2024 10:33:32 [Server Notification] Entering runphase Shutdown
25.12.2024 10:33:32 [Server Notification] Defragmented listener lists
25.12.2024 10:33:32 [Server Event] Mods and systems notified, now saving everything...
25.12.2024 10:33:32 [Server Event] Saved player world data...
25.12.2024 10:33:32 [Server Event] Saved map regions...
25.12.2024 10:33:32 [Server Event] Saved map chunks...
25.12.2024 10:33:32 [Server Event] Saved loaded chunks...
25.12.2024 10:33:32 [Server Event] Saved generating chunks...
25.12.2024 10:33:32 [Server Event] Saved savegamedata...2
25.12.2024 10:33:32 [Server Event] World saved! Saved 0 chunks, 0 mapchunks, 16 mapregions.
25.12.2024 10:33:32 [Server Event] Shutting down 6 server threads... 
25.12.2024 10:33:32 [Server Event] Killed console thread
25.12.2024 10:33:33 [Server Event] All threads gracefully shut down
25.12.2024 10:33:33 [Server Event] Doing last tick...
25.12.2024 10:33:33 [Server Event] Stopped the server!

```

**Comment by radfast** [comment]
OK so _something else_ has placed the player 2 billion blocks outside the world border.   And in consequence a few game systems are behaving abnormally or logging errors, which is hardly surprising.

I don't know _what_ is that "something else" which caused this.  Never seen this before.  There is always the possibility of crash / PC power loss during saving the game - even if code is perfect (and we're not suggesting it is!) anything can be corrupted if the PC loses power mid-way through a disk I/O operation.

If you want to keep playing this world, please try this command:  `/tp 0 150 0`.   Do it as soon as possible after the game starts.  Wait a couple of seconds for it to take effect.  Exit the game normally.  Then re-log, and hopefully the change of your player position was saved and you are now at or near spawn, and can play normally.

**Comment by tannyl** [comment]
Trying to teleport does not work (so far). Funny enough, shutting down the server works just fine (a bit slow) when I exit the singleplayer world. I have tried running in repair mode. And also running without debug mode turned on.

When I look in the server log it says it is placing the player at -562949953421312 -562949953421312 -562949953421312

[server-main.log](https://github.com/user-attachments/files/18255094/server-main.log)

After several tries I managed to take damage from gravity and next at next startup attempt i finally died and get the respawn or quit in anger box. Sadly pressing respawn does not work it seems nor do quiting and starting again not change anything. Just get the box again.

It also seems like the server is running fine, but the communication between server and client is messed up.

**Comment by radfast** [comment]
1. Is it only this worldsave, or does the issue occur if you start a new world on this server?  (I'm assuming you have control over the server)

2. Which game version did the issue start?

3. How is your server set up?  (a) same machine that you play on;  (b) another machine on your local network;  (c) remotely hosted?

**Comment by radfast** [comment]
(Possibly related issue, though I'm keeping an open mind: #4812)

**Comment by tannyl** [comment]
1. It so far only happens with this worldsave. None of the other pre rc6 I loaded or new ones I tried to make have this issue so far.

2. This current issue started with rc6, which fixed the original problem in this issue (the trying to do math on a NaN). So far it only happens in the worldsave that had that NaN related crash in rc5.

3. This is all just singleplayer instances. So client and server are all on the same machine.

4. I have not had this open to anyone, but I could try to a setup something on the LAN and try to run the worldsave as a server and then connect from another PC with another user. I might have time for for that later today.

5. I just tried connecting to an public rc6 server on the internet, and that worked fine.

**Comment by radfast** [comment]
Thank @tannyl for the detailed responses.

We have looked at this some more. We now believe it was either (a) a one-off glitch in this savegame for unknown reasons, including disk error or bad shutdown of the game; or (b) a rare bug deep in the new 1.20 physics code.  [For other coders, I think most likely a single NaN value was used to calculate x,y,z or Motion.X,Y,Z - since any arithmetic operation using NaN will in turn produce NaN as the result. Something has made **all three** of x,y,z become NaN. I looked at whether a NaN _dt_ was possible for example, but I can't see any possibility of that in the code.]

Anyhow @tannyl in upcoming release -rc.7 we have added code which detects invalid coordinates at the time of loading a player into the world, and if detected will reset the player to world spawn, with an entry in logs.  I think that is enough to resolve the problem.  If the problem recurs in future, it will likely cause errors or crashes within the physics engine itself while ticking and that will give us more information, for now I think this can be closed as resolved.

**Comment by tannyl** [comment]
@radfast sounds good. I'll test in rc7 when it arrives and report back if the reset works or not.

**Comment by tannyl** [comment]
@radfast I tested in rc7 now and the "reset player coordinates when invalid" worked. No new crashes so far related to the original problem.

**Comment by tyronx** [comment]
Turns out its not a one-off. There are other instances of this error
