### ISSUE TITLE
Game crashes when pruning

### ISSUE THREAD

**Issue by NastyFlytrap** [anegostudios/VintageStory-Issues#4780]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I ran prune with a keep and a threshhold of 0, confirmed, of course, and after 15 seconds or so the game errored out and sent me to the main menu.

NO MODS. I TURNED THEM OFF, DONT ASK.

### How to reproduce

Load the world
Turn off autogen
run the prune with the values above
run into error

### Logs

24.12.2024 03:43:31 [Notification] Server logger started.
24.12.2024 03:43:31 [Notification] Game Version: v1.19.8 (Stable)
24.12.2024 03:43:31 [Event] Launching server...
24.12.2024 03:43:31 [Event] Server v1.19.8, network v1.19.8, api v1.19.0
24.12.2024 03:43:31 [Notification] Entering runphase Initialization
24.12.2024 03:43:31 [Event] Loading configuration...
24.12.2024 03:43:31 [Notification] Entering runphase Configuration
24.12.2024 03:43:31 [Notification] Loading savegame
24.12.2024 03:43:31 [Notification] Loaded existing save game data. Playstyle: surviveandbuild, Playstyle Lang code: preset-surviveandbuild, WorldType: preset-surviveandbuild
24.12.2024 03:43:31 [Notification] Savegame C:\Users\BOSS\AppData\Roaming\VintagestoryData\Saves\voxelland2PrePrune.vcdbs loaded
24.12.2024 03:43:31 [Notification] World size = 256000 256 256000
24.12.2024 03:43:31 [Notification] Start discovering assets
24.12.2024 03:43:31 [Notification] Found 1 base assets in category blocktypes
24.12.2024 03:43:31 [Notification] Found 0 base assets in category itemtypes
24.12.2024 03:43:31 [Notification] Found 25 base assets in category lang
24.12.2024 03:43:31 [Notification] Found 0 base assets in category patches
24.12.2024 03:43:31 [Notification] Found 24 base assets in category config
24.12.2024 03:43:31 [Notification] Found 0 base assets in category worldproperties
24.12.2024 03:43:31 [Notification] Found 48 base assets in category sounds
24.12.2024 03:43:31 [Notification] Found 95 base assets in category shapes
24.12.2024 03:43:31 [Notification] Found 133 base assets in category textures
24.12.2024 03:43:31 [Notification] Found 0 base assets in category recipes
24.12.2024 03:43:31 [Notification] Found 0 base assets in category worldgen
24.12.2024 03:43:31 [Notification] Found 3 base assets in category entities
24.12.2024 03:43:31 [Notification] Found 0 base assets in category compatibility
24.12.2024 03:43:31 [Notification] Found 329 base assets in total
24.12.2024 03:43:31 [Event] Building assets...
24.12.2024 03:43:31 [Notification] Entering runphase LoadAssets
24.12.2024 03:43:31 [Notification] Will search the following paths for mods:
24.12.2024 03:43:31 [Notification]     C:\Users\BOSS\Stuff\Vintagestory\Mods
24.12.2024 03:43:31 [Notification]     C:\Users\BOSS\AppData\Roaming\VintagestoryData\Mods
24.12.2024 03:43:32 [Notification] Found 71 mods (68 disabled)
24.12.2024 03:43:32 [Notification] Mods, sorted by dependency: game, creative, survival
24.12.2024 03:43:32 [Notification] Instantiated 110 mod systems from 3 enabled mods
24.12.2024 03:43:32 [Notification] External Origins in load order: modorigin@C:\Users\BOSS\Stuff\Vintagestory\assets\creative\, modorigin@C:\Users\BOSS\Stuff\Vintagestory\assets\survival\
24.12.2024 03:43:32 [Notification] Found 404 external assets in category blocktypes
24.12.2024 03:43:32 [Notification] Found 242 external assets in category itemtypes
24.12.2024 03:43:32 [Notification] Found 0 external assets in category lang
24.12.2024 03:43:32 [Notification] Found 9 external assets in category patches
24.12.2024 03:43:32 [Notification] Found 56 external assets in category config
24.12.2024 03:43:32 [Notification] Found 25 external assets in category worldproperties
24.12.2024 03:43:32 [Notification] Found 418 external assets in category sounds
24.12.2024 03:43:32 [Notification] Found 3636 external assets in category shapes
24.12.2024 03:43:32 [Notification] Found 5573 external assets in category textures
24.12.2024 03:43:32 [Notification] Found 363 external assets in category recipes
24.12.2024 03:43:32 [Notification] Found 478 external assets in category worldgen
24.12.2024 03:43:32 [Notification] Found 64 external assets in category entities
24.12.2024 03:43:32 [Notification] Found 0 external assets in category compatibility
24.12.2024 03:43:32 [Notification] Reloaded lang file with mod assets
24.12.2024 03:43:32 [Notification] Compatibility lib: 0 assets added, 0 assets replaced.
24.12.2024 03:43:32 [Notification] JsonPatch Loader: 14 patches total, successfully applied 14 patches, unmet conditions on 18 patches, no errors
24.12.2024 03:43:33 [Notification] Loaded 3335 unique items
24.12.2024 03:43:34 [Notification] Loaded 9312 unique blocks
24.12.2024 03:43:34 [Notification] Loaded 606 unique entities
24.12.2024 03:43:34 [Notification] BlockLoader: Entities, Blocks and Items loaded
24.12.2024 03:43:34 [Event] Remapping blocks and items...
24.12.2024 03:43:34 [Event] 8 cooking recipes loaded
24.12.2024 03:43:35 [Event] 677 crafting recipes loaded from 233 files
24.12.2024 03:43:35 [Event] 9 metal alloys loaded
24.12.2024 03:43:35 [Event] 241 smithing recipes loaded
24.12.2024 03:43:35 [Event] 55 clay forming recipes loaded
24.12.2024 03:43:35 [Event] 36 knapping recipes loaded
24.12.2024 03:43:35 [Event] 142 barrel recipes loaded
24.12.2024 03:43:35 [Notification] Entering runphase AssetsFinalize
24.12.2024 03:43:35 [Event] Server assets loaded, parsed, registered and finalized
24.12.2024 03:43:35 [Event] Initialising systems...
24.12.2024 03:43:35 [Notification] Entering runphase LoadGamePre
24.12.2024 03:43:35 [Notification] Reloaded 19 weather patterns, 5 wind patterns and 5 weather events
24.12.2024 03:43:35 [Notification] Started 95 systems on Server:
24.12.2024 03:43:35 [Notification]     Mod 'VSEssentials.dll' (game):
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.Core
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.EntityPartitioning
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ErrorReporter
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.ModCompatiblityUtil
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.NoObf.ModJsonPatchLoader
24.12.2024 03:43:35 [Notification]         Vintagestory.Essentials.PathfindSystem
24.12.2024 03:43:35 [Notification]         Vintagestory.Essentials.PathFindDebug
24.12.2024 03:43:35 [Notification]         Vintagestory.Essentials.PathfindingAsync
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.JsonExport
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.ModBasicBlocksLoader
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemDormancyStateChecker
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemSyncHarvestableDropsToClient
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemEmotes
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.LeafBlockDecay
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.POIRegistry
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.RoomRegistry
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.WeatherSystemCommands
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.WeatherSystemServer
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.WorldMapManager
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.LoadColorMaps
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ClothManager
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GridRecipeLoader
24.12.2024 03:43:35 [Notification]     Mod 'VSSurvivalMod.dll' (survival):
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GenTerra
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GenSnowLayer
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemControlPoints
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.SurvivalCoreSystem
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GenTerraPostProcess
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.DebugSystem
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.UpgradeTasks
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.ChiselBlockBulkSetMaterial
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.ModSystemDetailModeSync
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.NpcControl
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.ModSystemTiledDungeonGenerator
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GenFromHeightmap
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GenMaps
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GenRockStrataNew
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GenHotSprings
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GenCreatures
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.WgenCommands
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemExplosionAffectedStability
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.MyceliumSystem
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModsystemButterflySpawnCondsExtra
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemCatchCreature
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemGliding
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ClutterBookshelfUtil
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ScreenshakeToClientModSystem
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemResoArchiveCommands
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ResoArchivesSpawnConditions
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemAuction
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemBlockReinforcement
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.Core
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.CharacterSystem
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.DialogueSystem
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.FruitingSystem
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemCommandHandbook
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemTutorial
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemCorpseReturnTeleporter
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemNightVision
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModJournal
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.LiquidItemStackRenderer
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemStructureLocator
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModLootRandomizer
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemRifts
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemRiftWeather
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSleeping
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemSupportBeamPlacer
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.TeleporterManager
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModTemperature
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.SystemTemporalStability
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.TemporalStabilityEffects
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemWearableStats
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemEditableBook
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.Mechanics.MechanicalPowerMod
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GenDungeons
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GenDeposits
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.GenStoryStructures
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GenCaves
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GenStructures
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GenBlockLayers
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GenPonds
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GenStructuresPosPass
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GenVegetationAndPatches
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.RecipeRegistrySystem
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GenRivulets
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GenLightSurvival
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.RecipeLoader
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemOreMap
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.ModSystemSnowballs
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.TraderOutfits
24.12.2024 03:43:35 [Notification]         Vintagestory.GameContent.DisableRecipeRegisteringSystem
24.12.2024 03:43:35 [Notification]     Mod 'VSCreativeMod.dll' (creative):
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.Core
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.WorldEdit.WorldEdit
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GenBlockLayersFlat
24.12.2024 03:43:35 [Notification]         Vintagestory.ServerMods.GenLightCreative
24.12.2024 03:43:35 [Notification] Server map set
24.12.2024 03:43:35 [Notification] Entering runphase LoadGame
24.12.2024 03:43:35 [Notification] Entering runphase WorldReady
24.12.2024 03:43:35 [Event] Starting world generators...
24.12.2024 03:43:36 [Notification] Sending server identification with remap False.  Server control privilege is True
24.12.2024 03:43:39 [Notification] Reloaded 35 tree generators
24.12.2024 03:43:39 [Event] Loading 7x7x8 spawn chunks...
24.12.2024 03:43:39 [Event] 0% (49 in queue)
24.12.2024 03:43:39 [Event] Begin game ticking...
24.12.2024 03:43:39 [Notification] Entering runphase RunGame
24.12.2024 03:43:39 [Notification] Successfully loaded 457 waypoints
24.12.2024 03:43:39 [Notification] Starting server threads
24.12.2024 03:43:39 [Event] Singleplayer Server now running!
24.12.2024 03:43:39 [Notification] All clients disconnected, pausing game calendar.
24.12.2024 03:43:40 [Notification] A Client attempts connecting via Dummy connection, assigning client id 1
24.12.2024 03:43:41 [Notification] Client uid [REDACTED] attempting identification. Name: NastyFlytrap
24.12.2024 03:43:41 [Notification] Upped server view distance because player is locally connected
24.12.2024 03:43:41 [Notification] Delayed join, need to load one spawn chunk first.
24.12.2024 03:43:41 [Notification] Placing player at 128133.47130683594 116 127995.68659853516
24.12.2024 03:43:42 [Event] NastyFlytrap 127.0.0.1 joins.
24.12.2024 03:43:42 [Notification] A client reconnected, resuming game calendar.
24.12.2024 03:43:47 [Notification] Handling Command (NastyFlytrap) /wgen autogen 0
24.12.2024 03:43:53 [Notification] Handling Command (NastyFlytrap) /db prune 0 keep confirm
24.12.2024 03:44:10 [Error] Failed loading blockentity BlockEntityFlintPile for block  in a chunk. Will discard it. Sorry. Exception logged to verbose debug.
24.12.2024 03:44:25 [Fatal] Caught unhandled exception in thread 'chunkdbthread'. Shutting down server.
24.12.2024 03:44:25 [Error] Exception: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at Microsoft.Data.Sqlite.SqliteConnection.RemoveCommand(SqliteCommand command)
   at Microsoft.Data.Sqlite.SqliteCommand.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at Vintagestory.Common.Database.SQLiteDbConnectionv2.DeleteChunk(UInt64 position, String tablename) in VintagestoryLib\Common\FileIO\Database\SQLiteDbConnectionv2.cs:line 259
   at Vintagestory.Common.Database.SQLiteDbConnectionv2.DeleteChunks(IEnumerable`1 chunkpositions, String tablename) in VintagestoryLib\Common\FileIO\Database\SQLiteDbConnectionv2.cs:line 251
   at Vintagestory.Common.Database.SQLiteDbConnectionv2.DeleteChunks(IEnumerable`1 chunkpositions) in VintagestoryLib\Common\FileIO\Database\SQLiteDbConnectionv2.cs:line 227
   at Vintagestory.Server.ServerSystemSupplyChunks.deleteChunkColumns() in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 443
   at Vintagestory.Server.ServerSystemSupplyChunks.OnSeparateThreadTick() in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 438
   at Vintagestory.Server.ServerThread.Update() in VintagestoryLib\Server\ServerThread.cs:line 111
   at Vintagestory.Server.ServerThread.Process() in VintagestoryLib\Server\ServerThread.cs:line 92
24.12.2024 03:44:29 [Notification] Last player disconnected, compacting large object heap...
24.12.2024 03:44:31 [Event] Player NastyFlytrap got removed. Reason: Server shutting down - Exception during Process
24.12.2024 03:44:31 [Notification] Server stop requested, begin shutdown sequence. Stop reason: Exception during Process
24.12.2024 03:44:31 [Notification] Server ticking has been suspended
24.12.2024 03:44:31 [Notification] Entering runphase Shutdown
24.12.2024 03:44:31 [Notification] Defragmented listener lists
24.12.2024 03:44:31 [Event] Mods and systems notified, now saving everything...
24.12.2024 03:44:31 [Event] Saved player world data...
24.12.2024 03:44:31 [Event] Saved map regions...
24.12.2024 03:44:31 [Event] Saved map chunks...
24.12.2024 03:44:31 [Event] Saved loaded chunks...
24.12.2024 03:44:31 [Event] Saved generating chunks...
24.12.2024 03:44:31 [Event] Saved savegamedata...2
24.12.2024 03:44:31 [Event] World saved! Saved 89 chunks, 265 mapchunks, 16 mapregions.
24.12.2024 03:44:31 [Event] Shutting down 6 server threads... 
24.12.2024 03:44:31 [Event] Killed console thread
24.12.2024 03:44:32 [Event] All threads gracefully shut down
24.12.2024 03:44:32 [Event] Doing last tick...
24.12.2024 03:44:32 [Event] Stopped the server!

**Comment by NastyFlytrap** [comment]
There was still one fucking flint stonepile left in the world. Read the server debug log, found out that way. Wish it'd tell me here in the main log.
