### ISSUE TITLE
Game crashing during prune. No mods this time, for real

### ISSUE THREAD

**Issue by NastyFlytrap** [anegostudios/VintageStory-Issues#4781]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Like the last post, `https://github.com/anegostudios/VintageStory-Issues/issues/4780`, game failed to prune again, but this time it didnt even tell me.

Like last time, no mods running, but unlike last time, no mod blocks are present, i dont think. I really dont know why a mod specific block crashed it last time, it shouldnt do that without the mod actively running, but i removed it, and its still erroring out.

Server debug doesnt have anything to say about the error. It just goes from routine, normal functions so server shutting down.

I really cant imagine a way this'd be a mod problem. No mods are running, and there are no mod specific blocks in the world at this point.

### How to reproduce

Turn off autogen
Run a prune with a threshold of zero and keeping the claims
Have it error out in the background quietly without telling the user

### Logs

24.12.2024 04:40:16 [Notification] Server logger started.
24.12.2024 04:40:16 [Notification] Game Version: v1.19.8 (Stable)
24.12.2024 04:40:16 [Event] Launching server...
24.12.2024 04:40:16 [Event] Server v1.19.8, network v1.19.8, api v1.19.0
24.12.2024 04:40:16 [Notification] Entering runphase Initialization
24.12.2024 04:40:16 [Event] Loading configuration...
24.12.2024 04:40:16 [Notification] Entering runphase Configuration
24.12.2024 04:40:16 [Notification] Loading savegame
24.12.2024 04:40:16 [Notification] Loaded existing save game data. Playstyle: surviveandbuild, Playstyle Lang code: preset-surviveandbuild, WorldType: preset-surviveandbuild
24.12.2024 04:40:16 [Notification] Savegame C:\Users\BOSS\AppData\Roaming\VintagestoryData\Saves\voxelland2PrePrune.vcdbs loaded
24.12.2024 04:40:16 [Notification] World size = 256000 256 256000
24.12.2024 04:40:16 [Notification] Start discovering assets
24.12.2024 04:40:16 [Notification] Found 1 base assets in category blocktypes
24.12.2024 04:40:16 [Notification] Found 0 base assets in category itemtypes
24.12.2024 04:40:16 [Notification] Found 25 base assets in category lang
24.12.2024 04:40:16 [Notification] Found 0 base assets in category patches
24.12.2024 04:40:16 [Notification] Found 24 base assets in category config
24.12.2024 04:40:16 [Notification] Found 0 base assets in category worldproperties
24.12.2024 04:40:16 [Notification] Found 48 base assets in category sounds
24.12.2024 04:40:16 [Notification] Found 95 base assets in category shapes
24.12.2024 04:40:16 [Notification] Found 133 base assets in category textures
24.12.2024 04:40:16 [Notification] Found 0 base assets in category recipes
24.12.2024 04:40:16 [Notification] Found 0 base assets in category worldgen
24.12.2024 04:40:16 [Notification] Found 3 base assets in category entities
24.12.2024 04:40:16 [Notification] Found 0 base assets in category compatibility
24.12.2024 04:40:16 [Notification] Found 329 base assets in total
24.12.2024 04:40:16 [Event] Building assets...
24.12.2024 04:40:16 [Notification] Entering runphase LoadAssets
24.12.2024 04:40:16 [Notification] Will search the following paths for mods:
24.12.2024 04:40:16 [Notification]     C:\Users\BOSS\Stuff\Vintagestory\Mods
24.12.2024 04:40:16 [Notification]     C:\Users\BOSS\AppData\Roaming\VintagestoryData\Mods
24.12.2024 04:40:17 [Notification] Found 71 mods (68 disabled)
24.12.2024 04:40:17 [Notification] Mods, sorted by dependency: game, creative, survival
24.12.2024 04:40:17 [Notification] Instantiated 110 mod systems from 3 enabled mods
24.12.2024 04:40:17 [Notification] External Origins in load order: modorigin@C:\Users\BOSS\Stuff\Vintagestory\assets\creative\, modorigin@C:\Users\BOSS\Stuff\Vintagestory\assets\survival\
24.12.2024 04:40:17 [Notification] Found 404 external assets in category blocktypes
24.12.2024 04:40:17 [Notification] Found 242 external assets in category itemtypes
24.12.2024 04:40:17 [Notification] Found 0 external assets in category lang
24.12.2024 04:40:17 [Notification] Found 9 external assets in category patches
24.12.2024 04:40:17 [Notification] Found 56 external assets in category config
24.12.2024 04:40:17 [Notification] Found 25 external assets in category worldproperties
24.12.2024 04:40:17 [Notification] Found 418 external assets in category sounds
24.12.2024 04:40:17 [Notification] Found 3636 external assets in category shapes
24.12.2024 04:40:17 [Notification] Found 5573 external assets in category textures
24.12.2024 04:40:17 [Notification] Found 363 external assets in category recipes
24.12.2024 04:40:17 [Notification] Found 478 external assets in category worldgen
24.12.2024 04:40:17 [Notification] Found 64 external assets in category entities
24.12.2024 04:40:17 [Notification] Found 0 external assets in category compatibility
24.12.2024 04:40:17 [Notification] Reloaded lang file with mod assets
24.12.2024 04:40:17 [Notification] Compatibility lib: 0 assets added, 0 assets replaced.
24.12.2024 04:40:17 [Notification] JsonPatch Loader: 14 patches total, successfully applied 14 patches, unmet conditions on 18 patches, no errors
24.12.2024 04:40:18 [Notification] Loaded 3335 unique items
24.12.2024 04:40:19 [Notification] Loaded 9312 unique blocks
24.12.2024 04:40:19 [Notification] Loaded 606 unique entities
24.12.2024 04:40:19 [Notification] BlockLoader: Entities, Blocks and Items loaded
24.12.2024 04:40:19 [Event] Remapping blocks and items...
24.12.2024 04:40:19 [Event] 8 cooking recipes loaded
24.12.2024 04:40:20 [Event] 677 crafting recipes loaded from 233 files
24.12.2024 04:40:20 [Event] 9 metal alloys loaded
24.12.2024 04:40:20 [Event] 241 smithing recipes loaded
24.12.2024 04:40:20 [Event] 55 clay forming recipes loaded
24.12.2024 04:40:20 [Event] 36 knapping recipes loaded
24.12.2024 04:40:20 [Event] 142 barrel recipes loaded
24.12.2024 04:40:20 [Notification] Entering runphase AssetsFinalize
24.12.2024 04:40:20 [Event] Server assets loaded, parsed, registered and finalized
24.12.2024 04:40:20 [Event] Initialising systems...
24.12.2024 04:40:20 [Notification] Entering runphase LoadGamePre
24.12.2024 04:40:20 [Notification] Reloaded 19 weather patterns, 5 wind patterns and 5 weather events
24.12.2024 04:40:20 [Notification] Started 95 systems on Server:
24.12.2024 04:40:20 [Notification]     Mod 'VSEssentials.dll' (game):
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.Core
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.EntityPartitioning
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ErrorReporter
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.ModCompatiblityUtil
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.NoObf.ModJsonPatchLoader
24.12.2024 04:40:20 [Notification]         Vintagestory.Essentials.PathfindSystem
24.12.2024 04:40:20 [Notification]         Vintagestory.Essentials.PathFindDebug
24.12.2024 04:40:20 [Notification]         Vintagestory.Essentials.PathfindingAsync
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.JsonExport
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.ModBasicBlocksLoader
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemDormancyStateChecker
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemSyncHarvestableDropsToClient
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemEmotes
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.LeafBlockDecay
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.POIRegistry
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.RoomRegistry
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.WeatherSystemCommands
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.WeatherSystemServer
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.WorldMapManager
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.LoadColorMaps
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ClothManager
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GridRecipeLoader
24.12.2024 04:40:20 [Notification]     Mod 'VSSurvivalMod.dll' (survival):
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GenTerra
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GenSnowLayer
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemControlPoints
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.SurvivalCoreSystem
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GenTerraPostProcess
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.DebugSystem
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.UpgradeTasks
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.ChiselBlockBulkSetMaterial
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.ModSystemDetailModeSync
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.NpcControl
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.ModSystemTiledDungeonGenerator
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GenFromHeightmap
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GenMaps
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GenRockStrataNew
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GenHotSprings
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GenCreatures
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.WgenCommands
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemExplosionAffectedStability
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.MyceliumSystem
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModsystemButterflySpawnCondsExtra
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemCatchCreature
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemGliding
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ClutterBookshelfUtil
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ScreenshakeToClientModSystem
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemResoArchiveCommands
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ResoArchivesSpawnConditions
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemAuction
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemBlockReinforcement
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.Core
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.CharacterSystem
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.DialogueSystem
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.FruitingSystem
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemCommandHandbook
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemTutorial
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemCorpseReturnTeleporter
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemNightVision
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModJournal
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.LiquidItemStackRenderer
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemStructureLocator
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModLootRandomizer
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemRifts
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemRiftWeather
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSleeping
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemSupportBeamPlacer
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.TeleporterManager
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModTemperature
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.SystemTemporalStability
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.TemporalStabilityEffects
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemWearableStats
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemEditableBook
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.Mechanics.MechanicalPowerMod
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GenDungeons
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GenDeposits
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.GenStoryStructures
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GenCaves
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GenStructures
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GenBlockLayers
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GenPonds
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GenStructuresPosPass
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GenVegetationAndPatches
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.RecipeRegistrySystem
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GenRivulets
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GenLightSurvival
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.RecipeLoader
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemOreMap
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.ModSystemSnowballs
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.TraderOutfits
24.12.2024 04:40:20 [Notification]         Vintagestory.GameContent.DisableRecipeRegisteringSystem
24.12.2024 04:40:20 [Notification]     Mod 'VSCreativeMod.dll' (creative):
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.Core
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.WorldEdit.WorldEdit
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GenBlockLayersFlat
24.12.2024 04:40:20 [Notification]         Vintagestory.ServerMods.GenLightCreative
24.12.2024 04:40:21 [Notification] Server map set
24.12.2024 04:40:21 [Notification] Entering runphase LoadGame
24.12.2024 04:40:21 [Notification] Entering runphase WorldReady
24.12.2024 04:40:21 [Event] Starting world generators...
24.12.2024 04:40:21 [Notification] Sending server identification with remap False.  Server control privilege is True
24.12.2024 04:40:24 [Notification] Reloaded 35 tree generators
24.12.2024 04:40:24 [Event] Loading 7x7x8 spawn chunks...
24.12.2024 04:40:24 [Event] 0% (49 in queue)
24.12.2024 04:40:25 [Event] Begin game ticking...
24.12.2024 04:40:25 [Notification] Entering runphase RunGame
24.12.2024 04:40:25 [Notification] Successfully loaded 457 waypoints
24.12.2024 04:40:25 [Notification] Starting server threads
24.12.2024 04:40:25 [Event] Singleplayer Server now running!
24.12.2024 04:40:25 [Notification] All clients disconnected, pausing game calendar.
24.12.2024 04:40:27 [Notification] A Client attempts connecting via Dummy connection, assigning client id 1
24.12.2024 04:40:27 [Notification] Client uid [Still redacted] attempting identification. Name: NastyFlytrap
24.12.2024 04:40:27 [Notification] Upped server view distance because player is locally connected
24.12.2024 04:40:27 [Notification] Delayed join, need to load one spawn chunk first.
24.12.2024 04:40:27 [Notification] Placing player at 128132.01022851563 116 127992.0029928711
24.12.2024 04:40:29 [Event] NastyFlytrap 127.0.0.1 joins.
24.12.2024 04:40:29 [Notification] A client reconnected, resuming game calendar.
24.12.2024 04:40:34 [Notification] Handling Command (NastyFlytrap) /wgen autogen 0
24.12.2024 04:40:45 [Notification] Handling Command (NastyFlytrap) /db prune 0 keep confirm
24.12.2024 04:41:27 [Error] Exception: Object reference not set to an instance of an object.
   at Microsoft.Data.Sqlite.SqliteConnection.RemoveCommand(SqliteCommand command)
   at Microsoft.Data.Sqlite.SqliteCommand.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at Vintagestory.Common.Database.SQLiteDbConnectionv2.GetChunk(UInt64 position, String tablename) in VintagestoryLib\Common\FileIO\Database\SQLiteDbConnectionv2.cs:line 223
   at Vintagestory.Server.ServerSystemSupplyChunkCommands.<>c__DisplayClass7_0.<prune>b__1() in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunkCommands.cs:line 166
   at Vintagestory.Server.ServerMain.ProcessMainThreadTasks() in VintagestoryLib\Server\ServerMain.cs:line 2782
   at Vintagestory.Server.ServerMain.ProcessMain() in VintagestoryLib\Server\ServerMain.cs:line 893
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 886
24.12.2024 04:41:27 [Fatal] Caught unhandled exception in thread 'chunkdbthread'. Shutting down server.
24.12.2024 04:41:27 [Error] Exception: Object reference not set to an instance of an object.
   at Microsoft.Data.Sqlite.SqliteConnection.RemoveCommand(SqliteCommand command)
   at Microsoft.Data.Sqlite.SqliteCommand.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters)
   at Microsoft.Data.Sqlite.SqliteTransaction.RollbackInternal()
   at Vintagestory.Common.Database.SQLiteDbConnectionv2.DeleteChunks(IEnumerable`1 chunkpositions, String tablename) in VintagestoryLib\Common\FileIO\Database\SQLiteDbConnectionv2.cs:line 251
   at Vintagestory.Server.ServerSystemSupplyChunks.deleteChunkColumns() in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 443
   at Vintagestory.Server.ServerSystemSupplyChunks.OnSeparateThreadTick() in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 438
   at Vintagestory.Server.ServerThread.Update() in VintagestoryLib\Server\ServerThread.cs:line 111
   at Vintagestory.Server.ServerThread.Process() in VintagestoryLib\Server\ServerThread.cs:line 92
24.12.2024 04:41:27 [Notification] Last player disconnected, compacting large object heap...
24.12.2024 04:41:28 [Event] Player NastyFlytrap got removed. Reason: Server shutting down - Exception during Process
24.12.2024 04:41:28 [Notification] Server stop requested, begin shutdown sequence. Stop reason: Exception during Process
24.12.2024 04:41:28 [Notification] Server ticking has been suspended
24.12.2024 04:41:28 [Notification] Entering runphase Shutdown
24.12.2024 04:41:28 [Notification] Defragmented listener lists
24.12.2024 04:41:28 [Event] Mods and systems notified, now saving everything...
24.12.2024 04:41:28 [Error] Exception thrown during handling event OnGameWorldBeingSaved:
24.12.2024 04:41:28 [Error] Exception: Object reference not set to an instance of an object.
   at Microsoft.Data.Sqlite.SqliteConnection.RemoveCommand(SqliteCommand command)
   at Microsoft.Data.Sqlite.SqliteCommand.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at Vintagestory.Common.Database.SQLiteDbConnectionv2.GetPlayerData(String playeruid) in VintagestoryLib\Common\FileIO\Database\SQLiteDbConnectionv2.cs:line 138
   at Vintagestory.Common.Database.SQLiteDbConnectionv2.SetPlayerData(String playeruid, Byte[] data) in VintagestoryLib\Common\FileIO\Database\SQLiteDbConnectionv2.cs:line 152
   at Vintagestory.Common.GameDatabase.SetPlayerData(String playeruid, Byte[] data) in VintagestoryLib\Common\FileIO\Database\GameDatabase.cs:line 243
   at Vintagestory.Server.ServerSystemLoadAndSaveGame.SaveGameWorld(Boolean saveLater) in VintagestoryLib\Server\Systems\World\LoadThread\LoadSaveGame.cs:line 366
   at Vintagestory.Server.ServerSystemLoadAndSaveGame.OnWorldBeingSaved() in VintagestoryLib\Server\Systems\World\LoadThread\LoadSaveGame.cs:line 263
   at Vintagestory.Server.ServerEventManager.TriggerGameWorldBeingSaved() in VintagestoryLib\Server\ServerEventManager.cs:line 525
24.12.2024 04:41:28 [Event] Shutting down 6 server threads... 
24.12.2024 04:41:28 [Event] Killed console thread
24.12.2024 04:41:29 [Event] All threads gracefully shut down
24.12.2024 04:41:29 [Event] Doing last tick...
24.12.2024 04:41:29 [Event] Stopped the server!

**Comment by Uncurlhalo** [comment]
Experiencing a very similar crash

```
20:08:10

26.4.2025 00:08:10 [Server Notification] Handling Console Command /db prune 1 keep confirm
26.4.2025 00:08:10 [Server Notification] Prune started, this may take some time.

20:18:39

26.4.2025 00:18:39 [Server Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.Common.Database.SQLiteDbConnectionv2.GetChunk(UInt64 position, String tablename) in VintagestoryLib\Common\FileIO\Database\SQLiteDbConnectionv2.cs:line 222
   at Vintagestory.Server.ServerSystemSupplyChunkCommands.<>c__DisplayClass7_0.<prune>b__1() in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunkCommands.cs:line 247
   at Vintagestory.Server.ServerMain.ProcessMainThreadTasks() in VintagestoryLib\Server\ServerMain.cs:line 2927
   at Vintagestory.Server.ServerMain.ProcessMain() in VintagestoryLib\Server\ServerMain.cs:line 957
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 914
26.4.2025 00:18:39 [Server Fatal] Caught unhandled exception in thread 'chunkdbthread'. Shutting down server.
26.4.2025 00:18:39 [Server Error] Exception: Object reference not set to an instance of an object.
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters)
   at Microsoft.Data.Sqlite.SqliteTransaction.RollbackInternal()
   at Vintagestory.Common.Database.SQLiteDbConnectionv2.DeleteChunks(IEnumerable`1 chunkpositions, String tablename) in VintagestoryLib\Common\FileIO\Database\SQLiteDbConnectionv2.cs:line 250
   at Vintagestory.Server.ServerSystemSupplyChunks.deleteChunkColumns() in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 524
   at Vintagestory.Server.ServerSystemSupplyChunks.OnSeparateThreadTick() in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 447
   at Vintagestory.Server.ServerThread.Process() in VintagestoryLib\Server\ServerThread.cs:line 92
26.4.2025 00:18:39 [Server Warning] Over 400ms tick. Skipping 610 physics ticks.
26.4.2025 00:18:39 [Server Notification] Server stop requested, begin shutdown sequence. Stop reason: Exception during Process
26.4.2025 00:18:39 [Server Notification] Server ticking has been suspended
26.4.2025 00:18:39 [Server Notification] Entering runphase Shutdown
26.4.2025 00:18:39 [Server Debug] Unpatching harmony methods

20:18:40

26.4.2025 00:18:40 [Server Notification] Unregistering from master server...
26.4.2025 00:18:40 [Server Event] Mods and systems notified, now saving everything...
26.4.2025 00:18:40 [Server Error] Exception thrown during handling event OnGameWorldBeingSaved. Will skip over.
26.4.2025 00:18:40 [Server Error] Exception: Object reference not set to an instance of an object.
   at Microsoft.Data.Sqlite.SqliteCommand.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at Vintagestory.Common.Database.SQLiteDbConnectionv2.GetPlayerData(String playeruid) in VintagestoryLib\Common\FileIO\Database\SQLiteDbConnectionv2.cs:line 137
   at Vintagestory.Common.Database.SQLiteDbConnectionv2.SetPlayerData(String playeruid, Byte[] data) in VintagestoryLib\Common\FileIO\Database\SQLiteDbConnectionv2.cs:line 151
   at Vintagestory.Common.GameDatabase.SetPlayerData(String playeruid, Byte[] data) in VintagestoryLib\Common\FileIO\Database\GameDatabase.cs:line 248
   at Vintagestory.Server.ServerSystemLoadAndSaveGame.SaveGameWorld(Boolean saveLater) in VintagestoryLib\Server\Systems\World\LoadThread\LoadSaveGame.cs:line 385
   at Vintagestory.Server.ServerSystemLoadAndSaveGame.OnWorldBeingSaved() in VintagestoryLib\Server\Systems\World\LoadThread\LoadSaveGame.cs:line 275
   at Vintagestory.Server.ServerEventManager.TriggerGameWorldBeingSaved() in VintagestoryLib\Server\ServerEventManager.cs:line 475
```

**Comment by NastyFlytrap** [comment]
Just a heads up, even a year or something later still happening.

https://github.com/anegostudios/VintageStory-Issues/issues/5806

**Comment by Craluminum2413** [comment]
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/3734
