### ISSUE TITLE
Failed registering item game:stackrandomizer-armor:

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#4784]
### Game Version

1.20.0-rc.6

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Logs

[Server Error] Failed registering item game:stackrandomizer-armor:
24.12.2024 14:54:11 [Server Error] Exception: Attempted to register Item with code game:stackrandomizer-armor, but an item with such code already exists. Must use a unique code
   at Vintagestory.Server.ServerMain.RegisterItem(Item item) in VintagestoryLib\Server\ServerMain.cs:line 1762
   at Vintagestory.Server.ServerCoreAPI.RegisterItem(Item item) in VintagestoryLib\Server\API\ServerCoreAPI.cs:line 126
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadItems>b__14_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 239

**Comment by WickedSchnitzel** [comment]
maybe there is such a randomizer in a modded ruin, just wanted to post in case its something else

**Comment by Craluminum2413** [comment]
Caused by Better Ruins mod
