### ISSUE TITLE
Schematic Problems

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#4785]
### Game Version

1.20.0-rc.6

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Problems with schematics spawning in the world.

1. There should be an option to prevent schematics from spawning within water bodies. 
2. Wild vines sometimes not attaching to the wall correctly (see screenshot).
3. Some modded blocks not rotating with the schematic (see screenshot).

### Screenshots

![Vintagestory Screenshot 2024 12 24 - 20 26 41 36](https://github.com/user-attachments/assets/6f8d7fed-b62d-44db-acef-7181a17cba0f)
![Vintagestory Screenshot 2024 12 24 - 20 25 45 90](https://github.com/user-attachments/assets/5f40bd47-1906-4783-bf89-063000e75602)
![Vintagestory Screenshot 2024 12 24 - 20 25 58 26](https://github.com/user-attachments/assets/28c5a8bd-6228-4d96-b9ed-4753c77401cf)
![Vintagestory Screenshot 2024 12 24 - 20 32 52 67](https://github.com/user-attachments/assets/01d993a2-54b6-4c00-8df9-d034732ef8ed)
![Vintagestory Screenshot 2024 12 24 - 13 31 45 59](https://github.com/user-attachments/assets/b5a9d442-e51a-4345-85aa-139704934e2c)

### Logs

```Crash```

**Comment by WickedSchnitzel** [comment]
![Vintagestory Screenshot 2024 12 24 - 20 38 25 70](https://github.com/user-attachments/assets/844a69bb-9541-446d-a22d-0d1973062efb)

**Comment by radfast** [comment]
(3) is a mod issue I think.   Please report (3) to the author of the relevant mod whose blocks are not rotating.

Issue (1): vanilla ruins are capable of being spawned in shallow water, because we think it looks pretty.   Essentially the mod making the ruins in your screenshot (which?) probably wants us to add an option "never in water".  But I'd say that as more in the way of an API Feature Request, not a bug

Issue (2) the wild vines I will look at

**Comment by WickedSchnitzel** [comment]
> (3) is a mod issue I think. Please report (3) to the author of the relevant mod whose blocks are not rotating.
> 
> Issue (1): vanilla ruins are capable of being spawned in shallow water, because we think it looks pretty. Essentially the mod making the ruins in your screenshot (which?) probably wants us to add an option "never in water". But I'd say that as more in the way of an API Feature Request, not a bug
> 
> Issue (2) the wild vines I will look at

can you give a hint what code to add, so that these will rotate correctly? the author says he does not know what to change.

**Comment by radfast** [comment]
> can you give a hint what code to add, so that these will rotate correctly? the author says he does not know what to change.

Example:  https://github.com/anegostudios/vssurvivalmod/blob/master/Block/BlockFence.cs#L172

There can also be similar examples in behaviors or BlockEntity, it depends how he implemented his modded block. Look at the code of similar blocks in the published source code for VS Survival Mod, it's there for this reason.

**Comment by WickedSchnitzel** [comment]
![Vintagestory Screenshot 2024 12 25 - 17 43 12 35](https://github.com/user-attachments/assets/3b3e87f6-2f2d-40b3-8b15-ee6ba2bb096a)

Custom schematics very often spawning close together.

**Comment by WickedSchnitzel** [comment]
Tried to paste in a schematic and got

[Error] Exception: Object reference not set to an instance of an object.
   at BetterCratesNamespace.BetterCrateBlockEntity.Initialize(ICoreAPI api) in D:\vsmods new\BetterCrates\src\BetterCrateBlockEntity.cs:line 80
   at Vintagestory.Common.BlockAccessorBase.SpawnBlockEntity(String classname, BlockPos position, ItemStack byItemStack) in VintagestoryLib\Common\API\BlockAccessorBase.cs:line 627
   at Vintagestory.API.Common.Block.OnBlockPlaced(IWorldAccessor world, BlockPos blockPos, ItemStack byItemStack) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 1333
   at Vintagestory.Common.BlockAccessorMovable.SetSolidBlock(Int32 blockId, BlockPos pos, IWorldChunk chunk, ItemStack byItemstack) in VintagestoryLib\Common\API\BlockAccessorMovable.cs:line 266
   at Vintagestory.Common.BlockAccessorMovable.SetBlock(Int32 blockId, BlockPos pos, Int32 layer) in VintagestoryLib\Common\API\BlockAccessorMovable.cs:line 451
   at Vintagestory.API.Common.BlockSchematic.PlaceReplaceAll(IBlockAccessor blockAccessor, BlockPos pos, Block newBlock, Boolean replaceMeta) in VintagestoryApi\Common\Collectible\Block\BlockSchematic.cs:line 1401
   at Vintagestory.API.Common.BlockSchematic.Place(IBlockAccessor blockAccessor, IWorldAccessor worldForCollectibleResolve, BlockPos startPos, EnumReplaceMode mode, Boolean replaceMetaBlocks) in VintagestoryApi\Common\Collectible\Block\BlockSchematic.cs:line 607
   at Vintagestory.API.Common.BlockSchematic.PasteToMiniDimension(ICoreServerAPI sapi, IBlockAccessor blockAccess, IMiniDimension miniDimension, BlockPos originPos, Boolean replaceMetaBlocks) in VintagestoryApi\Common\Collectible\Block\BlockSchematic.cs:line 1476
   at Vintagestory.ServerMods.WorldEdit.WorldEditWorkspace.CreateDimensionFromSchematic(BlockSchematic blockData, BlockPos startPos, EnumOrigin origin) in VSCreativeMod\Workspace.cs:line 907
   at Vintagestory.ServerMods.WorldEdit.WorldEditWorkspace.CreatePreview(BlockSchematic schematic, BlockPos origin) in VSCreativeMod\Workspace.cs:line 874
   at Vintagestory.ServerMods.WorldEdit.ImportTool.OnWorldEditCommand(WorldEdit worldEdit, TextCommandCallingArgs callerArgs) in VSCreativeMod\Tool\ImportTool.cs:line 171
   at Vintagestory.ServerMods.WorldEdit.WorldEdit.onToolCommand(TextCommandCallingArgs args) in VSCreativeMod\WorldEditCommands.cs:line 594
   at Vintagestory.Common.ChatCommandImpl.CallHandler(TextCommandCallingArgs callargs, Action`1 onCommandComplete, Dictionary`2 asyncParseResults) in VintagestoryLib\Common\API\Command\ChatCommandImpl.cs:line 245
   at Vintagestory.Common.ChatCommandApi.Execute(String commandName, IServerPlayer player, Int32 groupId, String args, Action`1 onCommandComplete) in VintagestoryLib\Common\API\Command\ChatCommandApi.cs:line 181

**Comment by WickedSchnitzel** [comment]
Its the "better crates" mod, but it should paste it nonetheless and just remove these blocks.

**Comment by WickedSchnitzel** [comment]
> (3) is a mod issue I think. Please report (3) to the author of the relevant mod whose blocks are not rotating.
> 
> Issue (1): vanilla ruins are capable of being spawned in shallow water, because we think it looks pretty. Essentially the mod making the ruins in your screenshot (which?) probably wants us to add an option "never in water". But I'd say that as more in the way of an API Feature Request, not a bug
> 
> Issue (2) the wild vines I will look at

https://github.com/anegostudios/VintageStory-Issues/issues/4785#issuecomment-2561367306

The gate is vanilla, isn't it? Opening in the wrong directions. Like mirrored.

**Comment by radfast** [comment]
After further investigation, these all appear to be Third Party issues - mods or whoever made these builds shown.

1. This is an API feature request (a ruin placement position which cannot be in water at all). Such feature requests do not belong on Github. The relevant modder can ask tyron for the feature if they can make a good case for it, or code it themselves.

2.  Vines on schematics are working correctly in vanilla in the tests I've just carried out. Place correctly on walls, and can be rotated in all 4 orientations without issue.  If you believe there is an issue in the game engine (not the mod), please provide precise steps to reproduce, specifying the wall blocks (ideally use Ctrl+F3 or Dev Debug mode to show the precise block code) and orientation and exact steps taken to reproduce the issue - or upload the schematic which is bugged.

3.  This is a request for API help for a third party modder. I have shown you an example of relevant code.

4.  The exception reported is clearly an exception in Better Crates mod.  The purpose of exceptions is to inform the modder they need to fix their code and show them where.  Please report it to them.  You can disable the mod until this is fixed.

**Comment by WickedSchnitzel** [comment]
> After further investigation, these all appear to be Third Party issues - mods or whoever made these builds shown.
> 
>     1. This is an API feature request (a ruin placement position which cannot be in water at all). Such feature requests do not belong on Github. The relevant modder can ask tyron for the feature if they can make a good case for it, or code it themselves.
> 
>     2. Vines on schematics are working correctly in vanilla in the tests I've just carried out. Place correctly on walls, and can be rotated in all 4 orientations without issue.  If you believe there is an issue in the game engine (not the mod), please provide precise steps to reproduce, specifying the wall blocks (ideally use Ctrl+F3 or Dev Debug mode to show the precise block code) and orientation and exact steps taken to reproduce the issue - or upload the schematic which is bugged.
> 
>     3. This is a request for API help for a third party modder. I have shown you an example of relevant code.
> 
>     4. The exception reported is clearly an exception in Better Crates mod.  The purpose of exceptions is to inform the modder they need to fix their code and show them where.  Please report it to them.  If it's a problem for your server, you can disable the mod until this is fixed.

2. I have attached the schematic with the vines and false orientation. Note that it uses mod blocks which are using the furniture library mod (https://mods.vintagestory.at/show/mod/4964). It may be a mod problem, but i haven't had that problem before 1.20 and the vines are un-modded. I believe so at least.

4. What i am asking for is some sort of dialogue to let the game delete/ replace the broken block. Its not the first time that a schematic can't be either rotated or placed at all because some block is broken. This may be a request that needs to go to the Discord as well, idk.
