### ISSUE TITLE
BlockEntityCharcoalPit.OnServerTick

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#4788]
### Game Version

1.20.0-rc.6

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Console error, no clue of the cause

### Logs

25.12.2024 07:52:06 [Server Error] At position 132002, 143, 158078 for block charcoalpit a BlockEntityCharcoalPit threw an error when ticked:
25.12.2024 07:52:06 [Server Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityCharcoalPit.OnServerTick(Single dt) in VSSurvivalMod\BlockEntity\BECharcoalPit.cs:line 95
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27

**Comment by pizza2004** [comment]
Fixed in next release.
