### ISSUE TITLE
Failed registering item game:stackrandomizer-armor:

### ISSUE THREAD

**Issue by morggin** [anegostudios/VintageStory-Issues#4791]
### Game Version

v1.20.0-rc.6 (Unstable)

### Platform

Linux

### Modded

Modded

### SP/MP

Multiplayer

### Description

[Error] Failed registering item game:stackrandomizer-armor:
25.12.2024 01:06:25 [Error] Exception: Attempted to register Item with code game:stackrandomizer-armor, but an item with such code already exists. Must use a unique code
   at Vintagestory.Server.ServerMain.RegisterItem(Item item) in VintagestoryLib\Server\ServerMain.cs:line 1762
   at Vintagestory.Server.ServerCoreAPI.RegisterItem(Item item) in VintagestoryLib\Server\API\ServerCoreAPI.cs:line 126
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadItems>b__14_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 239

### Logs

```Crash```

**Comment by morggin** [comment]
[server-main.log](https://github.com/user-attachments/files/18244933/server-main.log)

**Comment by Craluminum2413** [comment]
Caused by Better Ruins mod

**Comment by morggin** [comment]
per closed issue #4784 this appears to me caused by Better Ruins mod

**Comment by Craluminum2413** [comment]
Oh wait

**Comment by Craluminum2413** [comment]
Yes, I was right, it is caused by mod, since it adds the same item
