### ISSUE TITLE
Invisible Items and strange mist

### ISSUE THREAD

**Issue by teffan69** [anegostudios/VintageStory-Issues#4792]
### Game Version

1.2 rev6

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Items get invisible during pit kiln. Same without mods. Got some crashes during kiln this invis items too. And i found some caves, where placed torches dont light the area, but the area has or deep black areas or some with mist areas. Only possibility to see something is to hold a torch in my hand. Same mist i have sometimes in the surface. And the change from day to night or from good weather to bad, sometime skip from on sec to anonther. Feels off :)

### Logs

```Crash```

**Comment by Craluminum2413** [comment]
Send all logs from `\AppData\Roaming\VintagestoryData\Logs`

**Comment by teffan69** [comment]
[client-audit.log](https://github.com/user-attachments/files/18245045/client-audit.log)
[client-chat.log](https://github.com/user-attachments/files/18245046/client-chat.log)
[client-crash.log](https://github.com/user-attachments/files/18245047/client-crash.log)
[client-debug.log](https://github.com/user-attachments/files/18245048/client-debug.log)
[client-main.log](https://github.com/user-attachments/files/18245049/client-main.log)
[server-audit.log](https://github.com/user-attachments/files/18245050/server-audit.log)
[server-build.log](https://github.com/user-attachments/files/18245051/server-build.log)
[server-chat.log](https://github.com/user-attachments/files/18245053/server-chat.log)
[server-debug.log](https://github.com/user-attachments/files/18245054/server-debug.log)
[server-main.log](https://github.com/user-attachments/files/18245055/server-main.log)
[server-worldgen.log](https://github.com/user-attachments/files/18245056/server-worldgen.log)

**Comment by Craluminum2413** [comment]
I see a lot of errors like this in client-main.log
```
25.12.2024 10:20:23 [Error] Exception thrown during OnTesselation() of block entity Vintagestory.GameContent.BlockEntityGroundStorage@512006/54/511682. Block will probably not be rendered as intended.
25.12.2024 10:20:23 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.JsonTesselator.AddJsonModelDataToMesh(MeshData sourceMesh, Int32 lodlevel, TCTCache vars, IMeshPoolSupplier poolSupplier, Single[] tfMatrix) in VintagestoryLib\Client\Render\Tesselation\ChunkTesselator\JsonTesselator.cs:line 266
   at Vintagestory.GameContent.BlockEntityGroundStorage.OnTesselation(ITerrainMeshPool meshdata, ITesselatorAPI tesselator) in VSSurvivalMod\BlockEntity\BEGroundStorage.cs:line 1231
   at Vintagestory.Client.NoObf.JsonTesselator.Tesselate(TCTCache vars) in VintagestoryLib\Client\Render\Tesselation\ChunkTesselator\JsonTesselator.cs:line 162
```

**Comment by Craluminum2413** [comment]
I think it is caused by some mods, so you need to remove all mods and try to reproduce the issue in new world

**Comment by radfast** [comment]
There's also an issue in the German translation - I've already fixed it myself on CrowdIn, but that hasn't been pulled into the game release build yet.  @teffan69 you can fix it yourself, in your game installation folder find file `/assets/game/lang/de.json` .  In a decent text editor, go to line 8763 and edit the final `{3}` to `{2}`, like this:

	"shield-stats": "<strong>Aktive Nutzung<\/strong>\nBlockchance: {0}%\nSchadensabsorption: {2} LP\n<strong>Passive Nutzung<\/strong>\nBlockchance: {1}%\nSchadensabsorption: {2} LP",

**Comment by radfast** [comment]
> I see a lot of errors like this in client-main.log
> 
> ```
> 25.12.2024 10:20:23 [Error] Exception thrown during OnTesselation() of block entity Vintagestory.GameContent.BlockEntityGroundStorage@512006/54/511682. Block will probably not be rendered as intended.
> 25.12.2024 10:20:23 [Error] Exception: Object reference not set to an instance of an object.
>    at Vintagestory.Client.NoObf.JsonTesselator.AddJsonModelDataToMesh(MeshData sourceMesh, Int32 lodlevel, TCTCache vars, IMeshPoolSupplier poolSupplier, Single[] tfMatrix) in VintagestoryLib\Client\Render\Tesselation\ChunkTesselator\JsonTesselator.cs:line 266
>    at Vintagestory.GameContent.BlockEntityGroundStorage.OnTesselation(ITerrainMeshPool meshdata, ITesselatorAPI tesselator) in VSSurvivalMod\BlockEntity\BEGroundStorage.cs:line 1231
>    at Vintagestory.Client.NoObf.JsonTesselator.Tesselate(TCTCache vars) in VintagestoryLib\Client\Render\Tesselation\ChunkTesselator\JsonTesselator.cs:line 162
> ```

Lots of these errors in log, from many blocks (tapestries, barrels, many others) whose shape is given by their BlockEntity.

Looking at the (vanilla) code, it looks fine.  In agreement with @Craluminum2413, it looks like one of the mods may have changed our code here in a breaking way.   Strongly recommend these steps:

1.  Make a test world (it can be Creative), place in it some barrels, tapestries, doors, chests, trunks and (clutter) bookshelves - these are probably all the "invisible" blocks
2.  Do the following cycle a few times until these blocks are visible:  (a) logout, (b) disable half your remaining mods, keeping a note of which ones you just disabled; (c) rejoin the game
3.  Once they are visible, you know one of the mods you just disabled is the cause - so now re-enable half of those ones (you kept a note at 2(b), right?) and so forth until you can figure out which specific mod is the cause.

**Comment by teffan69** [comment]
Ok, thx :D

**Comment by wwwDayDream** [comment]
I've pinned this issue to something in Primitive Survival through tedious trial and error. May update if I figure out what's wrong with Primitive Survival that's causing this error across many other mods' blocks & items.

**Comment by wwwDayDream** [comment]
### Update - Found A Fix
The developer of the mod Primitive Survival mentions in several places throughout their comments that people experiencing texture/invisible block issues should use a mod that "Temporarily increase the texture atlas size and max # of animated elements."

Adding a mod that does this, like [Bigger Textured Atlas](https://mods.vintagestory.at/autoatlas) solves the issue. I've confirmed the bug with `Butchering 1.8.1` (the animals on the skinning hook don't render correctly if the error is happening) & `Primitive Survival 3.7.5`.

- Removing Primitive Survival fixes the error (and shows the animal on the hook)
- Keeping Primitive Survival and Adding Bigger Textured Atlas fixes the error (and shows the animal on the hook)
- Also fixes similar errors in other mods (such as ACulinaryArtillery) & vanilla game objects

### Fix Found... Not the Problem
Though this fixes the issue and maybe gives a game developer more hints about what the issue is... I'm still dumbfounded as to why this problem exists and frankly I think Primitive Survival developer is just as clueless about why, might be nice if anyone has any idea to post here but the problem is sort-of solved.

[💬](https://mods.vintagestory.at/primitivesurvival#cmt-42396) SpearAndFangAuthor, Dec 8th 2024 at 7:59 AM
Fasrin
It looks like a common issue with the vanilla texture atlas (when using mods)
This mod will likely fix you right up
https://mods.vintagestory.at/autoatlas

**Comment by wwwDayDream** [comment]
> > I see a lot of errors like this in client-main.log
> > ```
> > 25.12.2024 10:20:23 [Error] Exception thrown during OnTesselation() of block entity Vintagestory.GameContent.BlockEntityGroundStorage@512006/54/511682. Block will probably not be rendered as intended.
> > 25.12.2024 10:20:23 [Error] Exception: Object reference not set to an instance of an object.
> >    at Vintagestory.Client.NoObf.JsonTesselator.AddJsonModelDataToMesh(MeshData sourceMesh, Int32 lodlevel, TCTCache vars, IMeshPoolSupplier poolSupplier, Single[] tfMatrix) in VintagestoryLib\Client\Render\Tesselation\ChunkTesselator\JsonTesselator.cs:line 266
> >    at Vintagestory.GameContent.BlockEntityGroundStorage.OnTesselation(ITerrainMeshPool meshdata, ITesselatorAPI tesselator) in VSSurvivalMod\BlockEntity\BEGroundStorage.cs:line 1231
> >    at Vintagestory.Client.NoObf.JsonTesselator.Tesselate(TCTCache vars) in VintagestoryLib\Client\Render\Tesselation\ChunkTesselator\JsonTesselator.cs:line 162
> > ```
> 
> Lots of these errors in log, from many blocks (tapestries, barrels, many others) whose shape is given by their BlockEntity.
> 
> Looking at the (vanilla) code, it looks fine. In agreement with [@Craluminum2413](https://github.com/Craluminum2413), it looks like one of the mods may have changed our code here in a breaking way. Strongly recommend these steps:
> 
> 1. Make a test world (it can be Creative), place in it some barrels, tapestries, doors, chests, trunks and (clutter) bookshelves - these are probably all the "invisible" blocks
> 2. Do the following cycle a few times until these blocks are visible:  (a) logout, (b) disable half your remaining mods, keeping a note of which ones you just disabled; (c) rejoin the game
> 3. Once they are visible, you know one of the mods you just disabled is the cause - so now re-enable half of those ones (you kept a note at 2(b), right?) and so forth until you can figure out which specific mod is the cause.

Also thanks for this @radfast, I googled my error "Exception thrown during OnTesselation()" and that's how I finally stumbled on this, which cross referenced with my servers' mod list gave me the hints I needed to lock it down. Thanks to everyone here and @teffan69 as well for reporting this issue!
