### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ad1045nnn** [anegostudios/VintageStory-Issues#4793]
### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Running on 64 bit Windows with 4007 MB RAM
Game Version: v1.18.8 (Stable)
25/12/2024 10:39:51: Critical error occurred
Loaded Mods: 
System.TypeInitializationException: The type initializer for 'OpenTK.Windowing.Desktop.Monitors' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'glfw' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.LoadLibrary(String libraryName, Version version, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.<>c.<.cctor>b__3_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwInit()
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.Init()
   at OpenTK.Windowing.Desktop.GLFWProvider.EnsureInitialized()
   at OpenTK.Windowing.Desktop.Monitors..cctor()
   --- End of inner exception stack trace ---
   at OpenTK.Windowing.Desktop.Monitors.GetPrimaryMonitor()
   at VSPlatform.XPlatImpl.GetScreenSize()
   at Vintagestory.Client.NoObf.ClientPlatformWindows..ctor(Logger logger)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
System.DllNotFoundException: Unable to load DLL 'glfw' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.LoadLibrary(String libraryName, Version version, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.<>c.<.cctor>b__3_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwInit()
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.Init()
   at OpenTK.Windowing.Desktop.GLFWProvider.EnsureInitialized()
   at OpenTK.Windowing.Desktop.Monitors..cctor()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 25/12/2024 10:31:26, Site = , Source = .NET Runtime, Message = Description: A .NET application failed.
Application: Vintagestory.exe
Path: C:\Users\HP\Desktop\Vintage Story - (Www.ARealGamer.Org)\Game\Vintagestory.exe
Message: You must install .NET to run this application.

App: C:\Users\HP\Desktop\Vintage Story - (Www.ARealGamer.Org)\Game\Vintagestory.exe
Architecture: x64
App host version: 7.0.9
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=7.0.9

 }
--------------
{ TimeGenerated = 25/12/2024 10:26:32, Site = , Source = .NET Runtime, Message = Description: A .NET application failed.
Application: Vintagestory.exe
Path: C:\Users\HP\Desktop\Vintage Story - (Www.ARealGamer.Org)\Game\Vintagestory.exe
Message: You must install .NET to run this application.

App: C:\Users\HP\Desktop\Vintage Story - (Www.ARealGamer.Org)\Game\Vintagestory.exe
Architecture: x64
App host version: 7.0.9
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=7.0.9

 }
--------------
{ TimeGenerated = 25/12/2024 10:25:19, Site = , Source = .NET Runtime, Message = Description: A .NET application failed.
Application: Vintagestory.exe
Path: C:\Users\HP\Desktop\Vintage Story - (Www.ARealGamer.Org)\Game\Vintagestory.exe
Message: You must install .NET to run this application.

App: C:\Users\HP\Desktop\Vintage Story - (Www.ARealGamer.Org)\Game\Vintagestory.exe
Architecture: x64
App host version: 7.0.9
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=7.0.9

 

### How to reproduce

Running on 64 bit Windows with 4007 MB RAM
Game Version: v1.18.8 (Stable)
25/12/2024 10:39:51: Critical error occurred
Loaded Mods: 
System.TypeInitializationException: The type initializer for 'OpenTK.Windowing.Desktop.Monitors' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'glfw' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.LoadLibrary(String libraryName, Version version, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.<>c.<.cctor>b__3_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwInit()
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.Init()
   at OpenTK.Windowing.Desktop.GLFWProvider.EnsureInitialized()
   at OpenTK.Windowing.Desktop.Monitors..cctor()
   --- End of inner exception stack trace ---
   at OpenTK.Windowing.Desktop.Monitors.GetPrimaryMonitor()
   at VSPlatform.XPlatImpl.GetScreenSize()
   at Vintagestory.Client.NoObf.ClientPlatformWindows..ctor(Logger logger)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
System.DllNotFoundException: Unable to load DLL 'glfw' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.LoadLibrary(String libraryName, Version version, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.<>c.<.cctor>b__3_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwInit()
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.Init()
   at OpenTK.Windowing.Desktop.GLFWProvider.EnsureInitialized()
   at OpenTK.Windowing.Desktop.Monitors..cctor()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 25/12/2024 10:31:26, Site = , Source = .NET Runtime, Message = Description: A .NET application failed.
Application: Vintagestory.exe
Path: C:\Users\HP\Desktop\Vintage Story - (Www.ARealGamer.Org)\Game\Vintagestory.exe
Message: You must install .NET to run this application.

App: C:\Users\HP\Desktop\Vintage Story - (Www.ARealGamer.Org)\Game\Vintagestory.exe
Architecture: x64
App host version: 7.0.9
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=7.0.9

 }
--------------
{ TimeGenerated = 25/12/2024 10:26:32, Site = , Source = .NET Runtime, Message = Description: A .NET application failed.
Application: Vintagestory.exe
Path: C:\Users\HP\Desktop\Vintage Story - (Www.ARealGamer.Org)\Game\Vintagestory.exe
Message: You must install .NET to run this application.

App: C:\Users\HP\Desktop\Vintage Story - (Www.ARealGamer.Org)\Game\Vintagestory.exe
Architecture: x64
App host version: 7.0.9
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=7.0.9

 }
--------------
{ TimeGenerated = 25/12/2024 10:25:19, Site = , Source = .NET Runtime, Message = Description: A .NET application failed.
Application: Vintagestory.exe
Path: C:\Users\HP\Desktop\Vintage Story - (Www.ARealGamer.Org)\Game\Vintagestory.exe
Message: You must install .NET to run this application.

App: C:\Users\HP\Desktop\Vintage Story - (Www.ARealGamer.Org)\Game\Vintagestory.exe
Architecture: x64
App host version: 7.0.9
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=7.0.9

 

### Logs

```Crash```Running on 64 bit Windows with 4007 MB RAM
Game Version: v1.18.8 (Stable)
25/12/2024 10:39:51: Critical error occurred
Loaded Mods: 
System.TypeInitializationException: The type initializer for 'OpenTK.Windowing.Desktop.Monitors' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'glfw' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.LoadLibrary(String libraryName, Version version, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.<>c.<.cctor>b__3_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwInit()
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.Init()
   at OpenTK.Windowing.Desktop.GLFWProvider.EnsureInitialized()
   at OpenTK.Windowing.Desktop.Monitors..cctor()
   --- End of inner exception stack trace ---
   at OpenTK.Windowing.Desktop.Monitors.GetPrimaryMonitor()
   at VSPlatform.XPlatImpl.GetScreenSize()
   at Vintagestory.Client.NoObf.ClientPlatformWindows..ctor(Logger logger)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
System.DllNotFoundException: Unable to load DLL 'glfw' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.LoadLibrary(String libraryName, Version version, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.<>c.<.cctor>b__3_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwInit()
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.Init()
   at OpenTK.Windowing.Desktop.GLFWProvider.EnsureInitialized()
   at OpenTK.Windowing.Desktop.Monitors..cctor()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 25/12/2024 10:31:26, Site = , Source = .NET Runtime, Message = Description: A .NET application failed.
Application: Vintagestory.exe
Path: C:\Users\HP\Desktop\Vintage Story - (Www.ARealGamer.Org)\Game\Vintagestory.exe
Message: You must install .NET to run this application.

App: C:\Users\HP\Desktop\Vintage Story - (Www.ARealGamer.Org)\Game\Vintagestory.exe
Architecture: x64
App host version: 7.0.9
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=7.0.9

 }
--------------
{ TimeGenerated = 25/12/2024 10:26:32, Site = , Source = .NET Runtime, Message = Description: A .NET application failed.
Application: Vintagestory.exe
Path: C:\Users\HP\Desktop\Vintage Story - (Www.ARealGamer.Org)\Game\Vintagestory.exe
Message: You must install .NET to run this application.

App: C:\Users\HP\Desktop\Vintage Story - (Www.ARealGamer.Org)\Game\Vintagestory.exe
Architecture: x64
App host version: 7.0.9
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=7.0.9

 }
--------------
{ TimeGenerated = 25/12/2024 10:25:19, Site = , Source = .NET Runtime, Message = Description: A .NET application failed.
Application: Vintagestory.exe
Path: C:\Users\HP\Desktop\Vintage Story - (Www.ARealGamer.Org)\Game\Vintagestory.exe
Message: You must install .NET to run this application.

App: C:\Users\HP\Desktop\Vintage Story - (Www.ARealGamer.Org)\Game\Vintagestory.exe
Architecture: x64
App host version: 7.0.9
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=7.0.9

**Comment by Craluminum2413** [comment]
Update to latest stable, also try reinstall/update/downgrade your graphics drivers

**Comment by radfast** [comment]
@ad1045nnn this appears to be an unofficial version of the game.

Go to https://www.vintagestory.at/, create an account and download from there, and you should have no problems
