### ISSUE TITLE
NoObf.NetworkAPI.SendPlayerPositionPacket() error on server restart

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#4796]
### Game Version

1.20.0-rc.6

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Logs
```
Running on 64 bit Windows 10.0.19045.0 with 32723 MB RAM
Game Version: v1.20.0-rc.6 (Unstable)
25.12.2024 16:13:22: Critical error occurred
Loaded Mods: ancientarmory@1.0.6, bettercrates@1.8.0-rc.4, canoemod@1.0.2, chiseltools@1.14.4, decor@1.2.0, extrachests@1.8.0, fantasycreatures@0.7.1, fixedpaths@1.0.1, pantherinae@1.1.14, foundrymod@1.0.0, moreicons_cs@1.1.0, primitivesurvival@3.7.4, nvscaffolding@1.0.1, translocatorengineeringredux@1.5.4, game@1.20.0-rc.6, weaponpackalphaunoff@1.5.1, animalcages@3.0.3, apegrapes@1.1.3, betterruins@0.4.2, butterflycases@1.0.1, carryon@1.8.0-pre.1, commonlib@2.6.1, decayingcreatures@0.1.1, fairplayguardian@1.1.7, furniturelibrary@1.0.14, gourmand@1.2.7, heatretention@1.0.2, playerlist@2.1.5, rifteye@0.4.0, simplefootstepsredux@1.0.1, sleepvote@1.0.7, tentbag@2.2.0, th3dungeon@0.3.1, thecritterpack@0.9.1, vanity@2.2.1, vinconomy@0.4.0-rc.4, creative@1.20.0-rc.6, vsquest@1.2.0, vsserverpanel@0.1.5, survival@1.20.0-rc.6, wildgrass@1.1.3, xlibpatch@1.0.1, youvegotmail@1.0.8, cob2@1.6.9, cobserver@1.0.3, em@3.0.0-pre.3, outerspacetunesvolume1@1.0.2, outerspacetunesvolume2@1.0.2, playercorpse@1.11.0, stonequarry@3.4.2, xskillspatch@1.0.4, cob@2.0.0, outerspacetunesmaster@1.0.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.NetworkAPI.SendPlayerPositionPacket() in VintagestoryLib\Client\API\NetworkAPI.cs:line 256
   at Vintagestory.GameContent.EntityBehaviorPlayerPhysics.OnRenderFrame(Single dt, EnumRenderStage stage) in VSEssentials\Entity\Behavior\BehaviorPlayerPhysics.cs:line 404
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 188
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 825
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 161
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10.11.2024 17:19:55, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.20.0.0, Zeitstempel: 0x66470000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x54f0
Startzeit der fehlerhaften Anwendung: 0x01db338c37998c05
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: bd0722d8-f2e3-4919-b9d2-22bd3b03b432
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 07.11.2024 21:48:24, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.20.0.0, Zeitstempel: 0x66470000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x6ab8
Startzeit der fehlerhaften Anwendung: 0x01db315643baa536
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 30893ec8-ce92-4c18-812d-9d94a10b2d19
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 07.11.2024 14:09:10, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.20.0.0, Zeitstempel: 0x66470000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x1228
Startzeit der fehlerhaften Anwendung: 0x01db311615ac4736
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: a8fe137c-4ea9-4b8c-9b6d-79a84f2bfad4
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
```

**Comment by Th3Dilli** [comment]
When does this happen? 
when you are still on the server and it shuts down and is supposed to kick you?
and how often does it happen? always/sometimes?

yet i was not able to reproduce

**Comment by DanceWithDarknes** [comment]
Hi! 
I play Vintage Story with a friend on mp through hamachi. The game worked for us on the first day without dropping that we played for 10h continuously and there was no problem. The next day as we wanted to continue the adventure it started throwing me a critical error after about 2 hours. We took a break and returned to the game today. And the error continues to recur. I play for 10s to 2 minutes and get a crash. 
![Zrzut ekranu 2025-01-06 185525](https://github.com/user-attachments/assets/01fa8a63-a501-496c-9c88-207a087ec2ab)

**Comment by FloGui76** [comment]
Hi,

I have the same issue with a friend. We tried all the 1.20s, same everywhere. Nevertheless, on public dedicated servers, we don't have the crashes—only some really small roll-backs. 
Hope it helps you

**Comment by Th3Dilli** [comment]
[VintagestoryLib.zip](https://github.com/user-attachments/files/18358710/VintagestoryLib.zip)
anyone having this issue can please try replacing this two files in your vintagestory installation and see if that fixes it

**Comment by FloGui76** [comment]
Hi,
So we tried multiple things with my friend.
When he's hosting the server I still crash with this message :

"Running on 64 bit Windows 10.0.26100.0 with 16003 MB RAM
Game Version: v1.20.0-rc.8 (Unstable)
09/01/2025 12:28:22: Critical error occurred
Loaded Mods: game@1.20.0-rc.8, creative@1.20.0-rc.8, survival@1.20.0-rc.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.NetworkAPI.SendPlayerPositionPacket() in /home/dilli/drive_linux/git_repos/anego/game_1_20/VintagestoryLib/Client/API/NetworkAPI.cs:line 257
   at Vintagestory.GameContent.EntityBehaviorPlayerPhysics.OnRenderFrame(Single dt, EnumRenderStage stage) in VSEssentials\Entity\Behavior\BehaviorPlayerPhysics.cs:line 404
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in /home/dilli/drive_linux/git_repos/anego/game_1_20/VintagestoryLib/Client/Util/ClientEventManager.cs:line 188
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in /home/dilli/drive_linux/git_repos/anego/game_1_20/VintagestoryLib/Client/ClientMain.cs:line 825
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in /home/dilli/drive_linux/git_repos/anego/game_1_20/VintagestoryLib/Client/MainMenu/Screens/GuiScreenRunningGame.cs:line 161
   at Vintagestory.Client.ScreenManager.Render(Single dt) in /home/dilli/drive_linux/git_repos/anego/game_1_20/VintagestoryLib/Client/ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in /home/dilli/drive_linux/git_repos/anego/game_1_20/VintagestoryLib/Client/ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in /home/dilli/drive_linux/git_repos/anego/game_1_20/VintagestoryLib/Client/ClientPlatform/GameWindow.cs:line 92
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in /home/dilli/drive_linux/git_repos/anego/game_1_20/VintagestoryLib/Client/ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in /home/dilli/drive_linux/git_repos/anego/game_1_20/VintagestoryLib/Client/ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in /home/dilli/drive_linux/git_repos/anego/game_1_20/VintagestoryLib/Client/ClientPlatform/ClientNative/CrashReporter.cs:line 93
"

When i Host, two option :

- Connexion at my server by IP : crash 
- Connexion at my server by LocalHost : No crash for me, but crash for my friend with this message (with and without the fix): 

"
![image_2025-01-09_134020108](https://github.com/user-attachments/assets/65ef86e9-ea5b-4c1c-920a-86ed7efd2eee)

-

**Comment by Th3Dilli** [comment]
[VintagestoryLib.zip](https://github.com/user-attachments/files/18361777/VintagestoryLib.zip)
can you try again with those please

**Comment by FloGui76** [comment]
It seems to work, I don't crash anymore, But i get timed out by the server

**Comment by Th3Dilli** [comment]
fixed as of rc.9
