### ISSUE TITLE
GameContent.BlockSoil.OnServerGameTick error

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#4799]
### Game Version

1.20.0-rc.6

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

...

### Logs
```
[Error] Exception thrown in block.OnServerGameTick() for block code 'game:soil-low-none':
25.12.2024 15:52:23 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockSoil.OnServerGameTick(IWorldAccessor world, BlockPos pos, Object extra) in VSSurvivalMod\Block\BlockSoil.cs:line 87
   at Vintagestory.Server.ServerSystemBlockSimulation.OnServerTick(Single dt) in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 997
25.12.2024 15:52:23 [Error] Exception thrown in block.OnServerGameTick() for block code 'game:soil-low-none':
25.12.2024 15:52:23 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockSoil.OnServerGameTick(IWorldAccessor world, BlockPos pos, Object extra) in VSSurvivalMod\Block\BlockSoil.cs:line 87
   at Vintagestory.Server.ServerSystemBlockSimulation.OnServerTick(Single dt) in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 997
```

**Comment by radfast** [comment]
Likely a mod issue, @WickedSchnitzel.  I've never seen this reported in vanilla, and relevant code in BlockSoil has not changed recently.

**Comment by radfast** [comment]
I'm going to close this, feel free to post or re-open if it's occurring in an unmodded game
