### ISSUE TITLE
System.Collections.Generic.Dictionary`2.FindValue(TKey key) error

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#4805]
### Game Version

1.20.0-rc.6

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Logs

[Server Warning] Exception at client 16. Disconnecting client.
25.12.2024 22:56:04 [Server Notification] UDP: client disconnected Solowars
25.12.2024 22:56:04 [Server Error] Exception: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Vintagestory.API.Config.Lang.GetL(String langcode, String key, Object[] args) in VintagestoryApi\Localization\Lang.cs:line 153
   at Vintagestory.Server.ServerMain.HandleLeave(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\ServerGeneralPacketHandler.cs:line 419
   at Vintagestory.Server.ServerMain.HandleClientPacket(ConnectedClient client, Byte[] data) in VintagestoryLib\Server\ServerMainNetworking.cs:line 154
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\ServerMainNetworking.cs:line 147

**Comment by radfast** [comment]
@WickedSchnitzel anything about solowars/client16 in the log prior to this?  It appears that the player client did not provide the server with a language code in its joining packet, which should be impossible.

**Comment by radfast** [comment]
> @WickedSchnitzel anything about solowars/client16 in the log prior to this? It appears that the player client did not provide the server with a language code in its joining packet, which should be impossible.

Never mind.

This issue is fixed, we believe, from upcoming 1.20.0-rc.7
