### ISSUE TITLE
1.20rc6 Unable to cast object

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#4815]
### Game Version

1.20rc6

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Server log spaming error msgs..

### How to reproduce

idk

### Logs

[Error] Exception: Unable to cast object of type 'Vintagestory.GameContent.BlockSnowLayer' to type 'Vintagestory.GameContent.BlockCharcoalPile'.
   at Vintagestory.GameContent.BlockCharcoalPile.OnFallOnto(IWorldAccessor world, BlockPos pos, Block block, TreeAttribute blockEntityAttributes) in VSSurvivalMod\Block\BlockCharcoalPile.cs:line 11
   at Vintagestory.GameContent.EntityBlockFalling.OnFallToGround(Double motionY) in VSEssentials\Entity\EntityBlockFalling.cs:line 519
   at Vintagestory.API.Common.EntityBehaviorPassivePhysics.ApplyTests(EntityPos pos) in VintagestoryApi\Common\EntityBehavior\BehaviorPassivePhysics.cs:line 266
   at Vintagestory.API.Common.EntityBehaviorPassivePhysics.OnPhysicsTick(Single dt) in VintagestoryApi\Common\EntityBehavior\BehaviorPassivePhysics.cs:line 346
   at Vintagestory.Server.PhysicsManager.DoWork(Int32 threadNumber) in VintagestoryLib\Server\PhysicsManager.cs:line 583

**Comment by pizza2004** [comment]
Should be fixed in next release.
