### ISSUE TITLE
rc6 Crash in FindRoomForPosition

### ISSUE THREAD

**Issue by 46hawk** [anegostudios/VintageStory-Issues#4820]
### Game Version

v1.20.0-rc6

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Ran into a crash while digging dirt blocks. It seemed to happen right as the block was about to break, but that may have been coincidence. Playing on Wilderness survival, so maybe it was block gravity related? I lost no progress, and was able to load back in just fine as if I had saved and quit normally.

### How to reproduce

Not sure if it's a random thing or easily reproduced atm; just putting this out there as I don't see it already reported. IDK if it's the same as #4692, but the stack trace is different.

### Logs

```Running on 64 bit Windows 10.0.19045.0 with 32692 MB RAM
Game Version: v1.20.0-rc.6 (Unstable)
12/28/2024 10:34:03 AM: Critical error occurred
Loaded Mods: game@1.20.0-rc.6, prospecttogether@1.3.0, creative@1.20.0-rc.6, survival@1.20.0-rc.6
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.RoomRegistry.FindRoomForPosition(BlockPos pos, ChunkRooms otherRooms) in VSEssentials\Systems\RoomRegistry.cs:line 395
   at Vintagestory.GameContent.RoomRegistry.GetRoomForPosition(BlockPos pos) in VSEssentials\Systems\RoomRegistry.cs:line 379
   at Vintagestory.GameContent.EntityParticleInsect.playsound() in VSEssentials\Systems\ParticleEntity\EntityParticleInsect.cs:line 112
   at Vintagestory.GameContent.EntityParticleInsect.doSlowTick(ParticlePhysics physicsSim, Single dt) in VSEssentials\Systems\ParticleEntity\EntityParticleInsect.cs:line 39
   at Vintagestory.GameContent.EntityParticle.TickNow(Single dt, Single physicsdt, ICoreClientAPI api, ParticlePhysics physicsSim) in VSEssentials\Systems\ParticleEntity\EntityParticle.cs:line 27
   at Vintagestory.GameContent.EntityParticleSystem.OnNewFrameOffThread(Single dt, Vec3d cameraPos) in VSEssentials\Systems\ParticleEntity\EntityParticleSystem.cs:line 427
   at Vintagestory.GameContent.EntityParticleSystem.onThreadStart() in VSEssentials\Systems\ParticleEntity\EntityParticleSystem.cs:line 186
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)```

**Comment by The-M1k3y** [comment]
Just got the same error in Singleplayer. Vanilla on Arch Linux, installed via AUR.

```
Running on 64 bit Linux (Arch Linux) [Kernel 6.15.8.1] with 44037 MB RAM
Game Version: v1.20.12 (Stable)
08/09/2025 14:37:57: Critical error occurred
Loaded Mods: game@1.20.12, creative@1.20.12, survival@1.20.12
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.RoomRegistry.FindRoomForPosition(BlockPos pos, ChunkRooms otherRooms) in VSEssentials\Systems\RoomRegistry.cs:line 395
   at Vintagestory.GameContent.RoomRegistry.GetRoomForPosition(BlockPos pos) in VSEssentials\Systems\RoomRegistry.cs:line 379
   at Vintagestory.GameContent.EntityParticleInsect.playsound() in VSEssentials\Systems\ParticleEntity\EntityParticleInsect.cs:line 112
   at Vintagestory.GameContent.EntityParticleInsect.doSlowTick(ParticlePhysics physicsSim, Single dt) in VSEssentials\Systems\ParticleEntity\EntityParticleInsect.cs:line 39
   at Vintagestory.GameContent.EntityParticleSystem.OnNewFrameOffThread(Single dt, Vec3d cameraPos) in VSEssentials\Systems\ParticleEntity\EntityParticleSystem.cs:line 427
   at Vintagestory.GameContent.EntityParticleSystem.onThreadStart() in VSEssentials\Systems\ParticleEntity\EntityParticleSystem.cs:line 186
```

**Comment by radfast** [comment]
Fixed next release (1.21.0-rc.7).  Thank you all who have posted this issue - and sorry it took us a long time to fix it.
