### ISSUE TITLE
BlockEntityFruitPress.ToTreeAttributes(ITreeAttribute tree) error

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#4827]
### Game Version

1.20.0-rc.6

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

saw this in the console. dont know the cause.

### Logs

29.12.2024 15:37:00 [Server Error] Error thrown trying to serialize block entity Vintagestory.GameContent.BlockEntityFruitPress at 108173, 63, 162029, will not save, sorry!
29.12.2024 15:37:00 [Server Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityFruitPress.ToTreeAttributes(ITreeAttribute tree) in VSSurvivalMod\BlockEntity\BEFruitpress.cs:line 797
   at Vintagestory.Server.ServerChunk.BeforeSerialization() in VintagestoryLib\Server\Models\ServerChunk.cs:line 378

**Comment by WickedSchnitzel** [comment]
Mods, sorted by dependency: ancientarmory, bettercrates, canoemod, chiseltools, decor, extrachests, fixedpaths, pantherinae, foundrymod, moreicons_cs, primitivesurvival, nvscaffolding, translocatorengineeringredux, game, weaponpackalphaunoff, worldgenfixremix, fantasycreatures, animalcages, apegrapes, betterruins, butterflycases, carryon, commonlib, decayingcreatures, fairplayguardian, furniturelibrary, gourmand, heatretention, livemap, playerlist, rifteye, simpleemotemenu, simplefootstepsredux, sleepvote, tentbag, th3dungeon, vanity, vinconomy, creative, vsquest, vsserverpanel, survival, xlibpatch, youvegotmail, daynightcycles, loginprotection, thecritterpack, wildgrass, cob2, cobserver, em, outerspacetunesvolume1, outerspacetunesvolume2, playercorpse, stonequarry, xskillspatch, th3essentials, bunnybell119, cob, outerspacetunesmaster

**Comment by pizza2004** [comment]
Could you test this again on rc.8?

**Comment by pizza2004** [comment]
Are you still having an issue on the stable release?

**Comment by pizza2004** [comment]
I’m going to assume this was fixed and close this for the time being.  If you encounter the bug again feel free to reopen the issue.
