### ISSUE TITLE
crash happen when creating a campfire

### ISSUE THREAD

**Issue by NahuelDorin** [anegostudios/VintageStory-Issues#4829]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I was following the tutorial from the beginning, and when I got to the part about making a campfire, I placed the tinder and right-clicked with a log (the ones dropped when cutting a tree). The game immediately crashed.

### How to reproduce

Right-clicking with a log in hand on log.

### Logs

```Running on 64 bit Windows 10.0.19045.0 with 16336 MB RAM
Game Version: v1.19.8 (Stable)
29/12/2024 15:04:00: Critical error occurred
Loaded Mods: game@1.19.8, creative@1.19.8, survival@1.19.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.FirstStepsTutorial.<initTutorialSteps>b__1_14(BlockSelection blocksel) in VSSurvivalMod\Systems\Handbook\Tutorial\FirstStepsTutorial.cs:line 66
   at Vintagestory.GameContent.PlayerLookatBlockWatcher.OnBlockLookedAt(BlockSelection blockSel) in VSSurvivalMod\Systems\Handbook\Tutorial\PlayerReceiveItemWatcher.cs:line 17
   at Vintagestory.GameContent.TutorialStepLookatBlock.OnBlockLookedAt(BlockSelection currentBlockSelection) in VSSurvivalMod\Systems\Handbook\Tutorial\TutorialStepReceive.cs:line 35
   at Vintagestory.GameContent.TutorialBase.OnStateUpdate(ActionBoolReturn`1 stepCall) in VSSurvivalMod\Systems\Handbook\Tutorial\TutorialBase.cs:line 67
   at Vintagestory.GameContent.ModSystemTutorial.onStateUpdate(ActionBoolReturn`1 stepCall) in VSSurvivalMod\Systems\Handbook\Tutorial\ModSystemTutorial.cs:line 259
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Craluminum2413** [comment]
Does it happen in 1.20?

**Comment by radfast** [comment]
Hey @NahuelDorin - apologies that it crashed in the Tutorial, that's not good!   Are you able to re-join the game and continue?

It's possible the game will crash again if your player is still looking at that firepit which crashed it, I'm not sure without seeing your world.  What has happened here is placing the logs down very quickly (or some similar action) caused the firepit to be in a strange state.  I've actually never seen this before in close to 5 years working on VS.  I think that means it must happen very rarely, so I suggest let's not worry about it too much if you are able to continue the game.

**Comment by radfast** [comment]
In next upcoming build 1.20.0-rc.7 it now won't crash here, although if the firepit is borked (very rare, as I wrote above) it might be necessary to construct a second firepit to continue the tutorial.

[Details for coders: the firepit Block did not have a BlockEntityFirepit at the same position, for unknown reasons]
