### ISSUE TITLE
Attempt to harvest resin from a pine tree crashes MP client. 

### ISSUE THREAD

**Issue by morggin** [anegostudios/VintageStory-Issues#4834]
### Game Version

v1.20.0-rc.6 (Unstable)

### Platform

Linux

### Modded

Modded

### SP/MP

Multiplayer

### Description

[Error] Exception: Field not found: 'Vintagestory.GameContent.BlockBehaviorHarvestable.harvestedStack'.
   at berrybushfixes.BerryBushFixes.PatchHarvestable(BlockBehaviorHarvestable __instance, Single secondsUsed, IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel, EnumHandling& handled)
   at Vintagestory.GameContent.BlockBehaviorHarvestable.OnBlockInteractStop_Patch1(BlockBehaviorHarvestable this, Single secondsUsed, IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel, EnumHandling& handled)
   at Vintagestory.API.Common.Block.OnBlockInteractStop(Single secondsUsed, IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 1477
   at Vintagestory.Server.ServerSystemBlockSimulation.callOnUsingBlock(ServerPlayer player, Block block, BlockSelection blockSel, Single& secondsPassed, Boolean callStop) in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 533
   at Vintagestory.Server.ServerSystemBlockSimulation.HandleBlockInteract(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 429
   at Vintagestory.Server.ServerSystemInventory.HandleHandInteraction(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\Inventory.cs:line 255
   at Vintagestory.Server.ServerMain.HandleClientPacket(ConnectedClient client, Byte[] data) in VintagestoryLib\Server\ServerMainNetworking.cs:line 154
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\ServerMainNetworking.cs:line 147

### How to reproduce

Attempt to harvest resin from a pine tree crashes MP client. 
[server-main.log](https://github.com/user-attachments/files/18272603/server-main.log)

### Logs

```Crash```

**Comment by Craluminum2413** [comment]
Caused by berrybushfixes mod

**Comment by morggin** [comment]
thank you, looks like the mod is no longer needed anyway after 1.20.rc 4
