### ISSUE TITLE
Game Crash when trying to connect to a Server via IPv6

### ISSUE THREAD

**Issue by Aaron2550** [anegostudios/VintageStory-Issues#4837]
### Game Version

v1.20.0-rc6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Exactly what the Title says; Game crashes with a NullReferenceException when trying to connect to a Server via IPv6
I've censored the logs, the IPv6 is valid an the Windows Username is nothing special either: short, lowercase ascii letters only

### How to reproduce

- Start Game
- Add new Server with an IPv6
- Click connect in the Multiplayer menu
- See crash

### Logs

```
30.12.2024 17:35:32 [Notification] Client logger started.
30.12.2024 17:35:32 [Notification] Game Version: v1.20.0-rc.6 (Unstable)
30.12.2024 17:35:32 [Notification] Process path: F:\Games\Vintagestory\Vintagestory.exe
30.12.2024 17:35:32 [Notification] Operating System: Windows 10.0.19045.0
30.12.2024 17:35:32 [Notification] CPU Cores: 12
30.12.2024 17:35:32 [Notification] Available RAM: 32702 MB
30.12.2024 17:35:33 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
30.12.2024 17:35:33 [Notification] Graphics Card Vendor: NVIDIA Corporation
30.12.2024 17:35:33 [Notification] Graphics Card Version: 3.3.0 NVIDIA 566.03
30.12.2024 17:35:33 [Notification] Graphics Card Renderer: NVIDIA GeForce RTX 4060 Ti/PCIe/SSE2
30.12.2024 17:35:33 [Notification] Graphics Card ShadingLanguageVersion: 3.30 NVIDIA via Cg compiler
30.12.2024 17:35:33 [Notification] GL.MaxVertexUniformComponents: 4096
30.12.2024 17:35:33 [Notification] GL.MaxUniformBlockSize: 65536
30.12.2024 17:35:33 [Notification] C# Framework: .net 7.0.15
30.12.2024 17:35:33 [Notification] Cairo Graphics Version: 1.17.3
30.12.2024 17:35:33 [Notification] OpenAL Version: 1.1 ALSOFT 1.23.0
30.12.2024 17:35:33 [Notification] Zstd Version: 1.5.5
30.12.2024 17:35:33 [Notification] Start discovering assets
30.12.2024 17:35:33 [Notification] Found 28 base assets in category lang
30.12.2024 17:35:33 [Notification] Found 0 base assets in category patches
30.12.2024 17:35:33 [Notification] Found 24 base assets in category config
30.12.2024 17:35:33 [Notification] Found 0 base assets in category worldproperties
30.12.2024 17:35:33 [Notification] Found 49 base assets in category sounds
30.12.2024 17:35:33 [Notification] Found 95 base assets in category shapes
30.12.2024 17:35:33 [Notification] Found 80 base assets in category shaders
30.12.2024 17:35:33 [Notification] Found 18 base assets in category shaderincludes
30.12.2024 17:35:33 [Notification] Found 140 base assets in category textures
30.12.2024 17:35:33 [Notification] Found 4 base assets in category music
30.12.2024 17:35:33 [Notification] Found 0 base assets in category dialog
30.12.2024 17:35:33 [Notification] Found 438 base assets in total
30.12.2024 17:35:33 [Notification] Loading sounds
30.12.2024 17:35:33 [Notification] (Re-)loaded frame buffers
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass .
30.12.2024 17:35:33 [Notification] Sounds loaded
30.12.2024 17:35:33 [Notification] Begin loading shaders
30.12.2024 17:35:33 [Notification] Load shaders now
30.12.2024 17:35:33 [Notification] Loading shaders...
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass standard.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass particlescube.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass particlesquad.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass sky.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass nightsky.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass woittest.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass helditem.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass decals.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass final.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass gui.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass blur.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass findbright.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass godrays.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass autocamera.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass wireframe.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass entityanimated.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass luma.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass blit.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass texture2texture.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass celestialobject.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass colorgrade.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass guigear.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass ssao.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
30.12.2024 17:35:33 [Notification] Loaded Shaderprogramm for render pass chunkliquiddepth.
30.12.2024 17:35:33 [Notification] Cached session key is valid, validating with server
30.12.2024 17:35:34 [Notification] Server validation response: Good
30.12.2024 17:35:34 [Notification] Will search the following paths for mods:
30.12.2024 17:35:34 [Notification]     F:\Games\Vintagestory\Mods
30.12.2024 17:35:34 [Notification]     C:\Users\<REMOVED>\AppData\Roaming\VintagestoryData\Mods
30.12.2024 17:36:05 [Notification] Connecting to 0000:1111:2222:3333:4444:5555:6666:7777...
30.12.2024 17:36:05 [Error] Unable to read srv record, will connect to supplied hostname. Error: Server Failure
;; ->>HEADER<<- opcode: Query, status: Server Failure, id: 61880
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
30.12.2024 17:36:05 [Notification] Initialized GUI Manager
30.12.2024 17:36:05 [Notification] Initialized Server Connection
30.12.2024 17:36:05 [Warning] OpenAL Error during dispose of sound game:music/roots.ogg: InvalidName
30.12.2024 17:36:06 [Fatal] Game Version: v1.20.0-rc.6 (Unstable)
30.12.2024 17:36:06: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.UdpNetClient.Dispose() in VintagestoryLib\Client\Network\UdpNetClient.cs:line 88
   at Vintagestory.Client.NoObf.ClientMain.Dispose() in VintagestoryLib\Client\ClientMain.cs:line 2752
   at Vintagestory.Client.GuiScreenConnectingToServer.connectToGameServer() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 451
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 304
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 92
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Crash written to file at "C:\Users\<REMOVED>\AppData\Roaming\VintagestoryData\Logs\client-crash.log"

30.12.2024 17:37:13 [Notification] Exiting game now. Server running=False. Exit reason: Game crashed
```

**Comment by Th3Dilli** [comment]
thank you , will be fixed in next release

you may test it with replacing this two files on the server and client if you want
[VintagestoryLib.zip](https://github.com/user-attachments/files/18277478/VintagestoryLib.zip)
