### ISSUE TITLE
BlockEntityBeehive.IsSuitableFor error

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#4847]
### Game Version

1.20.0-rc.6

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Mod issue? Or vanilla?

### Logs

[Server Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityBeehive.IsSuitableFor(Entity entity, CreatureDiet diet) in VSSurvivalMod\BlockEntity\BEBeehive.cs:line 520
   at Vintagestory.GameContent.POIRegistry.GetNearestPoi(Vec3d centerPos, Single radius, PoiMatcher matcher) in VSEssentials\Systems\POIRegistry.cs:line 159
   at Vintagestory.GameContent.AiTaskSeekFoodAndEat.ShouldExecute() in VSEssentials\Entity\AI\Task\TasksImpl\AiTaskSeekFoodAndEat.cs:line 100
   at Vintagestory.GameContent.AiTaskManager.OnGameTick(Single dt) in VSEssentials\Entity\AI\Task\AiTaskManager.cs:line 214
   at Vintagestory.GameContent.EntityBehaviorTaskAI.OnGameTick(Single deltaTime) in VSEssentials\Entity\AI\Task\BehaviorTaskAI.cs:line 125
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\Entity.cs:line 928
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 589
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt) in VintagestoryLib\Server\Systems\World\EntitySimulation.cs:line 331
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt) in VintagestoryLib\Server\Systems\World\EntitySimulation.cs:line 143
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 896

**Comment by radfast** [comment]
Mod issue again @WickedSchnitzel .   Look at mods which offer creatures, look at the .json file of those creatures and how their diet is defined, one of the diets is defined in an incomplete way.
