### ISSUE TITLE
Game crashes on single player.

### ISSUE THREAD

**Issue by Gigglegasms** [anegostudios/VintageStory-Issues#494]
**Game Version:** 1.12.13
**Platform:** Windows
**Modded:** Yes, CarryCapacity-0.4.7, Adjustor_Release_V0.1.9, VS-1.12.8 Immersion 1.2.0

### Description
I start up the game and try to launch any single player world and the game crashes, I played it fine on version 1.12.11 with and without mods. But once I updated to version 1.12.13 all singleplayer worlds I tried to play crashed the game. I removed mods and disabled them to see if that caused the issue. Which I only got the same crashing result. Even creating a new world and reverting back to version 1.12.11 didn't fix it.

### How to reproduce
1. Clicked on any singleplayer world.
2. It crashes.

### Logs
```
Version: v1.12.13 (Stable)3/26/2020 4:12:40 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Server.ServerMain.Stop(String reason)
   at _MQWSaTJgjTk2HAVhjrFm8MbVpyAA._yB4AYVrviCZUQtWl4YBCeogsSJA()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
-------------------------------
Version: v1.12.12 (Stable)3/26/2020 4:28:27 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Server.ServerMain.Stop(String reason)
   at _7BCTb0JFhywtk4KFiscyT4pzzOf._pX0YlpaeFFFmioTS9gi4U1vabs2()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by tyronx** [comment]
Is this still happening in v1.12.14?

**Comment by Gigglegasms** [comment]
> Is this still happening in v1.12.14?

It's no longer happening, I went through and completely deleted all the files I had for vintage story then reinstalled it. Which ended up fixing whatever the issue was.
