### ISSUE TITLE
Crashing while trying to take a screenshot (display case with copper on a sculpted block)

### ISSUE THREAD

**Issue by wqpvs** [anegostudios/VintageStory-Issues#507]
**Game Version:** 1.12.14
**Platform:** Windows 
**Modded:** No 

### Description
Keeps crashing when i try to take a screenshot.
Multiplayer, i'd just placed a display case, copper crystal on a copper block. Press F12 to take SS and it crashes.

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
Not Crash

### Screenshots
uh..

### Logs
Running on 64 bit Windows with 32 GB RAM 
Version: v1.12.14 (Stable)2020-04-14 7:23:24 PM: Critical error occurred
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at _WX7Z8Lg47LcleaEL4Khx5kR8gVG._Lbhm4oIqq5XZFUhfUinhqOZNn4e(ClientPlatformAbstract , String , String , Boolean , Boolean )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.SaveScreenshot(String path, String filename, Boolean withAlpha, Boolean flip)
   at Vintagestory.Client.NoObf.SystemScreenshot.OnFrameDone(Single dt)
   at _clfmWA0YSY2as1BzXGL1FefIS0s._a4Hmi0OF3M1DtfqsRXVEQNMveaP(EnumRenderStage , Single )
   at _hLaepLRCOckdCEvZTPp1GxfgrdT._a4Hmi0OF3M1DtfqsRXVEQNMveaP(EnumRenderStage , Single )
   at _hLaepLRCOckdCEvZTPp1GxfgrdT._UfbESUwVALAm24tWKSVekibkmyy(Single )
   at _wbw3WsD1ic8cZIS5Ql2MkIqPWmb._UfbESUwVALAm24tWKSVekibkmyy(Single )
   at _s54YxMQ8l5DBeihbmw81nJkPTSU._RT1lBvzfhVzcDZ6jmYewDTkUdvx(Single )
   at _s54YxMQ8l5DBeihbmw81nJkPTSU._EZIJU8BLizIQdIOGgxu5BrkHzpV(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _gilSYm6aSzOct8TKUm64HAM8OHp._tyidesQGCE1oKHv8YEo8HwYCSty(_RxGTCHor7fqeGRNMEH5pZVfBHHK , String[] )
   at _xmrDk9pogtvR6xvbzmBc2dtFsbu._tyidesQGCE1oKHv8YEo8HwYCSty(ThreadStart )
-------------------------------

**Comment by wqpvs** [comment]
OK This was my computers fault! There was an issue with my D: drive.
