### ISSUE TITLE
Breaking block under filled crucible crashes game.

### ISSUE THREAD

**Issue by CorwinSolace** [anegostudios/VintageStory-Issues#509]
**Game Version:** 1.12.14
**Platform:** Windows.
**Modded:** No.

### How to reproduce
1. Make a crucible then fill with copper. Mine had 59 units of copper inside.
2. Place crucible on dirt block.
3. Break dirt block.
4. Game crashes as crucible falls.

### Expected behavior
Crucible drops.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.12.14 (Stable)4/14/2020 6:50:13 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockSmeltedContainer.GetDrops(IWorldAccessor world, BlockPos pos, IPlayer byPlayer, Single dropQuantityMultiplier)
   at Vintagestory.GameContent.BlockSmeltedContainer.OnPickBlock(IWorldAccessor world, BlockPos pos)
   at Vintagestory.API.Common.Block.GetPlacedBlockName(IWorldAccessor world, BlockPos pos)
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.ComposeBlockInfoHud()
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.BlockInView()
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at _hLaepLRCOckdCEvZTPp1GxfgrdT._gvVdZYlJjMijmkAmKtFDCvJNXax(Single )
   at _hLaepLRCOckdCEvZTPp1GxfgrdT._nu0syyqM6QcVDRvU3XOrq03zfUh(Single )
   at _wbw3WsD1ic8cZIS5Ql2MkIqPWmb._ibkrrJqCs89QNSe99xnFzRxp3sL(Single )
   at _s54YxMQ8l5DBeihbmw81nJkPTSU._RT1lBvzfhVzcDZ6jmYewDTkUdvx(Single )
   at _s54YxMQ8l5DBeihbmw81nJkPTSU._EZIJU8BLizIQdIOGgxu5BrkHzpV(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _gilSYm6aSzOct8TKUm64HAM8OHp._tyidesQGCE1oKHv8YEo8HwYCSty(_RxGTCHor7fqeGRNMEH5pZVfBHHK , String[] )
   at _xmrDk9pogtvR6xvbzmBc2dtFsbu._tyidesQGCE1oKHv8YEo8HwYCSty(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 4/14/2020 6:50:13 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.GameContent.BlockSmeltedContainer.GetDrops(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.MathTools.BlockPos, Vintagestory.API.Common.IPlayer, Single)
   at Vintagestory.GameContent.BlockSmeltedContainer.OnPickBlock(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.MathTools.BlockPos)
   at Vintagestory.API.Common.Block.GetPlacedBlockName(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.MathTools.BlockPos)
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.ComposeBlockInfoHud()
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.BlockInView()
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64, Vintagestory.API.Common.IWorldAccessor)
   at _hLaepLRCOckdCEvZTPp1GxfgrdT._gvVdZYlJjMijmkAmKtFDCvJNXax(Single)
   at _hLaepLRCOckdCEvZTPp1GxfgrdT._nu0syyqM6QcVDRvU3XOrq03zfUh(Single)
   at _wbw3WsD1ic8cZIS5Ql2MkIqPWmb._ibkrrJqCs89QNSe99xnFzRxp3sL(Single)
   at _s54YxMQ8l5DBeihbmw81nJkPTSU._RT1lBvzfhVzcDZ6jmYewDTkUdvx(Single)
   at _s54YxMQ8l5DBeihbmw81nJkPTSU._EZIJU8BLizIQdIOGgxu5BrkHzpV(Single)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _gilSYm6aSzOct8TKUm64HAM8OHp._tyidesQGCE1oKHv8YEo8HwYCSty(_RxGTCHor7fqeGRNMEH5pZVfBHHK, System.String[])
   at _xmrDk9pogtvR6xvbzmBc2dtFsbu._tyidesQGCE1oKHv8YEo8HwYCSty(System.Threading.ThreadStart)

 }
```

**Comment by Craluminum2413** [comment]
Doesn't crash in the latest versions, like 1.14.10. So I guess it applied for 1.15.0 too
