### ISSUE TITLE
Crashed while placing cobblestone half block

### ISSUE THREAD

**Issue by skudster13** [anegostudios/VintageStory-Issues#514]
**Game Version:** 1.12.14
**Platform:** Windows
**Modded:** No

### Description
Random crash after placing half block against side of stairs. Block placed flat against side of stairs.

### How to reproduce
Did not try to reproduce

### Expected behavior
block placed and keep moving on with life.

### Screenshots
N/A

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.12.14 (Stable)4/23/2020 8:23:33 PM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at Vintagestory.API.Datastructures.SyncedTreeAttribute.MarkPathDirty(String path)
   at Vintagestory.API.Common.EntityAgent.UpdateDebugAttributes()
   at Vintagestory.GameContent.EntityButterfly.SetAnimation(String animCode, Single speed)
   at Vintagestory.GameContent.EntityButterfly.OnGameTick(Single dt)
   at Vintagestory.Client.NoObf.ClientSystemEntities.OnGameTick(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at _hLaepLRCOckdCEvZTPp1GxfgrdT._gvVdZYlJjMijmkAmKtFDCvJNXax(Single )
   at _hLaepLRCOckdCEvZTPp1GxfgrdT._nu0syyqM6QcVDRvU3XOrq03zfUh(Single )
   at _wbw3WsD1ic8cZIS5Ql2MkIqPWmb._ibkrrJqCs89QNSe99xnFzRxp3sL(Single )
   at _s54YxMQ8l5DBeihbmw81nJkPTSU._RT1lBvzfhVzcDZ6jmYewDTkUdvx(Single )
   at _s54YxMQ8l5DBeihbmw81nJkPTSU._EZIJU8BLizIQdIOGgxu5BrkHzpV(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _gilSYm6aSzOct8TKUm64HAM8OHp._tyidesQGCE1oKHv8YEo8HwYCSty(_RxGTCHor7fqeGRNMEH5pZVfBHHK , String[] )
   at _xmrDk9pogtvR6xvbzmBc2dtFsbu._tyidesQGCE1oKHv8YEo8HwYCSty(ThreadStart )
-------------------------------
```

**Comment by Craluminum2413** [comment]
Doesn't crash in 1.15.0-pre2

**Comment by copygirl** [comment]
This appears to have something to do with butterflies. I will close for now until this happens again.
