### ISSUE TITLE
Crash if glDebugMode ClientSetting set to true.

### ISSUE THREAD

**Issue by darnuria** [anegostudios/VintageStory-Issues#517]
**Game Version:** Game Version: v1.12.14 (Stable)
**Platform:** Linux Ubuntu 16.04.04 LTS
**Modded:** No

### Description

If I Edit `clientSettings.json` to set `glDebugMode` to `true` I get a crash at startup.

### How to reproduce

0. edit clientSettings.json set `boolSettings.glDebug` to `true` was `false` by default.
1. Launch the game `mono Vintagestory.exe` or `mono --debug Vintagestory.exe`

### Logs

```
15:27:48 [Client Notification] Client logger started.
15:27:48 [Client Notification] Game Version: v1.12.14 (Stable)
Gtk-Message: 15:27:48.681: Failed to load module "canberra-gtk-module"
15:27:48 [Client Warning] Client side assembly resolver did not find the assembly in the binary path, the lib path or the mods path. Tested for the following paths: 
/home/darnuria/Games/vintagestory/Lib/UIAutomationWinforms.dll
/home/darnuria/Games/vintagestory/UIAutomationWinforms.dll
/home/darnuria/.config/VintagestoryData/Mods/UIAutomationWinforms.dll
/home/darnuria/Games/vintagestory/Mods/UIAutomationWinforms.dll
15:27:49 [Client Debug] Creating game window with window mode Fullscreen
15:27:49 [Client Notification] Graphics Card Vendor: Intel Open Source Technology Center
15:27:49 [Client Notification] Graphics Card Version: 4.5 (Core Profile) Mesa 19.2.8
15:27:49 [Client Notification] Graphics Card Renderer: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
15:27:49 [Client Notification] Graphics Card ShadingLanguageVersion: 4.50
15:27:49 [Client Notification] Cairo Graphics Version: 1.15.10
15:27:49 [Client Notification] OpenAL Version: 1.1 ALSOFT 1.18.2
15:27:49 [Client Notification] C# Framework: Mono 6.8.0.105 (tarball Tue Feb  4 21:20:20 UTC 2020)
15:27:49 [Client Notification] OpenTK Version: 3.1.0 (A set of fast, low-level C# bindings for OpenGL, OpenGL ES and OpenAL.)
15:27:49 [Client Notification] Start discovering assets
15:27:49 [Client Notification] Found 8 base assets in category lang
15:27:49 [Client Notification] Found 0 base assets in category journal
15:27:49 [Client Notification] Found 0 base assets in category patches

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x55d65a813265 - mono : (null)
	0x55d65a8135fc - mono : (null)
	0x55d65a7bea21 - mono : (null)
	0x55d65a80cbfb - mono : (null)
	0x7ff5fc570878 - Unknown

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x7ff5d0d1a700 from 0x7ff5fe7a7780
Pkilling 0x7ff5f041e700 from 0x7ff5fe7a7780
Pkilling 0x7ff5b3fff700 from 0x7ff5fe7a7780
Pkilling 0x7ff5f9ea0700 from 0x7ff5fe7a7780
Pkilling 0x7ff5d0b19700 from 0x7ff5fe7a7780
Pkilling 0x7ff5f021d700 from 0x7ff5fe7a7780
Pkilling 0x7ff5f061f700 from 0x7ff5fe7a7780
Could not exec mono-hang-watchdog, expected on path '/etc/../bin/mono-hang-watchdog' (errno 2)
Entering thread summarizer pause from 0x7ff5fe7a7780
Finished thread summarizer pause from 0x7ff5fe7a7780.
15:27:49 [Client Notification] Found 16 base assets in category config
15:27:49 [Client Notification] Found 0 base assets in category worldproperties
15:27:49 [Client Notification] Found 31 base assets in category sounds
15:27:49 [Client Notification] Found 2 base assets in category shapes

Waiting for dumping threads to resume
15:27:49 [Client Notification] Found 72 base assets in category shaders
15:27:49 [Client Notification] Found 13 base assets in category shaderincludes
15:27:49 [Client Notification] Found 58 base assets in category textures
15:27:49 [Client Notification] Found 3 base assets in category music
15:27:49 [Client Notification] Found 0 base assets in category dialog
15:27:49 [Client Notification] Found 203 base assets in total
15:27:49 [Client Notification] Loading sounds

=================================================================
	External Debugger Dump:
=================================================================
[New LWP 30077]
[New LWP 30078]
[New LWP 30079]
[New LWP 30080]
[New LWP 30081]
[New LWP 30082]
[New LWP 30083]
[New LWP 30090]
[New LWP 30091]
[New LWP 30092]
[New LWP 30093]
[New LWP 30094]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007ff5fdf9223a in __waitpid (pid=30097, stat_loc=0x7ffed90cf924, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
  Id   Target Id         Frame 
* 1    Thread 0x7ff5fe7a7780 (LWP 30076) "mono" 0x00007ff5fdf9223a in __waitpid (pid=30097, stat_loc=0x7ffed90cf924, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
  2    Thread 0x7ff5fc3ff700 (LWP 30077) "SGen worker" 0x00007ff5fdf8d9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55d65adee008) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  3    Thread 0x7ff5f9ea0700 (LWP 30078) "Finalizer" 0x00007ff5fdf906d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x55d65addf280) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  4    Thread 0x7ff5f061f700 (LWP 30079) "mono" 0x00007ff5fdf906d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7ff5ec000b80) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  5    Thread 0x7ff5f041e700 (LWP 30080) "Thread Pool Wor" 0x00007ff5fd364bf9 in __GI___poll (fds=0x7ff5f041d400, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  6    Thread 0x7ff5f021d700 (LWP 30081) "Thread Pool Wor" 0x00007ff5fdf8d9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55d65cbc2378) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  7    Thread 0x7ff5d89ff700 (LWP 30082) "mono:disk$0" 0x00007ff5fdf8d9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55d65d3ac6a8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  8    Thread 0x7ff5d3fff700 (LWP 30083) "mono:disk$0" 0x00007ff5fdf8d9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55d65cc73f78) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  9    Thread 0x7ff5d18d5700 (LWP 30090) "threaded-ml" 0x00007ff5fd364bf9 in __GI___poll (fds=0x7ff5c400a4c0, nfds=3, timeout=118) at ../sysdeps/unix/sysv/linux/poll.c:29
  10   Thread 0x7ff5d10d4700 (LWP 30091) "mono" 0x00007ff5fdf8d9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7ff5a8004048) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  11   Thread 0x7ff5b3fff700 (LWP 30092) "mono" 0x00007ff5fdf906d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x55d65adee740) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  12   Thread 0x7ff5d0d1a700 (LWP 30093) "Thread Pool Wor" __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
  13   Thread 0x7ff5d0b19700 (LWP 30094) "Thread Pool Wor" 0x00007ff5fdf8d9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55d65cbc23e8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88

Thread 13 (Thread 0x7ff5d0b19700 (LWP 30094)):
#0  0x00007ff5fdf8d9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55d65cbc23e8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007ff5fdf8d9f3 in __pthread_cond_wait_common (abstime=0x0, mutex=0x55d65cbc2398, cond=0x55d65cbc23c0) at pthread_cond_wait.c:502
#2  0x00007ff5fdf8d9f3 in __pthread_cond_wait (cond=0x55d65cbc23c0, mutex=0x55d65cbc2398) at pthread_cond_wait.c:655
#3  0x000055d65aa60a1d in  ()
#4  0x000055d65a9c464c in  ()
#5  0x000055d65a9c5c9f in  ()
#6  0x000055d65a9fe70d in  ()
#7  0x000055d65a93dd8c in  ()
#8  0x00000000420073fe in  ()
#9  0xffffffffffffffff in  ()
#10 0x0000000000000000 in  ()

Thread 12 (Thread 0x7ff5d0d1a700 (LWP 30093)):
#0  0x00007ff5fdf9110d in __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ff5fdf8bf02 in __pthread_mutex_cond_lock (mutex=mutex@entry=0x55d65adee6a0) at ../nptl/pthread_mutex_lock.c:78
#2  0x00007ff5fdf8dd9d in __pthread_cond_wait_common (abstime=0x7ff5d0d194f0, mutex=0x55d65adee6a0, cond=0x55d65adee660) at pthread_cond_wait.c:645
#3  0x00007ff5fdf8dd9d in __pthread_cond_timedwait (cond=0x55d65adee660, mutex=0x55d65adee6a0, abstime=0x7ff5d0d194f0) at pthread_cond_wait.c:667
#4  0x000055d65aa609bb in  ()
#5  0x000055d65aa6b978 in  ()
#6  0x000055d65a9aabf0 in  ()
#7  0x000055d65a93f48d in  ()
#8  0x0000000041fda2be in  ()
#9  0x0000000000000001 in  ()
#10 0x0000000000000000 in  ()

Thread 11 (Thread 0x7ff5b3fff700 (LWP 30092)):
#0  0x00007ff5fdf906d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x55d65adee740) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  0x00007ff5fdf906d6 in do_futex_wait (sem=sem@entry=0x55d65adee740, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007ff5fdf907c8 in __new_sem_wait_slow (sem=0x55d65adee740, abstime=0x0) at sem_waitcommon.c:181
#3  0x000055d65aa693f8 in  ()
#4  0x000055d65aa199c3 in  ()
#5  0x000055d65aa2a19c in  ()
#6  0x000055d65aa2a349 in  ()
#7  0x000055d65aa2a906 in  ()
#8  0x000055d65aa1a9f0 in  ()
#9  0x000055d65a9fea12 in  ()
#10 0x0000000041ebce8e in  ()
#11 0x00007ff5fc7ff9f0 in  ()
#12 0x00007ff5a8001560 in  ()
#13 0x0000000000000928 in  ()
#14 0x000055d65cc17408 in  ()
#15 0x00007ff5a8000ef0 in  ()
#16 0x00007ff5a8005790 in  ()
#17 0x00007ff5b3ffe450 in  ()
#18 0x00007ff5b3ffe3a0 in  ()
#19 0x00007ff5fc7ff090 in  ()
#20 0x0000000041ebbd8c in  ()
#21 0x00007ff5fc7d1278 in  ()
#22 0x0000000000000242 in  ()
#23 0x00007ff5b3ffe860 in  ()
#24 0x00007ff5fc800318 in  ()
#25 0x0000000000000011 in  ()
#26 0x0000000000000120 in  ()
#27 0x00007ff5fc7c8088 in  ()
#28 0x00007ff5fc7c8088 in  ()
#29 0x0000000000000028 in  ()
#30 0x0000000000000001 in  ()
#31 0x00007ff5fc7fefa0 in  ()
#32 0x00007ff5fc7d1278 in  ()
#33 0x00007ff5b3ffe860 in  ()
#34 0x0000000042005b4b in  ()
#35 0x00007ff5fc7c8088 in  ()
#36 0x00007ff5b3ffe860 in  ()
#37 0x0000000000000028 in  ()
#38 0x0000000000000001 in  ()
#39 0x00007ff5fc7fefa0 in  ()
#40 0x00007ff5fc7d1278 in  ()
#41 0x00007ff5fc7fefa0 in  ()
#42 0x00007ff5fc7d1278 in  ()
#43 0x3f800000c1000000 in  ()
#44 0x0000000000000000 in  ()

Thread 10 (Thread 0x7ff5d10d4700 (LWP 30091)):
#0  0x00007ff5fdf8d9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7ff5a8004048) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007ff5fdf8d9f3 in __pthread_cond_wait_common (abstime=0x0, mutex=0x55d65d986410, cond=0x7ff5a8004020) at pthread_cond_wait.c:502
#2  0x00007ff5fdf8d9f3 in __pthread_cond_wait (cond=0x7ff5a8004020, mutex=0x55d65d986410) at pthread_cond_wait.c:655
#3  0x00007ff5d2b63a68 in pa_threaded_mainloop_wait () at /usr/lib/x86_64-linux-gnu/libpulse.so.0
#4  0x00007ff5d35b29a7 in  () at /usr/lib/x86_64-linux-gnu/libopenal.so.1
#5  0x00007ff5d356b677 in  () at /usr/lib/x86_64-linux-gnu/libopenal.so.1
#6  0x00007ff5fdf876db in start_thread (arg=0x7ff5d10d4700) at pthread_create.c:463
#7  0x00007ff5fd37188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 9 (Thread 0x7ff5d18d5700 (LWP 30090)):
#0  0x00007ff5fd364bf9 in __GI___poll (fds=0x7ff5c400a4c0, nfds=3, timeout=118) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ff5d2b63481 in  () at /usr/lib/x86_64-linux-gnu/libpulse.so.0
#2  0x00007ff5d2b54e40 in pa_mainloop_poll () at /usr/lib/x86_64-linux-gnu/libpulse.so.0
#3  0x00007ff5d2b554d0 in pa_mainloop_iterate () at /usr/lib/x86_64-linux-gnu/libpulse.so.0
#4  0x00007ff5d2b55560 in pa_mainloop_run () at /usr/lib/x86_64-linux-gnu/libpulse.so.0
#5  0x00007ff5d2b633c9 in  () at /usr/lib/x86_64-linux-gnu/libpulse.so.0
#6  0x00007ff5d2905318 in  () at /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-11.1.so
#7  0x00007ff5fdf876db in start_thread (arg=0x7ff5d18d5700) at pthread_create.c:463
#8  0x00007ff5fd37188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7ff5d3fff700 (LWP 30083)):
#0  0x00007ff5fdf8d9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55d65cc73f78) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007ff5fdf8d9f3 in __pthread_cond_wait_common (abstime=0x0, mutex=0x55d65cc73f28, cond=0x55d65cc73f50) at pthread_cond_wait.c:502
#2  0x00007ff5fdf8d9f3 in __pthread_cond_wait (cond=0x55d65cc73f50, mutex=0x55d65cc73f28) at pthread_cond_wait.c:655
#3  0x00007ff5d9e8aecb in  () at /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#4  0x00007ff5d9e8aac7 in  () at /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#5  0x00007ff5fdf876db in start_thread (arg=0x7ff5d3fff700) at pthread_create.c:463
#6  0x00007ff5fd37188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7ff5d89ff700 (LWP 30082)):
#0  0x00007ff5fdf8d9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55d65d3ac6a8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007ff5fdf8d9f3 in __pthread_cond_wait_common (abstime=0x0, mutex=0x55d65d3ac658, cond=0x55d65d3ac680) at pthread_cond_wait.c:502
#2  0x00007ff5fdf8d9f3 in __pthread_cond_wait (cond=0x55d65d3ac680, mutex=0x55d65d3ac658) at pthread_cond_wait.c:655
#3  0x00007ff5d9e8aecb in  () at /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#4  0x00007ff5d9e8aac7 in  () at /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#5  0x00007ff5fdf876db in start_thread (arg=0x7ff5d89ff700) at pthread_create.c:463
#6  0x00007ff5fd37188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7ff5f021d700 (LWP 30081)):
#0  0x00007ff5fdf8d9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55d65cbc2378) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007ff5fdf8d9f3 in __pthread_cond_wait_common (abstime=0x0, mutex=0x55d65cbc2328, cond=0x55d65cbc2350) at pthread_cond_wait.c:502
#2  0x00007ff5fdf8d9f3 in __pthread_cond_wait (cond=0x55d65cbc2350, mutex=0x55d65cbc2328) at pthread_cond_wait.c:655
#3  0x000055d65aa60a1d in  ()
#4  0x000055d65a9c464c in  ()
#5  0x000055d65a9c5c9f in  ()
#6  0x000055d65a9fe70d in  ()
#7  0x000055d65a93dd8c in  ()
#8  0x00000000420073fe in  ()
#9  0xffffffffffffffff in  ()
#10 0x0000000000000000 in  ()

Thread 5 (Thread 0x7ff5f041e700 (LWP 30080)):
#0  0x00007ff5fd364bf9 in __GI___poll (fds=0x7ff5f041d400, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ff5f0854d34 in Mono_Unix_UnixSignal_WaitAny () at /usr/lib/../lib/libMonoPosixHelper.so
#2  0x0000000041ee2d06 in  ()
#3  0x00007ff5fc42e3c0 in  ()
#4  0x0000000000000002 in  ()
#5  0x0000000000000003 in  ()
#6  0x00007ff5fc42e3c0 in  ()
#7  0x00007ff5fc42ce20 in  ()
#8  0x00007ff5fc42d6e8 in  ()
#9  0x00007ff5e4002580 in  ()
#10 0x0000000000000002 in  ()
#11 0x00007ff5f041d650 in  ()
#12 0x0000000000000000 in  ()

Thread 4 (Thread 0x7ff5f061f700 (LWP 30079)):
#0  0x00007ff5fdf906d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7ff5ec000b80) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  0x00007ff5fdf906d6 in do_futex_wait (sem=sem@entry=0x7ff5ec000b80, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007ff5fdf907c8 in __new_sem_wait_slow (sem=0x7ff5ec000b80, abstime=0x0) at sem_waitcommon.c:181
#3  0x000055d65aa68fd2 in  ()
#4  0x000055d65aa6e99d in  ()
#5  0x000055d65aa6b985 in  ()
#6  0x000055d65aa0b332 in  ()
#7  0x000055d65a9ad760 in  ()
#8  0x00007ff5fdf876db in start_thread (arg=0x7ff5f061f700) at pthread_create.c:463
#9  0x00007ff5fd37188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7ff5f9ea0700 (LWP 30078)):
#0  0x00007ff5fdf906d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x55d65addf280) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  0x00007ff5fdf906d6 in do_futex_wait (sem=sem@entry=0x55d65addf280, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007ff5fdf907c8 in __new_sem_wait_slow (sem=0x55d65addf280, abstime=0x0) at sem_waitcommon.c:181
#3  0x000055d65a9fa5c8 in  ()
#4  0x000055d65a9ad760 in  ()
#5  0x00007ff5fdf876db in start_thread (arg=0x7ff5f9ea0700) at pthread_create.c:463
#6  0x00007ff5fd37188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7ff5fc3ff700 (LWP 30077)):
#0  0x00007ff5fdf8d9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55d65adee008) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007ff5fdf8d9f3 in __pthread_cond_wait_common (abstime=0x0, mutex=0x55d65adee020, cond=0x55d65adedfe0) at pthread_cond_wait.c:502
#2  0x00007ff5fdf8d9f3 in __pthread_cond_wait (cond=0x55d65adedfe0, mutex=0x55d65adee020) at pthread_cond_wait.c:655
#3  0x000055d65aa5354a in  ()
#4  0x00007ff5fdf876db in start_thread (arg=0x7ff5fc3ff700) at pthread_create.c:463
#5  0x00007ff5fd37188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ff5fe7a7780 (LWP 30076)):
#0  0x00007ff5fdf9223a in __waitpid (pid=30097, stat_loc=0x7ffed90cf924, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x000055d65a813575 in  ()
#2  0x000055d65a8135fc in  ()
#3  0x000055d65a7bea21 in  ()
#4  0x000055d65a80cbfb in  ()
#5  0x00007ff5fc570878 in  ()
#6  0xffffffffffffff67 in  ()
#7  0xfffffffffffffdcd in  ()
#8  0x0000000000000000 in  ()

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7ff5fc570878):0x7ff5fc570868  67 00 6d 00 6f 00 64 00 65 00 00 00 00 00 00 00  g.m.o.d.e.......
0x7ff5fc570878  60 ff 01 a8 f5 7f 00 00 00 00 00 00 00 00 00 00  `...............
0x7ff5fc570888  00 00 00 00 00 00 00 00 f6 88 fd 41 00 00 00 00  ...........A....
0x7ff5fc570898  c0 b5 42 fc f5 7f 00 00 e8 e3 00 a8 f5 7f 00 00  ..B.............

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
debug_launch.sh: line 6: 30076 Aborted                 (core dumped) mono --debug ./Vintagestory.exe
In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```

**Comment by tyronx** [comment]
I suspect that is due to the fact that the gl debug mode has only been introduced in OpenGL 4.3 - do your driver support it?

In any case I've now added a test on startup to see if GL_ARB_debug_output or GL_KHR_debug is supported.

**Comment by tyronx** [comment]
now new info in a few months, closing this for now

**Comment by darnuria** [comment]
Got caught by work no problem to close will try to reproduce as soon as I find time to play.
