### ISSUE TITLE
Crash while trying to removed borax chunk from quern

### ISSUE THREAD

**Issue by Bownz11** [anegostudios/VintageStory-Issues#519]
**Game Version:** 1.12.14 (Stable)
**Platform:** Windows
**Modded:** No

### Description
Put my 20 borax pieces into wrong quern(I use this one for flour), upon shift clicking them to remove them from the input slot, my game crashed pruducing the crash log.. When I reloaded the game Iwas approx. 25 blocks away where I was when the game crashed, at the chest where I took out the borax. The 20 pieces of borax are now gone, vanished. 

### How to reproduce
I was unable to reproduce tracing my steps exactly following the crash

### Expected behavior
I expected the borax chunks to come out of the input and into my inventory

### Screenshots
Not specific / non-visual

### Logs
```
Running on 64 bit Windows with 24 GB RAM 
Version: v1.12.14 (Stable)4/27/2020 7:06:06 PM: Critical error occurred
System.ArgumentException: Supplied slot is not part of this inventory (quern-1)!
   at Vintagestory.API.Common.InventoryBase.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack)
   at Vintagestory.API.Common.ItemSlot.OnItemSlotModified(ItemStack sinkStack)
   at Vintagestory.API.Common.ItemSlot.TryFlipWith(ItemSlot itemSlot)
   at Vintagestory.API.Common.InventoryBase.TryFlipItems(Int32 targetSlotId, ItemSlot itemSlot)
   at Vintagestory.Client.NoObf.HudHotbar.OnKeySlot(Int32 index, Boolean moveItems)
   at Vintagestory.Client.NoObf.HudHotbar.<OnBlockTexturesLoaded>b__24_0(KeyCombination viaKeyComb)
   at _LaxdUDtAGXwcs3Nz0P3hnODgzLgb._cWdJrYKwbBa2v0BbDLbflZu5Kwq(KeyEvent , IWorldAccessor , IPlayer , Boolean , Boolean , Boolean )
   at _hLaepLRCOckdCEvZTPp1GxfgrdT._Oy0GkyuVXem6XhfdpqRkRihlAWE(KeyEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(Object sender, KeyboardKeyEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnKeyDown(Key key, Boolean repeat)
   at OpenTK.Platform.Windows.WinGLNative.HandleKeyboard(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _gilSYm6aSzOct8TKUm64HAM8OHp._tyidesQGCE1oKHv8YEo8HwYCSty(_RxGTCHor7fqeGRNMEH5pZVfBHHK , String[] )
   at _xmrDk9pogtvR6xvbzmBc2dtFsbu._tyidesQGCE1oKHv8YEo8HwYCSty(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 2/15/2020 1:19:46 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFE4371A839
Stack:
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at System.Environment._Exit(Int32)
   at System.Environment._Exit(Int32)
   at System.Environment.Exit(Int32)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   at OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double, Double)
   at _hG3cjnuXqvBFIftztmAxyKIDzVK._djA1E8LGqTYn45ZuiP3uFxLopvF(_UYatkCgiPh2VvAulJFlAVY8VyYO, System.String[])
   at _x6YypWdxqt6nvg5Y8amUBlgFCtR._djA1E8LGqTYn45ZuiP3uFxLopvF(System.Threading.ThreadStart)
   at _hG3cjnuXqvBFIftztmAxyKIDzVK._HHUQpUPUVaY3V13HqVUfwFrCyfh(System.String[])
 }
```

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in v1.13 and onwards
