### ISSUE TITLE
Crash during smithing

### ISSUE THREAD

**Issue by AnthonyPaulO** [anegostudios/VintageStory-Issues#537]
**Platform:** Windows
**Modded:** No

### Description
Was smithing an iron scythe, for some reason it didn't complete so I added another iron block to it as another layer and was moving the little bits around and clicked on one piece at the edge and it crashed.

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.12.14 (Stable)5/26/2020 12:51:13 PM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockEntityAnvil.OnUpset(Vec3i voxelPos, BlockFacing towardsFace)
   at Vintagestory.GameContent.BlockEntityAnvil.OnUseOver(IPlayer byPlayer, Vec3i voxelPos, BlockSelection blockSel)
   at Vintagestory.GameContent.ItemHammer.OnHeldAttackStop(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at _AwTvpwXV1bHGBB8plvoGTYT5ihD._aXg8ff7JchZYkTRDnSjo139TZJH()
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at _hLaepLRCOckdCEvZTPp1GxfgrdT._gvVdZYlJjMijmkAmKtFDCvJNXax(Single )
   at _hLaepLRCOckdCEvZTPp1GxfgrdT._nu0syyqM6QcVDRvU3XOrq03zfUh(Single )
   at _wbw3WsD1ic8cZIS5Ql2MkIqPWmb._ibkrrJqCs89QNSe99xnFzRxp3sL(Single )
   at _s54YxMQ8l5DBeihbmw81nJkPTSU._RT1lBvzfhVzcDZ6jmYewDTkUdvx(Single )
   at _s54YxMQ8l5DBeihbmw81nJkPTSU._EZIJU8BLizIQdIOGgxu5BrkHzpV(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _gilSYm6aSzOct8TKUm64HAM8OHp._tyidesQGCE1oKHv8YEo8HwYCSty(_RxGTCHor7fqeGRNMEH5pZVfBHHK , String[] )
   at _xmrDk9pogtvR6xvbzmBc2dtFsbu._tyidesQGCE1oKHv8YEo8HwYCSty(ThreadStart )
-------------------------------
```

**Comment by tyronx** [comment]
Thank you, this should be fixed in v1.13
