### ISSUE TITLE
"Flipping" items crashes

### ISSUE THREAD

**Issue by Shionsan** [anegostudios/VintageStory-Issues#558]
**Game Version:** 1.12.14
**Platform:** Windows
**Modded:** Happens with and without mods

### Description
Game crashes when moving items from toolbelt to the barrel item slot with a number key.
Immersive mouse mode is enabled.

### How to reproduce
1. Open barrel GUI
2. Aim at the item slot
3. Press number key of toolbelt slot with an item
4. CRASH

### Expected behavior
As it should be - items in slots exchange.

### Logs
Running on 64 bit Windows with 32 GB RAM 
Version: v1.12.14 (Stable)07.08.2020 3:23:49: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.ItemSlotBarrelInput.OnItemSlotModified(ItemStack stack)
   at Vintagestory.API.Common.ItemSlot.TryFlipWith(ItemSlot itemSlot)
   at Vintagestory.API.Common.InventoryBase.TryFlipItems(Int32 targetSlotId, ItemSlot itemSlot)
   at Vintagestory.Client.NoObf.HudHotbar.OnKeySlot(Int32 index, Boolean moveItems)
   at Vintagestory.Client.NoObf.HudHotbar.<OnBlockTexturesLoaded>b__24_4(KeyCombination viaKeyComb)
   at _LaxdUDtAGXwcs3Nz0P3hnODgzLgb._cWdJrYKwbBa2v0BbDLbflZu5Kwq(KeyEvent , IWorldAccessor , IPlayer , Boolean , Boolean , Boolean )
   at _hLaepLRCOckdCEvZTPp1GxfgrdT._Oy0GkyuVXem6XhfdpqRkRihlAWE(KeyEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(Object sender, KeyboardKeyEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnKeyDown(Key key, Boolean repeat)
   at OpenTK.Platform.Windows.WinGLNative.HandleKeyboard(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _gilSYm6aSzOct8TKUm64HAM8OHp._tyidesQGCE1oKHv8YEo8HwYCSty(_RxGTCHor7fqeGRNMEH5pZVfBHHK , String[] )
   at _xmrDk9pogtvR6xvbzmBc2dtFsbu._tyidesQGCE1oKHv8YEo8HwYCSty(ThreadStart )

**Comment by Shionsan** [comment]
It seems shortcuts aren't misbehaving on barrels only. When trying to take hot crucible off the firepit with number shortcut - it moves only on "client" side, creating a visual dupping effect (playing SP here), while still staying in firepit. At least in my particular case.

**Comment by Shionsan** [comment]
Shortcuts are also screw up with firepits.

Have few firepit UI open in immersive mouse mode.
1. Try to flip something in cooking slot into the rightmost firepit UI slot.
2. Real item will probably go to the leftmost firepit UI, and the one you've tried to move it to will bug out with a ghost/desynced item.
3. Real item will probably go to the leftmost firepit UI, and the one you've tried to move it to will bug out with a ghost/desynced item.

Mods are not related. Version is still 1.12.14.

**Comment by Shionsan** [comment]
**Game Version:** v1.13.0
**Platform**: Windows

### Description
Crash on item-flip with a number-shortcut from quern (2nd slot) to toolbar (4th slot).

### How to reproduce
For some reason unable to reproduce it anymore.

### Logs
Running on 64 bit Windows with 32 GB RAM 
Version: v1.13.0 (Stable)24.08.2020 0:57:13: Critical error occurred
System.ArgumentException: Supplied slot is not part of this inventory (quern-512285/118/512578)!
   at Vintagestory.API.Common.InventoryBase.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack)
   at Vintagestory.API.Common.ItemSlot.OnItemSlotModified(ItemStack sinkStack)
   at Vintagestory.API.Common.ItemSlot.TryFlipWith(ItemSlot itemSlot)
   at Vintagestory.API.Common.InventoryBase.TryFlipItems(Int32 targetSlotId, ItemSlot itemSlot)
   at Vintagestory.Client.NoObf.HudHotbar.OnKeySlot(Int32 index, Boolean moveItems)
   at Vintagestory.Client.NoObf.HudHotbar.<OnBlockTexturesLoaded>b__24_3(KeyCombination viaKeyComb)
   at _oImCJbzWM22zweYyJu8BoEnQLai._NeioykUxr6cfXmTa83UE7J4vLeA(KeyEvent , IWorldAccessor , IPlayer , Boolean , Boolean , Boolean )
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(Object sender, KeyboardKeyEventArgs e)
   at System.EventHandler1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnKeyDown(Key key, Boolean repeat)
   at OpenTK.Platform.Windows.WinGLNative.HandleKeyboard(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _JQ8hJZaWfIKtgNCRVIFwsWJlGbD._PobINQXMJm1DRr8Q98KrBuOyaBI(_oOE8RvwwsA8CcfDxUcot5Tu1mbq , String[] )
   at _E1zChrmPoD6YADl4x90dHsneZYx._PobINQXMJm1DRr8Q98KrBuOyaBI(ThreadStart )

**Comment by tyronx** [comment]
thanks for the reports, this should be fixed in v1.13.4 or v1.14
