### ISSUE TITLE
Crash upon loading world

### ISSUE THREAD

**Issue by Ryorama** [anegostudios/VintageStory-Issues#560]
Game Version:  v1.13.0-pre.16 (Unstable)
Platform: Windows
Modded:No

Description:
When I try to log into a world, the game immediately crashes. I haven't tried with existing worlds, but it still crashes after creating it and attempting to enter the world again.

How to reproduce:
1. Make a new world and enter the world

Logs:
```
Running on 64 bit Windows with 4 GB RAM 
Version: v1.13.0-pre.16 (Unstable)8/7/2020 12:29:10 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.GuiDialogCharacter.updateEnvText()
   at Vintagestory.Client.NoObf.GuiDialogCharacter.OnRenderGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _W1UdvhSqpmdfbC7pWSbSZE3m7g6A._wUZrbhgcKXTkgf61PDfwRYnrELD(Single )
   at _XLNi2nAKDaXcz3srdrBuB2xYmjc._0WjOR0fDWNkJL8mpLKPBsPxraQC(Single )
   at _XLNi2nAKDaXcz3srdrBuB2xYmjc._gpzvT3PsruWCO1Iv52TVEHi8oOd(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _FsAlAxfye9Uuw09RBbOTpwVIpkC._RCCHTiRaWhQMGqyC5JPJSHBKOBb(_dPngusqOUg0pTQGSQE4bzhxiQ2O , String[] )
   at _7LVjtaeWAohJTwoa78wdtA8bDIJ._RCCHTiRaWhQMGqyC5JPJSHBKOBb(ThreadStart )
-------------------------------

```

**Comment by tyronx** [comment]
thanks for the report, this is fixed in the later pre-releases
