### ISSUE TITLE
Crash on opening application

### ISSUE THREAD

**Issue by Devilofether** [anegostudios/VintageStory-Issues#567]
**Game Version:** 1.13.0-rc.2
**Platform:** Windows
**Modded:** No

### Description:
The game crashes before opening properly, more specifically while loading shaders

### How to reproduce:
open the application

### Log:
```Running on 64 bit Windows with 16 GB RAM 
Version: v1.13.0-rc.2 (Unstable)13/08/2020 9:54:49 PM: Critical error occurred
System.Exception: GL_INVALID_VALUE error generated. Program handle does not refer to an object generated by OpenGL.
   at Vintagestory.Client.NoObf.ClientPlatformWindows.DebugCallback(DebugSource source, DebugType type, Int32 id, DebugSeverity severity, Int32 length, IntPtr message, IntPtr userParam)
   at OpenTK.Graphics.OpenGL.GL.GetUniformLocation(Int32 program, String name)
   at Vintagestory.Client.NoObf.ShaderProgram.Compile()
   at Vintagestory.Client.NoObf.ShaderRegistry.loadRegisteredShaderPrograms()
   at _dDHBYiuaTAUU3xN8s9I9j2BZwsT._vK8A7ulNEn4XG3ZDYQ5fT6kEbgp()
   at _HEDNRciSqRiA2rGAor2NGnYDqTG._FmLcKiS485SWAaM6QkwDcYFONMr(Single )
   at _dDHBYiuaTAUU3xN8s9I9j2BZwsT._No4bwDQNOOzBdLQRwbHXNsSqKC9(Single )
   at _dDHBYiuaTAUU3xN8s9I9j2BZwsT._Avo57EhsJoIcfXffuNR2NTBCY31(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _mJVDMTN2r0ABLs8tOUW1Hjdnpa1._e07gVZcAb5YH01LfLcd3TIuq2FtA(_PzFBod3PyjjUA7hYwmiyvdCntTb , String[] )
   at _hFDOpaYPD2hxg0BBe34QwVRcXFv._e07gVZcAb5YH01LfLcd3TIuq2FtA(ThreadStart )
-------------------------------
```

**Comment by Devilofether** [comment]
still happens on the new 1.13.0 stable release as well.

**Comment by copygirl** [comment]
Since this is a graphics related crash, can you tell us what graphics card and drivers you're using?

**Comment by Devilofether** [comment]
NVIDIA GeForce GTX 750 Ti
Driver date: 5/11/2015
Driver version: 10.18.13.5891

**Comment by Devilofether** [comment]
I solved the problem, I just needed to update my driver, for those wondering, my updated driver details are:
Driver date: 23/03/2018
Driver version: 23.21.13.9135
