### ISSUE TITLE
Error using the weather command in server

### ISSUE THREAD

**Issue by wilsonrost** [anegostudios/VintageStory-Issues#570]
**Game Version:** 1.13.0
**Platform:** Windows
**Modded:** No
### Description
Whilst playing a friend of mine kept getting crashes when the weather was prompting to change, however I didn't get the crash or any weather whatsoever. I then checked to the server to run the /weather command and I got this error.

I preformed a clean install to see if there was a glitch whilst updating and the issue persists.

### How to reproduce
1. Enter /weather in the server console
2. Error occurs

### Logs
20.8.2020 03:48:04 [Notification] Handling Command /weather 
20.8.2020 03:48:04 [Notification] An unhandled Exception was thrown while executing Command. Check error log.
20.8.2020 03:48:04 [Error] Player Admin/console caused an exception through a command.
20.8.2020 03:48:04 [Error] Command: /weather
20.8.2020 03:48:04 [Error] Arguments: 
20.8.2020 03:48:04 [Error] Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.WeatherSystemCommands.cmdWeatherServer(IServerPlayer player, Int32 groupId, CmdArgs args)
   at Vintagestory.Common.EventManager.TriggerChatCommand(IPlayer player, Int32 channelId, String command, CmdArgs args)
   at Vintagestory.Server.ServerMain.HandleCommand(IServerPlayer player, Int32 groupid, String command, String argument)
20.8.2020 03:48:04 [Error]    at Vintagestory.GameContent.WeatherSystemCommands.cmdWeatherServer(IServerPlayer player, Int32 groupId, CmdArgs args)
   at Vintagestory.Common.EventManager.TriggerChatCommand(IPlayer player, Int32 channelId, String command, CmdArgs args)
   at Vintagestory.Server.ServerMain.HandleCommand(IServerPlayer player, Int32 groupid, String command, String argument)

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in the stable version
