### ISSUE TITLE
Item from a mod crashes the game without the mod

### ISSUE THREAD

**Issue by Shionsan** [anegostudios/VintageStory-Issues#573]
**Game Version:** 1.13.0
**Platform:** Windows
**Modded:** Yes (https://www.vintagestory.at/forums/topic/1900-the-golden-wolf-v1034-the-partys-over/)

### Description
When you leave items from the mod (The Golden wolf) in your world, you won't be able to start the world without that mod.

### How to reproduce
1. Enable the mod
2. Place an item from this mod somewhere in the world
3. Disable the mod - game will crash when that item is in the vicinity

### Logs
25.8.2020 01:12:01 [Fatal] Caught unhandled exception in thread 'tesselateterrain'. Exiting game.
25.8.2020 01:12:01 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ChunkTesselator.GetFaceVisibilityFlags(Int32 tileSide, Int32 neighbourIndex3d)
   at Vintagestory.Client.NoObf.ChunkTesselator.CalculateVisibleFaces()
   at Vintagestory.Client.NoObf.ChunkTesselatorManager.TesselateChunk(Int32 chunkX, Int32 chunkY, Int32 chunkZ, Boolean priority)
   at Vintagestory.Client.NoObf.ChunkTesselatorManager.OnSeperateThreadGameTick(Single dt)
   at Vintagestory.Client.NoObf.ClientThread.Update()
   at Vintagestory.Client.NoObf.ClientThread.Process()

**Comment by tyronx** [comment]
thanks for the report, i assume this has been fixed by now, otherwise please reopen
