### ISSUE TITLE
Unhandled exception caused crash - no mods, latest version

### ISSUE THREAD

**Issue by clichnovsky** [anegostudios/VintageStory-Issues#580]
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.13.3 (Stable)9/8/2020 7:57:15 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.EntityItem.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntitySpawnPacket(_5GOHLI1CC5An2tjjVk1y4xkBUSk serverpacket)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _FrSmPmEETt213tDwMUqeNK9dUSf._VpXZ0z0s06I8pCopHym3flXsIvc(Single )
   at _CoPeQ63k4RZSnRnCfbwZncZiyNf._4B6WZ1ovaO4o2y2GHMno1cKVh4H(Single )
   at _CoPeQ63k4RZSnRnCfbwZncZiyNf._pIdpBAZ5sgW2oQCL6noq3KMOfOB(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _0fMjRHYAy4iVffofltqP0pIaiULA._DJ5LnALIS1Vge0eiSDg051jBzhp(_ej6xmfn8covhEe9L2UJYOcCVbEw , String[] )
   at _I8Vcm6hVwucecOsGYaKiAX3xKn6._DJ5LnALIS1Vge0eiSDg051jBzhp(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 9/8/2020 7:57:36 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.API.Common.EntityItem.FromBytes(System.IO.BinaryReader, Boolean)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntitySpawnPacket(_5GOHLI1CC5An2tjjVk1y4xkBUSk)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single)
   at _FrSmPmEETt213tDwMUqeNK9dUSf._VpXZ0z0s06I8pCopHym3flXsIvc(Single)
   at _CoPeQ63k4RZSnRnCfbwZncZiyNf._4B6WZ1ovaO4o2y2GHMno1cKVh4H(Single)
   at _CoPeQ63k4RZSnRnCfbwZncZiyNf._pIdpBAZ5sgW2oQCL6noq3KMOfOB(Single)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _0fMjRHYAy4iVffofltqP0pIaiULA._DJ5LnALIS1Vge0eiSDg051jBzhp(_ej6xmfn8covhEe9L2UJYOcCVbEw, System.String[])
   at _I8Vcm6hVwucecOsGYaKiAX3xKn6._DJ5LnALIS1Vge0eiSDg051jBzhp(System.Threading.ThreadStart)

 }
```

**Comment by copygirl** [comment]
Any idea what could have caused the crash? What did you do when this occurred?
It sounds like it has something to do with an item being crashed in the world. Did you drop an item?

**Comment by clichnovsky** [comment]
I was exploring when it happened, not breaking a block, dropping anything or eating.

**Comment by andrewpey** [comment]
I had the same error today. The world doesn't load.

That's what happened: I was digging some quartz blocks and the game suddenly froze. I waited some time and closed the game with Alt+F4. Now, every time I load the world, the game crashes with an error.

I wonder if there any way the world could be restored? Thank you for the wonderful game btw!

The error:

```
Running on 64 bit Windows with 16 GB RAM
Version: v1.13.3 (Stable)09.09.2020 21:01:16: Critical error occurred
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
в Vintagestory.API.Common.EntityItem.FromBytes(BinaryReader reader, Boolean forClient)
в Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntitySpawnPacket(_5GOHLI1CC5An2tjjVk1y4xkBUSk serverpacket)
в Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
в _FrSmPmEETt213tDwMUqeNK9dUSf._VpXZ0z0s06I8pCopHym3flXsIvc(Single )
в _CoPeQ63k4RZSnRnCfbwZncZiyNf._4B6WZ1ovaO4o2y2GHMno1cKVh4H(Single )
в _CoPeQ63k4RZSnRnCfbwZncZiyNf._pIdpBAZ5sgW2oQCL6noq3KMOfOB(Single )
в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
в OpenTK.GameWindow.DispatchRenderFrame()
в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
в _0fMjRHYAy4iVffofltqP0pIaiULA._DJ5LnALIS1Vge0eiSDg051jBzhp(_ej6xmfn8covhEe9L2UJYOcCVbEw , String[] )
в _I8Vcm6hVwucecOsGYaKiAX3xKn6._DJ5LnALIS1Vge0eiSDg051jBzhp(ThreadStart )
-----------------------------—

Event Log, last 3 entries
==================================
{ TimeGenerated = 23.08.2020 21:57:31, Site = , Source = .NET Runtime, Message = Приложение: Vintagestory.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за внутренней ошибки среды выполнения .NET по IP-адресу 000007FEDE7729E2 (000007FEDE580000) с кодом выхода 80131506.
}
```

**Comment by copygirl** [comment]
Does it help if you load the world in repair mode? To do that, click the Pencil in the world select screen, then "Run in Repair mode". Could be similar to #390, especially if, as @andrewpey says, it happens from the game unexpectedly closing.

**Comment by andrewpey** [comment]
Wow, this does help! Thank you a lot for such a helpful and fast response.

**Comment by clichnovsky** [comment]
I figured out the game was saving to my almost full hardrive despite me installing it on my other drive, and that caused the a crash that didn't make the crash report window pop up, and when i tried to load it back up is when i got the crash report window. After making room on the drive I tried again and it loaded up to a point where I had dropped a flint axe that was close to breaking, about an hour back from where the crash happened, and the game crashed again.

**Comment by tyronx** [comment]
did the repair mode also work for you? @clichnovsky

**Comment by copygirl** [comment]
@tyronx I also left this issue open because it might be worthwhile throwing in a check to see whether enough space is available to save the game (if possible) so 1. world corruption can be avoided and 2. the user gets a useful error.

**Comment by tyronx** [comment]
there is already a check, not sure why it didn't work for them :/
