### ISSUE TITLE
Crash in single player mode with error: something went awry, please check program log.

### ISSUE THREAD

**Issue by Emspara** [anegostudios/VintageStory-Issues#581]
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.13.3 (Stable)9/10/2020 10:37:42 PM: Critical error occurred
System.Exception: FBO BlurVerticalMedRes: There are no attachments.
   at Vintagestory.Client.NoObf.ClientPlatformWindows.CheckFboStatus(FramebufferTarget target, String fbtype)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.SetupDefaultFrameBuffers()
   at Vintagestory.Client.NoObf.ClientPlatformWindows.RebuildFrameBuffers()
   at Vintagestory.Client.NoObf.SystemScreenshot.takeMegaScreenshot(KeyCombination t1)
   at _4pQJlhiVj7d9I05CGUKWaaPLcXh._RHGtqMBwSPwPOD1AGrqMqZL8dVb(KeyEvent , IWorldAccessor , IPlayer , Boolean , Boolean , Boolean )
   at _4pQJlhiVj7d9I05CGUKWaaPLcXh._3XDXpAoDmFYVfxU9ZHBH3W7vmMi(KeyEvent , IWorldAccessor , IPlayer )
   at _CoPeQ63k4RZSnRnCfbwZncZiyNf._0HTkXRpLPpzD5ZqmGw76TUYsBDo(KeyEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(Object sender, KeyboardKeyEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnKeyDown(Key key, Boolean repeat)
   at OpenTK.Platform.Windows.WinGLNative.HandleKeyboard(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _0fMjRHYAy4iVffofltqP0pIaiULA._DJ5LnALIS1Vge0eiSDg051jBzhp(_ej6xmfn8covhEe9L2UJYOcCVbEw , String[] )
   at _I8Vcm6hVwucecOsGYaKiAX3xKn6._DJ5LnALIS1Vge0eiSDg051jBzhp(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 8/13/2020 9:50:48 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Graphics.OpenGL.GL.GenVertexArray()
   at Vintagestory.Client.NoObf.ClientPlatformWindows.UploadMesh(Vintagestory.API.Client.MeshData)
   at _mF8bOZItJBOhwSccLfb0LUqaTzK..ctor(Vintagestory.Client.NoObf.ClientPlatformAbstract)
   at _JXptEFjtbszRCFqIqGt0Pf6PpLb..ctor(_s54YxMQ8l5DBeihbmw81nJkPTSU)
   at _fttoiXnFXTb4HzoQpyTot0Qtmbd..ctor(_s54YxMQ8l5DBeihbmw81nJkPTSU)
   at _s54YxMQ8l5DBeihbmw81nJkPTSU._tyidesQGCE1oKHv8YEo8HwYCSty(_RxGTCHor7fqeGRNMEH5pZVfBHHK, System.String[])
   at _gilSYm6aSzOct8TKUm64HAM8OHp._tyidesQGCE1oKHv8YEo8HwYCSty(_RxGTCHor7fqeGRNMEH5pZVfBHHK, System.String[])
   at _xmrDk9pogtvR6xvbzmBc2dtFsbu._tyidesQGCE1oKHv8YEo8HwYCSty(System.Threading.ThreadStart)
   at _gilSYm6aSzOct8TKUm64HAM8OHp._ZoExSApIn1CvLIbxB8wFSJpix7A(System.String[])
```

**Comment by copygirl** [comment]
From the error it sounds like you might have tried to take a mega screenshot. Is that correct?

**Comment by Emspara** [comment]
No screenshot. Just tried to start the game...got that error...then it crashed...

**Comment by copygirl** [comment]
Ah, that's odd. According to the error there way a key press (`ClientPlatformWindows.game_KeyDown`), which the game recognized as the key combination to take a mega screenshot (`SystemScreenshot.takeMegaScreenshot`). Did this happen just once, or every game start? Does it crash before even getting to the main menu screen?

**Comment by Emspara** [comment]
The crash happened once. I cannot play a single player at all...the error
of something went awry please check program log. Multiplayer is
fine....just single player.

**Comment by tyronx** [comment]
Could you launch a single player world and then upload the client-main.txt and client-crash.txt one more time, please?

**Comment by tyronx** [comment]
no new info supplied in 2 months, closing for now
