### ISSUE TITLE
Single player, exploration, game crash

### ISSUE THREAD

**Issue by DancingHoskuld** [anegostudios/VintageStory-Issues#582]
Running on 64 bit Windows with 16 GB RAM 
Version: v1.13.4 (Stable)16/09/2020 10:31:49 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Datastructures.SyncedTreeAttribute.GetAttributeByPath(String path)
   at Vintagestory.API.Datastructures.SyncedTreeAttribute.PartialUpdate(String path, Byte[] data)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityAttributeUpdatePacket(_VavBQQYhBzsLJa8xzZ9ceiRuBkQ p)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityBulkAttributesPacket(_5JvvYf9KFEDVZitFymVPmMx6YcA packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _VtIDI6oYFpyEcQSZBFso9UVxS9aA._ZnYzeuHqveMMiEvOnpahncAMjfg(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._4BykKOCicJqCBHpyWIgTmxWrTrg(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._6XmOxKoTYrFLRCGd58p58XW43nD(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt , String[] )
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(ThreadStart )
-------------------------------

**Comment by tyronx** [comment]
Hi, thanks for the report, could you give me some detail as to when it happened and whether it is reproducible?

**Comment by DancingHoskuld** [comment]
It was my first time playing. I only lost a few seconds of game play
and it has not happened again. Sorry, I did not make a note of what I
was doing at the time. 

----- Original Message -----
