### ISSUE TITLE
Uh oh, Vintage Story has crashed

### ISSUE THREAD

**Issue by IBeeDad** [anegostudios/VintageStory-Issues#585]
Just bought an installed the game. It prompted me to restart my computer. It froze several times trying to restart. Finally, when I got the PC to boot up, I clicked to run the game and the screen flickered and this crash report popped up. I have a Gforce 1070 with the latest drivers. Plenty of hard drive space, and have run some of the most powerful games on this PC with no issues. I remember correctly I have at least 12 gigs of ram.

```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.13.3 (Stable)9/17/2020 4:53:55 PM: Critical error occurred
System.NotSupportedException: Your graphics card supports only OpenGL version 140 (1.40 - Intel Build 9.17.10.4459), but OpenGL version 330 is required.
Please check if you have installed the latest version of your graphics card driver. If they are, your graphics card may be to old to play Vintage Story.(Note: In case of modded gameplay with modded shaders, the mod author may be able to lower the OpenGL version requirements)
   at Vintagestory.Client.NoObf.Shader.EnsureVersionSupported(String versionUsed, String ownFilename)
   at Vintagestory.Client.NoObf.Shader.EnsureVersionSupported()
   at Vintagestory.Client.NoObf.ShaderProgram.Compile()
   at Vintagestory.Client.NoObf.ShaderRegistry.loadRegisteredShaderPrograms()
   at _CoPeQ63k4RZSnRnCfbwZncZiyNf._UvvbLjT6ArqC9ymlFbb6yswhrNG()
   at _l3QrkwTgaYl9NWjwaYHhJuZLM2G._eSJ2GvnRG3COpM42cK178DUUslE(Single )
   at _CoPeQ63k4RZSnRnCfbwZncZiyNf._4B6WZ1ovaO4o2y2GHMno1cKVh4H(Single )
   at _CoPeQ63k4RZSnRnCfbwZncZiyNf._pIdpBAZ5sgW2oQCL6noq3KMOfOB(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _0fMjRHYAy4iVffofltqP0pIaiULA._DJ5LnALIS1Vge0eiSDg051jBzhp(_ej6xmfn8covhEe9L2UJYOcCVbEw , String[] )
   at _I8Vcm6hVwucecOsGYaKiAX3xKn6._DJ5LnALIS1Vge0eiSDg051jBzhp(ThreadStart )
-------------------------------
```

**Comment by copygirl** [comment]
The screen flickering and crash message suggest that your graphics card driver crashed. This could be an issue with it, or your hardware. It is odd that your PC froze when restarting - the game does not affect that in any way.

If the issue persists, I'm wondering whether any other game using OpenGL has similar problems or if it's just Vintage Story. Only Minecraft comes to mind right now. I'm not sure I can recommend OpenGL benchmarks (like FurMark) which would likely push your graphics card or driver to crash, and you could find out quickly whether its related to that.

Hoping someone with more experience can weigh in.

**Comment by IBeeDad** [comment]
i got it resolved just now. My 2nd monitor was plugged into the onboard
graphics card for some reason. now it works! thanks

**Comment by copygirl** [comment]
That's good, I'm glad. Have fun with the game!
