### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by rock0head132** [anegostudios/VintageStory-Issues#586]
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.13.4 (Stable)9/17/2020 3:28:33 PM: Critical error occurred
System.MissingMethodException: Method not found: 'Void Vintagestory.API.Client.GuiElementDynamicText.SetNewText(System.String, Boolean, Boolean)'.
   at WaypointUtils.GuiDialogFloatyWaypoints.OnRenderGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _VtIDI6oYFpyEcQSZBFso9UVxS9aA._toICAyZ9EYSaLsmD4KTuQWUbqjP(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._4BykKOCicJqCBHpyWIgTmxWrTrg(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._6XmOxKoTYrFLRCGd58p58XW43nD(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt , String[] )
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(ThreadStart )
-------------------------------
```

**Comment by copygirl** [comment]
This suggests that you have a mod installed ([WaypointUtils / VSHUD](https://www.vintagestory.at/forums/topic/805-1133-vshud-1510-formerly-waypointutils/)) and it isn't compatible with the current version of the game.

**Comment by copygirl** [comment]
No response, will assume this is fixed.

**Comment by rock0head132** [comment]
sorry yes it was a mod.    On Wednesday, September 23, 2020, 02:45:10 AM MST, copygirl <notifications@github.com> wrote:  
 
 


No response, will assume this is fixed.
