### ISSUE TITLE
random crash after setting prospecting pick

### ISSUE THREAD

**Issue by Whentheblackmoonhowls** [anegostudios/VintageStory-Issues#612]
**Game Version:**1.13.4
**Platform:** Windows
**Modded:** yes but disabled. the cage mod for 1.13.4(which?)

### Description
just a random crash that keeps happening whenever i click on my world.

### How to reproduce
open up the game
click on single player
click on my world
crash

### Expected behavior
i expected the world to open

### Screenshots
n/a

### Logs
```
Paste crash here.

Running on 64 bit Windows with 8 GB RAM 
Version: v1.13.4 (Stable)10/16/2020 4:47:32 PM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.Client.NoObf.HudHotbar.UpdateCurrentToolMode(Int32 newSlotIndex)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _VtIDI6oYFpyEcQSZBFso9UVxS9aA._ZnYzeuHqveMMiEvOnpahncAMjfg(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._4BykKOCicJqCBHpyWIgTmxWrTrg(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._6XmOxKoTYrFLRCGd58p58XW43nD(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt , String[] )
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 10/16/2020 4:47:32 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException
   at Vintagestory.Client.NoObf.HudHotbar.UpdateCurrentToolMode(Int32)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64, Vintagestory.API.Common.IWorldAccessor)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single)
   at _VtIDI6oYFpyEcQSZBFso9UVxS9aA._ZnYzeuHqveMMiEvOnpahncAMjfg(Single)
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._4BykKOCicJqCBHpyWIgTmxWrTrg(Single)
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._6XmOxKoTYrFLRCGd58p58XW43nD(Single)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt, System.String[])
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(System.Threading.ThreadStart)

 }
{ TimeGenerated = 10/14/2020 6:09:48 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFF05233E49
Stack:
   at System.Environment._Exit(Int32)
   at System.Environment._Exit(Int32)
   at System.Environment.Exit(Int32)
   at _tbDNSZpN0b4WGkPbXXfou7PhsQl._4FaQHZNbeHKn9WINUsvqvFV8i9T()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(Vintagestory.API.Client.MouseEvent)
   at _VisI2OeWzgjAMuHLDUPaKaN5Lds._6J0Ioc1Jsh7Nj2siLiS88rTI5Ze(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(System.Object, OpenTK.Input.MouseButtonEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double, Double)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt, System.String[])
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(System.Threading.ThreadStart)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._k39DsboSFqAvcX2gaWs5Tk5Zl6Q(System.String[])
 }
```

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in pre.2. Be sure to use a valid number when configuring the propick via /worldConfig
