### ISSUE TITLE
Using Copper Scyte Causes CTD

### ISSUE THREAD

**Issue by Viss85** [anegostudios/VintageStory-Issues#625]
**Game Version:** 1.14.0-pre3
**Platform:** Windows 10
**Modded:** Yes

### Description
Using the copper scythe in a fort ruin to clear out grass causes CTD.
### How to reproduce
1. Find a fortress ruin with grass.
2. Use a copper scythe to clear grass.
3. It crashes.

### Logs
```
PRunning on 64 bit Windows with 16 GB RAM 
Version: v1.14.0-pre.3 (Unstable)10/25/2020 9:49:23 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemScythe.OnHeldAttackStep(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSelection, EntitySelection entitySel)
   at Vintagestory.API.Common.CollectibleObject.OnHeldUseStep(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _mO1OMh8kncBt6cjOWOIAi4uKXfh._tqCBmo91Iso0C6Z4MxE3pGk9BGm(Single )
   at _bLYKVt0OIIpbDM9s6d78wEvV4kh._T6ntkYAYy93JTmMeUW5BPEb2H9g(Single )
   at _bLYKVt0OIIpbDM9s6d78wEvV4kh._9wnG1I0dv2nE1qiCj4WtSykSuSBA(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _Af9KcMdBp4FV1bF3d63CYMzaRzM._hX3i5Vm8yHkCuhYPtFN3CuEBTRN(_Ky6UZsVVbxXy26d1FTibdLqrMyI , String[] )
   at _slFJfYF3pqJDCES83egtGxsoWTD._hX3i5Vm8yHkCuhYPtFN3CuEBTRN(ThreadStart )
-------------------------------
```

**Comment by tyronx** [comment]
thanks, fixed in pre4
