### ISSUE TITLE
Chiseling wood planks or stone paths crashes the game

### ISSUE THREAD

**Issue by NNx3** [anegostudios/VintageStory-Issues#630]
**Game Version:** v1.14.0-pre.3 (Unstable)
**Platform:** Windows
**Modded:** No 

### Description
Chiseling wood planks or stone paths crashes the game. Logs and regular stone blocks seem to be fine. Other blocks might cause this issue as well. (new to chiseling and the game in general btw so idk what usually chisel-able)

### How to reproduce
1. Make a 'Copper Chisel'
2. Use it on 'Pine/Maple/Any(?) Wood Planks' or 'Stone Path'
3. It crashes 

### Expected behavior
Expected to make chisel-able and probably not crash

### Screenshots
-

### Logs
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.14.0-pre.3 (Unstable)11/1/2020 1:37:22 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemChisel.IsChiselingAllowedFor(Block block, IPlayer player)
   at Vintagestory.GameContent.ItemChisel.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _mO1OMh8kncBt6cjOWOIAi4uKXfh._AEJH1xJpbVe88FAaFJiyfr66rYN(Single )
   at _bLYKVt0OIIpbDM9s6d78wEvV4kh._T6ntkYAYy93JTmMeUW5BPEb2H9g(Single )
   at _bLYKVt0OIIpbDM9s6d78wEvV4kh._9wnG1I0dv2nE1qiCj4WtSykSuSBA(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _Af9KcMdBp4FV1bF3d63CYMzaRzM._hX3i5Vm8yHkCuhYPtFN3CuEBTRN(_Ky6UZsVVbxXy26d1FTibdLqrMyI , String[] )
   at _slFJfYF3pqJDCES83egtGxsoWTD._hX3i5Vm8yHkCuhYPtFN3CuEBTRN(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 11/1/2020 12:35:05 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.GameContent.ItemChisel.IsChiselingAllowedFor(Vintagestory.API.Common.Block, Vintagestory.API.Common.IPlayer)
   at Vintagestory.GameContent.ItemChisel.OnHeldInteractStart(Vintagestory.API.Common.ItemSlot, Vintagestory.API.Common.EntityAgent, Vintagestory.API.Common.BlockSelection, Vintagestory.API.Common.EntitySelection, Boolean, Vintagestory.API.Common.EnumHandHandling ByRef)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(Vintagestory.API.Common.BlockSelection, Vintagestory.API.Common.EntitySelection, Vintagestory.API.Common.EnumHandInteract, Vintagestory.API.Common.EnumHandHandling ByRef)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(Vintagestory.API.Common.BlockSelection, Vintagestory.API.Common.EntitySelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single)
   at _mO1OMh8kncBt6cjOWOIAi4uKXfh._AEJH1xJpbVe88FAaFJiyfr66rYN(Single)
   at _bLYKVt0OIIpbDM9s6d78wEvV4kh._T6ntkYAYy93JTmMeUW5BPEb2H9g(Single)
   at _bLYKVt0OIIpbDM9s6d78wEvV4kh._9wnG1I0dv2nE1qiCj4WtSykSuSBA(Single)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _Af9KcMdBp4FV1bF3d63CYMzaRzM._hX3i5Vm8yHkCuhYPtFN3CuEBTRN(_Ky6UZsVVbxXy26d1FTibdLqrMyI, System.String[])
   at _slFJfYF3pqJDCES83egtGxsoWTD._hX3i5Vm8yHkCuhYPtFN3CuEBTRN(System.Threading.ThreadStart)

 }
{ TimeGenerated = 11/1/2020 12:20:31 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.GameContent.ItemChisel.IsChiselingAllowedFor(Vintagestory.API.Common.Block, Vintagestory.API.Common.IPlayer)
   at Vintagestory.GameContent.ItemChisel.OnHeldInteractStart(Vintagestory.API.Common.ItemSlot, Vintagestory.API.Common.EntityAgent, Vintagestory.API.Common.BlockSelection, Vintagestory.API.Common.EntitySelection, Boolean, Vintagestory.API.Common.EnumHandHandling ByRef)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(Vintagestory.API.Common.BlockSelection, Vintagestory.API.Common.EntitySelection, Vintagestory.API.Common.EnumHandInteract, Vintagestory.API.Common.EnumHandHandling ByRef)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(Vintagestory.API.Common.BlockSelection, Vintagestory.API.Common.EntitySelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single)
   at _mO1OMh8kncBt6cjOWOIAi4uKXfh._AEJH1xJpbVe88FAaFJiyfr66rYN(Single)
   at _bLYKVt0OIIpbDM9s6d78wEvV4kh._T6ntkYAYy93JTmMeUW5BPEb2H9g(Single)
   at _bLYKVt0OIIpbDM9s6d78wEvV4kh._9wnG1I0dv2nE1qiCj4WtSykSuSBA(Single)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _Af9KcMdBp4FV1bF3d63CYMzaRzM._hX3i5Vm8yHkCuhYPtFN3CuEBTRN(_Ky6UZsVVbxXy26d1FTibdLqrMyI, System.String[])
   at _slFJfYF3pqJDCES83egtGxsoWTD._hX3i5Vm8yHkCuhYPtFN3CuEBTRN(System.Threading.ThreadStart)

 }
```

**Comment by tyronx** [comment]
thanks for the report, should be fixed in pre.4 and later
