### ISSUE TITLE
Placing items in a barrel crashes the game.

### ISSUE THREAD

**Issue by Medasian** [anegostudios/VintageStory-Issues#632]
**Game Version:** 1.14.0-pre3
**Platform:** Windows
**Modded:** No

### Description
Placing items (or at least quicklime and sticks) in a barrel crashes the game. Server seems to handle it fine, but the client crashes, both me and my friend had the same issue.

### How to reproduce
Place something in a barrel (Only tried quicklime and sticks though). Not sure if it affects other items, but I tried 40 quicklime in a barrel with 10 liters of water, 64 in a barrel with 50 liters of water, 1 quicklime in an empty barrel, and 1 stick in an empty barrel.

### Expected behavior
Pretty self-explanatory. Should be able to place quicklime in a barrel of water, to make slaked-lime.

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.0-pre.3 (Unstable)11/2/2020 00:10:12: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.ItemSlotBarrelInput.OnItemSlotModified(ItemStack stack)
   at Vintagestory.API.Common.ItemSlot.TryPutInto(ItemSlot sinkSlot, ItemStackMoveOperation& op)
   at Vintagestory.Common.PlayerInventoryManager.TryTransferAway(ItemSlot sourceSlot, ItemStackMoveOperation& op, Boolean onlyPlayerInventory, Boolean slotNotifyEffect)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse)
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs)
   at Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _Af9KcMdBp4FV1bF3d63CYMzaRzM._hX3i5Vm8yHkCuhYPtFN3CuEBTRN(_Ky6UZsVVbxXy26d1FTibdLqrMyI , String[] )
   at _slFJfYF3pqJDCES83egtGxsoWTD._hX3i5Vm8yHkCuhYPtFN3CuEBTRN(ThreadStart )
-------------------------------
```

**Comment by tyronx** [comment]
thanks for the report, this is fixed in pre4/pre5
