### ISSUE TITLE
game will not launch

### ISSUE THREAD

**Issue by mrmerch2017** [anegostudios/VintageStory-Issues#634]
Running on 64 bit Windows with 16 GB RAM 
Version: v1.13.4 (Stable)

```
11/2/2020 5:21:19 PM: Critical error occurred
System.IO.IOException: The file or directory is corrupted and unreadable.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.Directory.GetDirectories(String path)
   at Vintagestory.Common.PathOrigin.ScanAssetFolderRecursive(String currentPath, List`1 list, Boolean shouldLoad)
   at Vintagestory.Common.PathOrigin.GetAssets(AssetCategory Category, Boolean shouldLoad)
   at Vintagestory.Common.AssetManager.GetAssetsDontLoad(AssetCategory category, List`1 fromOrigins)
   at Vintagestory.Common.AssetManager.InitAndLoadBaseAssets(ILogger Logger)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.LoadAssets()
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._T1cjQmXzSN3hXzPMPsuMGay1MAG()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
-------------------------------
```

**Comment by copygirl** [comment]
According to [the results I found searching for this error message](https://duckduckgo.com/?q="The+file+or+directory+is+corrupted+and+unreadable."), this is not something related to the game. The general suggestion appears to be running `ChkDsk` (on the drive that the game is installed on) - see the search results for how to do this. This should fix any issues that Windows believes there is with the drive. One of the reasons this could occur is the drive failing, so I would recommend looking into backing up important data.
