### ISSUE TITLE
Crash after taking brine from a barrel with bucket

### ISSUE THREAD

**Issue by Xythis** [anegostudios/VintageStory-Issues#635]
**Game Version:** X.Y.Z
**Platform:** Windows / Mac / Linux (which?)
**Modded:** No / Yes (which?)

### Description
The game crashed when I took some brine into a bucket from a barrel and then tried to open the barrel again.

### How to reproduce
1. Make brine in a barrel
2. Take some out with a bucket
3. Right click on barrel to look in it

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.13.4 (Stable)11/3/2020 7:19:31 PM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockBarrel.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target)
   at Vintagestory.Client.NoObf.SystemRenderHeldItem.RenderFpHandItem(ItemSlot inSlot, Boolean left, Single dt)
   at Vintagestory.Client.NoObf.SystemRenderHeldItem.OnRender3dOpaque(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _VtIDI6oYFpyEcQSZBFso9UVxS9aA._ZnYzeuHqveMMiEvOnpahncAMjfg(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._4BykKOCicJqCBHpyWIgTmxWrTrg(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._6XmOxKoTYrFLRCGd58p58XW43nD(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt , String[] )
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(ThreadStart )
-------------------------------

```

**Comment by Craluminum2413** [comment]
I don't know when it was fixed. But in 1.15 it don't crash for me because of this

**Comment by copygirl** [comment]
Will close for now, then. The issue wasn't even filled out properly. Open a new issue if this still occurs.
