### ISSUE TITLE
World broke after sudden power  outage

### ISSUE THREAD

**Issue by Kahoosh** [anegostudios/VintageStory-Issues#636]
**Game Version:** 1.13.4
**Platform:** Windows
**Modded:** Yes; carrycapacity, extra chests, HUD clock, workbench expansion

### Description
After a sudden power outage I am unable to load the world I was playing on at the time. Removing mods didn't work and other worlds are loading just fine. This isn't the first power outage to happen whilst playing on this world and it would usually load normally. However, this is the first power outage after installing mods.

### How to reproduce
1. Unsure, but try starting a world without mods, play, add mods, play more and turn the power off, try loading the world.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.13.4 (Stable)5.11.2020. 13:12:02: Critical error occurred
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.MemoryStream.InternalReadInt32()
   at Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.API.Common.EntityPlayer.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.Client.NoObf.ClientSystemEntities.createOrUpdateEntityFromPacket(_QZrkPDkApxKITNHv7gQ8CjGzfic entitypacket, ClientMain game, Boolean addToLoadQueue)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityLoadedPacket(_5JvvYf9KFEDVZitFymVPmMx6YcA serverpacket)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _FVGd1lrg8990jw7ZGueNjtrnCWl._toICAyZ9EYSaLsmD4KTuQWUbqjP(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._4BykKOCicJqCBHpyWIgTmxWrTrg(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._6XmOxKoTYrFLRCGd58p58XW43nD(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt , String[] )
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(ThreadStart )
-------------------------------

```

**Comment by Kahoosh** [comment]
running in repair mode fixed it
