### ISSUE TITLE
1.14.0 pre4 quicklime crash

### ISSUE THREAD

**Issue by EtherialMind** [anegostudios/VintageStory-Issues#637]
**Game Version:** 1.14.0pre4
**Platform:** Windows 
**Modded:** Yes 
Trail food
Temporal Tinkerer 2.1.0
Better Archery
Better Backpacks 1.0
Better Drifters Loot only 1.0.0
Better Poultice
Capture Animals 1.1.1
Creativeables 1.0.0
ExtraChest 1.0.0
FancyTools 0.1
Full Drop 1.0.0
More recipes 1.3.2
OreCrystals 1.2.0
PrimitiveSurvival 1.3.0
SuperFuel 1.0.0
TpTools 0.2
Workbench expansion 1.1.0

### Description
when placing quicklime into a barrel full of water the game crashes.

### How to reproduce
1. Make a quicklime
2. try to place it or shift-click it into a barrel full of water
3. It crashes

### Logs
Version: v1.14.0-pre.4 (Unstable)11/6/2020 2:27:05 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.ItemSlotBarrelInput.OnItemSlotModified(ItemStack stack)
   at Vintagestory.API.Common.ItemSlot.TryPutInto(ItemSlot sinkSlot, ItemStackMoveOperation& op)
   at Vintagestory.Common.PlayerInventoryManager.TryTransferAway(ItemSlot sourceSlot, ItemStackMoveOperation& op, Boolean onlyPlayerInventory, Boolean slotNotifyEffect)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse)
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs)
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _60EaReGt92MlFYmPfhqFxtFLnxD._HqNZ30YDnGsahL6bWBhPYPsw11k(_d8i4uXwdOmBUlVOHqZOzFmROq8D , String[] )
   at _1DS29Qw06IDvcgkzdyBmfLZ2sGf._HqNZ30YDnGsahL6bWBhPYPsw11k(ThreadStart )

**Comment by tyronx** [comment]
thanks for the report, already fixed in pre5
