### ISSUE TITLE
Tried to place a stack of anthracite game crash.

### ISSUE THREAD

**Issue by jonnypotseed** [anegostudios/VintageStory-Issues#638]
Game Version 1.14.pre4
Platform: Win 10
No mods 

Description
Tried to place a stack of anthracite and the game crashes at 5 partial stacks.

Logs

```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.0-pre.4 (Unstable)11/7/2020 3:28:52 PM: Critical error occurred
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Vintagestory.GameContent.BlockEntityCoalPile.get_Item(String textureCode)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(Int32 indexForLogging, MeshData meshdata, ShapeElement element, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(Shape shapeBase, MeshData& modeldata, Vec3f wholeMeshRotation, Vec3f wholeMeshOffset, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(String typeForLogging, Shape shapeBase, MeshData& modeldata, ITexPositionSource texSource, Vec3f wholeMeshRotation, Int32 generalGlowLevel, Byte climateColorMapId, Byte seasonColorMapId, Nullable`1 quantityElements, String[] selectiveElements)
   at Vintagestory.GameContent.BlockEntityCoalPile.OnTesselation(ITerrainMeshPool mesher, ITesselatorAPI tessThreadTesselator)
   at Vintagestory.GameContent.EntityBlockFallingRenderer..ctor(Entity entity, ICoreClientAPI api)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Vintagestory.Common.ClassRegistry.CreateEntityRenderer(String className, Object[] args)
   at Vintagestory.Client.NoObf.ClientSystemEntities.OnEntitySpawnOrLoaded(Entity entity, Boolean loaded)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerEntitySpawn(Entity entity)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntitySpawnPacket(_BI776dKHcKfCgOdsEePj50fqcby serverpacket)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _VKV8aPSHqjJZsKOc7Dte5PIJ98L._WgQSD5ggchxod76yBhv9koZLL5p(Single )
   at _FySaiBPbgZigObkPkliM8iBKEuu._8mmOpgccyI3ufYkRk3edRqZRsFR(Single )
   at _FySaiBPbgZigObkPkliM8iBKEuu._eElDi0JvWueOnTUIekuJRMPYcWK(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _60EaReGt92MlFYmPfhqFxtFLnxD._HqNZ30YDnGsahL6bWBhPYPsw11k(_d8i4uXwdOmBUlVOHqZOzFmROq8D , String[] )
   at _1DS29Qw06IDvcgkzdyBmfLZ2sGf._HqNZ30YDnGsahL6bWBhPYPsw11k(ThreadStart )
-------------------------------
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Vintagestory.GameContent.BlockEntityCoalPile.get_Item(String textureCode)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(Int32 indexForLogging, MeshData meshdata, ShapeElement element, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(Shape shapeBase, MeshData& modeldata, Vec3f wholeMeshRotation, Vec3f wholeMeshOffset, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(String typeForLogging, Shape shapeBase, MeshData& modeldata, ITexPositionSource texSource, Vec3f wholeMeshRotation, Int32 generalGlowLevel, Byte climateColorMapId, Byte seasonColorMapId, Nullable`1 quantityElements, String[] selectiveElements)
   at Vintagestory.GameContent.BlockEntityCoalPile.OnTesselation(ITerrainMeshPool mesher, ITesselatorAPI tessThreadTesselator)
   at Vintagestory.GameContent.EntityBlockFallingRenderer..ctor(Entity entity, ICoreClientAPI api)
```

**Comment by tyronx** [comment]
thanks for the report, this should be fixed for the upcoming pre.8
