### ISSUE TITLE
(1.14.0-pre.8) Crash on smithing-hitting a drifter?

### ISSUE THREAD

**Issue by PaulMisto** [anegostudios/VintageStory-Issues#644]
**Game Version:** 1.14.0-pre.8
**Platform:** Windows 10
**Modded:** Yes 

-ProspectorInfo v.2.0.0
-Simple HUD Clock v.2.2.1
-CarryCapacity v.5.0.0

### Description
I was smithing a copper ingot into 9 arrow heads onto a tin bronze anvil with a copper hammer at night, then a a drifter came out of nowhere and scared the living crap out of me and I think from the animation of moving a voxel from smithing I moved the cursor to hit the drifter, then it crashed

### Crash Log:
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.0-pre.8 (Unstable)16-Nov-20 14:19:44: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemHammer.OnHeldAttackStep(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSelection, EntitySelection entitySel)
   at Vintagestory.API.Common.CollectibleObject.OnHeldUseStep(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _VqiJI4DuKgpvydF62e56wP5mRiB._AgvaoVKaZHFSJjs3eINVKRWllvL(Single )
   at _GApKBQhf7bW5aVoKRSUGDZ1viKaA._rMGmCn7H96mcFo2cP4QmrT5sSmv(Single )
   at _GApKBQhf7bW5aVoKRSUGDZ1viKaA._eS99Txb8gRTWDbJkLRADvc56KqX(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _wRmJCunGLReBEeuv2ORdxS5rsYe._QA4Fg8ecmiKIQ8f6a4VDbpaut44A(_s9PM9DCMG5px7dCqSuuZFFSkn3c , String[] )
   at _ELzVGXP3i3cN7BhAWMfuM85U9tL._QA4Fg8ecmiKIQ8f6a4VDbpaut44A(ThreadStart )
-------------------------------
```

NOTE: After this, I went back in the world(it rolled me back in time a few hours, possibly to avoid corruption or smth like that idk) and then I tried to reproduce the exact same thing and it crashed again. **Hitting a worked item that's on an anvil with the hammer, then immediately switching to a drifter crashes.**

**Comment by copygirl** [comment]
Thank you for taking the time to reproduce this!

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in the rcs
