### ISSUE TITLE
Character Inventory Crash

### ISSUE THREAD

**Issue by VampireSquids** [anegostudios/VintageStory-Issues#650]
**Game Version:** 1.14.0 -pre 10
**Platform:** Windows 
**Modded:** Yes, GraveMod-2.1.1

When I attempt to open the character inventory the game crashes.  The bug only occurs in a world I updated from 1.13.4 both of which are modified with the same version of GraveMod.  Could not reproduce the bug in newly generated world.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.0-pre.10 (Unstable)11/18/2020 8:29:04 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntitySkinnableShapeRenderer.reloadSkin()
   at Vintagestory.GameContent.EntitySkinnableShapeRenderer.TesselateShape()
   at Vintagestory.GameContent.EntityShapeRenderer.PrepareForGuiRender(Single dt, Double posX, Double posY, Double posZ, Single yawDelta, Single size, MeshRef& meshRef, Single[]& modelviewMatrix)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderEntityToGui(Single dt, Entity entity, Double posX, Double posY, Double posZ, Single yawDelta, Single size, Int32 color)
   at Vintagestory.Client.NoObf.GuiDialogCharacter.OnRenderGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _7xlAfqflmyNWQv9mVdG48hrpRSs._aS86li9lQseS1QuGss8Xk344pYB(Single )
   at _WkjmC8j5TRq5FD4fN3IUAMzFQ5L._iYRGZcQFGGVxdrosCcPtkE6CagN(Single )
   at _WkjmC8j5TRq5FD4fN3IUAMzFQ5L._jP7cEUjgzwgxB0CAyZR3nm08s6K(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _ags0bIdhXbC5vqeEZ91JzIwuHNk._YceH1Dy6Vz88mNkEBfGjgoBMUtc(_2SIgCmQkGsBtYr1pBzpXEZcFKLW , String[] )
   at _5o400u19YmSeZDrcQK6AS4zfvaV._YceH1Dy6Vz88mNkEBfGjgoBMUtc(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 10/29/2020 5:15:33 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at _Af9KcMdBp4FV1bF3d63CYMzaRzM._IWVwq2h8Vg0v4mDwj9M5iZwnxPc(System.String[])

 }
{ TimeGenerated = 10/29/2020 5:15:25 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at _Af9KcMdBp4FV1bF3d63CYMzaRzM._IWVwq2h8Vg0v4mDwj9M5iZwnxPc(System.String[])

 }
```

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in the latest rc's
