### ISSUE TITLE
"Failed loading bitmap from png file" Crash upon loading a world

### ISSUE THREAD

**Issue by Ryorama** [anegostudios/VintageStory-Issues#651]
**Game Version:** All
**Platform:** Windows
**Modded:** No

### Description
When ever I try to login to a world, the window will go black and will go back and forth from responding and not responding. About a minute later, the game crashes with no crash report.

### How to reproduce
1. Make a new world or load into an existing world.
2. When it loads, the screen goes black and eventually crashed with no crash report

### Expected behavior
It's suppose to load the world for me to play.

### Logs
While there was no crash report, I did manage to find this in the log file:
```
9.11.2020 11:21:22 [Error] Failed loading bitmap from png file: System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Stream stream)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.BitmapCreateFromPng(Byte[] data, Int32 dataLength). Will default to an empty 1x1 bitmap.
9.11.2020 11:21:22 [Warning] Texture game:textures/item/resource/resonancearchives/3.png width is not divisible by 4, will probably glitch when mipmapped
9.11.2020 11:21:22 [Error] Failed loading bitmap from png file: System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Stream stream)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.BitmapCreateFromPng(Byte[] data, Int32 dataLength). Will default to an empty 1x1 bitmap.
9.11.2020 11:21:22 [Warning] Texture game:textures/item/resource/resonancearchives/5.png width is not divisible by 4, will probably glitch when mipmapped
9.11.2020 11:21:22 [Error] Failed loading bitmap from png file: System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Stream stream)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.BitmapCreateFromPng(Byte[] data, Int32 dataLength). Will default to an empty 1x1 bitmap.
9.11.2020 11:21:22 [Warning] Texture game:textures/item/resource/resonancearchives/6.png width is not divisible by 4, will probably glitch when mipmapped
9.11.2020 11:21:22 [Error] Failed loading bitmap from png file: System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Stream stream)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.BitmapCreateFromPng(Byte[] data, Int32 dataLength). Will default to an empty 1x1 bitmap.
9.11.2020 11:21:22 [Warning] Texture game:textures/item/resource/resonancearchives/7.png width is not divisible by 4, will probably glitch when mipmapped
9.11.2020 11:21:22 [Notification] Loaded 4989 block types from server
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
