### ISSUE TITLE
Crash on new creative world

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#656]
**Game Version:** v1.14-pre.12
**Platform:** Windows 
**Modded:** No 

### Description
Crash on creative world load for the first time after updating. Looks like it related to old chiseled blocks.

### How to reproduce
1. Make a new creative world in v14

### Logs
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.14.0-pre.12 (Unstable)11/22/2020 8:52:47 PM: Critical error occurred
System.TypeLoadException: Could not load type 'Vintagestory.ServerMods.ChiselBlockModelCache' from assembly 'VSSurvivalMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at VSHUD.PlacementRenderer.UpdateBlockMesh(Block toBlock, BlockPos altPos)
   at VSHUD.PlacementRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _N4nDLuymVlKT54yMf6r5eypdlNv._CW6bgwH0lbdtsdYyO76HdHdvOgg(Single )
   at _Clh9e9kpEz0RDtNUZFtTbGdnwNC._qXPu7jXmWoOyt7PSpddkMCsAikc(Single )
   at _Clh9e9kpEz0RDtNUZFtTbGdnwNC._tPTTX5aXHvocPdbQVKnvU0tPwmD(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _sci3tTeaioCntaWreFrjdJgav9v._1n2qGs9GZdzqu1Xw6Ehbbz74gfB(_moGYwxDmPsQDO4tat0Am1XyMmFj , String[] )
   at _PK8XvbG8PiVa6K9TSNEBcuaGUii._1n2qGs9GZdzqu1Xw6Ehbbz74gfB(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 11/22/2020 8:16:41 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFC7C9B3B29
Stack:
   at System.Environment._Exit(Int32)
   at System.Environment._Exit(Int32)
   at System.Environment.Exit(Int32)
   at _tbDNSZpN0b4WGkPbXXfou7PhsQl._4FaQHZNbeHKn9WINUsvqvFV8i9T()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(Vintagestory.API.Client.MouseEvent)
   at _VisI2OeWzgjAMuHLDUPaKaN5Lds._6J0Ioc1Jsh7Nj2siLiS88rTI5Ze(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(System.Object, OpenTK.Input.MouseButtonEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double, Double)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt, System.String[])
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(System.Threading.ThreadStart)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._k39DsboSFqAvcX2gaWs5Tk5Zl6Q(System.String[])
 }
```

**Comment by sirStroam** [comment]
`Running on 64 bit Windows with 8 GB RAM 
Version: v1.14.0-pre.12 (Unstable)11/22/2020 9:05:17 PM: Critical error occurred
System.TypeLoadException: Could not load type 'Vintagestory.ServerMods.ChiselBlockModelCache' from assembly 'VSSurvivalMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at VSHUD.PlacementRenderer.UpdateBlockMesh(Block toBlock, BlockPos altPos)
   at VSHUD.PlacementRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _N4nDLuymVlKT54yMf6r5eypdlNv._CW6bgwH0lbdtsdYyO76HdHdvOgg(Single )
   at _Clh9e9kpEz0RDtNUZFtTbGdnwNC._qXPu7jXmWoOyt7PSpddkMCsAikc(Single )
   at _Clh9e9kpEz0RDtNUZFtTbGdnwNC._tPTTX5aXHvocPdbQVKnvU0tPwmD(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _sci3tTeaioCntaWreFrjdJgav9v._1n2qGs9GZdzqu1Xw6Ehbbz74gfB(_moGYwxDmPsQDO4tat0Am1XyMmFj , String[] )
   at _PK8XvbG8PiVa6K9TSNEBcuaGUii._1n2qGs9GZdzqu1Xw6Ehbbz74gfB(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 11/22/2020 8:16:41 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFC7C9B3B29
Stack:
   at System.Environment._Exit(Int32)
   at System.Environment._Exit(Int32)
   at System.Environment.Exit(Int32)
   at _tbDNSZpN0b4WGkPbXXfou7PhsQl._4FaQHZNbeHKn9WINUsvqvFV8i9T()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(Vintagestory.API.Client.MouseEvent)
   at _VisI2OeWzgjAMuHLDUPaKaN5Lds._6J0Ioc1Jsh7Nj2siLiS88rTI5Ze(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(System.Object, OpenTK.Input.MouseButtonEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double, Double)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt, System.String[])
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(System.Threading.ThreadStart)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._k39DsboSFqAvcX2gaWs5Tk5Zl6Q(System.String[])
 }`

**Comment by tyronx** [comment]
thanks for the report buts that is a crash from the 3rd party mod VSHUD, please report that to novocain

**Comment by sirStroam** [comment]
Didn't realize. Thanks
