### ISSUE TITLE
Crashing Upon mining with Prospecting Pick

### ISSUE THREAD

**Issue by BigGuyForYou** [anegostudios/VintageStory-Issues#657]
**Game Version:**  v1.14.0-rc.1
**Platform:** Windows 
**Modded:** No 

### Description
Game crashes upon using a Prospecting Pick either mode without the chat open

### How to reproduce
1. Have chat closed via tab
2. Mine any block with a prospecting pick of any kind 
3, crash

Does not crash and works intently if chat is open, does not have to have the info log open just a chat log.  
### Logs
```
Multiplayer Crash on my server
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.0-rc.1 (Unstable)11/23/2020 2:00:19 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.HudDialogChat.UpdateText()
   at Vintagestory.Client.NoObf.HudDialogChat.OnTabClicked(Int32 groupId)
   at Vintagestory.Client.NoObf.HudDialogChat.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.GuiManager.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _5hCAkcR0qGwiw0p1Od3dkPNJr9m._k0IPcsxgDzTj2TKJ7rcHT9FrHio(Single )
   at _FaGPIoRIMmPde5LK617lMxGGqKO._ew8jFTkG0bv7vcU0TlSh3xJDYqG(Single )
   at _FaGPIoRIMmPde5LK617lMxGGqKO._hnsBUFFLbZEdYv6HeBM3aBRg9abA(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _tmN9JRMGK1p9Dl3DgNFsY2RcT7g._5B5vSMOrXjTPzrPEOuZxX9h6nsF(_2c8ErjpCBXuzdsmRdi2lVfNAkXQ , String[] )
   at _QJXScnkCUbxSWiShTSbTSz77sLA._5B5vSMOrXjTPzrPEOuZxX9h6nsF(ThreadStart )
-------------------------------
Singleplayer crash
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.0-rc.1 (Unstable)11/23/2020 2:08:09 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.HudDialogChat.UpdateText()
   at Vintagestory.Client.NoObf.HudDialogChat.OnTabClicked(Int32 groupId)
   at Vintagestory.Client.NoObf.HudDialogChat.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.GuiManager.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _5hCAkcR0qGwiw0p1Od3dkPNJr9m._k0IPcsxgDzTj2TKJ7rcHT9FrHio(Single )
   at _FaGPIoRIMmPde5LK617lMxGGqKO._ew8jFTkG0bv7vcU0TlSh3xJDYqG(Single )
   at _FaGPIoRIMmPde5LK617lMxGGqKO._hnsBUFFLbZEdYv6HeBM3aBRg9abA(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _tmN9JRMGK1p9Dl3DgNFsY2RcT7g._5B5vSMOrXjTPzrPEOuZxX9h6nsF(_2c8ErjpCBXuzdsmRdi2lVfNAkXQ , String[] )
   at _QJXScnkCUbxSWiShTSbTSz77sLA._5B5vSMOrXjTPzrPEOuZxX9h6nsF(ThreadStart )
-------------------------------

-------------------------------
```

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in rc.2 or rc.3
