### ISSUE TITLE
Placing 2 Blister Steel ingots on Helve Hammer crashes game

### ISSUE THREAD

**Issue by Electricianfromhell** [anegostudios/VintageStory-Issues#658]
**Game Version:** v1.14.0-rc.3 unstable
**Platform:** Windows
**Modded:** No

### Description
Placing 2 Blister Steel ingots on Helve Hammer crashes game

### How to reproduce
1. Make a helvehammer
2. place 2 Blister steel ingots on it at once
3. It crashes

### Expected behavior
Placing 2 Blister steel ingots on helvehammer at once.

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.0-rc.3 (Unstable)11/23/2020 8:12:24 PM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.ItemIngot.AddVoxelsFromIngot(ICoreAPI api, Byte[,,]& voxels, Boolean isBlisterSteel)
   at Vintagestory.GameContent.ItemIngot.TryPlaceOn(ItemStack stack, BlockEntityAnvil beAnvil)
   at Vintagestory.GameContent.BlockEntityAnvil.TryPut(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel)
   at Vintagestory.GameContent.BlockEntityAnvil.OnPlayerInteract(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel)
   at Vintagestory.GameContent.BlockAnvil.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _AlHq0Inapm61pWcZ59khYnLNZ4o._cIzo1HatEQocpAXHUQlayDnaOs(Single )
   at _3oBqZxtXFzGwmJ7quAnuEUCIsWB._l5fK2kGCHgpDIf3cGe4QLBObbKC(Single )
   at _3oBqZxtXFzGwmJ7quAnuEUCIsWB._oTv4ofbpa4AGXLcoYrtTL6GbHQf(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _4BWchexiFigD9Q16Uzu1AHRcMkKA._F6I3lsgrc5VRUFEGnBoXsboBGFs(_zaqE2EDRPzgKzO45PKPCgTGhJk6 , String[] )
   at _ZkFtsNKa9prG34Jd8zC0yw7G6T4._F6I3lsgrc5VRUFEGnBoXsboBGFs(ThreadStart )
-------------------------------
```

**Comment by tyronx** [comment]
thanks for the report, this will be fixed in rc.7 or rc.8
