### ISSUE TITLE
NullReferenceException in getOrCreateWeatherSimForRegion

### ISSUE THREAD

**Issue by InvertedCow** [anegostudios/VintageStory-Issues#660]
Original title: Crashed for no apparent reason and reloaded to crash

```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.0-rc.3 (Unstable)24/11/2020 6:35:55 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Vintagestory.GameContent.WeatherSystemBase.getOrCreateWeatherSimForRegion(Int64 index2d, IMapRegion mapregion)
   at Vintagestory.GameContent.WeatherDataReaderBase.LoadAdjacentSims(Vec3d pos)
   at Vintagestory.GameContent.CloudRenderer.UpdateCloudTilesOffThread(Int32 changeSpeed)
   at Vintagestory.GameContent.CloudRenderer.<.ctor>b__31_2()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
-------------------------------
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
