### ISSUE TITLE
Journal entries disappeared and new ones crash the game after update to v1.14.0-rc.3 from v1.14.0-pre.12

### ISSUE THREAD

**Issue by SunnyOpossum** [anegostudios/VintageStory-Issues#661]
v1.14.0-rc.3
**Platform:** Windows
**Modded:** No 

### Description
Journal entries disappeared and new ones crash the game after update to v1.14.0-rc.3 from v1.14.0-pre.12

### How to reproduce
Clicked on new journal entry

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.0-rc.3 (Unstable)11/25/2020 4:11:11 AM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.GuiDialogJournal.onClickItem(Int32 i)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _4BWchexiFigD9Q16Uzu1AHRcMkKA._F6I3lsgrc5VRUFEGnBoXsboBGFs(_zaqE2EDRPzgKzO45PKPCgTGhJk6 , String[] )
   at _ZkFtsNKa9prG34Jd8zC0yw7G6T4._F6I3lsgrc5VRUFEGnBoXsboBGFs(ThreadStart )
-------------------------------
```

**Comment by ray557913** [comment]
Had a similar issue when trying to read the tapestry entry 6/14 that I had just learned. A new world so no loss of old ones

**Comment by tyronx** [comment]
thanks for the report. this should be fixed in rc.4
