### ISSUE TITLE
Crash when exiting the game

### ISSUE THREAD

**Issue by CaptainWonders** [anegostudios/VintageStory-Issues#664]
**Game Version:** 1.13.4
**Platform:** Windows 10
**Modded:** No

### Description
The game crashed when I saved and exit my survival (Standard, climate changed to hot)

### Logs

```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.13.4 (Stable)11/25/2020 2:54:59 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.SystemSoundEngine.Dispose(ClientMain game)
   at Vintagestory.Client.NoObf.ClientMain.Dispose()
   at Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected)
   at Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnLeaveWorld()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt , String[] )
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(ThreadStart )
-------------------------------
```

**Comment by tyronx** [comment]
thanks, should be fixed in rc.8
