### ISSUE TITLE
IndexOutOfRangeException when clayforming

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#67]
> **Version:** 1.5.2.6
> While forming clay bowls I made multiple forms at once.  Client crashes with array out of bounds if you do not release mouse button when moving from one form to the next (using the 2x2 pattern to remove clay).  Appears to happen as soon as you move to the next form. Does not happen with a single form beyond the forms boundary. See screenshot below.

~ Elwood [on the forums](https://www.vintagestory.at/forums/topic/472-clay-forming-client-crash/?do=findComment&comment=2484)

![](https://content.invisioncic.com/r268468/monthly_2018_04/image.png.1944eb45aa2d542a234fbe9dc3a58cca.png)

```
2018-04-06 11:17:31 AM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockEntityClayForm.OnRemove(Vec3i voxelPos, BlockFacing facing, Int32 radius)
   at Vintagestory.GameContent.BlockEntityClayForm.OnUseOver(IPlayer byPlayer, Vec3i voxelPos, BlockFacing facing, Boolean mouseBreakMode)
   at Vintagestory.GameContent.ItemClay.OnHeldAttackStop(Single secondsPassed, IItemSlot slot, IEntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at _jl7sbR3JPBwA6mcttglneENOEEA._JQ6ygWnaP42hDcjXq9LEf2nkZ0H()
   at _LOCdge8fPO0OoGdFisvCWDCfxkFb._7SCBtNOLweRcxVKvLicl3PEXJ6AA(Int64 , IWorldAccessor )
   at _OcDw1EJDtyxSg2zIZUkz5GvfhLf._YvjVAV2DvRhhcGH5E47iqBGXLE1(Single )
   at _OcDw1EJDtyxSg2zIZUkz5GvfhLf._ESP6jvrKgTsShcp5CABSxRTgdjh(Single )
   at _NOGdaXHjcqYbZp309TBwE1lwaJoA._ExRcvCgtpj75hrxXNi0Fq2zHtPE(Single )
   at _EP7D7TCjbI38qUrbc8v9F8rIJvBA._f1gdadbeaLzUZvf0eYqEv8hB6HHA(Single )
   at _EP7D7TCjbI38qUrbc8v9F8rIJvBA._cCrJraU5W0BU0xQ8vqgu2GncwHh(Single )
   at _0i52t9CegOtDCetucrJbvQ8mTjy._0hTztHagGp0JVZ40l1FngGASBwh(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _KbPBTtpp9dCK8HCfZavQddEV3tP._5RUcArPeN1Ng7pkVPQqGdZQ033O(_6bvH7Blhp6ycqoRLHWCCCwkK7wD , String[] )
   at _I5JXPXhpKipFp36rslLC7Rct7JC._5RUcArPeN1Ng7pkVPQqGdZQ033O(ThreadStart )
```

**Comment by tyronx** [comment]
Ok, should be fixed for 1.5.3, thanks.
