### ISSUE TITLE
Game crashes if your inventory is open and you close an open chest

### ISSUE THREAD

**Issue by RaeRaeElla** [anegostudios/VintageStory-Issues#672]
Game will CTD if your inventory and a chest are open and you close the chest

```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.0-rc.5 (Unstable)29/11/2020 9:43:46 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnKeyCombinationToggle(KeyCombination viaKeyComb)
   at _e3KPBX8lW4XqaUg773jbQpz12Zm._1S5lAHLFadPxyblWZOYMoocH72D(KeyEvent , IWorldAccessor , IPlayer , Boolean , Boolean , Boolean )
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(Object sender, KeyboardKeyEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnKeyDown(Key key, Boolean repeat)
   at OpenTK.Platform.Windows.WinGLNative.HandleKeyboard(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _sWJvi87KMVRA99P6QjB8ef0CRMK._L2ZZFaBz7lnFfFTnN7V0TX152mF(_8Ma8rFd1NDRalKrUs12c54bE17W , String[] )
   at _Xq1gUZac3I12JyZZXgluJVi2l0P._L2ZZFaBz7lnFfFTnN7V0TX152mF(ThreadStart )
```

**Comment by tyronx** [comment]
thanks for the report. this should be fixed in rc.7
