### ISSUE TITLE
Crashes when placing 3-way chute

### ISSUE THREAD

**Issue by Jamie-Louise** [anegostudios/VintageStory-Issues#673]
**Game Version:** v1.14.0-rc.6
**Platform:** Windows
**Modded:** No

### Description
Placing a 3-way chute on a vertical surface causes a crash.

Placing it on the open side of another chute is fine, placing it adjacent to a hopper is fine, 
but placing it onto the closed side of another chute also causes a crash.

### How to reproduce
1. Get a 3-way chute.
2. Place it on the side of a block.
3. It crashes.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.0-rc.6 (Unstable)11/28/2020 8:21:05 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockChute.OrientForPlacement(IBlockAccessor worldmap, IPlayer player, BlockSelection bs)
   at Vintagestory.GameContent.BlockChute.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, String& failureCode)
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryPlace(BlockSelection blockSelection, String& failureCode)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnBlockBuild(BlockSelection blockSelection, Block onBlock, String& failureCode)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _DzqUHzWG5ivKdJyotgKDRm4cBXs._fvfOgmnSiLBCV4PoaifivggD8hx(Single )
   at _KbxK7q90sMEDjpXRpXP8nQnEHIi._oM5i5L2nnXhzgJOI4cVN9Wj0lfH(Single )
   at _KbxK7q90sMEDjpXRpXP8nQnEHIi._xDMDcHHJ1xDnaUhY1VWOZfcLetp(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _yrd7DRHjYt2aJYRh5SVKTWbLoPF._Sp8vmWBaO75ppWCciv7GQiQG5pO(_vP7Jnrc614sHmVvfHnkDt3mmV1L , String[] )
   at _NZnJc0jadrs2ul5ZN7k8egsplnC._Sp8vmWBaO75ppWCciv7GQiQG5pO(ThreadStart )

```

**Comment by tyronx** [comment]
thanks for the report. this should be fixed in rc.7
