### ISSUE TITLE
Tonight's crash Brought to you by the Unhandled exception.  

### ISSUE THREAD

**Issue by InvertedCow** [anegostudios/VintageStory-Issues#674]
Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.0-rc.5 (Unstable)28/11/2020 8:49:49 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.Block.GetPlacedBlockName(IWorldAccessor world, BlockPos pos)
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.ComposeBlockInfoHud()
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.BlockInView()
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _KnRlO59BkSQeg9qlk9Tik5osTV1._GSOVHjL9U25tJ58C6D3okkAUeF(Single )
   at _KUBjV7R7gk0w1e7MFeJCKloHUXg._cmq39dmU4rA5MGXX1JB6zy6zeoE(Single )
   at _KUBjV7R7gk0w1e7MFeJCKloHUXg._4Ruyco3i18d7NjeAvZWobOyiemd(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _sWJvi87KMVRA99P6QjB8ef0CRMK._L2ZZFaBz7lnFfFTnN7V0TX152mF(_8Ma8rFd1NDRalKrUs12c54bE17W , String[] )
   at _Xq1gUZac3I12JyZZXgluJVi2l0P._L2ZZFaBz7lnFfFTnN7V0TX152mF(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 27/11/2020 10:45:10 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException
   at Vintagestory.GameContent.GuiDialogJournal.onClickItem(Int32)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(System.Object, OpenTK.Input.MouseButtonEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double, Double)
   at _3vQyrEFzzTo621kbwI8uLnpbjmr._cXULfD9VBvCvsQciThzLrEAkULH(_Fyv0FiiCeZfDXS5LikSRvikkmxv, System.String[])
   at _hnCC2druuC6freuGMHRtfNd1TSw._cXULfD9VBvCvsQciThzLrEAkULH(System.Threading.ThreadStart)

 }
{ TimeGenerated = 25/11/2020 6:45:07 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException
   at Vintagestory.GameContent.GuiDialogJournal.onClickItem(Int32)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(System.Object, OpenTK.Input.MouseButtonEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double, Double)
   at _4BWchexiFigD9Q16Uzu1AHRcMkKA._F6I3lsgrc5VRUFEGnBoXsboBGFs(_zaqE2EDRPzgKzO45PKPCgTGhJk6, System.String[])
   at _ZkFtsNKa9prG34Jd8zC0yw7G6T4._F6I3lsgrc5VRUFEGnBoXsboBGFs(System.Threading.ThreadStart)

 }

**Comment by tyronx** [comment]
Thanks for the report.
What were you looking at at this time and what where you doing?
