### ISSUE TITLE
Moving Vessel game crashed

### ISSUE THREAD

**Issue by bean9236** [anegostudios/VintageStory-Issues#677]
**Game Version:** X.Y.Z
**Platform:** Windows / Mac / Linux (which?)
**Modded:** No / Yes (which?)

### Description
Explain the issue you're running into.

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash here.

Running on 64 bit Windows with 12 GB RAM 
Version: v1.14.0 (Stable)12/6/2020 2:16:50 PM: Critical error occurred
System.MissingMethodException: Method not found: 'Void Vintagestory.API.Common.BlockEntity.FromTreeAtributes(Vintagestory.API.Datastructures.ITreeAttribute, Vintagestory.API.Common.IWorldAccessor)'.
   at CarryCapacity.CarriedBlock.RestoreBlockEntityData(IWorldAccessor world, BlockPos pos)
   at CarryCapacity.CarriedBlock.PlaceDown(IWorldAccessor world, BlockSelection selection, Entity entity)
   at CarryCapacity.Common.CarryHandler.OnGameTick(Single deltaTime)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _6HHEy0R7TdcydZEq9IGp6JeHxdi._ogIdn3jhm7KUUuyvw6LDaa2X3PC(Single )
   at _gVBHOlByVD3vztgY4vPBxj2Bdae._ZKkvVIgccAdBc9j9BIZLqcgTrNL(Single )
   at _gVBHOlByVD3vztgY4vPBxj2Bdae._UQuOSpN5p2QIPbIExoPtD2ecXtb(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _93RBbYKdbejiH9hVmbTS8c6kZxJ._hbMghNVJIKTGI5zBx3SuxRG1XDI(_Lsm9ms4vr0dfuNPxkLwK9w8a58N , String[] )
   at _eVFDVqwXngafMmcD9boVPO86iWx._hbMghNVJIKTGI5zBx3SuxRG1XDI(ThreadStart )
-------------------------------



```

**Comment by copygirl** [comment]
This is a issue with the mod CarryCapacity, as you can see in the so-called stacktrace (`at CarryCapacity.CarriedBlock...`). I've uploaded a new version to fix it just now.

**Comment by bean9236** [comment]
Thank you
