### ISSUE TITLE
Shooting bow after remapping crashes game

### ISSUE THREAD

**Issue by zufar100** [anegostudios/VintageStory-Issues#678]
**Game Version:** 1.14.0
**Platform:** Windows 10
**Modded:** Yes (Mostly content mods) trade-o-mat, propickinfo, and grave stones

### Description
When shooting a bow, the game crashes if arrows are not in your hotbar.

### How to reproduce
Two ways: 
1) Attempt to fire a bow with arrows in your backpack (game crashes)
2) Attempt to fire a bow with no arrows

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.0 (Stable)12/6/2020 1:36:17 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemBow.<>c__DisplayClass3_0.<GetNextArrow>b__0(ItemSlot invslot)
   at Vintagestory.API.Common.EntityPlayer.WalkInventory(OnInventorySlot handler)
   at Vintagestory.GameContent.ItemBow.GetNextArrow(EntityAgent byEntity)
   at Vintagestory.GameContent.ItemBow.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _6HHEy0R7TdcydZEq9IGp6JeHxdi._AlWFhh8JhMArtkbaP7hQAQ2sQCE(Single )
   at _gVBHOlByVD3vztgY4vPBxj2Bdae._ZKkvVIgccAdBc9j9BIZLqcgTrNL(Single )
   at _gVBHOlByVD3vztgY4vPBxj2Bdae._UQuOSpN5p2QIPbIExoPtD2ecXtb(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _93RBbYKdbejiH9hVmbTS8c6kZxJ._hbMghNVJIKTGI5zBx3SuxRG1XDI(_Lsm9ms4vr0dfuNPxkLwK9w8a58N , String[] )
   at _eVFDVqwXngafMmcD9boVPO86iWx._hbMghNVJIKTGI5zBx3SuxRG1XDI(ThreadStart )
-------------------------------
```

**Comment by copygirl** [comment]
Could not reproduce on my end, but I only tried with the regular Bow, not Crude Bow.

**Comment by zufar100** [comment]
I am not able to reproduce it today either. Not sure what was happening. The game was running on a server that has since been restarted. The only other thing I can think of is that I had just remapped the blocks.

**Comment by copygirl** [comment]
It looks like it's related to the remapping then. I don't see why there would be a `null` during normal gameplay.
