### ISSUE TITLE
v1.14.0, game crashes when trying to put food from pot into a bowl

### ISSUE THREAD

**Issue by jaesaber** [anegostudios/VintageStory-Issues#680]
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.0 (Stable)12/8/2020 1:53:24 PM: Critical error occurred
System.MissingFieldException: Field not found: 'Vintagestory.GameContent.BlockEntityCookedContainer.RecipeCode'.
   at XSkills.BlockCookedContainerPatch.Prefix(Boolean& __result, BlockCookedContainer __instance, IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel)
   at Vintagestory.GameContent.BlockCookedContainer.OnBlockInteractStart_Patch1(BlockCookedContainer this, IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _6HHEy0R7TdcydZEq9IGp6JeHxdi._AlWFhh8JhMArtkbaP7hQAQ2sQCE(Single )
   at _gVBHOlByVD3vztgY4vPBxj2Bdae._ZKkvVIgccAdBc9j9BIZLqcgTrNL(Single )
   at _gVBHOlByVD3vztgY4vPBxj2Bdae._UQuOSpN5p2QIPbIExoPtD2ecXtb(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _93RBbYKdbejiH9hVmbTS8c6kZxJ._hbMghNVJIKTGI5zBx3SuxRG1XDI(_Lsm9ms4vr0dfuNPxkLwK9w8a58N , String[] )
   at _eVFDVqwXngafMmcD9boVPO86iWx._hbMghNVJIKTGI5zBx3SuxRG1XDI(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 12/8/2020 1:51:26 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.MissingFieldException
   at XSkills.BlockCookedContainerPatch.Prefix(Boolean ByRef, Vintagestory.GameContent.BlockCookedContainer, Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.IPlayer, Vintagestory.API.Common.BlockSelection)
   at DynamicClass.Vintagestory.GameContent.BlockCookedContainer.OnBlockInteractStart_Patch1(Vintagestory.GameContent.BlockCookedContainer, Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.IPlayer, Vintagestory.API.Common.BlockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Vintagestory.API.Common.Block, Vintagestory.API.Common.BlockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single)
   at _6HHEy0R7TdcydZEq9IGp6JeHxdi._AlWFhh8JhMArtkbaP7hQAQ2sQCE(Single)
   at _gVBHOlByVD3vztgY4vPBxj2Bdae._ZKkvVIgccAdBc9j9BIZLqcgTrNL(Single)
   at _gVBHOlByVD3vztgY4vPBxj2Bdae._UQuOSpN5p2QIPbIExoPtD2ecXtb(Single)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _93RBbYKdbejiH9hVmbTS8c6kZxJ._hbMghNVJIKTGI5zBx3SuxRG1XDI(_Lsm9ms4vr0dfuNPxkLwK9w8a58N, System.String[])
   at _eVFDVqwXngafMmcD9boVPO86iWx._hbMghNVJIKTGI5zBx3SuxRG1XDI(System.Threading.ThreadStart)

 }
{ TimeGenerated = 10/9/2020 10:18:29 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 0000000000000000
 }
```

**Comment by copygirl** [comment]
This looks to be an issue with the XSkills mod, as you can see in the stacktrace:
`at XSkills.BlockCookedContainerPatch.Prefix( [...]`

Make sure you are using the most recent version of the mod and if so, report the issue to its author.
