### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Haver12** [anegostudios/VintageStory-Issues#710]
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.13.4 (Stable)12/25/2020 12:01:15 AM: Critical error occurred
System.InvalidOperationException: Tried to remove mesh that does not exist. This shouldnn't happen
   at Vintagestory.API.Client.MeshDataPool.RemoveLocation(ModelDataPoolLocation location)
   at Vintagestory.Client.NoObf.SystemRenderDecals.OnBlockChanged(BlockPos pos, Block oldBlock)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockChanged(ClientMain game, BlockPos pos, Block oldBlock)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(_5JvvYf9KFEDVZitFymVPmMx6YcA packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _VtIDI6oYFpyEcQSZBFso9UVxS9aA._ZnYzeuHqveMMiEvOnpahncAMjfg(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._4BykKOCicJqCBHpyWIgTmxWrTrg(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._6XmOxKoTYrFLRCGd58p58XW43nD(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt , String[] )
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 12/24/2020 11:51:35 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NotSupportedException

Exception Info: System.IO.FileLoadException
   at System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(System.String, System.Security.Policy.Evidence, Byte[], System.Configuration.Assemblies.AssemblyHashAlgorithm, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Reflection.Assembly.LoadFrom(System.String)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._gdb9Q0D3sOCj2UTjGznj8urpROg(System.Object, System.ResolveEventArgs)

Exception Info: System.Exception
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._gdb9Q0D3sOCj2UTjGznj8urpROg(System.Object, System.ResolveEventArgs)
   at System.AppDomain.OnAssemblyResolveEvent(System.Reflection.RuntimeAssembly, System.String)

Exception Info: System.IO.FileLoadException
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp..ctor(System.String[])
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._k39DsboSFqAvcX2gaWs5Tk5Zl6Q(System.String[])

 }
{ TimeGenerated = 12/24/2020 11:51:20 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NotSupportedException

Exception Info: System.IO.FileLoadException
   at System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(System.String, System.Security.Policy.Evidence, Byte[], System.Configuration.Assemblies.AssemblyHashAlgorithm, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Reflection.Assembly.LoadFrom(System.String)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._gdb9Q0D3sOCj2UTjGznj8urpROg(System.Object, System.ResolveEventArgs)

Exception Info: System.Exception
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._gdb9Q0D3sOCj2UTjGznj8urpROg(System.Object, System.ResolveEventArgs)
   at System.AppDomain.OnAssemblyResolveEvent(System.Reflection.RuntimeAssembly, System.String)

Exception Info: System.IO.FileLoadException
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp..ctor(System.String[])
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._k39DsboSFqAvcX2gaWs5Tk5Zl6Q(System.String[])

 }
```

**Comment by copygirl** [comment]
You're running an old version of the game (1.13.4). This might have been fixed already. Can you try updating the game?

**Comment by Haver12** [comment]
Going to try that. Thanks

**Comment by copygirl** [comment]
Closing due to lack of response. Assuming fixed.
