### ISSUE TITLE
Vintage Story anvil helve hammer crash

### ISSUE THREAD

**Issue by cuotel** [anegostudios/VintageStory-Issues#713]
Game Version: v1.14.3-rc.1
Platform: Windows 10
Modded: Yes: RopeBridges v1.0.4, GrassStuff v1.1, medievalexpansion v3.1.3, MoreRecipes v1.4.3, necessaries v0.7.8-B, primitivesurvival v2.4.0, survivalcats v1.1.0, xlib v0.4.2, xskills v0.4.2, zeekea v1.2.7

### Description

I understand that this is an unstable game version and these mods have not been updated to this version of the game as well, so I am just going to go back to an older version of the game to fix this.

From what I've seen so far this crash only happens on a world that is open to LAN and occurs when someone else joins your world and either player does the following:
places a workable copper bar on an anvil that a helve hammer is working.
It crashes for the non-host player instantly, and a few seconds later crashes for the host as well.

### Logs
```
Running on 64 bit Windows with 12 GB RAM 
Version: v1.14.3-rc.1 (Unstable)12/26/2020 6:21:48 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at XSkills.XSkillsBlockEntityAnvil.CheckIfFinished(IPlayer byPlayer)
   at Vintagestory.GameContent.BlockEntityAnvil.OnHelveHammerHit()
   at Vintagestory.GameContent.Mechanics.BEHelveHammer.get_Angle()
   at Vintagestory.GameContent.HelveHammerRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _0u1q6j2nrxl4JzwTC8BEAbbebLx._6YPCnrKUsY1HrBD73vYwJF4fv3B(Single )
   at _nn74j8eVAVAbK3Vc7HCa6WlZ2TO._Wx6C2XWWBMmAj8Xc8sVbQSpBQhX(Single )
   at _nn74j8eVAVAbK3Vc7HCa6WlZ2TO._LariiMopou3QKxlaZPUOezuD1gF(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _Vh7qWGaAfshImsHW0OEC9KhXdHO._mRQYoY8wHQIB3uG1a4BIMqFnLig(_MDt6Z6BXXcl2VjqYltplpD0jxVe , String[] )
   at _b8JyYuNDWoo3X3Jn55tdcoeGYyj._mRQYoY8wHQIB3uG1a4BIMqFnLig(ThreadStart )
-------------------------------

**Comment by copygirl** [comment]
The crash appears to occur in mod code, as seen by the first line referencing XSkills:
`at XSkills.XSkillsBlockEntityAnvil.CheckIfFinished(IPlayer byPlayer)`

This is likely an issue with the mod and it has to be updated (due to an API change?), so I will close this for now.
