### ISSUE TITLE
Crash on getting berries

### ISSUE THREAD

**Issue by Meludan** [anegostudios/VintageStory-Issues#725]
```
Running on 64 bit Windows with 12 GB RAM 
Version: v1.14.3 (Stable)01/03/2021 2:23:23 PM: Critical error occurred
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.BlockBehavior.properties'.
   at XSkills.XSkillsBerryBushBehavior.OnBlockInteractStop(Single secondsUsed, IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel, EnumHandling& handled)
   at Vintagestory.API.Common.Block.OnBlockInteractStop(Single secondsUsed, IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _yr4EbBEnMXjrC79JHrKbHtfBrD4._qptdzIedTEEB7DugQCAVq1n4jucA(Single )
   at _tu2YgNIKQzOkT2nAdJFL4J6zoDR._BBB0hstHVskODF2K8rVkTQmFAwu(Single )
   at _tu2YgNIKQzOkT2nAdJFL4J6zoDR._GZQBLkBtgDYUMMZ3b1XMXmjhIoQ(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _DzwIHsHTgIxBlIoSlHXEFAccnLH._kUotKlTq40LFk1x77w5BI0TbA2I(_7vNFKI4BgGcjaNRXWcynARwku1P , String[] )
   at _q2ATBxADQgCwwacNPfwomqZ8iA._kUotKlTq40LFk1x77w5BI0TbA2I(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 01/03/2021 12:14:22 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFFB29AD759
Stack:
 }
{ TimeGenerated = 01/01/2021 8:48:46 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FF9B6F826A0 (00007FF9B6DB0000) with exit code 80131506.
```

**Comment by copygirl** [comment]
```
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.BlockBehavior.properties'.
at XSkills.XSkillsBerryBushBehavior.OnBlockInteractStop(Single secondsUsed, IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel, EnumHandling& handled)
```
This suggests the issue is with XSkills, rather than the main game. Likely, there has been a breaking change to the API and you will have to either update the mod, or downgrade the game for now.
