### ISSUE TITLE
game unexpectedly crashes when making an iron anvil top

### ISSUE THREAD

**Issue by keithwonderbar** [anegostudios/VintageStory-Issues#740]
**Game Version:** 1.14.5 (stable)
**Platform:** Windows
**Modded:** No

### Description
when making an iron anvil top with  a copper hammer
pushing a piece causes whole game to crash, 3 confirmed with self and 1 confirmed with an admin

### How to reproduce
1.hammering an iron anvil top with copper hammer
2. set up with a line of voxels 2 high 3 long, push top front voxel forward and game crashes
3. It crashes / doesn't do the thing.

### Expected behavior
the voxel to push up onto the voxel behind it

### Screenshots
n/a piece was destroyed before a screenshot was able to be taken

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.5 (Stable)1/10/2021 2:51:39 AM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockEntityAnvil.OnUpset(Vec3i voxelPos, BlockFacing towardsFace)
   at Vintagestory.GameContent.BlockEntityAnvil.OnUseOver(IPlayer byPlayer, Vec3i voxelPos, BlockSelection blockSel)
   at Vintagestory.GameContent.ItemHammer.OnHeldAttackStop(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _Vq7Xo4xIdbZDwh8iDcGnovGKH7D._5RNBrkQoxljreqLqfZ3LUVDaIrr(Single )
   at _7KGTxxuvfNubJZCLAMEMJZBkPDeA._07k4LSTgxALpYbS1S6K07SItFcH(Single )
   at _7KGTxxuvfNubJZCLAMEMJZBkPDeA._aysJzMcCvicDqo8MC3TmjcDsfdZ(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _4eRDDOqtbaPbgjN2dJ1zzD1FCRy._ExJp6VhLWG4xQoHsVn72tgyNbeG(_bWl72q5sGuTQypu8W8r7cRXUcRF , String[] )
   at _XKAWv6MyciUiZmECUonQCwPaCwE._ExJp6VhLWG4xQoHsVn72tgyNbeG(ThreadStart )
-------------------------------
```

**Comment by tyronx** [comment]
hi, thanks for the report - could you show me a screenshot a step before the crash?

**Comment by copygirl** [comment]
#740 has a screenshot of a configuration that can be used to recreate the crash.

**Comment by Craluminum2413** [comment]
Just reproduced the same crash

https://user-images.githubusercontent.com/69315569/147857785-a3472f04-7612-4de9-9564-63a51b88f3f0.mp4

**Comment by tyronx** [comment]
aw, i introduced this crash in rc.5

**Comment by tyronx** [comment]
should be fixed in rc.5. thanks.

**Comment by Craluminum2413** [comment]
You meant in rc.6?

**Comment by copygirl** [comment]
@Craluminum2413 Well, Tyron said it was introduced in rc.5 so - unless he has a time machine - he couldn't have fixed it in the same version. I assume he meant rc.6.

**Comment by tyronx** [comment]
ah yes, i meant rc.6
