### ISSUE TITLE
keeps crashing

### ISSUE THREAD

**Issue by Meludan** [anegostudios/VintageStory-Issues#741]
```
Running on 64 bit Windows with 12 GB RAM 
Version: v1.14.5 (Stable)01/10/2021 11:54:17 AM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.Client.CaveMusicTrack.ContinuePlay(Single dt, TrackedPlayerProperties props)
   at Vintagestory.Client.NoObf.SystemMusicEngine.OnEverySecond(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _Vq7Xo4xIdbZDwh8iDcGnovGKH7D._5RNBrkQoxljreqLqfZ3LUVDaIrr(Single )
   at _7KGTxxuvfNubJZCLAMEMJZBkPDeA._07k4LSTgxALpYbS1S6K07SItFcH(Single )
   at _7KGTxxuvfNubJZCLAMEMJZBkPDeA._aysJzMcCvicDqo8MC3TmjcDsfdZ(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _4eRDDOqtbaPbgjN2dJ1zzD1FCRy._ExJp6VhLWG4xQoHsVn72tgyNbeG(_bWl72q5sGuTQypu8W8r7cRXUcRF , String[] )
   at _XKAWv6MyciUiZmECUonQCwPaCwE._ExJp6VhLWG4xQoHsVn72tgyNbeG(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 01/07/2021 9:28:52 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFF9F1F1B35 (00007FFF9F020000) with exit code 80131506.
 }
{ TimeGenerated = 01/05/2021 1:05:21 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFF9F1F1444 (00007FFF9F020000) with exit code 80131506.
 }
{ TimeGenerated = 01/03/2021 12:14:22 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFFB29AD759
Stack:
 }
```

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in v1.14.6-rc.1
