### ISSUE TITLE
Game crashes when i use push to talk

### ISSUE THREAD

**Issue by tronedile** [anegostudios/VintageStory-Issues#745]
**Modded:** No

Game has been working fine since i got it, started playing with a friend and we rented a server using Gportal (unsure if this is relevant but posting just in case). Everything has been running smoothly, however today we used the server command to enable the node search function with prospecting pick (since we just learned about it). However as soon as that happened my game crashed with the above error. I've been able to reproduce the crash almost instantaneously from logging in.

Turns out my push to talk key for discord instantly causes the game to crash AFTER we did this change to the game using the console command. It wasn't an issue until now and i find it extremely bizarre that this is happening now. My push to talk key is bound to F24 which i wouldn't think would cause any issues.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.5 (Stable)1/11/2021 3:20:31 AM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.Client.NoObf.ClientMain.ReloadTextures()
   at _5xa6yzPgHxWbcagozplsQjiReif._rVrs3N4RiZPhWdofBYoMzhCPbJJ(KeyCombination )
   at _yqFp6c3X7WOQClrWTmvdJ5DRtPm._GzZOrp4gTUVPTSbB9tIXBJGT30m(KeyEvent , IWorldAccessor , IPlayer , Boolean , Boolean , Boolean )
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(Object sender, KeyboardKeyEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnKeyDown(Key key, Boolean repeat)
   at OpenTK.Platform.Windows.WinGLNative.HandleKeyboard(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _4eRDDOqtbaPbgjN2dJ1zzD1FCRy._ExJp6VhLWG4xQoHsVn72tgyNbeG(_bWl72q5sGuTQypu8W8r7cRXUcRF , String[] )
   at _XKAWv6MyciUiZmECUonQCwPaCwE._ExJp6VhLWG4xQoHsVn72tgyNbeG(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 1/11/2021 3:13:05 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FF8D8B2D759
Stack:
 }
{ TimeGenerated = 1/11/2021 3:10:55 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FF8D8B2D759
Stack:
 }
{ TimeGenerated = 1/11/2021 3:08:01 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FF8D8B2D759
Stack:
 }
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
