### ISSUE TITLE
Sudden crashing out of nowhere alongside graphical bugs

### ISSUE THREAD

**Issue by Koollan** [anegostudios/VintageStory-Issues#749]
I don't know much else other than what's in the title. Log follows.

```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.5 (Stable)1/11/2021 5:03:41 PM: Critical error occurred
System.Exception: FBO Render2DLoadedTexture: This particular FBO configuration is not supported by the implementation.
   at Vintagestory.Client.NoObf.ClientPlatformWindows.CheckFboStatus(FramebufferTarget target, String fbtype)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.CreateFramebuffer(FramebufferAttrs fbAttrs)
   at Vintagestory.Client.NoObf.ClientMain.RenderTextureIntoTexture(LoadedTexture fromTexture, Single sourceX, Single sourceY, Single sourceWidth, Single sourceHeight, LoadedTexture intoTexture, Single targetX, Single targetY, Single alphaTest)
   at Vintagestory.GameContent.MultiChunkMapComponent.setChunk(Int32 dx, Int32 dz, Int32[] pixels)
   at Vintagestory.GameContent.ChunkMapLayer.<>c__DisplayClass38_0.<loadFromChunkPixels>b__0()
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _Vq7Xo4xIdbZDwh8iDcGnovGKH7D._5RNBrkQoxljreqLqfZ3LUVDaIrr(Single )
   at _7KGTxxuvfNubJZCLAMEMJZBkPDeA._07k4LSTgxALpYbS1S6K07SItFcH(Single )
   at _7KGTxxuvfNubJZCLAMEMJZBkPDeA._aysJzMcCvicDqo8MC3TmjcDsfdZ(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _4eRDDOqtbaPbgjN2dJ1zzD1FCRy._ExJp6VhLWG4xQoHsVn72tgyNbeG(_bWl72q5sGuTQypu8W8r7cRXUcRF , String[] )
   at _XKAWv6MyciUiZmECUonQCwPaCwE._ExJp6VhLWG4xQoHsVn72tgyNbeG(ThreadStart )
-------------------------------
```

**Comment by Koollan** [comment]
A good example of the kinds of graphical bugs:

![image](https://user-images.githubusercontent.com/23038489/104261264-03970f80-543a-11eb-84e6-466f1514ffba.png)

**Comment by Koollan** [comment]
A good idea of the kinds of graphical bugs I get:

![image](https://user-images.githubusercontent.com/23038489/104261312-1c9fc080-543a-11eb-9b73-1c568725aa6a.png)

**Comment by Koollan** [comment]
Another hardcrash while playing in LAN. Logs follow.

Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.5 (Stable)1/12/2021 9:01:31 PM: Critical error occurred
System.Exception: FBO Render2DLoadedTexture: This particular FBO configuration is not supported by the implementation.
   at Vintagestory.Client.NoObf.ClientPlatformWindows.CheckFboStatus(FramebufferTarget target, String fbtype)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.CreateFramebuffer(FramebufferAttrs fbAttrs)
   at Vintagestory.Client.NoObf.ClientMain.RenderTextureIntoTexture(LoadedTexture fromTexture, Single sourceX, Single sourceY, Single sourceWidth, Single sourceHeight, LoadedTexture intoTexture, Single targetX, Single targetY, Single alphaTest)
   at Vintagestory.GameContent.MultiChunkMapComponent.setChunk(Int32 dx, Int32 dz, Int32[] pixels)
   at Vintagestory.GameContent.ChunkMapLayer.<>c__DisplayClass38_0.<loadFromChunkPixels>b__0()
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _Vq7Xo4xIdbZDwh8iDcGnovGKH7D._5RNBrkQoxljreqLqfZ3LUVDaIrr(Single )
   at _7KGTxxuvfNubJZCLAMEMJZBkPDeA._07k4LSTgxALpYbS1S6K07SItFcH(Single )
   at _7KGTxxuvfNubJZCLAMEMJZBkPDeA._aysJzMcCvicDqo8MC3TmjcDsfdZ(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _4eRDDOqtbaPbgjN2dJ1zzD1FCRy._ExJp6VhLWG4xQoHsVn72tgyNbeG(_bWl72q5sGuTQypu8W8r7cRXUcRF , String[] )
   at _XKAWv6MyciUiZmECUonQCwPaCwE._ExJp6VhLWG4xQoHsVn72tgyNbeG(ThreadStart )
-------------------------------

**Comment by Koollan** [comment]
Another pic of the graphical issues.

![image](https://user-images.githubusercontent.com/23038489/104409357-f4d45980-551a-11eb-94d6-9b8d2c04a486.png)

**Comment by copygirl** [comment]
Have you tried updating your graphics driver?

**Comment by Koollan** [comment]
> Have you tried updating your graphics driver?

Yes, my graphics drivers are entirely up to date. I have a GeForce 1050ti.

**Comment by copygirl** [comment]
Could you upload your `client-main.txt` log file?

**Comment by Koollan** [comment]
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/5811176/client-main.txt)

**Comment by copygirl** [comment]
If this happens again, could you post this log file? I'm wondering if there will be additional information.

To me, this looks kind of like a faulty graphics card or driver. I remember getting these types of glitches with Minecraft sometimes when I was using my previous graphics card.

**Comment by Koollan** [comment]
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/5812716/client-main.txt)
Maybe this? I crashed out of this one.

**Comment by tyronx** [comment]
This does look like a hardware or driver issue to me.

**Comment by copygirl** [comment]
If you could test the game with a different graphics card (and appropriate drivers) to see if the issues remain that would be great, but I understand not everyone has the ability to do that. Since Tyron also believes it's not an issue with the game I will close the issue. Feel free to still respond, though.
