### ISSUE TITLE
Game Crashes upon log-in

### ISSUE THREAD

**Issue by agon1zr** [anegostudios/VintageStory-Issues#757]
I am unfortunately unable to play the game a all, whatsoever, as I can't even get further than the login screen.

**Game Version:** 1.14.5 for Windows
**Platform:** Windows 10, 64 bit
**Modded:** No

### Description
I start up the game and it asks me for my log in and password. I enter these and then the game crashes.

 }
{ TimeGenerated = 1/15/2021 6:59:23 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Vintagestory.Common.ModCompilationContext..ctor()
   at Vintagestory.Common.ModLoader..ctor(Vintagestory.API.Common.ICoreAPI, Vintagestory.API.Common.EnumAppSide, Vintagestory.API.Common.ILogger, System.Collections.Generic.IEnumerable`1<System.String>, Boolean)
   at _7KGTxxuvfNubJZCLAMEMJZBkPDeA._T1LRC5DqtOWmU8vEDM4MFX3bDSe()
   at _7KGTxxuvfNubJZCLAMEMJZBkPDeA._YBI2wirTLm4C6GZD3048U2Em2dC()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }

**Comment by agon1zr** [comment]
First reinstall didn't work, second reinstall seemed to fix the issue.
