### ISSUE TITLE
Thrown Exception at Server for working Iron Bloom.

### ISSUE THREAD

**Issue by LordDan1989** [anegostudios/VintageStory-Issues#783]
**Game Version:** 1.14.5 (Server is not 1.14.7 yet - untested on 1.14.7 at time of writing)
**Platform:** Windows 10 64bit
**Modded:** No

### Description
Attempting to move the voxel pictured, in the direction illustrated causes a crash. Everyone else on the server will see "[Player] kicked for throwing an exception at the server."

Attempted by myself and another user with the same result.

### How to reproduce
1. Make an Iron Bloom (This does not happen with a standard ingot.)
2. Use it on an Anvil and attempt to move a voxel UP a layer.
3. It crashes

### Expected behavior
Either to allow moving the voxel up a layer, or for nothing to happen if it isn't possible.

### Screenshots
![Image of Crash](https://user-images.githubusercontent.com/27520934/106909115-dfa4b200-66f7-11eb-881e-5d0ee4bac107.png)

### Logs

> Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.5 (Stable)04/02/2021 14:38:32: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockEntityAnvil.OnUpset(Vec3i voxelPos, BlockFacing towardsFace)
   at Vintagestory.GameContent.BlockEntityAnvil.OnUseOver(IPlayer byPlayer, Vec3i voxelPos, BlockSelection blockSel)
   at Vintagestory.GameContent.ItemHammer.OnHeldAttackStop(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _Vq7Xo4xIdbZDwh8iDcGnovGKH7D._5RNBrkQoxljreqLqfZ3LUVDaIrr(Single )
   at _7KGTxxuvfNubJZCLAMEMJZBkPDeA._07k4LSTgxALpYbS1S6K07SItFcH(Single )
   at _7KGTxxuvfNubJZCLAMEMJZBkPDeA._aysJzMcCvicDqo8MC3TmjcDsfdZ(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _4eRDDOqtbaPbgjN2dJ1zzD1FCRy._ExJp6VhLWG4xQoHsVn72tgyNbeG(_bWl72q5sGuTQypu8W8r7cRXUcRF , String[] )
   at _XKAWv6MyciUiZmECUonQCwPaCwE._ExJp6VhLWG4xQoHsVn72tgyNbeG(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 17/01/2021 13:02:30, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FF9FEC43B29
Stack:
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at System.Environment._Exit(Int32)
   at System.Environment._Exit(Int32)
   at System.Environment.Exit(Int32)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   at OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double, Double)
   at _4eRDDOqtbaPbgjN2dJ1zzD1FCRy._ExJp6VhLWG4xQoHsVn72tgyNbeG(_bWl72q5sGuTQypu8W8r7cRXUcRF, System.String[])
   at _XKAWv6MyciUiZmECUonQCwPaCwE._ExJp6VhLWG4xQoHsVn72tgyNbeG(System.Threading.ThreadStart)
   at _4eRDDOqtbaPbgjN2dJ1zzD1FCRy._jyInOxlJtjeDvyVArlNd6UT8Cuf(System.String[])
 `}`

**Comment by impo** [comment]
Can confirm this, the same crash just happened to me.

```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.7 (Stable)2/8/2021 22:27:53: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockEntityAnvil.OnUpset(Vec3i voxelPos, BlockFacing towardsFace)
   at Vintagestory.GameContent.BlockEntityAnvil.OnUseOver(IPlayer byPlayer, Vec3i voxelPos, BlockSelection blockSel)
   at Vintagestory.GameContent.ItemHammer.OnHeldAttackStop(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _XJ8aPSlEBe0PiHYbVJEdfXv1yjvA._Kgao3H1tkjUV97mMFigKazMDiUo(Single )
   at _QXfAdKxrJ1KaNtwiV64JU2IvnpC._cl7z8c5uEEaIF1fo0XdijiZbRYk(Single )
   at _QXfAdKxrJ1KaNtwiV64JU2IvnpC._peV5mb21IaSJTAYBddj4gA99BDo(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _03wQBzfCnykaMLiRGgbQzrKOcn3._QN2fpVgRVBDOLs27GIkkdMlxeKf(_a9AJZVMB0wcgfRPD19VvLtZCbaX , String[] )
   at _NdjU5BXvKkfOW2d88pNMbEAjE1q._QN2fpVgRVBDOLs27GIkkdMlxeKf(ThreadStart )
-------------------------------```

**Comment by Craluminum2413** [comment]
Crash is the same as in #740

**Comment by copygirl** [comment]
Mhm. Closing as duplicate. Thank you for the additional information however.
