### ISSUE TITLE
Tried to join a multiplayer server and the game crashed

### ISSUE THREAD

**Issue by 825i** [anegostudios/VintageStory-Issues#790]
**Game Version:** Latest
**Platform:** Windows 10
**Modded:** Yes, but not my server.

### Description
Explain the issue you're running into.

### How to reproduce
Tried to join a multiplayer server that I had all the mods for, this happened randomly

### Expected behavior
I wanted to join the server as I do normally

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.7 (Stable)16/02/2021 22.35.40: Critical error occurred
System.Exception: Don't know how to instantiate block of class 'blocknailspike' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateBlock(String blockClass)
   at Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(_dDjK1Oy6M9Ja9stKVtxZeSblfuQ packet, IWorldAccessor world, ClassRegistry registry)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets(_SgnnqebBH0BM984ItS5vhDzSB2c packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _Ji8ZCYdD03AdlbF434eaGgnZqbbA._h7dO1pJXJpGwhthMPDN9E21LMTB(Single )
   at _QXfAdKxrJ1KaNtwiV64JU2IvnpC._cl7z8c5uEEaIF1fo0XdijiZbRYk(Single )
   at _QXfAdKxrJ1KaNtwiV64JU2IvnpC._peV5mb21IaSJTAYBddj4gA99BDo(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _03wQBzfCnykaMLiRGgbQzrKOcn3._QN2fpVgRVBDOLs27GIkkdMlxeKf(_a9AJZVMB0wcgfRPD19VvLtZCbaX , String[] )
   at _NdjU5BXvKkfOW2d88pNMbEAjE1q._QN2fpVgRVBDOLs27GIkkdMlxeKf(ThreadStart )
-------------------------------

```

**Comment by copygirl** [comment]
`blocknailspike` is a block from [Primitive Survival](https://www.vintagestory.at/forums/topic/2399-primitive-survival-traps-fishing-and-other-surprises/). Do you have the correct mod versions to join the server?

**Comment by Craluminum2413** [comment]
Caused by mod
