### ISSUE TITLE
CTD on clicking "Create a new world with this world seed" button

### ISSUE THREAD

**Issue by GhostLich** [anegostudios/VintageStory-Issues#795]
**Game Version:** 1.14.8
**Platform:** Windows 10
**Modded:** I confirmed this occurs on worlds generated with no mods.

### Description
A CTD when selecting "Create a new world with this seed" button.
This world had already been created from the seed from a previous world, that may be relevant. 

### How to reproduce
1. Make a new world.
2. Create a new world by using "Create a new world with this seed" from previous world.
3. Crash, hopefully.

### Expected behavior
The button should be self explanatory, lol.

### Screenshots

https://puu.sh/HkcxZ/df4fb76ea4.gif

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.8 (Stable)2/25/2021 8:13:37 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _PW8NVVq6wBR9krMQ9GulRnv6PMD._h9K0G4wbrt2CCpt5A92lCnKV2gP()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _oDnqPT3M9pq9hNGZM4RDtA6RTnG._TE0ypoo5kb57Ue2gLv7daIuY6VD(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2/13/2021 3:11:53 AM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.14.7.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 1114

Start Time: 01d701dfbdbfb726

Termination Time: 6

Application Path: C:\Users\OTTU\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: cfc2cd66-1e96-4543-8afd-ba6d9977f5bd

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 2/13/2021 3:11:51 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2119673566667689136, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.7.0
P3: 6006d010
P4: 86d0
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF1D8.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF1F8.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF1F7.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF227.tmp.txt
\\?\C:\Users\OTTU\AppData\Local\Temp\WERF739.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_7d3017befbb02abad3d5f0638bf839b18773e29e_8d93c905_ef09dd79-1d0e-4ff2-8a23-b1017dd5769d

Analysis symbol: 
Rechecking for solution: 0
Report Id: cfc2cd66-1e96-4543-8afd-ba6d9977f5bd
Report Status: 268435456
Hashed bucket: 7c9c74a3c6592354ad6a97e0dd034cb0
Cab Guid: 0 }
--------------
{ TimeGenerated = 2/13/2021 3:08:56 AM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.14.7.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 11b8

Start Time: 01d701df2f0397d5

Termination Time: 5

Application Path: C:\Users\OTTU\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: 2c8005cd-56c8-4881-a82c-df17607f6c15

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
```

**Comment by Craluminum2413** [comment]
I have the same 👍🏻

**Comment by Floyyd** [comment]
Yep me as well.

**Comment by copygirl** [comment]
Some more insight from @Rolocandy: https://github.com/anegostudios/VintageStory-Issues/issues/846#issuecomment-812595177
> update (this fixed the problem I was having)
> I uninstalled 1.14.8 and installed 1.14.0 pre.12. This allowed me to reuse seeds
> If I then update 1.14.0 to 1.14.8 the crashing behaviour returns

**Comment by Rares95** [comment]
`Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.8 (Stable)03/04/2021 22:18:38: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _PW8NVVq6wBR9krMQ9GulRnv6PMD._h9K0G4wbrt2CCpt5A92lCnKV2gP()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _oDnqPT3M9pq9hNGZM4RDtA6RTnG._TE0ypoo5kb57Ue2gLv7daIuY6VD(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
`

Same here just now

**Comment by astynax777** [comment]
As a workaround to this, I attempted to copy a seed from my world and create the new world using the same auto-generated seed from my first world.  The new world was not the same as the original.  Is this expected?  I'm thinking not, because to further troubleshoot it, I attempted to create a third world with the same seed and it matched the second world.  It seems as if the seed displayed on my original world was either not accurate, or the world is generated differently if the seed is auto-generated.  Should I create a new issue for this?

**Comment by Craluminum2413** [comment]
@astynax777 The size of the world influences this too

**Comment by astynax777** [comment]
Oooh I see.  I went back and looked and apparently if you don't click the "customize world" then the size defaults to 1000000x256x1000000, 
![image](https://user-images.githubusercontent.com/1410906/121043619-cafa2880-c782-11eb-9a80-7e2690ba31ef.png)

but if you click the customize button, it defaults to 1024000x256x102400
![image](https://user-images.githubusercontent.com/1410906/121043702-de0cf880-c782-11eb-8b79-33443ac8f18f.png)

**Comment by astynax777** [comment]
As a temporary workaround until I can figure out how to explicitly set the Min/Max X and Z to 1000000, I manually copied the original world vcdbs file over and renamed it..

**Comment by Craluminum2413** [comment]
Fixed in [1.15.0-rc.1](https://www.vintagestory.at/blog.html/news/the-homesteading-update-v115-rc1-r284/):
> Fixed: Crashing "Create a new world with this world seed" button

**Comment by Craluminum2413** [comment]
https://user-images.githubusercontent.com/69315569/124761144-28c49080-df3a-11eb-88ca-03de3470d144.mp4

**Comment by Craluminum2413** [comment]
You forgot to close the issue

**Comment by copygirl** [comment]
Thank you!
