### ISSUE TITLE
Battle for echo chamber

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#797]
**Game Version:** 1.14.8
**Platform:** Windows 10
**Modded:** Yes

### Description
You cannot put the resonance archive while someone wants to remove it

### How to reproduce
1. Put an echo chamber
2. First player should hold Shift + Right-Click on the echo chamber
3. Second player should hold Shift and put any resonance archive to the same echo chamber

### Expected behavior
I don't know

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.8 (Stable)2/26/21 13:53:19: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityEchoChamber.<>c__DisplayClass20_0.<onTrackLoaded>b__0()
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _jeEziyUSYl0BpbOxT46FYwj5VWL._t25VgrofhlXMw6hHEZh8JHhJz1A(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._DvzT6D0wN3fMakeuDyljJJ09hok(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._V5piYzG7beYPldE6UVxY58dqacE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )

**Comment by copygirl** [comment]
From the description it sounds like you're using CarryCapacity to pick up the echo chamber. It makes sure to [remove the block entity](https://github.com/copygirl/CarryCapacity/blob/master/src/CarriedBlock.cs#L175) before picking up the block but maybe that's not enough? Maybe the order matters.

**Comment by Craluminum2413** [comment]
Yeah, I'm using CarryCapacity, will try later how it works without it

**Comment by Craluminum2413** [comment]
The block was removed in 1.18
