### ISSUE TITLE
2 Crashes whilst smithing Iron Anvil Top

### ISSUE THREAD

**Issue by pythonInRelay** [anegostudios/VintageStory-Issues#800]
**Game Version:** 1.14.8
**Platform:** Windows 10 64bit
**Modded:** Yes (see attached img)
![oof](https://user-images.githubusercontent.com/58630825/109391168-71ca5f80-791e-11eb-84d6-08e25a756a87.png)

### Description
Game crashes to desktop

### How to reproduce
1. Make a Iron Anvil top. Get to about the 4th bar manually hammering
2. Game crashes whilst moving a block across the hot iron anvil

### Expected behavior
Game shouldn't have crashed whilst I was hammering a hot piece of iron anvil top.

### Logs

Client and Server main.txt are attached.
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/6054695/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/6054706/server-main.txt)

Crash 1:

```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.8 (Stable)27/02/2021 16.45.52: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockEntityAnvil.OnUpset_Patch1(BlockEntityAnvil this, Vec3i voxelPos, BlockFacing towardsFace)
   at Vintagestory.GameContent.BlockEntityAnvil.OnUseOver(IPlayer byPlayer, Vec3i voxelPos, BlockSelection blockSel)
   at Vintagestory.GameContent.ItemHammer.OnHeldAttackStop(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _jeEziyUSYl0BpbOxT46FYwj5VWL._t25VgrofhlXMw6hHEZh8JHhJz1A(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._DvzT6D0wN3fMakeuDyljJJ09hok(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._V5piYzG7beYPldE6UVxY58dqacE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 05/02/2021 18.30.02, Site = , Source = Windows Error Reporting, Message = Fault bucket 2030104223756818486, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.2.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\danie\AppData\Local\Temp\RDR7AAF.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7AC0.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7AD1.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7ADE.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7AFF.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 8228447a-7a00-465e-b59b-90eb22382bd0
Report Status: 268435456
Hashed bucket: d62de5179f3713dc7c2c61091a0b9836
Cab Guid: 0 }
```

Crash 2:

```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.8 (Stable)27/02/2021 16.58.37: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockEntityAnvil.OnUpset_Patch1(BlockEntityAnvil this, Vec3i voxelPos, BlockFacing towardsFace)
   at Vintagestory.GameContent.BlockEntityAnvil.OnUseOver(IPlayer byPlayer, Vec3i voxelPos, BlockSelection blockSel)
   at Vintagestory.GameContent.ItemHammer.OnHeldAttackStop(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _jeEziyUSYl0BpbOxT46FYwj5VWL._t25VgrofhlXMw6hHEZh8JHhJz1A(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._DvzT6D0wN3fMakeuDyljJJ09hok(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._V5piYzG7beYPldE6UVxY58dqacE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 05/02/2021 18.30.02, Site = , Source = Windows Error Reporting, Message = Fault bucket 2030104223756818486, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.2.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\danie\AppData\Local\Temp\RDR7AAF.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7AC0.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7AD1.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7ADE.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\W
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/6054697/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/6054698/server-main.txt)

ER7AFF.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 8228447a-7a00-465e-b59b-90eb22382bd0
Report Status: 268435456
Hashed bucket: d62de5179f3713dc7c2c61091a0b9836
Cab Guid: 0 }
```

**Comment by copygirl** [comment]
Related: #467, #659, #740

**Comment by Craluminum2413** [comment]
So if #803 is resolved, then #800 and #740 should too?

**Comment by Saricane** [comment]
Just had the same crash. Of course, If only I knew it would crash, I would have taken a screenshot. What I can describe is : 3 ingots used. I moved a pixel on the left of the first layer. The pixel was moved one row too far to the left (out of the green print), so I changed the tool to "move right". Pixel did not moved and crash occured 2 seconds after the hammer hit.

**Comment by Craluminum2413** [comment]
I found that voxel
https://user-images.githubusercontent.com/69315569/121682304-9b218c80-cac4-11eb-867a-63b59a163f01.mp4

**Comment by tyronx** [comment]
Thank you for finding a reproducible case with video, this is now fixed for pre.6
