### ISSUE TITLE
Saplings Crash anyone on our server

### ISSUE THREAD

**Issue by DrakeHawkins** [anegostudios/VintageStory-Issues#801]
**Game Version:** 1.14
**Platform:** Windows 
**Modded:** No 

### Description
Anyone who plants a sapling on our server crashes their client

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
n/a

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.8 (Stable)2021-02-28 9:18:25 PM: Critical error occurred
Newtonsoft.Json.JsonSerializationException: Error converting value "[24]" to type 'System.Single'. Path 'avg', line 2, position 15. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.String.System.IConvertible.ToSingle(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Vintagestory.ServerMods.BlockEntitySapling.OnBlockPlaced(ItemStack byItemStack)
   at Vintagestory.Client.NoObf.ClientWorldMap.SpawnBlockEntity(String classname, BlockPos position, ItemStack byItemStack)
   at Vintagestory.API.Common.Block.OnBlockPlaced(IWorldAccessor world, BlockPos blockPos, ItemStack byItemStack)
   at Vintagestory.Common.BlockAccessorRelaxed.SetBlock(Int32 blockId, BlockPos pos, ItemStack byItemstack)
   at Vintagestory.API.Common.Block.DoPlaceBlock(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel, ItemStack byItemStack)
   at Vintagestory.API.Common.Block.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, String& failureCode)
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryPlace(BlockSelection blockSelection, String& failureCode)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnBlockBuild(BlockSelection blockSelection, Block onBlock, String& failureCode)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _jeEziyUSYl0BpbOxT46FYwj5VWL._IIIrDcgMyMKwpTkEZsHikpfl3dh(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._DvzT6D0wN3fMakeuDyljJJ09hok(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._V5piYzG7beYPldE6UVxY58dqacE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.String.System.IConvertible.ToSingle(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2021-02-25 1:41:58 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1539023757749266810, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 6033ac5b
P4: OPENGL32.DLL
P5: 10.0.19041.546
P6: f010886b
P7: c0000005
P8: 000000000001cf3c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE6D4.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_d5668aca6f693d1df2c6c911d36ae1c4888f6aa_4fd6768e_505c0da4-0fed-4026-8ccb-1499fe7e5d16

Analysis symbol: 
Rechecking for solution: 0
Report Id: e6ea600e-70c4-49fe-88b0-8383a2c7e792
Report Status: 268566528
Hashed bucket: 15215c137e0d5ddaa55bb5f41d88297a
Cab Guid: 0 }
--------------
{ TimeGenerated = 2021-02-25 1:41:56 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 6033ac5b
P4: OPENGL32.DLL
P5: 10.0.19041.546
P6: f010886b
P7: c0000005
P8: 000000000001cf3c
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_d5668aca6f693d1df2c6c911d36ae1c4888f6aa_4fd6768e_505c0da4-0fed-4026-8ccb-1499fe7e5d16

Analysis symbol: 
Rechecking for solution: 0
Report Id: e6ea600e-70c4-49fe-88b0-8383a2c7e792
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 2021-02-25 1:41:55 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.14.8.0, time stamp: 0x6033ac5b
Faulting module name: OPENGL32.DLL, version: 10.0.19041.546, time stamp: 0xf010886b
Exception code: 0xc0000005
Fault offset: 0x000000000001cf3c
Faulting process id: 0x498c
Faulting application start time: 0x01d70bae392d5c8d
Faulting application path: C:\Program Files (x86)\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\SYSTEM32\OPENGL32.DLL
Report Id: e6ea600e-70c4-49fe-88b0-8383a2c7e792
Faulting package full name: 
Faulting package-relative application ID:  }
```

**Comment by DrakeHawkins** [comment]
Oh also I set the tree spawn to 30 day i think it was

**Comment by DrakeHawkins** [comment]
after resetting it to 8 days it still occurs

**Comment by radfast** [comment]
I cannot reproduce this.   Please can you paste up your copies of these two files:
`assets\survival\blocktypes\plant\plaintreesapling.json`
`assets\survival\patches\treesapling.json`

It appears that somehow the value `[24]` has been entered where it should be `24`.

Current 1.14.8 does not do this.  It's possible it was done by a past buggy VS version (I am not aware of any bug specifically relating to this, but there have been a lot of changes in 1.14 relating to world configuration).  It's possible it was done by a mod, maybe a mod you used in the past and uninstalled?

**Comment by DrakeHawkins** [comment]
I will check the issue first by changing the config to 24 without entering the [ ] that the wiki indicates. 

Do all the numbers (like season days length and such) also require entering without the [ ] ?

Live to Thrive!

**Comment by DrakeHawkins** [comment]
Just had a thought.  Before I try to change the setting you can log into my
server to get the error message just by trying to plant a sapling
anywhere/time on the server.

172.107.197.58:28000

PurpleTurtle

tis up 24/7

I'll wait till you reply to this to try and change the setting.

**Comment by radfast** [comment]
I'm set up with a different game version (1.15 dev) so it will be time-consuming to roll back to 1.14.8 just to test this.

If you have set up configs with [ ] round all the numbers then that is, undoubtedly, the issue.  Fix that and I think you'll find you have no more problems.

**Comment by DrakeHawkins** [comment]
Ok i will test it with this config ...

/worldconfig saplingGrowthDays [24]

if that doesn't work i will go to

/worldconfig saplingGrowthDays 24

**Comment by radfast** [comment]
Start with /worldconfig saplingGrowthDays 24

I don't understand where the [ and ] are even coming from?

**Comment by DrakeHawkins** [comment]
First console command

...
/worldconfig saplingGrowthDays [24]
19:12:26 [Server Notification] Handling Command /worldconfig
saplingGrowthDays [24]
Ok, value [24] set
19:12:26 [Server Notification] Ok, value [24] set
...

It did this in console then crashed

here is the report.

Running on 64 bit Windows with 32 GB RAM
Version: v1.14.8 (Stable)2021-03-03 6:14:23 PM: Critical error occurred
Newtonsoft.Json.JsonSerializationException: Error converting value "[24]"
to type 'System.Single'. Path 'avg', line 2, position 15. --->
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options,
NumberFormatInfo numfmt)
   at System.String.System.IConvertible.ToSingle(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType,
IFormatProvider provider)
   at
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader
reader, Object value, CultureInfo culture, JsonContract contract, Type
targetType)
   --- End of inner exception stack trace ---
   at
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader
reader, Object value, CultureInfo culture, JsonContract contract, Type
targetType)
   at
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract
contract, JsonProperty containerProperty, JsonReader reader, Type
objectType)
   at
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader
reader, JsonObjectContract contract, JsonProperty containerProperty,
ObjectConstructor`1 creator, String id)
   at
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader
reader, Type objectType, JsonContract contract, JsonProperty member,
JsonContainerContract containerContract, JsonProperty containerMember,
Object existingValue)
   at
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader
reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader,
Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type
type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value,
JsonSerializerSettings settings)
   at Vintagestory.ServerMods.BlockEntitySapling.OnBlockPlaced(ItemStack
byItemStack)
   at Vintagestory.Client.NoObf.ClientWorldMap.SpawnBlockEntity(String
classname, BlockPos position, ItemStack byItemStack)
   at Vintagestory.API.Common.Block.OnBlockPlaced(IWorldAccessor world,
BlockPos blockPos, ItemStack byItemStack)
   at Vintagestory.Common.BlockAccessorRelaxed.SetBlock(Int32 blockId,
BlockPos pos, ItemStack byItemstack)
   at Vintagestory.API.Common.Block.DoPlaceBlock(IWorldAccessor world,
IPlayer byPlayer, BlockSelection blockSel, ItemStack byItemStack)
   at Vintagestory.API.Common.Block.TryPlaceBlock(IWorldAccessor world,
IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, String&
failureCode)
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryPlace(BlockSelection
blockSelection, String& failureCode)
   at
Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnBlockBuild(BlockSelection
blockSelection, Block onBlock, String& failureCode)
   at
Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single
dt)
   at
Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single
dt)
   at
Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage
stage, Single dt)
   at
Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage
stage, Single dt)
   at
Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _jeEziyUSYl0BpbOxT46FYwj5VWL._IIIrDcgMyMKwpTkEZsHikpfl3dh(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._DvzT6D0wN3fMakeuDyljJJ09hok(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._V5piYzG7beYPldE6UVxY58dqacE(Single )
   at
Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object
sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double
frames_per_second)
   at
_YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h
, String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart
)
-------------------------------
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options,
NumberFormatInfo numfmt)
   at System.String.System.IConvertible.ToSingle(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType,
IFormatProvider provider)
   at
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader
reader, Object value, CultureInfo culture, JsonContract contract, Type
targetType)
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2021-02-25 1:41:58 PM, Site = , Source = Windows Error
Reporting, Message = Fault bucket 1539023757749266810, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 6033ac5b
P4: OPENGL32.DLL
P5: 10.0.19041.546
P6: f010886b
P7: c0000005
P8: 000000000001cf3c
P9:
P10:

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE6D4.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_d5668aca6f693d1df2c6c911d36ae1c4888f6aa_4fd6768e_505c0da4-0fed-4026-8ccb-1499fe7e5d16

Analysis symbol:
Rechecking for solution: 0
Report Id: e6ea600e-70c4-49fe-88b0-8383a2c7e792
Report Status: 268566528
Hashed bucket: 15215c137e0d5ddaa55bb5f41d88297a
Cab Guid: 0 }
--------------
{ TimeGenerated = 2021-02-25 1:41:56 PM, Site = , Source = Windows Error
Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 6033ac5b
P4: OPENGL32.DLL
P5: 10.0.19041.546
P6: f010886b
P7: c0000005
P8: 000000000001cf3c
P9:
P10:

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_d5668aca6f693d1df2c6c911d36ae1c4888f6aa_4fd6768e_505c0da4-0fed-4026-8ccb-1499fe7e5d16

Analysis symbol:
Rechecking for solution: 0
Report Id: e6ea600e-70c4-49fe-88b0-8383a2c7e792
Report Status: 131076
Hashed bucket:
Cab Guid: 0 }
--------------
{ TimeGenerated = 2021-02-25 1:41:55 PM, Site = , Source = Application
Error, Message = Faulting application name: Vintagestory.exe, version:
1.14.8.0, time stamp: 0x6033ac5b
Faulting module name: OPENGL32.DLL, version: 10.0.19041.546, time stamp:
0xf010886b
Exception code: 0xc0000005
Fault offset: 0x000000000001cf3c
Faulting process id: 0x498c
Faulting application start time: 0x01d70bae392d5c8d
Faulting application path: C:\Program Files
(x86)\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\SYSTEM32\OPENGL32.DLL
Report Id: e6ea600e-70c4-49fe-88b0-8383a2c7e792
Faulting package full name:
Faulting package-relative application ID:  }

**Comment by DrakeHawkins** [comment]
Second Method here ...


/worldconfig saplingGrowthDays 24
19:16:40 [Server Notification] Handling Command /worldconfig
saplingGrowthDays 24
Ok, value 24 set
19:16:40 [Server Notification] Ok, value 24 set

...

HURRAH!!!

19:18:34 [Server Event] DrakeHawkins 50.71.213.170:50208 joins.
19:18:36 [Server Notification] A client reconnected, resuming game calendar.

NO crash!
Thanks!

so the syntex shown  here left me ( and it seems many others) thinking you
need the [ ] arround the value ... ooops

**Comment by radfast** [comment]
I have updated the wiki with a pro tip saying do not use the [ ] around the value

I guess someone thought that was clear.

We can also make the game code detect invalid inputs I guess.

**Comment by Craluminum2413** [comment]
I remember how in the latest versions I wrote the value in [ ] for the propick radius, nothing crashed, so this is seems fixed
