### ISSUE TITLE
NullReferenceException when placing item on tool rack

### ISSUE THREAD

**Issue by spark503** [anegostudios/VintageStory-Issues#802]
**Game Version: v1.14.8
**Platform:** Windows 
**Modded:** No 
### Description
After updating, it has crashed multiple times throughout the day. Seems to be this most recent times because I'm trying to place the copper scythe into a tool rack.

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.8 (Stable)3/1/2021 6:01:58 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateItem(Item item, MeshData& modeldata, ITexPositionSource texSource)
   at Vintagestory.GameContent.BlockEntityToolrack.loadToolMeshes()
   at Vintagestory.GameContent.BlockEntityToolrack.didInteract(IPlayer player)
   at Vintagestory.GameContent.BlockEntityToolrack.PutInSlot(IPlayer player, Int32 slot)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _jeEziyUSYl0BpbOxT46FYwj5VWL._IIIrDcgMyMKwpTkEZsHikpfl3dh(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._DvzT6D0wN3fMakeuDyljJJ09hok(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._V5piYzG7beYPldE6UVxY58dqacE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2/15/2021 11:48:30 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.13.4.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\ADMINI~1\AppData\Local\Temp\RDRCFFE.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD05C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD06D.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD08A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD0BA.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: e8b5e81a-e620-46e9-9d54-9e56da00d2f5
Report Status: 536871008
Hashed bucket: 
Cab Guid: 0 }
```

latest one:

```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.8 (Stable)3/1/2021 6:07:46 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateItem(Item item, MeshData& modeldata, ITexPositionSource texSource)
   at Vintagestory.GameContent.BlockEntityToolrack.loadToolMeshes()
   at Vintagestory.GameContent.BlockEntityToolrack.didInteract(IPlayer player)
   at Vintagestory.GameContent.BlockEntityToolrack.TakeFromSlot(IPlayer player, Int32 slot)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _jeEziyUSYl0BpbOxT46FYwj5VWL._IIIrDcgMyMKwpTkEZsHikpfl3dh(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._DvzT6D0wN3fMakeuDyljJJ09hok(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._V5piYzG7beYPldE6UVxY58dqacE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2/15/2021 11:48:30 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.13.4.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\ADMINI~1\AppData\Local\Temp\RDRCFFE.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD05C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD06D.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD08A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD0BA.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: e8b5e81a-e620-46e9-9d54-9e56da00d2f5
Report Status: 536871008
Hashed bucket: 
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment]
Closing due to inactivity
