### ISSUE TITLE
Smithing Top Iron Anvil crashes the game

### ISSUE THREAD

**Issue by AlanFistwood** [anegostudios/VintageStory-Issues#803]
**Game Version:** 1.14.8
**Platform:** Windows
**Modded:** No

### Description
I was smithing an top of an iron anvil. when I hit on one of the voxel the game crashes

### How to reproduce
1. Make a iron anvil top
2. At some point in the procces when you hammer the voxels
3. It crashes

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 0 GB RAM 
Version: v1.14.8-rc.1 (Unstable)3/2/2021 7:02:57 PM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockEntityAnvil.OnUpset(Vec3i voxelPos, BlockFacing towardsFace)
   at Vintagestory.GameContent.BlockEntityAnvil.OnUseOver(IPlayer byPlayer, Vec3i voxelPos, BlockSelection blockSel)
   at Vintagestory.GameContent.ItemHammer.OnHeldAttackStop(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _ipdCTRGfCLl4yfQcpbyWZPZzBMZ._6C2asSglREPHjhx4NLj6jpKXKpH(Single )
   at _yWbPNPMmCoSseGoOZRcjfcIN4XC._OmZfb14mkw8Un0aM6Go5rdXofbC(Single )
   at _yWbPNPMmCoSseGoOZRcjfcIN4XC._3fRWFqXCqVOAQhIDfL6UaZGgx2o(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _KWsZWkZAuZolPgdae7el5tHBTClA._q6fsrB8CmVl3iiVwe0lNTjMFm0(_Pz3UPCq6dLufqfMv42T2mvIRCDn , String[] )
   at _45bJKQetuLcXXKsD9ELwUG90ErH._q6fsrB8CmVl3iiVwe0lNTjMFm0(ThreadStart )
-------------------------------

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```

**Comment by copygirl** [comment]
I'm going to close this as duplicate for #800 for now - there has been a number of reports of this issue in the past already. If you can provide a screenshot of which exact voxel you're moving and with which tool mode that causes the crash, please do so!
