### ISSUE TITLE
game crashes on start

### ISSUE THREAD

**Issue by gymteach** [anegostudios/VintageStory-Issues#814]
Windows

### Description
Game crashes on start.  Often crashes randomly.  Actually shuts down my computer when it crashes.

### How to reproduce
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.14.8 (Stable)3/13/2021 2:16:38 PM: Critical error occurred
System.Data.SQLite.SQLiteException (0x80004005): The database disk image is malformed
database disk image is malformed
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Vintagestory.GameContent.MapDB.GetMapPiece(Vec2i chunkCoord)
   at Vintagestory.GameContent.ChunkMapLayer.OnOffThreadTick(Single dt)
   at Vintagestory.GameContent.WorldMapManager.<OnLoaded>b__23_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/13/2021 2:16:45 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1602912988423389626, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 6033ac5b
P4: System.Data.SQLite
P5: 1.0.81.0
P6: 4fe8a177
P7: 9b
P8: 84
P9: System.Data.SQLite.SQLite
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC631.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCE9E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCECE.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCEDB.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCF2B.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_7a2693aeba9547bda81194bced59a1b11dc57389_4fd6768e_a586798d-700a-4a37-a2d6-da0c5b0e135c

Analysis symbol: 
Rechecking for solution: 0
Report Id: 593f353c-61e3-421e-9ce4-96d6925ac59a
Report Status: 268435456
Hashed bucket: 20b765ee244413c0263eb0ded0d601ba
Cab Guid: 0 }
--------------
{ TimeGenerated = 3/13/2021 2:16:41 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.14.8.0, time stamp: 0x6033ac5b
Faulting module name: KERNELBASE.dll, version: 10.0.19041.804, time stamp: 0x0e9c5eae
Exception code: 0xe0434352
Fault offset: 0x000000000002d759
Faulting process id: 0x140c
Faulting application start time: 0x01d7183d311ddec1
Faulting application path: C:\Users\James Morgan\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 593f353c-61e3-421e-9ce4-96d6925ac59a
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 3/13/2021 2:16:41 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Data.SQLite.SQLiteException
   at System.Data.SQLite.SQLite3.Reset(System.Data.SQLite.SQLiteStatement)
   at System.Data.SQLite.SQLite3.Step(System.Data.SQLite.SQLiteStatement)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(System.Data.SQLite.SQLiteCommand, System.Data.CommandBehavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(System.Data.CommandBehavior)
   at Vintagestory.GameContent.MapDB.GetMapPiece(Vintagestory.API.MathTools.Vec2i)
   at Vintagestory.GameContent.ChunkMapLayer.OnOffThreadTick(Single)
   at Vintagestory.GameContent.WorldMapManager.<OnLoaded>b__23_0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

 }
In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```

**Comment by copygirl** [comment]
The game might have started crashing regularly from your save file being corrupted due to an earlier crash. Your entire computer should not shut down due to an error in the game. Not sure if this is the appropriate advice, but do make sure your storage drives and RAM are okay and have plenty of space.

Do you get these crashes even if you play in a new world?

**Comment by gymteach** [comment]
Yes, I get them in a new world as well.

**Comment by gymteach** [comment]
Correction, it allowed me to create a new world.  Now the crashes shut down the game, but not the computer.  I guess that is progress.  I appreciate any ideas.  I will have my system checked out.  Its a good idea.  Thank you.

Running on 64 bit Windows with 8 GB RAM 
Version: v1.14.8 (Stable)3/13/2021 3:41:06 PM: Critical error occurred
System.Data.SQLite.SQLiteException (0x80004005): The database disk image is malformed
database disk image is malformed
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Vintagestory.GameContent.MapDB.GetMapPiece(Vec2i chunkCoord)
   at Vintagestory.GameContent.ChunkMapLayer.OnOffThreadTick(Single dt)
   at Vintagestory.GameContent.WorldMapManager.<OnLoaded>b__23_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/13/2021 3:41:10 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1602912988423389626, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 6033ac5b
P4: System.Data.SQLite
P5: 1.0.81.0
P6: 4fe8a177
P7: 9b
P8: 84
P9: System.Data.SQLite.SQLite
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER112D.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1787.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER17C7.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER17D5.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1833.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_7a2693aeba9547bda81194bced59a1b11dc57389_4fd6768e_5c305672-938f-43fc-a30e-81a011be567f

Analysis symbol: 
Rechecking for solution: 0
Report Id: 7f5f1ae0-268b-4bcd-ba95-7fa0dc8082ed
Report Status: 268435456
Hashed bucket: 20b765ee244413c0263eb0ded0d601ba
Cab Guid: 0 }
--------------
{ TimeGenerated = 3/13/2021 3:41:07 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.14.8.0, time stamp: 0x6033ac5b
Faulting module name: KERNELBASE.dll, version: 10.0.19041.804, time stamp: 0x0e9c5eae
Exception code: 0xe0434352
Fault offset: 0x000000000002d759
Faulting process id: 0x172c
Faulting application start time: 0x01d7184910500943
Faulting application path: C:\Users\James Morgan\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 7f5f1ae0-268b-4bcd-ba95-7fa0dc8082ed
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 3/13/2021 3:41:06 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Data.SQLite.SQLiteException
   at System.Data.SQLite.SQLite3.Reset(System.Data.SQLite.SQLiteStatement)
   at System.Data.SQLite.SQLite3.Step(System.Data.SQLite.SQLiteStatement)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(System.Data.SQLite.SQLiteCommand, System.Data.CommandBehavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(System.Data.CommandBehavior)
   at Vintagestory.GameContent.MapDB.GetMapPiece(Vintagestory.API.MathTools.Vec2i)
   at Vintagestory.GameContent.ChunkMapLayer.OnOffThreadTick(Single)
   at Vintagestory.GameContent.WorldMapManager.<OnLoaded>b__23_0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

 }
