### ISSUE TITLE
Game crash specific to one save (LAN)

### ISSUE THREAD

**Issue by novvon** [anegostudios/VintageStory-Issues#815]
played about 1.5hrs with some friends on my world I hosted thru LAN, and then the game crashed and now every time I try and load the same world, I can play for about 30 seconds before it crashes again.

I can make a new world and play just fine, so it looks like its only affecting the one save.

[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/6135602/client-crash.txt)

Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.8 (Stable)3/13/2021 3:14:46 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.EntityItem.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntitySpawnPacket(_uQLFO3G34CNPass7LE9Zs5TcuUF serverpacket)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _jeEziyUSYl0BpbOxT46FYwj5VWL._t25VgrofhlXMw6hHEZh8JHhJz1A(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._DvzT6D0wN3fMakeuDyljJJ09hok(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._V5piYzG7beYPldE6UVxY58dqacE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/13/2021 3:04:07 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1403937670060740015, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 6033ac5b
P4: VintagestoryAPI
P5: 1.7.0.0
P6: 6033ac59
P7: 16c1
P8: 21
P9: System.AccessViolationException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9080.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER93BD.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER93CE.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER93DB.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER93FC.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_fb4a5c15a2775d58eb223ab13d0768d529ba392_4fd6768e_af28b4c2-9759-44ca-bb3c-e81203834515

Analysis symbol: 
Rechecking for solution: 0
Report Id: 196456d4-c1e8-4707-bf2f-102f8d6d8c10
Report Status: 268435456
Hashed bucket: 7da72c221e309030437bc9df5ec28daf
Cab Guid: 0 }
--------------
{ TimeGenerated = 3/13/2021 3:04:05 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.14.8.0, time stamp: 0x6033ac5b
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ff7bf7d4dda
Faulting process id: 0x38d8
Faulting application start time: 0x01d71845464b135a
Faulting application path: C:\Users\John\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: unknown
Report Id: 196456d4-c1e8-4707-bf2f-102f8d6d8c10
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 3/13/2021 3:04:04 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Vintagestory.API.Client.MeshDataPoolManager.Render(Vintagestory.API.MathTools.Vec3d, System.String, Vintagestory.API.Client.EnumFrustumCullMode)
   at Vintagestory.Client.NoObf.ChunkRenderer.RenderShadow(Single)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single)
   at _jeEziyUSYl0BpbOxT46FYwj5VWL._t25VgrofhlXMw6hHEZh8JHhJz1A(Single)
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._DvzT6D0wN3fMakeuDyljJJ09hok(Single)
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._V5piYzG7beYPldE6UVxY58dqacE(Single)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h, System.String[])
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(System.Threading.ThreadStart)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._M1VY8jQRHnZmSa0tV4cFASebLsH(System.String[])

 }

**Comment by copygirl** [comment]
The occurence of the error is annoying but can often be fixed by starting the world in repair mode. Have you tried that yet? (You go to the world selection screen and click the pencil, there is a button to "run in repair mode".)

**Comment by copygirl** [comment]
Closing due to lack of response.
