### ISSUE TITLE
Game Crash Multiplayer on Crucible Pickup

### ISSUE THREAD

**Issue by BurntRouter** [anegostudios/VintageStory-Issues#817]
**Game Version:** X.Y.Z
**Platform:** Windows / Mac / Linux (which?)
**Modded:** Yes: VSHUD, CarryCapacitym Desertflora, ExpandedFoods, GrassStuff, LakeFlowers, PrimitiveSurvival, Neolithic

### Description
Full client and server crash on bad crucible interaction

### How to reproduce
Play multiplayer
Pickup crucible at same time as somebody else

### Expected behavior
Not crash ;)

### Logs
```
Version: v1.14.8 (Stable)3/17/2021 12:38:50 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockSmeltedContainer.GetDrops(IWorldAccessor world, BlockPos pos, IPlayer byPlayer, Single dropQuantityMultiplier)
   at Vintagestory.GameContent.BlockSmeltedContainer.OnPickBlock(IWorldAccessor world, BlockPos pos)
   at Vintagestory.API.Common.Block.GetPlacedBlockName(IWorldAccessor world, BlockPos pos)
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.ComposeBlockInfoHud()
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.BlockInView()
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _jeEziyUSYl0BpbOxT46FYwj5VWL._t25VgrofhlXMw6hHEZh8JHhJz1A(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._DvzT6D0wN3fMakeuDyljJJ09hok(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._V5piYzG7beYPldE6UVxY58dqacE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
```
[server-main.txt](https://gist.github.com/BurntRouter/75b489f14b75a14039af53101ab31e71)
[client-main.txt](https://gist.github.com/BurntRouter/276f2d71e6152b79f7603bf2b0b0fd1d)

**Comment by Craluminum2413** [comment]
I think this is Carry Capacity, because I had almost the same crash under the same conditions, but with an echo chumber

**Comment by copygirl** [comment]
Crucibles can't be picked up with CarryCapacity. The stacktrace is more similar to #509.

**Comment by Craluminum2413** [comment]
These are identical crash logs #509
