### ISSUE TITLE
Crash on mousing over full Cooking Pot

### ISSUE THREAD

**Issue by firox39** [anegostudios/VintageStory-Issues#818]
I'm running a few mods, including the latest version of Expanded Foods (1.2.4)
This crash happens only when I mouse over the item in the campfire output, not when it is actually done cooking. It also happens every time I cook any type of meal (I've tested with 4 different kinds, both vanilla and recipes added by Expanded Foods)

```
--------------------
Running on 64 bit Windows with 8 GB RAM 
Version: v1.14.8 (Stable)3/19/2021 12:38:35 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockCookedContainer.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug)
   at Vintagestory.API.Client.GuiElementItemstackInfo.Recompose()
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot)
   at Vintagestory.Client.NoObf.HudMouseTools.OnMouseEnterSlot(ItemSlot slot)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerOnMouseEnterSlot(ClientMain game, ItemSlot slot)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseMove(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseMove(MouseEvent mouse)
   at Vintagestory.API.Client.GuiDialog.OnMouseMove(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseMove(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseMove(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.UpdateMousePosition()
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/18/2021 8:07:56 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFB1370D759
Stack:
 }
--------------
{ TimeGenerated = 3/18/2021 10:00:33 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1564561481470198046, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\firox\AppData\Local\Temp\RDR2969.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2989.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER29A9.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER29C7.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER29F6.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 72420e2d-8c3e-40b0-bea4-2a575072a0a9
Report Status: 268435456
Hashed bucket: 2422f0d2706eedebe5b67060c44a411e
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment]
I think this has been fixed in subsequent versions of Expanded Foods mod

**Comment by copygirl** [comment]
Oh yeah if this crash can't be reproduced in Vanilla, it's probably best for the mod author to look at it, and make a report themselves if they know it to be an issue with the game? Apologies.
