### ISSUE TITLE
I cant play the game because it keeps crashing when i try to play

### ISSUE THREAD

**Issue by MITroboticsHACK** [anegostudios/VintageStory-Issues#820]
**Game Version:** X.Y.Z
**Platform:** Windows / Mac / Linux (whRunning on 64 bit Windows with 16 GB RAM 
Version: v1.14.8 (Stable)3/20/2021 7:05:39 PM: Critical error occurred
System.Exception: EndOfStreamException thrown while reading entity, you might be able to recover your savegame through repair mode ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.MemoryStream.InternalReadInt32()
   at Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   --- End of inner exception stack trace ---
   at Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.API.Common.EntityPlayer.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.Client.NoObf.ClientSystemEntities.createOrUpdateEntityFromPacket(_fjrI1GnJsEjAeKDyGGMlSIq0cUA entitypacket, ClientMain game, Boolean addToLoadQueue)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityLoadedPacket(_uQLFO3G34CNPass7LE9Zs5TcuUF serverpacket)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _h57p42MkW1QbZF33dSw2nGDMdRj._IIIrDcgMyMKwpTkEZsHikpfl3dh(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._DvzT6D0wN3fMakeuDyljJJ09hok(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._V5piYzG7beYPldE6UVxY58dqacE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.MemoryStream.InternalReadInt32()
   at Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/13/2021 12:29:22 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1822032227626530173, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\shawn\AppData\Local\Temp\RDR8182.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8193.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8194.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER81B1.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER81D1.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 01926d37-7d59-4677-9781-769e72edef6b
Report Status: 268435456
Hashed bucket: a995c73cc234971ef94928a850fe357d
Cab Guid: 0 }ich?)
**Modded:** No / Yes (which?)

### Description
Explain the issue you're running into.

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash here.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```

**Comment by MITroboticsHACK** [comment]
it works when I use a new world

**Comment by MITroboticsHACK** [comment]
fixed it
