### ISSUE TITLE
Repeating crash after stacking charcoal pile

### ISSUE THREAD

**Issue by CptPhil** [anegostudios/VintageStory-Issues#842]
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.14.8 (Stable)30/03/2021 21:31:35: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockCoalPile.GetSelectionBoxes(IBlockAccessor blockAccessor, BlockPos pos)
   at Vintagestory.API.MathTools.AABBIntersectionTest.RayIntersectsBlockSelectionBox(BlockPos pos, BlockFilter filter)
   at Vintagestory.API.MathTools.AABBIntersectionTest.GetSelectedBlock(Single maxDistance, BlockFilter filter)
   at Vintagestory.Common.GameMain.RayTraceForSelection(IWorldIntersectionSupplier supplier, Ray ray, BlockSelection& blockSelection, EntitySelection& entitySelection, BlockFilter bfilter, EntityFilter efilter)
   at Vintagestory.Common.GameMain.RayTraceForSelection(IPlayer player, BlockSelection& blockSelection, EntitySelection& entitySelection, BlockFilter bfilter, EntityFilter efilter)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.UpdateCurrentSelection()
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.UpdatePicking(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _jeEziyUSYl0BpbOxT46FYwj5VWL._IIIrDcgMyMKwpTkEZsHikpfl3dh(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._DvzT6D0wN3fMakeuDyljJJ09hok(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._V5piYzG7beYPldE6UVxY58dqacE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------
```

**Comment by copygirl** [comment]
According to the stack trace you might be looking at a coal pile as you log in. Either there's something wrong about its state or some state has not managed to syncronise with your as you're logging in, causing this crash. See if another player can remove this coal pile for now.

**Comment by CptPhil** [comment]
Hi,

And thank you again for getting back to me so soon.

One of my friends just tried to remove the blocks but the same issue happened and the game crashed.

Whoops my bad.

Any help would be great!

Thank you

Phil

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by copygirl** [comment]
When you say the same issue happened do you mean their game crashed, or you still get the same issue despite the blocks being removed? For some reason the coal pile appears to have more layers than should be possible. I don't suppose you know what might have caused this?

**Comment by CptPhil** [comment]
Hi,

sorry for not getting back sooner. My emails not been updating as expected... ok so what happened. I had used creative mode to spawn a shovel as removed my original as had been using creative to build a castle elsewhere away from our main base, taking it off my hot bar. I was about to go to bed shortly (in real life) and wanted to mine some charcoal I set burning before I leave. But because I’m not the smartest. I forgot to turn off creative. So I deleted the charcoal blocks instead of mining it.... not wanting to look an idiot and miss out on it digging out and collecting the charcoal (makes a nice sound also). So I spawned in some charcoal lumps and set about seeing if I could stack it like fire wood. It seemed to work but after I stacked a few layers (more than two) the game crashed. So in an effort to correct a mishap of laziness I kinda broke our world it seems...

Happy to provide any more information I can recall.

Kind regards

Phil

Sent from my iPhone

On 31 Mar 2021, at 20:32, copygirl ***@***.***> wrote:

﻿

When you say the same issue happened do you mean their game crashed, or you still get the same issue despite the blocks being removed? For some reason the coal pile appears to have more layers than should be possible. I don't suppose you know what might have caused this?

**Comment by Craluminum2413** [comment]
https://user-images.githubusercontent.com/69315569/121951904-32f0d600-cd64-11eb-87b5-a856f43188aa.mp4

**Comment by copygirl** [comment]
Indeed. Piles have been redone so it's possible that this specific issue has disappeared.
