### ISSUE TITLE
Game Crashes when attempting to load map on multiplayer or corrupts during map creation in singleplayer

### ISSUE THREAD

**Issue by TheTalkinPotato** [anegostudios/VintageStory-Issues#845]
**Game Version:** Version: v1.14.8 
**Platform:** Windows
**Modded:** no

### Description
When attempting to create or load into a multiplayer map It crashes on multiplayer. On single player it runs into an error and stops creating right at the start with this error. 

(Single Player Crash Log)
`31.3.2021 18:38:44 [Notification] Server logger started.
31.3.2021 18:38:44 [Notification] Game Version: v1.14.8 (Stable)
31.3.2021 18:38:44 [Event] Launching server...
31.3.2021 18:38:44 [Event] Server v1.14.8, network v1.14.13, api v1.7.0
31.3.2021 18:38:44 [Notification] Entering runphase Initialization
31.3.2021 18:38:45 [Event] Loading configuration...
31.3.2021 18:38:45 [Notification] Entering runphase Configuration
31.3.2021 18:38:45 [Notification] serverconfig.json not found, creating new one
31.3.2021 18:38:45 [Error] Failed opening savegame.System.IO.FileNotFoundException: Could not load file or assembly 'System.EnterpriseServices.Wrapper.dll' or one of its dependencies. The specified module could not be found.
File name: 'System.EnterpriseServices.Wrapper.dll' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.EnterpriseServices.Wrapper.dll' or one of its dependencies. The specified module could not be found.
File name: 'System.EnterpriseServices.Wrapper.dll' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.EnterpriseServices.Wrapper.dll' or one of its dependencies. The specified module could not be found.
File name: 'System.EnterpriseServices.Wrapper.dll'

### How to reproduce
Join a server and it crashes. 

Create a single player server and it fails to create it.

### Expected behavior
To create the server and join or join multiplayer server

### Logs
(Mutliplayer Crash Log)
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.8 (Stable)2021-03-31 6:41:09 PM: Critical error occurred
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Cannot open C:\Users\edrrr\AppData\Roaming\VintagestoryData\Maps\b7f3eefa-25ef-4ff0-aa42-54a3db704f2b.db, possibly corrupted. Please fix manually or delete this file to continue playing
   at Vintagestory.GameContent.ChunkMapLayer..ctor(ICoreAPI api, IWorldMapManager mapSink)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Vintagestory.GameContent.WorldMapManager.OnLoaded()
   at Vintagestory.API.Common.Action.Invoke()
   at Vintagestory.Client.NoObf.ClientMain.OnServerBlocksItemsReceivedStep5(Action onCompleted)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _h57p42MkW1QbZF33dSw2nGDMdRj._IIIrDcgMyMKwpTkEZsHikpfl3dh(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._DvzT6D0wN3fMakeuDyljJJ09hok(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._V5piYzG7beYPldE6UVxY58dqacE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------
System.Exception: Cannot open C:\Users\edrrr\AppData\Roaming\VintagestoryData\Maps\b7f3eefa-25ef-4ff0-aa42-54a3db704f2b.db, possibly corrupted. Please fix manually or delete this file to continue playing
   at Vintagestory.GameContent.ChunkMapLayer..ctor(ICoreAPI api, IWorldMapManager mapSink)
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2021-03-31 6:09:49 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1564561481470198046, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\edrrr\AppData\Local\Temp\RDRA71A.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA71B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA72C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA759.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA779.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 783eda54-5786-4dc1-90ea-12d354bcc50f
Report Status: 268435456
Hashed bucket: 2422f0d2706eedebe5b67060c44a411e
Cab Guid: 0 }

**Comment by TheTalkinPotato** [comment]
I fixed the issue, was due to missing Microsoft .Net Framework

**Comment by tyronx** [comment]
👌
