### ISSUE TITLE
create new world reusing seed crashes every time

### ISSUE THREAD

**Issue by Rolocandy** [anegostudios/VintageStory-Issues#846]
**Game Version:** 1.14.8
**Platform:** Windows 10
**Modded:** No

### Description
Totally vanilla install only a few days old. Trying to reuse seed crashes game, every seed i have tried does this

also oddly enough during this last crash the flint axe stopped cutting down trees after 15 minutes of play. the axe showed wear and tree showed blocks flying off it but the tree never came down. happened to all types of trees

### How to reproduce
1. Make a standard game
2. Use it on '....'
3. It crashes 

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash here.

Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.8 (Stable)4/2/2021 10:32:43 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _PW8NVVq6wBR9krMQ9GulRnv6PMD._h9K0G4wbrt2CCpt5A92lCnKV2gP()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _oDnqPT3M9pq9hNGZM4RDtA6RTnG._TE0ypoo5kb57Ue2gLv7daIuY6VD(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------


In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.

2.4.2021 10:32:43 [Fatal] Version: v1.14.8 (Stable)4/2/2021 10:32:43 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _PW8NVVq6wBR9krMQ9GulRnv6PMD._h9K0G4wbrt2CCpt5A92lCnKV2gP()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _oDnqPT3M9pq9hNGZM4RDtA6RTnG._TE0ypoo5kb57Ue2gLv7daIuY6VD(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------
Crash written to file at "C:\Users\bebo\AppData\Roaming\VintagestoryData\Logs\client-crash.txt"

2.4.2021 10:32:43 [Notification] Exiting game now. Server running=False. Exit reason: Game crashed

**Comment by Rolocandy** [comment]
update (this fixed the problem I was having)
I uninstalled 1.14.8 and installed 1.14.0 pre.12. This allowed me to reuse seeds
If I then update 1.14.0 to 1.14.8 the crashing behaviour returns

**Comment by copygirl** [comment]
Thank you for the insight. I will mention your comment in #795. Closing as duplicate, however.
