### ISSUE TITLE
Right clicking on barrel while holding filled barrel causes crash

### ISSUE THREAD

**Issue by SingABrightSong** [anegostudios/VintageStory-Issues#859]
**Game Version:** 1.14.8
**Platform:** Windows
**Modded:** No

### Description
Right clicking on a filled barrel while holding a filled barrel obtained with Pick Block in Creative Mode causes a game crash

### How to reproduce
1. Create new Creative world
2. Place barrel
3. Fill barrel with salt
4. Use middle-mouse button on barrel to add it to your hotbar
5. Right click on barrel while holding filled barrel
### Expected behavior
To open the interface
### Screenshots

![image](https://user-images.githubusercontent.com/1489009/114254697-228c3b80-996e-11eb-9992-829a65cc0225.png)

![image](https://user-images.githubusercontent.com/1489009/114254637-cb866680-996d-11eb-9d93-7a1e89e068d1.png)

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.8 (Stable)2021-04-09 7:55:35 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockLiquidContainerBase.TryPutContent(IWorldAccessor world, BlockPos pos, ItemStack contentStack, Int32 quantity)
   at Vintagestory.GameContent.BlockLiquidContainerBase.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel)
   at Vintagestory.GameContent.BlockBarrel.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _jeEziyUSYl0BpbOxT46FYwj5VWL._IIIrDcgMyMKwpTkEZsHikpfl3dh(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._DvzT6D0wN3fMakeuDyljJJ09hok(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._V5piYzG7beYPldE6UVxY58dqacE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------
```

**Comment by Craluminum2413** [comment]
Fixed in [1.16.0-rc.6](https://www.vintagestory.at/blog.html/news/homesteading-part-2-6th-release-candidate-1160-rc6-r307/#:~:text=Fixed%3A%20Game%20crashing%20when%20right%20clicking%20a%20barrel%20with%20a%20barrel%20in%20hands)
