### ISSUE TITLE
Reproducible crash with mod defined custom colored bags

### ISSUE THREAD

**Issue by DoctorVanGogh** [anegostudios/VintageStory-Issues#860]
**Game Version:** 1.14.8
**Platform:** Windows
**Modded:** Yes (SpecializedBags)

### Description
Game crashes if a mod defines bags with custom background colors and those bags are switched with other colored inventory bags while the player inventory is open.

See https://github.com/DeviatorTX/SpecializedBags/issues/1 for original issue report.

### How to reproduce
1. Use SpecializedBags mod
2. Spawn and equip a Forestry or Agriculture or Builder Bag
3. Put down a chest
4. Put a mining bag into chest
5. **Open the player inventory** (E), open the chest, pick up the mining back and replace the equipped specialized bag from step 2.
6. **Crash**

### Expected behavior
No crash :grin:

### Screenshots
I'll do you even better - a video: https://youtu.be/m_SWgBUF6VM

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.8 (Stable)04.04.2021 02:20:12: Critical error occurred
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.RenderInteractiveElements(Single deltaTime)
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime)
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _jeEziyUSYl0BpbOxT46FYwj5VWL._IIIrDcgMyMKwpTkEZsHikpfl3dh(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._DvzT6D0wN3fMakeuDyljJJ09hok(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._V5piYzG7beYPldE6UVxY58dqacE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------
```

---
I did some digging (gotta *love* dnSpy) and it seems the issue is triggered in 

```cs
namespace Vintagestory.API.Client {
  ...
  public abstract class GuiElementItemSlotGridBase : GuiElement {
    ...
    public override void RenderInteractiveElements(float deltaTime) {
      ...
      foreach (KeyValuePair<int, ItemSlot> keyValuePair in this.renderedSlots)
      {
      ...
      if (elementBounds.PartiallyInside(this.Bounds.ParentBounds))
      {
        ItemSlot value = keyValuePair.Value;
        int key = keyValuePair.Key;
        if (((value.Itemstack == null || this.AlwaysRenderIcon) && value.BackgroundIcon != null) || value.HexBackgroundColor != null)
        {
        string key2 = value.BackgroundIcon + "-" + value.HexBackgroundColor;
        this.api.Render.Render2DTexturePremultipliedAlpha(this.slotTextureIdsByBgIconAndColor[key2], elementBounds, 50f, null);
        ...
```
specifically the
```cs
this.slotTextureIdsByBgIconAndColor[key2]
```
access.

`slotTextureIdsByBgIconAndColor` has no entry for the custom bag element.
![image](https://user-images.githubusercontent.com/324067/114257345-a91d3900-99bf-11eb-83da-3569dbee72ac.png)

It almost looks like a previous call to `ComposeInteractiveElements` (which should initialize `slotTextureIdsByBgIconAndColor` as far as I understand) either does not happen or does not correctly set things up for later rendering.

**Comment by Craluminum2413** [comment]
Works fine
