### ISSUE TITLE
Mod defined liquids in barrels cause crash in barrel GUI

### ISSUE THREAD

**Issue by DoctorVanGogh** [anegostudios/VintageStory-Issues#863]
**Game Version:** 1.14.8
**Platform:** Windows
**Modded:** Yes
- [ExpandedFoods 1.3.2](https://mods.vintagestory.at/download?fileid=1008)

### Description
Putting a mod defined liquid (with a non default domain for waterTightContainerProps texture) in a barrel causes a crash in the barrel GUI.

### How to reproduce
1. Use ExpandedFoods 1.3.**2**
2. Create new world
3. Spawn in barrel
4. Place Barrel
5. Spawn in a juice portion
5. Open Barrel GUI
6. Try placing juice portion into barrel's item slot
7. **Crash**

### Expected behavior
No Crash :wink:

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.8 (Stable)14.04.2021 18:56:13: Critical error occurred
System.Exception: Asset game:textures/item/food/liquid/cranberry.png could not be found
   at Vintagestory.Common.AssetManager.Get(AssetLocation Location)
   at Vintagestory.API.Client.GuiElement.getImageSurfaceFromAsset(ICoreClientAPI capi, String texFileName)
   at Vintagestory.API.Client.GuiElement.getPattern(ICoreClientAPI capi, String texFileName, Boolean doCache)
   at Vintagestory.API.Client.GuiElement.fillWithPattern(ICoreClientAPI capi, Context ctx, String texFileName, Boolean nearestScalingFiler, Boolean preserve)
   at Vintagestory.GameContent.GuiDialogBarrel.fullnessMeterDraw(Context ctx, ImageSurface surface, ElementBounds currentBounds)
   at Vintagestory.API.Client.GuiElementCustomDraw.Redraw()
   at Vintagestory.GameContent.GuiDialogBarrel.UpdateContents()
   at Vintagestory.GameContent.BlockEntityBarrel.Inventory_SlotModified(Int32 slotId)
   at Vintagestory.API.Common.Action`1.Invoke(T t1)
   at Vintagestory.API.Common.InventoryBase.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack)
   at Vintagestory.API.Common.ItemSlot.MarkDirty()
   at Vintagestory.API.Common.ItemSlotBarrelInput.OnItemSlotModified(ItemStack stack)
   at Vintagestory.API.Common.InventoryBase.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed)
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse)
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs)
   at Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------
```

---
I did some digging trying to find out if this was a mod caused crash. It was not :(

`GuiDialogBarrel.fullnessMeterDraw(Context ctx, ImageSurface surface, ElementBounds currentBounds)` 

has the guilty code lines:
```cs
...
AssetLocation assetLocation = compositeTexture2.Base.Clone().WithPathAppendixOnce(".png");
GuiElement.fillWithPattern(this.capi, ctx, assetLocation.Path, true, false);
...
```
The asset location is correctly cloned at first, but then only has its **path** (without the defining mod's domain) passed into the drawing methods.
Subsequent calls ultimately end up in `GuiElement.getImageSurfaceFromAsset` which creates a *new* asset location:
```cs
...
byte[] data = capi.Assets.Get("textures/" + texFileName).Data;
...
```
which *only* contains the original path (with a prefix), but no longer has any information about the asset's original domain. So what might have been a texture definition of `foo:bar...` has now become `game:bar...`.
Thus the lookup fails, thus the crash.

**Comment by Craluminum2413** [comment]
Closing due to inactivity
