### ISSUE TITLE
Game crashes on specific multiplayer server (corrupted map data?)

### ISSUE THREAD

**Issue by embienbi** [anegostudios/VintageStory-Issues#868]
**Game Version:** 1.14.8-10
**Platform:** Windows
**Modded:** No

### Description
I have played the game in single player with no problems, in multiplayer on other servers without issue, but on one server the game crashes as soon as I log in. The server owner has tried deleting my character from the server in case the issue was with my inventory, but the error continues.

### How to reproduce
It just happens, I don't know why

### Expected behavior
To log in to server

### Screenshots
n/a

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.8 (Stable)4/7/2021 7:38:56 PM: Critical error occurred
System.Data.SQLite.SQLiteException (0x80004005): The database disk image is malformed
database disk image is malformed
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at Vintagestory.GameContent.MapDB.SetMapPieces(Dictionary`2 pieces)
   at Vintagestory.GameContent.ChunkMapLayer.OnOffThreadTick(Single dt)
   at Vintagestory.GameContent.WorldMapManager.<OnLoaded>b__23_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 4/7/2021 7:38:58 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1602912988423389626, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 6033ac5b
P4: System.Data.SQLite
P5: 1.0.81.0
P6: 4fe8a177
P7: 9b
P8: 84
P9: System.Data.SQLite.SQLite
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBC06.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBF04.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBF24.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBF22.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBF43.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_7a2693aeba9547bda81194bced59a1b11dc57389_4fd6768e_993b4a71-b521-42b9-8539-a0ece1eb38e9

Analysis symbol: 
Rechecking for solution: 0
Report Id: 57a54dac-06dd-493e-8b72-d7cbcc5c4a8e
Report Status: 268435456
Hashed bucket: 20b765ee244413c0263eb0ded0d601ba
Cab Guid: 0 }
--------------
{ TimeGenerated = 4/7/2021 7:38:56 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.14.8.0, time stamp: 0x6033ac5b
Faulting module name: KERNELBASE.dll, version: 10.0.19041.804, time stamp: 0x0e9c5eae
Exception code: 0xe0434352
Fault offset: 0x000000000002d759
Faulting process id: 0x3b60
Faulting application start time: 0x01d72c06b69e1446
Faulting application path: D:\Users\Em\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 57a54dac-06dd-493e-8b72-d7cbcc5c4a8e
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 4/7/2021 7:38:56 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Data.SQLite.SQLiteException
   at System.Data.SQLite.SQLite3.Reset(System.Data.SQLite.SQLiteStatement)
   at System.Data.SQLite.SQLite3.Step(System.Data.SQLite.SQLiteStatement)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(System.Data.SQLite.SQLiteCommand, System.Data.CommandBehavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(System.Data.CommandBehavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at Vintagestory.GameContent.MapDB.SetMapPieces(System.Collections.Generic.Dictionary`2<Vintagestory.API.MathTools.Vec2i,Vintagestory.GameContent.MapPieceDB>)
   at Vintagestory.GameContent.ChunkMapLayer.OnOffThreadTick(Single)
   at Vintagestory.GameContent.WorldMapManager.<OnLoaded>b__23_0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

 }
```

**Comment by Craluminum2413** [comment]
What's server?

**Comment by embienbi** [comment]
> What's server?

It's a private one shared with a household member. I haven't used any public servers. Other privately hosted servers with friends work fine.

**Comment by copygirl** [comment]
Sorry for the late response. It looks like the world map information for that server got corrupted. I'm not entirely sure at this time whether this is stored on the server or client. But if my guess is correct, you could check the `Maps/` folder in `VintagestoryData` and clear the one associated with the server. I have no idea how to find out which it is. In the worst case, you could move them out of the folder one by one until the error disappears, then move all but the latest one you moved back in. (Or, if you don't care about any maps (including singleplayer ones), you could just delete them all.)

**Comment by embienbi** [comment]
> Sorry for the late response. It looks like the world map information for that server got corrupted. I'm not entirely sure at this time whether this is stored on the server or client. But if my guess is correct, you could check the `Maps/` folder in `VintagestoryData` and clear the one associated with the server. I have no idea how to find out which it is. In the worst case, you could move them out of the folder one by one until the error disappears, then move all but the latest one you moved back in. (Or, if you don't care about any maps (including singleplayer ones), you could just delete them all.)

We were afraid this was the problem and while we didn't want to start over, we did end up just starting a new map. It sucks to have lost so much progress but the game is very fun and we wanted to continue even if it meant starting from nothing again. Thank you for looking into it.
