### ISSUE TITLE
Game crashes with "Cannot render a non-initialized or disposed VAO" sometimes upon joining server

### ISSUE THREAD

**Issue by VintageStoryCrash** [anegostudios/VintageStory-Issues#873]
**Game Version:** 1.14.8
**Platform:** Windows
**Modded:** Yes

### Description
Sometimes when joining my friend's server, my entire game crashes. Most of the time, it just doesn't connect, but out of the 10 times, it has crashed 4. I am assuming it is related to my laptop being a piece of garbage, and the game not being optimized for garbage systems lol. It wouldn't be the first time, that's for sure. My issue, is the fact I can run Modded Minecraft, but this game breaks if I have my render resolution at the second lowest option. My specs are intel core i3-6006U, 4gb RAM.

### How to reproduce
It only sometimes crashes upon loading the world. the rest of the time the game runs fine despite horrendous lag spikes.

### Expected behavior
For the game to load up fine with no issues.

### Screenshots
N/A

### Logs
```
Running on 64 bit Windows with 4 GB RAM 
Version: v1.14.8 (Stable)2021-04-25 10:58:41 AM: Critical error occurred
System.ArgumentException: Cannot render a non-initialized or disposed VAO
   at Vintagestory.Client.NoObf.ClientPlatformWindows.RenderMesh(MeshRef modelRef)
   at Vintagestory.Client.NoObf.ClientMain.RenderTextureIntoFrameBuffer(LoadedTexture fromTexture, Single sourceX, Single sourceY, Single sourceWidth, Single sourceHeight, FrameBufferRef fb, Single targetX, Single targetY, Single alphaTest)
   at Vintagestory.Client.NoObf.ClientMain.RenderTextureIntoTexture(LoadedTexture fromTexture, Single sourceX, Single sourceY, Single sourceWidth, Single sourceHeight, LoadedTexture intoTexture, Single targetX, Single targetY, Single alphaTest)
   at Vintagestory.GameContent.MultiChunkMapComponent.setChunk(Int32 dx, Int32 dz, Int32[] pixels)
   at Vintagestory.GameContent.ChunkMapLayer.<>c__DisplayClass38_0.<loadFromChunkPixels>b__0()
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _jeEziyUSYl0BpbOxT46FYwj5VWL._t25VgrofhlXMw6hHEZh8JHhJz1A(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._DvzT6D0wN3fMakeuDyljJJ09hok(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._V5piYzG7beYPldE6UVxY58dqacE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2021-04-17 12:35:42 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1221216751978381412, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 6033ac5b
P4: KERNELBASE.dll
P5: 10.0.19041.804
P6: 0e9c5eae
P7: c000041d
P8: 000000000002d759
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7C45.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8639.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8688.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8792.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8919.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_d69bbd7196562fc13df0b5bd4b9f3a52157131_4fd6768e_f621e208-21ff-4879-afee-d133f62d920d

Analysis symbol: 
Rechecking for solution: 0
Report Id: f2496cdf-9faa-4034-a1ff-c5891ea7a356
Report Status: 268566528
Hashed bucket: 1a987eaea154b6e8a0f2a22a676d8064
Cab Guid: 0 }
--------------
{ TimeGenerated = 2021-04-17 12:35:36 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.14.8.0, time stamp: 0x6033ac5b
Faulting module name: KERNELBASE.dll, version: 10.0.19041.804, time stamp: 0x0e9c5eae
Exception code: 0xc000041d
Fault offset: 0x000000000002d759
Faulting process ID: 0x5dc8
Faulting application start time: 0x01d733bc04d8b712
Faulting application path: C:\Program Files (x86)\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: f2496cdf-9faa-4034-a1ff-c5891ea7a356
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 2021-04-17 12:35:32 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1529028199541149696, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 6033ac5b
P4: KERNELBASE.dll
P5: 10.0.19041.804
P6: 0e9c5eae
P7: c0020001
P8: 000000000002d759
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8B5D.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3903.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3B37.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3B92.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3C20.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_bf55e48fe32baedf65e5ded46bf42dcc9fbaae_4fd6768e_10e4d8d1-04fa-44ef-bf1d-46c6656e7500

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5df6f99a-00b1-45d4-a9a2-c18f3bb16420
Report Status: 268566528
Hashed bucket: b005feb57a2c8f7a3538330bdd349000
Cab Guid: 0 }
```

**Comment by copygirl** [comment]
Which mods? Can you make a copy of the world and remove the mods, see if the issue persists?

**Comment by VintageStoryCrash** [comment]
Dang, I didn't think I'd get a response so fast, I've never used Github before lol. I'll have to try this tomorrow as my friend is off to bed, and it's their world. I hope this doesn't screw stuff up. Also, if you don't mind me asking, what is a client main txt and where can I find it LMAO.

**Comment by copygirl** [comment]
Press Win+R and type in `%appdata%/VintagestoryData`, which should get you to the VS Data folder. Alternatively you can open the game, go to the mod manager and open the mods folder, then go one folder back. Here you can find the `Logs` folder in which the log files reside.

**Comment by Craluminum2413** [comment]
#687 ?

**Comment by tyronx** [comment]
I feel fairly confident this has been fixed already, otherwise please reopen
