### ISSUE TITLE
World corrupted after canceled load and force quit

### ISSUE THREAD

**Issue by Bentorium** [anegostudios/VintageStory-Issues#877]
1.14.10
windows

### Description
Save is quite heavily modded one.
Canceled loading game because was wrong mods selected and seems that world save got corrupted.
Even that medievalexpansion is disabled / removed it seems to kill that game load.

Tried some basic sqlite3 fixes but any didnt work.

Is there anything to do about these kind of problems or was this end of this savefile.

### How to reproduce
1. Every time I try load this save it will crash after everything is loaded.

### Expected behavior
load current save.

Mods in game 
ArmorCraftingRebalance1.0.1, BetterArchery2.0.0, CarryCapacity-VS1.14.3-v0.5.3, CompatibilityLib_v1.14.7_v1.2.2, DoubleBurn, ExpandedFoods_1.3.7, farmlife_v0.98.11, hudclock-2.4.2, LessArmorNegatives1.0.1, medievalexpansion-3.4.2, necessaries_v1.14.5-0.8.8, NoMolding1.0.0, primitivesurvival2.5.6, QuickerBarrel, survivalcats_v1.14.2-1.2.7, vsprospectorinfo_v4.0.0, wildfarming_v0.9.3, workbench-expansion-1.2.8, xlib_v0.5.0-PR3, xskills_v0.5.0-PR3, yabba_100

### Logs

```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.10 (Stable)3.5.2021 20.23.49: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.CollectibleObject.GetHandBookStacks(ICoreClientAPI capi)
   at Vintagestory.GameContent.BlockBloomery.<>c__DisplayClass1_0.<OnLoaded>b__0()
   at Vintagestory.API.Util.ObjectCacheUtil.GetOrCreate[T](ICoreAPI api, String key, CreateCachableObjectDelegate`1 onRequireCreate)
   at Vintagestory.GameContent.BlockBloomery.OnLoaded(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientMain.OnServerBlocksItemsReceivedStep5(Action onCompleted)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _pnnd59ZE4jC5iGjIOcyNcWxgKsR._ZHf5IMlYChPlSKBWZX1ph2DB6EP(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._3HP2xkrryy8Ktr1q1yqHHv9s1kb(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._JbXJA0SA6LQOS6diuqtXAjMb8Fo(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._ofvn0Tr1zNGCbNV3SxvKs2MXNP(_C7CLMRbe3BejVtaARYCgl7Bg1vl , String[] )
   at _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 21.4.2021 18.56.20, Site = , Source = Windows Error Reporting, Message = Fault bucket 1526485451476567229, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 6079b344
P4: medievalexpansion
P5: 3.4.2.0
P6: a6dfdf2d
P7: 1b
P8: 1
P9: System.NullReferenceException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER161E.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1C97.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1CA7.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1CA5.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1CD5.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_543475b5be3b98985ca99bb67f729f9a73f8c05a_5674d60d_ae56dd9d-9abb-435c-8c66-d31b291c9e04

Analysis symbol: 
Rechecking for solution: 0
Report Id: 614ddab9-7617-48b6-855c-5c4873f4942a
Report Status: 268435456
Hashed bucket: 1aa95fcb9248150fd52f2a6e321004bd
Cab Guid: 0 }
--------------
{ TimeGenerated = 21.4.2021 18.56.16, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.14.10.0, time stamp: 0x6079b344
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ffa5f9fc628
Faulting process id: 0xfa4
Faulting application start time: 0x01d736bb5e49485a
Faulting application path: E:\games\Vintagestory\Vintagestory.exe
Faulting module path: unknown
Report Id: 614ddab9-7617-48b6-855c-5c4873f4942a
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 21.4.2021 18.56.16, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at medievalexpansion.src.util.Repairer.Dispose()
   at gates.src.MedievalExpansionMod.OnShutDown()
   at Vintagestory.Server.ServerEventAPI.OnServerStage(Vintagestory.API.Server.EnumServerRunPhase)
   at Vintagestory.Server.ServerSystemModHandler.OnBeginShutdown()
   at Vintagestory.Server.ServerMain.EnterRunPhase(Vintagestory.API.Server.EnumServerRunPhase)
   at Vintagestory.Server.ServerMain.Stop(System.String)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._WpGAXiVoJmxWu1fCRjqBgmcU7Y8()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

 }
```

**Comment by copygirl** [comment]
Having mod-selection be per-world is something that will be added in the future, so such a mistake does not happen as easily. I don't think it will make it into the next big release (1.15) though.

I'm not sure if it helps in this case, but have you tried running the world in repair mode? (You can get to that by clicking the pencil in the world selection screen.)

**Comment by Bentorium** [comment]
Yes, I tried to run repair mode too, with mods and without mods, but it crashes and gives same errors as I posted.

**Comment by copygirl** [comment]
Tyron suggested editing the game files. In the install folder, `assets/survival/blocktypes/clay/bloomerybase.json` you can temporarily add a line `enabled: false,` above `code` for example. That should disable the bloomery block and replace it with a questionmark block that you can just break. Hopefully that works for you.

**Comment by Bentorium** [comment]
thanks for update, tested to disable bloomery, error changed to following. 

Tried start normally and repair mode, both gives same error again.

That P4: medievalexpansion is a bit weird there, tried to start completely clear, deleted all mods and caches. 
Tested also open that save file with DB browser for sqlite and it seems open without any problems. Tho seems there is some bit in wrong position somewhere :/

**logs**
Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.10 (Stable)4.5.2021 8.36.34: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ClientWorldMap.MarkChunkDirty(Int32 cx, Int32 cy, Int32 cz, Boolean priority, Boolean sunRelight, Action OnRetesselated, Boolean fireEvent, Boolean edgeOnly)
   at Vintagestory.Client.NoObf.ClientWorldMap.loadChunkMT(_rkZtI0liDNWIY1kfEEayZaL9H3z p, ClientChunk chunk)
   at Vintagestory.Client.NoObf.ClientWorldMap.<>c__DisplayClass97_0.<LoadChunkFromPacket>b__0()
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _pnnd59ZE4jC5iGjIOcyNcWxgKsR._ZHf5IMlYChPlSKBWZX1ph2DB6EP(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._3HP2xkrryy8Ktr1q1yqHHv9s1kb(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._JbXJA0SA6LQOS6diuqtXAjMb8Fo(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._ofvn0Tr1zNGCbNV3SxvKs2MXNP(_C7CLMRbe3BejVtaARYCgl7Bg1vl , String[] )
   at _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 21.4.2021 18.56.20, Site = , Source = Windows Error Reporting, Message = Fault bucket 1526485451476567229, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 6079b344
P4: medievalexpansion
P5: 3.4.2.0
P6: a6dfdf2d
P7: 1b
P8: 1
P9: System.NullReferenceException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER161E.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1C97.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1CA7.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1CA5.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1CD5.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_543475b5be3b98985ca99bb67f729f9a73f8c05a_5674d60d_ae56dd9d-9abb-435c-8c66-d31b291c9e04

Analysis symbol: 
Rechecking for solution: 0
Report Id: 614ddab9-7617-48b6-855c-5c4873f4942a
Report Status: 268435456
Hashed bucket: 1aa95fcb9248150fd52f2a6e321004bd
Cab Guid: 0 }
--------------
{ TimeGenerated = 21.4.2021 18.56.16, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.14.10.0, time stamp: 0x6079b344
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ffa5f9fc628
Faulting process id: 0xfa4
Faulting application start time: 0x01d736bb5e49485a
Faulting application path: E:\games\Vintagestory\Vintagestory.exe
Faulting module path: unknown
Report Id: 614ddab9-7617-48b6-855c-5c4873f4942a
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 21.4.2021 18.56.16, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at medievalexpansion.src.util.Repairer.Dispose()
   at gates.src.MedievalExpansionMod.OnShutDown()
   at Vintagestory.Server.ServerEventAPI.OnServerStage(Vintagestory.API.Server.EnumServerRunPhase)
   at Vintagestory.Server.ServerSystemModHandler.OnBeginShutdown()
   at Vintagestory.Server.ServerMain.EnterRunPhase(Vintagestory.API.Server.EnumServerRunPhase)
   at Vintagestory.Server.ServerMain.Stop(System.String)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._WpGAXiVoJmxWu1fCRjqBgmcU7Y8()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

 }

**Comment by copygirl** [comment]
World maps are stored on the client in `%appdata%/VintagestoryData/Maos`, not in the world file. Maybe deleting it would help. Now, I'm not entirely sure how to find out which is the correct one.

**Comment by Bentorium** [comment]
Find right one in maps directory, renamed it. 
When starting it trying to regenerate that db, but it fails and file is 12 KB, original file is 60645 KB

Tried again without and with mods, emptied caches and repair mode and normally

error seems to stay about same


Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.10 (Stable)4.5.2021 9.29.51: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ClientWorldMap.MarkChunkDirty(Int32 cx, Int32 cy, Int32 cz, Boolean priority, Boolean sunRelight, Action OnRetesselated, Boolean fireEvent, Boolean edgeOnly)
   at Vintagestory.Client.NoObf.ClientWorldMap.loadChunkMT(_rkZtI0liDNWIY1kfEEayZaL9H3z p, ClientChunk chunk)
   at Vintagestory.Client.NoObf.ClientWorldMap.<>c__DisplayClass97_0.<LoadChunkFromPacket>b__0()
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _pnnd59ZE4jC5iGjIOcyNcWxgKsR._ZHf5IMlYChPlSKBWZX1ph2DB6EP(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._3HP2xkrryy8Ktr1q1yqHHv9s1kb(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._JbXJA0SA6LQOS6diuqtXAjMb8Fo(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._ofvn0Tr1zNGCbNV3SxvKs2MXNP(_C7CLMRbe3BejVtaARYCgl7Bg1vl , String[] )
   at _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 21.4.2021 18.56.20, Site = , Source = Windows Error Reporting, Message = Fault bucket 1526485451476567229, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 6079b344
P4: medievalexpansion
P5: 3.4.2.0
P6: a6dfdf2d
P7: 1b
P8: 1
P9: System.NullReferenceException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER161E.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1C97.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1CA7.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1CA5.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1CD5.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_543475b5be3b98985ca99bb67f729f9a73f8c05a_5674d60d_ae56dd9d-9abb-435c-8c66-d31b291c9e04

Analysis symbol: 
Rechecking for solution: 0
Report Id: 614ddab9-7617-48b6-855c-5c4873f4942a
Report Status: 268435456
Hashed bucket: 1aa95fcb9248150fd52f2a6e321004bd
Cab Guid: 0 }
--------------
{ TimeGenerated = 21.4.2021 18.56.16, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.14.10.0, time stamp: 0x6079b344
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ffa5f9fc628
Faulting process id: 0xfa4
Faulting application start time: 0x01d736bb5e49485a
Faulting application path: E:\games\Vintagestory\Vintagestory.exe
Faulting module path: unknown
Report Id: 614ddab9-7617-48b6-855c-5c4873f4942a
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 21.4.2021 18.56.16, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at medievalexpansion.src.util.Repairer.Dispose()
   at gates.src.MedievalExpansionMod.OnShutDown()
   at Vintagestory.Server.ServerEventAPI.OnServerStage(Vintagestory.API.Server.EnumServerRunPhase)
   at Vintagestory.Server.ServerSystemModHandler.OnBeginShutdown()
   at Vintagestory.Server.ServerMain.EnterRunPhase(Vintagestory.API.Server.EnumServerRunPhase)
   at Vintagestory.Server.ServerMain.Stop(System.String)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._WpGAXiVoJmxWu1fCRjqBgmcU7Y8()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

 }

**Comment by copygirl** [comment]
Ah, apologies then. I'm running out of ideas.

**Comment by Bentorium** [comment]
No problems, thank you for trying to help. 
Unexpected things happens when doing computer science :)

Problem caused by canceling loading the game. Something went boom in somewhere.

Things made to try to save current save files
vcdbs file and original map db file seems open fine and shows that integrity is ok.
Tried create dumps for vcdbs/db files and reread those back
Tried load with repair mode with and without mods
Tried with and without mods, cleared cache, tried to delete original map file but it wont regenerate fully.
Tried disable bloomery, it changed error a bit.

**Comment by tyronx** [comment]
Hey, send me the save game, I'll have a look

**Comment by Bentorium** [comment]
Here is the link to zipped save file
https://we.tl/t-q8ofa9eaEs

**Comment by tyronx** [comment]
Thanks, whats the coordinate to your base? The spawn point doesnt crash

**Comment by Bentorium** [comment]
umm, it should be south south east I think about 2000-3000 blocks from start.

**Comment by Bentorium** [comment]
Actually I got that world working now.
I started that save local server (vintagestoryserver.exe) once, everything went ok on start, then stopped server and tested to start it normally and it started without problems.
Coords of base is 821, 113, 2556

**Comment by Bentorium** [comment]
Thank you very much for helping, keep up the good work. Atleast I will make backups once a day by now :)
 
Thought something went wrong in first place so I hope you find what went wrong to possible to prevent it if that is possible.

**Comment by tyronx** [comment]
Oh, glad to hear you got it resolved. I did find a bug on the server side, that i've fixed for next version. Maybe that will resolve your issue as well, should it ever re-appear.
