### ISSUE TITLE
Crash on Load (Singleplayer)

### ISSUE THREAD

**Issue by ProCynic** [anegostudios/VintageStory-Issues#878]
Version: v1.14.10
Platform: Windows
Modded: No

Attempting to load save results in crash, twice in a row, same error.  No mods installed.  Game was working fine (same world) yesterday and the client hasn't been updated since.  Here's the stack trace.
```Running on 64 bit Windows with 18 GB RAM 
Version: v1.14.10 (Stable)5/4/2021 12:41:23 AM: Critical error occurred
System.IO.IOException: Data error (cyclic redundancy check).

   at Vintagestory.Client.NoObf.TextureAtlasManager.LoadBitmap(ClientMain game, AssetLocationAndSource textureLoc)
   at Vintagestory.Client.NoObf.TextureAtlasManager.LoadCompositeBitmap(ClientMain game, AssetLocationAndSource compositeTextureLocation)
   at Vintagestory.Client.NoObf.TextureAtlasManager.ComposeTextureAtlassesFromTextures(Dictionary`2 textureLocations, String itemclass)
   at Vintagestory.Client.NoObf.ItemTextureAtlasManager.ComposeItemTextureAtlasses(IList`1 items, OrderedDictionary`2 shapes)
   at Vintagestory.Client.NoObf.ClientMain.OnServerBlocksItemsReceivedStep4(Action onCompleted, Int32 blockCount)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _pnnd59ZE4jC5iGjIOcyNcWxgKsR._ZHf5IMlYChPlSKBWZX1ph2DB6EP(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._3HP2xkrryy8Ktr1q1yqHHv9s1kb(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._JbXJA0SA6LQOS6diuqtXAjMb8Fo(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._ofvn0Tr1zNGCbNV3SxvKs2MXNP(_C7CLMRbe3BejVtaARYCgl7Bg1vl , String[] )
   at _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(ThreadStart )
-------------------------------
```

**Comment by ProCynic** [comment]
Also happens on loading other save files or creating a new world.

**Comment by copygirl** [comment]
Could you try reinstalling the game? I wonder if something happened to the game files.

Do you remember anything in particular you did before this error occurred? System updates or an unexpected shutdown?

**Comment by ProCynic** [comment]
No, nothing I noticed that should have changed anything.  But running the `vs_update_1.14.10.exe` patch installer again seems to have fixed it, thank you.  (I thought I'd give it a shot before doing a full uninstall/reinstall.)  Anyway it's good on my end.
