### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by flakuk** [anegostudios/VintageStory-Issues#879]
**Game Version:** v1.14.10
**Platform:** Windows
**Modded:**  Yes 

```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.10 (Stable)04/05/2021 19:27:15: Critical error occurred
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: slotId
   at Vintagestory.API.Common.InventoryGeneric.get_Item(Int32 slotId)
   at Vintagestory.GameContent.BlockEntityMeal.OnBlockPlaced(ItemStack byItemStack)
   at Vintagestory.Client.NoObf.ClientWorldMap.SpawnBlockEntity(String classname, BlockPos position, ItemStack byItemStack)
   at Vintagestory.API.Common.Block.OnBlockPlaced(IWorldAccessor world, BlockPos blockPos, ItemStack byItemStack)
   at Vintagestory.Common.BlockAccessorRelaxed.SetBlock(Int32 blockId, BlockPos pos, ItemStack byItemstack)
   at Vintagestory.API.Common.Block.DoPlaceBlock(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel, ItemStack byItemStack)
   at Vintagestory.API.Common.Block.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, String& failureCode)
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryPlace(BlockSelection blockSelection, String& failureCode)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnBlockBuild(BlockSelection blockSelection, Block onBlock, String& failureCode)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _vKnDSS3ZW5fZhqcIJSzL9xbAUttA._ZHf5IMlYChPlSKBWZX1ph2DB6EP(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._3HP2xkrryy8Ktr1q1yqHHv9s1kb(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._JbXJA0SA6LQOS6diuqtXAjMb8Fo(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._ofvn0Tr1zNGCbNV3SxvKs2MXNP(_C7CLMRbe3BejVtaARYCgl7Bg1vl , String[] )
   at _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 26/04/2021 08:38:27, Site = , Source = Windows Error Reporting, Message = Fault bucket 1740237316794257994, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.18363.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\FLAKU\AppData\Local\Temp\RDR6A2E.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6A2F.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6A30.tmp.xml

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 2a0e1c93-013b-41d4-9427-b7a7a62607c8
Report Status: 268435456
Hashed bucket: 67c34500826d60989826909e9466924a
Cab Guid: 0 }
--------------
{ TimeGenerated = 24/03/2021 10:07:10, Site = , Source = Windows Error Reporting, Message = Fault bucket 2012437559967250361, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 10.0.18363.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\FLAKU\AppData\Local\Temp\RDREF5B.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREF6B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREF6C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREF87.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREF97.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 8a303ca1-6496-48f8-854e-aafbbc21cac2
Report Status: 268435456
Hashed bucket: a1492c2c0210332ebbed9d4c668077b9
Cab Guid: 0 }
--------------
{ TimeGenerated = 18/02/2021 15:57:27, Site = , Source = Windows Error Reporting, Message = Fault bucket 2199860474778786707, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.7.0
P3: 10.0.18363.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\FLAKU\AppData\Local\Temp\RDR8616.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8627.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8637.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8645.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8665.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 06677023-aed7-441a-9ad7-be992aab70f7
Report Status: 268435456
Hashed bucket: be3cf1634edaf807fe8779724a9c9b93
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment]
Any mods? Can you upload client-crash.txt and server-crash.txt?

**Comment by copygirl** [comment]
You placed a meal on the ground..? Do you remember what was in it?

**Comment by Craluminum2413** [comment]
Definitely Expanded Foods mod. Also it was reported there https://www.vintagestory.at/forums/topic/3783-expanded-foods-1314/?do=findComment&comment=20448

**Comment by copygirl** [comment]
Will close this for now then.
