### ISSUE TITLE
help the game crashes and then does my pc

### ISSUE THREAD

**Issue by yyyyyerytrdeswaqfrtyhb** [anegostudios/VintageStory-Issues#883]
**Game Version:** latest
**Platform:** Windows / Mac / Linux (which?) windows
**Modded:** No / Yes (yes

### Description
Explain the issue you're running into.   so the issue is i added some mods to my game and it starts getting realy laggy like just about 5 muinets after joning the world and then it crashes the game and sometimes crashes my pc

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.  number 3

### Expected behavior
If not obvious, what did you expect to happen?     to play the modded version

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.   

### Logs
```
Paste crash here.  Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.10 (Stable)5/12/2021 6:41:50 PM: Critical error occurred
System.Exception: Don't know how to instantiate item of class 'ItemMagicWand' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass)
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(_UVRYzDbb4cNLG0i5EVjyYzSJtsB packet, IWorldAccessor world, ClassRegistry registry)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets(_qiwXoSSrnCKEl5NMyGSjHlpQcE packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _pnnd59ZE4jC5iGjIOcyNcWxgKsR._ZHf5IMlYChPlSKBWZX1ph2DB6EP(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._3HP2xkrryy8Ktr1q1yqHHv9s1kb(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._JbXJA0SA6LQOS6diuqtXAjMb8Fo(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._ofvn0Tr1zNGCbNV3SxvKs2MXNP(_C7CLMRbe3BejVtaARYCgl7Bg1vl , String[] )
   at _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/12/2021 6:34:14 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.14.10.0, time stamp: 0x6079b344
Faulting module name: nvoglv64.dll, version: 27.21.14.6137, time stamp: 0x6009426d
Exception code: 0xc0000409
Fault offset: 0x0000000001182789
Faulting process id: 0x660
Faulting application start time: 0x01d7477e4b9982b1
Faulting application path: C:\Users\marco\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\DriverStore\FileRepository\nvdd.inf_amd64_0a539bf579a84773\nvoglv64.dll
Report Id: 1c598ada-4fc1-427d-9b6e-af6628abcfba
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 5/12/2021 5:25:44 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1687649954606885082, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 6079b344
P4: nvoglv64.dll
P5: 27.21.14.6137
P6: 6009426d
P7: 0000000001182789
P8: c0000409
P9: 0000000000000007
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF1CF.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF480.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF490.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF49E.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF4CE.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_8bfd8df572eda76b2a9180cc7e8449e0b8bd8f_5674d60d_191509f6-6651-4bd3-9c75-4441812982f4

Analysis symbol: 
Rechecking for solution: 0
Report Id: e05a9462-eb33-4170-aca6-e1a45f8926eb
Report Status: 268435456
Hashed bucket: f21709cfa40f110d976bbcb1318c28da
Cab Guid: 0 }
--------------
{ TimeGenerated = 5/12/2021 5:25:42 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.14.10.0, time stamp: 0x6079b344
Faulting module name: nvoglv64.dll, version: 27.21.14.6137, time stamp: 0x6009426d
Exception code: 0xc0000409
Fault offset: 0x0000000001182789
Faulting process id: 0x5d9c
Faulting application start time: 0x01d7477473f31723
Faulting application path: C:\Users\marco\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\DriverStore\FileRepository\nvdd.inf_amd64_0a539bf579a84773\nvoglv64.dll
Report Id: e05a9462-eb33-4170-aca6-e1a45f8926eb
Faulting package full name: 
Faulting package-relative application ID:  }

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```

**Comment by tyronx** [comment]
looks to me like you have disabled the creative mod, and the server this has it enabled? Try enabling the creative mod.
