### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Abbyboy868** [anegostudios/VintageStory-Issues#884]
**Game Version:** 1.14.10
**Platform:** Windows 
**Modded:** No 

### Description
Game crashed throwing this error

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.14.10 (Stable)13/05/2021 8:32:50 pm: Critical error occurred
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.ToArray()
   at Vintagestory.Client.NoObf.OggDecoder.OggToWav(Stream ogg, IAsset asset)
   at _dbYCA21jzaLNtbaIPTkHUXXNWwd._WIGB3g6HNXrfCShEWJbvMz9AhZ7(IAsset )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._rHo7EdLPo98qqpT3E4pTaaA4D8D(IAsset )
   at Vintagestory.Client.NoObf.SystemMusicEngine.ProcessTrackQueue()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 13/05/2021 8:32:51 pm, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.14.10.0, time stamp: 0x6079b344
Faulting module name: KERNELBASE.dll, version: 10.0.19041.906, time stamp: 0x2f2f77bf
Exception code: 0xe0434352
Fault offset: 0x0000000000034b59
Faulting process id: 0x5334
Faulting application start time: 0x01d748530dbb0168
Faulting application path: C:\Users\abbyb\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 34751cbb-70f3-43e7-93f7-25a6b1e30027
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 13/05/2021 8:32:50 pm, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException
   at System.IO.MemoryStream.ToArray()
   at Vintagestory.Client.NoObf.OggDecoder.OggToWav(System.IO.Stream, Vintagestory.API.Common.IAsset)
   at _dbYCA21jzaLNtbaIPTkHUXXNWwd._WIGB3g6HNXrfCShEWJbvMz9AhZ7(Vintagestory.API.Common.IAsset)
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._rHo7EdLPo98qqpT3E4pTaaA4D8D(Vintagestory.API.Common.IAsset)
   at Vintagestory.Client.NoObf.SystemMusicEngine.ProcessTrackQueue()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

 }
--------------
{ TimeGenerated = 12/05/2021 7:28:28 pm, Site = , Source = Windows Error Reporting, Message = Fault bucket 1815689438836956140, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 6079b344
P4: KERNELBASE.dll
P5: 10.0.19041.906
P6: 2f2f77bf
P7: c000041d
P8: 0000000000034b59
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1EC4.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_7adf7ccfcdc8a56b99adfd31e78e8f744d5b25_5674d60d_fa36316b-8083-412a-8565-5138589609bf

Analysis symbol: 
Rechecking for solution: 0
Report Id: 86098fb5-f6d7-462d-af63-84f3a76a9506
Report Status: 268435456
Hashed bucket: f4963f08a123704129329fecb84e1bec
Cab Guid: 0 }

**Comment by sirStroam** [comment]
@Abbyboy868 Did you have any other applications running on your device?

**Comment by tyronx** [comment]
Also how much ram do you have installed? And any mods installed?
