### ISSUE TITLE
Creating new world crashes the game

### ISSUE THREAD

**Issue by RinVindor** [anegostudios/VintageStory-Issues#888]
**Game Version:** v1.15.0-pre.1
**Platform:** Windows
**Modded:** No

### Description
I made a separate installation so to be able to test the v1.15.0-pre.1 so that I'd still have my other installation to enjoy while this is updated. Made a world, it began to load and it crashed and I realized it still was seeing the mods installed in the 1.14 installation's folder so I restarted and tried to create another world with the mods uninstalled, now even attempting to create a world fails.

### How to reproduce
1. Create a new world
2. Load a new world

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.15.0-pre.1 (Unstable)5/24/2021 5:13:20 AM: Critical error occurred
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at _hbUyCC3cATVAykxaAlEBjKdgWtnA._SouwGBCwt3vt19dhJpiDcgkZ21N(Boolean )
   at _gZDhzP3Tg63cu5tNZrkD3Dahswb._cyQdbN4D1GDMZDxelJi2miAKq5RA()
   at _gZDhzP3Tg63cu5tNZrkD3Dahswb..ctor(_s8KgWeJlIYNXma8EsZDJOscF1VA , _llHcxa89DarSoaUgdS8JwCmrYpv )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at _s8KgWeJlIYNXma8EsZDJOscF1VA._YClF0gBClh2j6z6wTMzohhllQRO(Type )
   at _A8WotwW2tf2CQ2lXhVedUYnpcxT._dX4cYtH4rtqfp8qkFQZRALmAGiO()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _llHcxa89DarSoaUgdS8JwCmrYpv._7FWcaHQOPkJazhbD1ceYYZm7C1H(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _Sfca4roOb4ikuKbMulRniUxARF4._0ytRimz1XDNkGpyxJcZbGf9Oxbd(_YzYAgXNLrh0iXJRtlZnQ7TqOSZX , String[] )
   at _hNqfhVOk3ksmv0cZQgnBG2cCt6o._0ytRimz1XDNkGpyxJcZbGf9Oxbd(ThreadStart )
-------------------------------
System.NullReferenceException: Object reference not set to an instance of an object.
   at _hbUyCC3cATVAykxaAlEBjKdgWtnA._SouwGBCwt3vt19dhJpiDcgkZ21N(Boolean )
   at _gZDhzP3Tg63cu5tNZrkD3Dahswb._cyQdbN4D1GDMZDxelJi2miAKq5RA()
   at _gZDhzP3Tg63cu5tNZrkD3Dahswb..ctor(_s8KgWeJlIYNXma8EsZDJOscF1VA , _llHcxa89DarSoaUgdS8JwCmrYpv )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/24/2021 5:05:51 AM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.15.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 5bf0

Start Time: 01d7507be7a1051c

Termination Time: 5

Application Path: C:\Users\zackb\AppData\Roaming\Vintagestory v1.15\Vintagestory.exe

Report Id: a5589834-5922-40c2-83e8-88849726d8b6

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 5/24/2021 5:05:51 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 60aa9427
P4: 86d0
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDD2.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDD3.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDE2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDF2.tmp.txt
\\?\C:\Users\zackb\AppData\Local\Temp\WER19DA.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_2ed958da1011a864ebfb3f2b93c160ccb59183_cdf018de_5df5bee3-8961-4aa7-803b-f6ef9096eaf4

Analysis symbol: 
Rechecking for solution: 0
Report Id: a5589834-5922-40c2-83e8-88849726d8b6
Report Status: 97
Hashed bucket: 
Cab Guid: 0 }```

**Comment by Craluminum2413** [comment]
My world starts only when I remove all the mods that are broken

**Comment by copygirl** [comment]
Just for your information: By default, even if you install Vintage Story in different locations, it will still share a data folder (`%AppData%/VintagestoryData` on Windows). This is where your client prefences, worlds and mods (usually) go. You can specify a custom data path using the `--dataPath` argument. You can also move your mods to the installation folder so they are only available for that version.

As for the crash - I can't say what's going on because of the obfuscated method names.

**Comment by tyronx** [comment]
Try deleting all other mods except the 3 vanilla ones for v1.15

**Comment by tyronx** [comment]
Assuming this to be fixed / no longer happening, please reopen otherwise
