### ISSUE TITLE
Crash when looking at BlockLeavesNarrow

### ISSUE THREAD

**Issue by Davis105** [anegostudios/VintageStory-Issues#893]
**Game Version:** 1.15pre
**Platform:** Windows
**Modded:** No

### Description
Was adventuring through a normal temperate biome near spawn and the game randomly crashed. This has happened to me a few times already on this version already. 

### How to reproduce
3. It crashes / doesn't do the thing. I am unsure how to re-create this it just happens periodically. 

### Logs

```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.1 (Unstable)5/24/2021 6:34:14 PM: Critical error occurred
System.Exception: Can't create itemstack without block!
   at Vintagestory.API.Common.ItemStack..ctor(Block block, Int32 stacksize)
   at Vintagestory.GameContent.BlockLeavesNarrow.OnPickBlock(IWorldAccessor world, BlockPos pos)
   at Vintagestory.API.Common.Block.GetPlacedBlockName(IWorldAccessor world, BlockPos pos)
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.ComposeBlockInfoHud()
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.BlockInView()
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _br2hCScGRpxc7JEG49NYhgjk3S4._fpuKYTCq2fX4VWquSrPHTZdG1hc(Single )
   at _s8KgWeJlIYNXma8EsZDJOscF1VA._FB2MkK2aZoabCIfGZBZyY5cprmB(Single )
   at _s8KgWeJlIYNXma8EsZDJOscF1VA._QvBwhnv5xx7yJWEXhyOtee8ykjG(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _Sfca4roOb4ikuKbMulRniUxARF4._0ytRimz1XDNkGpyxJcZbGf9Oxbd(_YzYAgXNLrh0iXJRtlZnQ7TqOSZX , String[] )
   at _hNqfhVOk3ksmv0cZQgnBG2cCt6o._0ytRimz1XDNkGpyxJcZbGf9Oxbd(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/24/2021 5:41:24 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1617108784218071861, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\DAVIS\AppData\Local\Temp\RDR51A8.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER51A9.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER51C9.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER51E6.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5216.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 97aa1df1-d88f-4b0f-bb9c-c08464d623e3
Report Status: 268435456
Hashed bucket: 53ec02d71894ee5b26711fdf167b6335
Cab Guid: 0 }
--------------
{ TimeGenerated = 3/21/2021 2:51:54 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1564561481470198046, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\DAVIS\AppData\Local\Temp\RDR99DB.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER99FB.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9A0C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9A39.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9A78.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 8d4a049b-128d-4d12-a22b-b2f3d4a2da24
Report Status: 268435456
Hashed bucket: 2422f0d2706eedebe5b67060c44a411e
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment]
What block did you placed?

**Comment by Davis105** [comment]
From what I can remember I did not place any blocks I was jumping up a hill looking around for some better quality dirt.

**Comment by copygirl** [comment]
`at Vintagestory.GameContent.BlockLeavesNarrow.OnPickBlock(IWorldAccessor world, BlockPos pos)`

It looks like it has something to do with looking at a leaves block? (Does the game have leaf piles now, or why is it called "narrow"?)

**Comment by Craluminum2413** [comment]
> `at Vintagestory.GameContent.BlockLeavesNarrow.OnPickBlock(IWorldAccessor world, BlockPos pos)`
> 
> It looks like it has something to do with looking at a leaves block? (Does the game have leaf piles now, or why is it called "narrow"?)

Cypress leaves

**Comment by radfast** [comment]
Thanks for reporting.  Unfortunately with this issue it's not safe to have Block Info overlay switched on in `1.15-pre.1`, at least if exploring Mediterranean climate zones.  I've fixed the issue for `pre.2` so this can be closed when convenient.
