### ISSUE TITLE
Crash on trying to load and server or my own game 1.15.0-pre 1 installed

### ISSUE THREAD

**Issue by ShellyB916** [anegostudios/VintageStory-Issues#894]
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.1 (Unstable)5/24/2021 7:08:38 PM: Critical error occurred
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.CollectibleObject.Attributes'.
   at medievalexpansion.src.block.mechanical.WaterWheel.<>c.<OnLoaded>b__4_1(CollectibleObject x)
   at System.Collections.Generic.List`1.FindAll(Predicate`1 match)
   at medievalexpansion.src.block.mechanical.WaterWheel.<>c__DisplayClass4_1.<OnLoaded>b__0()
   at Vintagestory.API.Util.ObjectCacheUtil.GetOrCreate[T](ICoreAPI api, String key, CreateCachableObjectDelegate`1 onRequireCreate)
   at medievalexpansion.src.block.mechanical.WaterWheel.OnLoaded(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientMain.OnServerBlocksItemsReceivedStep5(Action onCompleted)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _pO2zBM4Ht3KdZg9islHlXSG99V7._LckgF1V7SCSAnFcqBWkYfNkg6Ib(Single )
   at _s8KgWeJlIYNXma8EsZDJOscF1VA._FB2MkK2aZoabCIfGZBZyY5cprmB(Single )
   at _s8KgWeJlIYNXma8EsZDJOscF1VA._QvBwhnv5xx7yJWEXhyOtee8ykjG(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _Sfca4roOb4ikuKbMulRniUxARF4._0ytRimz1XDNkGpyxJcZbGf9Oxbd(_YzYAgXNLrh0iXJRtlZnQ7TqOSZX , String[] )
   at _hNqfhVOk3ksmv0cZQgnBG2cCt6o._0ytRimz1XDNkGpyxJcZbGf9Oxbd(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/5/2021 8:27:39 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1999085723610005733, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\kepon\AppData\Local\Temp\RDR5F53.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F63.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F74.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F91.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5FC1.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 1b32b947-04a9-4ef9-8293-a63e5f4ff432
Report Status: 268435456
Hashed bucket: ee3def5252484136fbbe2ddfbf5440e5
Cab Guid: 0 }
--------------
{ TimeGenerated = 4/1/2021 2:49:58 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1822032227626530173, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\kepon\AppData\Local\Temp\RDRB2D2.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB2E3.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB303.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB320.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB350.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: efa80281-9240-4eeb-9ea8-66f0fccac183
Report Status: 268435456
Hashed bucket: a995c73cc234971ef94928a850fe357d
Cab Guid: 0 }
--------------
{ TimeGenerated = 3/4/2021 12:17:01 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangTransient
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 6033ac5b
P4: unknown
P5: unknown
P6: unknown
P7: unknown
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5804.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5824.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5823.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5844.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5bb2455b-bff0-4587-bd88-9a979d9e84ce
Report Status: 2049
Hashed bucket: 
Cab Guid: 0 }

**Comment by ShellyB916** [comment]
NVM it was the mods i forgot to shut them off

**Comment by copygirl** [comment]
Just for the record, a `MissingFieldException` (or `MissingMethodException`) along with a mod name being mentioned in the stack trace (`at medievalexpansion.src.block.mechanical.WaterWheel.[...]`) highly suggests that changes to the game have caused the mod to become incompatible.

**Comment by ShellyB916** [comment]
I wrote a note at the bottom of my post I forgot to disable the mods... Games runs fine now

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
