### ISSUE TITLE
Chiseled blocks cause crash the game

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#895]
**Game Version:** 1.15.0-pre1
**Platform:** Windows
**Modded:** No

### Description
Any chiseled block crashes the game when you hovering at their icons with mouse pointer

### How to reproduce
1. Chisel any chiselable block
2. Copy/harvest it
3. Hover your mouse pointer over its icon
4. It crashes

### Expected behavior
Nothing happens

### Logs
```
Version: v1.15.0-pre.1 (Unstable)05/25/2021 13:05:32: Critical error occurred
System.ArgumentNullException: Value cannot be null.
Parameter name: collection
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Vintagestory.GameContent.BlockMicroBlock.Equals(ItemStack thisStack, ItemStack otherStack, String[] ignoreAttributeSubTrees)
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _br2hCScGRpxc7JEG49NYhgjk3S4._fpuKYTCq2fX4VWquSrPHTZdG1hc(Single )
   at _s8KgWeJlIYNXma8EsZDJOscF1VA._FB2MkK2aZoabCIfGZBZyY5cprmB(Single )
   at _s8KgWeJlIYNXma8EsZDJOscF1VA._QvBwhnv5xx7yJWEXhyOtee8ykjG(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _Sfca4roOb4ikuKbMulRniUxARF4._0ytRimz1XDNkGpyxJcZbGf9Oxbd(_YzYAgXNLrh0iXJRtlZnQ7TqOSZX , String[] )
   at _hNqfhVOk3ksmv0cZQgnBG2cCt6o._0ytRimz1XDNkGpyxJcZbGf9Oxbd(ThreadStart )
```

**Comment by Craluminum2413** [comment]
Fixed in 1.15.0-pre.3
