### ISSUE TITLE
Ground storage cause crash

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#902]
**Game Version:** 1.15.0-pre1
**Platform:** Windows
**Modded:** No

### Description
Ground storage cause crash, when you trying to interact with bowls in the ground storage. Sorry, just don't know how to reproduce this issue

### Logs
(This crash was on another computer)
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.15.0-pre.1 (Unstable)25.05.2021 17:37:33: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityGroundStorage.putOrGetItemSingle(ItemSlot ourSlot, IPlayer player)
   at Vintagestory.GameContent.BlockEntityGroundStorage.OnPlayerInteract(IPlayer player, BlockSelection bs)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _br2hCScGRpxc7JEG49NYhgjk3S4._LckgF1V7SCSAnFcqBWkYfNkg6Ib(Single )
   at _s8KgWeJlIYNXma8EsZDJOscF1VA._FB2MkK2aZoabCIfGZBZyY5cprmB(Single )
   at _s8KgWeJlIYNXma8EsZDJOscF1VA._QvBwhnv5xx7yJWEXhyOtee8ykjG(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _Sfca4roOb4ikuKbMulRniUxARF4._0ytRimz1XDNkGpyxJcZbGf9Oxbd(_YzYAgXNLrh0iXJRtlZnQ7TqOSZX , String[] )
   at _hNqfhVOk3ksmv0cZQgnBG2cCt6o._0ytRimz1XDNkGpyxJcZbGf9Oxbd(ThreadStart )
```

**Comment by Craluminum2413** [comment]
The cause of the crash is raising and placing bowls, but again difficult to reproduce

**Comment by Craluminum2413** [comment]
I guess it was fixed
1.15.0-pre.1
> Fixed: Ground storable interaction crash
