### ISSUE TITLE
Planting Walnut Sapling in Planter Crashes Game

### ISSUE THREAD

**Issue by Goibniu17** [anegostudios/VintageStory-Issues#905]
**Game Version:** 1.15.1pre1
**Platform:** Windows 
**Modded:** No

### Description
Game crashes when planting a walnut sapling into a regular or undergrowth planter (haven't tested with other planters.

### How to reproduce
1. Place planter on ground.
2. Plant walnut sapling in planter
3. It crashes

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.1 (Unstable)2021-05-25 5:19:26 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityPlantContainer.GenContentMeshes(ITesselatorAPI tesselator)
   at Vintagestory.GameContent.BlockEntityPlantContainer.genMeshes()
   at Vintagestory.GameContent.BlockEntityPlantContainer.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving)
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(_7wGIHlU1DhNO7xnOqI8AtkdVKbp p, ClientMain game)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(_qCgKt7sZEJPl7aklli8fiCArZTD packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _br2hCScGRpxc7JEG49NYhgjk3S4._fpuKYTCq2fX4VWquSrPHTZdG1hc(Single )
   at _s8KgWeJlIYNXma8EsZDJOscF1VA._FB2MkK2aZoabCIfGZBZyY5cprmB(Single )
   at _s8KgWeJlIYNXma8EsZDJOscF1VA._QvBwhnv5xx7yJWEXhyOtee8ykjG(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _Sfca4roOb4ikuKbMulRniUxARF4._0ytRimz1XDNkGpyxJcZbGf9Oxbd(_YzYAgXNLrh0iXJRtlZnQ7TqOSZX , String[] )
   at _hNqfhVOk3ksmv0cZQgnBG2cCt6o._0ytRimz1XDNkGpyxJcZbGf9Oxbd(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2021-05-09 11:12:53 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1837167348359640725, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 6079b344
P4: mscorlib
P5: 4.8.4341.0
P6: 60230124
P7: 1694
P8: 1d8
P9: System.IO.IOException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1A66.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_1764dc927acd2b13639dda21195759d282faf2c_5674d60d_aa58f359-2ea4-42a0-bf2d-0087108e59b0

Analysis symbol: 
Rechecking for solution: 0
Report Id: 8ebfad9f-45d7-4761-99d5-83825b3992f5
Report Status: 268435456
Hashed bucket: bad632bcf34946f3c97eedf837ec3695
Cab Guid: 0 }
--------------
{ TimeGenerated = 2021-05-09 11:12:51 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 6079b344
P4: mscorlib
P5: 4.8.4341.0
P6: 60230124
P7: 1694
P8: 1d8
P9: System.IO.IOException
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_1764dc927acd2b13639dda21195759d282faf2c_5674d60d_aa58f359-2ea4-42a0-bf2d-0087108e59b0

Analysis symbol: 
Rechecking for solution: 0
Report Id: 8ebfad9f-45d7-4761-99d5-83825b3992f5
Report Status: 4
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 2021-05-09 11:12:50 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.14.10.0, time stamp: 0x6079b344
Faulting module name: KERNELBASE.dll, version: 10.0.19041.906, time stamp: 0x2f2f77bf
Exception code: 0xe0434352
Fault offset: 0x0000000000034b59
Faulting process id: 0x9b78
Faulting application start time: 0x01d745633765d3e1
Faulting application path: D:\Games\Vintagestory\Vintagestory.exe
Faulting module path: C:\windows\System32\KERNELBASE.dll
Report Id: 8ebfad9f-45d7-4761-99d5-83825b3992f5
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Different planters are just variants of planter, if it happens to one, then it happens to all. Can confirm it also happens with pupleheart and other new saplingg

**Comment by tyronx** [comment]
thanks should  be fixed in pre.4
