### ISSUE TITLE
Game Crash when selecting chiseled block in inventory with mouse

### ISSUE THREAD

**Issue by EllingtonElectrician** [anegostudios/VintageStory-Issues#925]
Game crashes when selecting a chiseled block in the inventory with the mouse.

Running on 64 bit Windows with 32 GB RAM 
Version: v1.15.0-pre.1 (Unstable)5/28/2021 9:48:32 PM: Critical error occurred
System.ArgumentNullException: Value cannot be null.
Parameter name: collection
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Vintagestory.GameContent.BlockMicroBlock.Equals(ItemStack thisStack, ItemStack otherStack, String[] ignoreAttributeSubTrees)
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _br2hCScGRpxc7JEG49NYhgjk3S4._fpuKYTCq2fX4VWquSrPHTZdG1hc(Single )
   at _s8KgWeJlIYNXma8EsZDJOscF1VA._FB2MkK2aZoabCIfGZBZyY5cprmB(Single )
   at _s8KgWeJlIYNXma8EsZDJOscF1VA._QvBwhnv5xx7yJWEXhyOtee8ykjG(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _Sfca4roOb4ikuKbMulRniUxARF4._0ytRimz1XDNkGpyxJcZbGf9Oxbd(_YzYAgXNLrh0iXJRtlZnQ7TqOSZX , String[] )
   at _hNqfhVOk3ksmv0cZQgnBG2cCt6o._0ytRimz1XDNkGpyxJcZbGf9Oxbd(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/25/2021 9:37:17 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1252239485250825062, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Cam\AppData\Local\Temp\RDRF70E.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF71E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF73F.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF76B.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF7BB.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 7331aaa9-6d02-474b-a049-0b3818d8a906
Report Status: 268435456
Hashed bucket: 9a6d16c7ad62a31db160d92d5c17eb66
Cab Guid: 0 }
--------------
{ TimeGenerated = 4/13/2021 7:54:01 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1796462557534567629, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.9.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Cam\AppData\Local\Temp\RDRE434.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE445.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE465.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE4A2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE501.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 3601c30d-b3af-4130-b4ee-7cef11ef8d2c
Report Status: 268435456
Hashed bucket: 4ddef1e451eb81ebb8ee512d92233ccd
Cab Guid: 0 }
--------------
{ TimeGenerated = 3/14/2021 7:22:29 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1822032227626530173, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Cam\AppData\Local\Temp\RDRDF97.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDFA7.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDFC7.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE004.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE053.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: d5490524-a4e1-4549-8cc0-0acc44f597e1
Report Status: 268435456
Hashed bucket: a995c73cc234971ef94928a850fe357d
Cab Guid: 0 }

**Comment by EllingtonElectrician** [comment]
Duplicate of another issue. CASE CLOSED!!!!!!!!!
