### ISSUE TITLE
Crash when using BlockCookedContainer on an entity

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#953]
**Game Version:** 1.15.0-pre2
**Platform:** Windows 
**Modded:** No

### Description
Entered a Building material trader's cart. Clicked on the trader to open the transaction. Game crashed.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.2 (Unstable)02/06/2021 20:24:26: Critical error occurred
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à Vintagestory.GameContent.BlockCookedContainer.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handHandling)
   à Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling)
   à Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel)
   à Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt)
   à Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   à Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   à Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   à Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   à _xArlFw5lpThzIY0BN36UerAlHzU._14ww1iwrPaPwPpAZqZCUdf3d4Sm(Single )
   à _uFwaliVbJcYmzlP3dwic7HSHMr2._EuQCmN4cQf8FBHYrlJxd8EhIdNnA(Single )
   à _uFwaliVbJcYmzlP3dwic7HSHMr2._HlDCi3DfsJHaHE4jniBarrjFlHLB(Single )
   à Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   à System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   à OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   à OpenTK.GameWindow.DispatchRenderFrame()
   à OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   à _EKato5MKvGk9ELCMKyl4BGVO7pe._ninJWCWaWyMG9ZSA1Eyytms1G5F(_BjQ4x8rTRChySIeXrK1HK1YSqec , String[] )
   à _btwtpE4G1MfBqD34njKFCvBcSRd._ninJWCWaWyMG9ZSA1Eyytms1G5F(ThreadStart )
-------------------------------

**Comment by copygirl** [comment]
The issue is from the item you were holding (a pot? bowl?) rather than interacting with the trader. I'll change the title as such.

**Comment by Craluminum2413** [comment]
Tried to interact with building materials trader while holding cooking pot or without cause nothing

**Comment by Craluminum2413** [comment]
Okay, trying to interact with trader holding cooking pot with meal cause crash
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.2 (Unstable)06/02/2021 22:18:35: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockCookedContainer.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handHandling)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _xArlFw5lpThzIY0BN36UerAlHzU._14ww1iwrPaPwPpAZqZCUdf3d4Sm(Single )
   at _uFwaliVbJcYmzlP3dwic7HSHMr2._EuQCmN4cQf8FBHYrlJxd8EhIdNnA(Single )
   at _uFwaliVbJcYmzlP3dwic7HSHMr2._HlDCi3DfsJHaHE4jniBarrjFlHLB(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _EKato5MKvGk9ELCMKyl4BGVO7pe._ninJWCWaWyMG9ZSA1Eyytms1G5F(_BjQ4x8rTRChySIeXrK1HK1YSqec , String[] )
   at _btwtpE4G1MfBqD34njKFCvBcSRd._ninJWCWaWyMG9ZSA1Eyytms1G5F(ThreadStart )
```

**Comment by Saricane** [comment]
Well, I did not see the BlockCookedContainer in the log. But yes, I had a stew in a cooking pot.
Thanks for your help, Craluminum & Copygirl.

**Comment by Craluminum2413** [comment]
@copygirl I advise you to change the title issue from trader to entity, because I reproduced the same crash even with piglet

**Comment by tyronx** [comment]
thanks, fixed for pre.7
