### ISSUE TITLE
Crash on picking up item...

### ISSUE THREAD

**Issue by dan0h** [anegostudios/VintageStory-Issues#965]
LOTS of hours (over 100) in Vintage Story - first proper crash, happened just after another player (LAN) gave me an owl treasure chest, which on my client just looked like a normal chest...

Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.10 (Stable)05/06/2021 15:51:57: Critical error occurred
System.Exception: Chunk retesselated listener number 0 threw an exception (a=False, b=False, b=False)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityAnimationUtil.<StartAnimation>b__16_0()
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerChunkRetesselated(Vec3i chunkPos, ClientChunk chunk)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerChunkRetesselated(Vec3i chunkPos, ClientChunk chunk)
   at Vintagestory.Client.NoObf.ChunkTesselatorManager.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _vKnDSS3ZW5fZhqcIJSzL9xbAUttA._ZHf5IMlYChPlSKBWZX1ph2DB6EP(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._3HP2xkrryy8Ktr1q1yqHHv9s1kb(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._JbXJA0SA6LQOS6diuqtXAjMb8Fo(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._ofvn0Tr1zNGCbNV3SxvKs2MXNP(_C7CLMRbe3BejVtaARYCgl7Bg1vl , String[] )
   at _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 27/05/2021 19:43:58, Site = , Source = Windows Error Reporting, Message = Fault bucket 1601164709659358829, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\is0ex\AppData\Local\Temp\RDRF899.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF89A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF8BA.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF8D7.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF8E8.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9e3f12c8-6b39-428f-9bf0-a8cb708bd7bf
Report Status: 268435456
Hashed bucket: e2510997d6d277c626387ad1f223366d
Cab Guid: 0 }
--------------
{ TimeGenerated = 24/04/2021 22:38:46, Site = , Source = Windows Error Reporting, Message = Fault bucket 1999085723610005733, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\is0ex\AppData\Local\Temp\RDR6E08.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6E28.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6E39.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6E47.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6E77.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: cb4dc584-c47b-4020-ba24-4d4872557945
Report Status: 268435456
Hashed bucket: ee3def5252484136fbbe2ddfbf5440e5
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
#962 ? I don't like when these crash logs are inserted in bold font

**Comment by copygirl** [comment]
> I don't like when these crash logs are inserted in bold font. 

Yes this is what happens when people don't place their logs into logs into triple backticks (` ``` `). It happens quite often.

> Related to #962?

This is a indeed a duplicate.
