### ISSUE TITLE
Fixing object mapping between 1.15 -pre1 and -pre2 works, but crashes game once

### ISSUE THREAD

**Issue by hlangeveld** [anegostudios/VintageStory-Issues#971]
**Game Version:** 1.15.0-pre2
**Platform:** Windows
**Modded:** No
**Severity:** Minor

### Description
On fixing the object mapping after updating to -pre2, it has no effect when backup is still checked.  If I uncheck the backup option, as suggested by @copygirl, the object mapping is updated, but the game crashes once.

### How to reproduce (tested)
1. Create world in -pre1
2. Load in -pre2,
3. Notice popup,
4. Uncheck [_] Backup option,
5. Press OK,
6. Crash
7. Restart
8. All resolved
 
The good thing is that the object mapping is fixed after I started the game again.

### Expected behavior
> If you uncheck the backup option it will correctly apply the mappings and rejoin the world.

The rejoin is not automatic.

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.2 (Unstable)06/06/2021 15:20:21: Critical error occurred
System.Exception: GL_INVALID_OPERATION error generated. Buffer name does not refer to an buffer object generated by OpenGL.
   at Vintagestory.Client.NoObf.ClientPlatformWindows.DebugCallback(DebugSource source, DebugType type, Int32 id, DebugSeverity severity, Int32 length, IntPtr message, IntPtr userParam)
   at OpenTK.Graphics.OpenGL.GL.BindBuffer(BufferTarget target, Int32 buffer)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.UpdateMesh(MeshRef modelRef, MeshData data)
   at Vintagestory.API.Client.MeshDataPool.InsertAt(ICoreClientAPI capi, MeshData modeldata, Vec3i modelOrigin, Sphere frustumCullSphere, Int32 indexPosition, Int32 vertexPosition, Int32 listPosition)
   at Vintagestory.API.Client.MeshDataPool.TryAppend(ICoreClientAPI capi, MeshData modeldata, Vec3i modelOrigin, Sphere frustumCullSphere)
   at Vintagestory.API.Client.MeshDataPool.TryAdd(ICoreClientAPI capi, MeshData modeldata, Vec3i modelOrigin, Sphere frustumCullSphere)
   at Vintagestory.API.Client.MeshDataPoolManager.AddModel(MeshData modeldata, Vec3i modelOrigin, Sphere frustumCullSphere)
   at Vintagestory.Client.NoObf.TesselatedChunkPart.AddToPools(ChunkRenderer cr, List`1 locations, Vec3i chunkOrigin, Sphere boundingSphere, BoolRef[] cullVisible)
   at Vintagestory.Client.NoObf.TesselatedChunk.AddCenterToPools(ChunkRenderer chunkRenderer, Vec3i chunkOrigin, Sphere boundingSphere, ClientChunk hostChunk)
   at Vintagestory.Client.NoObf.ChunkRenderer.AddTesselatedChunk(TesselatedChunk tesschunk, ClientChunk hostChunk)
   at Vintagestory.Client.NoObf.ChunkTesselatorManager.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _xArlFw5lpThzIY0BN36UerAlHzU._14ww1iwrPaPwPpAZqZCUdf3d4Sm(Single )
   at _uFwaliVbJcYmzlP3dwic7HSHMr2._EuQCmN4cQf8FBHYrlJxd8EhIdNnA(Single )
   at _uFwaliVbJcYmzlP3dwic7HSHMr2._HlDCi3DfsJHaHE4jniBarrjFlHLB(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _EKato5MKvGk9ELCMKyl4BGVO7pe._ninJWCWaWyMG9ZSA1Eyytms1G5F(_BjQ4x8rTRChySIeXrK1HK1YSqec , String[] )
   at _btwtpE4G1MfBqD34njKFCvBcSRd._ninJWCWaWyMG9ZSA1Eyytms1G5F(ThreadStart )
-------------------------------```

**Comment by tyronx** [comment]
I made a world in pre.1 and did the remapping in pre.6. No crash happens for me at any point. Is this reproducible in pre.6 still?

**Comment by copygirl** [comment]
Will close as not reproducible for now, since the crash only occurred once for you and did not cause additional issues, and you were using an unstable pre-release.

**Comment by hlangeveld** [comment]
Completely agree. This did not happen with any of the builds after -pre2.  I've been running almost every build after -pre2 and they've been mostly stable.
