### ISSUE TITLE
Repeated crash when breaking block

### ISSUE THREAD

**Issue by strawberrysix** [anegostudios/VintageStory-Issues#973]
**Game Version:** X.Y.Z
**Platform:** Windows / Mac / Linux (which?)
**Modded:** No / Yes (which?)

### Description
Every time i break a block with beets growing on it I crash, but it is the same block/patch of beets. Others seem fine. I turned off my mods and it persisted, and I uninstalled and reinstalled and it still happened as well.

### How to reproduce
Im not sure if it is reproduceable besides my save.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.10 (Stable)6/6/2021 9:35:38 PM: Critical error occurred
System.Exception: EndOfStreamException thrown while reading entity, you might be able to recover your savegame through repair mode ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.MemoryStream.InternalReadInt32()
   at Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   --- End of inner exception stack trace ---
   at Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntitySpawnPacket(_qiwXoSSrnCKEl5NMyGSjHlpQcE serverpacket)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _vKnDSS3ZW5fZhqcIJSzL9xbAUttA._mhcyOBzdAWALla9FVcjc15WACGi(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._3HP2xkrryy8Ktr1q1yqHHv9s1kb(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._JbXJA0SA6LQOS6diuqtXAjMb8Fo(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._ofvn0Tr1zNGCbNV3SxvKs2MXNP(_C7CLMRbe3BejVtaARYCgl7Bg1vl , String[] )
   at _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(ThreadStart )
-------------------------------
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.MemoryStream.InternalReadInt32()
   at Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/6/2021 4:06:32 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1999085723610005733, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\OCEANM~1\AppData\Local\Temp\RDRC067.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC068.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC078.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC096.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC0B6.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: a10ac481-935c-4547-92b5-7f01177737d9
Report Status: 268435456
Hashed bucket: ee3def5252484136fbbe2ddfbf5440e5
Cab Guid: 0 }
```

**Comment by copygirl** [comment]
Please make a backup of your world right now, and upload it somewhere. Tell us at which block location the issue occurs. This way the developers might be able to look into this issue.

**Afterwards**, run the world in repair mode. That tends to fix the issue. You can find the button when you click the pencil next to the button that loads you into the world.

**Comment by Craluminum2413** [comment]
Crash log is the same as in most issues that you can find by `EndOfStreamException` in the search of closed issues

**Comment by copygirl** [comment]
I am aware but if this is reproducible this could be a good test case for the developers.

**Comment by copygirl** [comment]
No response in 2 weeks.
