### ISSUE TITLE
Falling a pie cause crash

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#979]
**Game Version:** 1.15.0-pre.3, 1.15.0-pre.5
**Platform:** Windows
**Modded:** No

### How to reproduce
1. Place a pie on the surface (make sure that after breaking the block underneath, pie will fall into the 1x1x1 pit)
2. Break the block under the pie
3. It crashes, if not, then repeat again

### Videos

https://user-images.githubusercontent.com/69315569/122412502-4b443900-cf8e-11eb-9b32-b2c003cc981f.mp4

https://user-images.githubusercontent.com/69315569/122671085-bb8ccd80-d1cd-11eb-97e5-9cf96017ae01.mp4

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.3 (Unstable)06/10/2021 00:40:49: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockContainer.GetContents(IWorldAccessor world, ItemStack itemstack)
   at Vintagestory.GameContent.BlockPie.GetHeldItemName(ItemStack itemStack)
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.ComposeBlockInfoHud()
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.BlockInView()
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _kG3l18Uo58XQnaOroOTVL156lmd._xkDAOmiQFj0Igekk6xBOkfLlbV2(Single )
   at _myXzIvBGuHgNhKsWypGDvkNbw4X._PeuIqQzFn7JdsiaCMO1A0nOHYOF(Single )
   at _myXzIvBGuHgNhKsWypGDvkNbw4X._12elMOUbssfuqzUtVoRc599RYNW(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _UwTpwIUKuzIrz4lc7aDEDr1w32f._ouD1c39oCQ2Eda0lkC3EXYeZtC7(_OdfjAwaG2wGU12XuYVt4myQv5bF , String[] )
   at _j9Ke4RlHC2L45ChATqqx7RI91CC._ouD1c39oCQ2Eda0lkC3EXYeZtC7(ThreadStart )
```

**Comment by Craluminum2413** [comment]
Okay, it crashes even when the pie falls into the 1x1x1 pit

**Comment by Craluminum2413** [comment]
Okay, it crashes even if the pie just fell, I don't understand anything, what

**Comment by tyronx** [comment]
thanks, fixed for pre.7
